### ISSUE TITLE
Implement sorting value for list of tokens

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#1007]
As a user, I want to see more popular tokens on each network 
As a Giveth Stakeholder, I want to suggest $GIV as the first token to donate

so as a Giveth Admin, I want to custom sort the token list so if any new tokens are added, we can manage the sorting manually.

**Comment by mohammadranjbarz** [comment]
@MoeNick  @jeevanplus007 
I think this is implemented now unless if you want to change the sorting algorithm
(Now `GIV` comes first, after that native token on each network, then `WETH` and other tokens would be listed sorted alphabetically

**Comment by MoeNick** [comment]
Let's move it to done
