### ISSUE TITLE
Verification form - Milestones section - File Upload

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#1012]
Testing here: https://giv-verification.vercel.app/
On chrome browser

The user should be able to upload files as well as images... pdf, docx, etc.

This should say "file" rather than image:

![image](https://user-images.githubusercontent.com/74267818/176033204-e10c5e8e-ec38-4067-9ac6-32a41abbfd34.png)

**Comment by divine-comedian** [comment]
@MoeNick where is the verification form being tested now? staging or the same giv-verification deployment?

**Comment by divine-comedian** [comment]
testing on https://staging.giveth.io/verification/testing-no-categories

made a quick fix to the text https://github.com/Giveth/giveth-dapps-v2/commit/5e9e2d37ac23b99440e3e5cc6a30415cd45e001e
 - was 
`Drag & drop some docs here`

changed to- 
`Drag & drop your files here`

I can see however now it does accept multiple file types this part seems to be working well! 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67759413/184405293-3807c2ae-c7c5-4254-a42b-048afb38b75b.png">

text is updated and issue looks to be resolved! moving to done!
