### ISSUE TITLE
Verification form - 'Before you start' section is missing some text

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#1026]
Testing on https://giv-verification.vercel.app/ with chrome browser.

There is content from the figma that is missing in this section.

Here is what the section shows on vercel:
![image](https://user-images.githubusercontent.com/74267818/176322184-af3bb372-dba2-409a-8559-be2ffec3f2f4.png)

Which matches this part in figma:
![image](https://user-images.githubusercontent.com/74267818/176322083-d8fbf6e8-b9d5-413c-a6a5-4d6b314708ac.png)

But there is another part that I dont see in the flow on vercel anywhere... this part:
![image](https://user-images.githubusercontent.com/74267818/176322231-1bea4605-7d52-486e-ba75-7bc21ccd0557.png)

I think we can have all of the text on one screen and just make it scrollable.. unless there was a purpose for splitting it up that Im unaware of. What do you think?

link to figma: https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=7489%3A189503

**Comment by alireza-sharifpour** [comment]
Thanks @WhyldWanderer for creating the issue, I agree with having the text on a single page because there is no new step defined for the second text on the left menu, what is your idea @MoeNick ?

**Comment by MoeNick** [comment]
Yeah lets do it @alireza-sharifpour 🙏

**Comment by divine-comedian** [comment]
all on one page now! looks good!

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67759413/178472912-d0113f39-d4e1-46b6-9054-5b49e8b0c508.png">

MOVING TO DONE!
