### ISSUE TITLE
Project verification form - Content fixes

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#1027]
Testing on https://giv-verification.vercel.app/ with chrome browser.

- [x] Remove "Make your project Traceable" - This is misleading because thier project does not get added to TRACE upon verification - the user must complete another step to make the project "Traceable"
![image](https://user-images.githubusercontent.com/74267818/176014807-b85e0ff0-54ac-4b5b-875d-904270b0492d.png)

- [x] Capitalize "Givers" to be congruent with branding
![image](https://user-images.githubusercontent.com/74267818/176015729-956bd646-bebb-474c-81f1-5d4d10968ee3.png)

- [x] Change 'Project registry' on tree menu. It should say "Registration"
![image](https://user-images.githubusercontent.com/74267818/176032243-cb29340a-3e9d-42a4-ad21-c429289f8f90.png)

- [x] Project's social media accounts. Text should say "Please provide links to any social media accounts owned by your organization /project."
![image](https://user-images.githubusercontent.com/74267818/176032728-77e5bb96-a5a3-44be-9a27-8100a05fefad.png)

- [x] On the project social media section, the user can "add other" - The modal should say "Add a new social media account"
![image](https://user-images.githubusercontent.com/74267818/176322881-1e25a5b3-9b81-40bf-bdef-eebd66bb46c8.png)

- [x] Add an Address Modal - Should say "Wallet Address" not receiving address
 ![image](https://user-images.githubusercontent.com/74267818/176322964-d074591f-2d56-4b41-89e2-d9c20a01778e.png)

**Comment by jeevanplus007** [comment]
@alireza-sharifpour  Can you list all the Fixes made as part of this Task ?

**Comment by jeevanplus007** [comment]
**Tested in URL :** https://giv-verification.vercel.app/verification/
**Snapshot 1 :Removed "Make your project Traceable" from The modal.**
![image.png](https://images.zenhubusercontent.com/62a3cf4962612d632dd3b42a/5e2b24df-259f-4dc5-882c-9f6a31d69bff)

**Snapshot 2 : Capitalized "Givers" in before start page**
![image.png](https://images.zenhubusercontent.com/62a3cf4962612d632dd3b42a/6988b972-0571-4cd8-a9dc-f4deee430741)

**Snapshot 3 : Changed 'Project registry' to "Registration" in the left menu**
![image.png](https://images.zenhubusercontent.com/62a3cf4962612d632dd3b42a/3991206c-
366b-4b70-ae60-1f3cf25acace)

**Snapshot 4 : Changed the add other modal title to "Please provide links to any social media accounts owned by your organization /project"**
![image.png](https://images.zenhubusercontent.com/62a3cf4962612d632dd3b42a/28d2f82e-f013-44da-8179-7149da9448bc)

Snapshot 5: Changed the text of Project's social media accounts
![image.png](https://images.zenhubusercontent.com/62a3cf4962612d632dd3b42a/ff60ccd9-547d-4f31-bcf2-ad49d30fe979)

**Snapshot 6 : Changed Add Address Modal "receiving address" to "Wallet Address"**
![image.png](https://images.zenhubusercontent.com/62a3cf4962612d632dd3b42a/e981bb21-c60a-4abb-ac3d-479873f56f1a)
