### ISSUE TITLE
When I try to edit my project description, it forces me to change my recipient wallet address

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#1038]
When I try to edit my project description - I just wanted to add one sentence to the description only.
It will not let me publish my changes without changing the wallet addresses.

![image](https://user-images.githubusercontent.com/74267818/176752281-21de4ad6-621d-4048-83b4-fb4af4df407c.png)

**Comment by divine-comedian** [comment]
testing on `staging.giveth.io` 

while editing a project I can change the description, title, photo, location and I do not receive a prompt to edit my wallet address..

looks to be fixed! moving to DONE!
