### ISSUE TITLE
Changing Center button on website to "Donate now" and changing the yellow "Create a project" wording

### ISSUE THREAD

**Issue by SymSL** [Giveth/giveth-dapps-v2#1058]
**What problem is this design solving? Why is it necessary?**
As users land on the Giveth website, they should be able to donate right away. We suggest to change the wording on the large center button to "Donate & Earn" and changing the yellow text that currently reads "Create a project" to "See Projects". We already have "Create a project" on the top right corner so there is no need to repeat.

**Is there any user data or feedback backing up this feature request?**
No research, but as Donations are the most important to keep Giveth running, and the website is the funnel that we push users to from all our other channels, its important that in one step, donors can see how to get involved.

**Which metrics will define this feature's success?**
*Provide current and/or expected metrics.*
Improved Conversion rate from users landing on the page, to making a donation.

**Additional context**
*Add any other context or screenshots related to your design here.*

![image](https://user-images.githubusercontent.com/100238380/177226597-30774782-3699-4eb7-99f9-182fb57cd699.png)

**Comment by laurenluz** [comment]
@SymSL I think "Donate" instead of "Donate & Earn"... because you can't earn for donating to any project, just verified projects.

@MoeNick so this issue is just to change the text "See Projects" to "Donate". The button should still link to the projects page.

**Comment by divine-comedian** [comment]
changes pending in PR https://github.com/Giveth/giveth-dapps-v2/pull/1193
