### ISSUE TITLE
In Project Onboarding allow the project owner to put in a contract address for every network

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#106]
This will allow us to avoid the issues around contracts... we can let contracts receive funds. The big question is if we allow them to only accept some currencies or not.

**Comment by markoprljic** [comment]
During the Create Project flow? Also in Edit project page which is the same. Yes we can add another input field (or as many) for different chanins. @mosaeedi Can mock this up quickly, devs have UI components library and can add it as well in the frontend. @MoeNick remains the estimate on backend implementation.

**Comment by mosaeedi** [comment]
I'm on it

**Comment by MoeNick** [comment]
Shall we make both of them required? 
Shall we consider the current user chain as enable field for better ux?

**Comment by markoprljic** [comment]
I'd say:

- prefill the field with the one use is connected with
- one is mandatory to fill in
- others are optional 
- UI throws error if all fields are empty with a message "Please enter a valid wallet address to receive donations to your project"

We should probably also validate the addresses user enters in the field, has to have 0x and 40 characters excluding the 0x prefix. For different chains we should validate according to the address format of that chain.

**Comment by mosaeedi** [comment]
Here are the two ideas for multiple receiving addresses,

Option A,
Simply add another input field so the user can enter the secondary address.
![Screen Shot 2022-03-01 at 5 41 51 PM](https://user-images.githubusercontent.com/13708322/156192043-39f163a1-07f4-434a-8455-3d6d7628d141.png)

Option B,
We present only one receiving address, and also the option to add a new address too, which makes it easier for newbies and also gives the option to more advanced users to add as many addresses for different chains as they want to.

- ![Screen Shot 2022-03-01 at 2 59 31 PM](https://user-images.githubusercontent.com/13708322/156192563-d2f21925-b3f7-420f-ac9e-4e6ec138657a.png)

- ![Screen Shot 2022-03-01 at 5 55 03 PM](https://user-images.githubusercontent.com/13708322/156192621-61480007-bb46-47c8-8dc2-fc6a3a105fd9.png)

**Comment by mosaeedi** [comment]
CC @GriffGreen @markoprljic @MoeNick

**Comment by markoprljic** [comment]
I think the UI can be simpler and interactions a bit more intuitive. I'll mock up something. @mosaeedi

**Comment by markoprljic** [comment]
@mosaeedi Let's go with Option B. It's the safest option that covers most scenarios we want to avoid :)

The input field should be Default (not Disabled). 
We don't need to repeat the below Primary address title, also make it color 900.
We don't need Change address link if the input is enabled, user has to Publish changes anyway before they are saved. 
We need option to remove all addresses other than the Primary address.
I would left align all buttons on that page, Add new and Publish.
I also decreased spacing between titles and input to 8px.

<img width="641" alt="Screenshot 2022-03-02 at 18 33 22" src="https://user-images.githubusercontent.com/5704285/156416322-0f1b7fa1-9d1d-4142-bac9-9a5859983c11.png">

**Comment by MoeNick** [comment]
@mosaeedi @Tosinolawale we are jumping into this soon, is the draft design already finalized?

**Comment by MoeNick** [comment]
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=5790%3A126811

**Comment by MoeNick** [comment]
> This will allow us to avoid the issues around contracts... we can let contracts receive funds. The big question is if we allow them to only accept some currencies or not.

@CarlosQ96 we have to remove the "smart contract" condition in WalletAddressIsValid. 
https://media.discordapp.net/attachments/826746756195680286/1059046627698028584/image.png

**Comment by MoeNick** [comment]
on staging and will get approved by @maryjaf, pls refer to #709 for the test scenario.

**Comment by maryjaf** [comment]
> on staging and will get approved by @maryjaf, pls refer to #709 for the test scenario.

I tested #790 and it passed
