### ISSUE TITLE
Add a triggered pop up for users to add themselves to our newsletter database

### ISSUE THREAD

**Issue by SymSL** [Giveth/giveth-dapps-v2#1060]
**What problem is this design solving? Why is it necessary?**
*A clear and concise description of what the problem is. Link to any relevant issues, PRs, and other resources.*
This will help us grow our newsletter database and keep donors and projects engaged. There are a few different ways this could be added, but it would be great to have a triggered pop up when we know the user has been on our site for longer than 45 seconds, or has scrolled at least 75% through any page. These are rough guidelines without knowing the website analytics just yet.

**Is there any user data or feedback backing up this feature request?**
*Share any user research conducted by yourself or others.*
Marketing best practices

**Which metrics will define this feature's success?**
*Provide current and/or expected metrics.*
Increased sign ups to newsletter through the website

**Additional context**
*Add any other context or screenshots related to your design here.*
![image](https://user-images.githubusercontent.com/100238380/177228394-88869cf6-be14-4bc2-8fda-40064dd91f68.png)

**Comment by SymSL** [comment]
@ahmadabugosh I have just opened up this issue so we can include a triggered pop up on the giveth site - where do you think it should go? I suggested the main page based on time or scrolls, let me know what you think

**Comment by c0ric0ri** [comment]
as per @tropicalmangos suggestion, can we offer something (lead magnet) in exchange to entice people to respond to this popup?

**Comment by ahmadabugosh** [comment]
Hey @MoeNick we discussed in our last comms meeting to experiment with adding a popup to two pages of the website:

1) On the homepage and 2) On the community (/join page).  It will be a popup that will let people subscribe to the newsletter and will only appear when the user is going to close the browser (exit intent) and will only show it to each user once a month (it will not show it to them 30 days after that). 

I have it setup already with our newsletter client, all we have to do is add the code below before the closing </body> tag of those two pages (homepage and join page)

`<script async>(function(s,u,m,o,j,v){j=u.createElement(m);v=u.getElementsByTagName(m)[0];j.async=1;j.src=o;j.dataset.sumoSiteId='dd7b1c88e814609c54c7b19a7f8e242fb978e0e39b006d392affa653f44de8ce';v.parentNode.insertBefore(j,v)})(window,document,'script','//load.sumo.com/');</script>`

Is that something we can do?
