### ISSUE TITLE
Page changer "broken"

### ISSUE THREAD

**Issue by danelsuga** [Giveth/giveth-dapps-v2#1065]
![page changer.png](https://images.zenhubusercontent.com/6066d509782b4d63df5cd761/c78544c8-2fa6-4c37-ae49-ec26f1e43f7e)

**Comment by divine-comedian** [comment]
hey @MoeNick I think this is more than a text issue

user is requesting we have arrow "buttons" to move from one set of text to the next

**Comment by Vyvy-vi** [comment]
we could replace it with a carousel or a "slide on scroll"
