### ISSUE TITLE
Redirect to previous address after the backend issue fixed

### ISSUE THREAD

**Issue by MohammadPCh** [Giveth/giveth-dapps-v2#1066]
When we can't connect to the backend we redirect the user to the /maintenance page. but after the issue is fixed we don't redirect it to the previous route and show that error page again.

**Comment by MohammadPCh** [comment]
The better idea is to show a component on that page and says: 'we can not ...', showing the maintenance component may confuse the user.
@MoeNick @mosaeedi

**Comment by MoeNick** [comment]
According to @MohammadPCh it's solved now, do we need QA?

**Comment by MohammadPCh** [comment]
It's not easy to test. I just test it yesterday and it's working.

**Comment by divine-comedian** [comment]
@MohammadPCh - Is this still relevant?
