### ISSUE TITLE
PROJECT VERIFICATION - Allow upload of multiple "proof" images

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#1093]
In the project verification flow where it asks for me to upload any files for proof of milestones I can only upload one image, if a project has achieved many things it might be hard to show it all in just one photo, users should be allowed to upload more than one photo for their proof.
![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/2533658e-29c4-4354-9e95-09e33ff299ac)
we shouldn't make it unlimited though, what is a reasonable cap? 5?

**Comment by MoeNick** [comment]
Let's do up to 5 files.
