### ISSUE TITLE
Add fade-in and fade-out animation to all modals

### ISSUE THREAD

**Issue by RamRamez** [Giveth/giveth-dapps-v2#1094]
Animation should be added when modal is opened or closed

**Comment by divine-comedian** [comment]
@RamRamez what should this animation look like? right now I'm testing the pop-up modals on `staging.giveth.io` and there is no animation on pop-ups inside the donation page, project creation page and project view page..

**Comment by divine-comedian** [comment]
woww! looking good 
https://www.loom.com/share/e918fd8ad5cd483c91319d978433cc8e

I'll do a thorough test of modals and update this issue

**Comment by RamRamez** [comment]
Great, thanks @divine-comedian

**Comment by divine-comedian** [comment]
okay, moving to DONE
