### ISSUE TITLE
Verification Form - Add an Address Modal text

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#1097]
Wallet Title seems confusing. I think we should add some examples here to show what we are looking for.
![image](https://user-images.githubusercontent.com/74267818/178497710-d3f86981-d88b-424a-921d-53ccf31b137e.png)

Should say "Choose a title for this address. eg. Salary Payments, Marketing, etc."

**Comment by MoeNick** [comment]
@MohammadPCh pls make the address required and remove the name.

**Comment by MoeNick** [comment]
Pls add placeholder: Salary Payments, Marketing, etc.

**Comment by divine-comedian** [comment]
this looks to be implemented!

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67759413/179577218-0cbd77eb-9ccf-4cf6-b54f-2ac89de9a983.png">

moving to DONE
