### ISSUE TITLE
Create a Project - Upload Image Cover - Not properly refreshing the removed data

### ISSUE THREAD

**Issue by jeevanplus007** [Giveth/giveth-dapps-v2#1106]
**Issue :** Create a Project - Upload Image Cover - Not properly refreshing the removed data. 

**Steps to Repro :**
1. Click on Create a Project
2. Go to Add an image to your project
3. Click on Upload Cover Image
4. Using Drive, Upload any image from System(Hard drive)
5.  After Successfully Uploading, Click REMOVE button
6. Now Select any image from our gallery as shown picture

**Results :** The Image Details of previously Uploaded information is displayed which is an issue. 

**Snapshot 1 for Reference :** Upload Image Issue 
![image.png](https://images.zenhubusercontent.com/62a3cf4962612d632dd3b42a/7cbb2e19-ba46-48c6-9ed8-783838270dbd)

**Comment by oyealmond** [comment]
Tested in https://staging.giveth.io/create 
After following the steps (upload a picture from Hard drive, removing it, and then upload a picture from Giveth's gallery), the past image information is not shown:

<img width="737" alt="Captura de Pantalla 2022-08-12 a la(s) 11 06 38" src="https://user-images.githubusercontent.com/110692280/184396971-9eefa53f-3b41-494c-999e-df6e52bcba7b.png">
