### ISSUE TITLE
After archiving a pool, the user should still be able to harvest rewards

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1108]
@Cotabe is down to test this for the GIV/HNY pool

Please make sure that you can harvest your GIV, and that you can unstake your LP tokens all fine :)

If there is an issue, tag Amin here so he can fix it.

**Comment by Cotabe** [comment]
The harvest reward button is not active. So I can't claim the rewartds.

Unstacking works.
And I can withdraw liquidity from the liquidity pool although I had to import the pair (so not making it easy checks)

So everything is alright, except harvesting rewards.

**Comment by laurenluz** [comment]
@aminlatifi can you look into this?

We want the user to still be able to claim rewards from an archived pool

**Comment by Cotabe** [comment]
BTW... regarding the rewards that are streamed, will they be claimed on that harvest button from now till the end of the stream?

**Comment by laurenluz** [comment]
@Cotabe no, once you claim once, the streaming rewards will just add to your givstream flowrate and can be claimed from the givstream page

**Comment by MoeNick** [comment]
As talk with @MohammadPCh he can make the button of harvesting and the link add liquidity to pool again on this card. shall we assign him?

**Comment by laurenluz** [comment]
@Cotabe can you test again?

**Comment by Cotabe** [comment]
It works now.
