### ISSUE TITLE
Technical Validation of bridging GIV from mainnet to gnosis chain

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1109]
We will be replacing the current 100% GIV staking card with the GIVpower card...

The thing is, the user can only stake for GIVpower on GC.

We want this card to still show up on mainnet, so want to figure out if it is possible to use the xDai bridge from our frontend. As in, when the user goes to stake on mainnet, it triggers a tx to bridge their tokens to GC. @paxthemax looking to you to help with this.

If it's not possible we will have the "stake" button just prompt a switch network, and may need to add a modal

**Comment by paxthemax** [comment]
This should hopefully provide enough information to implement bridging functionality between mainnet GIV and Gnosis chain GIV.

The goal is to **optimize and streamline** the experience of the GIV token bridging, and **remove friction** for users.

## User Flow

Alice owns GIV tokens on the mainnet. Alice would like to bridge these tokens to the Gnosis chain. We assume that GIV tokens exist as a mainnet mirror.

1. Alice must be connected to a web3 provider (the website prompts for an unlock)
2. Alice must be on the network we are bridging from (mainnet or Gnosis chain)
3. The bridge checks if Alice has allowance for mainnet GIV
4. Alice is directed to approve GIV
5. Alice sends a bridging transaction
6. Alice sees a review prompt with bridge operation details (tokens on both, sides, estimated gas costs etc.)
7. Alice confirms the transaction
8. Alice waits for 20 bridge confirmations (there is a visible indicator present)
9. Alice receives confirmation that the execution is complete

## Current approach

The application currently relies on linking to an outside implementation of the Gnosis omni-bridge. The flow can be inspected on this link: https://omni.gnosischain.com/bridge

This is reminiscent of the forced redirect used by payment providers (such as 3D-Secure). Stripe has an [explanation flow](https://stripe.com/docs/payments/bank-redirects) for how they integrate with bank authentication.

## In domain approach

Our goal is to keep the user within our application, on the same page, and communicate via a modal that is already familiar with Giveth users and simplified as much as possible.

To accomplish that, we have several requirements:

### Design

We MUST design modals that will replicate the above mentioned flow for each step of the bridging process, which is AT MINIMUM an **explanation screen** with an **approval button** and a **bridge assets** button, that prompts for the amount of GIV tokens to bridge.

The modal SHOULD also link to the omnibridge (if the user wants to use it as an alternative), as well provide some estimation on bridging cost.

The user MUST receive a completion screen, and SHOULD also be aware of the progress of the bridging.

### Implementation

The omnibridge UI is open source and available [here](https://github.com/omni/omnibridge-ui). There is no official SDK available, but the code is relatively legible and can be reused or rewritten for our purposes.

The bridging logc and chain interaction is available at [lib](https://github.com/omni/omnibridge-ui/tree/master/packages/dapp/src/lib). The actual React components used by the bridge are available at [components/bridge](https://github.com/omni/omnibridge-ui/tree/master/packages/dapp/src/components/bridge)

### Subgraph

The omnibridge UI has developed a subgraph for tracking transfers - but it appears to be unused. If we want, we could use it to track successful completed transfers.

## Conclusion and further actions

The approach is definitely sound - but it may require **moderate** to **significant** effort to execute. The main challenges are implementing a design that is an overall improvement over the existing application, as well as to analyze the omnibridge in more details and actually implement bridging. In addition, we will require **moderate** QA to implement, as we specifically want to avoid as much [jank](https://www.urbandictionary.com/define.php?term=jank) in the process.

It would be good to see a fronted estimate from the platform team on design complexity and frontend before we commit to the approach and prepare tasks.

**Comment by aminlatifi** [comment]
> This should hopefully provide enough information to implement bridging functionality between mainnet GIV and Gnosis chain GIV.
> 
> The goal is to **optimize and streamline** the experience of the GIV token bridging, and **remove friction** for users.
> 
> ## User Flow
> Alice owns GIV tokens on the mainnet. Alice would like to bridge these tokens to the Gnosis chain. We assume that GIV tokens exist as a mainnet mirror.
> 
> 1. Alice must be connected to a web3 provider (the website prompts for an unlock)
> 2. Alice must be on the network we are bridging from (mainnet or Gnosis chain)
> 3. The bridge checks if Alice has allowance for mainnet GIV
> 4. Alice is directed to approve GIV
> 5. Alice sends a bridging transaction
> 6. Alice sees a review prompt with bridge operation details (tokens on both, sides, estimated gas costs etc.)
> 7. Alice confirms the transaction
> 8. Alice waits for 20 bridge confirmations (there is a visible indicator present)
> 9. Alice receives confirmation that the execution is complete
> 
> ## Current approach
> The application currently relies on linking to an outside implementation of the Gnosis omni-bridge. The flow can be inspected on this link: https://omni.gnosischain.com/bridge
> 
> This is reminiscent of the forced redirect used by payment providers (such as 3D-Secure). Stripe has an [explanation flow](https://stripe.com/docs/payments/bank-redirects) for how they integrate with bank authentication.
> 
> ## In domain approach
> Our goal is to keep the user within our application, on the same page, and communicate via a modal that is already familiar with Giveth users and simplified as much as possible.
> 
> To accomplish that, we have several requirements:
> 
> ### Design
> We MUST design modals that will replicate the above mentioned flow for each step of the bridging process, which is AT MINIMUM an **explanation screen** with an **approval button** and a **bridge assets** button, that prompts for the amount of GIV tokens to bridge.
> 
> The modal SHOULD also link to the omnibridge (if the user wants to use it as an alternative), as well provide some estimation on bridging cost.
> 
> The user MUST receive a completion screen, and SHOULD also be aware of the progress of the bridging.
> 
> ### Implementation
> The omnibridge UI is open source and available [here](https://github.com/omni/omnibridge-ui). There is no official SDK available, but the code is relatively legible and can be reused or rewritten for our purposes.
> 
> The bridging logc and chain interaction is available at [lib](https://github.com/omni/omnibridge-ui/tree/master/packages/dapp/src/lib). The actual React components used by the bridge are available at [components/bridge](https://github.com/omni/omnibridge-ui/tree/master/packages/dapp/src/components/bridge)
> 
> ### Subgraph
> The omnibridge UI has developed a subgraph for tracking transfers - but it appears to be unused. If we want, we could use it to track successful completed transfers.
> 
> ## Conclusion and further actions
> The approach is definitely sound - but it may require **moderate** to **significant** effort to execute. The main challenges are implementing a design that is an overall improvement over the existing application, as well as to analyze the omnibridge in more details and actually implement bridging. In addition, we will require **moderate** QA to implement, as we specifically want to avoid as much [jank](https://www.urbandictionary.com/define.php?term=jank) in the process.
> 
> It would be good to see a fronted estimate from the platform team on design complexity and frontend before we commit to the approach and prepare tasks.

Thanks @paxthemax for the introduction. I just came across AMB bridge which technically enables relaying data between two chains. I read the document briefly and it doesn't seem unattainable

https://docs.tokenbridge.net/amb-bridge/development-of-a-cross-chain-application/how-to-develop-xchain-apps-by-amb

I imagine we deploy two contracts, one on mainnet and one on xDAI. Users who have GIV on mainnet and want to lock them for some number of rounds can interact with the mainnet contract. The mainnet contract can hold their token and call the appropriate method on the xDAI contract. The xDAI contract consequently increases user balance on GIVpower contract and locks them for the requested rounds.

@paxthemax I like to know your ideas

**Comment by laurenluz** [comment]
Hey @aminlatifi @paxthemax - love that you're looking into this, but we should cut scope for the MVP and just move forward with the simple modal flow that Mo & Cherik are working on.

I think we should move this to the icebox for now.

**Comment by laurenluz** [comment]
I'm talking about #1174
