### ISSUE TITLE
Verification form - The user needs to be able to give us the link to where they shared the social media post...

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#1114]
WE need to add a section where the user can provide the link to social media post where they share the link to their project.

Should be somewhere after their social media profiles here:
![image](https://user-images.githubusercontent.com/74267818/178814897-e4c7b16d-7c79-4e3e-afca-bfa7f19544d3.png)

The question should say "In order to ensure that you are actually a representative of the organization/project you're applying for, we ask that you **post a link to your Giveth project on the organization's twitter or social media account.** Please provide a link to the twitter or social media post here."

We need to make sure that the user creates a post on their project's social media account to take ownership of the project. This is a very important step of the application.

Maybe we need a design for it, Im not sure... what do you think @mosaeedi? Or can devs do something? :P

**Comment by MoeNick** [comment]
Label:
Link to your Giveth project on your social media.

**Comment by divine-comedian** [comment]
testing on `https://giv-verification.vercel.app/`

this section seems to be implemented

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67759413/179578110-fbbccffc-212b-472d-a4dd-d00d7ba18a08.png">

In the flow I am not allowed to proceed until this box has a url filled into it. works as expected, copy looks good. 

moving to DONE!
