### ISSUE TITLE
Empty search result

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#1119]
@mosaeedi commented on [Tue Jul 12 2022](https://github.com/Giveth/GIVeconomy/issues/660)

If a user searches for something that we can't find any result we show this screen.

![Screen Shot 2022-07-12 at 2.06.58 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/a7d118fd-1dbd-4c71-992b-90431af96439)

### Page structure
![Screen Shot 2022-07-12 at 4.13.56 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/010d2906-59a3-47ce-a8cb-e1be93196991)

## Design resource

[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=10923%3A201868](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=10923%3A201868)

---

---

@mosaeedi commented on [Tue Jul 12 2022](https://github.com/Giveth/GIVeconomy/issues/660#issuecomment-1181749145)

@laurenluz We need better examples for the search term that users can try when they land on the empty search result page.

---

@laurenluz commented on [Tue Jul 12 2022](https://github.com/Giveth/GIVeconomy/issues/660#issuecomment-1181929245)

@NikolaCreatrix or @WhyldWanderer would have a better idea of good search terms for this because they know what kinds of projects we have. Some suggestions off the top of my head:

- open source
- blockchain
- children
- land stewardship
- zero waste
- homelessness
- indigenous

**Comment by divine-comedian** [comment]
where can I test this issue? 
on `staging.giveth.io` my search result does not show any new changes
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67759413/182453524-e0852080-38be-41b4-87e2-67584b53966e.png">

**Comment by alireza-sharifpour** [comment]
> 

Every issue related to our New Categories design can be tested here:

https://giveth-dapps-v2-git-categories-develop-branch-givethio.vercel.app/

This includes:

- New Categories and SubCategories design
- New Filters and Sorting
- New Empty search or filter result
- Create new project with new Categories and Subcategories
- New Search
- New Single Project with Categories and Subcategories

@divine-comedian

**Comment by divine-comedian** [comment]
testing on `https://giveth-dapps-v2-git-categories-develop-branch-givethio.vercel.app/`

looking up a search term that yields no results currently looks like this:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67759413/182646856-a7531f12-5ced-4f4b-b59c-dfaf8f26fe9f.png">

I do not see any section for "Try These" nor any keywords that appear for a user to try searching 

I also notice that the GIveth Projects Banner is different than in the figma.

Does this need to go back to product backlog @mateodaza ?

**Comment by mateodaza** [comment]
Thanks @divine-comedian I totally missed that - Also not sure if the banner applies to this issue but I'll make sure before working on it

**Comment by divine-comedian** [comment]
testing on https://givfilter.vercel.app/

I go to the projects page and type in a search that yields no results.

i can see now some keyword suggestions for me to try to find projects. click any of those keywords creates a search for those keywords and I see projects matching those keywords successfully! 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67759413/184387924-7c959c87-2887-4118-996c-6aea1ea65628.png">


 moving to unit test passed!
