### ISSUE TITLE
Searching in projects

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#1120]
@mosaeedi commented on [Tue Jul 12 2022](https://github.com/Giveth/GIVeconomy/issues/659)

https://images.zenhubusercontent.com/410473836/ba195bf9-5af9-4844-a109-0d22f05a8578/screen_recording_2022_07_12_at_1_51_22_pm.mov

Users can tap on the search icon to open the search module.

1. Default state: [user didn't type anything yet]
![Screen Shot 2022-07-12 at 2.01.38 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/08b67a56-16e2-46d4-a3d6-01fc924b9de3)

2. Active state: [The user is typing something]
![Screen Shot 2022-07-12 at 1.59.13 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/9e375501-cf87-4ed4-9662-187e530cf0b8)

3. Searched state: [user entered to search a keyword]
![Screen Shot 2022-07-12 at 2.00.06 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/c4700093-a1e8-40f9-b74a-1b03d5e0e6b0)

## Design resource

1. Search module enabled -> [Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=10923%3A197431)

2. User is typing -> [Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=10923%3A198870)

3. Search result -> [Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=10923%3A200998)

---
## Important:

- The filter/sort module should also work on the search results.
- For empty search result page, please take a look at the task #660
---

**Comment by divine-comedian** [comment]
test this issue on https://givfilter.vercel.app/ right?

**Comment by oyealmond** [comment]
@MoeNick 
Tested on https://givfilter.vercel.app/projects and the user search experience does not match with the [Figma](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=10923%3A197431) provided. Filters does not shows any numbers:

https://user-images.githubusercontent.com/110692280/184404069-77ac1214-9d6a-4456-89f2-10dbf707849b.mp4

**Comment by divine-comedian** [comment]
moving to sprint backlog

**Comment by RamRamez** [comment]
> 

@oyealmond Do you mean the number beside `filter` button?
This number is only shown when you select some filters. It's not related to the search nor search result count.
![image](https://user-images.githubusercontent.com/73441857/184419788-3ddea3d4-4b9f-4134-af45-0d262c48f046.png)

**Comment by oyealmond** [comment]
You're right @RamRamez . Thanks for clarifying.
I tested again and the search bar works properly. 

<img width="1296" alt="Captura de Pantalla 2022-08-12 a la(s) 15 36 43" src="https://user-images.githubusercontent.com/110692280/184441461-e87ecc46-6e9d-4aea-9a79-763fb2621435.png">
