### ISSUE TITLE
Categories & subcategories

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#1122]
@mosaeedi commented on [Tue Jul 12 2022](https://github.com/Giveth/GIVeconomy/issues/657)

Module structure
![Screen Shot 2022-07-12 at 12.17.07 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/fa3a25fa-de8c-43d9-9c0d-2e8c1ba1b796)

---

## Exception
**All** category:
For the **All** category, we don't have any sub-categories and the sub-categories row should be disabled and not visible

![Screen Shot 2022-07-12 at 11.51.33 AM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/fa0b284c-43c1-427f-aaf0-cc1558d75e40)

---

## Design resource
**All** category selected - > [Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=11080%3A201383)

Main category selected - Sub categories are visible -> [Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=8026%3A172569)

---

**Comment by divine-comedian** [comment]
how can this issue be tested?

**Comment by alireza-sharifpour** [comment]
> how can this issue be tested?

You can test it here:
https://giveth-dapps-v2-git-categories-develop-branch-givethio.vercel.app/

**Comment by MoeNick** [comment]
Im also confused, recently @MohammadPCh send me this: https://givfilter.vercel.app/

**Comment by MohammadPCh** [comment]
@divine-comedian @MoeNick these are the same version of the app. I only added a new URL for easier access.

**Comment by divine-comedian** [comment]
testing on `https://giveth-dapps-v2-git-categories-develop-branch-givethio.vercel.app/`

checking out categories and sub-categories 

the first thing I notice is that when you scroll sideways through the categories the `All` category disappears, it wasn't clear the functionality from the figma but I think as a user we should always be able to see All and the other categories can scroll sideways. 

The category pages also load sort of slow and it feels like the switch between categories is very clunky, you can see the banner blink and reload and same with the project cards as they reload and shuffle around in the bottom. Would adding in some sort of transition effect help this appear smoother? I made a loom just to show what currently happens 

I tried to show a bit further what I mean with the `All` category and slow category loading in a quick loom video:
https://www.loom.com/share/cb54c043e11042cab386f7b5bb189435

**Comment by maryjaf** [comment]
I have some questions @MoeNick 

1-When I select "all" from the main category
Subcategories are not displayed
This is ok?

2-When I select the "all" from main category, the set filters are reset 
this is ok?

3-We should not be able to choose two or more  main categories and sub categories?

**Comment by maryjaf** [comment]
When I select one of the "sort by" options
After that, I can only change it, and it is not possible to deactivate the sort
except to change the  main category to "all" so that the filters are completely reset

**Comment by MoeNick** [comment]
> I have some questions @MoeNick
> 
> 1-When I select "all" from the main category Subcategories are not displayed This is ok?
> 
> 2-When I select the "all" from main category, the set filters are reset this is ok?
> 
> 3-We should not be able to choose two or more main categories and sub categories?

1- It's Okay.
2- It's ok
3- No it's not in the proposed UX by @mosaeedi , so functionally we should not seek it in QA.

**Comment by MoeNick** [comment]
> When I select one of the "sort by" options After that, I can only change it, and it is not possible to deactivate the sort except to change the main category to "all" so that the filters are completely reset

Good catch @maryjaf . let's talk about it.

**Comment by mosaeedi** [comment]
There is this button missing in the development, at the start it's disabled, but when user select a filter, the **CLEAR ALL FILTERS** button will be activated.

**Default/Deactive state**
![Screen Shot 2022-09-02 at 2 45 35 PM](https://user-images.githubusercontent.com/13708322/188132811-aa4b9f07-1392-46f3-8b79-919f0562793e.png)

--- 

**Active state**
![Screen Shot 2022-09-02 at 2 48 06 PM](https://user-images.githubusercontent.com/13708322/188133510-bea411d3-2c8a-42b9-9224-08c15f1f6b7e.png)

**Comment by MoeNick** [comment]
@alireza-sharifpour this is ready for you! :)

**Comment by MoeNick** [comment]
@maryjaf pls check.

**Comment by maryjaf** [comment]
@alireza-sharifpour plz check this scenario:

I choose the  "TestMary" mai category
3 projects will be viewed (Maryam jafarimehr/test cats/ testnotif11)
which  2 project have  "TestN" sub categories and one Jaftest  sub category
But when I select subcategory "TestN" , 0 projects is displayed
{4 items
"variables":{3 items
"sortingBy":string"QualityScore"
"category":string"testn"
"mainCategory":string"testmary"
}
"setVariables":string"function () {}"
"mainCategories":[...]10 items
"selectedMainCategory":{...}6 items
}

**Comment by maryjaf** [comment]
and this:
I choose the "non-profit"  main category
1117 projects are displayed
But the number of sub-category projects of this category is different from this number
@alireza-sharifpour 

{4 items
"variables":{2 items
"sortingBy":string"QualityScore"
"mainCategory":string"non-profit"
}
"setVariables":string"function () {}"
"mainCategories":[10 items
0:{...}6 items
1:{...}5 items
2:{...}5 items
3:{...}5 items
4:{...}5 items
5:{...}5 items
6:{...}5 items
7:{...}5 items
8:{...}5 items
9:{...}5 items
]
"selectedMainCategory":{6 items
"title":string"Non-profit"
"banner":string"https://giveth.mypinata.cloud/ipfs/QmXLDFigVKaSXig6TCddzHjckCqpAu3xC3CKxzL9Cfv5m5/Non%20-%20profit.png"
"slug":string"non-profit"
"description":string""
"categories":[...]5 items
"selected":booltrue
}
}

**Comment by maryjaf** [comment]
I didn't see search icon in some size of page, it's ok?
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/941e5dcc-ebb5-49a8-96b7-7a134bce4d3e)

**Comment by alireza-sharifpour** [comment]
> and this: I choose the "non-profit" main category 1117 projects are displayed But the number of sub-category projects of this category is different from this number @alireza-sharifpour
> 
> {4 items "variables":{2 items "sortingBy":string"QualityScore" "mainCategory":string"non-profit" } "setVariables":string"function () {}" "mainCategories":[10 items 0:{...}6 items 1:{...}5 items 2:{...}5 items 3:{...}5 items 4:{...}5 items 5:{...}5 items 6:{...}5 items 7:{...}5 items 8:{...}5 items 9:{...}5 items ] "selectedMainCategory":{6 items "title":string"Non-profit" "banner":string"https://giveth.mypinata.cloud/ipfs/QmXLDFigVKaSXig6TCddzHjckCqpAu3xC3CKxzL9Cfv5m5/Non%20-%20profit.png" "slug":string"non-profit" "description":string"" "categories":[...]5 items "selected":booltrue } }

Thanks @maryjaf for testing, we did some changes, could you please test it again?

**Comment by alireza-sharifpour** [comment]
> I didn't see search icon in some size of page, it's ok? ![image.png](https://camo.githubusercontent.com/40bb1b2d4c6c24f77ad9a3633bf131f53fd0f976ec4b8dbf7d0efaa0906795c4/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f39343165356463632d656262352d343961382d393662372d376131333462636534643365)

because of the size of your screen it renders tablet design and it's ok, in order to access search button you need to click on 3 dots icon.

**Comment by maryjaf** [comment]
> > and this: I choose the "non-profit" main category 1117 projects are displayed But the number of sub-category projects of this category is different from this number @alireza-sharifpour
> > {4 items "variables":{2 items "sortingBy":string"QualityScore" "mainCategory":string"non-profit" } "setVariables":string"function () {}" "mainCategories":[10 items 0:{...}6 items 1:{...}5 items 2:{...}5 items 3:{...}5 items 4:{...}5 items 5:{...}5 items 6:{...}5 items 7:{...}5 items 8:{...}5 items 9:{...}5 items ] "selectedMainCategory":{6 items "title":string"Non-profit" "banner":string"https://giveth.mypinata.cloud/ipfs/QmXLDFigVKaSXig6TCddzHjckCqpAu3xC3CKxzL9Cfv5m5/Non%20-%20profit.png" "slug":string"non-profit" "description":string"" "categories":[...]5 items "selected":booltrue } }
> 
> Thanks @maryjaf for testing, we did some changes, could you please test it again?

I tested again, but I did not see any change in these scenarios

**Comment by alireza-sharifpour** [comment]
> > > and this: I choose the "non-profit" main category 1117 projects are displayed But the number of sub-category projects of this category is different from this number @alireza-sharifpour
> > > {4 items "variables":{2 items "sortingBy":string"QualityScore" "mainCategory":string"non-profit" } "setVariables":string"function () {}" "mainCategories":[10 items 0:{...}6 items 1:{...}5 items 2:{...}5 items 3:{...}5 items 4:{...}5 items 5:{...}5 items 6:{...}5 items 7:{...}5 items 8:{...}5 items 9:{...}5 items ] "selectedMainCategory":{6 items "title":string"Non-profit" "banner":string"https://giveth.mypinata.cloud/ipfs/QmXLDFigVKaSXig6TCddzHjckCqpAu3xC3CKxzL9Cfv5m5/Non%20-%20profit.png" "slug":string"non-profit" "description":string"" "categories":[...]5 items "selected":booltrue } }
> > 
> > 
> > Thanks @maryjaf for testing, we did some changes, could you please test it again?
> 
> I tested again, but I did not see any change in these scenarios

I checked it and we are sending the query correctly to the backend, I think backend guys can check it @mohammadranjbarz @CarlosQ96

**Comment by alireza-sharifpour** [comment]
> @alireza-sharifpour plz check this scenario:
> 
> I choose the "TestMary" mai category 3 projects will be viewed (Maryam jafarimehr/test cats/ testnotif11) which 2 project have "TestN" sub categories and one Jaftest sub category But when I select subcategory "TestN" , 0 projects is displayed {4 items "variables":{3 items "sortingBy":string"QualityScore" "category":string"testn" "mainCategory":string"testmary" } "setVariables":string"function () {}" "mainCategories":[...]10 items "selectedMainCategory":{...}6 items }

I also check this and it seems frontend works fine, @mohammadranjbarz @CarlosQ96 please check this.

**Comment by CarlosQ96** [comment]
@alireza-sharifpour Ok I updated it according to another image I was shown in another issue. But seeing this one, I missed one query to update with the new sorting. 

Will update it accordingly. Letting you know soon.

**Comment by CarlosQ96** [comment]
After having a call with @alireza-sharifpour 
The issues are:
1. Filtering by main category for example,  'Non-profit' return 1170 projects, but the sum of subcategories is less than the total.
2. Filtering by TestMary mainCategory and TestN sub category is not returning the project, even tho the project has this categories.

**Comment by CarlosQ96** [comment]
@maryjaf I added in the projects details the missing sorting alphabetically.

**Comment by maryjaf** [comment]
> @maryjaf I added in the projects details page the missing sorting alphabetically.

Thanks @CarlosQ96 
Yes, I tested this and it passed
I also commented on issue 1494

**Comment by maryjaf** [comment]
> After having a call with @alireza-sharifpour The issues are:
> 
> 1. Filtering by main category for example,  'Non-profit' return 1170 projects, but the sum of subcategories is less than the total.
> 2. Filtering by TestMary mainCategory and TestN sub category is not returning the project, even tho the project has this categories.

Do we have an update  on this?

**Comment by mohammadranjbarz** [comment]
> After having a call with @alireza-sharifpour The issues are:
> 
> 1. Filtering by main category for example,  'Non-profit' return 1170 projects, but the sum of subcategories is less than the total.
> 2. Filtering by TestMary mainCategory and TestN sub category is not returning the project, even tho the project has this categories.

@CarlosQ96  Are you working on the second item?
do you have any idea about that?

**Comment by mohammadranjbarz** [comment]
@alireza-sharifpour  @MoeNick  I found the issue, backend is ok, the category(sub category) entity is like this
```
 {
                        "id": "37",
                        "source": null,
                        "name": "the-giving-block",
                        "value": "The Giving Block",
                        "isActive": false
                    }
```
You should show the value  in frontend but when sending to filter with sub categories you need to send name, so because of that you get 0 for giving block project while there 1118  projects in giving blocks, please do the changes you would get correct result


This is a curl that return giving blocks projects

```
curl --location --request POST 'https://serve.giveth.io/graphql' \
--header 'Accept-Encoding: gzip, deflate, br' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'Connection: keep-alive' \
--header 'DNT: 1' \
--header 'Origin: http://localhost:4000' \
--header 'VERCEL_KEY: 123' \
--data-raw '{"query":"\nquery {\n    mainCategories{\n        id\n        title\n        banner\n        slug\n        description\n        categories {\n            id\n            source\n            name\n            value\n            isActive\n        }\n    }\n}\n","variables":{}}'
```

**Comment by alireza-sharifpour** [comment]
Thanks @mohammadranjbarz, this is now implemented and ready to be tested
@maryjaf

**Comment by maryjaf** [comment]
Thanks @alireza-sharifpour @mohammadranjbarz 1 & 2 scenarios are passed
