### ISSUE TITLE
Adding banner to projects list page

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#1123]
@mosaeedi commented on [Tue Jul 12 2022](https://github.com/Giveth/GIVeconomy/issues/656)

for each category and related subcategories, we need to present a banner.
### here is the banner preview

![Screen Shot 2022-07-12 at 11.18.15 AM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/e6102949-f532-4fc8-99b5-07427902e047)

---

Each banner will be only visible on the related main category and its subcategories list page.
Exception: we have two special banners other than banners for each category,

1. Banner for search results 
2. a general banner for All categories

### Banner structure
Each banner has a **background image**, **Main title**, and **subtitle**.

![Screen Shot 2022-07-12 at 11.36.58 AM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/b334ef04-5b3e-4c37-b91a-585b155a86a8)

![Screen Shot 2022-07-12 at 11.38.35 AM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/a4c9e3bf-7a81-4269-9bbc-2fca5171c8bc)

**Comment by divine-comedian** [comment]
how can this issue be tested?

**Comment by divine-comedian** [comment]
test on https://givfilter.vercel.app/projects?

**Comment by oyealmond** [comment]
Tested on https://givfilter.vercel.app/projects, I can see that every category has a banner, and all of them matches with the expected. 
<img width="1294" alt="Captura de Pantalla 2022-08-12 a la(s) 10 04 40" src="https://user-images.githubusercontent.com/110692280/184384056-1a5ac1cc-6fc4-4feb-830b-4a3dfd08eaed.png">
