### ISSUE TITLE
Add/Edit project form: Refactoring category section.

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#1125]
## Design resource

Categories/sub categories on edit/create project form -> [Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=11651%3A207857)

![Screen Shot 2022-07-27 at 4.05.30 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/9ba7d220-4e86-49ad-9649-698217705c17)

**Comment by divine-comedian** [comment]
test on  https://givfilter.vercel.app/projects ?

**Comment by MoeNick** [comment]
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/1d1ad61e-02a0-4f2a-b415-cb46ddadeb99)
This is what I see on https://givfilter.vercel.app/create, the formatting has a lot of differences with provided design, maybe @mosaeedi can help better with the table formatting, padding s and fonts.

**Comment by mosaeedi** [comment]
Yep there are a couple of issues here

there is some weird spacing!

![Screen Shot 2022-08-30 at 11 13 16 AM](https://user-images.githubusercontent.com/13708322/187386033-e60b9a7e-deec-4240-b055-aae6c26fe1e4.png)

it should look like this

![Screen Shot 2022-08-30 at 11 13 05 AM](https://user-images.githubusercontent.com/13708322/187386187-c4addde4-22d7-4cf8-8d12-b22c7787c44c.png)


Also, the checkbox when they are unchecked won't need a white background

![Screen Shot 2022-08-30 at 11 20 48 AM](https://user-images.githubusercontent.com/13708322/187387321-009c5f65-1ff7-4617-a7f6-95adf5ec1d40.png)

**Comment by mosaeedi** [comment]
Also, the _main categories_ title use **Gray/900** color and the _sub-categories_ use **gray/800** color

**Comment by MoeNick** [comment]
@maryjaf would you please take a look and test the above reported issues again?

**Comment by maryjaf** [comment]
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/9f6df7e5-3dc5-45b3-803c-bf0ad82a6501)

The display of main categories and their subcategories is correct now
I just think that the main category must always have at least one subcategory below it, otherwise its name will be moved to the next column.
For example, in the picture above, Art & culture

**Comment by RamRamez** [comment]
> https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=13424%3A242421
> 
> ![Screen Shot 2022-09-05 at 6 35 58 PM](https://user-images.githubusercontent.com/13708322/188482720-4379457e-4434-420b-9a01-0c9a462bf309.png)

@maryjaf This design is merged and ready to be tested on [category branch](https://giveth-dapps-v2-git-categories-develop-branch-givethio.vercel.app/).

**Comment by maryjaf** [comment]
Thanks , the new design is ok @RamRamez
