### ISSUE TITLE
The 0 round info would be valuable

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#1126]
<img width="369" alt="Screen Shot 2022-07-14 at 7 01 42 PM" src="https://user-images.githubusercontent.com/14945613/179040033-7b8dcc02-7879-4f8c-88fa-b9e894ecc513.png">

I know the minimum is 1 round... and that content can stay there... but i would love to see the 0 round info when making the decision for how log to lock!

I imagine the easiest thing is to have it start at 0 instead of 1 and then show the 1x multiplier.

**Comment by Cotabe** [comment]
@GriffGreen @MoeNick @MohammadPCh 

DONE

**Comment by MoeNick** [comment]
Should test on Givpower branch.

**Comment by Cotabe** [comment]
I thought this was working already. 

What do you mean testing on Givpower branch?
