### ISSUE TITLE
Implement frontend of Angel Vault staking card

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1131]
Design in #1107

We need to add this to the GIVfarm & test it. Would be great to have this ready next week.

**Comment by laurenluz** [comment]
@MohammadPCh The design is ready!

https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy

![image](https://user-images.githubusercontent.com/75490971/179291120-2f83eef2-4513-4202-8443-8877e115a8bf.png)

**Comment by laurenluz** [comment]
Also we should have this launch with a 72 hr countdown :) So we should make sure that we have that devved up too

**Comment by aminlatifi** [comment]
Angel Vault staking card is ready to test here https://github.com/Giveth/giveth-dapps-v2/pull/1195 
@laurenluz Asked has a good idea about showing Angel Vault APR as a separate number in the tool tip. I can implement it in another PR.

There is a point, we used [oneFIL](https://kovan.etherscan.io/token/0x50633e780803b56a0d8606a3c674993080ea98c1) for test purpose (oneFIL is akin oneGIV). Anyone needs oneFIL just ask me to send them.

**Comment by divine-comedian** [comment]
this looks to be live already on `giveth.io`
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67759413/182475150-e195b501-9cfd-41bc-96ca-74f684973218.png">

moving this to DONE
