### ISSUE TITLE
Angel Vault Rewards Program

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1132]
oneGIV exists & so does the angel vault!

The only blocker to getting it out is setting up our incentives program.

The design is in #1107, the frontend will be build in #1131

@aminlatifi we need to you to deploy a the incentive program. oneGIV can be minted & liquidity added to the angel vault [here](https://app.ichi.org/vault?poolId=20009&back=vault).

Then the user should be able to stake their LP tokens in our farm to earn rewards.

The program will run for 180 days, and we will put out 6,000,000 GIV in total for rewards (they will be part of the GIVstream).

We want the *amount* of GIV that goes out in every 2 week period to change every 2 weeks, as follows:

|notification date|amount of GIV in rewards given|
|---|--------|
| July 22	| 485,142.86 |
| August 5	| 569,142.86 |
|August 19	|140,000.00 |
|September 2	|653,142.86 |
|September 16	|140,000.00 |
|September 30	|737,142.86 |
|October 14	|140,000.00 |
|October 28	|821,142.86 |
|November 11	|140,000.00 |
|November 25	|905,142.86 |
|December 9	|140,000.00 |
|December 23	|989,142.86 |
|January 6	|140,000.00 |
|January 20	|0.00|

We're calling this the "jagged staircase" - you can see the details in [this spreadsheet](https://docs.google.com/spreadsheets/d/1neUUsppi4HZ5b0BlOUR60Vt2Hn-_e-hvoJeO20cTqyk/edit#gid=780402339)

**Comment by laurenluz** [comment]
Remember we will launch with a 72 hr countdown @aminlatifi

**Comment by MoeNick** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-Devs-61644589b92edf0016f6999c/issues/Giveth/giveth-dapps-v2/1132?planning-poker) with ZenHub @aminlatifi

**Comment by aminlatifi** [comment]
We first will setup everything on test env (kovan), and if it goes well we can do it on the production.

**Comment by aminlatifi** [comment]
@laurenluz the sum of percentages in the spreadsheet is 100.01%, so for the last one I will use 2.32 instead of 2.33

**Comment by laurenluz** [comment]
that sounds good, although @aminlatifi I see that mitch is making an alternative proposal for the GIV distribution in the forum: https://forum.giveth.io/t/angel-vault-lets-get-er-done/704/9

How easy is it to change the weekly distribution?

**Comment by aminlatifi** [comment]
> that sounds good, although @aminlatifi I see that mitch is making an alternative proposal for the GIV distribution in the forum: https://forum.giveth.io/t/angel-vault-lets-get-er-done/704/9
> 
> How easy is it to change the weekly distribution?

It's easy, just changing this array values
https://github.com/Giveth/giv-token-contracts/blob/510f023975d1bc2894552decfc73035f5688a666/deployments/notifyRewardAmount/mainnet/giveth_angel_vault_distributor.js#L14

**Comment by laurenluz** [comment]
Ok, confirmed, no change!!

All we have to do now is the multisig txs to grant the distributor role to the unipool & send rewards to it....

Can we do that this week @aminlatifi? Or do we need to wait?

**Comment by aminlatifi** [comment]
I can deploy unipool tomorrow and make multisig txs

**Comment by aminlatifi** [comment]
I deployed the contract and made multisig transactions

Angel Vault (ICHI) LM (Unipool):	0xA4b727DF6fD608d1835e3440288c73fB28c4eF16
Angel Vault (ICHI) LP (the token is minted by depositing oneGIV in Angel Vault. I didn't deploy it)	0xc3151A58d519B94E915f66B044De3E55F77c2dd9

And these are multisig transactions

https://gnosis-safe.io/app/eth:0x4D9339dd97db55e3B9bCBE65dE39fF9c04d1C2cd/transactions/queue

<img width="1450" alt="image" src="https://user-images.githubusercontent.com/5684607/181502263-51b9eea9-9bbf-4982-a75f-d79f569bc1b1.png">


I appreciate if others take a look and verify I didn't do any mistakes. I suppose @divine-comedian and @mohammadranjbarz can help us in verifying these.

**Comment by aminlatifi** [comment]
I keep updated this doc https://www.notion.so/giveth/Deployment-52935e6579034f1b940bbef161e82229

**Comment by divine-comedian** [comment]
Reviewed! 

Tx 1 - grants distributor role from mainnet token distro to angel vault LM unipool
Tx 2 - allocates 6 million GIV to angel vault LM unipool from mainnet token distro

Looks good I think

**Comment by laurenluz** [comment]
Thank you @aminlatifi @divine-comedian ! I will catherd

**Comment by GriffGreen** [comment]
looks good to me

Did we send the 6 mil giv from the liquidity multisig already?

**Comment by aminlatifi** [comment]
> looks good to me
> 
> Did we send the 6 mil giv from the liquidity multisig already?

I would say let's postpone execution of mutisig transactions and 6M giv transfer to successful launch of angel vault with countdown

**Comment by aminlatifi** [comment]
I made this checklist for the production
https://github.com/Giveth/GIVeconomy/issues/678

**Comment by aminlatifi** [comment]
@laurenluz A new ICHI farm with countdown is launched here
https://giveconomy.vercel.app/givfarm

Your old lp can be unstaked from the old farm in archive section
