### ISSUE TITLE
Change "Consume" to "Learn"

### ISSUE THREAD

**Issue by danelsuga** [Giveth/giveth-dapps-v2#1134]
We would like to change the header "Consume" to read "Learn" instead.
![consume.png](https://images.zenhubusercontent.com/6066d509782b4d63df5cd761/28da9006-7c12-458a-ad25-d7e8b35afaec)

I chatted with @mateodaza about this a while ago and finished up another chat with @laurenluz and @c0ric0ri in issue #717 on the Giveth Planning board.

I can't actually assign anyone to the issue however.

@mateodaza 
@MoeNick

**Comment by MoeNick** [comment]
@alireza-sharifpour would u pls take it?

**Comment by alireza-sharifpour** [comment]
> @alireza-sharifpour would u pls take it?

Sure, I'll fix it.

**Comment by divine-comedian** [comment]
testing on `staging.giveth.io`

this looks to be implemented!
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67759413/179577571-6288e78d-3120-43a7-84df-257b19de0416.png">

moving to DONE!

**Comment by danelsuga** [comment]
Thanks, everybody!
