### ISSUE TITLE
Implement URL for each GIVfarm staking modal (for Angel Vault)

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1145]
We want to make it possible that we could send the user directly to the staking card for a particular pool in the GIVfarm.

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/01272402-6e65-41c6-adb1-bba9c6dc2562)

This will make it a lot easier for users who use the Angel Vault & provide liquidity to then go to our site to stake their LP tokens.

@aminlatifi @MohammadPCh - can you guys discuss?

**Comment by aminlatifi** [comment]
We should be ready for edge cases like when the user wallet is not connected or the user is connected to a wrong network!

**Comment by MohammadPCh** [comment]
@laurenluz @aminlatifi 
I think we can have it. let me investigate.

**Comment by MohammadPCh** [comment]
@laurenluz 
try it out like this:
/givfarm?open=`[StakeingType]`&chain=`[chainId]`

staking types:
- UniswapV2_GIV_DAI
- UniswapV3
- Balancer
- Sushiswap
- Honeyswap_GIV_HNY
- Honeyswap_GIV_DAI
- GIV_LM
- Honeyswap_FOX_HNY
- UniswapV2_CULT_ETH

chains:
- gnosis
- main

so if you want to show the GIV stake modal on Gnosis, the address will be something like this:
https://giveth-dapps-v2-git-open-staking-card-directly-givethio.vercel.app/givfarm?open=GIV_LM&chain=gnosis

**Comment by laurenluz** [comment]
Hey @MohammadPCh!

That's super cool.

It seems to work, but, only if:
- I am already connected to the right network
- I have tokens that can be staked
- the pool is not archived

But I think that's ok for our purposes right? because our real use case is to send people from the angel vault right to the staking card.

What do you think?

**Comment by MohammadPCh** [comment]
Hey @laurenluz,
We have handled the wrong network but yeah maybe we need to consider more edge cases for this for all forms.
Yeah I think it should work for our new farm (Angel Vault).
I think we can check it here:
https://giveth-dapps-v2-git-add-angel-vault-givethio.vercel.app/givfarm??open=Ichi_GIV_oneGIV&chain=main

**Comment by divine-comedian** [comment]
hey @MohammadPCh 
what deployment should we be testing this on?

**Comment by MohammadPCh** [comment]
All the GIVeconomy issues are testable on this URL: https://giveconomy.vercel.app/

**Comment by divine-comedian** [comment]
testing this out on https://giveconomy.vercel.app/ 

it appears to work but as lauren said, if I have tokens that can be staked, the pool is not archived and if they are connected to the right network. 

If I am not connected to the right network I am prompted to change networks, once I change networks however there is no following modal to stake my tokens anywhere.

**Comment by maryjaf** [comment]
Can we move this issue to Done? @divine-comedian

**Comment by laurenluz** [comment]
I think the way it has been implemented is ok for our purposes.
