### ISSUE TITLE
GIVpower Design: Show "locked token details" from the main card

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1146]
@mosaeedi right now it is really hard to get information about your already-staked&locked tokens.

The user has to go form here
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/5e57f542-21b5-4efa-9368-64f75e5519f6)

To here:
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/62449bec-7048-4b21-9b0d-62a3a8f6a21e)

To here:
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/86bad04f-4463-4095-aaf1-4ecfb94073b7)

We *really* should show this on the main card. I know there are a lot of buttons already, but I think we could have this as a "lock" emoji somewhere, perhaps at the bottom, w/ a tooltip that says "View your staked & locked GIV". when the user clicks the lock emoji, they get the lockup details modal.

**Comment by laurenluz** [comment]
@MohammadPCh

Design is ready on this... only one small change, please make the text say "Locked GIV Details"

Disabled state (if user did not lock any GIV)
![image](https://user-images.githubusercontent.com/75490971/180780516-36687f73-da37-4deb-9177-4443d185a92d.png)

Enabled state (if user locked GIV)
![image](https://user-images.githubusercontent.com/75490971/180780640-b1c0bbb4-b802-4ee8-8ce5-1ac2554a0477.png)

When the user clicks this it should open the modal with the information about locked GIV, APRs, etc.

**Comment by Cotabe** [comment]
@laurenluz @aminlatifi 

DONE
