### ISSUE TITLE
GIVpower staking modal "blockscout" is spelled wrong

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1147]
It's "Blockscout"

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/2bd7941e-e8b3-4288-b335-329835369166)

**Comment by divine-comedian** [comment]
looks to be resolved!

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67759413/180804559-55ad13e7-5e0f-4379-b05b-05acc63cfe83.png">


however clicking link does nothing, is this normal? is this part still in development?
@MohammadPCh

**Comment by MohammadPCh** [comment]
Thanks, @divine-comedian 
let me check It.

**Comment by Cotabe** [comment]
@laurenluz @MoahammadPCh @divine-comedian 

Fixed

**Comment by divine-comedian** [comment]
@Cotabe no need to tag us all, if the issue is fixed just move it into the DONE pipeline, also helpful to clarify what url and browser you tested it on.
