### ISSUE TITLE
GIVpower - small changes to staking, unstaking & locking modals

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1148]
- [x] The tooltips in the "multiplier" box where it says "GIVpower" on *all* the modals should say "Coming soon: GIVpower will allow you to support verified projects will earning rewards."
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/3ab700c0-91dc-4daf-bab9-ad9395983c03)

- [x] Remove the "I'll do it later" form the Locking modal (we should keep this text on the "increase your rewards" modal FYI)
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/8f664663-632a-4352-9fe6-48e0dcc054a4)

- [x] Lockup confirmation modal needs to change:
     - [x] should say "You also have ... x GIVpower"
     - [x]  text at the bottom should be replaced to say "Coming soon: You will be able to use your GIVpower to support verified projects without donating. Learn more." (this will change back later, so maybe comment it out)
     - [ ] "Learn more" will link to a blog post/documentation that isn't written yet
     - [x]  we should remove the button "Boost Projects" for the MVP (comment it out)... the use can just click the "X" to close the modal

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/4675927f-4114-46c0-9a8a-5b9bb1324744)

- [x] "Get more GIV" on staking modal should have external link icon
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/5321b3ef-7412-44b7-8c42-04c3cb2dfd74)

**Comment by MohammadPCh** [comment]
@laurenluz about 'should say "You also have ... x GIVpower"' item, we show total GIVpower amount there, so is it ok to say: you also have .... GIVpower? because users may wrongly think the new locked amount will be added to it.

**Comment by laurenluz** [comment]
Oh! That makes sense! Lets leave it with " you have" :) thanks cherik!

**Comment by Cotabe** [comment]
@laurenluz

This was done, but there was a typo:
The tooltips in the "multiplier" box where it says "GIVpower" on all the modals should say "Coming soon: GIVpower will allow you to support verified projects will earning rewards." 
I believe the correct sentence is "Coming soon: GIVpower will allow you to support verified projects while earning rewards."

Should we turn off the Learn more link while there is no blog post/documentation to connect it to?

Everything else is DONE
