### ISSUE TITLE
Implement new UX for adding removing addresses

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#1150]
[Figma Link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=5790%3A126811)

**Comment by divine-comedian** [comment]
how can this issue be tested?

**Comment by MoeNick** [comment]
@mosaeedi 
1- Pls name the network like Eth-mainnet
2- Pls consider the error we have on avoiding exchange addresses.
3- appreciate if you can also consider H-cases, like repeated addresses. 
Repeated addresses
Not valid eth address
ENS not valid
4- You can enter ENS for Ethereum mainnet

**Comment by MoeNick** [comment]
@RamRamez it should not say filed is required when the user unchecks it. 
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/51112783-1690-457e-bddc-b94f8e374b67)

**Comment by MoeNick** [comment]
The copy should change to: 
I’ll raise & receive funds on Mainnet and Gnosis chain networks **with the same address**.
do not neet to bold it, bold is for here for emphasis it. 
![image](https://user-images.githubusercontent.com/80677512/179972314-2958925e-ec28-4d57-b51f-36cc671376fb.png)

**Comment by MoeNick** [comment]
- [ ] 3- Change teh copy

The copy should change to: You can enter a new address to receive funds on all supported networks.
![image](https://user-images.githubusercontent.com/80677512/179972813-13b2c74b-9aa9-4018-8d5d-64e43abc0553.png)

**Comment by divine-comedian** [comment]
More issues while testing: 
<img width="1208" alt="Screenshot 2022-07-20 at 08 34 53" src="https://user-images.githubusercontent.com/67759413/180010070-c874eae2-ad82-4a1c-b5e5-53df3255993d.png">
"Gnosis Chain" both words should be capitalized.

Also the text below should say Gnosis Chain, not Mainnet.

lastly the ENS feature doesn't seem to be working, check out the loom video:
https://www.loom.com/share/36e878e13c2345a4bfeee6fedb2b67de

no matter what ENS address I put it it tells me it is pointing to this address:
`0x4976fb03C32e5B8cfe2b6cCB31c09Ba78EBaBa41`

**Comment by RamRamez** [comment]
> More issues while testing: <img alt="Screenshot 2022-07-20 at 08 34 53" width="1208" src="https://user-images.githubusercontent.com/67759413/180010070-c874eae2-ad82-4a1c-b5e5-53df3255993d.png"> "Gnosis Chain" both words should be capitalized.
> 
> Also the text below should say Gnosis Chain, not Mainnet.
> 
> lastly the ENS feature doesn't seem to be working, check out the loom video: https://www.loom.com/share/36e878e13c2345a4bfeee6fedb2b67de
> 
> no matter what ENS address I put it it tells me it is pointing to this address: `0x4976fb03C32e5B8cfe2b6cCB31c09Ba78EBaBa41`

We used to return the ens resolver instead of the ens wallet address, I fixed it with the other notes mentioned above in PR #1180

**Comment by divine-comedian** [comment]
testing on `staging.giveth.io`

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67759413/180272596-d7b6b510-28a5-4496-9363-9db0a018691c.png">

all of the copy changes request by moenick appear to be implemented

also the ENS resolver appears to be working correctly! it even detects my ENS name and throws an error if it's already used for a project. 

all issues appear to be fixed! moving to done.

**Comment by mosaeedi** [comment]
Here is the design for all other cases, please take a look

[Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=11580%3A205321)

**Comment by divine-comedian** [comment]
> Here is the design for all other cases, please take a look
> 
> [Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=11580%3A205321)

A few text update suggestions, moving this back to sprint backlog for @RamRamez to take a look.

**Comment by MoeNick** [comment]
@mosaeedi @divine-comedian 
Let's revise the proposed design in another issue and focus on testing the functionality of this feature as is. 
I'll move it as a new issue, I appreciate it @divine-comedian if you only confirm the current feature can go live or not. 
Thanks

**Comment by RamRamez** [comment]
I added ENS resolved address to multi-recipient and loader to validating in PR #1192

**Comment by divine-comedian** [comment]
@MoeNick I would say the core ux issue is resolved, please link the new issue and move this one to DONE!
