### ISSUE TITLE
As a Donor, I want to comment on the Project Updates

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapps-v2#117]
Reviewing updates on projects I contribute to, I would like to leave a comment on it!

Sometimes to say there's something wrong with the update, like in this case where the images aren't showing up; but also to increase engagement with donors and project participants. For example, other people working on the project could add information, without having to log in as the project administrator.

What would it take to have a 'comment' button on project updates (as terribly rendered on the below screenshot, or the like)?

![aa screenshot for GitHub](https://user-images.githubusercontent.com/39466970/156206355-2e5beff1-0309-455e-877d-bc3d949e67ba.png)

**Comment by Danibelle** [comment]
I suppose that would entail spam protection and the ability to delete comments.. 🤔

**Comment by Cotabe** [comment]
I have the same feature request

**Comment by markoprljic** [comment]
This is a good idea. At the beginning we kept it simple for dev reasons, but if now is the time and can go into the roadmap then we should consider it. 
We would definitely need spam/report features integrated, similar to Gitcoin
![Screenshot 2023-01-25 at 12.19.56.png](https://images.zenhubusercontent.com/5cc090818b624e26c3734d75/14016062-c3f8-402c-8ac9-b4b8bd54a2de)

A rule could be that only signed up users can comment, so we know their identity.
