### ISSUE TITLE
Implement default APR when the user is not connected w/ wallet

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1173]
![Uploading image.png…]()

**Comment by laurenluz** [comment]
Hey @MohammadPCh I was testing this on the [GIVpower deployment](https://givpower.vercel.app/givfarm)... it's strange though...

when my wallet is not connected, the default view I see is mainnet. I see the APRs, but I see the 100% GIV staking pool & the balancer pool... not the GIVpower card.

I think it is ok if we have the default view be mainnet (especially since it will show the angel vault then) but we should have the GIVpower card show up too... since the user will see it on mainnet.

What do you think? This is what I see.
![image](https://user-images.githubusercontent.com/75490971/182441704-fe2f77cf-530f-402e-bc47-7a0fbff57b50.png)

**Comment by divine-comedian** [comment]
how can this issue be tested? is this two issues rolled into one?

**Comment by laurenluz** [comment]
sorry, it kind of is. I created a new issue for the second point.

yeah I think @divine-comedian this can be tested just by checking to make sure default view is mainnet & that you see all the same things you would if you wallet was connected... APRs should be correct...

and it should show mainnet regardless of what network your wallet is on (because your wallet is not connected)

**Comment by MohammadPCh** [comment]
As you said showing the GIVpower card and bridge modal is another issue that I'm working on it :)

**Comment by divine-comedian** [comment]
testing on `https://givpower.vercel.app/givfarm`
clean cache and cookies

while my wallet is not connected I see by default the mainnet farms, it appears to have a few issues though.
I do not see the farm for GIV/DAI nor do I see the Angel Vault farms..

Also I still see the 0% APR while my web wallet is disconnected, when I log in only then does the APRs show actual numbers.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67759413/182673013-42057f6a-af93-44fc-952a-2b955671a74c.png">

from my understanding of this issue this does not seem to be working properly on the givpower-develop branch..

# but wait...

checking on `giveth.io` and `staging.giveth.io` I can see that the default APRs do show up while I am disconnected on my web wallet

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67759413/182674086-46d61629-d7f5-429b-a5ce-fb4901f80fee.png">

so this seems to be working fine on other deployments, again I am stuck, where should I test? which one needs to be changed if anything needs to be changed at all? 

@MohammadPCh 
PLEASE HELP I AM GOING CRAZY TESTING

**Comment by MohammadPCh** [comment]
Hey @divine-comedian,
It's because we are using the deployment 6 environment in the GIVpower, so our config is different from the other branches.

**Comment by divine-comedian** [comment]
> Hey @divine-comedian, It's because we are using the deployment 6 environment in the GIVpower, so our config is different from the other branches.

If this is still relevant can you please provide the testing link?
