### ISSUE TITLE
GIVpower - add "lock" icon & tooltip to the GIV amount under "unstake"

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1188]
*If* the user has some part of their GIV locked, we shoud show a "lock" icon (where i circled below).

This lock should be a tooltip that says "Some or all of your staked GIV is locked. Click "Locked GIV details" for more information."

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/33aa3272-78bf-4e5a-82e6-b66f12c7f1d4)

@MohammadPCh or @mateodaza - can you take this?

**Comment by laurenluz** [comment]
The issue this is solving is the fact that the number under "unstake" is the total amount of staked GIV... although some may be locked and not able to be unstaked. I noticed this and the @Cotabe made a separate issue about it as well (independent of my influence).

I do not think we should link the user directly to the modal... this is even more confusing. they're just trying to figure out what the unstaked tokens are at this time.

There will be a link to that modal at the bottom of the card.

Regarding the "lock" symbol of the "?"... I mean, if @mosaeedi doesn't like the lock and insists on the "?", then ok... but I think the "lock" showing up only when some part of the tokens are locked actually provides information at first glance... whereas the "?" only seems to add more confusion... like why should you by wondering about the number under unstake?

**Comment by divine-comedian** [comment]
still waiting for the lock icon from @mosaeedi to move forward on this.

**Comment by mosaeedi** [comment]
Since we are going to show a tooltip, I think it's better to show the "?" icon because we always used the "?" for the tooltip and when users saw it, they know there is some more information, but showing the lock, may actually prevent user hover on the icon and instead they may think all of the tokens are locked!

**Comment by laurenluz** [comment]
ok! thank you @mosaeedi 

@MohammadPCh - can you implement?

**Comment by divine-comedian** [comment]
pending in PR 
https://github.com/Giveth/giveth-dapps-v2/pull/1274

**Comment by divine-comedian** [comment]
Ready to test on:
https://givpower.vercel.app/givfarm

**Comment by WhyldWanderer** [comment]
Testing on https://givpower.vercel.app/

I see the ? and the following message:
![image](https://user-images.githubusercontent.com/74267818/182913766-6a6cbff9-4333-444e-ada4-6de36fbc1194.png)


Looks good! Moving to done
