### ISSUE TITLE
GIVstream modal text fix

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1189]
Top part should say

"Welcome to the expanding GIViverse! With the GIVstream, as the GIVeconomy grows, so does the governance power of its contributors."

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/653cfe1a-df93-44fc-9630-2589e49be769)

@MoeNick - small issues, can you assign someone?

**Comment by divine-comedian** [comment]
testing on `staging.giveth.io`

looks good, moving to done!
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67759413/182454293-0204c8af-4aa0-406e-ad62-5cab34d6e057.png">
