### ISSUE TITLE
GIVpower - Lockup details modal tooltips

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1190]
- [x] APR tooltip: "The average annual rate of return for this set of staked GIV."

- [x] Total Staked GIV tooltip: "All your staked GIV, including GIV that is locked."

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/3320935a-c9c8-429b-a497-3f76ec02f864)

**Comment by Cotabe** [comment]
@laurenluz @aminlatifi @MoeNick 

DONE
