### ISSUE TITLE
GIVpower - GIVpower page is showing a crazy number for GIVpower

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1191]
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/8fe00ced-e559-4dac-9d8e-e98ae134aca1)

**Comment by laurenluz** [comment]
this should show the user's GIVpower amount.

**Comment by Cotabe** [comment]
@laurenluz @mohammadPCh @MoeNick 

This is fixed.
