### ISSUE TITLE
Stake Modal Tiny Value Issue

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapps-v2#1199]
When user balance is tiny stake modal shows only zero when the user set the value by percentage buttons (25%, ...)
Also it's not possible to manually enter tiny value

<img width="378" alt="image" src="https://user-images.githubusercontent.com/5684607/181004375-9b685cc0-48f5-45df-9bd8-e567ba79f1b0.png">

**Comment by divine-comedian** [comment]
how should this issue be tested?

**Comment by aminlatifi** [comment]
> how should this issue be tested?

You can send tiny amount of GIV (like 0.000000000000323) to a wallet address and try to stake it.

**Comment by divine-comedian** [comment]
testing on `staging.giveth.io`
Success! I am able to approve and stake a very tiny amount of GIV into the GIVfarm.

https://blockscout.com/xdai/mainnet/tx/0xebf45ff1f948fd50f8719c460a9db41f5df68effa91c73399e4ecde7ec0209c2

moving to done
