### ISSUE TITLE
I can no longer see the wallet address of the project

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#1201]
I can no longer see the projects wallet address on the Donations tab of their project's page.

![image](https://user-images.githubusercontent.com/74267818/181095027-37bb3e67-f1f9-460e-8156-18abd6d6c2a7.png)

Now that we have the functionality to have 2 wallet addresses, we should show both of them here.

**Comment by MoeNick** [comment]
Sorry we will fix this asap

**Comment by mosaeedi** [comment]
Here is how it should look like,

Single address on both networks: [Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=11775%3A207600)

Different addresses for both networks: [Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=11775%3A208513)

**Comment by MoeNick** [comment]
@mateodaza Accepted to take this one

**Comment by mateodaza** [comment]
Merged as hotfix to live version

**Comment by WhyldWanderer** [comment]
that was fast!! It looks good Thanks Mateo!

**Comment by RamRamez** [comment]
Thanks @mateodaza. Please link the related PRs to issues. It helps us track changes.

**Comment by divine-comedian** [comment]
@WhyldWanderer is this issue tested successfully? can it be moved to done?

**Comment by MoeNick** [comment]
Moved to production as hotfix.

**Comment by MoeNick** [comment]
Moved to production as hotfix.
