### ISSUE TITLE
GIVpower - "unstake" amount is not updating appropriately.

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1202]
I had 10k ish GIV already staked, and 16k GIV available to stake.

I staked and locked this 16k... and the "unstake" amount did not update, although now it says I have 0 to stake...

it should say I have 26k to unstake.

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/b6781c39-3026-49b8-a9a9-daa10b896c00)

**Comment by laurenluz** [comment]
oh.... during the time it took me to create that issue, it updated... but it seems strange... is that a subgraph thing? why does it show my staked tokens disappearing, but not yet showing up in unstake?

![image](https://user-images.githubusercontent.com/75490971/181113099-3c81aceb-bb69-473d-92e6-b600da9a4f0e.png)

**Comment by MohammadPCh** [comment]
@laurenluz please see this [comment](https://github.com/Giveth/giveth-dapps-v2/issues/1204#issuecomment-1196557768) .

**Comment by Cotabe** [comment]
It's working fine now
