### ISSUE TITLE
GIVpower - delay in staking & locking

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1203]
So... I had 10k staked, and 16k GIV available to stake.

I tried to stake & lock my new GIV... so I went to stake... then max'd out... staked the 16k... then went to increase my reward... maxed out (I assumed it was the 26k... but I think it was only the 10k I had originally staked.

There appears to be a delay in the staking, where is this coming from?

@aminlatifi @MohammadPCh 

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/b98fa85a-ac1a-4579-bd86-099e8fa97965)

**Comment by MohammadPCh** [comment]
@laurenluz please see this [comment](https://github.com/Giveth/giveth-dapps-v2/issues/1204#issuecomment-1196557768) .

**Comment by Cotabe** [comment]
@laurenluz @mohammadPCh  

There is still some delay. If you are super fast and do it (I assume before the transaction gets logged in the blockchain) this still happens. But you literally have to do it super fast.

**Comment by MohammadPCh** [comment]
Thanks @Cotabe, for testing, actually the reason is we get data from the subgraph, and sometimes it's not syncing or takes time to sync. we have another issue to show users if we are out of sync.  maybe it improves UX.
