### ISSUE TITLE
GIVpower - freshly after staking new GIV, when I go to lock it... the "max" input gives me a negative number

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1204]
I just made two other issues... something weird is happening, I don't understand it

@aminlatifi @MohammadPCh 

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/6b113847-0ae1-4b3b-9f91-e0fbd99cef4c)

**Comment by MohammadPCh** [comment]
I think It was my fault, I used the wrong parameter(use totalGIVLocked as user locked amount). I think It's fixed now. can you check it again?

**Comment by Cotabe** [comment]
@laurenluz @mohammadPCh 

This seems to be working fine now.
