### ISSUE TITLE
GIVpower - locked GIV details modal is tripping

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1205]
it is showing that I locked 4 batched... pretty sure I only locked 2...

also, the batched total to MORE than my staked total (27k GIV)

@aminlatifi @MohammadPCh 

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/0c6a500a-42c3-4666-b24f-d6bb53bae443)

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/06338263-567c-486c-9638-a422f8b71cc2)

**Comment by Cotabe** [comment]
@laurenluz 

Can't seem to reproduce the problem. So I guess it's fixed
