### ISSUE TITLE
Get involved button on Project single page

### ISSUE THREAD

**Issue by markoprljic** [Giveth/giveth-dapps-v2#121]

**Comment by mosaeedi** [comment]
@Tosinolawale what do you think?

**Comment by Tosinolawale** [comment]
> @Tosinolawale what do you think?

It is a good idea especially since we are working on creating and improving interaction between project owners/admin and other users. So the idea is now to have a get involved CTA, a project chat/comment and reply feature?

**Comment by WhyldWanderer** [comment]
> It is a good idea especially since we are working on creating and improving interaction between project owners/admin and other users. So the idea is now to have a get involved CTA, a project chat/comment and reply feature?

I know that the devs have it on the roadmap to add a feature that donors can comment on project updates.


We could maybe have a button that says "get involved" and the project owner could provide the link where they want it to connect to?
