### ISSUE TITLE
GIVpower APR tooltip

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapps-v2#1210]
<img width="581" alt="image" src="https://user-images.githubusercontent.com/5684607/181195106-44208e34-91e8-4cac-a97e-faf73e641bbc.png">

**Comment by aminlatifi** [comment]
@laurenluz https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE?node-id=10527:194487#235617591

**Comment by laurenluz** [comment]
Got it covered in #1190
