### ISSUE TITLE
Prompt user to sign in when trying to add hearts

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#122]
If I try to give hearts when not signed in, there is no reaction.

We should prompt the user to sign in before adding hearts.

**Comment by aminlatifi** [comment]
> If I try to give hearts when not signed in, there is no reaction.
> 
> We should prompt the user to sign in before adding hearts.

@WhyldWanderer On which view you tried to give hearts? Was your wallet connected?

**Comment by aminlatifi** [comment]
It seems it doesn't work when the user's wallet is not connected. Technically it will be different when like/unlike doesn't work on specific view.
