### ISSUE TITLE
Cover Verification form when the request is rejected or confirmed

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#1224]
As an applicant, I don't want to see the verification form (if I have the direct address) while the form is rejected or confirmed. 

Rejection: 
Unfortunately, your request for verification does not meet the minimum requirements and was rejected by the verification team. If you have any objections please contact the {support team}. (Link to discord or Typeform feedback)

Confirmation:
Congratulations!
Your project is now verified, so the donors may have GIVbacks for their donations to your projects. 
{call to action link to the project or what is Givbacks)

**Comment by MoeNick** [comment]
@WhyldWanderer @divine-comedian please give me a hand on the copies above.

**Comment by MohammadPCh** [comment]
@MoeNick we need also content (copy) for the submitted status. because when the form is submitted user can't change form data. so showing steps to him is not valuable. and maybe it's better to show some message with this new design.

**Comment by divine-comedian** [comment]
Happy to assist but I think @WhyldWanderer will know the best copy to write here.

**Comment by divine-comedian** [comment]
how can this issue be tested?
