### ISSUE TITLE
Transaction failed on the front end but went through the chain?

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-dapps-v2#1236]
Hi @MohammadPCh 

I have experienced a weird issue today. As a project owner, I have received a donation. The donation went through, I received it in my project's wallet **BUT** I didn't receive any email about receiving the donation as usual, and when I came to the project donation dashboard it is showing that the transaction **FAILED**.

https://giveth.io/project/ReVillaging-Mutual-Mentorships-Program-0

![image.png](https://images.zenhubusercontent.com/621267ef682a86d0321e6ccc/1187fb6c-07f2-4118-83ad-4892277c7b79)

This is the tx hash
https://blockscout.com/xdai/mainnet/tx/0x05a6e9dcab0e9561061e9b3be9dff36edda82d250468ad19c93e2926a5e97562

**Comment by MohammadPCh** [comment]
Hi @NikolaCreatrix,
Thanks for reporting this issue. @mohammadranjbarz is the hero who can check the database and server logs.

**Comment by mohammadranjbarz** [comment]
@NikolaCreatrix  @MohammadPCh 
Thanks for reporting and mentioning me, I don't know what was the reason but I changed it manually in Db

<img width="1437" alt="Screen Shot 1401-05-09 at 02 20 16" src="https://user-images.githubusercontent.com/9850545/181997268-602b11a9-7361-4cb6-88a7-e00694a6b2ca.png">
