### ISSUE TITLE
Enable Gnosis Safe App to allow all interactions within the multisig interface

### ISSUE THREAD

**Issue by mateodaza** [Giveth/giveth-dapps-v2#1240]
Following these issues [1](https://github.com/Giveth/giveth-dapps-v2/issues/811), [2](https://github.com/Giveth/giveth-dapps-v2/issues/417) and many others discussions in [discord](https://discord.com/channels/679428761438912522/988784701231738910/1002217200939171860) where users wanna donate / stake / etc using a gnosis safe multisig

@WhyldWanderer suggested to allow our app to be a gnosis "Safe" App, so we can connect directly through their interface like this and interact with our contracts more smoothly

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/18689480/181824526-5dd33033-e509-4569-9faa-9f09948d08ba.png">

**Comment by mateodaza** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/18689480/181824799-07171786-a186-4dc6-aeb9-47672cc12320.png">

**Comment by mateodaza** [comment]
I left the steps to test this out on the PR [here](https://github.com/Giveth/giveth-dapps-v2/pull/1241#issuecomment-1199862722)

@GriffGreen @laurenluz @divine-comedian maybe you guys know someone from gnosis to get us listed when we get this live

**Comment by laurenluz** [comment]
I know people at Gnosis! Mojmir is super cool & a friend, bet you he can help us...

can you explain more clearly what you mean by "get us listed" so I know what to ask?

**Comment by laurenluz** [comment]
it's like... we need to get giveth.io listed as something "safe" within gnosis safes?

**Comment by divine-comedian** [comment]
OMG yes! this issue is awesome!!

How should we coordinate this issue? We can also reach out to Auryn, honestly there's no shortage of contact for Gnosis but we should pick a lead.
