### ISSUE TITLE
Improve Giveth Donor Flow 

### ISSUE THREAD

**Issue by tropicalmangos** [Giveth/giveth-dapps-v2#1269]
@laurenluz here is the strategic overview on improving donor flow along with the list of suggested improvements! Lmk your thoughts! :) 

https://docs.google.com/document/d/1YcBsosn6VE2KoHs_jjCIBEMULD_9PD_zK7gZL8g6d3U/edit#heading=h.ucd0r9yaatsa

**Comment by laurenluz** [comment]
@MoeNick I explained to Katya about the repos :)

She created some awesome suggestions for improving the donor flow for her onboarding assignment. She'll send you the videos & give you access to her content, but I think it would be great to get your feedback on it, and help her break the useful parts into issues.

I will go through it again as well and provide my recommendations. 

Moved this to v2 repo.
