### ISSUE TITLE
Option to delete draft projects

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1271]
I have so many sketchy test drafts in "my projects" with no clear way to get rid of them? Can we add a little trashcan w/ an "are you sure?" modal please?

@mosaeedi @MoeNick 

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/c77774a1-9891-403e-97b6-4c44878ee41e)

**Comment by divine-comedian** [comment]
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/f1fbe29e-0bd1-4621-8b78-c7b45bc85998)
Add Delete Project as option for actions menu when project is in draft mode.

We should add a confirmation modal ARE YOU SURE YOU WANT TO DELETE YOUR PROJECT?

**Comment by laurenluz** [comment]
omg guys this is getting painful... @divine-comedian @mosaeedi 

there was an update to "My projects" where now the projects info takes up so much more space on the page...

and I still can't delete all the useless drafts which all appear FIRST. above my very legitimate projects.. Giveth & the matching pool.

so "my projects" is just now a total mess for me, and I'm sure I'm not the only one.. can we please prioritize this issue?

https://github.com/Giveth/giveth-dapps-v2/assets/75490971/50e77d00-9326-42ae-9a6e-326a77e1b2e6

**Comment by mosaeedi** [comment]
[Link to Figma](https://www.figma.com/file/0YfkSvCVtc3Zhh7dBjoMuB/My-Account?type=design&node-id=46-40206&mode=design&t=GbB7TJxA41q5DMZg-4)


When a project is in draft mode, the **Delete Project** option should be added to the action dropdown.

And when users click the Delete option, we need to make sure they know what they are doing with a confirmation modal.


<img width="1414" alt="Screenshot 2024-05-01 at 2 31 19 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/02b1cc81-d53b-4bd9-9966-e066fb01d99f">

**Comment by divine-comedian** [comment]
This looks great! I made https://github.com/Giveth/impact-graph/issues/1519 to follow up making the back-end endpoint for this before proceeding with FE

**Comment by laurenluz** [comment]
you guys are amazing <3 thank you

**Comment by MohammadPCh** [comment]
@mohammadranjbarz Do we have an API to delete draft projects?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz Do we have an API to delete draft projects?

No we don't have any API for deleting projects (draft or non-draft)
@divine-comedian  @laurenluz  if we need it, please create an issue for that

**Comment by divine-comedian** [comment]
> This looks great! I made [Giveth/impact-graph#1519](https://github.com/Giveth/impact-graph/issues/1519) to follow up making the back-end endpoint for this before proceeding with FE

@mohammadranjbarz - issue was made here about 2 months ago :sweat_smile:

**Comment by mohammadranjbarz** [comment]
> > This looks great! I made [Giveth/impact-graph#1519](https://github.com/Giveth/impact-graph/issues/1519) to follow up making the back-end endpoint for this before proceeding with FE
> 
> @mohammadranjbarz - issue was made here about 2 months ago, but it was never assigned to anyone 😅

![unagi](https://github.com/Giveth/giveth-dapps-v2/assets/9850545/e44c8d38-3966-40d5-b315-0be5dd94be78)

**Comment by MohammadPCh** [comment]
@mohammadranjbarz Is there any new update for it?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz Is there any new update for it?

I just assigned it to @Reshzera  , he will let you know here when implemented and merged

**Comment by divine-comedian** [comment]
@MohammadPCh - @Reshzera has implemented the BE endpoint, Is there another FE dev we can pass this to? 

@Reshzera please share any details on accessing the endpoint

**Comment by divine-comedian** [comment]
the backend has been merged in https://github.com/orgs/Giveth/projects/9/views/1?filterQuery=+status%3Adone+is%3Aopen+-label%3AStellar&pane=issue&itemId=68913749

Since Rafael is no longer here we will need to find the endpoint and how to integrate it in the FE to allow draft projects to be deleted. @kkatusic pick this one up whenever you have time.

**Comment by kkatusic** [comment]
@divine-comedian, I will take it, thx

**Comment by kkatusic** [comment]
@laurenluz, cc @divine-comedian, we have problem with environment variable, after investigation @mhmdksh fixed. You can try to check change on staging domain.

**Comment by LatifatAbdullahi** [comment]
Test Update


When project status is "**Draft**", the "Delete Project" option is present - **Pass**


![msr](https://github.com/user-attachments/assets/24f7fbe5-70f0-4228-993f-53ec60c9c49d)

![image](https://github.com/user-attachments/assets/2a05b0f2-14c4-43d1-a8e6-7734e922d81d)

When Project status is "**Active**"  the "Delete Project" option is absent - **Pass**

![fa](https://github.com/user-attachments/assets/385f1270-16ef-4a5d-b419-a2efe06123e4)



@kkatusic 
**However, I am unable to complete the delete process, as no action is taken after clicking on the "Delete Project" button**

![image](https://github.com/user-attachments/assets/a6c5809c-a6d8-4a9d-95b6-fdab62b3014a)


https://github.com/user-attachments/assets/620d46ed-56fc-47bf-93da-1d83478ac5db

**Comment by kkatusic** [comment]
@LatifatAbdullahi this function for delete is missing from code I'm investigating :)

**Comment by laurenluz** [comment]
hey guys, this issue is on prod, but it's not working, see recording...
@kkatusic 

https://github.com/user-attachments/assets/b44ba249-6f99-4fd8-b129-7ea70bb21bcc

**Comment by divine-comedian** [comment]
@kkatusic @LatifatAbdullahi I'm not sure this feature passed QA - so how did it end up in production?

**Comment by LatifatAbdullahi** [comment]
@divine-comedian 

Last time this was tested, the delete action failed and it was still being investigated, that's why its still open.

**Comment by divine-comedian** [comment]
OK but the code - which doesn't work - has been pushed to production, so now this is a problem that we have to focus on fixing  and push a hotfix..

**Comment by kkatusic** [comment]
> OK but the code - which doesn't work - has been pushed to production, so now this is a problem that we have to focus on fixing and push a hotfix..

no code pushed, just environment variable: `NEXT_PUBLIC_DELETE_PROJECT_ENABLED` let ask someone to setup it to false

**Comment by kkatusic** [comment]
@laurenluz, cc @divine-comedian, when you get time can you please check on production side is that option removed? thx

**Comment by laurenluz** [comment]
remove from prod
![image](https://github.com/user-attachments/assets/050af2b0-f3cd-4e07-9236-cb46ccd6a131)

**Comment by divine-comedian** [comment]
Thanks @kkatusic so we'll continue work on staging for the remaining bugs that @LatifatAbdullahi reported above 
https://github.com/Giveth/giveth-dapps-v2/issues/1271#issuecomment-2332167850

**Comment by maryjaf** [comment]
If you are busy with unicorn tasks  , I can take this issue @LatifatAbdullahi

**Comment by maryjaf** [comment]
Now the "delete" option is only shown in my project list, shouldn't this option also be shown in project page ? like as continu creation button a button there should be for delete?
@mosaeedi @divine-comedian 

![image](https://github.com/user-attachments/assets/534bdb4b-b899-490e-8d27-0b6364790989)

**Comment by divine-comedian** [comment]
thanks @maryjaf - its a good suggestion but this feature isn't a high priority - I've made a new issue to follow up adding the button on the project details view, if all other tests pass we can call this issue done and follow up in the issue https://github.com/Giveth/giveth-dapps-v2/issues/4838
