### ISSUE TITLE
Add links to Create a Project Modal

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#128]
Add links to Covenant and Terms of Use

![image.png](https://images.zenhubusercontent.com/5ffdde8079760c4346381d45/92f08994-57a6-4871-b332-51cf95d0f6a0)

"Covenant" should link to: https://docs.giveth.io/whatisgiveth/covenant/
"Terms of Use" should link to: https://giveth-dapps-v2.vercel.app/tos

**Comment by RamRamez** [comment]
I have fixed this before.
![image](https://user-images.githubusercontent.com/73441857/157086529-a9bad876-d40c-45e3-83cd-61a5f3889aa1.png)
