### ISSUE TITLE
GIVpower tiny text fixes

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1281]
- [x] Tooltip in the multiplier box should say: "Coming Soon: GIVpower will allow you to support verified projects while earning rewards."
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/fb8a6cbd-d491-4d8a-9716-f2976eb9df38)

- [x] The button on the GIVpower card should say "Locked GIV Details" (not "Locked GIV Tokens")
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/d99abd84-a6a8-43f0-8551-2fb9a73c393b)

@divine-comedian do you want to take this one? If not, please assign Cherik :)

**Comment by divine-comedian** [comment]
https://github.com/Giveth/giveth-dapps-v2/commit/152285dc9660b4eb94c517d7ca036f5519e962b3
changes are in here. 

ready to test in a few minutes on `https://givpower.vercel.app/givfarm`

**Comment by WhyldWanderer** [comment]
Testing on https://givpower.vercel.app/

Book issues appear to be resolved:

![image](https://user-images.githubusercontent.com/74267818/182914169-d68a4b2b-e0bd-492c-ae36-b5b7486bf0d8.png)


![image](https://user-images.githubusercontent.com/74267818/182914178-829cb8b5-550c-4cee-b5a2-e4c1d5ca8acf.png)


Great job! Moving to done!

**Comment by divine-comedian** [comment]
testing on https://giveconomy.vercel.app/givfarm

says locked GIV details 

tooltip has a small change the `Coming soon:` text is removed - I assume this is in anticipation of imminent release of boosting.

**Comment by laurenluz** [comment]
this is weird, I don't know how this moved back, should have been closed as it was from pre-locking launch,.
