### ISSUE TITLE
GIVpower average APR after locking tokens is wrong (too high!)

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1283]
The min APR is 544%
I locked some tokens for the max 26 rounds... so they will get an APR of 2828% (mutlplier of 5.2)

That's all correct in the lock details modal.

However... my average APR on the farm card is now way off... it is saying 4460% - way too high!

@MohammadPCh @aminlatifi 

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/f52e9ec0-e76e-4585-a5aa-9224f6cf6f56)
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/d35cceb4-d97d-486e-9489-235d179aa26a)

**Comment by WhyldWanderer** [comment]
Looks like Im getting similar results..

![image](https://user-images.githubusercontent.com/74267818/182905370-e1a4c24a-9869-4a99-a9f6-4a1dc8302ae2.png)
![image](https://user-images.githubusercontent.com/74267818/182905380-05873a78-7d93-497d-aa0b-fe44cd722239.png)

Im really bad at math but I dont think this is fixed yet...

**Comment by MohammadPCh** [comment]
hi @WhyldWanderer 
please add screen shots of the GIVpower card and lockup modal, so I can calculate them manually and check the results.
Thanks :)

**Comment by MohammadPCh** [comment]
@laurenluz I think it's done, @WhyldWanderer and I talked about it and it's confirmed.
