### ISSUE TITLE
GIVpower test deployment - I can't stake LP tokens in the Sushiswap pool?

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1285]
Testing here: https://givpower.vercel.app/givfarm
on Gnosis Chain.

But I can't stake my sushiswap LPs? It let's me approve... or sign the tx for permit... but I can't actually stake anything.

Is this some nuanced problem w/ this deployment?

@aminlatifi @MohammadPCh 

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/0dcf7975-36ad-400c-ac35-2a72728f11a0)

**Comment by franculio** [comment]
Tested on https://givpower.vercel.app/givfarm with DRGIV2 and TestWETH for LP tokens.

I tested with both approving and permit mode and it worked both times. 

<img width="462" alt="Captura de Pantalla 2022-09-16 a las 19 02 45" src="https://user-images.githubusercontent.com/79286405/190691785-5c9d1476-565a-43ed-8e08-6f89caeff000.png">

**Comment by MoeNick** [comment]
@aminlatifi @MohammadPCh this is merged on GIVpower only, if it's a critical bug, lets merge it into GIVeconomy and an to live.

**Comment by MohammadPCh** [comment]
@MoeNick Yes we fixed it about 2 months ago, before merging the GIVpower to GIVeconomy.
