### ISSUE TITLE
How to write a great project description modal

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#129]
This text is redundant:
![image.png](https://images.zenhubusercontent.com/5ffdde8079760c4346381d45/6ff7a448-1b14-49f8-ba3b-fdc29c4d1790)

**Comment by WhyldWanderer** [comment]
Also, when clicked, all links on this modal should open a new tab.

**Comment by RamRamez** [comment]
Done in PR #143 
1. remove redundant text
2. improve responsiveness
3. add scrollbar for small screens
