### ISSUE TITLE
Created project not showing in user account

### ISSUE THREAD

**Issue by clara-zi** [Giveth/giveth-dapps-v2#1292]

**Comment by clara-zi** [comment]
Hi, is there any more info that you need to help with this issue? Thanks

**Comment by MoeNick** [comment]
@CarlosQ96 man can you take a look at this, I could not find a clue on Admin.

**Comment by CarlosQ96** [comment]
On it!

**Comment by CarlosQ96** [comment]
@clara-zi Hello Clara! I found the root issue. 
So Amber has 3 accounts with different wallets she logged in. The wallet you posted in the issue has no projects related to it.
The correct one is ```0x92c95830f5292c9db6ceed202e89b844afd3a72d```, can you confirm if she can switch to this wallet for logging in? 

If it's not posible, let me know, and I'll proceed with changing the project owner to the new wallet.

**Comment by clara-zi** [comment]
So, project owner doesn't recognise the wallet you found connected to the project. 

Here is email response: 

"So I have done some troubleshooting on my end.

These are the only wallets I have, none of them match the number that you mentioned was connected to my project (0x92c95830f5292c9db6ceed202e89b844afd3a72d)

Metamask # 0xd5F4E89809A4236F7b7E72E63941516b26296fB0

Gnosis # 0x4B7Fa02EA8bE6363dF2AEE75C80e0c026FE3e627

Coinbase #See Attachment Image

I originally only had a coinbase and metamask wallet and recently got a Gnosis Safe in order to be able to sign up for Giveth. I was able to sign up with metamask and even create a project without getting the gnosis safe originally, yet within a week I got an email from you guys saying my project was unpublished and that I needed to follow certain steps to become compliant basically. So I then create a gnosis safe and added it to my account and then all of a sudden my project was missing.

As far as your instructions, I want to clarify I was able to access my account through logging in by all three wallets I mentioned above. Each bringing me to the same account I originally created yet still the project I created is missing. The wallet # that you guys suggested I have no idea where that has come from nor dod I have access to that.

Im on stand by for any other trouble shooting that may need to happen on my end"

@CarlosQ96 is the wallet connected to the project a torus wallet, inadvertently created by project owner. 

Account created with consciouslyconcepted@protonmail.com

**Comment by MoeNick** [comment]
We can transfer whenever we are sure about the identity of the person who is going to claim that account.

**Comment by CarlosQ96** [comment]
@MoeNick @clara-zi the project has been transferred to the new user. I will notify him. @WhyldWanderer  also gave me the green light to do this

**Comment by CarlosQ96** [comment]
Should I move to done?

**Comment by CarlosQ96** [comment]
Here is the proof:
https://giveth.io/user/0xd5f4e89809a4236f7b7e72e63941516b26296fb0

Project show in her user page.

**Comment by CarlosQ96** [comment]
Updated the project wallet addresses

**Comment by MoeNick** [comment]
Thanks @CarlosQ96 
@clara-zi can you approve the user don't have any problem from now?

**Comment by clara-zi** [comment]
Problem is now resolved.
