### ISSUE TITLE
GIVpower - Add "coming soons!" and get the page live

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1302]
@mosaeedi 

I was talking with Griff about this, since the GIVpower back is already developed, I think it is both safe (and great for building hype!) to push the page live.

Can you go through the page design and add a "coming soon" thing all over the place? I will circle the spots:

![image](https://user-images.githubusercontent.com/75490971/182701724-4d6521c9-c102-43d6-8f46-14f71067d5a8.png)
![image](https://user-images.githubusercontent.com/75490971/182702000-d7ddf2cb-5117-4cac-a1e1-2572980c3149.png)
![image](https://user-images.githubusercontent.com/75490971/182702239-c8cf0b28-1b40-4b52-a3e6-1d3a7d9be07f.png)

Then when we launch "staking & locking" we can remove some of the "coming soons" and leave others (like on boosting).

**Comment by mosaeedi** [comment]
## Design resource
[Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=12207%3A224770)

**Comment by laurenluz** [comment]
@MoeNick are we able to have someone take this on so we can get it up soon? :)

maybe @alireza-sharifpour or @MohammadPCh ?

**Comment by MohammadPCh** [comment]
@alireza-sharifpour can you take it?

**Comment by alireza-sharifpour** [comment]
> @alireza-sharifpour can you take it?

Sure, I'll do it.

**Comment by divine-comedian** [comment]
testing on `https://givpower.vercel.app/givpower`

I can see the coming soon in all of the places lauren specified.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67759413/184951500-addcf462-e479-42d2-bc63-b0eda176821a.png">

looks to be finished! moving to unit test passed
