### ISSUE TITLE
Donate Card  Responsive issue

### ISSUE THREAD

**Issue by MohammadPCh** [Giveth/giveth-dapps-v2#1304]
Donate card not showing correctly on my mobile, also it's a sort of slow and useless, I think we need to refactor this part.
![donate](https://user-images.githubusercontent.com/17097576/182800593-0aaf48cd-1a3d-4845-8a47-cfcee8a4f19f.jpeg)
@MoeNick @mosaeedi  @RamRamez  what do you think?

**Comment by MoeNick** [comment]
of course, lts do it. 
I did testing at the time of lunch and it was ok :(

**Comment by MohammadPCh** [comment]
Thanks Moenick,
it depends on cell phone performance and screen size. so in the high-end cell phones, it's ok.
@RamRamez can you take it?

**Comment by RamRamez** [comment]
> Thanks Moenick, it depends on cell phone performance and screen size. so in the high-end cell phones, it's ok. @RamRamez can you take it?

I fixed single project page responsive issues in PR #1301

**Comment by divine-comedian** [comment]
testing this on `staging.giveth.io`
metamask browser on mobile
phone - Google Pixel 6 Pro

I don't think my phone is bad enough to simulate @MohammadPCh test 😂

but I did notice some small issues - when scrolling up the donate modal I can scroll it up past where the modal ends, exposing the bottom of the modal.

![Screenshot_20220808-080217.png](https://user-images.githubusercontent.com/67759413/183437146-b2abed79-2518-4a22-a837-a8196433ee36.png)

Also I can push it all the way down and on scroll the small tab does show up, allowing me to pull it back up, however on my phone it can be hard to grab it without touching the bottom panel of the metamask browser. 

Also when I pull it up it moves very slowly and doesn't always scroll up all the way, it can be very hard to control. I made a short video on my phone to show how it's working

https://photos.app.goo.gl/Y1YCJ633sXUTgn3n7

**Comment by RamRamez** [comment]
> testing this on `staging.giveth.io` metamask browser on mobile phone - Google Pixel 6 Pro
> 
> I don't think my phone is bad enough to simulate @MohammadPCh test 😂
> 
> but I did notice some small issues - when scrolling up the donate modal I can scroll it up past where the modal ends, exposing the bottom of the modal.
> 
> ![Screenshot_20220808-080217.png](https://user-images.githubusercontent.com/67759413/183437146-b2abed79-2518-4a22-a837-a8196433ee36.png)
> 
> Also I can push it all the way down and on scroll the small tab does show up, allowing me to pull it back up, however on my phone it can be hard to grab it without touching the bottom panel of the metamask browser.
> 
> Also when I pull it up it moves very slowly and doesn't always scroll up all the way, it can be very hard to control. I made a short video on my phone to show how it's working
> 
> https://photos.app.goo.gl/Y1YCJ633sXUTgn3n7

fixed in PR #1377

**Comment by divine-comedian** [comment]
looks good! 

![Screenshot_20220921-092219.png](https://user-images.githubusercontent.com/67759413/191530370-f0933f61-2dae-4be5-a865-a410ededafb2.png)
