### ISSUE TITLE
Navigation - “Start Here” button

### ISSUE THREAD

**Issue by tropicalmangos** [Giveth/giveth-dapps-v2#1308]
**What problem is this design solving? Why is it necessary?**
Getting people to complete donor process smoothly (without dropping off) = More successful donors. 

**Is there any user data or feedback backing up this feature request?**
We currently don't collect data on the website but working on that to find tracking Dapps. 
Based on anecdotal accounts, there is user drop off and process is not super user friendly for newbies. 

**Which metrics will define this feature's success?**
# of users who complete donation process versus current stats 

**Additional context**
*Add any other context or screenshots related to your design here.*

Navigation - “Start Here” button  ---> Top Right Corner "Start Here" Pink Button. Because we already have 2 buttons already "Create a Project" and Sign in then Maybe the Start Here is just a single right hand button with a drop down for each option 
-  Sign in 
- create a project 
- how to donate
for example

Start here button goes to landing page (specifically dedicated to Newbie onboarding)

What is Giveth?
 - intro video 

How to Donate? 
- Video - Step by step overview (videos with numbered steps walking through how to donate) 

What next? 
- Join GIV economy

**Comment by MoeNick** [comment]
- Only on Homepage. 
- Only before sign-in , after connecting it disappears
- Having a slide / banner for it in home page. 
- have in in the Footer
- Different color. 
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/c8f22cd2-d7e1-47c5-be5e-314582b8ea23)
