### ISSUE TITLE
"What is the GIVstream" modal text fix (GIVpower deployment)

### ISSUE THREAD

**Issue by clara-zi** [Giveth/giveth-dapps-v2#1309]
![image.png](https://images.zenhubusercontent.com/6228be80d06a422295d2247f/59b6ff6f-0c42-4069-9235-5dee743a6518)

The GIVstream community .............. members with the long term success of Giveth and the GIVeconomy.

should 'rewards' be in the gap for missing text?

**Comment by clara-zi** [comment]
Also change 'with' to 'for'

**Comment by laurenluz** [comment]
"The GIVstream aligns community members with the long term success of Giveth and the GIVeconomy"

Thatnks @clara-zi

**Comment by divine-comedian** [comment]
ready to test on `https://givpower.vercel.app/givfarm'

**Comment by divine-comedian** [comment]
> @divine-comedian would you pls attach the PR?

It was a very very small change - I added the commit to my comment above

**Comment by divine-comedian** [comment]
testing on https://giveconomy.vercel.app/givfarm

this text looks to have already changed - 

![image](https://user-images.githubusercontent.com/67759413/203170827-f94c3e7f-4770-4cbc-8a67-ade235ecac79.png)

> Welcome to the expanding GIViverse! With the GIVstream, as the GIVeconomy grows, so does the governance power of its contributors.

@laurenluz can you confirm this is the expected text?
