### ISSUE TITLE
GIVpower - add tooltip to "rounds"

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1310]
Got some feedback from the GIVpower testing party that people didn't really understand how long a round is.

Do you think we should add a tooltip @mosaeedi to "Rounds"? that says something like "Rounds are 2 week periods corresponding to GIVbacks rounds."

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/9d182161-5864-4d6f-8eff-3f584c512f94)

**Comment by mosaeedi** [comment]
Adding more helpful information for users is not a bad idea! I'll add it to Figma.

**Comment by mosaeedi** [comment]
![Screen Shot 2022-08-04 at 8 55 56 PM](https://user-images.githubusercontent.com/13708322/182918419-1d35ec46-f71f-4639-8727-6469647434a1.png)

**Comment by mosaeedi** [comment]
## Design resource
[Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=10527%3A195680)

**Comment by laurenluz** [comment]
@MohammadPCh - can you implement? :)

**Comment by MohammadPCh** [comment]
@laurenluz Done :)

**Comment by MoeNick** [comment]
Just a kind reminder to put it in unit test column ✌️🙂.

**Comment by divine-comedian** [comment]
are we testing on https://givpower.vercel.app/ ?

**Comment by divine-comedian** [comment]
testing on https://givpower.vercel.app/

going to the card for GIVpower and clicking increase my reward I can see the modal for locking for rounds, hovering on the `?` next to round I am shown the correct text on the hover tooltip

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67759413/184374452-1c250058-7417-46fb-95ef-6bccb8fb5cc6.png">

moving to unit test passed
