### ISSUE TITLE
GIVpower - "locked GIV details" grey-out is not consistent

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1313]
When I have no GIV locked, the main card has it greyed out:
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/400150c9-cafb-4c81-8d4d-a3bc7c746d26)

But in "unstake" it is not greyed out:
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/e91d1b30-9c1a-4749-90b9-df2cd688d8a3)
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/271c2ebc-462f-4c6e-9257-8e97cd9b02bb)

I think it's kind of nice to be able to click it, even without locked GIV, and my preference is to have it clickable in both places. What do you think @mosaeedi ?

**Comment by mosaeedi** [comment]
it should be disabled on the "Unstake" modal too, why do you think it should be clickable when user doesn't have any locked GIV? it's like enabling the Unstake button when user didn't stake yet!

**Comment by laurenluz** [comment]
ok! @mosaeedi - let's do it how you suggest.

@MohammadPCh please make the "locked GIV details" disabled on the "unstake" modal when the user has no locked GIV.

**Comment by divine-comedian** [comment]
testing on https://givpower.vercel.app/ ?

**Comment by laurenluz** [comment]
should be!

**Comment by franculio** [comment]
Tested with no locked GIV and the button is grey-out 

![Captura de pantalla 2022-08-12 a las 16.42.09.png](https://images.zenhubusercontent.com/62ea6f3faed0f381f5fe2f36/b9fd6712-dc2d-452d-8b99-e869dcf3df5c)
