### ISSUE TITLE
GIVpower Boosting - 3 scenarios for GIVpower page

### ISSUE THREAD

**Issue by tropicalmangos** [Giveth/giveth-dapps-v2#1315]
Shows me as having 0 GIVpower but in wallet i have 1000 DRGIV2

<img width="582" alt="Screen Shot 2022-08-04 at 21 17 16" src="https://user-images.githubusercontent.com/110338123/182935057-83221371-b8b6-4cc7-a074-aceff569f06d.png">

**Comment by laurenluz** [comment]
it's because your GIVpower is not the same as your GIV. You have to stake your GIV to get GIVpower.

It says it further down on the page here: 
![image](https://user-images.githubusercontent.com/75490971/192638212-112ec554-79a7-42d5-bebe-2021f0b51fee.png)


is that not clear? do you think there should be a tooltip or some text change? open to suggestions.

**Comment by laurenluz** [comment]
Ok, I have an idea. When you have GIV, but no GIVpower, and it shows "0 GIVpower", we should have some text that says "Stake GIV to get GIVpower!"... and the "Boost Projects" button should instead say "Stake" and redirect the user to the staking pool. @mosaeedi can you make a quick design for that?

@GriffGreen is also suggesting that perhaps we *always* have two buttons here "Boost Projects" & "Stake"... but I'm worried that will make things too cluttered. What do you think @mosaeedi ?

![image](https://user-images.githubusercontent.com/75490971/192638573-1b05f051-f052-40f7-8ca7-cb1c07b91fd1.png)

**Comment by mosaeedi** [comment]
Nice catch @tropicalmangos!
@laurenluz I added a new state to this card for that situation, but like you said, adding two buttons is not a good idea! at least with this card design, maybe we can think of something later @GriffGreen, it makes sense to have two actions there but I don't want to make things messier for our users.
---
![Screen Shot 2022-09-30 at 5 34 34 PM](https://user-images.githubusercontent.com/13708322/193293532-75981072-a8b0-4141-bde9-0a5310904d33.png)

![Screen Shot 2022-09-30 at 5 32 13 PM](https://user-images.githubusercontent.com/13708322/193293572-a317dfa8-a150-4be1-9540-eb122db84ff0.png)

**Comment by mosaeedi** [comment]
Don't know why my comment changes into bold style!

**Comment by laurenluz** [comment]
@MohammadPCh @RamRamez or @mateodaza - can one of you take this?

We need to update it in the boosting version of GIVpower, so right now, the test deloyment at https://givpower.vercel.app/givpower

This is for the GIVpower page, at the top.

Three scenarios:
1. If the user's wallet is connected & they have GIVpower:
![image](https://user-images.githubusercontent.com/75490971/193308411-afd7cefb-2c1f-48db-b5c9-d62dafadab7d.png)

2. If the user's wallet is connected & they have no GIVpower:
![image](https://user-images.githubusercontent.com/75490971/193308487-5ca7b909-319b-4fa4-b6a6-bb339af77858.png)

3. If the user's wallet is not connected:
![image](https://user-images.githubusercontent.com/75490971/193308640-832b47de-f088-460f-aa8e-e70def4349ec.png)

**Comment by RamRamez** [comment]
> @MohammadPCh @RamRamez or @mateodaza - can one of you take this?
> 
> We need to update it in the boosting version of GIVpower, so right now, the test deloyment at https://givpower.vercel.app/givpower
> 
> This is for the GIVpower page, at the top.
> 
> Three scenarios:
> 
> 1. If the user's wallet is connected & they have GIVpower:
>    ![image](https://user-images.githubusercontent.com/75490971/193308411-afd7cefb-2c1f-48db-b5c9-d62dafadab7d.png)
> 2. If the user's wallet is connected & they have no GIVpower:
>    ![image](https://user-images.githubusercontent.com/75490971/193308487-5ca7b909-319b-4fa4-b6a6-bb339af77858.png)
> 3. If the user's wallet is not connected:
>    ![image](https://user-images.githubusercontent.com/75490971/193308640-832b47de-f088-460f-aa8e-e70def4349ec.png)

I'm on it

**Comment by maryjaf** [comment]
1- If the user's wallet is connected & they have GIVpower: Passed
2-If the user's wallet is connected & they have no GIVpower:Passed
3-If the user's wallet is not connected: Failed
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/8cc91e04-005b-444d-8c41-19384666ca8c)
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/3ef8f2be-7442-4919-b478-759bd2d42f87)
plz check item 3 @RamRamez

**Comment by RamRamez** [comment]
> 1- If the user's wallet is connected & they have GIVpower: Passed 2-If the user's wallet is connected & they have no GIVpower:Passed 3-If the user's wallet is not connected: Failed ![image.png](https://camo.githubusercontent.com/9e7966c2160619aec518bd055f1006b1dfb7fca57fa747a50c6eb81e3a7f4e08/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f38636339316530342d303035622d343434642d386334312d313933383436363663613863) ![image.png](https://camo.githubusercontent.com/bfd60b6c1ab12143a13f4468462ea9c9d5f194933a053444208b042ecfd78fba/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f33656638663262652d373434322d343931392d623437382d373539626432643432663837) plz check item 3 @RamRamez

In some cases MetaMask says it's not connected but actually it's connected on another account. In this case, you can lock your MetaMask to test it.

**Comment by maryjaf** [comment]
Thanks @RamRamez 
That's right.
I tested again with lock metamask and the correct message is shown.
