### ISSUE TITLE
GIVPower- Show Round Dates When Locking 

### ISSUE THREAD

**Issue by tropicalmangos** [Giveth/giveth-dapps-v2#1316]
hey guys the rounds are every 2 weeks right?

So when i changed how many rounds I was locking in for, I expected it to tell me what date I would be locking my tokens until. It would be super handy b/c to an outside saying you are staking for 8 rounds means nothing.. they might not know rounds are every 2 weeks....a date makes it more understandable in my opinion

you can see when i slide the ball across it changed my round number but the date didn't change
<img width="464" alt="Screen Shot 2022-08-04 at 21 24 30" src="https://user-images.githubusercontent.com/110338123/182936433-caba0bbf-4584-427d-9060-e3b48bf1bfdf.png">

**Comment by laurenluz** [comment]
this is because the round time was set to I think... 5 minutes? so even after 26 rounds, you're still on the same date. this is fixed when the round time setting is 2 weeks.
