### ISSUE TITLE
GIVPower- Projected Earnings 

### ISSUE THREAD

**Issue by tropicalmangos** [Giveth/giveth-dapps-v2#1317]
hey guys this is more a nice to have but seeing projected earnigns would be really cool and get people excited about staking/locking their tokens

seeing their earnings go up will increase the likelihood they lock longer b/c the benefit becomes tangible

<img width="470" alt="Screen Shot 2022-08-04 at 21 27 41" src="https://user-images.githubusercontent.com/110338123/182936675-72664a3d-27c0-49de-8cb9-9a92025ae6e1.png">

**Comment by laurenluz** [comment]
I think projected earnings is kind of not useful because the number is always going to be super super off. It feels like a false promise. If you agree, please close the issue! Or if not, feel free to make a counter argument
