### ISSUE TITLE
GIVPower- Locked GIV confirmation 

### ISSUE THREAD

**Issue by tropicalmangos** [Giveth/giveth-dapps-v2#1318]
hey guys, after getting GIV power I think the next CTA and logical step is to get them to allocate their tokens to projects and change the "learn more" button we have now to "Back PRoject / Support Project/ Send GIVpower" ...something like that. 

Not sure if it's in the works ?
<img width="1006" alt="Screen Shot 2022-08-04 at 21 31 41" src="https://user-images.githubusercontent.com/110338123/182937420-14ce19b3-bd4b-40ba-bf17-9e52bf85a404.png">

**Comment by laurenluz** [comment]
Yeah, the version you are testing on is when "Boosting" is not yet launched, so it's impossible to do that action. In the version with "boosting"  there should be a "boost projects" button already there.
