### ISSUE TITLE
GIVPower- (?) not working GIVfarm Rewards card

### ISSUE THREAD

**Issue by tropicalmangos** [Giveth/giveth-dapps-v2#1321]
cicked on (?) for explanation and nothing happened

<img width="704" alt="Screen Shot 2022-08-04 at 21 46 12" src="https://user-images.githubusercontent.com/110338123/182939636-5ea65de7-204c-469d-bbca-512863cd4d9c.png">

**Comment by laurenluz** [comment]
the "?" is a mouseover tooltip, it shows text on hover. For me it is working fine on the giveconomy test deployment
