### ISSUE TITLE
Wrong `Total Staked` value on GIVpower unstake modal

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapps-v2#1323]
<img width="377" alt="image" src="https://user-images.githubusercontent.com/5684607/183285405-1e0813eb-0af6-4a6b-bce6-e3ca14c4c71d.png">

I had 100 GIV Staked, then locked 25 GIV. In unstake modal I see `Total Staked` value 75, but it must be 100

**Comment by aminlatifi** [comment]
@MohammadPCh It must be gGIV token balance techincally

**Comment by divine-comedian** [comment]
testing on GIVpower 
https://givpower.vercel.app/

**Comment by clara-zi** [comment]
Recreated issue and tested on: https://givpower.vercel.app/givfarm

I had 100 GIV Staked, then locked 25 GIV. In unstake modal I now see Total Staked value 100

Issue fixed:

https://givpower.vercel.app/givfarm


<img width="299" alt="image" src="https://user-images.githubusercontent.com/100724132/184405892-af1bcfc7-26da-4b12-98e5-a60b6182fbc7.png">
