### ISSUE TITLE
Uneven amount of project cards on home page

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#133]
When I'm on the home page on regular screen resolution 1440px x 800px I can see there is a blank space where normally more project cards could be displayed. 

![image](https://user-images.githubusercontent.com/67759413/156612222-6765672f-2ab0-4507-8742-e72796cf76f9.png)

it feels weird that there is a blank space of projects, at first glance I think that there are no more projects left to show..

**Comment by MoeNick** [comment]
I think it gonna solved after responsiveness, correct me if I'm wrong @RamRamez

**Comment by MoeNick** [comment]
pls let us know if it's getting ready for QAAing. @RamRamez

**Comment by divine-comedian** [comment]
nice! looks to be resolved with the responsiveness design - no more awkward space in the corner - also tested this on several screen size and looks like the project cards fit evenly. 

![image](https://user-images.githubusercontent.com/67759413/158903279-0df38c27-f21a-4d7a-adf8-abb3fdda4adf.png)
