### ISSUE TITLE
change network not working in the reward card 

### ISSUE THREAD

**Issue by MohammadPCh** [Giveth/giveth-dapps-v2#1338]
we should show connect wallet modal if the wallet is not connected. after the wallet is connected, we should check the network and ask the user to change the network.

**Comment by aminlatifi** [comment]
@MohammadPCh Would you please explain as a user what will be changed?

**Comment by MohammadPCh** [comment]
in our previous version when the user clicks on the change network we use the Metamask wallet. but maybe the user wants to connect to another wallet. so we should show the wallet modal instead.
