### ISSUE TITLE
Standardized Project Format (Template)

### ISSUE THREAD

**Issue by tropicalmangos** [Giveth/giveth-dapps-v2#1348]
Problem
Currently some projects provide a 1 sentence blurb and others provide an in depth overview including: videos, pictures, website links etc. It's hard to compare projects or for projects to get an equal chance to receive donations like this. The donor is confused on which projects to donate to since some are missing critical info.

Proposed solution is to....
Create a Standardized Project Format (Template) --- part of project onboarding 

Proposed project Navigation tabs: 
- About Us 
- Mission 
- Gallery (Picture, Videos etc) 
- Social LInks / Website Links  
- Ask (Amount Needed) 
- Updates 

VIdeo overview for reference : 
Start at min 3:22-4:49 (end of video)
https://www.loom.com/share/136ebcc213b2490cbdd90c73c1d30677

**Comment by laurenluz** [comment]
I love this idea, especially adding input fields for the project owner to give their social links... and then having those show up in a default place on the publish project's page.

@MoeNick let us know if adding this feature could fit well in with some of our current development. Not high-pri but these kinds of UX fixes would be nice to add.

@mosaeedi would be happy to hear your feedback as well.

**Comment by MoeNick** [comment]
https://github.com/Giveth/giveth-dapps-v2/issues/1374

**Comment by markoprljic** [comment]
My thougths:
- we already have a standardized template and provided project owners a place and ways of adding description, it's up to them to use it properly
- forcing someone to fill in extensive information will increase the barrier to create a project (on the other hand it might filter out less relevant projects)
- The donor should decide to which project to donate based on his impression
- allowing to add social media and external links is good (should also be optional) and need a dedicated place on the profile page (maybe a box on the About section right above the beginning of the description text)
- asking for amount they want to raise is a completely different model and way of how the platform works, I don't think we want to change that, it has many implications and dependencies
