### ISSUE TITLE
Unify all detect device hooks

### ISSUE THREAD

**Issue by RamRamez** [Giveth/giveth-dapps-v2#1351]
There are three different detect device width hooks in our app (`useDetectDevice.tsx`, `useDeviceDetect.tsx`, `useMediaQuery.tsx`) that must be unified in a single hook. It will also help us resolve some responsiveness issues.

**Comment by MoeNick** [comment]
@RamRamez can you provide more test scenarios to this? so @maryjaf can test?

**Comment by RamRamez** [comment]
It affects these pages: (it's not merged yet in staging, it should be tested in [categories branch](https://givfilter.vercel.app/))

1. givpower modal (when clicking boost on project page)
2. create project page
3. donate page
4. similar projects in project page
5. projects page
6. verification
