### ISSUE TITLE
Filters erased when changing from "ALL" category to any other categories

### ISSUE THREAD

**Issue by franculio** [Giveth/giveth-dapps-v2#1352]
Tested on https://givfilter.vercel.app/ with Brave browser.

Whenever selecting filters in projects section in the "ALL" category and then changing to any of the other categories it deletes the filters seleceted:

![Captura de pantalla 2022-08-12 a las 17.27.50.png](https://images.zenhubusercontent.com/62ea6f3faed0f381f5fe2f36/a9a62e1f-ffc1-4583-b355-054bbefb63fa)

![Captura de pantalla 2022-08-12 a las 17.28.23.png](https://images.zenhubusercontent.com/62ea6f3faed0f381f5fe2f36/dfe6c151-e1af-4674-a735-0bb27fe2804b)

But this does not happen when changing between the other categories:

![Captura de pantalla 2022-08-12 a las 17.29.10.png](https://images.zenhubusercontent.com/62ea6f3faed0f381f5fe2f36/3f3d80a3-3693-4a19-8b35-ed96abd92c4b)

![Captura de pantalla 2022-08-12 a las 17.29.52.png](https://images.zenhubusercontent.com/62ea6f3faed0f381f5fe2f36/af69f54b-08ea-4c02-aa2b-b777aab233b1)

I don't know if this is supposed to be like this but it'd be more comfortable to keep the filters selected from the ALL category and then being able to change to the other ones and keep the selected filters.

**Comment by divine-comedian** [comment]
So to be clear this still happens on production. 

User visits all projects page - selects some filters then clicks on a project category
filters are erased/removed. 

here's a short video to show the problem:

https://github.com/Giveth/giveth-dapps-v2/assets/67759413/f08c0ced-d608-499a-a025-76be76d86adb


## Expected outcome: 
Filters are persistent even when user is switching categories of projects to view, up until user changes them or selects clear all filters

**Comment by MohammadPCh** [comment]
If we need to handle this, we have to have a new address for the all projects page, something like this:
`/projects/add`.
because we handle all filter stuff in a context. and contexts resets on route changes.
@divine-comedian If you agree with this we can do it.

**Comment by divine-comedian** [comment]
would it also help to resolve this issue?
https://github.com/Giveth/giveth-dapps-v2/issues/910

**Comment by MohammadPCh** [comment]
As I know, It's not a common UX on the web to save the state of the page when the user goes to another page. but yes. it's helpful  for it.

**Comment by MohammadPCh** [comment]
@divine-comedian  If you agree we can start :rocket:

**Comment by divine-comedian** [comment]
> As I know, It's not a common UX on the web to save the state of the page when the user goes to another page. but yes. it's helpful for it.

Actually I would consider it a very common UX - Consider for example when anyone uses an online marketplace such as Amazon, Walmart, eBay anything - you set your parameters for thing you want to buy and those parameters are saved in the URL - you can view items and press back and return to the search page with all of your parameters still in effect

**Comment by maryjaf** [comment]
When I select "recently updated"  from drop down menu the sort is set based on RecentlyUpdated
https://staging.giveth.io/projects/all?sort=RecentlyUpdated

and then by tapping on for example community, this sort remains, https://staging.giveth.io/projects/community (plz check this screen record) is this

Is this behavior expected ? @MohammadPCh 

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/6c950d36-8407-45c2-a047-5b3188d52e96

**Comment by MohammadPCh** [comment]
@maryjaf Nice catch. thanks

**Comment by MohammadPCh** [comment]
@maryjaf Please test it again. Thanks.

**Comment by maryjaf** [comment]
Thanks @MohammadPCh this problem has been resolved
