### ISSUE TITLE
Allocate more GIV to 100% GIV staking & GIV/ETH balancer

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1354]
This is for the GIVfarm extension. The amount of rewards & details are in the epic. #1353

**Comment by aminlatifi** [comment]
For better distribution of knowledge, I suggest @mohammadranjbarz do it and then I review. It was reverse before.

**Comment by mohammadranjbarz** [comment]
* [ ] Create a distributor file for GIV stake rewards ( startTime would be after current end time of farming)
* [ ] Create a distributor file for ETH/GIV rewards
* [ ] Setup cronjob for running new scripts
* [ ] Assign 900,000 to GIV/ETH farm on token distro (multi-sig)
* [ ] Assign 800,000 to GIV stake farm on token distro (multi-sig)
* [ ] Transfer 1,700,000 GIV to token distro @divine-comedian

**Comment by divine-comedian** [comment]
Just to clarify - we'll need to send 900k GIV to the Mainnet Token Distro and we'll need to send anywhere from 400k-800k GIV to the Token Distro on Gnosis Chain. 

I have created the tx to top-up the mainnet token distro here- 
https://gnosis-safe.io/app/eth:0xf924fF0f192f0c7c073161e0d62CE7635114e74f/transactions/multisig_0xf924fF0f192f0c7c073161e0d62CE7635114e74f_0xe409c9961ff2b6502293c1992f9328f1e45235d424c7faf24924518cfb2d10ee

and for Gnosis Chain let's wait to see how many weeks until GIVpower launches then we'll know how much to top-up the token distro.

**Comment by mohammadranjbarz** [comment]
> Just to clarify - we'll need to send 900k GIV to the Mainnet Token Distro and we'll need to send anywhere from 400k-800k GIV to the Token Distro on Gnosis Chain.
> 
> I have created the tx to top-up the mainnet token distro here- https://gnosis-safe.io/app/eth:0xf924fF0f192f0c7c073161e0d62CE7635114e74f/transactions/multisig_0xf924fF0f192f0c7c073161e0d62CE7635114e74f_0xe409c9961ff2b6502293c1992f9328f1e45235d424c7faf24924518cfb2d10ee
> 
> and for Gnosis Chain let's wait to see how many weeks until GIVpower launches then we'll know how much to top-up the token distro.

Great, thank you

**Comment by divine-comedian** [comment]
Yes we need to top-up the token distro based on how long it takes for GIVpower to launch - how many weeks we needed to extend giv single staking

**Comment by divine-comedian** [comment]
> We plan to launch GIVpower staking/locking on Tuesday October 4 FYI

Nice! So just to make some calculations:

Between August 19th and October 4th that is 46 days

We know we spend 100,000 weekly on the farm. 100k / 7 gives us a daily rate of 14,285.714285714

14285.714285714 * 46 = 657,142.857142844 Total GIV spent in the farm, assuming we launch on the 4th.

That brings the total amount we need to top-up the tokenDistro to **1,557,142.857142844**

**Comment by MoeNick** [comment]
shall we close it @laurenluz ?
