### ISSUE TITLE
De-activate discontinued GIVfarm cards

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1355]
We will need to deactivate certain GIVfarm cards, as outlined in #1353 

- [x] We should have them look like this:
![image](https://user-images.githubusercontent.com/75490971/184451814-3806bada-7971-44cf-a179-18821b3e7202.png)

- [x] The user should still be able harvest their rewards and unstake from a deactivated card
- [x] The card should remain "unarchived" for 3 weeks, after which point they should be accessible only under the "show archived pools" toggle

**Comment by mateodaza** [comment]
For the last point I will set a timer of 3 weeks as soon as we deploy this to production, or do we have a date already? @laurenluz

**Comment by divine-comedian** [comment]
coming back to this issue - it's been well over 3 weeks and I can still see the discontinued pools, unarchived on production. Did we move the date or is this an error?

![image](https://user-images.githubusercontent.com/67759413/190705831-76997e9d-a9cb-4e3e-9646-87b22be0ce3d.png)

**Comment by maryjaf** [comment]
How do I find out how long it has been since the three-week deadline for the projects that will be archived soon? @mateodaza

**Comment by laurenluz** [comment]
they are!
