### ISSUE TITLE
Mandatory updates: Change the verified badge to revoked

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#1365]
After 104 days without an update, the project’s verified status should change to “revoked”. This means that the project is still listed and can receive donations, their donors will no longer receive GIVbacks, and the verification team will have an indication that the project was once verified.

**Comment by maryjaf** [comment]
How can I test this? @CarlosQ96 @MoeNick 
Can we change to hour on stg?

**Comment by maryjaf** [comment]
one question
When the project is   verified: No & verification status: revoked, after registering an update, what changes will be made in the status of the verified & verification status ?
Now my project has these conditions and I registered an update, but I did not see an option for editing in the admin section of the updates.
@CarlosQ96 @MoeNick

**Comment by CarlosQ96** [comment]
This second part is not implemented as it's new feedback Ashley told Moe. So I have to implement it.

I think the correct flow is.
IF verification status = Revoked and a new update is added -> make the project verified again. @MoeNick is that right?

I added a view inside the single project view in adminbro that lists the projectUpdates, they are not editable tho. I don't think we should edit them, but there is a future issue to make them reviewable but that haven't been implemented yet.

**Comment by maryjaf** [comment]
> IF verification status = Revoked and a new update is added -> make the project verified again. @MoeNick is that right?
Thanks @CarlosQ96 
This means when an update is registered for the Revoked project and this update is approved by the admin (currently we don't have this in admin and there is no option for approval or rejection in the Project Update section, it only has a show option) after confirming the verification status of project change to  null It changes that the user can see the "resume verification" option.
I got it right? @CarlosQ96 @MoeNick

**Comment by MoeNick** [comment]
I think they should re-apply (or resume) the verification form and submit it again to make their projects verified/ 
so no need should apply to a  "verified: No & verification status: revoked" project.

**Comment by maryjaf** [comment]
when verification status is Revoked, "RE-APPLY"button is shown which has the same function as "Resume Verification"
In other scenarios, when the form is draft and the  verification status status is null, reminder, warning, last chance & ready for revoking,  "resume verification" button is displayed
