### ISSUE TITLE
Verify Your Project: Single Project, Project Owner View

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#1367]
If a project’s verification status becomes “revoked” they will need to add an update and reapply in order to get the status reinstated. This will affect the ‘verify your project’ link availability.

**Comment by MoeNick** [comment]
@maryjaf @divine-comedian , pls chaeck for scenario: make it revoked in Admin so you should not see the apply for verification in owner view

**Comment by divine-comedian** [comment]
testing this out on https://staging.giveth.io

in the adminbro I 'revoke badge' of a verified project which I am the owner of. 

if this project is active then now my projects says I have to verify my project. 

I do not have to add any updates or change anything in my project to continue with the re-verification process. I have to completely redo the verification process and submit again for review, in admin bro I see my project and can add back my verification badge and listed status.

This UX could use some improvements:

- the obvious fix is that as a project owner I am not forced to make any updates or edits to my project and re-apply for verification
- there should be more frontend indications to the project owner that their project was revoked and they need to re-apply
- it was a bit annoying that I had to redo my entire verification application

**Comment by mateodaza** [comment]
@MoeNick should we make new issues from the UX suggestions Mitch just mentioned? or what do you say?

**Comment by MoeNick** [comment]
@mateodaza hmmm... yeah lemme talk with @mosaeedi and will update this issue, thanks for tagging me here.

**Comment by MoeNick** [comment]
@maryjaf 
Test Scenario:
Make a project revoked, and the verify my project button should be be appeared in project owner view, in all statuses.

**Comment by maryjaf** [comment]
After revoking the project In the view of : the project owner and other people and list of project , the verify  badge is not displayed.
