### ISSUE TITLE
Test environments for Subgraph

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#1373]

**Comment by mateodaza** [comment]
Adding GH Actions for main and staging branches - solved in this [PR](https://github.com/Giveth/givpower-subgraph/pull/21) from givpower subgraph repo

**Comment by MoeNick** [comment]
@mateodaza @aminlatifi what to do with this issue?

**Comment by aminlatifi** [comment]
We have two branches at the moment, one main for production and one develop for staging
Current version:
main -> 1.1.0
develop -> 1.2.0

**Comment by aminlatifi** [comment]
@mateodaza Did you follow up subgraph mainnet deployment issue? I mean can we assume we are ready for merging develop to main and deploy to production?
