### ISSUE TITLE
Improvements on "You're a Giver" page

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#1376]

**Comment by markoprljic** [comment]
Hi @tropicalmangos I appreciate the initiative and I love your ideas! :) 
One thing though, is the amount of content to show on this page. It's definitely too much. I left some comments in the doc.

What is the goal of this redesign? Do we have any analytics from this page where users are going or dropping? 
Did we spot a particular problem, or are we trying to test out a new funnel?
