### ISSUE TITLE
Stake modal initial permit/approve state

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapps-v2#1394]
**Describe the bug**
When you open the stake modal for the first time, the switch button is on permit mode. But when you want to stake by pressing a percentage button, the Approve button is shown.
You have to switch back and forth on permit/approve mode to be able to user permit mode functionality

**To Reproduce**
1. Go to the farm page
2. Refresh the page
3. Choose a farm that has permit mode feature and you have positive LP to stake
4. Click stake
5. Click 25% button
6. The approve button is shown while the switch is on permit mode

**Expected behavior**

**Screenshots**

<img width="396" alt="image" src="https://user-images.githubusercontent.com/5684607/185354187-bd8451fa-1279-476a-a654-ab344302e4a1.png">

**Desktop (please complete the following information):**
 - Browser Brave

**Comment by aminlatifi** [comment]
@maryjaf It's fixed in giveconomy branch. @MohammadPCh  will push this fix as a hot fix to production and also merge it to the develop branch too

**Comment by MoeNick** [comment]
If it's working on giveconomy branch (as a UAT) so @maryjaf after the success test, pls put it in Done.

**Comment by maryjaf** [comment]
<img width="522" alt="image" src="https://user-images.githubusercontent.com/111529185/191825520-5e0e58c9-8b69-440d-8dba-6cf1e4b01ed3.png">
I tested on staging env and the stake button is shown while the switch is on permit mode @aminlatifi

**Comment by aminlatifi** [comment]
@maryjaf it's fixed in giv economy branch
@MoeNick may have told you we have two env for testing

**Comment by maryjaf** [comment]
> @maryjaf it's fixed in giv economy branch @MoeNick may have told you we have two env for testing

<img width="1294" alt="image" src="https://user-images.githubusercontent.com/111529185/191892837-3d5fbc50-3d6c-4a6f-82d3-28b4e662d33f.png">
I tested again on https://giveconomy.vercel.app/ but i didn't see changes

**Comment by MoeNick** [comment]
> https://giveconomy.vercel.app

Approve is not shown while you are on permit mode. So seems it's ok. 
@maryjaf
