### ISSUE TITLE
Sort GIVFarm cards 

### ISSUE THREAD

**Issue by mateodaza** [Giveth/giveth-dapps-v2#1400]
Based on this [design](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=12493%3A231529) 

![image](https://user-images.githubusercontent.com/18689480/185518611-5c0be543-dd37-4150-ad95-8a6aeaf10892.png)

Sort all GIVFarms according to 

- [ ] Default
- [ ] Highest APR
- [ ] Newest
- [ ] Oldest

**Comment by divine-comedian** [comment]
It's not clear what defines `default`, let's just have Highest APR be the default view. 

so let's just have three options Highest APR (default), Newest and Oldest

**Comment by aminlatifi** [comment]
> It's not clear what defines `default`, let's just have Highest APR be the default view.
> 
> so let's just have three options Highest APR (default), Newest and Oldest

What defines data? and consequently newest and oldest order?

**Comment by mateodaza** [comment]
> > It's not clear what defines `default`, let's just have Highest APR be the default view.
> > so let's just have three options Highest APR (default), Newest and Oldest
> 
> What defines data? and consequently newest and oldest order?

We could use the contract deployment date or the date we made each farm publicly

**Comment by laurenluz** [comment]
I like the "Default" view to be the order we decide... So like.. GIVpower is first because we want people to use it the most, next we have Angel Vault because it is second more important to us... etc.

Is that possible? to have "default" be an order we decide based on "relevance to our mission"?
