### ISSUE TITLE
Title text cut off in popups for claiming GIVdrop

### ISSUE THREAD

**Issue by danelsuga** [Giveth/giveth-dapps-v2#1401]
I clicked on "claim", and the subsequent series of pop-up windows all had the top text of the window cut off (unreadable).

![image.png](https://images.zenhubusercontent.com/6066d509782b4d63df5cd761/3597e04c-75ad-47af-a71f-fa6f42c7ba00)

**Comment by MoeNick** [comment]
Hey @danelsuga , to be honest, we do not support this wizard, it's a legacy and old code, however, my question is why you got there. do users still visit this page?
