### ISSUE TITLE
Notification center [single page view]

### ISSUE THREAD

**Issue by mosaeedi** [Giveth/giveth-dapps-v2#1420]
## Design resource

- Notification center -> [Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=12068%3A209462)

- Notification structure -> [Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=12068%3A210172)

---

**Comment by maryjaf** [comment]
1- On test branch
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/57f981b7-8b30-4dfc-8d22-53cc88279121)
2- Figma

![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/c7a67e30-ad50-40a3-89dc-bed09d8f6c92)
1 OR 2 ? @MohammadPCh

**Comment by maryjaf** [comment]
All my notifications are not displayed on the notification center page
Should we see a specific number on this page? If so, how many or notifications related to what date @MohammadPCh @MoeNick 
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/bffd5598-6402-40ee-82f4-4760ef1315f0)
According to the image of one of the previous notifications that was not read, I do not see that it will be read

**Comment by maryjaf** [comment]
> All my notifications are not displayed on the notification center page Should we see a specific number on this page? If so, how many or notifications related to what date @MohammadPCh @MoeNick ![image.png](https://camo.githubusercontent.com/02c859702e4a163a747fba9a7cec53ec300698c4d1ac835af1f05a8f9a5cec76/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f62666664353539382d363430322d343065652d383266342d343736306566313331356630) According to the image of one of the previous notifications that was not read, I do not see that it will be read

reminder @MoeNick @MohammadPCh

**Comment by MohammadPCh** [comment]
@maryjaf This problem has been resolved. can you check it again? Thanks.
