### ISSUE TITLE
Failed Status but transaction successful

### ISSUE THREAD

**Issue by freshelle** [Giveth/giveth-dapps-v2#1434]
My donation status is "failed", and it doesn't show up in the list of donations to the project [The Giveth Community of Makers](https://giveth.io/project/the-giveth-community-of-makers).

The [transaction link](https://blockscout.com/xdai/mainnet/tx/0x30bc658a93eb326df5e94d9246702f271110a870b9e2d365ed1a8049c7cf45db) is successful in blockscout.

<img width="1330" alt="image" src="https://user-images.githubusercontent.com/86718721/186708188-5ce276e7-acfd-4298-bc66-0a06e8f865fd.png">

**Comment by freshelle** [comment]
It happened again :(

But the total donate of the project reflects my donation (I think). Project: https://giveth.io/project/pies-to-the-hospital


<img width="1294" alt="image" src="https://user-images.githubusercontent.com/86718721/186725379-4f66f05b-d946-4838-899f-492c13bbccdc.png">

**Comment by MoeNick** [comment]
@CarlosQ96 @mohammadranjbarz can you please take a look

**Comment by mohammadranjbarz** [comment]
@MoeNick  @freshelle 
I changed status of this donaiton manually in DB and created an issue for that ( before distributing givbacks in each round I test these kind of donation and fix them manually)

**Comment by mohammadranjbarz** [comment]
@freshelle  Thansk for you report and the detail that you put in the issue
