### ISSUE TITLE
GIVpower - improvements on rocket icon alignment

### ISSUE THREAD

**Issue by freshelle** [Giveth/giveth-dapps-v2#1435]
Just a minor comment on the alignment of the **rocket icon** after successful staking. Would be nice to have it center aligned with the amount of givpower, same as the one in green box

![image.png](https://images.zenhubusercontent.com/60e263ee73d25c2e2bd82cc4/c22a4383-4ed8-41d8-91a3-bf9953cae809)

**Comment by MoeNick** [comment]
@mosaeedi
