### ISSUE TITLE
showing the complete profile toast wrongly

### ISSUE THREAD

**Issue by MohammadPCh** [Giveth/giveth-dapps-v2#1437]
when the user's token is expired, and the user goes to the account page, we show a toast that says please complete your profile.

the main problem is when the user's token is expired the backend doesn't return the email, so we think the profile is not complete.

I talked with Mohammad (Giveth/impact-graph#602) and ask him to add `isSignedIn` to the `getUserByAddress` query. so we can distinguish that the user is not signed in or the profile is not complete.

**Comment by maryjaf** [comment]
On which test environment can it be tested? @alireza-sharifpour

**Comment by alireza-sharifpour** [comment]
@maryjaf 

You can test it on staging
https://staging.giveth.io/

**Comment by maryjaf** [comment]
I tested the scenario described in the issue (when the user's token is expired, and the user goes to the account page, we show a toast that says please complete your profile.)

on the staging env, the toast related to completing the profile is not displayed correctly.
But in this scenario, like in production, the list of projects and donations, etc., is not displayed
Is this how it should be? @alireza-sharifpour 
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/111529185/191933428-a467d730-d04a-4837-b540-0cb3f964c42b.png">

**Comment by alireza-sharifpour** [comment]
> I tested the scenario described in the issue (when the user's token is expired, and the user goes to the account page, we show a toast that says please complete your profile.)

When the token is expired in this page the user should be signed out and see the sing in message, not the account page.
