### ISSUE TITLE
Adding Discord icon at the bottom of the homepage 

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-dapps-v2#1458]
I was looking for the Discord link access at the bottom of the home page, and saw Discord is not included in the icons (Youtube, Reddit, Medium, etc) 
I found the Discord access in the [Join Our Community ](https://giveth.io/join)section. 
![Captura de Pantalla 2022-09-01 a la(s) 16.21.32.png] Think would be worth to add it as is the main comms channel for the community 

<img width="1285" alt="Captura de Pantalla 2022-09-01 a la(s) 16 21 32" src="https://user-images.githubusercontent.com/110692280/188016328-c0f9597a-dfd0-4f26-a513-d0b26e771657.png">

**Comment by MoeNick** [comment]
@alireza-sharifpour do you need the discord icon?

**Comment by alireza-sharifpour** [comment]
> 

I Have it, i'll add it to the footer.

**Comment by oyealmond** [comment]
I saw the icon is already placed and working in https://staging.giveth.io/  
@alireza-sharifpour @MoeNick 
:) 

<img width="1227" alt="Captura de Pantalla 2022-09-04 a la(s) 10 15 12" src="https://user-images.githubusercontent.com/110692280/188320733-71324861-2525-4a0f-aa3a-d7ff16dc6375.png">

**Comment by MoeNick** [comment]
I moved it to done @maryjaf 
You may want to test again to make sure? It's easy but in these easy cases we may also check both GIVeconomy and Dapp footer and also check it on mobile views.
