### ISSUE TITLE
Some issues on project donate card

### ISSUE THREAD

**Issue by RamRamez** [Giveth/giveth-dapps-v2#1459]
1. In some screen sizes, navigation buttons of similar projects are not center aligned to project card border 

![image](https://user-images.githubusercontent.com/73441857/188009542-a5f1ba4f-ab11-4c4a-aadc-e16da4ee84a0.png)

2. In liked projects tab in my projects section and also in liked projects tab and user projects tab in public profile view there are three issues
     1. top left border should have radius
     2. last updated value is `Just now` for all projects
     4. there is no author name, organization badge, verified and Givback eligible badge, in any of the projects

![image](https://user-images.githubusercontent.com/73441857/188144681-fe447b8c-d600-4fd0-99e0-7cb2f2c5e714.png)

3. project donate card width in all web pages should be 100% (project card width limit should be removed). It affects the project card responsiveness in the following pages:
     1. homepage
     2. similar projects in single project view
     3. projects page
     4. public profile (liked projects and user projects)
     5. liked projects in user account view

**Comment by maryjaf** [comment]
I tested and 1 & 2 passed, but i didn't understand 3 @RamRamez

**Comment by RamRamez** [comment]
> I tested and 1 & 2 passed, but i didn't understand 3 @RamRamez

According to [figma ](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=2900%3A99698) these gaps are wrong:

![image](https://user-images.githubusercontent.com/73441857/189626456-a1f1397f-395a-43f7-976b-3fab9559bc43.png)

It should be like:

![image](https://user-images.githubusercontent.com/73441857/189627981-dee981c8-3d8a-499c-aaf4-2be6b71908a3.png)

It affects the the following pages:
    homepage
    similar projects in single project view
    projects page
    public profile (liked projects and user projects)
    liked projects in user account view
