### ISSUE TITLE
Create new texty-primary and texty-secondary buttons in design system

### ISSUE THREAD

**Issue by alireza-sharifpour** [Giveth/giveth-dapps-v2#1468]
We need to implement two new button components in our design system
texty-primary 
<img width="128" alt="Screen Shot 2022-09-04 at 5 00 47 PM" src="https://user-images.githubusercontent.com/48887817/188313564-247510b4-7c14-46ac-a0e9-68feb41686fb.png">
texty-secondary
![Screen Shot 2022-09-04 at 5 01 17 PM](https://user-images.githubusercontent.com/48887817/188313586-8e11c614-3c4e-483b-b6b8-a71ab7242994.png)
![Screen Shot 2022-09-04 at 5 01 34 PM](https://user-images.githubusercontent.com/48887817/188313599-5a28621d-616d-4a96-9479-991ff97f098f.png)

Also we need to improve our button's types

**Comment by maryjaf** [comment]
How do I test texty-primary (NOT NOW)? @alireza-sharifpour

**Comment by alireza-sharifpour** [comment]
> 

I think it doesn’t need testing, because it's an internal thing, what is your idea @MohammadPCh ?

**Comment by MohammadPCh** [comment]
@alireza-sharifpour I totally agree with you. :+1:
