### ISSUE TITLE
No caption when address is correct

### ISSUE THREAD

**Issue by RamRamez** [Giveth/giveth-dapps-v2#1469]
On create project project page when entered wallet address is correct, the `You can enter a new address to receive ...` caption should be removed.

![image](https://user-images.githubusercontent.com/73441857/188313795-01ff92d7-a5c3-453c-b184-690e4a871166.png)

this is related to https://github.com/Giveth/giveth-dapps-v2/issues/1185#issuecomment-1213308951

**Comment by maryjaf** [comment]
I tested this scenario and  the caption will be removed when the addresses are entered correctly.
<img width="667" alt="image" src="https://user-images.githubusercontent.com/111529185/189533604-0c830dc3-2764-45d0-8ef1-15b2289261a4.png">
