### ISSUE TITLE
sign out user automatically when user wallet is changed

### ISSUE THREAD

**Issue by RamRamez** [Giveth/giveth-dapps-v2#1485]
1. in account view if user changes the metamask account, it says `Your profile is incomplete` (even if the user profile is completed). The correct way is that it should ask user to sign in.

![image](https://user-images.githubusercontent.com/73441857/189134313-eb135536-251c-44e9-8453-bc7091ea2fe8.png)

2. in account view if user locks his wallet, he can still see the dashboard. The correct way is to ask user to connect his wallet.

![image](https://user-images.githubusercontent.com/73441857/189134728-0e63fc31-8213-4311-b29d-ca4afa625e14.png)

**Comment by maryjaf** [comment]
I tested and 1&2 cases are passed .Thanks @RamRamez 
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/d0b7ec2a-697c-46b1-bfd8-92159fd1ff2f)
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/930c11fd-fa54-4411-b7d0-63a88ea131ab)
