### ISSUE TITLE
Add sorting to list of mainCategories and sub categories in project detail page

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#1494]
@maryjaf commented on [Sun Sep 11 2022](https://github.com/Giveth/GIVeconomy/issues/720)

Sorting is alphabetical. First in Main Categories then in Sub Categories.

**Comment by mohammadranjbarz** [comment]
@MohammadPCh  @alireza-sharifpour  @RamRamez 
Do you want this just for `projectBySlug` query?

**Comment by alireza-sharifpour** [comment]
> 

We are using projectBySlug here, so, yes.

**Comment by mohammadranjbarz** [comment]
@alireza-sharifpour  @MoeNick 
@CarlosQ96  Fixed that in https://github.com/Giveth/impact-graph/commit/fcf74cda9ff1ef896ff0dbef0ed679ceaa72416f , now it's on staging

**Comment by maryjaf** [comment]
I tested on givfilter.vercel.app and main category and sub category are displayed in alphabetical order

**Comment by CarlosQ96** [comment]
Oh thanks for testing so fast! I mentioned it too in another issue 😄
