### ISSUE TITLE
User profile information is not displayed on the onboarding page(/onboard)

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#1499]
Even though the user profile information is completed, when we enter the link below
https://staging.giveth.io/onboard
It is displayed as below:
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/d6d6ee68-9b98-461a-b447-e566cf598c16)
It is better to display user's completed fields

**Comment by maryjaf** [comment]
@MoeNick plz check this issue

**Comment by MoeNick** [comment]
1- in case of incomplete profile, the available information should be filled if any of them is available
2- in case of a completed profile with no information: we should say that the user should not see this page. (,maybe they have the URL https://staging.giveth.io/onboard)

**Comment by maryjaf** [comment]
Thanks @RamRamez 
1-in case of a completed profile  (on https://staging.giveth.io/onboard)this page is shown:
![image](https://user-images.githubusercontent.com/111529185/192693045-fcb0a409-1944-4bc9-a564-e31479644155.png)
and when tap on GO TO DASHBOARD my account page is shown:
<img width="1394" alt="image" src="https://user-images.githubusercontent.com/111529185/192693558-e8353197-c6a7-4c95-8c5d-9ec29004e3b5.png">

2-in case of a in completed profile (on https://staging.giveth.io/onboard) this page is shown:

<img width="1426" alt="image" src="https://user-images.githubusercontent.com/111529185/192693177-8d680a51-4f79-4325-bdab-66de1662922f.png">

----
During the testing of this issue, I also noticed this problem
When I select the DO IT LATER option in the second step of uploading the photo in completing the profile, the information is saved
For this problem, it should be created separately issue or not?@RamRamez

**Comment by RamRamez** [comment]
> 

When user clicks on `do it later` on second step, it should skip uploading photo and finish the onboarding.

**Comment by maryjaf** [comment]
> > 
> 
> When user clicks on `do it later` on second step, it should skip uploading photo and finish the onboarding.
So it is ok?

**Comment by RamRamez** [comment]
> 

Yeah I think this is our flow
