### ISSUE TITLE
Wallet information is incorrect

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#150]
My wallet is showing incorrect information..
None of the numbers are reflecting the correct values.

![image](https://user-images.githubusercontent.com/74267818/157286463-1f6a8688-f348-4223-8c88-06aed24e98af.png)

And when I click on the ? next to the amount of GIV p/week, I get this:
![image](https://user-images.githubusercontent.com/74267818/157287112-9a8173ab-ae76-464f-929d-a2a56e5d7443.png)

**Comment by aminlatifi** [comment]
@WhyldWanderer What's your wallet address?

**Comment by aminlatifi** [comment]
@WhyldWanderer Are you sure your wallet is connected to the correct network? in case you are connected a any other network, Mainnet (Kovan) will be considered as default.

**Comment by aminlatifi** [comment]
@WhyldWanderer Have you connected your wallet address, in MetaMask I mean
