### ISSUE TITLE
Boost table unlock icon and percentage alignment 

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapps-v2#1507]
**Describe the bug**
The unlock icon and the percentage sign overlap for a short moment after I click edit boost on my account page.

**To Reproduce**
1. Go to My account
2. Click on Boosted projects tab
3. Click on edit boosting
4. See the error

**Expected behavior**
Have the final alignment at the beginning

<img width="222" alt="image" src="https://user-images.githubusercontent.com/5684607/190326331-8b749a91-dad8-4165-896d-f2f40f915cf3.png">

**Screenshots**
<img width="388" alt="image" src="https://user-images.githubusercontent.com/5684607/190325973-fbef67d3-3a3b-4831-a91d-a9732be5d659.png">

**Desktop (please complete the following information):**
 - OS: Macos
 - Browser Brave

**Comment by maryjaf** [comment]
In mobile view i can't see boosted projects in my account
 ![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/c8cc027d-fceb-4c5e-a65e-17a95d3121be)

**Comment by RamRamez** [comment]
@maryjaf I tested with MetaMask on android and it's working well. I can't take screen shot due to security policy from MetaMask.
Could you please test it again?

**Comment by maryjaf** [comment]
> @maryjaf I tested with MetaMask on android and it's working well. I can't take screen shot due to security policy from MetaMask. Could you please test it again?

I tested with MetaMask on iPhone and it happened again.

**Comment by divine-comedian** [comment]
tested on https://givpower.vercel.app/account?tab=boosted
firefox browser

the % does not overlap with the lock icon - looks very smooth! 

[Screencast from 30-09-22 10:24:49.webm](https://user-images.githubusercontent.com/67759413/193304069-2e0cb36b-6d1d-4a79-b6b1-fba7a97a71f4.webm)

this seems resolved on desktop, waiting to see if @maryjaf s issue is resolved and we can move this along.

**Comment by RamRamez** [comment]
> tested on https://givpower.vercel.app/account?tab=boosted firefox browser
> 
> the % does not overlap with the lock icon - looks very smooth!
> 
>  Screencast.from.30-09-22.10.24.49.webm 
> this seems resolved on desktop, waiting to see if @maryjaf s issue is resolved and we can move this along.

Can you test maryam's issue on your phone?

**Comment by divine-comedian** [comment]
@RamRamez 
![Screenshot_20220930-113721.png](https://user-images.githubusercontent.com/67759413/193317069-e2a2ed97-30a7-44b9-9fa6-f7806d17f579.png)

seems to be working 
google pixel 6
metamask browser
givpower.vercel.app

could it be an iphone issue?

**Comment by RamRamez** [comment]
> @RamRamez ![Screenshot_20220930-113721.png](https://user-images.githubusercontent.com/67759413/193317069-e2a2ed97-30a7-44b9-9fa6-f7806d17f579.png)
> 
> seems to be working google pixel 6 metamask browser givpower.vercel.app
> 
> could it be an iphone issue?

I don't know yet. @MoeNick Can you test this issue with your iphone?

**Comment by MoeNick** [comment]
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/7eb2e9f1-3ec6-41b4-8ca9-87ad557e814f)

I can see the tab.

**Comment by maryjaf** [comment]
Unfortunately, I still have the problem that I can't view the boosted projects with my iPhone
I don't know if the problem is related to the user or the phone model because it was correct for Amin and moenick
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/8209e59c-f5d1-411e-8352-0bd0b4b3fded)
@RamRamez @MohammadPCh

**Comment by MohammadPCh** [comment]
@maryjaf I will try to find it out. will call you.

**Comment by maryjaf** [comment]
This issue has been solved and now I can see my GIVpower tab  in mobile view
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/c6cc542e-2cf0-46f5-a1ac-4f6598055e6d)
