### ISSUE TITLE
Cannot scroll down when adding profile picture

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#151]
After uploading my profile picture, the save and edit buttons are cut off and I am unable to scroll down to press the button.

![image](https://user-images.githubusercontent.com/74267818/157287844-a3f11d8d-1f06-4294-b521-e50abbdbbef8.png)

**Comment by laurenluz** [comment]
I can scroll!

![image](https://user-images.githubusercontent.com/75490971/159956864-e4e560e3-4ef7-48ee-9a83-fc375c9df7f5.png)
