### ISSUE TITLE
GIVpower Staking & Locking - Mobile Responsiveness

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#1513]
testing on metamask browser 
https://givpower.vercel.app/givfarm
google pixel 6

quite a few mobile responsiveness things that could be improved - I will follow with some screenshots from my mobile device

![Screenshot_20220916-130833.png](https://user-images.githubusercontent.com/67759413/190704554-4f049775-ff75-4227-821a-773927f81ccf.png)

the size of the numbers across the modals could be enlarged

![Screenshot_20220916-125341.png](https://user-images.githubusercontent.com/67759413/190704637-e9897b8d-bd7d-4f18-bf9a-994bd6d5f440.png)

in the unstake modal we have lots of blank space on the right - looks like the screen size is off.

![Screenshot_20220916-125334.png](https://user-images.githubusercontent.com/67759413/190704744-61cbabb3-d48b-46bb-a2f4-e30889085d7e.png)

and in general there is a lot of blank space under the stake and unstake modals

![Screenshot_20220916-131409.png](https://user-images.githubusercontent.com/67759413/190706780-ee4ce36e-7ce1-42cb-8321-0f2c9449cf0e.png)

GIVstream modal is too wide for screen

![Screenshot_20220916-131422.png](https://user-images.githubusercontent.com/67759413/190706823-c9df8b52-75bc-431c-8e89-2f01fa644954.png)

APR modal is too big, lots of empty space and the text could be made bigger so it's easier to read

![Screenshot_20220916-132412.png](https://user-images.githubusercontent.com/67759413/190706965-e2625a99-baaa-49c2-a51e-b30e6d2218e3.png)

Locked GIV details summary the table headers are cut off and formatted funny. The text and numbers outside of the table look very small

![Screenshot_20220916-132502.png](https://user-images.githubusercontent.com/67759413/190707319-d3cdf7ce-bddc-4717-8744-ae192730bda8.png)

the bottom part of the locked giv details modal is cut off by the bottom of the screen, needs more padding on the bottom

**Comment by MoeNick** [comment]
@maryjaf jan pls test on mobile, it's for staking and licking and its important
@MohammadPCh pls consider it in giveeconomy version and update the vercell pls.

**Comment by laurenluz** [comment]
This can be tested on mobile here: https://giveconomy.vercel.app/givfarm @maryjaf

**Comment by maryjaf** [comment]
@MohammadPCh  plz check these pic
1-
![image](https://user-images.githubusercontent.com/111529185/192717855-edd54302-6935-4333-b477-135484ac0910.png)
2-
![image](https://user-images.githubusercontent.com/111529185/192717954-88faa64b-3c55-4c65-aa7b-9f98288e8df3.png)
3-
![image](https://user-images.githubusercontent.com/111529185/192718155-3ce7bda6-874f-46aa-b600-1a188d087d02.png)
I could not reproduce item 3

**Comment by maryjaf** [comment]
Sometimes, after I lock staked giv, a transaction completion notification is displayed (below pic)
![image](https://user-images.githubusercontent.com/111529185/192755469-1706b16a-4c5f-4296-a4eb-c134db9002f8.png)

But  "lock your token" loading remains
![image](https://user-images.githubusercontent.com/111529185/192755517-aa0c9554-dab2-458b-884c-6c21935cf83a.png)
@MohammadPCh

**Comment by maryjaf** [comment]
Do we have an update on the last three reported cases?@MohammadPCh

**Comment by aminlatifi** [comment]
> Do we have an update on the last three reported cases?@MohammadPCh

@maryjaf Yes, please test it again.

**Comment by maryjaf** [comment]
> > Do we have an update on the last three reported cases?@MohammadPCh
> 
> @maryjaf Yes, please test it again.

Thanks the above cases have been resolved.
