### ISSUE TITLE
Show correct rank number in project view givpower table 

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapps-v2#1518]
Attribute `rank` is added to the user project givpower API by https://github.com/Giveth/impact-graph/pull/645
So the frontend must use that value for ranking

<img width="916" alt="image" src="https://user-images.githubusercontent.com/5684607/190973561-7bea223a-86e7-4547-a19f-df17c63247cd.png">

#761

**Comment by maryjaf** [comment]
Plz check this scenario @aminlatifi 
I deleted boosting of "new organization2 " project in y list and this project is not showing in my boosted projects list
but in GivPower of project my name is shown in list of user who boosted this project and the round is over

**Comment by maryjaf** [comment]
It seems that above scenario is OK
The round time is 8 hours, didn't it change to half an hour? @aminlatifi

**Comment by aminlatifi** [comment]
> It seems that above scenario is OK The round time is 8 hours, didn't it change to half an hour? @aminlatifi

We haven't. 
@maryjaf told me after her message that it's not necessary any more.
