### ISSUE TITLE
Sign Wallet Modal  - Text fixes

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#152]
![image](https://user-images.githubusercontent.com/74267818/157293803-d35b6c3f-e743-4369-9e23-6e43d1fbde91.png)
Should say "You need to authorize your wallet to be able to use it on Giveth."

![image](https://user-images.githubusercontent.com/74267818/157294344-2ae0ef0c-f9fa-4b49-afcf-38cd76b62922.png)
Should say "Note: This is necessary to be able to donate to projects or receive funding."

**Comment by danelsuga** [comment]
I recommend shortening it to: 

« Note: This step is required for donating to projects or receiving funding. »
