### ISSUE TITLE
Notification Pop Up Copy (sorry dunno where this goes)?

### ISSUE THREAD

**Issue by tropicalmangos** [Giveth/giveth-dapps-v2#1525]
Here's the copy I wrote @MoeNick 

https://docs.google.com/spreadsheets/d/1VMsmF9oJEwf1JyNEAfWi2n2eYvG6ZtnkXKB_3Hv29x8/edit#gid=0

**Comment by MoeNick** [comment]
Hey @tropicalmangos 
I made some changes to some of them, worth to tale a look at it again:
https://docs.google.com/spreadsheets/d/1VMsmF9oJEwf1JyNEAfWi2n2eYvG6ZtnkXKB_3Hv29x8/edit#gid=0

**Comment by laurenluz** [comment]
a lot this copy has (hopefully) changed based on comments in the figma. Closing this because I'm seeing the spreadsheet is at this point very out of date.
