### ISSUE TITLE
Add Google Analytics (Tag Manger) to the website

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-dapps-v2#1539]
Hey team, 

Following up on [this issue](https://forum.giveth.io/t/should-we-add-more-tracking-to-the-website/805). 
I just had a call with @geleeroyale about adding Google Analytics to the website, and we had a long discussion (along with @clara-zi and @tropicalmangos). 

We decided to use Google Analytics (using Google Tag Manager), mainly because it works out of the box with what we need, and any other tracking platform (like Plausible for example), would need us to track all events separately (by adding separate JavaScript code), which would add a lot of man hours to future releases (every time we add a new feature or new design we would need to add more tracking codes). However, with Google Analytics, we just add one code and everything else can be done in the backend (using Autoevent tracking). 

So to action this, below is the code that we need to add to **all pages** (CC @MoeNick )

In the < head > tag (as high as possible):

```
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-K99CFQ7');</script>
<!-- End Google Tag Manager -->
```

& 
In the < body > tag (as high as possible): 

```
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-K99CFQ7"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
```

**Comment by alireza-sharifpour** [comment]
Could you please check it to see wether it works fine or not? @ahmadabugosh 
It's not deployed on main or staging yet.
The preview link for testing:
https://giveth-dapps-v2-git-1539-add-google-analytics-givethio.vercel.app/

**Comment by ahmadabugosh** [comment]
Thanks for this @alireza-sharifpour !  Actually, I think we can implement this with Segment (that we have installed on our site already), so let me try doing it from there first (and we may not have a need for adding the code manually). I'll update you on this!

**Comment by ahmadabugosh** [comment]
Hey @alireza-sharifpour, Actually for this we wanted to use Segment, but when I was looking at the setup, I think we may not have implemented it fully (when I inspect I don't see the code and also it doesn't seem to be passing all of the Segment events). 

It says we need to install the Analytics.js from Segment across the website on all pages (which I don't think we're doing)

Can you do that instead? (since we already have Segment set up it would be easier just to run everything through that). 


--------

_Copy the Segment snippet and paste it high in the <head> of your website. Learn more about setting up Segment in the [Analytics.js guide](https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/quickstart/)._

```
<script>
  !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","debug","page","once","off","on","addSourceMiddleware","addIntegrationMiddleware","setAnonymousId","addDestinationMiddleware"];analytics.factory=function(e){return function(){var t=Array.prototype.slice.call(arguments);t.unshift(e);analytics.push(t);return analytics}};for(var e=0;e<analytics.methods.length;e++){var key=analytics.methods[e];analytics[key]=analytics.factory(key)}analytics.load=function(key,e){var t=document.createElement("script");t.type="text/javascript";t.async=!0;t.src="https://cdn.segment.com/analytics.js/v1/" + key + "/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(t,n);analytics._loadOptions=e};analytics._writeKey="lvBWopQhDusIfdEr0l1w7oYxk4Stsjvk";;analytics.SNIPPET_VERSION="4.15.3";
  analytics.load("lvBWopQhDusIfdEr0l1w7oYxk4Stsjvk");
  analytics.page();
  }}();
</script>
```

**Comment by alireza-sharifpour** [comment]
> Hey @alireza-sharifpour thanks for following up!
> 
> For https://segment.com/nextjs-example/sources/nextjs that link doesn't open for me I think that's a private app someone created.
> 
> I think you also need the Analytics API write keys rights?
> 
> I don't think I can add anyone else to Segment (since we reached our user account limit), but I'll share my login credentials with you over Discord.

Thanks @ahmadabugosh, I added development and production keys and also implemented it on the front-end side and tested it and it works fine.
it's ready for review.

**Comment by ahmadabugosh** [comment]
Thanks @alireza-sharifpour! I tested it and it looks good. Let me know once it's live and I can check it in production too

**Comment by MoeNick** [comment]
If it's QAed we can merge it into production. Shall we @ahmadabugosh ?

**Comment by ahmadabugosh** [comment]
Let's do it!

**Comment by MoeNick** [comment]
It was not merged into staging, so I asked @alireza-sharifpour to do it after code reviewing by @MohammadPCh

**Comment by MohammadPCh** [comment]
It's on staging now :)
and we will have it on production, after er release a new version.
@ahmadabugosh @MoeNick
