### ISSUE TITLE
GIVpower page modifications for Staking/Locking

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapps-v2#1540]
@laurenluz @MoeNick 
I have upgraded the Garden unipool contract corresponding to the develop env. Now it supports locking functionalities.
The start time equals token distro start time and the duration is 14 days.

I created the subgraph based on this new configuration, it's been deployed here https://thegraph.com/hosted-service/subgraph/aminlatifi/giveconomy-xdai-deployment-seven?selected=logs

What remain:
- [ ] Merge givpower to giveconomy branch and configure it to use the above subgraph temporarily. We can use develop default subgraph after this [PR](https://github.com/Giveth/giveconomy-subgraph/pull/30/files) is merged @MohammadPCh 
- [ ] Set up an unlock bot for develop env @aminlatifi

**Comment by MoeNick** [comment]
This is the preview before merging to giveconomy branch
https://giveth-dapps-v2-git-givpower-ready-to-merge-givethio.vercel.app/

**Comment by MoeNick** [comment]
@maryjaf this one also reported by @divine-comedian 
https://github.com/Giveth/giveth-dapps-v2/issues/1512

**Comment by divine-comedian** [comment]
on the GIVpower page did we decide to remove the greyed out boost projects?
https://giveth-dapps-v2-git-givpower-ready-to-merge-givethio.vercel.app/givpower

![image](https://user-images.githubusercontent.com/67759413/192383645-f43dc6ae-9b03-4dd1-bece-fe65d37ef690.png)

If so I would suggest adding some padding to the bottom of the element, otherwise it looks a bit squished. 
![image](https://user-images.githubusercontent.com/67759413/192383811-534f29ee-3936-4446-96d2-071314468053.png)

**Comment by divine-comedian** [comment]
on this page the two `?`s are aligned differently - one is centered and the other is top-aligned

another thing - the table doesn't seem to fit on one page - I have to scroll side ways to see the information. on the figma spec this should fit onto one page. 


![image](https://user-images.githubusercontent.com/67759413/192385416-5cb08665-3946-4482-81ca-8e822bf03b63.png)


https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=10527%3A194487

**Comment by RamRamez** [comment]
> w, without scroll

Iremoved

**Comment by laurenluz** [comment]
> on the GIVpower page did we decide to remove the greyed out boost projects? https://giveth-dapps-v2-git-givpower-ready-to-merge-givethio.vercel.app/givpower
> 
> ![image](https://user-images.githubusercontent.com/67759413/192383645-f43dc6ae-9b03-4dd1-bece-fe65d37ef690.png)
> 
> If so I would suggest adding some padding to the bottom of the element, otherwise it looks a bit squished. ![image](https://user-images.githubusercontent.com/67759413/192383811-534f29ee-3936-4446-96d2-071314468053.png)

@RamRamez can you readd this button as well? it should be greyed out "Boost Projects"

**Comment by laurenluz** [comment]
I would love to see a few more changes here actually:

- [ ] Can we please change the "For Projects" Section to read:

"Soon: Fire up your community to use GIVpower & help improve your rank.
The higher your rank, the more GIVbacks your donors will receive.
Top-ranked projects will eventually get funding from the Giveth Matching Pool."

Button: "Coming Soon" (*with no link*)

![image](https://user-images.githubusercontent.com/75490971/192642740-4f953795-b8df-4f05-ba22-8375da650a8b.png)

- [ ] Also, text fix for "For GIVers"

1: "Soon: Donate to top-ranked projects to get extra GIVbacks."
2: Button: "Stake GIV" (link to https://giveth.io/givfarm)

![image](https://user-images.githubusercontent.com/75490971/192644201-151ef801-6158-45f3-827f-0879de15ee5a.png)

- [ ] And last, re-add the button to the top, where it will show the GIVpower, but make it say "Get more GIVpower", and link to https://giveth.io/givfarm
![image](https://user-images.githubusercontent.com/75490971/192645187-9f211b73-27d4-40fb-a564-efe8d401ab2e.png)

**Comment by RamRamez** [comment]
@divine-comedian comments are fixed on PR #1562 and @laurenluz comments are fixed on PR #1568

**Comment by divine-comedian** [comment]
@RamRamez Let me know when #1568 is merged and we can test again!

**Comment by RamRamez** [comment]
> @RamRamez Let me know when #1568 is merged and we can test again!

It's merged. You can test it on [https://giveconomy.vercel.app](https://giveconomy.vercel.app)

**Comment by laurenluz** [comment]
tested, it all looks great!
