### ISSUE TITLE
 Modify the start and ends dates on GIVbacks page for Tuesdays

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1545]
GIVbacks round 20 should run from September 16 to October 4

![image](https://user-images.githubusercontent.com/75490971/192306519-8a90f2b5-03d1-44c7-98b2-364b5e13ed70.png)

GIVbacks round 21 should run from October 4 to October 18

**Comment by aminlatifi** [comment]
#1556 is merged, after round 20 finishes we must create another PR with simple round offset in the config.

**Comment by MohammadPCh** [comment]
@laurenluz it's merged, so you can test it on https://giveconomy.vercel.app/givbacks and if you approve it we can have a version on production.

**Comment by MohammadPCh** [comment]
@aminlatifi Thanks for reviewing, yeah, I totally agree with you, I will fix it after this round.

**Comment by laurenluz** [comment]
do we need another issue for that @MohammadPCh ? Or just keep this one?

**Comment by laurenluz** [comment]
it's on production!
