### ISSUE TITLE
Create new Honeyswap pool

### ISSUE THREAD

**Issue by Cotabe** [Giveth/giveth-dapps-v2#1548]

**Comment by Cotabe** [comment]
@aminlatifi @MoeNick @laurenluz 

Who would be the best person to do this?

Also, I'm talking with @willyogo to see what's best create a new FOX/XDAI pool or reward the FOX/WXDAI that is already active on Honeyswap

**Comment by laurenluz** [comment]
@aminlatifi is our guy here :)

**Comment by MoeNick** [comment]
@aminlatifi please help us how to QA it.
