### ISSUE TITLE
Deploy smart contract(s)

### ISSUE THREAD

**Issue by Cotabe** [Giveth/giveth-dapps-v2#1549]

**Comment by Cotabe** [comment]
@aminlatifi @MoeNick @laurenluz 

You probably know better than me what will this entails and who would be the best person to perform it.

**Comment by aminlatifi** [comment]
## Test Deployment
All information can be found in this [doc](https://www.notion.so/giveth/a22672a17cee44b2a2dc03f58691ffe0?v=dcccc8d6642040a18c1585295ab32c04)

FOX (TestFOX): `0x18cE354571ba71bC7b3d633b254954C5A9cfC195`
testDai: `0x97c4dD5cE204b8c1F2f3B8fBfBBDC771d867d18c`
#### LP token Honeyswap(testFox/testDAI)
Address:	`0x0714A2fE9574F591a4ed3fD03b63714e8681fBb7`
Provide liquidity: https://app.honeyswap.org/#/add/0x18cE354571ba71bC7b3d633b254954C5A9cfC195/0x97c4dD5cE204b8c1F2f3B8fBfBBDC771d867d18c

#### Unipool (testFOX/testDAI)
Address: `0x93c40bCA6a854B2190a054136a316C4Df7f89f10`

**Comment by MoeNick** [comment]
Hey @KurtMerbeth I’m using Zenhub in GitHub, [click this link](https://app.zenhub.com/workspaces/all-devs-61644589b92edf0016f6999c/board) to join my workspace and see other features available in GitHub or [download the Zenhub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [Zenhub](https://www.zenhub.com)_

**Comment by aminlatifi** [comment]
For production


LP Address (FOX/WXDAI): 0xc22313fd39f7d4d73a89558f9e8e444c86464bac


FOX/WXDAI Unipool   0x9A333AD00868472c0314F76DB8dA305B83890129






FOX/WXDAI Unipool | 0x9A333AD00868472c0314F76DB8dA305B83890129
-- | --

**Comment by aminlatifi** [comment]
BTW, Everything is documented here https://www.notion.so/giveth/FOX-Regen-Farm-7796408fb3b64978bca2d93b30fe1f9f

**Comment by KurtMerbeth** [comment]
@aminlatifi the deployment looks good to me
