### ISSUE TITLE
Complete your profile text fixes

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#155]
![image](https://user-images.githubusercontent.com/74267818/157296706-347c22e9-1ac7-49b5-a026-7459208d1991.png)

Should say: 
"This is what you look like right now... strange right!?
Upload a photo that represents who you are."

**Comment by laurenluz** [comment]
I edited this fix a little

**Comment by danelsuga** [comment]
This is actually still not correct. 
It reads, "This is how you look like right now, strange! right?"
It should read: "This is how you look right now! Strange, right?"

In English, you do not put "how" with "look like". It is either "how you look", or "what you look like".

Also, "strange" and "right" are part of the same question. "Strange" must be separated from the previous sentence. It is actually the content of the question "right?" (and so requires a comma).
