### ISSUE TITLE
Prepare the front end for the FOX/XDAI farm

### ISSUE THREAD

**Issue by Cotabe** [Giveth/giveth-dapps-v2#1551]
We need to dev up the frontend cards for the new FOX/XDAI farm. It would be ideal to have it by October, 2nd (the day the FOX/HNY farm runs out of rewards, I say let's aim for making it happen. The good news is that we have most of the information already on the FOX/HNY farm.

Here is an image with the things that we need to change.

![FOX new front end](https://user-images.githubusercontent.com/101358184/192401914-816d4cd0-ecd1-4df0-8e88-a42e9407c19d.PNG)

We need to:

- [ ]  Set up this farm so that it's visible only when the user is connected to Gnosischain
- [ ] Exchange should be Uniswap v2 (not honeyswap)
- [ ] Logos should show FOX & XDAI.
- [ ] Tokens should say FOX on the same places FOX/HNY and XDAI instead of HNY.
- [ ] When you click on the card keep the description. "ShapeShift is the free and open-source one-stop-shop for cross-chain DeFi. Buy, sell, send, receive, trade, and earn yield on your crypto across a growing number of protocols and chains with no added fees ever. FOX is the governance token of the ShapeShift DAO."
- [ ]  "Learn more" should go to: https://shapeshift.com/
- [ ]  "Provide liquidity" should link to FOX / XDAI pool on honeyswap*
*It is likely that we use the WXDAI pool that they already have. I'm waiting on Willy to confirm this.
- [ ] FOXstream. We should keep the FOXstream that liquidity providers already have from the FOX/HNY farm. Let me know if I'm missing something here.

FYI @MoeNick @aminlatifi @laurenluz @mateodaza @MohammadPCh @mosaeedi

**Comment by MohammadPCh** [comment]
@Cotabe Thanks,
do we need to change the current farm or it's a new farm? also, we need this information too:
- tokenDistroAddress
- rewardTokenAddress:
- tokenAddressOnUniswapV2
- POOL_ADDRESS
- LM_ADDRESS
- start time
- provideLiquidityLink
@aminlatifi can help us.

**Comment by aminlatifi** [comment]
> @Cotabe Thanks, do we need to change the current farm or it's a new farm? also, we need this information too:
> 
> * tokenDistroAddress
> * rewardTokenAddress:
> * tokenAddressOnUniswapV2
> * POOL_ADDRESS
> * LM_ADDRESS
> * start time
> * provideLiquidityLink
>   @aminlatifi can help us.

The values will be the same as fox/honey farm, except pool address and lm address. I have deployed for test env so far and put info here https://github.com/Giveth/giveth-dapps-v2/issues/1549#issuecomment-1259176806

**Comment by Cotabe** [comment]
Thanks @aminlatifi 

Anything else blocking you @MohammadPCh ?

**Comment by mosaeedi** [comment]
![Screen Shot 2022-09-29 at 3 22 38 PM](https://user-images.githubusercontent.com/13708322/193030116-408eda78-776a-4848-8f8b-a7cf1ee37b02.png)

**Comment by mosaeedi** [comment]
## Coming soon
---
![Screen Shot 2022-09-29 at 3 24 55 PM](https://user-images.githubusercontent.com/13708322/193030536-fada7b82-e826-454a-b138-ab085a9ac78a.png)

**Comment by mosaeedi** [comment]
## Design resource

RegenFarm page on Figma -> [https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=13925%3A253772](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=13925%3A253772)
