### ISSUE TITLE
Prepare front end to archive HNY/FOX pool after 2 weeks

### ISSUE THREAD

**Issue by Cotabe** [Giveth/giveth-dapps-v2#1552]
The HNY/FOC farm should be archived 2 weeks after the end of the rewards. This is October, 16th.

Is there anything else I'm missing to phase out this farm?

@MoeNick @aminlatifi @mateodaza @MohammadPCh @laurenluz

**Comment by laurenluz** [comment]
@MohammadPCh will this automatically archive in a couple of weeks? I think we should archive on Oct 31

**Comment by MohammadPCh** [comment]
@laurenluz  Thanks for the reminder, I left a PR for it.

**Comment by laurenluz** [comment]
looks good!
