### ISSUE TITLE
Comms for the new FOX/xDAI Regen Farm

### ISSUE THREAD

**Issue by Cotabe** [Giveth/giveth-dapps-v2#1554]
Here are a few ideas of comms:

- [ ] Teaser tweet (09-27-22 ish) - "He are cooking a FOXprise for you... coming soon @shapeshift "
- [ ] Countdown tweet (09-29-22 ish) - draft a tweet to send the day the countdown goes live
- [ ] Launching day tweet (10-02-22 ish) - draft a tweet to send the day of the launch
- [ ] Retweet FOX comms about it

FYI @c0ric0ri @laurenluz @oyealmond

**Comment by laurenluz** [comment]
Looks good! I think we might be a bit too packed this week for the teaser tweet though, we can try.

**Comment by laurenluz** [comment]
@Cotabe also I think this issue would be better in the giveth planning repo, and just link it in the epic, then Cori has an easier time keeping track of it too.

**Comment by c0ric0ri** [comment]
Issue moved to [Giveth/giveth-planning #894](https://github.com/Giveth/giveth-planning/issues/894) via [**Zenhub**](https://www.zenhub.com/)
