### ISSUE TITLE
Frontend: Adding "Accept Funds on Gnosis" filter to givfilter

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#1558]

**Comment by MoeNick** [comment]
@alireza-sharifpour 
@mohammadranjbarz has just updated the backedn, I assumed it;s ready for test, if it;s not pls let us know.

**Comment by alireza-sharifpour** [comment]
> @alireza-sharifpour @mohammadranjbarz has just updated the backedn, I assumed it;s ready for test, if it;s not pls let us know.

Yes, it can be tested on:
https://givfilter.vercel.app/projects
@MoeNick @maryjaf
