### ISSUE TITLE
SEO - include text in the body under the main banner. 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#1559]
originally from this comment: https://github.com/Giveth/giveth-planning/issues/865#issuecomment-1252435325

Can you add a section for text below the image, so we can have content for SEO purposes (just one small paragraph ex.
"Donate crypto directly to Economics and Infrastructure projects on Giveth! Support projects and get rewarded for giving with zero added fees."

- [ ] Design amendments by @mosaeedi 

Text suggestions by @ahmadabugosh under these main categories are required:

- [x] Art & Culture
- [x] Community
- [x] Economic and Infrastructure
- [x] Education
- [x] Equality
- [x] Finance
- [x] Health & Wellness
- [x] Nature
- [x] NGO
- [x] Technology

**Comment by MoeNick** [comment]
wow! so quick, thanks! @ahmadabugosh

**Comment by mosaeedi** [comment]
![Screen Shot 2022-09-28 at 3 45 36 PM](https://user-images.githubusercontent.com/13708322/192781917-ed0d6de0-8bdb-4494-8576-df4fd4d2553e.png)

**Comment by mosaeedi** [comment]
@ahmadabugosh 
I added a new section between the project cards, the "Zero added fees!" white section, you can have a title and a subheading to add anything you want.

Also, did you notice there is a subheading under the main category title? below the "Environment & energy" it's a dynamic text holder that you can use for each main category!

**Comment by mosaeedi** [comment]
Here is the link to Figma file -> [link to Figma](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=13866%3A248323)

**Comment by mosaeedi** [comment]
cc @MoeNick

**Comment by mosaeedi** [comment]
The white row, between the product, should appear just after the first row!

**Comment by MoeNick** [comment]
What are the use-cases in filtering or sorting? this shows only on main category filters? 
what if the main category don't have enough projects? one row for example? 
@mosaeedi

**Comment by ahmadabugosh** [comment]
Hey @mosaeedi thanks for this! 

A few points to follow up on:

1) Would the text I sent for the description fit on the top header image as a subtitle? If not you suggest do you suggest we change it to something else? If it does fit, maybe we don't need the white row at all. 

2) Maybe we should add the white row to the bottom of the page under all projects (below "Load More")? That might be better to not affect the focus on the projects + potential issues with filtering and sorting that MoeNick mentioned. 

3) I think we wouldn't want "Zero added fees!" as the title on the white row (if we keep it). I would probably use something like "Donate crypto to verified projects and [get rewarded](https://docs.giveth.io/giveconomy/givbacks/) for giving!" and then maybe "get rewarded" links to the docs where we talk about GIVbacks (opening in a new tab). 

@laurenluz @WhyldWanderer wdyt?

**Comment by mosaeedi** [comment]
1. if the text is dynamic and related to the current category that we are showing! why not, we can show it there, but I think you just want to show a fixed text, unrelated to the category, so I say it's a waste of space if we use that for just a simple and fixed slogan!

2. the white row is going to be visible just on the main categories and by filtering and sorting it can just disappear. (Please note that by filtering and sorting URL will change and it won't be visible anymore to Google, so it won't be an issue to remove it then.)
Also, from the UX perspective, I added a minimal and clear white row to make sure we won't lose the user focus!

3. "Zero added fee" is just a dummy title, you can write whatever copy you want to show there.

**Comment by ahmadabugosh** [comment]
Yes, please! @MoeNick @mosaeedi 

I edited the text to make it shorter for each category on [column E](https://docs.google.com/spreadsheets/d/1DAB5UHCYO4hkw_RLRtz8DLXpGduVDRMHfiW-71H0m8o/edit#gid=0) here for the subtitles on the category pages. 

For the white row text, can you please make it be:

**Donate Crypto Directly** 
Get rewarded for giving to public goods projects with zero added fees.

**Comment by MoeNick** [comment]
@MohammadPCh I assigned it to @alireza-sharifpour , if you have any suggestions on implementation pls let him know.
