### ISSUE TITLE
Submission guidelines modal - text fixes

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#156]
![image](https://user-images.githubusercontent.com/74267818/157297871-240128ce-4b36-4ccc-bff4-d1a137489a3f.png)

Should say "Clear project description explaining who the organization is and what you will do with the funds."

![image](https://user-images.githubusercontent.com/74267818/157297850-15fcbb2e-71b6-4acd-8184-4962ce9eb239.png)

Should say "(Optional) A link to the repository of open-source projects."

**Comment by WhyldWanderer** [comment]
Links are not working...
![image](https://user-images.githubusercontent.com/74267818/157298466-813789e8-555a-4126-be5b-f60cb34b2cb9.png)

They should open in a new tab.

**Comment by MoeNick** [comment]
pls let me know when it;s fixed.

**Comment by RamRamez** [comment]
Resolved in PR #186
