### ISSUE TITLE
Lock detail modal table improvement

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapps-v2#1561]
**What problem is this design solving? Why is it necessary?**
The GIVpower locked token details modal table can be narrower. There is some unused space and redundant texts. 
![image](https://user-images.githubusercontent.com/5684607/192567335-e15dfc79-ceb2-4a05-a212-e3802a19f629.png)

In the above picture, there is unused space between APR and Unlock Date. Actually, when the user opens the modal the Unlock Detail column is hidden and the user must scroll horizontally to see it. Not only it's an important column and must be seen in the first view, but also the horizontal scroller is not visible to me and I didn't know it exists until @alireza-sharifpour told me.

Another issue is redundant texts 
![image](https://user-images.githubusercontent.com/5684607/192568168-bffecb92-9b3f-4956-9174-72530944d449.png)
 In the header
 `GIV amount`  can be `Amount` -> GIV is visible above and repeated enough
`Rounds locked for` can be `Locked for` -> In the data `Round` word exists
`Multplier` and `APR` can be merged and their data can be shown in one column like `1.41(32.9%)`

**Comment by laurenluz** [comment]
Cherik was working on these ideas in the other issue, so I just copied your comment there Amin, with some adjiustments. will close this.
