### ISSUE TITLE
GIVpower Test branch - APR is 0

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1565]
@aminlatifi @MohammadPCh 

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/5a057d1f-70aa-4a6b-b689-4ac5147f55ed)

Did the rewards run out on GIVpower test deployment already? Or is this a bug?

**Comment by aminlatifi** [comment]
@laurenluz Yes, I replenished it.
