### ISSUE TITLE
Re-occurring donations 

### ISSUE THREAD

**Issue by tropicalmangos** [Giveth/giveth-dapps-v2#1566]
@MoeNick dunno if it's possible from a technical point of view so that's why I'm checking with you....but have we thought about enabling re-occuring donations as part of the process? 

Like for example, set a fixed amount to donate per month say $5/ $10/ $50/ $500 (enter custom amount)?

Also this is more of an idea/ suggestion, is there somewhere better to post this or is this the right way?

**Comment by laurenluz** [comment]
oh I did it already. for the future:

![image](https://user-images.githubusercontent.com/75490971/193124665-40d0f21b-1e0c-4936-846b-ac06b2258446.png)
