### ISSUE TITLE
Make design for the archive FOX/HNY pool

### ISSUE THREAD

**Issue by Cotabe** [Giveth/giveth-dapps-v2#1567]
I would suggest that it looks like this.

![FOX archived FOXHNY](https://user-images.githubusercontent.com/101358184/192639051-45dec11c-ebdb-4401-91b3-c072c2729745.PNG)

With the same modal of attention farmers.

To be activated with the same button than all other archived farms

And be situated here:

![Archived regen farms](https://user-images.githubusercontent.com/101358184/192639764-b4916819-fb8d-429c-b943-2d85991512a9.PNG)

**Comment by MoeNick** [comment]
hey @mosaeedi no news is not gong to be a good news :)

**Comment by mosaeedi** [comment]
I'm pretty sure that I posted the design for the archived pool before, but I can't find that issue right now!

So here it is, [Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=13925%3A253772)

**Comment by MoeNick** [comment]
@Cotabe here you are :)
