### ISSUE TITLE
Missing text in FAQ page title

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-dapps-v2#158]
on FAQ page, https://giveth-dapps-v2.vercel.app/faq

![image](https://user-images.githubusercontent.com/100084867/157311881-379e303c-dd97-4b84-823b-24be287ea30a.png)

the selected section on picture - text is not valid.

**Comment by MoeNick** [comment]
just asked @WhyldWanderer to provide some content for this page.

**Comment by laurenluz** [comment]
tbh this shouldn't say "How can we help you?"

I would change the title to

**"Frequently Asked Questions"**

and fully remove the subtext.
