### ISSUE TITLE
Add GIVpower banner to DApp Oct 4 w. GIVpower launch

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1582]
Hey @MohammadPCh @mateodaza 

I would love to see this banner go live when we launch staking & locking w/ GIVpower and have it link to to the GIVpower page (i.e. https://givpower.vercel.app/givpower) when the user clicks.

I think we can make it similar to the banner we used w/ previous gitcoin grants rounds. @mateodaza knows.

Can we do it?

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/85593a5d-5b7c-4b56-bda1-a0b2b426bc35)

Design in https://github.com/Giveth/giveth-planning/issues/892

cc: @MoeNick

**Comment by mateodaza** [comment]
I can grab this :) @laurenluz

**Comment by laurenluz** [comment]
oh nooo, I just realized I made a typo on it - should be "multiply" not multiple 🤦‍♀️ @mateodaza or @RamRamez can you fix it?

**Comment by mateodaza** [comment]
@laurenluz I'm using the image that @rodricastillo9013 made. Let's ask him to fix the typo and I'll change it

**Comment by laurenluz** [comment]
@mateodaza ok, he's on it!

**Comment by rodricastillo9013** [comment]
<img width="1440" alt="GivPower Banner" src="https://user-images.githubusercontent.com/61791380/193312324-3776a5cc-458e-4ab0-881f-cec26c199f41.png">
done! @mateodaza @laurenluz

**Comment by mateodaza** [comment]
@rodricastillo9013 now we missed a r in rewards 🙈

**Comment by laurenluz** [comment]
@mateodaza sorry 'bout that

![image](https://user-images.githubusercontent.com/75490971/193332348-a4aec001-1eb1-4466-ae06-bb19ba54192f.png)

**Comment by laurenluz** [comment]
Tested on GIVeconomy deployment, looks great!

![image](https://user-images.githubusercontent.com/75490971/193654592-335f1f05-1068-4033-a17e-17ba9ab65306.png)
