### ISSUE TITLE
GIVpower - we need to decide how long we will run this incentives program

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1585]
We allocated 7 million GIV to run GIVpower locking for 6 months.

Throughout that period, people can lock for up to 1 year.

So we are committing to running incentives essentially for 1.5 years.

Unless we decide to make it so that... part way through the 6 months etc etc you can lock for less than 26 rounds.

**Comment by divine-comedian** [comment]
These rewards are set to expire very soon!

**Comment by laurenluz** [comment]
We went live with staking & locking on Oct 4, 2022 - so the rewards should end around April 18. I think we should make a vote to extend it, and a forum post... but I think I can easily get that up after eth Denver and we go from there.

Announcement Tweet: https://twitter.com/Givethio/status/1577340015285354496
GIVfarm dates Notion: https://www.notion.so/GIVfarm-Dates-a9c623a1b3cd48ad8909d6e9826cf988

**Comment by laurenluz** [comment]
Request for additional rewards (and related snapshot vote) is here: https://forum.giveth.io/t/givpower-summary-requesting-giv-for-incentives-update-q2-2023/719/22

**Comment by laurenluz** [comment]
looks like end of Oct / early Nov we'll be running out of rewards. I think we should extend the program, and I can make a forum post to request GIV. pinging some folks for advice process

**Comment by divine-comedian** [comment]
@laurenluz - is this issue still relevant?
