### ISSUE TITLE
GIVpower - hide "locked GIV details" link on back of card

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1588]
Right now, the locked GIV details modal has nothing to do with GIVpower. We should hide it from here because it is confusing.

Let's comment it out thought, because if we make an update to the modal, I think we may want to re-add it to the back of the card later.

![image](https://user-images.githubusercontent.com/75490971/193136017-c3941542-f9a2-431d-8c91-5e4d80e253c3.png)

**Comment by laurenluz** [comment]
@mateodaza @MohammadPCh @RamRamez - can one of you take this?

**Comment by mateodaza** [comment]
> @mateodaza @MohammadPCh @RamRamez - can one of you take this?

On it!
