### ISSUE TITLE
GIVpower boosting deployment - GIVpower text fixes

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1593]
- [ ] "Coming Soon" should be "Boost Projects" and link to the Giveth projects page
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/72f1859d-cb86-42ca-a67f-6b8119356778)
 
- [ ] "Coming Soon" should be "Get GIVpower" and link to the GIVfarm

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/c13be587-2e4d-4a3a-8b30-a269ee442cc2)

- [x] The "For Projects" Section text should be changed a little, as follows:

Fire up your community to get more boosts & improve your rank.
The higher your rank, the more GIVbacks your donors receive.
Top-ranked projects will eventually get funding from the Giveth Matching Pool.

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/2f6a3429-c878-4746-9e88-aeef078c79de)

- [x] at the top, text fix:
Support verified projects using “Boost”. Projects backed by GIVpower will benefit from more GIVbacks for their donors and, eventually, matching funds.

![image](https://user-images.githubusercontent.com/75490971/193307255-d179c947-9332-465f-9ef5-001c32e14e50.png)

**Comment by divine-comedian** [comment]
I made the text changes in https://github.com/Giveth/giveth-dapps-v2/commit/5a51f9f56a2f611b19f564b0f9b3849bc539d7c7

@MohammadPCh already wrote the code and will uncomment the sections marked `coming soon` with the right text and link.

I'll leave this issue as is for a reminder.
