### ISSUE TITLE
GIVpower - staking & locking deployment text fix on GIVpower page

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1594]
Quick text fix here on the GIVpower page:

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/6de9bee5-dcbe-4da9-b7fb-deed336e571b)

"Support verified projects using “Boost”. Projects backed by GIVpower will benefit from more GIVbacks for their donors and, eventually, matching funds."

**Comment by divine-comedian** [comment]
testing on https://giveconomy.vercel.app/givpower

looks like this text already changed again - 

![image](https://user-images.githubusercontent.com/67759413/203170174-02dbf32e-ba30-42ad-8116-b53272032fa0.png)

> Use your GIVpower to _boost_ verified projects to improve their project ranking. Donors to higher ranked projects will get more GIV from our GIVbacks program.

@laurenluz can you confirm this is the text you are expecting?

**Comment by laurenluz** [comment]
yeah, removed matching because who knows when it's coming. I'm sorry I'm seeing a lot of old issues & redundant issues, I need to clean up the board. this shoul dhave been closed.
