### ISSUE TITLE
GIVpower - when the user has no GIV available to lock, they should see a different modal/not be able to get to the lock modal

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1607]
When the user has locked all their staked GIV, they should not be able to get to the lockup modal. (from feedback from @maryjaf testing on production)

@MohammadPCh 

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/9b09b89a-490b-4043-8427-11e5a20be4f3)

**Comment by laurenluz** [comment]
@MohammadPCh I think in this case, the "increase your reward" button should be greyed out.

**Comment by maryjaf** [comment]
Is this change on giveconomy.vercel.app?
I checked but didn't see any change. @MohammadPCh

**Comment by MoeNick** [comment]
@MohammadPCh @alireza-sharifpour 
It has been merged into GIVeconomy branch? if yes, seems @maryjaf can't confirm it, would you pls take a look?

**Comment by MohammadPCh** [comment]
@maryjaf @MoeNick let me check it :)

**Comment by MohammadPCh** [comment]
Thanks @maryjaf , I left a new PR :)

**Comment by maryjaf** [comment]
I tested it, if the available GIVE is 0, the"increase your reward " button is disabled
But the un-stake is active, Is this the expected result? @MohammadPCh @laurenluz 
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/1182b251-ae75-4556-8d03-7d8dfe8b6500)

**Comment by MohammadPCh** [comment]
@maryjaf nice catch :)
I fixed it in another PR and let you know when it merged :)

**Comment by MohammadPCh** [comment]
@maryjaf  please check the un-stake button

**Comment by maryjaf** [comment]
> @maryjaf please check the un-stake button

Thanks @MohammadPCh 
I checked and it passsed.
<img width="509" alt="image" src="https://user-images.githubusercontent.com/111529185/194897834-6cd2686a-7300-40b6-a954-7ef5d3e26cd2.png">

**Comment by MohammadPCh** [comment]
Finally :smile: 
Thanks @maryjaf
