### ISSUE TITLE
GIVpower - locked GIV tooltip is really crowded

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1608]
@MohammadPCh testing on production

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/d0e4c79b-0efa-4050-8ba6-aad2951df1d5)

**Comment by maryjaf** [comment]
<img width="737" alt="image" src="https://user-images.githubusercontent.com/111529185/195092726-e8816760-bf1c-4561-ba02-7e4acb1174b6.png">
Thanks @MohammadPCh 
It has been resolved.
