### ISSUE TITLE
Add newsletter subscription to the join page.

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#161]
Can we put somethings on the join page that allows users to subscribe to our newsletter?

**Comment by MoeNick** [comment]
@mosaeedi @Tosinolawale 
Would you pls provide some design guideline how we can have newsletter subscription in join us page?

**Comment by Tosinolawale** [comment]
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=7117%3A150623
@MoeNick @mosaeedi @Cotabe  @WhyldWanderer Check that out.

**Comment by MoeNick** [comment]
@Tosinolawale Pleas include successful subscription, client-side errors, etc. should it be the same as we have right now in home page?

**Comment by Tosinolawale** [comment]
> @Tosinolawale Pleas include successful subscription, client-side errors, etc. should it be the same as we have right now in home page?

Yeah. It should be the same as we have in the Home page. I have included it on the Join Page too.

**Comment by WhyldWanderer** [comment]
This is live on production now! 
![image](https://user-images.githubusercontent.com/74267818/173645840-77cbdd85-70da-4507-96af-4c88b561b4fe.png)

Thank you!

**Comment by MoeNick** [comment]
We have to change it to Revue and its implemented now on staging. Due to Ahmad related to #850
