### ISSUE TITLE
Integrate i18n to frontend

### ISSUE THREAD

**Issue by mateodaza** [Giveth/giveth-dapps-v2#1613]
- [x] Add language provider to whole dApp
- [x] Move every static text to a i18n translation on the frontend (EN / SP) (some may still be missing)
- [x] Spanish translation (going for testing with coverage at over 70%)
- [x] Dynamic translations for project descriptions (will be solved on [this issue](https://github.com/Giveth/giveth-dapps-v2/issues/1697))
- [x] Add footer for changing language as desired. Here's the [resource](https://github.com/Giveth/giveth-dapps-v2/issues/1614)
- [ ] Check backend messages translations with @CarlosQ96

**Comment by divine-comedian** [comment]
how can this issue be tested?

**Comment by divine-comedian** [comment]
> > how can this issue be tested?
> 
> go to any route on https://staging.giveth.io/es, although it's not ready to be tested as we're still missing strings on the giveconomy and a big percentage of translations

okay - should we keep this in UAT or back somewhere else?

**Comment by MoeNick** [comment]
@mateodaza would you please let us know what to do with this issue?

**Comment by mateodaza** [comment]
@MoeNick updated the comment with missing parts. sent back to in progress. will be sent to UAT when spanish coverage is at 100% by the translation team

**Comment by mateodaza** [comment]
Working on the last 3 steps to release a testing deployment branch

> * [ ]  Dynamic translations for project descriptions
> * [ ]  Add footer for changing language as desired. Here's the [resource](https://github.com/Giveth/giveth-dapps-v2/issues/1614)
> * [ ]  Check backend messages translations with @CarlosQ96
