### ISSUE TITLE
Change language config UX design

### ISSUE THREAD

**Issue by mateodaza** [Giveth/giveth-dapps-v2#1614]
### (>1280 & <1439)

** Footer / Light mode **
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19618%3A248554&t=NH2PjA7i86USVYu1-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19618%3A248554&t=NH2PjA7i86USVYu1-4)

** Footer/ Dark mode **
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19618%3A248798&t=NH2PjA7i86USVYu1-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19618%3A248798&t=NH2PjA7i86USVYu1-4)

** Switch language modal / Light mode**
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19618%3A249458&t=NH2PjA7i86USVYu1-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19618%3A249458&t=NH2PjA7i86USVYu1-4)

** Switch language modal / Dark mode**
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19618%3A249536&t=NH2PjA7i86USVYu1-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19618%3A249536&t=NH2PjA7i86USVYu1-4)

---

### (>768 & <1024)

** Footer / Light mode **
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19618%3A249141&t=NH2PjA7i86USVYu1-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19618%3A249141&t=NH2PjA7i86USVYu1-4)

** Footer / Dark mode **
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19620%3A248010&t=NH2PjA7i86USVYu1-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19620%3A248010&t=NH2PjA7i86USVYu1-4)

---

### ( <768)
** Footer / Light mode **
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19621%3A249102&t=NH2PjA7i86USVYu1-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19621%3A249102&t=NH2PjA7i86USVYu1-4)

** Footer / Dark mode **
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19621%3A248959&t=NH2PjA7i86USVYu1-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19621%3A248959&t=NH2PjA7i86USVYu1-4)

---

### (Mobile)
** Footer / Light mode **
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19620%3A248111&t=NH2PjA7i86USVYu1-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19620%3A248111&t=NH2PjA7i86USVYu1-4)

** Footer / Dark mode **
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19620%3A248242&t=NH2PjA7i86USVYu1-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19620%3A248242&t=NH2PjA7i86USVYu1-4)

** Switch language modal / Light mode **
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19621%3A248871&t=NH2PjA7i86USVYu1-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19621%3A248871&t=NH2PjA7i86USVYu1-4)

** Switch language modal / Dark mode**
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19621%3A248870&t=NH2PjA7i86USVYu1-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19621%3A248870&t=NH2PjA7i86USVYu1-4)

**Comment by MoeNick** [comment]
You may need @Tosinolawale help if you want @mateodaza .

**Comment by mateodaza** [comment]
We have the option to have a sub-path routing, nextjs let us set this up without much effort and without refactoring any of the code, for example we'll have three possible routes for projects...

/projects
/es/projects [this will be translated to spanish]
/en/projects [this is the same as /projects as english is default]

I like this feature a lot as we are not restricting the user to see a different language if desired. we are always checking the browser language and using it as a default (if we support it)

I believe an easy UX solution for this is allowing the user to see all supported languages and choose it as a preferred option, and then we leave it as a default for the whole user session on a cookie.

@Tosinolawale you have any ideas and suggestions?

**Comment by Tosinolawale** [comment]
Is it possible to have a default language influenced by the location of different users? With the option to also have the user see all supported languages and select a preferred one if need be? The user's choice or language used for the browsing session can then be stored on a cookie. @mateodaza

**Comment by mateodaza** [comment]
@Tosinolawale I think the browser defaults by a location influence, I believe using the browser language is the most reliable option. I like a lot the idea of seeing all supported languages and select a preferred one

**Comment by mosaeedi** [comment]
@mateodaza @MoeNick the language switch is added to the footer, please find all design resources on the issue detail on the top!

CC: @Tosinolawale

**Comment by MoeNick** [comment]
can you QA @mosaeedi @maryjaf ?
