### ISSUE TITLE
Giveth projects - add "likes" to updates

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1616]
I would love to be able to "like" a projects' update. just got an email letting me know about one, then went there to read it, and wanted to support, but then had no way to interact.

Can we add the <3 to updates? @mosaeedi @MoeNick 

![image](https://user-images.githubusercontent.com/75490971/193852661-d6ca9929-4cd1-4260-b046-537067054bc5.png)

**Comment by divine-comedian** [comment]
This is an interesting idea! Let's keep track of it.
