### ISSUE TITLE
GIVpower - Showing locked GIV that I didn't do!

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#1618]
**Describe the bug**
On the launch of GIVpower I went to lock up my tokens for the first time, however on 'locked GIV details' it shows a very small amount of GIV is locked up for 1 round already - I did not do this action. 

Associated address: 
`0x826976d7C600d45FB8287CA1d7c76FC8eb732030`
**To Reproduce**
1. Go to https://giveth.io/givfarm
2. Check 'locked GIV details

**Expected behavior**
I didn't do this action so I'm confused why this shows up on locked GIV details

**Screenshots**
![image](https://user-images.githubusercontent.com/67759413/193885794-315551c7-fb4b-41bb-9b53-68c3ba077f05.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser Firefox

Want to take a look @MohammadPCh @aminlatifi ?

**Comment by aminlatifi** [comment]
You had had locked that tiny amount (100 wei) for one round before 
https://blockscout.com/xdai/mainnet/tx/0xb78544f5f71294c8bcae7fc49d2c80b45abf5e524f463a5ea4b0760b7351485f
