### ISSUE TITLE
Some project cards are missing owners

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#162]
There are some project cards on the Projects page that are not displaying the owners correctly.

![image](https://user-images.githubusercontent.com/74267818/157336595-caccf791-9392-4e05-acec-164c44cde728.png)

The owner field appears blank, however, if I hover over it I can click it and it will take me to the owners profile.
Maybe the font is white and thats why I cant see it?

**Comment by aminlatifi** [comment]
@WhyldWanderer Aren't they GivingBlock projects? if yes their profile is empty since they are imported and we have only wallet address.

**Comment by mohammadranjbarz** [comment]
> @WhyldWanderer Aren't they GivingBlock projects? if yes their profile is empty since they are imported and we have only their owner's wallet addresses.

The owner of Giving block's projects is a wallet address in our config ( I think it's ashley's address)
I should check DB to find the cause
