### ISSUE TITLE
update reward notifier for FOX/xDAI Regen Farm

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1629]

**Comment by aminlatifi** [comment]
@willyogo 
Total amount to distribute in 13 rounds (182 days): 615306.8
Distribution like fox/hny: 7.70, 7.70, 7.69, 7.69, 7.69, 7.69, 7.69, 7.69, 7.69, 7.69, 7.69, 7.69, 7.70 percent
