### ISSUE TITLE
Allow Project Owners to generate a proof of donation when converting to fiat

### ISSUE THREAD

**Issue by markoprljic** [Giveth/giveth-dapps-v2#1632]
**As a Project Owner, I want to generate an official document from Giveth which states that I received donations in the amount I'm about to withdraw, so that my non-profit remains in legal compliance when converting crypto to fiat that are received on our bank account.**

Breaking this down:

As a Project Owner, when I want to convert crypto to fiat, on a monthly or quarterly basis, or anytime I want to do that, the funds I'm converting are sent to our non-profit bank account. In order to remain in legal compliance we must provide a document that states:
- information about the donor (in this case it's Giveth)
- amount of donation (in this case amount I'm converting at the time)
- purpose of donation (can be left blank for Project owner to input)

**Comment by mateodaza** [comment]
After doing a lot of research and reaching to different on/off ramp services besides the SDG, we should remove any workflow that implies fiat as an end - we'll focus on using fiat as a way to onboard more of our users to web3, not the other way around. I tried to check the feasibility of this but it's ridiculously hard as it was mentioned by @GriffGreen and @divine-comedian 

Very soon we'll be having Onramper as a solution to give users the option to send ETH and stable coins to projects on mainnet, and we're researching to integrate Radicle Drips for recurring donations also :)

**Comment by MoeNick** [comment]
As per de-prioritization of Fiat feature, I close this one.
