### ISSUE TITLE
Create Governance page on Dapp

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#1633]
**What problem is this design solving? Why is it necessary?**

Our governance platforms are really hard to find - often they are buried in forum posts, documentation or discord messages. It would be great for users who visit our platform and hold eligible tokens are given a clearer path to participate in our governance.

i would like to suggest adding a 'Governance' page accessible from the homepage of the dapp that shows users clearly where they can participate in governance voting. 

**Is there any user data or feedback backing up this feature request?**

Doing some research on our voting participation I found we only gather 3-5% of the eligible voting supply across the GIVgarden and snapshot. It would be great to see those numbers grow and engage donors and GIV holders in governance.

**Which metrics will define this feature's success?**

I would like Giveth to promote it's governance methods more clearly and increase the % of eligible tokens actively being used to vote and participate. Honestly even moving up into the 7-8% range would be massive.

**Additional context**
*Add any other context or screenshots related to your design here.*
this is a common feature I notice among many top performing protocols:
![image](https://user-images.githubusercontent.com/67759413/194627813-06f09470-e213-405f-aa75-e9b5e3dc6b8e.png)

![image](https://user-images.githubusercontent.com/67759413/194627946-bfe94a5b-cc8b-41c1-8b28-6b4af707dda7.png)
![image](https://user-images.githubusercontent.com/67759413/194628035-be707c36-8ccf-43e2-bb66-464b26a173e3.png)
![image](https://user-images.githubusercontent.com/67759413/194628420-3599fa4f-abe0-48d5-ace9-d8d9d9a0b520.png)

**Comment by divine-comedian** [comment]
Happy to do more research - we can start with something simpler and perhaps make something more interactive at some later point

**Comment by MoeNick** [comment]
Hello @mosaeedi :)

**Comment by divine-comedian** [comment]
some ideas: 

### from aave
![image](https://user-images.githubusercontent.com/67759413/195391226-1ea6ca4b-1bc3-42b1-b12c-2745f8551640.png)

### maybe v1 looks something simple like this
![image](https://user-images.githubusercontent.com/67759413/195392150-96169af9-eadb-4ce0-a636-781befb8a2f1.png)
