### ISSUE TITLE
Missing text under 'Calling all Changemakers!'

### ISSUE THREAD

**Issue by clara-zi** [Giveth/giveth-dapps-v2#164]
Missing "a" in "Do you have **_a_** for-good project"

**Comment by laurenluz** [comment]
![image](https://user-images.githubusercontent.com/75490971/158221512-948b2414-a81b-4234-b243-bdd1ea0db46f.png)


@mateodaza this should also have a comma, so:

"Do you have a for-good project that's creating value for society, for the environment, or for the world?
