### ISSUE TITLE
Change "GIVback" to "GIVbacks" everywhere & Text Fix on project card

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#1641]
**Describe the bug**
Small edit... Its GIVbacks not ever GIVback (ctrl-f GIVback and make sure we don't use this anywhere else). I would say "Eligible for GIVbacks" but that is long... Probably is better to be just "GIVbacks" (this is @laurenluz  approved... so its real)

**Screenshots**

<img width="425" alt="Screen Shot 2022-10-10 at 11 32 40 AM" src="https://user-images.githubusercontent.com/14945613/194913685-e93cf7d4-2853-4af3-9fdf-181ff194795e.png">

**Comment by laurenluz** [comment]
There are two action items here:
- [ ] ctrl-f the entire dapp to make sure we say "GIVbacks" not "GIVback" (it should always be plural)
- [ ] change the text on the project card from "GIVback Eligible" to just "GIVbacks"

**Comment by MohammadPCh** [comment]
should we change this copy too?
![image.png](https://images.zenhubusercontent.com/602bc460a2838adc28f21cdc/d77d58a1-2885-4dac-9552-8630693f8eff)
Do we have to change it GIVbacks, GIVbacks eligible, or eligible for GIVbacks?

**Comment by laurenluz** [comment]
oh yes - let's go with "GIVbacks" - good catch @MohammadPCh

**Comment by maryjaf** [comment]
Thanks @MohammadPCh 
On the projects card and in the details of the project, the "GIVBACK ELIGIBLE"has been changed to a "GIVBACKS"
