### ISSUE TITLE
Text box for project updates keeps expanding when reaching end of line

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-dapps-v2#1645]
**Describe the bug**
When the text put in the project update textbox reaches the end of line, it expands the text box.

**To Reproduce**
1. Go to one of your projects
2. Write in the text box
3. When you are about to reach the end of line, the textbox expands instead of dropping the cursor to the next line

**Expected behavior**
Cursor is dropped to next line instead of the box expanding

**Screenshots**
<img width="724" alt="image" src="https://user-images.githubusercontent.com/317685/195206254-fb16ae64-a57c-4020-ad23-a86a8e00da8e.png">
<img width="724" alt="image" src="https://user-images.githubusercontent.com/317685/195206312-6cd28fb8-4e60-4422-ac4b-0969ac0ea0ae.png">

**Desktop (please complete the following information):**
 - OS: MacOS 12.6
 - Browser: Chrome
 - Version: 105.0.5195.125 (Official Build) 

**Additional context**
Thank you for your hard work - our DApp is amazing ❤️

**Comment by MoeNick** [comment]
@RamRamez csn you please take a look?
