### ISSUE TITLE
Generate default donations to Giveth on regular donations

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#1654]
According to GIVeconomy calls on wednesday oct 13, we reached soft consensus on the method of collecting default donations to Giveth. 

We will use the simplest user flow to begin with until we have a robust and audited donation handler contract to put in place. 

This simple user flow will be to generate two transactions on every donations - 1 to Giveth and 1 to the project. 

User's can choose to take a percentage of their donation and redirect it to Giveth:
https://giveth.io/project/the-giveth-community-of-makers

User's are also able to toggle off this extra donation - meaning only 1 donation transaction would be generated. 
looping in @MoeNick @laurenluz @GriffGreen for any points I may have missed.

Design and User flow progress can be found here:
#1579

**Comment by MoeNick** [comment]
Hey @divine-comedian the modals redesign is also required for this feature I guess @mosaeedi is on it.

**Comment by MoeNick** [comment]
Here is my comment: https://github.com/Giveth/giveth-dapps-v2/issues/1579#issuecomment-1276348524

**Comment by divine-comedian** [comment]
https://default-donations.vercel.app/

**Comment by RamRamez** [comment]
> Another note to consider is the edge case where the project being donated to is Giveth itself.
> 
> In this case I think it makes sense that we wouldn't split the donation and perhaps hide the elements relating to that functionality

I fixed it. It won't show donation handler for Giveth project anymore.
Beside that I added tx steps and progress bar to make the flow easier to understand.
![image](https://user-images.githubusercontent.com/73441857/196992149-13180e15-34a0-48c5-b22e-3c733ca6b93f.png)

**Comment by MoeNick** [comment]
Let's finalize the whole flow with the Design team. maybe @Tosinolawale can help in absence of @mosaeedi

**Comment by Tosinolawale** [comment]
> Let's finalize the whole flow with the Design team. maybe @Tosinolawale can help in absence of @mosaeedi

Will do so

**Comment by divine-comedian** [comment]
going to close this issue - let's work out of #1579 to keep information in one place.
