### ISSUE TITLE
Design problem for Archived Regen Farm Cards

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#1663]

**Comment by laurenluz** [comment]
When user toggles show archive or not show archived... it would make things look a little funny.

We need some clearer design for this...

![image](https://user-images.githubusercontent.com/75490971/196726560-a0315a3f-6f29-45ad-ad47-cdc5e08310f5.png)

**Comment by laurenluz** [comment]
@mosaeedi let's discuss this one too

**Comment by laurenluz** [comment]
@MohammadPCh - @Tosinolawale is going to make some frames for this and get back to you here

**Comment by MohammadPCh** [comment]
JFYI, I fixed this and it's working properly.
