### ISSUE TITLE
GIVpower Boosting - GIVpower page styling and missing link

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#1669]
**Describe the bug**
on the GIVpower page
https://giveconomy.vercel.app/givpower

the button learn more is way too big 

also where it says coming soon we should add the link to allow users to boost projects and change the text
**To Reproduce**
1. Go to https://giveconomy.vercel.app/givpower

**Screenshots**
![image](https://user-images.githubusercontent.com/67759413/196481119-2462d4d1-35cf-492c-9465-3aa2b4468850.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser firefox

**Comment by laurenluz** [comment]
The learn more button is tested & looking right on staging now.

The change to "coming soon" should be done in #1698

moving to done!

**Comment by laurenluz** [comment]
![image](https://user-images.githubusercontent.com/75490971/197618577-4fc864d1-7bc2-4cdc-8939-18525a21a3d9.png)
