### ISSUE TITLE
GIVpower Boosting - Why is there no number for my boosted projects

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#1670]
**Describe the bug**
In every other tab you can see a total of items that correspond to the tab heading

i.e how many projects i own, how many donations I've made, how many projects I've liked. Why is there no similar functionality for boosted projects? 

**To Reproduce**
1. log into giveth
2. Click on my account

**Expected behavior**
A user should be able to see a small number next to `boosted projects` representing the number of projects they have boosted.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/276e2249-49c2-4d1a-88c7-c3b070438e9a)

**This happens on which Boosting Section?**
- [ ] Project's Card - GIVpower Rank
- [ ] Project's GIVpower ranking
- [ ] Single Project Public View | Boost Button
- [ ]  Single Project's owner view | Boost Button
- [ ]  Single Project's View | Givpower tab (Hall of fame, Total Boosted) 
- [ ] Boost Modal for a specific project
- [ ] Boost Succeeded
- [x] My Account | Boosting Tab: list of boosted projects
- [ ] My Account | Delete a Boosted Projects
- [ ] My Account | Edit boosting allocations
- [ ] My Account | Success editing allocations
- [ ] My Account | Success editing allocations. 

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.05
 - Browser firefox

**Comment by laurenluz** [comment]
It should have a number for sure - @MohammadPCh can you take it?
