### ISSUE TITLE
GIVpower Boosting | Update Project Boosted modal to explain that the rank will change later

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#1671]
**Describe the bug**
As a user it is very unclear the time difference between when I allocate GIVpower or change my allocation to a project to when it is reflected on the project page. We need to clarify or explain to the user when they should expect their new allocations to appear correctly on the GIVpower tab of the project page.

**To Reproduce**
1. Allocate GIVpower to a project
2. Go to my account -> boosted projects
3. Check your amount of GIVpower on a project
4. Go to the project page and check your GIVpower on the single project page

**Expected behavior**
Either the updated amounts are shown instantaneously or if there is a gap we should include one or two sentences to explain when the user should expect to see the updated GIVpower amount

**Screenshots**
[Screencast from 18-10-22 12:46:07.webm](https://user-images.githubusercontent.com/67759413/196507576-3e80e2f0-646d-407e-b7e7-4962350591db.webm)

**This happens on which Boosting Section?**
- [ ] Project's Card - GIVpower Rank
- [ ] Project's GIVpower ranking
- [ ] Single Project Public View | Boost Button
- [ ]  Single Project's owner view | Boost Button
- [x]  Single Project's View | Givpower tab (Hall of fame, Total Boosted) 
- [ ] Boost Modal for a specific project
- [ ] Boost Succeeded
- [x] My Account | Boosting Tab: list of boosted projects
- [ ] My Account | Delete a Boosted Projects
- [ ] My Account | Edit boosting allocations
- [ ] My Account | Success editing allocations
- [ ] My Account | Success editing allocations. 

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser firefox

**Comment by laurenluz** [comment]
@aminlatifi can you look into this? why is there a delay?

**Comment by aminlatifi** [comment]
> @aminlatifi can you look into this? why is there a delay?

@divine-comedian @laurenluz It's the nature of givpower boosting, we collect boosting information during a round and show the average of values when the round finishes. Currently, at most 5 minutes after a round finishes, we will update the ranking and allocated power. Is it clear? let me know if any further information you need.
Basically, we need some design to explain to the user what is happening. In case you need more information from the backend we can provide you.

**Comment by aminlatifi** [comment]
@divine-comedian @laurenluz Just a point, in staging/giveconomy deployment we set boosting round duration to 20 minutes and take snapshot every 5 minutes.

**Comment by MoeNick** [comment]
I think we have to have this copy on the top of the GIVpower tab of the project page.
"Updated on HH:MM Month, Day Year"

**Comment by laurenluz** [comment]
- [ ] We should mention to the user that the GIVpower ranking of the project will be changed at the top of the next round on the boosting confimed modal

![image](https://user-images.githubusercontent.com/75490971/196716295-4b473332-c491-4415-abbb-70a5fe43191b.png)

- [ ] We should add text  "Rank will be updated on x date" to the GIVpower tab
![image](https://user-images.githubusercontent.com/75490971/196717333-31b7007e-abf4-4272-884c-a71d45247c06.png)

**Comment by laurenluz** [comment]
@mosaeedi can you add this into the design quickly?

**Comment by laurenluz** [comment]
The bulk of these changes are being done in other issues... the only remaining task here is to change the modal a little.

The change to this modal can be found at this [figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=14344%3A260160)

![image](https://user-images.githubusercontent.com/75490971/197649750-ba0f1ddb-5260-4ba1-b1f6-d1061e0bd26d.png)

**Comment by maryjaf** [comment]
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/9dc0c0a2-e389-4216-a990-92e4b7ef51cc)

**Comment by laurenluz** [comment]
@divine-comedian -  sorry, this was a mistake on my part w/ the screenshot... the figma has the right copy... "ranking" should be "rank"

Can you make this small copy fix?

**Comment by divine-comedian** [comment]
done!
