### ISSUE TITLE
GIVpower Boosting | not able to boost my own project

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-dapps-v2#1673]
**Describe the bug**
Using google chrome. Signed in, giv staked and locked, on my own projects page there is no option to boost my own project.

![image](https://user-images.githubusercontent.com/100084867/196514785-f1aee66e-d951-413b-9c2c-a9b243931111.png)

![image](https://user-images.githubusercontent.com/100084867/196515065-e5d9eb2c-ce3f-4fa1-b183-a42a97513b00.png)

**To Reproduce**
1. Go to 'my account after sign in'
2. Click on 'view' to one of your active, listed projects

4. See error - no option to boost your own project

**Expected behavior**
add the 'boost' button

**This happens on which Boosting Section?**

- [ ]  Single Project's owner view | Boost Button

**Comment by laurenluz** [comment]
@MohammadPCh can you take this?

**Comment by laurenluz** [comment]
ooh @NikolaCreatrix boosting should only be possible on already verified projects (not ones in the middle of the verification process). Did you test with an already verified project?

**Comment by NikolaCreatrix** [comment]
Hi @laurenluz and @MohammadPCh 

I just tried with this project

https://giveconomy.vercel.app/project/giveth-tour-bridge-the-world

![image](https://user-images.githubusercontent.com/100084867/196745823-55aadc3d-555e-4daf-ba22-d876b4292d21.png)

Still no Boost button.

**Comment by MohammadPCh** [comment]
@NikolaCreatrix it's merged about 20 minutes ago, can you check it again?

**Comment by MoeNick** [comment]
@NikolaCreatrix based on recent changes you need to have a verified project to be able to boost it, is your project verified?

**Comment by NikolaCreatrix** [comment]
Hey @MoeNick and @MohammadPCh 

Thanks, it works now!

![image](https://user-images.githubusercontent.com/100084867/197028969-1aaa5a66-a31d-4d00-94a3-db11f532697e.png)
