### ISSUE TITLE
Similar projects are not displayed 

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#1675]
By selecting a project, the list of similar projects is empty in UI, but in the response of graphql, a list of similar projects is displayed.
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/111529185/196698787-18b4c67e-c9bd-4697-a7b4-f36c56d0f643.png">

**Comment by MohammadPCh** [comment]
@RamRamez, can you take it please? Thanks :)
