### ISSUE TITLE
GIVpower Boosting | Frontend fixes for verified (and not yet boosted) projects

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#1684]
non verified projects that have been boosted are displayed in the list of projects without rank
and in the detail of the project, there are't "GIVpower"  tab and "BOOST" button.
![image](https://user-images.githubusercontent.com/111529185/196900242-2d851d33-9863-4359-a5e0-e7419c2fb9b0.png)

![image](https://user-images.githubusercontent.com/111529185/196900342-6378b1d3-e3c2-445b-ab60-659175ec5a1f.png)

**Comment by laurenluz** [comment]
Hey @maryjaf - as per https://github.com/Giveth/GIVeconomy/issues/739 if a project is non-verified it should:
- [ ]  not have a rank on any page
- [ ] not have a GIVpower tab on the project single page
- [ ] not have any option to "boost" the project

I'm not sure I totally understand this issue, but can you double check the above conditions & test them? If it is not the case, please let us know here & it will need to be fixed.

**Comment by laurenluz** [comment]
related to #1800

**Comment by maryjaf** [comment]
> Hey @maryjaf - as per [Giveth/GIVeconomy#739](https://github.com/Giveth/GIVeconomy/issues/739) if a project is non-verified it should:
> 
> * [ ]   not have a rank on any page
> * [ ]  not have a GIVpower tab on the project single page
> * [ ]  not have any option to "boost" the project
> 
> I'm not sure I totally understand this issue, but can you double check the above conditions & test them? If it is not the case, please let us know here & it will need to be fixed.

Yes, when the project is unverified, it has all three conditions above
It's just that we have a problem related to displaying the rank in the list of projects after unverify, which is explained on #1736 (https://github.com/Giveth/giveth-dapps-v2/issues/1736#issuecomment-1308794255)

**Comment by MohammadPCh** [comment]
@laurenluz just for clarification, If a verified project has rank we show it (for example `#1`) but if it doesn't have rank, do we want to show something like this rocket  " 🚀 -- "? I mean a rocket instead of a sharp sign?

**Comment by laurenluz** [comment]
Hey @MohammadPCh !

The project card looks great.

Conditions:
If it is verified but not boosted - we show the rank like that "🚀 -- "
If it is verified and boosted by some amount - we show the rank like " 🚀 #24"
And if it is not verified, we show no rank at all, and no rocketship.

By project single page card... I mean this... I think we may have no yet implemented it 😨 we should! [Figma](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=14382%3A259227&t=DlX2URbXehHsPY9q-4)

![image](https://user-images.githubusercontent.com/75490971/202008019-0d6a11fc-5c2e-4589-8078-e5f7286b50ff.png)

**Comment by MohammadPCh** [comment]
@laurenluz Thanks, Got it.
