### ISSUE TITLE
GIVpower Boosting | Redesign Project Single Page to show better the rank - hide rank for unverified projects

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1688]
Related to #1671 & #1679 

Project Single page needs some updates for GIVpower:
- [x] if the project is unverified, there should be no ability to boost the project or see its GIVpower
- [x] if the project is verified, its rank should be shown predominately on the project single page
- [x] under the "GIVpower tab" - the rank & total GIVpower should be separated... we want to total GIVpower to be dynamic, changing every time the user changes their GIVpower
- [x] The rank should be more prominant and we should somehow show the user that the rank will change at the start of the next GIVbacks round (or that this rank is based on data from the last GIVbacks round)
- [x] Nice to have: it would be nice to show "projected rank for next GIVbacks round" <--- this number is possible for us to get dynamically, and it is an incentive for people to try to boost more when they know their rank will change.
- [x] we should remove the GIVpower "boosters'" (the GIVpower users') rank... it's confusing with the project rank.

@mosaeedi @Tosinolawale 

![image](https://user-images.githubusercontent.com/75490971/197034966-b16a4e04-21a4-4488-a931-b52f77a89f13.png)

**Comment by Tosinolawale** [comment]
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=14382%3A259227
@laurenluz Left a bunch of comments for you on the Figma file

**Comment by laurenluz** [comment]
@MohammadPCh this is ready to implement: [Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=14382%3A259227)

![image](https://user-images.githubusercontent.com/75490971/197649394-20599f3d-e6e2-40ce-b77b-73732ed1f5bb.png)

**Comment by laurenluz** [comment]
@Tosinolawale is making some tweaks to the design & will update it here asap

**Comment by Tosinolawale** [comment]
![Group 11147](https://user-images.githubusercontent.com/35389241/198325472-36cd9616-d934-450d-8d55-3222b6308d6f.png)
@MohammadPCh @laurenluz

**Comment by Tosinolawale** [comment]
![Group 11147(1)](https://user-images.githubusercontent.com/35389241/198325902-ea4e616a-9431-4632-9b2e-d07181ccdc7e.png)

**Comment by Tosinolawale** [comment]
![Public view](https://user-images.githubusercontent.com/35389241/198705076-5f7756b4-0e6d-4c44-8a73-93cb7fb70022.png)
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=14382%3A259227
updated @MohammadPCh @laurenluz

**Comment by MohammadPCh** [comment]
@Tosinolawale Thanks,
@laurenluz, Is It the final version? can I start working on it?

**Comment by laurenluz** [comment]
@MohammadPCh - @markoprljic had a few comments still in the figma... let's wait until they are resolved. I will confirm here when the design is final.

**Comment by MohammadPCh** [comment]
@aminlatifi @mohammadranjbarz Please look at the Figma link. we need the project's `current` and `next` rank.
![image.png](https://images.zenhubusercontent.com/602bc460a2838adc28f21cdc/45d84c94-6d9a-42db-af2c-8785bb5b395e)
Do we have it in the backend?

**Comment by aminlatifi** [comment]
> @aminlatifi @mohammadranjbarz Please look at the Figma link. we need the project's `current` and `next` rank. ![image.png](https://camo.githubusercontent.com/432b5e3bc3e202d91d5bfd243333bae1d08761025c2821a2700db5188622b271/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630326263343630613238333861646332386632316364632f34356438346339342d366439612d343264622d616632632d383738356262356233393565) Do we have it in the backend?

No, we must add it. https://github.com/Giveth/impact-graph/issues/710

**Comment by aminlatifi** [comment]
> > @aminlatifi @mohammadranjbarz Please look at the Figma link. we need the project's `current` and `next` rank. ![image.png](https://camo.githubusercontent.com/432b5e3bc3e202d91d5bfd243333bae1d08761025c2821a2700db5188622b271/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630326263343630613238333861646332386632316364632f34356438346339342d366439612d343264622d616632632d383738356262356233393565) Do we have it in the backend?
> 
> No, we must add it. [Giveth/impact-graph#710](https://github.com/Giveth/impact-graph/issues/710)

@MohammadPCh Made this PR to calculate future power of the user which will be joined when project is fetched by slug. Just not if we merge that PR, futurePower will not always be filled (like the beginning of a round). In that case projectPower has value but projectFuturePower would be null. It maybe better to show the same project power rank as the future value until new snapshots be taken

**Comment by maryjaf** [comment]
In the previous version, it was said that if a verified project did not have a boost, a rank would not be set for them in the Give Power tab and in the project list.

But now it does not have a rank in the list of projects, but we show the rank of the project in the Give Power tab
The expected result is this or it should be the same as before and we have a bug? @MohammadPCh @laurenluz  
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/4954d494-ff33-48f2-94f0-9d5fa7d6e50e)
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/149c4048-40c7-4250-87a3-0e42e379e2b8)

**Comment by laurenluz** [comment]
> In the previous version, it was said that if a verified project did not have a boost, a rank would not be set for them in the Give Power tab and in the project list.
> 
> But now it does not have a rank in the list of projects(pic 2), but we show the rank of the project in the Give Power tab(pic 1) The expected result is this or it should be the same as before and we have a bug? @MohammadPCh @laurenluz

Yes @maryjaf - good catch. This is an error.

- [ ] @MohammadPCh - make sure that, if a project loses it's verified status, the GIVpower tab should be hidden... it should look like a project that was never verified:

![image](https://user-images.githubusercontent.com/75490971/201227990-7a2feff6-fbe9-4356-a47d-0128ed584e2f.png)

**Comment by maryjaf** [comment]
> In the previous version, it was said that if a verified project did not have a boost, a rank would not be set for them in the Give Power tab and in the project list.
> 
> But now it does not have a rank in the list of projects(pic 2), but we show the rank of the project in the Give Power tab(pic 1) The expected result is this or it should be the same as before and we have a bug? @MohammadPCh @laurenluz ![image.png](https://camo.githubusercontent.com/3557ab4b8ec0c2dae8412c96b99f69a3fc42ed493c165e10c63b2eb7c3af49fa/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f34393534643439342d666633332d343866322d393466302d396435666137643665353065) ![image.png](https://camo.githubusercontent.com/399b2b48e7c8072c9a7e77eaff878e3997cbc2a2551fbcc8eeccee235ce4a447/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f66663332386133322d313765342d346163372d616462312d313733633734633461373737)![image.png](https://camo.githubusercontent.com/cf0a27c13e85028eb536981eb6bc9f2adb6853c9a5a2f9dd92851e5b1375cb43/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f31343963343034382d343063372d343235302d383761332d306534326533373965326238)



> In the previous version, it was said that if a verified project did not have a boost, a rank would not be set for them in the Give Power tab and in the project list.
> 
> But now it does not have a rank in the list of projects(pic 2), but we show the rank of the project in the Give Power tab(pic 1) The expected result is this or it should be the same as before and we have a bug? @MohammadPCh @laurenluz ![image.png](https://camo.githubusercontent.com/3557ab4b8ec0c2dae8412c96b99f69a3fc42ed493c165e10c63b2eb7c3af49fa/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f34393534643439342d666633332d343866322d393466302d396435666137643665353065) ![image.png](https://camo.githubusercontent.com/399b2b48e7c8072c9a7e77eaff878e3997cbc2a2551fbcc8eeccee235ce4a447/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f66663332386133322d313765342d346163372d616462312d313733633734633461373737)![image.png](https://camo.githubusercontent.com/cf0a27c13e85028eb536981eb6bc9f2adb6853c9a5a2f9dd92851e5b1375cb43/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f31343963343034382d343063372d343235302d383761332d306534326533373965326238)

Please also specify this case when the project is verified but it hasn't any boost yet
In the Givpower tab of project details are not ranked  as they are not ranked in the list of projects.
Or the last rating for these projects should be shown in the GivPower tab, like what we see in the image on the test environment now
@laurenluz

**Comment by MohammadPCh** [comment]
@laurenluz @maryjaf I fix the issue by showing `--` instead of number for non boosted projects. it happens because the backend returns the last number for non-boosted projects.

**Comment by maryjaf** [comment]
> @laurenluz @maryjaf I fix the issue by showing `--` instead of number for non boosted projects. it happens because the backend returns the last number for non-boosted projects.

Is this fix deploy on Giveconomy env? 
I tested and didn't see changes in this scenario

**Comment by MohammadPCh** [comment]
No, It's not merged yet. I just left a PR for it.

**Comment by MohammadPCh** [comment]
@maryjaf It's on the GIVeconomy now :)

**Comment by laurenluz** [comment]
@MohammadPCh I think this part of the project single page was overlooked... we redesinged the placement of the "boost" button and made it so that the rank appears on every page. [Figma](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=14382%3A259227&t=DlX2URbXehHsPY9q-4)

![image](https://user-images.githubusercontent.com/75490971/202008810-22ee7dda-c7b6-43b1-ad5c-b313536639dc.png)

**Comment by MohammadPCh** [comment]
@laurenluz Thanks for posting it here, actually, I didn't see this change :(
I will implement it soon, do we have the mobile design for it?

**Comment by laurenluz** [comment]
@Tosinolawale - if you can post the mobile & responsive designs in here when they're ready - would be great :)

**Comment by Tosinolawale** [comment]
Responsive Screen Guides @MohammadPCh @laurenluz 
1280px  > 
![Project Single - Donations ( _1440   up)](https://user-images.githubusercontent.com/35389241/202256266-644824f5-6521-47b0-8335-a01265138059.png)

1025px - 1280px
![Project Single - Donations (_1280   _1439)](https://user-images.githubusercontent.com/35389241/202256430-35f67a64-85eb-497c-94c7-249cb029a49c.png)

769px - 1024px
![Project Single - Donations (_1024   _1279)](https://user-images.githubusercontent.com/35389241/202256523-8f4f3c74-17ac-4ecd-ad87-769fd058b65c.png)

500px - 768px
![Project Single - Donations (_1024   _1279)(1)](https://user-images.githubusercontent.com/35389241/202256622-6222266b-dcd7-4a31-841b-6ca44dd97496.png)

https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=12922%3A242058&t=BqZDz2yJfpyN9E98-0

**Comment by Tosinolawale** [comment]
Mobile View 
![Group 11162(1)](https://user-images.githubusercontent.com/35389241/202257892-139b21bc-ca94-42f3-ba7d-fab33fd9c11b.png)
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=15336%3A276554&t=BqZDz2yJfpyN9E98-0

**Comment by laurenluz** [comment]
Hey @MohammadPCh - also let's make sure that the project single page owner's view looks right. Tosin made them up in figma as well: https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=15346%3A283524&t=9CQuKGmnvJ6SpydZ-4

![image](https://user-images.githubusercontent.com/75490971/202469590-d5ed9418-4b5f-49fb-b0b2-c3bdd3c7ad26.png)

**Comment by maryjaf** [comment]
plz check this problem @MohammadPCh 
 for unverified project in new design the rank and boost option are shown 
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/3548de5a-09ff-4281-b458-7378e8caac2e)

**Comment by maryjaf** [comment]
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/d67d6946-b1da-4797-b00c-8cf70c416a00)
There is overlap in this section @MohammadPCh

**Comment by laurenluz** [comment]
@MohammadPCh - can you fix it?

**Comment by MohammadPCh** [comment]
@maryjaf @laurenluz Thanks, I fixed them. please check it again.

**Comment by maryjaf** [comment]
Thanks, I tested and it passed
