### ISSUE TITLE
Header improvement: Hightlight the current tab

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1693]
In the categories section, the selected category is highlighted. We should also highlight the tab that the user has selected, for example "Project"

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/5ff5b1a5-efa1-455c-9d23-8aea0fcb4c80)

**Comment by divine-comedian** [comment]
The headers have now changed to drop down menus we'll need to rethink this one if it makes sense
