### ISSUE TITLE
GIVpower Boosting |  Copy fix on project single page when the project has no GIVpower on it.

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1703]
**Describe the bug**
We should use "boost" as a verb, not a noun! GIVpower is the noun. The reason is because GIVpower provides utility to GIV, which is valueable for the GIVeconomy. If we completely omit "GIV" from our comms around GIVpower and use "boost" everywhere instead... the user does not make the connection to GIV.

I would like to fix the copy on the project single page when the project has no GIVpower allocated to it.

**To Reproduce**
1. Go to 'project single page.
2. Click on 'GIVpower tab'
3. Make sure the project has no GIVpower on it
4. See copy

**Expected behavior**

Copy fixes:

- [ ] If you are looking at a project that is not yours, that has not been boosted:
"This project hasn't been boosted yet!
Be the first to boost this project with GIVpower."
![image](https://user-images.githubusercontent.com/75490971/197641060-d08486ad-34e4-4994-8cd5-338cc6774587.png)

- [ ] If you are looking at your own project, and it has not been boosted
"Your project has not yet been boosted!
Share your project on social media and ask your friends to use GIVpower to give you a boost!"

![image](https://user-images.githubusercontent.com/75490971/197641372-78ae8b6f-0161-402a-a584-b61bfdf72abb.png)

**Screenshots**

**This happens on which Boosting Section?**
- [ ] Project's Card - GIVpower Rank
- [ ] Project's GIVpower ranking
- [x] Single Project Public View | GIVpower tab
- [x]  Single Project's owner view | GIVpower tab
- [ ] Boost Modal for a specific project
- [ ] Boost Succeeded
- [ ] My Account | Boosting Tab: list of boosted projects
- [ ] My Account | Delete a Boosted Projects
- [ ] My Account | Edit boosting allocations
- [ ] My Account | Success editing allocations
- [ ] My Account | Success editing allocations.

**Comment by maryjaf** [comment]
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/10908ebd-c6c9-4098-806e-7ac989571397)
When i created a project on givpower branch i can't see details of project @RamRamez

**Comment by RamRamez** [comment]
I get this error. @CarlosQ96 Can you please check it?
![image](https://user-images.githubusercontent.com/73441857/198877076-4a353582-aca2-4a0c-ae7e-e755d9b22453.png)

**Comment by CarlosQ96** [comment]
@RamRamez What is the name of this query?

**Comment by RamRamez** [comment]
> @RamRamez What is the name of this query?

`ProjectBySlug` on `https://dev.serve.giveth.io/graphql`

**Comment by CarlosQ96** [comment]
@mohammadranjbarz @RamRamez  The issue is: after checking the files in the dev server is that dev doesn't have all the changes of our staging. So we gotta merge staging into dev.

There shouldn't be any problem right? Since givpower is already on staging. @mohammadranjbarz unless there are changes I am not aware.

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz @RamRamez  The issue is: after checking the files in the dev server is that dev doesn't have all the changes of our staging. So we gotta merge staging into dev.
> 
> There shouldn't be any problem right? Since givpower is already on staging. @mohammadranjbarz unless there are changes I am not aware.

Yeah man you can do it, just take care of env file in dev and make sure it has anything needed

**Comment by CarlosQ96** [comment]
Added project revoke env vars, everything else seems the same.

**Comment by CarlosQ96** [comment]
@RamRamez @maryjaf Its fixed, the view doesn't break anymore. You can keep testing / working.
