### ISSUE TITLE
GIVpower Boosting | Are we able to revert to previous boostings?

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1704]
@aminlatifi I was thinking about Giveth/GIVeconomy#739 and I have one concern I want to get your input on:

What if, by chance, a project was unverified by some mistake on our part? It would be nice if we were able to somehow revert to some point in the history to give them back their original boostings... would this be possible?

cc @MoeNick

**Comment by aminlatifi** [comment]
It will be a little complicated!
Generally, we don't keep the history of boosting. We only have snapshots taken regularly every 4 hours in production env. Though we can investigate how we can add history support to boosting, I don't think that would be so easy to implement it. As it may cause issues when a user which has boosted that project changes her/his boosting during the time the project was unverified.

**Comment by laurenluz** [comment]
we should be able push to culture side... if a project gets unverified, they will lose all their GIVpower, they won't get it back, etc. etc. @WhyldWanderer - can you be sure to include that info in our email communcations after boosting goes live?

And would also be good to have human readable snapshot data that we could revert to if need be.

**Comment by laurenluz** [comment]
it's going to be very challenging & complicated for us to do any reverting, so we won't likely be able to do it.
