### ISSUE TITLE
Project updates character limit is buggy

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1714]
Something really weird is going on with the character limit on updates... 

This copy is apparently way too long:
![image](https://user-images.githubusercontent.com/75490971/198691764-089b976b-1b1a-451b-90fa-bb5867fe8c59.png)

But google says otherwise:
![image](https://user-images.githubusercontent.com/75490971/198691781-2653d6bc-71f7-418f-962a-2d40cb7f9699.png)

A second example... this is an update i made previously that I copy/pasted... now apparently it's too long:
![image](https://user-images.githubusercontent.com/75490971/198691848-b60d003a-d8f8-460c-acf2-83fcf0d97fc0.png)

A third example, look what happens when I delete all the text:
![image](https://user-images.githubusercontent.com/75490971/198691882-e51dff3b-a1ec-4cb3-846f-b768a4f8d557.png)

**Comment by MoeNick** [comment]
Do you have this problem still? @laurenluz

**Comment by laurenluz** [comment]
yes - still a problem. I just tried posting an update... and without any text in there at all, you can see the character count is already at 11

![image](https://user-images.githubusercontent.com/75490971/214092698-6f4eb3cc-fa56-4086-9f43-3b8cd7f0135c.png)

**Comment by MoeNick** [comment]
@mateodaza this one is assigned to you, ae you happy or I can assign it to somebody else I think others may be interested

**Comment by laurenluz** [comment]
Can we pleaaase fix this? It is so extremely annoying for project owners and is wasting a ton of my time while I try to fight with it.
