### ISSUE TITLE
Can we add a "delete draft" to the "My projects tab"

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1715]
It is sooo annoying to me that I have all these trashy projects I made just to test things on Giveth... can we add something to the design that allows users to delete these projects?

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/d4c0aa2a-9a35-40e2-b016-44ec58beae85)

@mosaeedi @MoeNick

**Comment by Vyvy-vi** [comment]
perhaps we can replace the 
Edit View options with an edit icon that shows a window when clicked, and has the view, edit, delete options?

**Comment by laurenluz** [comment]
let's wait until we decide something for Giveth pro... but if we don't go ahead with Giveth pro, we can re-address this.

**Comment by divine-comedian** [comment]
#1271 

Also duplicate here
