### ISSUE TITLE
Bug report: Permit Mode does not work on the Angel Vault

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-dapps-v2#1716]
**Describe the bug**
When I try to stake in the Angel vault, I cannot use Permit mode (when I click it nothing happens), only Approve move works (see image below). 

![permit not working](https://user-images.githubusercontent.com/4855928/198724389-c7898834-79e2-434b-aafc-b23505bfcda3.gif)

**Comment by aminlatifi** [comment]
ICHI and GardenUnipool were excluded from `Permit Mode` feature! But that logic was overwritten and lost during some merge actions.
@mateodaza  you have fixed some issue related to that here https://github.com/Giveth/giveth-dapps-v2/pull/1425/files

We must return back that logic to the stake modal.

**Comment by MoeNick** [comment]
@maryjaf it needs your attention.

**Comment by maryjaf** [comment]
On which environment it should be tested and I don't know about Angel vault and couldn't see on staging @MoeNick @aminlatifi
