### ISSUE TITLE
For some projects in Mobile view, the dropdown menu is not displayed after closing

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#1718]
This problem has been observed for the verified projects that I am the owner of, after closing menu(pic 1&2). This problem was not observed for the other projects(pic 3)

![image](https://user-images.githubusercontent.com/111529185/198851026-08ec82c1-8449-4b05-9348-cddd00ee0b15.png)
![image](https://user-images.githubusercontent.com/111529185/198851034-83f70a91-056d-4096-8045-5a854c071241.png)
![image](https://user-images.githubusercontent.com/111529185/198851041-e956ff48-e660-4cbd-b2f8-161c47b05bcc.png)

**Comment by MohammadPCh** [comment]
@laurenluz @maryjaf  I will move this to IceBox, and I hope finds a new alternative package.
