### ISSUE TITLE
Pay out rewards to addresses who were farming in the affected GIVfarm pools pre-attack.

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1738]
@aminlatifi has created a compilation of rewards at the "block before the attack", and we are hoping to test them using the data Jesus gets for dAppNode.

Next we should pay these rewards out to users & announce on Twitter.

**Comment by laurenluz** [comment]
@aminlatifi will we need to do a disperse to send these funds out to users? or will we be able to have them claim from the old farm cards?

I imagine we will need to do a disperse & just notify them. correct?

**Comment by aminlatifi** [comment]
> @aminlatifi will we need to do a disperse to send these funds out to users? or will we be able to have them claim from the old farm cards?
> 
> I imagine we will need to do a disperse & just notify them. correct?

We must allocate rewards to them on the corresponding token distro, they themselves can then claim the liquid part later.

**Comment by aminlatifi** [comment]
What we are going to calculate is the reward of farming which finally is paid by allocating the reward to the user on the TokenDistro. Technically, I am going to simulate earned value of farm per user at the block before the attack

**Comment by aminlatifi** [comment]
I have prepared this repo 
https://github.com/aminlatifi/givpower-average-balance/

And it's the output result 
[Rewards_before_attack.zip](https://github.com/Giveth/giveth-dapps-v2/files/9917552/Rewards_before_attack.zip)

**Comment by laurenluz** [comment]
@divine-comedian

**Comment by laurenluz** [comment]
I've set up an announcement thread for tomorrow
