### ISSUE TITLE
GIVpower Boosting | My Boosted Projects Modals Copy Fixes

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1739]
When the user is in "My Account --> Boosted Projects", there are a series of modals w/ copy that we should revise.

- [x] Saving changes modal [Figma](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=13185%3A240957)
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/78f0cd8a-b2ed-4f5d-a32f-dc04d0b8cf5a)

- [x] Remove GIVpower modal [Figma](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=12771%3A233321)
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/d94bf285-384c-4960-aca2-11628edc14ee)

- [x] Trying to remove last boost [Figma](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=12771%3A233434)
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/419481a4-be9d-4e26-b47f-0f7609b4f501)

**Comment by divine-comedian** [comment]
fixes made in https://github.com/Giveth/giveth-dapps-v2/commit/4f1f9072cf25f6f3d84df57c97883a520b480907

on giveconomy deployment
