### ISSUE TITLE
GIVpower Boosting | Discrepancy in the boosted amount in the project list and project details

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#1741]
**Describe the bug**
For some projects, the amount we show for the boost in the list of my boosted projects and the details of the project boosts are different in decimal

![image](https://user-images.githubusercontent.com/111529185/199453138-f3fdd2d0-9a5b-4e94-a341-967913212e00.png)
![image](https://user-images.githubusercontent.com/111529185/199454853-64d0a3c9-7860-433c-8d63-d8b1b6be60e3.png)

**Comment by laurenluz** [comment]
I think this is redundant w/ #1800 now
