### ISSUE TITLE
Remove inactive partnership's from Giveth website

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#1742]
@SnakeGH commented on [Wed Nov 02 2022](https://github.com/Giveth/giveth-dapps-v2/issues/1751)

After speaking with Griff, he mentioned that these two partnerships are inactive, and Giveth will not be working with them moving forward. They can be removed from our partnership page on the Giveth website

-District0x
-SourceCred

@MoeNick would you be able to assist with this? 

---

@MoeNick commented on [Wed Nov 02 2022](https://github.com/Giveth/giveth-dapps-v2/issues/1751)

sure! Maybe @alireza-sharifpour can fix it.

**Comment by divine-comedian** [comment]
testing on https://giveth.io/partnerships

I can no longer find the partnerships listed above on the page! 

this looks to be live already on production so I will close this issue
