### ISSUE TITLE
Some form edits on verification form

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#1745]
everything is explained here well:
https://docs.google.com/document/d/1IAa8Osu7lbrULRAKkBA9ZtfTV0jq4dvns-9lyEAQS48/edit

**Comment by MoeNick** [comment]
Hey @CarlosQ96 
According to page 6 of this document, the fields should be like this:
1st Input: Problem
2nd Input: Mission
3rd Input: Initiation
4th Input: Past activities
5th Input: Impact
6th Input: Files
7th Input: Plans

so we need you help on the backed side, 

- [ ] input in the form
- [ ] show the on the admin bro 
thanks
FYI @RamRamez

**Comment by CarlosQ96** [comment]
@MoeNick @RamRamez PR https://github.com/Giveth/impact-graph/pull/714 has been merged to staging. 
You can now send as inputs the plans and problem fields in the form inputs for milestones.
```typescript
@ObjectType()
export class Milestones {
  @Field(type => String, { nullable: true })
  foundationDate?: String;
  @Field({ nullable: true })
  mission?: string;
  @Field({ nullable: true })
  achievedMilestones?: string;
  @Field(type => [String], { nullable: true })
  achievedMilestonesProofs?: string[];
  @Field(type => String, { nullable: true })
  problem?: string;
  @Field(type => String, { nullable: true })
  plans?: string;
}
```

**Comment by CarlosQ96** [comment]
Plans and problem show in the admin bro when added (this are empty strings because they are new fields)
<img width="732" alt="image" src="https://user-images.githubusercontent.com/92376054/200760680-665636c8-6d18-48db-9ba2-9aced643035c.png">

**Comment by RamRamez** [comment]
@maryjaf It's merged on staging and you test it

**Comment by maryjaf** [comment]
Thanks @RamRamez I tested this problem and it passed.
One question on production the minimum amount of donation is 0.00001 but now on STG I can donate a project for 0.000001 GIVpower, is this ok?and did we change the minimum amount?

**Comment by RamRamez** [comment]
> Thanks @RamRamez I tested this problem and it passed. One question on production the minimum amount of donation is 0.00001 but now on STG I can donate a project for 0.000001 GIVpower, is this ok?and did we change the minimum amount?

The minimum donation amount was > 0.000001 but now it's >= 0.000001
