### ISSUE TITLE
Remove inactive partnership's from Giveth website

### ISSUE THREAD

**Issue by SnakeGH** [Giveth/giveth-dapps-v2#1751]
After speaking with Griff, he mentioned that these two partnerships are inactive, and Giveth will not be working with them moving forward. They can be removed from our partnership page on the Giveth website

-District0x
-SourceCred

@MoeNick would you be able to assist with this?

**Comment by SnakeGH** [comment]
@alireza-sharifpour & @MoeNick, I learned of one more, MyCrypto was acquired and merged with MetaMask so I believe that one is not valid to have our on our website anymore as well.

**Comment by MoeNick** [comment]
@alireza-sharifpour I think we missed MyCrypto

**Comment by alireza-sharifpour** [comment]
> @alireza-sharifpour I think we missed MyCrypto

I will work on it

**Comment by MoeNick** [comment]
@maryjaf fyi to test and confirm

**Comment by maryjaf** [comment]
I checked and mycrypto has been removed from list.
