### ISSUE TITLE
GIVpower Boosting | Incorrect message display in GIVpower tab on project details page

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#1766]
**Describe the bug**
When I tap on  the Give Power tab, this message is displayed at the beginning of the loading page "This project hasn't received any boosts yet! Be the first one to boost this project."
 and after a few milliseconds, the boosting list is displayed.
**To Reproduce**
1. Go to 'project list'
2. Click on 'one project'
3. Click on ' GIVpower' tap
4. See message: This project hasn't received any boosts yet!

**Comment by laurenluz** [comment]
@mohammadranjbarz is this an issue because of delay from the graph?

**Comment by mohammadranjbarz** [comment]
@MohammadPCh 
It's not from frontend side?
I think maybe you show a placeholder till the response comes from server, am I right?

**Comment by MohammadPCh** [comment]
@mohammadranjbarz thanks for mentioning me.
yes, the problem is on the front-end side. because we don't show loading when data has not arrived yet.
