### ISSUE TITLE
Improve Home Page SSR

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapps-v2#177]
The home page project list has a few issues because it's rendered server-side and the list of projects and their data are not updated! It affects
 - Total project reaction count. First, the old values are shown and then updated by new values because we fetch based on user data (we fetch once even if no user is available, e.g. no wallet is connected)
 - The order of projects is not updated. So when user loads the page, the projects reorder in short time after render.

**Comment by aminlatifi** [comment]
This can be useful
https://www.redsunsoft.com/2021/10/simple-cache-expiration-for-apollo-graphql-queries/

**Comment by divine-comedian** [comment]
@aminlatifi @MoeNick do we still need this for anything? Icebox? Keep on our sprints?

**Comment by MoeNick** [comment]
I think we can compromise it. But lets wait for @aminlatifi 's comment
