### ISSUE TITLE
GIVpower Boosting | Add "GIVpower" to user page

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1775]
When I am looking a user's profile, I should be able to see also their GIVpower & boosted projects. This will also be useful when we implement delegation for GIVpower... for example, someone will be able to see how a person is using their GIVpower before delegating to them.

The user page is here, for an example: https://giveconomy.vercel.app/user/0xc46c67bb7e84490d7ebdd0b8ecdaca68cf3823f4

Currently, it looks like:
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/93428440-53ab-4926-b2bf-a99157e45024)

We should:
- [ ] Add in "Overview" tab (which should show GIVpower - related to #1776 )
- [ ] Add in a tab for "GIVpower" where it shows the user's boosted projects

So that it is more similar to "My Account":
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/fa2f5bfe-aeef-44dd-9288-a6bc58455cb4)

**Comment by Tosinolawale** [comment]
![Public Profile _ Projects](https://user-images.githubusercontent.com/35389241/200596370-8d4d82de-5826-4e36-8936-5c6ac24ff13b.png)
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=15039%3A275856

**Comment by Tosinolawale** [comment]
![Public Profile _ Projects(1)](https://user-images.githubusercontent.com/35389241/200596694-f9f04af7-733b-4ee1-a86b-461c2301e9f2.png)
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=15039%3A279168
@laurenluz

**Comment by laurenluz** [comment]
Thank you @Tosinolawale !

@MohammadPCh - can you implement?

**Comment by maryjaf** [comment]
Plz check these @MohammadPCh 
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/6175a545-380b-4e80-b2dd-45d69c5984ac)
![image.png]
(https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/6f6ffd72-88f0-42d0-9db4-6d3942ae5a06)
The font size of this number(PROJECTS BOOSTED) isn't correct 
and i didn't see the copy icon in this page according to the etched designs
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/718c0137-5539-4eed-8af1-863cb25774c6)

**Comment by MohammadPCh** [comment]
@maryjaf can you check it again? I fixed the font sizes. but what do you mean by this? ‍`i didn't see the copy icon in this page according to the etched designs`
this is Figma:
![image](https://user-images.githubusercontent.com/17097576/201970231-3f0d2480-68ec-4099-befe-600ec4dfb286.png)

**Comment by maryjaf** [comment]
> ![Public Profile _ Projects(1)](https://user-images.githubusercontent.com/35389241/200596694-f9f04af7-733b-4ee1-a86b-461c2301e9f2.png) https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=15039%3A279168 @laurenluz

In this pic

**Comment by maryjaf** [comment]
> @maryjaf can you check it again? I fixed the font sizes. but what do you mean by this? ‍`i didn't see the copy icon in this page according to the etched designs` this is Figma: ![image](https://user-images.githubusercontent.com/17097576/201970231-3f0d2480-68ec-4099-befe-600ec4dfb286.png)

<img width="914" alt="image" src="https://user-images.githubusercontent.com/111529185/202121489-9156ad6c-e6c8-4bcc-859a-6d138507a8db.png">
<img width="1348" alt="image" src="https://user-images.githubusercontent.com/111529185/202121650-c0fa01ff-cd5c-45ad-aa1a-bf34b86d00b9.png">
I think that the display of project numbers needs to be modified and be similar to the font and other numbers on the page

**Comment by laurenluz** [comment]
Actually, perhaps we should switch the two entries....

So from left to right it is:
- Projects Boosted
- GIVpower <-- we should change this from "Total Amount of GIVpower" to just "GIVpower" because it is long & redundant

@MohammadPCh can you fix it?

**Comment by MohammadPCh** [comment]
@laurenluz sure :)

**Comment by maryjaf** [comment]
Thanks @MohammadPCh The display of PROJECTS BOOSTED & GIVPOWER has been fixed but  in user page for a moment iI see the givpower  "--" as a below pic ,plz check this

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/111529185/203526734-b0d60a7e-b41b-4e62-8fe6-f72073fea863.png">

**Comment by MohammadPCh** [comment]
@maryjaf It should be a temporary problem. when we can't get user GIVpower, we show 2 dashes as a placeholder.
![image](https://user-images.githubusercontent.com/17097576/203556933-125cd7b7-c424-4522-b154-199949494751.png)

**Comment by maryjaf** [comment]
Yes the GIVpower shown after about 1 second maybe it's about my connection @MohammadPCh
