### ISSUE TITLE
GIVpower Boosting | copy fix in My account

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1777]
Change "Boosted Projects" to "My GIVpower" in My Account

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/343c1564-288f-4a2d-9166-418a1b7173ea)

**Comment by divine-comedian** [comment]
should be resolved in https://github.com/Giveth/giveth-dapps-v2/commit/bd25079ce22b9ebf5ee291aa3c5a4581c8ba3c83
