### ISSUE TITLE
Trying to post an update to my project, get "error" but it is posted anyway

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1785]
**Describe the bug**
When trying to post an update to my giveth project, I get "cannot read properies id null". And it seems like it doesn't get posted... but if I refresh the page... it was posted.

**To Reproduce**
1. Go to 'My project'
2. Click on any particular project you own 'View'
3. Click on the "updates" tab
4. Write out an update
5. Submit update
6. See error, although update is posted.

**Expected behavior**
I would like the update to be posted w/ no confusing error.

**Screenshots**
Sorry, the moment passed and I didn't take a screenshot. Here is my console though:
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/e082f79e-522d-473b-9759-17c89367ddcb)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Brave
 - Version  v1.45.118

**Additional context**
I think this may be related to my having not lowered shields. but we should still try to fix the problem.. I only know it could be related because I know all kinds of things about giveth.

@mateodaza this is a very oooold issue that apparently is STILL happening
cc @MoeNick

**Comment by mateodaza** [comment]
I'm not able to replicate this on chrome nor brave... I'll keep taking a look and see what may be
