### ISSUE TITLE
Allow smart contract addresses as project recipient 

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#1786]
Now that we have the ability to add an address for each chain, we no longer need to limit smart contract addresses.

I am currently adding them manually by request and would love if this process could be simplified by removing this limitation. 

I thought there was already an issue for it but I cannot find it... so I apologize if this is a duplicate.

![image](https://user-images.githubusercontent.com/74267818/200743953-04d3c4c5-2137-41e9-b076-9d6c63a63525.png)

**Comment by CarlosQ96** [comment]
@mohammadranjbarz just tagging us to not forget this issue.

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz just tagging us to not forget this issue. Gotta discuss it first in a call.

Nice, so we'll talk

**Comment by MoeNick** [comment]
I think it's resolved now
