### ISSUE TITLE
Show project recipient address even if they have not received any donations

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#1787]
If a project has not received a donation yet, I cannot see their wallet address(es) without looking it up in the AdminBro.
Can we display the wallet address(es) even if there are no donations?

Without donations:
![image](https://user-images.githubusercontent.com/74267818/200745199-df9f1c8c-df1c-49c3-bd75-957d0653fb10.png)

With donations:
![image](https://user-images.githubusercontent.com/74267818/200745468-e254f294-cbf3-4496-866c-b310a1d4d376.png)

**Comment by divine-comedian** [comment]
+1 on this issue - can we fix it @MoeNick ?

**Comment by MoeNick** [comment]
Sure @RamRamez can you jump into it?

**Comment by RamRamez** [comment]
I fixed it in PR #2049 
Now donation will be shown zero and donation table won't be shown. Is this ok?

![image](https://user-images.githubusercontent.com/73441857/213461789-940506e5-ab60-4d3f-863b-e8132ddf3033.png)

**Comment by WhyldWanderer** [comment]
Can it say "Be the first to donate!" instead of "$0"?

**Comment by RamRamez** [comment]
I changed the copy
![image](https://user-images.githubusercontent.com/73441857/213881217-326dc289-9c86-489e-91b5-c6e201a48ca1.png)

**Comment by MoeNick** [comment]
@maryjaf pls confirm

**Comment by maryjaf** [comment]
I checked on stg and now the wallet address is shown even if there are no donations

> @maryjaf pls confirm

**Comment by RamRamez** [comment]
I read that from the DB. As you see, you have no donations but your totalDonations is `1` in DB
![image](https://user-images.githubusercontent.com/73441857/214338623-d2f1ff7c-55a1-4eb0-a20f-ca7c4e8521d6.png)

**Comment by maryjaf** [comment]
> @maryjaf I read that from the DB. As you see, you have no donations but your totalDonations is `1` in DB ![image](https://user-images.githubusercontent.com/73441857/214338623-d2f1ff7c-55a1-4eb0-a20f-ca7c4e8521d6.png)

Yeah I edited this manual from admin bro and changed the total donation of project
this scenario isn't happened on production by admin user?

**Comment by RamRamez** [comment]
@mohammadranjbarz Is it ok to change total donations from admin bro?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz Is it ok to change total donations from admin bro?

You are right, we should not allow it, I changed admin-bro and don't allow admin to update `totalDonations`
