### ISSUE TITLE
GIVpower Boosting | GIVpower on Project Single Page should show current GIVpower on that project and should update often

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1800]
**Describe the bug**
I boosted the project "unique care connect inc" with around 400k GIVpower, but my GIVpower is not listed in the GIVpower tab for that project.

**To Reproduce**
1. Boost a project
2. Click on it's GIVpower tab
3. See that your GIVpower is not shown
4. Go to "My GIVpower"
5. See that your GIVpower is shown
6. Realize that there is a problem haha

**Expected behavior**
My "boosting" should appear in the GIVpower page of the project right after I boost it. (I should not have to wait until the next round for my boosting to appear).

The GIVpower total amount should be the "current" GIVpower... not the GIVpower from the previous round.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/ebc9f875-0eee-438a-871b-98f2df371543)

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/3236b7bf-06f0-41ae-98ff-972509c68345)

**This happens on which Boosting Section?**
- [ ] Project's Card - GIVpower Rank
- [ ] Project's GIVpower ranking
- [x] Single Project Public View | Boost Button
- [ ]  Single Project's owner view | Boost Button
- [ ]  Single Project's View | Givpower tab (Hall of fame, Total Boosted) 
- [ ] Boost Modal for a specific project
- [ ] Boost Succeeded
- [ ] My Account | Boosting Tab: list of boosted projects
- [ ] My Account | Delete a Boosted Projects
- [ ] My Account | Edit boosting allocations
- [ ] My Account | Success editing allocations
- [ ] My Account | Success editing allocations. 

**Additional context**

The GIVpower on any project should be dynamic... It should show the total GIVpower on that project in that moment... not the GIVpower on that project at the last round.

@aminlatifi @mohammadranjbarz @MohammadPCh - I'm not sure if this is a frontend or a backend issue, maybe you can tell me who should be assigned.

**Comment by laurenluz** [comment]
related to #1803

**Comment by laurenluz** [comment]
related to #1741

**Comment by aminlatifi** [comment]
@laurenluz We tried to implement what is inferred from the [GIVpower spec](https://docs.google.com/document/d/1NpyiETNClSw2BGLqE4ucr2eem5VtmZcIpHzFneC0ciE/edit#heading=h.jd4kbc7lrjwy).  This requirement (dynamic update) is not aligned with what is implemented and design, before having it we need to define the whole logic. Then go for implementing it.

**Comment by laurenluz** [comment]
@MohammadPCh @mohammadranjbarz @aminlatifi 

We should update the project single page so that it shows the current GIVpower on that project, and so that it dynamically updates.

This should not change how we are calculating our rank (which is correct right now, using average GIVpower from the snapshot.

From @mohammadranjbarz 

> Frontend currently uses getPowerBoosting for getting current boostings of  a user, you can pass projectId instead of userId and call it in single project view then you will get current power boostings of a project, but these just have percentages of users  ,but as we dont have current givPower balance for those user, you have to call  a subgraph to get user's balances ( our subgraph support getting an array of user's addresses and get balance of them so you just need to call one request for that purpose)

From @aminlatifi 

> Yeah, we can only get the user percentage and multiply it to the user's GIVpower balance we have already fetched from subgraph

This is the conclusion of our [discussion in Discord](https://discord.com/channels/679428761438912522/1041773251946364968/1041781795735228477)

**Comment by maryjaf** [comment]
Should these conditions be expected when a boost is removed from the project?
That is, when I delete the boost of Project X in my givpower list and at the same time it will be removed from my list,
I expect at the same  time that my user's boost will be deleted in the boost list of the project? @laurenluz

**Comment by laurenluz** [comment]
Yep! When you as a user remove your GIVpower from project X, it should be removed from your list in "My GIVpower" and should be removed from the GIVpower list on Project X's page. @maryjaf

**Comment by divine-comedian** [comment]
testing on https://giveconomy.vercel.app/project/testfilterr

in what case should this show as the project's projected rank? it shows as :rocket: -- what does this mean??

![image](https://user-images.githubusercontent.com/67759413/203167435-bdf034ab-639a-4cd1-812d-58d81ff5b68b.png)

**Comment by maryjaf** [comment]
Regarding the incorrect calculation of Give Power Project, I registered #1855 issue that it is related to this issue

**Comment by divine-comedian** [comment]
> yep @divine-comedian - the rank should only be "--" if it doesn't have a rank yet... i.e. it is its very 1st round.

In the photo above however the projected rank is `--` that means it will be unranked in the next round? 

Maybe this is a late change but does say `Unranked` instead of -- give more context to the user?

**Comment by laurenluz** [comment]
you don't think it will look weird on the projects & homepage to say  " 🚀 unranked "  on the projects cards?

**Comment by divine-comedian** [comment]
> you don't think it will look weird on the projects & homepage to say " rocket unranked " on the projects cards?

maybe - there would have to be some design reorganization - I don't think it's urgent but for me when I see `--` I don't think that the project is unranked but rather that somehow the page couldn't get the ranking or the page is broken

**Comment by laurenluz** [comment]
@MohammadPCh - what do you think we should do? you've got all the wisdom here :)

**Comment by MohammadPCh** [comment]
@laurenluz @divine-comedian thanks, I think the `--` is enough for now, because we show it in 3 places and if we want to change it, we should consider all of them in all responsiveness. but maybe after the release and seeing users' feedback we can think about it.

**Comment by laurenluz** [comment]
agreed.
