### ISSUE TITLE
GIVpower Boosting | "Are you sure" prompt if the user is allocating 100% of their GIVpower to a project (that is not the first one)

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1801]
GIVpower boosting works such that your first project always gets 100% of your GIVpower.
Every project boosted later, gets some %, and the % on other projects is adjusted proportionally.

If a user has boosted projects in the past... and is trying to boost a *new* project with 100%, we should inform the user that they will lose all their previous allocations!

As it is now, with a quick click of a button, all my other GIVpower project allocations can be erased while one new project can get 100%.

For example... imagine that I had my GIVpower split between 5 projects...

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/ac190587-2f49-442f-aa50-19f72a58bbc9)

Then I go to boost another... I select 100%...

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/8ebe1ea5-575f-47bd-8c48-a34bbc010ba1)

click confirm and...
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/ba19d776-5fdb-4619-9eeb-8ea14d7bdc36)

BOOM... lost all my hard work
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/2dc79bd4-299b-4743-908f-5ee9ee503bc8)

I think we can solve the problem with an extra modal that pops up when you click "confirm" after selecting 100% that says...

"Are you sure?"
"If you boost this project with 100% of your GIVpower, you will remove your GIVpower from all the other projects you boosted!"
"Confirm"
"No, take me back"

@Tosinolawale @mosaeedi - do you have any objections to this? If you're ok, can you make a quick mockup of the modal?

**Comment by Tosinolawale** [comment]
There is no need to add another modal to the flow. That is introducing too many steps when we can still work with the Modals we already have. @laurenluz

**Comment by Tosinolawale** [comment]
![Boosting _ First time boost](https://user-images.githubusercontent.com/35389241/201764128-db0c3eea-34c5-4059-b714-d36e8de1116e.png)

When you are Boosting a project with 100% for the first time, the design still stays as it is

**Comment by Tosinolawale** [comment]
![Boosting _ Confirm active](https://user-images.githubusercontent.com/35389241/201764446-334f51db-5813-4888-8615-add27baa18e5.png)
Same with subsequent allocation

**Comment by Tosinolawale** [comment]
![Boosting _ First time boost](https://user-images.githubusercontent.com/35389241/201764594-bb902024-4849-4fb3-90c2-24ece7ca7f81.png)

https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=15236%3A273248&t=VCnQBOuiAZUU4PgG-0

But here is the new mockup for this particular edge case. When a user who already has GIVpower allocated to various projects decides to allocate 100% either intentionally or by mistake, the information toast changes to red with the warning text, alerting users to their actions. 
If the user takes action and adjusts the slider back to less than 100%, the warning box reverts back to status quo. @laurenluz

**Comment by laurenluz** [comment]
Sounds good @Tosinolawale !

Just, a couple of small adjustments on the copy (already done before):

![image](https://user-images.githubusercontent.com/75490971/201799064-e110b67f-26e7-472b-a8bd-a153ebf220ba.png)

Is that ok?

**Comment by laurenluz** [comment]
@MohammadPCh - can you take this? It's basically a new condition for the boosting modal.

If the user is trying to allocate 100% of their GIVpower to a project (and it's not their first/only boost), the copy in the modal should change when the slider reaches 100% and the box should be red, as above and in the figma,

**Comment by MohammadPCh** [comment]
I left a PR for it.
