### ISSUE TITLE
GIVpower Boosting | Boosting Modal Improvements

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1802]
- [x] The grey text "Allocated to previous projects" has no meaning and should be deleted
- [x] The text in the blue box should be improved:

"When you allocate a percentage of your total GIVpower to this project, the GIVpower you have on other projects will decrease proportionally. You can review and manage your GIVpower allocations in **My GIVpower**"

- [x] The text at the bottom should be improved:

"Manage your GIVpower"

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/28ab0288-b0e3-4860-9392-dd514eb6d493)

**Comment by laurenluz** [comment]
Oh no @MohammadPCh I'm so sorry, I forgot an "r" on "your" 🤦 

When you allocate a percentage of your total GIVpower to this project, the GIVpower you have on other projects will decrease proportionally. You can review and manage your GIVpower allocations in  [My GIVpower](https://giveconomy.vercel.app/account?tab=boosted)

![image](https://user-images.githubusercontent.com/75490971/201749976-14e0bb16-6bbd-4a7d-961e-665ce7cfa133.png)

**Comment by laurenluz** [comment]
Everything else looks great on GIVeconomy

**Comment by MohammadPCh** [comment]
@laurenluz  I fixed it directly without PR. so you can test it in the GIVeconomy now.

**Comment by maryjaf** [comment]
Thanks @MohammadPCh all three items are correctly changed
