### ISSUE TITLE
RegenFarms Design Improvements

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1806]
As RegenFarms Expands, there are several design issues that we did consider / never fixed - and are now becoming necessary to improve.

- [ ] It would be nice to see all active RegenFarms in the same page, regardless of what network the user is connected to ( #821 )
- [ ] It saves the user gas to harvest from the a farm card (rather that the stream harvest button)  - we might want to add a tooltip or something about this ( #817 )
- [ ] when a RegenFarm ends, we are archiving it, but it does not make sense to hide the RegenStream under the archive toggle... because users will coninusouly getting rewards until the end of the RegenStream - we need to consider some way of showing these flowing RegenStreams more prominently, even if there is not active rewards program. (new!)
- [ ] we may want to improve the design for when a DAO has multiple different farms and only a single RegenStream - we made quick fix for this already (on production) but it's a bit weird when the user toggles the archive/unarchived button

@Tosinolawale @mosaeedi

**Comment by laurenluz** [comment]
@Tosinolawale - have we sorted this out yet?

cc @mosaeedi

**Comment by laurenluz** [comment]
@MoeNick would love your comments

**Comment by MoeNick** [comment]
@Tosinolawale can you provide the link here to discuss.

**Comment by laurenluz** [comment]
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=16238%3A298722&t=qFxISZdVQy3vnz8f-4

**Comment by laurenluz** [comment]
We should be pretty good to go on this. Only missing responsive guide & disclaimers for when projects are connected to the wrong network.

Here is the [figma](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=16238%3A298722&t=NZP2caNTF4ifAMgC-4)

@MohammadPCh - do you want to pick this up? Are you missing anything to get started?

**Comment by MohammadPCh** [comment]
@laurenluz Sure, leave it to me :)
it's easier to have responsive designs, then start implementing them since it helps to decrease duplicate code and repeated work.
so... we gonna separate regen farm stake cards and stream cards, am I right?

**Comment by laurenluz** [comment]
yep! separate regenfarm stake cards and stream cards :)

I'll ask designers for responsive version

**Comment by Tosinolawale** [comment]
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=16238%3A298722&t=ntfUJ5MmXFuyt4oe-1
Regen farm with Responsive and mobile guides

**Comment by laurenluz** [comment]
yahoo!! Ready for this one @MohammadPCh ?

**Comment by MoeNick** [comment]
We already started PFP @laurenluz , but let's see if @MohammadPCh can manage the work load of front-end better :)

**Comment by laurenluz** [comment]
ooh ok - well this can be done after PFP. @MohammadPCh @MoeNick

**Comment by laurenluz** [comment]
@Tosinolawale - when you adjust the view for when you are on the wrong chain/not connection - can you please share it here?

**Comment by Tosinolawale** [comment]
![Staking card](https://user-images.githubusercontent.com/35389241/225323432-aa073c9e-dd74-4cd0-bb76-e511333e1fb5.png)
![Staking cards](https://user-images.githubusercontent.com/35389241/225323461-425b81b4-eab5-431d-a3f0-b538717c884c.png)
You mean this @laurenluz ?
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/GIVeconomy?node-id=19017%3A262084&t=HxAkJ6OY3GOt0AaL-1

**Comment by maryjaf** [comment]
These two images are different from Figma
Change according to figma or stay the same? @laurenluz @MohammadPCh 
giveconomy:
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/3cbd73de-2c6f-4099-8f0d-5489fc9589e9)

![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/0a87d0c2-ed74-4641-a17c-3d3f0e36aa18)
