### ISSUE TITLE
After donating, I should be able to share on socials that I am a donor!

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1809]
Didn't we have the option to share on twitter? I want to tell everyone!!

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/bd305658-138b-447b-9276-56eab07e643f)

@mateodaza - what happened???

**Comment by mateodaza** [comment]
@laurenluz for some reason there was a condition to not show the social box for givback eligible donations. Let me fix that :)

**Comment by MoeNick** [comment]
@maryjaf can you approve it, please?

**Comment by maryjaf** [comment]
Yes, I check this and now I can share on twitter, Linkedin and facebook

This project is raising funds in crypto on @givethio! 🙌
Donate directly on Ethereum Mainnet or @gnosischain w/ no fees or intermediaries.👇 https://staging.giveth.io/project/the-teen-project-inc #Giveth

**Comment by MoeNick** [comment]
@maryjaf please re-test with also a non verified project. You should not see you're eligible for GIVback. but you can share on socials.

**Comment by maryjaf** [comment]
> @maryjaf please re-test with also a non verified project. You should not see you're eligible for GIVback. but you can share on socials.

Should we see some thing else on this page? (the below project is n't verified)
<img width="975" alt="image" src="https://user-images.githubusercontent.com/111529185/215250974-75857309-c3f1-4467-8a3f-f58622cf25f5.png">
