### ISSUE TITLE
Fewer clicks to donating

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#1810]
**As a random giveth donor, I want to quickly find the project i am donating to, so that I don't waste my time scrolling and clicking around. Every extra click is an opportunity for me to get distracted and not donate.**

We should minimize the clicks a donor needs to make to get to the project they want.

The search bar should be there on the giveth.io home page. Having to click projects is annoying.

<img width="1423" alt="Screen Shot 2022-11-13 at 2 43 37 PM" src="https://user-images.githubusercontent.com/14945613/201543863-f6114e24-56e9-451c-aaea-30294fd6cd9c.png">

When i click the search button and start typing, nothing happens... I should click that magnifying glass and the curser should pop up so i can start typing without a second click.

**Comment by divine-comedian** [comment]
We fixed this in #2369
