### ISSUE TITLE
Support page styling problems

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#182]
Support page is not following the provided design and needs a styling fix. 

https://giveth-dapps-v2.vercel.app/support

Implementation:
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/6f55a7aa-0abb-4848-b7a8-caf89289a676)

Design:
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/08b5c150-71a6-4ad0-94ac-e982e30f718a)

https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=1908%3A65528

**Comment by laurenluz** [comment]
looks good
![image](https://user-images.githubusercontent.com/75490971/159958494-58210e6c-3aea-4695-95cb-cdbdd21c418a.png)
