### ISSUE TITLE
GIVpower Boosting | Update on GIVpower modals

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1822]
- [x] We should remove "Coming Soon" from the confirmation modal, and add a button... Copy should be:

Use your GIVpower to support projects on Giveth while earning rewards. 

Button: Boost Projects (links to projects page)

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/1eae7713-45c2-4499-856d-356dbc77a476)

- [x] Copy on GIVpower back of card should say:
You get GIVpower when you stake & lock GIV. Use your GIVpower to boost projects on Giveth to influence their rank. Donors to top-ranked projects get more GIVbacks.

With GIVpower, you can support the projects you believe in, without sacrificing!

Boost Projects (links to projects page)
Learn More (links to docs)

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/c185d450-8f84-4bb4-a6cf-38c1328d9996)

@MohammadPCh - didn't we have this already developed somewhere? I feel like I am recreating the same issue and rewriting copy that I did already before.

**Comment by MohammadPCh** [comment]
@laurenluz final result:
![image](https://user-images.githubusercontent.com/17097576/201901217-f17f7c35-b9be-4b4f-8ec9-8fc05576457e.png)
![image](https://user-images.githubusercontent.com/17097576/201901324-3e2afc05-bf48-47b8-a176-425167987d6c.png)
oh, we have another coming soon here:
![image](https://user-images.githubusercontent.com/17097576/201902229-641a2f55-bf40-4984-b83b-e64eee9efc8a.png)
can you provide a copy for this?

**Comment by laurenluz** [comment]
> I changed it to this: GIVpower allows you to support verified projects on Giveth while earning rewards.

Your copy is great @MohammadPCh !! Thanks for finding this one!!

**Comment by maryjaf** [comment]
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/d163cebc-8917-4eec-9bb2-f6c4bad7055c)
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/e06d2a07-3b95-4286-a9d4-882f9e834882)
"support project" in pic 1 and "support verified project" shown in pic 2, which one is true?
I think it would be better to show the "support verified project" in the pic 1

**Comment by maryjaf** [comment]
> ![image.png](https://camo.githubusercontent.com/2878aaa7c3d86b6aa566f5879885647bbaf4d3f00dfd8936933c2d8e280890dd/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f64313633636562632d383931372d346565632d396262322d663663346261643730353563) ![image.png](https://camo.githubusercontent.com/db05b1e120ed39f6d4bc29c59d331931620d745ffd041f37f53d61b36435c452/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f65303664326130372d336239352d343238362d613964342d383832663965383334383832) "support projects" in pic 1 and "support verified projects" shown in pic 2, which one is true? @MohammadPCh I think it would be better to show the "support verified project" in the pic 1

@laurenluz

**Comment by laurenluz** [comment]
@divine-comedian can you make this little change to add "verified" in on pic 1?

**Comment by divine-comedian** [comment]
fixed in https://github.com/Giveth/giveth-dapps-v2/commit/ba94282784bfc271380aa9772f9083adeb783209
