### ISSUE TITLE
Switch to Gnosis from Georil isn't work

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#1823]
**Describe the bug**
Some time switch to Gnosis from Georil isn't work on staging

**To Reproduce**
1. The network set on Georil
2. Go to one project with gnosis address only such as "https://staging.giveth.io/donate/category2"
3. Click on 'Donate'
4. The modal "Switch to Gnosis Chain" is shown
5. Tap on 'Switch network' and it isn't work

**Comment by RamRamez** [comment]
also this button is not working
![image](https://user-images.githubusercontent.com/73441857/201903794-62e67dac-09ba-4d23-9d98-a3c228e9d537.png)

**Comment by RamRamez** [comment]
another problem: network names and icons do not match
![image](https://user-images.githubusercontent.com/73441857/201911806-1df046b5-4a48-4a0c-824d-3c33f12ef00c.png)

**Comment by maryjaf** [comment]
> also, this button is not working in your scenario ![image](https://user-images.githubusercontent.com/73441857/201903794-62e67dac-09ba-4d23-9d98-a3c228e9d537.png)

yeah "switch network"  option isn't work in modal and donation page when switch from georil to gnosis
but this scenario is okay for switching from gnosis to georil!

**Comment by RamRamez** [comment]
> > also, this button is not working in your scenario ![image](https://user-images.githubusercontent.com/73441857/201903794-62e67dac-09ba-4d23-9d98-a3c228e9d537.png)
> 
> yeah "switch network" option isn't work in modal and donation page when switch from georil to gnosis but this scenario is okay for switching from gnosis to georil!

on Goerli network on category2 project, click on `Projects from Giveth only accept donations on Gnosis Chain.` on it's not working
