### ISSUE TITLE
GIVdrop Claim | Remove GIVdrop from GIVeconomy design (and replace it?) - Revamp GIVeconomy Homepage

### ISSUE THREAD

**Issue by Cotabe** [Giveth/giveth-dapps-v2#1830]
This might not be a good issue...

As a new person in the GIVeconomy I got excited to see a button to claim a GIVdrop and then got a bit sad I missed it.

I ask myself should that still be there? But maybe it should because there are some people yet to claim their GIVdrop.

**Comment by laurenluz** [comment]
Also - we are making a new launch video for GIVpower - not sure if we will want to still keep the GIVeconomy one there.

**Comment by Cotabe** [comment]
I think this update is a good idea :)

Some thoughts:

Should we move the GIVpower modal to the GIVpower tab? If so, should we change the GiVfarm tab name to Regen Farms?

should the GIVgarden tab change to GIVernance to explain and link to all our governance mechanisms: Forum, Garden, Snapshot, NRGIV and Tokenlogs.

I like the GIVeconomy overview, but agree that it’s repetitive. I would suggest to aggregate the three sections in one with the following headers:

1. GIVtoken. I would leave this section as it is. I think it’s great to have it explained. I would just change the GIVdrop CTA for a get GIV CTA directed to a DEX.

2. GIVe and receive. I would keep this explanation. “Donate to empower change-makers that are working hard to make a difference. Get GIVbacks when you donate to verified projects.” 

Add the GIVbacks modal with 2 CTAs; 1. Donate now (linked to the matching fund), 2. See projects.

Add a GIVstream modal with an explanation similar to “All GIV you earn; GIVbacks, GIVpower APR and others are streamed to your account till December 24th, 2026. Your stream can only increase the more you support the GIVeconomy during this time”

3. Earn. Stake your GIV to support projects and curate the platform through GIVpower. Earn tokens from other for good projects providing liquidity to in the Regen Farms. 

Add a GIVpower modal, I think it should say this “ Support verified projects using “Boost”. Projects backed by GIVpower will benefit from matching funds & more GIVbacks for their donors.” with a CTA to where the GIVpower staking modal is, maybe the GIVpower tab.

Add a Regen Farms modal, I think it should say something like “Explore a multiverse of for good projects changing the world and earn rewards  in DAOs tokens for providing liquidity or supporting their economy” CTA to the GIVfarm or Regen farms tab.

4. GIVern. I would suggest something like “The GIVeconomy empowers our collective of projects, donors, builders and community members to vote on decisions and budget of the DAO to build together the Future of Giving.” CTA join the GIVernance (Link to the GIVernance tab)

LMK what you think @laurenluz

**Comment by markoprljic** [comment]
The Overview page should be simple and straightforward to understand for any web user (as much as possible). We should avoid jargon and going to much into details. This page should explain the idea and concept behind the GIVeconomy. From here, we invite user to learn more about each section.

**Comment by Cotabe** [comment]
When I was writing the script for the GIVpower walkthrough, I realized it would be good to have a more visible (and flashy) CTA to buy the GIV token.

Also, the current link takes them immediately to honeyswap (https://app.honeyswap.org/#/swap?outputCurrency=0x4f4F9b8D5B4d0Dc10506e5551B0513B61fD59e75), which is great if they are already on Gnosis.

However, maybe it would be good to have 2 options. 

1) For those on Gnosis - Honeyswap
2) For those not on Gnosis - A how-to blog, landing page or video (I talk about this on the GIVpower video)

The content should say that:
2.a) For those in other EVM-compatible blockchains, it's easy:
1) Get XDAI (to pay fees)
2) Buy GIV with another token. 
*Note: transferto from LiFi is a DEX and bridge aggregator with amazing UX for both steps (https://transferto.xyz/swap).

2.b) For those that do not have ETH or anything else, I think the simplest process is:
1) Download a wallet like metamask.
2) Buy in the wallet ETH or DAI in Optimism to avoid high fees. Or polygon or other, unfortunately, there is no direct option to Gnosis in Metamask. 
3) Bridge and exchange using transferto.xyz for example.
