### ISSUE TITLE
Infinite scroll for notifications page

### ISSUE THREAD

**Issue by alireza-sharifpour** [Giveth/giveth-dapps-v2#1832]
Based on the @mosaeedi's opinion, we should implement an infinite scroll for notifications center like the one we have in projects page.

**Comment by divine-comedian** [comment]
Where can this issue be tested?

**Comment by alireza-sharifpour** [comment]
> Where can this issue be tested?

You can test it here @divine-comedian 
https://notification-center-13.vercel.app/

**Comment by divine-comedian** [comment]
> > Where can this issue be tested?
> 
> You can test it here @divine-comedian https://notification-center-13.vercel.app/

thank you - are there any tricks to quickly generating many notifications?

**Comment by alireza-sharifpour** [comment]
> > > Where can this issue be tested?
> > 
> > 
> > You can test it here @divine-comedian https://notification-center-13.vercel.app/
> 
> thank you - are there any tricks to quickly generating many notifications?

The only way I use it is to donate to projects and see the notification. It's not an optimal way!
Maybe @mohammadranjbarz knows a better way.

**Comment by mohammadranjbarz** [comment]
@divine-comedian  @alireza-sharifpour 

Another way to create lots of notifications is to use admin bro and make your projected, listed, verified, unverified, activate, cancelled, ....

Another way is to create notification by calling a webservice ( it's the webservice that impact-graph use that for creating notifications) so if you wanted to use this way DM me I'll explain to you, but I think admin-bro way is easier
https://staging.notification.giveth.io/docs/#/Notification/SendNotification

**Comment by divine-comedian** [comment]
> @divine-comedian @alireza-sharifpour
> 
> Another way to create lots of notifications is to use admin bro and make your projected, listed, verified, unverified, activate, cancelled, ....
> 
> Another way is to create notification by calling a webservice ( it's the webservice that impact-graph use that for creating notifications) so if you wanted to use this way DM me I'll explain to you, but I think admin-bro way is easier https://staging.notification.giveth.io/docs/#/Notification/SendNotification

I think I can do the first option pretty easily, thanks!
