### ISSUE TITLE
GIVpower Boosting | Exclude deactivated projects from ranking calculations

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1839]
@mohammadranjbarz - we should exclude the deactivated projects from ranking calculations. The should keep their GIVpower on them (because they might keep the verified status), but should not come up in the ranking order.

**Comment by mohammadranjbarz** [comment]
@MoeNick  @maryjaf 
It's on Staging , you can test it

**Comment by mohammadranjbarz** [comment]
@MoeNick  @maryjaf 
It's on Staging , you can test it

**Comment by maryjaf** [comment]
When I deactivate the project, the rank and boost option are not displayed correctly in the project details and as before, the deactivate project is not displayed on the project page
But I have a question. I deactivated the project at 18:12. The ranking was like this
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/b08b0328-63e8-40ed-a321-bbef1b8251ef)
After a few minutes, it changed according to the picture
This is true?current and projected rank? @mohammadranjbarz @laurenluz 
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/8e8cb998-922a-4f9c-910e-2e3209cf6910)

**Comment by laurenluz** [comment]
if a project is deactivated, it should have current rank "--" and projected rank "--" right away... until it is reactivated. @MohammadPCh @mohammadranjbarz cc @maryjaf 

> Is it accepted that when the givpower of one of the project changes or one project deactivate or un-verify or every change about boosting and rank, Expected Rank(Projected Rank) for all projects change to "--"until next snapshot or round

The expected rank of all projects shouldn't become "--" just because one gets deactivated. We should just exclude the one deactivated (or cancelled or unverified) project from our calculations... so every other project that was ranked below it might move up one rank. @maryjaf

**Comment by mohammadranjbarz** [comment]
@laurenluz  @maryjaf 

1. Now I changed it to update raning immediately after activate/deactivate 
2. @MohammadPCh fixed the issue of showing future rank when `totalPower` is `0` and rank is the last
3. I couldn't reproduce the bug that Maryam said , deactivate/activate project doesn't affect other project's rankings , but @maryjaf  if you see that happens we can have a quick call to find the cause ( I couldn't reproduce the bug)

**Comment by maryjaf** [comment]
> * @MohammadPCh fixed the issue of showing future rank when `totalPower` is `0` and rank is the last

Thanks @mohammadranjbarz @MohammadPCh I tesed and the first problem about showing last rank in projected rank has been solved and changed to "--"
and the second scenario I couldn't reproduce it and it seems has been resolved

**Comment by maryjaf** [comment]
> * @MohammadPCh fixed the issue of showing future rank when `totalPower` is `0` and rank is the last

Thanks @mohammadranjbarz @MohammadPCh I tesed and the first problem about showing last rank in projected rank has been solved and changed to "--"
and the second scenario I couldn't reproduce it and it seems has been resolved

**Comment by CarlosQ96** [comment]
@maryjaf was this a project who's last rank was like that before Mohammad's fix or can you reproduce it still?

 I think it's because since he changed migrations and code, some things might be fixed when done NOW, but old data remained the same.

**Comment by laurenluz** [comment]
@MohammadPCh is this fixed now?

@maryjaf - can you retest?

**Comment by maryjaf** [comment]
> @MohammadPCh is this fixed now?
> 
> @maryjaf - can you retest?
Yeah I tested this and the above problem has been fixed
and I retested all scenarios about deactivate ,cancel & unverify after the changes related to the Projected Rank are ready to be tested (#1904)

**Comment by maryjaf** [comment]
> * @MohammadPCh fixed the issue of showing future rank when `totalPower` is `0` and rank is the last

The second item happend again
I deactivate a project (alirezatest)and I expected that projected rank changed to "--" but in this example changed into "26" 
<img width="1406" alt="image" src="https://user-images.githubusercontent.com/111529185/206872474-09175643-eea1-47ae-b0b7-708602728ecd.png">
 @mohammadranjbarz @MohammadPCh

**Comment by maryjaf** [comment]
Thanks @MohammadPCh this problem has been resolved
