### ISSUE TITLE
Remove photo in create project screen

### ISSUE THREAD

**Issue by mosaeedi** [Giveth/giveth-dapps-v2#184]
We need to update this section to make it clear for users that the X icon at the right,

![Screen Shot 2022-03-14 at 2 38 57 PM](https://user-images.githubusercontent.com/13708322/158174327-222406e8-f580-470f-9d29-28193d75a1a4.png)

delete the uploaded/chosen background.

### Here is the updated style and behavior

[Remove uploaded/chosen photo](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=6114%3A129258)

**Default state | Deactive**
![Screen Shot 2022-03-14 at 3 44 13 PM](https://user-images.githubusercontent.com/13708322/158174539-1e08988c-13ac-40d2-8171-93dbd0faf664.png)

**Active state | when there is a photo to delete**
![Screen Shot 2022-03-14 at 3 45 10 PM](https://user-images.githubusercontent.com/13708322/158174670-608f27b2-4da9-401c-815a-6208b3955b0a.png)

**In case you missed it!**
The remove button is separated from the rest of the list using a line separator

**Comment by laurenluz** [comment]
looks gud
![image](https://user-images.githubusercontent.com/75490971/159953232-93c54904-7e1f-460c-a0ed-9d3bb77c23a0.png)
