### ISSUE TITLE
GIVpower Boosting | Set up an interactive API on staging for testing GIVpower calculations

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1841]
@MoeNick @maryjaf - can you give ther requirements of what you need to perform tests, i.e. GIVpower at specific snapshots, rank at particular rounds, etc.

@CarlosQ96 can help to create this. @aminlatifi & @mohammadranjbarz can help him

**Comment by MoeNick** [comment]
@CarlosQ96 you need a talk how to implement it or it's clear for you?

**Comment by CarlosQ96** [comment]
Yeah I think the test api with various queries should return:
1. Current giv power.
2. Current distribution of givPower of a user.
3. Current PowerRank at a specific round.

**Comment by maryjaf** [comment]
> Yeah I think the test api with various queries should return:
> 
> 1. Current giv power.
> 2. Current distribution of givPower of a user.
> 3. Current PowerRank at a specific round.

In this API, do we also return the calculated expected rank for the next round after removing or adding Give Power for all project?

**Comment by CarlosQ96** [comment]
I have to check, but if it's posible to calculate it, I can certainly add it.

**Comment by maryjaf** [comment]
> I have to check, but if it's posible to calculate it, I can certainly add it.



> I have to check, but if it's posible to calculate it, I can certainly add it.

Thanks @CarlosQ96 
Do we have an initial contract for the input and response of this service? If yes please share it.
In this API, both user ID and project ID can be in body request? if yes, can we have  the amount of giving block for each user in the response ?

**Comment by laurenluz** [comment]
@CarlosQ96 - any update?

**Comment by CarlosQ96** [comment]
@laurenluz I am jumping back into this issue today, as I finished the others issues I had pending. 

Regarding @maryjaf when I have the full request/response of this service I will share it.
Also, Yes, the api will accept userID and projectID in body request for filtering. 

What do you mean by giving block?

**Comment by laurenluz** [comment]
@maryjaf - what did you mean by "giving block"?

@CarlosQ96 - how's this going?

**Comment by CarlosQ96** [comment]
So I am pushing today a PR for the following queries:

1. Getting the User powerBalances.
2. Querying the powerSnapshots to see what are the snapshots taken, Ids and the corresponding round.
3. Getting current Power Round.
4. Getting a User or Project PowerBoostings Percentages per round
5. Getting a project's future powers, (power rank, total power, round)
6. Getting a project's powers (power rank, total power, round)
7. Getting the User's or Project's PowerBoosts Amount per round

**Comment by laurenluz** [comment]
This is done right Carlos? Any issues come up from the API that we're not already aware of?

**Comment by CarlosQ96** [comment]
@laurenluz I think we can move to done. Maryjaf told me everything was ok. Let me know if you guys need anything else or any other info. 

Also I just merged today the process to archive old rounds so our performance doesn't degrade. So that's done too.

**Comment by maryjaf** [comment]
Thanks @CarlosQ96 
I tested these api and  passed
