### ISSUE TITLE
GIVdrop Claim frontend fix | Streaming amount in the Claim flow may be wrong

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1842]
As a user who has not yet claimed their GIVdrop can do so at this link: https://giveth.io/claim

They then go through the flow of all the simulators... and end up at the claim page w/ claim modal:
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/1938a139-8ce9-45d1-b861-b34c634d0771)

I think the "streaming amount" shown in the frontend here is actually not what the user has claimable at that time from their GIVstream... I think it is being calculated by some frontend hack.

This issue is not a huge priority, because we will end the GIVdrop on Dec 24, 2022 and hide this... but for the people trying to claim before Dec, this might be a little confusing.

If we have time, we can fix it.

@aminlatifi @MohammadPCh

**Comment by MohammadPCh** [comment]
@laurenluz I think @aminlatifi has resolved this problem.

**Comment by aminlatifi** [comment]
> @laurenluz I think @aminlatifi has resolved this problem.

I haven't touched it recently.

**Comment by laurenluz** [comment]
not worth fixing, let's just close it
