### ISSUE TITLE
Quick Fix, bad grammar in filter 

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#1845]
<img width="258" alt="Screen Shot 2022-11-17 at 12 20 33 PM" src="https://user-images.githubusercontent.com/14945613/202526972-215e8910-bf3d-48da-97b7-a3975311ecf9.png">

Should be:
"Accepts GIV"

and 

"Accepts Funds on Gnosis"

The other 2 are fine

**Comment by MoeNick** [comment]
I guess its on staging, is it? @MohammadPCh @alireza-sharifpour ?
