### ISSUE TITLE
Project Text Editor sucks - Feedback from a user

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#1846]
<img width="677" alt="Screen Shot 2022-11-17 at 3 45 00 PM" src="https://user-images.githubusercontent.com/14945613/202566408-82ec1a3d-6e95-431e-a262-d8d2a6761319.png">

I have also had this experience, that the spacing from this editor is not intuitive. Is it time for an upgrade?

**Comment by MoeNick** [comment]
@RamRamez can we change it to a better editor? 
@MohammadPCh do you have an idea?

**Comment by MohammadPCh** [comment]
@MoeNick  let me check it.
