### ISSUE TITLE
Getting error on grant edit "Eth address 0xXX is already being used for a project"

### ISSUE THREAD

**Issue by shayanb** [Giveth/giveth-dapps-v2#1847]
**Describe the bug**
Currently drafting a grant, looked at the preview and after second edits I cannot save the edits and the UI keeps giving me the following error on the top of the page:
"Eth address 0xXXXXX is already being used for a project"

**Screenshots**
<img width="861" alt="Screen Shot 2022-11-17 at 5 03 34 PM" src="https://user-images.githubusercontent.com/309108/202569744-0fec23af-6e72-4783-9fe2-e7aab539400b.png">

Error from the server:
```
{"errors":[{"message":"Eth address 0xXXXX is already being used for a project","locations":[{"line":2,"column":3}],"path":["updateProject"],"extensions":{"code":"INTERNAL_SERVER_ERROR"}}],"data":null}
```

**Comment by MoeNick** [comment]
@shayanb are you using this address somewhere else? even for a draft project? 
would you dm me your address? my discord handler is : MoeNick#1374

**Comment by MoeNick** [comment]
@shayanb are you using this address somewhere else? even for a draft project? 
would you dm me your address? my discord handler is : MoeNick#1374

**Comment by shayanb** [comment]
@MoeNick thanks for following up. It seems that there's an identical draft project on my profile but I think it was created when I clicked on Preview? not sure. I'll message you on discord shortly.

**Comment by MoeNick** [comment]
Seems its resolved 🙂
