### ISSUE TITLE
What is the GIVstream? in white background is unreadable 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#185]
In the reward menu, when click on ? icon, the GIVstream modal is shown, but it's ok on dark bg but unreadable on bright bg. 

![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/29131dba-711c-4381-abc9-4525263d5595)

**Comment by mosaeedi** [comment]
[https://www.figma.com/file/d3ciTS36toS9mra0RAPMe2/Giveth-Design-System-v0.1?node-id=2297%3A60139](https://www.figma.com/file/d3ciTS36toS9mra0RAPMe2/Giveth-Design-System-v0.1?node-id=2297%3A60139)

**Comment by laurenluz** [comment]
The background looks correct now.
