### ISSUE TITLE
Fail to resume verification "Response not successful: Received status code 400"

### ISSUE THREAD

**Issue by shayanb** [Giveth/giveth-dapps-v2#1852]
**Describe the bug**
I started the verification process a few days ago and now that I want to continue the process to the finish line I'm facing an error message.

**To Reproduce**
1. Go to the grant
2. Click on RESUME VERIFICATION
3. Page loads with this error message "Response not successful: Received status code 400"

**Expected behavior**
To be able to see the verification questions/forms and continue 

**Screenshots**

<img width="399" alt="Screen Shot 2022-11-21 at 5 24 38 PM" src="https://user-images.githubusercontent.com/309108/203170321-daf59718-92ec-4857-8ff3-6416d3120542.png">

<img width="1322" alt="Screen Shot 2022-11-21 at 5 21 10 PM" src="https://user-images.githubusercontent.com/309108/203170275-66b26f6f-2e11-4020-a5af-091b0a6020e3.png">

--------
Detailed Error message:
<img width="823" alt="Screen Shot 2022-11-21 at 5 25 39 PM" src="https://user-images.githubusercontent.com/309108/203170497-fe698a7d-8e2c-4d8c-89f0-2d9ee654c322.png">

**Comment by mohammadranjbarz** [comment]
@shayanb  @MoeNick 
Can you confirm that this bug doesn't exist anymore?

**Comment by shayanb** [comment]
@mohammadranjbarz my issue was resolved by redoing the verification process, don't know how to reproduce this but based on the hotfix code it should be resolved in the similar scenario. thanks.

**Comment by mohammadranjbarz** [comment]
@shayanb Thanks so much 

> @mohammadranjbarz my issue was resolved by redoing the verification process, don't know how to reproduce this but based on the hotfix code it should be resolved in the similar scenario. thanks.

@shayanb Thanks so much
