### ISSUE TITLE
hide pending toast modal after tx is successful

### ISSUE THREAD

**Issue by RamRamez** [Giveth/giveth-dapps-v2#1857]
@laurenluz requested a hotfix for production.
On donate modal, when there's only one tx, the blue toast that says `your donation is being processed` should be removed after the tx is mined and successful.
When there are two txs, the blue toast should be removed after both txs are successful and mined.
Also after both txs are mined, donate button should be changed from `donating` to `donate` but remain disabled.

![image](https://user-images.githubusercontent.com/73441857/203328548-adbb426e-06aa-431c-ad64-2e88ca264af0.png)

Mentioning @MoeNick and @divine-comedian to keep them in the loop.

**Comment by RamRamez** [comment]
@maryjaf Please test this hotfix with [this link](https://giveth-dapps-v2-git-1857removedonationbeingproc-49b25e-givethio.vercel.app/)

After this PR is approved, it'll be merged into production.

**Comment by maryjaf** [comment]
Thanks @RamRamez I tested and it passed

**Comment by RamRamez** [comment]
Thanks @maryjaf 
This hotfix is code reviewed and tested.

@MoeNick @divine-comedian if you approve we can go live.
