### ISSUE TITLE
"Sign out" Option does work.

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1860]
When I try to "Sign out" via our drop down menu (from the top where my name is)... the "sign out" actually doesn't disconnect my wallet or sign me out. It just makes the "sign out" option disappear.

@mateodaza @RamRamez \

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/72115a0e-22d0-4657-b58d-b47bb23b558a)

**Comment by RamRamez** [comment]
I tested with MetaMask and Brave and it was ok. @laurenluz which wallet are you using?

**Comment by RamRamez** [comment]
shields are up for me and it's ok.
@laurenluz what do you mean by `"sign out" actually doesn't disconnect my wallet or sign me out`? What is happening when you sign out?

**Comment by laurenluz** [comment]
@RamRamez Well, usually, after a 1st login, in this drop down menu I see a "sign out" option at the bottom. After I click it.. the page kind of refreshes & the sign out button disappears... but I'm still signed in:

![image](https://user-images.githubusercontent.com/75490971/204356209-3e924b7f-6b6b-4358-9ef4-b1a224ed2b15.png)

**Comment by MoeNick** [comment]
THis is the old ux problem we have for sign-in with eth,
currently: 
1- sign-out will not disconnect you from DApp, a wallet is still connected and we know who logged in, but it expires the token you signed in before with your wallet. so you get sign-out, you don't have a token and if you want to like a project, it asks you to sign again. Apparently in this situation, you can't see the sign-out choice. because you signed out already. 

2- Actually connecting the wallet wont mean logged in , we ask user to log in again with a msg to the Metamask or a wallet, so basically it's a 2 step connecting and sign the logging msg with a user wallet,. since the beginning we have this argument with design team that this flow won't mean the user signed in, we compromised it. 

However. we are solving this problem in MLA with @mosaeedi

**Comment by laurenluz** [comment]
Yeah I talked about this with @RamRamez in DM. The average user doesn't understand anything about how sign out deletes the token... in a web2 application sign out means your account isn't connected anymore. 

I think it would be better if sign out deleted the token & disconnected the wallet simultaneously.

**Comment by MoeNick** [comment]
is it possible to disconnect from DApp @RamRamez ?

**Comment by RamRamez** [comment]
> is it possible to disconnect from DApp @RamRamez ?

Yes, It's possible.
I've prepared a demo:
https://giveth-dapps-v2-git-1860disconnectonsignout-givethio.vercel.app/

**Comment by RamRamez** [comment]
> > is it possible to disconnect from DApp @RamRamez ?
> 
> Yes, It's possible. I've prepared a demo: https://giveth-dapps-v2-git-1860disconnectonsignout-givethio.vercel.app/

@laurenluz WDYT?

**Comment by laurenluz** [comment]
I don't see the sign out button anymore @RamRamez

![image](https://user-images.githubusercontent.com/75490971/216438245-052189dd-dbbf-4273-b5f8-a2c8cb8d47f2.png)

**Comment by RamRamez** [comment]
> I don't see the sign out button anymore @RamRamez
> 
> ![image](https://user-images.githubusercontent.com/75490971/216438245-052189dd-dbbf-4273-b5f8-a2c8cb8d47f2.png)

Yes, that's because you haven't signed the message yet and you don't have a token (and it's just like before). I agree it's confusing, I changed the sign out flow. Now, sign out button will always be shown and sign in flow is like before.

Please test again.

**Comment by MoeNick** [comment]
Heads-up @mosaeedi for this confusing flow, we insisted from the beginning that is not working well and now we get obliged to change it at last.

**Comment by maryjaf** [comment]
With this change, when I am signed out and, for example, I click the **like** or **boost** option of a project, the modal related  to sign wallet will be displayed.
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/6abeddfc-dcb3-4635-8eb7-a6045bd83625)
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/e1720ade-2f16-4b67-b22a-f03530e7e999)
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/bb2cc408-7cc8-4b64-8aa7-fd82f0f41804)

And after selecting MetaMask, the following modal will be displayed again
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/d58f6f7f-b1ed-4df8-88f0-5d19c58ec7b4)again
 by selecting the sign, the flow ralated to  selecting the wallet is shown
Are we ok with this flow and twice display of sign wallet  modal? @RamRamez @MoeNick

**Comment by maryjaf** [comment]
With this change, when I am signed out and, for example, I click the **like** or **boost** option of a project, the modal related  to sign wallet will be displayed.
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/6abeddfc-dcb3-4635-8eb7-a6045bd83625)
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/e1720ade-2f16-4b67-b22a-f03530e7e999)
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/bb2cc408-7cc8-4b64-8aa7-fd82f0f41804)

And after selecting MetaMask, the following modal will be displayed again
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/d58f6f7f-b1ed-4df8-88f0-5d19c58ec7b4)again
 by selecting the sign, the flow ralated to  selecting the wallet is shown
Are we ok with this flow and twice display of sign wallet  modal? @RamRamez @MoeNick

**Comment by maryjaf** [comment]
Plz check this  @RamRamez 
According to the menu, my user is signed in
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/804f947c-2680-4612-b1f8-018ef171cd3e)
But when I select the notification icon, the sign modal is displayed
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/8153972a-b169-4a62-b8cd-7a0aef00f4ad)

**Comment by RamRamez** [comment]
> Plz check this @RamRamez According to the menu, my user is signed in ![image.png](https://camo.githubusercontent.com/212a8bb496c19cf65d8e3ad81d9b84dc6e0749cde402f17848ce837bf83db922/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f38303466393437632d323638302d343631322d623166382d303138656631373163643365) But when I select the notification icon, the sign modal is displayed ![image.png](https://camo.githubusercontent.com/c7d964ee529efb0f77989100eb78343d3b2b2f61d4a9d0a94bc3dea665c67e03/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f38313533393732612d623136392d346136322d623863642d376130616566303066346164)

The sign-in definition has changed. Showing sign-out means your wallet is connected, it doesn't mean you have a token.

**Comment by RamRamez** [comment]
> With this change, when I am signed out and, for example, I click the **like** or **boost** option of a project, the modal related to sign wallet will be displayed. ![image.png](https://camo.githubusercontent.com/36a2988300e98194ce6c717e7e567d2178bef97a9fac6b4c2dd72ecd4bb02cfe/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f36616265646466632d646362332d343633352d386562372d613630343562643833363235) ![image.png](https://camo.githubusercontent.com/b541f3e3ebecc8020ca710cd978dbadb8f18a8f373d944b91a1adebbf3b161a8/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f65313732306164652d326631362d346236372d623232612d663033353330653765393939) ![image.png](https://camo.githubusercontent.com/8bc1bed012aeb4d8d0ac9cb6af4dd69eb3fe71fee647231ac2eaee5d1b84f7b2/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f62623263633430382d376363382d346236342d386161372d666438326630663431383034)
> 
> And after selecting MetaMask, the following modal will be displayed again
> 
> ![image.png](https://camo.githubusercontent.com/28049f18619444473a3e24a96a06c3eab3bcf986b43d0a274f620899051567c5/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f64353866366637662d623165642d346466382d383866302d356431396335386563376234) by selecting the sign, the flow ralated to selecting the wallet is shown Are we ok with this flow and twice display of sign wallet modal? @RamRamez @MoeNick

Fixed in PR #2300

**Comment by RamRamez** [comment]
@maryjaf says showing sign out button when user is not actually signed in (has no token) is confusing. In this case we can change `sign out` button to `disconnect`.
@MoeNick

**Comment by maryjaf** [comment]
> by selecting the sign, the flow ralated to selecting the wallet is shown
> Are we ok with this flow and twice display of sign wallet modal? @RamRamez @MoeNick

This problem has been resolved
Thanks @RamRamez
