### ISSUE TITLE
End the GIVdrop

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1865]
We need to set the merkle drop to end (not allow any new addresses to claim) on December 24, 2022.

**Comment by laurenluz** [comment]
To dos:
- [ ] remove UI on frontend
- [ ] make multsig tx to end the GIVdrop - need to revoke distributor role of merkledrop... Amin will make hex data so anyone can create tx later

**Comment by aminlatifi** [comment]
Transaction to revoke merkle distor admin role, 

Contract address (tokenDistro): 0xc0dbDcA66a0636236fAbe1B3C16B1bD4C84bB1E1

```
0xd547741ffbd454f36a7e1a388bd6fc3ab10d434aa4578f811acbbcf33afb1c697486313c000000000000000000000000fad63adefb8203f7605f25f6a921c8bf45604a5e
```

It's better another person validate it by information available here
https://www.notion.so/giveth/Deployment-52935e6579034f1b940bbef161e82229

**Comment by laurenluz** [comment]
@KurtMerbeth can you check this? This will be the tx to remove the distributor role from the merkle drop - i.e. disallow anyone else from claiming their GIVdrop - and we plan to execute it on Dec 24.

**Comment by KurtMerbeth** [comment]
@laurenluz 
i will check it

**Comment by KurtMerbeth** [comment]
@laurenluz @aminlatifi 
tx is correct

**Comment by laurenluz** [comment]
https://gnosis-safe.io/app/gno:0x4D9339dd97db55e3B9bCBE65dE39fF9c04d1C2cd/transactions/multisig_0x4D9339dd97db55e3B9bCBE65dE39fF9c04d1C2cd_0xabdf2859807d8b5d885c335ba46ffdfd7b25a99504d19c3cc40f129841240299
