### ISSUE TITLE
hard to distinguish user link and project link on project card

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#1869]
on the all projects page it is hard to distinguish when hovering over the user's name and the project's name that they are two different links 

![image](https://user-images.githubusercontent.com/67759413/203811292-700a77c6-980b-409c-8771-1f33fd0bcefb.png)

you can see in the image attached that they appear as the same colour on hover - some more spacing or a different distinction in colour on hover would make it more clear! I often click the wrong thing since they are so close together and appear the same colour on hover

**Comment by MoeNick** [comment]
@alireza-sharifpour do you have an idea for better UX on the coding side, or should I assign it to design team?

**Comment by alireza-sharifpour** [comment]
> @alireza-sharifpour do you have an idea for better UX on the coding side, or should I assign it to design team?

I can increase the spacing between the user and the project a little, is it ok?

**Comment by MoeNick** [comment]
I think so, thanks! @alireza-sharifpour

**Comment by alireza-sharifpour** [comment]
I've added some margin between the two links and i think now it's better.
You can test it @divine-comedian

**Comment by mosaeedi** [comment]
Thanks @alireza-sharifpour for the quick update

I also made some small changes to the project card on the design system
Please take a look,
[Project card on Figma](https://www.figma.com/file/d3ciTS36toS9mra0RAPMe2/Giveth-Design-System-v0.1?node-id=2059%3A59953&t=uhU5OJWgFDcoLjFH-4)

I've added **8px space** between the Project name and the project creator, also when the user mouse is over the project, we have to trigger the **Hover state**, but the **Project name** and the **project creator** will turn to pink only when the user mouse is over them. 

**The hover state for the project card**
<img width="426" alt="Screenshot 2023-01-24 at 4 19 59 PM" src="https://user-images.githubusercontent.com/13708322/214296017-a27591c1-2f22-4dc5-a6bb-d2375b5a87d9.png">


<img width="411" alt="Screenshot 2023-01-24 at 4 20 17 PM" src="https://user-images.githubusercontent.com/13708322/214296195-be7103d8-fae8-4972-8218-e1d151a824ec.png">
<img width="420" alt="Screenshot 2023-01-24 at 4 20 11 PM" src="https://user-images.githubusercontent.com/13708322/214296208-3352029c-8610-4cff-9759-2a80f1589b98.png">

**Comment by alireza-sharifpour** [comment]
Thanks @mosaeedi, I'll work on them.

**Comment by divine-comedian** [comment]
this looks way cleaner and more clear, thanks mo!

**Comment by maryjaf** [comment]
I tested the mentioned changes on stg and they are ok
@divine-comedian  Do you have approval to move to Done?

**Comment by divine-comedian** [comment]
looks great! thanks for testing, moving to DONE.
