### ISSUE TITLE
GIVpower Boosting Grammer Fixes

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-dapps-v2#1870]
Some minor comms typos to report here.

https://docs.google.com/document/d/1LPDvbIpGjbIPKC0SUzUslUYOTfyG8Lr3Eqd4dLZ0zP4/edit

**Comment by laurenluz** [comment]
@divine-comedian I went through and edited some and added one more! Thank you!

**Comment by divine-comedian** [comment]
fixed all reported issues in https://github.com/Giveth/giveth-dapps-v2/commit/5e3e2e09c6ca257fb906ee98f1e2c864c95ccd9a
