### ISSUE TITLE
Remove "Trace" from giveth.io projects

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1877]
We are sunsetting Giveth TRACE & disabiling traceable donations, we should remove the "Trace" labels & options. I see this:

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/c3a9d0f7-f075-4494-ac19-0d8618b9261b)

Do we have any other ways to interact with TRACE projects from giveth.io now? I can't seem to find it, but I do remember we had some kind of check box.

@aminlatifi @MoeNick @GriffGreen

**Comment by laurenluz** [comment]
We should remove the "Traceable" badge from Giveth projects on giveth.io

Who can take this @MoeNick @RamRamez @alireza-sharifpour @MohammadPCh ?

**Comment by RamRamez** [comment]
> We should remove the "Traceable" badge from Giveth projects on giveth.io
> 
> Who can take this @MoeNick @RamRamez @alireza-sharifpour @MohammadPCh ?

I can take it

**Comment by RamRamez** [comment]
@laurenluz Done. what about FAQ and About -> history? Do you wanna keep TRACE related copy there?

**Comment by laurenluz** [comment]
We should remove it from the FAQ for sure! I'll make a separate issue and ask someone from comms to go through everything and make specific suggestions on what to remove.

Good catch @RamRamez!

**Comment by MoeNick** [comment]
@maryjaf can you confirm?
