### ISSUE TITLE
GIVpower Design - Show that donors to top ranked projects get more GIVbacks

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1887]
The fact that we are giving up to 75% back of the donation (and very soon, up to 80% back) - is completely lost on our platform!

We should somehow show... maybe in the mouse-over of a project - the max % of GIVbacks that a donor will get when they donate to a particular project.

This is a huge selling point of our platform, and it's just lost behind too many close doors atm.

@mosaeedi @Tosinolawale @markoprljic - can you help?

**Comment by markoprljic** [comment]
I full agree with @laurenluz This information is valuable and should be forefront displayed and communicated all across the site. I don't think this info should be hidden anywhere behind a tooltip or else, it should be always visible. 
Isn't this what we already have? Except for the info on the % of givbacks. 

<img width="365" alt="Screenshot 2022-12-06 at 16 33 41" src="https://user-images.githubusercontent.com/5704285/205954997-7a6f67eb-006f-4a6b-8bce-0e8b0d78961f.png">

**Comment by laurenluz** [comment]
That's a good spot for it for sure!

Might be nice to show on the projects page as well somewhere - on the project card. We used to have the "new" or "verified" circle - this could be a place to put it.

**Comment by MoeNick** [comment]
do you guys have the time to take a look at this? @mosaeedi @Tosinolawale

**Comment by Tosinolawale** [comment]
![Wallet not connected](https://user-images.githubusercontent.com/35389241/213270795-169b06f5-4c1e-4b1e-9710-7db927fa1431.png)
![2](https://user-images.githubusercontent.com/35389241/213270819-4ae25410-1a3f-481a-bc76-6c83093360db.png)

We use to have this at the point of donation too. Is there a reason we removed it? @mosaeedi @laurenluz @MoeNick

**Comment by Tosinolawale** [comment]
> I full agree with @laurenluz This information is valuable and should be forefront displayed and communicated all across the site. I don't think this info should be hidden anywhere behind a tooltip or else, it should be always visible. Isn't this what we already have? Except for the info on the % of givbacks.
> 
> <img alt="Screenshot 2022-12-06 at 16 33 41" width="365" src="https://user-images.githubusercontent.com/5704285/205954997-7a6f67eb-006f-4a6b-8bce-0e8b0d78961f.png">

and this info is displayed already like you said on projects page, not hidden behind a tool tip. Obvious enough at the donation tool too? And we can also add additional information about GIVbacks and rewards on the platform landing page. @markoprljic , @mosaeedi @laurenluz

**Comment by laurenluz** [comment]
@Tosinolawale - are you saying we use to have "donate and get GIVbacks" at the top? and now we do not?

The requirements for this design are:
- [ ] Show that donors to the project ranked # 1 get up to 80% back in GIV, # 2 get up to 78% back, # 3 get 76% back, etc.
- [ ] It should be apparent right on the projects page, i.e. on the project card
- [ ] It should be apparent on the project single page as well (in that GIVback*s* eligible box would be good)
- [ ] It can be also made apparent when the user is donating

This kind of idea, is how we put it in the [launch video](https://youtu.be/KvMR-6JQ_fc?t=36)

![image](https://user-images.githubusercontent.com/75490971/214153728-17fc9aec-0ca5-4260-b50e-e3fbfc4942eb.png)

**Comment by mosaeedi** [comment]
I'm working on this issue. I'll update the design soon.

**Comment by MoeNick** [comment]
Any updates @mosaeedi

**Comment by laurenluz** [comment]
we are adding this in the single project page revamp
