### ISSUE TITLE
GIVeconomy: Adding steps to the Stake modal

### ISSUE THREAD

**Issue by mosaeedi** [Giveth/giveth-dapps-v2#189]
We need to add the steps to the stake modal to let users know the staking happens in two steps.

Link to the Figma component

[https://www.figma.com/file/d3ciTS36toS9mra0RAPMe2/Giveth-Design-System-v0.1?node-id=488%3A47225](https://www.figma.com/file/d3ciTS36toS9mra0RAPMe2/Giveth-Design-System-v0.1?node-id=488%3A47225)

**Comment by aminlatifi** [comment]
@mosaeedi Would you please add requirements of https://github.com/Giveth/liquidity-mining-dapp/issues/188 to that design too?

**Comment by divine-comedian** [comment]
very slick update - the modal seems to working according to the figma - 
![image](https://user-images.githubusercontent.com/67759413/163639098-4962a923-a629-44f7-aaa2-89984caae5ae.png)

call this DONE!
