### ISSUE TITLE
GIVpower Boosting | When projected rank & current rank are both the lowest... current shows "--" and projected says "#24" (for example)

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1894]
We should have the projected rank say "--" when it is projected to still be the lowest.

For example
https://giveconomy.vercel.app/project/blankets-of-hope

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/f15f1217-3a8e-41f2-b44d-658766d1d311)

**Comment by aminlatifi** [comment]
@MohammadPCh when a project has zero power amount we must show -- instead of rank

**Comment by laurenluz** [comment]
is this merged @MohammadPCh ?

**Comment by laurenluz** [comment]
looks right now: 
![image](https://user-images.githubusercontent.com/75490971/207142792-66947bbf-d0ee-40ad-9195-de41203c8e57.png)
