### ISSUE TITLE
GIVpower Boosting | Sort GIVpower boosters by amount boosted on project single page GIVpower tab

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1895]
It makes more sense for the users to be listed in order of amount boosted (not date boosted)... then the GIVpower tab can act kind of like a leaderboard.

cc @maryjaf @MoeNick 

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/0407e516-fb8b-4bc2-8ecf-3afbf6b306bc)

**Comment by maryjaf** [comment]
Thanks @MohammadPCh Now the list of users is sorted based on their givpower
