### ISSUE TITLE
user page - overview says 1 donation / donation page says no donations

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#1902]
Testing on https://giveconomy.vercel.app/user/0x9924285ff2207d6e36642b6832a515a6a3aedcab?tab=overview

on this user's page on the overview it says they have made 1 donation

![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/c4fb5af0-a5bf-4ac1-8b22-db3df3169bc8)

-----

but on their user page on the donations tab it says they haven't made any donations! 

![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/152251b8-9bb2-4e54-a0a2-939678e6bd86)

what's going on here?

**Comment by MoeNick** [comment]
@mohammadranjbarz @MohammadPCh is the address enough to detect the problem? 
what other information you need?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz @MohammadPCh is the address enough to detect the problem? what other information you need?

Yeah it's probably backend side problem, I will check it later
