### ISSUE TITLE
Make "Get GIV" link to Cowswap instead of Honeyswap?

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#1905]
**Describe the bug**
2 bugs

# 1 (Probably fine) I don't want DRGIV! I want GIV! :-D

# 2 Let's use CowSwap, instead of honeyswap: https://swap.cow.fi/#/100/swap/XDAI/GIV

**Screenshots**

<img width="443" alt="Screen Shot 2022-12-07 at 2 33 35 PM" src="https://user-images.githubusercontent.com/14945613/206281299-9b58a645-1c10-45a9-8590-500cba00fadf.png">

**Comment by laurenluz** [comment]
@aminlatifi he was testing on the GIVeconomy deployment... this should direct the user to get real GIV on production right? automatically?

or do we have to remember to change something before merging?

**Comment by aminlatifi** [comment]
> @aminlatifi he was testing on the GIVeconomy deployment... this should direct the user to get real GIV on production right? automatically?
> 
> or do we have to remember to change something before merging?

Probably he has tested on giveconomy (test env).
No I don't think so, actually we make the URL by filling in the token contract address and they are saved in separate file for the test env and the production env.

**Comment by laurenluz** [comment]
I thought so :)

**Comment by aminlatifi** [comment]
Oh, my mistake. The link is saved statically. So there is no template to fill with the contract address. We can easily switch to cowswap. Only for xdai?

**Comment by laurenluz** [comment]
Yeah giving the option to source any token is better. for some reason the gnosis chain one is working for me, but not the mainnet one?

![image](https://user-images.githubusercontent.com/75490971/206573463-46496f2e-be11-4acb-bab5-c65c1515d67d.png)

**Comment by aminlatifi** [comment]
> Yeah giving the option to source any token is better. for some reason the gnosis chain one is working for me, but not the mainnet one?
> 
> ![image](https://user-images.githubusercontent.com/75490971/206573463-46496f2e-be11-4acb-bab5-c65c1515d67d.png)

I guess the user mush have imported it before. So maybe cowswap is not safe!

**Comment by laurenluz** [comment]
Griff prefers cowswap because there is no MEV... I think that we can leave it as is with honeyswap if we have doubts. Give him a chance to reply.

**Comment by laurenluz** [comment]
@GriffGreen - can you please let us know what you think?

**Comment by GriffGreen** [comment]
Following up on Cowswap here: https://github.com/cowprotocol/cowswap/issues/1653

**Comment by GriffGreen** [comment]
Mainnet is not as big of a deal IMO, uniswap is fine for mainnet if cowswap doesnt work well on mainnet... but honeyswap is a constant MEV tax and cowswap if they get this slippage sorted, it will be better for the user... for now, we can wait. 

Soon (maybe a month or 2) Cowswap will have better routing for us than uniswap so it will also make sense to switch those links eventually IMO...

**Comment by MoeNick** [comment]
so it's a month pass I guess, should we follow it uu or close it?

**Comment by laurenluz** [comment]
@GriffGreen @brichis - can you let us know what you think?

**Comment by brichis** [comment]
Hey! I asked him already, I'll try to get an answer soon :)

**Comment by MoeNick** [comment]
Hey @GriffGreen @brichis :)  a gentle reminder on this.

**Comment by brichis** [comment]
Oh! I didn't receive the answer yet but Griff is on vacations now, let me add this issue to my to-do list to keeping it with a high priority :)

**Comment by brichis** [comment]
GM @MoeNick! He answered to me but he doesn't have access to Zenhub right know. 
He said: Tell them to test the slippage on cowswap and see if it looks good

**Comment by MoeNick** [comment]
a reminder on this @laurenluz @aminlatifi @GriffGreen

**Comment by laurenluz** [comment]
ok let's go then. if the slippage on cowswap is fine, let's make our default "get GIV" link to cowswap. @aminlatifi - do you agree?

**Comment by divine-comedian** [comment]
@mateodaza  - Can we make this our CowSwap fork link when we go live?

**Comment by mateodaza** [comment]
> @mateodaza - Can we make this our CowSwap fork link when we go live?

@divine-comedian >>> [PR here](https://github.com/Giveth/giveth-dapps-v2/pull/3010)

**Comment by divine-comedian** [comment]
Yes - I think that's what I asked for already.

**Comment by MoeNick** [comment]
I tested it and it works fine

**Comment by MoeNick** [comment]
@mateodaza can you make it happen again? let's change the link based on network based on what Mitch commented?

**Comment by divine-comedian** [comment]
So to clarify 

Get GIV on each chain should link to:
- Optimism - Uniswap
- Gnosis - CowSwap
- Mainnet - CowSwap

I think I misunderstood that swap.giveth.io would be the final site but actually we'll be ideally using CowSwap's main website with the donation feature?
