### ISSUE TITLE
GIVpower Boosting | Add "My GIVpower" to the drop down menu

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1912]
It should be below "My Donations" and above "Create a Project"... and should link to the "My GIVpower" tab (e.g. https://giveconomy.vercel.app/account?tab=givpower)

![image](https://user-images.githubusercontent.com/75490971/206280736-7262e5ee-e514-42fb-a324-127986eae3cf.png)

**Comment by maryjaf** [comment]
Thanks @MohammadPCh  I tested and it passed
