### ISSUE TITLE
Make entire project card clickable - Whyyy is it so hard to open the project now?!!!

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1913]
This used to be ok... but now there is some weird issue. I can only open a project from the projectspage if I click on the image, or the title. If I mouse-over the project description, I can't click.

It is super annoying and we should fix it asap!!

I can only open the project if I click in the highlighted area. I should be able to click the project and open its project single page from anywhere on the card (beside the donate button)

![image](https://user-images.githubusercontent.com/75490971/206278587-4b874fd2-9507-4a45-911d-a2cf40e7e1d6.png)

(P.S. I'm testing on the GIVeconomy deployment)
cc @MoeNick 

@MohammadPCh @mateodaza @RamRamez - can one of you pick it up?

**Comment by MohammadPCh** [comment]
@laurenluz, it's a bad practice to have a link in the link, and new nextjs prevent it.
[w3 organization link](https://www.w3.org/TR/REC-html40/struct/links.html)
so I had to remove it. I can handle it in another way, or find a temporary solution if we really need it. but maybe we need a redesign :)
