### ISSUE TITLE
GIVbacks harvested when claiming from the GIVfarm/GIVpower are not clear.

### ISSUE THREAD

**Issue by Cotabe** [Giveth/giveth-dapps-v2#1919]
I just harvested my GIV and realized that I had some GIVbacks from my donations. However, I was confused because nothing seemed to go from my stream.

After a few seconds of confusion and thinking about asking someone from the team, I realized it was represented but on the GIVstream row. 

![GIVbacks issue.PNG](https://images.zenhubusercontent.com/6239faf88ad3a4ffddc12d98/fc50270e-05b9-44e4-99bb-b6adfaf3dc02)

I think it would be way clearer if it showed up on the GIVbacks row.

![GIVbacks issue fix.PNG](https://images.zenhubusercontent.com/6239faf88ad3a4ffddc12d98/42491b58-6c1a-4a47-a316-8ebcf8ce6723)

**Comment by MoeNick** [comment]
Mentioning @laurenluz who can manage it better than me

**Comment by laurenluz** [comment]
it's just tough because actually... it was already added to your GIVstream... even before you clicked harvest.

So we put it with the GIVstream section... it was already included. This is like your "base" GIVstream... before you even click harvest.
