### ISSUE TITLE
Bad Bug, simple fix i bet... Failed donations are counting towards the total

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#1922]
**Describe the bug**
The donations total is counting the failed txs 

**To Reproduce**
1. Go to https://giveth.io/project/relocating-web3-iranians
2. Add up the amounts on the first and second page of donations
3. Notice it is counting the 700 DAI tx that failed

**Expected behavior**
The donations amount should exclude failed donations.

**Screenshots**
<img width="612" alt="Screen Shot 2022-12-10 at 6 32 24 PM" src="https://user-images.githubusercontent.com/14945613/206879475-41f357ad-3a88-495d-bf91-5b4414150dc3.png">
<img width="791" alt="Screen Shot 2022-12-10 at 6 32 32 PM" src="https://user-images.githubusercontent.com/14945613/206879477-b66ab5cc-bf55-4461-b059-90d06f166ba3.png">

**Comment by CarlosQ96** [comment]
Thanks Griff, I’ll take it, this is an easy fix
