### ISSUE TITLE
GIVpower Boosting | Current rank hotfix for 1st two weeks

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1930]
The 1st two weeks after launch is a special one! We will be keeping snapshot data from our soft launch to make reasonable predictions for projected rank, and will sort the projects according to soft launch data. 
Projects at launch will have a practical "current rank" but we should hide it from the frontend until the 2nd round starts on Dec 27.

We need to make the "current rank" show "--" for all projects on
- [ ] The project card
- [ ] The project single page card
- [ ]  The GIVpower tan

![image](https://user-images.githubusercontent.com/75490971/207073833-09c08475-04c7-41f4-b6e1-65afc759ebb5.png)
![image](https://user-images.githubusercontent.com/75490971/207073904-8d004a12-7e74-4aa7-bce2-ffb50de76463.png)

**Comment by laurenluz** [comment]
@MohammadPCh - make sure that we allow the current rank to update again starting on Dec 27 (at the start of the next GIVbacks round)

**Comment by MohammadPCh** [comment]
@laurenluz @maryjaf It's on production, could you please check it?

**Comment by laurenluz** [comment]
looks good :) do we have to revert back or do soemthing so that the rank is not hidden on Dec 27? or is it automatic? @MohammadPCh

**Comment by MohammadPCh** [comment]
@laurenluz yeah, It's automatic :)
