### ISSUE TITLE
GIVpower boosting | Add boost button to the projects page

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1932]
We had this in [the design](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=16087%3A287825&t=vdjoUHd33GQgSpzy-0) - this button, ideally, would navigate to the "boost projects" modal for a particular project. And should show up on the homepage & projects page.

@MohammadPCh  - what do you think? any issue with implementing this?

![image](https://user-images.githubusercontent.com/75490971/207165114-58f86fa3-d196-4adb-a962-e3ae9d9eff30.png)

**Comment by MohammadPCh** [comment]
@laurenluz @maryjaf could you please check this on the preview link?
https://giveth-dapps-v2-git-add-boost-button-to-project-card-givethio.vercel.app/

**Comment by maryjaf** [comment]
> @laurenluz @maryjaf could you please check this on the preview link? https://giveth-dapps-v2-git-add-boost-button-to-project-card-givethio.vercel.app/

> @laurenluz @maryjaf could you please check this on the preview link? https://giveth-dapps-v2-git-add-boost-button-to-project-card-givethio.vercel.app/
Thanks @MohammadPCh 
I tested and when I tap on this icon the project page is open and the modal of boosting is shown
<img width="1380" alt="image" src="https://user-images.githubusercontent.com/111529185/207587132-08f95673-37db-4596-b315-71bf281d30dd.png">
