### ISSUE TITLE
GIVeconomy homepage & GIVbacks - donate to projects button link is wrong

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#194]
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/197ed46f-2b92-4e55-8b02-cc9f3d7475e2)

this is linking to giveth.io/projects and opening it in a new tab.

I think it should be linking to https://giveth-dapps-v2.vercel.app/projects and opening in the same tab, no? @MoeNick

**Comment by laurenluz** [comment]
Same here
![image](https://user-images.githubusercontent.com/75490971/158266108-9d025c0f-0f3d-4504-b393-dd99f34756f1.png)

**Comment by laurenluz** [comment]
Here too:

![image](https://user-images.githubusercontent.com/75490971/158266719-4edc8433-9d27-499f-a0ba-f366522b06ac.png)

**Comment by laurenluz** [comment]
it's missing the "s" @aminlatifi 

![image](https://user-images.githubusercontent.com/75490971/159959806-48faa50a-3445-4edf-8717-f6075ae02e6c.png)

**Comment by laurenluz** [comment]
also I think it should not open in a new tab, but should stay in the same tab since it is still within the dapp

**Comment by divine-comedian** [comment]
Fixed another missing "s" - tested all the other buttons! 

tested changes - everything seems to be in working order now! moving this to done 
![image](https://user-images.githubusercontent.com/67759413/160920106-a29b3192-968b-4eaf-afe3-130a56060af8.png)
