### ISSUE TITLE
Add search function to homepage

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1942]
It's really weird/annoying that I can't just search projects from the giveth homepage.. but I have to go to the projects page.

Can we please include it? @markoprljic is there some objection to this from design?

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/ff64ef2f-4121-4a34-83a8-e1a938d37227)

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/19fddd3d-e874-4293-ba69-9e803d59dc71)

**Comment by markoprljic** [comment]
Indeed. Now that I'm looking at the Projects page I feel we're missing one big search inout field in the header. 
In order to make this work we need Search results page loaded separately. Technically I don't know how easy this is since we've implemented results directly on the Projects page. 

<img width="1470" alt="Screenshot 2022-12-16 at 10 23 26" src="https://user-images.githubusercontent.com/5704285/208066753-6fd03a1a-84f9-4a21-b6e1-a8faa4b11994.png">

<img width="1470" alt="Screenshot 2022-12-16 at 10 22 29" src="https://user-images.githubusercontent.com/5704285/208066807-7df4d48f-4baf-40a7-9ee8-506d98eb29bb.png">

**Comment by laurenluz** [comment]
@RamRamez @MoeNick - what do you think?

**Comment by RamRamez** [comment]
> Indeed. Now that I'm looking at the Projects page I feel we're missing one big search inout field in the header. In order to make this work we need Search results page loaded separately. Technically I don't know how easy this is since we've implemented results directly on the Projects page.
> 
> <img alt="Screenshot 2022-12-16 at 10 23 26" width="1470" src="https://user-images.githubusercontent.com/5704285/208066753-6fd03a1a-84f9-4a21-b6e1-a8faa4b11994.png">
> 
> <img alt="Screenshot 2022-12-16 at 10 22 29" width="1470" src="https://user-images.githubusercontent.com/5704285/208066807-7df4d48f-4baf-40a7-9ee8-506d98eb29bb.png">

We can redirect user to projects page (and show search results there) when user uses search input in homepage (or anywhere else). Is it ok?

**Comment by laurenluz** [comment]
So they will type something in the search bar, hit "enter" and then the page will reload to the projects page w/their search? @RamRamez

**Comment by RamRamez** [comment]
> So they will type something in the search bar, hit "enter" and then the page will reload to the projects page w/their search? @RamRamez

Yes, actually the page won't reload but re-render. Just like when you click projects from menu on homepage, page won't reload but re-render to show projects page.

**Comment by laurenluz** [comment]
I think it's ok. @markoprljic  - what do you think?

**Comment by markoprljic** [comment]
Yeah I figured we'd have to do it that way. That's ok.

**Comment by MoeNick** [comment]
@mosaeedi @Tosinolawale Who can jump into this guys?

**Comment by mosaeedi** [comment]
I'm working on the Homepage right now, I'll take care of this too.

**Comment by MoeNick** [comment]
will continue working on this in #2021 .

**Comment by MoeNick** [comment]
I think the design is ready and I assigned it to team.
you can review it here. https://github.com/Giveth/giveth-dapps-v2/issues/2059
 Shall I close this issue?
