### ISSUE TITLE
Improve Projected Rank Calculation

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1947]
Right now, the projected rank is comparing current GIVpower to the "Current rank" to determine the projected rank.

I do like the fast feedback, but right now it is set up so that multiple projects can actually have the same projected rank.

@MohammadPCh had an idea about comparing the current GIVpower to the most recent snapshot - is this worthwhile changing?

Goals are:
- To allow the user to feel that they have an impact on projects right away when they are boosting them
- Not make users confused by seeing multiple projects with the same projected rank

@aminlatifi would love to know your thoughts
And @MohammadPCh & @maryjaf if you have any other concerns about the current projected rank calculation, please let us know here.

**Comment by aminlatifi** [comment]
It's possible to do it. With this change, projects may have the same rank if they are updated after the last snapshot and their power amounts are between two same boundaries. The current implementation has the same rules, but the interval is one round (14 days) instead of the duration between two snapshots. So the rank anticipation can be more precise.

**Comment by aminlatifi** [comment]
> yeah I think making the rank anticipation more precise is a good idea. Can we make this happen @aminlatifi ?

Yeah, I agree. @laurenluz we can put it in backlog or we need to discuss it in a meeting?

**Comment by GriffGreen** [comment]
![mando-way-this-is-the-way (1)](https://user-images.githubusercontent.com/14945613/208179814-5f1aceaf-82b5-479b-bcc0-46d318f57dce.gif)

**Comment by laurenluz** [comment]
Yeah let's just put it in the backlog :) Thanks @aminlatifi

**Comment by MohammadPCh** [comment]
@laurenluz @aminlatifi I have another idea too, but maybe it has some security issue.
We calculate the total GIVpower of each project in the front end, so we can have a not-trustable table(DB) that is updated by the front end.
so we can have an instant rank system.
but the main issue is we can't trust the front-end calculation because each user can send fake data to us.
I don't know if is it worth thinking about it or not!

**Comment by aminlatifi** [comment]
Made the PR for review https://github.com/Giveth/impact-graph/pull/779

**Comment by CarlosQ96** [comment]
Reviewed!

**Comment by aminlatifi** [comment]
@laurenluz @maryjaf It's ready for test

**Comment by maryjaf** [comment]
> @laurenluz @maryjaf It's ready for test

Plz check this scenario
Current and projected rank of "mejan" is 23
I remove all givpower of "mejan"
The projected rank changed into "--"
But after a round current rank changed into "28" and projected rank "--" although the givpowr of project with rank 29 is more than "mejan" with current rank 28 
<img width="1337" alt="image" src="https://user-images.githubusercontent.com/111529185/208686924-58574d48-5af9-456a-b146-579bcae9f1d9.png">
![image](https://user-images.githubusercontent.com/111529185/208686954-5f9118e9-5dd3-4f46-a7e7-34f161473ba1.png)
Is this result acceptable? @aminlatifi

**Comment by aminlatifi** [comment]
@maryjaf You had made the project power zero. It's UI decision to show those value. @MohammadPCh

**Comment by maryjaf** [comment]
> @maryjaf You had made the project power zero. It's UI decision to show those value. @MohammadPCh

@MohammadPCh Kindly reminder

**Comment by aminlatifi** [comment]
We deployed GIVpower token unlock today and tested it on the staging env. The point about the staging env is that GIVpower round duration is 14 days, so every lock position would be unlocked in at least 14 days. To test it, we configured giveconomy notification micro service to index again from the past and received these events in the UI
![image](https://user-images.githubusercontent.com/5684607/209121146-fc1e7451-c6e0-4e7e-875b-e4202e57e3a2.png)

I would say we can consider it as tested, but @maryjaf can test herself by locking a token and see the result in few weeks.

**Comment by aminlatifi** [comment]
@MoeNick @laurenluz We have the round number which the tokens are unlocked at the end of. Do you think we can put it in the log representation?
Just note: it means all the locks are unlocked and not positions details!! For instance, if the user locks 100 tokens for two rounds, and after one round she/he locks another 300 tokens, at the end of next round we will have 400 tokens unlocked at the end of round 3
Nevertheless, the detail of unlocked positions can be fetched in a separate query to the subgraph.

**Comment by maryjaf** [comment]
> We deployed GIVpower token unlock today and tested it on the staging env. The point about the staging env is that GIVpower round duration is 14 days, so every lock position would be unlocked in at least 14 days. To test it, we configured giveconomy notification micro service to index again from the past and received these events in the UI ![image](https://user-images.githubusercontent.com/5684607/209121146-fc1e7451-c6e0-4e7e-875b-e4202e57e3a2.png)
> 
> I would say we can consider it as tested, but @maryjaf can test herself by locking a token and see the result in few weeks.

I think it's about  conversation on this issue 
https://github.com/Giveth/giveth-dapps-v2/issues/477#issuecomment-1358794692
and i replied on this #477

**Comment by maryjaf** [comment]
> > @laurenluz @maryjaf It's ready for test
> 
> Plz check this scenario Current and projected rank of "mejan" is 23 I remove all givpower of "mejan" The projected rank changed into "--" But after a round current rank changed into "28" and projected rank "--" although the givpowr of project with rank 29 is more than "mejan" with current rank 28 <img alt="image" width="1337" src="https://user-images.githubusercontent.com/111529185/208686924-58574d48-5af9-456a-b146-579bcae9f1d9.png"> ![image](https://user-images.githubusercontent.com/111529185/208686954-5f9118e9-5dd3-4f46-a7e7-34f161473ba1.png) Is this result acceptable? @aminlatifi

I see some project on Giveconomy that they haven't any boost and their currant rank grater than zero @MohammadPCh @aminlatifi 
<img width="1379" alt="image" src="https://user-images.githubusercontent.com/111529185/209675744-a40cb49c-5ee8-42be-ae7d-14af647a63d2.png">

**Comment by MohammadPCh** [comment]
I don't know what happend on that time, it has a GIVpower now:
![image](https://user-images.githubusercontent.com/17097576/209773472-6449a0f7-b904-494b-88fd-f14dd3e7333c.png)

**Comment by laurenluz** [comment]
@maryjaf - can you do a test on production?

**Comment by laurenluz** [comment]
@maryjaf - can you do a test on production?

**Comment by laurenluz** [comment]
@mohammadranjbarz or @CarlosQ96 can enable the API on production so @maryjaf can test for a short time. Will need to restart the server... but we should not keep it enabled for long. Only a fast test.

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz or @CarlosQ96 can enable the API on production so @maryjaf can test for a short time. Will need to restart the server... but we should not keep it enabled for long. Only a fast test.

@maryjaf  please tell me whenever you want to enable/disable that API

**Comment by maryjaf** [comment]
> > @mohammadranjbarz or @CarlosQ96 can enable the API on production so @maryjaf can test for a short time. Will need to restart the server... but we should not keep it enabled for long. Only a fast test.
> 
> @maryjaf please tell me whenever you want to enable/disable that API

Thanks @MohammadPCh It is ok for me now and if it is activated, I will test it

**Comment by maryjaf** [comment]
> @maryjaf - were you able to test this on production?

Sure, I checked with @mohammadranjbarz

**Comment by maryjaf** [comment]
I tested this on production and the calculation of  projected rank is true
