### ISSUE TITLE
GIVdrop End | Redesign of GIVeconomy homepage (push to production on Dec 24)

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1948]
The GIVdrop will end on Dec 24, and we should remove the "Claim" CTAs. We can also change some content of the homepage to make it more relevant for our purposes now.

A full redesign of the GIVeconomy will come later, this is just a timely improvement.

Worked with @mosaeedi on the design, and we're ready to build it!

@MohammadPCh - can we have this ready next week, and the deploy to production on Dec 24?

Here is the [figma](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=16164%3A293342&t=5txfmBS1OIw0isJA-4). This should be for [this page](https://giveth.io/giveconomy). I will put where the links go to as comments in the figma, and DM you the full video file for GIVpower (in case you need it). cc @MoeNick 

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/5e0468a4-4d91-498e-8a0f-e4ba0c988f56)

**Comment by MohammadPCh** [comment]
@laurenluz @maryjaf  could you please test it here: https://giveconomy.vercel.app/giveconomy

**Comment by maryjaf** [comment]
Thanks @MohammadPCh I checked the Giveconomy page and it has been changed  according to figma
