### ISSUE TITLE
Implement modal queue.

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#1954]
@MoeNick commented on [Mon Dec 19 2022](https://github.com/Giveth/GIVeconomy/issues/835)

As a user, I want to proceed on my previous action if I got asked to sign my wallet. (on donations, like and other required wallet sign-ins)

**Comment by MohammadPCh** [comment]
@maryjaf could you please test this? I can explain the scenario if you don't know it.

**Comment by maryjaf** [comment]
> @maryjaf could you please test this? I can explain the scenario if you don't know it.

Thanks @MohammadPCh I have tested this and once the authentication is complete, actions like and unlike are performed
and the modal related to boost and donate is displayed

**Comment by maryjaf** [comment]
> @maryjaf could you please test this? I can explain the scenario if you don't know it.

Thanks @MohammadPCh I have tested this and once the authentication is complete, like and unlike actions are performed and the modal related to boost and donate is displayed correctly for both cancel and sign flow.
