### ISSUE TITLE
After the donation process, social media buttons are not working

### ISSUE THREAD

**Issue by brichis** [Giveth/giveth-dapps-v2#1955]
**Describe the bug**
I donated to a new project and I want to share it in social media but the buttons are not working

**To Reproduce**
1. Go to Share this with your friends
2. Click on Twitter (for example)
3. Nothing happens

**Expected behavior**
It's supposed to open my post on Twitter

**Screenshots**

![image](https://user-images.githubusercontent.com/106570342/208515171-1c67f9a8-befd-4694-9e12-5543061d8d99.png)

**Desktop (please complete the following information):**
 - Browser: Brave
 - Version 1.46.144

**Comment by MoeNick** [comment]
@brichis Thanks for reporting.
 can you pls tale a look again, I guess it's solved now.
