### ISSUE TITLE
Add CULT to our GIVbacks tokens list

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#1957]
https://forum.giveth.io/t/givbacks-token-list/253/13

GM! Lets push this one since they are a regen farm partner... surprised they weren't on the list already.

Sorry for tagging everyone but i wasn't sure who the right person for the job is ;-D

**Comment by mohammadranjbarz** [comment]
@GriffGreen I can add it, please pass me this information :


**name**, **symbol**, **address**, **network**, **decimals**

**Comment by GriffGreen** [comment]
https://www.coingecko.com/en/coins/cult-dao
https://etherscan.io/token/0xf0f9d895aca5c8678f706fb8216fa22957685a13

name, symbol, address, network, decimals

Cult DAO

CULT

0xf0f9d895aca5c8678f706fb8216fa22957685a13

Mainnet

18

**Comment by mohammadranjbarz** [comment]
> 0xf0f9d895aca5c8678f706fb8216fa22957685a13

I just added it to our DB, can you test it and a donate a small amount to see if everything is ok?

<img width="1339" alt="Screen Shot 1401-09-30 at 18 20 46" src="https://user-images.githubusercontent.com/9850545/208933308-b0d20c8b-d7d8-4565-abbc-3a5055162437.png">

**Comment by GriffGreen** [comment]
This is done right?

**Comment by mohammadranjbarz** [comment]
> This is done right?

Yeah it's done.

**Comment by MoeNick** [comment]
@maryjaf can you please test and confirm? both staging and production.
