### ISSUE TITLE
Remove giveth DAC from footer

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#196]
Can we just take out "The Giveth DAC"? We're not using this terminology anywhere else, I would just delete it.

@WhyldWanderer what do you think?

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/0331ba1e-a3de-439d-9b88-c22374d2329a)

**Comment by GriffGreen** [comment]
hahaha

**Comment by laurenluz** [comment]
I second griff's though. this means nothing to me 😅

**Comment by geleeroyale** [comment]
Its an old relic - let's remove it. It's also MMXXII already ;-)

**Comment by laurenluz** [comment]
@geleeroyale I'm so glad you are here for the history lessons <3

@MoeNick @MohammadPCh Thanks for taking this on!

**Comment by laurenluz** [comment]
great
![image](https://user-images.githubusercontent.com/75490971/159959231-30ea4f17-8ac1-4eeb-852c-d95a23b09252.png)
