### ISSUE TITLE
Key info about our subgraph for a grant and marketing

### ISSUE THREAD

**Issue by Cotabe** [Giveth/giveth-dapps-v2#1962]
Hey team! The Graph will give us a Grant of 50K GRT and we will have a co-marketing campaign. I need to fill out a questionnaire most of it is done, but I need some technical help with the following questions:

1. Name of our subgraph (Can be found here https://thegraph.com/explorer I look for "Giv" and failed to find anything)

2. What is your subgraph used for?* (What data is being indexed by the subgraph, and how is that data used?)

3. Is subgraph data used to support the backend or UI, or both? - What does a user see when browsing through your dapp that's powered by your subgraph? (this helps us elaborate visually, what the subgraph is feeding into that the user sees)

4. Is there anything visible in your dapp's UI that should particularly be emphasized in a screen recording of your dapp?

5. How is the team championing decentralization?* - Is there decentralized governance? Why is decentralization important to the team?
(I already started this one, but let me know if you have something to add)
We are trying to progressively decentralize everything.
We have a very diverse governance structure that gives tokenholders governance over most important decisions. But also a reputation DAO to manage an independent budget. This is how it works:
GIV governance
Advice process - Discourse.
Signaling and non-budget related decision making - Snapshot.
Vote for the project's ranking. The projects with a better rank provide more GIVbacks and appear first on the platform - Giveth.io Dapp
Nominate projects to get onboarded - Tokenlog.
Vote on the features to be included in the roadmap - Tokenlog.

NRGIV governance
Reputation DAO with some independent budget; mostly for contributors - Aragorn.

Eventually, we also want to decentralize budgets and decision making of working groups into subDAOs and the verification process of projects.

6. Any other interesting information or fun facts you'd like to share about your project and the subgraph powering it?

**Comment by MoeNick** [comment]
@mateodaza @aminlatifi can u pls take a look?

**Comment by aminlatifi** [comment]
1. We maintain our subgraph codes [here](https://github.com/Giveth/giveconomy-subgraph). Its [readme file](https://github.com/Giveth/giveconomy-subgraph/blob/develop/README.md) includes paths of deployments.
### Hosted node endpoints on production

- **Mainnet**: https://thegraph.com/hosted-service/subgraph/giveth/giveth-economy-second-mainnet
- **Gnosis**: https://thegraph.com/hosted-service/subgraph/giveth/giveth-economy-second-xdai
### Hosted node endpoints on staging
- **Goerli**: https://thegraph.com/hosted-service/subgraph/giveth/giveth-economy-goerli-staging
- **Gnosis**: https://thegraph.com/hosted-service/subgraph/giveth/giveth-economy-xdai-staging

2. We use subgraphs to run comprehensive complex queries to load smart contracts data. We monitor contracts' events and save compiled data to run queries against later from both backend and frontend services. One important feature of the subgraph is allowing queries on specific blocks, like what archive nodes provide. We use this feature especially in the backend to retrieve all users' balances at a specific time (by finding the closest block number in advance).


3. We use it both in the backend and the front end. In the frontend, we inquire about the user's balances and related data from more than 10 contracts in a single query and update several components in a fraction of a second. So the UI loads very fast and shows real-time (updates every 5 seconds) updates about the user's account in Giveth De-Fi. Without the subgraph, we had to generate a massive number of queries which would be impossible and the user would be blocked by the node providers.
Moreover, the subgraph enables us to show the history of stream allocations and the list of the GIVpower locked positions.

4. 
We show all farms and all claimable amounts in a single view. Below, we have only one farm. But it supports multiple fams and shows the aggregate claimable amount in the top right component 
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/5684607/209112949-476e2356-bcd5-4e02-b5e4-03add6cfc23b.png">

We support different regen farms (different third-party DeFi with their own farms and stream)
<img width="995" alt="image" src="https://user-images.githubusercontent.com/5684607/209113013-c1e00635-a1cc-4f11-a0ea-a8303260a81b.png">

History of GIVpower token lock positions. Couldn't happen without the subgraph. As it shows we have had loaded multiple balances from different contracts, again in a single query.
<img width="442" alt="image" src="https://user-images.githubusercontent.com/5684607/209113206-89c61bf0-5244-452b-9751-cd043cfad08a.png">

Stream state: The user stream rate and current claimable amount. 
Also the history of allocations to the user stream and their sources. Couldn't happen without the subgraph.
<img width="931" alt="image" src="https://user-images.githubusercontent.com/5684607/209114287-9ebb82a7-5c2a-49ed-bc99-f8f25bcef4a3.png">

**Comment by Cotabe** [comment]
This is amazing @aminlatifi you are the best.

Just one question... is there any technical decentralization of servers, web services or anything else that we can highlight regarding championing decentralization?

**Comment by aminlatifi** [comment]
> This is amazing @aminlatifi you are the best.
> 
> Just one question... is there any technical decentralization of servers, web services or anything else that we can highlight regarding championing decentralization?

The decentralized parts of Giveth are smart contracts which are the main backend, specifically for the GIVeconomy. The subgraphs enable us to read from this backend part fastly and provides historic and compiled data which is not easy or impossible to deduce by querying web3 directly.

**Comment by MoeNick** [comment]
shall I close it @Cotabe ?
