### ISSUE TITLE
authentication service incorrect message value in SSR env

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapps-v2#1968]
**Describe the bug**
https://github.com/Giveth/giveth-dapps-v2/blob/1e94ab678f42ac9c764e23a46758b8ff1f5f7f54/src/features/user/user.thunks.ts#L28
It was supposed to be hostname, but it's not.
While its value is not used till now because in client-side rendering routes we use `window.location.hostname` value and ignore this, it may cause issues in routes rendered on the server side (SSR) later
**Additional context**
https://stackoverflow.com/questions/65199051/how-to-get-page-url-or-hostname-in-nextjs-project

**Comment by MoeNick** [comment]
@mateodaza do you want to continue on this ?

**Comment by mateodaza** [comment]
@MoeNick discussed this with @aminlatifi previously and we agreed to remove it to avoid confusion because this variable won't ever be accessed on the server
