### ISSUE TITLE
GIVeconomy - GIVgarden button links are all wrong

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#197]
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/dd4cf919-a197-4603-96e4-2492fee30ac7)

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/1bfdda32-6184-4d1c-b2c5-970a0c4cb32a)

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/189b120b-254c-40e9-97c3-df7780293777)

These buttons are going to gardens on staging... they should go to the real garden at: https://gardens.1hive.org/#/xdai/garden/0xb25f0ee2d26461e2b5b3d3ddafe197a0da677b98

**Comment by laurenluz** [comment]
here too: 
![image](https://user-images.githubusercontent.com/75490971/158266806-b44cf545-5156-4cf0-b3a3-1cd9ce356f3d.png)

**Comment by aminlatifi** [comment]
The link address is configuratble. The version you have tested has staging configuration.

**Comment by laurenluz** [comment]
oh niiiiice 🔥
