### ISSUE TITLE
Donation amount conversion is incorrect

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#1970]
I donated 2105 GIV to a project.

At the time of donation, the modal said that the value was 42.1.
![image](https://user-images.githubusercontent.com/74267818/209576151-6e3101f7-7cfe-4c91-bd92-282994ae644d.png)

But the actual value was 37.31 on CoinGecko.
![image](https://user-images.githubusercontent.com/74267818/209576194-f9b7e680-37e4-448c-9ffd-75940b846b1e.png)

This has been causing a lot of confusion for donors becasue they think they are donating 10.00 or more to receive the POAP in the GIVbacks round.. but really they are not donating enough to reach the $10 dollar requirement so they are missing the opportunity to claim the POAP. 

How can we make this more accurate?

**Comment by MoeNick** [comment]
@mohammadranjbarz @CarlosQ96 
Do you have any idea why this happened?

**Comment by mohammadranjbarz** [comment]
> I donated 2105 GIV to a project.
> 
> At the time of donation, the modal said that the value was 42.1. ![image](https://user-images.githubusercontent.com/74267818/209576151-6e3101f7-7cfe-4c91-bd92-282994ae644d.png)
> 
> But the actual value was 37.31 on CoinGecko. ![image](https://user-images.githubusercontent.com/74267818/209576194-f9b7e680-37e4-448c-9ffd-75940b846b1e.png)
> 
> This has been causing a lot of confusion for donors becasue they think they are donating 10.00 or more to receive the POAP in the GIVbacks round.. but really they are not donating enough to reach the $10 dollar requirement so they are missing the opportunity to claim the POAP.
> 
> How can we make this more accurate?

@MohammadPCh  @RamRamez 
Wich service you are using for showing GIV price in donation modal?

**Comment by RamRamez** [comment]
We round the token price with two decimal points so the price is not accurate. I fixed it and I'll send the PR.

**Comment by maryjaf** [comment]
<img width="511" alt="image" src="https://user-images.githubusercontent.com/111529185/211077787-3150c907-509d-4664-9d01-b7e9cf52247f.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/111529185/211077846-7e1ead56-b404-495e-84cc-5028011016c5.png">

What is the basis for calculating the conversion rate? @RamRamez 
I check this site and see a different rate
https://www.coinbase.com/converter/giv/usd

**Comment by RamRamez** [comment]
> <img alt="image" width="511" src="https://user-images.githubusercontent.com/111529185/211077787-3150c907-509d-4664-9d01-b7e9cf52247f.png">
> 
> <img alt="image" width="1440" src="https://user-images.githubusercontent.com/111529185/211077846-7e1ead56-b404-495e-84cc-5028011016c5.png">
> 
> What is the basis for calculating the conversion rate? @RamRamez I check this site and see a different rate https://www.coinbase.com/converter/giv/usd

We round the USD amount by two decimal points, So it's ok. You can check by entering higher token amounts.
![image](https://user-images.githubusercontent.com/73441857/211190140-e85cb4e5-e1dd-4b16-9750-018d7d5d7ace.png)
