### ISSUE TITLE
Show the website and social links in description of Change projects

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#1971]
We are pulling the website info from the Change API but it is not being displayed in the project description...

Here is one example from the API:
Can we include all of the highlighted info in the project description for Change projects?

![image](https://user-images.githubusercontent.com/74267818/209576584-c05f3020-bbb6-4f73-bdad-72b9886edbc0.png)

**Comment by WhyldWanderer** [comment]
Right now, the project descriptions for these projects are very bare... we are hoping to make them a bit more robust and provide more information for interested donors.

We dont have much to work with when it comes to the mission so I am hoping that by adding external links, we can make these projects a bit more attractive...

**Comment by WhyldWanderer** [comment]
Im not really sure what labels to add to this issue or who to assign it to @MoeNick

**Comment by divine-comedian** [comment]
@CarlosQ96 @WhyldWanderer 

Are change projects still relevant for us? Is this work worth it?

**Comment by MoeNick** [comment]
FYI 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbm9MIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--635eb94dd3b7eed2c979576e35cd5f7a7df9ff72/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbndMIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7b4c88fa8fe15f1f9e979d3e86112472d6b3421f/image.png)

**Comment by MoeNick** [comment]
So I think it's not and we have to make sure all CHANGE projects are erased.

**Comment by divine-comedian** [comment]
Yikes! Was anyone on our team in contact from them? Do we have a way of contacting change projects?  Maybe even change org themselves?

Maybe this is an onboarding opportunity for those non-profits who have been abandoned
