### ISSUE TITLE
Can't add an apostrophe to a project name when creating a project 

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#1975]
<img width="737" alt="Screen Shot 2022-12-27 at 12 18 28 PM" src="https://user-images.githubusercontent.com/14945613/209700125-2533c575-60ae-46f4-8b4b-abbd0c738788.png">

**Comment by mohammadranjbarz** [comment]
@MoeNick  @GriffGreen  We can disable any validator on title ( except not to be repetitive) , or we can just add a whitelist of special characters , then just let them be in the title, anything you want

**Comment by MoeNick** [comment]
> @MoeNick @GriffGreen We can disable any validator on title ( except not to be repetitive) , or we can just add a whitelist of special characters , then just let them be in the title, anything you want

Let's have a whitelist for more security, I suggest 
`
' 
<
>
+
"
+
-
&
^
$
#
@ 
!
*
?
/
\
|

%
`

Lets exclude parathesis signs, do you have other suggestions?

**Comment by mohammadranjbarz** [comment]
> > @MoeNick @GriffGreen We can disable any validator on title ( except not to be repetitive) , or we can just add a whitelist of special characters , then just let them be in the title, anything you want
> 
> Let's have a whitelist for more security, I suggest ` ' <
> 
> > 
> 
> 
> ## "
> +
> & ^ $
> 
> @ ! * ? / |
> 
> % `
> 
> Lets exclude parathesis signs, do you have other suggestions?

I think it's good to add
*  **#**
* `*`
* **.**
* **=**
* **_**
* **-**
* **>**

**Comment by GriffGreen** [comment]
Cool!!! Exciting!

**Comment by maryjaf** [comment]
> @maryjaf You can test it on Staging ( we should allow these characters in edit/create projects)

Thanks, I checked and it has been fixed.
