### ISSUE TITLE
When creating a project, we never want the user to enter an exchange address, for any chain

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#1976]
<img width="843" alt="Screen Shot 2022-12-27 at 12 27 56 PM" src="https://user-images.githubusercontent.com/14945613/209701093-d49f900d-2125-4257-aba6-4c708e0773b0.png">

<img width="773" alt="Screen Shot 2022-12-27 at 12 27 46 PM" src="https://user-images.githubusercontent.com/14945613/209701113-8abf7e1b-9cc4-4590-819f-1b6c4ad7d0db.png">

Currently we say "Please DO NOT enter exchange addresses for Gnosis Chain." for some address input boxes...

We need to have this warning in EVERY input box (mainnet too) and it should say instead:

"Please DO NOT enter an exchange deposit address, use a key you control in a wallet like Metamask, or your funds maybe lost."

**Comment by RamRamez** [comment]
Resolved in PR #1990
