### ISSUE TITLE
Can't doante w/ fiat - screen of death and then eventually a total fail :-/

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#1977]
**Describe the bug**
Can't donate... get error screen

**To Reproduce**
Metamask connected to Gnosis Chain, I am in Canada trying to use a US credit card

Tried to donate $60 to: https://fiat-38.vercel.app/donate/crowd-funded-cures

Failed on Moonpay with googlepay, applepay and credit card,

But got the next screen to pop up with Transact and Wyre.

Ended up using Wyre and it let me put in the info, but wouldnt let me donate

<img width="485" alt="Screen Shot 2022-12-27 at 12 47 58 PM" src="https://user-images.githubusercontent.com/14945613/209703759-ce5b9699-344f-4b0a-b65e-f1ef2e98619e.png">
**Expected behavior**

**Screenshots**

The Fail with moonpay:
<img width="517" alt="Screen Shot 2022-12-27 at 12 42 39 PM" src="https://user-images.githubusercontent.com/14945613/209702920-f79f9a01-a725-4b88-a34a-40e99a292880.png">

<img width="594" alt="Screen Shot 2022-12-27 at 12 42 23 PM" src="https://user-images.githubusercontent.com/14945613/209702883-eb8a7336-094c-4a98-8a07-ef1822ab200e.png">
<img width="511" alt="Screen Shot 2022-12-27 at 12 43 00 PM" src="https://user-images.githubusercontent.com/14945613/209702979-80c94bc9-dec2-4239-b155-eed1ce4e05c6.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by divine-comedian** [comment]
This feature is dead - still fiat crypto payments aren't good enough yet, didn't work out so we'll close this issue.
