### ISSUE TITLE
Seems like the #1 ranked project is always projected to rank #2...

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#1981]
<img width="228" alt="Screen Shot 2022-12-27 at 10 59 29 PM" src="https://user-images.githubusercontent.com/14945613/209755212-4ebaae5e-1b3f-4f9e-8c82-f794d214b4bf.png">

**Comment by GriffGreen** [comment]
Send the ID of the project with the GIVpower amount

**Comment by aminlatifi** [comment]
Made Giveth/impact-graph#789 PR, after it become merged we must add projectId to query run by frontend

**Comment by aminlatifi** [comment]
@MohammadPCh https://github.com/Giveth/impact-graph/pull/789 is merged, after that the powerAmountRank API accepts `projectId` as an optional parameter. If you pass `projectId`, it will give more precise predicted rank,

**Comment by maryjaf** [comment]
I checked on production and the problem has been solved

**Comment by maryjaf** [comment]
Hmmm
I see it as below pic, it is strange
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/111529185/217354821-ca59cbb1-754b-4daa-ab04-4dcc3a527e60.png">

**Comment by MohammadPCh** [comment]
same here:
![image](https://user-images.githubusercontent.com/17097576/217500455-e9d57010-409e-4e82-ae0c-e6abe4ab85d0.png)

**Comment by MoeNick** [comment]
Caching problem?

**Comment by laurenluz** [comment]
fine for me as well

![image](https://user-images.githubusercontent.com/75490971/217541729-036632fc-3b86-4843-8c37-051414ad1877.png)

**Comment by MohammadPCh** [comment]
Sorry Guys, but this feature was merged into the Giveconomy branch, and I now saw that it was tested on production. Should we release it now?
@laurenluz @MoeNick

**Comment by MohammadPCh** [comment]
With Moenick's approval, we have released a hotfix  now(version 2.7.6),
