### ISSUE TITLE
GIVdrop claim page redesign since GIVdrop has ended

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#1986]
Right now https://giveth.io/claim still looks like this:

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/7e092618-baf1-46cb-8f2b-440aac0fc483)

We should make it a "missing page"

Or "GIVdrop has ended" page

@MohammadPCh @MoeNick @markoprljic  - what do you guys think?

**Comment by MohammadPCh** [comment]
@laurenluz I asked guys to design a new page for it. I think @Tosinolawale is working on it.

**Comment by laurenluz** [comment]
want the last page - where people has all the buttons and can click - to show up for people who have already claimed

We should also say "GIVdrop has ended"

@mosaeedi

**Comment by laurenluz** [comment]
Two conditions:

1. The connected wallet address has already claimed --> they should be redirected to the page with all the links.
2. The wallet is not connected, or the connected wallet address has not claimed/has no GIVdrop --> The user should see some simple page that says "The GIVdrop has ended, but you can still get GIV! Donate to verified projects and get GIV from GIVbacks." With a link to the projects page.

@Tosinolawale - can you make a quick mockup for the second point?

**Comment by Tosinolawale** [comment]
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18078%3A245663&t=9vBmD66lEsaRntWL-0
@laurenluz

**Comment by laurenluz** [comment]
@MohammadPCh - can you implement? for giveth.io/claim ?

Two scenaios:
- [ ] The wallet is not connected, or the connected wallet address has not claimed/has no GIVdrop [figma](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18078%3A245663&t=IbiNC0mCPppRA5XD-4)
![image](https://user-images.githubusercontent.com/75490971/214446479-a071258b-ea8b-4b05-a3c9-c4bf76bfe8a2.png)

- [ ] The connected wallet address has already claimed
![image](https://user-images.githubusercontent.com/75490971/214446625-2fca6361-7e33-4c73-9bc5-21ae798309b9.png)

**Comment by laurenluz** [comment]
@RamRamez or @mateodaza - can you take this? Cherik has no time

**Comment by mateodaza** [comment]
I can take it @laurenluz
