### ISSUE TITLE
GIVeconomy - GIVstream history table shows some weird stuff for the uniswap pool

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#199]
Old txs show up as "uniswap pool" when they should show up as "GIVfarm"

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/cc2064d2-f1c2-4a7d-8e91-5a29a2bf1fa2)

**Comment by MoeNick** [comment]
@aminlatifi pls approve before I assign it.

**Comment by aminlatifi** [comment]
Fixed, thanks @laurenluz
