### ISSUE TITLE
"Why Giveth" block

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#1992]
## Responsive guides

**(>1280)**
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17681%3A345499&t=HA0MWRVrAq4gj0Hq-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17681%3A345499&t=HA0MWRVrAq4gj0Hq-4)

**(>1024 - <1279)**
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17681%3A345762&t=HA0MWRVrAq4gj0Hq-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17681%3A345762&t=HA0MWRVrAq4gj0Hq-4)

**(>768 - <1023)**
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17681%3A346049&t=HA0MWRVrAq4gj0Hq-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17681%3A346049&t=HA0MWRVrAq4gj0Hq-4)

**(Mobile)**
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17681%3A346339&t=HA0MWRVrAq4gj0Hq-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17681%3A346339&t=HA0MWRVrAq4gj0Hq-4)

---

![Screenshot 2023-01-10 at 3.39.04 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/fe8117c0-0379-484b-9fc8-00cfc701b247)

**Comment by MoeNick** [comment]
Do we need backend support on this? @RamRamez @CarlosQ96 @mohammadranjbarz

**Comment by RamRamez** [comment]
> Do we need backend support on this? @RamRamez @CarlosQ96 @mohammadranjbarz

I have these endpoints and I can use them:
`projectsPerDate
totalDonorsCountPerDate
donationsTotalUsdPerDate`

They return data per month and but I just need the total amount.
I think these endpoints are not efficient. Since they are queried each time on homepage, we can have separate endpoints for total amounts.
@CarlosQ96 @mohammadranjbarz knows better than me

**Comment by mohammadranjbarz** [comment]
> > Do we need backend support on this? @RamRamez @CarlosQ96 @mohammadranjbarz
> 
> I have these endpoints and I can use them: `projectsPerDate totalDonorsCountPerDate donationsTotalUsdPerDate`
> 
> They return data per month and but I just need the total amount. I think these endpoints are not efficient. Since they are queried each time on homepage, we can have separate endpoints for total amounts. @CarlosQ96 @mohammadranjbarz knows better than me

Yeah as @RamRamez  said, it's better to implement new web service to just return needed data.
@MoeNick we can jump to it anytime you want

**Comment by MoeNick** [comment]
is there ay updates @aminlatifi ?

**Comment by aminlatifi** [comment]
> is there ay updates @aminlatifi ?

Made this PR https://github.com/Giveth/impact-graph/pull/818 to add the API

**Comment by mosaeedi** [comment]
@MoeNick this section style is updated.

**Take a look to compare!**
![Screenshot 2023-02-11 at 11.40.05 AM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/fab6deba-b05e-47da-bd72-a54e2a1cf63c)

## Changes
1. **Why Giveth** title is moved to the top center of this section
2. Tiny elements added
3. The font of the title for the numbers is changed to **Lead-medium** 
4. The background color added for the numbers section
5. Font of the **Recent donations** title is changed to **Body/B**

**Comment by mosaeedi** [comment]
FYI @MoeNick

**Comment by mosaeedi** [comment]
FYI @MoeNick
