### ISSUE TITLE
Latest Donations Ticker

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#1993]
## Note
This is part of the **Why Giveth** section and as we may use this on other screens, we also shared the separated row here as well.

To check the **Why Giveth** section please go to issue #1992

## Responsive guides

**(>1280)**
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17980%3A245808&t=HA0MWRVrAq4gj0Hq-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17980%3A245808&t=HA0MWRVrAq4gj0Hq-4)

**(>1024 - < 1279)**
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17980%3A245829&t=HA0MWRVrAq4gj0Hq-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17980%3A245829&t=HA0MWRVrAq4gj0Hq-4)

**(>768 - <1279)**
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17980%3A245850&t=HA0MWRVrAq4gj0Hq-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17980%3A245850&t=HA0MWRVrAq4gj0Hq-4)

**(Mobile)**
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17980%3A245871&t=HA0MWRVrAq4gj0Hq-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17980%3A245871&t=HA0MWRVrAq4gj0Hq-4)

---

![Screenshot 2023-01-10 at 4.04.03 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/ff26119c-2f64-43e5-aba7-6aab7e7a7a84)

**Comment by MoeNick** [comment]
if it's still not testable with staging data, let's put it back in progress and assigned a backend issue

**Comment by MoeNick** [comment]
Do we need backend support for it @RamRamez ?

**Comment by RamRamez** [comment]
> Do we need backend support for it @RamRamez ?

Yes, I need the latest donations.

**Comment by MoeNick** [comment]
@mohammadranjbarz don't we have any related webservices for this?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz don't we have any related webservices for this?
@MoeNick  @RamRamez 
We have this

```
  query (
    $fromDate: String
    $toDate: String
  ) {
    donations(
      fromDate: $fromDate
      toDate: $toDate
    ) {
        id
        transactionId
        transactionNetworkId
        toWalletAddress
        fromWalletAddress
        currency
        anonymous
        valueUsd
        amount
        user {
          id
          walletAddress
          firstName
          email
        }
        project {
          listed
          verified
          slug
          admin
          title
          categories {
            name
            id
          }
        }
        createdAt
        status
    }
  }
```

But it doesn't have sorting field input, if it's ok you can use it, otherwise please tell me or @CarlosQ96  we can modify this webservice as you want

**Comment by RamRamez** [comment]
> > @mohammadranjbarz don't we have any related webservices for this?
> 
> @MoeNick @RamRamez We have this
> 
> ```
>   query (
>     $fromDate: String
>     $toDate: String
>   ) {
>     donations(
>       fromDate: $fromDate
>       toDate: $toDate
>     ) {
>         id
>         transactionId
>         transactionNetworkId
>         toWalletAddress
>         fromWalletAddress
>         currency
>         anonymous
>         valueUsd
>         amount
>         user {
>           id
>           walletAddress
>           firstName
>           email
>         }
>         project {
>           listed
>           verified
>           slug
>           admin
>           title
>           categories {
>             name
>             id
>           }
>         }
>         createdAt
>         status
>     }
>   }
> ```
> 
> But it doesn't have sorting field input, if it's ok you can use it, otherwise please tell me or @CarlosQ96 we can modify this webservice as you want

Yes, I need the latest donations (at least 30) sorted by date

**Comment by MoeNick** [comment]
@mohammadranjbarz they need some changes. pleae update us here

**Comment by aminlatifi** [comment]
> > Do we need backend support for it @RamRamez ?
> 
> Yes, I need the latest donations.

@RamRamez We have added recentDonations api

**Comment by aminlatifi** [comment]
@RamRamez test here https://serve.giveth.io/graphql
```
query {
  recentDonations(take: 3) {
    createdAt
    id
    user {
      walletAddress
    }
    project {
      slug 
    }
  }
}

```

**Comment by RamRamez** [comment]
> @RamRamez test here https://serve.giveth.io/graphql
> 
> ```
> query {
>   recentDonations(take: 3) {
>     createdAt
>     id
>     user {
>       walletAddress
>     }
>     project {
>       slug 
>     }
>   }
> }
> ```

Thanks @aminlatifi . Is this possible to return project title instead of project slug?

**Comment by RamRamez** [comment]
@aminlatifi valueUsd is `null` for some donations. Is this ok?
![image](https://user-images.githubusercontent.com/73441857/214301579-110a5e02-b823-4053-926e-b2dace60265a.png)

**Comment by aminlatifi** [comment]
> @aminlatifi valueUsd is `null` for some donations. Is this ok? ![image](https://user-images.githubusercontent.com/73441857/214301579-110a5e02-b823-4053-926e-b2dace60265a.png)

Maybe it happens on the staging env! @CarlosQ96 @mohammadranjbarz You must know better than me

**Comment by aminlatifi** [comment]
> @RamRamez Made the PR [Giveth/impact-graph#823](https://github.com/Giveth/impact-graph/pull/823), on @CarlosQ96 call

@RamRamez Merged, will be available after a while

**Comment by mosaeedi** [comment]
To show the hover state please use a fade-in/out animation.

**Comment by RamRamez** [comment]
> To show the hover state please use a fade-in/out animation.

Done

**Comment by maryjaf** [comment]
Can I have the curl related to the calculation of these three fields?
Projects on Giveth
Donated to projects
Of givers

**Comment by RamRamez** [comment]
> Can I have the curl related to the calculation of these three fields? Projects on Giveth Donated to projects Of givers @RamRamez @aminlatifi

I will send them to you in discord

**Comment by MoeNick** [comment]
@maryjaf would u pls take a look again?

**Comment by maryjaf** [comment]
The name of the project does not have to be clickable? or by clicking on the displayed donation, the list of project donations will be displayed@MoeNick @RamRamez 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/111529185/217739762-22c83101-1b94-4865-af8b-50bdc03ab4a4.png">
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/111529185/217740129-dbd36ad4-5ce9-4bbf-aff3-a79737816ec3.png">

**Comment by maryjaf** [comment]
Will RECENT DONATIONS be updated after an hour? @RamRamez

**Comment by RamRamez** [comment]
> Will RECENT DONATIONS be updated after an hour? @RamRamez

My PR is not merged and reviewed yet, but after that, yes at most 5 min.

**Comment by laurenluz** [comment]
Hey @RamRamez - the design has chaged a little on this - can you check the figma [here](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19416%3A246933&t=gWHIidB6WJhpMUTc-4)

![image](https://user-images.githubusercontent.com/75490971/217908782-ff6fa306-a0a2-4584-b9a3-780723507a81.png)

cc @mosaeedi

**Comment by RamRamez** [comment]
> Hey @RamRamez - the design has chaged a little on this - can you check the figma [here](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19416%3A246933&t=gWHIidB6WJhpMUTc-4)
> 
> ![image](https://user-images.githubusercontent.com/75490971/217908782-ff6fa306-a0a2-4584-b9a3-780723507a81.png)
> 
> cc @mosaeedi

I did the desktop part. @mosaeedi Please add the responsive designs too.
