### ISSUE TITLE
"Featured Projects" Block

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#1994]
## Responsive guides

**(>1280)**
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17681%3A349773&t=HA0MWRVrAq4gj0Hq-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17681%3A349773&t=HA0MWRVrAq4gj0Hq-4)

**(>1024 - < 1279)**
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17681%3A349872&t=HA0MWRVrAq4gj0Hq-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17681%3A349872&t=HA0MWRVrAq4gj0Hq-4)

**(>768 - <1023)**
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17681%3A349971&t=HA0MWRVrAq4gj0Hq-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17681%3A349971&t=HA0MWRVrAq4gj0Hq-4)

**(Mobile)**
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17681%3A350070&t=HA0MWRVrAq4gj0Hq-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17681%3A350070&t=HA0MWRVrAq4gj0Hq-4)

---

![Screenshot 2023-01-10 at 3.29.14 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/e3583d96-2846-4350-be63-3c121e503b5a)

**Comment by mosaeedi** [comment]
On the mobile version, the campaign header section should have a 32 px margin on both sides, 
Take a look here:

![Screenshot 2023-01-31 at 5.09.44 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/91862f8a-f5ba-4406-b789-bafb28ac8858)

**Comment by mosaeedi** [comment]
Same issue with the project card
32px on Left/Right
![Screenshot 2023-01-31 at 5.13.30 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/ee166c36-6803-4894-9329-6c8b53896d7d)

**Comment by MoeNick** [comment]
@RamRamez Fyi

**Comment by RamRamez** [comment]
> @RamRamez Fyi

Done!

**Comment by maryjaf** [comment]
It seems that in showing search result we have a problem @mohammadranjbarz @MohammadPCh 
For example : MATAYTEST : 
Type : SortField & Sorting Field :Newest
but when I tap on search for mayatest campaign this page is shown:
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/6614a708-ebc0-4a1d-9616-99c4fc27af28)

![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/b09835e9-101d-46c5-9c7e-938f87d51638)
