### ISSUE TITLE
Custom Banners Block

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#1995]
As a Giveth user I want to see a list of active campaigns in new homepage, As a comms team member I want to have these active campaigns to users. 

![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/3ed589ea-d5fd-45f9-b38a-68fbd7624315)

PC Design:
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17711%3A350162&t=rxbw3GyI6hSF3HN0-4

**Comment by MoeNick** [comment]
@mosaeedi please provide Mobile and tablet view design links to this issue

**Comment by MoeNick** [comment]
@c0ric0ri fyi
please take a look at this issue and the backed issue: https://github.com/Giveth/impact-graph/issues/806

**Comment by MohammadPCh** [comment]
@MoeNick Yes for sure,
In the first step, we need to separate the banners by type, I think we have 2 types of blocks:
1. Block with projects
1.1 block with selected projects
1.2 block with filtered projects
2. Block with video

we need to add each block's properties and separate them completely.
Then we can start implementign it on adminJS and Dapps simultaneously.
@mohammadranjbarz what do you think?

**Comment by MoeNick** [comment]
What do you mean block by projects? There is only video in these blocks or a banner. We have another featured projects block which is dirrent from this.

**Comment by maryjaf** [comment]
when I set  **Type : manually** and **"sorting filed: for example: newest "**
The display of the campaign is not correct and there is a problem
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/00e6a1be-fe67-48b6-b364-d6fc212976f6)
@mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
> when I set **Type : manually** and **"sorting filed: for example: newest "** The display of the campaign is not correct and there is a problem
> 
> ![image.png](https://camo.githubusercontent.com/22e8c0cdbbd828928ffcd71ab418e829b7859580b39c26bceb5086df4b7b256f/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f64656166313062622d633839392d346637362d393335352d383065376563356130656461) ![image.png](https://camo.githubusercontent.com/68446dd47557bf64cb27cfbeb41d04d862115ca1efe125ab45539b017b8e019f/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f30306536613162652d666536372d343862362d623336342d643666633231323937366636) @mohammadranjbarz

If you set **Manually selected** you should add project manually, you did user-error with this action

**Comment by maryjaf** [comment]
> If you set **Manually selected** you should add project manually, you did user-error with this action

You right , but I think it's better to show the appropriate error to the user by selecting these two fields together
Because now we allow this, but in the end, the system does not work properly
