### ISSUE TITLE
"Project Activity" Block

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#1996]
![Screenshot 2023-01-20 at 4.07.02 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/d9753a98-e4f4-4f08-ab7d-b5468d4c920f)

## Video preview
https://youtu.be/FbZvGIOyC_w

## Notes:
The project activity section consists of, **Project updates** and **latest updates** 
you can see the separated issues here,

Project updates -> #2052

Latest updates -> #2053

**Comment by MoeNick** [comment]
It is but without responsive and mobile, can you start the pc version?

**Comment by MohammadPCh** [comment]
Yeah for sure :)
