### ISSUE TITLE
Intro block

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#1997]
## Responsive guides

**(>1280)**
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17955%3A231153&t=HA0MWRVrAq4gj0Hq-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17955%3A231153&t=HA0MWRVrAq4gj0Hq-4)

**(>1024 - <1279)**
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17955%3A233991&t=HA0MWRVrAq4gj0Hq-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17955%3A233991&t=HA0MWRVrAq4gj0Hq-4)

**(>768 - <1023)**
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17955%3A234602&t=HA0MWRVrAq4gj0Hq-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17955%3A234602&t=HA0MWRVrAq4gj0Hq-4)

**(Mobile)**
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17955%3A235217&t=HA0MWRVrAq4gj0Hq-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17955%3A235217&t=HA0MWRVrAq4gj0Hq-4)

---
## Design asset

[Download the Exported illustration here](https://app.zenhub.com/files/448919340/09575db7-c961-4c7a-891e-4333a499ed19/download)

---

![Screenshot 2023-01-10 at 3.23.17 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/362f18c9-3d47-48a3-89e5-f07ab53a09e5)

**Comment by mosaeedi** [comment]
@rodricastillo9013 We need to replace the illustration on this intro section on the new Homepage

**Comment by rodricastillo9013** [comment]
![Intro block (_1280   _1439)](https://user-images.githubusercontent.com/61791380/217864361-81f0d2ab-a281-45eb-839e-0b61999410b5.png)
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19746%3A248987&t=iSAY1P8haiCzc4Od-1 wdyt @MoeNick @mosaeedi

**Comment by laurenluz** [comment]
I love the graphic Rodri! Can you please add it to the updated version [here](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19416%3A246933&t=gWHIidB6WJhpMUTc-4)

And also take a look at the little icons hightlighed here (those two should change to coorespond to the copy appropriately).

![image](https://user-images.githubusercontent.com/75490971/217902753-4165b3a0-f2d0-4e80-987b-b12510eadc70.png)

**Comment by rodricastillo9013** [comment]
ok I'll check the icons! @laurenluz

**Comment by mosaeedi** [comment]
@rodricastillo9013 Whenever you have the icons, please just send them to me.

**Comment by mosaeedi** [comment]
FYI @MoeNick I've added the exported illustration to the issue details under the **Design asset**

**Comment by mosaeedi** [comment]
![Screenshot 2023-02-17 at 2.13.39 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/bc041958-19af-4781-93a6-6ba992b5d2e9)

@MoeNick I've updated this section on Figma with the new copy,
Also, a new paragraph is added below the main tagline.

The Easy onboarding box CTA color is changed to **Primary/GIV/500**
The other two boxes is updated with the new copy.

**Comment by maryjaf** [comment]
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/e510bf94-b9f5-4c58-8e58-feed1bcb67b3)
The links aren't shown, plz check @alireza-sharifpour

**Comment by alireza-sharifpour** [comment]
> ![image.png](https://camo.githubusercontent.com/20b7f5686dd0e32d8d03370bd93a513210d794a576ebdf9e49f0d9b4f80c935a/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f65353130626639342d623966352d346335382d386535382d666565643162636236376233) The links aren't shown, plz check @alireza-sharifpour

@mosaeedi Removed them because currently we don't have places to link them.
