### ISSUE TITLE
User Story - Projects should become unlisted when deactivated by project owner

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#1999]
**As a project owner, I want my project to be unlisted when I deactivate it, so that its not confusing.**

https://discord.com/channels/679428761438912522/835168432520429578/1058827208325595177

**Comment by MoeNick** [comment]
@MohammadPCh @CarlosQ96 I was thinking this works like this and we wrote tests for it, would you please check it again?

**Comment by CarlosQ96** [comment]
I checked the code, and when a project is deactivated it's a status change only. However this by default "unlists" the project from public endpoints because the query only searches for active projects.

But the listed remains the same. 

We should update the listed field too to false if the project was deactivated, just in case we don't make mistakes in the future when writing queries and missing a condition.
This can be done fast, ill push it tomorrow morning.

**Comment by MoeNick** [comment]
Do you have an update on this @CarlosQ96 ?

**Comment by CarlosQ96** [comment]
WIll push this tomorrow as a hotfix.

**Comment by MoeNick** [comment]
I can't see the PR? does it merge? can we test it? @CarlosQ96

**Comment by maryjaf** [comment]
Now when listed project is deactivated by project owner the status changed to "unlist" and when the project owner activate project the list status changed to NotReviewed correctly 
but I have one question
When the listed project is canceled or deactivated by admin user, should this field be changed to that unlist? @MoeNick @WhyldWanderer

**Comment by maryjaf** [comment]
> Thanks @mohammadranjbarz @CarlosQ96 Now when listed project is deactivated by project owner the status changed to "unlist" and when the project owner activate project the list status changed to NotReviewed correctly but I have one question When the listed project is canceled or deactivated by admin user, should this field be changed to that unlist? @MoeNick @WhyldWanderer

kindly reminder

**Comment by mohammadranjbarz** [comment]
> > Thanks @mohammadranjbarz @CarlosQ96 Now when listed project is deactivated by project owner the status changed to "unlist" and when the project owner activate project the list status changed to NotReviewed correctly but I have one question When the listed project is canceled or deactivated by admin user, should this field be changed to that unlist? @MoeNick @WhyldWanderer
> 
> kindly reminder

@CarlosQ96

**Comment by WhyldWanderer** [comment]
@maryjaf yes I believe so

**Comment by MoeNick** [comment]
@CarlosQ96 can you take it, if the action took place by admin?

**Comment by CarlosQ96** [comment]
@MoeNick the action took place as I added it for the deactivation.

I'll add it today for canceled status like Maryjaf mentioned.  Is there any other status I should include?
```
export enum ProjStatus {
  rejected = 1,
  pending = 2,
  clarification = 3,
  verification = 4,
  active = 5,
  deactive = 6,
  cancelled = 7,
  drafted = 8,
}
```

**Comment by CarlosQ96** [comment]
@WhyldWanderer if the admin deactivated project should it also lose the verified status?

Right now only when cancelled that happens.

**Comment by MoeNick** [comment]
No the verified status remains @CarlosQ96
