### ISSUE TITLE
Fix zIndex issue of success view of donation

### ISSUE THREAD

**Issue by alireza-sharifpour** [Giveth/giveth-dapps-v2#2001]
There is an issue with zIndex in success view of donation that @divine-comedian mentioned in the Dev channel.
The animation is on top of our image and Learn more button.

**Comment by divine-comedian** [comment]
testing on https://staging.giveth.io/donate/herbs-and-drugs-and-tools-to-combat-sleepiness

made a donation and on the success page I can see all animations and images and the learn more button is functional! this looks to be resolved on staging!

![image](https://user-images.githubusercontent.com/67759413/210371190-f3282c42-afb0-4de7-8b32-860ca9e9c484.png)
