### ISSUE TITLE
Changing the error message during the transaction Reject Donation

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#2002]
**Describe the bug**

<img width="1352" alt="image" src="https://user-images.githubusercontent.com/111529185/210500024-1c34e32f-b281-4adf-b5ff-0411a2a16228.png">

**To Reproduce**
1. Go to 'projects'
2. Click on 'donation'
3. Set amount of Givpower and click on 'donate'
4. Then click on 'Reject'

**Comment by MoeNick** [comment]
@maryjaf pls take a look
