### ISSUE TITLE
Show zero give power in the list of project give powers

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#2003]
**Describe the bug**
when a user unstake your givpower and the givpower of user changed to zero , in the list of project boosts, this user is still displayed with 0 Give Power

<img width="954" alt="image" src="https://user-images.githubusercontent.com/111529185/210524092-4571dec2-dd93-4864-944b-bea2367c150b.png">

**Expected behavior**
In this situation, should the user be removed from the list? @laurenluz

**Comment by laurenluz** [comment]
yes! we should remove their boost from the list in that case.

@MohammadPCh - can you fix it?

**Comment by MohammadPCh** [comment]
Do we need to release a hotfix for it? or just put it on the staging? @laurenluz

**Comment by laurenluz** [comment]
sorry for the delay @MohammadPCh !

@maryjaf - can you test?

**Comment by maryjaf** [comment]
> sorry for the delay @MohammadPCh !
> 
> @maryjaf - can you test?

I tested this and now when I unstake my all givpower , my user is removed  from the list of project's givpower
but in my givpower It is displayed as below:
![image](https://user-images.githubusercontent.com/111529185/213406571-1ac180d9-3703-471e-ae9d-409507080ec0.png)
I think it should be removed from this list as well? Am I right?

**Comment by MohammadPCh** [comment]
@maryjaf It totally depends on PM's decision :) but I think it's good to show them somewhere to the user.

**Comment by MoeNick** [comment]
@laurenluz can you confirm this scenario?

**Comment by laurenluz** [comment]
This is an interesting edge case, I think it is nice to "remember" the user's allocations even if they unstake their GIV, so that if they stake again, it is already distributed.

However, one 1st glance it's confusing, so I think we should have some kind of message if this happens. Something that says (above the table, maybe in red @mosaeedi ? )

"Your GIVpower balance is zero! Stake GIV to boost these projects again."

"Stake GIV" should link to the GIVfarm.

![image](https://user-images.githubusercontent.com/75490971/214151741-f96e5c6e-e3ee-4868-9808-94c5a4637260.png)

wdyt @MohammadPCh @maryjaf ?

**Comment by MoeNick** [comment]
@mosaeedi @Tosinolawale please update us

**Comment by MoeNick** [comment]
Hey @mosaeedi @Tosinolawale pls at east add a reaction! :)

**Comment by mosaeedi** [comment]
## Design resource

[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=20258%3A253718&t=m5jzLf2nKFB3AjEk-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=20258%3A253718&t=m5jzLf2nKFB3AjEk-4)

---


<img width="1023" alt="Screenshot 2023-02-20 at 2 00 19 PM" src="https://user-images.githubusercontent.com/13708322/220080530-2cdcc376-dbd3-4083-af32-8c35c18e3cab.png">

**Comment by MohammadPCh** [comment]
Thanks @mosaeedi.
@MoeNick @laurenluz can we start it?

**Comment by MoeNick** [comment]
Yes please @MohammadPCh 
Thanks to @mosaeedi and you.

**Comment by maryjaf** [comment]
Thanks @RamRamez @MohammadPCh I checked and it passed
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/111529185/223116337-2900e142-2fe9-4b0a-af29-1b1177299835.png">
