### ISSUE TITLE
Check to see how much GIV was actually claimed from the GIVdrop

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2005]
Is the number on this dashboard right? https://dune.com/metacrypto/giveconomy

@aminlatifi - can you check it? Would be good to have for accounting purposes

cc @GriffGreen @divine-comedian

**Comment by laurenluz** [comment]
We want to know basically how much GIV was added to our budget so we know how much extra we have to repurpose

**Comment by aminlatifi** [comment]
We have two options,
1. See how much we have initially allocated to MerkleDistro on TokenDistro contract, and compare it with its current balance.
2. Query subgraph to obtain all token allocation from givdrop (MerkleDistro)
Subgraph URL: https://api.thegraph.com/subgraphs/name/giveth/giveth-economy-second-xdai
Query: 
```graphql
{
  tokenAllocations(first: 1000, where: {distributor: "givdrop"}, orderBy: recipient, orderDirection: asc){
    amount
    recipient
    distributor
  }
}
```

**Comment by divine-comedian** [comment]
checking from our tokenDistro on gnosis chain:
https://gnosisscan.io/address/0xc0dbdca66a0636236fabe1b3c16b1bd4c84bb1e1#readProxyContract#F3

If I look at the remaining balance allocated to the merkleDistro (GIVdrop) it is **74,452,829** GIV
merkleDistro = `0xFad63adEFb8203F7605F25f6a921c8bf45604A5e`

according to our GIVeconomy genesis spreadsheets we allocated a total **170,500,000 GIV** to the GIVdrop
https://docs.google.com/spreadsheets/d/1gJhdAv6uLDuGMI6PMHUAD3aODy_wTyxtiYv369x4GfA/edit#gid=1364393049

so my assumption is that this is a valid way to get the unclaimed GIVdrop funds and that we would have thus **74,452,829** GIV that we can reclaim for future purposes. 

That means a total of **96,047,171 GIV was claimed from the original total GIVdrop number**
Looks like the dune dashboard was off by a factor of 10 more or less

**Comment by aminlatifi** [comment]
I ran a script to go through the second approach (querying the subgraph). 
https://gist.github.com/aminlatifi/072061880d869bf7937d36f08a20006d

The value I obtained for the total GIVdrop claim is **96,047,144 GIV**
Super close!

**Comment by MoeNick** [comment]
@divine-comedian would you please check it issue.

**Comment by divine-comedian** [comment]
yes!
