### ISSUE TITLE
Add GIVpower Video to GIVpower Page

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-dapps-v2#2011]
Would be great to add our new GIVpower explainer launch video to our [GIVpower homepage](https://giveth.io/givpower).

@laurenluz @markoprljic

**Comment by laurenluz** [comment]
@markoprljic @mosaeedi - wdyt? Is this worth adjusting the design for before we do the full GIVeconomy redesign?

**Comment by markoprljic** [comment]
Depending on how far is the GIVecomony launch, adding the video shouldn't be much effort IMHO. We can put it anywhere on the page, preferably around the "How does GIVpower work?" section.

**Comment by c0ric0ri** [comment]
I feel like it's worth it with the Gitcoin grants round coming up and our comms efforts around it. It's hard to find this video unless you happen to catch a tweet about it, and we're trying to promote GIVpower all the time in talking points so it would be great if we could link to the landing page with more confidence. Just my 2 cents here

**Comment by mosaeedi** [comment]
Okay, I'll update the GIVpower page.

**Comment by MoeNick** [comment]
Hey can we have a quick fix? @mosaeedi

**Comment by MoeNick** [comment]
Hey hey @mosaeedi do you have an update?

**Comment by mosaeedi** [comment]
<img width="914" alt="Screenshot 2023-01-31 at 1 52 56 PM" src="https://user-images.githubusercontent.com/13708322/215734049-a1ce2c5d-da6f-44fa-97c8-31612fa180b9.png">

I've added the video block here on the GIVpower tab, What do you guys think? if that's ok, I can add the design resource as well.

**Comment by c0ric0ri** [comment]
Just some feedback @mosaeedi, I see GIVpower three times stacked on top of each other with the titles so I would change this.

How about just "Boost Projects" (instead of Boost Projects with GIVpower)

And, I would personally say that the video can stand on its own right **above** that. It will be bigger across the screen and serves as an engaging introduction (like how we have the GIVeconomy page set up). We could remove "Defining GIVpower - Learn more about GIVpower and see how you can use it too" because the big "GIVpower - Use GIV to boost projects to new heights!" already serves as an intro.

So:

1. GIVpower - Use GIV to boost projects to new heights!
2. Video on it's own
3. Boost Projects with GIVpower section

**Comment by laurenluz** [comment]
I like @c0ric0ri 's suggestions here!

**Comment by mosaeedi** [comment]
I agree with most parts, except it would be better to have a title and short description (with better copy) alongside the video so users would know what this video is about and have more reason to click on the play!

**Comment by mosaeedi** [comment]
The video block is the same as the one we have on the new homepage, so I didn't add the responsive guides here again.

You can take a look at the design here -> [Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19229%3A246662&t=bsDBTwQIyCNdB34G-4)

**Comment by laurenluz** [comment]
cool - who should we pass this to @MoeNick ?

**Comment by MoeNick** [comment]
@RamRamez this is a quick fix, thanks.

**Comment by MoeNick** [comment]
@laurenluz @mosaeedi do we also have to remove this video from GIVeconomy Overview page? or we leave it like as is?

**Comment by laurenluz** [comment]
@markoprljic said to leave it on both. So leave it like it is.

**Comment by MoeNick** [comment]
@MohammadPCh heads up for probable conflicts on staging.
