### ISSUE TITLE
Video Block

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#2015]
### (>1280)
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18282%3A247654&t=aiPuxojK60VosJQg-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18282%3A247654&t=aiPuxojK60VosJQg-4)

### (>1024 - <1279)
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18282%3A247709&t=aiPuxojK60VosJQg-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18282%3A247709&t=aiPuxojK60VosJQg-4)

### (>768 - <1023)
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18282%3A247755&t=aiPuxojK60VosJQg-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18282%3A247755&t=aiPuxojK60VosJQg-4)

### (Mobile)
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18282%3A247799&t=aiPuxojK60VosJQg-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18282%3A247799&t=aiPuxojK60VosJQg-4)

**Comment by maryjaf** [comment]
On which test environment can it be tested? @alireza-sharifpour

**Comment by alireza-sharifpour** [comment]
> On which test environment can it be tested? @alireza-sharifpour

It can be tested here:
https://giveth-homepage.vercel.app/
@maryjaf

**Comment by ahmadabugosh** [comment]
Here you go: https://drive.google.com/file/d/1nRkaHo9NIdqfm8TLCDLm577ePofogl9a/view?usp=share_link

**Comment by maryjaf** [comment]
> > On which test environment can it be tested? @alireza-sharifpour
> 
> It can be tested here: https://giveth-homepage.vercel.app/ @maryjaf

The current video is different from the one shared above
Is this not done yet? @alireza-sharifpour

**Comment by ahmadabugosh** [comment]
Hey team,  as per @mosaeedi 's request I made another version of the video https://drive.google.com/file/d/1zZr00JQdWnSYZd4djC7pAhIkE8GxEZuI/view?usp=sharing
