### ISSUE TITLE
"About Giveconomy"  Block

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#2016]
### (>1280 & <1439)
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17975%3A231415&t=Gn0Pg2XrJhFLGABA-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17975%3A231415&t=Gn0Pg2XrJhFLGABA-4)

### (>1024  & <1279)
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17975%3A232330&t=Gn0Pg2XrJhFLGABA-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17975%3A232330&t=Gn0Pg2XrJhFLGABA-4)

### (>768  & <1024)
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17975%3A233201&t=Gn0Pg2XrJhFLGABA-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17975%3A233201&t=Gn0Pg2XrJhFLGABA-4)

### (Mobile)
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17975%3A234074&t=Gn0Pg2XrJhFLGABA-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17975%3A234074&t=Gn0Pg2XrJhFLGABA-4)

## Download Assets

[Download the illustrations](https://app.zenhub.com/files/448919340/71d22f81-2a0b-45b1-b1bf-58550744a2f2/download)

---

**Comment by MoeNick** [comment]
For finalizing the Copies and design let's mention @c0ric0ri and @laurenluz here before starting the dev side. @MohammadPCh

**Comment by MohammadPCh** [comment]
@mateodaza can you take it, please?

**Comment by laurenluz** [comment]
hold up though - this page might change - @c0ric0ri is working on edits

**Comment by laurenluz** [comment]
@mateodaza - the figma has been updated with  the new copy & other fixes/rearrangements.

Check it out [here](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19416%3A246933&t=bu6wUm3l3Hwh3pqH-4)

![image](https://user-images.githubusercontent.com/75490971/217881943-9f7e71f9-709a-4762-bc43-802b41ad1932.png)

cc @mosaeedi @MoeNick @c0ric0ri

**Comment by laurenluz** [comment]
FYI - graphics will change! @rodricastillo9013 is working on them

**Comment by MoeNick** [comment]
@mosaeedi design resources please!

**Comment by mosaeedi** [comment]
@mateodaza @MoeNick 
The copy is final, we are just waiting for @rodricastillo9013 to finalize the illustrations.

**Comment by mateodaza** [comment]
Thanks @mosaeedi !

**Comment by mateodaza** [comment]
@c0ric0ri @laurenluz @MoeNick I put some links on the buttons there but I'm not sure where to redirect, right now it's like

- learn more about giveth => /giveconomy
- level up with givpower => /givpower
- discover our roadmap => https://docs.giveth.io/whatisgiveth/

The one I have more doubts is in the last one, please let me know what to set there :)

**Comment by laurenluz** [comment]
@mateodaza - those links are great for now - way to use your thinking brain 🧠 

A couple of issues just from a quick test:
- subtitle text should be italicized & closer to title text.

Test: ![image](https://user-images.githubusercontent.com/75490971/220176072-0b9eaadf-15a7-4772-b0f5-d7a2bd795494.png)
vs.
Design: ![image](https://user-images.githubusercontent.com/75490971/220176267-e5f1a4c4-6e65-4b99-a038-d03fc84bcae8.png)

- The graphics should be changed to reflect those [here](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=20091%3A249949&t=E9EL6bNWswVV4LPG-4) (sorry for all the confusion)

**Comment by mateodaza** [comment]
@laurenluz fixed on this [PR](https://github.com/Giveth/giveth-dapps-v2/pull/2229) 😄

**Comment by mosaeedi** [comment]
@laurenluz, our font book doesn't have an italic font in this size!
The font for the subtitle is Body/Lead-medium and that's not italic.

**Comment by maryjaf** [comment]
This is on home page branch and different  with figma
home page branch:
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/77c4b8b7-dfac-4947-9179-2cb2cb45d65b)
Figma:

![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/3c0a6fb5-a477-40c4-aff4-a7e3d41a31e6)

**Comment by mosaeedi** [comment]
@mateodaza @MoeNick 
I've uploaded all art in SVG format
Please update this section with the SVG assets.



[Homepage SVG assets](https://app.zenhub.com/files/448919340/010cc991-f4fc-4450-affb-a7285c72dab6/download)
