### ISSUE TITLE
Blog Updates Block

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#2018]
## Responsive guides

**(>1280)**
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17980%3A245340&t=HA0MWRVrAq4gj0Hq-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17980%3A245340&t=HA0MWRVrAq4gj0Hq-4)

**(>1024 - <1279)**
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17980%3A245420&t=HA0MWRVrAq4gj0Hq-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17980%3A245420&t=HA0MWRVrAq4gj0Hq-4)

**(>768 - <1023)**
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17980%3A245456&t=HA0MWRVrAq4gj0Hq-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17980%3A245456&t=HA0MWRVrAq4gj0Hq-4)

**(Mobile)**
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17980%3A245492&t=HA0MWRVrAq4gj0Hq-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17980%3A245492&t=HA0MWRVrAq4gj0Hq-4)

---

![Screenshot 2023-01-10 at 4.16.36 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/498d3f5c-443c-4513-9fa8-7698ff05a807)

**Comment by laurenluz** [comment]
The copy here should change: 

![image](https://user-images.githubusercontent.com/75490971/217909280-3456464b-cb85-4104-8b20-9e008f02dca8.png)


Figma:
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19416%3A251612&t=gWHIidB6WJhpMUTc-4

**Comment by RamRamez** [comment]
> The copy here should change:
> 
> ![image](https://user-images.githubusercontent.com/75490971/217909280-3456464b-cb85-4104-8b20-9e008f02dca8.png)
> 
> Figma: https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19416%3A251612&t=gWHIidB6WJhpMUTc-4

Done!
