### ISSUE TITLE
New menu: Project's sub-menu

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#2019]
### Light menu
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17955%3A230642&t=huSwZsLxPMwnLBB2-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17955%3A230642&t=huSwZsLxPMwnLBB2-4)

### Dark menu
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17978%3A239874&t=huSwZsLxPMwnLBB2-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17978%3A239874&t=huSwZsLxPMwnLBB2-4)

---

### Light menu
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18047%3A242231&t=huSwZsLxPMwnLBB2-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18047%3A242231&t=huSwZsLxPMwnLBB2-4)

### Dark menu
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18047%3A243268&t=huSwZsLxPMwnLBB2-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18047%3A243268&t=huSwZsLxPMwnLBB2-4)

**Comment by MoeNick** [comment]
I have to create backend issues for this one.

**Comment by MoeNick** [comment]
Let's remove Popular and Trending for now an have discussion about it later.

**Comment by MoeNick** [comment]
@MohammadPCh I tink your blocker is removed, shall I move it to unit testing?

**Comment by MohammadPCh** [comment]
Yes, Please.
Thanks @MoeNick

**Comment by maryjaf** [comment]
Based on the latest update, the following submenus are displayed:
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/4eb9db34-8838-4493-9655-3a1a108fd1f5)
