### ISSUE TITLE
New menu: GIVeconomy sub-menu

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#2020]
# Responsive guides

### Light
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17955%3A230645&t=huSwZsLxPMwnLBB2-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17955%3A230645&t=huSwZsLxPMwnLBB2-4)

### Dark
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17978%3A239877&t=huSwZsLxPMwnLBB2-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17978%3A239877&t=huSwZsLxPMwnLBB2-4)

### Light
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18047%3A242450&t=huSwZsLxPMwnLBB2-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18047%3A242450&t=huSwZsLxPMwnLBB2-4)

### Dark
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18047%3A243322&t=huSwZsLxPMwnLBB2-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18047%3A243322&t=huSwZsLxPMwnLBB2-4)

**Comment by maryjaf** [comment]
I tested on https://giveth-homepage.vercel.app/ and based on the figma the wallet menu is ok
