### ISSUE TITLE
word-break issue notification menu

### ISSUE THREAD

**Issue by alireza-sharifpour** [Giveth/giveth-dapps-v2#2026]
<img width="290" alt="Screen Shot 2023-01-10 at 4 28 04 PM" src="https://user-images.githubusercontent.com/48887817/211557822-e5f5b9d5-03ec-4939-a3f8-dd18db5ea700.png">

**Comment by MoeNick** [comment]
@alireza-sharifpour can you provide teh test scenario for @maryjaf

**Comment by alireza-sharifpour** [comment]
If the project name is something like a WalletAddress(without spaces) and that project receives a like it can be tested.
@maryjaf

**Comment by maryjaf** [comment]
Thanks @alireza-sharifpour It's ok
<img width="259" alt="image" src="https://user-images.githubusercontent.com/111529185/214340348-44f85832-5629-4e5a-8bf8-8f38b80799a5.png">
