### ISSUE TITLE
Giveth TRACE is over - splashpage

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2029]
We need a splashpage on the trace.giveth.io since it has been deprecated.

It should say something simple like:

"Giveth TRACE has been deprecated."
and a button "Go to giveth.io"

We need a quick design for this - nothing complicated, just simply & pretty.

@Tosinolawale @mosaeedi - can you take it?

**Comment by Tosinolawale** [comment]
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18076%3A246767&t=9vBmD66lEsaRntWL-0
@laurenluz

**Comment by MoeNick** [comment]
if it needs your confirmation @laurenluz , let's put it in design column.

**Comment by laurenluz** [comment]
@MoeNick I think it's good!

@MohammadPCh @aminlatifi - happy with this? can we implement?

**Comment by aminlatifi** [comment]
@laurenluz @MoeNick @Tosinolawale We don't need to do a heavy job. Besides, it's better to keep trace functionality visible for later demos.
I suggest just editing this banner text
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/5684607/213186734-c3c0751d-098c-4f89-a818-a57402b2445b.png">

And disable modification buttons

**Comment by laurenluz** [comment]
Can we just have the splashpage have a hidden corner that you can click to get behind it for any demos?

**Comment by laurenluz** [comment]
or do you have a specifc user in mind? @aminlatifi

**Comment by aminlatifi** [comment]
That's an idea. Just a point, this splash is created by design system components. @RamRamez do you think we can easily use that in Trace?

**Comment by MohammadPCh** [comment]
@laurenluz  @aminlatifi It's easy to implement. just left it to us and don't worry about it :sunglasses:

**Comment by MohammadPCh** [comment]
@RamRamez can you take it?

**Comment by RamRamez** [comment]
> @RamRamez can you take it?

Yeah, sure.

**Comment by laurenluz** [comment]
@RamRamez - awesome! So there are two points:

- [ ] implement a splash page, so that when the user goes to trace.giveth.io, they just see [this](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18076%3A246767&t=BdJCYA1BXXPwd91Y-4) 
     - [ ] "Go to Giveth.io" links to https://giveth.io/ (of course)


![image](https://user-images.githubusercontent.com/75490971/214155659-900b12e1-5062-402a-894e-5e9926394dd5.png)




- [ ] if they close the splashpage, they can see the dapp, but we change the banner text. It should say "**Giveth TRACE has been deprecated.** Go to giveth.io to explore public goods projects.
     - [ ] we should remove the little gas tank icon
     - [ ] & giveth.io should also link to the dapp.

![image](https://user-images.githubusercontent.com/75490971/214154739-dfd73d60-b24c-4485-8441-c679bd1ccdba.png)

**Comment by laurenluz** [comment]
@RamRamez - you working on this? :)

**Comment by RamRamez** [comment]
> @RamRamez - you working on this? :)

I sent the [PR](https://github.com/Giveth/giveth-dapp/pull/2610) yesterday and it's waiting for review.

**Comment by MoeNick** [comment]
@maryjaf please take a look here and approve
https://deploy-preview-2610--giveth-trace.netlify.app/

**Comment by maryjaf** [comment]
I checked this and it is approved

> @maryjaf please take a look here and approve https://deploy-preview-2610--giveth-trace.netlify.app/

**Comment by RamRamez** [comment]
@MoeNick

> I checked this and it is approved
> 
> > @maryjaf please take a look here and approve https://deploy-preview-2610--giveth-trace.netlify.app/

@MoeNick
