### ISSUE TITLE
Missing article before "for-good project"

### ISSUE THREAD

**Issue by danelsuga** [Giveth/giveth-dapps-v2#203]
![calling all.jpg](https://images.zenhubusercontent.com/6066d509782b4d63df5cd761/542a3b9d-c34a-45ad-8c85-2c73b5dd5bb6)

Should read: "Do you have a for-good project that's creating value for society, for the environment or for the world?"

**Comment by mateodaza** [comment]
there is a duplicate about this, fixed

**Comment by danelsuga** [comment]
Sorry! Thought I'd checked. Thank you.
