### ISSUE TITLE
Remove illiquid & very volatile tokens from GIVbacks token list

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2031]
@brichis did some great work to determine which tokens on the GIVbacks token list where very volatile or with low liquidity that we should now remove.

Here is the list from the [forum](https://forum.giveth.io/t/givbacks-token-list/253/17).

## Mainnet GIVbacks Token List
|Name|Symbol|Address|
|---|---|---|
|dAppNode|NODE|0xda007777d86ac6d989cc9f79a73261b3fc5e0da0|
|TerraUSD|UST|0xa47c8bf37f92abed4a126bda807a7b7498661acd|
|Wrapped MIR Token|MIR|0x09a3ecafa817268f77be1283176b946c4ff2e608|
|HedgeTrade|HEDG|0xf1290473e210b2108a85237fbcd7b6eb42cc654f|
|The Midas Touch Gold|TMTG|0x10086399dd8c1e3de736724af52587a2044c9fa2|
|Hyperion|HYN|0xe99a894a69d7c2e3c92e61b64c505a6a57d2bc07|
|HUSD|HUSD|0xdf574c24545e5ffecb9a659c229253d4111d87e1|
|Celsius|CEL|0xaaaebe6fe48e54f431b0c390cfaf0b017d09d42d|
|ZB Token|ZB|0xbd0793332e9fb844a52a205a233ef27a5b34b927|
|DxChain Token|DX|0x973e52691176d36453868d9d86572788d27041a9|
|Mixin|XIN|0xa974c709cfb4566686553a20790685a47aceaa33|
|MCO|MCO|0xb63b606ac810a52cca15e44bb630fd42d8d1d83d|
|Egoras|EGR|0x73cee8348b9bdd48c64e13452b8a6fbc81630573|
|APIX|APIX|0xf51ebf9a26dbc02b13f8b3a9110dac47a4d62d78|
|Unibright|UBT|0x8400d94a5cb0fa0d041a3788e395285d61c9ee5e|
|CyberVein|CVT|0xbe428c3867f05dea2a89fc76a102b544eac7f772|
|BTU Protocol|BTU|0xb683d83a532e2cb7dfa5275eed3698436371cc9f|
|Digitex Futures|DGTX|0xc666081073e8dff8d3d1c2292a29ae1a2153ec09|
|Xensor|XSR|0x6bc1f3a1ae56231dbb64d3e82e070857eae86045|
|Dragonchain|DRGN|0x419c4db4b9e25d6db2ad9691ccb832c8d9fda05e|
|Pundi X|NPXS|0xa15c7ebe1f07caf6bff097d8a589fb8ac49ae5b3|
|Molecular Future|MOF|0x653430560be843c4a3d143d0110e896c2ab8ac0d|
|Crypterium|CRPT|0x80a7e048f37a50500351c204cb407766fa3bae7f|
|Ripio Credit Network|RCN|0xf970b8e36e23f7fc3fd752eea86f8be8d83375a6|
|BHEX Token|BHT|0xfc29b6e626b67776675fff55d5bc0452d042f434|
|Idle Finance|IDLE|0x875773784Af8135eA0ef43b5a374AaD105c5D39e|
|Cryptex|CTX|0x321c2fe4446c7c963dc41dd58879af648838f98d|
|Moss Carbon Credit|MCO2|0xfc98e825a2264d890f9a1e68ed50e1526abccacd|
|Somnium Space Cubes|CUBE|0xdf801468a808a32656d2ed2d2d80b72a129739f4|
|Wrapped LUNA Token|LUNA|0xd2877702675e6ceb975b4a1dff9fb7baf4c91ea9|
|The Burn Token|ASH|0x71590d4ed14d9cbacb2cff8abf919ac4d22c5b7b|

## xDai GIVbacks Token List
|Name|Symbol|Address|
|---|---|---|
|Curve DAO Token|CRV|0x1337BedC9D22ecbe766dF105c9623922A27963EC|
|dAppNode on xDAI|XNODE|0xc60e38C6352875c051B481Cbe79Dd0383AdB7817|
|STAKE on xDai|STAKE|0xb7D311E2Eb55F2f68a9440da38e7989210b9A05e|
|Moons on xDai|xMOON|0x1e16aa4Df73d29C029d94CeDa3e3114EC191E25A|
|Tether USD on xDai|USDT|0x4ECaBa5870353805a9F068101A40E0f32ed605C6|
|Agave Token|AGVE|0x3a97704a1b25F08aa230ae53B352e2e72ef52843|
|xDAI Native Comb|XCOMB|0x38Fb649Ad3d6BA1113Be5F57B927053E97fC5bF7|
|DAOhaus|HAUS|0xb0C5f3100A4d9d9532a4CfD68c55F1AE8da987Eb|

More detailed analysis can be found in [this spreadsheet](https://docs.google.com/spreadsheets/d/1Wpsdx9Kii1vWlP6qNlP_pHpSBQvQQVtbLfM6MOUX74o/edit#gid=0) FYI

@mohammadranjbarz  or @CarlosQ96  - can you take this?

cc @MoeNick

**Comment by MoeNick** [comment]
I think comms team can do it at adminbro themselves. @WhyldWanderer can manage it easily I guess.

**Comment by WhyldWanderer** [comment]
I can remove those tokens... 

Im curious how this coincides with the process of token nomination in the forum. Will the process for nominating tokens still be the same?

**Comment by WhyldWanderer** [comment]
The tokens have been removed!

@laurenluz can you edit your original forum post to exclude these tokens? And/or maybe make a comment that explains what happened or something?

**Comment by WhyldWanderer** [comment]
@MoeNick Should I move this issue to QA now? Whats the flow for this one?

**Comment by mohammadranjbarz** [comment]
@MoeNick  @WhyldWanderer 
Yeah you are totally right it can be done by admin panel, and you don't need to remove token, you just should edit token and unmark to **is Givback Eligible** checkbox

<img width="1440" alt="Screen Shot 1401-10-22 at 09 08 23" src="https://user-images.githubusercontent.com/9850545/211986325-2aba8454-df4e-4f5b-be3d-1528cb6f4542.png">

**Comment by MoeNick** [comment]
I moved it to QA for more review by @laurenluz or @maryjaf on production.

**Comment by MoeNick** [comment]
@brichis can you pleae take a look at giveth,io and make sure the changes are correct?

**Comment by laurenluz** [comment]
@brichis - he's asking if you can go to the dApp on production and double check to make sure that the list of tokens is the same as the list here. Did you do that?

We should not have UST or LUNA in drop down list anymore on the dapp. Can you check?

**Comment by brichis** [comment]
I checked that every token in the list doesn't have GIV elegible icon on Giveth.io but for example LUNA is still available to donate, the only thing is that you won't receive GIVbacks for that donation. @laurenluz 
Is ok like that? Tomorrow I can check again if I miss something :)

**Comment by laurenluz** [comment]
I think it's better if we remove then from the drop down list all together. @brichis @MoeNick 

UST & LUNA are embarassing at this point

**Comment by brichis** [comment]
GM! @laurenluz @MoeNick I did a quick review as Griff told me but I think we still accepting donations with that tokens

![Screenshot 2023-02-01 at 12.18.51.png](https://images.zenhubusercontent.com/635c6dd0ed86045e2c4cd152/0d5679d5-b68a-4e52-bc47-7c8d480c112a)

**Comment by maryjaf** [comment]
I don't have access to the production admin, but I tested the following scenario on the stage
I disabled the "Is Givback Eligible" for the X-node token from the admin panel
But it is still displayed in the list of tokens
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/111529185/216264987-6f2678f5-8bd8-44b3-89b9-b55c27193433.png">
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/111529185/216265057-294b6ef4-8e7f-4adb-b9b4-1808730e0665.png">
It seems that the function of disabling this field does not work properly

**Comment by mohammadranjbarz** [comment]
> I don't have access to the production admin, but I tested the following scenario on the stage I disabled the "Is Givback Eligible" for the X-node token from the admin panel But it is still displayed in the list of tokens <img alt="image" width="1438" src="https://user-images.githubusercontent.com/111529185/216264987-6f2678f5-8bd8-44b3-89b9-b55c27193433.png"> <img alt="image" width="1072" src="https://user-images.githubusercontent.com/111529185/216265057-294b6ef4-8e7f-4adb-b9b4-1808730e0665.png"> It seems that the function of disabling this field does not work properly

@RamRamez  @MohammadPCh 
Do you filter tokens with `isGivbackEligible` field, in this place?
or if you expect we dont return non givback eligible tokens in get tokens web service tell us to change the backend web service

**Comment by RamRamez** [comment]
> > I don't have access to the production admin, but I tested the following scenario on the stage I disabled the "Is Givback Eligible" for the X-node token from the admin panel But it is still displayed in the list of tokens <img alt="image" width="1438" src="https://user-images.githubusercontent.com/111529185/216264987-6f2678f5-8bd8-44b3-89b9-b55c27193433.png"> <img alt="image" width="1072" src="https://user-images.githubusercontent.com/111529185/216265057-294b6ef4-8e7f-4adb-b9b4-1808730e0665.png"> It seems that the function of disabling this field does not work properly
> 
> @RamRamez @MohammadPCh Do you filter tokens with `isGivbackEligible` field, in this place? or if you expect we dont return non givback eligible tokens in get tokens web service tell us to change the backend web service

We don't filter, we show all tokens. Givback eligible tokens have a `hand` icon beside it and in @maryjaf pic, there is no icon for XNODE so it's ok

**Comment by mohammadranjbarz** [comment]
@RamRamez  thanks man

**Comment by MoeNick** [comment]
So are you going to remove them from DB or are you going to create a remove option in admin? @mohammadranjbarz

**Comment by laurenluz** [comment]
@brichis - are you sure that USDT should be removed from gnosis chain? @Cotabe is saying that there is good liquidity

**Comment by Cotabe** [comment]
I'm saying I think so... Unfortunately, its not so easy to see. But I made my research. This is what I found:

Honeyswap has about 2.5 K USD in liquidity
![USDT liquidity honeyswap](https://user-images.githubusercontent.com/101358184/217576649-00dece9d-0242-4b1b-8ddd-03a7663a01d9.PNG)
Sushiswap has about 75 K USD in liquidity
![USDT liquidity sushiswap](https://user-images.githubusercontent.com/101358184/217576656-435ec1ea-747e-4a95-8fae-a87054d89b18.PNG)

These come from coinmarketcap, but I belive they are the same than the ones in Sushi swap.

![USDT-USDC liquidity sushiswap](https://user-images.githubusercontent.com/101358184/217576663-06c9407b-44df-4994-9a14-9fc18e10cc8d.PNG)
![USDT-wxdai liquidity sushiswap](https://user-images.githubusercontent.com/101358184/217576666-4549ddd8-4cb3-4b6a-88b0-c9c62f0c9569.PNG)

I made a 1 K swap on Monday XDAI to USDT, no slippage (or minimal). But I'm testing the same in sushiswap and there is some 3% slippage right now. It's hard for me to make more sense out of this numbers. But maybe Griff can help with this with all the research made.

**Comment by brichis** [comment]
Hey @Cotabe @laurenluz I'm watching my spreadsheet and I'm seeing that I only considered HoneySwap and that's why I didn't considered enough liquidity, I can do a second review :) Is there another source that I should check? I checked Coingecko and Honeyswap, I can check too Sushi and Coinmarket Cap. Thanks for the feedback Cotabe! 
https://docs.google.com/spreadsheets/d/1Wpsdx9Kii1vWlP6qNlP_pHpSBQvQQVtbLfM6MOUX74o/edit#gid=267197215

**Comment by Cotabe** [comment]
It's hard to see... or at least I don't consider myself an expert at it by any means. But what you can do is simulate that you are going to make a swap in [transferto.xyz](https://transferto.xyz/swap), it will tell you what's the best route, aka, which DEX has more liquidity. It seems 1inche has more liquidity right now

**Comment by Cotabe** [comment]
And then go in there and try to find more info. In some DEXes is easier in other it's trickier. But it seems its actually coming out of curve.

![USDT liquidity 1inch](https://user-images.githubusercontent.com/101358184/217617055-8612b53c-98b9-4897-a0e2-ea8bb6820de3.PNG)

and then on Curve I just found the liquidity on the pools, search for USDT here https://curve.fi/#/gnosis/pools

Then you can go on this one and see the is 4M USDT liquidity paired with a similar amount of USDC and XDAI https://curve.fi/#/gnosis/pools/3pool/deposit

**Comment by brichis** [comment]
Thanks @laurenluz and @Cotabe, I'll ask to Griff about next steps :)

**Comment by GriffGreen** [comment]
The best way to check is to try trading them on cowswap... if the slippage is bigger than 3% for $10000 trade... we should exclude it...

I would test CRV & xMoon

**Comment by brichis** [comment]
CowSwap
![Screenshot 2023-02-13 at 10.22.21.png](https://images.zenhubusercontent.com/635c6dd0ed86045e2c4cd152/dd59b302-3a1f-4d3d-b9f4-0e208489f4c5)

Curve
![Screenshot 2023-02-13 at 10.20.04.png](https://images.zenhubusercontent.com/635c6dd0ed86045e2c4cd152/363e08a3-1380-4f91-8a82-86437d21e31c)

HoneySwap
![Screenshot 2023-02-13 at 10.25.52.png](https://images.zenhubusercontent.com/635c6dd0ed86045e2c4cd152/a5874d7b-560a-4042-8ed2-4a1b562f1efc)

**Comment by brichis** [comment]
![Screenshot 2023-02-13 at 10.20.04.png](https://images.zenhubusercontent.com/635c6dd0ed86045e2c4cd152/782dc75e-81b4-47e8-b1c4-fcecfdae7704)![Screenshot 2023-02-13 at 10.22.21.png](https://images.zenhubusercontent.com/635c6dd0ed86045e2c4cd152/689ff8d0-0f8f-4f80-a89a-3f60c1a9407f)![Screenshot 2023-02-13 at 10.25.52.png](https://images.zenhubusercontent.com/635c6dd0ed86045e2c4cd152/eb758b68-9e28-4af3-a29b-cfffc8b1f1ec)

**Comment by Cotabe** [comment]
I think, it passes. Honeyswap is just not seing the liquidity in curve

**Comment by divine-comedian** [comment]
![image](https://user-images.githubusercontent.com/67759413/219101378-34169715-8c2a-47e0-b451-ffa1ab71d4c7.png)
 looks good to me - +$2M liquidity on curve!

**Comment by MoeNick** [comment]
@mohammadranjbarz @CarlosQ96 can we add a delete button only for the admin role in the token page?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz @CarlosQ96 can we add a delete button only for the admin role in the token page?

Yeah it's an easy job

**Comment by laurenluz** [comment]
This can now me done in admin bro - @NikolaCreatrix or @WhyldWanderer - can you delete these tokens?

**Comment by NikolaCreatrix** [comment]
@laurenluz I'd gladly do that cause I just figured out how and where, but I don't have the right role for that (my access is limited so I don't do any harm :P), and I think that would be on @WhyldWanderer to assess if I am trustworthy enough to get it, so then @CarlosQ96 could do it for me...and tadaaaa, I can delete those tokens.

**Comment by WhyldWanderer** [comment]
@laurenluz - I already deleted the ones from the original post.

Are there more that need to be deleted? Which ones?

**Comment by MoeNick** [comment]
who's gonna QA it?

**Comment by MoeNick** [comment]
@brichis can you pls check and confirm

**Comment by brichis** [comment]
Sure! @MoeNick

**Comment by brichis** [comment]
Hi @MoeNick!
![Screenshot 2023-02-27 at 12.21.20.png](https://images.zenhubusercontent.com/635c6dd0ed86045e2c4cd152/5ed8961b-af70-421a-9b66-a9cc3d6f037b) 

The tokens are not eligible for GIVbacks but we still accept donations with LUNA or UST for example

**Comment by MoeNick** [comment]
@WhyldWanderer @NikolaCreatrix I guess it needs your attention again. :)

**Comment by divine-comedian** [comment]
DONE!

**Comment by MoeNick** [comment]
@maryjaf please check all tokens

**Comment by maryjaf** [comment]
Giveback is not eligible for all tokens listed in the description
Only for these two tokens:
UST(mainnet)
xMOON(xDAI)
they are not displayed in the list of tokens

**Comment by VirtualWizzard** [comment]
wow its all false, btw what are you doin with coinbase wrapped luna ?

![image](https://github.com/user-attachments/assets/a60dae1e-f29d-4420-8d66-5dcae451512e)
