### ISSUE TITLE
Wallet menu

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#2037]
@mosaeedi commented on [Sun Jan 15 2023](https://github.com/Giveth/GIVeconomy/issues/846)

# Responsive guides

### Light
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17996%3A234046&t=huSwZsLxPMwnLBB2-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17996%3A234046&t=huSwZsLxPMwnLBB2-4)

### Dark
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18047%3A244943&t=huSwZsLxPMwnLBB2-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18047%3A244943&t=huSwZsLxPMwnLBB2-4)

---

### Light
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18047%3A245570&t=huSwZsLxPMwnLBB2-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18047%3A245570&t=huSwZsLxPMwnLBB2-4)

### Dark
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18047%3A245595&t=huSwZsLxPMwnLBB2-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18047%3A245595&t=huSwZsLxPMwnLBB2-4)

**Comment by maryjaf** [comment]
On which environment are these changes? @MohammadPCh

**Comment by maryjaf** [comment]
I tested on https://giveth-homepage.vercel.app/ and based on the figma the wallet menu is ok
