### ISSUE TITLE
Rewards Menu

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#2038]
@mosaeedi commented on [Sun Jan 15 2023](https://github.com/Giveth/GIVeconomy/issues/847)

### Light
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17996%3A234134&t=huSwZsLxPMwnLBB2-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17996%3A234134&t=huSwZsLxPMwnLBB2-4)

### Dark
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18047%3A245034&t=huSwZsLxPMwnLBB2-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18047%3A245034&t=huSwZsLxPMwnLBB2-4)

---

### Light
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18047%3A246284&t=huSwZsLxPMwnLBB2-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18047%3A246284&t=huSwZsLxPMwnLBB2-4)

### Dark
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18047%3A246321&t=huSwZsLxPMwnLBB2-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18047%3A246321&t=huSwZsLxPMwnLBB2-4)

**Comment by maryjaf** [comment]
I checked on https://giveth-homepage.vercel.app/ but i didn't see any change based on this figma
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17996%3A234134
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/111529185/215353827-0002478e-16f5-48ec-ac4c-b2cc77a87f67.png">

**Comment by MoeNick** [comment]
@MohammadPCh fyi

**Comment by MohammadPCh** [comment]
@maryjaf please check it again.

**Comment by maryjaf** [comment]
Thanks @MohammadPCh Plz check these items
1-
Figma: GIVSTREAM FLOWRATE
Homapage branch:FLOWRATE
and capital letters are used in the rest of the items in Figma
<img width="310" alt="image" src="https://user-images.githubusercontent.com/111529185/218943607-b8d93ab1-b063-4a64-a23e-4a42af700763.png">
<img width="274" alt="image" src="https://user-images.githubusercontent.com/111529185/218943910-67392f90-87ac-48ed-906f-cbc477ca497e.png">
2-
Should we be redirected to a specific page by selecting the Flowrate menu?
This happens for the rest of the menus, but not for Flowrate
3-
By clicking on the question mark, the corresponding window is displayed with a delay and it seems that there is a problem

**Comment by MohammadPCh** [comment]
Thanks @maryjaf please chek them again.

**Comment by maryjaf** [comment]
> Thanks @maryjaf please chek them again.

Thank @MohammadPCh , these problems have been solved
