### ISSUE TITLE
Notifications Menu

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#2039]
@mosaeedi commented on [Sun Jan 15 2023](https://github.com/Giveth/GIVeconomy/issues/848)

### Light
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17997%3A234222&t=huSwZsLxPMwnLBB2-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17997%3A234222&t=huSwZsLxPMwnLBB2-4)

### Dark
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18047%3A245289&t=huSwZsLxPMwnLBB2-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18047%3A245289&t=huSwZsLxPMwnLBB2-4)

---

### Light
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18047%3A247230&t=huSwZsLxPMwnLBB2-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18047%3A247230&t=huSwZsLxPMwnLBB2-4)

### Dark
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18047%3A247285&t=huSwZsLxPMwnLBB2-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18047%3A247285&t=huSwZsLxPMwnLBB2-4)

**Comment by MohammadPCh** [comment]
This is blocked by merging the notification center branch to the develop branch.

**Comment by maryjaf** [comment]
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/1a387711-f9ff-4130-9fe9-ff51a1e0843c)
@MohammadPCh

**Comment by MohammadPCh** [comment]
@maryjaf Thanks, could you please check it again?

**Comment by maryjaf** [comment]
> @maryjaf Thanks, could you please check it again?

Thanks @MohammadPCh It is ok now
