### ISSUE TITLE
Supported Project Activity

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#2040]
New section! - We should have a new category of notifications pertaining to project activity for projects that the user does not own. 
 "Supported Project Activity" "Notifications for anyone who likes, donates to, or boosts projects."

@MoeNick commented on [Mon Jan 16 2023](https://github.com/Giveth/notification-center/issues/30)

---

@MoeNick commented on [Mon Jan 16 2023](https://github.com/Giveth/notification-center/issues/30#issuecomment-1384063326)

Notifications for projects you liked, donated to, or boosted by you. @laurenluz
 I think it could be the copy

**Comment by laurenluz** [comment]
@MoeNick are you saying that should be the copy for the subtext?

I prefer:

Title: Supported Project Activity
Subtext: Notifications related to projects you liked, donated to, or boosted.

**Comment by MoeNick** [comment]
> @MoeNick are you saying that should be the copy for the subtext?
> 
> I prefer:
> 
> Title: Supported Project Activity Subtext: Notifications related to projects you liked, donated to, or boosted.

@mosaeedi pls have this copy in Figma

**Comment by MoeNick** [comment]
Under this category, shall we have status and updates? I think both of them make sense, and can you please help us with a copy of these 2 items? 
@laurenluz

**Comment by MoeNick** [comment]
"Supported project updated" "Notify me when a project I liked, boosted or donated to has an update.
[image](https://user-images.githubusercontent.com/75490971/211388251-388a01da-ca38-4b92-9d3a-973868f4b093.png)

**Comment by mohammadranjbarz** [comment]
> "Supported project updated" "Notify me when a project I liked, boosted or donated to has an update. ![image](https://user-images.githubusercontent.com/80677512/212695268-f4074623-f7fa-467c-93c9-1a6837dfa748.png)

And I think in frontend we should show this:

`{Project name} that you are supporting before posted an update.`
@MoeNick  Am I right?

**Comment by MoeNick** [comment]
New Section:
Title: Supported Project Activity
Subtext: Notifications related to projects you liked, donated to, or boosted.

Related Events:

"Project updated"
"Notify me when a project I supported has been edited, or an update has been published."

"Project status"
"Notify me when a project I supported has been listed, unlisted, canceled, activated, or deactivated."

Verification
Notify me when a project I supported get verified or unverified.

I will update the notification format also

**Comment by MoeNick** [comment]
I think @alireza-sharifpour got blocked by @mohammadranjbarz by filtering query.

**Comment by mohammadranjbarz** [comment]
> I think @alireza-sharifpour got blocked by @mohammadranjbarz by filtering query.

@alireza-sharifpour  @MohammadPCh 
It's like https://github.com/Giveth/notification-center/issues/37#issuecomment-1420769595

**Comment by RamRamez** [comment]
I added `supportedProjects` category to notification center tab and to notification settings in PR #2147.

This PR can't be tested because it needs unread count for the `supportedProjects` group.
@CarlosQ96 is working on it.
cc @MoeNick @mohammadranjbarz 

`https://staging.notification.giveth.io/v1/notifications/countUnread/[address]`

![image](https://user-images.githubusercontent.com/73441857/217859064-80fce62f-8654-4032-871d-3f902d8af0b4.png)

**Comment by MoeNick** [comment]
Thanks @RamRamez and sorry I missed that @CarlosQ96
