### ISSUE TITLE
Giveth TRACE deprecation - we should adjust copy on Giveth.io in FAQ & history

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2045]
The copy on our dApp should be adjusted to refect the fact that Giveth TRACE has been deprecated. We can still mention it as part of our history, but it should be past-tense (like Giveth TRACE was built for traceability, and since has been deprecated because of the merge & rinkeby depreaction...)

This issue first requires someone from comms to go through the dApp copy & find what needs to be changed, and then make suggested changes (that are then reviewed).
Main things to look at are:
- FAQ
- About
- History

@c0ric0ri - this might be a good issue for you, wdyt?

Reference #1877

**Comment by laurenluz** [comment]
@danelsuga - can you take this on?

**Comment by danelsuga** [comment]
Is the Trace button supposed to still be there? Nothing loads on the page (errors all around), but it still exists. Feels confusing both on the level of the presence of the button on the homepage and on the Trace page itself.


FAQ's  https://giveth.io/faq

What is a Traceable project?
**CHANGE TO:** 
What was a Giveth “Traceable” project?

Giveth TRACE was the original fundraising application of Giveth that was sunsetted in Q3 2022 at the time of the ETH Merge and Rinkeby network deprecation. Its foundation was traceability and hence offered Verified projects on [Giveth.io](https://giveth.io/) to choose to also become a [Campaign](https://docs.giveth.io/dapps/entitiesAndRoles/#campaigns) on [Giveth TRACE](https://trace.giveth.io/), thus becoming a Traceable Project. It enabled project creators to manage their donations transparently using [Traces](https://docs.giveth.io/dapps/entitiesAndRoles/#traces). One
feature of Traces was specifying how a project used their donations to achieve the goals of the overarching Campaigns. Upgrading Giveth.io projects to Campaigns enabled project owners to specify parts of their project requiring funding as different types of [Traces](https://docs.giveth.io/dapps/entitiesAndRoles/#traces). Donors benefited from being able to choose to fund either specific Traces or the overarching Campaign, and were thereby able to trace the flow of their donations. Traceable projects formerly appeared on both [Giveth TRACE](https://trace.giveth.io/) (as a Campaign) and [Giveth.io](https://giveth.io/), creating double exposure. To learn more about the history Giveth TRACE and  how projects were made traceable, visit our [documentation](https://docs.giveth.io/dapps/makeTraceableProject).

**Comment by danelsuga** [comment]
While doing this issue, I found some editing needing done on the site, so I created the issue [Text edits on dApp, 2083](https://github.com/Giveth/giveth-dapps-v2/issues/2083).

**Comment by danelsuga** [comment]
@laurenluz

**Comment by laurenluz** [comment]
We're deleting the label "traceable" from projects - it shouldn't appear on the dapp anymore. Therefore, I think that this question kind of becomes irrelevant and should be removed. Who is frequently going to ask "what is/was a traceable project" if it doesn't say "traceable" anywhere - you know?

It would nice to add a question to the FAQ like "What was Giveth TRACE?" or "What happened to Giveth TRACE?" instea. You could use part of the copy your wrote here above for that. 

What do youi think @danelsuga ?

**Comment by danelsuga** [comment]
Yes, great idea @laurenluz

**Comment by laurenluz** [comment]
Can you rewrite something @danelsuga ? then we can pass to Ramin to implement?

**Comment by danelsuga** [comment]
Will do!

**Comment by danelsuga** [comment]
Could you have a quick read of this @laurenluz ? Thanks.

https://docs.google.com/document/d/1ULeLZIF4aK9CR7VIV6fRw6pdlGkj0K5SJvNKCJqsryQ/edit?usp=sharing

**Comment by laurenluz** [comment]
Hey @danelsuga - I think it's trying to preseve too much of the old copy, and it would be better to write something new explaining that TRACE was the original Giveht platform, that it had traceable donations, and that it was deprecated because it depended on rinkeby.

I would just summarize the key points of this blog post, basically: https://medium.com/giveth/giveth-trace-is-live-e91b0be1e1f6

Make it more high level. It's not useful to explain, for example... that at some point in the past verified projects could choose to upgrade to be traceable, etc.

**Comment by MoeNick** [comment]
shall we start this one? Im a little bit lost sorry!

**Comment by laurenluz** [comment]
@MoeNick - let's just keep it simple...

Remove the question "What is a traceable project?" in FAQs and replace with the following: 

What Was Giveth TRACE?

Giveth TRACE was Giveth's original donation application, first created in 2016 and sunsetted in Q3 2022 at the time of the ETH Merge and Rinkeby network deprecation. As is still the case with Giveth.io, Giveth TRACE’s foundation was the concept of traceability. Giveth TRACE also meant that verified projects on [Giveth.io](https://giveth.io/) could choose to become a [Campaign](https://docs.giveth.io/dapps/entitiesAndRoles/#campaigns) on [Giveth TRACE](https://trace.giveth.io/) and manage their donations transparently using [Traces](https://docs.giveth.io/dapps/entitiesAndRoles/#traces).

**Comment by MohammadPCh** [comment]
@alireza-sharifpour can you take it?
