### ISSUE TITLE
Project email verification bug

### ISSUE THREAD

**Issue by clara-zi** [Giveth/giveth-dapps-v2#2046]
Issue reported through 'support' channel.

"I've submitted a project verification bug several times but have not heard back from you and still experience the bug. Whenever I try to verify my email (first step) it gives me error. Project = Tuqtuquilal Center for Regenerative Living"

contact: tyler@omniharmonic.ventures

**Comment by MoeNick** [comment]
Thanks for reporting @clara-zi  and sorry for that, this was an OPS problem and seems to be fixed now.

**Comment by maryjaf** [comment]
I check this on stg and production and the problem has been resolved
