### ISSUE TITLE
Project update

### ISSUE THREAD

**Issue by mosaeedi** [Giveth/giveth-dapps-v2#2052]
![Screenshot 2023-01-20 at 4.16.38 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/9cd124cb-8d95-4c76-ad93-5a1fa290c2ca)

### ( >1280 )
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18635%3A256221&t=4L2vT9pUqo6psnBj-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18635%3A256221&t=4L2vT9pUqo6psnBj-4)

### ( >1024 - <1279 )
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18635%3A256762&t=4L2vT9pUqo6psnBj-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18635%3A256762&t=4L2vT9pUqo6psnBj-4)

### ( >768 - <1024 )
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18636%3A257203&t=4L2vT9pUqo6psnBj-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18636%3A257203&t=4L2vT9pUqo6psnBj-4)

### ( Mobile )
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18636%3A257644&t=4L2vT9pUqo6psnBj-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18636%3A257644&t=4L2vT9pUqo6psnBj-4)

**Comment by laurenluz** [comment]
Just FYI friends - after talking with @mosaeedi we decided that this block should be on the projects page and not the homepage :)

updated homepage design is [here](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19416%3A246933&t=gWHIidB6WJhpMUTc-4)

**Comment by MohammadPCh** [comment]
@laurenluz ok :)
so do we have a new design for the projects page?

**Comment by MoeNick** [comment]
@mosaeedi please update the projects page design.
