### ISSUE TITLE
Latest updates

### ISSUE THREAD

**Issue by mosaeedi** [Giveth/giveth-dapps-v2#2053]
![Screenshot 2023-01-20 at 4.14.31 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/f5e2d27a-e80e-4cf5-89bd-04d067e238fc)

### ( >1280 )
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18635%3A256222&t=4L2vT9pUqo6psnBj-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18635%3A256222&t=4L2vT9pUqo6psnBj-4)

### (>1024 - < 1279)
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18636%3A257149&t=4L2vT9pUqo6psnBj-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18636%3A257149&t=4L2vT9pUqo6psnBj-4)

### ( >768 - <1024 )
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18636%3A257502&t=4L2vT9pUqo6psnBj-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18636%3A257502&t=4L2vT9pUqo6psnBj-4)

### ( Mobile )
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18636%3A258030&t=4L2vT9pUqo6psnBj-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18636%3A258030&t=4L2vT9pUqo6psnBj-4)

**Comment by maryjaf** [comment]
I didn't see latest updates section on home page @MohammadPCh 
https://giveth-homepage.vercel.app/

**Comment by maryjaf** [comment]
According to the latest update, this part does not need to be displayed

**Comment by maryjaf** [comment]
Now we show the latest update of each project
That is, if a project has, for example, two updates in one day
In the list of latest updates, the second update replaces the first, is this ok? @MoeNick
