### ISSUE TITLE
New menu: Search screen

### ISSUE THREAD

**Issue by mosaeedi** [Giveth/giveth-dapps-v2#2059]
# Note
By clicking on **Search project** on the header, the search screen will pop over the whole screen.

# Responsive guides

### Light theme
**Desktop**
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18696%3A260239&t=88DCvbOSZF2tOiMF-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18696%3A260239&t=88DCvbOSZF2tOiMF-4)

**Mobile**
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18696%3A260297&t=88DCvbOSZF2tOiMF-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18696%3A260297&t=88DCvbOSZF2tOiMF-4)

### Dark theme
**Desktop**
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18696%3A260241&t=88DCvbOSZF2tOiMF-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18696%3A260241&t=88DCvbOSZF2tOiMF-4)
**Mobile**
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18696%3A260323&t=88DCvbOSZF2tOiMF-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18696%3A260323&t=88DCvbOSZF2tOiMF-4)

---

### Light theme
**Desktop**
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18696%3A261605&t=88DCvbOSZF2tOiMF-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18696%3A261605&t=88DCvbOSZF2tOiMF-4)

**Mobile**
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18696%3A261717&t=88DCvbOSZF2tOiMF-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18696%3A261717&t=88DCvbOSZF2tOiMF-4)

### Dark theme
**Desktop**
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18696%3A261635&t=88DCvbOSZF2tOiMF-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18696%3A261635&t=88DCvbOSZF2tOiMF-4)

**Mobile**
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18696%3A261738&t=88DCvbOSZF2tOiMF-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18696%3A261738&t=88DCvbOSZF2tOiMF-4)

**Comment by MohammadPCh** [comment]
@MoeNick I need a query to fetch these data from the backend:
![image](https://user-images.githubusercontent.com/17097576/214503748-9ea49d9a-0c57-4515-9c03-72b99d912752.png)

**Comment by MohammadPCh** [comment]
@MoeNick Also I need to know, do we want to have load more functionality here?
we don't have any design for showing results.

**Comment by MoeNick** [comment]
@mosaeedi it needs your attention regarding to the dev meeting

**Comment by mosaeedi** [comment]
When the user searches, we should show the result on the same project search screen and continue the flow there.
Is that clear? @MohammadPCh

**Comment by MohammadPCh** [comment]
Yes :)
Thanks @mosaeedi

**Comment by MoeNick** [comment]
> @MoeNick I need a query to fetch these data from the backend:
> 
> ![image](https://user-images.githubusercontent.com/17097576/214503748-9ea49d9a-0c57-4515-9c03-72b99d912752.png)
> 
> 

I think for this we have related query? Can you help us @mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
> 

No we dont have it, BTW what is featured projects or popular categories?
Are they something that admins set it or should we define an algorithm to achieve them?

**Comment by mohammadranjbarz** [comment]
> > @MoeNick I need a query to fetch these data from the backend:
> > ![image](https://user-images.githubusercontent.com/17097576/214503748-9ea49d9a-0c57-4515-9c03-72b99d912752.png)
> 
> I think for this we have related query? Can you help us @mohammadranjbarz

@MoeNick  No we dont have it, BTW what is featured projects or popular categories?
Are they something that admins set it or should we define an algorithm to achieve them?

**Comment by MoeNick** [comment]
Featured Projects:
getFeatuedProjects: List of projects by a specific campaign. 
in this case the specific campaign should be the default campaign or the latest campaign. 
does it make sense? @MohammadPCh @mohammadranjbarz

**Comment by MohammadPCh** [comment]
@MoeNick @mohammadranjbarz  could you please provide some more info on the mainCategories query to show if is it popular or not?

**Comment by MoeNick** [comment]
@mosaeedi believe that popular categories can set manually on front-end

**Comment by MohammadPCh** [comment]
@MoeNick @c0ric0ri I appreciate you if you select some categories to show in this modal.

**Comment by maryjaf** [comment]
plz check these @MohammadPCh 
1-The items related to the "Featured projects" are displayed with a slight delay
2-By selecting any of the  "Featured projects"&"Popular categories" items , 404 error will be displayed

**Comment by MohammadPCh** [comment]
@maryjaf Thanks,
Yes, we show Featured projects with delay, because we should get them from the backend. and we don't have a loading design for the column. and the second problem is fixed could you please check it again?

**Comment by maryjaf** [comment]
> @maryjaf Thanks, Yes, we show Featured projects with delay, because we should get them from the backend. and we don't have a loading design for the column. and the second problem is fixed could you please check it again?

Thanks @MohammadPCh It has been fixed

**Comment by mosaeedi** [comment]
A last-minute hotfix is needed!
Can we make it possible to close the search modal whenever a user clicks on the gray area? (everything expect the search input box and the links)

**Comment by mosaeedi** [comment]
Also the close button on this modal should be like this 👇

![Screenshot 2023-02-26 at 4.12.21 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/a7bc7473-3806-4786-b9bc-33878583c0bd)
