### ISSUE TITLE
"Well done!" profile completion page grammar fixes

### ISSUE THREAD

**Issue by danelsuga** [Giveth/giveth-dapps-v2#206]
![createdonate.png](https://images.zenhubusercontent.com/6066d509782b4d63df5cd761/7bbd2e3a-7870-4dbc-aa22-e5e5a62b95fa)

Should read: "Now your profile is complete." (Add verb.) 

For consistency, right box should should: "Take a look and donate to projects." (Add period.)

And below should read: "or go to the homepage to start exploring." (Add "the" and add period.)

**Comment by NikolaCreatrix** [comment]
Tested on chrome - resolved.
