### ISSUE TITLE
Integrate top up service with Mt Pelerin to allow xDAI purchases directly

### ISSUE THREAD

**Issue by mateodaza** [Giveth/giveth-dapps-v2#2067]
Following our Fiat exploration, we wanna offer a top up service for our users, to buy xDAI directly to their wallets

Inspired by Honeyswap, we should add something like this to our flow

![image](https://user-images.githubusercontent.com/18689480/214128308-2fd679f9-1c60-4b74-bf25-3f483c33a218.png)

**Comment by MoeNick** [comment]
@Tosinolawale do we have progress on this issue?

**Comment by Tosinolawale** [comment]
Yes working on it. I will have design ready tomorrow based off on feedbacks from @mateodaza

**Comment by MoeNick** [comment]
@Tosinolawale @mateodaza would you please update the design?

**Comment by mateodaza** [comment]
Here's the design by @Tosinolawale https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19763%3A249898&t=MwIH41UO9SBQqfQl-1

**Comment by MoeNick** [comment]
@mosaeedi please take a look

**Comment by Tosinolawale** [comment]
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19913%3A257522&t=DbcPgrwk4MgSkW2A-1
Use sees the first information on purchasing xDai with Mt Pellerin on the project donation modal

**Comment by Tosinolawale** [comment]
When user clicks on Buy xDAI, they are taken through this flow 

https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19913%3A258288&t=DbcPgrwk4MgSkW2A-1

**Comment by Tosinolawale** [comment]
In situations where a user wants to go through the flow, understand how it works without necessarily buying or test buying any xDai, the user clicks on the "how to buy link" on the donation modal and are taken through this flow 

https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19768%3A249554&t=DbcPgrwk4MgSkW2A-1
![How to buy](https://user-images.githubusercontent.com/35389241/220135731-0e9e5e0e-e7d8-4aab-91e8-6e1011f0394b.png)

**Comment by MoeNick** [comment]
hey 
@Tosinolawale @mosaeedi is the design final?

**Comment by Tosinolawale** [comment]
> hey @Tosinolawale @mosaeedi is the design final?

Yes
