### ISSUE TITLE
Emergency tag

### ISSUE THREAD

**Issue by brichis** [Giveth/giveth-dapps-v2#2072]
GM! 
@GriffGreen asked me to create this issue.

He said we need a tag for emergencies for example, in case of:
- A tornado hits a town 
- Something goes on fire
- Hurricanes 
- Earthquakes
Etc.

Could be not called emergencies, maybe immediate need, act of God, sudden emergency, or any other name.

Here is an example of a project that could use this tag: https://giveth.io/project/android-jones-studio-fire

**Comment by brichis** [comment]
@laurenluz @MoeNick I created this issue, can you confirm me if is the right format and place? Thank you

**Comment by MoeNick** [comment]
Hey @brichis we can define tags per repo, if it's not related to dev stuff, I suggest creating this in planning / giveconomy repo. if it can be related to dev we have to do it in v2/ impact/

**Comment by brichis** [comment]
Hey @MoeNick I think is related to dev stuff, I mean a tag on Giveth.io like the "Traceable" tag, or you mean should have a process before on planning/GIVeconomy? Like a discussion?

Thank you for the explanation about repos, I'll copy that on my Trello to don't forget it :)

**Comment by MoeNick** [comment]
Aha I got it now 😄👍

**Comment by brichis** [comment]
Oh no haha thanks!

**Comment by MoeNick** [comment]
I now feel the accuracy of this requirement after Turkey's earthquake, @mosaeedi can we handle it by categories or tags like donation tags? do you have an idea?

**Comment by mosaeedi** [comment]
I'll handle this while working on the project's detailed page redesign!

**Comment by brichis** [comment]
Thank you @mosaeedi !
