### ISSUE TITLE
Formatting on projects

### ISSUE THREAD

**Issue by brichis** [Giveth/giveth-dapps-v2#2073]
@GriffGreen asked me to create this issue

**Describe the bug**
First, he created this project on Giveth: https://giveth.io/project/android-jones-studio-fire with one title picture and submited the project, after he modified the tittle picture and the formatting became one giant paragraph.

**To Reproduce**
1. Go to Giveth
2. Create a project with one title picture
3. Submit it
4. Change the title picture
5. Resubmit it
6. See the problem: The formatting lost all of the next lines and just became one giant paragraph.

**Expected behavior**
That the original format is respected

**Screenshots**
He didn't take any

**Comment by brichis** [comment]
@laurenluz @MoeNick This is the second issue he asked to me create :)

**Comment by RamRamez** [comment]
I talked with @brichis in DM and she sent me griff comments, but I still don't know what exactly is the problem and how the title picture should behave!

**Comment by laurenluz** [comment]
Hey @RamRamez 

He says that he created the project with the project description formatting w/ rich text.

And then later came back to change the project's banner picture... clicked "save"... and then the project description's formatting got all message up - removing all the formatting and having it show up just as a single block of text.

Make sense?

**Comment by MoeNick** [comment]
will fix in https://github.com/Giveth/giveth-dapps-v2/issues/2269
