### ISSUE TITLE
The header should load sooner

### ISSUE THREAD

**Issue by mosaeedi** [Giveth/giveth-dapps-v2#2077]
When someone opens the website, the header is almost the last thing that will load. and for some seconds it can make the user think there are some issues with the website.

I know that we have some complex elements on the header, which will impact the whole website's speed if we don't lazy load it.

I suggest instead of lazy loading the whole header, try to show the menu and the logo first and then lazy load the right side elements such as the card & rewards menu.
This way user can see the header and we won't show an empty space on the top!

**Comment by MoeNick** [comment]
shall I move it to unit test?
