### ISSUE TITLE
Project updates Rich text/formatting is so messed up on copy/paste

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2078]
When I try to copy/past text from a google doc into our updates field for projects, I run into several problems:
- everything with bullet formatting doesn't show up at all
- the text is big, and I can't adjust it via our "normal, small, big" font sizer
- the character limit gets extremely weird... on every copy & paste is shows a different character count #1714

I basically have to rewrite the whole thing for it to show up right, and this is really bad UX.

**Comment by MohammadPCh** [comment]
@laurenluz can you check it on staging? I did some improvements.
I think all problems have been solved.

**Comment by maryjaf** [comment]
Plz check this:
When I changed the font size too large or huge the font of numbering or bullet didn't change.
![image.png]
(https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/c693746f-6a7f-4464-89cf-9335ca7d42b3)

I checked the rest of the reported cases and they seem to be resolved

**Comment by laurenluz** [comment]
omg this is amaaaazing. I just tested on staging and didn't have any of the same issues as before - Thank you @MohammadPCh !!!!!!!!!!!
