### ISSUE TITLE
Delete tag "This project is not eligible for GIVbacks"

### ISSUE THREAD

**Issue by brichis** [Giveth/giveth-dapps-v2#2079]
This is the third issue that Griff asked me to create.

He said:
Probably we should remove the "This project is not eligible for GIVbacks" tag. It makes people feel like they're project isn't good and there are some projects that don't need to be verified or shouldn't be verified.
And like the tag that says not receiving GIVbacks makes the project look not good, like it's a bad project.
It should say like GIVback eligible or nothing at all and for that issue.
![image.png](https://images.zenhubusercontent.com/635c6dd0ed86045e2c4cd152/7823badf-4be5-43ea-bc31-a7d411d9f51a)

**Comment by brichis** [comment]
Hey @laurenluz @MoeNick I reopened this issue in the correct repo, thanks! 

Reference to the old one:
Giveth/GIVeconomy#851

**Comment by laurenluz** [comment]
yeah I agree - I think we should remove this box.

Any objection @WhyldWanderer ?

**Comment by MoeNick** [comment]
@RamRamez jan can you start this one?

**Comment by RamRamez** [comment]
I fixed this in PR #2131. FYI, I think you should reconsider other messages. This is the new flow:

	`if (user is Eligible) {
		message = "Your currently connected wallet address is associated with a Giveth project, therefore donations made from this address are not eligible for GIVbacks."
	} else if (token is NOT Eligible) {
		message = "This token is not eligible for GIVbacks. To create a request to add this token to our GIVbacks token list, please make a comment"
	} else if (token is Eligible & project is Eligible) {
		message = "This token is eligible for GIVbacks."
	} else {
		show no messages;
	}`

Do you confirm this?

**Comment by RamRamez** [comment]
And we don't show any messages to inform users that this project is eligible for GIVbacks. I suggest adding a message saying "This project is eligible for GIVbacks" just like the token.

**Comment by laurenluz** [comment]
yeah that's a good idea - add it to verified projects @RamRamez

**Comment by MoeNick** [comment]
@maryjaf pls confirm

**Comment by maryjaf** [comment]
Thanks @RamRamez 
I checked it on https://giveth-dapps-v2-git-2079deletetagthisprojectisn-ab2e74-givethio.vercel.app branch and it is ok 
Now for verified project this message shown:
This token is eligible for GIVbacks.
<img width="1311" alt="image" src="https://user-images.githubusercontent.com/111529185/220410006-949027c9-5c31-47d4-ae99-72e8666c83f5.png">
And Nothing is displayed for unverified projects
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/111529185/220410527-bb05b4ca-b93a-41c8-9381-9499b91e064e.png">

**Comment by brichis** [comment]
Thank you so much dev team! You're the best!
