### ISSUE TITLE
"Join" - punctuation consistency

### ISSUE THREAD

**Issue by danelsuga** [Giveth/giveth-dapps-v2#208]
![join.png](https://images.zenhubusercontent.com/6066d509782b4d63df5cd761/d63203b5-2f32-4959-9432-f956cf18be1a)

Should read: "Join our Community.
Building the Future of Giving."

OR SHOULD READ: "Join our Community
Building the Future of Giving"

There is a lot of inconsistency on the site as a whole regarding punctuation that should be remedied at some point. In this case, there are two complete sentences back-to-back where one has a period and one does not. They should be the same, either with or without. I personally suggest with, so that there is no confusion when updating or writing new pages: use proper grammar such that all real complete sentences have periods.

**Comment by NikolaCreatrix** [comment]
Reviewed on chrome - resolved!
