### ISSUE TITLE
Delete "check out" from the link description

### ISSUE THREAD

**Issue by brichis** [Giveth/giveth-dapps-v2#2080]
Another issue Griff asked me to create :D

![image.png](https://images.zenhubusercontent.com/635c6dd0ed86045e2c4cd152/b1ff3f2f-189d-4590-bae6-8dcaa00d2e0d)

**Comment by brichis** [comment]
@laurenluz @RamRamez @MoeNick This is the new issue, sorry for the confusion! 

Reference of the old one: Giveth/GIVeconomy#852

**Comment by laurenluz** [comment]
@RamRamez - can you take this one? it's related I think to the metadata of the project, and I remember you working on this stuff before.

We just want it to say giveth.io w/ the previed image & the title of the project. No "Check out" text.

**Comment by RamRamez** [comment]
> @RamRamez - can you take this one? it's related I think to the metadata of the project, and I remember you working on this stuff before.
> 
> We just want it to say giveth.io w/ the previed image & the title of the project. No "Check out" text.

Yes, I fixed it.

**Comment by GriffGreen** [comment]
Thx Ramin!
