### ISSUE TITLE
Text edits on dApp

### ISSUE THREAD

**Issue by danelsuga** [Giveth/giveth-dapps-v2#2083]
While going over the site, I noticed the text needs some copy editing. Below is what I found.

**Comment by danelsuga** [comment]
What is Tor.us?

Tor.us is the non-crypto savvy way to sign in to, **REMOVE COMMA** and use Giveth.io. It is our wallet option alongside [Metamask ] **REMOVE EXTRA SPACE** (https://metamask.io/). For a more detailed answer, see [Tor.us documentation](https://docs.tor.us/).

What is the difference between Bitcoin and Ethereum?

**Comment by danelsuga** [comment]
What is Tor.us?

Tor.us is the non-crypto savvy way to sign in to, **REMOVE COMMA** and use Giveth.io. It is our wallet option alongside [Metamask ] **REMOVE EXTRA SPACE** (https://metamask.io/). For a more detailed answer, see [Tor.us documentation](https://docs.tor.us/).

What is the difference between Bitcoin and Ethereum?

Bitcoin is intended to function as INSERT “a” decentralized means of value transfer INSERT COMMA whereas Ethereum is a protocol that allows users to develop decentralized applications on top of a blockchain network. As prominent Ethereum developer Vlad Zamfir has confirmed on several occasions, Ethereum is “not money.” Ethereum’s native token, Ether (ETH) exists in order to facilitate the process of building and deploying distributed applications. Meanwhile, the Bitcoin currency exists on the Bitcoin blockchain to facilitate peer-to-peer (P2P) exchange of uncensorable, non-confiscatable money.

What is Giveth?

Giveth is a community focused on Building the Future of Giving using blockchain technology MAKE TWO WORDS. There are a lot of projects in the Giveth Galaxy CHANGE “Galaxy” to “universe (the GIViverse)” (lowercase) to distinguish from use of “Galaxy” to refer to other DAOs, but the core two projects are: [Giveth.io](https://giveth.io/) and the [GIVeconomy](https://giveth.io/giveconomy).
You can use Giveth to donate to projects or also propose projects that need funding, all using cryptocurrency and soon fiat currencies! We aim to foster a large network of organizations and to build a bright, transparent and decentralized Future of Giving.

How is Giveth funded?

Giveth has been adding value to Ethereum since 2016, funded solely by donations and a few grants programs FIX PARENTHETICAL to: (e.g., Panvala, Gitcoin) (i.e ([Panvala](https://panvala.com/), [Gitcoin](https://gitcoin.co/)). Our community has come this far without the help of any investors. You can support us by [donating to our project](https://giveth.io/donate/the-giveth-community-of-makers).

Is Giveth recognized as an official charity?

With the help of CAPITALIZE “i” and “f” (and include link: https://www.sdgimpactfund.org/)  SDG impact fund INSERT COMMA the Giveth DAO and community based organizational structure is represented as a non-profit 501c3 in the United States. We are a community-led project and will not derive any direct profit from the platform. We guarantee all funds will get recycled back into the LOWERCASE Community that is ensuring the Giveth LOWERCASE “p” Platform becomes adopted widely.

Is my donation tax deductible?

We do not support CHANGE support to help (“support” sounds like we do not approve) donors in obtaining tax deductions INSERT COMMA and if a donor receives GIVbacks for donating to a verified project, we can not guarantee that the donation is legally tax deductible.

Where can I see in detail how Giveth is spending their funds?

One of the core values of Giveth is transparency. We invite everyone to have a look at our finances. Funding, expenditures and payments relating to Giveth's LOWERCASE “t” Treasuries can be seen in many places, including:
[nrGIV](https://aragon.1hive.org/#/nrgiv/) for LOWERCASE “c” and “e” Contributor Expenses and GIVbacks
[GIVgarden](https://gardens.1hive.org/#/xdai/garden/0xb25f0ee2d26461e2b5b3d3ddafe197a0da677b98) for community initiatives and external funding requests
Giveth LOWERCASE “l” and “m” Liquidity Multisig on [Mainnet](https://gnosis-safe.io/app/eth:0xf924fF0f192f0c7c073161e0d62CE7635114e74f/balances) and [Gnosis Chain](https://gnosis-safe.io/app/gno:0xf924fF0f192f0c7c073161e0d62CE7635114e74f/balances) for LOWERCASE “l” Liquidity creation for $GIV
Giveth LOWERCASE “m” and “m” Main Multisig on [Mainnet](https://gnosis-safe.io/app/eth:0x4D9339dd97db55e3B9bCBE65dE39fF9c04d1C2cd/balances) and [Gnosis Chain](https://gnosis-safe.io/app/gno:0x4D9339dd97db55e3B9bCBE65dE39fF9c04d1C2cd/balances) for LOWERCASE “g” and “d” Grants and Donations to Giveth
Are there fees for creating a project?

Nope! Giveth will never RECOMMENDATION: change to “Giveth does not” charge any additional fees for creating projects on our platform. If you create a project on Giveth.io it creates an entry in our database that directly points to your chosen Ethereum wallet. You can do this as well with a brand new account that holds zero funds. There are minor fees when using the CAPITALIZE “e” ethereum network, and if you use other exchanges or services, there are likely associated fees. To learn more, read up on some of the [foundation mechanics of Ethereum](https://ethereum.org/en/eth/).

What percentage of the donations go directly to the project?

100% of funds raised on Giveth go directly to the project. Giveth does not charge fees to CHANGE TO “donors or project owners” givers or makers. There are minor fees when using the CAPITALIZE “e” ethereum network, and if you use other exchanges or services, there are likely associated fees. To learn more about fees and how Ethereum works, visit [their website](https://ethereum.org/en/eth/).

Can I donate on Giveth if I don’t have crypto?

Fiat integration (donate funds from your credit card or bank account) is coming soon! Stay tuned... Giveth has also partnered with [SDG Impact Fund](https://www.sdgimpactfund.org/) to make it possible for donors to contribute tax-deductible donations, in fiat or crypto, to altruistic projects on the blockchain. This is a major development in finance innovation to effectively care for the commons. We are very close to having fiat options integrated with the CHANGE SPELLING TO dApp Dapp. Until then, fiat donations will INSERT “be” accepted [here](https://www.sdgimpactfund.org/giveth-foundation). To learn more about the partnership between Giveth and the SDG Impact Fund, please refer to [this blog post](https://medium.com/giveth/giveth-2-0-next-level-community-philanthropy-f7e60d7e78cb).

I’m a donor. How do I know projects are getting my money?

Each project description page shows a list of all donations made to that project and by CHANGE TO “whom” who. Giveth.io does not collect any fees INSERT COMMA and your donation is sent directly to the project's provided wallet address. You can also find your donation on the blockchain by the link to the transaction on a block explorer CHANGE PARENTHETICAL TO (e.g., etherscan.io) (i.e [etherscan.io](https://etherscan.io/)) after you make a successful donation.

How do I know the project I contributed to was completed?

Each project has the opportunity to post updates as its status changes, and donors who contributed to that project will receive notifications when a project owner posts an update. Donors can log back on to Giveth to see photos, written updates, and sometimes videos of a given project. Updates are the responsibility of the project owner, CHANGE COMMA TO PERIOD Giveth has no direct control in facilitating these updates.

What types of projects are prohibited?

Projects that are found to exhibit unacceptable behaviour and/or violate our [covenant](https://docs.giveth.io/whatisgiveth/covenant/) and/or [Terms of Use](https://giveth.io/tos) are considered prohibited and will be cancelled immediately INSERT COMMA and an email will be CHANGE TO “sent” send to the project owner. Learn more in our [documentation article](https://docs.giveth.io/dapps/listedUnlisted/#cancelled-projects).

I love Giveth INSERT COMMA but right now I have no funds to donate, REPLACE COMMA WITH PERIOD how else can I contribute?


We are a very inclusive LOWERCASE “c” Community and would love for you to join and see how you can get involved. [Join us on any of our social channels](https://giveth.io/join) INSERT COMMA and come talk to us!

Why CHANGE TO “did Giveth launch” is Giveth launching a token?

Giveth’s mission is to reward & empower those who give -- to projects, to society & to the world. The GIV token fuels and drives the GIVeconomy INSERT COMMA and some has been already distributed to those who have contributed to making Giveth what it is today. Anyone with an Ethereum wallet can get GIV via our [GIVbacks program](https://docs.giveth.io/giveconomy/givbacks/) by donating to verified projects. GIV is a governance token that allows our community to actively participate in shaping the future of Giveth in a decentralized way.

What network is the GIV token on?

GIV was deployed on Ethereum Mainnet and is used most heavily on Gnosis Chain (xDai). However, the GIViverse is multi-chained INSERT COMMA and GIV will likely be bridged/transferred to other chains and LOWERCASE “l” Layer 2 networks.

What can I do with GIV?

With GIV, you can LOWERCASE “g”, “d”, “f” and “e” Govern, Donate, Farm & Earn! Explore the GIVeconomy [here](https://giveth.io/giveconomy).

How can I get (more) GIV?


You can get GIV by interacting with the GIVeconomy and Giveth in several ways:

LOWERCASE EVERY “b”
By [donating](https://giveth.io/projects) to verified projects and getting [GIVbacks](https://docs.giveth.io/giveconomy/givbacks/).
By providing liquidity and staking tokens in the [GIVfarm](https://giveth.io/givfarm).
By wrapping GIV and voting in the [GIVgarden](https://giveth.io/givgarden).
By [becoming a contributor](https://giveth.io/join).

Recipients of the GIVdrop include members of the Giveth Trusted Seed - our community of crypto philanthropists INSERT DASH, Giveth users & builders, CHANGE TO “blockchain-for-good” (Blockchain4Good is a for-profit collective) Blockchain4Good DAO members, and other ecosystem partners. Check your [GIVdrop](https://giveth.io/giveconomy) INSERT COMMA or learn more about eligibility in our [documentation](https://docs.giveth.io/giveconomy/givdrop/).

How do I claim my GIVdrop?

You can check your GIVdrop and claim your tokens [here](https://giveth.io/giveconomy) INSERT COMMA or read our [tutorial](https://docs.giveth.io/giveconomy/givdrop/#claiming-your-givdrop) on how to claim!

Why don’t I have a GIVdrop?

The GIVdrop CHANGE TO “was sent” has been sent to our community of crypto philanthropists, Giveth users & builders, CHANGE TO “blockchain for good” Blockchain4Good DAO members, and other ecosystem partners. We have made every effort to include all valid addresses in this GIVdrop, at our discretion. Not every person who has ever interacted with Giveth is eligible. If you did not receive GIV, that is because you were not eligible. We will not review past transactions or consider other addresses for inclusion. We appreciate your understanding.

I didn’t receive a GIVdrop. Can I get one now?

We have made every effort to include all valid addresses in this GIVdrop, at our discretion. Not every person who has ever interacted with Giveth is eligible. If you did not receive GIV, that is because you were not eligible. We will not review past transactions or consider other addresses for inclusion. We appreciate your understanding.

I RECOMMEND: REMOVE FROM Why don’t I have a GIVdrop? We will not review past transactions or consider other addresses for inclusion. We appreciate your understanding.

AND REMOVE FROM I didn’t receive a GIVdrop. Can I get one now? We have made every effort to include all valid addresses in this GIVdrop, at our discretion. Not every person who has ever interacted with Giveth is eligible. If you did not receive GIV, that is because you were not eligible. 

What is the GIVgarden?

CAPITALIZE “t” the [GIVgarden](https://giveth.io/givgarden) is the Giveth LOWERCASE “c” Community’s DAO governance platform, developed by [1Hive's Gardens team](https://1hive.gitbook.io/gardens/), where GIV token holders can influence the treasury, roadmap and mission of the Giveth ecosystem. To learn more, check out the [GIVgarden documentation](https://docs.giveth.io/giveconomy/givgarden/).

What is the GIVfarm?

CAPITALIZE “t” the [GIVfarm](https://giveth.io/givfarm) is the Giveth liquidity mining program that allows GIV holders to provide liquidity and stake tokens to earn GIV rewards. To learn more, check out the [GIVfarm documentation](https://docs.giveth.io/giveconomy/givfarm).

What is the GIVstream?

CAPITALIZE “t”  the [GIVstream](https://giveth.io/givstream) aligns community members with the long term success of Giveth and the GIVeconomy. With the GIVstream, anyone who adds value to the GIVeconomy gets GIV continuously for up to 5 years. The GIVeconomy starts out small INSERT COMMA but as more value is created, the GIViverse expands -- More GIV becomes liquid INSERT COMMA and more GIV spreads out to our community of stakeholders. To learn more, check out the [GIVstream documentation](https://docs.giveth.io/giveconomy/givstream).

Why is there a GIVstream?

The GIVstream nurtures the GIVeconomy at inception by having only 10% of the total supply of GIV liquid and transferable to start. As the GIVeconomy grows & stabilizes, more GIV become liquid and available for everyone. We want to empower those who support the Giveth ecosystem with steadily increasing governance rights, CHANGE COMMA TO PERIOD this includes participants who [donate to verified projects](https://giveth.io/projects), vote in the [GIVgarden](https://giveth.io/givgarden) or provide liquidity in the [GIVfarm](https://giveth.io/givfarm). Participants benefit from their GIVstream flowing as the GIVeconomy flourishes over time, therefore we ensure that Giveth is not just governed by people who buy tokens on the open market but by those who contribute in a more meaningful way.

How do I get a GIVstream?

RECOMMEND REMOVING xDAI references b/c it’s been long enough and in particular here it’s overwhelming. 

You can get (or increase) your GIVstream flow-rate on Gnosis Chain by donating (on Gnosis (xDai) or Mainnet) and getting [GIVbacks](https://giveth.io/givbacks), by wrapping GIV to use in the [GIVgarden](https://giveth.io/givgarden), or by staking in the [GIVfarm](https://giveth.io/givfarm) on Gnosis (xDai). You can get (or increase) your GIVstream flowrate on Ethereum Mainnet by providing Mainnet liquidity and staking GIV or LP tokens in the [GIVfarm](https://giveth.io/givfarm) on Mainnet.

Can I speed up my GIVstream?

You can increase your [GIVstream](https://giveth.io/givstream) flow-rate by participating in the GIVeconomy through [GIVbacks](https://giveth.io/givbacks) REMOVE SPACE, the [GIVgarden](https://giveth.io/givgarden), or the [GIVfarm](https://giveth.io/givfarm). INSERT SPACE You cannot, however, accelerate your GIVstream to decrease the time remaining. The 'GIViverse expansion' time period ends on December 23, 2026 and is the same for the entire GIVeconomy.

—-

**Comment by danelsuga** [comment]
Reference
[Giveth TRACE deprecation copy editing on dApp](https://github.com/Giveth/giveth-dapps-v2/issues/2045)

**Comment by danelsuga** [comment]
[FAQ edits in this doc.](https://docs.google.com/document/d/13YBEegcQMRaaEsU1Ly1MjNG0-gKrE4jHQ_3R69p9Tos/edit?usp=sharing)

**Comment by danelsuga** [comment]
Who do I tag for this? @laurenluz @mateodaza @MoeNick @aminlatifi @RamRamez Thanks!

**Comment by danelsuga** [comment]
Can anyone help me on this? Thanks! @laurenluz @mateodaza @MoeNick @aminlatifi @RamRamez

**Comment by aminlatifi** [comment]
@RamRamez Can you do it, It's a frontend stuff

**Comment by RamRamez** [comment]
> @RamRamez Can you do it, It's a frontend stuff

Yes, sure

**Comment by laurenluz** [comment]
@danelsuga - thanks for these edits!

Just want to check with @RamRamez - is the way this is written useful to you? Or would it be easier if Suga just provided what that copy should be, instead of highlighting all the pieces that should be changed?

**Comment by RamRamez** [comment]
> @danelsuga - thanks for these edits!
> 
> Just want to check with @RamRamez - is the way this is written useful to you? Or would it be easier if Suga just provided what that copy should be, instead of highlighting all the pieces that should be changed?

The doc is great. @danelsuga @laurenluz Thanks for your hard work.

**Comment by maryjaf** [comment]
Subjects that are not in this document must either be deleted or remain unchanged compared to the previous version, such as what is blockchain, what is Ethereum @RamRamez

**Comment by RamRamez** [comment]
> Subjects that are not in this document must either be deleted or remain unchanged compared to the previous version, such as what is blockchain, what is Ethereum @RamRamez

They should remain unchanged.
