### ISSUE TITLE
Sending twice notifications for users with two wallets

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#2084]
> Now when I set a new broadcast notification my user has received two notification <img alt="image" width="1025" src="https://user-images.githubusercontent.com/111529185/214334288-d5a90c3b-9922-43eb-b64f-fc0add705506.png">

It's not related to this PR, we had it before and it's the reason:

<img width="1110" alt="Screen Shot 1401-11-05 at 10 08 46" src="https://user-images.githubusercontent.com/9850545/214497126-d25ddfe4-0447-4420-a8c0-a41a08cb876e.png">

We have two users with you wallet address, one of them is your using account another one is for admin panel, so you receive two notifications, it's a bug , you can create another issue about it but it's not related to this PR

_Originally posted by @mohammadranjbarz in https://github.com/Giveth/impact-graph/issues/572#issuecomment-1403162758_

**Comment by MoeNick** [comment]
@mohammadranjbarz 
can you provide your solutions :
Comment validating uniqueness of trackId in the batch of notification for sending broadcast

**Comment by mohammadranjbarz** [comment]
@maryjaf 
It's on staging, can you test it now?

**Comment by maryjaf** [comment]
Thanks @mohammadranjbarz I test the broadcast notification and it has been fixed
