### ISSUE TITLE
"Engage" grammar fix

### ISSUE THREAD

**Issue by danelsuga** [Giveth/giveth-dapps-v2#210]
![engage](https://user-images.githubusercontent.com/81351744/158306169-90aaeb97-26c6-4c03-a0a9-3f309921ddcb.png)

Should read: "Follow our social media, and come say hello in a channel below. We look forward to welcoming you!"

In English, independent clauses joined in one sentence are separated by a comma and a coordinating conjunction.

Also, two independent clauses cannot be separated by only a comma. In the event you want to join them without a coordinating conjunction, you must insert a semi-colon.

**Comment by NikolaCreatrix** [comment]
Reviewed on chrome - resolved!
