### ISSUE TITLE
Sending a notificationtio, even though no changes have been made on status of project

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#2100]
when I Listed  a project that it's status already is listed , the notification is sent although the status isn't changed 
This problem exists for other changes as well

_Originally posted by @maryjaf in https://github.com/Giveth/impact-graph/issues/809#issuecomment-1407707938_

**Comment by mohammadranjbarz** [comment]
This would happen on 
- [ ] listing
- [ ] unlisting
- [ ] verifying
- [ ] unverifying (reject)
- [ ] activate
- [ ] deactivate

**Comment by mohammadranjbarz** [comment]
@maryjaf  It's on staging and is ready for test

**Comment by maryjaf** [comment]
Thanks @mohammadranjbarz  It has been fixed and now without changes in easch of the above statuses, notification is not sent
But this message is shown in admin bro with out any change, Is it ok?
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/111529185/218304027-ad35343b-f733-4768-b52c-607dd7cafa94.png">

**Comment by mohammadranjbarz** [comment]
> Thanks @mohammadranjbarz It has been fixed and now without changes in easch of the above statuses, notification is not sent But this message is shown in admin bro with out any change, Is it ok? <img alt="image" width="1072" src="https://user-images.githubusercontent.com/111529185/218304027-ad35343b-f733-4768-b52c-607dd7cafa94.png">

ِYeah changing that may need lots of implementation, and I guess it's needed it to fix that , but if @MoeNick  say we should  do it, we will jump to it
