### ISSUE TITLE
By selecting a project, changes will be applied to the previous project displayed in the search list

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#2101]
it related to admin bro
I search a project from the filter section
Project details are displayed
When I select another project name from the filter section and make a change on the project details, for example, listed/unlisted the changes is applied to both projects

_Originally posted by @maryjaf in https://github.com/Giveth/impact-graph/issues/809#issuecomment-1407707938_

**Comment by MoeNick** [comment]
Maybe @CarlosQ96 can jump to this IMPORTANT bug if Mohaammad is busy.

**Comment by CarlosQ96** [comment]
@maryjaf can you confirm if this happens in all environments? or only staging? we did upgrade typeorm and adminbro in staging but we haven't release this yet.

**Comment by MoeNick** [comment]
I'm pretty sure she finds this on staging.

**Comment by MoeNick** [comment]
@CarlosQ96 @mohammadranjbarz this is becoming critical cause it's a blocker to all of our waiting releases, let's prioritize it.

**Comment by CarlosQ96** [comment]
@maryjaf could you leave a set of more details steps. I am trying to reproduce it but no luck.

1. I search a project from the filter section
2. Display details on Show page of the first one
3. Go back and select another and list it with buttons (or in their edit page).
4. Only the second one is being edited succesfully. The first one remains the same.

**Comment by maryjaf** [comment]
Yeah, the steps are correct
I also checked today and could not reproduce it
But yesterday, when I was testing notification, this scenario happened again

> @maryjaf could you leave a set of more details steps. I am trying to reproduce it but no luck. I did multiple variations of this:
> 
> 1. I search a project from the filter section
> 2. Display details on Show page of the first one
> 3. Go back and select another and list it with buttons (or in their edit page).
> 4. Only the second one is being edited succesfully. The first one remains the same.

**Comment by WhyldWanderer** [comment]
I can try to help test but I havent noticed anything in the AdminBro on production.

@maryjaf - how are you making the changes to the project? Are you checking the box and pressing a button? or are you choosing edit and manually changing it in the form? or maybe another way?

**Comment by WhyldWanderer** [comment]
Okay.. I understand.

Also, I noticed that if you checked one of the boxes and then pushed a button, you need to uncheck that box or refresh the page before making any more edits. Maybe this is how the issue occurred?

**Comment by MoeNick** [comment]
Yeah i also had the same experience as @WhyldWanderer said,.
@maryjaf can we edit the issue with a clean reproducing guide for devs?

**Comment by maryjaf** [comment]
> Okay.. I understand.
> 
> Also, I noticed that if you checked one of the boxes and then pushed a button, you need to uncheck that box or refresh the page before making any more edits. Maybe this is how the issue occurred?

Thanks @WhyldWanderer 
Yes, I have already raised this problem with @mohammadranjbarz  and a separate issue has been registered for it
I close this issue considering that it did not happen again
