### ISSUE TITLE
Implement landing page - "REGISTER on our Chainvine Referal Program"

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#2102]
That landing page somewhere in giveth.io invites users to REGISTER on our Chainvine Referal Program and in their ChainvineUI, generate the link to invite their friends to donate.

Example of the landing:
https://www.binance.com/en/activity/referral/offers

That landing page somewhere in giveth.io invites users to REGISTER on our Chainvine Referal Program and in their ChainvineUI, generate the link to invite their friends to donate.

Example of the landing:
https://www.binance.com/en/activity/referral/offers

## Design resource

** (>1280 & <1439) **
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19663%3A248035&t=X0AGv9szyN0dYJi5-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19663%3A248035&t=X0AGv9szyN0dYJi5-4)

** (>1024  & <1279) **
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19663%3A249138&t=X0AGv9szyN0dYJi5-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19663%3A249138&t=X0AGv9szyN0dYJi5-4)

** (>768  & <1024) **
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19663%3A250241&t=X0AGv9szyN0dYJi5-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19663%3A250241&t=X0AGv9szyN0dYJi5-4)

** (Mobile) **
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19663%3A251344&t=X0AGv9szyN0dYJi5-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19663%3A251344&t=X0AGv9szyN0dYJi5-4)

**Comment by mosaeedi** [comment]
@rodricastillo9013 I'm working on the page structure, I'll need a nice illustration for this landing page!

**Comment by mateodaza** [comment]
Ready to work on this as design is done!

**Comment by MoeNick** [comment]
@mosaeedi UPDATED THE DETAILS SO you can start @mateodaza

**Comment by MoeNick** [comment]
btw, copies need to review bu @c0ric0ri 's team. just a heads up before finalizing the page,

**Comment by mateodaza** [comment]
We have the issue #2104, should we close this one? @MoeNick

**Comment by MoeNick** [comment]
That was the design and this is implementation, I move the other to done after cori's confirmation.

**Comment by divine-comedian** [comment]
Hey guys I have a concern that the UX is really bad - I know it's not your fault on the chainvine side but as a user I'm very confused on what is supposed to happen. 

some concerns:
![image](https://user-images.githubusercontent.com/67759413/221264018-bde645fb-0e12-41c1-bd03-f1423fabc78f.png)

following the chainvine link I go here - any user who connects with a web3 wallet can change this link - if I put in the wrong link I can effectively break the referral task link. 

as a user if I break this I have no indication on how to fix it - tbh I don't know why users that are not admins are allowed to change this. 

second:

I took this referral link and opened it in another tab with different connected wallet - i follow the task link and went to giveth, donate to a project successfully with the same connected wallet while connected to gnosis chain. 

nothing new shows up on the chain vine for either user (the referrer OR referree) as a user when should I expect to see a change? what happens next? did it work even? I have no confirmation on the chainvine dashboard that I'm doing things right...

**Comment by divine-comedian** [comment]
We also need some documentation to complement this landing page since there is a lot of details not explained to the user - 

- how much rewards should they expect?
- when should they expect to see the rewards?
- WHERE should they expect to see the rewards?
- is there any confirmation of a successful referral?
- if I break the URL as mentioned above then, what is the correct URL?

**Comment by ahmadabugosh** [comment]
Thanks for this @divine-comedian !

For your first concern (the changing of the url), that's something I told them to switch off and just default to the /projects page. Initially, we wanted to give people the freedom to add their own project urls but it just makes this way too confusing for a normal user. 

For the second one about the alerts on pending and successful rewards, I asked them about that as well and hopefully they can add some alerts in the UI to make it clear what's happening. 

Also, I gave them a bunch of other comments to change in the copy (that would explain how it works and when to expect rewards), UX, and placement of items on the page, so they should have a new version up soon to get everyone's feedback on. 

I'll update here once a new version is up!

**Comment by ahmadabugosh** [comment]
Hey @divine-comedian , 

They changed both of those issues + made the page look a lot cleaner now: https://app.chainvine.xyz/giveth

Now 1) You can't change that url you mentioned and 2) They have a loading image that says your rewards are pending (see below) until you complete the donation. 

<img width="672" alt="Screenshot 2023-02-28 at 11 49 36 PM" src="https://user-images.githubusercontent.com/4855928/222007315-4b46800a-eab4-4c4a-835b-5408a3d675f0.png">

-------

@MoeNick I think we're ready to launch this into production unless anyone has any other objections.

After that we would need to: 

1) Figure out how we're doing GIVbacks (for now I assume manually). This needs a discussion with @GriffGreen @WhyldWanderer @CarlosQ96 @mohammadranjbarz, to figure out how we can do this practically. I think we said we'll go with 10% for that GIVbacks round as a reward for the referrer? But then also we need to figure out how we'll do this in the GIVback calculation in our current workflow.

2) Launch our own landing page on the Giveth site (which is this issue):  https://github.com/Giveth/giveth-dapps-v2/issues/2104#issuecomment-1445158898

3) Build out our documentation and an explainer video to explain how it works.

**Comment by mosaeedi** [comment]
Here is the link for the video section:
[Video link](https://drive.google.com/file/d/1w1xtawKoAGfQWDMJrsUMgkDxvihp_xoI/view?usp=share_link)

**Comment by mosaeedi** [comment]
Please reduce the top margin to **40px**

---

<img width="1095" alt="Screenshot 2023-03-07 at 3 05 31 PM" src="https://user-images.githubusercontent.com/13708322/223411049-67d604b7-c925-451f-b5db-9425ceed617c.png">
