### ISSUE TITLE
Design "Giveth Referral Program" landing page

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#2104]
That landing page somewhere in giveth.io invites users to REGISTER on our Chainvine Referal Program and in their ChainvineUI, generate the link to invite their friends to donate.

Example of the landing:
https://www.binance.com/en/activity/referral/offers

## Design resource

** (>1280 & <1439) **
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19663%3A248035&t=X0AGv9szyN0dYJi5-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19663%3A248035&t=X0AGv9szyN0dYJi5-4)

** (>1024  & <1279) **
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19663%3A249138&t=X0AGv9szyN0dYJi5-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19663%3A249138&t=X0AGv9szyN0dYJi5-4)

** (>768  & <1024) **
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19663%3A250241&t=X0AGv9szyN0dYJi5-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19663%3A250241&t=X0AGv9szyN0dYJi5-4)

** (Mobile) **
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19663%3A251344&t=X0AGv9szyN0dYJi5-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19663%3A251344&t=X0AGv9szyN0dYJi5-4)

**Comment by mosaeedi** [comment]
@MoeNick FYI, 👆

**Comment by MoeNick** [comment]
Thanks @mosaeedi  I asked @c0ric0ri to review the copies first by Monday.

**Comment by mateodaza** [comment]
@c0ric0ri let me know if the content is alright! - I started developing this

**Comment by mateodaza** [comment]
Excellent work @mosaeedi! also I think a tiny detail is missing, where will this page be accessed from? - I set this as a new page called /givferral

**Comment by MoeNick** [comment]
Do we need to access it from our generic hyperlinks? I think the flow will start from chainvine and it should be like this. correct me if Im wrong

**Comment by mateodaza** [comment]
> Do we need to access it from our generic hyperlinks? I think the flow will start from chainvine and it should be like this. correct me if Im wrong

It could start from either, chainvine lists all active campaigns [here](https://app.chainvine.xyz/)

- if it starts from chainvine the person won't know about our landing page and go straight to the /projects&referral_id page
- if it starts from giveth then it would sent the user to the [campaign link](https://app.chainvine.xyz/giveth) and then do the flow as the previous point

**Comment by MoeNick** [comment]
@ahmadabugosh what do you think?

**Comment by c0ric0ri** [comment]
Hey @MoeNick @mateodaza I went through the copy and have some edits here:

https://docs.google.com/document/d/1evcNo7M4cbo6izHt4iRempVS15McrKHx6H59pxVOw_c/edit

**Comment by mateodaza** [comment]
@ahmadabugosh  @mosaeedi in the design we are displaying a video, what video are we using there?

**Comment by ahmadabugosh** [comment]
@mateodaza We don't have the video yet, we still need to record it. For now, can you put an image or another placeholder?

**Comment by laurenluz** [comment]
@mateodaza @c0ric0ri - I changed the copy in the figma to reflect Cori's feedback (and added my own) [here](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19663%3A248035&t=T8I4TjFkkGNIdy3N-4) in the figma.

Can we please not call this "GIVferral"? it's horrible.

**Comment by ahmadabugosh** [comment]
@laurenluz haha I thought we liked "[GIVferral ](https://forum.giveth.io/t/chainvine-referral-program/910/24)" ? I guess it is a bit cheesy. For now we're just calling it the "Giveth Referral Program"

**Comment by laurenluz** [comment]
"GIVferral" not to be confused with "GIVferal" 🤣 
![image](https://user-images.githubusercontent.com/75490971/221369683-a6cfc9eb-d1a2-4a1a-982d-a91daf3a8ab5.png)
