### ISSUE TITLE
PFP | eligibility user flow

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#2107]
As a user I want to check my eligibility for being able to buy some Gibeth NFT, so after I insert my address, what will happen if Im not eligible or eligible?

**Comment by MoeNick** [comment]
@Santigs @divine-comedian fyi

**Comment by Tosinolawale** [comment]
> As a user I want to check my eligibility for being able to buy some Gibeth NFT, so after I insert my address, what will happen if Im not eligible or eligible?

All addresses are eligible to mint. Eligibility questions come into play if we are discussing addresses on the allow list and this is the flow    
![Group 1000001214](https://user-images.githubusercontent.com/35389241/215508548-6ed2abf3-429e-44f5-a99e-19c77afedb3a.png)
Or did I misunderstand the question?

**Comment by MoeNick** [comment]
Perfect thanks @Tosinolawale 
would you please update the links here? https://github.com/Giveth/giveth-dapps-v2/issues/2109
I missed these designs

**Comment by Tosinolawale** [comment]
> Perfect thanks @Tosinolawale would you please update the links here? #2109 I missed these designs

Sure. 
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19021%3A269123&t=NlzNhjosXrzx95Zk-1
