### ISSUE TITLE
PFP | implement eligibility check with backend and error 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#2109]
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19021%3A269123&t=NlzNhjosXrzx95Zk-1

**Comment by Tosinolawale** [comment]
Sure 
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19021%3A269123&t=NlzNhjosXrzx95Zk-1
