### ISSUE TITLE
Sunset Giveth TRACE

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2115]
- [ ] @aminlatifi to move server to local
- [ ] we already migrated the database, should close paid service

**Comment by geleeroyale** [comment]
- db has been backed up and migrated to feathers local
- will run another backup and then decommission the paid instance

**Comment by geleeroyale** [comment]
I terminated the instance. It felt no pain 🥲

**Comment by MoeNick** [comment]
Can I close this?

**Comment by geleeroyale** [comment]
❤️  yes please - will note next time that the issue can be closed

**Comment by MoeNick** [comment]
Thank you all :) and bye lovely Trace!
