### ISSUE TITLE
Remove nice token banner from the Projects page

### ISSUE THREAD

**Issue by mosaeedi** [Giveth/giveth-dapps-v2#2119]
There is a HUGE nice token banner showing on top of the projects list on the projects page! We already have that covered on the Homepage.
Also, the projects page has its own banner showing the project categories, and adding another big banner is not helping users!

Is that necessary or it just appeared there by mistake? 

CC: @laurenluz

**Comment by laurenluz** [comment]
I think this might have been a mistake when we removed the gitcoin alpha round banner.

@mateodaza - can you have a look

cc @MoeNick

**Comment by mateodaza** [comment]
That was a mistake. I'll fix it
