### ISSUE TITLE
"About us" page - "Our Values"

### ISSUE THREAD

**Issue by danelsuga** [Giveth/giveth-dapps-v2#212]
All of the statements under "Our Values" should have periods (no screenshot).

![values altruism.png](https://images.zenhubusercontent.com/6066d509782b4d63df5cd761/4cba27c0-8765-4b5e-9d75-8bd7f90640e7)

Also note that there are two sections entitled "Giveth Altruism" (screenshot).

**Comment by NikolaCreatrix** [comment]
Reviewed on chrome and only last detail to fix is this sentence (screenshot)

![image](https://user-images.githubusercontent.com/100084867/159811701-0f1a233b-b2ff-4cbc-a4fd-f7f6ac4b8eff.png)
