### ISSUE TITLE
Switch network from Georil To Gnosis doesn't work

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#2121]
**Describe the bug**
Switch network from Georil To Gnosis doesn't work on stg

**To Reproduce**
1. Network set on Georil
1. Go to 'https://staging.giveth.io/donate/the-teen-project-inc'
2. Click on 'donate'
3.Click on 'switch network'

**Comment by MohammadPCh** [comment]
@RamRamez could you please take a look?

**Comment by RamRamez** [comment]
> @RamRamez could you please take a look?

No problem I'll take a look

**Comment by MoeNick** [comment]
I think @maryjaf had this problem on third parties projects like GivingBlock (like https://staging.giveth.io/donate/the-teen-project-inc) only in the stage, so config should be re-considered I guess.
 on the production it works fine.

**Comment by maryjaf** [comment]
> **Describe the bug** Switch network from Georil To Gnosis doesn't work on stg
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Network set on Georil
> 2. Go to 'https://staging.giveth.io/donate/the-teen-project-inc'
> 3. Click on 'donate'
>    3.Click on 'switch network'

Plz check these steps @RamRamez

**Comment by MoeNick** [comment]
@RamRamez did you take this one?

**Comment by RamRamez** [comment]
This project has no wallet address associated with it and that's the problem. Other giving block projects on staging is ok and you can test.

![image](https://user-images.githubusercontent.com/73441857/217205968-b6d446f7-04d1-4f23-8b5a-2bf334aa2c64.png)

![image](https://user-images.githubusercontent.com/73441857/217206196-435bd348-171c-4e99-80ff-7299d67601dd.png)

[https://staging.giveth.io/donate/pure-earth](https://staging.giveth.io/donate/pure-earth)
