### ISSUE TITLE
Projects link misplaced

### ISSUE THREAD

**Issue by danelsuga** [Giveth/giveth-dapps-v2#213]
Sorry if this is already an issue! I can't seem to find it if it is however, so I'm creating this one. Sorry @mateodaza if I'm wrong!

I just wanted to point out that the link is misplaced in the word, which I'm assuming is a mistake.

![projects.png](https://images.zenhubusercontent.com/6066d509782b4d63df5cd761/13f97b58-9d4f-4b4d-b34d-1193ff10ea82)

The link also appears to be broken.

I will also add that the text should have a comma (joining two independent clauses with a coordinating conjunction): "Explore the Giveth crypto fundraising platform COMMA and give crypto directly to charities and social good projects with zero fees on donations!"

**Comment by MoeNick** [comment]
@mateodaza I think you know this old bg picture .

**Comment by NikolaCreatrix** [comment]
Checked on chrome - resolved.
