### ISSUE TITLE
make a landing page for SEO purposes.

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#2137]
Hey @mosaeedi @MoeNick, We want to make a landing page for SEO purposes. 

Can you make it into a template we can easily use to create more pages in the future? 

It will be a page that doesn't appear on the navigation and can be super simple. For the top maybe a simple image that we already have and the rest is just text. 

Can you start with this page here please? https://docs.google.com/document/d/10StNqgY411icT6FmhfPcnxHimiwBFWrV7pydWJSRvRs/edit#heading=h.5zovxx6ai50x

Thanks! 

_Originally posted by @ahmadabugosh in https://github.com/Giveth/giveth-planning/issues/1190#issuecomment-1420613835_

**Comment by MoeNick** [comment]
Here is the general design;
https://www.figma.com/file/hNqwpebu4JCy1XIed2c862/Giveth-Public?node-id=244-21173&t=7bJkmhntxnM5rtBi-4

**Comment by mosaeedi** [comment]
## The banner section
Contain an image and a place to show the Title(required), subtitle(optional), and a CTA button(Optional)

![Screenshot 2023-04-20 at 5.42.53 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/3821e08d-9d96-4c84-b727-139b3c963597)

## Short intro
A short intro section is good for showing the tagline for the landing page

![Screenshot 2023-04-20 at 5.43.20 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/e0e2728d-0029-4df9-932f-a5e35c898fe0)


## Simple content
We can have the image on the **left** or **right**. Also, the image can be simply presented or in an elevated border to make it more prominent.
The button is optional.

**Simple content + elevated image**
![Screenshot 2023-04-20 at 5.46.00 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/2de1b5ae-4036-446f-af3d-d5936559ff0b)

**Simple content + simple image**
![Screenshot 2023-04-20 at 5.46.37 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/b9d4a8dd-73ee-4e10-b739-3618f38478ac)


## Important content
We can use the **Important content** section to show critical information. The image in this section can only be a simple image. 
The button is optional.

**Image on the right**
![Screenshot 2023-04-20 at 5.49.39 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/616bf461-1f8f-45e9-946d-0a371e64fb81)

**Image on the left**
![Screenshot 2023-04-20 at 5.49.52 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/33b70041-27d9-48c0-8004-4186c435a2b2

## Custom project row
We can also have the option to show some projects specifically on this page.
**Note:** The title should not be more than 20 characters.

![Screenshot 2023-04-20 at 5.52.19 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/5847fb68-8d48-4779-9810-c369eaac540c)


## Possible partners
Showing the possible partners on the Landing page

![Screenshot 2023-04-20 at 5.53.35 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/7afbe259-6e20-4505-b230-7de7e00ee7a1)

## Content breaker
It's good to break the order on the Landing page to present something important to the reader.

![Screenshot 2023-04-20 at 5.54.29 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/0ac843fa-6f22-464b-a9bc-e11442b9c110)


## Quote Section
Suitable to present long text on the Landing page.
The button is optional.

![Screenshot 2023-04-20 at 5.55.20 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/a6733eea-2047-40aa-8ef2-3c4d1383c0b8)

**Comment by ahmadabugosh** [comment]
First version of this page is live: https://giveth.io/landings/web3-crypto-donation-platform
