### ISSUE TITLE
Content for our team page

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#214]
on https://giveth-dapps-v2.vercel.app/about and on Team tab, we need a sentence below the title. 

![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/01311349-e45f-45d7-ac5c-78ff5ee0353a)

**Comment by mateodaza** [comment]
Removing until we have a sentence

**Comment by Cotabe** [comment]
DONE
