### ISSUE TITLE
Earthquake Relief Banner 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#2144]
![Donate banner](https://user-images.githubusercontent.com/61791380/217827816-1b69e7fc-ddcc-4efe-b050-f7339d2c6923.png)
I have made this Banner, tell me if it is ok! @danelsuga 

_Originally posted by @rodricastillo9013 in https://github.com/Giveth/giveth-planning/issues/1208#issuecomment-1424204907_

**Comment by danelsuga** [comment]
No worries, @MoeNick ! It's already published with the new banner! Thank you! :D

https://medium.com/giveth/ways-to-help-earthquake-victims-in-turkey-and-syria-on-giveth-155d7855164

**Comment by MoeNick** [comment]
I was thinking we have to have it on our home-page and linked it to the blog post, so I created another issue in v2. @danelsuga 
did the plan change?

**Comment by danelsuga** [comment]
Oh sorry!! Yes!!

**Comment by danelsuga** [comment]
I misunderstood. I was distracted today.
