### ISSUE TITLE
Improve project search function quality

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#2145]
Suggesting a few quality of life features to the project search function on the all projects page 

## 1 
I noticed that when we click the search icon the search box is not automatically selected. This means I need to click the search icon then click the search box and begin typing - ideally I should have 1 click less - I click the search icon and begin typing my query. 

![image](https://user-images.githubusercontent.com/67759413/218170610-7538c27c-f1c2-4b03-8e39-562508ac5eee.png)

## 2 
A great feature is a search bar hot key - the most common one I've seen on web apps is ctrl +f or ctrl + k. I would recommend we go with ctrl + k so we do not interfere with the browsers built-in search hot key. We also use ctrl + k in our giveth docs for searching. 
![image](https://user-images.githubusercontent.com/67759413/218170682-1c08e815-9f79-42cd-8aa9-c638291e375c.png)

@MoeNick does this make sense?

**Comment by mosaeedi** [comment]
1. I agree with the first suggestion. 

2. In the current design, we don't have enough space to educate users that we do have the hotkey option, and also, it's better to know how many users are using the search function than adding more advanced features!

**Comment by MoeNick** [comment]
Make the textbox selected in the modal when users click on the search bar.
