### ISSUE TITLE
Metadata on project links show old information

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2148]
@clara-zi updated the graceaid project & I shared the link via twitter... but the metadata on the link preview on twitter still shows the old information.

It would be great if the metadata reflected project updates.

See this tweet: https://twitter.com/Givethio/status/1623720178683977729

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/47311b56-7034-4787-ba8c-0765259247e8)

**Comment by RamRamez** [comment]
Project Metadata is being updated on our website instantly. You can check page source.

view-source:https://giveth.io/project/turkey-earthquake-relief-fund

![image](https://user-images.githubusercontent.com/73441857/218324125-5e34f815-b08a-4742-ad4d-9a4663784136.png)

**Comment by RamRamez** [comment]
For some reason, Twitter updates card information every seven days.

"The Twitter web crawler re-indexes the Card tag information on your page roughly every seven days."

https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/troubleshooting-cards#refreshing_tags

**Comment by RamRamez** [comment]
Twitter suggests using bit.ly URL to fix this problem and to show the latest updates on Twitter URL cards. I checked and it's working:

test link:
https://bit.ly/ram-test

![Screenshot 2023-02-12 200538](https://user-images.githubusercontent.com/73441857/218324463-d8e0d26e-d95c-4056-8443-bd14cbc9bb77.png)

**Comment by laurenluz** [comment]
Wow - so interesting! thanks for looking into that @RamRamez - we'll do that then :)
