### ISSUE TITLE
GIVpower module is buggy

### ISSUE THREAD

**Issue by brichis** [Giveth/giveth-dapps-v2#2149]
**Describe the bug**
It doesn't allow you to add more than 1 number at a time and is having troubles when you try to scroll on the module, it keeps undoing the scroll and scrolling up (from the phone) 

**To Reproduce**
1. Go to Get GIVpower
2. Click on Stake
3. Write 2 or more numbers on the "Amount to stake"

**Screenshots**
![photo_2023-02-09_10-44-07](https://user-images.githubusercontent.com/106570342/217881263-44f1ffe1-a1bc-4290-8536-eb7fe0908ba7.jpg)

https://user-images.githubusercontent.com/106570342/217881417-8b9d7ad9-a603-4615-8d86-7c2bd4bb08f5.mov

**Desktop (please complete the following information):**
 - OS: (Video) macOS
 - Browser: Brave

Cc. @MoeNick @laurenluz

**Comment by MohammadPCh** [comment]
Thanks @brichis for reporting, This problem was fixed in 2 or 3 previous versions. Are you still having this problem?

**Comment by MohammadPCh** [comment]
Thanks @brichis for reporting, This problem was fixed in 2 or 3 previous versions. Are you still having this problem?

**Comment by brichis** [comment]
Hi @MohammadPCh ! I tested it and I don't have that problem anymore. Thank you!
