### ISSUE TITLE
GIVpower boosting is buggy

### ISSUE THREAD

**Issue by brichis** [Giveth/giveth-dapps-v2#2150]
**Describe the bug**
When I'm boosting, I select an amount and percentage but when I save it, the platform saves another amount that I didn't choose.

**To Reproduce**
1. Go to Boost any project
2. Click on the amount you want to boost
3. Save it

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Brave
 - Version: [Version 1.47.186 Chromium: 109.0.5414.119 (Official Build) (arm64)](https://brave.com/latest/)

Cc. @MoeNick

**Comment by MoeNick** [comment]
@maryjaf can you take a look and reproduce it.

**Comment by maryjaf** [comment]
Do you have this problem with the Chrome browser? @brichis

**Comment by brichis** [comment]
Hi! @maryjaf my problem was with Brave, I assume it's the same than Chrome but Idk

**Comment by maryjaf** [comment]
> Hi! @maryjaf my problem was with Brave, I assume it's the same than Chrome but Idk
But I can't reproduce this scenario
when I change the percentage of givpower and tap on confirm the amount of boost is changed correctly 
<img width="478" alt="image" src="https://user-images.githubusercontent.com/111529185/218941358-be65ef62-aafa-4571-ad97-bae58384a6d9.png">
<img width="1420" alt="image" src="https://user-images.githubusercontent.com/111529185/218941441-a2d913dd-32ec-433d-8ffd-fcee30a8503f.png">
<img width="969" alt="image" src="https://user-images.githubusercontent.com/111529185/218941604-655924cc-2eef-4d3d-92b5-34b7d47e265e.png">

**Comment by brichis** [comment]
I tried again now and I didn't have that problem anymore, we can close this issue. Thanks!
