### ISSUE TITLE
Add BANK on the cryptocurrencies accepted

### ISSUE THREAD

**Issue by brichis** [Giveth/giveth-dapps-v2#2151]
Hey devs team! Could you add BANK on the list of cryptocurrencies accepted please? 
We already talk about this on our Forum: https://forum.giveth.io/t/bank-listed-on-the-cryptocurrencies-accepted/992

It's only adding it to our list of cryptocurrencies accepted so they can donate to our projects with BANK token. It won't be part of GIVbacks token list.

Info. about $BANK:
https://www.coingecko.com/en/coins/bankless-dao

If I'm missing something please let me know, THANKS!
Cc. @MoeNick @laurenluz

**Comment by MoeNick** [comment]
We have "adding tokens" feature in Admin, if this is dev issue, I think we can close it now, if it's a Gov issue, let's move it to planning board.

**Comment by brichis** [comment]
Thanks @MoeNick for always answer the issues that I create on Zenhub :)
