### ISSUE TITLE
Highlight Giveth projects responding to Turkey crisis to Giveth projects page

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2155]
Our default sorting should be by rank still, however - in reponse to the crisis in Tukey - we should pin these 4 projects to the top of the projects page and hopepage.

I think, if they user selects manually another sorting option, they should be sorted normally with the other projects.

These are the projects we want to highlight:
https://giveth.io/project/gnosisdao-earthquake-relief
https://giveth.io/project/banklessdao-turkey-disaster-relief-fund
https://giveth.io/project/graceaid
https://giveth.io/project/anka-relief

We need design for this! Would love some quick support from @mosaeedi or @Tosinolawale 

@aminlatifi will make a PR for this today & get @CarlosQ96 to review

cc @MoeNick @GriffGreen

**Comment by laurenluz** [comment]
After much deliberation, we will be using the campaing block from the homepage new design (minus the backend) - manually adding those 3 projects above.

1- add featured projects bloc on home page (static projects)
2- add featured projects block on projects page on top (static projects)
3- adding banner in home page and project page which will link to blog post (above the projects bloc)

![image](https://user-images.githubusercontent.com/75490971/218183759-878a1c30-bd38-4ede-b8e4-c220d7c54df5.png)

**Comment by NikolaCreatrix** [comment]
Those are all we have so far @laurenluz

**Comment by WhyldWanderer** [comment]
Heres another but its not verified yet - https://giveth.io/project/turkey-earthquake-relief-fund

**Comment by c0ric0ri** [comment]
As we now have a time-sensitive push to raise funds for the Earthquake Relief QF Matching Pool, can we please add this project to the campaign block? The campaign ends on Monday Feb 20th so we want to have it as visible as possible.

https://giveth.io/project/earthquake-relief-qf-matching-pool

@mateodaza @MoeNick

**Comment by danelsuga** [comment]
This one is also missing from the earthquake feature list (both on the landing page and on the "see projects" page): 

https://giveth.io/project/gnosisdao-earthquake-relief

@mateodaza @MoeNick
