### ISSUE TITLE
FAQs more grammar

### ISSUE THREAD

**Issue by danelsuga** [Giveth/giveth-dapps-v2#216]
![faqs more.png](https://images.zenhubusercontent.com/6066d509782b4d63df5cd761/8539bd2d-70a4-490b-8c20-c5498338fdc7)

Under the question "Are there fees for creating a project?" the word Ethereum should be capitalized for a second time.

Under the question "I’m a donor. How do I know projects are getting my money?"

Should read: "Each project description page shows a list of all donations made to that project and by whom."

As well as: "You will get to see photos and receive frequent updates on the status of each project to which you've donated."

**Comment by Cotabe** [comment]
DONE
