### ISSUE TITLE
Add link to 101 video guides (YouTube) to 'docs' guides

### ISSUE THREAD

**Issue by clara-zi** [Giveth/giveth-dapps-v2#2168]
1) Add link Project Owners 101 Guide (YouTube) to Giveth Docs: https://docs.giveth.io/dapps/createproject

https://youtu.be/QgC05uGTaZo

2) Add link to Donor 101 Guide (YouTube) to Giveth Docs:  https://docs.giveth.io/dapps/projectdonating

https://youtu.be/-JXwwIGJGQQ

**Comment by franculio** [comment]
Hey @clara-zi ! I did add the Donor 101 Guide, but it's on the [Getting started](https://docs.giveth.io/dapps/gettingStarted) section. I think it's a good idea to add it as well to where you are suggesting. I'll work on it.

**Comment by franculio** [comment]
@clara-zi I've drafted this sentences to add the links and put them like this. Let me know what do you think and if it looks good I'll create the pull request with the update. 

**This one for the Project Owners 101 in the Create a project section.**

<img width="1150" alt="Captura de Pantalla 2023-02-14 a las 12 52 03" src="https://user-images.githubusercontent.com/79286405/218730552-73845f65-f77f-4aa1-8ed5-e538c7a6396e.png">


**This one for the Project Donor 101 in the Project donation section.**

<img width="1169" alt="Captura de Pantalla 2023-02-14 a las 12 41 17" src="https://user-images.githubusercontent.com/79286405/218728219-fdb2d6cf-fbbf-4029-a3cf-01e31102fc66.png">

**Comment by franculio** [comment]
Hey @danelsuga, would you mind taking a look at these two sentences that @clara-zi asked me to add and have links for the Project Owners and Donor 101 video courses? If it looks good I can send the update right away. Thanks!

**Comment by danelsuga** [comment]
Hi @franculio !

For the first one, where it says, "Think about the project..." I would change this question, "What are you asking for funding for?" for clarity to simply "What do you need funding for?" or even "Why are you requesting funding?"

For the end of that one where it says, "Discover the ins and outs", I thought it was the Project Owners 101 video course? Or is it singular?

For the second image, same question for "Donor/s". And for the last sentence, I'd put a comma after fiat.

Otherwise, great!

Thanks!

**Comment by franculio** [comment]
Thank you @danelsuga ! I just followed the way it is written on youtube, if you check the links to the courses, the titles of the playlists are [Project Owner](https://youtube.com/playlist?list=PL4Artm1rmCWFi-qEkOtjl9nL4tojSIIKm&si=EnSIkaIECMiOmarE) and [Donor](https://youtube.com/playlist?list=PL4Artm1rmCWH4Q5XnrQWf8fm0xob3hbdZ&si=EnSIkaIECMiOmarE) 101 respectively. 

But then on the actual video (and other places like Discord) is actually written in plural (at least on the Project Owners one). 
I'll change the playlist title and this link to plural so there's more consistency.

Donor 101 according to [this tweet](https://twitter.com/Givethio/status/1529482645029126146) seems to be singular.

I'll make the other changes and finish with this update! Thanks!

**Comment by franculio** [comment]
This has been updated, closing the issue.
