### ISSUE TITLE
FAQs more grammar part 3

### ISSUE THREAD

**Issue by danelsuga** [Giveth/giveth-dapps-v2#217]
![faqs 3](https://user-images.githubusercontent.com/81351744/158374362-cfaa6b3c-b68b-45ff-b248-24b96c314168.png)

Capitalize Ethereum under this question: 
What percentage of the donations go directly to the project?

The content of this question "How can I be sure my donations are making a difference?" is a repeat of this question "I’m a donor. How do I know projects are getting my money?"

For the question "Can I donate on Giveth if I don't have crypto?" the last sentences should read: "Until then, fiat donations will accepted here EMBED LINK, OR INSERT COLON. (https://www.sdgimpactfund.org/giveth-foundation). To learn more about the partnership between Giveth (CAPITALIZE) and the SDG Impact Fund, please refer to this blog post  EMBED LINK, OR INSERT COLON. (https://medium.com/giveth/giveth-2-0-next-level-community-philanthropy-f7e60d7e78cb). PERIOD

**Comment by mateodaza** [comment]
About the second point, should we remove one or change the whole answer?

**Comment by laurenluz** [comment]
I think we should keep both, they are different. The one "How can I be sure my donations are making a difference?" is saying tha t projects can provide updates to say how they're using the funds... 

This one "I’m a donor. How do I know projects are getting my money?" is saying you can check tx history to see that the project is getting the money.

**Comment by Cotabe** [comment]
1ST PART DONE

2ND PART I agree that having the same answer for both questions feels weird. Maybe something for a future launch.

3RD PART It seems that I can already pay with credit card. But I haven't been able. My wallet is connected and when I push on pay with credit card it says thanks for donating without getting any of my details. I will post this in a different issue.
