### ISSUE TITLE
QF - feature request - add batch transactions / cart + donation to matching pool

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-dapps-v2#2175]
**What new feature(s) would you like to see on Giveth?**
batch transaction when sending donation + donation to matching pool

**Comment by MoeNick** [comment]
I moved the sprint and moved it back to product backlog @laurenluz

**Comment by laurenluz** [comment]
this is basically: https://github.com/Giveth/Roadmap/issues/14
