### ISSUE TITLE
PFP minting page fixes

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#2177]
testing on https://givpfp.vercel.app/nft
OS: Linux 22.04 
Brave Browser 

### This text should be centered 
![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/ddeb0c5f-a817-444a-ba78-9944de856fa5)

### Dead link to opensea page
Also remove the hover button that shows - should just be a normal link

![image](https://user-images.githubusercontent.com/67759413/218864064-63f88de0-6adb-4256-9d5e-51fd5ae95b32.png)

### verify button throws an error if the user isn't connected with their wallet 
The user should be prompted to sign in with their web wallet on entering the page and if they try to click any buttons requiring a blockchain connection - similar to how it already works on the dapp
![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/8c2dc97f-4047-4e54-a83e-3b239b49aa81)

## Check user balance and throw error on front-end
we will need to check the user balance so they don't try to mint over their max balance allowance
if the max balance is 10 and I own 5 and try to mint 6 more the contract will throw an error - by not checking on the frontend we waste the users gas on making the approve and trying to mint
![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/a9b4fa9f-f021-4b96-b237-4ba68863ee87)

# Check list
- [x] center text 
- [x] fix opensea button dead link
- [x] remove hover button state on opensea button
- [ ] add in pop up for user to sign with web wallet

**Comment by MohammadPCh** [comment]
@alireza-sharifpour I will fix the Mint page problems.

**Comment by MohammadPCh** [comment]
@divine-comedian about this part: "Check user balance and throw an error on front-end":
when the user wants to mint for example n NFTs, we should first fetch the `balanceOf` user from the contract (consider it is m) and also `maxMintAmount` (consider it is k) and check this: n + m should be less or equal to k.
am I right?

**Comment by divine-comedian** [comment]
> @divine-comedian about this part: "Check user balance and throw an error on front-end": when the user wants to mint for example n NFTs, we should first fetch the `balanceOf` user from the contract (consider it is m) and also `maxMintAmount` (consider it is k) and check this: n + m should be less or equal to k. am I right?

yes that's correct

**Comment by MohammadPCh** [comment]
> > @divine-comedian about this part: "Check user balance and throw an error on front-end": when the user wants to mint for example n NFTs, we should first fetch the `balanceOf` user from the contract (consider it is m) and also `maxMintAmount` (consider it is k) and check this: n + m should be less or equal to k. am I right?
> 
> yes that's correct

 @divine-comedian  And what should be the error message?

**Comment by divine-comedian** [comment]
`You cannot mint or own more than the maximum amount.`

@MohammadPCh

**Comment by MohammadPCh** [comment]
@divine-comedian also, I think it would be nice to have somewhere on the mint card to show the user how many NFTs he has minted.

**Comment by divine-comedian** [comment]
> @divine-comedian also, I think it would be nice to have somewhere on the mint card to show the user how many NFTs he has minted.

Can we stick it on this line? Very likely users won't go to mint more than once so we shouldn't break our heads with finding a solution.

![image](https://user-images.githubusercontent.com/67759413/220169086-5ce5f6f8-dfe8-4727-b38c-060b68d1112e.png)

`3/1000 Minted; This wallet holds x Givers NFTs`

You can also add the balance into the error message if it's easy. 

`You cannot mint or own more than the maximum amount. This wallet holds x Givers NFTs`

**Comment by MohammadPCh** [comment]
This is how it turned out
![image](https://user-images.githubusercontent.com/17097576/220267503-be9f4c76-3a31-4053-9db3-19a7bcb98c4e.png)

**Comment by alireza-sharifpour** [comment]
This is how verify button works now after fixing the Infura API_KEY in our configs:

We check whether the user wallet is connected or not, if it's connected we check the eligibility from their wallet web3 provider and if not we check it directly from Infura, is it ok @divine-comedian?

Another option would be to force the user to connect their wallet and not use the Infura directly.

**Comment by divine-comedian** [comment]
@alireza-sharifpour yes this is fine - there's no need to force the user to sign in - as long as the feature works seamlessly and we don't get any errors

**Comment by divine-comedian** [comment]
a few more issues here: 

there is a lot of blank space here below the main content of the minting page 
https://givpfp.vercel.app/nft/mint

![image](https://user-images.githubusercontent.com/67759413/220427601-dac2b36e-16c1-4d6e-9cf1-d483229f1ed0.png)

is there a reason it is like this or can we remove this empty space and have just the footer follow?

## ALSO 

we should have two links here:
![image](https://user-images.githubusercontent.com/67759413/220427814-a374d984-633f-4c8e-8eb4-a1bbc6a39457.png)

in each section at the end. 

`Learn more about $nice.` - should link to https://docs.giveth.io/giveconomy/niceToken
`Learn more about the benefits.` - should link to https://docs.giveth.io/dapps/giverspfp/#benefits



- [ ] add link to $nice docs
- [ ] add benefits link
- [ ] remove empty space from bottom of mint page

**Comment by divine-comedian** [comment]
checking the responsiveness and we can see the text and the image overlap a bit - you can see the screen resolution in the image attached
![image](https://user-images.githubusercontent.com/67759413/220430741-5094d235-542d-4910-ac9d-9d45cbbb5e01.png)

on the minting error page this link appears to be dead - it doesn't go anywhere at least 
i got here for example trying to mint when the address was not on the allow list - there was an approve and then the mint failed with no transaction generated
![image](https://user-images.githubusercontent.com/67759413/220431173-757633b3-f60d-43ac-84e3-3a7050152d39.png)

**Comment by divine-comedian** [comment]
I added in those links and some typo fixes here:
https://github.com/Giveth/giveth-dapps-v2/commit/ec3d6d6eb4eecec70c09c5f87c382b6eedeea6b2

**Comment by MohammadPCh** [comment]
@divine-comedian Thanks :+1:

**Comment by MohammadPCh** [comment]
@divine-comedian if fixed it directly on the PFP develop branch, it looks like this now:
![image](https://user-images.githubusercontent.com/17097576/220656401-0ce7e5f4-cf81-4320-90d8-479620aa95a3.png)

**Comment by divine-comedian** [comment]
looks good! @MohammadPCh
