### ISSUE TITLE
Tiny website edits

### ISSUE THREAD

**Issue by danelsuga** [Giveth/giveth-dapps-v2#2185]
Just going through things and have found some tiny mistakes.

On the "About" page, the "Join here" link is smaller text than the rest.
![Screenshot 2023-02-15 8 52 51 AM](https://user-images.githubusercontent.com/81351744/218966288-c305574e-4c7f-4fe8-9435-884d11a8ed0a.png)
@aminlatifi @RamRamez @mateodaza @MoeNick @CarlosQ96

**Comment by RamRamez** [comment]
I transferred this issue to `giveth-dapps-v2`

**Comment by danelsuga** [comment]
Oh thank you! Sorry! And thank you. :)

**Comment by danelsuga** [comment]
Another text change please @RamRamez
Based on a discussion on issue [1167](https://github.com/Giveth/giveth-planning/issues/1167) on planning, could you please change the link AND page title that reads "Partners" to "GIVfriends"?

And change the subtext line to: 

Check out our GIVfriends: partners and fellow organizations that are helping us further our mission.

---
Thanks!

![Screenshot 2023-02-16 9 59 53 AM](https://user-images.githubusercontent.com/81351744/219629033-0708ba2c-8d2d-460a-a65a-14eb8646876e.png)

**Comment by danelsuga** [comment]
Yes to all! Thank you!

**Comment by RamRamez** [comment]
> Yes to all! Thank you!

Done!

**Comment by danelsuga** [comment]
@RamRamez thanks! I'm confused though. I don't see any changes anywhere.

![image](https://user-images.githubusercontent.com/81351744/220062079-ebac21e4-f0fc-4a7e-8248-809aad7c51bf.png)

**Comment by RamRamez** [comment]
> @RamRamez thanks! I'm confused though. I don't see any changes anywhere.
> 
> ![image](https://user-images.githubusercontent.com/81351744/220062079-ebac21e4-f0fc-4a7e-8248-809aad7c51bf.png)

My PR is not reviewed yet. Changing a page URL address will result in SEO penalties.
@MoeNick Do you confirm this to be merged?

**Comment by MohammadPCh** [comment]
@danelsuga Thank you for improving this page content. as a technical concern, we need to consider what happens to our old URL, Are we going to redirect users that go to the partnership page to this page? show them `page not found`?

**Comment by danelsuga** [comment]
Let's get some more voices to weigh in here. Thanks @MohammadPCh !
@laurenluz @c0ric0ri @ahmadabugosh @WhyldWanderer @SnakeGH @clara-zi

**Comment by laurenluz** [comment]
@MohammadPCh - we should redirect them - can we do it?

**Comment by MoeNick** [comment]
danelsuga I suggest while after you reviewed and had list of changes which are final with your team members, then assign in to me. Devs issues are a little bit different than planning and discussions may distract them. So if you agree please un-assign @RamRamez @MohammadPCh and move this issue back to planning. We may start right after the changes are final and in a list.

**Comment by ahmadabugosh** [comment]
hey in terms of the url, I would either keep it as /partnerships or if we decide to change it to /givfriends, make sure to do a 301 redirect from /partnerships to /givfriends, to avoid any SEO penalties

**Comment by MohammadPCh** [comment]
@laurenluz Yes, It's possible to redirect it.

**Comment by laurenluz** [comment]
I like @ahmadabugosh suggestion of keeping it as /partnerships (I just thought it was already changed)

**Comment by RamRamez** [comment]
> I like @ahmadabugosh suggestion of keeping it as /partnerships (I just thought it was already changed)

I changed it back to `/partnerships` (PR #2230)
