### ISSUE TITLE
Traces of TRACE to be removed

### ISSUE THREAD

**Issue by danelsuga** [Giveth/giveth-dapps-v2#2187]
@aminlatifi @RamRamez @mateodaza 

Everything under Trace is visible and available.
https://trace.giveth.io/traces

TRACE link present at the bottom of Giveth.io

**Comment by RamRamez** [comment]
> Could you change the repository for this one too please @RamRamez ? I don't seem able. Thank you.

Sure, I moved it.

**Comment by RamRamez** [comment]
> ojects have the TRACE badge on their pro

The Trace badge is already removed in staging. It will go into production on our next release.

**Comment by RamRamez** [comment]
> @aminlatifi @RamRamez @mateodaza
> 
> Everything under Trace is visible and available. https://trace.giveth.io/traces
> 
> TRACE link present at the bottom of Giveth.io

I removed Trace link from Giveth.io footer in PR #2194

**Comment by RamRamez** [comment]
I removed trace donations from single projects page.

cc @MoeNick 

![image](https://user-images.githubusercontent.com/73441857/219810127-507a58e1-d58b-43af-9372-6a408177f53a.png)

**Comment by laurenluz** [comment]
@divine-comedian for updating blogs that were uploaded to the docs... do we need to update them directly in the docs? or can we make edits in medium & have them auto-refected in the docs?

**Comment by divine-comedian** [comment]
> @divine-comedian for updating blogs that were uploaded to the docs... do we need to update them directly in the docs? or can we make edits in medium & have them auto-refected in the docs?

They are unfortunately edited manually - honestly they're a big pain in the butt
