### ISSUE TITLE
PFP | 

### ISSUE THREAD

**Issue by Santigs** [Giveth/giveth-dapps-v2#2198]
**Describe the bug**
A link to collection documentation shoud be added in the message announcing address not in the allow list
**To Reproduce**
1. Go to minting page
2. Click on submit after entering an address, not in the allowlist
3. In the pop up  message I would include the link to the documentation

**Expected behavior**
I would include the link to the documentation doc.
I would also encourage to come back when minting is public.
Also, "Learn More" button does not send you anywhere, maybe this where whe could add the link to the documentation page.

**Screenshots**
![Screenshot 2023-02-17 at 16 51 08](https://user-images.githubusercontent.com/34634436/219703532-7e269d9f-e656-4d64-9a9b-433f034c313f.png)

**This happens on which Boosting Section?**
- [ ] Overview page
- [X] Overview page | verifying the eligibility
- [ ] Minter Page
- [ ]  Success Page
- [ ] Docs
- [ ] Other (like login, broken links, header, footer, language, etc.) 

**Desktop (please complete the following information):**
 - OS: IOS
 - Browser Chrome
 - Version  109.0.5414.119 (Official Build) (x86_64)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MohammadPCh** [comment]
@alireza-sharifpour could you please take a look?

**Comment by alireza-sharifpour** [comment]
> * Click on submit after entering an address, not in the allowlist

Sure

**Comment by alireza-sharifpour** [comment]
@Santigs Could you please send me the documentation link? I will link the learn more button to that.

**Comment by Santigs** [comment]
@alireza-sharifpour here

https://docs.giveth.io/dapps/giverspfp/
