### ISSUE TITLE
"syntax error at or near \")\"" error  on new homepage branch

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#2200]
**Describe the bug**
When I choose two fillers **from giving block** and **accepts funds on gnosis** together
Or when I search for the name of the **testmyprojec**t that I have just created, I get this error
syntax error at or near \")\" @MohammadPCh @MoeNick 

<img width="1084" alt="image" src="https://user-images.githubusercontent.com/111529185/219787270-2d8a504b-8042-4e2c-97b8-ff15c75ad490.png">
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/111529185/219787473-eecb0a13-be5f-4356-879d-6ba55a6ec15c.png">

**Comment by mohammadranjbarz** [comment]
@CarlosQ96 I fixed it through https://github.com/Giveth/impact-graph/issues/873
