### ISSUE TITLE
PFP | 

### ISSUE THREAD

**Issue by Santigs** [Giveth/giveth-dapps-v2#2213]
**Describe the bug**
In the minting page, when logging in with an address not in allow list, the error shown inside the alert box has a "Learn More" button which sends you to the top of the landing page, it would be better if it would send you to the "What else?" section of the landing page where there is a description on how to get into the allow list.

**To Reproduce**
1. Go to ['minting page'](https://givpfp.vercel.app/nft/mint)
2. Sign in with an address not in allow list

**Expected behavior**
![Screenshot 2023-02-20 at 12 45 39](https://user-images.githubusercontent.com/34634436/220098995-5349c85e-85b3-430b-9da5-8ffff18fa4dd.png)

It would be better if the "Learn More" button would send you to the "What else?" section of the landing page where there is a description on how to get into the allow list.

**Screenshots**
![Screenshot 2023-02-20 at 12 49 17](https://user-images.githubusercontent.com/34634436/220098884-ca3699d5-0831-4f36-bb40-2040312e7229.png)

**This happens on which Boosting Section?**
- [ ] Overview page
- [ ] Overview page | verifying the eligibility
- [X] Minter Page
- [ ]  Success Page
- [ ] Docs
- [ ] Other (like login, broken links, header, footer, language, etc.) 

**Desktop (please complete the following information):**
 - OS: IOS
 - Browser Chrome/Metamask
 - Version 109.0.5414.119 (Official Build) (x86_64)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by divine-comedian** [comment]
let's close it!
