### ISSUE TITLE
PFP | Sucess minting "View on Opensea" message

### ISSUE THREAD

**Issue by Santigs** [Giveth/giveth-dapps-v2#2214]
**Describe the bug**
There is no link in the "View on Opensea" message after a successful minting.

**To Reproduce**
1. Go to minting page
2. Click on mint button after introducing an amount less or equal than 10
3. Confirm and pay transaction (two steps)
4. See success message with the View on Opensea button

**Expected behavior**
There is no link in the Opensea message.
User should be sent to the collection page in Opensea
https://testnets.opensea.io/collection/givers-test-collection

![Screenshot 2023-02-20 at 13 25 47](https://user-images.githubusercontent.com/34634436/220108107-442cd700-790d-4ac9-b672-42bce25d6c3c.png)

**Screenshots**

**This happens on which Boosting Section?**
- [ ] Overview page
- [ ] Overview page | verifying the eligibility
- [X] Minter Page
- [ ]  Success Page
- [ ] Docs
- [ ] Other (like login, broken links, header, footer, language, etc.) 

**Desktop (please complete the following information):**
 - OS: IOS
 - Browser Chrome
 - Version 109.0.5414.119 (Official Build) (x86_64)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MohammadPCh** [comment]
This problem has been fixed.
