### ISSUE TITLE
PFP | Error when trying to mint (a second time) an amount bigger than your max left

### ISSUE THREAD

**Issue by Santigs** [Giveth/giveth-dapps-v2#2215]
**Describe the bug**
After a successful mint of 4 units, I try to mint again, this time a total of 8 which added to the previous 4 would exceed the max value of 10. The minting process moves forward but I finally get an error showing a "view transaction" message with no link

**To Reproduce**
1. Go to the minting page
2. Click on mint, adding a total number below or equal to 10 but exceeding  your left minting capacity
3. See error message

**Expected behavior**
There should be a message indicating you have exceeded your minting capacity, and avoid showing "View transaction" message

**Screenshots**
![Screenshot 2023-02-20 at 13 40 35](https://user-images.githubusercontent.com/34634436/220112171-453c4761-761b-431a-9baf-d008365170b3.png)

**This happens on which Boosting Section?**
- [ ] Overview page
- [ ] Overview page | verifying the eligibility
- [ ] Minter Page
- [ ]  Success Page
- [ ] Docs
- [ ] Other (like login, broken links, header, footer, language, etc.) 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MohammadPCh** [comment]
This problem has been fixed.
