### ISSUE TITLE
Status Id of project is not changed from edit page

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#2216]
**Describe the bug**
Status Id of project is not changed from edit page but it changed from list

**To Reproduce**
1. Go to 'admin bro'
2. Click on 'one project'
3. Scroll down to 'status id'
4. change status from active to deactivate
5. see the status isn't changed

**Comment by mohammadranjbarz** [comment]
![admin bro detail](https://user-images.githubusercontent.com/9850545/220120278-f9db627e-afef-4fbc-8c3e-85af89bd7645.png)

**Comment by CarlosQ96** [comment]
Error was in statusId column (eager:true) flag.

Adminbro maps eager (preloaded values/relations) as a big json and pass it between requests. So when we edit it, he was prioritising the big json value which was the previous statusId, so it returns it back to normal.

I tested by forcing the update on the value by code, but in the next step adminbro returned it back previous.

if you put console logs in the ui components you can see how adminbro maps values as the big json.


PUSHING HOTFIX, no test was broken and the filter works

**Comment by CarlosQ96** [comment]
@maryjaf you can check now its pushed the hotfix. to both staging and prod.

**Comment by maryjaf** [comment]
Thanks @CarlosQ96 I checked on stg and prod and it has been resolved
