### ISSUE TITLE
Contact Us - Terms of Use correction to style

### ISSUE THREAD

**Issue by danelsuga** [Giveth/giveth-dapps-v2#222]
![terms](https://user-images.githubusercontent.com/81351744/158385925-169a10ee-f73e-4dd4-893f-fd2bf995cfcd.png)

I don't think the address is meant to be in a bulletpoint list, no?

**Comment by mateodaza** [comment]
Good eye!

**Comment by NikolaCreatrix** [comment]
Reviewed - FIXED
