### ISSUE TITLE
PFP | Change image on de success page

### ISSUE THREAD

**Issue by Santigs** [Giveth/giveth-dapps-v2#2225]
**Describe the bug**
The image shown in the Contratulations for your mint page should be changed

**To Reproduce**

**Expected behavior**
This is the image we need to show instead of the one appearing now.

![image](https://user-images.githubusercontent.com/34634436/220427900-6885cd10-479c-45a7-9fba-7ad873d2c801.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/34634436/220427611-ac7854f3-fd8c-42dd-91a8-450722f273ee.png)

**This happens on which Boosting Section?**
- [ ] Overview page
- [ ] Overview page | verifying the eligibility
- [ ] Minter Page
- [ ]  Success Page
- [ ] Docs
- [ ] Other (like login, broken links, header, footer, language, etc.) 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MohammadPCh** [comment]
it's based on the Figma:
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/GIVeconomy?node-id=18007-236937&t=ZNmzQPPwfMjVlflF-4
do we have the plan to change it?

**Comment by divine-comedian** [comment]
let's leave this one as is.
