### ISSUE TITLE
PFP | Intro page Copy Changes & Making clickable buttons

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2227]
![image](https://user-images.githubusercontent.com/75490971/220431451-0767df21-a53c-4406-b4ba-5ff0eb388657.png)

- [x] Delete "What else?" (not a useful title, and there is too much text on this page)

![image](https://user-images.githubusercontent.com/75490971/220432319-abb95ba7-01c3-46c4-bf59-6dbf1efef800.png)

- [x] Title change "Get on the "$nice list""
- [x] Subtext slight change: "Anyone who donates 100 or more DAI, USDC or xDAI to the Giveth Project is on our $nice list and eligible for early minting of a Giver. Eligible donations will also earn additional rewards through the $nice token program.
- [x] This should be clickable! "Learn more about $nice."

![image](https://user-images.githubusercontent.com/75490971/220432377-3d207ef6-00a0-4a0d-8fea-79fda417174a.png)

- [x] Title Change: "Unlock special benefits"
- [x] Subtext change: If you hold a Giver, your profile will be emphasized wherever you make an impact on Giveth. You’ll also receive a discount to register a custom .giveth Punk Domain name (e.g. vitalik.giveth)."
- [x] This should be clickable! "Learn more about the benefits."

@divine-comedian - can you have a look at these suggestions? I tried to make things a little shorted & clearer overall.

**Comment by divine-comedian** [comment]
changes made - ready to test
