### ISSUE TITLE
PFP | Check if allow list is on or off to show modal

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#2228]
on the minting page when a connected wallet is not on the allow list we receive an warning modal
https://givpfp.vercel.app/nft/mint

![image](https://user-images.githubusercontent.com/67759413/220439230-d0394b43-25b5-4e78-a4c5-8d845a805813.png)

however when the allow list is set to off we should no longer since this warning since anyone with DAI is now allowed to mint an NFT

specifically this variable here in the contract - `allowListOnly`
https://goerli.etherscan.io/address/0x9f8c0e0353234f6f644fc7af84ac006f02cece77#readContract#F2

when it returns `true` we should show the warning - when it returns `false` we should not show the warning

**Comment by MohammadPCh** [comment]
@divine-comedian could you please check it again?

**Comment by divine-comedian** [comment]
testing it out on multiple non allow list accounts and I also tested turning the allow list back on to see if the modal returned and then turned it back off and then the modal no longer pop-ups

everything works as expected! moving this to DONE
