### ISSUE TITLE
PFP | Pages do not scroll down on Firefox Browser

### ISSUE THREAD

**Issue by Santigs** [Giveth/giveth-dapps-v2#2234]
**Describe the bug**
The functionality works fine but none of the three pages scroll down; landing, minting, and success.
I managed to mint working with the browser zoom out in the settings.
I tried other pages as giveth.io to check if it was my computer but it worked fine in the other pages and I was able to scroll down the page.

**Screenshots**
![Screenshot 2023-02-22 at 10 22 02](https://user-images.githubusercontent.com/34634436/220577916-b4956be5-54e9-41c7-ab95-14676254673b.png)
![Screenshot 2023-02-22 at 10 21 49](https://user-images.githubusercontent.com/34634436/220577923-47c02cb8-f429-46ab-9266-37234b91be54.png)

**This happens on which Boosting Section?**
- [X] Overview page
- [ ] Overview page | verifying the eligibility
- [X] Minter Page
- [X]  Success Page
- [ ] Docs
- [ ] Other (like login, broken links, header, footer, language, etc.) 

**Desktop (please complete the following information):**
 - OS: IOS
 - Browser Firefox
 - Version 110.00 (64bit)

**Comment by MohammadPCh** [comment]
@alireza-sharifpour can you take look?
