### ISSUE TITLE
Giveth Homepage Copy Fixes

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-dapps-v2#2243]
Can we make a few updates to the homepage before we go live?

- make "regenerative funding opportunities" be in **bold**

- remove "WAGMI + 2 emojis"

- video section: change the tagline from "What people say about the Giveth and why they love it" to: 

What is Giveth?
Hear from us how the platform works and why we love it!

- use this video for launch: https://www.youtube.com/watch?v=-JXwwIGJGQQ

**Comment by c0ric0ri** [comment]
@MoeNick per our meeting today.
@mosaeedi FYI
@laurenluz do we have this video of Griff without the Giveth background added to it? I think for the homepage it would make more sense to just have the clip of him, since we will have text next to it.

**Comment by laurenluz** [comment]
@c0ric0ri - we do... but it had "zoom" in the corner and looked kind of hacky. That's why Ahmad made it like this.

cc @ahmadabugosh related #2015
