### ISSUE TITLE
GIVpower | glitchy scroll bug on the "increase your rewads" modal

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2246]
When I try to "increase my reward" on GIVpower staking (lock up my GIV tokens), I get this modal:
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/2514fb27-4125-42d3-b34c-34de2e365e7e)

There is a weird bug happening that skips to the top of the modal really fast after I scroll to the bottom... so I can't see the bottom of the modal for long. verrry annoying....

Can we please make a hot fix?

@MoeNick - who is best to take this? @MohammadPCh

**Comment by MohammadPCh** [comment]
Yes, Leave it to me :smile:

**Comment by MohammadPCh** [comment]
It's on the Production now.

**Comment by MohammadPCh** [comment]
This problem should be solved in the new version that has been released. So I move it to the test column.
