### ISSUE TITLE
Scroll issue on Stream page

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapps-v2#2247]
**Describe the bug**
Giveconomy stream page scroll doesn't work after closing the Harvest Modal
**To Reproduce**
1. Go to stream page [`/givstream`](https://giveth.io/givstream)
2. Click on the `Harvest` button and open the Harvest Modal
3. Close the Harvest Modal
4. See error as you cannot scroll

**Expected behavior**
Can scroll after closing the Harvest Modal

**Screenshots**
<img width="1146" alt="image" src="https://user-images.githubusercontent.com/5684607/220905870-8b390984-45d0-4d33-8b7e-282e988da488.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox
 - Version 109.0.1 (64-bit)

**Comment by MohammadPCh** [comment]
@aminlatifi Thanks for reporting. I have fixed this issue and it will resolve on the new release.

**Comment by MohammadPCh** [comment]
@aminlatifi  This issue should be resolved in the new version that has been released. Could you please check it again on production?

**Comment by aminlatifi** [comment]
Thanks @MohammadPCh
