### ISSUE TITLE
Tiny inconsistencies in Partnerships

### ISSUE THREAD

**Issue by danelsuga** [Giveth/giveth-dapps-v2#225]
No screenshot.

All partner slogans should have periods for consistency even if they are not full sentences. The only two that don't are 1hive and Alibre. If these are genuine slogans, it's OK if some have capitalized their words and some have not. However, if Giveth has done this, there should be consistency, and no words but the first should be capitalized. (Also note for future reference: prepositions and articles (a, an, the) are never capitalized unless the first word in the phrase.)

Also, Rainbow Rolls accidentally has an exclamation and a period. You can remove the period! :)

**Comment by NikolaCreatrix** [comment]
Reviewed - issue fixed
