### ISSUE TITLE
Adding new newsletter provider

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#2263]
1) For the homepage, could we add this iframe? I'm not sure how it will look, but this is the one that they recommend to add:

`<iframe src="https://paragraph.xyz/@giveth/embed" width="480" height="480" style="border:1px solid #EEE; background:white;" frameborder="0" scrolling="no"></iframe>`

You can also check their docs https://docs.paragraph.xyz/docs/development

2) For the /join page, can you add the iframe or this link? https://paragraph.xyz/@giveth/subscribe

_Originally posted by @ahmadabugosh in https://github.com/Giveth/giveth-planning/issues/1094#issuecomment-1368770839_

**Comment by MohammadPCh** [comment]
Hmmm It Looks like this:
![image](https://user-images.githubusercontent.com/17097576/221420479-4090db0e-83d8-49e7-a8d8-6ee25a2c7ebb.png)
We need @mosaeedi :heart:  here.

**Comment by MoeNick** [comment]
As @mosaeedi suggested we decided to remove subscribe and think about adding a link to the newsletter later.

**Comment by mosaeedi** [comment]
It doesn't look good, and it's not the same style as the rest of the homepage, for now, please hide the newsletter section and let's find a better solution ASAP.

**Comment by ahmadabugosh** [comment]
@MoeNick @mosaeedi @MohammadPCh Can we just add a button for people that opens in a new tab for them to subscribe? https://paragraph.xyz/@giveth/subscribe

**Comment by MoeNick** [comment]
@mosaeedi is working on it, maybe with a modal.

**Comment by mosaeedi** [comment]
# Design resource
## Newsletter section

![Screenshot 2023-02-28 at 3.15.08 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/031a1612-361f-4dbc-af75-d256247300c0)

### (>1280 & <1439)
[Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=20714%3A283507&t=gd5S1Nfqg0kilgTO-4)

### (>1024  & <1279)
[Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=20714%3A283555&t=gd5S1Nfqg0kilgTO-4)

### (>768  & <1024)
[Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=20714%3A283603&t=gd5S1Nfqg0kilgTO-4)


### (Mobile)
[Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=20714%3A283653&t=gd5S1Nfqg0kilgTO-4)
---

## Newsletter modal
[Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=20714%3A283454&t=gd5S1Nfqg0kilgTO-4)


![Screenshot 2023-02-28 at 3.15.24 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/3ce9bd32-4597-4801-a0c2-8ac21e96e98b)

**Comment by mosaeedi** [comment]
The design resources are added. 
@MohammadPCh @MoeNick

**Comment by MohammadPCh** [comment]
@RamRamez Can you take it?

**Comment by RamRamez** [comment]
> @RamRamez Can you take it?

Yes, no problem.
I'm currently busy with adding the Polygon chain. After that, I'll start this one.

**Comment by ahmadabugosh** [comment]
hey @MoeNick @RamRamez, 

1) @mosaeedi I left a comment on the Figma for the copy of that component. Can you change it please? 

2)  Can we also add a section for the Newsletter on this page: https://giveth.io/join

**Comment by RamRamez** [comment]
I moved this issue to design backlog.

**Comment by MoeNick** [comment]
@maryjaf pls check

**Comment by maryjaf** [comment]
Shouldn't email address validation be checked? @RamRamez 
For example, I can subscribe this email: maryjaf70@gmail.co

**Comment by maryjaf** [comment]
When I tap on disconnect I see the below pic, it seems isn't ok
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/9b49bdfa-ca89-4842-b2b2-6a6050e6fc3a)
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/41864430-a36f-4bf9-a6e0-b5222048bd72)
