### ISSUE TITLE
Homepage Copy hot fix: "What is Giveth"?

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2264]
The copy in this block doesn't make sense with the current video.

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/90f38507-d895-4d15-84b7-703b2fab2c15)

Change subtext to: 
"Discover what makes Giveth different from other donation platforms"

@RamRamez @MohammadPCh @mateodaza - who can take it quick? :)

cc @MoeNick

**Comment by MohammadPCh** [comment]
leave it to me :)
