### ISSUE TITLE
Homepage hot fixes: What's up on Giveth? (a few issues)

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2265]
- [x] Impact quest image is cut off... it's not showing the bottom of the image - it needs to be resized because it looks weird.
right now on giveth.io:
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/430f36ee-7dda-4787-8982-7f841e4270dd)
full image: https://imgflip.com/i/7bxm3l

- [x] Copy in "impact @ Denver" is weak and feels redundant w/ the 1st slide. Copy chage:
Title: "Find the Giveth Team @ ETHDenver"
Subext: "From impact quests to hackathon mentorship to presentations, the Giveth team will be in full force in Denver."

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/1b46dd30-a13e-4194-901a-afc757377c6e)

- [x] Copy in "Help Tukey & Syria" is weak. Copy fix:
Title "Disaster relief in Turkey & Syria"
Subtext: "Explore Giveth projects who are raising funds to support those affected by this devastating earthquake."

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/7a88f195-dc16-4434-86d3-4fb5c85b0e60)

Also... @MoeNick @mosaeedi  - do they have to all say "Explore" as the CTA? I don't like it. In the future, it would be better to have a unique CTA for each one, so it can be more relevant.... maybe we can set that in admin bro as well?

Who can take this issue on? @RamRamez @MohammadPCh @alireza-sharifpour @mateodaza

**Comment by MoeNick** [comment]
1- The pictures should follow the dimentions in the block, so resizing wont solve the problem, we need to ask @mosaeedi or @rodricastillo9013 to provide some illustrations for it. 

2- Tites in campaign are the same, at least for now. 
so ""impact @ Denver"
comes here 
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/2b9437ed-e480-4683-986c-02788a5fb65f)

And here:
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/40f0fca8-5ac5-4826-8e89-ea64399e9fdf)

We can remove one of them if you want. 

3- I edited Turkey campaign data in Admin and it's fixed now.

**Comment by MoeNick** [comment]
for #1 we gonna use eth Denver picture, I updated the admin. 
for #2 we decided to remove it in what's up on Giveth block
