### ISSUE TITLE
Homepage copy hot fix: remove "WAGMI" text

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2267]
Let's remove the title completely so it doesn't have "WAGMI" & the emojis

cc @c0ric0ri @MoeNick 

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/4a41f28a-bc0c-4a46-b441-dd75a7206342)

**Comment by MoeNick** [comment]
The question is why we changed the original design, and then after implementation, we decided to remove it. 

Is it because of the implemented look on the web or a decision-making process?

**Comment by laurenluz** [comment]
Sorry @MoeNick - it's because we don't have a clear flow of approvals. It had a different title before, then needed a change. Griff suggested this, Mo put it in, I was fine w/ it. Then Cori later say it and really didn't like it and asked to remove it.

It was basically because the copy decided broke up the professionalism of the page, and used unapproachable jargon.

Sometimes in comms, these decisions come in a sort of chaotic way 😕
