### ISSUE TITLE
changing quill rich text editor

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#2269]
> Hey @RamRamez
> 
> He says that he created the project with the project description formatting w/ rich text.
> 
> And then later came back to change the project's banner picture... clicked "save"... and then the project description's formatting got all message up - removing all the formatting and having it show up just as a single block of text.
> 
> Make sense?

I got it thanks, Lauren. It's another issue related to Quill rich text editor.

_Originally posted by @RamRamez in https://github.com/Giveth/giveth-dapps-v2/issues/2073#issuecomment-1428323122_

**Comment by RamRamez** [comment]
I investigated more than 10 rich text editor libraries. One of the best is [Slate](https://docs.slatejs.org/libraries/slate-react) but uses JSON format as input and output. The previous component (Quill) uses HTML format. So we need to convert HTML to JSON and vice versa which complicates it.
I'm still working on it to find better solutions.

**Comment by RamRamez** [comment]
TinyMCE, Editor.js, and Draft.js are other options

**Comment by RamRamez** [comment]
I talked with @MohammadPCh and he told me Quill issues had been resolved.

There were some Quill style issues that I fixed in PR #2292 

So, we can close this.
