### ISSUE TITLE
Frontend: Add Polygon network

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#2271]
- adding recipient address in Create Project Page,
- switch the network in the header, @mosaeedi
- supported network error in the donation page
- unsupported network on GIVeconomy!

**Comment by mosaeedi** [comment]
# Design resource

1. user can tap on the **Switch network** and open the switch network modal

### How it looks on the Desktop
[Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=20714%3A268639&t=gd5S1Nfqg0kilgTO-4)

### And Small tablets
[Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=20714%3A267784&t=gd5S1Nfqg0kilgTO-4)


### Mobile version
[Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=20714%3A268060&t=gd5S1Nfqg0kilgTO-4)


## A tiny update for the wallet/user dropdown
1. The network icon is added 
2. the font size is changed to **Body/caption-medium**

[Figma link to review the wallet/user dropdown
](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=20714%3A268489&t=gd5S1Nfqg0kilgTO-4)

<img width="261" alt="Screenshot 2023-02-28 at 2 23 06 PM" src="https://user-images.githubusercontent.com/13708322/221833276-99cd27a9-f5d4-4c42-8bef-dd22626ec34a.png">

**Comment by mosaeedi** [comment]
@MoeNick design resources are added.

**Comment by RamRamez** [comment]
@MoeNick 
Should I add Polygon chain to the Manage funds section in the verification steps?

**Comment by MoeNick** [comment]
Yes please but only on its feature branch to test.

**Comment by RamRamez** [comment]
> * adding recipient address in Create Project Page,
> * switch the network in the header, @mosaeedi
> * supported network error in the donation page
> * unsupported network on GIVeconomy!

PR #2296 
- add polygon network params
- add polygon to create project page
- add polygon chain native token (Matic) balance to donate page
- add polygon chain to donate modal to fetch polygon token prices
- add polygon logo and name to donate page wrong network modal
- add polygon chain to metamask add network function
- add polygon chain logo
- add polygon chain to project recipient addresses in single project page
- add switch network modal to menu
- add polygon chain to the Manage funds section in the verification steps
