### ISSUE TITLE
Can't sign in with new menu

### ISSUE THREAD

**Issue by RamRamez** [Giveth/giveth-dapps-v2#2279]
> Hi, I want to connect/sign in to post a project update. My wallet is connected, but the screen  with the sign in button to click shows up really briefly and than disappears. So I can not sign in. Is there some sort of bug crept in at the moment?

[Ref](https://discord.com/channels/679428761438912522/835168432520429578/1079874711548350597)

**Comment by maryjaf** [comment]
Thanks @RamRamez it has been resolved
