### ISSUE TITLE
ETHDenver landing page quick fixes

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-dapps-v2#2288]
Hey @MoeNick we need to make a couple of quick small changes to the ETHDenver landing page: 

1)  Can you add this event for "Public Goods Pizza Party" under the GIVtalks section:

FRI, MAR 3 AT 5:00 PM

Link for Event: https://www.eventbrite.com/e/public-goods-pizza-party-registration-554833029527

Link to Calendar: https://calendar.google.com/calendar/event?action=TEMPLATE&tmeid=M2EzOGd2NXNmaHNqcTF0amN1YzFmYWNxNTkgZ2l2ZXRoZXRoZGVudmVyQG0&tmsrc=givethethdenver%40gmail.com

2) Can we change the following for the Impact Track Mentorship section

Reach out to us on the ETHDenver Discord server under the "Building" section!

 to 

Reach out to us on the ETHDenver Discord server under the "Partners" section!

**Comment by MohammadPCh** [comment]
Hey @ahmadabugosh , This is the result:
![image](https://user-images.githubusercontent.com/17097576/222035443-be355329-b49c-4771-8b93-8a3225acc380.png)
![image](https://user-images.githubusercontent.com/17097576/222035621-32c238c2-4407-4dab-af1b-89b119601d4c.png)

**Comment by ahmadabugosh** [comment]
Thanks @MohammadPCh !
