### ISSUE TITLE
Front-end: Deactivated projects are allowing donations

### ISSUE THREAD

**Issue by CarlosQ96** [Giveth/giveth-dapps-v2#229]
After talking to @MoeNick Deactivating a project prevents further donations. But this isn't the behaviour I found.
I deactivated Ramin project and it still allowed me to donate.
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/92376054/158477418-be672d74-bf34-42ea-83d0-2f2639cb27da.png">

**Comment by CarlosQ96** [comment]
@mateodaza

**Comment by CarlosQ96** [comment]
This is in the v2 dapp

**Comment by CarlosQ96** [comment]
We should add further protection in the backend, but will need to validate the flow with the frontend team.

**Comment by laurenluz** [comment]
it seems that, when I try to go to a deactivated project's donate page, I just get sent to the homepage. good stuff.

also, when I am trying to look at a deactivated project via its link it says "you do not have permission to view this project". great.
