### ISSUE TITLE
Cancelled projects will not be returned by project by slug query (better error management for this in the front)

### ISSUE THREAD

**Issue by CarlosQ96** [Giveth/giveth-dapps-v2#230]
This is the expected behaviour, only the owner should see it. I am getting this error on the front, it should be handle like drafted projects (not sure if that is implemented already).
<img width="1448" alt="image" src="https://user-images.githubusercontent.com/92376054/158477637-6b97c9be-4166-4ad8-b6a0-fb29bf68a69b.png">

**Comment by CarlosQ96** [comment]
Maybe @RamRamez or @MohammadPCh can take a look at this.

**Comment by CarlosQ96** [comment]
Or @mateodaza

**Comment by MoeNick** [comment]
@mohammadranjbarz changed the error msg, but we have to disable donation button, and edit or verify button also in owner view. 
@mateodaza @pkretzschmar

**Comment by aminlatifi** [comment]
@MoeNick use ram-4th-project project for test

**Comment by laurenluz** [comment]
@CarlosQ96 can you test this one? I don't get it

**Comment by mateodaza** [comment]
Using https://giveth-dapps-v2.vercel.app/project/ram-4th-project works as expected, this is done
