### ISSUE TITLE
when project owner deactivated your project, two notifications are fired

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#2302]
**Describe the bug**
In some cases when project owner deactivated your project, two notification is fired, but when admin bro deactivate one project the project owner received one notification

Our initial guess is that because, for example, my user with this wallet account (0xcd192b61a8Dd586A97592555c1f5709e032F2505)has both an admin user and giveth user , for this reason, I will receive two notifications.

**To Reproduce**
1. Go to 'details of project"
2. Click on 'Deactivated Project'
3. See notification list

**Screenshots**
![image](https://user-images.githubusercontent.com/111529185/223414741-4a7a6d94-6963-48f0-a848-c29b2e508442.png)

**Comment by aminlatifi** [comment]
The same notification is sent twice without trackId
<img width="734" alt="image" src="https://user-images.githubusercontent.com/5684607/224330802-5a6dc67a-eaf3-4ae0-9c52-735b7ab07c37.png">


I am creating a Pr to add a unique track id for this event and many others who lack
