### ISSUE TITLE
Campaign slider fix

### ISSUE THREAD

**Issue by mosaeedi** [Giveth/giveth-dapps-v2#2304]
![Screenshot 2023-03-07 at 4.49.03 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/c3eabcaf-acbe-46d7-a274-747ef04a1330)

The vertical project list should be as wide as the display and not cut in the middle of the screen.

**Comment by maryjaf** [comment]
On which environment can I test? @MohammadPCh 
I checked on this https://giveth-dapps-v2-git-changing-featured-projects-style-givethio.vercel.app/  and the problem still exists

**Comment by maryjaf** [comment]
@mosaeedi approved this and we can move this issue  to done
