### ISSUE TITLE
Project was successfully completed but the notification makes it seem like it was in violation

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#2305]
This is very off-putting as this project has been deactivated and unlisted because it completed its mission successfully and no longer needs funding. This message makes it seem like the project was in violation of something when really its just finished.

![image](https://user-images.githubusercontent.com/74267818/223459698-27ec902b-0619-4f54-b865-249be7227737.png)

**Comment by NikolaCreatrix** [comment]
Yeah, I also noticed.... maybe we need one more simple button that will say - mission complete! (that would just deactivate and archive the project automatically without performing the unlist notification... And the notification center will say something like - "This project has reached its goal and has been deactivated. Let's celebrate the impact you made!"

Is that any possible option?

**Comment by MoeNick** [comment]
I think the copy is not suitable, unlisting means not been searchable or list, its not necessarily related to  listing guidance. 

Completing is another feature,we do not have this concept in Giveth, projects are not time-limited, or fund limited. Lets not mix completing with diactivating. @

**Comment by WhyldWanderer** [comment]
I also received this one today... it means that anytime the project makes an edit or adds an update the user will be notified. It just seems unnecessary to notify the user EVERY time the project becomes relisted after review.. Sometimes this happens multiple times in one day if the project is newer.

Maybe we should consider not sending notifications for listing or unlisting as it is an internal thing...
![image](https://user-images.githubusercontent.com/74267818/224062549-e2e4fb3f-cdd6-48b4-83b9-3e75db59bfda.png)

**Comment by laurenluz** [comment]
ok, from the feedback above, we should:

- [ ] never send notifications *to the project supporters* when a project they supported is listed or unlisted @mohammadranjbarz 
- [ ] hide/remove this section from the notification settings
![image](https://user-images.githubusercontent.com/75490971/226400645-c82456fd-3f55-4c47-8cdf-0e309a27d643.png)

Also - is there somewhere I can see the copy we have for the notifications *to project owners* for when their project is listed/unlisted? Ideally, we can make it simple, so something like:

- [ ] Change copy on notifications to project owner when project gets listed to "Your project < project name > has been listed on the projects page."
- [ ] Change copy on notifications to project owner when project gets unlisted to "Your project < project name > has been unlisted from the projects page."

Is that ok @WhyldWanderer ?

**Comment by WhyldWanderer** [comment]
Looks great to me.. Thanks for this Lauren!

**Comment by divine-comedian** [comment]
@mohammadranjbarz is this clear? can you check this out?

**Comment by MoeNick** [comment]
@mohammadranjbarz can you take the last 2 text changes?

**Comment by mohammadranjbarz** [comment]
@maryjaf 
It's on staging, you can test it now

**Comment by mohammadranjbarz** [comment]
> @maryjaf
> It's on staging, you can test it now

@maryjaf
It's on staging, you can test it now

**Comment by maryjaf** [comment]
> * never send notifications _to the project supporters_ when a project they supported is listed or unlisted @mohammadranjbarz

When a project has been listed/unlisted, the notification is sent for project supporter , should this notification be removed?

Unlist:
my project :
Your project [MAYAMAYATEST](https://staging.giveth.io/project/mayamayatest) has been unlisted from the projects page.
supported projects:
[MAYAMAYATEST](https://staging.giveth.io/project/mayamayatest) did not meet our [guidelines for listed projects](https://docs.giveth.io/dapps/listedUnlisted/#listed-projects) and has been hidden from the projects page.

List:
my project :
Your project [MAYAMAYATEST](https://staging.giveth.io/project/mayamayatest) has been listed on the projects page.

supported projects:
[MAYAMAYATEST](https://staging.giveth.io/project/mayamayatest) is now listed on the Giveth projects page.

**Comment by mohammadranjbarz** [comment]
> > * never send notifications _to the project supporters_ when a project they supported is listed or unlisted @mohammadranjbarz
> 
> When a project has been listed/unlisted, the notification is sent for project supporter , should this notification be removed? @MoeNick @mohammadranjbarz
> 
> Unlist: my project : Your project [MAYAMAYATEST](https://staging.giveth.io/project/mayamayatest) has been unlisted from the projects page. supported projects: [MAYAMAYATEST](https://staging.giveth.io/project/mayamayatest) did not meet our [guidelines for listed projects](https://docs.giveth.io/dapps/listedUnlisted/#listed-projects) and has been hidden from the projects page.
> 
> List: my project : Your project [MAYAMAYATEST](https://staging.giveth.io/project/mayamayatest) has been listed on the projects page.
> 
> supported projects: [MAYAMAYATEST](https://staging.giveth.io/project/mayamayatest) is now listed on the Giveth projects page.

@MoeNick  mentioned for this step we just need to implement those two change copy items in list of tasks
https://github.com/Giveth/giveth-dapps-v2/issues/2305#issuecomment-1686468939

**Comment by divine-comedian** [comment]
Yes the other two items imply more effort - we can deal with them later
