### ISSUE TITLE
Many notifications for a single project update

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#2318]
OS: Ubuntu 22.04 
Brave browser
https://giveth.io

On production I went to check my notifications and this single update from a project created ~10 notifications. If we visit the project we can see only 1 update was published. https://giveth.io/project/creating-the-perfect-villages-in-burundi

As a user I should only get a single notification for a single update.

![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/d6493cb8-d52a-46cc-bb07-d26554ae18db)

**Comment by aminlatifi** [comment]
@divine-comedian What's your wallet address?

**Comment by divine-comedian** [comment]
> @aminlatifi 

0x826976d7C600d45FB8287CA1d7c76FC8eb732030

**Comment by aminlatifi** [comment]
@divine-comedian I looked at the notification records, they have the same data and were made at almost the same time. So, it shows the production impact-graph service has sent one notification multiple times. We have solved a similar issue by this https://github.com/Giveth/impact-graph/pull/899. So, probably this issue would be considered solved.
