### ISSUE TITLE
Allow PFP Holders to set them as their Giveth dapp profile picture

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#2319]
Following the promised benefits for holders of the Giver's PFP We should define how users will have cosmetic benefits on the dapp. 

The primary ideas were:

Comestic benefits around user names where users show up on dapp (Donations, GIVpower, project owner...)

Allow users to put their purchased PFP art as their profile picture on the Giveth dapp.

**Comment by divine-comedian** [comment]
Feature 1:

![image](https://user-images.githubusercontent.com/67759413/226373344-ef59122a-5276-401e-88d2-d67fffe045e9.png)

Allow users to put their Giveth PFP as their profile picture inside of the dapp.

I think we're missing a few designs @Tosinolawale from this page when a user clicks `edit profile` then what are the next modal(s) that show up? 

We'll need to show a view where they can see all of the PFPs they own, how to select the one they want to use and if there is a confirmation button and/or modal to apply it as their PFP

**Comment by divine-comedian** [comment]
@MoeNick according to the convo with @MohammadPCh we may need some back-end help, is anyone able to work on it?

particularly to save pfp image data (via IPFS) to a user's profile once they select it

**Comment by Tosinolawale** [comment]
Here is the Figma link to this project. 
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/GIVeconomy?node-id=21303%3A197903&t=WWtZPGB9txZXKe78-1

![uploading file](https://user-images.githubusercontent.com/35389241/226740326-3a119425-770e-4c3f-8372-9002df59df2e.png)
When Onboarding new users, users can either upload generic image as profile pictures or click on a link to the Minter page, Mint a Giveth’s PFP and subsequently upload.

![Edit profile](https://user-images.githubusercontent.com/35389241/226740447-ca2fcbc8-ea1a-4d81-9605-514c48aef14b.png)
When Users click on Edit Profile, with the intention of changing or uploading a new picture

![Edit profile-1](https://user-images.githubusercontent.com/35389241/226740830-a5285911-ca9b-4689-bb62-cbcd3252d440.png)
![Edit profile-2](https://user-images.githubusercontent.com/35389241/226740834-1bdb35bf-8d2f-4817-b7da-c0ea3c1f7cc5.png)
![Edit profile-3](https://user-images.githubusercontent.com/35389241/226740838-bf9308ec-2c7c-47cc-ba13-3941202eb8c9.png)
![Edit profile-4](https://user-images.githubusercontent.com/35389241/226740846-d573c61e-28f1-4c7d-84aa-30922a97975d.png)
![Edit profile](https://user-images.githubusercontent.com/35389241/226740849-62b796dd-1846-4c68-9546-ab899014abf0.png)
Users can upload a generic image which is constrained to only reflecting on the wallet connection modal 

![Empty](https://user-images.githubusercontent.com/35389241/226741012-467af052-a3f1-4205-a880-653b5f2e3b6d.png)
![Group 1000001215](https://user-images.githubusercontent.com/35389241/226741778-5810bd3b-b108-47a9-a046-50eb5d4647b0.png)
PFP is incorporated and can be changed from user account. Users can also upload a Giveth’s NFT (Only) which reflects with the  user names everywhere they come up on the platform including the wallet connection modal 

![Public view-1](https://user-images.githubusercontent.com/35389241/226741175-6a3ab5cd-e6dd-4ff9-aa7f-2348d378a4e6.png)
![Public view](https://user-images.githubusercontent.com/35389241/226741180-59f3436e-755c-4359-a68e-0451ee667852.png)
PFP is incorporated and its seen beside donor’s name on donation table. Same thing with GIVpower allocation table.
Shadow is deployed on hover with visible tool tip showing metadata of unique NFT. Image is clickable opening with an external link to NFT details on OpenSea

![Header](https://user-images.githubusercontent.com/35389241/226742042-1ef63328-a48b-4561-8d5a-0e3623bf8c9e.png)
PFP is incorporated and its seen beside project’s owner page on project detail page

![Hover](https://user-images.githubusercontent.com/35389241/226743060-73c07849-e2e9-4ae4-85f5-86072437b292.png)
PFP is incorporated and its seen beside user’s name on project card

![Overview V2](https://user-images.githubusercontent.com/35389241/226743154-3d83157d-73f0-4d7d-9645-2de4633b7b4f.png)
Users can interact with the CTA here, which links to the collection display modal and select their newly minted NFT as profile picture

**Comment by Tosinolawale** [comment]
@divine-comedian @MoeNick @mosaeedi

**Comment by MohammadPCh** [comment]
@divine-comedian Should we control the PFP owner? I mean we should consider the situation in which the user sells his PFP after setting it to the DApp's profile

**Comment by divine-comedian** [comment]
> @divine-comedian Should we control the PFP owner? I mean we should consider the situation in which the user sells his PFP after setting it to the DApp's profile

We could.. I don't think it will be a big issue, I don't expect many users to transfer them away, at least at the beginning - however it wouldn't be very hard - let's talk about it on our next call - I don't think this case is a blocker to begin though.

**Comment by divine-comedian** [comment]
@Tosinolawale one more CTA if we can add is for them to register their Giveth Domain Name

Givers holders get a 50% discount on registering their name (Gnosis Chain)

Here's the URL 
https://giveth.punk.domains/#/

**Comment by divine-comedian** [comment]
@alireza-sharifpour we should implement a horizontal scroll instead of vertical - the user is not able to see the relevant metadata at the bottom 

OR 

fix some elements outside of the scroll - such as the metadata display and the `SAVE` button

https://user-images.githubusercontent.com/67759413/230453442-315677ee-97b3-4b03-ade0-43db19a8fd4e.mp4

**Comment by alireza-sharifpour** [comment]
> @alireza-sharifpour we should implement a horizontal scroll instead of vertical - the user is not able to see the relevant metadata at the bottom
> 
> OR
> 
> fix some elements outside of the scroll - such as the metadata display and the `SAVE` button

I implemented the first solution, @divine-comedian please check it here: https://givpfp.vercel.app/ and if we need to also implement the second thing, let me know.

**Comment by divine-comedian** [comment]
It looks like on first load that the SAVE and CANCEL buttons do not appear properly - only when I resize the screen do the buttons go down to the appropriate space. There also appears to be a bug that adds `456` to the # of the PFP and on the top header as well.


https://user-images.githubusercontent.com/67759413/231484615-3f960a8a-744b-460f-90e2-15bf1f70f186.mp4

![image](https://user-images.githubusercontent.com/67759413/231486865-53db5f47-c320-4412-a943-4adabf900fbc.png)


I would also recommend we fix the sizing and styling of the modal - ideally the user does not need to scroll down at all to see all of the information on most laptop screens - we could try increasing the width of the modal and set the grid for traits to 2 rows on large screens

**Comment by alireza-sharifpour** [comment]
> It looks like on first load that the SAVE and CANCEL buttons do not appear properly - only when I resize the screen do the buttons go down to the appropriate space. There also appears to be a bug that adds `456` to the # of the PFP and on the top header as well.
> 
> ![image](https://user-images.githubusercontent.com/67759413/231486865-53db5f47-c320-4412-a943-4adabf900fbc.png)
> 
> I would also recommend we fix the sizing and styling of the modal - ideally the user does not need to scroll down at all to see all of the information on most laptop screens - we could try increasing the width of the modal and set the grid for traits to 2 rows on large screens

I removed the 456! and also increased the width of the modal to have 5 attribute items in a row, can you check it @divine-comedian ?

**Comment by divine-comedian** [comment]
I think this is a lot better - my only wish is that these buttons `save` and `cancel` don't get hidden by the scroll - is it possible to make them fixed?

![image](https://user-images.githubusercontent.com/67759413/232505161-780a99cc-6b7a-4aa6-a4f7-9e9fafed5931.png)

**Comment by divine-comedian** [comment]
- [ ] Need to add padding above the save button
![Screenshot from 2023-04-18 09-07-59](https://user-images.githubusercontent.com/67759413/232821337-29e1e84e-284a-4d0e-8b8d-48ff2db5cefb.png)

- [ ] On mobile the save and cancel button are cut off and are not shown
![image](https://user-images.githubusercontent.com/67759413/232821254-082eef07-38ed-4567-85d7-ebbbc77e8271.png)

**Comment by alireza-sharifpour** [comment]
> @alireza-sharifpour
> 
> * [ ]  Need to add padding above the save button
>   ![Screenshot from 2023-04-18 09-07-59](https://user-images.githubusercontent.com/67759413/232821337-29e1e84e-284a-4d0e-8b8d-48ff2db5cefb.png)
> * [ ]  On mobile the save and cancel button are cut off and are not shown
>   ![image](https://user-images.githubusercontent.com/67759413/232821254-082eef07-38ed-4567-85d7-ebbbc77e8271.png)

Both of them are fixed now!

**Comment by divine-comedian** [comment]
Great! I also tested on the onboarding flow and the changes look fine

![image](https://user-images.githubusercontent.com/67759413/232835529-4f6274e4-54cc-4879-84c5-531002d55690.png)


And on mobile view the save button is now showing appropriately! Looks good

@alireza-sharifpour please notify here when this has been merged to the main feature branch

**Comment by maryjaf** [comment]
@alireza-sharifpour plz check this
[Uploading... image.png]![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/1aa9a6de-7cfb-417c-a8ca-7fd5a5ef5a26)

**Comment by maryjaf** [comment]
We have a problem is showing "Max Mint Amount" , my wallet holds 3 Givers NFTs but max min amount is shown 10 
@alireza-sharifpour 
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/e8b4f921-680e-4be5-bd5d-292baff42089)

**Comment by alireza-sharifpour** [comment]
> We have a problem is showing "Max Mint Amount" , my wallet holds 3 Givers NFTs but max min amount is shown 10 @alireza-sharifpour ![image.png](https://camo.githubusercontent.com/fbddd8a90fa0f87cf5e44e338bc1325e53eaeff069f111d267ab6a64639a8932/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f65386234663932312d363830652d346265352d626435642d323932626166663432303839)

I'll fix it and let you know

**Comment by divine-comedian** [comment]
> > We have a problem is showing "Max Mint Amount" , my wallet holds 3 Givers NFTs but max min amount is shown 10 @alireza-sharifpour ![image.png](https://camo.githubusercontent.com/fbddd8a90fa0f87cf5e44e338bc1325e53eaeff069f111d267ab6a64639a8932/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f65386234663932312d363830652d346265352d626435642d323932626166663432303839)
> 
> I'll fix it and let you know

Hold up @maryjaf @alireza-sharifpour - the 10 is meant to clarify the max amount of PFPs you can hold in your wallet at a given time - maybe we only need to change the text?

**Comment by maryjaf** [comment]
> > > We have a problem is showing "Max Mint Amount" , my wallet holds 3 Givers NFTs but max min amount is shown 10 @alireza-sharifpour ![image.png](https://camo.githubusercontent.com/fbddd8a90fa0f87cf5e44e338bc1325e53eaeff069f111d267ab6a64639a8932/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f65386234663932312d363830652d346265352d626435642d323932626166663432303839)
> > 
> > 
> > I'll fix it and let you know
> 
> Hold up @maryjaf @alireza-sharifpour - the 10 is meant to clarify the max amount of PFPs you can hold in your wallet at a given time - maybe we only need to change the text?

Yeah, Maybe it is better to separate the total allowed Mint amount and the allowed Mint for each user
Now, by selecting "Max", the allowed Mint of my users will be set in the box.
 It is a UX issue, Is the current implementation OK or should it be changed?

**Comment by MoeNick** [comment]
I suggest a copy of  "Max Mint Amount Left"

**Comment by divine-comedian** [comment]
> > > > We have a problem is showing "Max Mint Amount" , my wallet holds 3 Givers NFTs but max min amount is shown 10 @alireza-sharifpour ![image.png](https://camo.githubusercontent.com/fbddd8a90fa0f87cf5e44e338bc1325e53eaeff069f111d267ab6a64639a8932/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f65386234663932312d363830652d346265352d626435642d323932626166663432303839)
> > > 
> > > 
> > > I'll fix it and let you know
> > 
> > 
> > Hold up @maryjaf @alireza-sharifpour - the 10 is meant to clarify the max amount of PFPs you can hold in your wallet at a given time - maybe we only need to change the text?
> 
> Yeah, Maybe it is better to separate the total allowed Mint amount and the allowed Mint for each user Now, by selecting "Max", the allowed Mint of my users will be set in the box. It is a UX issue, Is the current implementation OK or should it be changed?

Let me just adjust the text instead of changing the logic

**Comment by divine-comedian** [comment]
I fixed up the logic a bit so I now show the max they can mint based on their balance. I also fixed an edge case where a user could have a balance greater than the max that would show a negative amount for Max Mint Amount 

![image](https://user-images.githubusercontent.com/67759413/233450785-95ed38a3-d32f-4379-8459-e76e98cd1f2d.png)

**Comment by maryjaf** [comment]
When I select edit and change the profile picture, I must refresh to change the display photo in the profile
But the photo displayed in the menu or modal edit was displayed correctly at the same time @alireza-sharifpour @MohammadPCh 
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/1f604f80-f9d6-42bd-9bfa-140e3eb5405d)
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/780cb710-8788-4b85-ba0a-1f830c2f2441)

**Comment by maryjaf** [comment]
> When I select edit and change the profile picture, I must refresh to change the display photo in the profile But the photo displayed in the menu or modal edit was displayed correctly at the same time @alireza-sharifpour @MohammadPCh ![image.png](https://camo.githubusercontent.com/b6b7931297b16fe014e6e5fa9a73c3bd7d1a2faf356b38f8110e4ec0b214c906/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f31663630346638302d663964362d343262642d396266612d313430653365623534303564) ![image.png](https://camo.githubusercontent.com/61e3d56e11c68218bbc3dbe38f018035afa9a1582a0875888f3c8168c6af6d7c/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f37383063623731302d383738382d346238352d626130612d316638333063326632343431)

Thanks @MohammadPCh this problem has been resolved.

**Comment by maryjaf** [comment]
> I fixed up the logic a bit so I now show the max they can mint based on their balance. I also fixed an edge case where a user could have a balance greater than the max that would show a negative amount for Max Mint Amount
> 
> ![image](https://user-images.githubusercontent.com/67759413/233450785-95ed38a3-d32f-4379-8459-e76e98cd1f2d.png)

Thanks @divine-comedian I checked and it passed
