### ISSUE TITLE
Sigle Project Page: Prevent public view to be shown, if the wallet is locked or the user is not signed-in

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#232]
As a user, I still can see the "owner view" instead of the "public view" of the single project page. 

![image](https://user-images.githubusercontent.com/80677512/158549134-d9dc0db9-ef18-4de7-8c4b-6d954301b3de.png)

It was reported here if regular user testing: https://github.com/Giveth/giveth-next/issues/682

**Acceptance Criteria:**
If I sign-out OR lock my wallet, I should see the only public view with DOnate button.

**Comment by NikolaCreatrix** [comment]
Tested with chrome on giveth.io

When I sign out while looking at my own project, it doesn't trigger page reload, so I can still see the options 'edit' or 'publish'. But when I click on one of them, it triggers 'sign wallet' window and if I don't sign back in page says.... (prentscreen)

![image](https://user-images.githubusercontent.com/100084867/159815752-09a1b137-ad48-4476-b428-280f48585e83.png)


'Public view' nor project page doesn't appear after sign out.

**Comment by laurenluz** [comment]
it's working for me
![image](https://user-images.githubusercontent.com/75490971/159969457-09ce73a9-a789-42e5-a900-a3a02c27c103.png)
