### ISSUE TITLE
Chainvine | USD rewards amount is probably going to be confusing...

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2322]
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/48949913-6361-456f-9d00-f4c86d244768)

Are rewards supposed to show up here as some USD value in Chainvine? OR can this be hidden from their UI?

@CarlosQ96 @ahmadabugosh

**Comment by laurenluz** [comment]
Imo - we should at the minimum, hide if from their UI.

Better would be if we can say "Your rewards (GIV)" and actually show the amount of GIV that they are getting via GIVbacks from this program. And add a link that sends them to claim on the GIVbacks page.

cc @MoeNick

**Comment by MoeNick** [comment]
@ahmadabugosh @CarlosQ96 
I don't have contact with 'em, wdyt?

**Comment by ahmadabugosh** [comment]
I'm solving this already in this issue: https://github.com/Giveth/giveth-planning/issues/1264

**Comment by ahmadabugosh** [comment]
Feel free to close this one @MoeNick
