### ISSUE TITLE
Fiat | Mt Pelerin Ramp page copy fixes

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2324]
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/0c00a7a4-1e14-4c0e-9176-2465f17a3ca5)

Looking at this page: https://fiat-38.vercel.app/purchase-xdai

- [x] Banner Title: "Get Crypto with Mt Pelerin"
- [x] Banner subtext: "Use a bank transfer or credit card to purchase crypto and deposit it directly into your web3 wallet."

Side text:

- [x] Title:  "Crypto made easy"
- [x] Subext: "Thanks to Mt Pelerin, you can "onramp" your dollars and get the crypto you want to donate to projects. There is a 0% fee for onramping funds under $500/year, and they charge a small fee for anything over that.
• Purchase with credit, debit, Visa, or Mastercard
• The funds are sent to your wallet within minutes with zero gas fees
• The service is a KYC-free authorized financial intermediary based in Switzerland"

**Comment by mosaeedi** [comment]
@Tosinolawale Please update the copy on Figma as well.
