### ISSUE TITLE
Fiat | Demo flow Copy Fixes

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2325]
Looking at this page: https://fiat-38.vercel.app/how-to-buy-xdai?slug=test-project-in-production-0

![image](https://user-images.githubusercontent.com/75490971/225003580-4949271f-64fb-463a-8229-72e4672ee69a.png)

- [ ] First, can we add a button that says "Next" on every page but the last one? And a "back" button on every page but the 1st one? It's kind of weird that the user has to click the numbers or arrows in the bottom right. @mosaeedi @mateodaza 

Now... some copy fixes for every page:

Page 1:
- [ ] Title: "Getting Started"
- [ ] Subtext: " The Mt Pelerin "onramp" allows you to use a credit card or bank transfer to get crypto in your web3 wallet to donate. First, select the method of payment (bank transfer or credit card), and then select the currency you want to use to purchase crypto. Then, select the crypto currency you wish to purchase. The currency "xDAI" and network "Gnosis Chain" will be selected by default. Finally, click "Buy". 

Page 2:
- no changes

Page 3:
- [ ] Subtext: "Enter your email address, mark the checkbox "I accept the T&C of Mt Pelerin" and click "Next." "

Page 4:
- [ ] Subtext: " Wait for the confirmation message "Congrats, you're registered", then click "Next". Note: You will have the option to identify yourself if you wish to skip these steps in the future. "

Page 5: 
- [ ]  Subtext: "Connect the wallet to which you would like to receive your crypto."

Page 6:
- [ ] Subtext: "The address of your connected wallet will be auto-filled as the "receiving address", or you can use the drop down menu to select a different address. If your preferred address is not in the drop down, you may need to connect to another wallet. Mt Pelerin will display the chain on which you will receive your funds below. Once the information is all correct, click "Validate this address" and then click "Next". "

Page 7:
- [ ] Title: "Using your Credit Card"
- [ ] Subtext: " If using a credit card to purchase crypto, fill in your card information and then click "Buy". "

Page 8: 
- [ ] Title: "Wait for Confirmation"
- [ ] Subtext: "You can wait on this page until the payment goes through, or you can close it. If the payment is successful, the funds will automatically appear in your chosen wallet after some time. Note: If you click "Close", you will be redirected back to the start and will not get to the next page."

Page 9:
- [ ] Subtext: "Once the payment is approved it will say "Payment successful" and show the transaction information. It may take a some minutes for the crypto to appear in your wallet."

**Comment by MoeNick** [comment]
Thanks @laurenluz , just tagging @Tosinolawale who worked with that design and familiar with it ti be in the loop.
