### ISSUE TITLE
Remove ETHDenver banner from homepage

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#2326]
Can we remove this banner now that ETHdenver is over?

![image](https://user-images.githubusercontent.com/74267818/225035974-efe5c44e-b37b-4c56-8e0d-f13255273ee3.png)

**Comment by WhyldWanderer** [comment]
and this? 
![image](https://user-images.githubusercontent.com/74267818/225038814-785c53c4-81f8-4a1c-8c01-38982cbf4ca4.png)

I would be happy to do this from the Adminbro in the future if someone would give me a demo of how I would go about doing so...

**Comment by laurenluz** [comment]
@MoeNick knows how and can probably give you a demo.

Also - @MoeNick - can you help to assign removing the banner to someone? I'm surprised it's still on there

**Comment by laurenluz** [comment]
@RamRamez or @alireza-sharifpour maybe?

**Comment by MoeNick** [comment]
We are release party now, we will do it today. Blocked by other changes we have on staging. @laurenluz 
( That's why I usually avoid hard-coded banners @mosaeedi  Let's avoid it later, hard for maintaining! )

**Comment by laurenluz** [comment]
gotcha - thank you @MoeNick !
