### ISSUE TITLE
Make default donation token ETH on mainnet & xDAI on Gnosis

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2331]
Right now we have the default token to be GIV on every chain, but tbh, I think this negatively impacts the price of GIV - people donate, projects, sell & it dumps.

I also have the experience that people without GIV see GIV as the default and their gut reaction is "oh, I don't have GIV so I can't donate".

I also notice that most donations are in GIV.

Let's change that so that the default token is the native token of the chain... so:

Mainnet: Default should be ETH
Gnosis Chain: Default should be xDAI

@MoeNick - any objections?

**Comment by MoeNick** [comment]
The order of token is editable in admin, However, I can take this one.

**Comment by MoeNick** [comment]
Done, please approve.

**Comment by laurenluz** [comment]
@MoeNick - can you make it MATIC on Polygon? I checked and it is AAVE as default
![image](https://user-images.githubusercontent.com/75490971/226353288-9dbc5164-2066-4e28-a18a-8ca8db52db2f.png)

Also it should be xDAI on Gnosis Chain
and ETH on Mainnet

Right now it is still GIV on both those chains.

I tested on production.

**Comment by MoeNick** [comment]
@mohammadranjbarz I changed the order in AdminBro but seems its not got affected. Its a front end thing? Can you check pls?

**Comment by MoeNick** [comment]
I made the order of GIV. 2

![image](https://user-images.githubusercontent.com/80677512/226382112-959b84f6-fd20-4291-b6cb-5389e5670476.png)


changes for ETH
![image](https://user-images.githubusercontent.com/80677512/226382285-e3e75640-3441-4cfe-9fd5-286eb163f801.png)


![image](https://user-images.githubusercontent.com/80677512/226382459-89cac940-9f9b-48ae-bd56-4ba6425cf815.png)


I think they did not happen in the list.

**Comment by laurenluz** [comment]
Actually @mohammadranjbarz - I think we should show `GIV` in its place in alphabetical order. We don't need to put it 2nd (and actually, it's better if it is lower down)

**Comment by RamRamez** [comment]
> @RamRamez Can you check it please, it seems everything is fine with admin panel and tokenInfo, maybe there is something happening in frontend:
> 
> We should show native token first in each network, for gnosis and mainent we should show `GIV` token in the second order in list

There's an `order` field in the `getProjectAcceptTokens`.
If there's an order, we put ordered tokens regarding that, but if the order is null, we sort alphabetically.

![image](https://user-images.githubusercontent.com/73441857/226885272-310a75a5-22b9-4c4e-8bd0-392f6ed4007b.png)

**Comment by laurenluz** [comment]
@RamRamez - I think we should put the native token as the default token... and then every other token is sorted alphabetically.
