### ISSUE TITLE
PFP Collection Announcement Design for "What's New"

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2333]
@rodricastillo9013 can you help w/ this? 

@divine-comedian will give you some details :)

We need it hopefullly this week.

**Comment by laurenluz** [comment]
it should be 16*9

**Comment by rodricastillo9013** [comment]
@laurenluz @divine-comedian algun copy para esto?

**Comment by divine-comedian** [comment]
"The Givers PFP Collection"
