### ISSUE TITLE
Decrease the number of decimals

### ISSUE THREAD

**Issue by brichis** [Giveth/giveth-dapps-v2#2344]
**Describe the bug**
Good morning! Griff asked me to create a couple of issues, this is the first one. 
CC. @MoeNick 
![Decimals](https://user-images.githubusercontent.com/106570342/225395942-14bc2f8b-3a52-4673-ae14-32d06c9b7a32.jpg)

**To Reproduce**
1. Go to ['...'](https://giveth.io/project/anka-relief?tab=donations)
2. See error

**Screenshots**
<img width="638" alt="Screenshot 2023-03-15 at 11 40 06" src="https://user-images.githubusercontent.com/106570342/225396301-d3c3e82d-10bb-4b8a-9a98-271c82051fa0.png">

**Desktop (please complete the following information):**
 - OS: iOs
 - Browser: Brave
 - Version: 1.49.120

**Comment by MoeNick** [comment]
@alireza-sharifpour jan
this is a quick fix we missed it, can you take it?

**Comment by RamRamez** [comment]
This issue is fixed on our last release
