### ISSUE TITLE
amount column should be wider

### ISSUE THREAD

**Issue by brichis** [Giveth/giveth-dapps-v2#2345]
**Describe the bug**
Good morning! Griff asked me to create a couple of issues, this is the second one.
CC. @MoeNick 

The amount column should be wider and no scroll
<img width="848" alt="Screenshot 2023-03-15 at 11 50 37" src="https://user-images.githubusercontent.com/106570342/225399030-72e2516e-7de3-4161-a8ea-56d5e83e88f6.png">
https://giveth.io/project/anka-relief?tab=donations

**To Reproduce**
1. Go to [ '...'](https://giveth.io/project/anka-relief?tab=donations)
2. See error (1inch donation)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Brave
 - Version: 1.49.120

**Additional context**

**Comment by MoeNick** [comment]
@MohammadPCh jan, can we make it or we need to change the design?

**Comment by MoeNick** [comment]
@mosaeedi I think you had a draft design on this table, right? *

**Comment by divine-comedian** [comment]
I played a bit with this when we updated the NFT collection into the dapp


 @maryjaf - Can you test the donation and GIVpower tables to make sure none of the data is cut off or squished as above?

**Comment by maryjaf** [comment]
> I played a bit with this when we updated the NFT collection into the dapp
> 
> @maryjaf - Can you test the donation and GIVpower tables to make sure none of the data is cut off or squished as above?

In some special case for example like as below pic this problem still exists
<img width="1257" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/6c0c1091-8be2-405c-8c46-b6cd47f06be6">

**Comment by divine-comedian** [comment]
@RamRamez is it possible to limit the numbers in the amount column to three decimal places?

**Comment by RamRamez** [comment]
> @RamRamez is it possible to limit the numbers in the amount column to three decimal places? This might prevent it from overflowing and creating the horizontal scroll.

Done! my PR is waiting for code review.

**Comment by maryjaf** [comment]
Thanks @RamRamez the issue has been resolved.
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/69c9362b-401b-41e6-9766-b0dcbfdaff2c)
