### ISSUE TITLE
It is better not to display the add option for deactivated projects

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#2346]
It seems that it is better to show the "add" option depending on the status of the project @MoeNick 
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/111529185/225402865-8131d8d3-9103-479e-861d-e47c9185a940.png">

**Comment by divine-comedian** [comment]
@maryjaf Is this issue still persistent?

**Comment by maryjaf** [comment]
> @maryjaf Is this issue still persistent?

The design is changed and now "manage address" is shown for all  projects
We can close this issue if it's okay to show "Manage Address" for the deactivated project as enable
<img width="1435" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/584c6feb-9698-4422-bd69-93a161976358">

**Comment by MoeNick** [comment]
As far as adding an address won't change the status of the project, I think it's ok and expected.
