### ISSUE TITLE
The dApp doesn't fully recognize polygon addresses yet!

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2349]
I added polygon address to Giveth project, and then like 30 min later tried to test donating...

I got this:

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/2428605d-cbdc-476a-a35f-cf476c6887c4)

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/4d9733c5-8e70-4c36-8fbe-7d078f57b928)

But you can see I have the address in there:
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/4bec4bd4-6eae-493d-9902-73faeaf8b3ec)

@MoeNick - who should I give this to?

**Comment by maryjaf** [comment]
It seems by the latest hotfix the changes related to donation modal and switch network modal are disappeared, before this change this was correct and the  donate ob polygon network  are  passed
@MohammadPCh @RamRamez
