### ISSUE TITLE
Bug when adding youtube link into verification form

### ISSUE THREAD

**Issue by Cotabe** [Giveth/giveth-dapps-v2#2353]
**Describe the bug**
Truing to verify a project, the verification form was failing to recognize the Youtube link.

I think the reason is that youtube recently changed link and added an "@" (https://www.youtube.com/@Givethio/videos). But that's just my speculation.

**To Reproduce**
1. Go to 'Verify project'
2. When adding Youtube link, see if it's recognizing it.

**Comment by maryjaf** [comment]
Thanks @MohammadPCh it has been resolved
