### ISSUE TITLE
As donor, I want to be able to copy/paste a token address to donate

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2358]
From @aminlatifi:

> It can be an awesome feature, yes it's possible!
> We currently use monoswap, a package which can be used in the frontend too! BTW, monoswap has limitation, we can use an alternative solution like fetching the prices from subgraph!
> So I think it's feasible to resolve prices both on the backend and frontend. On backend for filling data, and in the frontend for knowing whether a price is valuable or not!
> But there can be an issue, I can create a token myself and don't distribute it (I am the only owner). Then create a uniswap pool of pairs <my token> and <USDT or DAI or etc.>. Technically my token is valuable and I can configure the pool as my token worth a lot, like a million per each.
> Example:
> - I create MYTOKEN token and only I be the owner,
> - I create a uniswap pool of <MYTOKEN,USDT> and put there 10^-6 of my token and 1 USDT. So MYTOKEN price will be 1M$ if you look at that pool
> - Then donate with 1 token to a project! We would save 1M$ donation to that project!

> To be short, we will be prone to be fooled by scam tokens!

I'm wondering...  what if we made it possible, but don't determine a USD price for the token - and just exclude it from the total donations calculation? And definitely no GIVbacks.

cc @MoeNick

**Comment by aminlatifi** [comment]
@laurenluz That's possible! we can have a token whitelist, either create/maintain ourselves or fetch from external service, like uniswap etc.

**Comment by laurenluz** [comment]
that's possible and easy? then we can just add some copy/design for when a user is copy/pasting an address.. and let them know that they won't get GIVbacks or have their donation showing up adding to the total... and we can also send them to the forum...

Wdyt? Should I work on some design for that?

**Comment by aminlatifi** [comment]
> that's possible and easy? then we can just add some copy/design for when a user is copy/pasting an address.. and let them know that they won't get GIVbacks or have their donation showing up adding to the total... and we can also send them to the forum...
> 
> Wdyt? Should I work on some design for that?

In my view it's possible and not difficult. So, technically there is not blocker

**Comment by aminlatifi** [comment]
> that's possible and easy? then we can just add some copy/design for when a user is copy/pasting an address.. and let them know that they won't get GIVbacks or have their donation showing up adding to the total... and we can also send them to the forum...
> 
> Wdyt? Should I work on some design for that?

In case we don't want to save any footprint on the backend (Don't want to list the donation), it will be totally a frontend task

**Comment by aminlatifi** [comment]
> @aminlatifi what do you mean without ANY footprint of the backend? We have a list of donations almost everywhere that comes to the backend. and we have lots of statuses, Do you mean the front end just sends the donation to the wallet and we don't verify or save it?

Yes, I meant that. We have saved an entry in the token table corresponding to each token we support.

**Comment by MoeNick** [comment]
how we can calculate GIVbacks then?

**Comment by laurenluz** [comment]
no GIVbacks when the user does copy/paste - we can just add a little message when they do that "! note! you won't get GIVbacks" - you know?

**Comment by aminlatifi** [comment]
I suggest if we implement it, only show random donations to the donor and not all the users

**Comment by laurenluz** [comment]
where will the random donations be stored? only in the frontend and only shown to that particular user?

**Comment by aminlatifi** [comment]
No in the backend, but like pending donations will be shown only to the its donor
