### ISSUE TITLE
Make the textbox selected in the modal when users click on the search bar.

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#2369]
Make the textbox selected in the modal when users click on the search bar.

_Originally posted by @MoeNick in https://github.com/Giveth/giveth-dapps-v2/issues/2145#issuecomment-1475920078_

**Comment by alireza-sharifpour** [comment]
I've added this feature to Projects page and also Project Search Modal in the homepage @MoeNick @divine-comedian

**Comment by alireza-sharifpour** [comment]
It has some problem with react-hook-form. So we revert it and should implement it with another solution.
