### ISSUE TITLE
Giveth database - auto feed data for metrics

### ISSUE THREAD

**Issue by clara-zi** [Giveth/giveth-dapps-v2#2380]
@CarlosQ96 
would be good to find a way to auto-populate .csv file that feeds metrics report with the following data:

1) donor / donations
2) projects
and eventually
3) GIVeconomy stats

@WhyldWanderer

**Comment by clara-zi** [comment]
Hi @MoeNick I have been creating a metrics report in Google Looker (Studio), which is currently populated with a .csv with projects data from database. At the moment Ash has been downloading data from adminBro. To make the process smoother, it would be great to find a way to populate the .csv file automatically, probably on a monthly basis but may be even more effective is auto-updates in real-time.

**Comment by MoeNick** [comment]
Hi @clara-zi thanks now I get it ..

**Comment by MoeNick** [comment]
@CarlosQ96 it's related to another task that you're working on it.
