### ISSUE TITLE
Fix text on fiat donating transaction steps

### ISSUE THREAD

**Issue by danelsuga** [Giveth/giveth-dapps-v2#2392]
The word "card" is missing from this sentence when donating in fiat: 

"Buy crypto with your credit without leaving the platform."

The second sentence is:

"Donate the purchase to this project directly with your credit card with Onramper"

It needs a period at the end. I also feel like the text is a little confusing. I don't know that most people understand this as a "purchase" in itself (buying fiat with crypto). Cruggles (crypto Muggles) call this "converting" money typically.

So, in the first place, I think donors might not understand this phrase in the first sentence "without leaving the platform" because they wouldn't know why they WOULD leave the platform. Of course they won't be leaving the platform to make a donation. They don't see that behind the scenes part of the monetary conversion. Follow me?

I would recommend changing it to something more like:

"Donate that converted sum to this project directly with [only] your credit card using Onramper." 

Give or take "only". Not sure. 

One more bit of confusion is that the two sentences are a wee bit redundant. I wanted to right "Next, donate..." or "Then donate..." but oddly that doesn't work because it's kind of all the same step, isn't it. So maybe like this then:

"Buy crypto with your credit without leaving the platform: donate the converted sum to this project directly via your credit card using Onramper." 

@mateodaza @laurenluz 

![Screenshot 2023-03-22 2 11 56 PM](https://user-images.githubusercontent.com/81351744/226917492-d1aea92c-7dac-4ffd-a231-a0a5ce89527f.png)

**Comment by laurenluz** [comment]
Onramper isn't ready yet, is it? I thought we weren't going ahead with it @mateodaza ?

If we are... thanks @danelsuga - simplest, let's just change it to:

Text: "Buy crypto with your credit card, and donate it directly to your favourite Giveth project." 
Button: "Continue with Onramper"

**Comment by MoeNick** [comment]
I don't want to lose this issue, so move it back to backlog
