### ISSUE TITLE
Confused by fiat donation set-up

### ISSUE THREAD

**Issue by danelsuga** [Giveth/giveth-dapps-v2#2395]
Sorry, I'm confused by the fiat donation set-up.
So I find the project I want to donate to using fiat.
I click "credit card". All the while, there is a banner above my future transaction that says "Buy xDAI with FIAT" with a button and with an explainer.  
Now, here I am again. I click "credit card". The only currency I am able to buy is ETH. I'm confused because the banner says to buy xDAI, but that is not an option. If I click on the button, it takes me back to the same place that I was before I chose my project.
Is this correct? If so, it's confusing because I don't know why I'm buying ETH if I'm being told to buy xDAI.
![Screenshot 2023-03-22 2 34 03 PM](https://user-images.githubusercontent.com/81351744/226921991-ec531949-6d79-4d43-bdab-079de16cbe61.png)

@mateodaza

**Comment by mateodaza** [comment]
thanks for the feedback @danelsuga !

I understand the confusion and maybe a good way to be more clear is to hide the upper banner once the user clicks on the credit card tab - as they're different products

The issue of it just showing ETH is for the current problems we have on the widget, that's partially why we have stopped testing Onramper

**Comment by danelsuga** [comment]
ah! yes! thank you.
