### ISSUE TITLE
testing fiat mt pelerin ramp landing page

### ISSUE THREAD

**Issue by danelsuga** [Giveth/giveth-dapps-v2#2396]
I just want to confirm that this is how the page looks only for testing.
Otherwise it would be very confusing for donors to look at this and to understand how to navigate next, as there is no button or anything to go anywhere.
Thanks!

@mateodaza 
![Screenshot 2023-03-22 2 40 18 PM](https://user-images.githubusercontent.com/81351744/226922601-d754d9d9-23ef-4a6c-b4e3-53d8dcac4870.png)

**Comment by danelsuga** [comment]
Ooooo. That looks much more interesting! Ha. Yeah, I don't see that. 😵‍💫

**Comment by MoeNick** [comment]
is it still happening to you? can you provide more details? such as browsers, specific projects, OS etc.

**Comment by danelsuga** [comment]
@MoeNick I still have the same problem. I am on a Chrome browser, ChromeOS. No projects. Just at the buying site directly: https://fiat-38.vercel.app/
