### ISSUE TITLE
changes of referral landing page

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#2404]
Here is the link to the updated design on Figma -> [Figma link](https://www.figma.com/file/hNqwpebu4JCy1XIed2c862/Giveth-Public?node-id=22-36561&t=pz3ZryuftcRIwqs3-4)

_Originally posted by @mosaeedi in https://github.com/Giveth/giveth-planning/issues/1234#issuecomment-1477546795_

**Comment by ahmadabugosh** [comment]
@mosaeedi I made some minor comments on the Figma file. Can you incorporate those today please?
