### ISSUE TITLE
Taketh LandingPage

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#2405]
Here is the design for the Taketh landing page -> [Figma link](https://www.figma.com/file/hNqwpebu4JCy1XIed2c862/Giveth-Public?node-id=80-20153&t=SypBG474jAlUzLlq-4)

Just waiting for @rodricastillo9013 to replace the banner.

_Originally posted by @mosaeedi in https://github.com/Giveth/giveth-planning/issues/1276#issuecomment-1479395569_

**Comment by MohammadPCh** [comment]
@RamRamez can you take this?

**Comment by RamRamez** [comment]
What is the desired path for this? `/taketh`?

**Comment by MohammadPCh** [comment]
It's good to be like this is good: `/landing/taketh`

**Comment by ahmadabugosh** [comment]
@MohammadPCh @RamRamez  Yes I think /landing/taketh is fine. 

Also, minor thing can you change where it says "Simply tweet us" to instead be "Simply DM us" 

Thanks!

**Comment by danelsuga** [comment]
Please put a fish on the banner.

**Comment by laurenluz** [comment]
https://staging.giveth.io/landings/taketh

**Comment by ahmadabugosh** [comment]
Hey @RamRamez @MohammadPCh @laurenluz , 

Can we replace the last paragraph "Want in?" with the following (the last paragraph on [this sheet ](https://docs.google.com/document/d/1b4R6TCnpCM3SxYcOFLMm3mkhTIwjC17wOmDK5WXPct8/edit#)and also below)? 

"**Sound Good?**
If this doesn’t sound like the world you want to live in, then you’re always welcome to go back to [Giveth](https://giveth.io/projects) and support the mission to Build the Future of Giving while donating to projects with zero fees and actually getting rewarded for it with GIV tokens. The choice is yours."

**Comment by RamRamez** [comment]
> Hey @RamRamez @MohammadPCh @laurenluz ,
> 
> Can we replace the last paragraph "Want in?" with the following (the last paragraph on [this sheet ](https://docs.google.com/document/d/1b4R6TCnpCM3SxYcOFLMm3mkhTIwjC17wOmDK5WXPct8/edit#)and also below)?
> 
> "**Sound Good?** If this doesn’t sound like the world you want to live in, then you’re always welcome to go back to [Giveth](https://giveth.io/projects) and support the mission to Build the Future of Giving while donating to projects with zero fees and actually getting rewarded for it with GIV tokens. The choice is yours."

Google doc suggests that `Sounds good` is correct. Maybe it is short for "it sounds good". You know better me, I just wanted to check with you.

**Comment by danelsuga** [comment]
It should indeed be "Sound good?"
