### ISSUE TITLE
"Projects" tab should be clickable from the homepage!!

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2415]
Since the homepage update, getting to the projects page has become slow with unecessary extra clicks.

We should make it so that the user can still click "Projects" and get redirected to the projects page will all projects showing.

Click here...
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/90f133a5-2618-4090-b438-fc7a21162061)

Go here...
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/2a9fa9c1-6e50-4c55-a7b3-4c5091a9bdb3)

@mosaeedi @MoeNick

**Comment by laurenluz** [comment]
@mosaeedi said to me the other day in DM that it's ok if we make it clickable. We did already update the copy. Can we make it clickable as a quick fix and assign a dev @MoeNick ?

**Comment by laurenluz** [comment]
in fact, I think we should make all the header titles clickable...

- [ ] Projects --> goes to project page
- [ ] GIVeconomy --> goes to GIVeconomy overview page
- [ ] Community --> goes to join (as it is now)

These huge text-heavy drop down menus make everything feel slow and clunky.

**Comment by maryjaf** [comment]
> in fact, I think we should make all the header titles clickable...
> 
> * [ ]  Projects --> goes to project page
> * [ ]  GIVeconomy --> goes to GIVeconomy overview page
> * [ ]  Community --> goes to join (as it is now)
> 
> These huge text-heavy drop down menus make everything feel slow and clunky.

Thanks @MohammadPCh Now all of them are clickable
