### ISSUE TITLE
Fix Copy & rearrange text in projects tab

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2416]
This is so messy, let's make some small changes

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/b538eec8-5b02-41cc-be4f-452a4c453bcc)

- [x] "All projects" should be 1st
- [x] "Recently Updated" needs a space
- [x] Second title should just say "CATEGORY" (no "by")

@MoeNick

**Comment by laurenluz** [comment]
this is @mosaeedi approved!

Can @RamRamez or @alireza-sharifpour  take it?

**Comment by alireza-sharifpour** [comment]
> this is @mosaeedi approved!
> 
> Can @RamRamez or @alireza-sharifpour take it?

I'll take it.
