### ISSUE TITLE
GIVpower staking & lockups dashboard

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2419]
It would be really useful for us to get information on GIV staking & locking for GIV so that when we are planning incentives for future rounds, or making adjustments, we can easily access this data.

@GriffGreen & I discussed the requirements, & chatted w/ @aminlatifi & @RamRamez - and @RamRamez can take this on!

Requirements - we basically want to know how much GIV is staked, locked & until when:
- every 2 weeks, how much GIV can be unlocked?
- how much GIV is staked and not locked?
- how much GIV is locked for 1 year?
- when are the big "unlock" moments - i.e. when will large amount of GIV get unlocked
- % of total supply (GIV) that is staked
- % of total supply (GIV) that is locked
- % of total supply (GIV) that is locked for more than 6 months
- value (in $) of GIV that's locked

**Comment by laurenluz** [comment]
@RamRamez - let me know once you get started on this, want to make sure everything is on the right track

**Comment by m-r-g-t** [comment]
Happy to help out in this one 🧙‍♂️

**Comment by MoeNick** [comment]
This is old but gold, Would you mind putting it in GIVeconomy proposal @laurenluz ?

**Comment by aminlatifi** [comment]
@germanier Thanks for offering help. If you are still volunteer, it's good to know all the information could be fetched from subgraph. If anything is missed let us know.

**Comment by laurenluz** [comment]
will put it in the proposal @MoeNick

**Comment by divine-comedian** [comment]
@laurenluz  - is this issue still relevant?

**Comment by laurenluz** [comment]
I copied the requirements on the other dashboard issue so we can combine them and close this.
