### ISSUE TITLE
Donations list on project is total chaos! (Bug)

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#243]
This doesn't look right:

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/6b342dad-1653-49e4-a96c-b751e7387e6e)

**Comment by laurenluz** [comment]
I'm on live, btw.

**Comment by NikolaCreatrix** [comment]
Tested on live and staging version - bug is fixed!
