### ISSUE TITLE
Connected to Ropsten (testing on v2), tells me to switch to gnosis chain for a giving block project

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#244]
this popup makes no sense, Giving block projects don't even accept funds on gnosis chain.

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/9ded9ee7-69d6-43d4-bd3f-cc90a327406e)

**Comment by pkretzschmar** [comment]
@laurenluz I changed the modal behavior. Now, if you go to a project that belongs to GivingBlock, and you're not connected to Ethereum, will ask you to change to ETH chain, and if you are trying to donate to another project that is not from Giving Block, will suggest to use Gnosis or Ethereum.

**Comment by divine-comedian** [comment]
I just made a small update to the text - other than that the changes are working as expected! 

on regular projects we get this modal 
![image](https://user-images.githubusercontent.com/67759413/161094369-71feae1f-f242-4f17-b58e-d3f09fa7d5ea.png)

on giving block projects we receive a prompt just for ethereum mainnet

![image](https://user-images.githubusercontent.com/67759413/161094682-75d34f49-be3b-40e5-b368-7187f648cc2c.png)

resolved! moving to done
