### ISSUE TITLE
In emergency, there should be a maintenance mode

### ISSUE THREAD

**Issue by RamRamez** [Giveth/giveth-dapps-v2#2440]
[Ref.](https://discord.com/channels/679428761438912522/861692942645067777/1089843068678705212)

**Comment by MoeNick** [comment]
@RamRamez do you have an idea how we can test this issue?

**Comment by RamRamez** [comment]
> @RamRamez do you have an idea how we can test this issue?

First, you should change `NEXT_PUBLIC_IS_MAINTENANCE` env variable to true here:

https://vercel.com/givethio/giveth-dapps-v2/settings/environment-variables

Be careful to change it for develop and preview only and not the production, otherwise production will go to maintenance mode.

Then go to this URL:

https://vercel.com/givethio/giveth-dapps-v2/deployments

search for `develop` branch, click on the newest result, then click `Redeploy`

FYI @geleeroyale . Just in case.
