### ISSUE TITLE
One project is throwing 500 error

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#2441]
Ever since the day we had a server problem, this project has been showing 500 error.

https://giveth.io/project/sustainable-food-security-and-ecosystem-restoration

Seems that it is only this one project
![image](https://user-images.githubusercontent.com/74267818/228925605-3808d69d-1eb0-482e-be8e-19d137d0786b.png)

**Comment by MoeNick** [comment]
@mohammadranjbarz @alireza-sharifpour would u please check it together?

**Comment by aminlatifi** [comment]
There is an issue with this project, the size of its limitation is around 30M, more than 30 Million characters!
We are going to add limitation on text field sizes

**Comment by aminlatifi** [comment]
@WhyldWanderer If we clear this project description, do you have access to project owners to fill the description again?
I attached the description here
[Uploading 1880-description.zip…]()

**Comment by aminlatifi** [comment]
> There is an issue with this project, the size of its limitation is around 30M, more than 30 Million characters! We are going to add limitation on text field sizes

@WhyldWanderer I fixed the issue by transforming that project description content. Now all images are uploaded to IPFS and the length of the description less 5K.

**Comment by WhyldWanderer** [comment]
Thank you Amin! I messaged the project owner also and it seems to be okay now!
