### ISSUE TITLE
Don't save images as base64 in descriptions

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapps-v2#2449]
**Describe the bug**
Currently, there are projects in Giveth whose images are stored in the description in raw base64 format! This cause issues in storing data in db and backend performance, like this https://github.com/Giveth/giveth-dapps-v2/issues/2441

**Expected behavior**
It's better images be saved in IPFS via the API already exists.

**Comment by aminlatifi** [comment]
The project mentioned in #2441 is not the only one, we have a bunch of projects with description length of around 3MB

**Comment by maryjaf** [comment]
> @maryjaf Could you please take a look?

Thanks @MohammadPCh this issue has been resolved.
