### ISSUE TITLE
Add NFT in onboarding page 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#2453]
When a user is completing their profile for the first time we should show them by default any Givers NFTs they own and allow them to easily set it as their profile picture. 
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/GIVeconomy?node-id=21490-198054&t=QdicBdzd0wkGtXA4-0

![image](https://user-images.githubusercontent.com/67759413/229529364-a1e3e24d-122d-425a-b1e1-81fed574271c.png)
----

Cases to consider:
- user is by default shown the `My PFP` tab 
- if the user has no eligible NFTs in their wallet we inform them and encourage them to mint a Givers PFP
- user can click `Upload Image` tab and upload an image from their computer

It's all in the Figma!

**Comment by alireza-sharifpour** [comment]
It can be tested here @divine-comedian :
https://givpfp.vercel.app/account

**Comment by divine-comedian** [comment]
@alireza-sharifpour we should implement a horizontal scroll instead of vertical - the user is not able to see the relevant metadata at the bottom 

OR 

fix some elements outside of the scroll - such as the metadata display and the `SAVE` button

https://user-images.githubusercontent.com/67759413/230453442-315677ee-97b3-4b03-ade0-43db19a8fd4e.mp4

**Comment by divine-comedian** [comment]
@alireza-sharifpour 

Noticing a few things - when we land on this page by default we should show the my NFT tab - not the upload image tab

the `MINT NOW` and `SAVE` button are two different sizes between the two tabs


https://user-images.githubusercontent.com/67759413/230457303-a72ee53d-e1b4-4c33-9007-27a1f68e9176.mp4

**Comment by divine-comedian** [comment]
One other consideration - when a user owns a PFP and they select one - we increase the height of the modal to accomodate showing the trait info - I would recommend adding a transition effect so it appears more smooth 

https://user-images.githubusercontent.com/67759413/230459379-6edede5b-8252-4699-b583-f46559ff8aa6.mp4

**Comment by alireza-sharifpour** [comment]
I'm working on this

**Comment by divine-comedian** [comment]
> @alireza-sharifpour
> 
> Noticing a few things - when we land on this page by default we should show the my NFT tab - not the upload image tab
> 
> the `MINT NOW` and `SAVE` button are two different sizes between the two tabs
> 
>  Screencast.2023-04-06.11.51.02.mp4

@maryjaf can you confirm these are passed?

**Comment by maryjaf** [comment]
There are some difference between figma anf pfp branch , Which one is final?
<img width="709" alt="image" src="https://user-images.githubusercontent.com/111529185/232880491-6a8b23fe-76ca-4ee6-aba2-29f76c7136a5.png">
<img width="1359" alt="image" src="https://user-images.githubusercontent.com/111529185/232880604-441fce3c-57a8-4b0d-a64f-cf2de1467951.png">

@alireza-sharifpour @divine-comedian

**Comment by divine-comedian** [comment]
PFP branch is final, I updated the text directly on the app
