### ISSUE TITLE
Remove Early Minting Checker

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#2455]
Early Minting will end March 24, 11am CST, after which we will no longer need that feature on the pfp landing page. 

Section `1` I will need to rewrite and we will change the link probably as well - I will work on it today 

We can remove the entire section marked `2` 

![image](https://user-images.githubusercontent.com/67759413/227243501-09e3c9b6-6cd3-4064-975d-6364f0ef9e58.png)

**Comment by alireza-sharifpour** [comment]
Yes it is @divine-comedian
