### ISSUE TITLE
Write/update text for pfp integration pages and views

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#2457]
Improving and Updating the text for all pages relevant to the pfp dapp integration 
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/GIVeconomy?node-id=14997-268092&t=nXVOZvvLw4IckUiF-0

Just for these sections:
![image](https://user-images.githubusercontent.com/67759413/229595349-5bed3aae-f759-4d24-a60c-9e07f0953bee.png)

Add in your copy @danelsuga  as comments over the relevant sections in figma

Looping in @Tosinolawale @MohammadPCh  - @danelsuga will provide the new text over the next day or two.

**Comment by danelsuga** [comment]
Gave it a go, @divine-comedian !

**Comment by divine-comedian** [comment]
@danelsuga 

This is the deployment link to check all the features for pfp integration! 
https://givpfp.vercel.app/

If you provide me an address I can mint you some test NFTs 

Check the text for these flows:
-  Onboarding and adding a pfp already owned as a new user
- Onboarding with a fresh wallet that does not hold any Givers NFTs
- Editing your profile while holding a PFP in the connected wallet
- Editing profile with a wallet that does not hold a PFP
- Check all above flows as well for uploading an image from your computer

**Comment by danelsuga** [comment]
0x2fEe53687906bA239602eD42CCEee2aC8A4ADa36

**Comment by divine-comedian** [comment]
> 0x2fEe53687906bA239602eD42CCEee2aC8A4ADa36

Sent!

**Comment by danelsuga** [comment]
Couple of errors so far. I'll post them here one by one.

**Comment by danelsuga** [comment]
![Screenshot 2023-04-12 4 28 56 PM](https://user-images.githubusercontent.com/81351744/231492687-586547e4-abb7-4de8-ab73-f00c9aac929d.png)

"The" is repeated, so it says "The The Givers".

**Comment by danelsuga** [comment]
![Screenshot 2023-04-12 4 30 18 PM](https://user-images.githubusercontent.com/81351744/231492983-77f9ef1c-1c10-4894-b878-8abb8b70dce8.png)

Minor error, but should still be fixed. "Upload" should not be capitalized, and technically there should be a comma before "or".

Also I think it would be better if it said:

"Suggested image size: min. 600px width, max. 4MB."

**Comment by danelsuga** [comment]
![Screenshot 2023-04-12 4 34 04 PM](https://user-images.githubusercontent.com/81351744/231494278-7c9878b9-34ec-4673-ae90-36c191547927.png)

"Save" is not in the right spot (and it stays in that spot, covering the info) for the SECOND nft and not for the first (it was fine for the first).

**Comment by divine-comedian** [comment]
@alireza-sharifpour Can you take a look at these?

**Comment by danelsuga** [comment]
I'm posting the rest of the errors here, as requested by @MoeNick: 
https://discord.com/channels/679428761438912522/1075056376293888128

**Comment by alireza-sharifpour** [comment]
> ![Screenshot 2023-04-12 4 34 04 PM](https://user-images.githubusercontent.com/81351744/231494278-7c9878b9-34ec-4673-ae90-36c191547927.png)
> 
> "Save" is not in the right spot (and it stays in that spot, covering the info) for the SECOND nft and not for the first (it was fine for the first).

Thanks @danelsuga for noticing, it should be fixed now.
