### ISSUE TITLE
Create multisig for building a "scorer" for passport

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2459]

**Comment by laurenluz** [comment]
They just changed the name "Community" to "scorer".

Basically the scorer is where we decide the criteria for "scoring" a passport - i.e. we decide which stamps are worth what: https://scorer.gitcoin.co/

Instead of having a single user build the community, we perhaps should do this via a multisig so we can add stamps & change the scores later, but as a DAO.

**Comment by MoeNick** [comment]
Can we go forward with this without @aminlatifi ?

**Comment by laurenluz** [comment]
we are going to do this with a new wallet... multisig support seems shady...
