### ISSUE TITLE
When donation is pending, I can click the "donating button" and the tx gets triggered again

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#246]
This might cause the user to accidentally donate twice.... the "donating" button should be unclickable

Testing on [v2](https://giveth-dapps-v2.vercel.app/donate/how-many-photos-is-too-many-photos)

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/8eb6a85c-46fb-4c85-8877-03d89a9ad297)

**Comment by MoeNick** [comment]
I can still click on donating button while Im in the process.

**Comment by MoeNick** [comment]
@pkretzschmar should I bring it back ?
