### ISSUE TITLE
Change authentication service for passport

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2460]

**Comment by laurenluz** [comment]
We should change our authentication service so that people don't need to sign multiple times to interact w/ their passport score.

**Comment by laurenluz** [comment]
Amin added endpoints for intergating w/ passport. @CarlosQ96 - can you review this please?

**Comment by MoeNick** [comment]
Im wondering what are test cases, and where is the PR? @aminlatifi

**Comment by aminlatifi** [comment]
> Im wondering what are test cases, and where is the PR? @aminlatifi
The PR includes some tests

https://github.com/Giveth/SiweAuthMicroservice/pull/12

**Comment by maryjaf** [comment]
How can I test it ? @aminlatifi

**Comment by aminlatifi** [comment]
> How can I test it ? @aminlatifi

It's an API that must be called/used by frontend... so you cannot test it until we use it in our application
