### ISSUE TITLE
Allow users to set their PFP on dapp right after minting

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#2467]
We should add this button upon success on the pfp minting page: `USE AS PROFILE PICTURE`

![image](https://user-images.githubusercontent.com/67759413/229860840-ecabded6-fc8d-46a4-8b47-354c8829de39.png)

this will allow users to directly go to their edit profile page and choose their NFT they just minted

There are two cases to consider: 
- user has already setup their profile 
- user has not setup their profile on the dapp

in the first case we take them here:

![image](https://user-images.githubusercontent.com/67759413/229861203-4b7dbe25-cc8c-4605-88be-4601a379df1d.png)

in the second case, they do not have a profile, we take them to the beginning of the onboarding view:

![image](https://user-images.githubusercontent.com/67759413/229862064-5271a272-4d97-429b-96b5-c9da59b9b700.png)

**Comment by maryjaf** [comment]
There is a problem in the implementation of this part of the story
"in the second case, they do not have a profile, we take them to the beginning of the onboarding view:"

Now if they do not have a profile after minting the below pic is shown
and by selecting save button this message is shown(pic 2):


![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/3f0bac72-5926-457e-ab50-9e8c5692c3cf)
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/57cb920d-ca3e-41bf-b88f-ed977335d971)

**Comment by divine-comedian** [comment]
Good catch! My understanding for the first-time user setup (onboarding) they should not be able to proceed to setting an image without providing a last name or first name. 

### User should be required to fill out the required fields here:
![image](https://user-images.githubusercontent.com/67759413/231208302-6dc6061e-5307-45ef-ad16-87d56510137c.png)


### Before being allowed to continue to this page:
![image](https://user-images.githubusercontent.com/67759413/231208203-766c7826-e356-44a1-aa93-51cff58d636b.png)

**Comment by MohammadPCh** [comment]
@maryjaf @divine-comedian Thanks guys.
I will check if the user profile isn't completed yet, and I will send it to the onboarding page. and I think all problems will fix.
@alireza-sharifpour can you take look at the problem with the "do it later" button?

**Comment by maryjaf** [comment]
> In below pic when I click on "mint" and I redirected to https://givpfp.vercel.app/nft/mint ![image.png](https://camo.githubusercontent.com/fa7f99e6f5630784015d42a6633ba25b3f9538e6fbce03d912d730d90f0f4a11/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f39613934663263372d646363662d346634342d613665622d313066336462393138306266)
> 
> for example my user hasn't sufficient fund when I back to boboard page i see this: ![image.png](https://camo.githubusercontent.com/d490a95de1df60a7c5da60d08eeb069a560416b8d56503b9a889c8a3214703b0/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f35643537393334342d623062342d346630642d393131662d633738626634373461323337) Is this ok? or should I redirected to this page ? @MohammadPCh ![image.png](https://camo.githubusercontent.com/233de3fbb060779ec5a3591939124c33de616798077d186d6fb68253d75dd918/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f35616133336639662d353539632d343162392d626266312d333233623763626563343965)

Is it not necessary to make a change in this flow? @MohammadPCh @divine-comedian

**Comment by maryjaf** [comment]
> There is a problem in the implementation of this part of the story "in the second case, they do not have a profile, we take them to the beginning of the onboarding view:"
> 
> Now if they do not have a profile after minting the below pic is shown and by selecting save button this message is shown(pic 2):
> 
> ![image.png](https://camo.githubusercontent.com/6af66ec049c3d4281b2d64c09f8ec26eb45fca512ec9b63ff0359e655c78c717/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f33663062616337322d353932362d343537652d616235302d396538633536393263336366) ![image.png](https://camo.githubusercontent.com/8e51d97017f672a30d0e7acd5aaf6702b8096d97fd687fe603360f100ee928e5/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f35376362393230642d636133652d343162662d623838662d656439373733333564393731)

Thanks @MohammadPCh @alireza-sharifpour , the problem related to "DO IT LATER "and user without profile flow has been solved
