### ISSUE TITLE
Show dollar sign in user profile contribute card

### ISSUE THREAD

**Issue by MohammadPCh** [Giveth/giveth-dapps-v2#2471]
now:
![Screenshot from 2023-04-05 12-48-03](https://user-images.githubusercontent.com/17097576/230039131-3d25c390-f8b1-4961-b896-b8948871de65.png)
expected:
![Screenshot from 2023-04-05 12-50-30](https://user-images.githubusercontent.com/17097576/230039186-9f344c68-369e-42af-ac97-9a8e02970d13.png)

**Comment by maryjaf** [comment]
Thanks @MohammadPCh it has been shown correctly 
<img width="1315" alt="image" src="https://user-images.githubusercontent.com/111529185/230097913-a7f84bb9-cf0a-4cec-872b-5a92bc8ac28f.png">
