### ISSUE TITLE
GIVpower - extend incentives program until October 31, 2023

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2474]
The [proposal](https://forum.giveth.io/t/givpower-summary-requesting-giv-for-incentives-update-q2-2023/719/22) and [snapshot vote](https://snapshot.org/#/giv.eth/proposal/0xde423f49452e8340de5843134f3389b49afaeb278a2f96fdbe73705414686e9e) to extend this rewards program has passed, so we should proceed. 

We need to `notify reward` on the GIVstaking pool for an additional 14 rounds, and a total of 13 million GIV, according to the following:

|Round|Start Date|GIV|% of 6 mo. Total|
|---|---|---|---|
|Round 1|April 18|753,000|5.79%|
|Round 2|May 2|780,000|6.00%|
|Round 3|May 16|807,000|6.21%|
|Round 4|May 30|834,000|6.42%|
|Round 5|June 13|861,000|6.62%|
|Round 6|June 27|888,000|6.83%|
|Round 7|July 11|915,000|7.04%|
|Round 8|July 25|942,000|7.25%|
|Round 9|August 8|969,000|7.45%|
|Round 10|August 22|996,000|7.66%|
|Round 11|September 5|1,023,000|7.87%|
|Round 12|September 19|1,050,000|8.08%|
|Round 13|October 3|1,077,000|8.28%|
|Round 14|October 17|1,105,000|8.50%|
||Total:|13,000,000|100.00%|

**Comment by laurenluz** [comment]
@aminlatifi it turns out that we have not yet even made a grant requesting the money to put GIVpower on Celo.

So it will be at least a month (or maybe more) until we need to take any funds from this total 13mil to move to celo chain. However, we should still keep in mind that we might need to reduce the GIV amounts at some point, to move some to other chains.

Are we able to change the percentages per round later? because we need to be sure that we have rewards going out next round at least :)

**Comment by laurenluz** [comment]
DM me if any of that is not clear

**Comment by aminlatifi** [comment]
> @aminlatifi it turns out that we have not yet even made a grant requesting the money to put GIVpower on Celo.
> 
> So it will be at least a month (or maybe more) until we need to take any funds from this total 13mil to move to celo chain. However, we should still keep in mind that we might need to reduce the GIV amounts at some point, to move some to other chains.
> 
> Are we able to change the percentages per round later? because we need to be sure that we have rewards going out next round at least :)

That's fine, we can have the same distribution on CELO when we want to support it. When the time comes, we can still continue this program with less reward for Gnosis Chain. Practically, I will touch only the total reward of the program for the Gnosis Chain reward distribution and will duplicate everything on Celo with the same distribution and a less total reward. 
To clear it more, after the launching of CELO, the sum of the total reward of the Gnosis and Celo programs will be the total reward of the Gnosis Program before the CELO launch.

**Comment by laurenluz** [comment]
perfect

**Comment by aminlatifi** [comment]
The new distribution script on xDAI is created and reviewed by Mohammad.
I configured the bot to run the new script on scheduled intervals instead of the old one. The new script must recharge givpower contract on  April 18, 2023 18:00:00 GMT

**Comment by laurenluz** [comment]
@aminlatifi - we only allocated enough GIV for 2 rounds right? so we need to allocate more GIV on May 16?

**Comment by aminlatifi** [comment]
@laurenluz We haven't allocate any!

**Comment by laurenluz** [comment]
Let's assign the entire 13 mil GIV to the gnosis chain unipool. We can change the amount later when we actually add the new chains.

**Comment by laurenluz** [comment]
Ok let's assign a balance to the gnosis chain unipool for 2,340,000 GIV ... which will cover us for the 1st 3 rounds until May 30. We can assign a new balance later... and take into consideration if/when we launch optimism incentives.

Spreadsheet [here](https://docs.google.com/spreadsheets/d/14kj7eIJg_hTf8BwVoGvPEWAo2Z6O18lA2bd1jOGZaNc/edit#gid=0)

**Comment by laurenluz** [comment]
@aminlatifi & I set up the tx: https://app.safe.global/transactions/tx?id=multisig_0x4D9339dd97db55e3B9bCBE65dE39fF9c04d1C2cd_0x74709515e172b3d69f860ebcc5dbc157aabadf6650404d47cc099e9c6d42bba6&safe=gno:0x4D9339dd97db55e3B9bCBE65dE39fF9c04d1C2cd
