### ISSUE TITLE
My Account | Manage Address Modal

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#2482]
My account page
[Figma link](https://www.figma.com/file/vMiyVd1Ly5LjgSyZrChVV8/Giveth-users?node-id=325-96063&t=F3KuJZa225LcBggc-4) 

One time modal 
[Figma link](https://www.figma.com/file/vMiyVd1Ly5LjgSyZrChVV8/Giveth-users?node-id=325-96180&t=F3KuJZa225LcBggc-4)

Manage wallet modal
[Figma link](https://www.figma.com/file/vMiyVd1Ly5LjgSyZrChVV8/Giveth-users?node-id=325-96179&t=F3KuJZa225LcBggc-4)

Add a new wallet address (no error)
[Figma link](https://www.figma.com/file/vMiyVd1Ly5LjgSyZrChVV8/Giveth-users?node-id=327-97093&t=F3KuJZa225LcBggc-4)

Add a new wallet address
[Figma link](https://www.figma.com/file/vMiyVd1Ly5LjgSyZrChVV8/Giveth-users?node-id=325-96177&t=F3KuJZa225LcBggc-4)

**Comment by laurenluz** [comment]
Please make any comments in the figma if you wish @laurenluz @divine-comedian

**Comment by maryjaf** [comment]
So far, I have encountered two problems in "https://givcelo.vercel.app/" environment.
plz check this @MohammadPCh 
1-Switch network to Celo isn't work
2- In Manage addresses modal Optimism network isn't shown

**Comment by MohammadPCh** [comment]
@maryjaf  Thanks,
It's better to have a call and check your meta mask settings. or please remove your Celo network and add it again.
You are right about item 2, I have fixed it and you can check it now.

**Comment by maryjaf** [comment]
> @maryjaf Thanks, It's better to have a call and check your meta mask settings. or please remove your Celo network and add it again. You are right about item 2, I have fixed it and you can check it now.

Thanks @MohammadPCh #  2 item has been resolved
I think we had a problem with Alfajores testnet  because In addition to  # 1 , the name of this network  "Alfajores testnet " is not displayed in below module, if the wallet address is set for Cello in this project 

<img width="1166" alt="image" src="https://user-images.githubusercontent.com/111529185/232253268-76f4b7d3-41b0-4d40-95fe-5e3b500f1e37.png">
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/111529185/232253283-16ecc206-68b1-47bb-bb04-440d62fda266.png">

**Comment by maryjaf** [comment]
> > @maryjaf Thanks, It's better to have a call and check your meta mask settings. or please remove your Celo network and add it again. You are right about item 2, I have fixed it and you can check it now.
> 
> Thanks @MohammadPCh # 2 item has been resolved I think we had a problem with Alfajores testnet because In addition to # 1 , the name of this network "Alfajores testnet " is not displayed in below module, if the wallet address is set for this network in "testoptimism" project
> 
> <img alt="image" width="1166" src="https://user-images.githubusercontent.com/111529185/232253268-76f4b7d3-41b0-4d40-95fe-5e3b500f1e37.png">
> 
> <img alt="image" width="1432" src="https://user-images.githubusercontent.com/111529185/232253283-16ecc206-68b1-47bb-bb04-440d62fda266.png">

This problem also has been resolved, thanks @MohammadPCh
