### ISSUE TITLE
Fix i18n error

### ISSUE THREAD

**Issue by MohammadPCh** [Giveth/giveth-dapps-v2#2485]
It seems that we missed some translations, especially for categories.
![image](https://user-images.githubusercontent.com/17097576/230879983-e5a013cd-b1a9-49a2-b5e4-1e1d1c47d8ff.png)

**Comment by MohammadPCh** [comment]
@RamRamez can you take a look?

**Comment by RamRamez** [comment]
> @RamRamez can you take a look?

Yeah, I fixed it
