### ISSUE TITLE
List of Optimism Tokens for donations & for GIVbacks

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2495]

**Comment by aminlatifi** [comment]
@mateodaza Can you help @CarlosQ96 by providing list of eligible tokens?

**Comment by maryjaf** [comment]
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/b83f3ba8-69a8-4b1c-8b34-4c50981e00a0)
All if these tokens are not shown in the token list, like: RAI, ALUSD, wstETH, Kwenta, BoB,
oeth
@CarlosQ96 @aminlatifi

**Comment by maryjaf** [comment]
Donation with USDT token is shown pending in list of project's donation
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/705e1dd4-54ae-4249-9f52-8096dcc3fe0b)
https://serve.giveth.io/admin/resources/Donation/records/16428/show
@aminlatifi

**Comment by aminlatifi** [comment]
> ![image.png](https://camo.githubusercontent.com/84cc86eca44ece33d43fc5cc9042205eb0cf168e598942ded40bbbc75d4733af/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f62383366336261382d363961382d346231632d386233342d346335303938316530306130) All of these tokens are not shown in the token list, like: RAI, ALUSD, wstETH, Kwenta, BoB, oeth @CarlosQ96 @aminlatifi

We didn't have wstETH and oeth addresses, https://forum.giveth.io/t/givbacks-token-list/253/37?u=amin
So skipped it!
The other 4 tokens were left out since they don't have enough liquidity on uniswap v3
https://forum.giveth.io/t/givbacks-token-list/253/32?u=amin

**Comment by aminlatifi** [comment]
> Donation with USDT token is shown pending in list of project's donation ![image.png](https://camo.githubusercontent.com/8c7dcc686edc62023bd6fc399b074d1e6e969ad36bf65f0b79dd1637b48d7ff7/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f37303565316464342d353461652d343234392d396635322d383039366463633366653062) https://serve.giveth.io/admin/resources/Donation/records/16428/show @aminlatifi

It's verified as I see now
