### ISSUE TITLE
Deploy GIVpower Staking on Optimism Chain

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2497]

**Comment by laurenluz** [comment]
We should deploy GIV staking & locking on optimism chain, and should allocate 10% of the incentives we current have going out for GIVpower to this new program.

**Comment by divine-comedian** [comment]
@aminlatifi 

Is this the  similar process for the tokenDistro in terms of deploying on optimism-goerli? 

We also need to update the subgraph we launched from the tokenDistro once it's deployed?

**Comment by aminlatifi** [comment]
> @aminlatifi
> 
> Is this the similar process for the tokenDistro in terms of deploying on optimism-goerli?
> 
> What is the GIVpower contract(s) called? I assume we set 1 of them as a tokenDistro distributor
> 
> We also need to update the subgraph we launched from the tokenDistro with the GIVpower contract info once it's deployed?

GIVpower is built on top of GardenUnipool! so we must first apply some modifications to that contract and make it an extension of an ordinary unipool!
Then we can deploy and add it to the subgraph, probably will be easy and won't need much modification on subgraph

**Comment by laurenluz** [comment]
As discussed in the GIVeconomy call, it would be great to have @aminlatifi take this one, and then we should talk to (and compensate) Sem for auditing the contracts.

@aminlatifi can you work on this gradually over the next couple of weeks while you're working on Canon?

FYI @MoeNick

**Comment by divine-comedian** [comment]
Amin and I worked on first version of GIVpower with Unipool - next step is to develop automated tests for modified contract.

**Comment by divine-comedian** [comment]
Sorry tests are done and the contract was deployed on OP Goerli a few weeks ago - We should keep this issue open until we have production deployment done and setup

**Comment by divine-comedian** [comment]
@MoeNick @laurenluz 

GIVpower has been deployed to op mainnet
https://optimistic.etherscan.io/address/0x301c739cf6bfb6b47a74878bdeb13f92f13ae5e7

I also granted it the distributor role on the op mainnet token distro

**Comment by MoeNick** [comment]
This is blocked by a reward notifier bot!

**Comment by MoeNick** [comment]
https://github.com/Giveth/giv-token-contracts/pull/92#issuecomment-1695115272

**Comment by aminlatifi** [comment]
@divine-comedian Next step:

- [ ] Set 0xbf6F3Ec9779079b91360D15FAb06dCEaB25Fd427 as reward distributor on the [Optimism UnipoolGivpower](https://optimistic.etherscan.io/address/0x301c739cf6bfb6b47a74878bdeb13f92f13ae5e7)
- [ ] Fill 0xbf6F3Ec9779079b91360D15FAb06dCEaB25Fd427 with gas on Optimism Mainnet network
- [ ] Top up Optimism UnipoolGivpower (0x301C739CF6bfb6B47A74878BdEB13f92F13Ae5E7) balance on TokenDistro (0x301C739CF6bfb6B47A74878BdEB13f92F13Ae5E7) - By assign method. The value to assign is 622,000 GIV according to [this](https://docs.google.com/spreadsheets/d/14kj7eIJg_hTf8BwVoGvPEWAo2Z6O18lA2bd1jOGZaNc/edit#gid=1038166692)
- [ ] Be sure there are enough GIV in the tokenDistro to pay rewards

**Comment by divine-comedian** [comment]
One small detail 

Amin and I updated the UnipoolGIVpower balance to 425,500 - not 622,000 - this was because our date to start rewards will be Sept 5, Not August 8 as initially marked in the sheet
