### ISSUE TITLE
GIVpower balance should consider GIVpower from multiple chains

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2498]
We will be deploying GIVpower on Optimism and eventually (most likely) Celo.

We need to adjust the backend so that the user's GIVpower balance is the sum of GIVpower from Gnosis Chain & from Optimism (and we should build this so it's easy to add more chains later).

**Comment by aminlatifi** [comment]
> Do we need an issue for the frontend as well? To change where we get the number from?

Yes, we need support multiple chaings too

**Comment by aminlatifi** [comment]
> Do we need an issue for the frontend as well? To change where we get the number from?

Yes, we need support multiple chaings on the frontend too

**Comment by aminlatifi** [comment]
https://github.com/Giveth/GIVeconomy/issues/869

**Comment by MoeNick** [comment]
Can we test this one @aminlatifi ?

**Comment by aminlatifi** [comment]
We haven't deployed GIVpower on other networks yet
