### ISSUE TITLE
"Last Updated" time on homepage is wrong

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#250]
All the projects say that they were updated within the last few hours... and it seems like each row has a different "last updated" time. This can't be true. I'm testing on live.

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/3d33d73e-2fbb-41c9-aafc-6788b89cf744)

**Comment by CarlosQ96** [comment]
Ok here the migration didn't run correctly. Ill hotfix it.
Since we did not have the updateAt column initially we set it as the creationDate. Thats the expected outcome. Will update as soon as I upload the hotfix.

**Comment by CarlosQ96** [comment]
Actually I am not completely sure, there are projects that have last updated months ago. But it seems something is updating projects.
any .save() call upon our column UpdateDateColumn().
@mohammadranjbarz should we remove that column and update ourselves manually the value? 
Trace methods might change this value automatically

**Comment by mohammadranjbarz** [comment]
> Actually I am not completely sure, there are projects that have last updated months ago. But it seems something is updating projects. any .save() call upon our column UpdateDateColumn(). @mohammadranjbarz should we remove that column, make it a normal date column and update ourselves manually the value? Trace methods might change this value automatically, when they run.
> 
> It would be only changing it only when editing the project, on creation and when project updates are added.

Sorry I was a little busy so I screwed up and missed your comments before implementing PR but I think my PR would solve the problem

**Comment by mohammadranjbarz** [comment]
@laurenluz @MoeNick 
1. I wrote a migration to fill `updatedAt` field of projects with creation time of their last `projectUpdate`
2. Now We change `updatedAt` of project when user edits his/her project and when a projectUpdate will be created
We will merge it with this spec for hotfix, but if you want to change `updatedAt` when status of projects change in admin-bro, or user activate/deactivate his/her project, please create another issue, we can do it

**Comment by laurenluz** [comment]
I think having `updatedAt` change when a user edits his/her project & when projectUpdate is created is the best solution :)

**Comment by mohammadranjbarz** [comment]
> I think having `updatedAt` change when a user edits his/her project & when projectUpdate is created is the best solution :)

Nice, so it's on staging and production, you can test it to see wether works good or not

**Comment by laurenluz** [comment]
Looks good on production!
