### ISSUE TITLE
Frontend update to make GIVpower balance the sum of GIVpower on multiple chains

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2503]
Following deployment of GIVpower staking on Optimism (and eventually celo) we should ensure that the GIVpower balance number is correctly to sum of GIVpower from all chains.

**Comment by MoeNick** [comment]
@aminlatifi can we test this one?

**Comment by aminlatifi** [comment]
We haven't deployed GIVpower on other networks

**Comment by laurenluz** [comment]
we haven't finished the design & frontend, but I thought mitch was working on deploying the staking contracts on Optimism goerli, no? @divine-comedian

**Comment by divine-comedian** [comment]
GIVpower and GIVbacks contracts are up on op goerli

**Comment by MohammadPCh** [comment]
@laurenluz Sorry I missed this issue, It's done and testable on GIVeconomy from about one week ago.

**Comment by divine-comedian** [comment]
I think this is related to the balance aggregator right? Can we use this on staging.giveth.io for both Gnosis Chain and Optimism Goerli?  @MohammadPCh 

If this is approved then @maryjaf should test 

If I understand this should mean that you should stake your GIV into the GIVpower farm on Gnosis Chain and Optimism and your combined GIVpower for boosting should be the calculated sum from both chains..

**Comment by divine-comedian** [comment]
@aminlatifi did we finish this issue with the balance aggregator?

**Comment by maryjaf** [comment]
I finished test of GIVpower OP & Gnosis scenarios
And all raised problems(stake, combined GIVpower &...) during the test were discussed on this issue :https://github.com/Giveth/giveth-dapps-v2/issues/2512
