### ISSUE TITLE
Anonymous donations are showing up registered w my user profile

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#251]
I donated 10 GIV normally and then donated 2 GIV & 4 GIV with the "anonymous" check box ticked, but both are showing up with my name.

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/46cef22d-4676-4726-85c1-61c4e3a42ea0)

On the project page:
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/f3652ff8-1dde-4afa-8b0b-0b86c50a2a35)

In "My donations":
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/c8020b76-56b7-469b-875f-dfc0bc524d51)

**Comment by pkretzschmar** [comment]
@laurenluz did some test yesterday, and it was working fine. Could you try to reproduce it, and send me more details?

**Comment by laurenluz** [comment]
ok interesting, yesterday it wasn't working, but today I can't reproduce... I tried both with brave shields up and then down. Maybe it got resolved somehow?

![image](https://user-images.githubusercontent.com/75490971/158875555-4d34f232-9b79-4e1d-9493-70be0ea750bc.png)
