### ISSUE TITLE
Add GIVpower staking to GIVfarm on Optimism

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2512]
We need to accomodate multiple chains for GIvpower staking and perhaps need to reflect this in the design.

We need to:
- Add Optimism Chain to the GIVfarm (and later, Celo)
- Make GIVpower multi-chain
- Show GIVpower total as the sum of GIVpower from multiple chains

**Comment by mosaeedi** [comment]
The new network selector is on the GIVfarm tab.

[link to Figma](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/GIVeconomy?type=design&node-id=22477-208069&t=DJmTFSmLNOONRQli-4)

### Network dropdown on GIVfarm

[Link to Figma](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/GIVeconomy?type=design&node-id=22877-217146&t=DJmTFSmLNOONRQli-4)

![Screenshot 2023-06-11 at 5.13.00 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/6c9c840d-c289-4967-8e65-745f49164dd8)


### Reward card Connected and not connected state

![Screenshot 2023-06-11 at 5.15.04 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/54c1c486-833a-4245-a325-93be5053d04b)

### Switch network modal filter to available networks on GIVfarm.

![Screenshot 2023-06-11 at 5.15.46 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/afedfcdb-87ab-44aa-9c03-35a14ea6b070)

**Comment by mosaeedi** [comment]
Is this what you are looking for @laurenluz ?
GIVpower staking card with different APR Copy. I think the rest of the card is the same on any network! Right?

<img width="734" alt="Screenshot 2023-06-21 at 5 18 05 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/1dd4635d-8a5b-4585-93a9-9a3924280189">

**Comment by laurenluz** [comment]
hmm - what do you think about have just one card... and then having both APRs on it? and we add a "switch to Optimism" to the card?

then we don't need to add anything extra to the back of the cards, and it's more clear that you can stake GIV on either chain for the same result 🤔

**Comment by laurenluz** [comment]
this is obviously ugly and way too much info on one card... what what do you think about this general idea? somehow showing both APRs and the option to switch network on a single card?

is there someway we can do that more elegantly and with less CTAs? @mosaeedi 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/415c8431-0da9-4547-b876-63888129d0b2)

**Comment by mosaeedi** [comment]
Farm cards with the improvements to show APR on all networks.

[Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/GIVeconomy?type=design&node-id=23050-217398&mode=design&t=PblIVCI7D1ZGiCil-4)

@laurenluz

**Comment by laurenluz** [comment]
@MohammadPCh - here is the design for multi-chain GIVpower. I think the contracts are already ready for this on Optimism Goerli, so now that we have added Optimism Goerli to staging (it's done, right?), we can develop this and start testing.

Check the figma, and lmk if you have any questions!

**Comment by aminlatifi** [comment]
> @divine-comedian @aminlatifi - do we have the unipool deployed on Optimism goerli yet? cherik will need it to implement this

@laurenluz the PR https://github.com/Giveth/givpower/pull/32 is ready to review by a third person. Nevertheless, we can deploy this beta version in case we are in rush for demo/staging

**Comment by divine-comedian** [comment]
We have deployed GIVpower to Optimism Goerli - Amin needs to make some mods to the subgraph but should be mostly good to go.. 

It can be found here:
https://goerli-optimism.etherscan.io/address/0x632ac305ed88817480d12155a7f1244cc182c298

**Comment by MoeNick** [comment]
@aminlatifi Are you the one who does the subgraph? how can I help?

**Comment by aminlatifi** [comment]
> @aminlatifi Are you the one who does the subgraph? how can I help?
Has update here https://github.com/Giveth/Roadmap/issues/84#issuecomment-1651648764

**Comment by maryjaf** [comment]
1- The showing GIVpower in this modal (after locking) isn't correct and the GIVpower before lock is shown
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/2513a099-fa2b-4049-9032-231dc1ea2928)

2-the calculated GIVpower in this page after locking isn't correct and only the locked amount is added to the previous number without considering its coefficient 
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/60a64279-94d3-478c-a028-4ed4e6abf77c)
@MohammadPCh

**Comment by maryjaf** [comment]
3-
Project's GIVpower in "my GIVpower" and project detail are different. is it related to that backend's changes are not ready to be tested?

<img width="1419" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/1ca6e1cc-ab4a-446d-9df1-9f9c8b9737c7">
<img width="1437" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/55dbf40c-a9d7-447a-93ce-ea501e55fb33">

**Comment by maryjaf** [comment]
3-
Total GIVpower of other users should be  the summation of Gnosis & OP GIVpowe
4-
When Network is set on OP Goerli By taping on [Buy GIV token](https://github.com/Giveth/giveth-dapps-v2/issues/2512) the below pic is shown

<img width="1337" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/d975f1d6-8544-40cb-920f-f16ce00bb49a">
<img width="1154" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/d3b8f631-e801-44cc-8c7a-6a041d9a9a4f">

**Comment by divine-comedian** [comment]
> 3- Total GIVpower of other users should be the summation of Gnosis & OP GIVpowe 4- When Network is set on OP Goerli By taping on [Buy GIV token](https://github.com/Giveth/giveth-dapps-v2/issues/2512) the below pic is shown
> 
> <img alt="image" width="1337" src="https://user-images.githubusercontent.com/111529185/260696350-d975f1d6-8544-40cb-920f-f16ce00bb49a.png"> <img alt="image" width="1154" src="https://user-images.githubusercontent.com/111529185/260696482-d3b8f631-e801-44cc-8c7a-6a041d9a9a4f.png">

@MohammadPCh on optimism we can link here for where we have some liquidity on Optimism 

https://app.velodrome.finance/swap?from=eth&to=0x528CDc92eAB044E1E39FE43B9514bfdAB4412B98c

**Comment by divine-comedian** [comment]
FYI on Optimism we should still use uniswap since cowswap does not exist there 

We have some DAI/GIV liquidity on Uniswap 
https://app.uniswap.org/#/swap?chain=optimism

**Comment by maryjaf** [comment]
> 1- The showing GIVpower in this modal (after locking) isn't correct and the GIVpower before lock is shown ![image.png](https://camo.githubusercontent.com/598b19c91d16cb0955b5ee76a6cc4f6d5ffb26d96fff44d5325e9e77e410abc4/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f32353133613039392d666132622d343034392d393033322d323331646331656132393238)
> 
> @MohammadPCh

Thanks @MohammadPCh This problem has been resolved

**Comment by maryjaf** [comment]
I'v been facing this error when I taped on BOOST
https://giveth-dapps-v2-git-add-op-givpower-givethio.vercel.app/project/giveth?open=boost
<img width="1424" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/1f712b55-61d8-4f60-9665-ca75c743907b">
plz check @MohammadPCh

**Comment by maryjaf** [comment]
5- When I removing some projects on my GIVpower list, GIVpower of other projects isn't changed

**Comment by maryjaf** [comment]
> 3-
> Total GIVpower of other users should be the summation of Gnosis & OP GIVpowe

Now this problem has been resolved but another problem has been happened 
pic 1 
my wallet is set on account 5 and see my givpower  and every thing is fine
<img width="1440" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/284cea79-1af2-4699-a780-00f2e43dc393">

I change my wallet and check the account 5 user
https://giveconomy.vercel.app/user/0xf577ae8b97d839b9c0522a620299dc08792c738c?tab=givpower
<img width="1384" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/bd503346-3065-4582-88e6-d06df6008787">

**Comment by maryjaf** [comment]
> > 3-
> > Total GIVpower of other users should be the summation of Gnosis & OP GIVpowe
> 
> Now this problem has been resolved but another problem has been happened pic 1 my wallet is set on account 5 and see my givpower and every thing is fine <img alt="image" width="1440" src="https://user-images.githubusercontent.com/111529185/261044192-284cea79-1af2-4699-a780-00f2e43dc393.png">
> 
> I change my wallet and check the account 5 user https://giveconomy.vercel.app/user/0xf577ae8b97d839b9c0522a620299dc08792c738c?tab=givpower <img alt="image" width="1384" src="https://user-images.githubusercontent.com/111529185/261044977-bd503346-3065-4582-88e6-d06df6008787.png"> @MohammadPCh

This problem has been existing on production, should I create separate issue for this??

**Comment by divine-comedian** [comment]
@maryjaf @MohammadPCh - where is this being tested? 

Can't seem to find it available on staging... 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/ffabb7e5-239b-49fb-b649-1b4f4de5587d)

**Comment by maryjaf** [comment]
> @maryjaf @MohammadPCh - where is this being tested?

https://giveconomy.vercel.app/

**Comment by maryjaf** [comment]
@MohammadPCh It seems the showing GIVpower is buggy
For example sometimes the givpower on gnosis is shown incorrectly 
My GIVpowr is 1532.21 but I saw below pic and by refreshing this problem has been resolved
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbHdRIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--12ee6e4c298111788520a47a11729328f6b0e3cd/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbDBRIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4b2e01be935a651838e4bfb4e0fb9f173c9e23a4/image.png)

**Comment by MohammadPCh** [comment]
@maryjaf Thanks for reporting,
What's you network?

**Comment by MohammadPCh** [comment]
Sorry, my question was not complete.
I need to know your GIVpower on each chain.  this `687.5` is your GIVpower on gnosis? or on OP? (you see your current chain balance? )

**Comment by maryjaf** [comment]
> @maryjaf Sorry, my question was not complete. I need to know your GIVpower on each chain. this `687.5` is your GIVpower on gnosis? or on OP? (do you see your current chain balance? )

I'm not sure that 687.5 is related to Gnosis or OP   but when my network is set on gnosis I saw 687.5 
and I can't reproduce it

**Comment by maryjaf** [comment]
> 3- Total GIVpower of other users should be the summation of Gnosis & OP GIVpowe 4- When Network is set on OP Goerli By taping on [Buy GIV token](https://github.com/Giveth/giveth-dapps-v2/issues/2512) the below pic is shown
> 
> <img alt="image" width="1337" src="https://user-images.githubusercontent.com/111529185/260696350-d975f1d6-8544-40cb-920f-f16ce00bb49a.png"> <img alt="image" width="1154" src="https://user-images.githubusercontent.com/111529185/260696482-d3b8f631-e801-44cc-8c7a-6a041d9a9a4f.png">

kindly reminder

**Comment by divine-comedian** [comment]
@MohammadPCh - on Optimism let's link to Uniswap - related to #1905

**Comment by maryjaf** [comment]
> @MohammadPCh It seems the showing GIVpower is buggy For example sometimes the givpower on gnosis is shown incorrectly My GIVpowr is 1532.21 but I saw below pic and by refreshing this problem has been resolved I haven't found the scenarios yet [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbHdRIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--12ee6e4c298111788520a47a11729328f6b0e3cd/image.png)
> 
> [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbDBRIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4b2e01be935a651838e4bfb4e0fb9f173c9e23a4/image.png)

I'v faced this issue again , Instead of total GIVpower on gnosis and OP,  GIVpower on gnosis is shown 
network: Gnosis
user: 0xA1179f64638adb613DDAAc32D918EB6BEB824104
GIVpower on Gnosis:125
GIVpower on OP: about 1207.1
Total:  1,332.1

<img width="1354" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/17c3df7e-6719-43c4-80a3-faa98937a2ff">
<img width="1226" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/08dbb85e-352c-48b1-b667-b0cfb14fde50">
@MohammadPCh

**Comment by MoeNick** [comment]
@MohammadPCh this one needs your attention pls.

**Comment by maryjaf** [comment]
> I'v faced this issue again , Instead of total GIVpower on gnosis and OP, GIVpower on gnosis is shown

Last Update:

Resolved problems:
-The issue related to bug in showing user's table of project's givpower has been resolved
-showing wrong user's givpower when my network is on Polygon or Celo has been resolved
- OP giv link is set : https://app.uniswap.org/#/swap?chain=optimism&outputCurrency=0xc916Ce4025Cb479d9BA9D798A80094a449667F5D

Open problems:
This bug happens again:
1-On GIVeconomy branch when my network is set on Optimism(not optimism goerli) and other undefined chains, by taping on GIVfarm the below pic is shown
<img width="1436" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/0c1756cf-c096-4627-a7d0-47bc683049eb">

2- for some account on production  on Optimism GIVfarm reward is calculated 
for example: 
0xcd192b61a8Dd586A97592555c1f5709e032F2505: GIVfarm reward:  0.08 GIV
0xf577Ae8b97d839B9c0522A620299DC08792c738c : GIVfarm reward: 0

@MohammadPCh @divine-comedian @MoeNick

**Comment by MohammadPCh** [comment]
@maryjaf Nice Catch,
Will fix them soon.

**Comment by maryjaf** [comment]
> 1-On GIVeconomy branch when my network is set on Optimism(not optimism goerli) and other undefined chains, by taping on GIVfarm the below pic is shown

This issue still exists on test branch , plz check @MohammadPCh 
https://giveth-dapps-v2-git-fix-reward-on-givfarm-givethio.vercel.app/givpower
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/d16b0bfe-e2cd-40b3-a5e9-fbbd064ca828)

**Comment by maryjaf** [comment]
Thanks @MohammadPCh All of open issues have been resolved.
