### ISSUE TITLE
Create new function in token distro to "send praise" so it shows up in GIVstream history table

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2523]

**Comment by divine-comedian** [comment]
To clarify: we should add a new function to the tokenDistro! 

currently we have a function called sendGIVbacks that emits an event that is picked up and registered in the user's history table that they received GIVbacks

similarly we should create a function called `sendPraise` that does the same thing but emits a slightly different event that registers that the user received praise rewards, not GIVbacks


On Gnosis Chain that's this contract:
https://blockscout.com/xdai/mainnet/address/0xc0dbDcA66a0636236fAbe1B3C16B1bD4C84bB1E1/write-proxy#address-tabs

**Comment by divine-comedian** [comment]
I wrote the update to our tokendistro implementation, amin upgraded the token distro on test deployment 7 - I need to test actually making the tx and see if it shows up
