### ISSUE TITLE
Subgraph work for adding praise to GIVstream history table

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2524]

**Comment by divine-comedian** [comment]
@mateodaza could you confirm if the work is done or is there more to do? When we move this to production do we need to update anything on the subgraph?

**Comment by aminlatifi** [comment]
@divine-comedian I made this PR #2566 to support praise. I granted one of your wallets to distribute reward (GIVback, Praise, ...) on test env token distro `0x18a46865AAbAf416a970eaA8625CFC430D2364A1`. You can send praise reward to any other wallet you like and test with the PR's preview link.

**Comment by aminlatifi** [comment]
@divine-comedian For you https://discord.com/channels/@me/809108194999533568/1098740699719012452

**Comment by laurenluz** [comment]
We should inform the devops guys that they need to add this to studio

**Comment by MoeNick** [comment]
@aminlatifi how can proceed fo changing the code base?

**Comment by aminlatifi** [comment]
@MoeNick @divine-comedian On production we don't have any blocker now, we deployed latest version of subgraph to hosted service, the one we use still in the production

**Comment by geleeroyale** [comment]
Ok thanks for clarifying - the task required was unclear to me. I will update the studio graphs.

**Comment by geleeroyale** [comment]
Subgraph has been updated, deployed and will be published pending your signature @aminlatifi 

https://app.safe.global/transactions/queue?safe=eth:0x57D21de42B12Ad58B2ccECA126Ed6f364C9eb6f2

**Comment by aminlatifi** [comment]
> Subgraph has been updated, deployed and will be published pending your signature @aminlatifi
> 
> https://app.safe.global/transactions/queue?safe=eth:0x57D21de42B12Ad58B2ccECA126Ed6f364C9eb6f2

The multisig needs one member approval, so you can yourself execute them without being blocked by others.
