### ISSUE TITLE
Frontend for showing praise on GIVstream history table

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2525]

**Comment by divine-comedian** [comment]
@mosaeedi 

Here! Please update us when you have a icon ready for us to show on the givstream table.

**Comment by aminlatifi** [comment]
Most of the frontend is ready, just appropriate ICON in the stream history
to design by @mosaeedi , then add to design system and then to frontend

**Comment by mosaeedi** [comment]
On it

**Comment by mosaeedi** [comment]
<img width="86" alt="Screenshot 2023-05-01 at 6 26 11 PM" src="https://user-images.githubusercontent.com/13708322/235471964-526a2d06-8a1e-4a62-bf2d-8b959453965e.png">
Here is the icon

**Comment by mosaeedi** [comment]
The link to icon on Giveth DS

[Link to Figma](https://www.figma.com/file/d3ciTS36toS9mra0RAPMe2/Giveth-Design-System-v0.1?node-id=4589-64891&t=8Prs5Rru55LgL7F3-4)

**Comment by divine-comedian** [comment]
@MohammadPCh  

here is the updated design from Mo:

![image](https://user-images.githubusercontent.com/67759413/236284077-189c6530-5c27-4b73-815f-ae1f736a3062.png)


It should already be in the design system. 

What other info do you need to carry out this task? Are you the right person for it?

**Comment by divine-comedian** [comment]
Great work! Cherik! This is now live on staging 
https://staging.giveth.io/givstream

I can confirm it shows up on the GIVstream history table 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/eb5ebcbf-392d-43ad-9193-e5b57b6b38bd)
