### ISSUE TITLE
Design - Instant Boost

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2526]
We are updating the project sorting by GIVpower to be more immediate. Users will be able to boost projects with GIVpower, and then their default position in the project sort will be affected within 5 min.

We need design to explain to the user, after the boost a project, that:
- The project's position on the projects page will be updated within 5 min.
- The project's rank will be updated at the end of the current GIVbacks round.

@mosaeedi

**Comment by laurenluz** [comment]
@mosaeedi I was thinking about this more after writing the [mini-spec](https://www.notion.so/giveth/Instant-Boost-Mini-Spec-cea340e1bbf2456f8c7b237c07e5f8aa) and I think we should:

- [ ] Put some indication on the project page, maybe a tooltip or something on hover on the project card, inviting the user to boost projects to change their position in the sort. Here is some copy: "Want to see this project higher up? Boost it with your GIVpower and make it more visible to potential donors." 

- [ ] Change the copy on the boosting confirmation modal to:
Title: Project boosted!
Text: Nice! You boosted this project with x% of your GIVpower. Keep an eye on the projects page, as it'll move up the list and become more visible to others within 5 minutes or less!
Button: Go to Projects Page
Subtext: See your GIVpower Allocations
Remove "dismiss"

I think we can remove the part about the changing rank, because I think we need to improve the communication around rank and GIVbacks % anyway, and it's a bigger [issue](https://github.com/Giveth/giveth-dapps-v2/issues/1887).

![image](https://user-images.githubusercontent.com/75490971/234137860-624ecc74-46b3-4038-9d48-f107f8ebc078.png)

**Comment by mosaeedi** [comment]
I'm working on the first suggestion, @laurenluz 

> Put some indication on the project page, maybe a tooltip or something on hover on the project card, inviting the user to boost projects to change their position in the sort. Here is some copy: "Want to see this project higher up? Boost it with your GIVpower and make it more visible to potential donors."

It should be something noticeable and also not very distracting for users!

**Comment by mosaeedi** [comment]
I have compiled a list of necessary improvements to effectively communicate the background happenings to our users.

**1. Success modal**
Once the user boosts a project, we will display a success modal. In this modal, we need to indicate when the project's rank will be updated.

[Link to Figma](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?node-id=920-56629&t=PufNboTMnlqsdv5i-4)

<img width="673" alt="Screenshot 2023-05-01 at 3 18 36 PM" src="https://user-images.githubusercontent.com/13708322/235447729-a6816ac9-a167-45fe-a771-a14d16ca386f.png">

---

**2. On the Givpower tab in the project detail the public view**
On this tab, under the current/projected rank card, we can show when the project rank is going to be updated.

[Link to Figma](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?node-id=1044-57701&t=PufNboTMnlqsdv5i-4)

<img width="773" alt="Screenshot 2023-05-01 at 3 20 20 PM" src="https://user-images.githubusercontent.com/13708322/235447893-bf8606dc-c85d-4e39-b494-a4d167f075f2.png">

---

**3. Sending notification**
When the project rank is updated after 5 minutes, we have to send a notification to the user to let them know that the project rank is updated.
_Note: Only the person who boosted the project will receive this notification just once!_

[Link to Figma](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?node-id=1046-59451&t=PufNboTMnlqsdv5i-4)

<img width="1260" alt="Screenshot 2023-05-01 at 3 27 23 PM" src="https://user-images.githubusercontent.com/13708322/235448611-b0703009-5278-4430-9dc6-9138e430a51c.png">

**Comment by laurenluz** [comment]
Hey @mosaeedi - thanks for these updates! Some clarifications:
- The rank won't update after 5 min, only the project's position in the default sorting. 
- We won't accurately be able to predict the time the sort will change... it will vary, so I think we should remove the countdowns.

So, with that in mind, some suggested changes:
1. Success modal - remove the "project rank will update in x min"

2. Project detail GIVpower tab - remove the "project rank will update in x min". Also... it is true that project ranked #1 will yield more GIVbacks for donors... but it is not true that project #1 will be positioned on top.

I think we need something else for the project page - I'll leave comments in the figma.

3. Sending notification - @aminlatifi - what are your thoughts about adding in a notification to users who boosted the project within the last 5 min... when the project moves position in the sorting?

**Comment by aminlatifi** [comment]
@aminlatifi I am 99% sure we can send notifications on rank change.

**Comment by MoeNick** [comment]
> @aminlatifi I am 99% sure we can send notifications on rank change.

@aminlatifi @laurenluz 
@mohammadranjbarz prepared this event on staging and seems it works now, but the receivers of notif are only owners of projects.

**Comment by laurenluz** [comment]
@aminlatifi @MoeNick but instant boost doesn't have to do with a rank change (these designs need to be changed, Mo was mistaken, I left comments)

Instant boost is just changing the position in the project sort. I was asking if THAT would be too challenging to send notifications on... my instinct is that its a bit too much.

**Comment by mosaeedi** [comment]
![Screenshot 2023-05-03 at 7.39.21 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/a93bd1c6-c360-424e-8762-c2b155e7b17b)

Sorry for the delay.
I've updated the design and removed the unnecessary.

**Comment by mosaeedi** [comment]
Please take a look:

[Link to Figma](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?node-id=116-46262)

**Comment by laurenluz** [comment]
So @mosaeedi can we finalize this? There are two design changes:

1. Update success modal - [Link to Figma](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?node-id=116-46262)
![image](https://user-images.githubusercontent.com/75490971/236073982-d917f1b9-3dce-4cd4-a6c0-d548cb334123.png)

2. Add GIVbacks % and message to project single page - [Link to Figma](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?node-id=1170-58435&t=Oo2Zbk5tZtoIDngd-4)
![image](https://user-images.githubusercontent.com/75490971/236073928-54b671cc-6464-4525-b998-d03af3a1389a.png)

Are we ok to go ahead with this? We can even add 2. to our existing project single page design and get this out the door now. Can you help w. that?

**Comment by laurenluz** [comment]
ok design is done! https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?node-id=1044-57701&t=Npzcw6QxmI4lHHY7-4
