### ISSUE TITLE
GIVbacks notification is misleading

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#2527]
People are confused because the notification says they have a certain amount to claim, but when they click the link to go to the claim page, the number does not match. 

![image](https://user-images.githubusercontent.com/74267818/232662954-d28b1798-e13f-4363-81a1-bbcbe513f16c.png)

We should figure out a way to communicate to the user that only a certain percentage is claimable right away and the rest will be streamed to them.

**Comment by divine-comedian** [comment]
I think this is a back-end issue, who can take it? @CarlosQ96 @mohammadranjbarz 

We should make it simple and change the notification to read:

"You have [GIVbacks](https://giveth.io/givbacks) waiting to be claimed!"

**Comment by divine-comedian** [comment]
@CarlosQ96 is this issue still relevant?

**Comment by Reshzera** [comment]
@RamRamez  Yes, I'll take a look

**Comment by Reshzera** [comment]
@maryjaf @LatifatAbdullahi This Issue is ready to be tested on the staging, could you please take a look?

**Comment by maryjaf** [comment]
> @maryjaf @LatifatAbdullahi This Issue is ready to be tested on the staging, could you please take a look?

I think the giveback should be set manually for my user that I could be able to check the notification
0xcd192b61a8Dd586A97592555c1f5709e032F2505

0xD5db3F8B0a236176587460dC85F0fC5705D78477

**Comment by divine-comedian** [comment]
> 0xD5db3F8B0a236176587460dC85F0fC5705D78477

I sent you some GIVbacks manually but I'm not sure if it's enough to trigger the notification...

**Comment by maryjaf** [comment]
> > 0xD5db3F8B0a236176587460dC85F0fC5705D78477
> 
> I sent you some GIVbacks manually but I'm not sure if it's enough to trigger the notification...

Thanks @divine-comedian 
But I haven't received any notification related to  givback

**Comment by RamRamez** [comment]
@ae2079 could you please help @Reshzera and @maryjaf for testing this issue?

**Comment by ae2079** [comment]
> @ae2079 could you please help @Reshzera and @maryjaf for testing this issue?

Sure

**Comment by divine-comedian** [comment]
> I use this data:
> 
> ```
> {
>   "eventName": "GIVback is ready to claim",
>   "sendEmail": false,
>   "sendSegment": false,
>   "userWalletAddress": "0x85A2779454C0795714cA50080b67F6aCf453F264",
>   "metadata": {
>     "contractName": "Gnosis Chain Token Distro",
>     "transactionHash": "testTransactionHash",
>     "network": 100,
>     "amount": "10"
>   }
> }
> ```
> 
> and send a request to this URL: https://notification.serve.giveth.io/v1/thirdParty/notifications and get this error:
> 
> ```
> {
>     "message": "Notification type is invalid",
>     "httpStatusCode": 400
> }
> ```
> 
> I'll try to debug it locally (maybe I missed some fields of data)

OK - also coordinate with @Reshzera as needed. since he made the migration updating the notification.

**Comment by ae2079** [comment]
The previous error was related to the header that I used another microservice secret and it works after changing it to giveconomy-notification-service.
another problem that I face with it now, is related to migration execution errors on staging:
![Screenshot 2024-07-31 003352](https://github.com/user-attachments/assets/e92f45d4-f9ae-499b-b9b8-ad1e82d5aefc)
and because of that, I got the wrong message (previous version):
![Screenshot 2024-07-31 002505](https://github.com/user-attachments/assets/3ebc9bc4-97a4-4f62-9af5-ec7f1001edc7)

**Comment by ae2079** [comment]
![image](https://github.com/user-attachments/assets/6bee69cb-ad20-44c7-ab48-f5c1e7d74393)
after fixing the data manually, it works
(we have a migration execution problem that is not related to changes in this issue)

**Comment by divine-comedian** [comment]
Thanks for debugging that @ae2079 - so the screenshot above is from staging? If so we can say this feature has passed QA.

**Comment by ae2079** [comment]
> Thanks for debugging that @ae2079 - so the screenshot above is from staging? If so we can say this feature has passed QA.

you're welcome, yes it is from staging, but the migration issue remains and I'm working on that. (To deploy it on production, we need to fix this problem first)

**Comment by ae2079** [comment]
> > Thanks for debugging that @ae2079 - so the screenshot above is from staging? If so we can say this feature has passed QA.
> 
> you're welcome, yes it is from staging, but the migration issue remains and I'm working on that. (To deploy it on production, we need to fix this problem first)

@divine-comedian 
Now, the migration issue is fixed and we can deploy it whenever you want

**Comment by divine-comedian** [comment]
great! we should make sure we include it in our next general release for the FE and BE

**Comment by maryjaf** [comment]
It seems this change hasn't been deployed on prod yet 
I've commented only for kindly remind this for next release 
![image](https://github.com/user-attachments/assets/9ac4c938-e744-4df9-9f70-1ba7018a220f)

**Comment by divine-comedian** [comment]
@ae2079 does this require a release on the notification-center repo? 

I think our last release was on July 21 so this might have not been included in the impact-graph release

**Comment by ae2079** [comment]
> @ae2079 does this require a release on the notification-center repo?
> 
> I think our last release was on July 21 so this might have not been included in the impact-graph release

yeah, it is on the notification center

**Comment by divine-comedian** [comment]
OK if this doesn't need a release on the impact-graph can we make a release for this repo?

**Comment by ae2079** [comment]
> OK if this doesn't need a release on the impact-graph can we make a release for this repo?

@RamRamez

**Comment by divine-comedian** [comment]
@ae2079 @RamRamez can we confirm that we made a release on notification center to production? if so we can close this one.

**Comment by RamRamez** [comment]
@divine-comedian last week we didn't make a release on notification center to production, but the PR related to this issue is on production
