### ISSUE TITLE
Low pri: When editing my project, there is only an option to "publish" no option to reject changes

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#253]
Ideally:

If I didn't change anything, "publish" should be greyed out
And if I did change something, there should be an option to "cancel" (you know, like... not publish changes & end up w an unlisted project... it can say "cancel" or "reject changes" or something like that... tbh I don't remember what it said on the old version, but there was an option.

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/00fca916-f4db-4360-97c2-97399446389e)

**Comment by divine-comedian** [comment]
testing on `staging.giveth.io`

if I don't make any changes then the `publish` button is greyed out and unclickable 
there is a cancel button - if I make changes while editing and click cancel the changes are reverted and project remains unedited. 

this looks to be working correctly! moving to DONE

**Comment by MoeNick** [comment]
The cancel button was not at prospered design and due to lack of proper analysis, it caused some problems and bugs, @RamRamez solved it right now on staging and its ready for test. @divine-comedian @pkretzschmar 
Moving it back to UAT.

**Comment by divine-comedian** [comment]
tested out cancelling - I can update any sort of information, images, category, project description or title, recipient address. Pressing cancel instead of publish does not save any changes and takes me to the previously visited page. 

Looks to be functioning okay! 

Moving to DONE!
