### ISSUE TITLE
Copy fix - Projects page "All projects" banner

### ISSUE THREAD

**Issue by danelsuga** [Giveth/giveth-dapps-v2#2538]
@ahmadabugosh: https://giveth.io/projects page needs a better h1 text.

currently: SUPPORT CHANGEMAKERS FROM AROUND THE WORLD

suggestions: 

SUPPORT PUBLIC GOODS, SUSTAINABILITY, AND REGENERATION WITH CRYPTO DONATIONS

SUPPORT GLOBAL PROJECTS IN PUBLIC GOODS, SUSTAINABILITY, AND REGENERATION

SUPPORT PUBLIC GOODS AND REFI REGENERATION WITH CRYPTO DONATIONS
(clumsy and convoluted, I know, but it hits the big SEO words!)

GLOBAL PROJECTS IN PUBLIC GOODS, SUSTAINABILITY, AND REGENERATION 

![Screenshot 2023-04-19 10.13.05 AM.png](https://images.zenhubusercontent.com/6066d509782b4d63df5cd761/5bbf240f-67a7-47e9-acf1-bdda2aba5d83)

@laurenluz 
@c0ric0ri 
@clara-zi

**Comment by laurenluz** [comment]
@RamRamez can you change the subtext here to:

SUPPORT GLOBAL PROJECTS IN PUBLIC GOODS, SUSTAINABILITY, AND REGENERATION WITH CRYPTO DONATIONS

**Comment by RamRamez** [comment]
> @RamRamez can you change the subtext here to:
> 
> SUPPORT GLOBAL PROJECTS IN PUBLIC GOODS, SUSTAINABILITY, AND REGENERATION WITH CRYPTO DONATIONS

Done! (PR #2541)
