### ISSUE TITLE
Add archived label to FOX farm & change archive label copy

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2539]
- [x] The FOX rewards have run out! We should put a label on this farm card that says that the rewards have run out, but we should NOT hide it behind the archived toggle yet.

I will make another issue when it's time to hide it. I'm asking Shapeshift if they want to extend the rewards or not

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/37f68873-4c85-4518-a307-aed664724d39)

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/7868d0ef-5c0c-4e24-8e2d-8f051660cd50)

- [x] Also! can we change the copy on all these labels to say:

Title: ARCHIVED
Subtext: This farm has ended. You can still harvest your rewards and unstake your tokens.
Button: Got it

@RamRamez can you take this?

cc @MoeNick @WhyldWanderer @MohammadPCh

**Comment by RamRamez** [comment]
@laurenluz Please check this:

https://giveth-dapps-v2-git-fox-xdaifarmisoutdated-givethio.vercel.app/givfarm

If you approve the functionality, we can go live

**Comment by laurenluz** [comment]
it looked good to me!
