### ISSUE TITLE
Public view | project tags

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#2544]
**Please note:**

1. We can only have up to 5 tags on every project.
2. If a project has no tags, the place for tags needs to be empty. 

![Group 618.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/dff41652-1ff8-4959-8b84-474bc252c4a3)

## Responsive resource

**WIP.**

## Check the design
[Link to Figma](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?node-id=134-72524&t=yMkADlANl4In8UtA-4)

**Comment by MoeNick** [comment]
@maryjaf you can test.

**Comment by maryjaf** [comment]
<img width="1436" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/f4c10c93-d80d-4ea4-ac34-56fdd65d51a7">
Now I see only verified tag for projects , should the campaign name be  shown? @MohammadPCh 
I added this project to a campaign but i didn't see the tag related to campaign 
<img width="1436" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/4ca8b085-ea07-4796-a72b-8ddb3306203b">

**Comment by MohammadPCh** [comment]
@alireza-sharifpour could you please take a look?

**Comment by alireza-sharifpour** [comment]
We don't have the Backend for this feature yet.

**Comment by MoeNick** [comment]
@mohammadranjbarz is it easy to go or it needs efforts?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz is it easy to go or it needs efforts?

No we need to implement something for that, I created an issue for that

https://github.com/Giveth/impact-graph/issues/1051

**Comment by laurenluz** [comment]
Can we just skip the tags for the QF MVP... include only two options: "Verified" and "< QF round name >" ??

**Comment by MoeNick** [comment]
we don't need campaigns, it's ok .

**Comment by MoeNick** [comment]
Ok, after the QF release I think we can put it in backlog again

**Comment by MoeNick** [comment]
I think this is now unblocked for front end ? Did you test the backed @maryjaf ?

**Comment by MoeNick** [comment]
@maryjaf jan, seems this one is ready for testing too.

**Comment by maryjaf** [comment]
1-project owner view
[Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbERQIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--349c7ceb9babf7aa3c2a7145abcb6cd6f46c911b/image.png)

2- For a project in a round campaign tag isn't shown
For example there are these two projects in a campaign
https://staging.giveth.io/project/how-many-photos-is-too-many-photos 
https://staging.giveth.io/project/a-delicious-help
The campaign tag isn't shown in  "a-delicious-help " project page
@alireza-sharifpour @MohammadPCh

**Comment by alireza-sharifpour** [comment]
For the campaign isn't shown I think we should check it with the backend because we show everything we get from the backend

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcFBQIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--015b66750f3c80683ec034e8a5181a2e3fdd342b/Screenshot%202023-09-25%20at%2011.34.26%20AM.png)


@mohammadranjbarz @CarlosQ96

**Comment by alireza-sharifpour** [comment]
@maryjaf The spacing issue should be fixed.

**Comment by maryjaf** [comment]
checked with @mohammadranjbarz @alireza-sharifpour now campaign tag is shown only for projects which are added manualy to a campaign and @mohammadranjbarz  is working on it

**Comment by maryjaf** [comment]
Plz check this problem in showing tag on mobile project view @alireza-sharifpour 

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/c396d65b-00f9-46b6-b031-ce2e49072550

**Comment by maryjaf** [comment]
> 1-project owner view
> [Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbERQIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--349c7ceb9babf7aa3c2a7145abcb6cd6f46c911b/image.png)

I'v checked but there is now change in this pic on stg
