### ISSUE TITLE
Public view | Project banner

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#2546]
**Please note:**
1. we will present only the project name and the project creator on the new banner.

![New project banner](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/7b41ab2b-a954-484e-a380-a53e2531d5e0)
![Mind the gap](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/07b00abe-1c74-4ba1-84da-5d320ac4ad98)

## Responsive resource

**WIP**

## Check the design

[Link to Figma](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?node-id=134-72524&t=yMkADlANl4In8UtA-4)

**Comment by MoeNick** [comment]
Would u please attache the PR?

**Comment by alireza-sharifpour** [comment]
> Would u please attache the PR?

It has two issues, i connected it to #2550 issue.
this is the PR @MoeNick :
https://github.com/Giveth/giveth-dapps-v2/pull/2595

**Comment by maryjaf** [comment]
We have a problem in showing project name for some projects such as below pic, plz check @alireza-sharifpour 
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/5aff683c-8ed2-4157-a154-f76e2d6095ac)

**Comment by alireza-sharifpour** [comment]
> We have a problem in showing project name for some projects such as below pic, plz check @alireza-sharifpour ![image.png](https://camo.githubusercontent.com/d5c7ed057b07701c5fba44d50891e22dfb78f35f09f6b0ab5a83e69776b088f5/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f35616666363833632d386564322d343135372d613135342d663736653264363039356163)

I think it's a design issue: @mosaeedi

**Comment by MoeNick** [comment]
Can @maryjaf start testing?

**Comment by MoeNick** [comment]
@mosaeedi this is a design issue we had for single project page, 
cc: @laurenluz

**Comment by mosaeedi** [comment]
<img width="1181" alt="Screenshot 2023-07-07 at 4 33 42 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/f5194332-6b67-44ae-86aa-2b15f71ce0c1">

There is a transparent background behind the project title but I forgot to mention that before. 
CC: @alireza-sharifpour

**Comment by maryjaf** [comment]
for some projects like this the banner isn't shown correctly 
https://staging.giveth.io/project/test-issue-173
plz check? @alireza-sharifpour

**Comment by MohammadPCh** [comment]
@alireza-sharifpour I suggest to show our old place holder there, can you take it?
