### ISSUE TITLE
Public view | donation & GIVpower card

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#2547]
**Please note:**
1. The donation and GIVpower can be zero! In that case, there is a **zero-state** design to show.

![Screenshot 2023-04-24 at 11.58.22 AM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/54fae3af-f3c1-4ea5-9c54-1ecb5de1d6fb)

## Responsive resource

WIP

## Check the design

[Link to Figma](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?node-id=857-56699&t=yMkADlANl4In8UtA-4)

**Comment by maryjaf** [comment]
How could I test boosting on this branch?
Because I only see the changes related to Donate @MohammadPCh

**Comment by MohammadPCh** [comment]
@maryjaf  This is our preview link for this Epic: https://givproject.vercel.app/

**Comment by maryjaf** [comment]
The boost option is not shown in this branch I think deployment of this section is not finished @MohammadPCh

**Comment by MohammadPCh** [comment]
@maryjaf The design has been changed totally. and I think it has been updated again these days.

**Comment by MohammadPCh** [comment]
@maryjaf have you had a chance to check the new design?
FYI the new share options will be implemented in the new epic (@MoeNick knows about it)

**Comment by MoeNick** [comment]
@maryjaf you may need to test it again.

**Comment by maryjaf** [comment]
1-new design of givpower tab
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/3dd380cd-0aa2-43a3-a3bc-c04c76dde621)

2-donation tab
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/3fba7934-60c5-466a-90f8-768976b8f1bb)
These pics are different from the attached pic, which one is accepted ? @MoeNick @MohammadPCh

**Comment by MohammadPCh** [comment]
@maryjaf Thanks, It's based on Figma design (The attached pics are outdated)
