### ISSUE TITLE
Trying to post an update, I get:  "Cannot read id null"

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#255]
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/68f697c9-ab8c-490e-b484-4df9809beb2b)

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/1cbff6fc-40c3-4516-8dcc-f563a0a9534f)

**Comment by laurenluz** [comment]
It tells me that... yet it worked... and I accidentally posted twice. Testing on live.

![image](https://user-images.githubusercontent.com/75490971/158684589-982debac-49a7-48a7-9a3c-d6c6f42447e8.png)

**Comment by CarlosQ96** [comment]
Could not reproduce this issue on my account with projects.

**Comment by MoeNick** [comment]
We cant replicate it. move it back to a new issue for now.
Would you pls check it again @laurenluz ? It might be related to DB connection temporary problems.

**Comment by laurenluz** [comment]
It might have something to do with shields on brave. When i lowered shields i was able to post the update.

**Comment by CarlosQ96** [comment]
Ok Parsley tested on Brave and reported the same issue. It seems something related to the Brave Browser.

**Comment by laurenluz** [comment]
I tried again with shields lowered on brave browser and was able to update - I think we need to somehow communicate better to the user about lowering shields...

or better yet, is it possible to dev some solution so that shields don't create this issue? we have a lot of users w brave.
