### ISSUE TITLE
Project banner [Owner view]

### ISSUE THREAD

**Issue by mosaeedi** [Giveth/giveth-dapps-v2#2550]
The project banner for the owner is the same as the public view.

## Design Resource
[Link to Figma](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?node-id=496-53312&t=PufNboTMnlqsdv5i-4)

![Screenshot 2023-05-01 at 4.02.58 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/107b5ef6-3bcf-4099-9b98-b850bb901ed1)

**Comment by maryjaf** [comment]
Same as this comment https://github.com/Giveth/giveth-dapps-v2/issues/2546#issuecomment-1552712882
