### ISSUE TITLE
Project status [Owner view]

### ISSUE THREAD

**Issue by mosaeedi** [Giveth/giveth-dapps-v2#2551]
To give our project owners a better overview of their projects, we gathered the project statuses in a single space.

### Design resource
[Link to Figma](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?node-id=507-54138&t=PufNboTMnlqsdv5i-4)

![Screenshot 2023-05-01 at 4.07.14 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/89956c12-0976-4fe1-8fa9-a1982015a2d5)

### Project status and banner side by side

![Screenshot 2023-05-01 at 4.06.21 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/a0847c01-ad61-4e61-a0ca-9a1276c6ff2a)

**Comment by maryjaf** [comment]
It seems that deployment of this part is not finished @MohammadPCh 
I move this issue to sprint backlog
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/5ebeba75-8b22-4843-b861-cb0361d8254c)

**Comment by MohammadPCh** [comment]
@maryjaf Yes, the designs changed :)

**Comment by MoeNick** [comment]
I think we still have this feature in the owner view, why do we move it back? @MohammadPCh @mosaeedi 
It was planned 3 weeks ago.

**Comment by maryjaf** [comment]
project owner view on stg:
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/07d18cfd-7ccd-45e3-be4d-1ecffe4ea292)
Next mandatory update should be shown ? @MoeNick @MohammadPCh

**Comment by MoeNick** [comment]
@laurenluz 
@mosaeedi si going to change the design a little change

**Comment by mosaeedi** [comment]
Here is the updated design for both the normal project and the QF projects.

### QF Project
<img width="1228" alt="Screenshot 2023-07-11 at 12 40 12 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/b9bee407-096d-4aac-8344-a79616ddba20">

### Normal projects
<img width="1211" alt="Screenshot 2023-07-11 at 12 40 27 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/69532d6e-a471-4be3-8f59-cbe139a7d3e0">


### Dropdown menu
<img width="488" alt="Screenshot 2023-07-11 at 12 46 10 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/724a9118-e7c1-4b04-9638-8aededb51814">

**Comment by laurenluz** [comment]
looks good - only, we should hide the "verify project" action if the project is already verified

**Comment by MoeNick** [comment]
> looks good - only, we should hide the "verify project" action if the project is already verified

@laurenluz it has a business behind it, if user started the verification process it shows Resume, and if the user submitted the application, it showed waiting for confirmation, I think it's fine we keep the currant button use-cases for it.

**Comment by laurenluz** [comment]
ok great @MoeNick 

let's make it happen! @MohammadPCh - can you take it away?

**Comment by MohammadPCh** [comment]
@laurenluz  Yes, Sure.
so with the new design, the user can't boost his project?
because we show the share banner instead of the boost under the project's banner:
![image](https://github.com/Giveth/giveth-dapps-v2/assets/17097576/c0c48682-e161-4c11-8b92-9bbf0ce9324b)

**Comment by laurenluz** [comment]
noooo, the user should be able to boost their own project. I don't like this share thing... we should keep the regular share & get rewarded button as we have already with the referral program.

And here, the project owner should see a similar banner... let me find the figma link...

**Comment by laurenluz** [comment]
Here! https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=113-25287&mode=design&t=c3GXIQuDvbdcyu5J-4

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/a3dc76a6-1dd4-48a3-ac62-8e742eb932fb)

**Comment by mosaeedi** [comment]
For now, let's put the share button under the Project action dropdown to prevent making this issue a blocker for the QF launch, after that, we can improve and fix it.

[Figma link](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=3945-113536&mode=design&t=DRgNylQUd3hBTpXC-4)

<img width="576" alt="Screenshot 2023-07-13 at 7 00 00 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/b1a45da6-20aa-4ab6-a352-39352d3670c0">

**Comment by laurenluz** [comment]
all yours @MohammadPCh !

**Comment by MohammadPCh** [comment]
@laurenluz @maryjaf please test it on staging :)

**Comment by laurenluz** [comment]
@MohammadPCh - some issues:

1. When a project is verified, we should hide the "verify your project" action (redundant w/ #2823)
![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/c9cd5353-2138-42ac-85e9-93acff303479)

2. "Share and get rewarded" button is buggy on staging... it leads to a spinning wheel and then nothing. instead, I should see this modal (redundant w/ #2838)
![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/73697219-ccfb-41de-a3fb-e88b8d0e9539)

3. We need the copy in the tooltips - you can find it here --> [figma link](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=3928-114707&mode=design&t=PmBenZr6j37HQDHi-0). Please note, there is a copy change on the "estimated matching" tooltip that should apply for both project owner view, and public view. (redundant w #2823)
![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/f86c6445-fcd4-4009-9851-8ef890328b9c)

**Comment by maryjaf** [comment]
The item 3 is reported on this issue and I think @RamRamez  works on it https://github.com/Giveth/giveth-dapps-v2/issues/2837

**Comment by MohammadPCh** [comment]
@laurenluz @maryjaf Please test it again, Thanks

**Comment by maryjaf** [comment]
Thanks @MohammadPCh It seems that the 1 3&4 are fixed but the item 2 (https://github.com/Giveth/giveth-dapps-v2/issues/2837) isn't resolved
