### ISSUE TITLE
Public view | About sub tabs sidebar

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#2554]
**Please note:**

1. Please look at the structure below.

![Screenshot 2023-04-24 at 12.46.40 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/4ffc346b-f3f7-4341-8d3c-e364e38a7e87)

##Responsive resource

WIP

## Check the design

[Link to Figma](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?node-id=899-57756&t=yMkADlANl4In8UtA-4)

**Comment by mosaeedi** [comment]
## Note: 
We add these side tabs only when the backend is ready, and at least the top 20 projects on Giveth added information to show on each tab.
