### ISSUE TITLE
Public view| Similar projects

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#2565]
![Screenshot 2023-05-01 at 4.38.38 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/de8904d9-e03e-465c-9cbd-497717b6f920)

**Comment by maryjaf** [comment]
I checked on https://giveth-dapps-v2-git-2565newprojectviewsimilarprojects-givethio.vercel.app/
but I didn't see any changes in similar project view @RamRamez Am I checking the right place?
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/111529185/236620324-27e74323-47bc-44fd-b83b-2ba8a701d76c.png">

**Comment by RamRamez** [comment]
@maryjaf Some colors, padding, and margins have changed a button is added.
![image](https://user-images.githubusercontent.com/73441857/236623739-48201c99-db09-46c3-bc74-b08a9608a202.png)

You can compare with Figma design
https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=131-60706&t=6vxWavpq6Lu2OaJu-0

**Comment by maryjaf** [comment]
> @maryjaf Some colors, paddings, and margins have changed and a button is added. ![image](https://user-images.githubusercontent.com/73441857/236623739-48201c99-db09-46c3-bc74-b08a9608a202.png)
> 
> You can compare with Figma design https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=131-60706&t=6vxWavpq6Lu2OaJu-0

Thanks @RamRamez I see differences between figma and  feature branch, plz check
and I have one guestion 
![image](https://user-images.githubusercontent.com/111529185/236660642-1e6520df-1ab1-48e0-b258-1ff092cf4330.png)![image](https://user-images.githubusercontent.com/111529185/236660651-972d44a3-5150-4cbf-ae04-caf65b694a70.png)

**Comment by RamRamez** [comment]
> > @maryjaf Some colors, paddings, and margins have changed and a button is added. ![image](https://user-images.githubusercontent.com/73441857/236623739-48201c99-db09-46c3-bc74-b08a9608a202.png)
> > You can compare with Figma design https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=131-60706&t=6vxWavpq6Lu2OaJu-0
> 
> Thanks @RamRamez I see differences between figma and feature branch, plz check and I have one question : should the "view more" button be linked "all project"? ![image](https://user-images.githubusercontent.com/111529185/236660642-1e6520df-1ab1-48e0-b258-1ff092cf4330.png)![image](https://user-images.githubusercontent.com/111529185/236660651-972d44a3-5150-4cbf-ae04-caf65b694a70.png)

Thanks @maryjaf. I will fix author color.
@MoeNick which one is the desired word? Givbacks or Givback eligible?

**Comment by MoeNick** [comment]
Shall I move it to unit test?

**Comment by maryjaf** [comment]
https://staging.giveth.io/project/testpfp010
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/f2bf2db3-89a2-4ae5-aa8d-cfba30292f3d)
plz check @RamRamez

**Comment by RamRamez** [comment]
> https://staging.giveth.io/project/testpfp010 ![image.png](https://camo.githubusercontent.com/c52c927fd2664f87c5ed96dde00c65ecff97a5ad45659362fc3ffe4b268193c0/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f66326266326462332d383961322d346165352d616138642d636662613330323932663364) plz check @RamRamez

@maryjaf I fixed it. It's on staging and you can test it.

**Comment by maryjaf** [comment]
Thanks @RamRamez ,it has been resolved
