### ISSUE TITLE
Low pri: homepage formatting on text is strange

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#257]
If I remember right in the design, this should be like 4 corners... not a list of 4 things. Am i wrong, @mosaeedi ?

This is not so important though.

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/929cad68-8881-4a74-9f79-65828ed4b443)

**Comment by divine-comedian** [comment]
section is now in columns, they shift around depending on the screen resolution

![image](https://user-images.githubusercontent.com/67759413/161095288-f28a64fb-8623-4342-ac19-e8f483710ad0.png)

or 

![image](https://user-images.githubusercontent.com/67759413/161095632-b50616fb-da09-404c-91cb-f8fb3b149cac.png)


definitely looks a lot cleaner! I think this is good enough to call done
