### ISSUE TITLE
Make default project sorting "By GIVpower Amount"

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2571]
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/cc56b51d-4e26-4063-b82d-ae497616cd3e)

**Comment by maryjaf** [comment]
Thanks @aminlatifi , I tested with API and the results displayed in the response are as expected, but since the front change is not ready, I will move this issue to DONE after the final test
