### ISSUE TITLE
PFP | show relevant message when user hasn't sufficient balance for gas of mint transaction

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#2575]
**Describe the bug**
my user has sufficient balance for gas of  first step(approve) but my wallet hasn't sufficient balance for  gas of 2Th transaction ,
when I tap on  approve for first transaction(pic 1) I see "approve" button on  Mint modal again and it isn't changed to "Mint" button
This process is repeated and the user does not understand what happened

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/111529185/234334019-15b958a2-fb0a-4682-8cab-2d794fcfe111.png">
<img width="686" alt="image" src="https://user-images.githubusercontent.com/111529185/234335156-516d74ed-572b-4673-8b9a-d008039a3b6b.png">

**Expected behavior**
A clear message is shown that the user hasn't sufficient balance for gas transaction

**Comment by divine-comedian** [comment]
Great Issue but I think we can leave it out of the launch issues for now - we don't deal with any of these cases anywhere else on the dapp so it might be a larger edge case. E.G using the donate to Giveth checkbox on mainnet donations. GIVfarm interactions, Regenfarm interactions etc..
