### ISSUE TITLE
Strange Pending Donation

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#2576]
Today, this user:
https://giveth.io/user/0xc517d11676cdba59751cb2544d478de7e6c25a0c 
reported a donation: 
https://etherscan.io/tx/0x993060889106a0653a8fa172ee47832403c2712e0d3afa5f9013f864c593cecc 
that has shown as pending for days on their project: 
https://giveth.io/project/documentary-about-nigerian-human-trafficking?tab=donations

![image](https://user-images.githubusercontent.com/74267818/234402114-dd71d06d-df4c-406f-9bf2-b54ce85c1cf1.png)

However, when I navigate to the project, I dont see a pending donation at all.
Etherscan shows that the transaction was successful...
It seems like the issue is on our side.

Can you take a look?

**Comment by mohammadranjbarz** [comment]
It's the error message that we got from Infura
`rejected due to project ID settings`
I changed the infura key in config, we would wait for few hours to see what happens

JFYI
@MoeNick

**Comment by mohammadranjbarz** [comment]
@WhyldWanderer 

Now the donations is verified

<img width="823" alt="Screen Shot 1402-02-06 at 09 51 07" src="https://user-images.githubusercontent.com/9850545/234486832-9d445037-d9dd-4d89-9614-f555f407d620.png">

**Comment by WhyldWanderer** [comment]
Awesome! Thanks Mohammad... I will inform the user
