### ISSUE TITLE
PFP UX Suggestion - Add modal for PFP holders who have not set their Giver as their PFP

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2580]
I did some testing on the PFP integration and I really that it's too many steps for the PFP holding user to figure out that they could add their PFP.

I think that, upon sign in, we should check if the user has a PFP (and if they have not yet set it as their profile pic)... and if they do, we should show them a modal that says:

"Set your Giver a your profile pic!"

And perhaps we can preview an image of the pic.

It would be nice to make this very basic PFP utility very obvious to the users who are already using our platform. Personally, I wouldn't really go to my profile page if I'm just on the platform to donate... and if I don't follow Giveth closely, I may not every realize that we added the NFT integration to the dApp.

@divine-comedian

**Comment by divine-comedian** [comment]
I hear you but I don't think we should add any more design or changes to the flow for the pfp integration at this point. 

I did hear your point yesterday and made a small change on the user's my account page. If they hold a Givers PFP in their wallet and have not set it as their profile pic yet we inform them on the `My Account` page and they can go directly to setting their NFT as their profile 

![image](https://user-images.githubusercontent.com/67759413/234616294-5e0daa4d-7f88-4863-9e0e-5ba307de4d5b.png)

**Comment by laurenluz** [comment]
This isn't just feedback from me. It's also from @MoeNick & @GriffGreen - I mean sure we can say "I don't want to do it"... but as it is... it is not easy for users to find.

**Comment by laurenluz** [comment]
that's a nice improvement you did already though.
