### ISSUE TITLE
BIG BUG! Can't Donate

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#2583]
https://giveth.io/donate/trusted-seed-unconference

Try donating to that project and tell me what you see ;-)

this is what I see, on gnosis:

<img width="1207" alt="Screen Shot 2023-04-27 at 12 09 56 PM" src="https://user-images.githubusercontent.com/14945613/234954561-b535cefc-d2bb-4852-a613-0e6def03d13f.png">

And Mainnet:

<img width="1491" alt="Screen Shot 2023-04-27 at 12 12 24 PM" src="https://user-images.githubusercontent.com/14945613/234954689-2bdb7f4b-ecfb-4c9d-8719-63fab9a5119a.png">

Is this impacting other projects?

HELP! :-D

**Comment by MoeNick** [comment]
@aminlatifi @RamRamez @CarlosQ96 can u guys help?

**Comment by CarlosQ96** [comment]
Ill jump on it, I could donate on other projects just fine. Seems specific to this project @mateodaza  can you look why the frontend redirecting me?

**Comment by MoeNick** [comment]
@CarlosQ96 Apparently all recipient addresses for this project were erased! 
I guess it's from backend, Maybe it's related to organizations whose tokens are linked to them.

**Comment by MoeNick** [comment]
But other projects seem dont have this problem.

**Comment by CarlosQ96** [comment]
@MoeNick yeah confirmed in the db the project has no recipient addresses, other projects are completely fine

**Comment by CarlosQ96** [comment]
What was the original address? I would add it in the db

**Comment by CarlosQ96** [comment]
Can contact owner @MoeNick ?

**Comment by RamRamez** [comment]
It may be related to admin bro. @CarlosQ96 can you check admin bro logs? we need a clue.

**Comment by MoeNick** [comment]
I dont have contact, maybe @GriffGreen have.

**Comment by GriffGreen** [comment]
Can we check if there are other projects with no addresses?

**Comment by CarlosQ96** [comment]
@RamRamez Ill add logs to the projectAddress tab in adminjs, but I couldnt find anything in the logs.

**Comment by GriffGreen** [comment]
0xb604cda24cca1838428be7d40fcd830451c23a0e

**Comment by GriffGreen** [comment]
Thank you for the quick response to this everyone

**Comment by CarlosQ96** [comment]
@GriffGreen I inserted the addresse you should be able to donate now without issue to the project.  It will arrive to 0xb604cda24cca1838428be7d40fcd830451c23a0e

**Comment by CarlosQ96** [comment]
@RamRamez ill add logs to project address but I couldnt find anything in the logs. Seems we missed this tab. But I doubt someone changed it.

**Comment by CarlosQ96** [comment]
@MoeNick is working now.
