### ISSUE TITLE
Changes for Single Project View | Givpower Tab

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#2588]

**Comment by laurenluz** [comment]
ok! design is finished, all we need to do is add a little text box to the GIVpower tab for verified projects [Link to Figma](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?node-id=1044-57701&t=Npzcw6QxmI4lHHY7-4).

Note that in the image it says "up to 80%" of your donation value... but this 80% number should be different for each project, dependent on their GIVbacks rank. @mohammadranjbarz I hope knows were @MohammadPCh can get fetch this number from.

![image](https://user-images.githubusercontent.com/75490971/236332899-0313df69-047d-49a8-a725-48bfde02fc6f.png)

**Comment by MohammadPCh** [comment]
@alireza-sharifpour  could you please take it?

**Comment by alireza-sharifpour** [comment]
> @alireza-sharifpour could you please take it?

Sure, i take it.

**Comment by alireza-sharifpour** [comment]
The issue related to percentage decimals should be fixed now, and about the logic behind the percentage i think @MoeNick or @mohammadranjbarz know better.

**Comment by maryjaf** [comment]
For projects where this number is an integer, do not display two digits after the decimal point
For example, show 74 instead of 74:00
