### ISSUE TITLE
Public view | Updates list

### ISSUE THREAD

**Issue by MohammadPCh** [Giveth/giveth-dapps-v2#2591]
The content area for the project updates is 100% wide now. 

### Design resource
[Link to Figma](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?node-id=131-56930&t=PufNboTMnlqsdv5i-4)

![Screenshot 2023-05-01 at 4.41.29 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/284e863d-bfc4-4adb-8a55-c4e73dfdda3d)

## For later
The **comments** and **report** are hidden for now. When we have the backend ready, we will add them as well.

![Screenshot 2023-05-01 at 4.41.43 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/fadb77c1-f88c-4971-a010-f553f170c5f3)

**Comment by divine-comedian** [comment]
Hey @RamRamez @MohammadPCh  - what happened to this issue? it's  marked as high prio in the icebox.. what should we do with it?

**Comment by RamRamez** [comment]
@divine-comedian The new design for updates is developed and merged.
I didn't develop like, comment and report buttons, bc backend wasn't ready.

@CarlosQ96 @mohammadranjbarz What do you think?

**Comment by MoeNick** [comment]
I DMed @divine-comedian about the status of this Epic, let's move into icebox for now.
