### ISSUE TITLE
Why do tokens on Polygon have the Ethereum logo?

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#2599]
![Screenshot 2023-05-02 at 1 11 44 PM](https://user-images.githubusercontent.com/14945613/235762905-9b57afb6-e474-4e45-a537-234ea2377d6d.png)

That feels confusing... either no logo or the Polygon logo would be better... otherwise people might think they are on Mainnet.

**Comment by MoeNick** [comment]
@mosaeedi can you take a look?

**Comment by mosaeedi** [comment]
@MohammadPCh Is this related to what we were working on?

I've updated the logos based on the CSV file you gave me. It's not done yet!
I'll add the rest of the missing icons later this week.

Please take a look -> [Figma link](https://www.figma.com/file/d3ciTS36toS9mra0RAPMe2/Giveth-Design-System-v0.1?type=design&node-id=4767-71303&t=M6iSvHX9Qt3TpBhS-4)

**Comment by mosaeedi** [comment]
There is only 32 icons left, I can add them by tomorrow. we can show the token icon instead of a general icon.
I'm adding all icons based on this file that @MohammadPCh shared with me.

[production_tokens (1).csv](https://github.com/Giveth/giveth-dapps-v2/files/11747373/production_tokens.1.csv)

**Comment by MohammadPCh** [comment]
@mosaeedi let me know when it is finished. Thanks.

**Comment by MohammadPCh** [comment]
@maryjaf can you test it, please?
