### ISSUE TITLE
Token price USD values are wrong on mainnet! They all say 1 (some token) = 1 USD (on donation popup)

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#260]
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/da0ccda5-96db-4b70-aabc-c4a4293702f3)

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/6f0cfec8-26ec-4d92-9f29-56dac0f9a83a)

GIV is wrong:

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/f5886e75-6654-4033-8197-8c81f9e9a933)

SEED is wrong:

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/d8d65266-0f7c-4a45-88b8-f6135844d022)

ETH is ok:

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/74442b80-e23c-480e-9a05-a38ff3cf8a3f)

**Comment by laurenluz** [comment]
Note: they are ok in the donation leaderboard

![image](https://user-images.githubusercontent.com/75490971/158688656-42a42f83-2c87-4955-b9f2-b73f8e19818c.png)

**Comment by divine-comedian** [comment]
testing on `giveth.io` 

It appears to be fixed but I don't have a diverse range of tokens on mainnet to properly test this issue! 

![image](https://user-images.githubusercontent.com/67759413/159366533-60d131bb-a726-4be1-b288-10721c204184.png)

@GriffGreen maybe try to whack this one?

**Comment by laurenluz** [comment]
I checked a few, I think it's working well
