### ISSUE TITLE
Landing Page for "Learn how GIVbacks works"

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2627]
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/2e78e2c0-af66-4634-8579-a4d0ed8cb845)

**Comment by laurenluz** [comment]
We need a simple landing page to make it easy for our users to read and understand the GIVbacks! - @mosaeedi

**Comment by mosaeedi** [comment]
@laurenluz do we have the content for this page?

**Comment by laurenluz** [comment]
we don't. maybe someone from comms @danelsuga @ahmadabugosh - can make something

**Comment by oyealmond** [comment]
@laurenluz @ahmadabugosh @danelsuga Could you review @surbhiaroraa [text for the landing](https://docs.google.com/document/d/1P2aQ3E9ZWyHuWEuuK3e6IR2EtmS-a9XFbVpPkiwVlTo/edit?usp=sharing)? 

Thanks!

**Comment by danelsuga** [comment]
I've left some comments. I think this needs a lot of revising, as I think the presentation of the GIVbacks concept is slightly off.

**Comment by ahmadabugosh** [comment]
hey @surbhiaroraa , I also left a few comments. Can you integrate these with the ones @danelsuga mentioned and then share a next draft with us?

**Comment by surbhiaroraa** [comment]
Thank you @ahmadabugosh @danelsuga @oyealmond 
I have edited the content as per your suggestions. Can you please have a fresh look at it once and let me know if any more changes are needed.

**Comment by MoeNick** [comment]
Please tag me again if the content is ready for design. Thanks

**Comment by danelsuga** [comment]
Hi @surbhiaroraa. Looking great with new edits! I left a few more comments.

**Comment by surbhiaroraa** [comment]
@danelsuga 
Can you please add that last part on GIVfarm? I am not very sure about it.

**Comment by surbhiaroraa** [comment]
@ahmadabugosh 
Can you have a quick look at this? Let me know if this is good to proceed for design and development?

**Comment by oyealmond** [comment]
hey @surbhiaroraa! how is this doing?

**Comment by surbhiaroraa** [comment]
@oyealmond 
This is done from my end a week back. I heard from grapevine that before content goes out for design and development, it needs 2 reviewers. So I tagged Ahmad for his approval. However please go ahead and send it for design and development if no further reviewing is needed.

**Comment by danelsuga** [comment]
There are three comments that still need approval. One of them is directed to @ahmadabugosh. And I think the other two are for @surbhiaroraa.

**Comment by surbhiaroraa** [comment]
All done from my end. @ahmadabugosh Please review this once and also tag someone concerned for design and development.

**Comment by ahmadabugosh** [comment]
hey @surbhiaroraa I added some more comments and suggestions too, can you check please

**Comment by surbhiaroraa** [comment]
I checked and incorporated your suggestions. I have left 3 comments for you. Can you please address those? 
Also, can you tell me who should I contact for the design of this page?

**Comment by MoeNick** [comment]
@RamRamez whenever you want to start, pls tag currant sprint and move it to in progress.
