### ISSUE TITLE
When creating a project, viewing the preview, I should have the option to edit/go back

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#263]
Edit is greyed out

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/ee3eff07-94ac-4cb2-99f1-3c788b061ebc)

**Comment by MoeNick** [comment]
It's happened on production @RamRamez

**Comment by NikolaCreatrix** [comment]
Tested - issue FIXED
