### ISSUE TITLE
Ensure that GIVbacks go out on Optimism

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2630]
@mohammadranjbarz  we have a bunch of eligible GIVbacks tokens, we need to make sure that the donations on Optimism are going into the GIVbacks flow.

GIV will be rewarded on Gnosis Chain, as like other chains.

cc @MoeNick

**Comment by mohammadranjbarz** [comment]
@MoeNick @laurenluz  Givback-calculation supports **Celo** right now

**Comment by mohammadranjbarz** [comment]
@maryjaf  It's similar to Giveth/giveth-dapps-v2#2579 please test it

**Comment by maryjaf** [comment]
> @maryjaf It's similar to #2579 please test it
It's ok 

[
  {
    "amount": 0.000055,
    "currency": "ETH",
    "createdAt": "2023-05-09-10:37:21",
    "valueUsd": 0.10129955,
    "bottomRankInRound": 134,
    "givbacksRound": 35,
    "projectRank": 1,
    "givbackFactor": 0.8,
    "valueUsdAfterGivbackFactor": 0.0810396,
    "giverAddress": "0xcd192b61a8dd586a97592555c1f5709e032f2505",
    "txHash": "0xa60950a63acbf7935fb8ba1b8296da42214c26463be96daf240dcaa22c1561fd",
    "network": "optimistic",
    "source": "giveth.io",
    "giverName": "maryam jafarymehr",
    "giverEmail": null,
    "projectLink": "https://giveth.io/project/the-giveth-community-of-makers",
    "isReferrerGivbackEligible": false,
    "referrerWallet": null
  },

**Comment by laurenluz** [comment]
I made a mistake when I initially named the issue @mohammadranjbarz - I want to make sure they go out on Optimism :) Are we all good there too?

**Comment by mohammadranjbarz** [comment]
> ok, so I made a mistake before in the specification.
> 
> We want GIVbacks actually to go out _on Optimism chain_. So ideally:
> 
> * let's NOT have GIVbacks go out on Gnosis chain for donations that happened on Optimism. Instead, we should keep track of these donations & GIVbacks amounts, and hold off on sending them until we deploy the token distro on Optimism chain.
> 
> I will create new issues for that and make an epic.
> 
> @mohammadranjbarz - can you confirm that you got the message?

@laurenluz  So for now is it enough to just exclude optimism donations in givback-calculation response? and we can reward them on Optimism chain later, am I right?

**Comment by laurenluz** [comment]
yes exactly, I created an epic for the flow https://github.com/Giveth/Roadmap/issues/84

We should wait until we have everything deployed for distributing GIVbacks on optimism, and then should include optimism donations in a separate list for givback-calculation so that they can be distributed via the new token distro.

How does that work @mohammadranjbarz ? Will you need to change anything? or just get two lists (on for optimism, one for all other chains) and then send them to @WhyldWanderer ?

**Comment by mohammadranjbarz** [comment]
> yes exactly, I created an epic for the flow [Giveth/Roadmap#84](https://github.com/Giveth/Roadmap/issues/84)
> 
> We should wait until we have everything deployed for distributing GIVbacks on optimism, and then should include optimism donations in a separate list for givback-calculation so that they can be distributed via the new token distro.
> 
> How does that work @mohammadranjbarz ? Will you need to change anything? or just get two lists (on for optimism, one for all other chains) and then send them to @WhyldWanderer ?
@laurenluz  @WhyldWanderer 
I should think and implement best approach, how much time do I have for that, when is the next givback distribution time( I guess I should do it before that)?

**Comment by laurenluz** [comment]
yes, I think we can try to have it finished by the end of next GIVbacks round... so May 30

**Comment by mohammadranjbarz** [comment]
@divine-comedian 
But about nice token reward its the same, no change for Optimism donations there, am I right?

**Comment by mohammadranjbarz** [comment]
<img width="1444" alt="Screen Shot 1402-02-27 at 17 44 25" src="https://github.com/Giveth/giveth-dapps-v2/assets/9850545/4704ee1c-0b53-4f00-ba6b-c9dda3027fcc">

I added a chain filter for /calculate and /eligible-donations now you need to select **all-other-chains** to exclude Optimism donations and once we had tokenDistro ready on Optimism we can select **Optimism** then we can just consider Optimisim donations. 

**PS** niceToken amounts would not get affected by these changes

JFYI @divine-comedian  @laurenluz  @WhyldWanderer

**Comment by WhyldWanderer** [comment]
I saw that there were some Optimism donations included in this round (36) when I pulled the spreadsheet data.
Does this mean that we should not distribute GIVbacks for these donations on Gnosis Chain for this round and save them for the next round?

I can make sure that we remove them from the distribution.. and keep a list.

**Comment by mohammadranjbarz** [comment]
> I saw that there were some Optimism donations included in this round (36) when I pulled the spreadsheet data. Does this mean that we should not distribute GIVbacks for these donations on Gnosis Chain for this round and save them for the next round?
> 
> I can make sure that we remove them from the distribution.. and keep a list.

Yeah we should not distribute in this round

No need to save them for the future, when Optimisim tokenDistro got ready you can call /calculate for Optimism with the time range from adding Optimism  time till distributtion time

**Comment by laurenluz** [comment]
amazing work team!!

**Comment by divine-comedian** [comment]
> @divine-comedian But about nice token reward its the same, no change for Optimism donations there, am I right?

Correct, no changes for $nice token - they will still be distributed on gnosis chain.

**Comment by divine-comedian** [comment]
Just a thought here since I am in the process of deploy the GIVbacks Relayer - 

Since we are working out of ipfs hashes for loading up the distribution data we should have separate ipfs hashes that contain the distribution data separated by chain. 

i.e. run givbacks-calculation for given data ranges -> output should include 1 ipfs hash for givbacks going out on gnosis chain AND an ipfs hash for givbacks going out on optimism

**Comment by laurenluz** [comment]
@mohammadranjbarz - is that clear to you? can we add it?

**Comment by MoeNick** [comment]
@divine-comedian can explain it better to @mohammadranjbarz

**Comment by divine-comedian** [comment]
@mohammadranjbarz  

To explain a bit better, currently when we run `calculate-givbacks` we get a JSON file that looks something like this:

```
{
  "raisedValueSumExcludedPurpleList": 52034,
  "givDistributed": 1000001,
  "givethioDonationsAmount": 52034,
  "result": "load giveth; giveth:initiate-givbacks QmUz2rm8wDV5ZWNjwehWLEoUoviXwGapgYokmfqEuy4nW9 --relayer 0xd0e81E3EE863318D0121501ff48C6C3e3Fd6cbc7",
  "hashParams": {
    "ipfsLink": "https://gateway.pinata.cloud/ipfs/QmUz2rm8wDV5ZWNjwehWLEoUoviXwGapgYokmfqEuy4nW9",
    "0xb66aeb4587d3c3a47236ee32f2ec02665b532b8da6610edec7c8e6a1cd96e240": {
      "rawData": {
        "nonce": 0,
        "amounts": [
          "640984417784000100000000",
          "98414782900000000000000",
          "39476448246000000000000",
          "38578983127000000000000",
          "20698141282000000000000",
          "20543027075000000000000",
          "19589667574000000000000",
          "11384517989000000000000",
          "10715355112000000000000",
          "8253881128999999000000",
          "5480074359000000000000",
          "3802103113000000000000",
          "3723228587000000000000",
          "3381093594999999700000",
          "2909969570000000000000",
          "2740074596000000000000",
          "2634836006999999600000",
          "2522433199000000000000",
          "2467366896000000000000",
          "2349183039000000000000",
        ......
        ],
        "recipients": [
          "0xf77dd6e758ba8b96fcd2f02df2f4373f26b9137b",
          "0x5f0253950c0a7715cba25153a6ed5ebcffede48e",
          "0x94f3cdfc19763b3ad3b31925643174423c773a5f",
          "0xf03f91a8df491e48e274d4185589bc822cc9c176",
          "0xd714dd60e22bbb1cbafd0e40de5cfa7bbdd3f3c8",
          "0xf8f263c7d028afc754252059382226cf28f812d3",
          "0x05a1ff0a32bc24265bcb39499d0c5d9a6cb2011c",
          .....
        ]
      }
    },
    "0xdd89243de5c64c566cbde330c291c4294207b05c4382849e3b4c0a2b1538cf59": {
      "rawData": {
        "nonce": 1,
        "amounts": [
          "20314881000000000000",
          "20258341000000000000",
          "19631158000000000000",
          "19372171000000000000",
          "19348345000000000000",
          "18709167000000000000",
          "18567918000000000000",
          "18107555000000002000",
          "17866966000000002000",
          "17714659999999998000",
          "15735464000000000000",
          "14505644000000000000",
         .....
        ],
        "recipients": [
          "0xcc3d7f9fe6946979215a901bba385a88fdabbbf4",
          "0x348b9ee858d0d88f90d661d92d2e37dd909c0a40",
          "0x4958f797fc5833f7663e4b7e27a08c288ab8c906",
          ..... ( rest of output...)
        ]
      }
    }
  },
````

The ipfs hash we produce at the top is a json object that holds all of the raw distribution data for givbacks, separated by nonces. It is separated by nonces because there are too many addresses to distribute to, so we divide them into batches, the GIVbacks Relayer is a contract that then allows us to send off multiple batches with a single tx. 

We use EVMcrispr with Giveth specific commands that uses the ipfs hash to parse the GIVbacks data contained within and send them out. 

The issue above is that the rawData JSON and the ipfs hash have all of the GIVbacks data for all chains - which if we want to separate distributions by different chains (GNosis Chain & Optimism in this case) we'll need to produce separated raw distribution data and also a separate ipfs hash containing that data for each chain we want to distribute on. 

So what we need now as part of the calculate-givbacks is
 - one JSON object with raw givbacks distribution data for optimism
 - a corresponding ipfs hash with json object data for optimism givbacks
 - one JSON object with raw givbacks distribution data for all other chains 
 -  - a corresponding ipfs hash with json object data for givbacks on all other chains, for distribution on gnosis chain

**Comment by laurenluz** [comment]
@mohammadranjbarz - for starters, can you, this week, pass mitch the raw data for the GIVbacks on Optimism? so he can get an estimate of the multisig txs he'll need to set up.

We won't need the IPFS has for about a month until we can set up the relayed w/ open zeppelin

**Comment by MoeNick** [comment]
@CarlosQ96 
@mohammadranjbarz is super busy these days, can we ask you to do this? 

FYI: @divine-comedian

**Comment by divine-comedian** [comment]
I think I can get all the info I need by using the calculation API with the optimism toggle on
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/891513b8-fb63-4b10-9960-3b483257eedf)

First Date - May 2nd (Round 36)

**Comment by divine-comedian** [comment]
Oh also - just for any accounting purposes:

**I sent 2,508,030.080346629829613608 GIV to the token distro today.**  

I noticed to date we need to send about 800k GIV tokens on Optimism for GIVbacks and we will be adding GIVpower rewards that will go on top of this amount that needs to come from the token distro.

**Comment by MoeNick** [comment]
> @mohammadranjbarz
> 
> To explain a bit better, currently when we run `calculate-givbacks` we get a JSON file that looks something like this:
> 
> ```
> {
>   "raisedValueSumExcludedPurpleList": 52034,
>   "givDistributed": 1000001,
>   "givethioDonationsAmount": 52034,
>   "result": "load giveth; giveth:initiate-givbacks QmUz2rm8wDV5ZWNjwehWLEoUoviXwGapgYokmfqEuy4nW9 --relayer 0xd0e81E3EE863318D0121501ff48C6C3e3Fd6cbc7",
>   "hashParams": {
>     "ipfsLink": "https://gateway.pinata.cloud/ipfs/QmUz2rm8wDV5ZWNjwehWLEoUoviXwGapgYokmfqEuy4nW9",
>     "0xb66aeb4587d3c3a47236ee32f2ec02665b532b8da6610edec7c8e6a1cd96e240": {
>       "rawData": {
>         "nonce": 0,
>         "amounts": [
>           "640984417784000100000000",
>           "98414782900000000000000",
>           "39476448246000000000000",
>           "38578983127000000000000",
>           "20698141282000000000000",
>           "20543027075000000000000",
>           "19589667574000000000000",
>           "11384517989000000000000",
>           "10715355112000000000000",
>           "8253881128999999000000",
>           "5480074359000000000000",
>           "3802103113000000000000",
>           "3723228587000000000000",
>           "3381093594999999700000",
>           "2909969570000000000000",
>           "2740074596000000000000",
>           "2634836006999999600000",
>           "2522433199000000000000",
>           "2467366896000000000000",
>           "2349183039000000000000",
>         ......
>         ],
>         "recipients": [
>           "0xf77dd6e758ba8b96fcd2f02df2f4373f26b9137b",
>           "0x5f0253950c0a7715cba25153a6ed5ebcffede48e",
>           "0x94f3cdfc19763b3ad3b31925643174423c773a5f",
>           "0xf03f91a8df491e48e274d4185589bc822cc9c176",
>           "0xd714dd60e22bbb1cbafd0e40de5cfa7bbdd3f3c8",
>           "0xf8f263c7d028afc754252059382226cf28f812d3",
>           "0x05a1ff0a32bc24265bcb39499d0c5d9a6cb2011c",
>           .....
>         ]
>       }
>     },
>     "0xdd89243de5c64c566cbde330c291c4294207b05c4382849e3b4c0a2b1538cf59": {
>       "rawData": {
>         "nonce": 1,
>         "amounts": [
>           "20314881000000000000",
>           "20258341000000000000",
>           "19631158000000000000",
>           "19372171000000000000",
>           "19348345000000000000",
>           "18709167000000000000",
>           "18567918000000000000",
>           "18107555000000002000",
>           "17866966000000002000",
>           "17714659999999998000",
>           "15735464000000000000",
>           "14505644000000000000",
>          .....
>         ],
>         "recipients": [
>           "0xcc3d7f9fe6946979215a901bba385a88fdabbbf4",
>           "0x348b9ee858d0d88f90d661d92d2e37dd909c0a40",
>           "0x4958f797fc5833f7663e4b7e27a08c288ab8c906",
>           ..... ( rest of output...)
>         ]
>       }
>     }
>   },
> ```
> 
> The ipfs hash we produce at the top is a json object that holds all of the raw distribution data for givbacks, separated by nonces. It is separated by nonces because there are too many addresses to distribute to, so we divide them into batches, the GIVbacks Relayer is a contract that then allows us to send off multiple batches with a single tx.
> 
> We use EVMcrispr with Giveth specific commands that uses the ipfs hash to parse the GIVbacks data contained within and call the functions on the GIVbacks Relayer with the parsed data to distribute GIVbacks.
> 
> The issue above is that the rawData JSON and the ipfs hash have all of the GIVbacks data for all chains - which if we want to separate distributions by different chains (GNosis Chain & Optimism in this case) we'll need to produce separated raw distribution data and also a separate ipfs hash containing that data for each chain we want to distribute on.
> 
> So what we need now as part of the calculate-givbacks is
> 
> * one JSON object with raw givbacks distribution data for optimism
> * a corresponding ipfs hash with json object data for optimism givbacks
> * one JSON object with raw givbacks distribution data for all other chains, for distribution on gnosis chain
> * a corresponding ipfs hash with json object data for givbacks on all other chains, for distribution on gnosis chain

@divine-comedian do we still need to do these changes by @mohammadranjbarz ?

**Comment by divine-comedian** [comment]
Yes.

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz
> 
> To explain a bit better, currently when we run `calculate-givbacks` we get a JSON file that looks something like this:
> 
> ```
> {
>   "raisedValueSumExcludedPurpleList": 52034,
>   "givDistributed": 1000001,
>   "givethioDonationsAmount": 52034,
>   "result": "load giveth; giveth:initiate-givbacks QmUz2rm8wDV5ZWNjwehWLEoUoviXwGapgYokmfqEuy4nW9 --relayer 0xd0e81E3EE863318D0121501ff48C6C3e3Fd6cbc7",
>   "hashParams": {
>     "ipfsLink": "https://gateway.pinata.cloud/ipfs/QmUz2rm8wDV5ZWNjwehWLEoUoviXwGapgYokmfqEuy4nW9",
>     "0xb66aeb4587d3c3a47236ee32f2ec02665b532b8da6610edec7c8e6a1cd96e240": {
>       "rawData": {
>         "nonce": 0,
>         "amounts": [
>           "640984417784000100000000",
>           "98414782900000000000000",
>           "39476448246000000000000",
>           "38578983127000000000000",
>           "20698141282000000000000",
>           "20543027075000000000000",
>           "19589667574000000000000",
>           "11384517989000000000000",
>           "10715355112000000000000",
>           "8253881128999999000000",
>           "5480074359000000000000",
>           "3802103113000000000000",
>           "3723228587000000000000",
>           "3381093594999999700000",
>           "2909969570000000000000",
>           "2740074596000000000000",
>           "2634836006999999600000",
>           "2522433199000000000000",
>           "2467366896000000000000",
>           "2349183039000000000000",
>         ......
>         ],
>         "recipients": [
>           "0xf77dd6e758ba8b96fcd2f02df2f4373f26b9137b",
>           "0x5f0253950c0a7715cba25153a6ed5ebcffede48e",
>           "0x94f3cdfc19763b3ad3b31925643174423c773a5f",
>           "0xf03f91a8df491e48e274d4185589bc822cc9c176",
>           "0xd714dd60e22bbb1cbafd0e40de5cfa7bbdd3f3c8",
>           "0xf8f263c7d028afc754252059382226cf28f812d3",
>           "0x05a1ff0a32bc24265bcb39499d0c5d9a6cb2011c",
>           .....
>         ]
>       }
>     },
>     "0xdd89243de5c64c566cbde330c291c4294207b05c4382849e3b4c0a2b1538cf59": {
>       "rawData": {
>         "nonce": 1,
>         "amounts": [
>           "20314881000000000000",
>           "20258341000000000000",
>           "19631158000000000000",
>           "19372171000000000000",
>           "19348345000000000000",
>           "18709167000000000000",
>           "18567918000000000000",
>           "18107555000000002000",
>           "17866966000000002000",
>           "17714659999999998000",
>           "15735464000000000000",
>           "14505644000000000000",
>          .....
>         ],
>         "recipients": [
>           "0xcc3d7f9fe6946979215a901bba385a88fdabbbf4",
>           "0x348b9ee858d0d88f90d661d92d2e37dd909c0a40",
>           "0x4958f797fc5833f7663e4b7e27a08c288ab8c906",
>           ..... ( rest of output...)
>         ]
>       }
>     }
>   },
> ```
> 
> The ipfs hash we produce at the top is a json object that holds all of the raw distribution data for givbacks, separated by nonces. It is separated by nonces because there are too many addresses to distribute to, so we divide them into batches, the GIVbacks Relayer is a contract that then allows us to send off multiple batches with a single tx.
> 
> We use EVMcrispr with Giveth specific commands that uses the ipfs hash to parse the GIVbacks data contained within and call the functions on the GIVbacks Relayer with the parsed data to distribute GIVbacks.
> 
> The issue above is that the rawData JSON and the ipfs hash have all of the GIVbacks data for all chains - which if we want to separate distributions by different chains (GNosis Chain & Optimism in this case) we'll need to produce separated raw distribution data and also a separate ipfs hash containing that data for each chain we want to distribute on.
> 
> So what we need now as part of the calculate-givbacks is
> 
> * one JSON object with raw givbacks distribution data for optimism
> * a corresponding ipfs hash with json object data for optimism givbacks
> * one JSON object with raw givbacks distribution data for all other chains, for distribution on gnosis chain
> * a corresponding ipfs hash with json object data for givbacks on all other chains, for distribution on gnosis chain

@divine-comedian 
I think we have what you want right now,  I executed the webservice with this times:
`startDate`: **2023/08/07-16:00:00**
`endDate`: **2023/08/21-15:59:59**

Can you clarify it for me what other changes do you need for this web service?

# This is when you select `Optimism`
<img width="1287" alt="Screen Shot 1402-05-31 at 11 00 41" src="https://github.com/Giveth/giveth-dapps-v2/assets/9850545/f7bfd653-b747-409a-b36c-03a50019e20a">

[givbackreport_2023_08_07-16_00_00-2023_08_21-15_59_59 - optimism.csv](https://github.com/Giveth/giveth-dapps-v2/files/12406116/givbackreport_2023_08_07-16_00_00-2023_08_21-15_59_59.-.optimism.csv)

# This is when you select `all-other-chains`
<img width="1319" alt="Screen Shot 1402-05-31 at 11 00 59" src="https://github.com/Giveth/giveth-dapps-v2/assets/9850545/5452679a-7764-4e90-9e75-885589442e1e">

[givbackreport_2023_08_07-16_00_00-2023_08_21-15_59_59.csv](https://github.com/Giveth/giveth-dapps-v2/files/12406120/givbackreport_2023_08_07-16_00_00-2023_08_21-15_59_59.csv)

**Comment by divine-comedian** [comment]
This is great!

**Comment by MoeNick** [comment]
@mohammadranjbarz any updates on this?

**Comment by MoeNick** [comment]
Do you do the QA @divine-comedian ?
I love @maryjaf to also be in the loop for maintaining the test scenarios.

**Comment by maryjaf** [comment]
When I donate on op, I can see this record in response of  /eligible-donations on optimism chain
 {
    "amount": 0.000001,
    "currency": "ETH",
    "createdAt": "2023-08-24-08:12:38",
    "valueUsd": 0.00167739,
    "bottomRankInRound": 150,
    "givbacksRound": 43,
    "projectRank": 1,
    "givbackFactor": 0.8,
    "valueUsdAfterGivbackFactor": 0.0013419,
    "giverAddress": "0xcd192b61a8dd586a97592555c1f5709e032f2505",
    "txHash": "0x74d12dd9ba23b7db930893fac717cd6e228ad9e81358503482e527e0a0b4a764",
    "network": "optimism",
    "source": "giveth.io",
    "giverName": "maryam jafarymehr",
    "giverEmail": null,
    "projectLink": "https://giveth.io/project/the-giveth-community-of-makers",
    "isReferrerGivbackEligible": false,
    "referrerWallet": null
  },

**Comment by mohammadranjbarz** [comment]
After discussing with @divine-comedian  and @WhyldWanderer  
We understood we still need to implement this for that in givback-calculation
** it should be calculated all together but provide two separate responses (For Optimism and other chains)
I mean two separated distributions**

**Comment by MoeNick** [comment]
Bring it back to Sprint planning as a high priority.

**Comment by MoeNick** [comment]
@mohammadranjbarz is it still in progress?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz is it still in progress?

After long time it's on the staging now( I did lots of change on the /calculate response)

https://github.com/Giveth/givback-calculation/pull/34#issuecomment-1701007048

**Comment by maryjaf** [comment]
It seems we have a problem on GIVbacck OP, maybe related to last changed  that it need to be correctet
My account " 0x523e41a134ab0999f2dc844ea02d9b53cc28fd1a" there isn't in purple list but in donation page I get this warning and I can't check the new change on OP givback

**This token is not eligible for GIVbacks. To create a request to add this token to our GIVbacks token list, please make a comment in our forum.**

@mohammadranjbarz

**Comment by maryjaf** [comment]
Do you need that this changes also be applied in this request  /eligible-donations?
<img width="1254" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/239c86ca-7472-4339-adc4-24498b3f9e67"> 
@divine-comedian

**Comment by maryjaf** [comment]
> It seems we have a problem on GIVbacck OP, maybe related to last changed that it need to be correctet My account " 0x523e41a134ab0999f2dc844ea02d9b53cc28fd1a" there isn't in purple list but in donation page on OP chain I get this warning and I can't check the new change on OP givback
> 
> **This token is not eligible for GIVbacks. To create a request to add this token to our GIVbacks token list, please make a comment in our forum.**
> 
> @mohammadranjbarz

Thanks @mohammadranjbarz this problem has been resolved after changing the config of givback on admin bro

**Comment by MoeNick** [comment]
@divine-comedian can you check it again pls

**Comment by maryjaf** [comment]
plz check this curl @mohammadranjbarz 
curl -X 'GET' \
  'https://givback.develop.giveth.io/staging/calculate?startDate=2023%2F02%2F01-00%3A00%3A00&endDate=2023%2F09%2F05-23%3A59%3A59&givPrice=1&givAvailable=1000000&givRelayerAddress=0xd0e81E3EE863318D0121501ff48C6C3e3Fd6cbc7&maxAddressesPerFunctionCall=200&nicePerDollar=1&niceWhitelistTokens=DAI%2CWXDAI%2CXDAI%2CUSDC&niceProjectSlugs=the-giveth-community-of-makers&download=no' \
  -H 'accept: application/json'
  
What is the maximum time interval that we can set in the parameter request?

**Comment by mohammadranjbarz** [comment]
> plz check this curl @mohammadranjbarz
> 
> curl -X 'GET' 'https://givback.develop.giveth.io/staging/calculate?startDate=2023%2F02%2F01-00%3A00%3A00&endDate=2023%2F09%2F05-23%3A59%3A59&givPrice=1&givAvailable=1000000&givRelayerAddress=0xd0e81E3EE863318D0121501ff48C6C3e3Fd6cbc7&maxAddressesPerFunctionCall=200&nicePerDollar=1&niceWhitelistTokens=DAI%2CWXDAI%2CXDAI%2CUSDC&niceProjectSlugs=the-giveth-community-of-makers&download=no' -H 'accept: application/json'
> 
> Response
> 
> "message": "Float cannot represent non numeric value: NaN: {"response":{"errors":[{"message":"Float cannot represent non numeric value: NaN","locations":[{"line":13,"column":13}],"path":["donations",9,"givbackFactor"],"....
> 
> What is the maximum time interval that we can set in the parameter request?

@maryjaf 
We might have some old data that is not compatible, and we use this webservice just for 2 weeks period and we don't need old data, so if there is problem on some old data or on very big range, you don't have to worry about it ( also it might be problem of staging data)

**Comment by divine-comedian** [comment]
Yes I encountered this error as well - because I think older data is in a different format so it's not able to fetch it across large periods because there are different data formats

**Comment by maryjaf** [comment]
> Do you need that this changes also be applied in this request /eligible-donations? <img alt="image" width="1254" src="https://user-images.githubusercontent.com/111529185/265448862-239c86ca-7472-4339-adc4-24498b3f9e67.png"> @divine-comedian

kindly reminder @divine-comedian

**Comment by divine-comedian** [comment]
> > Do you need that this changes also be applied in this request /eligible-donations? <img alt="image" width="1254" src="https://user-images.githubusercontent.com/111529185/265448862-239c86ca-7472-4339-adc4-24498b3f9e67.png"> @divine-comedian
> 
> kindly reminder @divine-comedian

Sorry it is fine to keep it like this.
