### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by brichis** [Giveth/giveth-dapps-v2#2635]
GM @MoeNick ! I think I found a bug 

**Describe the bug**
When I'm on my profile, and I click My GIVpower, My Projects or My Donations, it shows me an error but I can access normaly to my project if I enter directly from its link.

**To Reproduce**
1. Go to https://giveth.io/account?data=all&view=projects
2. Click on My GIVpower, My Projects or My Donations
3. See error

**Screenshots**

https://github.com/Giveth/giveth-dapps-v2/assets/106570342/d97de48d-7ef8-400c-99cb-a0447a5de9de

**Desktop (please complete the following information):**
 - OS: iOs
 - Browser Brave
 - Version 1.51.110

**Additional context**

**Comment by MoeNick** [comment]
Thanks for reporting
@maryjaf  can you check all scenarios for thiss issue

**Comment by Vyvy-vi** [comment]
@MoeNick This is still broken. Can I work on this?

**Comment by MoeNick** [comment]
we could not reproduce it, if you could, yes please take it.

**Comment by MohammadPCh** [comment]
@Vyvy-vi we should change our logic in : ProfileContributes.tsx
```
<Link href={pathname + profileTabs.overview}>
	<ProfileTab active={tab === EProfile.OVERVIEW}>
		{formatMessage({ id: 'label.overview' })}
	</ProfileTab>
</Link>
```
we have to add query params in another way :)
can you take a look?

**Comment by divine-comedian** [comment]
@MohammadPCh is this still relevant?

**Comment by maryjaf** [comment]
It is an old problem, now there is no bug in this page.
