### ISSUE TITLE
Set conditions for if the project is part of QF when creating donation

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2636]
MVP plan:
- project needs to be within the top x% of boosted projects with GIVpower
- project needs to be listed & verified
- project needs to have been updated within the last y rounds
- tbh: project needs to have Giveth Pro

**Comment by mohammadranjbarz** [comment]
For filling first qfRound projects I would write a migration once everything implemented

**Comment by MoeNick** [comment]
According to @mohammadranjbarz question:

we can check these conditions at the moment we want to make them part of the round, but  What happened when the status of listing/verified changed during the round? 

Shall we check these conditions before creating a donation? or whenever we load the project or donation page? 
and do we have to re-check the matching funds at the end of the round?

**Comment by mohammadranjbarz** [comment]
> Well, in order to qualify to be part of the round, a project would need to be verified at the start of the round. But then, if it's verified/listed status changes during the round, they should still be included in the round (no change on QF).
> 
> At the end of the round, as long as the project was not cancelled, they should still qualify for matching funds, but also - we will be doing manual review of the donations to check for anything fishy... so it would be nice to be able to see if the project's listed/verified status changed during the round.
> 
> Also @mohammadranjbarz - are we going to be able to set a project's QF status via admin bro? or will it be automatic based on our criteria (top x of GIVpower, recent update, etc.)?

Good, I want to make it automatic by writing a migration for start of round but will try to add something in admin bro to admin can add/remove projects to qfRound

**Comment by laurenluz** [comment]
amazing!

**Comment by MoeNick** [comment]
Shall we change the owner of this issue? @CarlosQ96 @mohammadranjbarz ?
