### ISSUE TITLE
Track projects that add an optimism address & disitribute OP

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2637]
@MoeNick, I just learned, we promised that we would donate 25 OP to the first 640 projects who add an optimism address on Giveth.

@mohammadranjbarz can you help create a process for tracking this? Basically we just need to know who the 1st 640 address are... and then we can distribute the funds.

**Comment by laurenluz** [comment]
note: we need a filter to show only verified projects.

and for the next steps... we will need to send the OP out, but first we need the money! 

@oyealmond want to fill you in on this so we can push it as well for comms!

**Comment by divine-comedian** [comment]
> I think @mohammadranjbarz that it's enough.
> 
> Can we also include something in our GIVbacks flow so that we fetch the addresses that need the OP and then send them via disburse every 2 weeks. Wdyt @divine-comedian ? Is that something you can handle? Or do you think we should do it another way/less frequently?

If there is a clear list of addresses we can maintain in a spreadsheet then.. probably yes

**Comment by laurenluz** [comment]
that sounds good to me, how do we do it with GIVbacks? who is responsible for getting the data and setting it up in a spreadsheet? 

Is there someway we can automate that part? @divine-comedian @mohammadranjbarz

**Comment by divine-comedian** [comment]
right now @WhyldWanderer does all of the spreadsheet gathering for GIVbacks, so if mohammad makes the API query then probably Ashley would be the one assembling it. 

The problem, if I understand would be when we run createdAt every 2 weeks or something is that we have to run it against a list of projects that have already gotten OP and that list also needs to be maintained and updated regularly.|

I have no idea how to automate this.

**Comment by WhyldWanderer** [comment]
Right now we only have 200 verified projects that can even be eligible for this. 

Can't we add the project ID to a 'redlist' once they have received the OP?
Then, in each round of GIVbacks, I can pull the new project IDs that have added Optimism wallets, distribute the OP, and then add those project IDs to the list? Once we have reached 640 project IDs on the list, we stop.

It makes much more sense to track project ID's because it wont change even if the wallet address changes.
I could see it working something like the purple list...

**Comment by laurenluz** [comment]
I like that idea a lot @WhyldWanderer!

Also I know we only have 200 projects that could be eligible so far. We really need to push this from a comms perspective and we can use it as an extra incentive for people to add their projects to Giveth and get verified.  I already created yhe issue in comms,  I think I tagged you.

**Comment by laurenluz** [comment]
Hey @WhyldWanderer @divine-comedian @mohammadranjbarz 

We have received this OP now and so we should start distirbuting it to projects who add their OP address.

Comms is starting [a new campaign](https://github.com/Giveth/giveth-planning/issues/1510) to tell projects to get verified & add their OP address, so we should set up a process for actually sending the funds out.

Can you guys start adding it to our regular flow?

**Comment by divine-comedian** [comment]
@mohammadranjbarz Do we have a way currently that we can get a list of projects that have added Optimism Addresses into a CSV?

**Comment by mohammadranjbarz** [comment]
[projects_with_OP_addresses_2023-13-AUG.csv](https://github.com/Giveth/giveth-dapps-v2/files/12329119/projects_with_OP_addresses_2023-13-AUG.csv)

@divine-comedian here you are
(I used below query for fetch this file)
```
SELECT 
    pa."createdAt" as "walletAddressAddedTime",
    pa."projectId",
    pa.address,
    p.slug
FROM 
    project_address pa
JOIN 
    project p ON pa."projectId" = p.id
WHERE 
    pa."networkId" = 10 AND pa."isRecipient" = true
ORDER BY 
    pa."createdAt" ASC;

```

**Comment by divine-comedian** [comment]
> [projects_with_OP_addresses_2023-13-AUG.csv](https://github.com/Giveth/giveth-dapps-v2/files/12329119/projects_with_OP_addresses_2023-13-AUG.csv)
> 
> @divine-comedian here you are (I used below query for fetch this file)
> 
> ```
> SELECT 
>     pa."createdAt" as "walletAddressAddedTime",
>     pa."projectId",
>     pa.address,
>     p.slug
> FROM 
>     project_address pa
> JOIN 
>     project p ON pa."projectId" = p.id
> WHERE 
>     pa."networkId" = 10 AND pa."isRecipient" = true
> ORDER BY 
>     pa."createdAt" ASC;
> ```

Is there any place where we can run this query ourselves? 

Basically it fetches everything to date matching the query, how do we get it into a CSV?

**Comment by mohammadranjbarz** [comment]
> > [projects_with_OP_addresses_2023-13-AUG.csv](https://github.com/Giveth/giveth-dapps-v2/files/12329119/projects_with_OP_addresses_2023-13-AUG.csv)
> > @divine-comedian here you are (I used below query for fetch this file)
> > ```
> > SELECT 
> >     pa."createdAt" as "walletAddressAddedTime",
> >     pa."projectId",
> >     pa.address,
> >     p.slug
> > FROM 
> >     project_address pa
> > JOIN 
> >     project p ON pa."projectId" = p.id
> > WHERE 
> >     pa."networkId" = 10 AND pa."isRecipient" = true
> > ORDER BY 
> >     pa."createdAt" ASC;
> > ```
> 
> Is there any place where we can run this query ourselves?
> 
> Basically it fetches everything to date matching the query, how do we get it into a CSV?

@divine-comedian  I run this query on database, if you want to do it yourself you should connect to DB with an application that has UI ( but it's not recommended because you might change something that you should not change it, and make a mistake)
Those applications have an option for download the result as CSV

**Comment by mohammadranjbarz** [comment]
> > > > [projects_with_OP_addresses_2023-13-AUG.csv](https://github.com/Giveth/giveth-dapps-v2/files/12329119/projects_with_OP_addresses_2023-13-AUG.csv)
> > > > @divine-comedian here you are (I used below query for fetch this file)
> > > > ```
> > > > SELECT 
> > > >     pa."createdAt" as "walletAddressAddedTime",
> > > >     pa."projectId",
> > > >     pa.address,
> > > >     p.slug
> > > > FROM 
> > > >     project_address pa
> > > > JOIN 
> > > >     project p ON pa."projectId" = p.id
> > > > WHERE 
> > > >     pa."networkId" = 10 AND pa."isRecipient" = true
> > > > ORDER BY 
> > > >     pa."createdAt" ASC;
> > > > ```
> > > 
> > > 
> > > Is there any place where we can run this query ourselves?
> > > Basically it fetches everything to date matching the query, how do we get it into a CSV?
> > 
> > 
> > @divine-comedian I run this query on database, if you want to do it yourself you should connect to DB with an application that has UI ( but it's not recommended because you might change something that you should not change it, and make a mistake) Those applications have an option for download the result as CSV
> 
> Oh sorry @mohammadranjbarz - these projects apparently need to be verified! can you refine this query and pass me the CSV?

@divine-comedian No problem, I guess they should be `verified` and also `active`, or just `verified`?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz - yes

@divine-comedian 
# Query
```
SELECT 
    pa."createdAt" as "walletAddressAddedTime",
    pa."projectId",
    pa.address,
    p.slug
FROM 
    project_address pa
JOIN 
    project p ON pa."projectId" = p.id
WHERE 
    pa."networkId" = 10 AND pa."isRecipient" = true AND p.verified = true AND p."statusId"=5
ORDER BY 
    pa."createdAt" ASC;
```

# Result
[active-verified-projects-that-have-optimism-address.csv](https://github.com/Giveth/giveth-dapps-v2/files/12335823/active-verified-projects-that-have-optimism-address.csv)

**Comment by divine-comedian** [comment]
Perfect! 

We'll need to run this periodically until we reach 200 addresses - this is good for now.

**Comment by brichis** [comment]
![image](https://github.com/Giveth/giveth-dapps-v2/assets/106570342/7c454a93-feb8-4ff2-870d-36fe415079c4)
GM! This is what I found on the Grant Proposal https://gov.optimism.io/t/giveth-growth-experiment/5637/12

**Comment by divine-comedian** [comment]
Thanks @brichis ! So none of this 16k OP was explicitly earmarked for liquidity - rather only what we'll get in the next round of RPGF funding?

**Comment by divine-comedian** [comment]
First batch of airdrop went out to 97 projects for 25 OP according to this sheet:
https://docs.google.com/spreadsheets/d/1pZ7SUtFcf6sNZ3A8fZXBvtDGAn_w21qD3WOaB4baDOE/edit?usp=sharing

We can keep running this query that mohammad made and filter out the duplicates or filter by date (AUG 14, 2023)

I did it via disperse.app, here;s the txs:
https://optimistic.etherscan.io/tx/0x75b2dd3d79aa53164a46f231ebed3c213d2b932a8455c6929cf1289b09d86a47
https://optimistic.etherscan.io/tx/0x291cdc497731f78642e3a991dec04cf18ac9d002f8b0df878763d21719bbbb29

I already notified @oyealmond to keep comms in the loop

**Comment by MoeNick** [comment]
What are the next steps @divine-comedian ?

**Comment by divine-comedian** [comment]
We'll keep checking periodically - maybe every other GIVbacks round (4 weeks) for new verified projects with OP addresses and do subsequent distributions 

We should keep this issue until we hit our promised cap of 640 projects.

**Comment by divine-comedian** [comment]
I think I'll close this issue and @mohammadranjbarz and I can coordinate on a monthly basis.

**Comment by divine-comedian** [comment]
Updated a new entry into the spreadsheet and used a formula to detect projects we already distributed to -
https://docs.google.com/spreadsheets/d/1pZ7SUtFcf6sNZ3A8fZXBvtDGAn_w21qD3WOaB4baDOE/edit?usp=sharing
