### ISSUE TITLE
Fix section of Landing page - Web3 Crypto Donation Platform

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-dapps-v2#2638]
hey @RamRamez , 

Can you update a paragraph for this landing page: https://giveth.io/landings/web3-crypto-donation-platform

To be this ->

Ethereum donations (also on Gnosis chain, Optimism, Polygon and Celo): Nonprofits and other projects can fundraise and accept donations on multiple chains including Ethereum mainnet, Gnosis chain, Optimism, Polygon and Celo, making it super easy for you to connect your wallet of choice (MetaMask etc.) and make Ethereum donations directly to any project.

**Comment by divine-comedian** [comment]
@RamRamez  - Did this get done?

**Comment by RamRamez** [comment]
> @RamRamez - Did this get done?

Sorry I missed this one.
I sent the PR, it's waiting for review.
