### ISSUE TITLE
Low pri: when decativating my project, the text box should only useable when I select "other"

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#264]
Right now, I can type in the box, but unless I select "other" it doesn't let me deactivate

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/2176fe72-20e6-445f-9bcd-624554ce0223)

**Comment by MoeNick** [comment]
@mosaeedi we need custom text while "Other" is selected, do we need to disable it until other options are selected?

**Comment by mosaeedi** [comment]
by default, we just have to present the dropdown and hide the Textarea, when the user chooses "Other" the Textarea will appear!

Also please change "Other/Prefer not to say" to just "Other"!

[default state modal](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=3879%3A106350)

[When "Other" is selected](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=6302%3A133371)

**Comment by laurenluz** [comment]
it's awesome. works as described.
