### ISSUE TITLE
Update the token list for Giving block

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#2644]
I noticed some tokens on the giving block's token list that probably aren't acceptable anymore... we should remove the tokens that are not on gemini's list anymore: https://support.gemini.com/hc/en-us/articles/115005868106-What-cryptos-are-supported-on-the-Gemini-Exchange-

Bonus points for adding some of the new tokens that are there as well... like Pepe :-D

**Comment by MoeNick** [comment]
Can I ask @brichis or @WhyldWanderer to help us with this? 

The feature is on the adminJS, we need some OPS or support here, Admins can add remove or edit ANY token for the supported networks.

**Comment by WhyldWanderer** [comment]
I can help with this!

**Comment by WhyldWanderer** [comment]
I removed the tokens that are no longer accepted.

When I try to add new tokens, I get an error that says to check the console. 
Here is what is in the console:
![image](https://github.com/Giveth/giveth-dapps-v2/assets/74267818/4d063de8-5614-4b44-a564-3fd2a782e489)

However, even though I get an error it looks like the token I added (ENS) was successfully added to the list.

Im unsure if I should proceed adding more of the tokens or not after receiving this error.

**Comment by mohammadranjbarz** [comment]
> I removed the tokens that are no longer accepted.
> 
> When I try to add new tokens, I get an error that says to check the console. Here is what is in the console: ![image](https://user-images.githubusercontent.com/74267818/246527180-4d063de8-5614-4b44-a564-3fd2a782e489.png)
> 
> However, even though I get an error it looks like the token I added (ENS) was successfully added to the list.
> 
> Im unsure if I should proceed adding more of the tokens or not after receiving this error.

Hey @WhyldWanderer  I think it's ok, just please at the end put the tokens you have added here to someone else (I or @CarlosQ96 ) check it in admin panel and DB to make sure everything is ok

**Comment by MoeNick** [comment]
@WhyldWanderer can you take a look again?

**Comment by WhyldWanderer** [comment]
Sure! I have not added any tokens yet, only removed the above ones. 

I will put this back on my todo list and make some time for it this week.

**Comment by MoeNick** [comment]
Hey just a reminder on this @WhyldWanderer

**Comment by MoeNick** [comment]
Hey @WhyldWanderer 
Just a kindly reminder on this, can be edited on AdminJS. 

FYI @divine-comedian
