### ISSUE TITLE
Add GatewayFM to partner projects

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-dapps-v2#2645]
As you probably are aware we are exploring a partnership with GatewayFM who kindly offered to sponsor dedicated RPC connection. I would like to give back a little. Can we add them to our partnerships page? (https://giveth.io/partnerships)

https://gateway.fm/

*Unbreakable
Web3 Infrastructure
That Seamlessly
Scales With You*

Logo seems to be a bit harder but we can ask them if a nice vector graphic exists.

**Comment by divine-comedian** [comment]
Boom! 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/905cd82f-5991-4b96-8723-f3ed5d7f1af1)
