### ISSUE TITLE
Sometimes the "All notification" doesn't shown in notification menu

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#2647]
**Describe the bug**
When the text of 4 notifications displayed in the menu is more than a certain limit, "All notification" is not displayed and the user couldn't tap on "all notification" to see all o them
@MohammadPCh 

**Screenshots**
<img width="1433" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/6f42cefe-35c9-441a-9ad5-a605030f1185">

**Comment by MohammadPCh** [comment]
@alireza-sharifpour can you check it, please?

**Comment by alireza-sharifpour** [comment]
> @alireza-sharifpour can you check it, please?

Sure, i'm working on it
