### ISSUE TITLE
Change copy of Giveth project link metadata

### ISSUE THREAD

**Issue by Cotabe** [Giveth/giveth-dapps-v2#2649]
I realized that when we send the Giveth link it says you can donate directly to over 1000 projects.

![Giveth SEO intro.PNG](https://images.zenhubusercontent.com/6239faf88ad3a4ffddc12d98/2b6fccf4-d3f6-4284-9af6-5b4370bca5d5)

I believe we should update it to well over 2000 projects. Here is the banner of the landing page for reference

![Giveth total projects.PNG](https://images.zenhubusercontent.com/6239faf88ad3a4ffddc12d98/b20fdce4-c55e-4af5-943d-590d64edf759).

Curious to know your thoughts: @ahmadabugosh  @WhyldWanderer  @MoeNick  @laurenluz

**Comment by laurenluz** [comment]
@MoeNick - can you assign someone?
