### ISSUE TITLE
Slug for new project 'MetaGame' is changing after edits.

### ISSUE THREAD

**Issue by luxumbra** [Giveth/giveth-dapps-v2#265]
Firstly, amazing work on Giveth as a whole and the new update. 🚀 

The issue: I created a new project for MetaGame yesterday and the URL that it was at when I first published was https://giveth.io/project/MetaGame. I then made some edits to the description and after saving, I noticed that the URL had changed to https://giveth.io/project/MetaGame-0 and the previous one returned a 404. Today, the original URL was working again but after completing the verification application, shortly before the site went down for todays update, I notice that we are back to the MetaGame-0 URL.

**Comment by mohammadranjbarz** [comment]
Thanks for reporting

@MoeNick
We merged the PR can you test it please?

**Comment by luxumbra** [comment]
> Thanks @mohammadranjbarz I think it's resolved. @luxumbra would u pls confirm. Please try to edit the project w title and wo the title, and all new and old URLs should work fine and show your recent changes.

That was quick! 😄 Thank you both @mohammadranjbarz & @MoeNick. Sorry, do you mean to try an edit with a changed Project name and one with just the description for example?

**Comment by MoeNick** [comment]
@luxumbra yeah
But it's optional just to make you sure, we tested it, it was working.

**Comment by luxumbra** [comment]
@MoeNick would it be possible to change our default slug to simply 'metagame' as it was when I set the project up? Even though /metagame works, the share feature uses /metagame-0 which isn't so clean.

**Comment by CarlosQ96** [comment]
@luxumbra Hello! I changed your slug back to only "metagame"

**Comment by luxumbra** [comment]
@CarlosQ96 thank you much! 🙏🏻

**Comment by luxumbra** [comment]
@CarlosQ96, I just noticed in the share modal, the vercel domain is showing instead of giveth.io.
![image](https://user-images.githubusercontent.com/780350/158897896-96ca4a40-4d1d-402c-a425-a2a7fe76cbc1.png)

**Comment by CarlosQ96** [comment]
Thanks for reporting! @mateodaza @pkretzschmar will take a look soon enough.

**Comment by luxumbra** [comment]
Cheers and thanks for the support.
