### ISSUE TITLE
QF - New Quadratic Funding Projects Page

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2652]
For quadratic funding, we should have a new dedicated projects page that shows only the projects that are part of QF. It's kind of like with a QF filter applied, but it's always there. 

The URL should be https://giveth.io/qf

And it will look like this! (roughly).

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/f905a85a-39df-44f1-a4a2-77b10213c817)

Note: The design will change a little, namely:
- Gitcoin passport banner needs to updated with Giveth design vibe
- All project cards should still have the GIVpower boost small icon (but no rank)
- All of the projects will have the QF version of the project card
- The copy in the middle-page banner will change
- The banner at the top of the page will change
- Some colors/styling may change

Still, I think we can start building the page, with all of that in mind.

Link to [figma](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=1486-64154&t=v9RpJgXeL6iRVDHB-4)

@MoeNick @MohammadPCh - can you assign the appropriate person?

cc @markoprljic @mosaeedi

**Comment by laurenluz** [comment]
Note: gitcoin passport banner is in https://github.com/Giveth/giveth-dapps-v2/issues/2654

**Comment by MoeNick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-Devs-61644589b92edf0016f6999c/issues/Giveth/giveth-dapps-v2/2652?planning-poker) with Zenhub @alireza-sharifpour @mateodaza @MohammadPCh @RamRamez

**Comment by MoeNick** [comment]
Questions:
- filtering located in the "filter by a category " section , so it means user won't be able to filter by category and rounds together, besides, we have a filtering menu at the end of this page, I think we have to change the design to put it there instead of category 
- What-if we have 20 rounds? 20 buttons in a section won't seem ok.

**Comment by laurenluz** [comment]
I don't think we will ever have 20 simultaneous rounds... and once a round is over, we can remove the filter button. The QF Round 1 Filter button should only exist for 2 weeks whil ther round is active. Does that make sense?

In the future, maybe we will have like a QF Climate Round, QF Celo Round, etc... so we can have a few buttons at the same time... but also we can reconsider in the future if we need to adjust the design.

And re: your 1st question.. can they not select multiple buttons at the same time?

**Comment by laurenluz** [comment]
The banner for this page has been completed by Rodri and can be found [here](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=1690-73265&t=Gufua3FP3WCi8U8M-4)

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/d0212d3b-0f3d-42e8-85cf-e2c2c0485ac6)

**Comment by maryjaf** [comment]
One question , when there are no active round, what is the expected result by selecting quadratic funding  in drop down menu(https://givqf.vercel.app/qf) ?
Now in this situation the below pic is shown 
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/440b7717-09b8-4129-8c03-92982a17db08)
@MohammadPCh @laurenluz

**Comment by MohammadPCh** [comment]
@laurenluz Nice catch,
In my opinion, we need to show another page that says QF round finished.

**Comment by laurenluz** [comment]
Thanks @maryjaf @MohammadPCh!

We need to consider a few cases:
1. There is an upcoming QF round but it hasn't started yet - In this case, we should have a banner showing what the start time of the round will be... and perhaps the projects are hidden
2. A QF round recently ended - In this case, I think we should show in the banner that the round has ended... it would be nice if people could still see the projects & donations... and they could donate, but not get matching
3. A round has not recently ended, and there is no round coming soon - in this case, I think we need another banner that says "There is no active QF round" and perhaps a CTA.

@markoprljic what do you think? Can you help w/ opinions and designs?

**Comment by laurenluz** [comment]
@MohammadPCh I think we can go ahead w/ my ideas here and make it simple.

1. If there is an upcoming round that is scheduled but not yet started... let's just have the banner subtext say "round starts in days:hrs:seconds"
2. If a recent round recently ended, we should show everything the same... put the subtext is hidden on the main banner... and we should have the gitcoin passport top banner look like this: ![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/dda72b99-6665-444e-a329-f4c3bc495361)

I will create an issue for the final case in which there is no soon upcoming or recently ended round.

**Comment by laurenluz** [comment]
created issue #2728 for design
