### ISSUE TITLE
QF - Project Single page for QF projects

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2653]
For projects that are actively part of a QF round, they will have a modified project single page. It will look like this:

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/c12a8b4b-8f29-475e-8a7d-1ec3bf9bd71d)

Notes:
- The key difference is the donate card w/ the estimate matching amounts & numbers
- The numbers for the estimate matching on donations should come from the work in: https://github.com/Giveth/impact-graph/issues/980 (forked from gitcoin)
- The gitcoin passport banner will change in styling and will have different variations on text
- Donations page is not finished yet, we can only work on the main tab

Link to [figma](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=1331-59634&t=v9RpJgXeL6iRVDHB-4)

Can you assign the appropriate person? @MoeNick @MohammadPCh 

cc @markoprljic @mosaeedi

**Comment by laurenluz** [comment]
Note: gitcoin passport banner is in #2654

**Comment by MoeNick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-Devs-61644589b92edf0016f6999c/issues/Giveth/giveth-dapps-v2/2653?planning-poker) with Zenhub @alireza-sharifpour @mateodaza @MohammadPCh @RamRamez

**Comment by MoeNick** [comment]
According to @MohammadPCh it's blocked by responsive and @mosaeedi is working on this today.

**Comment by MoeNick** [comment]
@alireza-sharifpour is taking care of responsiveness of this page

**Comment by alireza-sharifpour** [comment]
We don't have the backend side. @MoeNick

**Comment by MoeNick** [comment]
Just to confirm @laurenluz 
![image](https://github.com/Giveth/giveth-dapps-v2/assets/80677512/c06c7645-1b51-41fd-9cf6-1aeb88c8b3f7)
These numbers are for the current round.

**Comment by laurenluz** [comment]
yes exactly @MoeNick

**Comment by laurenluz** [comment]
Hey @alireza-sharifpour - the designs have been updated based on our discussions. Can you revise?

Now, we have, for projects in an *active* QF round, donation card shows "amount raised in this round" [link to figma](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=1632-73102&t=LnMFdneB8oKQlfKt-4)

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/b5729e44-9121-47a5-9fc4-8bd4fb104f79)

For projects that are not part of an active QF round, we should say "Total amount raised". I'm asking Mo to do a quick updated of that part in the figma [here](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=857-56699&t=LnMFdneB8oKQlfKt-4)

**Comment by alireza-sharifpour** [comment]
Thanks @laurenluz for letting me know.
I'll update the frontend side based on the new designs

**Comment by mosaeedi** [comment]
Sorry for sharing this comment late!
Thanks @alireza-sharifpour for working on this page, it looks really good!
But there is some inconsistency in the developed page. Please take a look at the screenshot I've shared.

![Screenshot 2023-06-22 at 11.39.34 AM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/90d1f612-0f9e-43a6-9165-f1330456fd23)

**Comment by RamRamez** [comment]
@mosaeedi I checked boost toast and it was ok.
![image](https://github.com/Giveth/giveth-dapps-v2/assets/73441857/39422fd4-335f-4590-8b5c-619a17aaaccc)
![image](https://github.com/Giveth/giveth-dapps-v2/assets/73441857/8c4917cd-7d7f-4a68-b3da-61c229bf0ee7)

**Comment by mosaeedi** [comment]
@RamRamez The boost card size is okay, the problem is the project banner which is taller than it should be.

**Comment by maryjaf** [comment]
The logic of these field in below pic isn't clear for me that I can test it, please send the formula or logic @alireza-sharifpour @MohammadPCh 
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/061505e9-3943-4fa5-a888-146e4b45c8e4)

**Comment by alireza-sharifpour** [comment]
> The logic of these field in below pic isn't clear for me that I can test it, please send the formula or logic @alireza-sharifpour @MohammadPCh ![image.png](https://camo.githubusercontent.com/8085ad9df3026691369df9122f1edbb4637f40f29cd724313a12cdd5be9cb19f/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f30363135303565392d333934332d346661352d613838382d313436653462343563386534)

This section shows for example with 10 DAI donation, this project will receive how much extra matching.

**Comment by RamRamez** [comment]
> @RamRamez The boost card size is okay, the problem is the project banner which is taller than it should be.

@mosaeedi Project image height is 380px same as in Figma design

![image](https://github.com/Giveth/giveth-dapps-v2/assets/73441857/265b70ca-51bd-430b-9eac-8ecb90180b99)

**Comment by maryjaf** [comment]
> > The logic of these field in below pic isn't clear for me that I can test it, please send the formula or logic @alireza-sharifpour @MohammadPCh ![image.png](https://camo.githubusercontent.com/8085ad9df3026691369df9122f1edbb4637f40f29cd724313a12cdd5be9cb19f/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f30363135303565392d333934332d346661352d613838382d313436653462343563386534)
> 
> This section shows for example with 10 DAI donation, this project will receive how much extra matching.

Yeah , but I want to check the calculation , it isn't clear for me how it is calculated ,
and the field of Next Update

**Comment by alireza-sharifpour** [comment]
> > > The logic of these field in below pic isn't clear for me that I can test it, please send the formula or logic @alireza-sharifpour @MohammadPCh ![image.png](https://camo.githubusercontent.com/8085ad9df3026691369df9122f1edbb4637f40f29cd724313a12cdd5be9cb19f/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f30363135303565392d333934332d346661352d613838382d313436653462343563386534)
> > 
> > 
> > This section shows for example with 10 DAI donation, this project will receive how much extra matching.
> 
> Yeah , but I want to check the calculation , it isn't clear for me how it is calculated , and the field of Next Update

This is the function we are using to calculate this amount:
```ts
export const calculateEstimatedMatchingWithDonationAmount = (
	donationAmount: number,
	projectDonationsSqrtRootSum?: number,
	allProjectsSum?: number,
	matchingPool?: number,
) => {
	if (!matchingPool || !donationAmount) return 0;
	const _projectDonationsSqrtRootSum = projectDonationsSqrtRootSum || 0;
	const _allProjectsSum = allProjectsSum || 0;
	const beforeNewDonationPow = Math.pow(_projectDonationsSqrtRootSum, 2);
	const afterNewDonationPow = Math.pow(
		_projectDonationsSqrtRootSum + Math.sqrt(donationAmount),
		2,
	);
	return (
		(afterNewDonationPow /
			(_allProjectsSum + afterNewDonationPow - beforeNewDonationPow)) *
		matchingPool
	);
};
```
we receive all amounts from backend and put donationAmount here to calculate the final value.
If you have questions about this formula and why we use it you can ask @aminlatifi as he is the expert of this!
@maryjaf

**Comment by alireza-sharifpour** [comment]
And about the next update field we should remove it as we don't have it yet in the backend.
So i'll remove it.

**Comment by MohammadPCh** [comment]
@ I think it should open the QF doc in a new tab, am I right @laurenluz ? and do we have this doc link?

**Comment by laurenluz** [comment]
it will be at: https://docs.giveth.io/quadraticfunding cc @franculio
