### ISSUE TITLE
QF - Gitcoin Passport Banner

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2654]
We will have a few different conditions for passport banner:

- not connected
- match eligible
- match ineligible
- loading
- invalid passport
- error
- invalid response

We can fork what gitcoin did [here](https://github.com/gitcoinco/grants-stack/blob/860d30236624686e38a2a6feb1bc5dada3eeb7c6/packages/grant-explorer/src/features/common/PassportBanner.tsx#L63) for copy & states. Check lines approx. 173 to 236

We should use Giveth styling though for these, so waiting on an update from @mosaeedi but I think we can still start with setting up the states & copy.

@MoeNick @MohammadPCh - can you assign the right person?

cc @markoprljic

**Comment by MoeNick** [comment]
@mohammadranjbarz to wrap the Gitcoin Services with @aminlatifi 
@MohammadPCh will investigate how we can we map with these patams.

**Comment by aminlatifi** [comment]
https://github.com/Giveth/impact-graph/issues/987

**Comment by MoeNick** [comment]
@markoprljic 
Is it assigned to @rodricastillo9013 or @mosaeedi ? 
And which pages we have to consider this banner, only in single project and donation page?

**Comment by markoprljic** [comment]
Either Mo or Rodri. 
Single and Donation, yes.

**Comment by laurenluz** [comment]
@markoprljic shouldn't we have it also on the main QF page as well? the QF projects page?

**Comment by laurenluz** [comment]
You can see all the conditions & copy in gitcoin's code [here](https://github.com/gitcoinco/grants-stack/blob/860d30236624686e38a2a6feb1bc5dada3eeb7c6/packages/grant-explorer/src/features/common/PassportBanner.tsx#L63). Check lines approx. 173 to 236

**Comment by mosaeedi** [comment]
Here is the completed component on Figma.

[Figma link](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=936-58385&t=rZ8BKKrgoJnrjagv-4)

@laurenluz I used the Copy from Gitcoin. Please take a look and make sure they are consistent with Giveth.

**Comment by laurenluz** [comment]
Copy is fine w/ me! Thanks @mosaeedi !

if you can just resolve Marko's comment about the banner not being so alarming, then we can let Cherik take it away.

**Comment by MoeNick** [comment]
Yes it shift the whole page down.

**Comment by MoeNick** [comment]
Did you integrate it with the backend @MohammadPCh ? Is there any blocker? shall we move it to unit test?

**Comment by CarlosQ96** [comment]
Ok the endpoints are:

**Comment by CarlosQ96** [comment]
@RamRamez @MohammadPCh here are 3 endpoints from the gitcoin api and passport submit let me know if you have question. There is more to this but this is like the core start

**Comment by MohammadPCh** [comment]
@CarlosQ96  Thanks, I will dm you and ask questions.

**Comment by laurenluz** [comment]
@MohammadPCh - the designs/copy for the gitcoin passport banner have been updated and approved. The [link is here](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=2521-95177&t=LnMFdneB8oKQlfKt-4).

They look like this w/ 8 different conditions:
![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/2c3ff38a-bdfe-4279-ae12-879c0bcb3bc1)

**Comment by MohammadPCh** [comment]
@laurenluz Where are we gonna show this banner? I just add this banner to the project page.

**Comment by maryjaf** [comment]
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/4a36d5b9-0f8d-4820-9d81-4cc70a8a707d)
To which page should the "update score" be redirected?

**Comment by maryjaf** [comment]
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/7d9d5394-75f5-44e5-a109-3930db137fc6)
When  and under what conditions should I see this Gitcoin Passport Banner? @MohammadPCh

**Comment by maryjaf** [comment]
I set a new QF round (https://dev.serve.giveth.io/admin/resources/QfRound/records/36/show)
but after that I haven't seen this banner, why?

**Comment by MohammadPCh** [comment]
@maryjaf We only show the passport banner on projects that belong to the current active qf round.

**Comment by laurenluz** [comment]
> 
@laurenluz Where are we gonna show this banner? I just add this banner to the project page.

@MohammadPCh we should show this banner on the major pages related to QF including:
- QF projects page
- QF project single page
- QF donation page

We won't have the banner at the top of the passport page... but we show the same information lower on the page (as you know).

We DON'T need to show the banner on:
- My account
- My projects
- My donations

**Comment by maryjaf** [comment]
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/1e18651b-2c27-4131-bf2e-345dab5a68ae)
The round is not over, but I see this banner, plz check @MohammadPCh

**Comment by maryjaf** [comment]
2-
When I signed passport with account which hasn't passport profile, I see pic 1 when I expect that see pic 2

<img width="1373" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/69b00b09-f567-4fe7-8531-fe357be89457">


<img width="1099" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/5a2674ee-0832-4fd6-b125-8081a6a0455e">
@MohammadPCh

**Comment by maryjaf** [comment]
3- In some cases the shown passport status in not related to the account that I signed in, we can set a call to explain this case @MohammadPCh 

<img width="1430" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/85f1ecda-47b0-4fcc-a0e9-3b3d7cff14a0">

**Comment by maryjaf** [comment]
We talked about 1&2 and they are resolved

**Comment by maryjaf** [comment]
for some wallet account that it hasn't profile passport the pic 1  banner is shown  and others pic 2 @MohammadPCh 
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/26a0565e-b9c1-43e8-b50a-ab156262be85)
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/e23f3a8f-6efc-45c4-b226-0be05d92bf33)

**Comment by MohammadPCh** [comment]
@maryjaf Based on our conversation in the GIVeconomy call, we change the passport banner flow, and we get the user's score from our database, the user should go to the passport page and click on update score to update it. so please check the passport banner flow from zero again. 
Thanks

**Comment by laurenluz** [comment]
yes! Thanks @MohammadPCh and sorry about that @maryjaf , so to make it very clear:

- the passport score should only refresh when the user clicks "update score" on giveth.io/passport
- when the user clicks "go to passport" or "update score" on the banner, giveth.io/passport should open in a new tab. from there, they can update their score and get the refreshed version.
- "verify passport" from the banner should also open giveth.io/passport in a new tab.
