### ISSUE TITLE
Adding filtering by network to the front-end

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#2658]

**Comment by MoeNick** [comment]
@maryjaf pls take a look and confirm

**Comment by MoeNick** [comment]
@maryjaf pls take a look and confirm

**Comment by maryjaf** [comment]
When I set the cello filter, no project is displayed
Is this because it is a test chain on stage?  @MohammadPCh

**Comment by maryjaf** [comment]
Shouldn't Mainnet be in this list? @MohammadPCh 
<img width="373" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/2a391cf2-2659-4459-8cec-6f90a0247359">

**Comment by laurenluz** [comment]
ooh I just made an issue for it #2677

**Comment by MohammadPCh** [comment]
Final result:
![image](https://github.com/Giveth/giveth-dapps-v2/assets/17097576/2a48b3a2-f114-42ec-a98e-980dd45f3c32)

**Comment by laurenluz** [comment]
Nice, @MohammadPCh ! Can we adjust it a little more?
- delete title "Project features"
- for all chains, delete "accepts funds"... so it says, for e.g. "On Mainnet" "On Gnosis" "On Polygon"

**Comment by MohammadPCh** [comment]
@laurenluz @maryjaf What do you think about this?
![image](https://github.com/Giveth/giveth-dapps-v2/assets/17097576/e8987c9e-8b82-4189-956f-e5240ff9b301)

**Comment by laurenluz** [comment]
sure, sounds good!
