### ISSUE TITLE
Deploy token distro on Optimism

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2661]
Donations to projects on optimism should yield GIVbacks on Optimism. Therefore, we need to deploy GIVbacks & the GIVstream on optimism, and will need a token distro

@divine-comedian @aminlatifi 

FYI @MoeNick @mohammadranjbarz

**Comment by divine-comedian** [comment]
Amin created a test GIV token on Optimism Goerli 
https://goerli-optimism.etherscan.io/address/0xc916ce4025cb479d9ba9d798a80094a449667f5d

deployed test tokenDistro 
https://goerli-optimism.etherscan.io/address/0x8D2cBce8ea0256bFFBa6fa4bf7CEC46a1d9b43f6

implementation:
https://goerli-optimism.etherscan.io/address/0x78c07ac82bad3718affe3a99e5aaa78b0bbdc4e4

**Comment by divine-comedian** [comment]
sent test praise here
https://goerli-optimism.etherscan.io/tx/0x658c0d8f7be35879233be5d43db951050276467eb37da3e6df2ed15e229ca445#eventlog

### next step @aminlatifi deploy subgraph

**Comment by divine-comedian** [comment]
Fill out deployment information for goerli deployment 
https://github.com/Giveth/giveconomy-subgraph/blob/develop/networks.yaml

create start block for contract 
find block created for the proxy on etherscan 
fill this out and Amin * Mitch will have a call tomorrow morning

**Comment by divine-comedian** [comment]
changes are in:
https://github.com/Giveth/giveconomy-subgraph/commit/e3f916e44183d17e581af818a0333c001c629163

**Comment by divine-comedian** [comment]
Ready for front end deployment! Subgraph is ready 
https://thegraph.com/hosted-service/subgraph/giveth/giveth-economy-optim-staging
