### ISSUE TITLE
Design for GIVbacks & GIVpower on Optimism Chain

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2664]
We should add a new chain for claiming GIVbacks, and we should perhaps adjust copy through the dApp on donations so that the user knows what to expect.

This requires someone to walk through the dapp and make a list of suggested changes

I can do it later this week, or @divine-comedian if you have time

**Comment by divine-comedian** [comment]
Sorry I have a lot of things to manage this week

**Comment by laurenluz** [comment]
I made this [design spec doc](https://www.notion.so/giveth/Optimism-GIVbacks-Design-Spec-b0981e3f4ccf405c807a1e78a2bb2a6e) with some suggestions on things we should chain to accomodate Optimism GIVbacks.

@mosaeedi can you go through the doc and makes some designs for these pages? they are relatively small changes.

**Comment by laurenluz** [comment]
cc @MoeNick

**Comment by laurenluz** [comment]
Hey @mosaeedi - FYI I also just added some info at the bottom of the spec doc wrt to staking for GIVpower on multiple changes. I think we just need to add a little to the design on the GIVfarm page. I put some ideas in that notion, please let me know your thoughts.

**Comment by laurenluz** [comment]
redundant with #2512
