### ISSUE TITLE
Default sort for the donation table to be sorted by USD value of Donation instead of date

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#2668]
Yes it is nice to see that as a donor you just donated...

But if we sort by Donation USD Amount, we are effectively rewarding large donors... and incentivizing donors to to donate more... If someone wants to see their most recent donation, they can sort by time.

This should apply to QF AND our DApp in general... at least as an experiment... for some time.

**Comment by MoeNick** [comment]
It can be handled on Frontedn only, Am I right @MohammadPCh ?

**Comment by MohammadPCh** [comment]
Yes, It's possible.

**Comment by MoeNick** [comment]
Not sure who to assign, Can you do or assign it, please? @MohammadPCh

**Comment by maryjaf** [comment]
Thanks @MohammadPCh I checked and now default sorting is set by USD Value in all donation and QF round
