### ISSUE TITLE
For the Zcash grant request we need to design an "Anon donations, powered by Zcash" flow

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#2675]
**What problem is this design solving? Why is it necessary?**
We are applying for a huge grant from Zcash:

https://forum.zcashcommunity.com/t/giveth-and-zcash-grant-proposal/44597/6

They suggested they would give us more money if we design a flow that encourages Ethereum users to use Zcash for anon donations

**Is there any user data or feedback backing up this feature request?**
*Share any user research conducted by yourself or others.*

<img width="738" alt="Screenshot 2023-05-18 at 6 16 43 AM" src="https://github.com/Giveth/giveth-dapps-v2/assets/14945613/60a9811e-9489-4b71-834f-c84de7c6b3ce">

**Which metrics will define this feature's success?**
*Provide current and/or expected metrics.*

If we get the grant

**Additional context**
*Add any other context or screenshots related to your design here.*

All we need is some small design on the app... I'm imagining it like this (feel free to change it):

If a project adds a Zcash address, then, IF they click the Anonymous donation check box, then we have a hyper linked text that says "Want to make it truly anonymous? Use Zcash" 

That hyperlink, if they click it will pop up a modal the explains how to convert from ETH to Zcash and how to download a wallet.

## What I actually need

Just confirmation of this approach and maybe a quick mock up of the Hyperlinked text so i can show it in the forum post.

**Comment by markoprljic** [comment]
Technical confirmation to be provided by @MoeNick 
Design confirmed.

@mosaeedi Could you mock this up for Griff?

**Comment by GriffGreen** [comment]
he did! and i posted it :-D  https://forum.zcashcommunity.com/t/giveth-and-zcash-grant-proposal/44597/6 Thx Mo!
