### ISSUE TITLE
Changes for referral page

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#2676]
After recent improvements, user is able to create referral id from our website, and create links in all Giveth URLs like:

- https://giveth.io/?referrer_id=(paste-yours-here)
- https://giveth.io/project/{specific project}?referrer_id=(paste-yours-here)
- https://giveth.io/projects/?referrer_id=(paste-yours-here)
- etc.
- 
The way that we create referral id and empower the user to share the links is not appealing now, so:

**We have to change this page:** https://giveth.io/referral

And change the copy and have these steps: 

1- Connect Your Wallet > Sign > Get Referral ID >  a widget to create urls and put it in a cookie (or back-end) with share on social icon + copy icon

2- in a single project page > a button called "share with your referral id" > 
   if user has a  referral id ,it produces the link in a modal but copy and share icons .
   if not, get redirected to giveth/referral t  claim a referral id.

**Comment by MoeNick** [comment]
fyi @laurenluz @ahmadabugosh @mosaeedi 
open for comment and drafting a design.

**Comment by MoeNick** [comment]
@mateodaza this one is for you, please take a look
it can add to referral testing env

**Comment by mateodaza** [comment]
> @mateodaza this one is for you, please take a look it can add to referral testing env

Perfect! just in time to start working on it
