### ISSUE TITLE
Update filter drop-down on Projects page

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2677]
These filters are out of data & a bit weird. We should update them to be:

1. Remove title "Project Features"
2. Filters should be:
- Verified
- Mainnet
- Gnosis Chain
- Optimism
- Polygon
- Celo

And later, we will have the QF filter in this list as well.

I think we should remove the filters:
- boosted w/ GIVpower (sort of redundant w/ verified)
- from giving block (we are dissolving this partnership, no need to give them free advertising)
- accepts GIV (people should be allowed to donate GIV, but imo, it's better if we don't push people to donate GIV because this leads to sell pressure on the GIV token)

@MoeNick @MohammadPCh @CarlosQ96 
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/63328c81-c677-4027-bdcc-62e7368efbda)

**Comment by MohammadPCh** [comment]
@MoeNick @CarlosQ96 we don't have any filter for mainnet:
Variable "$filters" got invalid value "AcceptFundOnMainnet" at "filters[0]"; Value "AcceptFundOnMainnet" does not exist in "FilterField" enum. Did you mean the enum value "AcceptFundOnCelo", "AcceptFundOnGnosis", "AcceptFundOnOptimism", or "AcceptFundOnPolygon"?

**Comment by MohammadPCh** [comment]
Final result:
![image](https://github.com/Giveth/giveth-dapps-v2/assets/17097576/995de256-6fea-4553-8c71-1b0a0d5edb72)
