### ISSUE TITLE
QF Business Model

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2678]
We need to create criteria for QF as to why it is beneficial for GIveth. Some ideas:
- take a small % of matching pool (or a flat fee) to fund Giveth treasury / buy GIV
- Do we keep the "donate 5% to Giveth?" Should we add "donate 5% to the next matching pool?
- should giveth be in the rounds (likely not, based on what Gitcoin's experience was)
- Giveth Pro as hard requirement? Or abstract it as a beta
- GIVpower determines order
- if you have x gGIV in your wallet, get a boost on passport score

We should build a spreadsheet to illustrate the value adds of QF to Giveth, and make some decisions on which way to swing this!

cc @GriffGreen @divine-comedian @MoeNick

**Comment by divine-comedian** [comment]
I like:

- Giveth takes a % of Matching Pool, we calculate this at the beginning of the round and set it aside, send it to ourselves when the round closes.
- Giveth Pro as a requirement (after alpha round)
- hold gGIV to boost passport score
- order determined by GIVpower (actual rank, not projected, right?)

**Comment by laurenluz** [comment]
I agree! I like all those things too. We may also have to take a % of matching pool to offer our sybil detection solution people.

also, order should be determined by GIVpower - not rank, but the actual live GIVpower amount... so the "instant boost" results, imo. that way, people can actively affect the ranking during the round and we enough use of GIV and GIVpower.

**Comment by laurenluz** [comment]
From our call w/ disruption Joe: Apparently they conducted some user research and people generally felt that taking 15% of the matching pool was acceptable.

We may also need to give some part of this to our sybil protection solution

**Comment by laurenluz** [comment]
Notes from last GIVeconomy call:
    - make a spreadsheet to simulate QF, check different parameters and see what makes sense as a cut we take out
    - if we get $1M of matching funds, so we make a profit
    - Check how many donors are donating the 5% to Giveth
    - determine how many we can pay out to sybil protection
