### ISSUE TITLE
Instant Boost not communicating well enough to the user

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#2679]
THIS SHOULD NOT BLOCK THE RELEASE!!!

**Describe the bug**
Instant boost before had design on the main page that would tell the user that it takes 5 minutes to update the sort... no one reads the modal that pops up, they should see it in on the projects page after they close the success modal 

<img width="545" alt="Screenshot 2023-05-20 at 6 40 23 AM" src="https://github.com/Giveth/giveth-dapps-v2/assets/14945613/5a2abd4d-32d1-49a5-b116-dbd80fdcb1e3">

There used to be a timer there... i get that it might be inaccurate... but I really liked it! If there was a 5 minute timer every time, then at some point the sort would happen, so for sure if they check after the timer, the sort will have taken place... that would work great! Under promise over deliver, and great communication.

The timer is my preference because it's very entertaining and gets people excited about the change, but at least there should be some highlighted text under the rank that is communicating to the user that the rank will change in less than 5 minutes (and then the text should go away after the 5 minutes)

**Comment by MoeNick** [comment]
@laurenluz you may like to see this

**Comment by laurenluz** [comment]
There was part of the design missed. I created and issue for it #2680

Also this issue makes no sense otherwise. The rank isnt changing every 5 min, the position on the project page is.

We put that on the success modal and the givpower tab. When the project single page update goes through, it will be even better w the boost button in the same text box as #2680 but on the main project single page.

I refuse to ask the devs to add in an arbitrary 5 min timer and i 100% do not think this would make our dapp hetter

**Comment by laurenluz** [comment]
Hey @MoeNick - actually, we are waiting on design for this... it's just not a high priority. we discussed in the giveconomy calls that we need to perhaps add a timer back or some other communication. it's in @mosaeedi 's hands, but after QF & optimism

**Comment by mosaeedi** [comment]
After the user boosts and returns to the project detail, this timer will be visible below the Boost button.

<img width="1045" alt="Screenshot 2023-06-14 at 6 40 52 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/b1e5232d-bef4-414b-ba34-7641ec0dd833">

@laurenluz

**Comment by laurenluz** [comment]
@GriffGreen - are you happy with this?

**Comment by MoeNick** [comment]
Sent this one to Griff's DM for reminder

FYI: @divine-comedian
