### ISSUE TITLE
Deactivated Project confirmation: Links don't work!

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#268]
"Go to projects" should go --> https://giveth.io/projects
"Back to my account" should go --> https://giveth.io/account

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/26c93913-5927-4d3b-8819-5fdc57c9e940)

**Comment by NikolaCreatrix** [comment]
Tested - issue fixed!
