### ISSUE TITLE
"My Projects" isn't counting all my projects

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#269]
I have 4 projects, it says I have 3

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/9c49378f-6b20-4a48-952b-6df91e1e130a)

**Comment by CarlosQ96** [comment]
@mateodaza with my hotfix it seems to be working but you have to reload the page. Not sure what the bug is, could be cache?

**Comment by CarlosQ96** [comment]
After creating the project, the number doesn't update instantly unless you reload.

**Comment by CarlosQ96** [comment]
But in the project list it does show

**Comment by CarlosQ96** [comment]
I am inclined to believe that, the list is being fetched but the profile is not refetched thats why the numbers don't match when coming back to the view unless you reload it.

**Comment by CarlosQ96** [comment]
<img width="1393" alt="image" src="https://user-images.githubusercontent.com/92376054/158713359-1132aa7c-3d08-450c-80da-69c63bea9862.png">

**Comment by CarlosQ96** [comment]
@RamRamez @mateodaza @MohammadPCh @mohammadranjbarz I think the backend is working fine now. But when coming back to this view, the profile data should be refetched to it matches with the project list/ donation list

**Comment by aminlatifi** [comment]
We can do the same as we do in updating liked project counter! Whenever a user creates a project we can increase it.

**Comment by divine-comedian** [comment]
testing on `staging.giveth.io`

I accessed several of my user accounts and counted the projects vs. the total displayed. 
everything seems to match up, call this one DONE!
