### ISSUE TITLE
Change GIVpower item to instant query and make it default

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#2691]
that doesn't make sense because the rank is not affected by instant boost! It should be:

1- GIVpower (instant boosting)
2- Rank (previous ranking)

_Originally posted by @laurenluz in https://github.com/Giveth/giveth-dapps-v2/issues/2626#issuecomment-1557572026_

**Comment by laurenluz** [comment]
Thank you @MoeNick ! Let me know if this needs further clarification @MohammadPCh

**Comment by MohammadPCh** [comment]
This is the final version:
![Screenshot from 2023-05-24 12-31-48](https://github.com/Giveth/giveth-dapps-v2/assets/17097576/937e37ea-3e06-4e71-9183-7dc060c7d756)
1. GIVpower (sort projects by instant boosting) -> default
2. Rank (sort projects by givpower)

**Comment by laurenluz** [comment]
@MohammadPCh - the Rank option should sort by the rank numbers, i.e. average GIVpower of the previous round. Is that what's happening here?

Also I would switch the icons for GIVpower & rank, so we have 🚀 GIVpower, and perhaps # Rank.

**Comment by MohammadPCh** [comment]
@laurenluz Yeah Exactly :) and about the icons I will switch them.

**Comment by laurenluz** [comment]
thank you!

**Comment by maryjaf** [comment]
Every thing is ok on production we can close this issue.
