### ISSUE TITLE
QF - Donation Page

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2692]

**Comment by laurenluz** [comment]
Design is ready for the donate page! [link to figma](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=2259-93618&t=H1s3nHekMcuH4OGd-4)

@MohammadPCh - can you assign the right person?

**Comment by maryjaf** [comment]
When I enter amount of GIV, estimated matching is shown 0 ?why? @RamRamez 
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/db913d64-24ce-4324-85b7-74c6f89cd199)

**Comment by mosaeedi** [comment]
## Responsive guides

Donation (>1280 & <1439)
[Figma link](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=3344-116619&mode=design&t=ZFYDlXVbvJeWRFXN-4)

Donation (>1024  & <1279)
[Figma link](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=3344-116711&mode=design&t=ZFYDlXVbvJeWRFXN-4)

Donation (>768  & <1024)
[Figma link](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=3344-116881&mode=design&t=ZFYDlXVbvJeWRFXN-4)

Donation (Mobile)
[Figma link](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=3344-118355&mode=design&t=ZFYDlXVbvJeWRFXN-4)

**Comment by RamRamez** [comment]
> @maryjaf I tested for GIV and WETH tokens and the estimated matching changes as expected. But it doesn't change when I enter different amounts of xDai. @alireza-sharifpour can you check it please?

I fixed it and sent the PR. It's waiting for review.
@maryjaf you can test it after the PR is merged.

**Comment by maryjaf** [comment]
> > @maryjaf I tested for GIV and WETH tokens and the estimated matching changes as expected. But it doesn't change when I enter different amounts of xDai. @alireza-sharifpour can you check it please?
> 
> I fixed it and sent the PR. It's waiting for review. @maryjaf you can test it after the PR is merged.

ُThanks, Please let me know when it is ready to test

**Comment by RamRamez** [comment]
@maryjaf You can test it.

**Comment by maryjaf** [comment]
Thanks @RamRamez 
Now the estimated matching is calculated but i'm not sure this calculation is right ?
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/03dbcf16-3a37-4eff-9e4c-61aa294980f2)
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/722f9234-460a-4983-8f9c-a92e1d4953f3)

**Comment by RamRamez** [comment]
> Thanks @RamRamez Now the estimated matching is calculated but i'm not sure this calculation is right ? ![image.png](https://camo.githubusercontent.com/40cc2aa72fd1d6d952d6eb37222cc3e5781f0f0f1fe6866d1ed5c2d592357493/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f30336462636631362d336133372d346566662d396534632d363161613239343938306632) ![image.png](https://camo.githubusercontent.com/fa7b568a78d97459910f935649da79e7718a8e637289dff650762dafa4f78327/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f37323266393233342d343630612d343938332d386639632d613932653164343935336633)

@aminlatifi Can you please check these and approve them?

**Comment by maryjaf** [comment]
> @CarlosQ96 - can you check to see if the matching calculations are right? @maryjaf - are you testing on https://givqf.vercel.app/qf

Yes I checked with demo and now have a conflict with the result shown in the demo.
This is because on donation page, every donation is considered as a new wallet address, if it can be a wallet that has already has a donation and in this case, the number we display on this screen is not correct

**Comment by laurenluz** [comment]
right! so as discussed in the GIVeconomy call on wed, our estimate matching calculation assumes that the donor is new and never donated before... if they had donated before of course their actual matching will be different.

but that's ok. we can include this explanation in our docuemtnation and ignore this case.
