### ISSUE TITLE
QF - Donation Success Page

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2693]

**Comment by maryjaf** [comment]
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/23c97136-e5bb-42ab-8de2-1a2d8b204a43)

I don't know this time is related about which fields in backend , It seems wrong @RamRamez

**Comment by RamRamez** [comment]
> ![image.png](https://camo.githubusercontent.com/6e8f4eb022d2c66d0a89c6d81c3f2b52146b619edbe832e89af5e69b95e46c8f/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f32336339373133362d653562622d343261622d386465322d316132643862323034613433)
> 
> I don't know this time is related about which fields in backend , It seems wrong @RamRamez

I fixed it and sent the PR. It's waiting for review.

**Comment by maryjaf** [comment]
When I tap on "Go to passport" I'm redirected to :https://givqf.vercel.app/ @RamRamez

**Comment by maryjaf** [comment]
Plz check this scenario, is this expected? @RamRamez 
I donate with a wallet which it's score is lower than minimum score and after donation I see this box correctly
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/6b329ca9-bc70-44b8-a6e2-08f87f985488)
when I change my wallet from MetaMask and connect a wallet with higher score, the box is changed although I didn't donate with this wallet 
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/8d53d78e-17db-4425-a94d-0a608768a15b)
and some times the end date isn't shown correctly
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/8caad848-ed48-4406-9edf-87c6cedd0527)

**Comment by RamRamez** [comment]
> When I tap on "Go to passport" I'm redirected to :https://givqf.vercel.app/ @RamRamez

I fixed it and my PR is waiting for review.

**Comment by RamRamez** [comment]
> Plz check this scenario, is this expected? @RamRamez I donate with a wallet which it's score is lower than minimum score and after donation I see this box correctly ![image.png](https://camo.githubusercontent.com/27073a085696b92ecadbed048b3de8e3d11094eb047c9fad8bc230ae85cf8db2/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f36623332396361392d626337302d343462382d613665322d303866383766393835343838) when I change my wallet from MetaMask and connect a wallet with higher score, the box is changed although I didn't donate with this wallet ![image.png](https://camo.githubusercontent.com/136da5cc5029088dc4ed20c369f5f089e82787c59c82e7f9da813ea5d48938a2/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f38643533643738652d313764622d343432352d613934642d306136303837363861313562) and some times the end date isn't shown correctly ![image.png](https://camo.githubusercontent.com/6dd87b5488186ef0813ddb773d916b6a4aed9a383254035d52db24a79f54f852/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f38636161643834382d656434382d343430362d396564662d383763366365646430353237)

@maryjaf About first and second image, we use a custom hook for updating passport and when wallet changes, it automatically updated passport state. And we should change that hook for this specific case for success page.
Changing wallet on success page is a rare case and I think we can skip that.

**Comment by RamRamez** [comment]
> Plz check this scenario, is this expected? @RamRamez I donate with a wallet which it's score is lower than minimum score and after donation I see this box correctly ![image.png](https://camo.githubusercontent.com/27073a085696b92ecadbed048b3de8e3d11094eb047c9fad8bc230ae85cf8db2/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f36623332396361392d626337302d343462382d613665322d303866383766393835343838) when I change my wallet from MetaMask and connect a wallet with higher score, the box is changed although I didn't donate with this wallet ![image.png](https://camo.githubusercontent.com/136da5cc5029088dc4ed20c369f5f089e82787c59c82e7f9da813ea5d48938a2/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f38643533643738652d313764622d343432352d613934642d306136303837363861313562) and some times the end date isn't shown correctly ![image.png](https://camo.githubusercontent.com/6dd87b5488186ef0813ddb773d916b6a4aed9a383254035d52db24a79f54f852/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f38636161643834382d656434382d343430362d396564662d383763366365646430353237)

@MohammadPCh can you check third picture please?
When I change account on MetaMask, passport hook returns null for current round.

**Comment by maryjaf** [comment]
> > Plz check this scenario, is this expected? @RamRamez I donate with a wallet which it's score is lower than minimum score and after donation I see this box correctly ![image.png](https://camo.githubusercontent.com/27073a085696b92ecadbed048b3de8e3d11094eb047c9fad8bc230ae85cf8db2/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f36623332396361392d626337302d343462382d613665322d303866383766393835343838) when I change my wallet from MetaMask and connect a wallet with higher score, the box is changed although I didn't donate with this wallet ![image.png](https://camo.githubusercontent.com/136da5cc5029088dc4ed20c369f5f089e82787c59c82e7f9da813ea5d48938a2/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f38643533643738652d313764622d343432352d613934642d306136303837363861313562) and some times the end date isn't shown correctly ![image.png](https://camo.githubusercontent.com/6dd87b5488186ef0813ddb773d916b6a4aed9a383254035d52db24a79f54f852/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f38636161643834382d656434382d343430362d396564662d383763366365646430353237)
> 
> @maryjaf About first and second image, we use a custom hook for updating passport and when wallet changes, it automatically updated passport state. And we should change that hook for this specific case for success page. Changing wallet on success page is a rare case and I think we can skip that.

Thanks @RamRamez 
No problem, if @laurenluz approves, we can ignore it

**Comment by laurenluz** [comment]
1. Passport links

"Go to passport" should go to https://givqf.vercel.app/passport - does it @RamRamez?

We should have all our links "to passport" and "to update score" from **the banner** open *our* passport page in a new tab.
From the donation success page, "go to passport" can redirect to *our* passport page (no new tab).

The user should only get sent to gitcoin's passport page from our passport page (giveth.io/passport), and gitcoin's page should always open in a new tab (not redirect the same tab). 

@MohammadPCh - this is the flow we agreed to, right? :) 

2. Re: 1st & 2nd image (donation success page w/ wallet change)

I think it's ok if we ignore this case of changing wallet on the success page. It won't be a problem on the passport banners or any other page, and it's true that it's kind of a rare case that someone would switch wallet here. If we were to build any other solution.. we'd kind of need to get rid of the donation success page all together because they actually didn't donate to that project from that wallet 😅 

I'll keep it in mind though.

3. Invalid date

@CarlosQ96 @mohammadranjbarz - we need to be able to set somewhere the round start & end dates. Are we doing that already in admin bro? It would also be nice to be able to set the "gitcoin passport eligibility end date" (the "invalid date" in the pictures above) somewhere too... because we might want to make it a day or a few days after the "round end date".

**Comment by RamRamez** [comment]
@laurenluz 

1. "Go to passport" does go to `/passport`

2. I agree with you. In success page if wallet is changed, we still show `You're a giver now!`
I can switch to donate page when wallet is changed. Does it work for you?

**Comment by laurenluz** [comment]
For 2. @RamRamez yeah! If that's easy to do, that solves all the problems :)

**Comment by RamRamez** [comment]
> For 2. @RamRamez yeah! If that's easy to do, that solves all the problems :)

Done! It's merged on QF branch.

**Comment by maryjaf** [comment]
> 1. "Go to passport" does go to `/passport`

In one other issue Lauren refers that when tap on o passport the user should be  redirected to passport page in new tab @RamRamez

**Comment by RamRamez** [comment]
> 1. Passport links
> 
> "Go to passport" should go to https://givqf.vercel.app/passport - does it @RamRamez?
> 
> We should have all our links "to passport" and "to update score" from **the banner** open _our_ passport page in a new tab. From the donation success page, "go to passport" can redirect to _our_ passport page (no new tab).
> 
> The user should only get sent to gitcoin's passport page from our passport page (giveth.io/passport), and gitcoin's page should always open in a new tab (not redirect the same tab).
> 
> @MohammadPCh - this is the flow we agreed to, right? :)
> 
> 2. Re: 1st & 2nd image (donation success page w/ wallet change)
> 
> I think it's ok if we ignore this case of changing wallet on the success page. It won't be a problem on the passport banners or any other page, and it's true that it's kind of a rare case that someone would switch wallet here. If we were to build any other solution.. we'd kind of need to get rid of the donation success page all together because they actually didn't donate to that project from that wallet 😅
> 
> I'll keep it in mind though.
> 
> 3. Invalid date
> 
> @CarlosQ96 @mohammadranjbarz - we need to be able to set somewhere the round start & end dates. Are we doing that already in admin bro? It would also be nice to be able to set the "gitcoin passport eligibility end date" (the "invalid date" in the pictures above) somewhere too... because we might want to make it a day or a few days after the "round end date".

here @maryjaf
`From the donation success page, "go to passport" can redirect to _our_ passport page (no new tab).`

**Comment by maryjaf** [comment]
In this case that there is a round that it hasn't started yet and some project is linked to this round
when I  tap on donate for this project, in donation page the estimated matching is shown although the round it hasn't started 
and in the success page of donation the box related to Quadratic Funding is shown
I think it should be revised if this scenario could be happened on prod @laurenluz @RamRamez 

![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/f26d1297-4d6e-4e25-be8e-61d2c7e7a9e8)

![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/802c5d58-cbce-4a4e-9574-73a083ba3000)

**Comment by laurenluz** [comment]
definitely!! in order for us to show estimated matching, there should be two conditions:
1. the project should be in the current QF round
2. The current date must be past the start date and before the end date of the QF round

**Comment by RamRamez** [comment]
> definitely!! in order for us to show estimated matching, there should be two conditions:
> 
> 1. the project should be in the current QF round
> 2. The current date must be past the start date and before the end date of the QF round (we should be able to set these dates in Admin bro)

I talked with @mohammadranjbarz. Backend checks for end dates and will deactivate rounds automatically if passed, so in frontend side, we only need to check the begin date and active field of QF rounds.
I sent the PR and it's waiting for review.

**Comment by maryjaf** [comment]
> > definitely!! in order for us to show estimated matching, there should be two conditions:
> > 
> > 1. the project should be in the current QF round
> > 2. The current date must be past the start date and before the end date of the QF round (we should be able to set these dates in Admin bro)
> 
> I talked with @mohammadranjbarz. Backend checks for end dates and will deactivate rounds automatically if passed, so in frontend side, we only need to check the begin date and active field of QF rounds. I sent the PR and it's waiting for review.

Thanks @RamRamez I checked and this problem has been resolved.
