### ISSUE TITLE
QF - Project Single Page Donation tab

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2694]

**Comment by laurenluz** [comment]
Ok @MohammadPCh ! Design here is ready, can you hook us up & assign the right dev? Maybe it's you? 😻 

[link to figma](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=1651-150440&t=H1s3nHekMcuH4OGd-4)

Note:
- we have filters to see donations that were part of each round
- we removed an old seemingly useless column
- the "funds raised" box on the right shows different numbers based on the filters that are applied
- if a project is part of an active QF round, we show "Estimated Matching"
- if the QF matching round has ended and the funds have been distributed, we show "Matching Funds" instead of "Estimated Matching"... if the funds have not yet been distributed, we show "+ TBD" instead of the number for matching funds. (this condition isn't shown in the design, but I left a comment for Mo).

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/1fe4f850-5bdf-47b6-b783-52ef36d3100e)

**Comment by CarlosQ96** [comment]
yeah 👍

**Comment by CarlosQ96** [comment]
@MohammadPCh @RamRamez to get the estimated matching formula parts required for calculations you can use this or the projects new field estimatedMatching that returns the same structure.
```
export const expectedMatchingFormulaQuery = `
  query (
    projectId: Int!
  ) {
    expectedMatching(
      projectId: $projectId
    ) {
      projectDonationsSqrtRootSum
      allProjectsSum
      matchingPool
    }
  }
`;
```

Furthermore we use this method to calculate the estimated matching final number in the backend. However you will have to implement it on your side, to calculate how much a new donation would increase the estimated matching.
```
export const calculateEstimatedMatchingWithParams = async (params: {
  matchingPool: number;
  projectDonationsSqrtRootSum: number;
  allProjectsSum: number;
}): Promise<number> => {
  const { projectDonationsSqrtRootSum, allProjectsSum, matchingPool } = params;

  return (
    ((projectDonationsSqrtRootSum * projectDonationsSqrtRootSum) /
      allProjectsSum) *
    matchingPool
  );
};
```

We can have a meeting tomorrow to go through it. But to calculate how much a certain donation would increase the matching.
You need to:
1. Add the new SquareRootSum to the projects total squareroot sum.
2. Subtract the old squareroot sum to the AllProjectsSum and add the new one.
3. Rerun the formula with the new values for the new estimated matching.
4. Subtract the new estimated matching - old estimated matching.

Like in the previous PRs.
The project also has the attributes, countUniqueDonorsForActiveQfRound, sumDonationValueUsd, sumDonationValueUsdForActiveQfRound in its fields returned from any query you previously used.

**Comment by MohammadPCh** [comment]
@alireza-sharifpour FYI :)

**Comment by mohammadranjbarz** [comment]
@MohammadPCh  @alireza-sharifpour 

donations filter by donations is done and we'll be deployed on develop in 20 minutes,  and @CarlosQ96  is working on the remaining things of this issue

please see https://github.com/Giveth/impact-graph/pull/1028#issuecomment-1590544180

**Comment by MohammadPCh** [comment]
@mohammadranjbarz Thanks a lot :)

**Comment by alireza-sharifpour** [comment]
Hey @CarlosQ96, I think we also need some additinal data based in the design 
<img width="514" alt="Screenshot 2023-06-14 at 4 20 02 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/48887817/cc308f7f-b236-4db7-afaf-70858db3ea79">
Here we need Matched amount for specific Round + Number of contributors for that specific round (both for Active round and prev rounds) + transaction link
and also for each round it seems like the total amount is not changing when we specify the selected round in the filter

**Comment by MohammadPCh** [comment]
![image](https://github.com/Giveth/giveth-dapps-v2/assets/17097576/36d4f7fb-6e3a-49a3-b368-5b643873f89e)
What should we show if the round doesn't have any donations?
I think it's confusing to leave it blank :smiling_face_with_tear:  @laurenluz @mosaeedi

**Comment by laurenluz** [comment]
if a project was not part of the QF round, then we should not show this filter for them at all.
if they were part of the QF round, but there were no donations in that round, we can say, in the donation table part: "This project didn't raise any funds in < QF Round x >."

And for the donation card. We can show it like this... Note @MohammadPCh - let's not say "Round: QF Round x"... just delete the "Round", as it is here:
![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/24fe0d03-84ca-4843-99a9-13e8839c5825)

**Comment by mosaeedi** [comment]
## Responsive guides

Project Single - Donations (>1280 & <1439)
[Figma link](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=3343-108197&mode=design&t=ZFYDlXVbvJeWRFXN-4)

Project Single - About (>1024  & <1279)
[Figma link](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=3343-109411&mode=design&t=ZFYDlXVbvJeWRFXN-4)

Project Single - About (>768  & <1024)
[Figma link](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=3344-112336&mode=design&t=ZFYDlXVbvJeWRFXN-4)

Project Single - About (Mobile)
[Figma link](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=3344-114391&mode=design&t=ZFYDlXVbvJeWRFXN-4)

**Comment by maryjaf** [comment]
1-In all donation tab the number of contributor isn't shown
!https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/af4f8a1c-cf9e-4e04-b3b9-009deff1682e

2-In closed round tab with some donation the amount of donation isn't shown 
!https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/debf22f0-ba3b-4729-bb96-8b9e8f1bf472 

3- In closed round with any donation It seems better the design and message are changed 
!https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/3ed7ffda-7b65-441e-bd79-0cb13726f7fa

@MohammadPCh

**Comment by MohammadPCh** [comment]
@maryjaf Thanks,
1, please check this again :)
2. I think it's about the backend calculations, this round is ended before the backend implemented completely and maybe this is the reason.
3. I put a new message there but we need @laurenluz 's confirmation. this is the message that I show now:
![image](https://github.com/Giveth/giveth-dapps-v2/assets/17097576/c09cf4ac-e328-42bd-924d-1558b109075f)

**Comment by MohammadPCh** [comment]
@mohammadranjbarz could you please take a look? (for Item 2) :point_up_2:

**Comment by mohammadranjbarz** [comment]
@maryjaf 
about this on
> 2-In closed round tab with some donation the amount of donation isn't shown

The account that donated to this project has `passportScore=4.48` but `minimumPassportScore` for that round is `8` and when calculating the qfRound history donation value USD we consider donor's passportScore despite of estimated matching, so the donations amount USD that we count is zero for that project in that round

@laurenluz  @MohammadPCh I think it might be confusing it would be good if you explain it below the USD amount that we just calculated matching fund eligible donations

**Comment by laurenluz** [comment]
@mohammadranjbarz actually, let's discuss!

All donations should be included in our "total donation" amount for QF rounds. We should neglect the passport score. I think we even decided to neglect passport score in our estimated matching amount calculations... so the user is encouraged to donate and not worry about passport... they can increase their score any time.

We will only need to know if the user had a sufficient passport score or not at the end of the round when we are sending the eligible donor addresses to Trustalabs for sybil analysis, so we'll basically need to be able to query for it when the round ends.

Do you disagree?

**Comment by mohammadranjbarz** [comment]
> 

1. @laurenluz Actually the history that we create here and frontend shows are being generated after qfRound ends, so there is no more time for those users to increase their passportScore, but this is totally a business decision, and changing it to ignore passport score in history items is an easy and small task to implement


2. And for this part 
> We will only need to know if the user had a sufficient passport score or not at the end of the round when we are sending the eligible donor addresses to Trustalabs for sybil analysis, so we'll basically need to be able to query for it when the round ends.
I think we need to backup all qf donations to another table including donor's passportScore to know their score after round ends, because currently we just have a number ad we don't have a history of changes of passportScores

**Comment by laurenluz** [comment]
1. I think even if the user does not have sufficient passport score at the end of the round to be considered for matching, we should still include their donation amount in the "total" on the donation tab.

2. yeah I think that might be a good idea. because it's true that passport score might increase later... and then those donations should be eligible for matching, and we should make note of that before sending the final donation list to Trustalabs.

**Comment by maryjaf** [comment]
When I donate with Goerli my donation is shown in all donation but it isn't shown in donation of specific round 
Is it  related to test network or we have a bug? @mohammadranjbarz 
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/7c15cf60-036e-4642-857e-9ccf8cc7be68)
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/b6a45628-0667-483f-ba0a-820ed383235a)

**Comment by mohammadranjbarz** [comment]
@carlos

> 1. I think even if the user does not have sufficient passport score at the end of the round to be considered for matching, we should still include their donation amount in the "total" on the donation tab.
> 2. yeah I think that might be a good idea. because it's true that passport score might increase later... and then those donations should be eligible for matching, and we should make note of that before sending the final donation list to Trustalabs.

@CarlosQ96  I did the first one, can you handle the second item?
I think it would be good to have a new collection to save these data to that after round ends

donationId, donationUsdValue, donorScore, projected and other fields you think we need them, when filling this table after ending rounds we should  ignore donations that are not related to desired qfRound and donations that their donor passportScore is less than qfRound.miniumPassportScore, we are going to use this table data for distributing matching funds

@maryjaf  Now we ignore passportScore in qfRoundHistory so you would see correct total amount there.

**Comment by CarlosQ96** [comment]
Working on the second issue Mohammad mentioned

**Comment by CarlosQ96** [comment]
> When I donate with Goerli my donation is shown in all donation but it isn't shown in donation of specific round Is it related to test network or we have a bug? @mohammadranjbarz ![image.png](https://camo.githubusercontent.com/bc72b394024b672853c9889de5615312a7581c74257de36bcc560895c03a7f07/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f37633135636636302d303336652d343634322d383537652d396363663863633762653638) ![image.png](https://camo.githubusercontent.com/1aa075c7b7325dffef0d66ad323adbdc14cd29e3646cdc94c16d1da00aa6bf92/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f62366134353632382d303636372d343833662d626130612d383230656433383332333561)

I checked the donations, they had no qf round, added a qfround an the filters work fine. Seems the QFround is null. Are you sure the round was active? all rounds show inactive.

That's the reason why it never set the qfround to the donations and the filter didn't find anything.

**Comment by maryjaf** [comment]
> > When I donate with Goerli my donation is shown in all donation but it isn't shown in donation of specific round Is it related to test network or we have a bug? @mohammadranjbarz ![image.png](https://camo.githubusercontent.com/bc72b394024b672853c9889de5615312a7581c74257de36bcc560895c03a7f07/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f37633135636636302d303336652d343634322d383537652d396363663863633762653638) ![image.png](https://camo.githubusercontent.com/1aa075c7b7325dffef0d66ad323adbdc14cd29e3646cdc94c16d1da00aa6bf92/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f62366134353632382d303636372d343833662d626130612d383230656433383332333561)
> 
> I checked the donations, they had no qf round, added a qfround an the filters work fine. Seems the QFround is null. Are you sure the round was active? all rounds show inactive.
> 
> That's the reason why it never set the qfround to the donations and the filter didn't find anything.

Thanks for checking @CarlosQ96
Based on pic and the date of the 6th round in the admin, when I donated, the 6th round was active, but I will check again if it doesn't happen again, we can close this.

**Comment by maryjaf** [comment]
I checked again and there isn't any problem about that
