### ISSUE TITLE
QF - My Account Overview Tab

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2695]
Add Gitcoin Passport - we need to decide if we want to keep the stamps

**Comment by laurenluz** [comment]
My account design is ready! [link to figma](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=1164-58099&t=H1s3nHekMcuH4OGd-4)

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/10f569ae-dfb6-443f-b5be-180c968923f8)

Passport connected - any score:
![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/d2b9c2ed-0262-42f5-b4a7-0248411733fc)

Passport not connected:
![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/99b589e0-2aa2-4ba9-aa06-1bfe997d829a)

**Comment by maryjaf** [comment]
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/df00ad2d-834b-46dc-9cdd-a2085f44e7e7)

To which page should the "learn more" be redirected? /passport?
and based on figma "learn more" should be in new line
plz check @MohammadPCh

**Comment by laurenluz** [comment]
@mosaeedi We need to update the design on My Account Overview to include GIVpower & be more similar to what exists on production.

**Comment by laurenluz** [comment]
@MohammadPCh - all ready for you! I left a comment in figma about the update score linking directly to gitcoin passport. It should open gitcoin's passport page in a new tab.
