### ISSUE TITLE
Notify Reward Bot to extend FOX/xDAI Rewards

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2702]
We will have 735,000 FOX going out over a 180 days
Waiting on the shapeshift team to confirm distribution rate (I think it will probably just be the same amount every week)
We should have a countdown time - duration tbd

Who should I assign this to? @aminlatifi @mohammadranjbarz 

cc @MoeNick

**Comment by MoeNick** [comment]
@aminlatifi can take it if it will not be too late until he's back.

**Comment by mohammadranjbarz** [comment]
@MoeNick  JFYI https://github.com/Giveth/giv-token-contracts/pull/90

**Comment by MoeNick** [comment]
Thanks @mohammadranjbarz I connect the PR
