### ISSUE TITLE
Frontend for extended FOX/xDAI RegenFarm

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2703]
We are extending the rewards for this farm! Once the specs are confirmed and we're read to set this up, the FOX/xDAI farm card should become "unarchived"... and start w/ a countdown timer until the notify reward begins.

cc @MoeNick @aminlatifi

**Comment by MohammadPCh** [comment]
@laurenluz could you please send me the start time?
