### ISSUE TITLE
Analytics dashboard bug

### ISSUE THREAD

**Issue by clara-zi** [Giveth/giveth-dapps-v2#2706]
https://analytics-dashboard-blue.vercel.app/

Total Donations Count/monthly numbers are the same as the Total USD donations numbers:

**Comment by clara-zi** [comment]
March number for donation count is incorrect? - looks like the total USD donations number: 128,186:

<img width="609" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/100724132/7b3ce7d5-9337-4f5f-89f7-698905af5c22">

Matching the total USD donations number: 128,186

<img width="626" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/100724132/679e9824-dcf3-449d-96e1-4f3c93b74d4a">


The same is true for each other month. Although, the aggregated/roll-up total appears to show the right numbers for each chart.

**Comment by MoeNick** [comment]
@RamRamez

**Comment by RamRamez** [comment]
@clara-zi That's weird. Maybe it was a temporary browser conflict.
Could you please test again?
[https://stats.giveth.io/](https://stats.giveth.io/)

<img width="947" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/73441857/6f4e74bf-60f4-4cb5-ad35-721fd4a5a9f3">

**Comment by MoeNick** [comment]
@maryjaf pls check it out again if you can. thanks

**Comment by clara-zi** [comment]
just checked and it's working ok now on my machine.
