### ISSUE TITLE
Trusted Seed project page edit failed

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#2711]
<img width="1079" alt="Screenshot 2023-05-29 at 5 03 53 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/14945613/0682abb1-2567-4052-ae8e-4b0871cdca76">

**Comment by GriffGreen** [comment]
HALP ... Ivy made a bug report too

**Comment by MohammadPCh** [comment]
It might be a temporary problem with the backend. anyway, I need more information to investigate.

**Comment by MohammadPCh** [comment]
@mohammadranjbarz this is the backend error, am I right?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz this is the backend error, am I right?

I have no idea, can we reproduce it to see what happens?

**Comment by MoeNick** [comment]
Griff do you guys still have this problem?

**Comment by iviangita** [comment]
It's working now! Thanks, everyone :)

**Comment by divine-comedian** [comment]
Looks to be a one off - closing this one
