### ISSUE TITLE
ReFi Keyword Landing Page

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#2713]
https://docs.google.com/document/d/1oD1fxHYLLY_hh8tidYZkINUcGNLmDEAsGTAt8Di8jN4/edit?usp=sharing

Here is the text for the SEO ReFi landing page. Let me know what you think please. It might be too long? In which case, the descriptions of the first list could be removed for example.

Should it have some charts or images? 

@c0ric0ri @ahmadabugosh

_Originally posted by @danelsuga in https://github.com/Giveth/giveth-planning/issues/1352#issuecomment-1547430663_

**Comment by RamRamez** [comment]
@ahmadabugosh what is the desired slug for this page? `/landings/refi` is ok?
