### ISSUE TITLE
The hover state on donation table

### ISSUE THREAD

**Issue by mosaeedi** [Giveth/giveth-dapps-v2#2715]
**Describe the bug**
When hovering on the donations table on my account, the projects column doesn't have the right hover style.

**To Reproduce**
1. Go to 'My account -> My Donations'
2. Hover on 'a donation'

**Expected behavior**
The whole row should change to the hover style while hovering.

**Screenshots**
<img width="1343" alt="Screenshot 2023-05-30 at 5 05 55 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/e79f3b62-6163-4730-b097-462b7578dc35">

**Desktop (please complete the following information):**
 - OS: [Mac os]
 - Browser [chrome]
 - Version [113]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MoeNick** [comment]
@maryjaf pls take a look
