### ISSUE TITLE
text is overlapping on the updates page - bad formatting

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#2717]
https://giveth.io/project/revillaging-mutual-mentorships-program-0?tab=updates

<img width="1337" alt="Screenshot 2023-05-30 at 3 27 52 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/14945613/5bcc3b48-5eaa-4569-b56a-0157bf9b0b6b">
<img width="734" alt="Screenshot 2023-05-30 at 3 27 56 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/14945613/8d21ce5a-3426-41aa-95fc-60dba605950e">

**Comment by RamRamez** [comment]
I fixed it. My PR is waiting for code review.

@maryjaf I did some code refactoring on Quill styles to prevent future inconsistency in formatting. Please test these scenarios:
1. create project page -> desc input
2. single project page -> project desc
3. single project page -> project updates (non owner view)
4. single project page -> project updates (owner view)
5. single project page -> project updates -> add new updates
6. single project page -> project updates -> edit existing updates

Thanks @maryjaf

**Comment by alireza-sharifpour** [comment]
It's ready to be tested @maryjaf

**Comment by maryjaf** [comment]
Thanks @RamRamez @alireza-sharifpour 
I checked and the previous issue has been resolved and no there is no overlapping on the update/ about page 

but I faced another issue 
Like as  below pic I selected a sentence to change the format into H1
but all of context is changed 
1-
<img width="703" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/23cb68f7-271d-4266-91c5-cbc43fbf2718">
2-
<img width="854" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/6d8020fc-bc5c-45af-bc0d-f4cba793ef72">

**Comment by RamRamez** [comment]
@maryjaf When H1 tag is selected, the tag is applied to the whole paragraph.

**Comment by maryjaf** [comment]
> @maryjaf When H1 tag is selected, the tag is applied to the whole paragraph.

So this is an expected behavior
Ok, we can move this issue to Done 
Should the old update of projects with this overlapping be corrected after deploying this change?

**Comment by RamRamez** [comment]
@maryjaf Yes, all project updates should be ok now.

**Comment by maryjaf** [comment]
I checked on prod and this issue has been resolved, thanks @RamRamez
