### ISSUE TITLE
GIVstream history table labels are not showing up properly

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#272]
You can see my GIV/HNY harvests are weird (on live)

@aminlatifi 
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/01c5a64b-c9a2-4efd-965c-2ddb9e094d05)

**Comment by divine-comedian** [comment]
testing on `staging.giveth.io`

checking out the history table I checked across all my txs - GIVdrop, GIVbacks, GIVfarm all images are showing correctly 
![image](https://user-images.githubusercontent.com/67759413/159365419-6cfa7f49-cd27-4c43-b56e-9645bfa1c83c.png)

calling this one DONE
