### ISSUE TITLE
Horizontal scroll - (Test Failed) 

### ISSUE THREAD

**Issue by MohammadPCh** [Giveth/giveth-dapps-v2#2725]
we have to release this horizontal issue:
![image](https://github.com/Giveth/giveth-dapps-v2/assets/17097576/7f87c52b-2ddb-4395-a206-d06e7f80cc89)

**Comment by MoeNick** [comment]
Does it ned to be tested again?

**Comment by maryjaf** [comment]
I could see the horizontal scroll in this size
[ Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbFVjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6e7cd50c47765b9d345c6fbb0f778c1f035897fc/image.png)
but  I couldn't move it much

**Comment by MohammadPCh** [comment]
@maryjaf Thanks for catching this, could you please add your screen size?

**Comment by maryjaf** [comment]
> @maryjaf Thanks for catching this, could you please add your screen size?

765*724

**Comment by MoeNick** [comment]
@MohammadPCh plseaaaase take a look, it rejected in UAT an back in progress.

**Comment by maryjaf** [comment]
I didn't see any change I think this issues had been moved to unit testing by mistake

**Comment by MoeNick** [comment]
Ok I put it back

**Comment by MoeNick** [comment]
@maryjaf jan, Cherik make another hot fix, please approve
