### ISSUE TITLE
QF - QF page when there is no active, recently ended or upcoming round

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2728]
@mosaeedi we should make a quick design for this... maybe just a simple landing page that explains what QF is and we have a CTA that's like "Support upcoming rounds! Donate the the matching pool here: < link >"

wdyt?

**Comment by mosaeedi** [comment]
### Design resource

[Link to Figma](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=3504-134086&mode=design&t=cnYtP505GEN96Flm-4)

**Comment by laurenluz** [comment]
Great! @MohammadPCh can you implement?

This should be the QF page at giveth.io/qf when there is no active QF round.
Donate should link to https://giveth.io/project/Giveth-Matching-Pool-0

**Comment by maryjaf** [comment]
Now In this case "there is no active, recently ended or upcoming round", the below pic is shown
<img width="1390" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/d1de8dba-6a44-428a-bb00-1db02467e35b">
Plz let me know when it's ready to test @MohammadPCh

**Comment by maryjaf** [comment]
I can't find the figma related to this scenarios 
Now we show this banner when there is no active, recently ended or upcoming round , is this ok? @laurenluz @MohammadPCh 
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/5d402af9-2fe3-49f1-8a4e-f68621a45a1c)
It think it's better that the highlighted part in this pic should be removed

**Comment by laurenluz** [comment]
yeah I agree - we should show the text that says "Quadratic Funding" on top, no "- Round --" @MohammadPCh

**Comment by maryjaf** [comment]
Thanks @MohammadPCh This problem has been resolved
