### ISSUE TITLE
Receiving error with certain images when trying to publish project

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#2738]
**Describe the bug**
Users are getting a non-descript error when trying to publish a project. It seems to be an issue with images. 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/74267818/19797f7d-30e6-4e40-9f36-0612b29e32e9)
https://discord.com/channels/679428761438912522/835168432520429578/1111975448574955610

![image](https://github.com/Giveth/giveth-dapps-v2/assets/74267818/7b4bfdf0-5c4c-4e01-9fbd-469792704eb0)
https://discord.com/channels/679428761438912522/808032358933856306/1113488448284790885

**To Reproduce**
I tried to reproduce the error and I believe it happens when you directly copy and paste an image into the description.

**Expected behavior**
I would expect that you should be able to copy/paste an image directly into the project description.
If this is not possible, then I would expect the error message to be more clear so that the user understands what the problem is and can rectify it.

**Comment by RamRamez** [comment]
@WhyldWanderer I created a project with a long description and several large images in description and it was ok for me. One of the images was about 6MB.

This is my test project:

https://staging.giveth.io/project/test-inline-image

**Comment by RamRamez** [comment]
@mohammadranjbarz @CarlosQ96 Can you check this?

When I try to add images to my project banner from my computer, app uploads images to myPinata, then we send the link to backend and it's all ok. But when I try to ad images from unsplash, we sent the unspash link to backend in createProject route, I give this error: "Argument Validation Error"

![image](https://github.com/Giveth/giveth-dapps-v2/assets/73441857/9ada9d0e-d99e-4ede-8682-e4464e64d1dd)

![image](https://github.com/Giveth/giveth-dapps-v2/assets/73441857/0f09659a-2765-4679-84b3-8be4b578f3e2)

**Comment by MoeNick** [comment]
@CarlosQ96 can you take a quick look pls?

**Comment by CarlosQ96** [comment]
Ill take a look

**Comment by CarlosQ96** [comment]
Looking at the project input from the mutations @RamRamez @MoeNick  we have a limit of 200 characters
```
export const IMAGE_LINK_MAX_SIZE = 200;
  

 @Field({ nullable: true })
  @MaxLength(IMAGE_LINK_MAX_SIZE)
  image?: string;
```

The link posted in the unplash picture seems to be quite long, this is the reason its failing. All those extra params extend the link past 200 characters.

Users that are getting errors, are usually copying and pasting into a text box the raw link, this leads to the huge long link version, this will fail.

**We can increase the image link max size, what would be a recommended character limit?
or remove the limit? or suggest a certain format for the links (maybe a shortened version)**

Because im sure even on google if you copy image address directly the link is WAYYYY to huge, so it will fail with our current validation.

**Comment by MoeNick** [comment]
Will it cause a problem if we remove the limitation of that link?

**Comment by CarlosQ96** [comment]
In theory, not really, it's minor database optimization.

It's a reasonable practice to keep things tight like urls, to prevent taking excessive space. We don't want massive strings in the database with unnecesary params that could generate _potential_ errors in the frontend or be badly formatted.

@aminlatifi  added it 4 months ago, as he added limitations to many strings that had no limit. (like titles)

What do you think @aminlatifi ? Maybe we should increase the size to a more reasonable amount but not entirely remove it. 

I'd say lets increase it a lot more but not remove it.

**Comment by RamRamez** [comment]
I can remove URL params but it's not efficient for the app, some Unsplash images are 100 kb and when I remove the params it become 1 MB, so it's better to increase character limit.

**Comment by MoeNick** [comment]
Let's remove the character limit, until @aminlatifi will get back and review. 
Thanks @CarlosQ96

**Comment by RamRamez** [comment]
@CarlosQ96 has doubled the char limit. @maryjaf can you test Unsplash images, please?

**Comment by MoeNick** [comment]
The problem was not only for unsplash images, pls take a look at main user report in the body of this issue.

**Comment by RamRamez** [comment]
> The problem was not only for unsplash images, pls take a look at main user report in the body of this issue.

I couldn't reproduce the problem. This is my test project with different inline images:
https://staging.giveth.io/project/test-inline-image

**Comment by maryjaf** [comment]
I haven't seen this error by copy and paste photo in description 
I'll try to check more scenarios to reproduce this

**Comment by aminlatifi** [comment]
Even doubling image url size to 400 is okay, I set that to prevent saving image data instead of link

**Comment by MoeNick** [comment]
@maryjaf try the Uganda project, the title of the project is there in Ashley's comment in top of this issue.
