### ISSUE TITLE
Test catalog for environment values

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-dapps-v2#2739]
DevOPS has begun to compile a catalog of **environment value locations** and **test cases** for certain things that need to be tested often in our maintenance work. 

The primary purpose is to know how to test when changing certain values. I would love to be paired with one of our backend devs pending availability. The session will be 1 hour max.

Following list is incomplete and will be extended:
- subgraphs
- RPC endpoints
- DAppMailer
- GIVnotification
- GIVpower
- GIVeconomy other things?

Maybe we can take over something from frontend testing as well @maryjaf - do you have a catalogue like this?

**Comment by mohammadranjbarz** [comment]
I will put the config infos here

**Comment by mohammadranjbarz** [comment]
@mhmdksh  @geleeroyale  I dont know if this is what you want or you need something 
else

* **RPC Endpoints and Keys**
  * `XDAI_NODE_HTTP_URL`
  * `ETHERSCAN_MAINNET_API_URL`
  * `ETHERSCAN_ROPSTEN_API_URL`
  * `ETHERSCAN_GOERLI_API_URL`
  * `POLYGON_SCAN_API_URL`
  * `POLYGON_SCAN_API_KEY`
  * `OPTIMISTIC_SCAN_API_URL`
  * `OPTIMISTIC_SCAN_API_KEY`
  * `CELO_SCAN_API_URL`
  * `CELO_SCAN_API_KEY`
  * `CELO_ALFAJORES_SCAN_API_URL`
  * `CELO_ALFAJORES_SCAN_API_KEY`
  * `GNOSISSCAN_API_URL`
  * `ETHERSCAN_API_KEY`
  * `GNOSISSCAN_API_KEY`
  *  `POLYGON_MAINNET_NODE_HTTP_URL`
  *  `CELO_MAINNET_NODE_HTTP_URL`
  *  `CELO_ALFAJORES_NODE_HTTP_URL`
  * `OPTIMISM_NODE_HTTP_URL`
  *  `OPTIMISM_GOERLI_NODE_HTTP_URL`
  * `INFURA_API_KEY

* **Price**
  * `GIVETH_GIV_PRICES_URL`
  
* **Pinata**
  * `PINATA_GATEWAY_ADDRESS`

* **GivPower**
   * `GIV_POWER_SUBGRAPH_URL`
   *  `GIV_POWER_UNIPOOL_CONTRACT_ID`
   *  `FIRST_GIVBACK_ROUND_TIME_STAMP`
   *  `GIVPOWER_ROUND_DURATION`
   
 * **Notification Center**
   * `NOTIFICATION_CENTER_BASE_URL`
   * `NOTIFICATION_CENTER_USERNAME`
   * `NOTIFICATION_CENTER_PASSWORD`
   
  * **Dapp Mailer**
    * `DAPP_MAILER_URL`
    * `DAPP_MAILER_AUTHORIZATION_KEY`

**Comment by divine-comedian** [comment]
@geleeroyale @mohammadranjbarz Is this issue still relevant?

**Comment by divine-comedian** [comment]
@geleeroyale @mohammadranjbarz please provide an update on this issue
