### ISSUE TITLE
Add "Share and get rewarded" Button to project single page. 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#2741]
if the user has signed in he can share the link of the project page with his referral ID but if the user didn't sign in in referral program, front end should ask for a referral and then create a link again.

There are some modals for connecting the wallet, signing in, and also error handling. 

The design is here. https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=1896-86071&t=NYufAAyI7SqfYZOi-4
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/ae8eb0d3-f9e8-4810-8a8b-a66632d80247)

The Modals: https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=2406-96745&t=NYufAAyI7SqfYZOi-4

![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/1112033d-4d5f-4d63-adca-df370adce0a5)

**Comment by maryjaf** [comment]
When I tap on one any of these 3 buttons nothing happens, plz check @mateodaza 
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/1c350c14-8309-4ff4-bd83-4340fd41ced0)

**Comment by maryjaf** [comment]
When I connect account 2 I get this link
https://giveth.io/project/the-giveth-community-of-makers?referrer_id=rKhkRoAgKMPRltoBqNYg9MzVDTT2

and when I connect account 3 I get this 
https://giveth.io/project/the-giveth-community-of-makers?referrer_id=fR1n0TkX3SUGAeIxNrfbpFyZZDz1&slug=d80fed75&utm_source=chainvine&utm_medium=chainvine&utm_campaign=chainvine
@mateodaza 

In which condition these parameters are shown in the link  slug,utm_source=,utm_medium,utm_campaign?

**Comment by maryjaf** [comment]
3-
In project owner view this button "Share & Get Rewarded" isn't shown, is this expected? @mateodaza @MoeNick 
4-
Since unverified project isn't Givback eligible, should we shown this button for these projects ?

**Comment by maryjaf** [comment]
5-
In this branch , when tap on one project this message is shown in project page
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/a10ef690-80eb-4468-a965-c072641f8bc2)
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/420007eb-5c01-480c-ad31-8ece4a80181a)

**Comment by maryjaf** [comment]
6- 
It seems we have a problem in donation flow by referral link
I do some donation with this link 
https://givchainvine.vercel.app/project/the-giveth-community-of-makers?referrer_id=fR1n0TkX3SUGAeIxNrfbpFyZZDz1&slug=d80fed75&utm_source=chainvine&utm_medium=chainvine&utm_campaign=chainvine
But when I check the /eligible-donations api the "isReferrerGivbackEligible" is  false

[
  {
    "amount": 0.0001,
    "currency": "ETH",
    "createdAt": "2023-06-16-02:45:04",
    "valueUsd": 0.166925,
    "bottomRankInRound": 133,
    "givbacksRound": 36,
    "projectRank": 1,
    "givbackFactor": 0.8,
    "valueUsdAfterGivbackFactor": 0.13354,
    "giverAddress": "0xcd192b61a8dd586a97592555c1f5709e032f2505",
    "txHash": "0x5ec569b6553ff8007b2b73ef35c5c874daf2ee00334566e72410e380e8b33336",
    "network": "optimistic",
    "source": "giveth.io",
    "giverName": "maryam jafarymehr",
    "giverEmail": null,
    "projectLink": "https://giveth.io/project/the-giveth-community-of-makers",
    "isReferrerGivbackEligible": false,
    "referrerWallet": null
  },

**Comment by mateodaza** [comment]
> 2- When I connect account 2 I get this link https://giveth.io/project/the-giveth-community-of-makers?referrer_id=rKhkRoAgKMPRltoBqNYg9MzVDTT2
> 
> and when I connect account 3 I get this https://giveth.io/project/the-giveth-community-of-makers?referrer_id=fR1n0TkX3SUGAeIxNrfbpFyZZDz1&slug=d80fed75&utm_source=chainvine&utm_medium=chainvine&utm_campaign=chainvine @mateodaza
> 
> In which condition these parameters are shown in the link slug,utm_source=,utm_medium,utm_campaign?

Those are trackers

**Comment by CarlosQ96** [comment]
Pushed hotfix on friday, and fixed manually the chainvineIds with extra params

**Comment by mateodaza** [comment]
@laurenluz so, an UX dilemma arise from the 4th point

if only verified projects get the  "share & get rewarded" button, then what should I show for regular projects? regular modal without the referral? 

 joining @mosaeedi  because maybe this decision would represent a change in design

**Comment by maryjaf** [comment]
Thanks @mateodaza @CarlosQ96 1 & 2 problems has been resolved.

**Comment by laurenluz** [comment]
@mateodaza what modal are you talking about? I think we should just not show the button at all.

**Comment by mateodaza** [comment]
> @mateodaza what modal are you talking about? I think we should just not show the button at all.

share button is on every project card also, so we would have to hide that for many projects - it's the same "share and get rewarded" modal every time

**Comment by laurenluz** [comment]
I think we should just hide the share & get rewarded button from the project single page, and from the project card if the project is not verified. Can we set up a condition like, if the project is verified - show the button.., if not - comment it out?

Thinking about it, this is going the be the least confusing overall... and it's kind of another incentive for projects to get verified... if you're verified... it's easier for people to share your project...

If we keep the share button on the project card for nonverified projects... it just becomes confusing. like I'm shareing a link to a project but I don't get rewarded for donations to that project... but I do get rewarded to donations to any OTHER verified project within x time period... it just turns into a headache.

If anyone has a better suggestion, by all means.. but I think this is simplest.

**Comment by MoeNick** [comment]
> @laurenluz so, an UX dilemma arise from the 4th point
> 
> 
> 
> if only verified projects get the  "share & get rewarded" button, then what should I show for regular projects? regular modal without the referral? 
> 
> 
> 
>  joining @mosaeedi  because maybe this decision would represent a change in design

@laurenluz I think @mateodaza is talking about the currant share modal that we have, I think its ok we have the regular share button in project cards for non-verified projects. 

Beside of that, why do have to remove them for non-verified projects? Urls can be simply create with users even for whole giveth.io with my ReferralId, so it wont make a problem, I only wont get rewarded for non-verified projects, its ok cause I might share my url even for the list of projects.

**Comment by CarlosQ96** [comment]
> 6- It seems we have a problem in donation flow by referral link I do some donation with this link https://givchainvine.vercel.app/project/the-giveth-community-of-makers?referrer_id=fR1n0TkX3SUGAeIxNrfbpFyZZDz1&slug=d80fed75&utm_source=chainvine&utm_medium=chainvine&utm_campaign=chainvine But when I check the /eligible-donations api the "isReferrerGivbackEligible" is false
> 
> [ { "amount": 0.0001, "currency": "ETH", "createdAt": "2023-06-16-02:45:04", "valueUsd": 0.166925, "bottomRankInRound": 133, "givbacksRound": 36, "projectRank": 1, "givbackFactor": 0.8, "valueUsdAfterGivbackFactor": 0.13354, "giverAddress": "0xcd192b61a8dd586a97592555c1f5709e032f2505", "txHash": "0x5ec569b6553ff8007b2b73ef35c5c874daf2ee00334566e72410e380e8b33336", "network": "optimistic", "source": "giveth.io", "giverName": "maryam jafarymehr", "giverEmail": null, "projectLink": "https://giveth.io/project/the-giveth-community-of-makers", "isReferrerGivbackEligible": false, "referrerWallet": null },

can you share the payload you shared in here? did the referrerWallet was null again?

**Comment by maryjaf** [comment]
> 

curl -X 'GET' \
  'https://givback.develop.giveth.io/eligible-donations?chain=optimism&startDate=2023%2F06%2F16-00%3A00%3A00&endDate=2023%2F06%2F16-23%3A59%3A59&download=no' \
  -H 'accept: application/json'
  
  My donation is shown in result of develop api giveback eligible but the referral is empty
  May this is related to this  test branch? https://givchainvine.vercel.app/ was linked to production

**Comment by mateodaza** [comment]
> > 
> 
> curl -X 'GET' 'https://givback.develop.giveth.io/eligible-donations?chain=optimism&startDate=2023%2F06%2F16-00%3A00%3A00&endDate=2023%2F06%2F16-23%3A59%3A59&download=no' -H 'accept: application/json'
> 
> My donation is shown in result of develop api giveback eligible but the referral is empty May this is related to this test branch? https://givchainvine.vercel.app/ was linked to production

yes, sadly we gotta test on production - will try to solve the old issues we had on the staging with @CarlosQ96 but for now please test on production projects

**Comment by laurenluz** [comment]
> @laurenluz I think @mateodaza is talking about the currant share modal that we have, I think its ok we have the regular share button in project cards for non-verified projects.
> 
> Beside of that, why do have to remove them for non-verified projects? Urls can be simply create with users even for whole giveth.io with my ReferralId, so it wont make a problem, I only wont get rewarded for non-verified projects, its ok cause I might share my url even for the list of projects.

@MoeNick ok - we can keep the currently share button and share modal for nonverified projects... and not have it show the referral id. We should not have it say anywhere though "share and get rewarded" on the nonverified projects.

**Comment by maryjaf** [comment]
> > > 
> > 
> > 
> > curl -X 'GET' 'https://givback.develop.giveth.io/eligible-donations?chain=optimism&startDate=2023%2F06%2F16-00%3A00%3A00&endDate=2023%2F06%2F16-23%3A59%3A59&download=no' -H 'accept: application/json'
> > My donation is shown in result of develop api giveback eligible but the referral is empty May this is related to this test branch? https://givchainvine.vercel.app/ was linked to production
> 
> yes, sadly we gotta test on production - will try to solve the old issues we had on the staging with @CarlosQ96 but for now please test on production projects

I donated to this project :
https://givchainvine.vercel.app/project/the-giveth-community-of-makers?referrer_id=fR1n0TkX3SUGAeIxNrfbpFyZZDz1&slug=d80fed75&utm_source=chainvine&utm_medium=chainvine&utm_campaign=chainvine
and I checked the givback eligible with this endpoint
https://givback.develop.giveth.io/eligible-donations
should I change the scenarios ? @mateodaza

**Comment by maryjaf** [comment]
> 5- In this branch , when tap on one project this message is shown in project page ![image.png](https://camo.githubusercontent.com/0653199d272dfeae68e9371c970023f131564938c5c94c6d2ca1eaa72807a099/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f61313065663639302d383065622d343436382d613936352d633037323634316638626332) ![image.png](https://camo.githubusercontent.com/de6047a61c5923dee4863b8ed8ca310aab700d88d567062748751c3b4f7f81c6/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f34323030303765622d356330312d343830632d616433312d386563653461383031383161)

This problem wasn't resolved, plz check again @CarlosQ96 @mateodaza

**Comment by maryjaf** [comment]
> 3- In project owner view this button "Share & Get Rewarded" isn't shown, is this expected? @mateodaza @MoeNick 4- Since unverified project isn't Givback eligible, should we shown this button for these projects ?

For double check 
must we show the "share & Get Rewarded" in project owner view? this is'n implemented yet @mateodaza @laurenluz 
and I'm not sure about the final decision related to the showing this button for non verified projects

**Comment by maryjaf** [comment]
> Thanks @mateodaza @CarlosQ96 1 & 2 problems has been resolved. Could you check 5 & 6 ? I've tested and they aren't resolved
Thanks @mateodaza @CarlosQ96 

Last updated about test
-item 5 & 3 has been fixed  and now the floating modal is shown in project owner view
-item 4 (unverified project) next phase
-item 6 Carlos is checking 
-in this phase we have this modal only in desktop view no mobile view 
@laurenluz @MoeNick

**Comment by laurenluz** [comment]
3. Project owner view
We should definitely show "Share & Get Rewarded" in the project owner view for verified projects. This is actually super important 😄  @mateodaza 

4.
For non-verified projects, we can do it as @MoeNick suggested - we can keep the regular modals & flow... but tbh, I think we should add some copy to the modal to clarify about verified projects... then people are not disappointed or confused when they share a referral link to a nonverified project...

Maybe we can change the copy "Here's your unique referral link" to "Earn GIV when someone donates to any verified project through your referral. Share your unique link to get started:" @MoeNick - what do you think?

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/82096ef3-8945-42e1-851e-869ab086d0c3)

**Comment by MoeNick** [comment]
Yes I completely agree with changing the copy @mateodaza @maryjaf

**Comment by maryjaf** [comment]
> -item 5 & 3 has been fixed and now the floating modal is shown in project owner view
in project owner view the button is shown, but now  for both verified & non-verified project is shown
