### ISSUE TITLE
Share and get rewarded in projects page. 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#2742]
Design assets:
https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=1988-81052&t=NYufAAyI7SqfYZOi-4

It should be floating button, modals will be the same as [in this issue](https://github.com/Giveth/giveth-dapps-v2/issues/2741)

**Comment by MoeNick** [comment]
Would u pls connect the PR to your issues and move them in the pipeline? :) @mateodaza

**Comment by maryjaf** [comment]
When I tap on get rewarded in project page, I get this link 
https://giveth.io/projects?referrer_id=FMzjWX4ueNSic8YLg20hYcOybkt2&slug=d80fed75&utm_source=chainvine&utm_medium=chainvine&utm_campaign=chainvine
but when I enter this link in my browser no projects are shown, plz check
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/3b167980-0632-4625-9b67-4c4e683afa97)

**Comment by maryjaf** [comment]
Thanks @mateodaza @CarlosQ96 this issue has been resolved
