### ISSUE TITLE
Enhance Configuration Setup for Frontend

### ISSUE THREAD

**Issue by mhmdksh** [Giveth/giveth-dapps-v2#2747]
Currently our frontend app is configured to run using the configuration values hardcoded in the source code file found under here:

https://github.com/Giveth/giveth-dapps-v2/tree/develop/src/config

To better service that application and to make it more versatile and portable to use (Especially that we have hosting changes coming to the Dapp soon)

We need all the configuration values that are concerned with managing the connection between other components of the Dapp to be configured from the .ENV file instead of being hardcoded. Basically the below values should also be able to be configured form the env:

- `NEXT_PUBLIC_BASE_ROUTE`
- `NEXT_PUBLIC_AUTH_BASE_ROUTE`
- `NEXT_PUBLIC_NOTIFICATION_BASE_ROUTE`
- `NEXT_PUBLIC_BACKEND_LINK`
- `NEXT_PUBLIC_FRONTEND_LINK`

**Comment by mhmdksh** [comment]
@MohammadPCh Can you update the readme.md so that it reflects those changes? And all other changes so that the documentation can be accurate. And prevent misleading

**Comment by MohammadPCh** [comment]
I think we can close it. wdty @mhmdksh ?

**Comment by mhmdksh** [comment]
It has been enhanced and merged already, thanks @MohammadPCh.

The only points are the documentation should be updated often, and we should confirm we are able to configure this on Vercel ENV as well so that it's the official way of config

But for now yes I don't see any reason to keep this open. Thanks again @MohammadPCh
