### ISSUE TITLE
Add Optimism to GIVbacks page

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2749]
Link to [figma](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/GIVeconomy?type=design&node-id=22488-208700&t=k2ZRnAVib40pDx6z-4)

Things to do:
- [x] Add Optimism to chain toggle
- [x] Change copy for when on the wrong chain/ wallet not connected
- [x] Switch network button --> opens modal w/ 2 chain options
- [x] Show optimism GIVbacks when wallet is connected to optimism

@MohammadPCh @MoeNick - who can take this?

**Comment by MohammadPCh** [comment]
Let me do it :)

**Comment by laurenluz** [comment]
Thanks @MohammadPCh! - keep in mind the new version of the network selector in #2751 

There should be nothing under "coming soon", Optimism should be considered live when we launch this. And we should show gnosis chain & Optimism for GIVbacks page.

**Comment by MohammadPCh** [comment]
@laurenluz @maryjaf please test it on https://giveconomy.vercel.app/givbacks
you can see your GIVbacks, harvest them, and see your harvest in GIVstream.

**Comment by maryjaf** [comment]
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/ee7340de-7f1a-4708-88f7-3bd16b5ce92a)
plz take a look @MohammadPCh

**Comment by MohammadPCh** [comment]
@maryjaf Thanks, yes we have a translation problem because we are waiting for approving translations. @laurenluz know about it.

**Comment by maryjaf** [comment]
when I harvest my Givback after showing success transaction modal, I can still see the amount of Givback as below pic and it isn't changed to zero 
for example I could do 3 times harvest
my wallet address: 0xA1179f64638adb613DDAAc32D918EB6BEB824104
my Your GIVbacks rewards: 38.98GIV

**Comment by maryjaf** [comment]
> 2-
> when I harvest my Givback after showing success transaction modal, I can still see the amount of Givback as below pic and it isn't changed to zero
> for example I could do 3 times harvest
> my wallet address: 0xA1179f64638adb613DDAAc32D918EB6BEB824104
> my Your GIVbacks rewards: 38.98GIV

This problem is related to subgraph issues and now has been resolved

**Comment by maryjaf** [comment]
4- The problem related to stake on OP Goerli still exists and we couldn't stake on OP @CarlosQ96

**Comment by maryjaf** [comment]
> 4- The problem related to stake on OP Goerli still exists and we couldn't stake on OP @CarlosQ96

I'v check wit moenick and this is out of the scope of this phase

**Comment by maryjaf** [comment]
> 3- we can't complete the stake/unstake scenarios and donation on OP Goerli
The problem related to stake on OP Goerli still exists and we couldn't stake on OP

**Comment by maryjaf** [comment]
> > 3- we can't complete the stake/unstake scenarios and donation on OP Goerli
> 
> The problem related to stake on OP Goerli still exists and we couldn't stake on OP

I'v check with @MoeNick  and this is out of the scope of this phase

**Comment by MoeNick** [comment]
As per GIVeconomy meeting, we decided not to have any active pool in givfarm, but users will be able to harvest in Givback page. 

Im not talking about release, but I think for better testing we should have all GIVeconomy scenarios to work fine, so it's in scope for stake, lock and unstake in OP, bt out for the Givback release.

**Comment by maryjaf** [comment]
> 4-OP Goerli shows unknown here @MohammadPCh
Thanks @MohammadPCh This problem has been resolved

**Comment by maryjaf** [comment]
> 3- we can't complete the stake/unstake scenarios and donation on OP Goerli

All cards in Givfarm are shown as inactive as expected
<img width="1437" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/768419b8-f438-463f-96b4-7ca904481eed">
