### ISSUE TITLE
Improving network selector

### ISSUE THREAD

**Issue by mosaeedi** [Giveth/giveth-dapps-v2#2751]
Right now, we use a segmented button to switch networks on GIVfarm, GIVstream and we are adding it to GIVbacks,
With two networks, the structure is okay, but adding more networks to the segmented button might not be a good idea because it can make the UX on those pages more complicated and make the UI busy.

![Segmented button](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/79a9b44f-01cc-447e-abe8-d685b3f91a3e)

So, here is the solution to improve the network selector.

![Network selector](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/ee85b218-70e2-403e-aba4-48a1b99a1819)

Instead of the segmented button, we can have all networks in a dropdown menu, so the user can easily switch to the desired network using the dropdown.

![The Networks Dropdown](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/68ca6348-d6d0-4dd7-8ece-9234a630b729)

### Design asset
A closer look at all the different states of the Network selector and the Dropdown.

[Figma Link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/GIVeconomy?type=design&node-id=22877-217082&t=DJmTFSmLNOONRQli-4)

![Screenshot 2023-06-11 at 5.05.35 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/22fd3302-f3a9-404b-ba16-1d8183ba40ba)

**Comment by MoeNick** [comment]
I moved it to done @maryjaf fyi
I guess you test it already, if not pls let me know
