### ISSUE TITLE
QF - post-round, show the actual matching funds sent to the project

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2757]
After a round ends, we will take the donation tx data, so some post-round sybil analysis... remove sybils... and then (manually?) recalculate the matching funds that should go to each project.

Then, we will send the actual matching funds to the projects from donation.eth via disperse.

For our MVP, these funds will be sent out on Optimism chain.

After this we will need:
- To show the amount of matching funds sent to each project in the frontend on the [donation tab](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=2689-95212&t=BWuiQb1LBHFFrvVA-4)
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/3df7e0b1-6b0f-4522-8ea6-74085a64b4e2)
- Nice to have: to trigger a notification when the matching funds are sent to alert project owners that they have gotten matching funds. (we could also just manually send out an email and cut this from scope)

Chatted w/ @CarlosQ96 about this. Looping in @mohammadranjbarz @MoeNick 

Related to #2694

**Comment by divine-comedian** [comment]
@CarlosQ96 will jump to it this week 

found a bug in exporting donations to google spreadsheet where we apply filters for QF, it is filtering in the view but its not sending the filtered list to the spreadsheet.

**Comment by laurenluz** [comment]
once we have the matching funds actual amounts, send spreadsheet to @CarlosQ96 who will manually input them in the database

**Comment by laurenluz** [comment]
@divine-comedian when you send the funds, can you post the tx links here?

@CarlosQ96 - then please input them in the database.

@maryjaf - once that's done, please test to make sure that on production, the projects that were part of the QF alpha round have the correct "Matching funds" amount shown on their project page. You can see what the "Matching funds" amount should be for each project from [this spreadsheet](https://docs.google.com/spreadsheets/d/1UDg3YT59xaLdh8RDlFC0ttvKRCTumMBbsHMvFR6Dl1M/edit#gid=1175767477).

For example, on the [commons stack project](https://giveth.io/project/commons-stack?tab=donations), the matching funds amount should be 702.24 (not 450 as it shows now).

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/d754df3a-342c-452f-a333-9f2d38970a26)

**Comment by divine-comedian** [comment]
pending tx to sign here:
https://app.safe.global/transactions/tx?safe=gno:0x6e8873085530406995170Da467010565968C7C62&id=multisig_0x6e8873085530406995170Da467010565968C7C62_0x0375258d6cf1500dd167dc387d2a11328092fd7422c8aaef5086160d2ec7690a

**Comment by CarlosQ96** [comment]
Query used to distribute funds:
```
UPDATE public.qf_round_history
SET 
  "matchingFund" = CASE 
    WHEN "projectId" = 2542 THEN 2000.00
    WHEN "projectId" = 1711 THEN 2000.00
    WHEN "projectId" = 3 THEN 702.24
    WHEN "projectId" = 2097 THEN 647.87
    WHEN "projectId" = 1923 THEN 638.20
    WHEN "projectId" = 1415 THEN 563.13
    WHEN "projectId" = 2242 THEN 469.75
    WHEN "projectId" = 1181 THEN 413.18
    WHEN "projectId" = 9 THEN 361.29
    WHEN "projectId" = 1951 THEN 236.91
    WHEN "projectId" = 2475 THEN 201.94
    WHEN "projectId" = 1352 THEN 186.66
    WHEN "projectId" = 2176 THEN 183.86
    WHEN "projectId" = 1874 THEN 174.14
    WHEN "projectId" = 1178 THEN 120.86
    WHEN "projectId" = 1384 THEN 112.26
    WHEN "projectId" = 2246 THEN 110.05
    WHEN "projectId" = 2054 THEN 78.29
    WHEN "projectId" = 2217 THEN 74.90
    WHEN "projectId" = 34 THEN 71.76
    WHEN "projectId" = 136 THEN 61.16
    WHEN "projectId" = 66 THEN 56.30
    WHEN "projectId" = 1884 THEN 56.02
    WHEN "projectId" = 2167 THEN 52.81
    WHEN "projectId" = 1439 THEN 48.22
    WHEN "projectId" = 69 THEN 37.87
    WHEN "projectId" = 125 THEN 35.93
    WHEN "projectId" = 1642 THEN 32.01
    WHEN "projectId" = 1350 THEN 30.05
    WHEN "projectId" = 1160 THEN 26.10
    WHEN "projectId" = 2609 THEN 25.88
    WHEN "projectId" = 1254 THEN 23.38
    WHEN "projectId" = 1172 THEN 20.74
    WHEN "projectId" = 164 THEN 19.79
    WHEN "projectId" = 2119 THEN 18.86
    WHEN "projectId" = 2351 THEN 18.65
    WHEN "projectId" = 1919 THEN 17.55
    WHEN "projectId" = 1842 THEN 14.26
    WHEN "projectId" = 1536 THEN 11.09
    WHEN "projectId" = 2 THEN 9.11
    WHEN "projectId" = 313 THEN 8.73
    WHEN "projectId" = 118 THEN 6.89
    WHEN "projectId" = 2020 THEN 6.71
    WHEN "projectId" = 119 THEN 6.37
    WHEN "projectId" = 297 THEN 4.82
    WHEN "projectId" = 70 THEN 2.58
    WHEN "projectId" = 122 THEN 0.82
    ELSE "matchingFund"
  END,
  "distributedFundNetwork" = 100
WHERE "projectId" IN (
  2542, 1711, 3, 2097, 1923, 1415, 2242, 1181, 9, 1951,
  2475, 1352, 2176, 1874, 1178, 1384, 2246, 2054, 2217, 34,
  136, 66, 1884, 2167, 1439, 69, 125, 1642, 1350, 1160, 2609,
  1254, 1172, 164, 2119, 2351, 1919, 1842, 1536, 2, 313, 118,
  2020, 119, 297, 70, 122
) AND "qfRoundId" = 2;
```

**Comment by aminlatifi** [comment]
@CarlosQ96 Values look good, thanks

**Comment by CarlosQ96** [comment]
Data inserted in project QFRound history!

**Comment by maryjaf** [comment]
The Matching Funds amount has been rounded on donation page for example :
120.86 in file is changed to 121 in donation tab
112.26-->121
Is That ok? @laurenluz

**Comment by divine-comedian** [comment]
> The Matching Funds amount has been rounded on donation page for example : 120.86 in file is changed to 121 in donation tab 112.26-->121 2.58-->3 Is That ok? @laurenluz

Lauren is out for the next 3 weeks - we should show two decimal places

**Comment by maryjaf** [comment]
> 120.86 in file is changed to 121 in donation tab
> 112.26-->121

> The Matching Funds amount has been rounded on donation page for example :
> 120.86 in file is changed to 121 in donation tab
> 112.26-->121
> 2.58-->3

should we change this rounding logic? @divine-comedian @MohammadPCh

**Comment by divine-comedian** [comment]
> > 120.86 in file is changed to 121 in donation tab
> > 112.26-->121
> 
> > The Matching Funds amount has been rounded on donation page for example :
> > 120.86 in file is changed to 121 in donation tab
> > 112.26-->121
> > 2.58-->3
> 
> should we change this rounding logic? @divine-comedian @MohammadPCh

I meant we should change the rounding logic so we show up to two decimal places

**Comment by MohammadPCh** [comment]
@alireza-sharifpour we should show exact funded numbers (not rounded numbers) for the matched funds. can you take it?

**Comment by maryjaf** [comment]
> I meant we should change the rounding logic so we show up to two decimal places

Should this change also be applied in public view for showing donation and matching funds?
I mean this:
<img width="1274" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/84b512dc-efce-4d2c-b2da-7c4b7215826f">
@divine-comedian

**Comment by divine-comedian** [comment]
I think this is OK... I don't have a better solution but I don't know if this scenario is a problem yet

**Comment by maryjaf** [comment]
For example it is possible when a round is active the number is shown for matching fund will be different because of different rounding logic in donation tab and project view

**Comment by divine-comedian** [comment]
> For example it is possible when a round is active the number is shown for matching fund will be different because of different rounding logic in donation tab and project view

Sorry I don't understand - can you explain this a bit more?

**Comment by maryjaf** [comment]
> I mean this:

imagine a QF round is active and projects have been receiving donation 
if calculated matching fund is 123.58, in donation tab of this QF round the matching fund is shown 123.58 and in project view is shown 123

**Comment by divine-comedian** [comment]
> Sure imagine a QF round is active and projects have been receiving donation if calculated matching fund is 123.58, in donation tab of this QF round the matching fund is shown 123.58 and in project view is shown 123
> 
> and my question is : Should this change about logic of rounding numbers also be applied in public view for showing donation and matching funds?
> 
> <img alt="image" width="1158" src="https://user-images.githubusercontent.com/111529185/263205613-d5635c1b-1b23-4dbc-a097-25987810bbf7.png">

Oh great question! I think for the estimated matching we can keep it simple and round to the nearest whole number (no decimals) - the estimated matching is not very accurate anyway, so the extra decimals of precision is meaningless.

**Comment by maryjaf** [comment]
> Oh great question! I think for the estimated matching we can keep it simple and round to the nearest whole number (no decimals) - the estimated matching is not very accurate anyway, so the extra decimals of precision is meaningless.

@alireza-sharifpour
