### ISSUE TITLE
Improve Recommended Projects (using AI!)

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2769]
@sembrestels has built a solution that uses embeddings to provide MUCH improved recommended projects on the dApp. It is really cool!

What we require is basically:
- to deprecate our existing recommended projects solution
- to create a new endpoint to get the data from the new recommended projects

Right now, the AI is recommending projects based on a projects list in a csv. We need a solution basically for updating the csv regularly as new projects get added. So...

Stretch goal:
- automatically update the csv at some regular intervals

@mateodaza is familiar with this as well so tagging him here.

@MoeNick, if it makes sense in our prioritization, it would be good to get some bandwidth from @CarlosQ96 to help review Sem's PR and get this into our flow (next week perhaps? I think it will be relatively low effort)

**Comment by CarlosQ96** [comment]
Now that you mention this I saw that @mhmdksh was talking about a db replica, maybe we can use that one for this feature? and connect the AI to that.

(I am quite nervous about connecting to main db)

**Comment by sembrestels** [comment]
Let's go step by step. First provide value to the user, which will be 20% of the work. Then when we refine it and we are sure of what we really want, we can connect it to the database direct or indirectly. I still do not get why we can't have different users with different roles (one with read-only capabilities) so the AI do not mess up the DB. But let's focus on that later. This issue should be about creating the new endpoint in the backend and connect the recommendation frontend.

**Comment by mhmdksh** [comment]
@sembrestels @CarlosQ96 Yes, as you mentioned earlier, we do have a read replica for the main DB (Please DM for connection information), We also have daily full backups of the entire DB, and we can do it on the fly.

So don't worry about messing it up :)

Let me know.
