### ISSUE TITLE
Bugs related to showing and calculating estimated matching 

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#2771]
**Describe the bug**
There are two QF round
1 -- >active
37--> inactive

In  donation tab of projects in QF round two rounds are shown correctly
but estimated matching for round 1 is also shown in round 37 as below pics
@MohammadPCh @mohammadranjbarz 
<img width="1424" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/c557d24c-ee7c-4530-a3bd-34031f751964">
<img width="1388" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/21dea697-8f49-4f3a-af0e-984c2257b6a0">

**Comment by MoeNick** [comment]
@MohammadPCh is on it.

**Comment by MohammadPCh** [comment]
@maryjaf I can't move it to unit testing. could you please check it again?

**Comment by maryjaf** [comment]
I checked and now the problem that estimated matching for active round is also shown in deactivated round  has been resolved
But we still have problems @MohammadPCh @mohammadranjbarz 
round 3 : deactivated
round 6 : active
1- the number of contributor is shown 0
2- The estimated matching for round 3 Is shown 0 although the user's score of  maryam jafarimehr is upper than 4 
4- I'm not sure why the amount of donation is shown 0.12 because I think in this section we should show the all donation of this project in this round Even if the user's score is less than 4 and the logic of passport score is considered only in estimated matching

<img width="1414" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/23446d79-008b-4f2c-8b97-869fc0be1eb2">

**Comment by mohammadranjbarz** [comment]
> I checked the problem that estimated matching for active round is also shown in deactivated round hasn't been resolved and we still have problems @MohammadPCh @mohammadranjbarz (this test has been done when the donation and estimated matching for round 6(active round) was still 0 ) round 3 : deactivated round 6 : active 1- the number of contributor is shown 0 for round 3 2- The estimated matching for round 3 Is shown 0 although the user's score of maryam jafarimehr is upper than 4 1&2 was happened because we show the number of contributor and estimated matching for deactivated round based on active round
> 
> 3- I'm not sure why the amount of donation is shown 0.12 because I think in this section we should show the all donation of this project in this round Even if the user's score is less than 4 and the logic of passport score is considered only in estimated matching
> 
> <img alt="image" width="1414" src="https://user-images.githubusercontent.com/111529185/250066143-23446d79-008b-4f2c-8b97-869fc0be1eb2.png">

@maryjaf  Can you test it again?
resolved in https://github.com/Giveth/giveth-dapps-v2/issues/2694#issuecomment-1616563290

**Comment by maryjaf** [comment]
> I checked the problem that estimated matching for active round is also shown in deactivated round hasn't been resolved and we still have problems @MohammadPCh @mohammadranjbarz (this test has been done when the donation and estimated matching for round 6(active round) was still 0 ) round 3 : deactivated round 6 : active 1- the number of contributor is shown 0 for round 3 2- The estimated matching for round 3 Is shown 0 although the user's score of maryam jafarimehr is upper than 4 1&2 was happened because we show the number of contributor and estimated matching for deactivated round based on active round
> 
> 3- I'm not sure why the amount of donation is shown 0.12 because I think in this section we should show the all donation of this project in this round Even if the user's score is less than 4 and the logic of passport score is considered only in estimated matching
> 
> <img alt="image" width="1414" src="https://user-images.githubusercontent.com/111529185/250066143-23446d79-008b-4f2c-8b97-869fc0be1eb2.png">

item 3 has been resolved and now the donation of all user is shown in the round .thanks @mohammadranjbarz 
but 1 & 2 wasn't changed, I'm not sure they are backend or front-end problems 
@mohammadranjbarz @MohammadPCh

**Comment by laurenluz** [comment]
FYI @MohammadPCh @mohammadranjbarz @maryjaf - we should ignore the user's passport score when calculating estimated matching. we should show estimated matching whether they have a passport w/ sufficient score or not.

**Comment by maryjaf** [comment]
> FYI @MohammadPCh @mohammadranjbarz @maryjaf - we should ignore the user's passport score when calculating estimated matching. we should show estimated matching whether they have a passport w/ sufficient score or not.

Both for the ended rounds (matching funds )and the open rounds (estimated matching)?

**Comment by MoeNick** [comment]
@maryjaf did you meet with @mohammadranjbarz ?
Is it clear for you?
