### ISSUE TITLE
The display of the number of contributors and the amount of the donation are buggy 

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#2772]
**Describe the bug**
1-
Display the number of contributors of a round in the project page, Project card and donation tab are different and each one seems to have separate logic

2-
In displaying the donation amount of a round, donations outside the round are also displayed

@MohammadPCh 
pics related to 1:
project card:
<img width="1425" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/d742f18b-211f-41e2-bcb9-96ece7a6d97a">
project single page:
<img width="1410" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/814e55bd-e82c-4b7f-9f71-87ba58849228">
donation tab:
<img width="1405" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/1fd644ea-292e-40af-aed6-5f0929fe7a4b">

pics related to 2:
<img width="1425" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/24aca216-6d61-4281-9ef8-2fe183d087c5">

**Comment by MohammadPCh** [comment]
@alireza-sharifpour @mohammadranjbarz could you please take a look? thanks :)

**Comment by MoeNick** [comment]
@mohammadranjbarz is reviewing it

**Comment by MohammadPCh** [comment]
@mohammadranjbarz @maryjaf As we talked about in Giveth/impact-graph#1034 I think we need a new web service for this info,

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz @maryjaf As we talked about in [Giveth/impact-graph#1034](https://github.com/Giveth/impact-graph/issues/1034) I think we need a new web service for this info,

The related backend issue
https://github.com/Giveth/impact-graph/issues/1034

**Comment by laurenluz** [comment]
was this issue resolved @MohammadPCh  @mohammadranjbarz ?

**Comment by mohammadranjbarz** [comment]
> was this issue resolved @MohammadPCh @mohammadranjbarz ?

@laurenluz  The backend has been implemented, @maryjaf  @MohammadPCh  is frontend implemented as well?

**Comment by MohammadPCh** [comment]
@laurenluz Yes, and tested by @maryjaf.
Do we have any problem there?

**Comment by maryjaf** [comment]
The all problems related to number of contributor have been done
