### ISSUE TITLE
Bug related to two rounds

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#2773]
**Describe the bug**
there are two rounds
round 1 -- ended 
round 37-- active

(one question, should the admin user change status of round into inactive after the time ended? 
if not  we have a bug because the status of this round is shown open after time ended in donation tab )
and in above situation
two rounds are shown open in donation tab as below pic
and the estimated matching for previous round is shown on project card &....
@mohammadranjbarz @MohammadPCh 

<img width="1436" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/fe356b82-6591-4837-86ec-4076a37577ab">
<img width="1437" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/203f7e11-c921-4bbf-8f58-ff44b87e4fbf">

**Comment by MohammadPCh** [comment]
@maryjaf Thanks for reporting this, but we decided to have only one active round and the admin should take care of it.

**Comment by maryjaf** [comment]
> @maryjaf Thanks for reporting this, but we decided to have only one active round and the admin should take care of it.

Yeah,
but in above scenario one round was ended and another was active
I checked with Mohammad and he is implementing a job that it deactivates the ended round

**Comment by mohammadranjbarz** [comment]
> > @maryjaf Thanks for reporting this, but we decided to have only one active round and the admin should take care of it.
> 
> Yeah, but in above scenario one round was ended and another was active I checked with Mohammad and he is implementing a job that it deactivates the ended round

Yeah, the PR is ready for review now
https://github.com/Giveth/impact-graph/pull/1024
