### ISSUE TITLE
Adding Goerli OP as a supported network to staging 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#2774]
it includes all subgraphs requests plus:

- change network modal 
- Create edit projects page
- My account manage recipient's address
- Verification flow: manage other addresses
- Tokens logo . token list in the donation page
- checking the balance in donation list to be correct

**Comment by MoeNick** [comment]
cc: @laurenluz

**Comment by laurenluz** [comment]
Thank you @MoeNick for creating this issue! do we need also to assigned someone for subgraph support?

**Comment by MoeNick** [comment]
As @maryjaf said and I see, we don't have OP Goerli on staging. 
Im surprised how it gets closed directly from sprint planning.

I asked @RamRamez to review this PP and merge it to staging so we can test it.

**Comment by MoeNick** [comment]
I meant this PR:
https://github.com/Giveth/giveth-dapps-v2/pull/2793

**Comment by MoeNick** [comment]
can be tested on giveconomy branch

**Comment by maryjaf** [comment]
1-
in verification form "optimism" is still shown , not optimism Goerli
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/6e53dbb2-4461-424c-ba9d-e1e045b951bf)

2-
I created a new project(testopgoerli) and set a OP Goerli wallet address for this project, when I try to add this address into other chain from manage wallet address in my account I get an error
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/2cc48bca-cbda-47f4-a32e-76045b26ff87)
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/58831c8b-6838-4ec7-b45e-49ccbc7a6859)

**Comment by MoeNick** [comment]
@RamRamez can you take a look?

**Comment by maryjaf** [comment]
3-
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/9130ddb0-895a-412e-a25f-3f1d1c53e08e)
The icon is not shown correctly in donation page

**Comment by maryjaf** [comment]
Plz check these 3 problems @RamRamez

**Comment by RamRamez** [comment]
> Plz check these 3 problems @RamRamez

@maryjaf I fixed 1 and 3 (it's waiting for review). I couldn't reproduce No 2. Can you test it again?

**Comment by maryjaf** [comment]
> I couldn't reproduce No 2. Can you test it again?

I'v been checking again but the previous error didn't happen, in face I saw this error only for this project
https://giveconomy.vercel.app/project/testopgoerli with this wallet address:
0xD00A9D501a6a37085Dc37664eba5a579EF7DF160

**Comment by RamRamez** [comment]
> > I couldn't reproduce No 2. Can you test it again?
> 
> I'v been checking again but the previous error didn't happen, in face I saw this error only for this project https://giveconomy.vercel.app/project/testopgoerli with this wallet address: 0xD00A9D501a6a37085Dc37664eba5a579EF7DF160

Maybe it was a temporary issue.
No 1 and 3 are fixed and you can test them on staging

**Comment by maryjaf** [comment]
Thanks @RamRamez these issues have been resolved
