### ISSUE TITLE
Estimated matching isn't calculated 

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#2776]
**Describe the bug**
Similar to the previous problem for two rounds (https://github.com/Giveth/giveth-dapps-v2/issues/2773) , this scenario also needs to be checked
@MohammadPCh @mohammadranjbarz 
round 1 -- Ended(inactive)
round 37-- Active

1- Donations related to previous round are shown in new round
2- after donation in new round the estimated matching is not calculated and remains 0 

<img width="1439" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/46590434-7f3c-4516-b61e-78a1c84fabdd">

**Comment by MohammadPCh** [comment]
@alireza-sharifpour can you take a look?

**Comment by laurenluz** [comment]
what happened with this issue? is it resolved? @alireza-sharifpour

**Comment by maryjaf** [comment]
Yes this Issue has been resolved and know the amount and number of contributor are shown correctly
