### ISSUE TITLE
Easier way to find Giver NFTs

### ISSUE THREAD

**Issue by SteffanThorn** [Giveth/giveth-dapps-v2#2780]
There doesn't seem to be a clear way to find Giver NFTs for people who've never bought before. 

I recommend we could include it in the top bar of the Giveth homepage.

There is a segment of new web3 users who come in through NFTs -- so having a clear way to get it could encourage new users. 

@laurenluz I'll ping you and see what you think about this issue.

**Comment by laurenluz** [comment]
@divine-comedian - as PM of the Givers, maybe you want to take this feedback?

**Comment by divine-comedian** [comment]
I think we wanted to do this originally @mosaeedi 

Is it possible?

**Comment by mosaeedi** [comment]
We need a better title for the dropdown! Then we can have the **Community** and **Giver NFT** as the menu items.

**Comment by divine-comedian** [comment]
Here's some ideas

> We need a better title for the dropdown! Then we can have the **Community** and **Giver NFT** as the menu items.

Why is adding the feature contingent on changing the text? 

I would argue that getting a Giver implies being part of the Community

**Comment by mosaeedi** [comment]
<img width="476" alt="Screenshot 2023-07-22 at 3 42 12 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/51ee6559-ac7c-4be7-80ea-68da93836cc5">

We might need a better here!
<img width="487" alt="Screenshot 2023-07-22 at 3 44 14 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/0a226207-d325-4afc-a4dd-2b921a87bcde">

**Comment by divine-comedian** [comment]
I think this flow makes sense - 

However do we want to have any link to About or Mission? 

The copy will need to be improved but that is easy.

**Comment by mosaeedi** [comment]
We can add a link to the Mission.

Can you please share a better copy?

**Comment by divine-comedian** [comment]
Sure @mosaeedi 

like this: 

## Community 
Get a 
**Givers NFT**

Learn how to 
**Join Us**

Discover our 
**Mission**

**Comment by divine-comedian** [comment]
@mosaeedi 

Can we make this happen? Seems like an easy fix to get the NFTs accessible from the homepage.

**Comment by divine-comedian** [comment]
@alireza-sharifpour Can you work on it this week? I think the design is clear enough.

**Comment by alireza-sharifpour** [comment]
I left a PR and it's fixed @divine-comedian

**Comment by divine-comedian** [comment]
> I left a PR and it's fixed @divine-comedian

Can you link the PR here?

**Comment by divine-comedian** [comment]
> I left a PR and it's fixed @divine-comedian

Oops! The text here should be reversed in its position.. The copy is also wrong and should match here:
## Community 
**Get a** 
Givers NFT

**Community Connection**
Join Us

**Why Giveth?**
Our Mission

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/2fddb10f-603f-475a-82d9-04f3649e96fd)

**Comment by alireza-sharifpour** [comment]
OK, I'll update them.

**Comment by divine-comedian** [comment]
Thanks, let us know when the PR is approved and move the issue here!

**Comment by MohammadPCh** [comment]
@maryjaf It's ready to test.

**Comment by divine-comedian** [comment]
> > I left a PR and it's fixed @divine-comedian
> 
> Oops! The text here should be reversed in its position.. The copy is also wrong and should match here:
> 
> ## Community
> **Get a** Givers NFT
> 
> **Community Connection** Join Us
> 
> **Why Giveth?** Our Mission
> 
> ![image](https://user-images.githubusercontent.com/67759413/259111604-2fddb10f-603f-475a-82d9-04f3649e96fd.png)

@MohammadPCh - the text should match this one.

**Comment by MoeNick** [comment]
@alireza-sharifpour pls let us know when it's ok.

**Comment by alireza-sharifpour** [comment]
It will be fixed on this PR
https://github.com/Giveth/giveth-dapps-v2/pull/3023
@MoeNick @divine-comedian
