### ISSUE TITLE
"Failed to Fetch" trying to open a project

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#279]
I clicked on bridging digital communities from the homepage and got this:

![image](https://user-images.githubusercontent.com/75490971/158707354-5d1bb38d-e701-4541-9e57-b38047c6184b.png)

**Comment by laurenluz** [comment]
oh yeah, and it said "failed to fetch"

**Comment by RamRamez** [comment]
@laurenluz I checked and it was ok for me. Can you check again?

**Comment by laurenluz** [comment]
it's working for me now, not sure if the issue is fixed of if it's something lurking. will more to "done" for now, and if the issue is repeated, we can revisit.
