### ISSUE TITLE
Content length exceeded error when characters are below limit

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#2795]
As per the user report:

Hi frens! Trying to post a project update but keep getting a content length exceeded error even tho I'm only at 1733/2000

and @MohammadPCh review it and he responded:
This is a back-end Issue, in front-end the calculated lenght is: 1752,
but when I sent it to the back-end it says: Content length exceeded.

**Comment by Vyvy-vi** [comment]
What was the content that was being sent?
Did it have any formatting?
