### ISSUE TITLE
Share & get rewarded on Donation page

### ISSUE THREAD

**Issue by mosaeedi** [Giveth/giveth-dapps-v2#2798]
Replacing the **social share button** with the **Share & get rewarded button**.

[Link to Figma](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=2731-95560&mode=design&t=ybgRg5sqUouTZ1r8-4)

**Comment by maryjaf** [comment]
For verified project:

<img width="687" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/2cea9647-19bf-41fb-ac1b-04e2733e2239">

for Unverified project:
<img width="840" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/b69013ce-8d7c-455a-956b-2186c51bf927">

there is different between this and Figma 
<img width="1200" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/bc072111-011e-42ae-82c5-7d5e1b367db2">
@mateodaza @MoeNick

**Comment by MoeNick** [comment]
Yeah, it seems to be ok. let's go live!
