### ISSUE TITLE
Losing everything when creating a project is really discouraging.... scary story of a horrific UX failure

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#2805]
**Describe the bug**

I was creating a project on giveth, I perfected my description and spent hours adding pictures and all that, then I was done and I went to add the address as the LAST STEP, so i go to my metamask and switch address to the address that will collect the donation and I lose everything.

Then i decide, fuck this, i can't believe i have to make that whole project again from scratch so i just make a crappy version and call it good and hate this platform forever.

**Expected behavior**
I expect to be able to interact with metamask and then continue to edit and submit my project.

**Additional context**
we should do everything in our power to prevent the project creation page from refreshing... and we should make sure that it is easy to recover the content in teh project creation text field... the rest of the fields are sooo much less important, but that field, people will take hours to edit and the frustration of losing it all turns an excited first time user into an enemy of Giveth, crypto and all that is good in the world, they become full of hate and rage, and probably go and kill puppies...

**Comment by MoeNick** [comment]
@MohammadPCh do you know what made the page refresh? Is it counting characters?

**Comment by MohammadPCh** [comment]
Our platform exclusively displays the create page to users who are signed in. So, when you change your wallet, we automatically remove all elements from the page and prompt you to sign in again. Even if you already have a token, the following steps are executed:

1. All elements are removed from the page.
2. A sign-in message is displayed.
3. If the user had previously signed in, the create page is presented once again.

my solution:
Maybe it's better to show the create project page for all users (even if the user's wallet is not connected). then on submit or on adding wallet ask him to connect or sign.

**Comment by MoeNick** [comment]
> Our platform exclusively displays the create page to users who are signed in. So, when you change your wallet, we automatically remove all elements from the page and prompt you to sign in again. Even if you already have a token, the following steps are executed:
> 
> 1. All elements are removed from the page.
> 2. A sign-in message is displayed.
> 3. If the user had previously signed in, the create page is presented once again.
> 
> my solution: Maybe it's better to show the create project page for all users (even if the user's wallet is not connected). then on submit or on adding wallet ask him to connect or sign.
Thanks @MohammadPCh 
I guess we need the connect/sign for some validations, like address-recipient redundancy. Maybe we can review all field validation first to check whether your solution is doable or not.

**Comment by Vyvy-vi** [comment]
The reload on wallet change is only part of the issue. The project data is also lost when the user reloads

**Comment by maryjaf** [comment]
Thanks @RamRamez 
Now  by changing account  in "creation project" flow when the new account has a profile, data is not missed and we can completing the flow for creation project by new account

And when the new user hasn't profile,  by changing account we were forwarded to completing profile flow and after that by taping on "Create a Project" we can see the data that they have been  set recently

Are these expected result ? If yeah ea can move to Done
@MoeNick @divine-comedian 
@RamRamez 
As a suggestion we shouldn't have an option for "cancel" in this page? because now by selecting back and tap again on create project the previous filled fields are shown for current account and if we change the account

**Comment by divine-comedian** [comment]
I think we can create a separate issue for a sort of "Reset" button that resets the fields. But I think for the scope of this issue we can call it done.
