### ISSUE TITLE
QF Project Single page donation tab - Donations shown in "All donation" but not when a specific QF round filter is applied

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2812]
When I donate with Goerli my donation is shown in all donation but it isn't shown in donation of specific round 
Is it  related to test network or we have a bug? @mohammadranjbarz 
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/7c15cf60-036e-4642-857e-9ccf8cc7be68)
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/b6a45628-0667-483f-ba0a-820ed383235a)

_Originally posted by @maryjaf in https://github.com/Giveth/giveth-dapps-v2/issues/2694#issuecomment-1614533100_

**Comment by laurenluz** [comment]
@maryjaf - can you let us know which project you were testing with in this picture? @CarlosQ96 needs it to reference.

**Comment by maryjaf** [comment]
https://givqf.vercel.app/project/testmatic2020?tab=donations @CarlosQ96
