### ISSUE TITLE
Fixing  "Create a project"  button on header in the single project page.

### ISSUE THREAD

**Issue by mosaeedi** [Giveth/giveth-dapps-v2#2821]
On the **single project page**, the Donate button is in Primary style, and we want users to see the Donate button first, so only on the single project page, the **"Create a Project"** button style should change to **Texty style**.

![Screenshot 2023-07-07 at 5.07.12 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/a5647932-afc5-4a60-ab20-4f5e45f391b6)

![Screenshot 2023-07-07 at 5.08.14 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/88952fa0-7821-4004-8948-8d4ae64f63e2)

**Comment by divine-comedian** [comment]
@MohammadPCh can we make this quick fix?

**Comment by divine-comedian** [comment]
@alireza-sharifpour or @RamRamez can we take this on?

**Comment by RamRamez** [comment]
> @alireza-sharifpour or @RamRamez can we take this on?

Done! It's waiting for review.

**Comment by maryjaf** [comment]
the "Create a Project" button' style is changed to Texty style in **project view** and **owner view**
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/4f94fb21-4a18-4d28-b313-529a221210fa)
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/a69c3a25-4494-40c9-bf92-ad2a3d1264df)

 Should this new style be displayed in Owner View? @mosaeedi
