### ISSUE TITLE
Public view : project page

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#2824]
**For project that it wasn't linked to a round the below pic is shown:**
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/07e3065e-919a-468e-9c24-6439670b8b34)
1- Is the displayed text correct and final? Where can I see the final figma?
2- by tapping on [Learn about our zero-fee policy](https://staging.giveth.io/) I'm redirected to https://staging.giveth.io/

 **project that it was linked to a round** 
 by tapping on [How it works?](https://docs.giveth.io/quadraticfunding) I'm redirected to https://docs.giveth.io/quadraticfunding
 and I got 404
 @MoeNick @MohammadPCh

**Comment by laurenluz** [comment]
1- copy should change to "100% goes to the project. Always." (then it's fine)
2- Learn about our zero-fee policy should link to our documentation. @franculio - when you upload https://github.com/Giveth/giveth-planning/issues/1394, can you please send us the link to that doc in this issue?

for "how it works"... we will be uploading the documentation for QF at that link.. it's just not up yet. https://github.com/Giveth/giveth-planning/issues/1395

**Comment by MohammadPCh** [comment]
@Vyvy-vi can you take a look?

**Comment by franculio** [comment]
Here's the link to the Zero-fee policy doc:

https://docs.giveth.io/whatisgiveth/zero-fees

@laurenluz

**Comment by Vyvy-vi** [comment]
<img width="1286" alt="Screenshot 2023-07-14 at 4 00 33 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/62864373/dbbaad9c-8603-49fc-b652-35f3a0dd9124">
Does this look alright, or should the "Always" be on the same line as the other text?

**Comment by laurenluz** [comment]
I think that's ok on two lines. @Vyvy-vi

**Comment by Vyvy-vi** [comment]
I opened a PR with the needed changes
