### ISSUE TITLE
Project card with PFP

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#2830]
**Describe the bug**
Showing of project card for project with pfp profile has a problem as below pic
<img width="1440" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/85203da6-363d-4e18-811d-2359509d4c72">

@alireza-sharifpour Plz check

**Comment by maryjaf** [comment]
Thanks @alireza-sharifpour This issue has been resolved

**Comment by MoeNick** [comment]
I moved it to done @maryjaf 
pls always do it after you confirmed
