### ISSUE TITLE
Bug in taping on like & "share and get rewarded"

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#2837]
**Describe the bug**
Change the wallet and set a new wallet address on Metamask
on project page view tap on like
the sign modal is shown after signing this error is shown : "Something went wrong."
and by tapping on share and rewarded the loading icon is shown
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/32b87c72-2677-4ae9-b2b8-b9f1cb863e40)
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/e0b02c13-2876-4f35-9d8e-9408af980bdf)
@mo

**Comment by MohammadPCh** [comment]
@mateodaza @RamRamez do you have time to take a look?
