### ISSUE TITLE
Donation Page: weird project card view

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#284]
While Im trying to donate to this project:
https://giveth.io/donate/333

I gt this: 
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/ed4dfade-9fb9-47b2-ab3d-3069f2be7022)

**Comment by divine-comedian** [comment]
formatting looks to be resolved! 

![image](https://user-images.githubusercontent.com/67759413/161101413-588ec726-aca0-4487-b130-dc877da73765.png)
