### ISSUE TITLE
QF - Project card: Let's get rid of the colons!

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2840]
See the ":"? on "Amount raised" "Estimated Matching" & "Number of contributors"? we should delete them all!

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/184936a4-fc4c-4fdf-a443-47f0b08fd0b4)

@MohammadPCh

**Comment by laurenluz** [comment]
this one is really small @Vyvy-vi - maybe you can take it?

**Comment by franculio** [comment]
I don't know if this was fixed or not but I can see that just one of the colons has been removed, the one in "Estimated matching". 

I can still see the one on "Raised from X contributors" 


<img width="478" alt="Captura de Pantalla 2023-07-14 a las 17 29 56" src="https://github.com/Giveth/giveth-dapps-v2/assets/79286405/38f65296-9b36-4ae6-a556-66ee85e2f025">

**Comment by laurenluz** [comment]
it looks fixed now

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/a96bf8bd-2cb1-4203-81a2-f53e6d80109f)
