### ISSUE TITLE
I just donated 100 xDAI and my donation didn't show up!

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2842]
I donated 100 xDAI to gravity here --> https://gnosisscan.io/tx/0x8157bb15775e346a881bb7c1ca07a8fdcd791fb3dcc9509f7ad670716290bced

And I didn't get a confirmation email, and it's not showing up on the donation list. What happened?

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/c5a7984c-59a2-4779-93fb-d2871e6103be)

@MoeNick @RamRamez @MohammadPCh

**Comment by laurenluz** [comment]
hmm... ok I tried donating again smaller amounts, and they worked fine.. maybe we can just close this... but something weird definitely happened. 

my donation didn't show up on the donation list for several minutes. Is that normal?

**Comment by MoeNick** [comment]
Yes its normal, it needs verification process from network, it change from pending to verified. Sometimes the process needs a minute, but @mohammadranjbarz know it better what is the max duration needed to change the status from pending to verified

**Comment by RamRamez** [comment]
@laurenluz Did you wait for the tx to be mined before closing the tab (or going to another page)? Did you see the success view?

**Comment by laurenluz** [comment]
yeah I might have clicked away before the success page @RamRamez - maybe we can just close this

**Comment by RamRamez** [comment]
@laurenluz because if you wait for the success page and don't close the tab, the front-end notifies the backend that the tx has been mined and backend approves it instantly, but if you move away, backend doesn't know if tx has been mined, so it checks periodically.

**Comment by laurenluz** [comment]
that makes a lot of sense :) thanks @RamRamez
