### ISSUE TITLE
QF - 500 server error when trying to boost projects

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#2848]
QF Testing - https://staging.giveth.io/givpower
When i click the button to boost projects from the GIVpower page, I get a 500 server error.

![image](https://github.com/Giveth/giveth-dapps-v2/assets/74267818/11f3f39d-aab9-4646-82ff-62f08ebbbb6a)
![image](https://github.com/Giveth/giveth-dapps-v2/assets/74267818/461e2453-61e7-4388-9add-212ea8b45c02)

Using Chrome browser on Windows 10

**Comment by laurenluz** [comment]
should be resolved
