### ISSUE TITLE
QF - Default % donation to Giveth is overlapping

### ISSUE THREAD

**Issue by freshelle** [Giveth/giveth-dapps-v2#2851]
From [this](https://staging.giveth.io/donate/teach-music-to-children) donation page, the default 5% field is overlapping.

<img width="1027" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/86718721/b95c0b83-1e41-4774-9a6e-46716d838cfe">

**Comment by laurenluz** [comment]
I'm not able to reproduce this

**Comment by MohammadPCh** [comment]
same here :(

**Comment by MoeNick** [comment]
@maryjaf pls test again

**Comment by maryjaf** [comment]
I checked and it's ok for me too

> @maryjaf pls test again
