### ISSUE TITLE
Quadratic funding testing

### ISSUE THREAD

**Issue by Santigs** [Giveth/giveth-dapps-v2#2852]
Was able to donate to an initial project
![image](https://github.com/Giveth/giveth-dapps-v2/assets/34634436/fd71ac97-f37b-4dc0-9c11-f9c1ddf66c5d)
I used goerli and everything seemed to work fine, but I was unable to donate anymore as I was getting a 500 error when trying to search for additional projects testing any link in the projects section
![image](https://github.com/Giveth/giveth-dapps-v2/assets/34634436/1791b800-70f2-4d01-8ae1-10fb8573db7b)

**Comment by laurenluz** [comment]
Thanks Santi!

The reason you can't donate to some projects on Goerli is because the project owner didn't add a Goerli address. I just added one to that "how many photos" project. you should be able to donate to it now on goerli.

the other error should be resolved now!
