### ISSUE TITLE
QF - Cannot click the QF Round filter on projects page

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#2853]
Testing QF - I am on this page and trying to filter for QF Round projects - The option to filter is unavailable to check the box
Chrome browser
Windows 10
https://staging.giveth.io/projects/art-and-culture

![image](https://github.com/Giveth/giveth-dapps-v2/assets/74267818/1dcf95fe-9e6c-4796-8544-65ce5001df07)

**Comment by laurenluz** [comment]
@MohammadPCh - can you look into it?

I'm getting the same issue. looks like you can't add the QF filter when you are on a specific Category's page.

**Comment by MohammadPCh** [comment]
@laurenluz as I remember, we decide to have separate logic for the normal projects page and qf projects page. based on that discussion, I have to remove the qf filter from the projects page filter menu.
I will do it.
wdyt?

**Comment by MoeNick** [comment]
If you did pls connect the PR so 
@maryjaf FYI and to be in the loop of logic!

**Comment by maryjaf** [comment]
Plz let me know when it's ready to test @MohammadPCh

**Comment by MohammadPCh** [comment]
@maryjaf, It's ready to test.

**Comment by maryjaf** [comment]
> @maryjaf, It's ready to test.

Thanks @MohammadPCh I check and now the filter related to QF isn't shown as expected

**Comment by laurenluz** [comment]
oh I SEE what happened.

1. We should have the option for the user to select the QF filter when they are on the normal projects page at https://giveth.io/projects
2. The filter should be always on (and hidden from the filter menu) on the page https://giveth.io/qf

is that possible to do?
