### ISSUE TITLE
Add label or clear marker for QF projects to make them look different

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2854]
Many people in the testing parties said they couldn't tell the different between QF projects and not QF projects.

@mosaeedi @markoprljic - can we add something? like a label or badge? it's ok if it's redunant... I think we need to be clear.

we should perhaps put the same kind of badge on the project single page. because it will be disappointing for people to donate to not-QF projects without realizing it.. we need to make it clear

**Comment by mosaeedi** [comment]
We can use tags,

QF Tag
Content: QF Alpha Round
Font color: Neutral/Gray/100
Background: Secondary/Cyan/600

### QF tag on single project page
<img width="1028" alt="Screenshot 2023-07-11 at 6 17 31 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/65b071d8-bbd7-4ac0-8751-8e58906d7f92">


### QF tag on Project card
<img width="635" alt="Screenshot 2023-07-11 at 6 22 45 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/82744964-243c-425d-9386-d5895f381944">

**Comment by laurenluz** [comment]
@mosaeedi a few requests:
- can we remove the "GIVbacks" label? it's redundant w/ verified
- can we make "QF Alpha Round" bigger/more bold
- can we change copy "Quadratic Funding" to "Eligible for Matching"

**Comment by mosaeedi** [comment]
<img width="714" alt="Screenshot 2023-07-12 at 12 09 49 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/308499d9-4dba-495d-8c26-32c9ad3b1c3c">


<img width="490" alt="Screenshot 2023-07-12 at 12 10 20 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/f6b110d7-6ede-41f1-aa62-4a57e27da261">


<img width="962" alt="Screenshot 2023-07-12 at 12 12 30 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/8e362d8c-e5cd-4273-905f-bdb163a32892">

**Comment by MohammadPCh** [comment]
@laurenluz Can we start implementation? :eyes:

**Comment by laurenluz** [comment]
yep, let's go! @MohammadPCh

**Comment by laurenluz** [comment]
FYI @MohammadPCh - the label on the project card should be = the name set by the admin for the round in admin bro

**Comment by maryjaf** [comment]
1 or 2 is final ? now the pic 2 is shown on stg
1-
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/2152e4e8-bead-47ab-99d1-e35bf802baff)
2-![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/214266df-3d16-45d2-878f-44de9940a719)
@mosaeedi @alireza-sharifpour

**Comment by mosaeedi** [comment]
2 is the final one.

**Comment by maryjaf** [comment]
> 2 is the final one.

@alireza-sharifpour

**Comment by divine-comedian** [comment]
I just wanted to leave a comment on this - is it normal that you have three badges for QF and each one uses the same color but has different text? 

Shouldn't the badges be consistent? 

## Single project page 
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/5cf409b5-82a6-47db-90e5-6925e90a79c3)

## Project card on projects list page 
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/2cc74f3a-11c6-468e-98d2-d5ca36656ef1)

## drop down menu on navbar
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/dc99fc70-3b00-4d9c-8e92-e3a70d9ceacf)

**Comment by maryjaf** [comment]
> I just wanted to leave a comment on this - is it normal that you have three badges for QF and each one uses the same color but has different text?
> 
> Shouldn't the badges be consistent?
> 
> ## Single project page
> ![image](https://user-images.githubusercontent.com/67759413/253602819-5cf409b5-82a6-47db-90e5-6925e90a79c3.png)
> 
> ## Project card on projects list page
> ![image](https://user-images.githubusercontent.com/67759413/253603068-2cc74f3a-11c6-468e-98d2-d5ca36656ef1.png)
> 
> ## drop down menu on navbar
> ![image](https://user-images.githubusercontent.com/67759413/253603153-dc99fc70-3b00-4d9c-8e92-e3a70d9ceacf.png)

Based on @mosaeedi's comment the "quadratic funding" shroud  be changed to "Eligible for Matching"

**Comment by laurenluz** [comment]
We should basically have two possible texts:

1. "Eligible for Matching" in the drop-down menu links to giveth.io/qf
2. "Eligible for Matching" should be on the project single page if the condition is met that the project is part of the QF round
3. On the project card.... if the project is part of the QF round, we should have the label show the name of the round... i.e. "QF test" or "QF alpha round"

@divine-comedian - if you think it would be better to change it , open to suggestions (trying to juggle a lot of opinions here on what this should say)

**Comment by maryjaf** [comment]
Thanks @alireza-sharifpour 
<img width="1116" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/e6e00cbb-b24d-4bd5-b047-d76dab1b00c2">
