### ISSUE TITLE
Copy fix on link to block explorer

### ISSUE THREAD

**Issue by Zeptimus** [Giveth/giveth-dapps-v2#2855]
[ ] When a donation is processed, it directs to look it up on Etherscan instead of Blockscout, though the link provided is correct. The issue lies with the visual representation.

**Comment by laurenluz** [comment]
Hey @Zeptimus - can you send a screeenshot of where you are seeing this?

when I make a dontaion, I see the copy "view on a block explorer"

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/b9a1103f-032a-4e07-8146-7ca233e153ee)

**Comment by divine-comedian** [comment]
@RamRamez can you check this out? 

Maybe ctrl + f 'Etherscan' 

We should say 'blockchain explorer' instead so that is more general and the text doesn't depend on what website we use

**Comment by divine-comedian** [comment]
Okay! Interesting - let's close this then since it really isn't an important issue I think.
