### ISSUE TITLE
QF - Update "Other" project type description

### ISSUE THREAD

**Issue by freshelle** [Giveth/giveth-dapps-v2#2857]
compared this with [actual project categories](https://giveth.io/projects) but there's no "Other" category yet.

So maybe the description here is not yet final? Best to update it
<img width="1385" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/86718721/254d3e93-47e9-4219-b943-17bb46e044a8">

**Comment by laurenluz** [comment]
@RamRamez or @alireza-sharifpour - can you take it?

We can just have the subtext blank.

**Comment by RamRamez** [comment]
> @RamRamez or @alireza-sharifpour - can you take it?
> 
> We can just have the subtext blank.

No problem, I fixed it. It's waiting for review.
