### ISSUE TITLE
staging > was I shadow banned from GIVbacks?

### ISSUE THREAD

**Issue by parrachia** [Giveth/giveth-dapps-v2#2861]
gm 
On staging, after creating a project draft but not publishing/completing it, I got this warning while donating saying I'm not eligible for GIVbacks because I already have a project. 
Testing on production works fine.
I'm using brave and firefox on ubuntu
![image](https://github.com/Giveth/giveth-dapps-v2/assets/9451597/265337fb-c020-448e-a39b-8d99f86aec65)

cc @laurenluz

**Comment by divine-comedian** [comment]
Seems like we need to add some condition to not add the user wallet to the purple list while the project is in draft state 

@CarlosQ96 @mohammadranjbarz 

Does this issue make sense? How much effort would be required?

**Comment by MoeNick** [comment]
@maryjaf it worth you tale a look at it again.

**Comment by maryjaf** [comment]
There is a bug on stg
In donation page with my account that it is used on my active verified project I saw that my account is eligible for givback as below pic:
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/18ac2269-767c-4166-b07b-9fc650253414)
0xeCCe9a0bd601861Bb81578a3538DB3c35286e86F

@mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
> There is a bug on stg In donation page with my account that it is used on my active verified project I saw that my account is eligible for givback as below pic: ![image](https://user-images.githubusercontent.com/111529185/261328854-18ac2269-767c-4166-b07b-9fc650253414.png) 0xeCCe9a0bd601861Bb81578a3538DB3c35286e86F
> 
> @mohammadranjbarz

@maryjaf 

Can you test it now?
( we were checking the addresses case sensitive, but now is case insensitive so it works now)

**Comment by maryjaf** [comment]
> > There is a bug on stg In donation page with my account that it is used on my active verified project I saw that my account is eligible for givback as below pic: ![image](https://user-images.githubusercontent.com/111529185/261328854-18ac2269-767c-4166-b07b-9fc650253414.png) 0xeCCe9a0bd601861Bb81578a3538DB3c35286e86F
> > @mohammadranjbarz
> 
> @maryjaf
> 
> Can you test it now? ( we were checking the addresses case sensitive, but now is case insensitive so it works now)

Thanks @mohammadranjbarz this problem has been resolved and now the correct message is shown in donation page when I try to donate with address that it was used in a active verified project
<img width="1222" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/35e2ec61-0013-42c7-b9c2-d4a27210b190">

and if i donate with address that it was used in Draft project this message is shown
<img width="381" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/363b7b70-007f-4c12-afe2-27e2d3a0998e">
