### ISSUE TITLE
"Save on gas fees - switch network" on Donate page

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2863]
Right now we prompt people to swtich from mainnet to gnosis. I think, with all our new chains, we should make this more equal opportunity...

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/883dd609-1314-47b5-804f-920340b86afe)

we should change copy from "Save on gas fees - to gnosis chain" to "Save on gas fees - switch network"

And when user clicks switch network, they get this modal:

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/9357db23-2d78-461f-b30e-fbf950e41bd3)

**Comment by laurenluz** [comment]
@MoeNick - not sure who to give it to

**Comment by MohammadPCh** [comment]
@laurenluz Done, JFYI, we have a better switch network in the GIVeconomy branch that we can pass the networks to it. in the current modal, we show all networks, and maybe the project didn't accept fund on it. but after merging GIVeconomy brach we can only show the networks that the project accepts funds on it.

**Comment by MohammadPCh** [comment]
@laurenluz I did cherry-pick that feature, and now we have it here :)

**Comment by laurenluz** [comment]
wooohoo!
