### ISSUE TITLE
Project single page - GIVpower tab - delete redundant statment on GIVpower rank card

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2864]
We should remove the part about "this rank will update at the start of the next GIVbacks round"... because we are showing the date and it is redundant.

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/2acefcd1-7de5-469d-9203-1886e9ce6598)

@MohammadPCh

**Comment by maryjaf** [comment]
The redundant statement is removed 
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/286ef12f-c3d9-4617-afcc-17b504f2e278)
but we have a problem on stag that for all project the rank is set "__" and  I think we should check this in a new issue
