### ISSUE TITLE
Bug on sorting by GIVpower

### ISSUE THREAD

**Issue by Cotabe** [Giveth/giveth-dapps-v2#2866]
GM!

For some reason, this project (https://staging.giveth.io/project/Music-I'm-Listening-to-Now) appears lower in the QF page even though I'm sorting by GIVpower & it has more GIVpower than several of the ones above.

![QF sorting by GIVpower1](https://github.com/Giveth/giveth-dapps-v2/assets/101358184/9715f544-3532-4048-9a82-e7c24320d014)

![QF sorting by GIVpower2](https://github.com/Giveth/giveth-dapps-v2/assets/101358184/d074d623-af1d-4acd-95d8-7ea9edfe615d)

FYI: @laurenluz

**Comment by laurenluz** [comment]
@MohammadPCh @MoeNick - can you investigate?

**Comment by maryjaf** [comment]
The rank filter displays the projects in order of Gipower rank
The Give Power filter filters the projects in the order of the current GivPower amount
We had a recent change in the logic of these two filters
And the system behavior is as expected

**Comment by laurenluz** [comment]
@maryjaf - I checked it myself, there is an issue. I know we changed the logic.
Default is set to sort by GIVpower
Project "music I'm listening to..." has 93,000 GIVpower

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/68557d9c-6535-486a-9ece-9462b4587147)
Project "foundations of living..." has 63,000 GIVpower

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/cfe3053f-c390-4615-ae50-0229abe56f0a)

But "music I'm listening to is 3 positions LOWER than foundations in the default sorting...

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/3d17a807-f8ac-4f42-a2b8-4afb9fff604d)

there is a bug.

**Comment by laurenluz** [comment]
and I double checked - its set to sort by GIVpower 
![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/733e3796-2318-4ccc-b947-cf738995cc21)

**Comment by maryjaf** [comment]
> @maryjaf - I checked it myself, there is an issue. I know we changed the logic. Default is set to sort by GIVpower Project "music I'm listening to..." has 95,000 GIVpower
> 
> ![image](https://user-images.githubusercontent.com/75490971/252958561-68557d9c-6535-486a-9ece-9462b4587147.png) Project "foundations of living..." has 63,000 GIVpower
> 
> ![image](https://user-images.githubusercontent.com/75490971/252958640-cfe3053f-c390-4615-ae50-0229abe56f0a.png)
> 
> But "music I'm listening to is 3 positions LOWER than foundations in the default sorting...
> 
> ![image](https://user-images.githubusercontent.com/75490971/252958117-3d17a807-f8ac-4f42-a2b8-4afb9fff604d.png)
> 
> there is a bug.

ُThanks @laurenluz we'll check it

**Comment by maryjaf** [comment]
@mohammadranjbarz @aminlatifi plz take a look

**Comment by laurenluz** [comment]
@CarlosQ96

**Comment by mohammadranjbarz** [comment]
I investigated client requests in chrome network and this is the result

1. When You select sort by **GIVpower** frontend send sorting by **InstantBoosting** to server so the response is actually sorted by instant boosting ( I'm not aware about Instant boosting logic much as I didn't implement it)

2. When you select sort by **Rank** frontend  sends dorting by **GIVPower** to server and if you test it you can see the response is ok and all projects are sorted by give power correctly

So as I understood there is nothing wrong from backend, it depends on what frontend send to backend ot what text shows to user in sorting by drop dow

@maryjaf  @laurenluz  @MohammadPCh

**Comment by mohammadranjbarz** [comment]
> could there be an issue in the logic of instant boosting? @mohammadranjbarz @aminlatifi ?

I mean default sorting should be givPower or instant boosting? maybe frontend sends sorting by filed wrong

**Comment by laurenluz** [comment]
default sorting should be by instant boosting... and the label on the frontend is "GIVpower"

the way it's being sorted though by default isn't EITHER by GIVpower or by rank... it's something else... something wrong 👀

**Comment by mohammadranjbarz** [comment]
> default sorting should be by instant boosting... and the label on the frontend is "GIVpower"
> 
> the way it's being sorted though by default isn't EITHER by GIVpower or by rank... it's something else... something wrong 👀

So @aminlatifi  might can help on that

**Comment by aminlatifi** [comment]
@laurenluz @Cotabe 
It's working fine. There is some misunderstanding/unclarity here. When projects are sorted by GIVpower on front, the result is sorted by instant boosting, and when they are sorted by rank, the result is sorted by GIVpower! It's how the frontend is implemented....
For instance, it's the query result when the in query we ask sort by InstantBoosting (Sort by GIVpower on the frontend):
```json
{
    "data": {
        "allProjects": {
            "projects": [
                {
                    "title": "The Giveth Community of Makers",
                    "projectInstantPower": {
                        "totalPower": 12749984.78,
                        "powerRank": "1"
                    },
                    "projectPower": {
                        "powerRank": 1
                    }
                },
                {
                    "title": "GRACEaid Earthquake relief",
                    "projectInstantPower": {
                        "totalPower": 8175715.98,
                        "powerRank": "2"
                    },
                    "projectPower": {
                        "powerRank": 2
                    }
                },
                {
                    "title": "Giveth House",
                    "projectInstantPower": {
                        "totalPower": 7011329.71,
                        "powerRank": "3"
                    },
                    "projectPower": {
                        "powerRank": 3
                    }
                },
                {
                    "title": "BanklessDAO Turkey Disaster Relief Fund",
                    "projectInstantPower": {
                        "totalPower": 6682068.98,
                        "powerRank": "4"
                    },
                    "projectPower": {
                        "powerRank": 4
                    }
                },
                {
                    "title": "Giveth Matching Pool",
                    "projectInstantPower": {
                        "totalPower": 5983107.97,
                        "powerRank": "5"
                    },
                    "projectPower": {
                        "powerRank": 7
                    }
                },
                {
                    "title": "ShapeShift DAO",
                    "projectInstantPower": {
                        "totalPower": 5866391.77,
                        "powerRank": "6"
                    },
                    "projectPower": {
                        "powerRank": 132
                    }
                },
                {
                    "title": "Commons Stack",
                    "projectInstantPower": {
                        "totalPower": 5798904.52,
                        "powerRank": "7"
                    },
                    "projectPower": {
                        "powerRank": 6
                    }
                },
                {
                    "title": "Building the Future of Giving One Mural at a Time",
                    "projectInstantPower": {
                        "totalPower": 5017670,
                        "powerRank": "8"
                    },
                    "projectPower": {
                        "powerRank": 9
                    }
                },
                {
                    "title": "EVMcrispr",
                    "projectInstantPower": {
                        "totalPower": 3854364.41,
                        "powerRank": "9"
                    },
                    "projectPower": {
                        "powerRank": 5
                    }
                },
                {
                    "title": "Gitcoin Grants Matching Pool",
                    "projectInstantPower": {
                        "totalPower": 3031568.27,
                        "powerRank": "10"
                    },
                    "projectPower": {
                        "powerRank": 12
                    }
                }
            ]
        }
    }
}
```

If you look at the 6th item, it's GIVpower rank is 123 but it's Instant Boosting rank is 6. 
Any fix to this confusion can be implemented on the frontend.

**Comment by laurenluz** [comment]
do believe there is still a bug, but I think we're all on the same page now @aminlatifi @mohammadranjbarz @maryjaf 

lmk if we find a solution!

**Comment by aminlatifi** [comment]
@laurenluz I and Maryam discussed the issue. The sorting is correct, you got confused maybe because you mixed up the value shown here with Project Instant Boosting power
<img width="1226" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/5684607/d5b1de19-3c68-4544-8b64-47d941b3b25b">
Actually, the values in this table are GIVpower boosting, from previous round (same values sum up to make the project GIVpower and rank). But instant boosting (which is not shown anywhere in the UI) is the sum of boosts to this project at the moment.

**Comment by aminlatifi** [comment]
@laurenluz We haven't had such a requirement, so we haven't prepared the essential backend APIs for that.

**Comment by laurenluz** [comment]
No way! That was always a requirement.  I distinctly remember changing it before the launch of GIVpower so we showered the givpower amount in real time.

Otherwise it's very confusing to the user..
 We show donations right away... we should also show givpower

**Comment by aminlatifi** [comment]
> No way! That was always a requirement. I distinctly remember changing it before the launch of GIVpower so we showered the givpower amount in real time.
> 
> Otherwise it's very confusing to the user.. We show donations right away... we should also show givpower

I checked the backend before lefring my previous comment. The API to show the details of project instant boosting has not been implemented. That view had been implemented in frontend by fetching top power boosting to the project, only for the logged in user we show her/his current power.

If we need that feature we can plan it
@MoeNick

**Comment by laurenluz** [comment]
How long will it take to implement? What we need is:

- show the user on the givpower tab the real time givpower on their project
- allow sorting by live givpower amount (instant boost) and set this as the default sort option

**Comment by aminlatifi** [comment]
> How long will it take to implement? What we need is:
> 
> * show the user on the givpower tab the real time givpower on their project
> * allow sorting by live givpower amount (instant boost) and set this as the default sort option

The second item is already implemented and is what's live now.
The first item needs both backend and frontend support, the backend would need at most one day

**Comment by laurenluz** [comment]
If we can prioritize it to have it live by Tuesday, it would be amazing. I know that's not much time.

**Comment by aminlatifi** [comment]
Okay, @laurenluz I will implement the backend today.

**Comment by maryjaf** [comment]
> > @maryjaf - I checked it myself, there is an issue. I know we changed the logic. Default is set to sort by GIVpower Project "music I'm listening to..." has 95,000 GIVpower
> > ![image](https://user-images.githubusercontent.com/75490971/252958561-68557d9c-6535-486a-9ece-9462b4587147.png) Project "foundations of living..." has 63,000 GIVpower
> > ![image](https://user-images.githubusercontent.com/75490971/252958640-cfe3053f-c390-4615-ae50-0229abe56f0a.png)
> > But "music I'm listening to is 3 positions LOWER than foundations in the default sorting...
> > ![image](https://user-images.githubusercontent.com/75490971/252958117-3d17a807-f8ac-4f42-a2b8-4afb9fff604d.png)
> > there is a bug.
> 
> ُThanks @laurenluz we'll check it

May we check together ? because this scenario was not changed on stg @MohammadPCh

**Comment by laurenluz** [comment]
yes exactly... but then we should really try to address and fix this issue asap post-launch @aminlatifi @MohammadPCh

**Comment by divine-comedian** [comment]
Should bring back sorting by instant boosting and see if this is fixed, completely related to front-end, back-end is untouched. need to revert it on the front-end to test it @MohammadPCh

**Comment by MohammadPCh** [comment]
@maryjaf @laurenluz can test it on staging, please? (It will be deployed in 5 mins)

**Comment by maryjaf** [comment]
> @maryjaf @laurenluz can test it on staging, please? (It will be deployed in 5 mins)

It seems the problem has remained still, for example :
when the filter is set on Givpower
the project **"Primate Rescue Center"**(https://staging.giveth.io/project/primate-rescue-center?tab=givpower) with **TOTAL GIVPOWER 187.86** is shown in **position **9****
and the project **Teach music to Children**(https://staging.giveth.io/project/teach-music-to-children?tab=givpower) with **TOTAL GIVPOWER 53,018.17** is shown in **position **11****, although it has more givpower than "Primate Rescue Center"
@MohammadPCh @aminlatifi

**Comment by laurenluz** [comment]
@aminlatifi just pushed a commit here: https://github.com/Giveth/impact-graph/actions/runs/5609895363

after this merges, we can test again

**Comment by maryjaf** [comment]
No change
<img width="1369" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/086da0a9-0177-4e15-8ff6-9154dc0f45f0">
this project with rank 5 and about 97000 givpower is shown in position 16 
https://staging.giveth.io/project/test-adminuser-admin?tab=givpower

**Comment by aminlatifi** [comment]
It must be fixed now.

**Comment by laurenluz** [comment]
I think it looks good now! did some testing. can we get it on prod?

@maryjaf do you agree?

**Comment by maryjaf** [comment]
> 



> I think it looks good now! did some testing. can we get it on prod?
> 
> @maryjaf do you agree?

Yeah I'v been checking and it seems everything is working correctly 
 Thanks @aminlatifi @MohammadPCh

**Comment by mateodaza** [comment]
@CarlosQ96 mentioning you here to check for releasing on production asap

**Comment by laurenluz** [comment]
just gotta say, this feature is SUCH a game changer. thank you all so much for helping get it live
