### ISSUE TITLE
Confusing UX when during QF rounds, many categories are empty

### ISSUE THREAD

**Issue by brichis** [Giveth/giveth-dapps-v2#2867]
**To Reproduce**
1. Go to https://staging.giveth.io/qf/equality
2. Click on the buttons of the different categories
3. See error

**Expected behavior**
Sometimes the category that I want to open moves in a weird way, and sometimes I choose one but I didn't send me to the category that I wanted and stays in the same category.

**Screenshots**
https://images.zenhubusercontent.com/410473836/32391791-51c1-46d5-ba88-3adf5ab18d37/screen_recording_2023_07_11_at_13_14_52.movhttps://images.zenhubusercontent.com/410473836/d8ba1bf1-c281-41f6-92fa-f5719f71c320/screen_recording_2023_07_11_at_13_12_42.mov

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Brave
 - Version: v.1.52.126

**Comment by laurenluz** [comment]
Is it reasonable just to hide the category filters on the QF page? I feel like it's creating a lot of confusiion.. also with so few projects many of these category filters will just be empty.

wdyt @MohammadPCh @MoeNick ?

**Comment by brichis** [comment]
![Screenshot 2023-07-11 at 13 31 42](https://github.com/Giveth/giveth-dapps-v2/assets/106570342/cc6f6768-5f24-4303-b1d3-5a5de4d9a2fb)

**Comment by brichis** [comment]
https://github.com/Giveth/giveth-dapps-v2/assets/106570342/7a8700ed-3e50-4757-aa88-b846af38723f

Sorry, the videos didn't work well

**Comment by brichis** [comment]
https://github.com/Giveth/giveth-dapps-v2/assets/106570342/63749302-9bdb-4773-9afc-ee95e159cbc2

**Comment by maryjaf** [comment]
we checked and couldn't reproduce this and every thing related to category worked correctly.

**Comment by MohammadPCh** [comment]
@brichis Thanks for reporting, but I can't see the error in the video and also in the real test.

**Comment by laurenluz** [comment]
@MohammadPCh - I'm revisiting this now and would like your opinion...

Is there a way that we can hide a category button from a view if there is nothing it it when a particular filter is being applied?
I think it might be some extra logic we'd have to build, but I think that would make this a lot less confusing for people.

cc @jainkrati

**Comment by MoeNick** [comment]
@jainkrati a gentle reminder on this, as @laurenluz asked to remove the category filtering, and need your confirmation and assignments.

**Comment by jainkrati** [comment]
Yes thsi can be done. @MohammadPCh please do your magic !!!!

**Comment by MohammadPCh** [comment]
Hi @Lauren,
Apologies for the delayed response; it appears I overlooked this issue.
Just to clarify, are we in agreement to remove all categories from the QF page?

**Comment by laurenluz** [comment]
I think ideally, we would hide the category if there is no project within that category when the QF filter is one 🤔 - wdyt? is that possible?

**Comment by MohammadPCh** [comment]
@laurenluz, while it's technically feasible, it would require heavy requests to the backend or possibly a new endpoint to fetch the project count in each category and subcategory. However, I believe it's not worth it.

**Comment by laurenluz** [comment]
ok, let's just hide the whole bar on the QF page then

**Comment by MohammadPCh** [comment]
@maryjaf could you please test it? Thanks.

**Comment by maryjaf** [comment]
Sub categories have been removed from QF page like as below pic

QF page:
<img width="1267" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/e8807623-5054-4c96-9430-c93a04aade2e">
All Projects:
<img width="1240" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/0996b49a-c37f-41ad-9a6a-039282d628ce">

Is this your expected result? @laurenluz

**Comment by maryjaf** [comment]
This change has been deployed on prod 
If other solution should be applied, we could create a new issue or reopen this issue
