### ISSUE TITLE
"How it works?" button sends to "Page not found"

### ISSUE THREAD

**Issue by brichis** [Giveth/giveth-dapps-v2#2868]
**To Reproduce**
1. Go to ['...'](https://staging.giveth.io/project/giveth-tour-bridge-the-world)
2. Click on How it works?
3. See error

**Expected behavior**
The page is not found on Giveth Docs

**Screenshots**

https://github.com/Giveth/giveth-dapps-v2/assets/106570342/253598a4-0b69-46fb-b23a-816c27197a90

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Brave
 - Version: v.1.52.126

**Comment by laurenluz** [comment]
@franculio - we can close this wopnce you update the docs.
