### ISSUE TITLE
My Acount: My Project, if Listing status is null

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#287]
if listing=null, we have to show listing status as "waiting for review " 

![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/b61bb40b-f0d9-43dc-9103-a63486d38d47)

**Comment by laurenluz** [comment]
it's good, but a new issue emerged: #399 

![image](https://user-images.githubusercontent.com/75490971/161127918-dddd0c01-185e-4de2-b781-e90b075c2b27.png)
