### ISSUE TITLE
Fix logic & copy on "no results" for category filters

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2879]
When I click many of the categories in QF... I end up with "no results". Then, when I click any of the suggested keywords of categories from below... I get directed AWAY from the QF page, and to a regular projects page w/ that filter applied.

I think this flow is really overly complex and we shouldn't repeat the categories. Also the copy isn't native-english. Can we instead make this simple?

So when I click a category that has no projects... or search a keyword that has no projects... I just see copy:

"There are no projects matching your search. Try removing some filters or using another keyword."

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/22f4f9a3-bc68-420a-91c2-b16f18300155)

any objections @MoeNick @mosaeedi ?

**Comment by MoeNick** [comment]
I think @MohammadPCh has removed the category filtering banner from Qf, so this is solved.

**Comment by MoeNick** [comment]
@MohammadPCh for other project rather than QF, can we change the copy? 
@maryjaf fyi

**Comment by maryjaf** [comment]
Now this message is shown
<img width="976" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/6a83b344-4edb-4bce-b1f6-d00531461cd2">

**Comment by laurenluz** [comment]
oops... a typo....

should be "There **are** no projects..." @MohammadPCh

**Comment by MohammadPCh** [comment]
Fixed, @laurenluz @maryjaf Please test it again :)

**Comment by maryjaf** [comment]
<img width="802" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/e163ad8e-f711-4e65-9b44-72d6d9ea92ba">
ُThanks @MohammadPCh
