### ISSUE TITLE
project preview when sharing the link shows GIVeconomy 

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#288]
When I share a link to a project, the preview no longer says "Check out this project"
It just says GIVeconomy

![image](https://user-images.githubusercontent.com/74267818/158873390-9c863847-bb0a-40dd-8fef-9cb1f4633d98.png)

It should show a preview of the project picture and description and the title should say 'Check out this project etc'

**Comment by mateodaza** [comment]
duplicate [here](https://github.com/Giveth/giveth-dapps-v2/issues/305)

**Comment by aminlatifi** [comment]
#305

**Comment by divine-comedian** [comment]
loooks to be resolved! I checked several projets on the learn more and donate pages and the meta data is showing uniquely
moving to done!

![image](https://user-images.githubusercontent.com/67759413/159725220-9fd64ab6-8c26-4ebc-bfcb-17b9392946eb.png)
