### ISSUE TITLE
QF staging site doesn't say anything about Gitcoin Passport before syncing

### ISSUE THREAD

**Issue by danelsuga** [Giveth/giveth-dapps-v2#2880]
I connected my wallet, was approved for matching, but then the only next (tiny) "instruction" is "update score". (See screenshot.) _Update score of what?_ folks might be asking. No reference to the Gitcoin Passport.

I also recall that before I had updated and refreshed my score, there was no mention of the Passport.
![Screenshot 2023-07-12 1 50 49 PM](https://github.com/Giveth/giveth-dapps-v2/assets/81351744/2262b694-562c-47a9-9023-b63fda182586)

**Comment by laurenluz** [comment]
@Vyvy-vi - can you fix the copy of this to just "Go to Passport" instead of "Update Score"? 

cc @MohammadPCh

**Comment by divine-comedian** [comment]
@maryjaf can you test this text change on staging

**Comment by maryjaf** [comment]
Thanks 
Now below message is shown
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/1b1e77fa-0b2e-4e7e-80c6-8ba96f4f57c6)
