### ISSUE TITLE
Ensure all projects in the QF round have a gnosis address

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2883]
We will be distributing the funds on gnosis - so we need to make sure that projects add their gnosis address to be eligible.

We should:
- run a query to check if projects have a gnosis address
- contact projects who do not an support them to add theirs
- mention that projects will need a gnosis address in our email to them @danelsuga

**Comment by laurenluz** [comment]
@CarlosQ96 or @mohammadranjbarz - can you do a quick check for us on this list of projects to see if they have a gnosis address?

[spreadsheet](https://docs.google.com/spreadsheets/d/1vAH98Q_yhEETouuHheMg-0xD_xxZLeVp1MJ--2lOtMI/edit#gid=1629807942) - look at the tab "Final"... actually this is a list of projects that have raised over $500 since the beginning of Giveth until June 30... so you could just set those limits and then see which have a gnosis address

**Comment by laurenluz** [comment]
leftharis's project was the only one w/o gnosis.. and he says it's not active anymore. so we're good on our main list... just need to ensure that the sponsor-recommended projects have a gnosis address.

@WhyldWanderer - can you check them?

**Comment by WhyldWanderer** [comment]
Checked them and they all have Gnosis!
