### ISSUE TITLE
QF - Single project donation tab - Active round is not reflecting donations

### ISSUE THREAD

**Issue by franculio** [Giveth/giveth-dapps-v2#2891]
Testing on https://staging.giveth.io/ with Brave

When checking the donations made to this project which is eligible for the active round 
![Captura de Pantalla 2023-07-11 a las 16.50.37.png](https://images.zenhubusercontent.com/62ea6f3faed0f381f5fe2f36/11e784ef-4db2-46fa-bcea-5827497058b5)

You can see several donations made during the round that should be reflected in the active round tab (10)
![Captura de Pantalla 2023-07-11 a las 16.50.46.png](https://images.zenhubusercontent.com/62ea6f3faed0f381f5fe2f36/d7dd8fd3-8815-4925-b8af-b53a67dbef59)

But when you go there non of the recent donations appear there, and the amount of estimated matching is not updated as well
![Captura de Pantalla 2023-07-11 a las 16.50.52.png](https://images.zenhubusercontent.com/62ea6f3faed0f381f5fe2f36/a2dba653-8e79-492c-921e-9902e86975b2)

Maybe it has to do that this is not a verified project but it's still included in the round? 

@laurenluz 
@carlosjmelgar 
@mohammadranjbarz 
@mo

**Comment by maryjaf** [comment]
Thanks @franculio for reporting
I tested this for other project and every thing is ok,  only difference between this project and others is that this project was added to the round recently after that the other 20 projects were added  (I think 11 jul ) 
we can check it together tomorrow @mohammadranjbarz @MohammadPCh

**Comment by maryjaf** [comment]
I added a new project to round and this scenarios is happened  for it 
https://staging.giveth.io/project/testgnosis25?tab=donations
but for old project on this round every thing is ok and expected and based on this, I think the hypothesis I mentioned above is probably correct

**Comment by laurenluz** [comment]
@maryjaf - you are the best tested ever!!

@mohammadranjbarz @CarlosQ96 - can you investigate the solution?

**Comment by mohammadranjbarz** [comment]
> @maryjaf - you are the best tested ever!!
> 
> @mohammadranjbarz @CarlosQ96 - can you investigate the solution?

@laurenluz  Yeah I'm working on it

**Comment by mohammadranjbarz** [comment]
@laurenluz  @maryjaf 
I fixed it through https://github.com/Giveth/impact-graph/issues/1058#issuecomment-1634121007

The reason that donations were not connected to projects was the project was not verified, now I donated and it's part of qf round donations

<img width="1283" alt="Screen Shot 1402-04-22 at 15 30 43" src="https://github.com/Giveth/giveth-dapps-v2/assets/9850545/68c4a28a-af7d-47e2-890b-a9d757020fce">

**Comment by maryjaf** [comment]
Thanks @mohammadranjbarz this issue has been resolved
