### ISSUE TITLE
Out of gas error on donation to Giveth on mainnet

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#2893]
**Describe the bug**
Out of gas error on donating the ENS token to Giveth

https://etherscan.io/tx/0x1e7e31d062fc8cd29b106b9b44b8ae3538d1c6937d504bd97a52862a822c8b8e

This was part of a $1000 donation to the matching pool... the second 5% default donation to giveth tho failed 

OH NO!

**Comment by RamRamez** [comment]
@GriffGreen We don't suggest gas for the transactions; Wallets suggest it. Maybe the user had manually changed the gas limit. The gas limit suggested by wallets should be enough for transactions.

https://support.metamask.io/hc/en-us/articles/360038849792-Why-did-my-transaction-fail-with-an-Out-of-Gas-error-How-can-I-fix-it-
