### ISSUE TITLE
QF Testing - no filter for active QF projects

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#2898]
On the Giveth projects page, there is no filter for active QF projects.
![image](https://github.com/Giveth/giveth-dapps-v2/assets/74267818/e773976f-d9d4-41c5-8041-695f88533d68)

I would expect to be able to go to the projects page or a category page and filter to see all active qf projects from all projects or within a category..

**Comment by laurenluz** [comment]
@MohammadPCh - on this page, can we include the filter " [ ] Eligible for Matching "? under the category "Project features"?

I know it's a bit weird... wdyt?

cc @maryjaf

**Comment by laurenluz** [comment]
related at: https://github.com/Giveth/giveth-dapps-v2/issues/2853

**Comment by MohammadPCh** [comment]
@laurenluz  hmm, It's possible I think, but when the user selects this filter, we have to change many things in the project. so I suggest postponing it to the next step.

**Comment by laurenluz** [comment]
ok deal

**Comment by laurenluz** [comment]
We should have the option for the user to select the QF filter when they are on the normal projects page at https://giveth.io/projects
The filter should be always on (and hidden from the filter menu) on the page https://giveth.io/qf

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz says we might already have this implemented on the back-end
> 
> @MohammadPCh - we have to change many things in the all projects list page - will check more on this

These are filters that we have already

```

export enum FilterField {
  Verified = 'verified',
  AcceptGiv = 'givingBlocksId',
  AcceptFundOnGnosis = 'acceptFundOnGnosis',
  AcceptFundOnMainnet = 'acceptFundOnMainnet',
  AcceptFundOnPolygon = 'acceptFundOnPolygon',
  AcceptFundOnCelo = 'acceptFundOnCelo',
  AcceptFundOnOptimism = 'acceptFundOnOptimism',
  GivingBlock = 'fromGivingBlock',
  BoostedWithGivPower = 'boostedWithGivPower',
  ActiveQfRound = 'ActiveQfRound',
}
```

@MohammadPCh  so for this purpose you can just send this filter **ActiveQfRound**

**Comment by MohammadPCh** [comment]
@laurenluz Can you please test it here? https://giveth-dapps-v2-git-add-qf-filter-to-projects-page-givethio.vercel.app/

**Comment by maryjaf** [comment]
Now when we select a specific category like finance this filter related to QF round is set automatically as below pic
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/2d1fa8f9-f227-42d8-ab22-2d44bf7c3736)

**Comment by maryjaf** [comment]
> Now when we select a specific category like finance this filter related to QF round is set automatically as below pic ![image.png](https://camo.githubusercontent.com/4c4cadd3847a8b2cbebb9ee1828bd9553b0a51307aaa7d4404b3611b00253d2d/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f32643166613866392d663232372d343264382d616232322d326434346266376333373336)

Thanks @RamRamez This problem has been resolved
