### ISSUE TITLE
Confusing text when viewing QF donations in project page

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#2899]
Should say 

<Round Name> Donations

e.g "Round 10 Donations"

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/dc6e5b1b-2fba-4184-a8fe-c13f9f8c0808)

**Comment by laurenluz** [comment]
We should:
- delete intro copy "Round:"
- say: "< round name > donations"

 ... so for our live round it will say "QF Alpha Round donations", and we'll set the round name in admin bro.

**Comment by maryjaf** [comment]
<img width="465" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/61ca8bbd-4be1-4777-a719-85d555af47e9">
Is this ok ? or QF-test round donation ? @laurenluz @MohammadPCh

**Comment by laurenluz** [comment]
that's perfect @maryjaf @MohammadPCh
