### ISSUE TITLE
Fix redirects for giv.giveth.io

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#290]
Right now: htttps://giv.giveth.io/givfarm redirects to https://giveth.io/giveconomy

Same for /givgarden /givstream /givbacks

We should fix it so that:

giv.giveth.io/givfarm --> giveth.io/givfarm
giv.giveth.io/givgarden --> giveth.io/givgarden
giv.giveth.io/givstream --> giveth.io/givstream
giv.giveth.io/ --> giveth.io/giveconomy

**Comment by geleeroyale** [comment]
I am pretty sure this is not possible easily. We set a general redirect for giv.giveth.io and it will redirect everything to giveth.io/goveconomy - there are no individual routes (as suggested by the slash). We could probably spin up an instance of nginx and route everything manually, but it is very bad practice to use it like this. The URL giv.giveth.io does not exist anymore. We should use the real URLs when promoting the content.

**Comment by laurenluz** [comment]
I asked devops Mike to look into this as well

**Comment by CFWHISPERER** [comment]
Do either of these two links help?  One is Apache the other NGINX

https://stackoverflow.com/questions/11388618/redirect-all-wildcard-subdomains-to-root-domain
https://serverfault.com/questions/583944/nginx-redirect-all-old-domain-subdomains-to-new-one

**Comment by CFWHISPERER** [comment]
This is a bit more current for the NGINX web server https://thesynack.com/posts/setup-nginx-subdomain-redirect/

**Comment by geleeroyale** [comment]
Thanks Mike, I will take a look!

**Comment by geleeroyale** [comment]
I completed this task. Because we use permanent redirects your browser might not resolve correctly. One option is to "flush DNS cache" for your operating system, or use a new device to check the links (I used my phone for example). I can confirm that all links work and resolve correctly for new users (first clicks)

FYI @aminlatifi I used the nginx fowarder we already use for other service located on the `feathers` server

**Comment by divine-comedian** [comment]
tested using the links provided above on brave browser w/ clean cache and cookies

> giv.giveth.io/givfarm --> giveth.io/givfarm
giv.giveth.io/givgarden --> giveth.io/givgarden
giv.giveth.io/givstream --> giveth.io/givstream
giv.giveth.io/ --> giveth.io/giveconomy

Looks like they all redirect successfully - calling this DONE

**Comment by MoeNick** [comment]
@divine-comedian according to [this bug](https://github.com/Giveth/giveth-dapps-v2/issues/441), would you pls check it again?

**Comment by MoeNick** [comment]
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/9b615309-85a1-40c7-983a-c6b5870c7fd0)

**Comment by MoeNick** [comment]
It's solved now

**Comment by divine-comedian** [comment]
yessss.. just fixing the emails right now
