### ISSUE TITLE
QF - Donation page - Donation amount changes when scrolling

### ISSUE THREAD

**Issue by franculio** [Giveth/giveth-dapps-v2#2900]
Testing on https://staging.giveth.io/ with Brave

When selecting the text field to introduce the amount number for the donation if you are using a trackpad and you scroll down to go and click `Donate` the number changes. Scrolling down it goes to minus numbers and it doesn't let you donate...

I'm trying to make a video but I can get Loom to work so I'll post picture for now. 
![Captura de Pantalla 2023-07-13 a las 18.44.40.png](https://images.zenhubusercontent.com/62ea6f3faed0f381f5fe2f36/60c14a6c-34a6-4fb5-af56-31282412895a)

**Comment by franculio** [comment]
@laurenluz

**Comment by laurenluz** [comment]
@MoeNick I think this one we don't need to fix for the MVP, but it would be nice to fix eventually 😅  can you help it not get lost?

**Comment by divine-comedian** [comment]
Can we disable the scrolling feature or can we bound it so it can't go below 0? 

@MohammadPCh

**Comment by laurenluz** [comment]
tested on staging and thankgaaawd it works @Zeptimus @danelsuga @franculio :D
