### ISSUE TITLE
QF Project page - Passport link goes to..givbaks docs??

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#2906]
On the single project page for a QF eligible project.. 

There is a card that explains GIVbacks, offers to boost etc.. and a button that says Go To Passport.. however when I click this link it takes me to the GIVbacks documentation... 

Either this should say "Learn More" (about GIVbacks) or the link should lead to the passport page. It's also strange because the text in the card says nothing about passport so the user doesn't have a clue about what the passport is by reading the associated text..

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/baa03df0-eff6-4fb0-95a1-58f2107ddd99)

**Comment by divine-comedian** [comment]
fixed in 

https://github.com/Giveth/giveth-dapps-v2/commit/b70436ac60732bbf80a7d84cb0ada349ca0d7faf

**Comment by laurenluz** [comment]
oh man 😮‍💨  I made an issue to make "Learn more" related to passport change to "Go to Passport" - did you check all instances of "Go to passport" @divine-comedian ?

**Comment by divine-comedian** [comment]
> oh man face_exhaling I made an issue to make "Learn more" related to passport change to "Go to Passport" - did you check all instances of "Go to passport" @divine-comedian ?

Yeah, I can see whoever did the issue must have gotten confused and changed in our translations file the `learn_more` tag to say "Go To Passport" - so I just simply changed it back to Learn more.

**Comment by divine-comedian** [comment]
@divine-comedian  needs to test this scenrario again

**Comment by laurenluz** [comment]
@divine-comedian - did you check this?

**Comment by divine-comedian** [comment]
looks good!

testing on production:
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/c69948c2-5da5-41d5-9752-e858b212c54a)
