### ISSUE TITLE
Change links for "Our Mission"

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#2907]
Hovering over the Our Mission link makes it go pure white, so it looks like it dissapears. It also links to our docs when it should link to the mission page that we have already inside of the dapp.

https://github.com/Giveth/giveth-dapps-v2/assets/67759413/00f51bb0-521f-4b2d-8395-c55f7f1b0aad

**Comment by MoeNick** [comment]
@maryjaf 
Pls check.
@alireza-sharifpour do you have a band width for a quick fix?

**Comment by laurenluz** [comment]
@alireza-sharifpour Two things:

- fix color change (I think it can just stay blue when you mouse over...
- let's make it link to here: https://giveth.io/about

**Comment by MohammadPCh** [comment]
@maryjaf It's ready to test.

**Comment by maryjaf** [comment]
Thanks @MohammadPCh this issue has been resilved

**Comment by maryjaf** [comment]
Now this link is shown:
https://staging.giveth.io/about#mission
