### ISSUE TITLE
Too many decimals places on GIVbacks matching amount 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#2909]
testing on staging
browser: brave

on the single project page of a verified project there is too many decimal places shown for the GIVbacks matching amount - it should be limited to one decimal place 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/69192064-527d-4c53-9b8c-894b38dcc845)

**Comment by Vyvy-vi** [comment]
related to #2865

**Comment by divine-comedian** [comment]
fixed in 

https://github.com/Giveth/giveth-dapps-v2/commit/ff8c73fbe335fa58610170338ea8758452e0ad80

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/78469733-1bee-4d0b-bb13-25718ffef152)
