### ISSUE TITLE
Most funded and most liked doesn't sound right

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#2911]
<img width="347" alt="Screenshot 2023-07-14 at 8 42 23 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/14945613/c20cdda0-d3f1-4273-ba0f-e1b63051ca68">
<img width="912" alt="Screenshot 2023-07-14 at 8 41 16 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/14945613/30fcbf7f-a066-4dd1-a966-4da5e61db6db">

I would say "Raised" And "Likes"

**Comment by laurenluz** [comment]
@MohammadPCh - easy fix - can we do it with QF?

**Comment by MoeNick** [comment]
It's backend @mohammadranjbarz 
FYI @maryjaf

**Comment by MoeNick** [comment]
Aha you meant copy, OK

**Comment by laurenluz** [comment]
- change "most funded" to "Amount raised"
- change "most likes" to "Likes"

**Comment by RamRamez** [comment]
@maryjaf It's merged. You can test it.

**Comment by laurenluz** [comment]
oh no... now on the QF page, when you sort by "amount raised"... I think it sorts still be all time funding (not in the QF round) - so it looks wrong.

@RamRamez - maybe the easiest solution is to say instead "All time funding"? will it fit in one line? or is it too long?

**Comment by RamRamez** [comment]
> oh no... now on the QF page, when you sort by "amount raised"... I think it sorts still be all time funding (not in the QF round) - so it looks wrong.
> 
> @RamRamez - maybe the easiest solution is to say instead "All time raised"? will it fit in one line? or is it too long?

@MohammadPCh Can you check it?
