### ISSUE TITLE
By taping on reject in sign in process of passport the incorrect  error message is shown

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#2924]
**Describe the bug**
By taping on reject in sign in process of passport the below error is shown
"user rejected signing (action=\"signMessage\", from=\"0x1C4f4115b3234d6033Da4B77a3d09f66b4F7B623\", messageData=\"I hereby agree to submit my address in order to score my associated Gitcoin Passport from Ceramic.\\n\\nNonce: d2d06170c79864d16d5af38239b67610f0b7f2b76b5e02f17dee59aa43c5\\n\", code=ACTION_REJECTED, version=providers/5.7.2)"

**To Reproduce**
1. Go to 'https://staging.giveth.io/qf'
2. Click on 'sign message'
3. tap on "reject" on metamask modal

**Expected behavior**
showing appropriate message related to rejection of process

**Screen Shot**
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/7390045c-c6d4-4bf2-89cd-d8a2e77c7c95)

@MohammadPCh

**Comment by MohammadPCh** [comment]
Moved :smile:
