### ISSUE TITLE
Make modals more user friendly

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapps-v2#294]
It would be better if modals be closed by:

- Clicking outside the modal
- Pressing the escape button

It should be implemented in the modal component of the design system (https://github.com/Giveth/ui-design-system/)

**Comment by divine-comedian** [comment]
testing on `staging.giveth.io` 

clicked on the donate modals as well as the modals inside of the givfarm 

i noticed this signIn modal I am only able to exit by clicking the `x`
![image](https://user-images.githubusercontent.com/67759413/163679917-fca6027f-c096-4132-99a7-91861a94f51d.png)

and the web wallet one that follows I cannot exit with the `esc` key
![image](https://user-images.githubusercontent.com/67759413/163679957-d804e807-32f0-44ce-bdd7-315522e3b075.png)

tested out the others and everything else seems to look good
@RamRamez
