### ISSUE TITLE
When the QF round has not started yet, our Gitcoin passport banner should say "there is no active round!"

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2946]
Right now, when we "activate" a QF round in admin bro... but have the start date/time at some point in the future, we are showing this:
![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/15028e9c-a81d-4421-8635-2f20bf84a75c)

Basically, we need a new condition for the passport banner for this...
- when there is an active round, but the round start date is in the future - we should show the "no active round!" banner

@MohammadPCh - does this need backend support?

post-MVP

**Comment by MohammadPCh** [comment]
@laurenluz No, It's totally front-end. I will do it.
