### ISSUE TITLE
QF Testing - Copy Edit on Banner

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#2950]
Banner should say "Your donations are eligible to be matched!"

![image](https://github.com/Giveth/giveth-dapps-v2/assets/74267818/4087ac54-745c-4f8b-9ebd-6a31ad0ec9f5)

@laurenluz @MohammadPCh

**Comment by MohammadPCh** [comment]
Nice catch, Thanks @WhyldWanderer
