### ISSUE TITLE
After donation confirmation - copy fix on QF passport box

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2956]
this should say "After the < round name > ends on < round end date > ..." 
...and maybe we need to make sure that the copy is also correct with the other passport conditions

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/d86fb2e6-2c19-4e7c-8e31-675410960a8f)

**Comment by maryjaf** [comment]
Thanks @MohammadPCh 
below pic is shown after donating with wallet that has enough score
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/707a2ef9-f9c2-4669-ab98-85ec25c6308c)
should we also change this copy? @laurenluz 
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/b31420a1-71e8-4018-a0c3-df3cccdbed44)

**Comment by laurenluz** [comment]
@maryjaf - I think the copy on the second condition is ok as it is :) we can call this done.
