### ISSUE TITLE
Catalan Translations

### ISSUE THREAD

**Issue by Zeptimus** [Giveth/giveth-dapps-v2#2961]
https://docs.google.com/document/d/1uXjovr7Pc8MB6r3GO7j3yuIvpajwSMZLxTd1Z_bkIiU/edit

Incorporate those sugestion on the catalan version of giveth.

**Comment by divine-comedian** [comment]
Is that this file?
https://github.com/Giveth/giveth-dapps-v2/blob/develop/lang/t_ca.json

**Comment by divine-comedian** [comment]
Yep! @RamRamez can work on this and @Santigs can answer any questions and help review it since he is a native speaker.

**Comment by Santigs** [comment]
I've reviewed the GitHub file and most of the wording is correct but there are a few sentences I am not sure about.
Who can show me the context to make sure the translations reflect the correct message?

**Comment by divine-comedian** [comment]
> I've reviewed the GitHub file and most of the wording is correct but there are a few sentences I am not sure about. Who can show me the context to make sure the translations reflect the correct message?

If you can paste in text the labels of the sections that don't make sense then @RamRamez can show you where they are on the dapp

**Comment by MoeNick** [comment]
@Santigs @RamRamez 
Do you guys need a meeting? 
How we can push it forward?

**Comment by Santigs** [comment]
I'd like to get some context for a few of the translations to make sure
they are correct, how can I find out the page/popup where those messages
are shown?

**Comment by divine-comedian** [comment]
@Santigs you and I can pick a time and I think we can do this one together.
