### ISSUE TITLE
USER REPORT: The Blockies dont match metamask and other platforms

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#2963]
<img width="595" alt="Screenshot 2023-07-20 at 12 17 59 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/14945613/34d86713-79bf-4724-8953-535a8c37776a">

This is an important fix, as this user runs CLR.fund (an ally in the web3 donation space) and donated 1001 xDai to the Matching Pool!

Lower priority than QF bugs... but still an important fix!

**Comment by MohammadPCh** [comment]
we use a default image for users who don't have a profile picture. It's not real blockies :D
if we want to show blockies for users, we need to implement it in the backend.
these are 2 libraries for it:
https://github.com/Imdavyking/blockies_ethereum
https://github.com/MyCryptoHQ/ethereum-blockies-base64

@GriffGreen @laurenluz @mohammadranjbarz

**Comment by laurenluz** [comment]
I'm not sure if that's worth the work. @GriffGreen - wdyt?

**Comment by GriffGreen** [comment]
We should just change the default image to be not a blockie! 

Lets make it a unicorn, or a giveth flower or something :-D

**Comment by MoeNick** [comment]
@mosaeedi can you give us user icon for this purpose?

**Comment by mosaeedi** [comment]
Behold the mighty Giveth unicorn profile photo!

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb0l0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9b3fcb72668bd17ca198f13b123c1c6ce4664410/Screenshot%202023-08-23%20at%204.21.15%20PM.png)

**Comment by mosaeedi** [comment]
Download the exported file from here -> [Profile photo.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb1F0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b362e19b772b7104d63c8b5961992471785da2ef/Profile%20photo.zip)

**Comment by mosaeedi** [comment]
Please download the file!
It contain SVG and PNG.

**Comment by MohammadPCh** [comment]
@mosaeedi Thanks  :)

**Comment by MoeNick** [comment]
@maryjaf pls take a look and confirm

**Comment by maryjaf** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdXRQIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--76caa5d465d75db07aa28c743bdb24b78e0ea63a/image.png)

**Comment by MoeNick** [comment]
@maryjaf pls test in MetaMask brower on your mobile.

**Comment by maryjaf** [comment]
> It should be better that for default pic the remove pic is disabled because by taping on it nothing happens . [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBakpwIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2567943348fa06a92d465bc446208b0cd121d040/image.png) @MohammadPCh @mosaeedi
Is this  Accepted? @MoeNick 
I checked on mobile and laptop

**Comment by MoeNick** [comment]
@MohammadPCh @alireza-sharifpour @RamRamez a quick QA issue is here:
 Disabling the "removed pic button" for the default profile picture.

**Comment by RamRamez** [comment]
> @MohammadPCh @alireza-sharifpour @RamRamez a quick QA issue is here: Disabling the "removed pic button" for the default profile picture.

I'm on it.

**Comment by maryjaf** [comment]
> It should be better that for default pic the remove pic is disabled because by taping on it nothing happens.

Thanks @RamRamez This issue has been resolved
