### ISSUE TITLE
Project's rank is shown"__" for all projects on stg

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#2969]
**Describe the bug**
showing rank of project is buggy on stg

**To Reproduce**
1. Go to 'all projects'
2. check rank

<img width="1427" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/e8e9c31c-cb87-45d3-92b9-45797e378475">

**Comment by CarlosQ96** [comment]
Fixed thanks to Amin and me investigating the server.

**Comment by MoeNick** [comment]
Can u confirm @maryjaf ?

**Comment by maryjaf** [comment]
> Can u confirm @maryjaf ?

Yeah , I checked on stg and the problem has been resolved
