### ISSUE TITLE
bug in update form of project on STG

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#2970]
**Describe the bug**
when I tap on tab of update for one of my projects , I can't type anything in title and description

**To Reproduce**
1. Go to one of your projects 
2. Click on 'Update'
3. See error

**Comment by MohammadPCh** [comment]
@maryjaf it's ready to test :)

**Comment by maryjaf** [comment]
Thanks @MohammadPCh this issue has been resolved
