### ISSUE TITLE
Project Single Page, public view: iPhone Mobile view issues 

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#2971]
**Describe the bug**
we have some issue for project view on iPhone
 
**To Reproduce**
1. Go to 'all project'
2. Click on 'one project' by iPhone
3. See error

**Screenshots**
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/92df116a-99e3-45a3-bb95-44ab3d5fd3f5)

**Smartphone (please complete the following information):**
 - Device: iPhone12
 - Browser: Metamask browser,Chrome,Safari

**Comment by maryjaf** [comment]
2- Qf passport banner on iPhone
<img width="318" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/3952b116-8880-4938-8e70-a43bc30e0b50">
<img width="310" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/7ce3c476-988e-4d65-8ad0-da7f30d87e3f">
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/0ecede9e-b96c-4b31-86e0-97e021b8a10c)

**Comment by maryjaf** [comment]
3- Owner view
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/82d3a782-678c-49ce-926a-dbe5d465c453)

**Comment by maryjaf** [comment]
Thanks @alireza-sharifpour Item 2 has been resolved 
 1 and 3 are still open

**Comment by MoeNick** [comment]
https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=4054-112467&mode=design&t=xjtf7LQnI6q0d3od-4

It's the public view hot fix design
@MohammadPCh

**Comment by MohammadPCh** [comment]
@alireza-sharifpour Can you take it?

**Comment by alireza-sharifpour** [comment]
Yes i'll work on the new design of this page (Bottom of the page)

**Comment by maryjaf** [comment]
> Thanks @alireza-sharifpour Item 2 has been resolved 1 and 3 are still open

**Comment by alireza-sharifpour** [comment]
> > Thanks @alireza-sharifpour Item 2 has been resolved 1 and 3 are still open

We are waiting for the owner's view design of this section, after the design get's ready and the change in the Frontend, issue number 1 and 3 should be fixed.

**Comment by divine-comedian** [comment]
Thanks @alireza-sharifpour - @mosaeedi I assume you're on it?

**Comment by MoeNick** [comment]
We'll start it this week with @mosaeedi

**Comment by MoeNick** [comment]
I will rename this to public view and create another one for owner view.

**Comment by MoeNick** [comment]
@maryjaf you can test the rest

**Comment by maryjaf** [comment]
Problems related to project view and owner view are still exist on STG
Do we have any feature branch for that? @alireza-sharifpour

**Comment by maryjaf** [comment]
> I implemented the new public view for mobile and for the rest, everything should be the same as before. Please test mobile and desktop view for this section on staging. @maryjaf


Thanks @alireza-sharifpour 
The public view is ok on iPhon and the problem has been resolved

**Comment by maryjaf** [comment]
Do we have a separate issue for owner view? @alireza-sharifpour If yes we can move this issue to Done
