### ISSUE TITLE
ENS Opportunity

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#2977]
We could give each project on Giveth a subdomain in a pretty interesting way.... completely gasless, but we would pay a service provider to maintain it.

https://namestone.xyz/docs

https://t.me/superslobo has more information, but it would be something like every project gets: xxxxx.giv.eth e.g. givethouse.giv.eth, they could pick it themselves.  

I think we are on a feature freeze right now, but I want to make sure i put it here so that it doesnt get lost.

**Comment by MoeNick** [comment]
Want to plan it @divine-comedian

**Comment by divine-comedian** [comment]
Nope! Keep this in the icebox
