### ISSUE TITLE
there are some discrepancy in verification status in my project list and project owner view

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#2979]
**Describe the bug**
it seems that verification status of project in my project list is shown based on verified status in [Project](https://serve.giveth.io/admin/resources/Project) and verification status of project in project  owner view is shown based on verification status in [Project Verification Form](https://serve.giveth.io/admin/resources/ProjectVerificationForm)

for example:
https://staging.giveth.io/project/mary00000
<img width="1422" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/b47386f0-ac8a-4f39-965a-b2547de7893c">
<img width="1440" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/9c3d7984-d4d1-499c-8de7-ff8f54f333d7">

**Comment by MoeNick** [comment]
@maryjaf did you change something manually for this verification request in Admin?

**Comment by maryjaf** [comment]
the verify /unverified flow is manually and when we change the verified status from edit page in admin bro this scenario is happened
for example:
the project is verified and verification status is verified in "project verification form"
when we change the verified status and uncheck the box,  from edit page,  the verification status isn't changed in project verification form status
it seems backend issue and it better that @mohammadranjbarz also take a look 
<img width="1439" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/d6333843-6f97-4b3a-bb8b-af30020db215">

**Comment by CarlosQ96** [comment]
Ill take it

**Comment by CarlosQ96** [comment]
This is an edge case as you should be using the buttons verify and unverify not the edit it directly which is a functionality of Adminjs that we left editable.

I can copy the logic off the Unverify/verify buttons to modify the verification form when editing.
Or we can disable the edit directly of the field. What do you think? 
@maryjaf @MoeNick

**Comment by MoeNick** [comment]
Admins sometimes need to do verification process here, so disabling is not a good choice, if we can copy the logic here it would be fantastic, but it's out of the scope of this issue.
@maryjaf can you confirm testing on another clean project that we can close this one?

**Comment by maryjaf** [comment]
> Admins sometimes need to do verification process here, so disabling is not a good choice, if we can copy the logic here it would be fantastic, but it's out of the scope of this issue. @maryjaf can you confirm testing on another clean project that we can close this one?

for every project that the admin user changes verification status from edit page this scenario is happened
shouldn't we fix this bug?

**Comment by maryjaf** [comment]
> for every project that the admin user changes verification status from edit page this scenario is happened

If this is accepted we can close this issue 
But I think if this functionality  is buggy it's better that either we disable changing verify status from edit page or fix it

**Comment by CarlosQ96** [comment]
Yeah i'll push a Pr

**Comment by CarlosQ96** [comment]
Pr ready for review.

**Comment by CarlosQ96** [comment]
Its deployed on staging can test @maryjaf

**Comment by maryjaf** [comment]
> the verify /unverified flow is manually and when we change the verified status from edit page in admin bro this scenario is happened for example: the project is verified and verification status is verified in "project verification form" when we change the verified status and uncheck the box, from edit page, the verification status isn't changed in project verification form status it seems backend issue and it better that @mohammadranjbarz also take a look <img alt="image" width="1439" src="https://user-images.githubusercontent.com/111529185/257696258-d6333843-6f97-4b3a-bb8b-af30020db215.png"> <img alt="image" width="1440" src="https://user-images.githubusercontent.com/111529185/257696466-66f3b8ac-f71c-433d-afcb-3558d84070a4.png"> <img alt="image" width="1434" src="https://user-images.githubusercontent.com/111529185/257696562-85551342-c182-4ff4-9dc0-6b300ac3487b.png">

Thanks @CarlosQ96 this problem has been resolved and now if the verify status is changed from edit page the verification status in project verification form has been updated correctly

**Comment by maryjaf** [comment]
> it seems that verification status of project in my project list is shown based on verified status in [Project](https://serve.giveth.io/admin/resources/Project) and verification status of project in project owner view is shown based on verification status in [Project Verification Form](https://serve.giveth.io/admin/resources/ProjectVerificationForm)

But this question still exists
Do we want to equalize the front logic for showing the verify status in the "my project" list and in the "project view"?
imagine verification status of one project in "verification project form" is submitted and so  verify status  of this is project in "project list" in admin bro is false
for this project the status of verification is shown as below pic 
<img width="1406" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/9496aebe-2d76-452e-a278-fb123e4b0269">

<img width="1437" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/aff9d9ae-61d8-463f-a1a6-1ddf591f27dd">

@MoeNick @RamRamez

**Comment by CarlosQ96** [comment]
This is mostly a staging thing I can fix them manually but you can also fix them in the Adminjs, but the main issue is solved.

**Comment by MoeNick** [comment]
I think it's good @maryjaf 
Lets mve t to done
