### ISSUE TITLE
Deploy GIVbacks Relayer on Optimism

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#2980]
We need to deploy the GIVbacks Relayer first on Optimism Goerli and then on Optimism 

The GIVbacks Relayer is a distributor from the token distro that allows us to send out many GIVbacks to many recipients with a single transaction - it creates batches of GIVbacks to send out and fires them off sequentially by itself.

@paxthemax worked in this many moons ago so I will figure out how we can set it up again on OP goerli

**Comment by divine-comedian** [comment]
Looks very simple to deploy - will also ask for help from @sembrestels  to make some updates to EVMcrispr so we can use it to send out GIVbacks on Optimism

**Comment by divine-comedian** [comment]
Relayer has been deployed to OP Goerli! 
https://goerli-optimism.etherscan.io/address/0x3e2c98f1fd45481f391005f259bc85cce12f87d1

It has been assigned as a distributor by the token distro and given 100k GIV tokens to allocate

**Comment by laurenluz** [comment]
From mitch:

> The GIVbacks Relayer has already been deploy to OP goerli - I need to work with @sembrestels to make some changes to EVMcrispr so we can use it there, same as we do with current GIVbacks - otherwise it can be a big pain in the butt to work with.
> 
> EDIT: Oops I think that since we won't be able to use an Aragon DAO on Optimism - Aragon doesn't exist on Optimism - we'll have to find a way to do it with gnosis safe that isn't too complicated.

@divine-comedian - do you have any ideas on how to do it with gnosis safe?

**Comment by divine-comedian** [comment]
@laurenluz 

I am actually working with Sem to see if we can do it with a Governor Contract that we would only need to deploy on Optimism Goerli, using Gnosis Safe would be very complex. 

https://docs.openzeppelin.com/contracts/4.x/governance

**Comment by divine-comedian** [comment]
@sembrestels and I discussed - there is actually Aragon deployed on Optimism! (thanks to sem) 

So he has prepared a new aragon app called batcher-app which will make it easier and more universal for doing actions like sending GIVbacks 

He is working to integrate this now into Aragon DAOs and modifying EVMcrispr so it can be used from there.

**Comment by divine-comedian** [comment]
GIVbacks relayer is live! 
 https://optimistic.etherscan.io/address/0xf13e93af5e706ab3073e393e77bb2d7ce7bec01f
 
 We should wait for successful distribution but it should work the same as Gnosis Chain - Sem needs to make some modification to EVMcrispr to allow multichain givbacks
