### ISSUE TITLE
Get GIV on Optimism for GIVpower incentives

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#2986]
Assuming we launch August 8, we should make sure we have at least 600k GIV on Optimism.

In the call last week, we agreed to bridge 5 Million GIV to Optimism for future uses and hold it in the multisig

**Comment by divine-comedian** [comment]
Hey, I finished it this morning already actually - you can check on the main multisig on Optimism it has 4m GIV in it.

About 750k-800k will be used to make GIV/DAI on Velodrome as part of an unrelated initiative.

**Comment by laurenluz** [comment]
Thank you Mitch!!
