### ISSUE TITLE
Refactor create project coding

### ISSUE THREAD

**Issue by RamRamez** [Giveth/giveth-dapps-v2#2995]
Due to recent chains added to the dapp, codes are messy and prone to be buggy.
Besides that, we can refactor codes to automatically detect new chains that are added to the config, then on adding a new chain, there will be no code changing, and adding the chain to the conf would be enough.

**Comment by RamRamez** [comment]
I've done this refactoring to:
1. Manage Project Addresses Modal (on the user projects page)
2. Switch Network Modal (right top menu)
3. Add Address Modal (on verification - manage funds step)

Create project page is much more complicated, but it would be definitely helpful if we do this

**Comment by MoeNick** [comment]
Are you still busy with this? if so pls attach a sprint tag. @RamRamez

**Comment by RamRamez** [comment]
> Are you still busy with this? if so pls attach a sprint tag. @RamRamez

I've sent the PR. it's waiting for review.

**Comment by maryjaf** [comment]
Plz check this
[Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBandyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--51292dc0e9190234e1808060a1ae7094c2820228/image.png)

I added this wallet address for Goerli  and when I try to add this address for Gnosis I got this error:Failed to fetch

**Comment by maryjaf** [comment]
There has been a problem on backend stg maybe the reported bug was related to that

**Comment by maryjaf** [comment]
one question
we had a problem on creation projects scenarios by changing wallet address that Griff also has reported, 
can we consider this changes in refactoring create project ?

**Comment by maryjaf** [comment]
it seems @Vyvy-vi is working on it 
Thanks @RamRamez every scenarios related to creation project works as before
