### ISSUE TITLE
Bug In deactivated project flow 

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#2998]
**Describe the bug**

1-When I change status of my verified project from "active" to "deactivated" it is better that the status of verification also is changed to unverified 
Do you agree? @MoeNick @divine-comedian 

2-Some times after deactivating a project this message is shown
Application error: a client-side exception has occurred (see the browser console for more information).
and by refreshing this problem has been resolved(this bug don't happen every time for me )
 
<img width="1430" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/a9f5a5ba-b424-4cc4-b6e9-1c3a44ca0377">

**Comment by MoeNick** [comment]
1- No it shouldn't, @WhyldWanderer team wants it in this way that the verification badge won't change on deactivation. 

2- please add more information that can DEvs reproduce it.

**Comment by maryjaf** [comment]
> 1- No it shouldn't, @WhyldWanderer team wants it in this way that the verification badge won't change on deactivation.
> 
> 2- please add more information that can DEvs reproduce it.

I have no more evidence, some times we try to deactivate the project this bug happens
1-go to my project and select one of them
2-tap on deactivate project
3- select a reason
4- see error

**Comment by divine-comedian** [comment]
> > 1- No it shouldn't, @WhyldWanderer team wants it in this way that the verification badge won't change on deactivation.
> > 2- please add more information that can DEvs reproduce it.
> 
> I have no more evidence, some times we try to deactivate the project this bug happens 1-go to my project and select one of them 2-tap on deactivate project 3- select a reason 4- see error

What does your console say? Might give us more information on the error (ctrl + shift + i)

**Comment by maryjaf** [comment]
I will check a few more times to create this error again, this time with open console

**Comment by maryjaf** [comment]
<img width="1435" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/fbe0a098-15dc-482c-9a1c-3f02f388cb3f">

instrument.js:109 TypeError: Cannot read properties of undefined (reading 'cancel')
    at tS (DeactivateProjectIndex.tsx:139:31)
    at ab (react-dom.production.min.js:167:135)
    at ud (react-dom.production.min.js:197:256)
    at i (react-dom.production.min.js:292:18)
    at oO (react-dom.production.min.js:280:383)
    at react-dom.production.min.js:280:319
    at oF (react-dom.production.min.js:280:319)
    at ox (react-dom.production.min.js:271:86)
    at oS (react-dom.production.min.js:268:399)
    at x (scheduler.production.min.js:13:197)
    at MessagePort.T (scheduler.production.min.js:14:126)
(anonymous) @ instrument.js:109
overrideMethod @ console.js:213
K @ index.js:244
fn @ index.js:194
componentDidCatch @ index.js:59
a.componentDidCatch.t.callback @ react-dom.production.min.js:190
lH @ react-dom.production.min.js:144
uY @ react-dom.production.min.js:261
e @ react-dom.production.min.js:260
(anonymous) @ react-dom.production.min.js:260
oI @ react-dom.production.min.js:282
oS @ react-dom.production.min.js:269
x @ scheduler.production.min.js:13
T @ scheduler.production.min.js:14
Show 1 more frame
Show less
instrument.js:109 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred

**Comment by divine-comedian** [comment]
Thanks @maryjaf  - I think this implies a bug on the front-end

@mateodaza would you have any bandwidth to investigate this week?

**Comment by mateodaza** [comment]
I opened this [draft PR](https://github.com/Giveth/giveth-dapps-v2/pull/3009) with a  better debugging, check the console on here to see what's going on as I can't replicate on my local

**Comment by maryjaf** [comment]
I think I found the scenario
after selecting a reason taping on "deactivate this project" button
If we tap on this button("deactivate this project") twice, before showing the last modal of successful  deactivation this error is shown 
@mateodaza @divine-comedian

**Comment by MoeNick** [comment]
@mateodaza we need your support here again.

**Comment by mateodaza** [comment]
> I think I found the scenario after selecting a reason taping on "deactivate this project" button If we tap on this button("deactivate this project") twice, before showing the last modal of successful deactivation this error is shown @mateodaza @divine-comedian

Thanks for that scenario! It's more clear now to replicate

Latest changes on the [PR](https://github.com/Giveth/giveth-dapps-v2/pull/3009) fixes this

**Comment by maryjaf** [comment]
thanks @mateodaza I checked on this pr and the problem has been resolved
