### ISSUE TITLE
Giveth NFT Project

### ISSUE THREAD

**Issue by markoprljic** [Giveth/giveth-dapps-v2#300]
NFT project with utility for Donors and anyone who wants to participate in the GIVeconomy. 
Santi proposed this project and will prepare an official proposal on the Forum to discuss further.

**Comment by MoeNick** [comment]
Hey Hey :) 
Can you pls elaborate it more, what is it? where did it get discussed? do we have any specs? @markoprljic @Santigs 
I cant find proposal of the forum.

**Comment by markoprljic** [comment]
@MoeNick This is an Epic, it has some issues attached to it. 
The proposal is on the Forum https://forum.giveth.io/t/the-givers-the-giveth-ecosystem-pfp-collection/478/2

**Comment by MoeNick** [comment]
Oh Ok @Santigs , just moved both of them to Epic column in ZenHub. Thanks

**Comment by Santigs** [comment]
Thank you, it is related to this forum proposal
https://forum.giveth.io/t/using-nfts-to-facilitate-more-donations-to-giveth-projects-poignart-giveth-integration/531
