### ISSUE TITLE
Token Icons not updating on donation page

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3000]
testing on production 
browser: brave & firefox
OS ubuntu 22.04

While choosing a token to donate with I can see the list of eligible tokens and their token symbol, however when I select a token the token icon does not update in the donation box, when I switch networks it does not update the symbol either, only on a page refresh does the token icon update from a network change. 

The token selected should have its associated icon show up along with it in the donation box when a user selects a token to donate with.

![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/ef509aef-0edd-408a-9f84-b7fcbb8a20ef)

![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/49542b5d-a002-452c-98af-1d4dce6d40a4)

Here's a short video showing more of the bug:
https://images.zenhubusercontent.com/448919340/08c25fc0-efae-462f-95d8-20a4ec6cdee7/givethtokenbug.mp4

**Comment by alireza-sharifpour** [comment]
Yes @divine-comedian, I'll check it.

**Comment by alireza-sharifpour** [comment]
I tested it with both main branch and development.
The problem has fixed on development branch.
But because today the staging backend has problem I created a test environment with Main branch's api with development code, so you can test it again!
You can test it here:
**Don't forget it's Main branch's APIs, so be careful!** @divine-comedian 

https://giveth-dapps-v2-git-production-test-givethio.vercel.app/donate/cryptoconexioncom

**Comment by divine-comedian** [comment]
> I tested it with both main branch and development. The problem has fixed on development branch and with next release it will also fix on production. But because today the staging backend has problem I created a test environment with Main branch's api with development code, so you can test it again! You can test it here: **Don't forget it's Main branch's APIs, so be careful!** @divine-comedian
> 
> https://giveth-dapps-v2-git-production-test-givethio.vercel.app/donate/cryptoconexioncom

Thanks! @maryjaf  - can you give this a test?

**Comment by maryjaf** [comment]
Yes, I'll test
But I think this issue has already been resolved on STG because during the testing one issue on stg, I've brought up this icon mismatch
