### ISSUE TITLE
Show token balances in drop down token list

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3002]
We should update the token list drop down menu on the donate page for a project
- Users click the drop down menu and now it opens a full modal for them to choose from a list of eligible tokens 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/bf1c7d9a-2076-46b9-82f8-3fa7cd2ed7ad)

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/13c0891b-2f30-4d62-84e9-d9cbf62a16a3)

## Feature checklist 
- [x] - We show them their token balances right inside the modal 
- [x] - we will need to query their balances for many tokens 
- [ ] - the list should then be sorted to show the highest balances at the top of the list 
- [ ] - users can click a toggle that hides tokens with zero balances 
- [ ] - users see a small logo on top of the token icons that signifies that the given token is givbacks eligible
- [ ] - message at the bottom to inform users that GIVbacks logo means that the token is GIVbacks eligible
- [ ] show states for when token is unselected, highlighted & selected 

## Figma 
https://www.figma.com/file/d3ciTS36toS9mra0RAPMe2/Giveth-Design-System-v0.1?type=design&node-id=5189-12966&mode=design&t=a8nAqx77zJyXDFLx-4

## Current flow for handling custom tokens 

https://github.com/Giveth/giveth-dapps-v2/assets/67759413/d15bc8a7-ee5a-483d-b5e6-957ec2bcfb4c

**Comment by divine-comedian** [comment]
@Tosinolawale - want to take a look at this one?

**Comment by mosaeedi** [comment]
We added the token balance and also made some other improvements!

<img width="343" alt="Screenshot 2023-10-18 at 7 06 09 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/b8a9ee63-c622-4b83-a07e-76688b6a8c20">

We are redesigning the whole donation page by adding the recurring donation. This new modal is totally aligned with the new design, which is coming soon!

### Design asset

[Link to Figma](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=4604-82682&mode=design&t=sKh5J0E57E7OVi2l-4)

**Comment by mosaeedi** [comment]
@divine-comedian Design is done. Please take a look and let me know WDYT!

**Comment by divine-comedian** [comment]
Thanks @mosaeedi - just left a few comments - otherwise lookin' good!

**Comment by mosaeedi** [comment]
Thanks @divine-comedian .
I've shared my comments as well.
If we are all okay, we can hand it over to the devs.

**Comment by mosaeedi** [comment]
Sorry, it was moved to another file.

[New Figma link](https://www.figma.com/file/d3ciTS36toS9mra0RAPMe2/Giveth-Design-System-v0.1?type=design&node-id=5189-12966&mode=design&t=a8nAqx77zJyXDFLx-4)

**Comment by RamRamez** [comment]
@MohammadPCh has already developed this in "superfluid-develop-branch".
I think we can close this issue.

**Comment by divine-comedian** [comment]
> @MohammadPCh has already developed this in "superfluid-develop-branch". I think we can close this issue.
@RamRamez 

Do we fetch all the balances in that branch or just the 5 tokens that are superfluid eligible? 

Is there anything else we need to build to accommodate using this modal for single donations?

**Comment by MoeNick** [comment]
I added superfluid epic to this one not to miss it, pls check the assignees are correct and it's planned as well
Also if possible put priority tags

cc: @jainkrati @divine-comedian

**Comment by MoeNick** [comment]
I guess it's p2, I put the priority and I unassigned @RamRamez for now, until we start working on that

**Comment by divine-comedian** [comment]
Looks like it is added on the recurring donation modal but not on the one-time donation modal - we should make sure they are consistent. @MoeNick can we put this one back on our radar?


https://github.com/Giveth/giveth-dapps-v2/assets/67759413/d3d57896-ac4d-4f98-a8b7-84734766686d

**Comment by MoeNick** [comment]
Sure 
@jainkrati Would you please assign it back to devs? It's still p2.

**Comment by jainkrati** [comment]
@MohammadPCh pls take this up and move to QA if already fixed

**Comment by MohammadPCh** [comment]
Hey @divine-comedian, do we still support using custom tokens?

**Comment by MohammadPCh** [comment]
@divine-comedian how about showing gemini modal for donating GIV to givingBlock projects? do we need it or we can remove them?

**Comment by divine-comedian** [comment]
> @divine-comedian how about showing gemini modal for donating GIV to givingBlock projects? do we need it or we can remove them?

Soon we will remove giving block projects to be replaced with endaoment projects, so not worth the effort at this point 

> Hey @divine-comedian, do we still support using custom tokens?

I don't think we figured out custom token support https://github.com/Giveth/impact-graph/issues/1226#issuecomment-2156805348
but for now we don't need to handle showing balances of custom tokens in the drop down token list

**Comment by MohammadPCh** [comment]
Thanks @divine-comedian 
so I don't implement it since we need the UI to support custom tokens on the select token modal.

**Comment by MohammadPCh** [comment]
@divine-comedian @maryjaf I fetch the balance of only the visible tokens to reduce the number of requests. Since we have around 140 tokens on mainnet, sending 140 requests might block the user or hit the rate limit. This optimization might limit our ability to sort tokens by balance or indicate if the user has no balance in any token.

**Comment by divine-comedian** [comment]
> @divine-comedian @maryjaf I fetch the balance of only the visible tokens to reduce the number of requests. Since we have around 140 tokens on mainnet, sending 140 requests might block the user or hit the rate limit. This optimization might limit our ability to sort tokens by balance or indicate if the user has no balance in any token.

hmmm.... do we know how other DEXes might handle this feature? Sorting by balance is a very nice feature to have for this. 

Also related - looks like when I am staging and have not selected a token yet there is an available balance that is shown... 

if I haven't selected a token yet how come it shows a token balance! it looks by default to check the balance of the native token. I would be okay if the native token is always selected by default on page load in the drop down menu, but is that the intention? 
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/5aa40758-6969-470d-91cb-6b58165ea6ae)

**Comment by maryjaf** [comment]
I see this changes are on staging env but the status of this issue is "inprogress"
Is it ready for testing or not ?
Since we have a release in upcoming days if this issue isn't ready it should be reverted

**Comment by divine-comedian** [comment]
@kkatusic - If you're able to jump in here I will clarify what we need for the release: 

fix bug related to showing native token balance when no token is selected. 

let's leave out the sorting token balance requirements and work on it after the new version release.

**Comment by kkatusic** [comment]
@divine-comedian, I fixed that, please check it [here](https://giveth-dapps-v2-git-resolvebalancesorting-givethio.vercel.app/)

**Comment by divine-comedian** [comment]
@maryjaf  - can you please test this one

**Comment by lovelgeorge99** [comment]
@divine-comedian i fixed the sorting based on highest balance here https://github.com/Giveth/giveth-dapps-v2/pull/4416
can you please check

**Comment by maryjaf** [comment]
Since this issue needs to be tested before release and I'm working on the qf issue now, it would be great if @LatifatAbdullahi  has a chance to look into this issue, wdyt? @divine-comedian

**Comment by LatifatAbdullahi** [comment]
@divine-comedian 

 - We show them their token balances right inside the modal - Pass
 - We will need to query their balances for many tokens - **Pass**
 - The list should then be sorted to show the highest balances at the top of the list  - **Fail**
 - Users can click a toggle that hides tokens with zero balances - **Pass**
 - Users see a small logo on top of the token icons that signifies that the given token is Givbacks eligible - **Pass**
 - Message at the bottom to inform users that GIVbacks logo means that the token is GIVbacks eligible - **Pass**
 
- Show states for when token is unselected - Pass
- Show states for when token is highlighted - Pass
- Show states for when token is selected - Pass



 - The list should then be sorted to show the highest balances at the top of the list  - **Fail**
 
 
![0](https://github.com/user-attachments/assets/74782377-b0f7-4bf7-af7a-1d1e4b8ca5e3)


![image](https://github.com/user-attachments/assets/5575cbe0-53e7-4b80-925b-2bf897ff11d9)

**Comment by kkatusic** [comment]
@LatifatAbdullahi, cc @divine-comedian, please check balance sorting on this PR: [here](https://giveth-dapps-v2-git-sorttokenbalance4415-givethio.vercel.app/)

**Comment by LatifatAbdullahi** [comment]
@divine-comedian @kkatusic 

**Test Update**

The list should then be sorted to show the highest balances at the top of the list - **Pass**



![image](https://github.com/user-attachments/assets/83bdc1e6-255c-4255-8997-3e214f451074)


![image](https://github.com/user-attachments/assets/4bcc5942-a7c2-4945-9dfa-5f979f3465d2)

**Comment by kkatusic** [comment]
@LatifatAbdullahi please when you get time can you test this issue task:

- [ ] Users can click a toggle that hides tokens with zero balances

Link for vercel temp link is [here](https://giveth-dapps-v2-git-resolvebalancesorting-givethio.vercel.app/)

**Comment by LatifatAbdullahi** [comment]
@kkatusic 
Test Update

 Users can click a toggle that hides tokens with zero balances - Test Pass


Before Clicking the check box

![image](https://github.com/user-attachments/assets/686c1fc3-e313-427f-9da4-29c60fa3872b)


After clicking the check box

![image](https://github.com/user-attachments/assets/d27b793c-602f-4d32-a05c-c094b1ee3e2c)

**Comment by kkatusic** [comment]
@LatifatAbdullahi just to notice here, @MohammadPCh resolved this issue, me and @lovelgeorge99 just fix 2 twings.

But thanks @LatifatAbdullahi to testing all options ;)

**Comment by LatifatAbdullahi** [comment]
Alright, noted, thanks

**Comment by divine-comedian** [comment]
@kkatusic - we need to make sure we are testing this on staging and not on feature branches - can you please confirm when this is on staging so it can be tested properly.

**Comment by kkatusic** [comment]
> @kkatusic - we need to make sure we are testing this on staging and not on feature branches - can you please confirm when this is on staging so it can be tested properly.

sorry @divine-comedian , I thought this is some fast fix for this to be published on Friday, that's why I ask @LatifatAbdullahi to test on feature branch. And also when I close or someone else close pull request this issue automatically, that's why we left it on feature branch.

**Comment by kkatusic** [comment]
@LatifatAbdullahi these two fix, about balance order and 0 balance have been merged to staging, when you get time please test, thx.

**Comment by LatifatAbdullahi** [comment]
@kkatusic @divine-comedian 

Test Update on Staging - **Pass**

Sorting tokens from highest in quantity to lowest - **Pass**

**Before checking the box to hide tokens with zero balance**

![image](https://github.com/user-attachments/assets/2ac371cf-37d2-494f-8233-72effa779810)


**After checking the box to hide tokens with zero balance**

![image](https://github.com/user-attachments/assets/a7d8187f-ba88-47db-b3ca-e99993f9bf4b)
