### ISSUE TITLE
Drop down menu for actions on my projects 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3003]
This actions column is getting a bit unruly in the `My Projects` - can we convert it into a drop down menu on hover? 

![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/d4d93319-6711-4a37-a873-f553c49e050a)

Ideally by default it says `Select ⌄` - when user hovers it expands downward and gives these options in this order:

View 
Add Update
Edit 
Manage Addresses

**Comment by mosaeedi** [comment]
Link to Figma -> [Here](https://www.figma.com/file/vMiyVd1Ly5LjgSyZrChVV8/Giveth-users?type=design&node-id=165-109353&mode=design&t=iBWRRTTuPkKnAZQ4-4)

<img width="621" alt="Screenshot 2023-08-08 at 10 07 00 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/4abbaa0f-957d-43cb-9314-feb7ef22dadb">


<img width="634" alt="Screenshot 2023-08-08 at 10 08 17 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/c05da623-c55d-4c18-9cd7-178531831792">


<img width="473" alt="Screenshot 2023-08-08 at 10 08 42 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/420e389c-dde7-4814-a50f-cebedb612a86">

**Comment by mosaeedi** [comment]
Also, I was working on this before to let user Archive their project or delete the archived projects from the actions dropdown.
I don't know if we can also include that!
@divine-comedian 

<img width="761" alt="Screenshot 2023-08-08 at 10 10 04 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/7b0555b3-3510-4ebc-9108-89e7e2f8f112">

**Comment by divine-comedian** [comment]
> Also, I was working on this before to let user Archive their project or delete the archived projects from the actions dropdown. I don't know if we can also include that! @divine-comedian
> 
> <img alt="Screenshot 2023-08-08 at 10 10 04 PM" width="761" src="https://user-images.githubusercontent.com/13708322/259196791-7b0555b3-3510-4ebc-9108-89e7e2f8f112.png">

I think this implies some back-end work as well - let's add it in later 

@CarlosQ96  
Could you explain what happens in the DB when a user would archive a project? Also what happens if they delete a project? Is that even possible?

**Comment by divine-comedian** [comment]
> Link to Figma -> [Here](https://www.figma.com/file/vMiyVd1Ly5LjgSyZrChVV8/Giveth-users?type=design&node-id=165-109353&mode=design&t=iBWRRTTuPkKnAZQ4-4)
> 
> <img alt="Screenshot 2023-08-08 at 10 07 00 PM" width="621" src="https://user-images.githubusercontent.com/13708322/259196091-4abbaa0f-957d-43cb-9314-feb7ef22dadb.png"> <img alt="Screenshot 2023-08-08 at 10 08 17 PM" width="634" src="https://user-images.githubusercontent.com/13708322/259196374-c05da623-c55d-4c18-9cd7-178531831792.png"> <img alt="Screenshot 2023-08-08 at 10 08 42 PM" width="473" src="https://user-images.githubusercontent.com/13708322/259196474-420e389c-dde7-4814-a50f-cebedb612a86.png">

@RamRamez 
You wanna check this one out too? You've been firing 'em off pretty fast ;)

**Comment by RamRamez** [comment]
@mosaeedi @divine-comedian If a project a cancelled, all actions will be disabled. What is the design in this case? Will the dropdown open with disabled items? or won't open at all?

**Comment by divine-comedian** [comment]
> @mosaeedi @divine-comedian If a project a cancelled, all actions will be disabled. What is the design in this case? Will the dropdown open with disabled items? or won't open at all?

@RamRamez  - let's build the first menu - not including the options for archive or delete. 

### This one to be specific :point_down: 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/4ed940ee-835b-4b78-9075-3ec97c6ccc89)

**Comment by divine-comedian** [comment]
> @divine-comedian I'm not talking about the delete or archiving a project. Now, when a project is cancelled by admin bro, we disable all action buttons for that project (as in below pic).
> 
> What's the design for this case? open drop down with disabled items? or disable the dropdown itself?
> 
> ![image](https://user-images.githubusercontent.com/73441857/259431564-65653838-dc17-499c-af48-e72de09a6ea7.png)

Ah got it, my bad. Let's gray out the text and remove the "⌄" when the project has been cancelled

**Comment by MohammadPCh** [comment]
@maryjaf It's on staging and ready to test.

**Comment by maryjaf** [comment]
Thanks @RamRamez @MohammadPCh 
For activate/ deactivate and draft project the new design is like below pic and all of actions work correctly

<img width="1312" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/723479aa-076f-4aae-a255-c674cdf1af74">

For cancelled project:

<img width="1309" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/53ffa40d-d36e-44ad-b424-d6ff1eb969fd">

Now name of cancelled project is also clickable, should this be changed? @divine-comedian 
<img width="1431" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/6fd0bcb8-aea6-45b1-bc24-9d996c2d4e6f">

**Comment by RamRamez** [comment]
> Thanks @RamRamez @MohammadPCh For activate/ deactivate and draft project the new design is like below pic and all of actions work correctly
> 
> <img alt="image" width="1312" src="https://user-images.githubusercontent.com/111529185/260698869-723479aa-076f-4aae-a255-c674cdf1af74.png">
> For cancelled project: <img alt="image" width="1309" src="https://user-images.githubusercontent.com/111529185/260698984-53ffa40d-d36e-44ad-b424-d6ff1eb969fd.png">
> 
> Now name of cancelled project is also clickable, should this be changed? @divine-comedian
> 
> <img alt="image" width="1431" src="https://user-images.githubusercontent.com/111529185/260700477-6fd0bcb8-aea6-45b1-bc24-9d996c2d4e6f.png">

Thanks @maryjaf. I fixed it.

**Comment by divine-comedian** [comment]
Looks great! Excellent work Ramin
