### ISSUE TITLE
Project Title in my projects should be clickable link

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3004]
On the my projects page the title of the project should be a clickable link that goes to the single project page. 

I keep wanting to click it and it doesn't do anything, this could be a small intuitive update. 

![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/b37a6516-86b0-4d17-843a-b0ddba85b1fc)

Can you take it @RamRamez ?

**Comment by RamRamez** [comment]
> It seems it didn't merge on stg @RamRamez

Staging backend was down and all deploys were failed. Backend is live now, I redeployed the staging frontend, and you can test it now.
