### ISSUE TITLE
Remove Gnosis Safe option from Sign in modal

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3007]
AFAIK this feature does not work at all - we need to remove this panel from the modal until Gnosis Safes actually work on the dapp.

![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/eae80c84-0cfe-4ac7-99b2-858ed3d137a9)

**Comment by divine-comedian** [comment]
@RamRamez can we make this happen?

**Comment by RamRamez** [comment]
> @RamRamez can we make this happen?

Done!

**Comment by divine-comedian** [comment]
> > @RamRamez can we make this happen?
> 
> Done!

Thanks man! Did you merge it directly to staging or where? Where can it be tested?

**Comment by RamRamez** [comment]
@divine-comedian Yes, it's merged on staging but can't be tested now, because staging backend is down.

**Comment by RamRamez** [comment]
@divine-comedian It's live on staging now.

**Comment by maryjaf** [comment]
Thanks @RamRamez 

![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/62d38428-e185-415f-bcbf-695d3687e304)
