### ISSUE TITLE
Increase visibility of language icon

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3008]
The translations feature is kind of buried and hard to find if I want to change the language of the dapp. Currently it is at the bottom of the page so most users might not know it even exists! 

We should consider adding the small globe symbol which toggle the language list modal to somewhere on either the navbar or fixed to the screen on the homepage view. 

![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/bc3f9e27-54bc-4651-ac98-69d1f6c9a111)

Or on mobile view we can add it to the burger menu of options or in the bottom of the screen 

![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/51463fc0-fa81-4cd3-82cd-f7e519824a77)

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/e3b2bde4-00c1-45ba-b12d-77af03a39ed9)

Whatever we choose there certainly needs to be an improvement, I doubt most users will find the language button if it remains only in the footer of the website.

**Comment by mosaeedi** [comment]
I think we can have better options that adding another elements to the super crowded header.

**Another alternative** would be show the language modal based on user IP address or browser language settings!
If it's anything other than English or an English spoken country(IP) and also if we have the Giveth on that specific language, we can present the language modal to user!
But this should happen just once! not every time user check Giveth.

Also, checking the well known platform such as, Kickstarter, Indiegogo, Gofundme, they all have much cleaner headers but you can see they all have this language option just on their footer! 

The header on Giveth has too many options for user and putting the language option there, can only create more distraction for user.

**Comment by divine-comedian** [comment]
> I think we can have better options that adding another elements to the super crowded header.
> 
> **Another alternative** would be show the language modal based on user IP address or browser language settings! If it's anything other than English or an English spoken country(IP) and also if we have the Giveth on that specific language, we can present the language modal to user! But this should happen just once! not every time user check Giveth.
> 
> Also, checking the well known platform such as, Kickstarter, Indiegogo, Gofundme, they all have much cleaner headers but you can see they all have this language option just on their footer!
> 
> The header on Giveth has too many options for user and putting the language option there, can only create more distraction for user.

Got it, that's also a very interesting option
