### ISSUE TITLE
Deploy Token Distro on Optimism

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3019]
@divine-comedian @aminlatifi 

Can we get this set up in the next few days so we can test GIVbacks on Optimism on production?

**Comment by divine-comedian** [comment]
TokenDistro deployed to mainnet 
https://optimistic.etherscan.io/address/0xe3ac7b3e6b4065f4765d76fdc215606483bf3bd1

subgraph has to be deployed - need to work with @aminlatifi to get that working 

we'll need to fill it with some GIV and test it out to be triple sure it works well

**Comment by mateodaza** [comment]
@divine-comedian [PR is here](https://github.com/Giveth/giveconomy-subgraph/pull/62)  for the deployment

**Comment by divine-comedian** [comment]
@MohammadPCh - do you have what you need to hook this up to production optimism for testing?

**Comment by MohammadPCh** [comment]
@mateodaza @divine-comedian  Thanks,
Do we have a Notion for production configs?

**Comment by aminlatifi** [comment]
> TokenDistro deployed to mainnet https://optimistic.etherscan.io/address/0xe3ac7b3e6b4065f4765d76fdc215606483bf3bd1
> 
> subgraph has to be deployed - need to work with @aminlatifi to get that working
> 
> we'll need to fill it with some GIV and test it out to be triple sure it works well

@divine-comedian The deployed contract is not verified. We must stop proceeding on any other action on top of this contract till we verify it. If we won't be able to verify it, we must deploy another one.

**Comment by divine-comedian** [comment]
Configs of what specifically? If you need contract addresses they are kept here:

https://www.notion.so/giveth/Deployment-52935e6579034f1b940bbef161e82229
