### ISSUE TITLE
Total amount received is wrong in public user view

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#3021]
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/479842e0-d812-4134-be53-172baba48800)

**Comment by MoeNick** [comment]
@alireza-sharifpour can you take a look I tik you have the query for this from bakend.

**Comment by alireza-sharifpour** [comment]
It seems like this is a backend problem, i checked it and for totalReceived amount we get 0.
<img width="670" alt="Screenshot 2023-08-17 at 11 25 23 AM" src="https://github.com/Giveth/giveth-dapps-v2/assets/48887817/2990c059-f79e-4f93-beb3-c4e03c2bdd50">
The totalReceived amount here is 0 in the project @MoeNick mentioned.
Can you check it @mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
@maryjaf  It's on staging, you can test it now.
After you donate to a project the total received amount for the project owner would update successfully

**Comment by maryjaf** [comment]
Thanks, I checked and after donation this filed be updated correctly
