### ISSUE TITLE
Fixing Donate Button on iPhone 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3025]
The scroll & drag functionatlity of the donate button on iPhone 

Cherik says it doesn't work trying to fix it

Old design for user project page 

@mosaeedi  worked on a fix here:
https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=4054-112467&mode=design&t=xjtf7LQnI6q0d3od-4

@MoeNick 
You can add more details if you need 

Add actions button 
Owner view the donate button becomes edit

**Comment by divine-comedian** [comment]
@mosaeedi 

Is this issue fixed? What is the status?

**Comment by MoeNick** [comment]
We still need owner's view, the public view is fixed and merged on production

**Comment by mosaeedi** [comment]
The owner view -> [Link to Figma](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=4193-71776&mode=design&t=6EACO8oRlyiscdYj-4)

**Comment by divine-comedian** [comment]
Related to #3055

**Comment by divine-comedian** [comment]
@MoeNick do we have enough to carry this issue forward?

**Comment by MoeNick** [comment]
Let's move on with this issue https://github.com/Giveth/giveth-dapps-v2/issues/3055
I will close this one.
