### ISSUE TITLE
Donation tab for new project or a project without donation

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3026]
**Describe the bug**
ُIt  seems the view of donation tab for new project or a project without donation isn't good 

**To Reproduce**
1. Go to 'https://staging.giveth.io/project/testtttt'
2. Click on 'Donation' tab
4. See the page

**Expected behavior**
We need a better design for that 

**Screenshots**
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/6f95f81e-eba4-4395-9383-45dd412a9836)

cc: @divine-comedian

**Comment by divine-comedian** [comment]
@mosaeedi  

Is this a bug? What should the default design look like when there is no donations?

**Comment by mosaeedi** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdFFyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ba2716f5dd96daa7cb57fc9e5d3ac9bd711457b5/Screenshot%202023-08-23%20at%2011.29.45%20AM.png)

## Design Assets

**Exported asset** -> [GIV background.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdFVyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3a11fe124c4432dd48e4ec712c95b6c34e16cf4a/GIV%20background.zip)

[Link to Figma](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=4185-62406&mode=design&t=VxidVA8xCRYfthTC-4)

**Comment by mosaeedi** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdWdyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b3550c1e668567e1a299c530b09d592557957c04/Screenshot%202023-08-23%20at%2011.42.32%20AM.png)

When there is no donations, please remove this line.

**Comment by divine-comedian** [comment]
@mosaeedi 

Unfortunately we need to improve this banner,

First it doesn't make sense, if the project isn't verified they won't get rewarded. Also can we avoid that blue? I know it's in the design guide but I'm really not a fan.

Maybe we can move the text on the right "BE THE FIRST TO DONATE!" into this space instead? the messaging is more applicable. 

I agree with the rest of your points.

**Comment by mosaeedi** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbzZnIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--88e3c1e2d78e3e259d76340d0801275a6829997c/Screenshot%202023-09-14%20at%2010.13.02%20PM.png)

WDYT now?

**Comment by mosaeedi** [comment]
@divine-comedian

**Comment by divine-comedian** [comment]
Looks great! 

For the devs:
https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=4185-62406&mode=design&t=VxidVA8xCRYfthTC-4

- [ ] check on project single page if project has received no donations
- [ ] show design where donation table would normally be 
- [ ] button below that leads to donate page for given project

**Comment by maryjaf** [comment]
What is should be shown for a closed round ? @mosaeedi @alireza-sharifpour 
QF round sub tab for Project that hasn't any donation:
[ Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcy95IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b285916933e661821a6dc422b232133e4526fb94/image.png)

**Donate button is shown for a closed round and it should be changed** 

QF round sub tab for Project that has donation:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdER5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--837cc2f166b1a7d63d9b43c31c83c9f73fd2b7db/image.png)

**Comment by maryjaf** [comment]
In this scenario : the all donation tab has a record , but in the open round sub tab  there is no donation 
the below pic is shown 
https://staging.giveth.io/project/testremove?tab=donations
[ Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdEh5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9b1a54defcebdf5995f44dd28e478e50df2954fa/image.png)

Maybe it's better  the "be the first to donate" copy and donate button be shown in this sub tab

**Comment by MohammadPCh** [comment]
@maryjaf Can you test it again?

**Comment by maryjaf** [comment]
> What should be shown for a closed round sub tab ? @mosaeedi @alireza-sharifpour


This problem has been resolved and the donate button isn't shown for closed rounds.

**Comment by mosaeedi** [comment]
**"Be the first to donate"** message, and the donate button should only appear on **all donation tabs** when **there isn't any donation.**

We should have a more related copy for **open Qf round tabs** without any donation, but still, we can show the donate button.

For **closed QF round tabs**, we need another copy to tell the user there is no QF donation.

@divine-comedian, what do you think? If you agree, can you provide a copy for these two states?

**Comment by laurenluz** [comment]
Well for these cases, we already added some copy in the donation box... if we put copy instead in that white space, I think we'll need to make changes there... maybe we can just put "$0" in the donation box for both cases and then:

**For Open QF round tabs without any donation**: In the white space, we can say "Be the first to donate this round!"
**For closed QF round tabs with no donations**: In the white space, can say "There were no donations in this round."

Is that clear @mosaeedi ? can you make a design image that shows both.. .the copy in the white space & the $0 in the donations box?

**Comment by maryjaf** [comment]
Thanks @MohammadPCh
