### ISSUE TITLE
Remove credit card option from donate page

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3031]
These radio buttons and option for credit card has been up on the dapp for almost 3 years now I think... But we've never had this feature and I don't think we are actually going to build it. 

We need to remove this line entirely and not have a switch for credit card or cryptocurrency and adjust the card accordingly 

@Tosinolawale  can you draft this quickly? 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaDRDIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8245220e14439ed325db31d4e333d81a31e2d73d/image.png)

**Comment by Tosinolawale** [comment]
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/GIVeconomy?type=design&node-id=14141%3A253144&mode=design&t=oNljqsCjyZRKKo55-1
@divine-comedian on this end, we changed the design to reflect that Months ago. Check out the Figma link

**Comment by divine-comedian** [comment]
Thanks! @RamRamez  can you take it?

**Comment by Vyvy-vi** [comment]
Can I take this issue?

**Comment by MoeNick** [comment]
@maryjaf confiem pls
