### ISSUE TITLE
Improve drop down menu on navbar for projects

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3033]
Small fixes here :

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbWNFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5181155fd1e232a32e65412a8c15655af2b16fed/image.png)

- [x] Capitalization of headings - should be "All Projects", "Recently Updated", "Just Launched" 
- [ ] Remove "Other" from this category section

**Comment by RamRamez** [comment]
@divine-comedian I fixed the first item.
About the second item:
category list is coming from backend, and we don't have "other" category in production.
If you want to remove "other" from staging only, I can ask backend guys to remove it.

**Comment by divine-comedian** [comment]
> @divine-comedian I fixed the first item. About the second item: category list is coming from backend, and we don't have "other" category in production. If you want to remove "other" from staging only, I can ask backend guys to remove it.

Oh okay! No problem then - we can leave it as is.

**Comment by MoeNick** [comment]
@maryjaf you can confirm
