### ISSUE TITLE
QF - When the round is over, but matching funds have not yet been send, we should show "pending" on the donation tab

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3035]
Right now, the alpha round funds have not yet been sent... so this should not show a matching amount... it should show "pending"

On production:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa2tHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4114e1f81174e4d39453dcd1d18da4367c62b113/image.png)

What I want:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa29HIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1a4252670d967159af43123403be541c92c02c78/image.png)

@mosaeedi can you let me know if you're ok with the "pending..." thing I did in figma? if so, we can pass to the devs.

**Comment by mosaeedi** [comment]
@laurenluz WDYT about the copy?

[Link to Figma](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=4119-19247&mode=design&t=779HUnPv9ppR6gCW-4)

**Comment by laurenluz** [comment]
I made a small change! Let's implement it like this:

Note @alireza-sharifpour - The text "Alpha Round" here is an example... it should change based on the round, i.e. this should actually be < QF round name > 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/45a3f199-2167-49f4-b978-6eedb90069a9)

**Comment by maryjaf** [comment]
‌Based on issue's description I think this new design is for round that it is ended 
But now I see the below pic for optimism round that it will be ended in 30 days later 
plz check this @alireza-sharifpour 
<img width="1440" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/1c316eae-53ca-47e5-9b04-ece8c40e8713">

**Comment by laurenluz** [comment]
yep! @alireza-sharifpour - if the round "is Open/ Active" - here we should show the estimated matching funds (as before).

the only time we show this "pending" design is when the round "is Closed" and the matching funds have not been sent yet/manually inputted into our backend.

cc @MohammadPCh

**Comment by alireza-sharifpour** [comment]
Since we require this feature before merging Wagmi, I've transferred the relevant commits to the 'develop' branch. It's now ready for testing on staging. @maryjaf @laurenluz

**Comment by maryjaf** [comment]
It seems we had a problem 
for example the right status of  QF-Test round's donation is **matching funds** (pic 2) but it is shown Matching funds coming soon... on stg(pic1)
this new status should be shown only for rounds that it has been ended and the funds haven't distributed yet 
<img width="1384" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/ed09d5e4-ecaf-403e-adfc-18ef059337ff">

<img width="1384" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/ed09d5e4-ecaf-403e-adfc-18ef059337ff">

**Comment by maryjaf** [comment]
I'v checked again, all status : estimated matching, coming soon and matching funds are shown correctly
