### ISSUE TITLE
Change Bridging GIV link on Optimism 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3043]
Hey! I noticed that we still use the omnichain link for bridging GIV while connected to Optimism. However omnichain bridge only works for mainnet <> gnosis chain. 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/d68c8778-ead5-45bf-ae7c-2e7db9cbf5f8)

We should use this link instead:

https://jumper.exchange/?fromChain=100&toChain=10

**Comment by MoeNick** [comment]
@maryjaf to be in the loop and test

**Comment by divine-comedian** [comment]
@mateodaza  - I think you pushed this to production in the HOTFIX correct?
