### ISSUE TITLE
Preview on shared links is generic - it should actually show the unique project!

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#305]
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/c980fa1f-0b5f-4f45-9020-f021640859d9)

https://twitter.com/cheo0202c/status/1505669192703479809

This is super important for sharing on social media... we need to have the preview thing show unique content... else it's not appealing to the user to click.

**Comment by laurenluz** [comment]
@mateodaza @RamRamez @MoeNick any chance we can try to get this issue fixed before we announce the DApp?

It looks pretty bad on twitter when people are sharing projects just to see that dark giveth thing... you can't even see the project.

**Comment by RamRamez** [comment]
@laurenluz Do we have any design or any ideas for the preview thing?

**Comment by laurenluz** [comment]
previously, when the user shared a link to a project, the preview showed the project's header image. The text showed "Check out <this project> on Giveth". It was like this:

![image](https://user-images.githubusercontent.com/75490971/159369210-583d0ad8-b468-42aa-b875-0d1c7241c7be.png)
https://twitter.com/Givethio/status/1491411743742267392

Scrolling back, it seems like some shares are now also showing this black Giveth image instead 🤔

**Comment by RamRamez** [comment]
Resolved in PR #315 

The `Meta` were not set for dapp pages and they were using giveconomy meta tags.
I changed it, so now single project view will look like this:
![image](https://user-images.githubusercontent.com/73441857/159391559-0c6eaed4-7429-41f1-920e-2b1101de56ea.png)

And donate page:
![image](https://user-images.githubusercontent.com/73441857/159391621-3a80e2ea-03e7-475b-aaf6-933c232d6a1a.png)

@laurenluz we usually set three types of metas, title, description and image, you can check the metas for other pages like giveconomy. Specifically send me the three metas for the homepage to set.

**Comment by laurenluz** [comment]
This is awesome Ramin! Thanks!

Do you think we should really set metas for each of the GIVeconomy pages? ie. GIVfarm, GIVgarden, GIVbacks, GIVstream

**Comment by RamRamez** [comment]
I've set for GIVeconomy pages before. I think we need good title, description and image for homepage preview.
