### ISSUE TITLE
Create an "all articles" page for SEO

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-dapps-v2#3052]
We need to create a page that collects all of the landing pages we created for SEO and add it to the footer of the website.  It's important for SEO to have the new landing pages we create be linkable from the homepage (or at least a few clicks away), so I suggest having a footer link that takes users to a category page, then from there they can view each of these landing pages we're creating. 

For example, all of the new landing pages:

1. https://giveth.io/landings/refi
2. https://giveth.io/landings/web3-crypto-donation-platform 
And all the new ones we're making. 

I suggest we have a simple page (like a blog category page) with links to each of the articles, and we'll include a link in the footer of the website. 

Let me know what you think @MoeNick @mosaeedi

**Comment by MoeNick** [comment]
tagging @divine-comedian to be also in the loop.

**Comment by mosaeedi** [comment]
## Design asset

[Link to Figma](https://www.figma.com/file/hNqwpebu4JCy1XIed2c862/Giveth-Public?type=design&node-id=1017-18443&mode=design&t=VPdKxGMNnbEx4Vve-4)

**Comment by MoeNick** [comment]
@divine-comedian fyi
shall we implement it regardless of AdminJS feature.

**Comment by divine-comedian** [comment]
I think we still need it to be accessible from our homepage somewhere - regardless of how we build this adminJS feature. 

As long as we have a banner image, title and text to use for preview it should fit into this design.

**Comment by divine-comedian** [comment]
Let's hold off on this issue - if we go with using blog.giveth.io we might not need to do anything else..
