### ISSUE TITLE
Wallet Connect & Mobile experience

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3053]
We should fix some of the ways we currently let users connect to our dapp - first is by reviving our Wallet Connect integration and improving how users can connect to our dapp on mobile and with wallets that do not have a browser extension. 

## LOOK AT THIS UX, JUST LOOK AT IT!! 

https://github.com/Giveth/giveth-dapps-v2/assets/67759413/1e40842e-97db-49f9-8380-c24ddd83e752

- The user does not have to use a wallet browser like metamask (horrible web browser feature) and can browse from their favourite mobile browser
- wallet connect handles generating message signatures and tx generation on the source web wallet - user can browse from any regular mobile browser and near seamlessly integrate with their preferred mobile crypto wallet (this is rainbow wallet in the video for example)
- we should disable any types of wallets we're not ready to handle (mostly just multisigs)

What do we need to do to achieve this? I believe this is the SDK package we're looking for 
https://docs.walletconnect.com/2.0/web3modal/about

I understand this would require some big package changes like using wagmi and viem but perhaps this is the future! 

WDYT @MoeNick - This could be a good project for @alireza-sharifpour

**Comment by MoeNick** [comment]
Thank YOU @divine-comedian 
yeah, It was working fine with wallet connect before! now I mentioned we removed it! what happened! :))

**Comment by divine-comedian** [comment]
Nice! 

Then can we go ahead and research what we need to add in Wallet Connect - AFAIK we need a project key from wallet connect and add in some options for connecting to the dapp using `wagmi` - which will require `viem` which is a sort of replacement for ethersJS. 

@alireza-sharifpour can you start looking into this? This will be a good project for you I think to focus on.

**Comment by alireza-sharifpour** [comment]
Yes, sound like a good idea, i'll work on it, as you know, we need to change about almost 80-90 percent of our files. @divine-comedian

**Comment by MohammadPCh** [comment]
@alireza-sharifpour @divine-comedian thanks :)
yeah I saw that the wallet connect V2 is supported by wagmi.
and also it's trend:
![image](https://github.com/Giveth/giveth-dapps-v2/assets/17097576/57a71b13-eab7-4eaa-a93c-f5f13cc7d0ad)
I think it's good to work together on it. and take care of all changes.( if we don't have any more important issue )

**Comment by MoeNick** [comment]
And do you want to use Rainbow as well? Is there any need we convert it to an Epic and creat a task list there?

**Comment by MohammadPCh** [comment]
@MoeNick  I think yes :D

**Comment by divine-comedian** [comment]
> And do you want to use Rainbow as well? Is there any need we convert it to an Epic and creat a task list there?

"Rainbow Kit" you mean? That's used more specifically for connecting wallets, correct?

AFAIK however "Rainbow Wallet" is just another wallet app among many that gets support automatically from using the wallet connect web3modal

**Comment by divine-comedian** [comment]
Let's refine the scope more for this project. 


There are three ways to connect to the dapp now with wallet connect:
- Desktop Browser with wallet extension (Chrome/Brave, Safari, Edge)
- Dekstop Browser with Wallet Connect
- Mobile browser with Wallet Connect 

We should also define these web3 actions that are required to work:
- Sign in
- Switch Network (from navbar dropdown menu)
- Switch Network (from givfarm)
- Switch network (from donate page)
- Donate ERC20
- Donate native token
- Stake GIV
- Lock GIV
- Unstake GIV
- Harvest rewards (GIVfarm)
- claim GIVbacks 
- claim GIVstream

Along with factors such as wallet, OS and browser we have this list of combinations to consider for testing:

## 1. Desktop Browser with Wallet Extension
- Chrome/MetaMask
- Safari/MetaMask
- Edge/MetaMask

## 2. Desktop Browser w/ Wallet Connect/web3Modal (to mobile wallet)
### Chrome (desktop)
- Metamask (mobile)
- Trust Wallet
- Coinbase Wallet 

### Safari (desktop)
- Metamask (mobile)
- Trust Wallet
- Coinbase Wallet 

### Edge (desktop)
- Metamask (mobile)
- Trust Wallet
- Coinbase Wallet 

## 3. Mobile Browser with Wallet Connect
### Android
#### Chrome (mobile)
- Metamask (mobile)
- Trust Wallet
- Coinbase Wallet 

## iPhone 
### Safari (mobile)
- Metamask (mobile)
- Trust Wallet
- Coinbase Wallet

**Comment by maryjaf** [comment]
> ## 2. Desktop Browser w/ Wallet Connect/web3Modal (to mobile wallet)
> ### Chrome (desktop)
> * Metamask (mobile)
> * Trust Wallet
> * Coinbase Walle

I couldn't sign in with these, after scanning  QR code and opening Metamask nothing happens

**Comment by maryjaf** [comment]
> ## 1. Desktop Browser with Wallet Extension
> * Chrome/MetaMask

Connect wallet from GIV farm : failed 
https://github.com/Giveth/giveth-dapps-v2/issues/3265#issuecomment-1752784578

stake: failed 
https://github.com/Giveth/giveth-dapps-v2/issues/3265#issuecomment-1754539634
Other scenarios has been passed on Chrome/Metamak

**Comment by maryjaf** [comment]
> ## 1. Desktop Browser with Wallet Extension
> * Safari/MetaMask
> * Edge/MetaMask

* Safari/MetaMask
Safari in't supported and we can ignore it 

* Edge/MetaMask
 plz check the below screen @MohammadPCh 

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/5d7ba7d3-a577-4255-a556-09d896a57da6

**Comment by maryjaf** [comment]
> * Edge/MetaMask
>   I couldn't complete sign in flow plz check the below screen @MohammadPCh

This problem has been resolved
I'll report the result of rest of scenarios on this issue  https://github.com/Giveth/giveth-dapps-v2/issues/3319

**Comment by divine-comedian** [comment]
Because there are too many bugs presented by providing coverage for so many wallets on mobile we have cut scope to only guarantee full functionality on MM ... further wallets will be added in #3346
