### ISSUE TITLE
Project Owner View: iPhone Mobile view issues

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3055]
**3- Owner view**

![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/82d3a782-678c-49ce-926a-dbe5d465c453)

_Originally posted by @maryjaf in https://github.com/Giveth/giveth-dapps-v2/issues/2971#issuecomment-1651068002_

**Comment by divine-comedian** [comment]
@alireza-sharifpour is there any update for this issue? Does it need more design?

**Comment by mosaeedi** [comment]
The main difference on mobile is related to the **Actions button** and the **Boost button**.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdEo2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--136d321c08dd850ff89ae379b66d85556688b6e5/Screenshot%202023-09-07%20at%209.52.03%20PM.png)

The **Project Actions** button is now in the same card with the project details.
When user taps on it, the full-page menu will appear.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdkY2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1830be2cab70dbcf9e08a147144338dc4e850efc/Screenshot%202023-09-07%20at%2010.04.08%20PM.png)


---

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdDE2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d8523a9a98c379ce57e95fac54e881411678dc6f/Screenshot%202023-09-07%20at%209.55.12%20PM.png)

And the Boost button is on the same card as the donations detail,
When user taps on it, a full-page modal will appear to show boost details, and then they can go to the boost modal.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ043IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d6f779f9f43becd83d5243d2a8810a4a681233ca/Screenshot%202023-09-07%20at%2010.20.05%20PM.png)

**Comment by mosaeedi** [comment]
Take a closer look here -> [Link to Figma](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=4267-28694&mode=design&t=3xhevQsSIQ9jf1mo-4)

**Comment by MoeNick** [comment]
@divine-comedian @laurenluz Appreciate it if take a look and approve the design.

**Comment by divine-comedian** [comment]
I think it looks fine - I recognize there is a lot of white space on the screen but perhaps its the simplest solution to not let the user accidentally scroll away or lose the menu when on mobile

**Comment by divine-comedian** [comment]
@alireza-sharifpour so to be clear for the changes - everything in this issue only applies to MOBILE

- [ ] Remove "drawer" scroll up menu from project owner view of project single page
- [ ] add components for plain, scrollable page on mobile  
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/1f99ce04-f11a-4565-9f1e-4f8e01b1d89b)

- [ ] "Project Actions" is now a button which triggers this full mobile screen menu:
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/1dcf60ac-8f2b-4f53-b8c9-629082e7ef73)

- [ ] Clicking the "Boost" button triggers this full mobile screen menu:
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/97bfa3e0-f7a6-4bb5-b1fd-aa60756f0485)

- [ ] Ensure when user clicks any items on new menus that they trigger appropriate components/modals - e.g. "Edit Project", "Boost", "Verify Project" etc...

**Comment by alireza-sharifpour** [comment]
I don't understand what the functionality of this section is?
It seems like it has also added to Desktop view.
Is it something related to this issue?
@divine-comedian 

<img width="286" alt="Screenshot 2023-09-13 at 12 41 32 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/48887817/182cb29c-710e-4deb-b80f-09d1478af704">

**Comment by alireza-sharifpour** [comment]
I think the Boost button should be static like this:

<img width="413" alt="Screenshot 2023-09-13 at 1 44 01 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/48887817/fe2a913e-5ed9-47b9-9fe5-2660126395d2">

in the design it has not included the boost button for non qf projects as it is in QF card.
@divine-comedian

**Comment by maryjaf** [comment]
Plz check below pic related to draft projects  @alireza-sharifpour 
[ Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdW1vIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6a4a269fd3a453aea3dc8f68d0cf5b9ec6463359/image.png)

**Comment by maryjaf** [comment]
Some changes about project actions was made by @divine-comedian on https://github.com/Giveth/giveth-dapps-v2/issues/3081
I think these changes also should be applied on mobile view   @divine-comedian @alireza-sharifpour

**Comment by maryjaf** [comment]
Thanks @alireza-sharifpour both problem has been resolved

**Comment by maryjaf** [comment]
@divine-comedian If you can check it on Samsung, I would appreciate it

**Comment by divine-comedian** [comment]
Tested - looks good on Android! Thanks
