### ISSUE TITLE
Redirect link for Project's update in notification list

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3057]
By tapping project name in project's update notification it's better that the user is redirected  to Update tab.for example:
https://giveth.io/project/evmcrispr-0?tab=updates
Now the user is redirected to :https://giveth.io/project/evmcrispr-0

What do you think? @divine-comedian @MoeNick

**Comment by divine-comedian** [comment]
I like that suggestion!

**Comment by CarlosQ96** [comment]
@divine-comedian  @maryjaf  I merged to staging, can test please.

**Comment by maryjaf** [comment]
> @divine-comedian  @maryjaf I merged to staging, can test please.

Thanks @CarlosQ96 It has been resolved
