### ISSUE TITLE
Project's tab in user link

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3060]
**Describe the bug**
Both projects and donations are displayed in the project tab of user link
https://staging.giveth.io/user/0xf577ae8b97d839b9c0522a620299dc08792c738c?tab=projects
1- Is this ok or should it be changed and according to the title of the tab, only the user's projects should be displayed
2- In the second part, the title is " **MAYA MAYA’s donations & projects"**
But only the user's projects are displayed and the projects that the user have donated are not displayed

**To Reproduce**
1. Go to 'all project'
2. Click on 'project owner of one of projects'
3. Click on project
4. See

**Expected behavior**
I think It's better to show only the project's user based title of tab
What do you think? 

**Screenshots**
<img width="1335" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/0e2ae687-e631-4d61-a1b7-3e1df7efe181">
cc: @divine-comedian @MoeNick @mosaeedi @MohammadPCh

**Comment by divine-comedian** [comment]
Excellent find MJ! I agree - we should make the following changes:

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/6baaefaa-3188-4143-8e9e-fb7fcfffbad8)


- [ ] Change header title to {project owner name}'s Projects
- [ ] Move the "Donations" component to the "Donations" tab" - in the same position at the top
- [ ] Fix text on projects component - should read "DONATIONS RECEIVED"

Who can take it?

**Comment by maryjaf** [comment]
Thanks @MohammadPCh 
The new design of Project's user and donation's user:
[Donation](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdUZQIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ed5d5f29220f8befb37238a09d3ee428733bc351/image.png)

[Projects](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdVJQIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--933964e2f6cfa261a8a452ca462373d92abeeecb/image.png)

**Comment by divine-comedian** [comment]
> Thanks @MohammadPCh The new design of Project's user and donation's user: @divine-comedian [Donation](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdUZQIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ed5d5f29220f8befb37238a09d3ee428733bc351/image.png)
> 
> [Projects](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdVJQIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--933964e2f6cfa261a8a452ca462373d92abeeecb/image.png)

Looks great! I approve.

**Comment by RamRamez** [comment]
> > Thanks @MohammadPCh The new design of Project's user and donation's user: @divine-comedian [Donation](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdUZQIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ed5d5f29220f8befb37238a09d3ee428733bc351/image.png)
> > [Projects](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdVJQIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--933964e2f6cfa261a8a452ca462373d92abeeecb/image.png)
> 
> This view is different on stg Plz check @MohammadPCh @RamRamez Only donation received should be shown in project tab as the above pic on feature branch
> 
> <img alt="image" width="1434" src="https://user-images.githubusercontent.com/111529185/265637834-ddac94dc-2c0f-4be8-9a97-3f21d64ed8a4.png">

I fixed it. It's waiting for review.

**Comment by maryjaf** [comment]
based on below pic the user has 19 project but 6 of them are shown because only 6 projects are listed, 
maybe it's better the number should be changed into the number of listed/active project 


[Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdnB3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5163fb410c14faeec6ee80a8a1f6e74b0c461fbc/image.png)

**Comment by RamRamez** [comment]
> based on below pic the user has 19 project but 6 of them are shown because only 6 projects are listed, maybe it's better the number should be changed into the number of listed/active projects
> 
> [Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdnB3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5163fb410c14faeec6ee80a8a1f6e74b0c461fbc/image.png)

We only show 6 projects there. I can add a pagination or infinite scroll. @divine-comedian WDYT?

**Comment by maryjaf** [comment]
> We only show 6 projects there. I can add a pagination or infinite scroll. @divine-comedian WDYT?

For other user like my user the pagination is shown ,I think the reason is status of project that i described above

https://staging.giveth.io/user/0xcd192b61a8dd586a97592555c1f5709e032f2505?tab=projects
<img width="1310" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/6c89b6aa-90a3-4dec-8b49-109053c035e5">

**Comment by divine-comedian** [comment]
I think if we already have used pagination then let's keep with it.

**Comment by maryjaf** [comment]
> based on below pic the user has 19 project but 6 of them are shown because only 6 projects are listed, maybe it's better the number should be changed into the number of listed/active projects
> 
> [Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdnB3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5163fb410c14faeec6ee80a8a1f6e74b0c461fbc/image.png)

The problem isn't related to pagination
 In user's project tab the number of all projects of user are shown even though some of them are maybe unlisted , deactivated or cancelled and I think this is the reason that for example i see the user has 19 project but i can see only 6
 maybe it should be better that projects with unlisted status have been excluded .
 
 I am not sure if we want to do something about this problem or not? Should I create a new issue?
 
@divine-comedian @RamRamez

**Comment by RamRamez** [comment]
> > based on below pic the user has 19 project but 6 of them are shown because only 6 projects are listed, maybe it's better the number should be changed into the number of listed/active projects
> > [Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdnB3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5163fb410c14faeec6ee80a8a1f6e74b0c461fbc/image.png)
> 
> The problem isn't related to pagination In user's project tab the number of all projects of user are shown even though some of them are maybe unlisted , deactivated or cancelled and I think this is the reason that for example i see the user has 19 project but i can see only 6 maybe it should be better that projects with unlisted status have been excluded .
> 
> I am not sure if we want to do something about this problem or not? Should I create a new issue?
> 
> @divine-comedian @RamRamez

We have two different queries for this, one of them returns all projects and the other returns active and listed projects.
I talked with @mohammadranjbarz, he will work on it.

**Comment by mohammadranjbarz** [comment]
> > > based on below pic the user has 19 project but 6 of them are shown because only 6 projects are listed, maybe it's better the number should be changed into the number of listed/active projects
> > > [Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdnB3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5163fb410c14faeec6ee80a8a1f6e74b0c461fbc/image.png)
> > 
> > 
> > The problem isn't related to pagination In user's project tab the number of all projects of user are shown even though some of them are maybe unlisted , deactivated or cancelled and I think this is the reason that for example i see the user has 19 project but i can see only 6 maybe it should be better that projects with unlisted status have been excluded .
> > I am not sure if we want to do something about this problem or not? Should I create a new issue?
> > @divine-comedian @RamRamez
> 
> We have two different queries for this, one of them returns all projects and the other returns active and listed projects. I talked with @mohammadranjbarz, he will work on it.

I created https://github.com/Giveth/impact-graph/issues/1123 regarding our discussion

**Comment by maryjaf** [comment]
> based on below pic the user has 19 project but 6 of them are shown because only 6 projects are listed,
> maybe it's better the number should be changed into the number of listed/active projects

I think this issue can be moved to Done and the this problem can be followed on new backend issues https://github.com/Giveth/impact-graph/issues/1123
