### ISSUE TITLE
Add "Share and Get rewarded" in all project on mobile view

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3062]
In the first phase mobile view was out of scope 
I created this issue to consider this change in next phases

**Steps to reproduce the behavior:**
1. Go to 'Giveth.io' on mobile
2. Click on 'all projects'

Mobile view:
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/64e07729-6729-46ee-96d2-663cc539638b)

Desktop:
<img width="1439" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/9fcba20f-aa97-4a57-8276-23d3213e1347">

cc: @divine-comedian

**Comment by divine-comedian** [comment]
@alireza-sharifpour want to take a look at this one?

**Comment by alireza-sharifpour** [comment]
I think we decided to remove this behavior (Bottom Sheets) from our app because it is a native mobile thing and it's not optimized for desktop and it will cause bugs. @mosaeedi @divine-comedian

**Comment by alireza-sharifpour** [comment]
> @alireza-sharifpour want to take a look at this one?

I'm working on it. @divine-comedian

**Comment by maryjaf** [comment]
Thanks @alireza-sharifpour I'v tested this on Metamask browser on iPhone and every thing was ok
