### ISSUE TITLE
Disable edit project view for cancelled projects

### ISSUE THREAD

**Issue by RamRamez** [Giveth/giveth-dapps-v2#3066]
This project is cancelled but I can still see the edit project page

https://giveth.io/project/test-listing

![image](https://github.com/Giveth/giveth-dapps-v2/assets/73441857/d686481f-e16d-4bf9-abcb-35f50963bafb)

**Comment by MoeNick** [comment]
@maryjaf can u pls confirm

**Comment by maryjaf** [comment]
Thanks @RamRamez 
Now if the user has edit link for a cancelled project  the below pic is shown
[Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdmxvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d1bd16f3f4d2502b30eedad9c9cd8db8a0c78d8c/image.png)
