### ISSUE TITLE
Wrong error message on editing the project

### ISSUE THREAD

**Issue by RamRamez** [Giveth/giveth-dapps-v2#3068]
In the edit project page, consider I'm not owner, app show "Only project owner can edit the project"

but when I switch to the owner account, I can see the edit project page but I still get this error
"Only project owner can edit the project"

![image](https://github.com/Giveth/giveth-dapps-v2/assets/73441857/875d50e5-7daa-4d3a-9ac6-0bfa26ab70c3)

**Comment by RamRamez** [comment]
FYI @maryjaf

**Comment by maryjaf** [comment]
plz check this @RamRamez 
By editing a project with another user, the below pic is shown
[ Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcDVvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--05c70b8df1dcbc31080d32ecea8ec5401d6d9758/image.png)

**Comment by RamRamez** [comment]
@maryjaf I didn't change this part, and we had this before.
@divine-comedian if you think this message is not informative, I can change it.
