### ISSUE TITLE
make the title clickable in recent posts

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3069]
Now only by taping on "read more" we can see the post
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/ee47e388-f757-47b7-b8c5-ad0fce366bf9)

cc: @RamRamez @divine-comedian

**Comment by MoeNick** [comment]
I think this was a design suggestion.
@mosaeedi

**Comment by maryjaf** [comment]
Thanks @RamRamez I checked and it passed
