### ISSUE TITLE
amount column should be wider in "My Donations"

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3071]
**Describe the bug**
This issue has been resolved in project's donation but in "My Donations"  still exists 
**To Reproduce**
1. Go to 'my account'
2. Click on 'my donation'

**Expected behavior**
The scroll bar should be removed

**Screenshots**
<img width="1251" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/3c18c95f-7a7b-43c1-9cdf-a8e10bf67caf">

**Comment by MoeNick** [comment]
@maryjaf pls confirm

**Comment by maryjaf** [comment]
Now for small amount "<0.01 " is shown, is this ok or it should be better changed to <0.001? @MoeNick 
[Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ1ZwIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--08ebfbc15ebca26d2982d06bccb540069387692a/image.png)
