### ISSUE TITLE
formatting for really long project names on My Projects table

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3072]
on staging.giveth.io 

currently if I have a really long project name (e.g. max 55 characters) then the verified badge currently gets formatted all weird. Ideally everything should fit nicely when using a  reasonable screen size - this is 1440 x 1121 for example. 

How can we fix this? Maybe just adjust some spacing? @mosaeedi 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdVFpIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fe07ce599b3aaee158f22cb1c812a72f57de836f/image.png)

**Comment by RamRamez** [comment]
I can force the badge to be beside the title:

desktop:
![image](https://github.com/Giveth/giveth-dapps-v2/assets/73441857/41a45756-cde0-47f2-9135-482c04b0fbe7)


mobile:
![image](https://github.com/Giveth/giveth-dapps-v2/assets/73441857/2ddab135-9e56-417f-adbc-4c366f4685d8)


@divine-comedian WDYT?

**Comment by divine-comedian** [comment]
Still doesn't look great.. perhaps we set so past a certain character count we show an elipsis ...

e.g. - this is my really long proj...

**Comment by MoeNick** [comment]
any updates @RamRamez ? just a kind reminder

**Comment by RamRamez** [comment]
> any updates @RamRamez ? just a kind reminder

I sent the PR. It's waiting for review.

**Comment by maryjaf** [comment]
Now if I have a really long project name, it is shown in the list like below pic, is this final expected view? @divine-comedian 

[Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc0tMIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8020c39856fe7dc143bbea5f650d6a61cd320c73/image.png)

**Comment by divine-comedian** [comment]
Yup I would call this passed!
