### ISSUE TITLE
QF bug on stg

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3076]
**Describe the bug**
QF round :[MARYTESTROUND](https://serve.giveth.io/admin/resources/QfRound/records/56/show)
Allocated fund :1 $
2 projects were connected to this round 
[testprofilepic](https://staging.giveth.io/project/testprofilepic?tab=donations)
[testmarya](https://staging.giveth.io/project/testmarya?tab=donations)

The estimated matching and then matching fund are calculated 1 $ for both of them although the allocated fund was 1 for this round
 

**Expected behavior**
the summation of matching funds should be 1 $

**Screenshots**
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/7f661e20-580c-4e2d-acef-7da69bfc50f6)
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/1c17f42c-bf44-43de-9a11-cb0fefae6a70)
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/5d131505-a4c1-4542-9587-59a9195151ba)

@MohammadPCh @alireza-sharifpour

**Comment by maryjaf** [comment]
[data-1692719919177.csv](https://github.com/Giveth/giveth-dapps-v2/files/12410656/data-1692719919177.csv)
[data-1692719945440.csv](https://github.com/Giveth/giveth-dapps-v2/files/12410657/data-1692719945440.csv)

**Comment by maryjaf** [comment]
<img width="1431" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/87378471-22b9-4c20-a16f-35458608d8ed">

**Comment by alireza-sharifpour** [comment]
When the output is between 0 and 1 we show 1 because of this line in the code:
``return result > 0 && result < 1 ? 1 : result;
``
I remember someone requested this in another issue.

If we have this issue with numbers more than 1 it should be investigated. @maryjaf

**Comment by maryjaf** [comment]
> When the output is between 0 and 1 we show 1 because of this line in the code: `return result > 0 && result < 1 ? 1 : result; ` I remember someone requested this in another issue.
> 
> If we have this issue with numbers more than 1 it should be investigated. @maryjaf

Thanks @alireza-sharifpour Yeah, it should be related to this condition
I'v checked with other project and other matching funds and this problem didn't exist
