### ISSUE TITLE
QF Donation tab

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3077]
The order of showing QF round in donation tab was out of scope of phase 1
We can pick this issue for next phase

**1- The open round always is shown in first position** 
<img width="1417" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/e9a8d5fa-0aaf-4549-bfe5-d4c0355c7991">

**2-user can scroll between older rounds**
<img width="1439" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/a7904d5f-dd8c-4d92-be60-8d360690c99f">

**Comment by laurenluz** [comment]
@maryjaf - for 1, are you saying that the open round SHOULD be shown in 1st position but it's not? because it looks to me that you have the open round in the 2nd position in your screenshot.

**Comment by maryjaf** [comment]
Yeah exactly
This issue is related to https://github.com/Giveth/giveth-dapps-v2/issues/2915

**Comment by MoeNick** [comment]
closing this to continue on  #2915

**Comment by maryjaf** [comment]
1- The open round always is shown in first position
There is't donation sub tab display order in #2915 @MoeNick

**Comment by maryjaf** [comment]
Thanks @divine-comedian Yeah it has been resolved
