### ISSUE TITLE
Actions for Project with "Draft" or "Deactivated" status

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3081]
I think it's better that the **"Project Actions"** for **Draft** and **Active** project be different
For example now I can complete verification form for draft project 
Is this Ok? @divine-comedian @MoeNick 

1. Go to 'my projects'
2. Click on 'a draft project'
3. Click on 'Project Actions'
4. See 'Verify Project'
5. Complete verification form

**Expected behavior**

**Screenshots**
<img width="1078" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/f70c6aaa-42f0-4a80-9ecf-a9ac7717d8da">

and one more thing
I can activate  draft project by taping on **active project** on "project actions" with out needed to taping on **continue creation**,  is this accepted?  
<img width="1430" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/2e8266c3-0adb-420c-9d50-b437e81256ad">

**Comment by divine-comedian** [comment]
Nice catch MJ! I'm wondering then what would be the appropriate "Project Actions" we should include when a project is in draft state - should we include any at all in this view? Maybe it's more confusing for the user.

**Comment by maryjaf** [comment]
Yeah, I think the only action required for a project in draft status is to complete the project publish operation.
Maybe it is better to customize these project actions based on the status of the project  Active,Deactivate and Draft

**Comment by divine-comedian** [comment]
Okay so what do you think:

## Active 
- All regular options 

## Deactivated 
- Edit Project 
- Activate Project

## Draft  
- remove actions drop down menu entirely

**Comment by maryjaf** [comment]
> Okay so what do you think:
> 
> ## Active
> * All regular options
> 
> ## Deactivated
> * Edit Project
> * Activate Project
> 
> ## Draft
> * remove actions drop down menu entirely

Yes, exactly
But i'm not sure by removing actions for Draft project, how does the design be changed? 
For example the  "Continue creation" can be shown instead of project actions 
<img width="1432" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/db5e9b9d-a29c-4656-b404-34967d5f69bc">

**Comment by divine-comedian** [comment]
- I think it's okay to have edit for a deactivated project - There is a case that a project owner might want to edit their project before reactivating it so its fine I think 

- No, lets not add any new buttons, I think it's okay if we just remove the drop down, the design shouldn't be impacted in a significant way I think

**Comment by divine-comedian** [comment]
I think we can move forward on this issue. 

- [ ] If a project is in draft status remove action drop down menu
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/64429e24-c7cc-4904-a424-06a401c547b7)

- [ ] If a project is "Deactivated" we remove the "share" & "verify" options from the drop down menu

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/309a048c-5b99-4bb8-8179-2ea894b3ed6e)

**Comment by MoeNick** [comment]
We only need a publish, edit and cancel button and the status, listing, and verification status are non-sense here, so the whole right column should get removed, and the ugly buttons at the button if the page should go up.

**Comment by maryjaf** [comment]
Thanks @divine-comedian All scenarios are as expected 
Now for Draft project no actions is shown and CREATION PROJECT button is shown in the bottom of the page maybe it's better to be changed this design later

**Comment by alireza-sharifpour** [comment]
@maryjaf, OK, i'll work on that.
