### ISSUE TITLE
Cow swap: by selecting max in cowswap modal the wrong message is shown

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3084]
**Describe the bug**
based on @divine-comedian's report  when we tap on max the "Insufficient GIV balance" button is shown
but this flow is ok for example for XDai, it's weird 

**To Reproduce**
1. Go to 'https://swap.giveth.io/#/100/swap/GIV/USDC'
2. Select  'GIV'
3. tap on 'max'

**Screenshots**
<img width="560" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/110297c5-8b08-4920-a6c8-95ed26b8db45">

<img width="511" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/e4f306ec-7487-493a-8f56-68643b87fd9b">

@mateodaza

**Comment by MoeNick** [comment]
did we fix it? @mateodaza ?

**Comment by mateodaza** [comment]
> did we fix it? @mateodaza ?

Yes sir. It's fixed :)

**Comment by maryjaf** [comment]
> Yes sir. It's fixed :)

plz check this @mateodaza 

when I tap on "max" the number is shown in box is different from the maximum amount

**Comment by divine-comedian** [comment]
@mateodaza I think we can close this one, right?
