### ISSUE TITLE
Make it easy for project to post on social media for verification

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3086]
After going through the hoops myself to verify some projects I want to suggest an improvement on this section, particularly for the requirement of making a social media post of my giveth project:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcFF4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fa1015a84e5a74b439bd48c5291a2a02ab079c08/image.png)

Let's make it easy for projects to share on social media - can we add some commons button like facebook and twitter that generates a message automatically they can post on their social media account. We already do this for our users/donors 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcGd4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2a0ccad45d7acd96862a02f8628ba18c35ecd053/image.png)

When we give them an easier way to post with the text we want them to say it can make the process streamlined, they only need to copy the url and pase it back in the text field linking to their social media post

**Comment by MoeNick** [comment]
connecting with oAuth does not need operation on our side to recheck the posts, the only need to click, verify and done,  only 2 clicks.

**Comment by MoeNick** [comment]
connecting with oAuth does not need operation on our side to recheck the posts, the only need to click, verify and done,  only 2 clicks.

**Comment by MohammadPCh** [comment]
@kkatusic can you take it up, please? Thanks.

**Comment by kkatusic** [comment]
@divine-comedian, cc @MohammadPCh , I added share button and share modal for easy sharing to project owner.

![Screenshot 2024-05-30 at 12 44 40](https://github.com/Giveth/giveth-dapps-v2/assets/1242145/17eb50be-7bdc-496b-8531-1a2011a9196c)

and result is:

![Screenshot 2024-05-30 at 12 41 29](https://github.com/Giveth/giveth-dapps-v2/assets/1242145/839546ea-f0d9-4c42-8033-da9e4ba64901)

and branch is: [link to branch](https://github.com/Giveth/giveth-dapps-v2/tree/easy_social_verify)

But main problem, issue, @divine-comedian  now for me is this button on right place or we need some UI touch here?

**Comment by divine-comedian** [comment]
We'll need to adjust the copy on both the prompt inside the social media post as well as on the modal itself. 

The modal should say: 

> ## Share your project 
>
> Share this project directly to social media or use the link to post it on your other platforms. Ensure you are posting this link from the organization's official channels!

the social media prompt should say:

> We're applying to become a verified project on @giveth, a zero fee crypto donation platform. 
>
> Check out our project here:
{projectLink}

**Comment by kkatusic** [comment]
> We'll need to adjust the copy on both the prompt inside the social media post as well as on the modal itself.
> 
> Conditionally, when being triggered from the project verification form the modal should say:
> 
> > ## Share your project
> > Share this project directly to social media or use the link to post it on your other platforms. Ensure you are posting this link from the organization's official channels!
> 
> the social media prompt should say:
> 
> > We're applying to become a verified project on @Giveth, a zero fee crypto donation platform.
> > Check out our project here:
> > {projectLink}

@divine-comedian that wan't be problem, main concern for me now is position of the Share button inside verification step

**Comment by divine-comedian** [comment]
> > We'll need to adjust the copy on both the prompt inside the social media post as well as on the modal itself.
> > Conditionally, when being triggered from the project verification form the modal should say:
> > > ## Share your project
> > > Share this project directly to social media or use the link to post it on your other platforms. Ensure you are posting this link from the organization's official channels!
> > 
> > 
> > the social media prompt should say:
> > > We're applying to become a verified project on @Giveth, a zero fee crypto donation platform.
> > > Check out our project here:
> > > {projectLink}
> 
> @divine-comedian that wan't be problem, main concern for me now is position of the Share button inside verification step

I think the position is fine where you have it is fine - do you have a vercel link?

**Comment by kkatusic** [comment]
@divine-comedian , I don't have vercel access, I will push commit tomorrow

**Comment by MoeNick** [comment]
I wonder why do we close the issue while it has not merged into the production yet! :( 
CC: @MohammadPCh

**Comment by maryjaf** [comment]
This issue hadn't been moved to QA/UAT and was moved to "done" directly 
this the current behavior 
is this the expected result ? @divine-comedian @MoeNick 



Uploading Screen Recording 2024-06-23 at 12.47.34 PM.mov…

**Comment by maryjaf** [comment]
https://github.com/Giveth/giveth-dapps-v2/assets/111529185/5b4315c8-8a89-4139-ac87-7f15896e8294

**Comment by MohammadPCh** [comment]
@MoeNick @maryjaf Thanks, guys! I'm not sure why this happened—I never close issues. Maybe a special role on ZenHub caused this, or perhaps I closed it by mistake. :(

**Comment by divine-comedian** [comment]
@maryjaf this looks good! If you didn't find any bugs let's move it to done.
