### ISSUE TITLE
Improving showing "Amount" and "USD Value" in donation tab

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3087]
It seems it's better that for low amounts for example less than 0.001 instead of showing 0 , <0.001 is shown , showing 0 amount and 0 $ in donation tab doesn't make sense

<img width="1422" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/0e358da4-e0ed-4eb2-8628-1aaf4e760abc">
@RamRamez @MohammadPCh @divine-comedian

**Comment by MoeNick** [comment]
Awesome suggestion.

**Comment by divine-comedian** [comment]
I think @RamRamez can check this one out

**Comment by maryjaf** [comment]
Same comment 
https://github.com/Giveth/giveth-dapps-v2/issues/3071#issuecomment-1706164587
