### ISSUE TITLE
Dedicated Socials/Links section on product page 

### ISSUE THREAD

**Issue by SteffanThorn** [Giveth/giveth-dapps-v2#3088]
**What problem is this design solving? Why is it necessary?**
We want to drive more traffic to project's websites and social media to increase their awareness. 
More awareness leads to more donations. 

I'm often doing the GivethMakers write up and have noticed that I go searching for projects' links. 

Sometimes it's at the bottom of about, sometimes it's in their updates, sometimes it's none existent -- in this case I go searching on twitter to find them. 

Having a dedicated socials section on their product page would make it easier for interested donors to find out more easily. 

**Is there any user data or feedback backing up this feature request?**
No. 
Personal experience. 

**Which metrics will define this feature's success?**
It will be easier for me to find out more about projects when I'm doing write ups. This would indicate it's easier for users to find more information. 

A data point could be that traffic for projects' websites and social media increase and donations increase.

**Additional context**
My suggestion is have a drop down menu to the right of the GIVpower window. 
Give project creators the options of adding the main socials/Links, and only show the ones they include in the drop down menu. 
Main socials/links:
•Their own website 
•Twitter
•Discord
•Telegram
•Medium
•Instagram
•Facebook
•Lens
•Giveth domain 
•Mirror
•Paragraph
•LinkedIn
•Notion.site

 @laurenluz , @oyealmond , @divine-comedian , @MoeNick

**Comment by divine-comedian** [comment]
Nice we did have some designs planned at there was a forum post made for it:
https://forum.giveth.io/t/improving-single-project-screen/983

AFAIK we didn't start working on this because of the QF designs received priority

**Comment by Tosinolawale** [comment]
This should be closed @divine-comedian
