### ISSUE TITLE
Managing a recurring donation already ongoing.

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3092]
Donors will need to view and manage their recurring donations from a page accessible from My Donations in a sub-tab called Recurring Donations - the other new sub-tab One-time Donations will contain the current regular donations table view

![My recurring donations (1)](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/78986d66-d3ee-4262-94dd-596283fced47)
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/GIVeconomy?type=design&node-id=23293-17833&mode=design&t=7J6iMuXHXGGPhHxz-0

The first component is a table of My Active Streams - this is a list of all super token balances for the given account/donor

this table includes:
- [ ] current super token balances (if it's not 0)
- [ ] outflow rate
- [x] how many projects they have recurring donations to with this token
- [x] #3285 

The second table below shows each individual recurring donation, this table includes:

- [x] date stream was created
- [x] name of project receiving recurring donation
- [x] network
- [x] monthly amount of recurring donation
- [ ] when their stream balance will run out for given token*
- [ ] total amount donated to project
- [x] actions menu

- [ ] *When the token balance is under 1 month remaining we should highlight in red & bold - showing a hover tooltip with the text included in the figma (from https://github.com/Giveth/giveth-dapps-v2/issues/3093)

#### for an active stream
- [x] #3286 
- [x] End Recurring Donation (ends stream)

#### for ended stream
- [x] Renew Donation (creates new recurring donation to project)
- [x] Archive Donation (removes this row entry from the table)

**Comment by jainkrati** [comment]
@MohammadPCh can you please lead this. If needed please distribute sub tasks to @alireza-sharifpour

**Comment by jainkrati** [comment]
@mohammadranjbarz can you comment on backend efforts here

**Comment by MohammadPCh** [comment]
@jainkrati @divine-comedian, here are the estimations for each task:

- Streams Balances: Approximately 12 hours (withdraw functionality not finished yet).
- Donation table: Approximately 20 hours.
- Action dropdown and modals: Approximately 24 hours.

**Comment by MohammadPCh** [comment]
@divine-comedian Yes, I am currently waiting for the backend. However, the top section has been implemented.

**Comment by jainkrati** [comment]
@MohammadPCh and @mohammadranjbarz to sync up and unblock the development

**Comment by divine-comedian** [comment]
Needs https://github.com/Giveth/impact-graph/issues/1398 and https://github.com/Giveth/impact-graph/issues/1400 to proceed.

**Comment by divine-comedian** [comment]
Testing this one I want to make sure we don't forget to update the icons and text color in the actions menus as per the figma! 
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/2fcc57d8-1d4f-416e-a4ad-c7f243be4d25)

**Comment by jainkrati** [comment]
@MohammadPCh pls take up on pirority

**Comment by maryjaf** [comment]
I haven't seen any changes in action styles in compare of before @MohammadPCh is this the final version?
<img width="1793" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNU11QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e754912687ebd176661e37cb5e3b663f0e60adc8/image.png" alt="image.png" />

**Comment by maryjaf** [comment]
> * total amount donated to project

based on the description this field " total amount donated to project" should be sown like as below pic in the second table
<img width="736" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/c2e91603-737c-45e5-8ec3-c94f3ce0be8d">


but in current design it is shown like as below pic, is this final and ok ? @divine-comedian @MoeNick 
<img width="1310" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/9af2ddec-7299-4636-a760-3b96b9f3bf98">

**Comment by maryjaf** [comment]
when their stream balance will run out for given token*

 *When the token balance is under 1 month remaining we should highlight in red & bold - showing a hover tooltip with the text included in the figma (from #3093)
@MohammadPCh @divine-comedian

**Comment by maryjaf** [comment]
> * [ ]  *When the token balance is under 1 month remaining we should highlight in red & bold - showing a hover tooltip with the text included in the figma (from [View & understand recurring donations being sent to a Project #3093](https://github.com/Giveth/giveth-dapps-v2/issues/3093))

It hasn't been implemented, I haven't seen this design in my recurring donation list with <1 month , is it in the scop or was removed?

**Comment by maryjaf** [comment]
4-
> * [ ]  total amount donated to project

and this item is blocked by this problem that should be checked 
https://github.com/Giveth/impact-graph/issues/1437#issuecomment-2031344160

**Comment by divine-comedian** [comment]
@maryjaf the current design on the FE is okay for now.

**Comment by maryjaf** [comment]
> #### for ended stream
> * [x]  Renew Donation (creates new recurring donation to project)
> * [x]  Archive Donation (removes this row entry from the table)

should any action be shown for archived  donation? I think the action icon should be removed for archive , am I right? @divine-comedian @MohammadPCh 

<img width="1228" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/67427bc3-ca61-48e5-89d8-7ffea6996135">

**Comment by MohammadPCh** [comment]
@maryjaf I think we have to hide it. I've done it but with new changes, it has a problem and shows the actions. so I can hide it again.

**Comment by MohammadPCh** [comment]
@divine-comedian @maryjaf What about adding an unarchive option?!

**Comment by maryjaf** [comment]
> should any action be shown for archived donation? I think the action icon should be removed for archive , am I right? @divine-comedian @MohammadPCh

ُThanks @MohammadPCh this problem has been resolved
