### ISSUE TITLE
As a Project, I want to understand & claim my recurring donations

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3094]
Project owners will claim their streamed tokens from the My Projects page from their project card component, check out #3283 

https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/GIVeconomy?type=design&node-id=23644%3A30769&mode=design&t=r1TrXxvCgPKGumvf-1

![My accounts](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/d4ff8d7f-923b-4a69-9195-aa7a9990ff02)

On this component we need to show the available balance the user can claim for a particular project on the given chain they are connected to.

The user should be able to click inside of the Actions dropdown and select 'Claim Recurring Donations'  ("Claim Streamed Tokens" ) - it should open up this modal 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/584536e6-477e-415e-bb09-ff10a0952f0e)

On this modal we should show the user's balance for each streamable token held in their anchor address (allo protocol) ( we can use recipient addresses for now) as well as the USD value of the claimable tokens

Clicking `Claim Tokens` will open a confirmation modal for claiming that particular token - This will downgrade the selected token to the project's recipient address for the given chain 

Clicking `Claim All Tokens` will claim all tokens in a batch tx - downgrading them all to the project's recipient address for the given chain 

https://docs.superfluid.finance/superfluid/developers/batch-calls/batch-calls

**Comment by divine-comedian** [comment]
the recipient address needs to approve somehow the project owner to unwrap the tokens

**Comment by alireza-sharifpour** [comment]
Update about deadline, I think it will be finished by 11 Dec.
The only remaining part of this issue will be the functionality of claiming which i think Sem is working on it.

@jainkrati

**Comment by alireza-sharifpour** [comment]
The UI and functionality of the part related to account page My projects tab is done.
The claim part is not completed yet.
we have the claim part also on this issue on Allo Protocol Epic.
https://github.com/Giveth/giveth-dapps-v2/issues/3441

@jainkrati

**Comment by alireza-sharifpour** [comment]
This issue is done merged, but it cannot be tested until the backend of donation is completed.
@maryjaf @divine-comedian

**Comment by jainkrati** [comment]
dependent on savnig donation on FE by @MohammadPCh

**Comment by alireza-sharifpour** [comment]
This issue is the same as #3441

**Comment by maryjaf** [comment]
the tests have been passed

**Comment by divine-comedian** [comment]
We still need to verify that users can claim ETH successfully - moving this back into in progress
