### ISSUE TITLE
As a Donor, I want to be made aware & notified of when my recurring donation will end.

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3097]
Donors should be made aware and pushed to top-up their stream balance so that their recurring donations does not end to a project. Their recurring donation will end when they have 0 streamable tokens left in their "stream balance". 

We should highlight information regarding their imminently ending recurring donations. We should also send them notifications & emails at appropriate intervals as their stream balance approaches 0.

## My Recurring donations page
users see a warning symbol next to their balances that are close to running out 
![My recurring donations (1)](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/c83ad6f6-b471-440a-814f-8993eb22f676)

**Comment by divine-comedian** [comment]
Related to #3160

**Comment by divine-comedian** [comment]
@MohammadPCh  - could provide an update here? This issue is to show the end dates of the streams on the app and the styline involved if the donation is in a critical state - Since we are now handling things in months we should show the red warning & tooltip for when a recurring donation has < 1 month left .

**Comment by MohammadPCh** [comment]
@divine-comedian Unfortunately, nothing has been implemented as we currently don't have any data.

**Comment by divine-comedian** [comment]
We will close this issue and can follow it up in https://github.com/Giveth/giveth-dapps-v2/issues/3092
