### ISSUE TITLE
Update for Deactivated project

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3102]
should  a project owner be able to add an update for his deactivated project? @MoeNick @divine-comedian 
If answer is no some changes should be applied on action of my project list and project's update tab, if yes, we can close this issue

<img width="1433" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/86945a63-b45c-40f6-b110-38513ea7f01a">
<img width="1434" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/9ca5dd99-57cb-4913-b828-1cd0dadbef85">

**Comment by divine-comedian** [comment]
I think it's fine. There is a case for a project owner who may want to deactivate (no longer accept funds) their project and provide an update to their donors, how funds were spent, impact created.. etc..
