### ISSUE TITLE
User's GIV balance on header

### ISSUE THREAD

**Issue by MohammadPCh** [Giveth/giveth-dapps-v2#3103]
now we show the user's GIV balance on the header:
![image](https://github.com/Giveth/giveth-dapps-v2/assets/17097576/7b7c639e-233f-424b-8d60-f5467049a2eb)
But this is the user's balance on the Gnosis chain, what about the user's balance on OP? or other chains?
@laurenluz @divine-comedian

**Comment by divine-comedian** [comment]
We should show the balance depending on the chain they are connected with - there should be a GIV token on all chains, but perhaps not all test chains - token addresses can be found in "Deployments" doc


Wasn't this already implemented? What changed in this issue?
