### ISSUE TITLE
Improving GIVbacks Distribution process

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3107]
Currently GIVbacks is very tedious and leaves too many opportunities for human errors. We use a variety of different applciations such as swagger API interfaces, EVMcrispr, google sheets, AdminJS dashboard and AragonDAO. 

We should try to find a way to simplify all of these numerous steps and platforms to not only reduce the effort required to do GIVbacks but also to increase its security. 

This could take the form of a simple front-end that makes fetching data for GIVbacks as well as reviewing & red listing donations much simpler 

Maybe there's a way we can even use EVMcrispr scripts from inside the Front-end app as well? 

@Vyvy-vi is on it! 

Pinging @WhyldWanderer @sembrestels @brichis @MohammadPCh  to advise this project since each of them has a hand in how GIVbacks are handled.

@WhyldWanderer usually manages the entire process and most steps regarding creating votes, using EVMcrispr to create the distribution scripts, generating the donation info and GIVbacks calculation info from the swagger APIs

@sembrestels  is the lead developer of EVMcrispr and built custom commands specifically for Giveth & running GIVbacks 

@brichis often does the GIVbacks review for fradulent or recirculated donations out of google spreadsheets 

@mohammadranjbarz is the developer for the GIVbacks back-end - he built all of the APIs, queries and calculations for GIV & GIVbacks data. 

### Resources 
API UI is here:
https://givback.develop.giveth.io/api-docs/#/default

EVMcrispr GIVbacks example is here:
https://evmcrispr.com/#/terminal/QmR4DqzvNCW7kJU4k3HHnxhAndTqhahzoUGyEZvx8BwijP

**Comment by WhyldWanderer** [comment]
Thanks for creating this issue Mitch! 

I have been talking with Sem yesterday and we will explore more today as well.
Going through each step and seeing if there are any automation solutions.

@Vyvy-vi - Have you already found some automation solutions? How do we get.keep us all aligned and on the same page?

**Comment by WhyldWanderer** [comment]
I created this HackMD doc that outlines every step I take when processing a round of GIVbacks:

https://hackmd.io/@WhyldWanderer/rymizYnpn

Keep in mind that there may be some steps missing since we are still working out GIVbacks on Optimism in EVM Crispr..

But as of today, this is accurate.

https://hackmd.io/@WhyldWanderer/rymizYnpn

**Comment by Vyvy-vi** [comment]
- The swagger interface makes requests to the givbacks API. Website can call those endpoints. (steps 1, 3, 5, 7, 9, 13, 28, 30)
- The spreadsheet processing can be done in-memory, or in a lightweight client-side database (like duckdb), and then dumped to google spreadsheets. (or we could create automated google sheets with macros) (steps 15, 20)
- The discord post can be sent by a discord webhook (step 22).
- Latest block can be fetched via [blockscout's API](https://gnosis.blockscout.com/api?module=block&action=eth_block_number) (step 26)
- We can have pre-populate the forum post or send it via a webhook (step 35)

**Comment by divine-comedian** [comment]
Oh wow! This is amazing @Vyvy-vi  

What do you need to start? How would you imagine an admin interacting with all this? Is there anyway we can secure this so only certain people can access it? Either by typical username/pw combo or with eth address

**Comment by Vyvy-vi** [comment]
eth address would be better

**Comment by Vyvy-vi** [comment]
Should the application wait for review before creating the - **RX GIVbacks Calculation (G)** and **RX GIVbacks Calculation (G)**?

**Comment by divine-comedian** [comment]
> Should the application wait for review before creating the - **RX GIVbacks Calculation (G)** and **RX GIVbacks Calculation (G)**?

Yes - we fetch all the spreadsheets of donation info then a manual review happens of the donations transactions. 

If there's any ineligible donations that the system didn't catch (people gaming the system or system bugs) then we need to flag them in the DB (hopefully this process too can be optimized). 

Once the review finishes then we can run the calculations - the review can take 1-3 days to happen.

**Comment by Vyvy-vi** [comment]
To confirm, these 4 sheets are sent to the fraud detection team, right?
- RX Eligible Donations (O)
- RX Eligible Donations (G)
- GIVbacks Data Round X (G)
- GIVbacks Data Round X (O)

**Comment by WhyldWanderer** [comment]
Yes! If you send me your email address, I would be happy to share the spreadsheets with you @Vyvy-vi

**Comment by divine-comedian** [comment]
> To confirm, these 4 sheets are sent to the fraud detection team, right?
> 
> * RX Eligible Donations (O)
> * RX Eligible Donations (G)
> * GIVbacks Data Round X (G)
> * GIVbacks Data Round X (O)

I think it's more than that - I think all three of these are used for the review - both Gnosis and Optimism right @WhyldWanderer ?

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/6aba2af6-5a6e-4eb2-8813-274a3a0ba8a4)

**Comment by WhyldWanderer** [comment]
Yes @divine-comedian
Except /purpleList-donations-to-verifiedProjects shows both chains so I only import it to the 'GIVbacks Data Round X (G)' spreadsheet

**Comment by WhyldWanderer** [comment]
I think it is important to keep in mind that Mohammad has been making some changes to the APIs that have not yet been merged. I will be testing it out more tomorrow. There is an issue for it here: https://github.com/Giveth/givback-calculation/pull/34#issuecomment-1701007048

**Comment by jainkrati** [comment]
@divine-comedian could you confirm the priority of this task

**Comment by divine-comedian** [comment]
Closing this one as we will be taking a new approach as part of https://www.notion.so/giveth/Improving-GIVbacks-65fdc5e1eed94d95ad776af63e7c07bb
