### ISSUE TITLE
Integrate donation formatters

### ISSUE THREAD

**Issue by MohammadPCh** [Giveth/giveth-dapps-v2#3114]
we have 2 different donation formatter we need to integrate them together,

**Comment by maryjaf** [comment]
Now for small amount "<0.01 " is shown, is this ok or it should be better changed to <0.001? @MoeNick

**Comment by maryjaf** [comment]
There is a problem in donation tab on stg as below pic
I'm not sure it's related to this issue or not
[Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcnR3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1720cee28e34d657498b939f9c960566a645c637/image.png)

**Comment by MoeNick** [comment]
> Now for small amount "<0.01 " is shown, is this ok or it should be better changed to <0.001? @MoeNick

I think it's ok cause we have the USD amount in other column.
