### ISSUE TITLE
Use Viem and Wagmi instead of ethers package

### ISSUE THREAD

**Issue by MohammadPCh** [Giveth/giveth-dapps-v2#3116]

**Comment by maryjaf** [comment]
Plz check this @MohammadPCh 
1- showing NaN in project's GIVpower table
[Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdGV5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7ee3ce73f97f9194538eebfe162c516b74885533/image.png)
https://givwagmi.vercel.app/project/how-many-photos-is-too-many-photos?tab=givpower

**Comment by maryjaf** [comment]
2- 
When I try to stake the showing number in Metamsak modal is different from entering number 
For example I enter 1672.24 but 167 is set 
[Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbEt6IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--979e73bcb061084b8453477bfbaf31c8e0589db1/image.png)

[Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbHF6IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--25bc5dab137bdc0bd4c3ea4d082a5f3bc80945ee/image.png)

**Comment by maryjaf** [comment]
4-
When I have.n't balance on some token for example AAVE on polygon, ma balance isn't shown 0 
In below pic my balance is set 11.92 because before changing to polygon, the network was set on Gnosis any my GIV balance was 11.92
[Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBczY0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--79dd338a5298463a8af94e595395f0cc12db4fd4/image.png)

@alireza-sharifpour @MohammadPCh

**Comment by maryjaf** [comment]
5-
I had a problem to switch network on mobile for example polygon to optimism, I think it's better to check this together

**Comment by maryjaf** [comment]
Thanks @MohammadPCh 1,2 & 3 have been resolved

**Comment by maryjaf** [comment]
6-plz check this video, Connect wallet and switch network don’t work @alireza-sharifpour @MohammadPCh 
Device:iPhone
Browser:chrome
https://github.com/Giveth/giveth-dapps-v2/assets/111529185/eaca81a2-2a8c-4485-b939-e664ef248e59

**Comment by maryjaf** [comment]
7-When my user is sign-in,switch network works correctly some times from user’s menu but some times the system behavior is like below video:

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/2ec5401d-c5ab-47eb-8484-0325c49aeda0

**Comment by maryjaf** [comment]
> 4- When I have.n't balance on some token for example AAVE on polygon, ma balance isn't shown 0 In below pic my balance is set 11.92 because before changing to polygon, the network was set on Gnosis any my GIV balance was 11.92 [Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBczY0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--79dd338a5298463a8af94e595395f0cc12db4fd4/image.png)
> 
> @alireza-sharifpour @MohammadPCh

Thanks @alireza-sharifpour This problem has been resolved

**Comment by maryjaf** [comment]
8-
Imagine my user isn't sign-in  and the user is on QF page, by tapping on Connect Wallet in passport banner nothing happens
Desktop view
Chrome
<img width="1440" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/01b22b32-adb9-4863-bc53-11ced5eddc28">

**Comment by MohammadPCh** [comment]
@maryjaf 
We made a couple of improvements last week. Could you please test it again?

**Comment by maryjaf** [comment]
> 8- Imagine my user isn't sign-in and the user is on QF page, by tapping on Connect Wallet in passport banner nothing happens @MohammadPCh @alireza-sharifpour 

Thanks, this problem has been resolved

**Comment by maryjaf** [comment]
> 7-When my user is sign-in,switch network works correctly some times from user’s menu but some times the system behavior is like below video:

The switch network problem has beed resolved for me, Is this ok for you now? @divine-comedian

**Comment by maryjaf** [comment]
> 6-plz check this video, Connect wallet and switch network don’t work @alireza-sharifpour @MohammadPCh 

The switch network problem has beed resolved for me, Is this ok for you now? @divine-comedian

**Comment by maryjaf** [comment]
Some times connect wallet flow is buggy 
plz check these two videos @MohammadPCh 


https://github.com/Giveth/giveth-dapps-v2/assets/111529185/fbb789f4-75c2-49b2-b704-f32c3b0f07e5


https://github.com/Giveth/giveth-dapps-v2/assets/111529185/6e6d9ba4-fbd8-4cc0-b34a-ceb7487e3879

**Comment by maryjaf** [comment]
change wallet isn't shown on wagmi branch @MohammadPCh 
givwagmi.vercel:
[Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcFRYIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c9c761151cee4acaadca7ca706c028f8c63e6b5c/image.png)

staging:
[ Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcG5YIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--01f3db0a70133b126131a0a9db8fa3381f358334/image.png)

**Comment by maryjaf** [comment]
> The switch network problem has beed resolved for me, Is this ok for you now?

I couldn't understand the problem, now the switch network flow doesn't work on my mobile! in the morning it was ok
Device:iPhone
Browser : chrome & safari
Wallet : Metamask

**Comment by MohammadPCh** [comment]
@maryjaf Thanks for reporting, actually the UX of the change wallet in the new package is different and I think it's better than what we had. we connect each wallet to a specific account. so it's meaningless that we switch wallets. we should sign out and then sign in again with our new wallet(account). and it's what we have in the new flow.
