### ISSUE TITLE
When donating on Optimism, the USD value is not calculated

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#3119]
When donating on Optimism with Metamask on Chrome, the USD value of my donation is not calculated on the donation page.

![image](https://github.com/Giveth/giveth-dapps-v2/assets/74267818/5973f86b-ba04-4858-8a2b-b6ea482a763d)

**Comment by divine-comedian** [comment]
Maybe this was a temporary bug it looks fine for me now

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/c609c8d0-955d-4fd8-bafd-eea8901946b5)
