### ISSUE TITLE
Update GIVeconomy to use wagmi & viem

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3120]
Update GIVeconomy sections to use wagmi & viem, where needed 

- [x] GIVfarm page
- [x] GIVbacks page
- [x] GIVstream page
- [x] GIVpower page
- [x] GIVgarden page
- [ ] GIVdrop ??

**Comment by MoeNick** [comment]
@alireza-sharifpour can you attach the Cherick's draft PR to this issue?

**Comment by alireza-sharifpour** [comment]
> 

Sure. @MoeNick

**Comment by maryjaf** [comment]
When I try to unlock or stake after redirecting to Metamask, nothing happens 
plz check this video @MohammadPCh 

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/f374b6f4-aa14-44cd-aff0-226f6bbddfbe
