### ISSUE TITLE
Update Donate page to use wagmi & viem

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3121]
We'll need to update the donate page for projects to use wagmi & viem for making donations

**Comment by maryjaf** [comment]
I couldn’t complete donation flow on my iPhone
Browser : chrome & safari
The transaction confirmation modal in meta mask isn’t shown and the flow is stopped 
Plz check this screen record @alireza-sharifpour @MohammadPCh 
https://github.com/Giveth/giveth-dapps-v2/assets/111529185/ecd45bc7-a842-4fc5-9b23-e6c668f72033

**Comment by divine-comedian** [comment]
> I couldn’t complete donation flow on my iPhone Browser : chrome & safari The transaction confirmation modal in meta mask isn’t shown and the flow is stopped Plz check this screen record @alireza-sharifpour @MohammadPCh https://github.com/Giveth/giveth-dapps-v2/assets/111529185/ecd45bc7-a842-4fc5-9b23-e6c668f72033

Can you create a more specific issue for this test case failure?
