### ISSUE TITLE
Edit Profile Image Issue

### ISSUE THREAD

**Issue by CFWHISPERER** [Giveth/giveth-dapps-v2#314]
I created a profile and then uploaded an image to the profile, then decided to change that image, however even though the image uploaded and was viewable, I was unable to save it.

**Comment by CFWHISPERER** [comment]
I tried deleting the original image and uploading from scratch and that did not work either, the results were the same; could not save it.  This Brave browser on Windows 11 with Metamask wallet.

**Comment by CFWHISPERER** [comment]
This is more of a related observation; I did create a project yesterday and did not get any email confirmation or feedback as yet.

**Comment by RamRamez** [comment]
What error did you get?
Can you change your profile picture again and check it?

**Comment by laurenluz** [comment]
I was able to upload and change my project picture on develop

**Comment by CFWHISPERER** [comment]
It's not an error, per-se in the sense there is no error message; the image does not get added to my profile.  Bear in mind the first upload worked, it was in replacing it that I hit these issues; this in Brave Browser.
![Screenshot 2022-03-24 155311_uploadPhoto](https://user-images.githubusercontent.com/728102/160023662-58538747-ace0-40a7-822c-01c24bb0f264.png)

**Comment by RamRamez** [comment]
I think I found the problem. You have chosen a tall picture so you don't see the save button. We've fixed this problem and added a scrollbar. Please check again and try saving your image.
![image](https://user-images.githubusercontent.com/73441857/160115554-25ef7ab8-f8d7-4973-a0ab-8e357f13f18b.png)
