### ISSUE TITLE
Wrong USD value of stream harvestable amount on mainnet

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapps-v2#3141]
https://giveth.io/givstream
My wallet address: 0xF23eA0b5F14afcbe532A1df273F7B233EBe41C78

On mainnet network the usd value of stream harvestable amount is zero, while it's positive on Gnosis network

<img width="1260" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/5684607/8592d0dc-f7a9-463c-a91b-3bd011482db9">

**Comment by aminlatifi** [comment]
The error has happened since we use uniswap subgraph, it stores `drivedEth` value per token. In mainnet we fetch this value for `GIV` and `DAI`, then divide. Since GIV token has become too small in comparison to ETH, the first value has become zero!

One solution is to switch to a centralized solution, getting balance from coingecko public simple API

`https://api.coingecko.com/api/v3/simple/price?ids=giveth&vs_currencies=usd`

**Comment by MoeNick** [comment]
I think it was fixes, is it? 
Can you verify it's fixed @maryjaf ?

**Comment by maryjaf** [comment]
> The error has happened since we use uniswap subgraph, it stores `drivedEth` value per token. In mainnet we fetch this value for `GIV` and `DAI`, then divide. Since GIV token has become too small in comparison to ETH, the first value has become zero!
> 
> One solution is to switch to a centralized solution, getting balance from coingecko public simple API
> 
> https://api.coingecko.com/api/v3/simple/price?ids=giveth&vs_currencies=usd

Amin described the reason in this comment 
I'm not sure we have a plan to take this or not

**Comment by MoeNick** [comment]
@laurenluz can you put a priority tag on this one? it seems to be p0, right?

**Comment by laurenluz** [comment]
yeah agree, we should consider it a P0. cc @jainkrati

**Comment by jainkrati** [comment]
@MohammadPCh @mohammadranjbarz @mhmdksh pls use same API using multiple free accounts of Coingecko or any other better API provider. Its okay if you chat async also.

**Comment by MohammadPCh** [comment]
@maryjaf Could you please test this? Thanks.

**Comment by laurenluz** [comment]
is this on prod yet? because for me on prod, it still shows 0
![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/7975b96e-3865-4f6a-b58f-4b4c74f355fe)

**Comment by MohammadPCh** [comment]
@laurenluz No, it hasn't been merged yet.

**Comment by maryjaf** [comment]
I don't have GIVstream Rewards on the mainnet. Could you please take a look at prod so we can be sure this problem has been resolved? @laurenluz @aminlatifi

**Comment by laurenluz** [comment]
fixed 
![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/ea93c79c-4562-4cf9-9002-ba3afa31421c)
