### ISSUE TITLE
Show analytics of donations distinguished by tokens donated 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#3147]
We need to update https://analytics-dashboard-blue.vercel.app/ based on changes made by @CarlosQ96 before.

**Comment by RamRamez** [comment]
Based on Discord comments from @spectoregia, we need:

1. Per chain data:
adding ability to filter data per chain (just like for OP that @CarlosQ96 did before) for Donors Count, Donations Count, and Total Donations USD

2. Which tokens are used the most on each chain by unique donors
(e.g. 50 unique donors have used ETH, 30 unique donors have used GIV and 20 unique donors have used UNI then, 50% ETH, 30% GIV, 20 UNI)

@CarlosQ96 has added added `getDonationStats` query before (related to No. 2). We need to add time range filter and chain filter for that query.

**Comment by MoeNick** [comment]
@RamRamez I think you did this, shall I close it?

**Comment by RamRamez** [comment]
@MoeNick No, we are still blocked by the backend.

**Comment by jainkrati** [comment]
whats the priority of this task @MoeNick

**Comment by MoeNick** [comment]
I updated the priority thanks for reminding

**Comment by jainkrati** [comment]
@RamRamez can you share what exactly does BE data can unblock this? then @mateodaza can take over.

**Comment by RamRamez** [comment]
> @RamRamez can you share what exactly does BE data can unblock this? then @mateodaza can take over.

I've listed on the comment here https://github.com/Giveth/giveth-dapps-v2/issues/3147#issuecomment-1787020107

**Comment by divine-comedian** [comment]
@RamRamez @mateodaza - what is the update on this issue?

**Comment by divine-comedian** [comment]
@RamRamez what is the update for this issue? Can it be closed?

**Comment by RamRamez** [comment]
@LatifatAbdullahi @maryjaf Please test and verify

**Comment by LatifatAbdullahi** [comment]
@RamRamez 


The section for Analytics of Unique Donors distinguished by tokens has been added as shown below

![image](https://github.com/user-attachments/assets/77d11961-e9c1-492d-a4d9-409a3516ee0f)



Also, the Analytics can be filtered by date as well as Networks to show number of Unique donors and tokens used.

**Comment by divine-comedian** [comment]
@RamRamez - maybe this is a weird staging anomaly but why is there a separate slice on the pie chart for xDai & XDAI - aren't they the same thing?

Also, since this one is a bit hard to understand without some more information could you add some subtext under the query header? 

> Which tokens have been used by each unique donor - 
> (e.g. 50 unique donors have used ETH, 30 unique donors have used GIV and 20 unique donors have used UNI. Result would be 50% ETH, 30% GIV, 20 UNI)

![image](https://github.com/user-attachments/assets/ada7b944-e8f8-4e1f-b407-ae1cdafc772b)

**Comment by RamRamez** [comment]
@divine-comedian we had two donations on staging DB with symbol `xDai`, I changed them manually to `XDAI` because all symbols should be uppercase.

I believe it's not a bug because we don't have any donation with symbol `xDai` on production.

**Comment by divine-comedian** [comment]
Nice! Do we need any other release for this to go to production or do we just need to update the analytics FE? 

If it's only updating the analytics dashboard FE we can go ahead and make a release for it.

**Comment by divine-comedian** [comment]
OK - let's wait then for the next general release and we will include this feature then, no need for cherry picking since we do not need this urgently.
