### ISSUE TITLE
Adding Reset or Cancel button in creation project page

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3157]
based on: https://github.com/Giveth/giveth-dapps-v2/issues/2805#issuecomment-1706634739
It's better to consider a button for reseting  the fields or cancel flow in creation project page.

In the current flow, when the user fills the fields but refuses to continue creating the project, there are only two options: Preview and publish
And by selecting the back option, the previously recorded data will remain            

cc: @divine-comedian

**Comment by divine-comedian** [comment]
@RamRamez Do you want to check this one out? It's a continuation of the issue you already worked on in saving the fields from the create project flow

**Comment by maryjaf** [comment]
Thanks @RamRamez **CANCEL** button is shown in creation project page and by selecting this all field will be restet and this page will be closed
