### ISSUE TITLE
Integrating Allo Protocol registry for projects

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3166]
This feature would bring in smart contracts for projects and permit advanced interactions between project owners and their recipient addresses with significantly less friction. 

This is a contract system developed by Gitcoin and Giveth would implement a version of their Registry.sol contract:
https://github.com/allo-protocol/allo-v2/blob/main/contracts/core/Registry.sol

And also interact with a deployed AnchorContract - which is done by the Registry for a project on Giveth:
https://github.com/allo-protocol/allo-v2/blob/main/contracts/core/Anchor.sol

High level is that we can create profiles for each project on Giveth, each profile has an associated "anchor contract" an owner who can perform actions on the anchor.

What this solves for Giveth are some of the UX complexities of the superfluid integration, such as 
- Project Owners needing to change the recipient address of their project 
- Project Owners able to unwrap/downgrade supertokens to their project recipient address

This also unlocks issues we faced with GIVfi and is compatible with an eventual Account Abstraction integration.

## Contract Flow

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/7e48a96d-057c-4065-9b36-24d2742ce6f0)

## Creating an Allo Protocol Profile 
We call this function in the registry contract: 
https://github.com/allo-protocol/allo-v2/blob/main/contracts/core/Registry.sol#L118

Which takes a few arguments:
```
   function createProfile(
        uint256 _nonce,
        string memory _name,
        Metadata memory _metadata,
        address _owner,
        address[] memory _members
    )
```
### nonce
- unique integer used with the owner address to create the address hash of the anchor contract 
- must use a different nonce for project owners who own multiple projects (can we use the projectId in our DB?)

### name
- can use the project slug or project name

### metadata
- empty for now

### _owner
- the address of the project owner 

### _members
- leave empty for now

### Creating a recurring donation
Since most projects won't need Allo protocol or an anchor address until they receive their first recurring donation we should pass off the deployment of the anchor contract to the donor when they are doing the transaction. 

- User sets up a recurring donation to a project on Giveth, submits tx.
- Check if profile exists for project on the registry contract
- If profile exists continues regular flow
- If no profile exists we add an extra tx for the donor to sign, creating a profile for the project, we need:
   - projectId of project - use for "name" variable
   - address of project owner - becomes profile owner
 - profile is created along with anchor contract 
 - user creates stream to anchor contract
 - save anchor contract address to project's data entry in Giveth DB 
 
### Project Owner claiming streamed tokens 
- Project Owner goes to "my project" page
- Hits claim recurring donations on the corresponding project card which they want to claim tokens for 
- generate tx for project owner to call [`downgradeTo`](https://github.com/superfluid-finance/protocol-monorepo/blob/dev/packages/ethereum-contracts/contracts/superfluid/SuperToken.sol#L643) - downgrading super tokens to the project recipient address
---
## Project Owner changing their recipient address
- project owner goes to their project page, clicks "edit"
- owner enters new recipient address for given chain
- update Giveth DB
- donor's recurring donation continues as normal to anchor contract
- nothing on chain needs to happen

## Changing Project Ownership 
- This will create complications in this flow - AFAIK users cannot do this - only a dev can 
- The current Project Owner address will have to sign a tx for every project they own on Optimism to propose to transfer the ownership of their allo profiles 
- The incoming project owner address will have to accept the proposal to make the switch
- If the project owner loses control of their keys they're screwed (we can't help them)
- Maybe we can kick the can down the road and deal with it as needed

**Comment by jainkrati** [comment]
@divine-comedian what is the priority of this epic

**Comment by jainkrati** [comment]
@maryjaf pls close if tested

**Comment by maryjaf** [comment]
After deploying on prod the issues would be closed.
