### ISSUE TITLE
Add TRYC token to Giveth 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#3171]
> @WhyldWanderer I suggest we add TRYC token, @mohammadranjbarz whats' the blocker for adding this one? @maryjaf can you take a look and test, please?
- [ ] Modify monoswap to support this token
- [ ] Write a migration
- [ ] Add some test cases to make sure it works

I think we can create another issue for that purpose

ؤیی

_Originally posted by @mohammadranjbarz in https://github.com/Giveth/giveth-dapps-v2/issues/2733#issuecomment-1713681496_

**Comment by divine-comedian** [comment]
This is like a turkish lira stablecoin? I couldn't find any info on it - all the links go to this one centralized exchange based in Turkey
