### ISSUE TITLE
Add "Ambassador" field to Verification Application

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#3172]
We want to add a field to the verification application that asks:

"Were you onboarded by a Giveth Ambassador? If so, who was it?"

Thanks!

**Comment by MoeNick** [comment]
In which step do you want to add this question?

**Comment by divine-comedian** [comment]
@WhyldWanderer - is this issue still relevant?

**Comment by WhyldWanderer** [comment]
@divine-comedian no.. We can close this one.
I think It will be quite sometime before this might become relevant again. Thanks Mitch!
