### ISSUE TITLE
Showing wrong message in Draft project page 

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3176]
**Describe the bug**
When i select one draft project in my project list for about one  second this message is shown 

<img width="1349" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/a77dceba-39d5-4cf4-811d-cb74d51249f2">

**To Reproduce**
1. Go to 'my project'
2. Click on 'a draft project'
3. See error

cc: @RamRamez

**Comment by maryjaf** [comment]
I checked and it seems there is no change on this scenario 

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdGp5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c5e57521ee58353e398c2ceb69aea7bc3e7325f2/4A017CD7-6C81-4DE4-B7D9-038267D6D5FB.mov)

**Comment by MohammadPCh** [comment]
I found a problem in this flow.
actually, The owner when signed in can only fetch the draft project data for other states. so we can't distinguish whether the project exists or not and can't show this message: "Only the project owner can edit this project.".
Do we want to remove it? or change the backend?
@MoeNick

**Comment by MoeNick** [comment]
Thanks @MohammadPCh for the review. 
I guess we need to define another backend issue here. 

moving it back to the product backlog to analyse it more with @mohammadranjbarz

**Comment by maryjaf** [comment]
This issue has been resolved
