### ISSUE TITLE
QF - Only donations made on specified chains are eligible for matching

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3178]
Polygon wants to run a QF round with Giveth where only donations made on Polygon are eligible for matching.
In the future, we may want to run rounds for only Optimism, only Gnosis, only Celo, etc.
We need to make some small modifications to our design to inform the user which chains are eligible for matching.

My suggestions:

1. Project Single Page - Add text under estimated matching that says "Only donations made on < Polygon > are eligible to be matched."

We should be able to specify which chains are eligible in admin bro. If all chains are eligible, there is no message. If two chains are eligible, we can say, for example " "Only donations made on < Polygon > and < Gnosis > are eligible to be matched."

<img width="1337" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/75490971/540955a7-4114-4c20-9e4b-ffc66e970b1c">

2. Project Single Page - Donations tab - QF Round tab - We may want to show here ONLY the project recipient addresses for the eligible chains. We should still, however, show all the addresses on the "All donations" tab.

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/2f6721e1-8970-4269-b22a-fceda758a987)

3. Donate page - If the user is connected to a matching-eligible chain - we show the page as normal for QF projects
![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/8f2eea1b-18df-4a9d-89db-4f512abcf341)

4. Donate page - if the user is connected to a chain that is not eligible for matching in the QF round, we show the normal donate page (for non QF projects), but with an extra message (where the red box is in my image) that says "Make your donation eligible for matching. Switch to < Polygon >. *Switch Network*"

<img width="1061" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/75490971/b845ce28-ac9f-47cd-8039-2ea40325f460">

Anything I'm missing @MoeNick @divine-comedian @mosaeedi

**Comment by mosaeedi** [comment]
So here is my thought about these different areas to promote eligible chains.

1. we can add a line there, but I think it doesn't have much value since that space is already crowded, and user would miss that. 
My suggestion: We might use this space to promote the eligible chain 

<img width="809" alt="Screenshot 2023-09-14 at 9 52 49 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/3aa4b380-3d86-493f-abc5-1e7e587d25ee">

2. I think it's better to add a line somewhere here to specifically say which chains are eligible instead of promoting "project recipient addresses for the eligible chains" because it might give the user the idea that this specific address is eligible rather than a chain!

3. ok.

4. Sound's good.

**Comment by laurenluz** [comment]
1. It's going to make things a lot more complicated if we start messing with the gitcoin passport banner. there are already a lot of conditions and variations... and this requires the user to do another action beyond donating. also, we may run rounds where multiple chains are eligible for donating, yet not ALL. this would make the copy on some banners really long.

I hear you on not making that other space more crowded, but maybe there is another spot?

There are the banners, so you recall:
<img width="1429" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/75490971/b1ebbd42-e748-4cca-b97b-203b5c20eb3e">

The rest sounds goods to me.

**Comment by mosaeedi** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb1dyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4001a595ab6a4abe77171762677c37b3f69533de/Screenshot%202023-09-18%20at%204.07.46%20PM.png)

Take a look at the design here -> [Figma link](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=4337-70577&mode=design&t=SgUirw4He0TqVVOx-4)

**Comment by mosaeedi** [comment]
When user is not on the eligible network, we show this message box...

<img width="766" alt="Screenshot 2023-09-18 at 6 26 19 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/950f50f9-c18f-44a3-a57e-42e2e4ac6675">

By taping on the Switch network, we will show the Switch network modal but only list the eligible networks for user to choose!

<img width="483" alt="Screenshot 2023-09-18 at 6 29 02 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/92ea1eaf-9430-47de-991e-4561eb932878">

**Comment by mosaeedi** [comment]
Take a look at the designs -> [Figma link](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=4334-51130&mode=design&t=779HUnPv9ppR6gCW-4)

**Comment by alireza-sharifpour** [comment]
> @alireza-sharifpour or @MohammadPCh - can you check this one out?

Is the backend ready for this issue? I think we need a way to understand eligible chains. @divine-comedian

**Comment by laurenluz** [comment]
yes @alireza-sharifpour, in #1126 carlos prepared the backend.

**Comment by alireza-sharifpour** [comment]
Thanks @laurenluz,
How can we get eligible QF chains? @CarlosQ96

**Comment by MoeNick** [comment]
@mohammadranjbarz can direct you the field.

**Comment by CarlosQ96** [comment]
When you fetch the project you should be able to get the QfRound relationdata and inside that one the attribute ```eligibleNetworks``` which is an array of integers with the network identification.

**Comment by CarlosQ96** [comment]
For example in projectbyslug you can:
```
qfRound {
          id
          name
          isActive
          eligibleNetworks
        }
```

**Comment by CarlosQ96** [comment]
but let me know which query in specific you need it and ill check and let you know or add it if its required. @alireza-sharifpour

**Comment by maryjaf** [comment]
When I create a round and set chainId on op & goerli and donate to a project on gnosis 
after completing donation flow in donation  success page the the Quadratic funding box is shown as below pic,
I think It's better that this part also be changed @laurenluz @alireza-sharifpour 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc1hmIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--59a1e1d7ea79a443787d49065bc7da265558c3cd/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc2ZmIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--aedf6f76afc5602f6e2432c9f94ce4174176b7e6/image.png)

**Comment by maryjaf** [comment]
Switch network doesn't work on mobile but it is ok on desktop

**Comment by laurenluz** [comment]
@alireza-sharifpour - can you please check & fix these 2 issues asap? :)
cc @MohammadPCh

**Comment by alireza-sharifpour** [comment]
> Switch network doesn't work on mobile but it is ok on desktop
> 
>  RPReplay_Final1695824228.mp4

Thanks @maryjaf for testing.
Is it related to this specific issue?
Is Switch Network modal working on other parts of the Dapp on your iPhone? @maryjaf

**Comment by maryjaf** [comment]
> > Switch network doesn't work on mobile but it is ok on desktop
> > RPReplay_Final1695824228.mp4
> 
> Thanks @maryjaf for testing. Is it related to this specific issue? Is Switch Network modal working on other parts of the Dapp on your iPhone? @maryjaf

No it's related to switch network problem on mobile on wagmi.vercel branch

**Comment by alireza-sharifpour** [comment]
@maryjaf 

Can you please test this issue again on staging?

**Comment by maryjaf** [comment]
> I think It's better that this part also be changed and if user donates to a project on unsupported network in a round, Quadratic funding box isn't shown in this page @laurenluz @alireza-sharifpour

ُThanks @alireza-sharifpour This issue has been resolved
Switch network is work correctly on Metamask browser
and copy changes be applied on project page and  it is ok on both mobile and desktop
