### ISSUE TITLE
Small SEO content changes on Homepage and Project page

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-dapps-v2#318]

**Comment by ahmadabugosh** [comment]
Yeah good point @laurenluz ! SEO is a tradeoff between the keywords we want to rank for that get traffic and what makes sense for our brand, so we should definitely change it if it doesn't make sense. We could also add some of these in the Meta Descriptions instead. 

I guess mainly we should decide what is a one liner we can use across these pages that replace "social good projects and charities"?

**Comment by laurenluz** [comment]
@ahmadabugosh - what are the most important keywords we want in there? if you let me know, I'll make some suggestions on the dapp

**Comment by MoeNick** [comment]
@laurenluz @ahmadabugosh is there any updates on this?

**Comment by laurenluz** [comment]
On homepage, under "Explore":
"Donate crypto directly to for-good projects."
![image](https://user-images.githubusercontent.com/75490971/161578917-40078927-2447-4d53-9200-49f8683be01d.png)

On projects page:
"Support for-good projects, nonprofits & charities with crypto donations. Give directly with zero added fees. Get rewarded when you donate to verified projects!"
![image](https://user-images.githubusercontent.com/75490971/161579221-fc62f2eb-ba3c-46a7-8ec3-4faffafbdc51.png)

I think that hits all the buzz words. Unless we get any other feedback from @ahmadabugosh I think we can just change it like that and call this done.

**Comment by ahmadabugosh** [comment]
@laurenluz Yes I think that's fine, I think as long as we mention "crypto donations" or "donate crypto" it's good
