### ISSUE TITLE
Accepting X links during verification form and changing twitter logo on Giveth

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3184]
**Describe the bug**
-Verification form 
X link ism't acceptable in verification form and changing  twitter logo
-Share & get rewarded
-Share
-Donation

**Screenshots**
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/7bef9706-e151-40ce-bdd9-76b6d0e8301b)
<img width="1286" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/dc69712a-87c7-4f6e-b6e1-81c8f5f771d6">
<img width="1410" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/46b56f19-fda1-4489-82a8-05718979e7b5">
<img width="615" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/bc1e1655-1db9-4deb-b069-11bca08f4772">
<img width="670" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/474fc43a-4f33-4fdd-bb8c-807fe9b1476f">

cc: @MohammadPCh @MoeNick @divine-comedian

**Comment by divine-comedian** [comment]
Oooh that's a sneaky one Mr. Elon!

**Comment by MoeNick** [comment]
Users were stuck on verification form! We got obliged to! 😀

**Comment by alireza-sharifpour** [comment]
It's ready for testing @maryjaf .

**Comment by maryjaf** [comment]
Plz check this @alireza-sharifpour 
unverified projects--> share
<img width="759" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/61520453-e643-4b8a-bf78-1478628e07f5">

**Comment by maryjaf** [comment]
Success Donation
<img width="1295" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/63a14988-6240-43e3-adc7-550cd1a62528">

**Comment by maryjaf** [comment]
Thanks @alireza-sharifpour this problem has been resolved
