### ISSUE TITLE
For non verified projects, it should not give me the "GIVbacks Learn more" prompt

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#319]
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/795340cd-1595-405d-b7c6-f49675c0e622)

**Comment by RamRamez** [comment]
for testing the PR #371:
1. Show givback for verified projects and hide for admins
2. show "View similar projects" and "Report an issue" for non-admin

**Comment by divine-comedian** [comment]
testing on `staging.giveth.io` 

I checked out a couple non-verified projects and the GIVbacks modal no longer shows. I can see only "Report Issue" and "View similar projects"

verified projects still show the givbacks modal 
this issue looks to be resolved! moving to done
