### ISSUE TITLE
MetaMask Wallet: Issues on GIVfarm

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3196]
On the GIVfarm: 

Wallet: MetaMask
Device: Pixel 7
Browser: Chrome 

While trying to harvest my rewards it totally fails and throws a JSON RPC-error that I cannot a reason for. 

While on the stake & lock features - the buttons for adding a percentage of my current balance do not work at all (25%, 50%, 75%... max) - clicking the buttons do nothing 

When I tried to use the round lock slider the giveth app crashed with a client-side error

https://github.com/Giveth/giveth-dapps-v2/assets/67759413/bc346736-f54c-45ca-86ef-59f977a1f7cd

https://github.com/Giveth/giveth-dapps-v2/assets/67759413/74b90458-4556-403b-b991-66fd57bdfab5

**Comment by divine-comedian** [comment]
Testing this out with MetaMask on desktop on staging I receive the same error - looks like it could be unrelated to wallet connect 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/5d25b2a3-60a8-4955-9209-976a56dbb689)

**Comment by MohammadPCh** [comment]
@divine-comedian 
I made some improvements 3 days ago, and now I can't reproduce this bug on my machine, could you please check it again?

**Comment by maryjaf** [comment]
In harvest flow I have a problem like this:


Uploading RPReplay_Final1695718880.mp4…
