### ISSUE TITLE
Responsive Header: Remove title in the header in shorten menu

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#321]
According to design,  mobile view, I think we can remove title beside the Shorten menu icon.

I can see this as an example:
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/3745f49a-e1d4-474b-b75b-92aa3bf56724)

**Comment by divine-comedian** [comment]
testing on mobile w/ metamask browser 

headers/navbar show up as such 

![Screenshot_20220330-140434.png](https://user-images.githubusercontent.com/67759413/160921623-02e55197-a889-4dd8-9528-84a20bf1e6a7.png)

![Screenshot_20220330-140411.png](https://user-images.githubusercontent.com/67759413/160921640-bdbd1509-3f4a-452a-b23f-254d386eefd7.png)

looks to match the spec with the omission of the notification circle - assuming we don't have notifications implemented yet.



checking the figma that @mosaeedi  posted it seems we keep the text in the bar

**Comment by divine-comedian** [comment]
moving this issue to DONE!
