### ISSUE TITLE
Share & Get rewarded on Project details

### ISSUE THREAD

**Issue by mosaeedi** [Giveth/giveth-dapps-v2#3211]
## Public view

This is how it should look like on mobile devices.
**Note:** The like button, doesn't need to show the amount of like on mobile

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaUxEIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--130f9753f4bdbf26636304daab2e3647615d2142/Screenshot%202023-09-21%20at%204.25.11%20PM.png)

### Full-screen modal

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdVhEIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--67087f62bb3a329cf818eeff8e414977ea5d435b/Screenshot%202023-09-21%20at%205.52.06%20PM.png)

## Owner view

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaEhFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--15a9d5b5c0c590a544f3b3031ca3a1c638777e21/Screenshot%202023-09-21%20at%206.10.25%20PM.png)

And the modal for showing the share is the same as public!
[Link to Figma](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=4265-55787&mode=design&t=IzjXCJYImCazp93U-4)

**Comment by MoeNick** [comment]
@alireza-sharifpour Owner view has not been implemented yet
@maryjaf FYI.

Public view is on production and QAed.

**Comment by MoeNick** [comment]
It was implemented 2 weeks ago, and it's live on production so I close this.
