### ISSUE TITLE
Exodus Wallet (Android/Desktop/Chrome/Brave): Cannot Connect 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3220]
Currently when I try to connect using Exodus Wallet it will not allow me to connect at all. It will allow me to scan the QR from desktop or pull up the app from my mobile browser.. however when I do so the exodus wallet produces an error saying chain not supported. 

Exodus Wallet supports:
 Ethereum, Solana, BNB Smart Chain, Polygon, Avalanche, and Fantom networks.

So while users should not be able to connect on Gnosis, Goerli, Celo.. Optimism etc... we should be able to allow them to connect by Polygon and Ethereum 

https://github.com/Giveth/giveth-dapps-v2/assets/67759413/985fd722-9e7e-4aa1-841c-b3da73dcab50

**Comment by MohammadPCh** [comment]
@divine-comedian Thanks, for reporting this,
actually, we don't have enough access to manipulate the rainbowkit functionality. we only configured the rainbow kit as it mentioned in its doc.

**Comment by divine-comedian** [comment]
> @divine-comedian Thanks, for reporting this, actually, we don't have enough access to manipulate the rainbowkit functionality. we only configured the rainbow kit as it mentioned in its doc.

Okay - I emailed exodus support - maybe they know how to figure this out.

**Comment by MohammadPCh** [comment]
Thanks @divine-comedian  as we decided to try web3modal instead of rainbowkit I hope all issues will be fixed.
