### ISSUE TITLE
Add pyUSD & GLO to the givbacks token list

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#3221]
we need to wait a week to see if there is push back here:

https://forum.giveth.io/t/givbacks-token-list/253/41?u=griff

but assuming there is no push back

GLO is on Mainnet, Polygon OP, and Celo and it has the same address on every chain :-D

https://etherscan.io/token/0x4f604735c1cf31399c6e711d5962b2b3e0225ad3
https://polygonscan.com/token/0x4f604735c1cf31399c6e711d5962b2b3e0225ad3
https://celoscan.io/token/0x4F604735c1cF31399C6E711D5962b2B3E0225AD3
https://optimistic.etherscan.io/token/0x4f604735c1cf31399c6e711d5962b2b3e0225ad3

pyUSD is only on Mainnet
https://etherscan.io/token/0x6c3ea9036406852006290770BEdFcAbA0e23A0e8

**Comment by MoeNick** [comment]
@mohammadranjbarz can we support the price of them if we add them in Admin?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz can we support the price of them if we add them in Admin?

@mateodaza  maintains this ( and Amin but I guess we don't have Amin anymore), so Mateo knows more

**Comment by maryjaf** [comment]
Thanks @mohammadranjbarz 
I set "is stable coin: true" for DrGIV3 on goerli on stg and the result was expected 
<img width="1405" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/2728381c-d5a3-4695-89d4-0d5b0c91a460">

**Comment by mohammadranjbarz** [comment]
@GriffGreen  @divine-comedian  I added these tokens to production, And as I talked with Mitch in DM, I set them stable coin so we assume they always have **1$** price
