### ISSUE TITLE
Add links to homepage first fold 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3222]
Follow discussion in #2667 we should add a link to this onboarding guide somewhere on our homepage 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/e48a70dc-c7f7-4174-b1b2-f359a6a742c2)

In the original homepage design on figma we had links under each of those three subheadings 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/4ad9b1f7-983f-4276-a6fa-304c1419bf22)

We can bring these back and keep it simple

### Verified projects 
HOW IT WORKS --> https://docs.giveth.io/dapps/projectVerification/

### Donor Rewards
LEARN MORE --> https://docs.giveth.io/giveconomy/givbacks

### Easy Onboarding 
GET STARTED --> https://giveth.io/onboarding

**Comment by MoeNick** [comment]
I removed Ramin as he's fully on Asymmetry and we should meet our deadline soon. next week.

**Comment by MoeNick** [comment]
@MohammadPCh can take a look as his plan for this week is light so far.

**Comment by divine-comedian** [comment]
What's the latest on this one? looks like @RamRamez has a PR already

**Comment by maryjaf** [comment]
it's better that after submiting the email address user see a related mesage
Now the behavior of sysyem is like below video 
https://github.com/Giveth/giveth-dapps-v2/assets/111529185/39bd7874-fd55-4b33-a5bd-c54af7d741c9
@RamRamez

**Comment by MoeNick** [comment]
@maryjaf 
 I can see this
 
![image](https://github.com/Giveth/giveth-dapps-v2/assets/80677512/de9d2ea5-9876-4f12-bb74-4cc4601f2378)


it's good in my point of view

**Comment by maryjaf** [comment]
> Now the behavior of sysyem is like below video
> https://github.com/Giveth/giveth-dapps-v2/assets/111529185/39bd7874-fd55-4b33-a5bd-c54af7d741c9
> @RamRamez

I see like this screen record

**Comment by divine-comedian** [comment]
It also appears fine for me 
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/da0ef4ce-c0a5-455f-81ba-0652cf5819eb)

Perhaps try with a different browser @maryjaf ?

**Comment by maryjaf** [comment]
I've checked on chrome & safari
