### ISSUE TITLE
"Sign in to Giveth" grammar and text

### ISSUE THREAD

**Issue by danelsuga** [Giveth/giveth-dapps-v2#323]
Under the "Create a Project" button, you have the "Sign in to Giveth" page.

Should read: Please sign in to your account and start using Giveth. (Lowercase "sign".)

ALSO:

When you click on any of the non-Ethereum sign-in possibilities, I believe the text is incorrect?

Currently: 
Sign in
Your blockchain wallet in one-click

Is that deliberate? Or it should read: 
Sign in
to your...
(add "to" and "lowercase "your".)

Or is it announcing "[Here is] your blockchain wallet in one click"? I find it looks peculiar, if so. (But my fix also looks peculiar.) Maybe if there was a space between "Sign in" and "Your blockchain wallet..."

MEANWHILE: remove dash from "one click". The command is literally asking for one click of the mouse. With a dash, the phrase is turned into an adjective. We want to keep it a noun (the "click"!) and have one of them. :)

![image2.jpeg](https://images.zenhubusercontent.com/6066d509782b4d63df5cd761/21f7b547-dd9a-4667-87fe-8c20fa1e58a4)![image3.jpeg](https://images.zenhubusercontent.com/6066d509782b4d63df5cd761/b381af82-3de5-4009-be83-e4dc8f640309)

**Comment by RamRamez** [comment]
First one (Lowercase "sign") is resolved in PR #334 
We can't change the second one, because it's the Torus modal.

**Comment by divine-comedian** [comment]
grammar fix looks to be resolved! 
![image](https://user-images.githubusercontent.com/67759413/160965733-c403bb80-22d6-4c64-b6f6-b8499a855fe6.png)

torus modal appears to be uneditable for other text fixes, moving to done!
