### ISSUE TITLE
Wallet Connect issue on Rainbow

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3241]
**Describe the bug**
I couldn't connect wallet by Rainbow and got an error like below pic 

Device: Mobile(iPhone)
Browser: chrom & safari
Rainbow 

**To Reproduce**
1. Go to '[wagmi vercel](https://givwagmi.vercel.app/)'
2. Click on 'Sign in '
3. select Rain bow
4. Tap on connect
5. see error

**Screenshots**
![IMG_7931](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/4516fb3e-4c42-4a9e-885a-894121e607c0)

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/a293498f-e3cd-47aa-9592-631901da68b1

cc: @MohammadPCh

**Comment by divine-comedian** [comment]
related to #3197

**Comment by divine-comedian** [comment]
Check out this one I mentioned Cherik:
https://www.rainbowkit.com/docs/custom-wallet-list#rainbow

**Comment by MohammadPCh** [comment]
@divine-comedian This P2 issue currently has no assignee. Should we follow up on it or close it?

**Comment by divine-comedian** [comment]
> @divine-comedian This P2 issue currently has no assignee. Should we follow up on it or close it?

Sure now it's assigned to you :)
