### ISSUE TITLE
Some times Metamask connect wallet flow is buggy on mobile

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3242]
Some times connect wallet flow is buggy 
Device: iPhone
Browser:chrome
Wallet: Metamask 

plz check these two videos @MohammadPCh 

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/fbb789f4-75c2-49b2-b704-f32c3b0f07e5

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/6e6d9ba4-fbd8-4cc0-b34a-ceb7487e3879

_Originally posted by @maryjaf in https://github.com/Giveth/giveth-dapps-v2/issues/3116#issuecomment-1735143123_

**Comment by MohammadPCh** [comment]
Thanks @maryjaf We decided to try web3modal instead of rainbowkit. I hope all issues will be fixed.
