### ISSUE TITLE
Bug in maximum balance on donation page

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3243]
I set the maximum balance for donate to a project , when I tap on Donate I get this error "You don’t have enough funds!" although I set the available balance in this page

I get this error with this account 0xD5db3F8B0a236176587460dC85F0fC5705D78477
But the same scenario with this account is ok 0xcd192b61a8Dd586A97592555c1f5709e032F2505 and I couldn't find what the problem is 

**Screenshots**
<img width="1389" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/497e75bf-dddd-4f36-bcf6-9bbb9114b06c">

<img width="1237" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/8ad8deed-048b-4473-96b6-bfa19edb4f93">

**Comment by MoeNick** [comment]
@maryjaf  I put this in QA FYI

**Comment by maryjaf** [comment]
Thanks @MohammadPCh this issue has been resolved on production
