### ISSUE TITLE
GIVbacks page - when I'm connected to Polygon or non GIVbacks-eligible network, GIVbacks dates are wrong

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3248]
This doesn't make sense. Dates are wrong (i.e. the same). My wallet is connected, I'm signed in, and connected to Polygon network. 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/8dfb7c1e-1eb5-4962-98b0-6914b70921db)

If I connected to Optimism network, I see the same thing... but if I REFRESH on Optimism network, it looks right:

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/5b3534a6-901d-4d85-b447-6b0044665b83)

We should be showing the correct dates regardless of what chain the user is on, and regarless of whether or not they are signed in.

https://giveth.io/givbacks

@divine-comedian @MoeNick - who can I assign to this? usually I would assigned Cherik, but I'm not sure of our flow now.

**Comment by divine-comedian** [comment]
Tested it on https://giveth.io/givbacks

connected with polygon - round is showing correct number. 
connected with mantle and still shows correct, I'm assuming this was fixed because I can't repro
