### ISSUE TITLE
GIVpower - what is NaN and why is it messing with my GIVpower amounts?

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3251]
Testing on staging...

@maryjaf is boosting this project with NaN GIVpower, so the total GIvpower on the project is NaN.. and the project is not being sorted corrected. What is NaN and why is it breaking things?

@maryjaf - do you know?

This project: https://staging.giveth.io/project/how-many-photos-is-too-many-photos?tab=givpower

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdFhrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--24dd56102715429b8600e71b32e4839743470a4e/image.png)

**Comment by maryjaf** [comment]
There was a bug about this my account **(maryam account 3)**, that it was resolved on this branch
https://givwagmi.vercel.app/project/how-many-photos-is-too-many-photos?tab=givpower
 But it wasn't merged on stg, I talked with Cherik and said it will be fixed on stg by next deployment 

<img width="1281" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/4873bce0-687b-45fc-b8b7-b1d7d0c4f750">

**Comment by laurenluz** [comment]
oh ok great! Thanks Maryam 🙏

**Comment by MoeNick** [comment]
@MohammadPCh will merge it on staging and removing it from wagme branch.

**Comment by MohammadPCh** [comment]
@maryjaf Ready for test.
