### ISSUE TITLE
Conditional Verification modals on project owner view of project 

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#3255]
I was trying to onboard a project and i couldn't find the verification button! Why is it hidden in a drop down... soooooo bad... we want them to verify!

I literally thought they werent able to verify until they were listed. I'm actually embarrassed now.

<img width="412" alt="Screenshot 2023-09-28 at 10 40 22 AM" src="https://github.com/Giveth/giveth-dapps-v2/assets/14945613/9e1a81ae-353c-4f7c-a986-df9d103464c3">

Please add back the buttons for Edit and Verify!

I wonder if we should have them start verifying from the project splash page too? Right after they create the project.

Right now it is REALLY bad UX and i'm sure we have a huge drop of rate from projects creating their project and applying for verification.

**Comment by divine-comedian** [comment]
Sure @mosaeedi can take a look and revert it back

**Comment by mosaeedi** [comment]
<img width="1312" alt="Screenshot 2023-10-04 at 1 02 38 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/a1eb5e9d-c738-43e3-bd2c-3d854a1b0be8">

Right now, when a project is not verified yet, we show a message below the project banner to encourage them to verify their project.
We can just add a button here to make it easier for user to apply for verification. 

### It can be like this...
<img width="676" alt="Screenshot 2023-10-04 at 1 02 08 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/6e7a8b7d-fa73-4772-a707-dd3c8698b8ca">

**Comment by mosaeedi** [comment]
Regarding the Edit button, we can still keep it under the project action dropdown to keep the page clean.

**Comment by mosaeedi** [comment]
<img width="1372" alt="Screenshot 2023-10-04 at 1 07 52 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/c91e8270-8930-41f6-96a9-14fccf8554ab">

**Comment by divine-comedian** [comment]
I like this! let me chase @GriffGreen to see if this satisfies his concerns.

**Comment by divine-comedian** [comment]
Griff says it's great! Let's go for it! @mosaeedi

**Comment by mosaeedi** [comment]
So, we will add only the **Verify Project** button to this card verify project card.

<img width="910" alt="Screenshot 2023-10-07 at 3 25 28 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/c5f724ad-0081-4866-b561-2eb979fd8486">


[Link to Figma](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=4483-27571&mode=design&t=WAAEDIZ8mdgs6a4R-4)

**Comment by RamRamez** [comment]
FYI in PR #3368,
1. I removed the verify button from dropdown
2. "Take your project to the next level with Verification" message will be shown in all verified projects (even if the project is deactivated)

**Comment by divine-comedian** [comment]
@RamRamez 

We can reference this issue for when we should show the verify button:
https://github.com/Giveth/giveth-dapps-v2/issues/3081

Currently when a project is deactivated we do not give the user the option to verify nor to share their project - So we should not show this component when the project is deactivated.

If the project is in draft status we should not show the verify component either.

**Comment by RamRamez** [comment]
@divine-comedian In /verification view, we allow owners to continue verification process for deactivated projects, it's better to follow up /verification in another issue.

![image](https://github.com/Giveth/giveth-dapps-v2/assets/73441857/289f97c7-d1f5-4f35-8ed5-3846a0d013ad)

What should we show instead of inline verification toast for deactivated and draft projects?

**Comment by divine-comedian** [comment]
Nice catch Ramin - I'll make another issue for design 

For now let's make sure the verify button isn't available from the drop down menu

**Comment by RamRamez** [comment]
Yes, the verify button is removed from the dropdown.

**Comment by maryjaf** [comment]
when I submit a verification form  or my verify request has been rejected, "Verify project" button is still  shown , is this accepted?
<img width="1417" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/e363d7ae-9bd4-4f97-bb72-bd8408911c9a">

**Comment by MoeNick** [comment]
It's a design bug @mosaeedi 
In the previous view, we handled all verification statuses in the `verify project` button, and now it's affected. 

- Draft: Cant apply
- Active: can apply 
- Deactive: can't
- canceled: can't

- Listed: can
- Unlisted: can 

When they apply or complete the application we have:
- resume 
- waiting for review (submitted)
- rejected
- verified
if not above: they can apply! 
so I suggest we handle it in a button, or move the apply button o the right side. 

FYI: @divine-comedian

**Comment by mosaeedi** [comment]
I'm working on it and trying to find a solution!

**Comment by RamRamez** [comment]
For now, I've removed "verify project" button for cancelled, deactivated and draft projects and we still have "Take your project to next level" component (without button).
(PR #3405)

**Comment by divine-comedian** [comment]
> when I submit a verification form or my verify request has been rejected, "Verify project" button is still shown , is this accepted? <img alt="image" width="1417" src="https://user-images.githubusercontent.com/111529185/278811523-e363d7ae-9bd4-4f97-bb72-bd8408911c9a.png">

This is accepted - projects can re-apply for verification if they improve their application information or provide more information

**Comment by maryjaf** [comment]
> This is accepted - projects can re-apply for verification if they improve their application information or provide more information

Now on production if a project has been verified after that "Verify your project" isn't shown again
This logic should be changed ?
<img width="1440" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/f9a64ddf-79ae-411f-b263-5f49193b3c76">

**Comment by divine-comedian** [comment]
If the project has already been verified then they should not be shown the verification option should not be shown again. 

This looks correct according to your screenshot unless I am not understanding something..?

**Comment by MoeNick** [comment]
@mosaeedi we need a quick fix for this

**Comment by mosaeedi** [comment]
I've put all of the different project status design here -> [Figma link](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=4914-11677&mode=design&t=oMYF1kBcEEa8eOKq-4)

**Comment by maryjaf** [comment]
> Sorry for the delay!
> 
> Please take a look here -> [Figma link](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=4896-56432&mode=design&t=oMYF1kBcEEa8eOKq-4)
> 
> I've added a new copy for different situations, @divine-comedian. Please take a look and verify!
> 
> CC: @MoeNick

Thanks‌ @mosaeedi , I have a few questions
When the project has been verified, will we show it with the same design as before?
with "Boost" option
<img width="1384" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/d82cc684-f43c-440d-ba44-2f94df2aa9da">


And if the status of the verification form is changed by admin user  to "make eligible by user", what will the design look like?

<img width="1162" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/339ae3c3-d406-4d8d-87f3-145d63ed6d48">

**Comment by mosaeedi** [comment]
Thanks @maryjaf 
About the first part, I made a mistake and removed that banner! I've added it again. When the project is verified, we should show the Boost banner.

[Link to Figma ](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=4896-12839&mode=design&t=oMYF1kBcEEa8eOKq-4)

<img width="988" alt="Screenshot 2023-11-27 at 6 30 32 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/7682856d-b39b-4731-a65a-2b5bcb0bd56d">
CC: @divine-comedian 


Regarding the second part of your comment, I didn't understand what you were saying!

**Comment by maryjaf** [comment]
> Regarding the second part of your comment, I didn't understand what you were saying!

When the user submits the form, the status changes to Submitted, then the admin user can confirm or reject the form or choose the "make eligible by user" option so that user can change and submit the form again

**Comment by mosaeedi** [comment]
Thanks @maryjaf 

I've added this one.

<img width="1032" alt="Screenshot 2023-11-27 at 10 02 38 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/d54eadf6-77a0-490f-bbe6-b256d0ef5563">

@divine-comedian Please check the copy!


[**Link to the Figma**](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=4896-56432&mode=design&t=DUJRES2UG4DHUFl3-4) for quick access

**Comment by RamRamez** [comment]
@jainkrati I can take this issue

**Comment by RamRamez** [comment]
@divine-comedian @mosaeedi What is url of "learn more" for each state?

**Comment by divine-comedian** [comment]
# Links 
Here are the links for the following headers: 

### Application Incomplete
Learn More -> https://docs.giveth.io/dapps/projectVerification

### Verification in Progress
Learn More -> https://docs.giveth.io/dapps/projectVerification

### Verification Rejected 
Learn More -> https://docs.giveth.io/dapps/projectVerification

### Donors get rewarded with up to 80% of the donation value!
Learn More -> https://docs.giveth.io/giveconomy/givpower

### Project Unpublished
Learn More -> https://giveth.io/onboarding/projects

### Take your project to the next level with Verification!
Learn More -> https://docs.giveth.io/dapps/projectVerification

### Project Deactivated 
removed the Learn More link (no appropriate documentation for this)

### Project Cancelled 
Learn More -> https://docs.giveth.io/dapps/listedUnlisted#cancelled-projects
Discord -> https://discord.giveth.io

**Comment by RamRamez** [comment]
@divine-comedian When project is cancelled, we show this on single project view:
![image](https://github.com/Giveth/giveth-dapps-v2/assets/73441857/3358974d-61b5-45cf-bdec-a9f2e28e5300)

**Comment by divine-comedian** [comment]
Got it, let's keep it as is then for project cancelled

**Comment by maryjaf** [comment]
The previous action related to "verify your project" in project action should be removed by developing this new design ?
<img width="1686" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFk1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ebdecb2310d9625d6306b87b8ce0a89e7b8ffbf6/image.png" alt="image.png" />
@divine-comedian @mosaeedi

**Comment by maryjaf** [comment]
when The verification form request has been rejected by admin user, the status changes to declined and by tapping on "verify button" the below message is shown that contact with support 
but in project page we say to user that try again for submitting form , is that ok ?
@divine-comedian @mosaeedi 
<img width="1332" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/3f64e120-277d-4dbc-bd1b-dccd1aae9539">

<img width="1437" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/527d5f16-7b41-40f2-b6a7-b5d737fb3d75">

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/4b427232-8a7f-47b2-b1d4-c7e48802f2e9

**Comment by maryjaf** [comment]
One question , it isn't exactly related to this issue 
In the admin panel, the admin user cannot change the status of form after the rejection and I don't know how the user can reapply the form after being rejected
You know ? @MoeNick

**Comment by maryjaf** [comment]
When the user apply his request and the admin user select "make eligible by user" option 
the below copy is shown, is this ok ? because in this condition the user has completed and submited  the form and we show "You haven’t submitted your verification application! "
<img width="1422" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/65f1b0e6-34f5-4d87-bfb1-43095a64e58a">
@divine-comedian

**Comment by RamRamez** [comment]
> When the user apply his request and the admin user select "make eligible by user" option the below copy is shown, is this ok ? because in this condition the user has completed and submited the form and we show "You haven’t submitted your verification application! " <img alt="image" width="1422" src="https://private-user-images.githubusercontent.com/111529185/288673967-65f1b0e6-34f5-4d87-bfb1-43095a64e58a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5Mzg3NjAsIm5iZiI6MTcwMTkzODQ2MCwicGF0aCI6Ii8xMTE1MjkxODUvMjg4NjczOTY3LTY1ZjFiMGU2LTM0ZjUtNGQ4Ny1iZmIxLTQzMDk1YTY0ZTU4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwN1QwODQwNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNjBmZTkwMzYyYTZiZWM4MDkzM2Y0YjFmOTFlZDVmZTE4NmI1NjA5NDBmYTUzODJmY2U3YTc0NWVkMjQ1Yzg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7JGOWXXWic4iEyDaYGM5hAGfbmjP2AFmiD5hAVplT9I"> @divine-comedian

When admin selects "make editable by user", the form application changes from submitted to draft, and user is allowed to change it, so toast component in project view will change to "Application Incomplete"

**Comment by RamRamez** [comment]
> in new design when the verification status is "submitted", the "verify" button is not shown, is it ok to show this action in project action when status is "submitted " or it should be removed from project actions too? <img alt="image" width="1440" src="https://private-user-images.githubusercontent.com/111529185/288664405-55405fd2-0f2f-42af-9770-ba21bd0046d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5Mzg3NTksIm5iZiI6MTcwMTkzODQ1OSwicGF0aCI6Ii8xMTE1MjkxODUvMjg4NjY0NDA1LTU1NDA1ZmQyLTBmMmYtNDJhZi05NzcwLWJhMjFiZDAwNDZkOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwN1QwODQwNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNzc2NmRmNjE3MjdiNTEzYWE0NTY3YzkyMDVlNDk0NjM1ODJkMjMzYzA4OTEyN2E1ZjIzNWMwZDQ1ODgxN2M4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Sbmxpky1Fj0pvpuk1BHxHVbgxPkLzhVtvJYiYOHSzjA">

Thanks @maryjaf. I will fix it.

**Comment by divine-comedian** [comment]
Ooops! Looks like it wasn't clear to me how it works - 

So @RamRamez  - looks like then when the application is rejected we should not let them continue - since they are not allowed to apply when status is rejected 

I will fix the copy and component

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/c5eaaf31-108f-41ec-b030-96f1b2679f92)

**Comment by maryjaf** [comment]
Thanks @RamRamez two item of the current problems have been resolved
The only remaining problem is to decide on this:

Now the image below is displayed in two modes
1- When the user starts to register the form but does not complete it, in this case the displayed text is correct
2- In the case where the user submit the form and the admin tao on "make eligible by  user" and changes the status of the form to "draft"
In this case, it seems that the text is not correct
<img width="1966" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHhJQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7928262636da96d8fcfbb2a45518d317fc83ed3b/image.png" alt="image.png" />

For these two scenarios the status of form is "Draft"
Either a text should be replaced that covers both scenarios  or a different status should be set from backend 
@divine-comedian

**Comment by MoeNick** [comment]
I think its not worth to add new statuses, verification team definitely contact the project owner and let them know they changed the status so they can re-apply again.  

In this case, i only vote to text edits in draft status.

**Comment by divine-comedian** [comment]
I'll draft some new text Monday

**Comment by divine-comedian** [comment]
@RamRamez  

Here's the updated view/text for when an application is in draft 

https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=4896%3A56432&mode=design&t=P5SPZBimG7493aqw-1

I also added another badge to capture the draft status that exists already in the back-end for a verification application 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/f198cb8e-20c9-49c8-94f2-409014af643e)

**Comment by RamRamez** [comment]
@maryjaf I fixed three issues in PR #3480:
1. Badges in my projects
![image](https://github.com/Giveth/giveth-dapps-v2/assets/73441857/ce7903c4-a480-4bd3-961c-42035bf5227d)
2. Submitted and not verified badge colors
3. Rejected copy in single project view

**Comment by RamRamez** [comment]
There's no way to publish or edit a draft project from single project view. We should add a button for editing the project in project actions or toast component.
@divine-comedian @mosaeedi 
![image](https://github.com/Giveth/giveth-dapps-v2/assets/73441857/602556f1-eeda-445b-8327-7fd6db463c0c)

**Comment by maryjaf** [comment]
> There's no way to publish or edit a draft project from single project view. We should add a button for editing the project in project actions or toast component.

There is this button, but I agree with you to change this , in previous changing of project action I suggested that a little bit change be considered  for this button but finally it was approved 
<img width="1352" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/c5cc93e0-352d-43f8-845d-688bf05746f5">

**Comment by divine-comedian** [comment]
@maryjaf @RamRamez - we can forget about the issue you raised on the editing project from preview - we assume users will scroll down to preview their project description & categories and will see the button. 

Let's focus on finishing this issue as defined and move on

**Comment by maryjaf** [comment]
When will you  deploy these changes on the STG? @RamRamez

**Comment by RamRamez** [comment]
> When will you deploy these changes on the STG? @RamRamez

The PR is waiting for code review.
