### ISSUE TITLE
Project Creation Success page should have the second call to action be Verify your project

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#3256]
<img width="1398" alt="Screenshot 2023-09-28 at 10 39 45 AM" src="https://github.com/Giveth/giveth-dapps-v2/assets/14945613/4e1af91b-d91c-4dcc-a117-84e5908e9b33">

Can we replace the view project button with "Verify your project" and have it link to there verification link e.g. https://giveth.io/verification/testing-for-verification

**Comment by divine-comedian** [comment]
@mosaeedi 

What is the update on this issue?
