### ISSUE TITLE
timezonedb blocks user

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapps-v2#326]
timezonedb api blocks user

**Comment by laurenluz** [comment]
@aminlatifi can you test this? I don't understand how.

**Comment by aminlatifi** [comment]
If you machine time is not synced, but the reward is shown correctly it means that it works as it should

**Comment by aminlatifi** [comment]
> If you machine time is not synced, but the reward is shown correctly it means that it works as it should

@laurenluz
