### ISSUE TITLE
Use web3modal instead of Rainbowkit

### ISSUE THREAD

**Issue by MohammadPCh** [Giveth/giveth-dapps-v2#3265]
Since the RainbowKit's various issues on mobile, we need to change it and use another package.

**Comment by MoeNick** [comment]
@maryjaf is testing on the preveiew 
we may test all scenarios with mobile.
she's checking the metamask for now (cherik suggestion) for the first step.

**Comment by maryjaf** [comment]
https://github.com/Giveth/giveth-dapps-v2/assets/111529185/548d1664-e4b4-4d30-a73e-e0b05714cd42

Connect wallet with MetaMask is ok but there is a problem in sign in flow 
Plz check video @MohammadPCh 

Device: iPhone
Browser: safari
MetaMask

**Comment by maryjaf** [comment]
Strange thing happen that I don’t understand.
The initial sign in and connect wallet that it was ok in previous video , it isn’t ok in below video 
Browser :safari

Uploading RPReplay_Final1696234750.mp4…

**Comment by maryjaf** [comment]
Strange thing happen that I don’t understand.
The initial sign in and connect wallet that it was ok in previous video , it isn’t ok in below video
Browser :safari

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/c48a4049-6ef7-419a-a1ff-275432ca4cc9

**Comment by maryjaf** [comment]
I couldn’t complete a donation flow and it remains loading 
MetaMask
Chrome

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/e72c7498-6792-45c9-93bd-69e67128ab88

**Comment by maryjaf** [comment]
> I couldn’t complete a donation flow and it remains loading
> MetaMask
> Chrome & safari

This scenario also happens in stake flow

**Comment by divine-comedian** [comment]
Can you please confirm the deployment link for testing, I can't find it anywhere.

**Comment by maryjaf** [comment]
https://giveth-dapps-v2-git-add-web3modal-givethio.vercel.app/

**Comment by maryjaf** [comment]
> This scenario also happens in stake

I also can't complete stake flow on desktop (chrome,Metamak) but unstake was ok 
<img width="1347" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/ebbcf899-ed17-4990-a335-dbff7c99b452">

**Comment by maryjaf** [comment]
**Connect wallet** button in  GIVpower  and GIVback tab doesn't work, by tapping on this button nothing happens ,
plz check @MohammadPCh 
mobile and desktop
<img width="1432" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/d79a2919-7ced-4a51-aa07-64cf7e542901">

**Comment by maryjaf** [comment]
I haven't been able to stake on this branch, https://giveth-dapps-v2-git-add-web3modal-givethio.vercel.app/givfarm
I'm not sure the below pic is related to these changes or sth else, plz check this 
https://giveth-dapps-v2-git-add-web3modal-givethio.vercel.app/givfarm

Desktop / chrome 

<img width="1430" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/e59e3027-e334-4c70-8b35-ecd06a431ee8">
<img width="1328" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/dd46f769-b58a-433c-ac78-57d1fdfb6b90">

**Comment by divine-comedian** [comment]
@maryjaf - can you break these out into more clear issues - we also haven't done any dev work in the last few days
