### ISSUE TITLE
Modifying the display and pagination of the project card on the user page

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3268]
1-Go to 'https://staging.giveth.io/user/0xcd192b61a8dd586a97592555c1f5709e032f2505?tab=projects'
2- check showing project cards

**Screenshots**
<img width="1436" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/57c101cf-8981-4c3e-a6f3-6e7da349017a">

**Comment by Reshzera** [comment]
@maryjaf @LatifatAbdullahi This Issue is ready to be tested on the staging, could you please take a look?

**Comment by maryjaf** [comment]
Thanks @Reshzera It has been fixed
