### ISSUE TITLE
Adding updates to projects is a bit buggy

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3273]
We had a user report through twitter that the update process was buggy.

They mentioned that the picture took a really long time to buffer and then the udpate didn't post. I see that their update was actually posted twice though... and the image kind of repeated.

@maryjaf can you do a bit of testing on the update process and see if you can repeat these issues?

https://giveth.io/project/litter-token-ltk-we-pay-people-to-pick-up-litter?tab=updates

**Comment by divine-comedian** [comment]
@maryjaf - Can you test this please?

**Comment by maryjaf** [comment]
I've checked this issue, it is an old issue and the problem of posting an update twice has been resolved in another issue .
But the problem of taking long time to upload a picture is still exist but only for pictures with big size, I've tested this with a picture by 8 Mb and 200 Kb 

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/2057db15-f145-4e68-a541-c4eedb793e97


https://github.com/Giveth/giveth-dapps-v2/assets/111529185/7e5176bd-8c9f-4f45-bd38-bcfe72aa4587

**Comment by divine-comedian** [comment]
This is okay, we can follow up slow loading times elsewhere - let's call it done
