### ISSUE TITLE
Copy fix on donations tab estimated matching when there are no donations

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3278]
I find "Lead the way" really strange in this context. 

1. When the round is open, but no one yet has donated to the project a specific QF round, we should say "Be the first to give!"

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaWIvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2a1e5d6429c3a6fd9a0d34e311e2800302be54ca/image.png)

2. if the QF round has ended, and no one donated in it, we should say: "There were no donations in this round."
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaWYvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3b711f142b5f76562dca54c43da54b4600671582/image.png)

**Comment by laurenluz** [comment]
@MohammadPCh @alireza-sharifpour

**Comment by divine-comedian** [comment]
hot fixed in https://github.com/Giveth/giveth-dapps-v2/commit/a353098d318d6deedd5f9276331dbfde8e4a4a5c
