### ISSUE TITLE
Projects on Staging are NOT being sorted by GIvpower!

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3280]
[this project](https://staging.giveth.io/project/giveth-tour-bridge-the-world?tab=givpower) with 6.9 Million GIV is in position 4

whereas [this project](https://staging.giveth.io/project/herbs-and-drugs-and-tools-to-combat-sleepiness?tab=givpower) with 1.5 Million GIV is in position 1!

The project in position 4 also has RANK # 1... whereas the project in position 1 has RANK # 3. Something really weird is happening with the GIvpower sort.

What is happening?! @CarlosQ96 @MohammadPCh @mohammadranjbarz @maryjaf ?

**Comment by laurenluz** [comment]
cc @MoeNick

**Comment by laurenluz** [comment]
it's possible that on staging that we are not considering OP on both Gnosis & Optimism. Amin might have made a fix/ change to the aggregator that was not applied to staging

**Comment by maryjaf** [comment]
Yeah there is a problem in instant boosting sorting on stg, we could check it together   @mohammadranjbarz

**Comment by laurenluz** [comment]
@mohammadranjbarz @maryjaf - were you able to solve it? Do we need more support this weekend? 

pinging @CarlosQ96 to keep an eye

**Comment by maryjaf** [comment]
Thanks @mohammadranjbarz this problem has been resolved

**Comment by mohammadranjbarz** [comment]
@laurenluz  I solved it and @maryjaf  approved that it's working fine

JFYI @MoeNick
