### ISSUE TITLE
Update matching cap for Optimism QF round

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3282]
Right now, we have the "cap" set at 20% per project. I think we might want to decrease this cap... depending on how many projects we end up having in the round.

And perhaps, we will even increase the matching pool size... but should have like a monetary cap of about $5000 per project.

We won't know what we want to change it to until later this week, but I'm creating this issue as a reminder

cc @maryjaf @GriffGreen @CarlosQ96

**Comment by laurenluz** [comment]
there is no option in admin bro to change the %, but @mohammadranjbarz can investigate how to change it

**Comment by mohammadranjbarz** [comment]
@laurenluz  @MoeNick  We checked the code and saw that the 20% amount is something hard coded in frontend, so it's not possible to change it for different qfRounds, but if you want we can add two fields for QfRound Entity **maxAmountCap** and **maxPercentageCap**  and frontend can use them and if those field didn't exist use the hardcoded **20%** , if you are ok with that please tell us to do it ( I suggest we skip it for this release)

FYI @maryjaf  @MohammadPCh  @alireza-sharifpour

**Comment by MoeNick** [comment]
We discussed it today and I thin @alireza-sharifpour will jump into it

**Comment by MohammadPCh** [comment]
@laurenluz we released a new version. let me know if you want to change it.

**Comment by laurenluz** [comment]
we leave it at 20% :)
