### ISSUE TITLE
New Component for projects in 'My Projects'

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3283]
Project owners will claim their streamed tokens from the My Projects page. 

This is a totally new component to see projects from a list view. 

This new component includes:

- [x] Veirifcation status
- [x] Listed status 
- [x] active qf round eligibility
- [x] project actions menu
- [x] project activation status 
- [x] project title
- [x] project created date 
- [x] total raised number
- [x] claimable recurring donations on connected network

https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/GIVeconomy?type=design&node-id=23293-17833&mode=design&t=3NphLaAiiOTZ5y7Q-0
![My accounts](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/56013b28-6ac6-4b04-a3cc-bddb17e20b29)

**Comment by alireza-sharifpour** [comment]
I have some questions:
1- we need all the badges for all conditions for this section because they are different from our previous design.
<img width="189" alt="Screenshot 2023-10-26 at 6 55 03 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/48887817/ab76ff14-b638-408f-b95b-730d2fc15217">

2-This typography is not from the design system.
<img width="1077" alt="Screenshot 2023-10-26 at 6 55 47 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/48887817/8730c30a-dac9-42f6-be12-f186d1a791bc">

3-We need the badge design for verified and unverified, here is just verified design.
<img width="155" alt="Screenshot 2023-10-26 at 6 56 39 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/48887817/2480c629-8fe8-4cba-a46d-d69f7feddf74">

4-We need design for all conditions in this section.
<img width="195" alt="Screenshot 2023-10-26 at 6 57 10 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/48887817/fd203ad6-ec9d-4788-8521-0913b31d8649">

5- And also for this section if it has other conditions:
<img width="151" alt="Screenshot 2023-10-26 at 6 57 37 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/48887817/445415c5-0984-480e-b064-21526c8fe167">

6- What does this arrow do? and what is behind the text, i cannot see.
<img width="141" alt="Screenshot 2023-10-26 at 6 58 17 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/48887817/906f8252-9160-41fb-86b1-7092d944099f">

7- I Cannot see what is under the menu and this tooltip is
<img width="800" alt="Screenshot 2023-10-26 at 6 58 47 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/48887817/2d37952e-5287-40e7-b85e-b746eaf4f5da">

8- It seems like everything is so close together.
<img width="780" alt="Screenshot 2023-10-26 at 6 59 33 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/48887817/23491290-fd8a-41cb-9111-5613a0cec6fe">

9-We need all the tooltip texts here.

**Comment by divine-comedian** [comment]
@mosaeedi & @Tosinolawale need to review these designs - please tag me for any copy needed

**Comment by alireza-sharifpour** [comment]
@divine-comedian I think the questions here are not completely answered yet, 
and also this icon is not in the design system.
<img width="95" alt="Screenshot 2023-11-02 at 6 42 30 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/48887817/dee9d637-9ca7-46b9-bcdd-01c58823eada">

**Comment by divine-comedian** [comment]
Unfortunately I think @Tosinolawale came down with the flu, 

Can you still make progress with the basic component? 

@mosaeedi can assist with putting the clock icon into the DS

**Comment by divine-comedian** [comment]
Some updates have been made to the projects component 

https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/GIVeconomy?type=design&node-id=23644%3A30769&mode=design&t=kl6FPbijaTkBMNxC-1
![Screenshot from 2023-11-09 18-45-53](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/739045fa-49cc-4a2a-b250-07486f780fa1)

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/8bcce993-7120-48f1-a5b1-4d0d97a110eb)

**Comment by maryjaf** [comment]
I've checked preview link to see the future change, I know it isn't ready to test :)
but i think maybe you didn't see before
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3d4QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0370cbf9fe932e682647351f65b119cc93738d3c/image.png" alt="image.png" />
cancelled status isn't shown

**Comment by alireza-sharifpour** [comment]
For Deadline the only remaining thing for this issue is Project status that @maryjaf mentioned and The amount that user can claim. I can work on it after current PR of @MohammadPCh is merged. because we have some changes on calculating prices on that PR.
So I think it will be finished by the end of the week hopefully.
@jainkrati

**Comment by maryjaf** [comment]
> Thanks for testing @maryjaf, please send the link of the project and I'll check it.

https://giveth-dapps-v2-git-claim-recurring-donations-givethio.vercel.app/project/test2805
but this project is cancelled and you can't see the details 
and also in this branch the shown message in project page for cancelled project isn't correct, it seems this branch  does not have recent changes

**Comment by alireza-sharifpour** [comment]
@maryjaf I left a PR for the Canceled project issue and it's waiting for review.
https://github.com/Giveth/giveth-dapps-v2/pull/3475

**Comment by maryjaf** [comment]
The project name shouldn't be clickable in new design of my projects ?

**Comment by maryjaf** [comment]
2-
"testaaab" project has been added to a active QF round but "Quadratic funding" is shown : not eligible

3- 
"Total Raised" is shown with 8 digit after decimal point , is that ok or it should be shown like in project page?

<img width="1284" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/e0205a8f-3dfb-4a12-95df-8126ea3a8d6b">
<img width="1433" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/c3576455-07c6-4d6f-ba63-a759462d6089">

4-
last changes related to verification status in my project list should be applied  on this new design

**Comment by divine-comedian** [comment]
@alireza-sharifpour can you take a look at these issues? 

Decimal amount should be same as the project page - also if the amount is represented in dollars ($) then a dollar sign should be put in front of the amount

@maryjaf - on point 4 you mention - is this related to #3255 or something else? It isn't clear

**Comment by maryjaf** [comment]
> @maryjaf - on point 4 you mention - is this related to #3255 or something else? It isn't clear

Yeah, I meant in new design of my project this change also should be applied
Now on production in current design these badges are shown correctly

**Comment by alireza-sharifpour** [comment]
> @alireza-sharifpour can you take a look at these issues? I see this is in code review but I can't see any open PRs associated with this.
> 
> Decimal amount should be same as the project page - also if the amount is represented in dollars ($) then a dollar sign should be put in front of the amount
> 
> @maryjaf - on point 4 you mention - is this related to #3255 or something else? It isn't clear

Hey @divine-comedian, I'm currently working on Solana issues because of the deadline of it's release, I'll come back and check all issues related to Superfluid after that.

**Comment by alireza-sharifpour** [comment]
Fixes are merged and ready to be tested.
@maryjaf

**Comment by maryjaf** [comment]
> 2- **"testaaab" project has been added to a active QF round but "Quadratic funding" is shown : not eligible*


> 4- **last changes related to verification status in my project list should be applied on this new design**

Thanks @alireza-sharifpour 1 & 3 have been resolved 
but item 2 & 4 haven't been fixed, please take a look 

2-
I've added this project to a active round but it is shown not eligible in my project list
https://staging.giveth.io/project/testsolanaaddress
<img width="1409" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/b723bb0c-a261-407d-988b-e15ce40aab5c">

4- 
verification status

**Comment by alireza-sharifpour** [comment]
It seems like for QFRound issue we need to add QFRound Data to user's allProject's query.
Currently I get null for my project which is in a QF round.

This is my project and @maryjaf added it to a round.
https://staging.giveth.io/project/test-123415
This is the result I get from backen
<img width="480" alt="Screenshot 2024-02-22 at 11 52 29 AM" src="https://github.com/Giveth/giveth-dapps-v2/assets/48887817/f477e854-f19b-4d82-9864-349f233aa4f2">

The query is: projectsByUserId

Can someone take a look? @aminlatifi @mohammadranjbarz @CarlosQ96

**Comment by maryjaf** [comment]
5- 
By tapping on name of project in my user page, 404 error is shown @alireza-sharifpour 
Uploading Screen Recording 2024-02-22 at 2.10.45 PM.mov…

**Comment by alireza-sharifpour** [comment]
It should be fixed now @maryjaf

**Comment by maryjaf** [comment]
> 2-
> I've added this project to a active round but it is shown not eligible in my project list
> https://staging.giveth.io/project/testsolanaaddress

I think It would be better if QF round's name is shown instead of id 
<img width="1380" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/633ca721-585a-405f-a63d-272bb1516929">

**Comment by alireza-sharifpour** [comment]
> > 2-
> > I've added this project to a active round but it is shown not eligible in my project list
> > https://staging.giveth.io/project/testsolanaaddress
> 
> Thanks @alireza-sharifpour , item 2 and 5 have been resolved but for 2 I think It would be better if QF round's name is shown instead of id
> 
> <img alt="image" width="1380" src="https://private-user-images.githubusercontent.com/111529185/308212716-633ca721-585a-405f-a63d-272bb1516929.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMjQ3NTMsIm5iZiI6MTcwOTEyNDQ1MywicGF0aCI6Ii8xMTE1MjkxODUvMzA4MjEyNzE2LTYzM2NhNzIxLTU4NWEtNDA1Zi1hNjNkLTI3MmJiMTUxNjkyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOFQxMjQ3MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMGRmZWI5ZjBhMzc4YTQyZWQ1ZWVjYThkNGYzZTg0NzZlMWIwNTVkMTFiYzljZTJiY2Y4ZDc2Yjg5MTBiYmUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.X3TOWGOv73YiNwj5bYqFRsbN1wCIUcCrUS1sPGxQs0k">

It's exactly same as the design, we also have this badge with QF id in other places, I think if we want to add the name of the round it will be too long for a badge, what do you think? @maryjaf @divine-comedian

**Comment by divine-comedian** [comment]
@alireza-sharifpour

## First thing
 taking a look now - unrelated but I noticed one of my badges is empty on this component - what could be the problem here? 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/e21cc678-94a9-4008-9472-c04c1fb41173)

## second thing
to the problem MJ mentioned - Maybe we can make some copy changes 

Change the title to "QF Eligibility" and the badge to only include the round name - I didn't have any included projects in an active test QF round so the wrong badge colour is you used but you get the idea... :point_down: 
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/c0452720-db19-455a-b74f-d40d341a915e)

## third thing 

the first column probably needs some more spacing on the right to prevent this from happening on smaller views: 
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/5e1fc940-5f15-45c8-9b83-492ead37a53d)

**Comment by alireza-sharifpour** [comment]
I'm changing the QF badge, @maryjaf can you add my project "test-123415" to a round so I can test it?

**Comment by divine-comedian** [comment]
> About the first problem, do you know the status of your project? Currently we have these states for projectStatus so your project's status should be something else which we are not aware of in the frontend. Maybe a Backend dev can check it with DB and see. These are the statuses we currently have in FE:
> 
> ```ts
> switch (projectStatus) {
> 			case EProjectStatus.ACTIVE:
> 				return 'Active';
> 			case EProjectStatus.DEACTIVE:
> 				return 'Deactivated';
> 			case EProjectStatus.DRAFT:
> 				return 'Draft';
> 			case EProjectStatus.CANCEL:
> 				return 'Canceled';
> 		}
> ```
> 
> @divine-comedian

I checked it out on the admin panel - for some reason the project had status of 'rejected' but I don't think that should happen - could be when I was messing around with project status of this project it to test a different issue I made this mistake. 

i changed it to activate and now it is fixed.

**Comment by divine-comedian** [comment]
> test-123415

Added you to the active round!

**Comment by maryjaf** [comment]
> Thanks @alireza-sharifpour , item 2 and 5 have been resolved but for 2 I think It would be better if QF round's name is shown instead of id

Thanks @alireza-sharifpour this problem has been resolved 
<img width="651" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/2f387bc8-58bd-45c8-bc57-8815d05d0594">

**Comment by maryjaf** [comment]
The tests of this issue had completed and I moved it to done,
after deploying on prod it could be closed 
cc: @alireza-sharifpour @jainkrati
