### ISSUE TITLE
Donor: Deposit/Withdraw from Stream Balance

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3285]
From #3092 the donor will have an option to either deposit more tokens or withdraw tokens from their "stream balance" - this is actually them simply upgrading/downgrading their tokens to super tokens & vice versa.

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/8314c833-e30d-4687-a041-dc4077a1d45e)
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/GIVeconomy?type=design&node-id=23293-17833&mode=design&t=7J6iMuXHXGGPhHxz-0

Users will have two options from this modal - Deposit (Upgrade) & Withdraw (Downgrade)

underneath we show:

- [ ] Stream Balance (balance of super tokens)
- [ ] outflow rate 
- [ ] # of projects receiving tokens from this account for this token

under this we have an input field for the user to select an amount of tokens to deposit or withdraw. 
below this input field we show a token balance which changes based on if they selected deposit or withdraw. 

- [ ] deposit - we show balance of regular tokens available to be deposited
- [ ] withdraw - show balance of super tokens available to be withdrawn 

## User Errors

- [ ] If a user has active streams for this token, user cannot withdraw tokens to bring expected date when stream balance runs out below 1 day
- [ ] user cannot deposit/withdraw more tokens than their balance
- [ ] user cannot proceed if amount entered is blank or 0

**Comment by MohammadPCh** [comment]
@maryjaf to test and close

**Comment by maryjaf** [comment]
The item 2 of below comment is also related to this issue @MohammadPCh 

https://github.com/Giveth/giveth-dapps-v2/issues/3286#issuecomment-1990961456

**Comment by divine-comedian** [comment]
@maryjaf - yes this makes sense, you withdrew 40 tokens from your stream balance but you did not modify how much you are donating monthly to a given project, 

Since you are technically donating per second you can see that your stream balance will last less than one month now since 40 > 29.9

**Comment by maryjaf** [comment]
> yes this makes sense, you withdrew 40 tokens from your stream balance but you did not modify how much you are donating monthly to a given project,
> 
> Since you are technically donating per second you can see that your stream balance will last less than one month now since 40 > 29.9

I meant that when it is shown that the total stream balance is 29 and on the other hand it is shown that the "total recurring donation" is 40, which is greater than 29, it may cause the user to make a mistake.
But if it is accepted from your point of view, we can consider it as Done

**Comment by divine-comedian** [comment]
Got it, I will make some comms improvements on the pages but technically it makes sense. Moving to Done

**Comment by maryjaf** [comment]
This problem is new and I haven't seen this error before, please take a look @MohammadPCh 
By tapping on "Top-up stream balance" the below error is shown:
Application error: a client-side exception has occurred (see the browser console for more information).

<img width="984" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/3965a165-ab33-4eb8-99c2-b17626750360">


https://github.com/Giveth/giveth-dapps-v2/assets/111529185/fbb503bb-2cf9-4aff-a190-f0265765ea24

**Comment by maryjaf** [comment]
- [ ] 2- imagine my current network is set on Gnosis, by tapping on "Modify stream balance" , in Modify Stream Balance
 modal the balance of gnosis network is shown but my recurring donation is on op sepolia
what is the expected result in this scenario ? should this option should be disabled for  other networks ?
@MohammadPCh @divine-comedian 

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/8dc6896d-116c-49c0-9224-73cdb6a9d733

**Comment by divine-comedian** [comment]
Nice catch! 

If they click any of the buttons such as deposit/withdraw or to modify an individual stream we should give them the switch network modal.

**Comment by alireza-sharifpour** [comment]
I changed it to this:

![Screenshot 2024-03-26 at 11 54 46 AM](https://github.com/Giveth/giveth-dapps-v2/assets/48887817/267d793b-5d5c-4389-84cb-44de39a40e00)

So when the user is not in the correct chain we show this and after clicking we change the network to OP and if the user is on OP we show Deposit/Withdraw.

is It ok @divine-comedian?

**Comment by divine-comedian** [comment]
It's not the prettiest solution but I think it will solve the issue.  

So the user clicks "switch to <network>" and then web wallet pops up reqeusting to switch network 

When the user connects to the right network this text will change to Deposit/Withdraw? 

What about the actions drop down related to recurring donations in the table below? 

Another solution is we don't show them the text, we just launch the request automatically when they click Deposit/Withdraw and are on the wrong network - without having any conditional text changes.

**Comment by alireza-sharifpour** [comment]
Yes, we will change the text to Deposit/Withdraw again.

OK, so I'll get remove the changed text so it will always be Deposit/Withdraw, and also add this switch network functionality when the user clicks on actions drop down.
@divine-comedian

**Comment by divine-comedian** [comment]
Yep, that is the wei I think @alireza-sharifpour - thank you

**Comment by alireza-sharifpour** [comment]
It's ready for testing @maryjaf

**Comment by maryjaf** [comment]
please take a look on this video @alireza-sharifpour 

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/927ad860-b0b8-47f4-8d2d-fcfcef9ae914

By tapping on "start new donation", first the sign modal and after that overviw of user is shown 
before last changes there wasn't this problem

**Comment by maryjaf** [comment]
> please take a look on this video @alireza-sharifpour
> 
>  Screen.Recording.2024-03-28.at.12.50.49.PM.mov 
> By tapping on "start new donation", first the sign modal and after that overviw of user is shown before last changes there wasn't this problem

It seems this problem isn't related to your changes, thanks @alireza-sharifpour i'll check with @MohammadPCh 

Now by tapping on withdraw/ deposit and actions the switch modal to OP is shown , is this the final acceptance criteria of this issue ? @divine-comedian if yes we could move it to Done

**Comment by divine-comedian** [comment]
Yep! 

- Donors can successfully deposit tokens into their stream balance - their balance updates on the UI on the table.
- Donors can successfully withdraw tokens on their stream balance - their balance updates on the UI on the table.
- Donors receive a warning if they try to withdraw an amount of tokens that would reduce their top-up amount to less than one month.

**Comment by alireza-sharifpour** [comment]
> please take a look on this video @alireza-sharifpour
> 
>  Screen.Recording.2024-03-28.at.12.50.49.PM.mov 
> By tapping on "start new donation", first the sign modal and after that overviw of user is shown before last changes there wasn't this problem

This issue should be fixed now.

**Comment by maryjaf** [comment]
Thanks @alireza-sharifpour the problems have been resolved

**Comment by divine-comedian** [comment]
@maryjaf  - Can we call this issue done?
