### ISSUE TITLE
Donor: Modify existing stream

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3286]
Donor wants to modify active recurring stream - accessible from #3092 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/a088b3ce-0843-4a34-875f-015bcd43c59c)
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/GIVeconomy?type=design&node-id=23293-17833&mode=design&t=7J6iMuXHXGGPhHxz-0

At the top we show:

- [ ] Stream Balance (balance of super tokens)
- [ ] outflow rate 
- [ ] # of projects receiving tokens from this account for this token

below is an input field, user enters new amount for monthly flowrate.

clicks confirm and creates transaction to make update to their stream

## User Errors

- [ ] User enters amount that would lower expected end date to below 1 month for stream balance
- [ ] user enters 0 or is blank they cannot proceed

**Comment by MoeNick** [comment]
Let's put priorities and it's assignments pls. 

CC: @divine-comedian 
@jainkrati

**Comment by MohammadPCh** [comment]
@divine-comedian Most parts have been implemented, except sending the data to the backend.

**Comment by maryjaf** [comment]
- [ ] 1- I think it would be better if the real available amount should be shown , I see available 199.35 but when I set 199 the donate button isn't enabled because this isn't real available amount for deposit 
<img width="544" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/cae52a4a-d66c-4108-b7cb-8ec4a17b7525">

**Comment by divine-comedian** [comment]
@maryjaf - Hey MJ I didn't understand your first point - looks like you're trying to withdraw most of your tokens - you have 199.35 available to withdraw and you attempt to withdraw 199 and it prevents you?

**Comment by maryjaf** [comment]
> @maryjaf - Hey MJ I didn't understand your first point - looks like you're trying to withdraw most of your tokens - you have 199.35 available to withdraw and you attempt to withdraw 199 and it prevents you?

Yeah the amount that I can withdraw is lower than the shown available amount 
And I meant the amount that could be withdraw  should be shown for user

**Comment by maryjaf** [comment]
- [ ] 3-What should happens by tapping on "Manage recurring donations"? 
Now nothing happens by tapping on that 

<img width="964" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/5f79db64-6391-4ca5-85a5-96d9d13d8245">

**Comment by divine-comedian** [comment]
Nice catch! @maryjaf 

@MohammadPCh  we can add in a green confirmation modal that we use similarly in other transaction modals

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/6298d6d6-70e8-413a-919c-2b16224fde97)

### For Deposits 
"Deposit to your Stream Balance was successful."

### For Withdrawals 
"Withdrawal from your Stream Balance was successful."

**Comment by divine-comedian** [comment]
@MohammadPCh - I think I fixed the first two tasks for depositing and withdrawing but couldn't figure out making the toast notification conditional 
> When I want to withdraw an amount of tokens that would reduce my "runs out in" to less than 1 month we should change the toast notification to become a warning

It's in this PR: 
https://github.com/Giveth/giveth-dapps-v2/pull/3865

**Comment by MohammadPCh** [comment]
@maryjaf  Item 3 will be addressed once the PR above is merged.

**Comment by divine-comedian** [comment]
@MohammadPCh  I've moved the issue regarding toast notifications for confirmation here - https://github.com/Giveth/giveth-dapps-v2/issues/3904 

We can deal with it later if you have not already started it.

**Comment by maryjaf** [comment]
So It could be moved to Done, Thanks
