### ISSUE TITLE
Updating the Button font style

### ISSUE THREAD

**Issue by mosaeedi** [Giveth/giveth-dapps-v2#3293]
Right now, the button's font style is set to **ALL-CAPS**!

There are some issues with the all-caps font style:

1. From the UX perspective reading long text in all-caps is not easy.
2. It takes lots of space visually.
3. The buttons with long text are a bit ugly in all caps style.

### So, we need to update the button's font style and change that to **Camel Case**.

We just need this

`text-transform: capitalize;`

[Link to Figma](https://www.figma.com/file/d3ciTS36toS9mra0RAPMe2/Giveth-Design-System-v0.1?type=design&node-id=5106-904&mode=design&t=YVXQh5SW6tTVVFql-4)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmNMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--abb8de1286dc2d1d6b252ef0b1d9c6c7f274c51a/Screenshot%202023-10-05%20at%206.49.50%20PM.png)

**Comment by kati-neville** [comment]
Hello @mosaeedi , I would love to work on this
