### ISSUE TITLE
Project in Chain specific round but has no recipient address for the specified chain

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3294]
This project is included in the round for matching for donations made on Optimism Goerli, however it doesn't have an address for Optimism Goerli, meaning I can't donate any matching eligible funds to it! 
https://staging.giveth.io/donate/herbs-and-drugs-and-tools-to-combat-sleepiness
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK29OQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b0988c3b24cd57bb022874c5768f1694de97a949/image.png)

**Comment by laurenluz** [comment]
yes! this is actually a hack that Maryjaf did to add more projects into the round for load testing. this won't be possible on live.

Her comment from https://github.com/Giveth/giveth-dapps-v2/issues/3279:

> Because the number of projects that have OP on stg was less than 150 and in order to be able to test the addition of a large number of projects for the round.
> The projects that have Gnosis or OP were added to the round with the db query
> On production, we can set only the projects that must have OP to be added to the round
