### ISSUE TITLE
QF projects view - projects filter by chain not working! 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3295]
In the view for all projects included in the QF round - I try to filter by projects with optimism addresses. some of the projects that appear in the filtered list don't have any optimism address added - it doesn't appear to sorted in any order. 

If I choose to filter this list by a specific chain it should only show me projects that meet this criteria. 

https://github.com/Giveth/giveth-dapps-v2/assets/67759413/b60c82aa-39e7-4bf9-8072-b20db723febd

**Comment by laurenluz** [comment]
@CarlosQ96 @mohammadranjbarz @MohammadPCh  - do you know what could be causing this?

cc @maryjaf

**Comment by CarlosQ96** [comment]
@laurenluz @divine-comedian this is a staging issue only. We have for optimism two chains the testnet and the mainnet.

 The mainnet and testnet should have been added to all projects, but seems some did not get the optimism goerli one, but have the optimism. So the filter catches those with optimism, even tho they don't have the testnet.

**Comment by CarlosQ96** [comment]
I think it's an issue on project creation, because we receive from the frontend the input addresses, so new projects are being created with optimism but not the testnet. 

Solution would be to write a migration to add those addresses. 
And fix project creation to detect if the network has a testnet and add it too. ORRRRRRRR the frontend simply sends the testnet too.

**Comment by CarlosQ96** [comment]
I think this occurred because we first had optimism as a network, and later on we added optimism goerli. So some projects only have optimism, not the testnet.

**Comment by CarlosQ96** [comment]
Fixed the issue, but also wiped the qfround projects. Need to readd them manually @maryjaf can test the issue.

I added optimism goerli to everyone.
