### ISSUE TITLE
Change copy on banner for Optimism round

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3296]
This banner needs adjusting:

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/b2d82a9f-52a5-4597-9bad-4b80256635c9)

Title: Quadratic Funding on Optimism
Subtext: Amplify your impact on verified projects! Donate to participating verified projects on Optimism network, earn rewards, and get your donations matched with the power of quadratic funding.

**Comment by divine-comedian** [comment]
fixed in https://github.com/Giveth/giveth-dapps-v2/commit/cfb556cdae71e00d2c7062d83a4614a413dd9567

**Comment by mateodaza** [comment]
sorry we crossed our tails here and I think the merge didn't include it- will fix it
