### ISSUE TITLE
Show "amount raised all time" somehow on project card during QF rounds (but smaller)

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3308]
There is a problem that is not related to this new sorting, but it may cause the user to make mistakes and get confused
I am commenting here, if necessary, we can create a separate issue
There is already a **"Amount Raised All Time"** sort that displays the total amount of project donation in order, when we have an active round, by selecting this field, we may see a view like the below pic , which will make the user get confused.
The first project has a higher total donation and therefore it is displayed in position one, but in the project card where we show the donation amount for this round, it is zero.

[ Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNm9LQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--96a369da65a88142deda92660b016c0c64f08ea3/image.png)

What we can do for this?
It should remains like before or should be changed @laurenluz

_Originally posted by @maryjaf in https://github.com/Giveth/giveth-dapps-v2/issues/3281#issuecomment-1748854711_

**Comment by laurenluz** [comment]
@mosaeedi - this is related to #3371 

Can you come up with a modification for the project card on the projects page too, to consider this?

**Comment by mosaeedi** [comment]
The project card on the left shows a project in the QF round; the amount raised all the time is visible below the amount raised in the round.
We won't show the _Raised from **x** contributors._

The card on the right is a project not in the QF round; below the amount raised, we need to show the __Raised from **x** contributors._

<img width="1096" alt="Screenshot 2024-02-14 at 2 42 10 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/8decd00d-de17-4c77-b5d6-43942a0fe204">

**Comment by mosaeedi** [comment]
The project card on the left shows a project in the QF round; the amount raised all the time is visible below the amount raised in the round.
We won't show the _Raised from **x** contributors._

The card on the right is a project not in the QF round; below the amount raised, we need to show the __Raised from **x** contributors._

Link to the component -> [Figma link](https://www.figma.com/file/d3ciTS36toS9mra0RAPMe2/Giveth-Design-System-v0.1?type=design&node-id=2678-62803&mode=design&t=w6A52odnzXEAoEXb-4)

<img width="893" alt="Screenshot 2024-02-14 at 2 51 45 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/820ee5eb-aaa7-4619-b5e6-3b7a7e1a492d">

**Comment by laurenluz** [comment]
that sounds good to me! lets' get this added.

**Comment by jainkrati** [comment]
Will try to prioritize this soon.

**Comment by jainkrati** [comment]
@RamRamez pls work on FE as well as BE changes for this and get the review from @mohammadranjbarz

**Comment by RamRamez** [comment]
@maryjaf to test and verify

**Comment by maryjaf** [comment]
Are total raised and vr/ar in correct position relative to the dividing line? @RamRamez 

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHd6QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4bd5506e903421c1ba8cc97eeb133eb37f46e285/Screen%20Recording%202024-04-04%20at%2011.24.21%20AM.mov)
