### ISSUE TITLE
Changing copy of passport banner when there is an active round that will be started in future

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3310]
It would be good if we consider this change  for next round
If there is no active round the "There is no active round " message is shown and it's ok but if there is an active round that will start in future, it's better if this message be changed 
<img width="974" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/fb0b8c26-fb76-4c36-a848-f03e275f8d05">
cc: @laurenluz

**Comment by laurenluz** [comment]
We should change this instead to:

"This round is starting soon!"

@MohammadPCh @mohammadranjbarz @CarlosQ96 - I think this might require some small change in the backend as well as the copy element, am I right?

cc @jainkrati

**Comment by MohammadPCh** [comment]
@jainkrati @laurenluz  It's entirely handled in the front-end. I can take care of it.

**Comment by MohammadPCh** [comment]
result:
<img width="611" alt="Screenshot 2024-02-06 at 12 24 05 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/17097576/1d901dde-731f-4da0-b8a1-3c390be2ee03">
Oops, @laurenluz, I just saw your message now. I've noted the start date. Should we change it to 'soon'?

**Comment by jainkrati** [comment]
For now it is fine to edit in FE @MohammadPCh but we should make changes so that we can fetch this value in FE from AdminBro setting.

**Comment by laurenluz** [comment]
@MohammadPCh I like that we put the date in there! can you make a comma though after the number... so like "Feb 8, 2024"

**Comment by MohammadPCh** [comment]
@jainkrati, just to clarify, we fetch the round dates from the backend and use the current date to determine the display. so we didn't hardcode this.

**Comment by MohammadPCh** [comment]
@laurenluz Done
<img width="624" alt="Screenshot 2024-02-06 at 10 46 42 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/17097576/7eaec53e-7b1f-4723-894e-d3c6dc1dcaf7">

**Comment by laurenluz** [comment]
love it!

**Comment by MohammadPCh** [comment]
@maryjaf Could you please test this? Thanks.

**Comment by maryjaf** [comment]
Thanks @MohammadPCh the copy has been changed correctly
"The next round starts on Feb 17, 2024"
