### ISSUE TITLE
Token should be "Optimism" not "OPTIMISTIC"

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3312]
Quick hotfix for production... this token name is wrong on Optimism network.

Should be "Optimism" and not ALL CAPS

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/2f316834-d204-4467-9a68-121fa504e55e)

like this:

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/3c99f46e-8f79-461a-9823-9ad644e9fb73)

@alireza-sharifpour @mateodaza @MohammadPCh 

cc @MoeNick

**Comment by laurenluz** [comment]
maybe @WhyldWanderer can fix in admin bro?

**Comment by MoeNick** [comment]
I will do

**Comment by laurenluz** [comment]
oh @divine-comedian did it!

**Comment by MoeNick** [comment]
yeah
![image](https://github.com/Giveth/giveth-dapps-v2/assets/80677512/f53b08f3-441d-4a9b-ba94-b7cbbedb03b1)
