### ISSUE TITLE
Change language based on browser settings

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3314]
Related to #3008 

We should consider showing the user the website in a certain language based on their browser's language settings or the IP location from which they connect to the website with. 

If a user connects from a spanish speaking country we show the app in spanish, and save their language preferences locally. 

If the user switches to a different language, by selecting one from the footer options we update those preferences stored locally so that when they come back to the website it shows in their preferred language. 

Right now this is only applicable to Catalan (Catalonia) & Spanish (Latin America & Spain)

**Comment by RamRamez** [comment]
@divine-comedian ok, now the app locale will be automatically changed by preferred locale on first render.

The preferred locale will be determined by four parameters (listed in order of importance):
1. User choice (browser storage)
2. IP
3. Browser settings
4. Default locale (en)

**Comment by divine-comedian** [comment]
Okay so for me - If I clear my cache and cookies and visit the website from Mexico it should default show in Spanish, correct? 

Is there anyway to reset the preferred language in a user's browser storage?

**Comment by RamRamez** [comment]
I changed the storage label for saving preferred language in browser storage, so after release, we will predict the language by IP address.

Also I added the country codes for Spanish-speaking countries, now the app will be shown in Spanish for countries like Mexico and Colombia

**Comment by divine-comedian** [comment]
Check this on brave (on incognito) it doesn't appear to change the language 

However on firefox (not incognito) the dapp changes languages after loading for a few seconds

**Comment by divine-comedian** [comment]
testing this with:

firefox
chrome
brave

when I visit https://staging.giveth.io/ while connected from spain or mexico the page will load first in english then switch to spanish after a brief moment 

I would say we can call this feature done. However we could improve it in the future by preventing the first load of the page in english and try to have it detect the country and then load the page in the correct language.
