### ISSUE TITLE
WC Testing: Chrome Desktop | Metamask Desktop Extension

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3315]
The following test cases should be completed and successful:

- [x] - Sign in
- [x] - Switch Network (from navbar dropdown menu)
- [x] - Switch Network (from givfarm)
- [x] - Connect Wallet(from GIVfarm/GIVback)
- [x] - Connect Wallet and sign in (from passport banner)
- [x] - Switch network (from donate page)
- [x] - Donate ERC20
- [x] - Donate native token
- [x] - Stake GIV
- [x] - Lock GIV
- [x] - Unstake GIV
- [x] - Harvest rewards (GIVfarm)
- [x] - claim GIVbacks 
- [x] - claim GIVstream

**Comment by maryjaf** [comment]
https://github.com/Giveth/giveth-dapps-v2/issues/3053#issuecomment-1755475932

Connect wallet from GIV farm : failed
#3265 (comment)

stake: failed
#3265 (comment)

**Comment by divine-comedian** [comment]
Related to: https://github.com/Giveth/giveth-dapps-v2/issues/3265#issuecomment-1752784578
> **Connect wallet** button in GIVpower and GIVback tab doesn't work, by tapping on this button nothing happens , plz check @MohammadPCh mobile and desktop <img alt="image" width="1432" src="https://user-images.githubusercontent.com/111529185/273563865-d79a2919-7ced-4a51-aa07-64cf7e542901.png">

I can't seem to reproduce this issue...


https://github.com/Giveth/giveth-dapps-v2/assets/67759413/f6316502-6680-45df-a912-c1b6750fad16

**Comment by maryjaf** [comment]
> ### GIVfarm staking
> Tried staking 100% of my elgibile tokens, similar to issue reported in #3317

Same issue happens to me @divine-comedian @MohammadPCh

**Comment by maryjaf** [comment]
> Tried staking 100% of my elgibile tokens, similar to issue reported in #3317

Thanks @MohammadPCh this problem has been resolved

**Comment by divine-comedian** [comment]
> > Tried staking 100% of my elgibile tokens, similar to issue reported in #3317
> 
> Thanks @MohammadPCh this problem has been resolved

Can we call this one passed then MJ?
