### ISSUE TITLE
WC Testing: Firefox Desktop | Metamask Desktop Extension

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3317]
The following test cases should be completed and successful:

- [x] - Sign in
- [x] - Switch Network (from navbar dropdown menu)
- [x] - Switch Network (from givfarm)
- [x] - Connect Wallet(from GIVfarm/GIVback)
- [x] - Connect Wallet and sign in (from passport banner)
- [x] - Switch network (from donate page)
- [x] - Donate ERC20
- [x] - Donate native token
- [x] - Stake GIV
- [x] - Lock GIV
- [x] - Unstake GIV
- [x] Approve GIV
- [x] - Harvest rewards (GIVfarm)
- [x] - claim GIVbacks 
- [x] - claim GIVstream

**Comment by maryjaf** [comment]
I couldn't complete sign in flow on Firefox|Metamask extension 
plz check the below video

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/d5a3fa0d-5f1a-4cce-9724-89f1ec1eb476

**Comment by divine-comedian** [comment]
@maryjaf - Maybe check this one again? 

Tested it out w/ Firefox on Linux and it appears to work fine.

**Comment by divine-comedian** [comment]
While trying to approve GIV I choose an amount to approve on the Giveth UI - however on the generated metamask transaction it populates with only 0 

The transaction should ask to approve the amount I entered in the input field on the staking modal on the giveth UI

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/14f60f8e-54d5-43ae-be97-39f376b3c526)

**Comment by divine-comedian** [comment]
Most of the test cases have passed - only a few issues I found related to staking & unstaking 100% of my tokens - could be related to wagmi..

**Comment by maryjaf** [comment]
> Most of the test cases have passed - only a few issues I found related to staking & unstaking 100% of my tokens - could be related to wagmi..

this issue has been resolved
