### ISSUE TITLE
WC Testing: Chrome Desktop | MetaMask MOBILE 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3318]
The following test cases should be completed and successful:

- [x] - Sign in
- [x] - Switch Network (from navbar dropdown menu)
- [x] - Switch Network (from givfarm)
- [x] - Connect Wallet(from GIVpower/GIVback)
- [x] - Connect Wallet and sign in (from passport banner)
- [x] - Switch network (from donate page)
- [x] - Donate ERC20
- [x] - Donate native token
- [x] - Stake GIV
- [x] - Lock GIV
- [x] - Unstake GIV
- [x] - Harvest rewards (GIVfarm)
- [x] - claim GIVbacks 
- [x] - claim GIVstream

**Comment by divine-comedian** [comment]
Related to: https://github.com/Giveth/giveth-dapps-v2/issues/3053#issuecomment-1755471388

> > ## 2. Desktop Browser w/ Wallet Connect/web3Modal (to mobile wallet)
> > ### Chrome (desktop)
> > 
> > * Metamask (mobile)
> > * Trust Wallet
> > * Coinbase Wallet
> 
> I couldn't sign in with these, after scanning QR code and opening Metamask nothing happens

**Comment by maryjaf** [comment]
For completing test scenarios plz set manually GIV back for these my accounts on Gnosis & OP
0xD5db3F8B0a236176587460dC85F0fC5705D78477
0xcd192b61a8Dd586A97592555c1f5709e032F2505
Thanks

**Comment by maryjaf** [comment]
> Connect wallet from GIV farm : failed [#3265 (comment)](https://github.com/Giveth/giveth-dapps-v2/issues/3265#issuecomment-1752784578)
> 
> stake: failed [#3265 (comment)](https://github.com/Giveth/giveth-dapps-v2/issues/3265#issuecomment-1754539634)

These test results are related to Chrome Desktop | MetaMask Extension 
I'll add these result to another issue

**Comment by maryjaf** [comment]
> Connect wallet from GIV farm : failed [#3265 (comment)](https://github.com/Giveth/giveth-dapps-v2/issues/3265#issuecomment-1752784578)
> 
> stake: failed [#3265 (comment)](https://github.com/Giveth/giveth-dapps-v2/issues/3265#issuecomment-1754539634)

These test results are related to Chrome| Metamask extension
I'll add these to another issue

**Comment by divine-comedian** [comment]
> 0xcd192b61a8Dd586A97592555c1f5709e032F2505

Sent!
