### ISSUE TITLE
WC Testing: Chrome Desktop | Trust Wallet MOBILE

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3320]
The following test cases should be completed and successful:

- [x] - Sign in
- [x] - Switch Network (from navbar dropdown menu)
- [x] - Switch Network (from givfarm)
- [x] - Connect Wallet(from GIVfarm/GIVback)
- [x] - Connect Wallet and sign in (from passport banner)
- [x] - Switch network (from donate page)
- [x] - Donate ERC20
- [x] - Donate native token
- [x] - Stake GIV
- [x] - Lock GIV
- [x] - Unstake GIV
- [x] - Harvest rewards (GIVfarm)
- [x] - claim GIVbacks 
- [x] - claim GIVstream
- [x] Connect with Multisig
- [x] Create recurring donation
- [x] modify recurring donation
- [x] deposit/withdraw from stream balance 
- [x] end recurring donation
- [ ] - Donate SOL
- [ ] Donate Solana Token

**Comment by maryjaf** [comment]
in this case Trust Wallet MOBILE,  different flows like sign-in change, network some times  is passed and sometimes I see different behavior for example after confirmation on mobile ,nothing happens on desktop 
in this case and Coinbase wallet I need someones who helps me for testing because I can't accept or reject the test

**Comment by maryjaf** [comment]
Some time I got an error in Stake flow, plz check this screen record when I try to confirm transaction on my mobile @MohammadPCh

**Comment by maryjaf** [comment]
three are meta mask wallet and trust wallet on my iPhone
but when I scan QR code i see Metamask link:



I tried with other phone that there is only trust wallet on it and the result is as below pic:

**Comment by maryjaf** [comment]
> three are meta mask wallet and trust wallet on my iPhone but when I scan QR code i see Metamask link and i could complete flows with Metamask:
> 
> I tried with other phone that there is only trust wallet on it and the result is as below pic: ![image](https://private-user-images.githubusercontent.com/111529185/274509248-37931495-ff54-490d-9f67-fc96905151c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MTE1MDksIm5iZiI6MTcyMjUxMTIwOSwicGF0aCI6Ii8xMTE1MjkxODUvMjc0NTA5MjQ4LTM3OTMxNDk1LWZmNTQtNDkwZC05ZjY3LWZjOTY5MDUxNTFjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMVQxMTIwMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NTg0NDY2ODg5MDU1YmJmMmJiZGZhZGI0MzM3NjhjMWMxNWFlMDk5YTljNGNjOTVjYTA5ZmQxNjgzOTYwOTViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lzjn3CwVewA7O5q5TX7kB1y4X3Mhsj3qnmfDJPufr7I) ![image](https://private-user-images.githubusercontent.com/111529185/274509298-67e491bc-3778-432c-aab0-3df3f65f967b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MTE1MDksIm5iZiI6MTcyMjUxMTIwOSwicGF0aCI6Ii8xMTE1MjkxODUvMjc0NTA5Mjk4LTY3ZTQ5MWJjLTM3NzgtNDMyYy1hYWIwLTNkZjNmNjVmOTY3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMVQxMTIwMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mODhmZDYyZjQ0Y2FkMjJhMWI2ZjZmZWNkOGM3ZTJhMzQ3ZDNhNWNiZDQ4YzFhMmQwOTE0OTk1MWFjYWU3Njk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LL0hdqj73jGyDPhkj99sKsX0lIyrLbchn3Mj0WTQKmE)

I've tested again , and by scanning QR code I can see only the metamask option

**Comment by divine-comedian** [comment]
@maryjaf - when logging in I can see the Trust Wallet option available on the wallet connect modal, I scanned a QR code from my Trust Wallet app and logged in w/ no problems :thinking: 


https://github.com/user-attachments/assets/7083e1f8-bf3b-444a-87fa-6814332820aa

**Comment by maryjaf** [comment]
> I've tested again , and by scanning QR code I can see only the metamask option
> How can I check trust wallet , I have trust wallet on my phone

Thanks , It has been fixed and I could compelet sign flow with trust wallet

**Comment by maryjaf** [comment]
- [ ] for testing recurring donation, I tap on "Switch network" on donation page, but nothing happens 
could you please take a look ? @MohammadPCh @divine-comedian 


https://github.com/user-attachments/assets/4bbdade7-1d17-4c45-8c13-9307fa9dc04a

**Comment by maryjaf** [comment]
> * [ ]  for testing recurring donation, I tap on "Switch network" on donation page, but nothing happens
>   could you please take a look ? @MohammadPCh @divine-comedian
> 
> * [ ]  in general I couldn't switch network to op  sepolia, actually I haven't found a way to add op sepolia into trust wallet

These problems does not exist on production,  for recurring donation tests I checked prod address and the scenarios pass

**Comment by maryjaf** [comment]
- [ ] There is no "wallet connect" option when user taps on "sign with solana"
and sol scenarios could be tested only in Desktop browser | Trust Wallet DESKTOP

https://github.com/user-attachments/assets/6e756a14-0477-4e5a-8304-55b7589567b4

**Comment by divine-comedian** [comment]
@kkatusic maybe you can take this one from Cherik? I think it is related to adding support for Trust Wallet within the solana wallet adapter code

**Comment by kkatusic** [comment]
@divine-comedian I added adapter, for Trust and WalletConnect adapter for the Solana network. Unfortunately it didn't work, when you try to connect with qr code on trust mobile wallet you get just one error:

![WhatsApp Image 2024-08-14 at 13 59 48](https://github.com/user-attachments/assets/f73b9a5a-8ef1-434b-be00-d85cafe8de58)

I will try using blank nextjs project add all this option and test it, if it than not works maybe to contact all related networks and connector community support and report problems

**Comment by divine-comedian** [comment]
@maryjaf @kkatusic since we are removing Solana from scope we can call this issue DONE assuming all other test cases have passed 

@maryjaf - if you can confirm then please move this issue to "Done"
