### ISSUE TITLE
WC Testing: Firefox Desktop | MetaMask MOBILE

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3322]
The following test cases should be completed and successful:

- [x] - Sign in
- [x] - Switch Network (from navbar dropdown menu)
- [x] - Switch Network (from givfarm)
- [x] - Connect Wallet(from GIVfarm/GIVback)
- [x] - Connect Wallet and sign in (from passport banner)
- [x] - Switch network (from donate page)
- [x] - Donate ERC20
- [x] - Donate native token
- [x] - Stake GIV
- [x] - Lock GIV
- [x] - Unstake GIV
- [x] - Harvest rewards (GIVfarm)
- [x] - claim GIVbacks 
- [x] - claim GIVstream

**Comment by maryjaf** [comment]
Connect wallet haven't worked on Firefox| MM mobile
By tapping on this button, nothing happens 
<img width="1405" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/b6b919e6-f17c-4ac0-b22c-db79d1822f07">
plz check @MohammadPCh

**Comment by maryjaf** [comment]
> Connect wallet haven't worked on Firefox| MM mobile

This problem has been resolved
