### ISSUE TITLE
WC Testing: Firefox Desktop | Coinbase Wallet MOBILE

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3324]
The following test cases should be completed and successful:

- [x] - Sign in
- [x] - Switch Network (from navbar dropdown menu)
- [x] - Switch Network (from givfarm)
- [x] - Connect Wallet(from GIVfarm/GIVback)
- [x] - Connect Wallet and sign in (from passport banner)
- [x] - Switch network (from donate page)
- [x] - Donate ERC20
- [x] - Donate native token
- [x] - Stake GIV
- [x] - Lock GIV
- [x] - Unstake GIV
- [x] - Harvest rewards (GIVfarm)
- [x] - claim GIVbacks 
- [x] - claim GIVstream
- [x] Connect with Multisig
- [x] Create recurring donation
- [x] modify recurring donation
- [x] deposit/withdraw from stream balance 
- [x] end recurring donation

**Comment by kkatusic** [comment]
@divine-comedian this all have been tested and passed.

**Comment by divine-comedian** [comment]
@LatifatAbdullahi this is ready for QA on staging 

You can get the coinbase wallet here 
https://www.coinbase.com/wallet

download it for mobile on your phone and set it up with some test funds

Then using firefox browser test the connection via wallet connect and go through the test cases outlined above

**Comment by LatifatAbdullahi** [comment]
@kkatusic  @divine-comedian 
 **Firefox Desktop | Coinbase Wallet MOBILE**


**Test Update**

 - Sign in - **Pass**
 - Switch Network (from navbar dropdown menu) - **Pass**
 - Switch Network (from givfarm) - **Pass**
 - Connect Wallet(from GIVfarm)- **Pass**
 -  Connect Wallet(from GIVback) - **Pass**
 - Connect Wallet and sign in (from passport banner)- **Pass**
 - Switch network (from donate page) - **Pass**
 - Donate ERC20 - **Pass**
 - Donate native token - **Pass**
 - Stake GIV - **Pass**
 - Lock GIV - **Pass**
 - Unstake GIV - **Pass**
 - Harvest rewards (GIVfarm) **Pass**
 - Claim GIVbacks - **Pass**
 - Claim GIVstream  - **Pass**
 - Connect with Multisig - **Pass**
 - Create recurring donation - **Pass**
 - Modify recurring donation - **Pass**
 - Deposit to stream balance -**Pass**
 - Withdraw from stream balance -**Pass**
 - End recurring donation - **Pass**
