### ISSUE TITLE
WC Testing: Edge Desktop | Trust Wallet MOBILE

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3326]
The following test cases should be completed and successful:

- [x] - Sign in
- [ ] - Switch Network (from navbar dropdown menu)
- [x] - Switch Network (from givfarm)
- [x] - Connect Wallet(from GIVfarm/GIVback)
- [ ] - Connect Wallet and sign in (from passport banner)
- [x] - Switch network (from donate page)
- [ ] - Donate ERC20
- [x] - Donate native token
- [ ] - Stake GIV
- [ ] - Lock GIV
- [x] - Unstake GIV
- [ ] - Harvest rewards (GIVfarm)
- [x] - claim GIVbacks 
- [ ] Connect with Multisig
- [x] Create recurring donation
- [x] modify recurring donation
- [ ] deposit/withdraw from stream balance 
- [ ] end recurring donation
- [ ] - Donate SOL
- [ ] Donate Solana Token
- [ ] - claim GIVstream

**Comment by maryjaf** [comment]
only Solana scenarios haven't been passed

**Comment by divine-comedian** [comment]
> only Solana scenarios haven't been passed

We can remove Solana from scope!

**Comment by divine-comedian** [comment]
Yes we can revert those changes AND remove Trust, Coinbase and Wallet Connect since they don't want to play nice.
