### ISSUE TITLE
WC Testing: Android/Chrome MOBILE | MetaMask MOBILE

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3328]
The following test cases should be completed and successful:

- [x] - Sign in
- [x] - Switch Network (from navbar dropdown menu)
- [x] - Switch Network (from givfarm)
- [x] - Connect Wallet(from GIVfarm/GIVback)
- [x] - Connect Wallet and sign in (from passport banner)
- [x] - Switch network (from donate page)
- [ ] - Donate ERC20
- [ ] - Donate native token
- [ ] - Stake GIV
- [ ] - Lock GIV
- [ ] - Unstake GIV
- [ ] - Harvest rewards (GIVfarm)
- [ ] - claim GIVbacks 
- [ ] - claim GIVstream

**Comment by maryjaf** [comment]
Shouldn’t l be redirected to dApp after metamask modal is confirmed? 
@MohammadPCh 
https://github.com/Giveth/giveth-dapps-v2/assets/111529185/f0ba0b2e-2c30-4833-914c-f7980de9dff3

**Comment by maryjaf** [comment]
I couldn’t complete donation flow on mobile /chrome/metamask 
The confirmation modal isn’t shown on metamask to complete the flow 
@MohammadPCh 

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/6ee81212-1d77-4056-b2fa-a94eb999db51

**Comment by maryjaf** [comment]
> I couldn’t complete donation flow on mobile /chrome/metamask The confirmation modal isn’t shown on metamask to complete the flow @MohammadPCh
>

also stake , unstake, harvest

**Comment by maryjaf** [comment]
Today I get this error on donation page
@MohammadPCh 
![IMG_8087](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/de786023-8156-45b0-91e4-a60453710eef)

**Comment by mohammadranjbarz** [comment]
@maryjaf 
This problem has been made through https://github.com/Giveth/impact-graph/pull/1151
I will fix it ASAP

**Comment by mohammadranjbarz** [comment]
@maryjaf  It's ok now

**Comment by divine-comedian** [comment]
We can move the switch network concerns to a new issue and call this unit test passed
