### ISSUE TITLE
WC Testing: Android/Chrome MOBILE | Trust Wallet MOBILE

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3329]
The following test cases should be completed and successful:

- [ ] - Sign in
- [ ] - Switch Network (from navbar dropdown menu)
- [ ] - Switch Network (from givfarm)
- [ ] - Connect Wallet(from GIVfarm/GIVback)
- [ ] - Connect Wallet and sign in (from passport banner)
- [ ] - Switch network (from donate page)
- [ ] - Donate ERC20
- [ ] - Donate native token
- [ ] - Stake GIV
- [ ] - Lock GIV
- [ ] - Unstake GIV
- [ ] - Harvest rewards (GIVfarm)
- [ ] - claim GIVbacks 
- [ ] - claim GIVstream
- [ ] Connect with Multisig
- [ ] Create recurring donation
- [ ] modify recurring donation
- [ ] deposit/withdraw from stream balance 
- [ ] end recurring donation
- [ ] Donate SOL
- [ ] Donate Solana Token

**Comment by maryjaf** [comment]
I don't have android phone to check this issue.

**Comment by LatifatAbdullahi** [comment]
@divine-comedian 


- Sign in - **Pass**
 - Switch Network (from navbar dropdown menu)- *Pass*
 - Switch Network (from givfarm)- *Pass*
 - Connect Wallet(from GIVfarm/GIVback)- *Pass*
 - Connect Wallet and sign in (from passport banner)
 - Switch network (from donate page) - *Pass*
 - Donate ERC20 - *Pass*
 - Donate native token- *Pass*
 - Stake GIV- *Pass*
 - Lock GIV - *Pass*
 - Unstake GIV- *Pass*
 - Harvest rewards (GIVfarm)- *Pending*
 - claim GIVbacks - Pending - *Pending*
 - claim GIVstream - *Pending*
 Connect with Multisig
 Create recurring donation- *Failed*
 modify recurring donation-  *Pending*
 deposit/withdraw from stream balance -*Pending*
 end recurring donation  - *Pending*
 Donate SOL - *Trust wallet option not coming when Users select "with Solana" even though there is a Solana wallet Present in the Trust wallet*
 Donate Solana Token - *Pending*





When Users attempt to recurring donation with Optimism Sepolia

![Screenshot_20240803_173548_Trust Wallet](https://github.com/user-attachments/assets/83a06e8f-7ecc-4bd5-8fa0-8d609d2c838d)

![Screenshot_20240803_173555_Chrome](https://github.com/user-attachments/assets/6cef372a-192a-4cad-8e00-a8f5bfc7bad8)



Also with other networks except Gnosis/Polygon


![image](https://github.com/user-attachments/assets/cc135158-6c9b-4e8b-b2ed-56534fab3fc9)

**Comment by divine-comedian** [comment]
@MohammadPCh - perhaps we need to add Trust wallet into the wallet adapter plug-in we use for Solana connections 

Trust Wallet doesn't support most test networks out of the box, you need to set them up as custom networks, let's make sure they are configured properly inside your Trsut wallet app @LatifatAbdullahi. 

Recurring Donations also won't work unless we are sure Optimism Sepolia network config has been set correctly inside of Trust Wallet

**Comment by LatifatAbdullahi** [comment]
@divine-comedian @divine-comedian 

I tried importing with same details you used @divine-comedian, but it showed "Chain already exists", meaning it was configured properly in trust wallet.

![Screenshot_20240804_214136_Trust Wallet](https://github.com/user-attachments/assets/888e6bc9-a979-48b0-a344-a1771f7fcea7)




I also got same error when I attempted to donate again.

![image](https://github.com/user-attachments/assets/09f041aa-7363-4c20-9160-b3288461984d)

**Comment by mohammadranjbarz** [comment]
Thanks @LatifatAbdullahi 
but I think these things are just related to to test chain networks, not our application, so I dont know how we can handle it, @divine-comedian WDYT?

**Comment by LatifatAbdullahi** [comment]
@mohammadranjbarz @divine-comedian 

I tested donation(Recurring Donation)using Optimism also Onte-time donation with Arbitrum one on Production and it was successful. I was also able to modify the recurring dnation.

Therefore, the issue on stage is probably with the Test networks.



![Screenshot_20240806_170528_Chrome](https://github.com/user-attachments/assets/33c1e774-c938-4ee6-a4b4-c58569378dd1)

**Comment by LatifatAbdullahi** [comment]
@divine-comedian @mohammadranjbarz 


- Sign in - **Pass**
 - Switch Network (from navbar dropdown menu)-  **Pass**
 - Switch Network (from givfarm)- **Pass**
 - Connect Wallet(from GIVfarm/GIVback)- **Pass**
 - Connect Wallet and sign in (from passport banner) - **Pass**
 - Switch network (from donate page) - **Pass**
 - Donate ERC20 - **Pass**   
 - Donate native token- **Pass**
 - Stake GIV- **Pass**
 - Lock GIV - **Pass**
 - Unstake GIV- **Pass**
 - Harvest rewards (GIVfarm)- **Pass**
 - claim GIVbacks - Pending - **Pass**
 - claim GIVstream - **Pass**
 - Connect with Multisig - **Pass**
 - Create recurring donation- *Failed* on stage .... **Pass** on Production
 - modify recurring donation-  **Pass** on Production
-  deposit/withdraw from stream balance -*Failed*
 - End recurring donation  - *Failed*
-  Donate SOL - *Trust wallet option not coming up when Users select "with Solana" even though there is a Solana wallet Present in the Trust wallet*
- Donate Solana Token - *Failed*



After donating on Prod(Recurring donation), I atrempted to deposit stream and also end a recurring donation, both failed and threw the errors below.


End Recurring donation
![Screenshot_20240806_172807_Chrome](https://github.com/user-attachments/assets/ccf501dc-dcdb-40f7-a8f1-b71c9b6c373e)
 

Deposit streams
![Screenshot_20240806_173104_Chrome](https://github.com/user-attachments/assets/03cec5b3-2d24-4a7c-947e-ae9b9f08d753)


Also couldnt connect to Solana

**Comment by kkatusic** [comment]
@mohammadranjbarz, cc @LatifatAbdullahi, maybe you can add Trust Wallet Adapter here maybe that help to login with Solana Trust Address: https://github.com/Giveth/giveth-dapps-v2/blob/b8633878fbaa24cd43da0c155632a7dda001dce0/src/providers/solanaWalletProvider.tsx#L28

**Comment by divine-comedian** [comment]
Thanks @LatifatAbdullahi - @kkatusic maybe you can check out adding trust wallet to solana wallet adapter.

**Comment by kkatusic** [comment]
> Thanks @LatifatAbdullahi - @kkatusic maybe you can check out adding trust wallet to solana wallet adapter.

@divine-comedian, cc @LatifatAbdullahi  sdded adapter in PR, waiting to someone review it
