### ISSUE TITLE
Add approve+stake option to givfarm staking

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapps-v2#333]
As a user, I can choose to stake on unipool (givfarm pools) by two transactions of approve+stake instead of a single transaction of `stakeWithPermit`.
It is useful when a multisig user wants to stake and he/she cannot sign a message in advance.

Refs https://github.com/Giveth/GIVeconomy/issues/502

**Comment by mosaeedi** [comment]
### Design resource

[Modal with infinity approval](https://www.figma.com/file/d3ciTS36toS9mra0RAPMe2/Giveth-Design-System-v0.1?node-id=488%3A47168)

**Comment by pkretzschmar** [comment]
@mosaeedi @aminlatifi this toggle shouldn't refer to the stake with a permit or without a permit?

**Comment by aminlatifi** [comment]
> @mosaeedi @aminlatifi this toggle shouldn't refer to the stake with a permit or without a permit?

You are right @pkretzschmar. @mosaeedi this design is different than the topic of this issue!
