### ISSUE TITLE
WC Testing: Android/Chrome MOBILE | Coinbase Wallet MOBILE

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3330]
The following test cases should be completed and successful:

- [x] - Sign in
- [x] - Switch Network (from navbar dropdown menu)
- [x] - Switch Network (from givfarm)
- [x] - Connect Wallet(from GIVfarm/GIVback)
- [x] - Connect Wallet and sign in (from passport banner)
- [x] - Switch network (from donate page)
- [x] - Donate ERC20
- [x] - Donate native token
- [x] - Stake GIV
- [x] - Lock GIV
- [x] - Unstake GIV
- [x] - Harvest rewards (GIVfarm)
- [x] - claim GIVbacks 
- [x] - claim GIVstream
- [x] Connect with Multisig
- [x] Create recurring donation
- [x] modify recurring donation
- [x] deposit/withdraw from stream balance 
- [x] end recurring donation

**Comment by divine-comedian** [comment]
@LatifatAbdullahi - this is testing on PURE mobile with coinbase wallet - using coinbase wallet on an android phone, I know coinbase wallet may make you use their in-wallet browser. This is accepted as long as all the test cases pass

**Comment by LatifatAbdullahi** [comment]
@kkatusic  @divine-comedian 

**Test Update**


 - Sign in - **Pass**
 - Switch Network (from navbar dropdown menu ) - **Pass**
 - Switch Network (from givfarm) - **Pass**
 - Connect Wallet(from GIVfarm) - **Pass**
 -  Connect Wallet(from GIVback) - **Pass**
 - Connect Wallet and sign in (from passport banner) - **Pass**
 - Switch network (from donate page)  - **Pass** 
 - Donate ERC20  - **Pass**
 - Donate native token  - **Pass**
 - Stake GIV -  - **Pass**
 - Lock GIV  - **Pass**
 - Unstake GIV -  - **Pass**
 - Harvest rewards (GIVfarm)  - **Pass**
 - claim GIVbacks  - **Pass**
 - claim GIVstream  - **Pass**
-  Connect with Multisig   - **Pass**
 - Create recurring donation  - **Pass**
 - Modify recurring donation  - **Pass**
 - Deposit/withdraw from stream balance - **Pass**
 - Withdraw from stream balance - **Pass**
 - End recurring donation - **Pass**
