### ISSUE TITLE
WC Testing iPhone/Safari MOBILE | MetaMask MOBILE

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3331]
The following test cases should be completed and successful:

- [x] - Sign in
- [x] - Switch Network (from navbar dropdown menu)
- [x] - Switch Network (from givfarm)
- [x] - Connect Wallet(from GIVfarm/GIVback)
- [x] - Connect Wallet and sign in (from passport banner)
- [x] - Switch network (from donate page)
- [x] - Donate ERC20
- [x] - Donate native token
- [ ] - Stake GIV
- [x] - Lock GIV
- [x] - Unstake GIV
- [x] - Harvest rewards (GIVfarm)
- [x] - claim GIVbacks 
- [x] - claim GIVstream

**Comment by maryjaf** [comment]
I could complete donation flow on safari but stake, unstake, harvest .. just were like the result on chrome

**Comment by divine-comedian** [comment]
I found this reported error related to iPhone - the user was on chrome/iPhone but also could be applicable - they mentioned it was related to an ad-blocker service that blocked the tx popup on metamask on iPhone 
https://github.com/orgs/WalletConnect/discussions/3232

**Comment by maryjaf** [comment]
https://github.com/Giveth/giveth-dapps-v2/assets/111529185/841a27a1-a149-4ea0-974c-4094b6976793

**Comment by maryjaf** [comment]
https://github.com/Giveth/giveth-dapps-v2/assets/111529185/1cbe4f4f-519f-4e72-be75-53be0c494ddd

**Comment by maryjaf** [comment]
> y and I have only a problem on stake flow
> When I set 25%, the amount is shown 0 on

This problem has been resolved 
But now I get internal json-rpc error  in every try for staking on my iPhone 
![IMG_8127](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/0ee78866-de5d-48cc-8780-5b66c9f86902)

But @jainkrati has tested and could complete stake flow without any error

**Comment by maryjaf** [comment]
https://github.com/Giveth/giveth-dapps-v2/assets/111529185/15126ac7-f890-4262-a5bb-ae2fdc51fdd7

**Comment by divine-comedian** [comment]
According to @jainkrati  comments and test it appears to work fine for her - could be an issue related to the iPhone version 

I think we have to call this done and move on..

**Comment by maryjaf** [comment]
> According to @jainkrati comments and test it appears to work fine for her - could be an issue related to the iPhone version
> 
> I think we have to call this unit test passed and move on..

I checked with @MohammadPCh and based on logs that was set by Cherik,  there is a problem about difference of amount of stake in the first step and confirmation modal 
I'm not sure how much the impact of this problem can be on prod and whether we can ignore it or not

**Comment by maryjaf** [comment]
Should all type of wallets be shown in this modal or only metamask & wallet connect ?
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/158115dc-04e8-457a-b2d6-5f575b657040)

**Comment by divine-comedian** [comment]
@maryjaf - one thing that could be a cause of failure is if the approve amount is less than the amount requested to stake 

If the approve amount is even 0.0000000001 below the stake amount the tx will fail. @MohammadPCh  - so we need to absolutely make sure the approve amount is equal or a tiny amount greater than the stake amount to avoid any potential failures on staking 

We should also remove trust wallet from featured & included wallets.. for now.

**Comment by maryjaf** [comment]
> @maryjaf - one thing that could be a cause of failure is if the approve amount is less than the amount requested to stake
> 
> If the approve amount is even 0.0000000001 below the stake amount the tx will fail. @MohammadPCh - so we need to absolutely make sure the approve amount is equal or a tiny amount greater than the stake amount to avoid any potential failures on staking

Yeah exactly , checked with Cherik  yesterday and finally we could realize what happens, the amount of approval and amount  of stake are different and  it is the reason that some transaction failed 
if approval is more than stake amount the transaction completes but otherwise no

**Comment by maryjaf** [comment]
By last change that was made  by @MohammadPCh  this problem has been resolved
