### ISSUE TITLE
WC Testing: iPhone/Safari MOBILE | Coinbase Wallet MOBILE

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3333]
The following test cases should be completed and successful:

- [x] - Sign in
- [x] - Switch Network (from navbar dropdown menu)
- [x] - Switch Network (from givfarm)
- [x] - Connect Wallet(from GIVfarm/GIVback)
- [x] - Connect Wallet and sign in (from passport banner)
- [x] - Switch network (from donate page)
- [x] - Donate ERC20
- [x] - Donate native token
- [x] - Stake GIV
- [x] - Lock GIV
- [x] - Unstake GIV
- [x] - Harvest rewards (GIVfarm)
- [x] - claim GIVbacks 
- [x] - claim GIVstream
- [x] Connect with Multisig
- [x] Create recurring donation
- [x] modify recurring donation
- [x] deposit/withdraw from stream balance 
- [x] end recurring donation

**Comment by kkatusic** [comment]
@maryjaf do you have iphone?

**Comment by divine-comedian** [comment]
@maryjaf  this is ready for QA on staging 

You can get the coinbase wallet here 
https://www.coinbase.com/wallet

download it for mobile on your phone and set it up with some test funds

Then using safari browser on mobile test the connection and go through the test cases outlined above on mobile.
