### ISSUE TITLE
ETC on DApp | Donation page

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#3337]
- [ ] Allowed networks per org
- [x] balance tokens
- [ ] Token Logos
- [ ] Saving donation in impact-graph and 
- [ ] other edge-cases

**Comment by maryjaf** [comment]
Th showing balance for mETC isn't correct , and my balance for previous token is shown for this token @alireza-sharifpour 

<img width="1368" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/da106ab2-1b59-476b-bd9b-26d6da47b2da">
<img width="1060" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/dd92450f-b432-4873-8f16-1f6ef00895f1">

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/eaedcbe4-3ff2-447b-a9e1-89a44012abcb

**Comment by maryjaf** [comment]
> Th showing balance for mETC isn't correct , and my balance for previous token is shown for this token @alireza-sharifpour

This issue has been resolved.

**Comment by maryjaf** [comment]
When I try to donate on ETC by tapping on Donate button nothing happens 
<img width="1428" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/34798bbc-5fa7-4726-8218-fd214253707c">

**Comment by maryjaf** [comment]
> When I try to donate on ETC by tapping on Donate button nothing happens <img alt="image" width="1428" src="https://user-images.githubusercontent.com/111529185/276609160-34798bbc-5fa7-4726-8218-fd214253707c.png">

@mohammadranjbarz plz take a look

**Comment by alireza-sharifpour** [comment]
This issue should be fixed @maryjaf
