### ISSUE TITLE
ETC on DApp | Verification Wizard | Adding relative addresses

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#3340]

**Comment by alireza-sharifpour** [comment]
We already have this with basic configuration on the branch.

**Comment by maryjaf** [comment]
ETC isn't shown in this list @alireza-sharifpour 
<img width="1183" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/b89b494b-1f09-48eb-a82b-81192f53d180">

**Comment by alireza-sharifpour** [comment]
I think you are checking it on Staging but it's not on staging yet, it's on etc branch.

**Comment by maryjaf** [comment]
Yeah for this issue I checked a wrong url :)

When I select ETC and try to add address, I receive this error 
\"managingFunds.relatedAddresses[0].networkId\" must be one of [1, 3, 5, 137, 42220, 44787, 10, 420, 100]

<img width="1409" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/caf438a8-414a-41a1-83cb-70790894391e">

**Comment by alireza-sharifpour** [comment]
@mohammadranjbarz Can you please check it?
Address Payload:
<img width="834" alt="Screenshot 2023-10-18 at 2 31 28 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/48887817/f9a18879-1bbf-488f-8d41-332bced990c1">
Error:
<img width="917" alt="Screenshot 2023-10-18 at 2 31 59 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/48887817/5d80f1c8-688d-4012-8f64-fccef3d14a7f">

**Comment by maryjaf** [comment]
> @mohammadranjbarz Can you please check it? Address Payload: <img alt="Screenshot 2023-10-18 at 2 31 28 PM" width="834" src="https://user-images.githubusercontent.com/48887817/276122533-f9a18879-1bbf-488f-8d41-332bced990c1.png"> Error: <img alt="Screenshot 2023-10-18 at 2 31 59 PM" width="917" src="https://user-images.githubusercontent.com/48887817/276122623-5d80f1c8-688d-4012-8f64-fccef3d14a7f.png">

Kindly reminder @mohammadranjbarz

**Comment by maryjaf** [comment]
Thanks @mohammadranjbarz this problem has been resolved
