### ISSUE TITLE
Bundle "% to Giveth" donation w/ other donations so we don't have 2 txs

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3344]
Is there an easy way to do it?

In many cases, 5% of the donation is less than the gas the user pays for the 2nd tx. Got this feedback from one of our users in the Optimism QF round, and I totally agree!!

@MoeNick @divine-comedian @RamRamez - do you know anything about this?

**Comment by divine-comedian** [comment]
AFAIK it can't be done, not easily at least - we looked into this when we first implemented the donation to giveth option,

not unless we put a contract in place to batch the txs or we have smart wallets with AA
