### ISSUE TITLE
Add link to Bridge for QF rounds not on mainnet

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3345]
Someone suggested we add a link to the optimism bridge so that people can more easily donate in the Optimism QF round:

https://app.optimism.io/bridge/deposit

@mosaeedi - do you know a good place to put it?

**Comment by laurenluz** [comment]
@Tosinolawale can you take a look at this one & think about it?

basically... for some round, only donations on certain chains are eligible for matching... we have a warning thing on here that prompts a switch network.

maybe we also want to add somewhere a prompt to bridge funds & link to a bridge?

@divine-comedian - what's a good multipurpose bridge that we should send users to by default through giveth? cc @GriffGreen 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/16b153f2-7ae1-44dd-a6fb-b660d1324660)

**Comment by divine-comedian** [comment]
Still connext is great because it supports all of the EVM chains that Giveth does 
https://bridge.connext.network/

However Across has a rewards program but does not support gnosis chain
https://across.to/bridge

**Comment by laurenluz** [comment]
Thanks Mitch! I also asked @SnakeGH if he can do some research on if any of these bridges will give us referral bonuses...

@SnakeGH - maybe you can check these two + jumper and see what you come up with.

**Comment by laurenluz** [comment]
Thanks so much @SnakeGH for this research. Accross sounds great.

@Tosinolawale can you help to find a place where we can put a simple UX for supporting the user to bridge to a specific chain during QF rounds? 
lmk if you have questions.

**Comment by Tosinolawale** [comment]
> prompt to bridge funds & link to a bridge?

@laurenluz is there a specific trigger that will prompt this? Or is the link going to be present for all users to see irrespective of network connected?

**Comment by Tosinolawale** [comment]
https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=5441%3A59490&mode=design&t=zC1aaRqznG9pBfCd-1
@laurenluz 
![Wallet   is    connected](https://github.com/Giveth/giveth-dapps-v2/assets/35389241/5cb35a63-986d-49da-899f-408418a50c2d)

**Comment by laurenluz** [comment]
that's greaaaat - thanks @Tosinolawale!

not for referrer wallet.... @divine-comedian do you think you could/should generate the referral link w/ the treasury handler address... then we code that into the dapp here... and then when people use it, treasury handler earns rewards?

you can then claim them as part of treasury management?

otherwise, I can create a fresh wallet just for this and handle rewards claims. lmk

https://across.to/rewards/referrals

**Comment by divine-comedian** [comment]
I checked out if we could just hack the referral link but it looks like you can't use across on multisigs - so it would be hard to claim our referral rewards 

Please use the treasury address since it will be easy to cash out and dump our rewards back into giv.eth 

https://across.to?ref=0x9cd1E4A6b3361abcCC90C7F8E788ac246d194303

**Comment by laurenluz** [comment]
ok great, so this is out of design phase and ready for development @jainkrati. 

Basically it's just adding the "Bridge Funds" option when the QF round is restricted to specific chains. Looks like this:
![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/99db1612-1758-4485-8075-2d1babc561af)

Here is the link to figma: https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=5441-59490&mode=design&t=7NY56J80yRYP3mUH-4

And here is the link we should put for "bridge funds": [https://across.to?ref=0x9cd1E4A6b3361abcCC90C7F8E788ac246d194303](https://across.to/?ref=0x9cd1E4A6b3361abcCC90C7F8E788ac246d194303)

**Comment by maryjaf** [comment]
Thanks @MohammadPCh this new option is shown in donation page and redirected to (https://across.to/?ref=0x9cd1E4A6b3361abcCC90C7F8E788ac246d194303) 

<img width="944" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/b7d8acc9-7483-43af-93da-add48b02200e">
