### ISSUE TITLE
Bug in "% of Total" calculation in GIVpower summary table 

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3351]
Plz check the below video :
I try to set 54.89 % for one the projects in GIV power table but %54.9 has been set
or I try to set 54.86  but %54.85 has been set 

STG &  web3modal Env 

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/d4a2b47f-4073-4def-9ea6-b39698b06099

@MohammadPCh

**Comment by MohammadPCh** [comment]
@maryjaf Can we close this since we checked it together?
