### ISSUE TITLE
Weird QF scrolling issue

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#3356]
A lot of projects are listed twice... its like w eird loading error wher eit loaded the same projects again on the scroll

I scroll down and see this..
<img width="1514" alt="Screenshot 2023-10-16 at 7 40 01 AM" src="https://github.com/Giveth/giveth-dapps-v2/assets/14945613/e1d7601d-d8f2-4361-a2fc-b63891255b9c">

Then I scroll down more and see this:
<img width="1486" alt="Screenshot 2023-10-16 at 7 39 39 AM" src="https://github.com/Giveth/giveth-dapps-v2/assets/14945613/c4dde124-9e6f-4523-aadd-5d157023c17c">

https://giveth.io/qf

**Comment by laurenluz** [comment]
maybe you were scrolling when the projects were being rearranged by GIVpower?

or @MoeNick did you work with anyone to solve this? it seems to be fixed
