### ISSUE TITLE
Superfluid Donor: Creating recurring donation to project already donating to 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3360]
Related to #3091,  & #3359 
**Design is here:**
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/GIVeconomy?type=design&node-id=23293-17833&mode=design&t=Is2s27hF4hgjPWca-0

Condition is that user is trying to create a recurring donation of the same token to the same project.
![Donation-Recurring  3rd donation](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/5f8c5e43-6301-41d6-89a9-a3106dbff9d1)

User selects a token for which they are already using for a recurring donation to this project (on the same chain) 

- [ ] We show them an info toast message with some text and a link to the documentation ( link pending) 
- [ ] The user is not allowed to add a donation to giveth (UI portion is blurred out and unclickable) 
- [ ] The button text changes to "Modify Recurring Donation" - clicking this button opens the modify recurring donation modal #3286 
- [ ] show relevant information for if user action is successful or failed from modify modal (design pending from @Tosinolawale )

**Comment by MoeNick** [comment]
I added superfluid epic to this one, pls check the assignments and priorities.

@divine-comedian

**Comment by divine-comedian** [comment]
@MohammadPCh  - Did you already do this one?

**Comment by MohammadPCh** [comment]
@divine-comedian Yes, I did, but I need to update it when the backend is finished, and I may also need to check the changes that were made in the design.

**Comment by MohammadPCh** [comment]
@maryjaf it's ready to test.

**Comment by maryjaf** [comment]
> > 1- but by tapping on "modify recurring. donation" I see a strange result, please take a look on below screen record :
> 
> @maryjaf - Could you clarify the strange result you're seeing, I have a hard time following in the video what you're referring to.

I’ve checked it with Cherik and he starts working on that

**Comment by maryjaf** [comment]
> Could you clarify the strange result you're seeing, I have a hard time following in the video what you're referring to.

I think it’s about this problem that 
imagine I donated all of my super token, after that  I could select this super token and again donate all of them

**Comment by maryjaf** [comment]
> [x] 2- when I try to this project with another token I got this error

This problem has been resolved 
but I don't move this issue to done until the backend will be unblocked to test the donation flow completely(the donations is shown pending)

**Comment by jainkrati** [comment]
@mohammadranjbarz can you help test this

**Comment by maryjaf** [comment]
This problem has been resolved
but I don't move this issue to done until the backend will be unblocked to test the donation flow completely(the donations is shown pending)
