### ISSUE TITLE
GIV Apr shows 0% on Gnosis Chain

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-dapps-v2#3362]
**Describe the bug**
GIV Apr shows 0% on Gnosis. The token balances are shown correctly. Fox Apr shows correctly. GIV Apr on Optimism shows correctly.

**To Reproduce**
1. Go to 'giveconomy/givfarm'
2. Use Gnosis Chain and look at the GIV farm

**Expected behavior**
APR is shown

**Screenshots**
![image](https://github.com/Giveth/giveth-dapps-v2/assets/317685/978f44c5-cecb-489f-9cf9-372bc0e5f440)

**Desktop (please complete the following information):**
 - OS: MacOS 13.2.1
 - Browser: Chrome
 - Version: Version 117.0.5938.149 (Official Build) (arm64)

**Additional context**
I checked all the RPC endpoints we use for problems, but they are running fine

**Comment by laurenluz** [comment]
@mohammadranjbarz I didn't get a notify reward alert on Gnosis chain today for GIVpower.

I did get the alert for optimism chain... when we made the changes to optimism, did we forget to set the notify reward bot for gnosis?

cc @divine-comedian @MoeNick

**Comment by laurenluz** [comment]
Okiiii so just got eh notify reward email and now the APR is up... there must be an issue w. the time of our notify reward bot. @mohammadranjbarz can you check?
