### ISSUE TITLE
By tapping on "Create a Project" button, nothing happens 

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3363]
When I am on a below page I see "Create A Project" button but by tapping on it ,nothing happens 

<img width="1024" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/9526e880-4dce-42c9-9e1e-7efc616b7559">

Screen record:

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/6fb57466-aafe-4ea5-957a-cf2e3dc78846

cc: @MohammadPCh @divine-comedian

**Comment by divine-comedian** [comment]
Ah very interesting - looks like nothing happens because the success page for project creation and "create project"  are on the same route - `/create`

I don't think this is an urgent case and we can have it in the p backlog

**Comment by RamRamez** [comment]
@divine-comedian I moved the success view to /success route, so after project is created, user will be redirected to /success/[slug]

**Comment by maryjaf** [comment]
Tthanks @RamRamez this issue has been resolved
