### ISSUE TITLE
Users complaining that it's not obvious enough that only x chain is eligible for QF

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3364]
@mosaeedi would love your help this!
maybe a modal flow?

**Comment by mosaeedi** [comment]
On the donation page, 
if a user is not on an eligible network, we show this modal to let them know they must be on the specific network[ Optimism ] to match their donations.

[**Link to Figma**](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=4688-141694&mode=design&t=CPfYUe3fY0xsXjml-4)

<img width="595" alt="Screenshot 2023-10-27 at 1 30 38 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/0dbfd9ff-8a43-47d7-ad74-7a273348ce5e">

### Note
This modal is just for the situation where a user should switch to just **one specific network**. When we have to let the user to switch to more than one, we need to fix this modal.

**Comment by RamRamez** [comment]
@mosaeedi @laurenluz We already have this component:
![image](https://github.com/Giveth/giveth-dapps-v2/assets/73441857/460bb239-92ed-4367-a34e-0e1c52bfa2dd)

Should this be removed and show modal instead?

**Comment by laurenluz** [comment]
We should keep both!

Also copy edit on modal:
 
Title: Get you donations matched!

Subtext: Only donations made on < chains > are eligible for matching in the < name of round >.

Button: Switch network

Small text at bottom: You can still donate on other networks, but your donation won't be matched by quadratic funding.

**Comment by RamRamez** [comment]
We have a wrong network modal that will overlay this QF modal. I can show the QF modal only when user is on a project accepted chain (so there's no wrong network modal), but not on a QF matching eligible chain.

The second solution is to show both modals. When user closes first one, he will see the other.

@laurenluz WDYT?

**Comment by laurenluz** [comment]
I think we can set it up so that... if the user is on a chain not accepted by the project, they see only wrong network modal. 

then if they click "donate" and they are on a non-QF eligible chain, they get the "get your donations matched" modal.

In general, I think we should only show this "get your donations matched modal" if the user clicks "donate" after typing the doantion amount.

I updated my previous comment to explain this flow a little better. lmk if it's not clear

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/893ddb0d-47d8-45fc-8df1-fd32d9b5b1ba)

**Comment by maryjaf** [comment]
By tapping on "Donate" this error is shown
<img width="1431" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/1cee56c9-4fbb-400a-93d8-160dacb029e8">
@RamRamez

**Comment by RamRamez** [comment]
> By tapping on "Donate" this error is shown <img alt="image" width="1431" src="https://user-images.githubusercontent.com/111529185/281724814-1cee56c9-4fbb-400a-93d8-160dacb029e8.png"> @RamRamez

This is because the GF round is on OP but your project accepts OP Goerli. I don't have an idea how to prevent this in admin bro.
@divine-comedian @MoeNick @mohammadranjbarz do you have any idea?

I fixed it and now we show "unknown" for unknown chains.
@maryjaf You can test again.

**Comment by maryjaf** [comment]
> I fixed it and now we show "unknown" for unknown chains.
> @maryjaf You can test again.

I forgot to answer
I had tested this problem and it was solved

**Comment by divine-comedian** [comment]
@RamRamez @maryjaf - if there is no pending PR and the test has passed can we move this to the appropriate pipeline?
