### ISSUE TITLE
Remove typeform verification link from FAQ page

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#3367]
Looks like we found another typeform link that was missed.
https://giveth.io/faq

![image](https://github.com/Giveth/giveth-dapps-v2/assets/74267818/1c7dda7a-f46e-497f-a669-59e04bab47ba)

We should update this as we no longer use typeform.

Maybe it could say something like:

"If you would like to apply to receive the 'Verified' badge, encourage more giving and give back to those who have helped you reach your goals, you can apply directly from you project's page. Check out [this video](https://youtu.be/8myBgJCKXiU?si=bshRYsP9K5rNMZrn) or [this documentation](https://docs.giveth.io/dapps/projectVerification/) to learn more!"

**Comment by divine-comedian** [comment]
fixed in https://github.com/Giveth/giveth-dapps-v2/commit/bafdc70cc0fd59ea410159db323190a13e6eb182
