### ISSUE TITLE
Discontinue support for Torus wallets 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3374]
With the upcoming release of wallet connect we will no longer support torus wallets. 

We will need to:

- [x] - Draft banner/toast notification informing users that we no longer support torus wallet 
- [x] - provide link of documentation to show how to move their wallet to MM or another wallet https://docs.giveth.io/dapps/importTorusMM
- [x] - Remove options to log in with torus from dapp. related to: https://github.com/Giveth/giveth-dapps-v2/issues/3370

@mosaeedi up to you who you want to give this one to.

**Comment by divine-comedian** [comment]
@mosaeedi can we give this to @Ayaz1997 or is there a better way to kick this one out? the changes to the wallet connections went live earlier this week...

**Comment by mosaeedi** [comment]
<img width="1339" alt="Screenshot 2023-10-30 at 10 57 26 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/d8c36740-6d90-485c-88f1-d7bdc548e012">


[**Link to Figma**](https://www.figma.com/file/hNqwpebu4JCy1XIed2c862/Giveth-Public?type=design&node-id=1891-23265&mode=design&t=9jr2RvwjgpLak4i9-4)

@divine-comedian We need a better copy. I just put a dummy copy there!

**Comment by divine-comedian** [comment]
### Torus Wallet has been deprecated! 

We've removed support for Torus Wallets to connect to the Giveth Dapp, [follow this guide to move your keys over to MetaMask ](https://docs.giveth.io/dapps/importTorusMM).

**Comment by RamRamez** [comment]
@divine-comedian @mosaeedi We are going to inform all users, so we should show this banner on all pages, right?
Is the banner fixed or absolutely positioned?

**Comment by divine-comedian** [comment]
> @divine-comedian @mosaeedi We are going to inform all users, so we should show this banner on all pages, right? Is the banner fixed or absolutely positioned?

I don't think it is a heavily used feature 

We can feature it on the homepage only and have it as fixed position

**Comment by RamRamez** [comment]
@divine-comedian In FAQ, we tell user we support Torus. I think it's better to remove that.

**Comment by divine-comedian** [comment]
Good catch! Can you make a new issue @RamRamez and tag me?

**Comment by divine-comedian** [comment]
@RamRamez - what is the status? still waiting code review?

**Comment by maryjaf** [comment]
when I see this banner and I tap on close icon, after that by refreshing I see this banner for a one second, I think after closing this banner, banner shouldn't be shown again , am I right? @RamRamez 

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/aad564e1-c1b8-41cb-bb18-0afcb83b0a4a

**Comment by divine-comedian** [comment]
@RamRamez is there a way to make sure this doesn't show up at all for users who have already closed it?

**Comment by divine-comedian** [comment]
@RamRamez is there a way to make sure this doesn't show up at all for users who have already closed it?

**Comment by RamRamez** [comment]
I fixed it. @maryjaf Can you please test it again?

**Comment by divine-comedian** [comment]
@RamRamez Can we push this as a Hotfix? Many users are confused and don't have information on how to get back into Giveth
