### ISSUE TITLE
Not available project issues

### ISSUE THREAD

**Issue by RamRamez** [Giveth/giveth-dapps-v2#3377]
1. When I open a draft project with a non owner account I see this:
![image](https://github.com/Giveth/giveth-dapps-v2/assets/73441857/48390d0c-c058-4057-a988-19849c21ce27)

2. When I open a project with a wrong slug I see this:
![image](https://github.com/Giveth/giveth-dapps-v2/assets/73441857/971b0218-bdba-4580-8f99-89d10a010fc5)

3. When I open a cancelled project with owner and non owner I see this:
![image](https://github.com/Giveth/giveth-dapps-v2/assets/73441857/9c85c078-b345-4cd3-a8eb-d284472e47eb)

4. When I open edit project page with a wrong project ID I see this. Also top error toast should be removed.
![image](https://github.com/Giveth/giveth-dapps-v2/assets/73441857/fea27596-4711-488f-9966-95d272c4214a)

5. When I open edit project page with a non owner account I can see the edit view
![image](https://github.com/Giveth/giveth-dapps-v2/assets/73441857/13ea44ac-c20b-4c6b-bcdd-b64d680efdc2)

6. When I open draft project with owner and change account to non owner, I can still see the project
![image](https://github.com/Giveth/giveth-dapps-v2/assets/73441857/662e127d-9095-4b74-8460-1af08b475042)

7. When I open edit page for cancelled project with a owner account I see this
![image](https://github.com/Giveth/giveth-dapps-v2/assets/73441857/f400739b-3fb3-47c6-9196-b3e6f2b4e9bf)

8. When I open edit page for cancelled project with a non owner account I see this. Top toast should be removed.
![image](https://github.com/Giveth/giveth-dapps-v2/assets/73441857/4ef34c98-6293-4563-8f3f-6c8c14a6edb9)

FYI @maryjaf

**Comment by maryjaf** [comment]
Thanks @RamRamez This issue is related to changes of this https://github.com/Giveth/giveth-dapps-v2/issues/3176
