### ISSUE TITLE
Verification page issues

### ISSUE THREAD

**Issue by RamRamez** [Giveth/giveth-dapps-v2#3379]
1. When I open Verification view with a wrong slug, I expect to see not available view.
![image](https://github.com/Giveth/giveth-dapps-v2/assets/73441857/a585ff30-8c92-463f-beaf-19f9600c2267)

2. When I open Verification view for a deactivated, cancelled or draft project, I expect to see proper error message and disallow next steps.
![image](https://github.com/Giveth/giveth-dapps-v2/assets/73441857/51a91f51-be00-477c-9a51-a941740f2500)

3. When me as a not owner user try the verification process, I should get a proper error message

4. In single project view, the Verify button should only be shown to active not verified projects

FYI @maryjaf

**Comment by maryjaf** [comment]
Thanks @RamRamez the below pics be shown in different scenarios that are mentioned in issue 

1 & 2:
<img width="1678" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTVLQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--15eee6eaf297b66511af2a20cbe6e91d6aea5b0b/image.png" alt="image.png" />
3:
<img width="1624" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTFLQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c4c74e2f4cf9f27f4cca2549288d7ccef4d01a76/image.png" alt="image.png" />
