### ISSUE TITLE
Count Matching funds as part of the "funds raised" by the project for QF

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3386]
I want to include the matching funds as part of the total amount raised for projects.

We are already including it on the dapp & in our backend, but want to check to make sure it is adding to the total.

@mohammadranjbarz @CarlosQ96 - are we doing this already?

**Comment by maryjaf** [comment]
Now matching funds isn't counted in "All donation" calculation

**Comment by mohammadranjbarz** [comment]
I will implement these items, if you have another thing in your mind please let me know 
- [ ] Add a matching fund in each round to the sum of all donations of a project ( there wouldn't be any donation related to matching funds in donation table but we will sum up that value in all donations sum)
- [ ] Add it to value of total received of users ( project owner)

**Comment by laurenluz** [comment]
Agreed!

**Comment by maryjaf** [comment]
I've added 1000 matching fund  into this project "testprofilepic" and "MAYATESTI" round
<img width="1414" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/ef371028-b8fc-4caf-9c9f-16a6f3df4c09">
<img width="1408" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/54d10964-bc6c-4fab-b109-c5ee44da2132">

**Comment by mohammadranjbarz** [comment]
@maryjaf 
Can you make a donation to that project after adding the record to see what happens?

**Comment by maryjaf** [comment]
> @maryjaf Can you make a donation to that project after adding the record to see what happens?

After donating 0.01 USD  
**all donation** 
$122.64 --> 1122.65 (1000 matching fund + 0.01 donation )

**DONATIONS RECEIVED**
$1,019.04 -->  $9,019.11 (????)

**Comment by mohammadranjbarz** [comment]
@maryjaf Thanks for reporting that, now it's fixed and ok

**Comment by maryjaf** [comment]
Thanks @mohammadranjbarz the problem related to user's ONATIONS RECEIVED has been resolved
please take a look on this 
<img width="1329" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/30ad16ae-da77-4b04-a9e2-76730a8247f5">

**Comment by mohammadranjbarz** [comment]
@MohammadPCh  
What field do you use to show below **Total amount raised**?
You should use **totalDonations** to show correct amount

**Comment by maryjaf** [comment]
> @MohammadPCh What field do you use to show below **Total amount raised**? You should use **totalDonations** to show correct amount

Kindly reminder @MohammadPCh @mohammadranjbarz

**Comment by maryjaf** [comment]
@alireza-sharifpour has checked, it's field is "sumDonationValueUsd"
Now I'm not sure fixing this problem  should  be on backend or frontend
@mohammadranjbarz

**Comment by laurenluz** [comment]
was this fixed @aminlatifi @mohammadranjbarz  @maryjaf ?

**Comment by maryjaf** [comment]
Yeah It has been resolved on stg
after matching fund for polygon QF I'll check on prod and after that it would be closed
