### ISSUE TITLE
USD value calculations look off 

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapps-v2#339]
USD value does not make sense between these two rewards:

![image](https://user-images.githubusercontent.com/39466970/159834682-61d2906a-8db3-4f83-9789-a0b06c10b9d5.png)

**Comment by pkretzschmar** [comment]
@Danibelle I'm trying to reproduce this error but I can't. Could you test it again?

**Comment by MoeNick** [comment]
@Danibelle do you still have this issue?
