### ISSUE TITLE
As a Donor, I want to make a donation to a project on Solana

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3391]
When a user is connected to the solana network we should allow them to make a donation to a project. we should only allow specific tokens on solana network including the SOL native token.

related to https://github.com/Giveth/impact-graph/issues/1175

- SOL 
- mSOL
- USDC
- USDT
- RAY
- bSOL
- AUDIO
- MANGO
- Coin98

Here are the token images for some of the new tokens (USDT and USDC can be the same)

![iconC98Circle 5b1a0f1e](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/ed48f788-39bd-40f9-b17d-a0544dbbb572)
![mango](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/8fcf7b77-506f-425e-b5eb-dc57d94d9d64)
![audio](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/fbeed673-ca56-4043-bb24-d715cce258ac)
![bsol](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/5905d55a-a29b-4678-9227-36e54498c423)
![raydium](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/b4438467-a09e-4edb-abb2-d868146dac7e)
![solanaLogoMark](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/a9b61c3d-1f93-4450-abed-453b73f92506)
![solanaLogoMark](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/4ab30c11-70af-4bfd-8d0a-87dffa1897d4)
![mSOL](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/a57fc0cd-78de-4369-94a9-7985b46e502e)
![mSOL](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/07b6c242-02b6-4d79-a5f8-ffde9ed4aa03)

**Comment by MoeNick** [comment]
Is it ready and assigned to @CarlosQ96 already, what else you guys need pls lmk?

**Comment by CarlosQ96** [comment]
I think to start with just the Native token and a stable token might be the best option. 

But in any case this might not be THAT different than how we import tokens. We should work on the list to create a migration and add them.

But **4 hours** would be my estimate. We can re-use token logic.

Note: This estimate is just adding the tokens to the database, the actual donation is this issue: https://github.com/Giveth/impact-graph/issues/1188

**Comment by MoeNick** [comment]
Is it assigned to @CarlosQ96 or @mohammadranjbarz ?

**Comment by maryjaf** [comment]
I'm not sure this behavior is relato to incomplete implementation of this page or not, however I describe this to be checked 

My network Is set on solana and my user is signed in , by tapping on donate , Sign button is shown

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/9c59d0d4-5814-4458-864e-28928027bc54

**Comment by RamRamez** [comment]
> I'm not sure this behavior is relato to incomplete implementation of this page or not, however I describe this to be checked
> 
> My network Is set on solana and my user is signed in , by tapping on donate , Sign button is shown
> 
>  Screen.Recording.2024-01-11.at.2.14.14.PM.mov

it's related to recurring donations. My changes related to Solana on donation page is on the old donation page.
@jainkrati I think we should turn off recurring donation flag on staging because all new Solana changes are in old donation page.

**Comment by maryjaf** [comment]
@alireza-sharifpour  is going to turn recurring donation off on stg

**Comment by divine-comedian** [comment]
> > I'm not sure this behavior is relato to incomplete implementation of this page or not, however I describe this to be checked
> > My network Is set on solana and my user is signed in , by tapping on donate , Sign button is shown
> > Screen.Recording.2024-01-11.at.2.14.14.PM.mov
> 
> it's related to recurring donations. My changes related to Solana on donation page is on the old donation page. @jainkrati I think we should turn off recurring donation flag on staging because all new Solana changes are in old donation page.

Won't you need to update the donation page to the new one anyway in order to have both Solana features and recurring donation on production?

**Comment by MoeNick** [comment]
@RamRamez is working on token list

**Comment by RamRamez** [comment]
@mohammadranjbarz @aminlatifi do we have these tokens list on staging? because when I filter by "networkId: 103" I can only see the native token

mSOL
USDC
USDT
RAY
bSOL
AUDIO
MANGO
Coin98

**Comment by aminlatifi** [comment]
> @mohammadranjbarz @aminlatifi do we have these tokens list on staging? because when I filter by "networkId: 103" I can only see the native token
> 
> mSOL USDC USDT RAY bSOL AUDIO MANGO Coin98

@RamRamez can you get the list of all solana tokens returned for `getAcceptableTokens`?
