### ISSUE TITLE
Verification | Managing Funds Tab| Missing Networks

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#3396]
I can't see 
- Polygon
- Celo

networks in the list

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVIxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ee867c284b9812231a44cd2fdd87e7e2c86713f2/image.png)

@CarlosQ96 can you take a look at production? 

FYI @maryjaf

**Comment by maryjaf** [comment]
It seems there is no problem in this list
<img width="1242" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/5a52ca08-fb1e-4c2c-a171-a2ac17df67e7">

**Comment by MoeNick** [comment]
Ah that scroll! 
ok nevermind, maybe even I typed above and could not find any specific chains!

**Comment by maryjaf** [comment]
could we close this ? @MoeNick 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWwrQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--896ef6c099160e1a2a99abd390a0c9f8f18a6cce/image.png)
