### ISSUE TITLE
Notify Users to switch network if a feature is not available on Solana (or Ethereum)

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3399]
This should include:
- Projects that don't accept funds on Solana
- Projects that don't accept funds on EVM chains
- Recurring Donations 
- GIVeconomy pages
- NFT | PFP
- Gitcoin passport

---

## figma
https://www.figma.com/file/vMiyVd1Ly5LjgSyZrChVV8/Giveth-users?type=design&node-id=992%3A142551&mode=design&t=6gBBVPBLcG3Z1cC7-1

**Comment by MoeNick** [comment]
@jainkrati shall we move it to the product backlog and assign it to @aminlatifi ?

**Comment by MoeNick** [comment]
This issue has been defined before, on Nov 28th I asked for an assignment.
CC: @jainkrati

**Comment by mosaeedi** [comment]
<img width="450" alt="Screenshot 2024-01-01 at 6 38 43 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/6551d739-5717-4150-9f3f-b06035e2726d">

I think we have to think about a copy that can be logical for all situations or probably use different copies in the modal!

[Link to Figma](https://www.figma.com/file/vMiyVd1Ly5LjgSyZrChVV8/Giveth-users?type=design&node-id=1722-32872&mode=design&t=ilrJO5Cd0G1kZBgQ-4)

**Comment by MoeNick** [comment]
@mosaeedi 
the cases are dfferent:
 -Projects that don't accept funds on Solana: we have this change network modal like below
 
![image](https://github.com/Giveth/giveth-dapps-v2/assets/80677512/3135e92f-d126-43f4-a3f8-1c1012068a06)

 but we need the Solana logo to load sign-in with Solana Splash page

- GIVeconomy pages: we have this design, 
![image](https://github.com/Giveth/giveth-dapps-v2/assets/80677512/b78cdaf2-2b90-43af-bc19-a3c76a3b7aec)
![image](https://github.com/Giveth/giveth-dapps-v2/assets/80677512/4eb298bc-5284-4abe-a9ab-dc5a17290965)

But we need all of these logos load sign-in with Ethereum splash. 

- Recurring donation:
I think you should help me for this case.

**Comment by mosaeedi** [comment]
I think this one can solve the issue.

[Link to Figma](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=5096-28961&mode=design&t=iYhuH3AeplOVxxND-4)

**Comment by maryjaf** [comment]
> This should include:
> 
> * Projects that don't accept funds on Solana
> * Projects that don't accept funds on EVM chains
> * Recurring Donations
> * GIVeconomy pages
> * NFT | PFP
> * Gitcoin passport
> 
> ## figma
> https://www.figma.com/file/vMiyVd1Ly5LjgSyZrChVV8/Giveth-users?type=design&node-id=992%3A142551&mode=design&t=6gBBVPBLcG3Z1cC7-1

If Givpower isn't active on solana should the "boost option " be disabled when user signed in with solana network ? or a seperate message on boost modal should be shown in this scenario @MoeNick @divine-comedian

**Comment by MoeNick** [comment]
Boost can be done, its not related to staking

**Comment by MoeNick** [comment]
> I think this one can solve the issue.
> 
> [Link to Figma](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=5096-28961&mode=design&t=iYhuH3AeplOVxxND-4)

This is the final design @divine-comedian @mosaeedi @maryjaf

**Comment by maryjaf** [comment]
> This is the final design @divine-comedian @mosaeedi @maryjaf

GIVeconomy isn't based on this figma 

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/51dad8ec-5a77-4f9e-b596-cef0c1a252e0

**Comment by maryjaf** [comment]
2-
"switch network" doesn't  work in donation page 

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/58f68752-180a-4515-9897-a2370c5b3e96

**Comment by maryjaf** [comment]
> * Gitcoin passport
3-
gitcoin passport doesn't support solana, but I see "connect wallet" in passport banner when my network is set on solana
and by tapping connect wallet sth weird happens 


https://github.com/Giveth/giveth-dapps-v2/assets/111529185/6245b673-6d85-4dc8-b211-6cb5647c2321

**Comment by maryjaf** [comment]
Is it possible that this issue has been moved to QA by mistake?

**Comment by maryjaf** [comment]
> * NFT | PFP

There is no change on this

**Comment by maryjaf** [comment]
Is it possible that this issue has been moved to QA by mistake?

**Comment by maryjaf** [comment]
please take look on the below scenario of switch network

-my network is set on solana and my wallet is phantom
-tap on switch network from menu
-select phantom 
-I see a new eth wallet address and m network is set on goerli
-by tapping on sign out I see my previous wallet address on solana 

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/390b64ec-eb9a-489b-971d-212c08a8e846

**Comment by alireza-sharifpour** [comment]
> 2- "switch network" doesn't work in donation page
> 
>  Screen.Recording.2024-01-15.at.11.25.27.AM.mov

We should continue this when backend's data structure for Solana is finalized. With current backend implementation it has 103 networkId 
<img width="522" alt="Screenshot 2024-01-16 at 1 48 39 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/48887817/27e3ab31-cdbe-4ffa-8644-0aec23cf7516">
And this button is not working.

**Comment by MoeNick** [comment]
@mohammadranjbarz can we add the data to staging that it can be testable?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz can we add the data to staging that it can be testable?

I didn't get your point

**Comment by alireza-sharifpour** [comment]
With the latest PR every issues related to GivEconomy switch network and PFP switch network functionality should be fixed.
It's ready for review.

**Comment by maryjaf** [comment]
> 5- please take look on the below scenario of switch network
> 
> -my network is set on solana and my wallet is phantom -tap on switch network from menu -select phantom -I see a new eth wallet address and m network is set on goerli -by tapping on sign out I see my previous wallet address on solana
> 
>  Screen.Recording.2024-01-15.at.11.51.30.AM.mov

‌By previous changes on switch network, this problem has been resolved

**Comment by alireza-sharifpour** [comment]
> > * Gitcoin passport
> 
> 3- gitcoin passport doesn't support solana, but I see "connect wallet" in passport banner when my network is set on solana and by tapping connect wallet sth weird happens
> 
>  Screen.Recording.2024-01-15.at.11.37.40.AM.mov

Thanks @maryjaf,
Please test this again, it should be fixed.

**Comment by maryjaf** [comment]
should"connect wallet" on GIVpower page be changed to "switch wallet "like as GIVback and GIVfarm page? @alireza-sharifpour 
<img width="1304" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/43f0d42c-e2da-4bbf-80bc-fb973db09945">

**Comment by maryjaf** [comment]
> > * NFT | PFP
> 
> 4- There is no change on this

Thanks @alireza-sharifpour item 4  has been resolved and if the chain be set on solana "switch network" button is shown

**Comment by maryjaf** [comment]
> > > * Gitcoin passport
> > 
> > 
> > 3- gitcoin passport doesn't support solana, but I see "connect wallet" in passport banner when my network is set on solana and by tapping connect wallet sth weird happens
> > Screen.Recording.2024-01-15.at.11.37.40.AM.mov
> 
> Thanks @maryjaf, Please test this again, it should be fixed.

Item 3 has been resolved and Now everything about passport banner is fine

**Comment by maryjaf** [comment]
> 2- "switch network" doesn't work in donation page
> 

> should"connect wallet" on GIVpower page be changed to "switch wallet "like as GIVback and GIVfarm page? @alireza-sharifpour <img alt="image" width="1304" src="https://private-user-images.githubusercontent.com/111529185/297379868-43f0d42c-e2da-4bbf-80bc-fb973db09945.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0OTUyNzUsIm5iZiI6MTcwNTQ5NDk3NSwicGF0aCI6Ii8xMTE1MjkxODUvMjk3Mzc5ODY4LTQzZjBkNDJjLWUyZGEtNGJiZi04MGJjLWZiOTczZGIwOTk0NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExN1QxMjM2MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDM0ZjM4Y2IyNjhiMTY3MWYxZDEwNWY4NjU3ZDQ4NGI3Mjk3ZjdjNDUxMDkyYTY0M2I4ODI2OGIyZTEyMjdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Fs8Dmc6vlP8B1n7q67WvS8JVqAHnR1Xa229D_-rDHio">

last Update :
Only this problemes are still open

**Comment by maryjaf** [comment]
> 2- "switch network" doesn't work in donation page
> 
>  Screen.Recording.2024-01-15.at.11.25.27.AM.mov

I tested again and the problem still exists. by tapping on switch network nothing happens and also in change network modal the solana network isn't shown , this project has only one solana wallet address
please take  a look @alireza-sharifpour

**Comment by alireza-sharifpour** [comment]
> I tested again and the problem still exists. by tapping on switch network nothing happens and also in change network modal the solana network isn't shown , this project has only one solana wallet address

Yes, I'm working on it, I'll let you know when it's fixed. @maryjaf

**Comment by maryjaf** [comment]
> I tested again and the problem still exists. by tapping on switch network nothing happens and also in change network modal the solana network isn't shown , this project has only one solana wallet address
> please take a look @alireza-sharifpour

I tested again the issue related to not showing solana network icon in change network modal has been resolved, Thanks @alireza-sharifpour 

but please take a look on below scenario:

-My network is set on polygon 
-The project supports solana , celo and ethereum classic 
-By tapping on switch network on donation page
-Only "Connect a wallet on Solana to continue"  modal is shown 
In this case what is the expected result  in your opinion ? @MoeNick 

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/254ed228-00e2-4569-8c59-6fe5b96bd920

**Comment by alireza-sharifpour** [comment]
> > I tested again and the problem still exists. by tapping on switch network nothing happens and also in change network modal the solana network isn't shown , this project has only one solana wallet address
> > please take a look @alireza-sharifpour
> 
> I tested again the issue related to not showing solana network icon in change network modal has been resolved, Thanks @alireza-sharifpour
> 
> but please take a look on below scenario:
> 
> -My network is set on polygon -The project supports solana , celo and ethereum classic -By tapping on switch network on donation page -Only "Connect a wallet on Solana to continue" modal is shown In this case what is the expected result in your opinion ? @MoeNick
> 
>  Screen.Recording.2024-01-22.at.11.21.39.AM.mov

This behavior is something from the past, when the user clicks on "that" switch network button you clicked, we don't show the user the list of networks, we just switch to first network of the list of supported networks we get from the backend.
So it's not something new. but if we need to change it please tell me. @MoeNick @maryjaf

**Comment by alireza-sharifpour** [comment]
@maryjaf The Givpower switch network also should be fixed.

**Comment by maryjaf** [comment]
> @maryjaf The Givpower switch network also should be fixed.

Thanks @alireza-sharifpour this problem also has been resolved and now the below pic is shown
<img width="1321" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/ba0a1b41-cb0e-4a1c-88c8-f817abfd88c7">

**Comment by MoeNick** [comment]
> > > I tested again and the problem still exists. by tapping on switch network nothing happens and also in change network modal the solana network isn't shown , this project has only one solana wallet address
> > > please take a look @alireza-sharifpour
> > 
> > 
> > I tested again the issue related to not showing solana network icon in change network modal has been resolved, Thanks @alireza-sharifpour
> > but please take a look on below scenario:
> > -My network is set on polygon -The project supports solana , celo and ethereum classic -By tapping on switch network on donation page -Only "Connect a wallet on Solana to continue" modal is shown In this case what is the expected result in your opinion ? @MoeNick
> > Screen.Recording.2024-01-22.at.11.21.39.AM.mov
> 
> This behavior is something from the past, when the user clicks on "that" switch network button you clicked, we don't show the user the list of networks, we just switch to first network of the list of supported networks we get from the backend. So it's not something new. but if we need to change it please tell me. @MoeNick @maryjaf

@alireza-sharifpour 
Can we disable that button in the header menu while the user is on Solana?

**Comment by alireza-sharifpour** [comment]
> > > > I tested again and the problem still exists. by tapping on switch network nothing happens and also in change network modal the solana network isn't shown , this project has only one solana wallet address
> > > > please take a look @alireza-sharifpour
> > > 
> > > 
> > > I tested again the issue related to not showing solana network icon in change network modal has been resolved, Thanks @alireza-sharifpour
> > > but please take a look on below scenario:
> > > -My network is set on polygon -The project supports solana , celo and ethereum classic -By tapping on switch network on donation page -Only "Connect a wallet on Solana to continue" modal is shown In this case what is the expected result in your opinion ? @MoeNick
> > > Screen.Recording.2024-01-22.at.11.21.39.AM.mov
> > 
> > 
> > This behavior is something from the past, when the user clicks on "that" switch network button you clicked, we don't show the user the list of networks, we just switch to first network of the list of supported networks we get from the backend. So it's not something new. but if we need to change it please tell me. @MoeNick @maryjaf
> 
> @alireza-sharifpour Can we disable that button in the header menu while the user is on Solana?

You mean the SwitchNetwork Button on donation top of donation page?

<img width="473" alt="Screenshot 2024-01-22 at 1 59 17 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/48887817/9ab3756d-fb82-46d5-8cce-812143d888d9">

**Comment by MoeNick** [comment]
- Switching the network on the donate page should pen up the wrong network modal again. 
- Switch network on the header should be hidden
@alireza-sharifpour

**Comment by maryjaf** [comment]
Thanks @alireza-sharifpour switch network problem has been resolved
