### ISSUE TITLE
Add image to USDGLO token

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3401]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGwzQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0d1f1485a1d504a02d5d344680b9e5343dfe16ec/image.png)

It should be "Glo Dollar (USDGLO)" as per [coin gecko](https://www.coingecko.com/en/coins/glo-dollar)

I think this is on Ethereum Mainnet, Optimism, Polygon & Celo.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHgzQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6038a43d914c34d0b4ba6eb83cece0f9d7f05fbc/image.png)

Also, shouldn't we have the logo/icon for Glo in there instead of the "?"

@divine-comedian @MoeNick

**Comment by divine-comedian** [comment]
related to https://github.com/Giveth/impact-graph/issues/1168

**Comment by divine-comedian** [comment]
Changes should be made to the names & symbol 

Can you update the token image? @mohammadranjbarz 
https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fd235dzzkn2ryki.cloudfront.net%2Fglo-dollar_large.png&f=1&nofb=1&ipt=fc735a104aa632a618da6c2e3bda11fc0242c81442670270e1efb36f9b61a604&ipo=images

**Comment by laurenluz** [comment]
maybe this one is bigger? Glo dollar sent it to me via twitter

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/4aa04381-ebd9-465f-826e-372c59b688c7)

**Comment by divine-comedian** [comment]
pushed a hotfix and should be working properly now on production 
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/9c6c9280-b56d-4ff6-a3a2-36762ace8b53)
