### ISSUE TITLE
Set up notify reward bots for gnosis & optimism

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3402]
Hey @mohammadranjbarz !

We need to extend the rewards for GIVpower starting on Tuesday so I'll need your help setting up notify reward bots for both gnosis and optimism.

We will have a total of 12.5 million GIV for incentives for 14 rounds

25% on Optimism = 3 125 000 GIV total
75% on Gnosis = 9 375 000 GIV total.

We basically want to distribute them according to the following percentages (but the GIV amounts here is showing the total accross both chains, so I think it's not useful to you):

![Screenshot_20231028_221126_Sheets.jpg](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/e88a7a6f-1e89-4de5-958b-a350fadec025)

I grabbed that screenshot from [this spreadsheet](https://docs.google.com/spreadsheets/d/1neUUsppi4HZ5b0BlOUR60Vt2Hn-_e-hvoJeO20cTqyk/edit?usp=drivesdk) in the GIVpower Oct '23 tab.

So we need to set up the notify reward bots  for both chains.

On Monday I'll make sure we assign a new balance to the unipools but would love if you could help set up the notify reward!

They should basically start on Tues Oct 31 so ideally you could work on this tomorrow or monday :)

cc @MoeNick

**Comment by mohammadranjbarz** [comment]
@MoeNick  @laurenluz 
We did it a month ago, we can move it to done, WDYT?

**Comment by laurenluz** [comment]
done and closed!
