### ISSUE TITLE
Naming of "GIVpower" & "Rank" filter 

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3406]
It seem it should be better if this filter name is changed 
because I think it makes the user be confused 
I set rank sort but in url GIVpower is shown although  GIVpowr sort exists also and it's related to instant boosting

<img width="1439" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/6fd6282a-0800-44af-b117-99a7fe5e6b00">
@MohammadPCh

_Originally posted by @maryjaf in https://github.com/Giveth/giveth-dapps-v2/issues/910#issuecomment-1783737064_

**Comment by maryjaf** [comment]
https://github.com/Giveth/giveth-dapps-v2/issues/910#issuecomment-1784031055

**Comment by laurenluz** [comment]
I think we can change the name of "rank" for now to "GIVbacks %"

coming soon I think we will be changing the functionality of GIVpower, and so will likely soon just remove this filter... but a simple copy fix in the meantime should help.

cc @divine-comedian

**Comment by divine-comedian** [comment]
fixed in https://github.com/Giveth/giveth-dapps-v2/commit/71f3cbc90f6eff02907fc3d8b9187d2fedf10146
