### ISSUE TITLE
GIV/week value is not correct on op network

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapps-v2#3421]
**Describe the bug**
In stream page (/givstream) the flowrate of givstream is shown in two places, small one on top and big one on the center
In op network, the flowrate at the center is zero, while it's positive
![image](https://github.com/Giveth/giveth-dapps-v2/assets/5684607/e3ff2ca2-28c1-469f-b633-6160fd406420)

**Comment by laurenluz** [comment]
!! wow this is still happening months later.

we should allocate some resources to fixing bugs like this, I think, if we can, in the next sprint @MoeNick @jainkrati

**Comment by jainkrati** [comment]
@MohammadPCh please take a look

**Comment by aminlatifi** [comment]
@MohammadPCh Do you want to push this as a hotfix to production soon?

**Comment by MohammadPCh** [comment]
@maryjaf Could you please test this? Thanks.

**Comment by MohammadPCh** [comment]
@aminlatifi I think we can have a release too. but actually, I don't know who is responsible for this decision.

**Comment by aminlatifi** [comment]
@MohammadPCh would you please make a hotfix PR for it?

**Comment by maryjaf** [comment]
Thanks @MohammadPCh this problem has been resolved
Thanks @aminlatifi for reporting
<img width="1564" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelZZQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e8d2b4eb5846cba5f50faec7170289f5176283be/image.png" alt="image.png" />

**Comment by laurenluz** [comment]
is this merged to prod yet? still shows 0 for me.
![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/aa963691-326a-41b7-86f9-8666c63a28c3)

**Comment by MohammadPCh** [comment]
@laurenluz No, it hasn't been merged yet.
