### ISSUE TITLE
GitCoin and torus wallet banners issue

### ISSUE THREAD

**Issue by MohammadPCh** [Giveth/giveth-dapps-v2#3429]
![image](https://github.com/Giveth/giveth-dapps-v2/assets/17097576/28219443-3cdd-4122-a6b8-64643ef99f78)
go to giveth.io and scroll down. I think it's not acceptable.

**Comment by maryjaf** [comment]
Uploading Screen Recording 2023-11-27 at 4.16.37 PM.mov…

**Comment by maryjaf** [comment]
https://github.com/Giveth/giveth-dapps-v2/assets/111529185/261d7ca6-e827-4c1c-a34c-ddfe2bf6ac71

**Comment by RamRamez** [comment]
@divine-comedian When the user scrolls down, will the banners disappear (like the passport banner in /qf)? or should they stick to the page top? What is the expected behavior for GitCoin and Torus banner?
