### ISSUE TITLE
Low pri: kind of weird that the "donating" button changes color when I mouse over it

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#343]
When the tx is in progress... I think it should just be grayed out and untouchable.

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/48c5321d-3ec5-413f-9521-52ead6fde7df)

**Comment by divine-comedian** [comment]
button does not change colour anymore and it is untouchable when hovered over. moving to DONE! 
![image](https://user-images.githubusercontent.com/67759413/163680305-9c393162-8d4a-4c64-9aaf-7c2c09f3d71f.png)
