### ISSUE TITLE
P0 - Assign balance to GIVpower unipool on Gnosis

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3430]
We have extended the GIVpower incentives program as per [this forum post](https://forum.giveth.io/t/givpower-summary-requesting-giv-for-incentives-update-q4-2023/719/25) and updated the notify reward bot as per this PR: https://github.com/Giveth/giv-token-contracts/pull/94

But afaik, we did not assign a new balance to the unipools on gnosis of Optimism to give the unipool permission to actually send out those rewards.

We need to do this!

Only, at this point, I'm confused about how much of a balance the unipools have, and how much GIV we need to assign to them.

I could really use help looking into these numbers from @aminlatifi or perhaps @mohammadranjbarz

**Comment by laurenluz** [comment]
The last tx I saw that assigned a balance on gnosis chain was [here](https://discord.com/channels/679428761438912522/773912257368817684/1153529239711260702). In my message it says that this should have covered us until October 17... but I think I meant that it should go until Oct 31.

I'm assuming that a balance was assigned to the unipool in Optimism, but I didn't see this happen. There was only a message, [this in discord](https://discord.com/channels/679428761438912522/759816279623467023/1148742832367079546).

And then, afaik, we never assigned a balance to the unipools for the new rewards that we started up Oct 31! so we need to!

With 12,500,000 GIV assigned & a 75% / 25% split gnosis / Optimism... we should assign a balanace of 9,375,000 GIV on Gnosis and 3,125,000 GIV on Optimism.

**Comment by aminlatifi** [comment]
@mohammadranjbarz Can you do it? then I review

**Comment by mohammadranjbarz** [comment]
> Reference

We dont want to notify reward we just want to send GIVs to token distro
@laurenluz  Am I right?

## Optimism
Token Distro address : https://optimistic.etherscan.io/address/0x301c739cf6bfb6b47a74878bdeb13f92f13ae5e7
We have **23Million** GIV that is enough

## Gnosis
Token Distro address: 
https://gnosisscan.io/address/0xd93d3bdba18ebcb3317a57119ea44ed2cf41c2f2

We need 12,500,000  * (1 - 0.0615 round 1 - 0.063 round2) = 12,500,000 * 0.8755 = **109,437,50**

**Comment by laurenluz** [comment]
Not quite - we need to assign a balance of GIV to the unipool, I think basically giving permission to the unipool to spend GIV from the token distro... (while it looks like we also need to send extra GIV to the token distro on gnosis)

Amin was doing this before and then the last couple of times I did it. I never it did it on Optimism though. It requires the giv.eth multisig to basically sign a tx to give permissions to the unipool to spend GIV.

**Comment by aminlatifi** [comment]
> Not quite - we need to assign a balance of GIV to the unipool, I think basically giving permission to the unipool to spend GIV from the token distro... (while it looks like we also need to send extra GIV to the token distro on gnosis)
> 
> Amin was doing this before and then the last couple of times I did it. I never it did it on Optimism though. It requires the giv.eth multisig to basically sign a tx to give permissions to the unipool to spend GIV.

We topped up optimism givpower permission to pay reward on Dec 25 for 3125000.0 GIV
https://optimistic.etherscan.io/tx/0x11dd771661ee9d54054e85ec71c6a5c242096c9f06839e11f1c64cdf7ad59b4d#eventlog
The final step is being sure optimism tokenDistro has enough GIV inside to pay rewards. So, we must send equivalent amount of liquidity (3125000.0 GIV) to token distro.

**Comment by aminlatifi** [comment]
@laurenluz We have implemented an endpoint to query history of assigns on token distro
https://givback.develop.giveth.io/api-docs/#/GivFarm%20utilities/get_token_distro_assign_histories
The default values are set to inquiry Gnosis GivPower assigned history. 
For other chains, fill contract values based on records https://www.notion.so/giveth/Deployment-52935e6579034f1b940bbef161e82229?pvs=4 and set appropriate RPC endpoint (https://chainlist.org/ can help)  

I prepared queries for OP and Gnosis here:

## Optimism ## 
https://givback.develop.giveth.io/token_distro_assign_histories?tokenDistroAddress=0xE3Ac7b3e6B4065f4765d76fDC215606483BF3bD1&uniPoolAddress=0x301C739CF6bfb6B47A74878BdEB13f92F13Ae5E7&rpcUrl=https%3A%2F%2Foptimism.llamarpc.com


## Gnosis ##
https://givback.develop.giveth.io/token_distro_assign_histories?tokenDistroAddress=0xc0dbDcA66a0636236fAbe1B3C16B1bD4C84bB1E1&uniPoolAddress=0xD93d3bDBa18ebcB3317a57119ea44ed2Cf41C2F2&rpcUrl=https%3A%2F%2Frpc.gnosischain.com

**Comment by divine-comedian** [comment]
@laurenluz  - this alredy happened correct?

**Comment by laurenluz** [comment]
yesss

**Comment by GriffGreen** [comment]
oops didnt do gnosis

**Comment by GriffGreen** [comment]
There is a Discord DM with the deets, can we push this out this week PLEASE.
