### ISSUE TITLE
Donor: Create Allo Profile in Recurring Donation

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3439]
Extension of #3091 

There is an extra step involved when a project is going to receive its first recurring donation - We need to setup a profile for it on Allo Protocol - This deploys an AnchorContract which becomes the recipient of the recurring donation. 

cc: @MohammadPCh FYI

## System Flow
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/12fb5b20-a2ef-410c-9dff-aa2900bfc41d)

This is an extra modal/transaction for the Donor, who pays the tx and sets up the profile on behalf of the project. This is done by calling `createProfile` on the registry contract

https://github.com/allo-protocol/allo-v2/blob/main/contracts/core/Registry.sol#L118

The Registry can be found here on OP Goerli:
https://goerli-optimism.etherscan.io/address/0x4AAcca72145e1dF2aeC137E1f3C5E3D75DB8b5f3

And on OP Mainnet: 
https://optimistic.etherscan.io/address/0x4AAcca72145e1dF2aeC137E1f3C5E3D75DB8b5f3

## Creating an Allo Protocol Profile 
We call this function in the registry contract: 
https://github.com/allo-protocol/allo-v2/blob/main/contracts/core/Registry.sol#L118

Which takes a few arguments:
```
   function createProfile(
        uint256 _nonce,
        string memory _name,
        Metadata memory _metadata,
        address _owner,
        address[] memory _members
    )
```
### nonce
- unique integer used with the owner address to create the address hash of the anchor contract 
- must use a different nonce for project owners who own multiple projects (can we use the projectId in our DB?)

### name
- can use the project slug or project name

### metadata
- empty for now

### _owner
- the address of the project owner 

### _members
- leave empty for now

## Sequence
Here is the flow for when a user starts a recurring donation from the UI:
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/507367fb-f215-47ef-8531-04e91c131308)

## Figma
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/GIVeconomy?type=design&node-id=23970%3A14336&mode=design&t=Y0WYEAUOBSeS2TK1-1

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/9a54a058-0c94-4df8-ae59-0f569f37e3c1)

**Comment by jainkrati** [comment]
@CarlosQ96 and @mateodaza assigned you a similar one earlier. @divine-comedian lets discuss this in our meeting as well.

**Comment by alireza-sharifpour** [comment]
I've implemented a hook for this feature so we can use it in both Create Project and first donation.
It is working, the remaining part is saving it on the backend so we can fetch it later.
Also the UI for this needs to be implemented on donation page.

@divine-comedian @jainkrati

**Comment by alireza-sharifpour** [comment]
This issue is ready for testing @maryjaf

**Comment by maryjaf** [comment]
could you plz check this @alireza-sharifpour 

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/afdcf6cc-e52c-475b-bef2-05ba9889e987

**Comment by maryjaf** [comment]
2-
when I try to complete a recurring donation for the first time on  [metesta](https://staging.giveth.io/donate/metesta) )project
I got an error
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/124377c1-97d6-4fe5-8b91-c72583105df6)

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/4439072a-ddc1-409a-af0c-044d5c3ca697

**Comment by maryjaf** [comment]
3-
in the first try "Donate Monthly to testamotestam" and "Donate Monthly to the Giveth DAO" are shown zero in confirm donation modal , please check the below video 
I'm not sure item 2 & 3 is  related to this issue for sth else 

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/0f5a1428-1ec6-4d0f-b9dd-92f41bdab671

**Comment by alireza-sharifpour** [comment]
Thanks @maryjaf for all the testing, this issue is only for creating AlloProtocol profile for projects that does not have AlloProtocol profile while donating.

So the only thing you need to test for this issue is that part.

The Donation flow is not completed yet as far as I know because it does not have Backend.
Also donation flow has it's own issue.

**Comment by maryjaf** [comment]
Thanks @alireza-sharifpour I've completed test of Allo profile and it seems everything is ok 
and for a project with Allo profile these fields be added in response of api
"anchorContracts": [
                {
                    "txHash": "0x37c2b2aa35a08b3762a49dc72fc822ca2b36655343a97f46910a3ed50d02d4fb",
                    "address": "0x7dade7edf31abd8e14d90779295028b112b67100",
                    "networkId": 420,
                    "isActive": true
                }
            ]

and I'll  add above comments on related issue

**Comment by jainkrati** [comment]
@mohammadranjbarz to add details to unblock this.

**Comment by jainkrati** [comment]
@mohammadranjbarz gentle reminder to add the details

**Comment by maryjaf** [comment]
> Thanks @alireza-sharifpour I've completed test of Allo profile and it seems everything is ok and for a project with Allo profile these fields be added in response of api "anchorContracts": [ { "txHash": "0x37c2b2aa35a08b3762a49dc72fc822ca2b36655343a97f46910a3ed50d02d4fb", "address": "0x7dade7edf31abd8e14d90779295028b112b67100", "networkId": 420, "isActive": true } ]
> 
> and I'll add above comments on related issue

The tests of this issue had completed and I moved it to done,
after deploying on prod it could be closed
cc: @alireza-sharifpour @jainkrati

**Comment by divine-comedian** [comment]
Testing on https://staging.giveth.io/donate/test-social-media 

I tried to create an anchor contract for a project - I clicked the confirm button and received the tx, the first tx was successful however it was not registered by the FE or the BE and I cannot proceed, the modal popups and does nothing 

https://github.com/Giveth/giveth-dapps-v2/assets/67759413/4ab5bfcb-fce3-437e-9c5a-86b03a392535

You can see we have an info message in the console showing our error: 
```
error ContractFunctionExecutionError: The contract function "createProfile" reverted.

Error: NONCE_NOT_AVAILABLE()
 
Contract Call:
  address:   0x4AAcca72145e1dF2aeC137E1f3C5E3D75DB8b5f3
  function:  createProfile(uint256 _nonce, string _name, (uint256 protocol, string pointer), address _owner, address[] _members)
  args:                   (223949, test-social-media, {"protocol":1,"pointer":""}, 0x10a84b835c5df26f2a380b3e00bcc84a66cd2d34, [])
  sender:    0x826976d7C600d45FB8287CA1d7c76FC8eb732030
  ```
  
  The nonce is random however it looks like it is trying to insert the same number into the function call, even on page refresh this problem persists. #3842 did not solve this issue it appears.
  
 Also, as I've mentioned before We should also be using the projectId of the project not it's slug - sine the Id is constant while the slug can be changed.

**Comment by alireza-sharifpour** [comment]
> Testing on https://staging.giveth.io/donate/test-social-media
> 
> I tried to create an anchor contract for a project - I clicked the confirm button and received the tx, the first tx was successful however it was not registered by the FE or the BE and I cannot proceed, the modal popups and does nothing
> 
>  Screencast.2024-03-25.15.52.18.mp4 
> You can see we have an info message in the console showing our error:
> 
> ```
> error ContractFunctionExecutionError: The contract function "createProfile" reverted.
> 
> Error: NONCE_NOT_AVAILABLE()
>  
> Contract Call:
>   address:   0x4AAcca72145e1dF2aeC137E1f3C5E3D75DB8b5f3
>   function:  createProfile(uint256 _nonce, string _name, (uint256 protocol, string pointer), address _owner, address[] _members)
>   args:                   (223949, test-social-media, {"protocol":1,"pointer":""}, 0x10a84b835c5df26f2a380b3e00bcc84a66cd2d34, [])
>   sender:    0x826976d7C600d45FB8287CA1d7c76FC8eb732030
> ```
> 
> The nonce is random however it looks like it is trying to insert the same number into the function call.
> 
> Navigating back to this donate page from a fresh browser window or even on page refresh this problem persists. #3842 did not solve this issue it appears.
> 
> Also, as I've mentioned before We should also be using the projectId of the project not it's slug - sine the Id is constant while the slug can be changed.
> 
> @alireza-sharifpour you'll need to take another look at this issue and the fix for this bug.

It's not a problem with the random number, I did the changes on Create Project page but I forgot to update this modal on donation page.
I'll update it and the problem should resolve.

**Comment by maryjaf** [comment]
Thanks 
This problem has been resolved
