### ISSUE TITLE
What is GIVstream popup from reward menu, it goes away before I tell it to

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#344]
From reward menu "?"... when I click it, I get the popup and then the popup just disappears... without me clicking it or anything.

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/4fbca962-f3e3-4772-b2fe-3081b8900692)

**Comment by divine-comedian** [comment]
testing on `staging.giveth.io` 

the GIVstream popup no longer closes automatically - I can close the modal by clicking away from the modal, clicking GOT IT or clicking the x in the top corner. 

issue seems to be resolved! moving to DONE!
