### ISSUE TITLE
Project Owner: Claim Recurring Donations from Anchor Contract

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3441]
Related to #3094 

Once #3440 & #3439 are implemented we will need to claim recurring donations from the project's Anchor contract instead of their project recipient address, since the anchor contract will be the recipient of the super tokens via recurring donation. 

This starts by calling the execute() function in the Anchor contract by the projectOwner
https://github.com/allo-protocol/allo-v2/blob/main/contracts/core/Anchor.sol#L73C4-L73C4
```
function execute(address _target, uint256 _value, bytes memory _data) external returns (bytes memory)
```
We target the supertoken Contract and encode some callData to call this function: 
```
function downgradeTo(address to, uint256 amount) external virtual override
```
https://github.com/superfluid-finance/protocol-monorepo/blob/dev/packages/ethereum-contracts/contracts/superfluid/SuperToken.sol#L715C4-L715C5

This will allow us to downgrade the super tokens held by the anchor contract to regular tokens and give them to the project recipient address

# How to claim multiple tokens
while this is possible via the SDK we will need to figure out how to do this via encoded callData 

the superfluid docs only provided information on batching calls via SDK

this is an open research question @jainkrati 
cc: @alireza-sharifpour 

# Sequence 
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/569ceb6e-17bd-4723-b788-af2554808859)

**Comment by divine-comedian** [comment]
Loop through a list of multiple downgradeTo function calls - depending how many tokens - if we loop through multiple downgradeTo calls - if we go beyond the gas limit the tx reverts - more complicated to call the batch call

if you want to downgrade and transfer it will be more complex. 

what are the thigns we can change? allo protocol is from gitcoin 

what are the changes that gitcoin made? what can we change and what can't we? we can't change this execute - make a middle contract and change it multiple times? 

project owner is EOA - make a contract inbetween that handles batching the function 

middle contract is called by project owner which calls the anchor contract which executes the batch calls 

do we need to deploy two contracts for one project per contract? middle contract can be owned by Giveth? 

we have two options - one option is to have a smart contract that owns all the anchor contract - don't have to redeploy everytime - allow people to call the anchor contracts and downgrade the tokens

if it has some security issues we don't like we create one clone per project - the front-end will need to call one function - if we have to engineer somethign with the database w/ the front-end if its just a smart contract that will be there forever 

one token at a time 

use case is how many tokens do we support and how often you want the receivers to downgrade - how often do we want the users to claim? 

why did we opt to use allo protocol - might simpler solution in superfluid before - receiver is an nft - the NFT is transferrable 
the owner is receiving the flows flow NFTs are not sure if they are transferrable - tradeable cash-flow NFTs

whatever request we are making it should request a signature from a user - use case should be the project owner should decide who the recipient address is

the anchor contract is made when you have to check it out - 

should be triggered from - maybe power pool can do this - if we make it good users won't know 

we can batch all the txs on one chain 

wagmi can allow us to batch txs later - can implement this later 

superfluid has batch txs - pieces of solidity code

need meta transactions to solve it - wagmi can't do this yet

will be hard to solve later 

three steps - downgrade tokens then transfer ownership then transfer 

biconomy has good options - if there is just one token per users - doing one token at a time we can keep showing them to move to the next token.

if we want to batch in the future we need to change the anchor contract owners

**Comment by alireza-sharifpour** [comment]
Thanks @divine-comedian for the data.
The UI Part of this issue is done (Except the change that was introduced lately that the user can only claim one token at a time), I'll start investigating and working on it after I finish the backend part of Anchor Contract creation.
@jainkrati

**Comment by alireza-sharifpour** [comment]
This issue is done and merged, but it cannot be tested until the backend of donation is completed.
@maryjaf @divine-comedian

**Comment by alireza-sharifpour** [comment]
I should test this issue after finishing createDonation section to see if it works on OP Sepolia or not.

**Comment by maryjaf** [comment]
- [ ]  1- "Claim recurring donation" should be shown only in project actions in my project list? or it should be add in actions in project page also? @divine-comedian 

<img width="1339" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/ba8a58a0-5a7a-4d78-b8eb-1743c825cc9f">
<img width="1228" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/20716672-90e6-49cb-a7b4-3e079f72f536">

- [ ] 2- after completing claim flow the shown amount isn't updated, please take a look @alireza-sharifpour 

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/e65cfe7a-52e6-4a96-9584-35569226e939

**Comment by divine-comedian** [comment]
@maryjaf - nice catch! 

@alireza-sharifpour is it possible to add this button the menu she mentioned above on the project owner view of the project page.
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/88e46c3e-9df9-4ddd-ab54-eb2de2b1604e)

**Comment by maryjaf** [comment]
Thanks @alireza-sharifpour these 2 problem have been resolved
<img width="545" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/bac418b1-6165-49a3-a33c-8cbe9a3a3406">
<img width="1358" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/eaf15a91-bd66-4933-aa9b-a8171f7b3a62">

**Comment by maryjaf** [comment]
This process has run into trouble again and it should be assigned again to a developer @jainkrati 

- [ ] - by tapping on "claim recurring donation" nothing happens 

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/69d70dfd-b9bf-4fce-bfe2-15e41190328d

- [ ] -the showing usd in't correct 
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/14532c34-3ba3-4fb2-ab11-d7b5c7178ca2)

**Comment by alireza-sharifpour** [comment]
@maryjaf, It should be fixed and It's ready for testing.

**Comment by maryjaf** [comment]
> - [ ] 2-the showing usd in't correct

ETH price has been fixed but GIV price is shown 0
<img width="842" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/223ab433-56d3-4943-bea3-cb5f577fe766">
@alireza-sharifpour

**Comment by maryjaf** [comment]
> **- [ ] 1- by tapping on "claim recurring donation" nothing happens**

This problem hasn't been fixed yet  @alireza-sharifpour

**Comment by alireza-sharifpour** [comment]
Can you check the scope of the Claim issue?

Is it related to any specific project or address?
Is it related to any specific Token? for example do you have problem claiming both ETH and GIV or one of them?
@maryjaf

**Comment by maryjaf** [comment]
> Can you check the scope of the Claim issue?
> 
> Is it related to any specific project or address? Is it related to any specific Token? for example do you have problem claiming both ETH and GIV or one of them? @maryjaf

I've checked claim flow on these 2 project and ETH claim doesn't work 
but for GIV this flow is ok and I haven't any problem for claiming 
https://staging.giveth.io/project/testupdate1000
https://staging.giveth.io/project/mejan

**Comment by divine-comedian** [comment]
@alireza-sharifpour  - looks like something is wrong with their contract - you might need to call `downgradeToETH` and then transfer the ETH from anchor to recipient address (two txs) 

https://sepolia-optimism.etherscan.io/address/0x0043d7c85C8b96a49A72A92C0B48CdC4720437d7#writeContract#F1

**Comment by alireza-sharifpour** [comment]
> @alireza-sharifpour - looks like something is wrong with their contract - you might need to call `downgradeToETH` and then transfer the ETH from anchor to recipient address (two txs)
> 
> https://sepolia-optimism.etherscan.io/address/0x0043d7c85C8b96a49A72A92C0B48CdC4720437d7#writeContract#F1

Thanks @divine-comedian, Yes I saw this downgradeToEth function for first transaction and it works fine and downgrade the ETHx to ETH correctly.
For the second transaction, which function of the contract should I encode and pass to execute? @divine-comedian

**Comment by divine-comedian** [comment]
@alireza - we would need to downgrade the ETHx to ETH then transfer the ETH from the anchor to the recipient address - 

We may be able to use https://www.multicall3.com/ to batch these transactions together, preventing any failures and stuck funds @jainkrati is familiar with this one.

**Comment by jainkrati** [comment]
Best if superfluid fixes it so that we dont have to play the catchup game. If Superfluid team cant fix it in next 3 weeks, lets do it ourselves.

**Comment by divine-comedian** [comment]
@jainkrati to follow up with @MohammadPCh  to code the necessary work around.

**Comment by maryjaf** [comment]
> > Can you check the scope of the Claim issue?
> > Is it related to any specific project or address? Is it related to any specific Token? for example do you have problem claiming both ETH and GIV or one of them? @maryjaf
> 
> I've checked claim flow on these 2 project and ETH claim doesn't work but for GIV this flow is ok and I haven't any problem for claiming https://staging.giveth.io/project/testupdate1000 https://staging.giveth.io/project/mejan

On this issue, this problem was reported @divine-comedian @jainkrati 
and it is in "inprogress" state
