### ISSUE TITLE
Add Trust Wallet to web3Modal

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3445]
Add in support for Trust Wallet for users to login and use the dApp
https://walletconnect.com/explorer/trust-wallet 

We will need to thoroughly test all cases & app functions - Test cases exist in this epic already

**Comment by MohammadPCh** [comment]
@divine-comedian We now have the Trust Wallet! Should we pass it to QA, or is there a bug we need to address first?

**Comment by divine-comedian** [comment]
We can find all the test cases here: 

- [ ] #3320 
- [ ] #3323
- [ ] #3326 
- [ ] #3329 
- [ ] #3332 


https://github.com/orgs/Giveth/projects/9/views/1?filterQuery=is%3Aopen+trust"
to confirm @MohammadPCh we can test this on STAGING? 

@LatifatAbdullahi you can find this wallet app here https://trustwallet.com/ there is a desktop extension you can use for desktop based testing and also there is a phone app for mobile testing. 

Regarding testing & tokens - you might be able to import your metamask accounts into trust wallet (I don't know exactly) which will let you have all your token balances you need for testing. 

AFAIK trust wallet should support all the chains that we support according to this page https://trustwallet.com/browser-extension

**Comment by divine-comedian** [comment]
@maryjaf just a few more test scenarios to go through, if they all pass we can move this issue to done 

Reminder that we removed solana compatibility from the requirements
