### ISSUE TITLE
Archive FOX/xDAI regen farm

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3450]
related to #3420 

The rewards on the FOX/xDAI RegenFarm have run out! We should put a little "This farm has ended" thing on top of it.. and then after 2-3 weeks we should hide the farm under the "archived" tab.

We have done this in the past with other farms. @mateodaza & @MohammadPCh are familiar with it.

@jainkrati @MoeNick - this should really be done soon, because the 0% APR is confusing to people. The farm ended Nov 30.

**Comment by laurenluz** [comment]
this is what it should look like:

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/1d943404-c1ee-4363-9486-778469a39979) 

The stake button should be disabled, the unstake button & harvest button should function as normal, if the user has some rewards or staked tokens.

**Comment by MoeNick** [comment]
I think it's shipped, shall we close it? @maryjaf
