### ISSUE TITLE
Problem relate to sign Gitcoin passport message with multisig account 

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3451]
When I try to sign  message of Gitcoin passport, after confirmation of 2 signer, the below message is shown
**"Invalid signature for nonce"**

**To Reproduce**
1. Go to 'My Account'
2. Scroll down to 'Gitcoin Passport'
3. Tap on "SIGN MESSAGE"
4. complete confirmation and sign
5. See error

**Screenshots**
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/802893c2-c8c3-434d-9bca-41a4728d94cd)

![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/7b8b048d-3ac8-4f0b-b9dc-82f167ee7f47)

**Comment by maryjaf** [comment]
In QF page the "sign message" option is shown
<img width="1434" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/4434cd76-de8a-486a-a6db-c5bf248264e7">

**Comment by divine-comedian** [comment]
> In QF page the "sign message" option is shown @mateodaza @divine-comedian <img alt="image" width="1434" src="https://private-user-images.githubusercontent.com/111529185/289773884-4434cd76-de8a-486a-a6db-c5bf248264e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NzUyMjAsIm5iZiI6MTcwMjQ3NDkyMCwicGF0aCI6Ii8xMTE1MjkxODUvMjg5NzczODg0LTQ0MzRjZDc2LWRlOGEtNDg2YS1hNmRiLWM1YmYyNDgyNjRlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QxMzQyMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hODk0YzViZjhjMjkyNTI1NTM5NWNlYzU4YjBjNWY2NzI1MzA2ZDYwM2UxOWE5YzFkYzNhZDQyNWRjYWVkZDhlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7lUWqM-F5P5jZtZcZ2vNRZE7Ik7KZRTPiEmSeIdGH18">

We shouldn't give them the option to sign a message if they are a multisig - since it will be pointless work for them. 

We should show the banner with the text I mentioned above for this condition

**Comment by maryjaf** [comment]
"Estimated matching" and passport box in donation page and success page are  shown when the user signed in with multisig,  if we just remove those elements when a multisig is connected it will be fine
 ![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/9f136baa-a1ac-4a48-a8b4-fd7dce5407cb)
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/e12032b4-a9e3-459d-833f-3928c54a2f67)

**Comment by maryjaf** [comment]
Thanks @mateodaza it has been resolved
