### ISSUE TITLE
List of problems related to Multisig 

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3453]
- [x] 1. After confirmation of signer and sign in Giveth, by tapping on my account with multisig account this error is shown
**"Application error: a client-side exception has occurred (see the browser console for more information)."**
([More description](https://discord.com/channels/@me/1179670731882233896/1180143689612415006))

- [x] 2. Error on donation, it's sending the safe tx hash instead of the regular tx hash - so the backend is not finding it

- [x] 3. Problem relate to sign Gitcoin passport message with multisig account #3451

- [x] 4. Problem about user profile after expiration of his session 
(Description: after 3 days that my session is expired, when I do confirmation of signers and then tap on my account, this message is shown 
"Your profile is incomplete, You can’t create a project unless you complete your profile."
although I already have a complete profile)
([More description](https://discord.com/channels/@me/1179670731882233896/1181137034115567657))

- [x] 5. Stake problems 
(when I try to stake some giv I stuck in "approve" loop  or after confirmation of 2 signers this message is shown " Something went wrong")
([More description](https://discord.com/channels/@me/1179670731882233896/1181566749796208701))

- [x] 6. switch network problem from GIV menu
([More description](https://discord.com/channels/@me/1179670731882233896/1181542347809509406))

- [x] 7. success modal isn't shown after stake, lock...

cc: @mateodaza @CarlosQ96 @divine-comedian

**Comment by mateodaza** [comment]
@maryjaf as udpates

For #1 and 4 I'm not able to replicate, I have the feeling is something related with gnosis safe interface being slow on load

For #6 I'll hide the change network button, it shouldn't be allowed just like the signout option

I'm working on the other ones

**Comment by mateodaza** [comment]
@maryjaf 

For # 7 I gotta refactor the "waitForTransaction" function that is used in almost all actions, it's different for all multisigs

I'll research and check what's the most optimal approach

**Comment by maryjaf** [comment]
> For # 1 and # 4 I'm not able to replicate, I have the feeling is something related with gnosis safe interface being slow on load

Thanks @mateodaza 
# 1 happens when you create a new safe account and for the first time tap on My account
# 4 you should complete the profile for your multisig account in Giveth , after the token expires (after three days or manually through the admin panel) tap on my account and you could  see the below pic
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/21d87f2f-cb35-4aed-804a-b8081a8d229c)


I think the changes related to 6 aren't deployed, I couldn't see any change, am I right?
Please let me know when the changes are deployed so I can test again

**Comment by maryjaf** [comment]
Update:
Thanks @mateodaza @CarlosQ96 
4,5,6 & 7 have been resolved 

1 & 2 are open, I've written more description about  bugs of donation [here](https://discord.com/channels/@me/1179670731882233896/1184403052707467384)

and about #3 it should be considered a correct copy in passport banner if the user signed in with multisig account

**Comment by maryjaf** [comment]
Thanks @mateodaza all problems have been resolved

**Comment by maryjaf** [comment]
Please check below scenarios @mateodaza 
When one of singer rejected transaction, unsuccess modal isn't shown
for example in donation flow the user sees this modal until clicks on close icon

<img width="1364" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/9a97c55a-d5af-4f73-ac1f-4e8068302d8e">

**Comment by maryjaf** [comment]
My donations is not shown in "my donation" table but in project's donation table my donation is recorded
@mateodaza 

<img width="1370" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/f6c5956b-0a9a-41ae-919f-51d36bd387b6">

<img width="1427" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/066443f8-994f-489d-85f1-003158fef335">

**Comment by maryjaf** [comment]
> My donations is not shown in "my donation" table but in project's donation table my donation is recorded @mateodaza
> 
Thanks @mateodaza 
This problem has been resolved and now  my donation are shown.
but there is an problem related to rejection of donation that this makes a pending donation is shown in list , I create an issue for this to be resolved in next phase
