### ISSUE TITLE
Change matching cap from 20% to 18% for our Holiday QF round

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3457]

**Comment by laurenluz** [comment]
@MohammadPCh @mohammadranjbarz this needs to be working properly on production by the lastest December 18 :)

As discussed, I think it's just changing a hard-coded numbers, but since we never changed this before since we went live with the alpha round, I think it's worth testing. 

cc @jainkrati @maryjaf

**Comment by mohammadranjbarz** [comment]
In the backend side we just need to change `QF_ROUND_MAX_REWARD_PERCENTAGE` from `0.2` to `0.18` in our config (production.env)

@jainkrati 
When you say I will change it and restart the production application to load new config


@MohammadPCh  But I think there is something in frontend that you should change as well

**Comment by laurenluz** [comment]
let's make sure we get this live before monday please!

**Comment by mohammadranjbarz** [comment]
> In the backend side we just need to change `QF_ROUND_MAX_REWARD_PERCENTAGE` from `0.2` to `0.18` in our config (production.env)
> 
> @jainkrati Once you say I will change it and restart the production application to load new config
> 
> @MohammadPCh But I think there is something in frontend that you should change as well

@laurenluz Done.

**Comment by laurenluz** [comment]
done & on production? ready for QF round start on Tuesday? :) @MohammadPCh @mohammadranjbarz 

or are we waiting for a release?

**Comment by MohammadPCh** [comment]
@MoeNick @jainkrati We need to release this. who is responsible for release? also, I can release it as a hotfix. let me know what should I do in our new structure.

**Comment by MoeNick** [comment]
tbh Im confused and I dont know.
I think @maryjaf also cant test all changes in staging in a new flow in one day.
I vote for hotfix, if you can give here a preview to test.

**Comment by maryjaf** [comment]
I tested this on feature branch and the matching found cap was calculated correctly 
https://giveth-dapps-v2-git-change-qf-matching-cap-givethio.vercel.app/
