### ISSUE TITLE
Put "Giveth Quadratic Force"  PDF under Giveth domain

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#3459]
[GivethQF Marketing.pdf](https://github.com/Giveth/giveth-planning/files/13529734/GivethQF.Marketing.pdf)

Figma:
 https://www.figma.com/file/LKBHpnxI9sLjde7DzOQIYQ/Giveth-Marketing?type=design&node-id=4240%3A247&mode=design&t=CdbE1fKjr9IkbvE6

**Comment by GriffGreen** [comment]
> The URL should be https://giveth.io/GivethQuadraticForce

can we make it:
https://giveth.io/QuadraticForce
?

**Comment by mmahdigh** [comment]
> > The URL should be https://giveth.io/GivethQuadraticForce
> 
> can we make it: https://giveth.io/QuadraticForce ?

Absolutely!

**Comment by MoeNick** [comment]
Any updates on that @mmahdigh ?

**Comment by mmahdigh** [comment]
#3474
