### ISSUE TITLE
Typo on "my projects" for users without projects

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#346]
Should say:
"You haven't created any projects yet!"

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/946a7798-755d-402e-a2b1-fe430011b9db)

**Comment by RamRamez** [comment]
For testing PR #374:
1. fix typo for `projects`, `donations` and `liked projects` tab in my account and public profile view (in my account should read: "You haven't" and in public profile view should read "This use hasn't")
2. Add "user not found" for public profile view

**Comment by divine-comedian** [comment]
testing on `staging.giveth.io` 

checked my user account for when I have no projects and also from user public profile and the typos appear to be fixed! 
![image](https://user-images.githubusercontent.com/67759413/163816598-94479312-1604-4076-aac9-df94b476824f.png)

calling this DONE
