### ISSUE TITLE
Project Quality Improvements

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3461]
# Problem

- Projects are often low quality with short descriptions and/or no media
- Project Owners make projects and expect funds to arrive automatically - they don’t promote their projects well.
- Project Owners abandon their project and stop using Giveth after some time - they stop providing periodic updates
- Checking if a project made an update in the last 3 months and notifying projects to make an update is entirely manual and very time consuming

# Solution

Identify small upgrades we can make to the project owner experience. This work should be small enough that it can be done piece meal between larger projects or picked up when developers are blocked by other work.

## Ideas

- minimum characters count for project description
- adding in social media handles on profile info - giving admins a more direct way to contact project owners/users
- checking for project updates & automating sending emails to remind projects to update their project periodically - make sure we cover this in email service migration
- notifications center - notifications for project update reminder
    - https://github.com/Giveth/impact-graph/issues/932

<img width="325" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjA3QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--14f784dbe491bfa08560c6e108317a14b737b8bf/image.png" alt="image.png" />

- improve the intro window - project description checklist! Add a checklist - tell the project they should add:
    - links to their project website
    - links to their social media accounts
    - photos/video of their project

<img width="679" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnc3QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4686b874f6c3f6dca8b14f3988e4d39d81ad9774/image.png" alt="image.png" />

- hub for creators - where they can easily find information that is useful for their project
    - https://giveth.io/onboarding/projects
- have the onboarding landing pages and project onboarding page available from more places
    - project creation page
    - community navbar drop down
    - homepage first fold - ramin is working on this
- could have more content for project owners on the homepage update - projects page view

**Comment by jainkrati** [comment]
@RamRamez pls take this up and sync up with @divine-comedian

**Comment by divine-comedian** [comment]
@jainkrati - Do we want to give these FE issues to @MohammadPCh ?
