### ISSUE TITLE
Allow projects to provide social handles for contacting them

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3466]
Allow projects to provide users with ways to find them on various social media platforms - these fields would be private and totally optional for them, potential handles should include: 

- Faceook
- Website
- Discord 
- Twitter

**Comment by jainkrati** [comment]
Please assign me once designs are ready @divine-comedian

**Comment by divine-comedian** [comment]
add input field in the project creation flow, we don't need them to validate with Oauth

validate the url only for now 

maybe we do some sort of Oauth verification later

have something for users who already have a project - ask them to enter a social media so they are aware and use this new feature. have it when they look at 'my projects' when they look at my project details page. 

show toast notification on my projects page that shows up only once for users letting them know to add social media info to their existing project

**Comment by divine-comedian** [comment]
We will add a separate section to the edit/create project flow that will allow projects to add specific social media links, the section looks like this: 

https://www.figma.com/file/vMiyVd1Ly5LjgSyZrChVV8/Giveth-users?type=design&node-id=2177%3A18369&mode=design&t=htQC6qxgOxveRl2V-1
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/fe87cf50-66ed-43f9-ad91-81c878c89597)


On the public/preview/private project page view the entered social media links appear as badges like this: 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/1fec220e-3b3f-401a-ac5a-3cc5771e6f9b)

The full options and their url validation must contain: 

| Platform Name | Validation Text            |
|---------------|----------------------------|
| Twitter       | twitter OR x.com       |
| Facebook      | facebook.com               |
| Youtube       | youtube.com OR youtu.be    |
| Reddit        | reddit.com                 |
| Discord       | discord                    |
| Instagram     | instagram.com              |
| Linkedin      | linkedin.com  |
| Farcaster     | no validation              |
| Lens          | no validation              |
| Website  | no validation  |


## In the back-end 

We will need to add fields to store this new project information, either appending or creating a new table associated with each project as well as a way to save & retrieve them from the front-end

**Comment by divine-comedian** [comment]
@jainkrati  - take a look at this one - needs a little bit of back-end work before the front-end work

**Comment by divine-comedian** [comment]
@jainkrati  - Do we want to pass this one to another developer? It will require BE work so we might have to wait longer for this one.

**Comment by MoeNick** [comment]
For your information, we have some ready-to-go codes in the verification flow with domain validation and some oAuth validation for X, Google account, and Discord. it has a call-back service to impact -graph. 
I hope this will be helpful to you.

**Comment by alireza-sharifpour** [comment]
If the backend of this issue is ready, I need details.
@MoeNick

**Comment by MoeNick** [comment]
It needs backend work, please sync with @jainkrati for that the link in figma has designs

**Comment by divine-comedian** [comment]
Just made the BE issues here, waiting for a dev to be assigned 

https://github.com/Giveth/impact-graph/issues/1364

One correction we'll need to make on the designs is in the public view the text. In the original design each badge had the handle of the social media account in the badge text. This might be complicated to retrieve for each platform, like Discord for example. or if the user uses a shortened link  
![Screenshot from 2024-02-26 08-06-02](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/b3a678c7-b14d-4159-a501-5445a43f542d)

**Comment by RamRamez** [comment]
@divine-comedian I can see "Reddit" in [your comment](https://github.com/Giveth/giveth-dapps-v2/issues/3466#issuecomment-1930615789) in this issue, but I can't see it in the Figma or in the [impact-graph issue](https://github.com/Giveth/impact-graph/issues/1364). We need "Reddit" as well, am I right?

**Comment by divine-comedian** [comment]
> @divine-comedian I can see "Reddit" in [your comment](https://github.com/Giveth/giveth-dapps-v2/issues/3466#issuecomment-1930615789) in this issue, but I can't see it in the Figma or in the [impact-graph issue](https://github.com/Giveth/impact-graph/issues/1364). We need "Reddit" as well, am I right?

Good catch! @Tosinolawale - can you add in the missing field for reddit on the create/edit project page?

**Comment by Tosinolawale** [comment]
![Create Project UI](https://github.com/Giveth/giveth-dapps-v2/assets/35389241/c6770ec3-fbe7-4529-8ca4-2510d83ebb6c)
![Project Single - About](https://github.com/Giveth/giveth-dapps-v2/assets/35389241/a70a4662-18ff-44b9-a7ba-606069031caa)

https://www.figma.com/file/vMiyVd1Ly5LjgSyZrChVV8/Giveth-users?type=design&node-id=1907%3A23890&mode=design&t=WCheVDY1PgmWjwDl-1

Updated @divine-comedian
