### ISSUE TITLE
Link onboarding guide in more places on the dapp

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3467]
We should add links to our onboarding guide in the following places, I will explain the section and reference the exact links we need to use: 

Here's the figma for referece:
https://www.figma.com/file/vMiyVd1Ly5LjgSyZrChVV8/Giveth-users?type=design&node-id=2206%3A43398&mode=design&t=7MQM0shETRJXjcpH-1

## on the navbar -> Community tab
link: https://giveth.io/onboarding
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/d7f7727f-abe7-48d5-9b9e-2c5a7be405f5)

## Footer 
link: https://giveth.io/onboarding
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/eb3ea138-1855-480f-a49f-fb5559d41a8d)

## project details page -> donation details component
link: https://giveth.io/onboarding/donors
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/e8fd860c-a354-4893-acc0-8aaa4be632c4)

## project donation page at the bottom
link: https://giveth.io/onboarding/donors
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/f9535f23-c229-46c0-80db-a51ba13a9835)

# Checklist 

- [ ] navbar
- [ ] footer
- [ ] project details 
- [ ] project donation

**Comment by divine-comedian** [comment]
We should add links to our onboarding guide in the following places, I will explain the section and reference the exact links we need to use: 

Here's the figma for referece:
https://www.figma.com/file/vMiyVd1Ly5LjgSyZrChVV8/Giveth-users?type=design&node-id=2206%3A43398&mode=design&t=7MQM0shETRJXjcpH-1

## on the navbar -> Community tab
link: https://giveth.io/onboarding
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/d7f7727f-abe7-48d5-9b9e-2c5a7be405f5)

## Footer 
link: https://giveth.io/onboarding
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/eb3ea138-1855-480f-a49f-fb5559d41a8d)

## project details page -> donation details component
link: https://giveth.io/onboarding/donors
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/e8fd860c-a354-4893-acc0-8aaa4be632c4)


## project donation page at the bottom
link: https://giveth.io/onboarding/donors
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/f9535f23-c229-46c0-80db-a51ba13a9835)

# Checklist 

- [ ] navbar
- [ ] footer
- [ ] project details 
- [ ] project donation

**Comment by Tosinolawale** [comment]
And GIVeconomy https://giveth.io/onboarding/giveconomy  @divine-comedian 
![Giveconomy dropdown](https://github.com/Giveth/giveth-dapps-v2/assets/35389241/86f4b55e-f25b-4269-b1df-b769ad735efa)

**Comment by divine-comedian** [comment]
@jainkrati  - Do we want to pass this one to another developer?

**Comment by jainkrati** [comment]
@divine-comedian could you assign priority to this

**Comment by jainkrati** [comment]
@Meriem-BM pls take this up with guidance from @mohammadranjbarz

**Comment by maryjaf** [comment]
> ## on the navbar -> Community tab
> link: https://giveth.io/onboarding ![image](https://private-user-images.githubusercontent.com/67759413/303064640-d7f7727f-abe7-48d5-9b9e-2c5a7be405f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5NzgyNDksIm5iZiI6MTcxNDk3Nzk0OSwicGF0aCI6Ii82Nzc1OTQxMy8zMDMwNjQ2NDAtZDdmNzcyN2YtYWJlNy00OGQ1LTliOWUtMmM1YTdiZTQwNWY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDA2NDU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0ZjM4MjY4NzYzN2FhODdiZjdlOGExMmRlYzU1ODVmMmU0ZWE3MTkyNzgyMzhiOTZhZmRjZjMwNzlkNGFlNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mSdGdSgrcn_xZYJyUQfZeiESA-zKUmWnAmk4EOMZBJ4)
> 
> ## Footer
> link: https://giveth.io/onboarding

In "community tab" and "footer" by tapping on which section the onboarding page should be shown?

**Comment by maryjaf** [comment]
In footer by tapping on "Support us
[ with your Donation](https://staging.giveth.io/donate/giveth-2021:-retreat-to-the-future)" user should be redirected to /onboarding?
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/102f02c4-f621-463c-b13e-588a3d2f5668)

and on the navbar by tapping on "[Community](https://staging.giveth.io/join)" the user should be redirected to /onboarding?
If yes, they don't work correctly

**Comment by MoeNick** [comment]
Close as it's merged on prod
