### ISSUE TITLE
Small but important text edit on Create a project's Add an address modal

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#3470]
<img width="526" alt="Screenshot 2023-12-08 at 8 17 28 AM" src="https://github.com/Giveth/giveth-dapps-v2/assets/14945613/bdaae429-7c70-403a-a881-02a39cbd8592">

At first glance it sounds like both metamask and exchanges are bad..

Change:

Please DO NOT enter an exchange deposit address, use a key you control in a wallet like Metamask, or your funds maybe lost

To:

Please DO NOT enter an exchange deposit address, or your funds maybe lost! 
Use an account you control on this network. We recommend using Metamask.

**Comment by laurenluz** [comment]
this is a tiny copy fix, I think we can get in the pipeline soon @jainkrati @divine-comedian

**Comment by divine-comedian** [comment]
fixed on prod in https://github.com/Giveth/giveth-dapps-v2/commit/1680bb2e60d3a08a92d65e3c0a56b55bf91881d4
