### ISSUE TITLE
Add filter: AcceptFunds on Solana

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#3472]
As a user, I want to be able to filter projects that is raising fund on Solana. 

Note:
After the network is defined in backend, the backend endpoint for AcceptFunds will be ready for front end, no need to implement a new endpoint.

**Comment by jainkrati** [comment]
@CarlosQ96 do you have experience working on this filter?

**Comment by jainkrati** [comment]
@alireza-sharifpour for Frontend changes here

**Comment by alireza-sharifpour** [comment]
> @alireza-sharifpour for Frontend changes here

The frontend side is easy and fast to implement. @jainkrati 
@CarlosQ96 Please let me know when the backend is ready.

**Comment by alireza-sharifpour** [comment]
I should continue my work on this issue after backend merge.

**Comment by MoeNick** [comment]
Is teh backedn merge? @alireza-sharifpour is it done?

**Comment by MoeNick** [comment]
FYI @aminlatifi

**Comment by alireza-sharifpour** [comment]
This is Done. @MoeNick

**Comment by MoeNick** [comment]
@maryjaf FYI
