### ISSUE TITLE
Fetch Balance of 'Claimable' recurring donations 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3477]
From https://github.com/Giveth/giveth-dapps-v2/issues/3094

We need to fetch the balance of the super tokens for a given project's anchor address (allo protocol) (or recipient addresses for now). There will only be a limited amount of tokens we need to check for, those will be on Optimism: 

- ETHx `0x4ac8bd1bdae47beef2d1c6aa62229509b962aa0d`
- USDCx `0x8430f084b939208e2eded1584889c9a66b90562f`
- DAIx `0x7d342726b69c28d942ad8bfe6ac81b972349d524`
- OPx `0x1828bff08bd244f7990eddcd9b19cc654b33cdb4`
- GIVx `0x4cab5b9930210e2edc6a905b9c75d615872a1a7e`

We also need to show the dollar value for this token, as well as the combined dollar value for all balances

we should see if we can query the recipient address's balance of superTokens - this would be the claimable amount or the amount that is possible to downgrade 
https://console.superfluid.finance/subgraph?_network=optimism-mainnet

also we can query the balance using the superfluid sdk
https://docs.superfluid.finance/superfluid/developers/super-tokens/super-token-operations

We derive the price using the price of the underlying asset (e.g. the price of DAIx is equal to the price of DAI)

**Comment by alireza-sharifpour** [comment]
> @alireza-sharifpour
> 
> I'm second guessing myself now on this issue - Do we need back-end services for this or can we query the subgraph directly to get claimable balances?
> 
> This is related to when you need to find the super token balances held by a recipient of a recurring donation & then claim them

I currently get balances directly from SDK, didn't have any problem so far with it. @divine-comedian

**Comment by jainkrati** [comment]
Assigning to @alireza-sharifpour then.

**Comment by alireza-sharifpour** [comment]
This and #3441 are merged in the same PR.

**Comment by divine-comedian** [comment]
Great! @alireza-sharifpour - can you link the PR here?

**Comment by maryjaf** [comment]
Current stream balance is updated in token list modal and my active stream 
 
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/e2147c07-f863-448d-9081-c69ebf544e6d)
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/de4cb282-09d3-4270-a619-ef35dda2713a)

But  in claim modal it should be fixed 
<img width="644" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/15929a63-79d6-4d85-81bf-bb04cd449de2">

**Comment by divine-comedian** [comment]
@maryjaf  This is actually referring to the project owner when they are claiming their recurring donation, the project owner should go to `my project` and from a project that has received a recurring donation go to the actions menu and click claim recurring donations
You should see a modal with the amount of tokens to claim and its USD value, clicking claim should successfully claim those tokens to your recipient address for the project.


https://github.com/Giveth/giveth-dapps-v2/assets/67759413/222493ef-dc20-4a9b-acd5-33f095034744

@alireza-sharifpour - just on recording the flow for MJ I notice that after claiming the claimable balance isn't updated on the modal.

**Comment by divine-comedian** [comment]
@maryjaf  this issue the acceptance criteria is redundant to https://github.com/Giveth/giveth-dapps-v2/issues/3441#issuecomment-1991886435

Which you've already tested - we can move both of these to done when QA is approved.
