### ISSUE TITLE
Suggestion: Change the copy in the share to Twitter button

### ISSUE THREAD

**Issue by graymachine** [Giveth/giveth-dapps-v2#348]
It's weird that the button below the copy "Can't donate? Share this page instead." brings up a Tweet that says "I am a Giver and you can be one too! "

I would suggest something more like:

Support my/our/this (?)  project at @givethio. Let's Build the Future of Giving together! 🙌 🌈

**Comment by laurenluz** [comment]
+1 on this!! Comms approved. but this should not change the content for the tweet that appear after someone donates

**Comment by Vyvy-vi** [comment]
This issue can be closed.

This is the current tweet content:
"This project is raising funds in crypto on @Giveth! 💜
100% of every donation goes directly to the project to help them make an impact. Check it out 👇

{project-link} #giveth"
