### ISSUE TITLE
APR on Gnosis Chain GIVpower is 0%

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3487]
https://giveth.io/givfarm

<img width="604" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHRaQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1c77ef0aed6bdd16fa80cde8d316ab5144a35304/image.png" alt="image.png" />

I got the email about notify rewad on Optimism yesterday but not on Gnosis. there is some issue.

@aminlatifi @0xGabi 

cc @jainkrati @MoeNick

**Comment by aminlatifi** [comment]
The notify reward had issues as the manual gas price wasn't working anymore after more than two years!!!! I made it to be calculated automatically like other chains. The notify reward transaction has gone through
https://gnosisscan.io/tx/0xf940d44f01063dfb80cf0d2e2ebdaa5132a6d463c964e7308338c7c7b98733cc

**Comment by laurenluz** [comment]
looks like the subgraph caught up & the APR shows up ok now.
