### ISSUE TITLE
Fix Donation Logic for One-time donations 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3488]
We need to fix the logic for creating one-time donations. Currently there is different logic depending if the user selects to donate the max amount of a token in their wallet or if they put a fixed number into the input field. 

This video demonstrates the difference: 

https://github.com/Giveth/giveth-dapps-v2/assets/67759413/dc8fb611-e809-4fa2-b51b-9fbcf14d39b0

This makes a problem because it is possible for the user to unknowingly try to donate more tokens than they hold in their wallet. As a user when this occurs the easiest solution is to turn off the donation to Giveth, which we don't want! 

## What to do
We should fix the logic when a user inputs a fixed number to match the logic of when they choose to donate the max. For a reminder this is an example of how it should be: 
 
> user wants to donate 100 DAI
> 
> selects donate 5% to Giveth
> 
> Donation to project is adjusted to 95 DAI (95%)
> Donation to Giveth is 5 DAI (5%)
> 
> Total amount of funds user is donating equals 100 DAI

**Comment by jainkrati** [comment]
@RamRamez please take this up in the upcoming week. If needed get the guidance from @MohammadPCh .

**Comment by RamRamez** [comment]
@divine-comedian I think this was the flow that we talked about before. When I developed the donation page, I created a state for the max donation amount, that can be false or true. When user clicks on the "available: ...", max donation mode will be enabled, and total donation will be fixed to token balance, regardless of donation to Giveth percentage.
When user clicks on input box and enters an amount, max donation mode will be disabled and user is free to enter any amount regardless of their token balance. When 42 xDAI is entered in the input box and you change the Giveth donation amount, donation to project will be fixed to entered amount and total donation will be increased by increasing donation to Giveth.

**Comment by divine-comedian** [comment]
@RamRamez - got it - however after thinking a bit more it makes sense to have them just work with one logic - regardless if user enters the max amount or inputs an amount directly into the field.

Sorry if this makes for redundant work

**Comment by RamRamez** [comment]
@divine-comedian So, I should change donation to Giveth max percentage as well, since the total donation amount will be fixed to input amount.
I will set donation to Giveth max percentage to 90, is that ok?

**Comment by RamRamez** [comment]
@divine-comedian Is it acceptable to have only 6 decimal places for all tokens? it helps us simplify multiple unit conversions.

**Comment by divine-comedian** [comment]
@RamRamez 

Yes let's set it to 90% max 

6 decimal places max is good too.

**Comment by RamRamez** [comment]
@maryjaf FYI min donation amount will be 0.000001, users can't donate less than that (applies to both project and donation to giveth)

**Comment by maryjaf** [comment]
> @maryjaf FYI min donation amount will be 0.000001, users can't donate less than that (applies to both project and donation to giveth)

Is it ready to be tested on stg?

**Comment by RamRamez** [comment]
> > @maryjaf FYI min donation amount will be 0.000001, users can't donate less than that (applies to both project and donation to giveth)
> 
> Is it ready to be tested on stg?

No, it's still blocked by code review

**Comment by maryjaf** [comment]
@RamRamez please take a look
<img width="1520" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVRFQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3cfcae3d1496ee8367f936611aef508a1622a38f/image.png" alt="image.png" />

<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVhFQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--92150fd7f5c3d21bc1f43ee9367114fe62c115f2/image.png" alt="image.png" />

**Comment by maryjaf** [comment]
@RamRamez please take a look
<img width="1520" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVRFQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3cfcae3d1496ee8367f936611aef508a1622a38f/image.png" alt="image.png" />

<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVhFQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--92150fd7f5c3d21bc1f43ee9367114fe62c115f2/image.png" alt="image.png" />
