### ISSUE TITLE
Onboarding Pages Blocked By Search Engine

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-dapps-v2#3499]
I checked Google Search Console and I noticed that two of our pages are being blocked by the "robots.txt file" i.e they are not being indexed by Google. 

https://giveth.io/onboarding/projects
https://giveth.io/onboarding/donors

Can we look into this please and also make sure that no other normal public pages are not also being blocked from being indexed?
<img width="971" alt="Screenshot 2023-12-18 at 1 24 00 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/4855928/b3ddf918-4a81-4038-b676-57019f509ed8">

 
@divine-comedian @MoeNick 
Thanks!

**Comment by divine-comedian** [comment]
Got it, I think @MohammadPCh you're aware of this file and its purpose - can you take a look?

**Comment by MoeNick** [comment]
Let's put priority not to miss it, is it p1 or p2?

**Comment by MohammadPCh** [comment]
@ahmadabugosh @divine-comedian, This is our robots.txt:
```
User-agent: *
Disallow: /onboard
Disallow: /account
```
I believe this is the reason. I will leave a PR and let you know when you can check.

**Comment by MoeNick** [comment]
does it needs testing? @jainkrati 
@maryjaf
