### ISSUE TITLE
Add solana address to a project

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapps-v2#3503]
The backend for adding solana address to a project is ready. In the frontend we must implement that as well.

**Comment by aminlatifi** [comment]
@MoeNick Does it need specific design?

**Comment by MoeNick** [comment]
> @MoeNick Does it need specific design?

No, the designs are the same with before. For adding the Addresses on front end we have 2 views that should work:

- My projects, manage addresses, add address 
- Add / Edit project view. 

Why do you create a new issue for it? this is the [main issue. ](https://github.com/Giveth/giveth-dapps-v2/issues/3393)

**Comment by MoeNick** [comment]
@maryjaf FYI
