### ISSUE TITLE
Create GIVfarm Rewards Distribution on Staging 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3504]
We need another GIVfarm distribution so we can test out  GIVfarm compatibility for our features in development. 

Preferably Gnosis Chain but Optimism Goerli is fine too. We should have at least 6 months or more of rewards.

Please tag @maryjaf when this is ready so she can test out the blocked test cases for features

**Comment by aminlatifi** [comment]
I notified staging givfarm to pay rewards ... it will have positive APR for two weeks, then we must renew.
https://staging.giveth.io/givfarm
@maryjaf
