### ISSUE TITLE
P0 Ensure we can handle QF rounds of 300 projects!

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3507]
Polygon just got back to us that they will want 300 projects in the round... and the top 100 will get funding...

We need to make sure that our estimated matching & other backend things don't break!

@maryjaf @mohammadranjbarz - can you help with load testing? this round will start Jan 8, so we need to make sure we are good before then.

cc @jainkrati @MoeNick

**Comment by aminlatifi** [comment]
@laurenluz I haven't followed up this, anything special to do for it?

**Comment by laurenluz** [comment]
@aminlatifi I'm not 100% sure what need to be done from a development standpoint, I just created this issue to make sure we can handle those projects & associated users. I think we'll need load testing & to address other issue related to dapp performance.

We might have 100 users at a time, or 100+ donations in a day, for example. plus 300 projects in the QF round, I'm worried that estimated matchign may have issues 🤔 

I wish I knew how to more clearly define this.

**Comment by aminlatifi** [comment]
> @aminlatifi I'm not 100% sure what need to be done from a development standpoint, I just created this issue to make sure we can handle those projects & associated users. I think we'll need load testing & to address other issue related to dapp performance.
> 
> We might have 100 users at a time, or 100+ donations in a day, for example. plus 300 projects in the QF round, I'm worried that estimated matchign may have issues 🤔
> 
> I wish I knew how to more clearly define this.

What is the maximum number of projects in a QF round we have had till now? do you know?
Overall, from what we have seen so far the issues we have faced till now weren't related to performance, but reliability. I mean some misconfiguration has caused the issue, e.g. wrong rate limit between servers and bug in cors limitation.

**Comment by laurenluz** [comment]
We had 125 projects in the Optimism round we ran last fall.
