### ISSUE TITLE
Rejection transaction in safe account 

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3514]
There are 2 problem that should be investigated for next phase of multisig

- [ ] **1-When a singer rejects transaction, unsuccess modal isn't shown
for example in donation flow the user sees loading modal until clicks on close icon**
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/b7515fe7-35f3-4152-a902-b41552f49aed)

- [ ] **2- when a signer rejects donation, this donation is shown as pending donation in list of user's donation** 
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/c3b620ac-908f-43b0-9fb5-6cf475ba0af0)

cc: @divine-comedian @mateodaza @CarlosQ96

**Comment by MoeNick** [comment]
Can you pls put priorities to do it? is it something that sounds broken and p0? or it can be p1?

**Comment by divine-comedian** [comment]
> Can you pls put priorities to do it? is it something that sounds broken and p0? or it can be p1? @divine-comedian

It's sort of broken but also a very rare case
