### ISSUE TITLE
Bug in donation flow

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3516]
Sometimes I got an error in donation flow, it isn't permanenet 
<img width="1435" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/251959e2-6caa-4fd8-b7a3-fb46f390c64b">

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/b35ef01a-f177-4d0e-9ff9-42da68cc7051

cc: @mohammadranjbarz @MohammadPCh @CarlosQ96

**Comment by RamRamez** [comment]
https://support.metamask.io/hc/en-us/articles/360059289871-Error-Internal-JSON-RPC-error-when-trying-to-interact-with-other-networks

It seems the problem is with OP RPC URL, maybe it's outdated.
@maryjaf please update your MetaMask extension and then update OP node and try donating again.
