### ISSUE TITLE
Sign in BUGs - REALLY BAD users can't donate!!!

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3525]
This is the flow... Try to donate:

<img width="1099" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNldEQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4078c6d4436c3d6596c13dfcfd1d48bc31c1aa8a/image.png" alt="image.png" />

Have to sign in:
<img width="1083" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmFEQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6e6430b049bf3f1911b70f5628a4e26f13d3a090/image.png" alt="image.png" />

Sign message:
<img width="488" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmVEQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f25d58522a69219c8dbc7c5d3529f492235c1ce2/image.png" alt="image.png" />

End up back at donate button:
<img width="1056" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmlEQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--38d4dc187489babfafe7fb086a2398973f3f87e4/image.png" alt="image.png" />

The console:
<img width="532" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnFEQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c958d39ec7fea5a1005e9c0b876f9d551b6fea97/image.png" alt="image.png" />

**Comment by maryjaf** [comment]
maybe it's related to this behavior 
I'v completed my user profile long time ago but now I see that I should complete my profile

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/96836122-b430-48b8-ab53-37e6440a4d20


and by tapping on donate I should sign again although I had signed in, like the happening that we checked together at the start of the round @CarlosQ96 

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/2c0e58c1-586e-4ec3-956a-cd35ff22ab60

**Comment by geleeroyale** [comment]
I could replicate Laurens problem. The logs for notification-center and impact-graph do not give out any indication to what's the problem. Sentry and console report the application having a problem with the user being unauthorized.

<img width="913" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/317685/c770c925-eaf9-4b89-981a-9357d7d0d742">

<img width="577" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/317685/1e74d12e-2ec9-4f1d-9490-fcc1876857e1">

**Comment by geleeroyale** [comment]
I managed to free the service by restarting the reverse proxy used (NGINX) - I give a full breakdown in the devops repo (due to possible sensitive information in the logs) -> https://github.com/Giveth/devops/issues/180

**Comment by MoeNick** [comment]
@maryjaf can you take a look on production again?

**Comment by maryjaf** [comment]
I tested again on Friday, the problem was solved  and I couldn't reproduce it.
and I've checked today and there was no problem on donation flow for me

**Comment by MoeNick** [comment]
Great, thanks.

**Comment by laurenluz** [comment]
seems fixed for me too now
