### ISSUE TITLE
Add missing donations to the database

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3526]
The Dapp has some problems during our QF round and some donations (that went through) were not included in the UI. We need to add them!!

Some questions:
- Do we know the time period during which the dapp was down?
- What's the best way to collect all the donations that need to be added? Manually? or via Script? @aminlatifi @mohammadranjbarz 
- Once we flag the donations to be included, can we easily add them to the backend so that they show up in the round?

Looping in @divine-comedian & @missgene

**Comment by divine-comedian** [comment]
Related to #3520

**Comment by mohammadranjbarz** [comment]
@maryjaf 
Can you check the projects to see if all this donations are in our DB with correct data now?
And if they are correct check the item of that tx in this issue

You can see these donation details and projects here ( if you had any question to have to test it please ping me)
https://github.com/Giveth/impact-graph/blob/master/migration/1703398409668-add_missed_op_donations_to_db.ts

**Comment by laurenluz** [comment]
ok, so Carlos helped me get this list of the projects in the QF round & their optimism addresses:

https://docs.google.com/spreadsheets/d/1PsKU05ubHAV5sBz33GMeMTEfjQ10HSo5V3SnGKNyj4Q/edit#gid=0

@missgene - this is a really big task! let me know if you're down:
- look at each project address on Optimistic Etherscan: https://optimistic.etherscan.io/
- export the data for both "ETH" and "tokens" into csvs
![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/3baf9357-8661-458d-ab52-9d1f79c566fd)
- Set the date range from Dec 18 - Jan 3 (so spanning the entire Giving Season round + a buffer
![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/58e74a7b-9f89-4abb-b6d8-97eea81010b4)
- Copy & paste the data (from both csvs you download into the spreadsheet above, and add the project name as column A. I did this for Dream DAO as an example.

That's it!

From there we will pass these txs to the devs to do a dif & check which ones were not included in our data base & which were contracts etc... and then we can be sure we won't miss any donations.

I think it will make sense to do this work as soon as the Giving season round ends.

**Comment by laurenluz** [comment]
ok @missgene is going to compile the list of tx hashes starting tomorrow & then I will pass that list to backend guys.

I spoke with @CarlosQ96 about this, I think the backend guys will need to write some code to check if the from addresses have a user profile... and then we can include those in our database as donations in the round.

We may end up including more donations than actually went through giveth, but better to include them than miss them when calculating the matching funds for QF.

cc @jainkrati - this work is a blocker for us being able to compile donation data for QF and start fraud analysis, so it's pretty important. I would say a P1, though it's not as important as improving dapp performance before Polygon QF. Will need some support from developers who can process this data & find all the missing donations.

Also... good to recognize that the only reason we have all this extra crazy work now is because our dapp had so many failed donations during the round because we couldn't handle the load.

**Comment by CarlosQ96** [comment]
Ideally we would write a migration file with the donations that we know are not already in the db, as we can curate the list with a few simple queries. 
Then in the migration, create those donations, making them go through a few validations, like the user exists for example.

**_I'd say it can take 2 days of work_**. We have already done similar things, but we have now to query with ethers.js the donations. 

Could probably be a cronjob instead of a migration, so its more reusable for future issues.

**Comment by jainkrati** [comment]
@CarlosQ96 will you be able to complete this by jan 13

**Comment by CarlosQ96** [comment]
@jainkrati I don't have the list of donations yet, so it can be a small blocker there.

However for the implementation, i'll have it for tomorrow!!!

**Comment by laurenluz** [comment]
@missgene IS A HERO!

Check the "consolidated sheet" for all the tx hashes for all the transactions for the 85 projects' OP Mainnet addresses... from Dec 18 to Jan 3 are there.

So mr. @CarlosQ96 - can you help me to figure out which are donations and which should be included?
I think we do it like we discussed... check the transfers "in", check if the sender has a registered user profile in Giveth... and if not, exclude it... and if so! check if we already have that tx as a tracked donation in our db.. and if not... add it to the database.

We might end up saying some direct transfers were donations when they weren't but it's better than missing out on any real donations/votes for the Giving season round. Pretty sure the matching results will all be taken care of too once we check gitcoin passport scores for those addresses & do the final analysis w/ Trusta.

lmk if you have any questions!


https://docs.google.com/spreadsheets/d/1PsKU05ubHAV5sBz33GMeMTEfjQ10HSo5V3SnGKNyj4Q/edit#gid=0

**Comment by laurenluz** [comment]
I'm so happy this is DONE
