### ISSUE TITLE
Investigate Front End nonsense errors in normal mode

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapps-v2#3528]
Frontend in normal mode throws lots of errors and they eat up all sentry resources. The root cause of them should be found and addressed to have only meaningful errors in sentry dashboard and keep the user console clean.

**Comment by aminlatifi** [comment]
@MohammadPCh Please prioritize this as we will have larger user base in close future and we must be ready to keep the service available.

**Comment by MohammadPCh** [comment]
@aminlatifi Thanks, Sure. I will do.

**Comment by laurenluz** [comment]
@MohammadPCh I would put this high priority! I'm making a group now and trying to rally the team around prioritizing dapp performance the next 2 weeks. When the polygon round comes we will have a lot more traffic & if things break, it will really damage our repuration and future opportunities.

We need to rally the team around these performance issues.

**Comment by geleeroyale** [comment]
I want to add that sentry offers a really convenient *ask AI* button per error that can make fixing things faster
<img width="284" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/317685/70275cef-43c5-4d05-a09d-77ed1e3c34fd">

**Comment by geleeroyale** [comment]
the amount of errors here is insane. I just increased our plan a couple of days ago and again we are out of resources 😭 
should we drop staging from sentry @aminlatifi ? its responsible for most of the errors
<img width="590" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/317685/341301bd-ba20-4d12-bb85-feb441461176">

**Comment by aminlatifi** [comment]
> > the amount of errors here is insane. I just increased our plan a couple of days ago and again we are out of resources 😭 should we drop staging from sentry @aminlatifi ? its responsible for most of the errors <img alt="image" width="590" src="https://private-user-images.githubusercontent.com/317685/293020969-341301bd-ba20-4d12-bb85-feb441461176.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NzYxMDUsIm5iZiI6MTcwMzY3NTgwNSwicGF0aCI6Ii8zMTc2ODUvMjkzMDIwOTY5LTM0MTMwMWJkLWJhMjAtNGQxMi1iYjg1LWZlYjQ0MTQ2MTE3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyN1QxMTE2NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZTlkZTkxZTU0ZmYyZGI0ZjFhMWY2NTMwZGRlNjIyYjc1ODViZTJmNzQ5YmFhODJkODNlNDM0MDgwZjg5NTc2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jytwUzTtCTFwojwjjD_9dADol73dhbXFmEzxSNP9Gn0">
> 
> Okay, let's do it. I think we should stop monitoring on sentry since they are visible in the client's console and we can debug ourself without sentry help.

@geleeroyale You can do it? or it must be done by developers? I suppose there is something in the vercel setting to change an env variable for staging.

**Comment by aminlatifi** [comment]
@geleeroyale Should we disable sentry logging on local ENVs? devs usually have a copy of stating env on their machine to run programs locally with staging config.

**Comment by geleeroyale** [comment]
@aminlatifi I think no matter what we do - the only way to make this better is to look at production and squash the bugs. All other instances are negligible in terms of sentry usage:

<img width="965" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/317685/60644d5a-1c27-4788-91b9-b1a603e80597">

**Comment by geleeroyale** [comment]
Re - @aminlatifi mentioned reducing what we send to Sentry:

https://docs.sentry.io/product/accounts/quotas/manage-transaction-quota/
