### ISSUE TITLE
Change copy on failed donation modal

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3539]
related to Giveth/impact-graph#1233 

The copy was changed and now it is worse!! We shouldn't tell people to "retry" because they have already donated... we just failed to record it.

Copy change suggestion:

"Our dApp is experiencing a lot of traffic right now and we were not able to record your donation.

Don't worry! If the transaction was successful and funds were sent, we will be adding your donation to the UI soon.

View transaction ↗️ "

cc @MoeNick @jainkrati @divine-comedian

**Comment by divine-comedian** [comment]
We should tell them that they should contact support - not that we will automatically find it and save it

**Comment by laurenluz** [comment]
we are going to need to manually add them all anyway. we can't expect everyone to report every donation. re: https://github.com/Giveth/giveth-dapps-v2/issues/3526

**Comment by MohammadPCh** [comment]
@laurenluz This is the result:
<img width="514" alt="Screenshot 2023-12-28 at 6 11 13 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/17097576/c1f1b084-3891-4402-8b8e-55e92e19fe2c">
Is it good?

**Comment by laurenluz** [comment]
Maybe we should simplify it:

We were not able to record your donation.

Please check if the transaction was successful and report this to our support team.

Link: Contact support
Small: View on block explorer
