### ISSUE TITLE
Add new categories to Giveth for Polygon QF round - on prod by Jan 7

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3540]
Polygon wants to have these specific categories for projects in their round.
- Impact
- DeFi
- NFT
- DAO
- Socials
- Tools
- Community
- Creator
- Gaming
- B2B

Is it possible to add these categories to the dapp? We'd need it in:
- Create a project
- Category filters on projects pages

Thoughts? @mosaeedi @MoeNick @MohammadPCh @MohammadPCh 

This would need to be live by January 2 if we want it available for projects onboarding to the Polygon round.

**Comment by MohammadPCh** [comment]
@laurenluz Yes, it's possible, we get the categories from the backend.

**Comment by CarlosQ96** [comment]
We can add them manually from admin bro, but I found some bugs when adding sub categories, making a PR to correct this bugs then maryjaf can test and Ramin can do the changes.

**Comment by CarlosQ96** [comment]
Staging backend has all categories and main category of polygon. Let me know if you need anything else @RamRamez

**Comment by RamRamez** [comment]
The values for all subcategories are "test". @CarlosQ96 Please change it to follow other categories structure.
![image](https://github.com/Giveth/giveth-dapps-v2/assets/73441857/4ebb5f47-2e7a-414d-91d9-fe19ff5a3a86)
![image](https://github.com/Giveth/giveth-dapps-v2/assets/73441857/53919f48-d9b7-47e2-b3d2-c904aa722562)

**Comment by maryjaf** [comment]
Thanks @RamRamez I've checked new categories and all scenarios have been passed
only one question
should this new category be shown in this page as a popular category during the round? @laurenluz 
<img width="1382" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/52ec09b5-15ad-4807-8848-1494519353af">
