### ISSUE TITLE
Add tunable QF to estimated matching

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3541]
Polygon wants to give us a list of address of projects... and say that every donation to these projects counts a 2x its size.

There will be 100 projects with this 2x thing, and 200 other projects without it, in the round.

Polygon want to know if it's possible for us to add this "tunable QF" to the estimated matching calculation... and if it's possible to do it before the round starts on January 15.

@CarlosQ96 @aminlatifi @mohammadranjbarz - can you help to provide an estimation on this?

It's my cut feeling that we won't be able to do it. This is nowhere near as important as the improving dapp performance stuff, it's more a nice-to-have.

cc @MoeNick @jainkrati

**Comment by mohammadranjbarz** [comment]
I think we shoul change schema of qfRound and projects, and maybe donations as well, so we have to add some logic to handle it correctly, and changing materialized view and writing lots of test cases to make sure it works, so I think it would take at least 5-6 working days from backend

**Comment by aminlatifi** [comment]
Is the copy of this https://github.com/Giveth/giveth-dapps-v2/issues/3687

**Comment by laurenluz** [comment]
well it's kind of a copy. the other issue is more of a discussion of HOW to calculate the FINAL matching... this issue was about adding the tunable portion to the estimate matching to use during the round... which at this moment is not important.
