### ISSUE TITLE
Projects with the same name  and address

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3547]
If user tap on publish very fast for twice, two projects be added in users' project list
it should be handled from backend to prevent adding 2 project with same name and address

**Comment by jainkrati** [comment]
This should be handled in FE to disable the button after 1st click and also keep track of active API calls for saving project. Can you take this up @MohammadPCh

**Comment by MohammadPCh** [comment]
@maryjaf to test and close

**Comment by maryjaf** [comment]
Thanks @MohammadPCh this problem has been resolved on STG
