### ISSUE TITLE
Create backup service to save failed donations

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3549]
@mohammadranjbarz & @MohammadPCh discussed a solution to our ongoing problem in Giveth/impact-graph#1233 :

"to have a separate simple serve for backup, that if the donation failed save it there, then backend can check it."

If we can have a better way of tracking failed donations it will be great! because we're going to have to do a lot of work to check for the ones that failed in the giving season round.

**Comment by aminlatifi** [comment]
Yeah, we can start. 
I am thinking about using prism integration with vercel, it allow us to move fast.

**Comment by MohammadPCh** [comment]
I left a PR for the front-end side, we have to add these env variables for `production' and `staging`:
```
MONGO_DONATION_URL
MONGO_DONATION_API_KEY
MONGO_DONATION_COLLECTION
MONGO_DONATION_DATA_SOURCE
MONGO_DONATION_DATABASE
```
@mohammadranjbarz 
can someone mention moshehab here? I couldn't find him.

**Comment by mhmdksh** [comment]
> I left a PR for the front-end side, we have to add these env variables for `production' and `staging`:
> 
> ```
> MONGO_DONATION_URL
> MONGO_DONATION_API_KEY
> MONGO_DONATION_COLLECTION
> MONGO_DONATION_DATA_SOURCE
> MONGO_DONATION_DATABASE
> ```
> 
> @mohammadranjbarz can someone mention moshehab here? I couldn't find him.

Hey I'm here. @mohammadranjbarz @CarlosQ96 Can easily do that to reflect changes in the our Secret management platform over at https://vault.giveth.io

**Comment by mhmdksh** [comment]
@laurenluz Thanks for opening this issue. I think it's better to identify this as a backend issue as well.

One other aspect of this can also be a donation queuing service that queues failed donations until the backend system catches them again. (@aminlatifi @mohammadranjbarz @MoeNick @CarlosQ96 do we have something like this in our backend? It might be a good idea

**Comment by MoeNick** [comment]
Yeah I have the same experience with RabbitMQ  for a trading platform

**Comment by mohammadranjbarz** [comment]
@mhmdksh 
You should create two database in https://www.mongodb.com one for staging, one for production , and create API keys then give them to @MohammadPCh  to put it in the vercel config ( frontend will use MongoDB data API directly so impact-graph wont need these configs) 
Now frontend test it with the db of my personal account, but it's better to have DBs on giveth account

**Comment by MoeNick** [comment]
This is the preview
https://giveth-dapps-v2-git-release-2211-givethio.vercel.app/

**Comment by mhmdksh** [comment]
> @mhmdksh You should create two database in https://www.mongodb.com one for staging, one for production , and create API keys then give them to @MohammadPCh to put it in the vercel config ( frontend will use MongoDB data API directly so impact-graph wont need these configs) Now frontend test it with the db of my personal account, but it's better to have DBs on giveth account.
> 
> We wanted something independent of our servers and our applications, so we used Mongodb.com API

Thanks @mohammadranjbarz I've opened this issue in devops for that: https://github.com/Giveth/devops/issues/189

Will update you once it's ready

**Comment by geleeroyale** [comment]
Endpoints have been created and distributed to @MohammadPCh

**Comment by aminlatifi** [comment]
@MohammadPCh Can you manage the rest?

**Comment by mhmdksh** [comment]
@mohammadranjbarz I think the endpoint that you were testing is a deployed function on AWS. with an api access key.

What we created is a bit different. I think we'll need to deploy something on the new endpoints so that they are usable.

Do you have any idea about this?? Can you provide more information on what should be deployed on the new MongoDB Instances so that they are usable as endpoints?

FYI @aminlatifi @MohammadPCh @MoeNick

**Comment by aminlatifi** [comment]
> @mohammadranjbarz I think the endpoint that you were testing is a deployed function on AWS. with an api access key.
> 
> What we created is a bit different. I think we'll need to deploy something on the new endpoints so that they are usable.
> 
> Do you have any idea about this?? Can you provide more information on what should be deployed on the new MongoDB Instances so that they are usable as endpoints?
> 
> FYI @aminlatifi @MohammadPCh @MoeNick

@mhmdksh As you found [the answer](https://github.com/Giveth/giveth-dapps-v2/issues/3549#issuecomment-1873767979), we must create mongo API on top of the db. 
Just have we created different DBs and consequently APIs for staging and production?

**Comment by mhmdksh** [comment]
> > @mohammadranjbarz I think the endpoint that you were testing is a deployed function on AWS. with an api access key.
> > What we created is a bit different. I think we'll need to deploy something on the new endpoints so that they are usable.
> > Do you have any idea about this?? Can you provide more information on what should be deployed on the new MongoDB Instances so that they are usable as endpoints?
> > FYI @aminlatifi @MohammadPCh @MoeNick
> 
> @mhmdksh As you found [the answer](https://github.com/Giveth/giveth-dapps-v2/issues/3549#issuecomment-1873767979), we must create mongo API on top of the db. Just have we created different DBs and consequently APIs for staging and production?

Thanks @aminlatifi in fact we did not. I'll create one and share for the same

**Comment by mhmdksh** [comment]
@MohammadPCh I've shared the full details of the API and endpoint staging deployment with you, let me know if it works for you. And update me please

**Comment by mhmdksh** [comment]
@Rolazo Can you please follow up on this issue, we need the same environments that our devs are using for testing.

The servers are already created, we need to double check the API connections (I created one for staging)
And we need to make sure that the DB has the correct collections (Schema + Data)

You can find credentials in vault

**Comment by Rolazo** [comment]
@MohammadPCh I shared with you the credentials via DM, if you need anything, please let me know

**Comment by MohammadPCh** [comment]
I configured them, and both are working great.
Thanks @mhmdksh @Rolazo

**Comment by aminlatifi** [comment]
Let's push this to production

**Comment by mhmdksh** [comment]
@MohammadPCh @mohammadranjbarz Hey, can anyone share the backup service business flow?? Is it automatically submitting the donations after some time? Or are they only being save to be manually submitted later??

CC: @MoeNick @jainkrati

**Comment by MohammadPCh** [comment]
@mhmdksh This is the flow:
1. after the donation tx is created and goes to the pending state in the network, we send its information to the backend to save it.
2. if there is any problem with saving donation to backend w send it to donation-backup-service automatically. this is our code snippet:
```ts
try {
				const id = await saveDonation({ ...donationData });
				setDonationId(id);
				setDonationSaved(true);
				return id;
			} catch (e: any) {
				await postRequest('/api/donation-backup', true, {
					chainId: transaction?.chainId!,
					txHash: transaction?.hash,
					amount: amount,
					token,
					projectId,
					anonymous,
					nonce: transaction?.nonce,
					chainvineReferred,
					walletAddress: transaction?.from,
					symbol: token.symbol,
					error: e.message,
				});
				setFailedModalType(EDonationFailedType.NOT_SAVED);
			}
```

**Comment by mhmdksh** [comment]
Thanks @MohammadPCh
