### ISSUE TITLE
Hide gitcoin passport related components for Solana users

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapps-v2#3553]
When the user is connected his solana wallet and not EVM one, all solana related components must be hidden.

https://github.com/Giveth/giveth-dapps-v2/issues/3400#issuecomment-1868891784

**Comment by MoeNick** [comment]
Im My Account Gitcoin Passport Section please change the copy of "Go to Passport" with:

To activate your Gitcoin Passport please Switch to an Ethereum wallet.

Please link the "Switch to an Ethereum Wallet" to switch wallet splash page

**Comment by MoeNick** [comment]
Please have it on the banner of /qf route. @alireza-sharifpour

**Comment by maryjaf** [comment]
This problem has been resolved on #3399
