### ISSUE TITLE
buttons too close to bottom of project card

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#356]
on the projects/home page the two buttons, `learn more` and `donate` look too close to the bottom of the project card. Maybe add some padding? 

![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/ddd55d3b-c8e3-48be-b303-fbd25e6e1ff0)

While testing the responsiveness I notice the buttons start to look funny from screen widths of 1024px and wider.

**Comment by laurenluz** [comment]
looks good

![image](https://user-images.githubusercontent.com/75490971/161128582-6d9e9f7c-845e-4006-936b-113c8dad247a.png)
