### ISSUE TITLE
Update Banner for Polygon QF round - on prod by Jan 7

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3561]
@rodricastillo9013 can you help design a new banner for the Polygon PoS Round?

I'm asking them for design elements and colors, hopefully they get back to me in the next days, because we should get this live on the dapp before Jan 8.

Let's be sure to use the new standards we were outlining in the other issue that now I can't seem to find!

cc @MohammadPCh @jainkrati

**Comment by laurenluz** [comment]
I found this for polygon brand guides: https://polygon.technology/brandguidelines
And this for the polygon village: https://polygon.technology/village?utm_campaign=%5BCampaign%5D%20Polygon%20Village%20Reloaded&utm_medium=email&_hsmi=79831412&utm_content=79831412&utm_source=hs_email

Since this is the "Buidl on Polygon" Village grants round... "aiming to reward creators, builders and projects that contribute to the growth and well-being of the Polygon ecosystem"

I think we can more or less just copy their themes in there an make something simple. We could make it dark/black w/ this kind of image, and some Polygon logos in there. A bit of Giveth elements mixed in if we can.

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/f0828231-ffbe-409d-8a17-04a5bf4a58c5)

**Comment by jainkrati** [comment]
@laurenluz is the design done for this? Once done please assign it to @MohammadPCh

**Comment by laurenluz** [comment]
@MohammadPCh this is ready to go. You can find the [figma link here](https://www.figma.com/file/LKBHpnxI9sLjde7DzOQIYQ/Giveth-Marketing?type=design&node-id=4695-37022&mode=design&t=7kWwOnfujqMKzgmQ-0)

It should look like this in the end, but ofc, some of the the text comes from admin bro:
![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/3748074b-2bf2-49a0-88d5-719fab337f54)

Here are the elements:
![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/9fd3e1db-8c21-4d12-9c6a-1a6cfe161f85)

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/93e03b80-24b5-4e32-b46b-9e58f50b44db)

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/87b5b829-bc4d-4474-aada-229c2a817ecf)


And here is the background on its own:

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/2a53b811-0d92-4b5a-a58d-36201cdb5188)

**Comment by laurenluz** [comment]
oh no, wait. We need to modify the background... I need help from @rodricastillo9013 ... sent him a DM.

**Comment by rodricastillo9013** [comment]
team sorry for the delay! I'm sorry! here it goes new background. 
<img width="840" alt="Polygon Round - FINAL" src="https://github.com/Giveth/giveth-dapps-v2/assets/61791380/77119962-6a27-4ef4-abd5-be74abbe87ad">

**Comment by laurenluz** [comment]
@MohammadPCh I'm seeing some issues for this:
1. the responsive version & mobile version for the banner look really weird/bad. I think we need to make the layered images adjust in size, or not overlap somehow... do you need design for it? or can you do some magic?
2. also the background looks quite pixelated/low quality! how can we fix that?

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/d46946be-0d6d-4cad-a241-a2ee5e803b49)
![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/03c33e5b-f88d-4b47-a253-b71e6b96b5cc)

**Comment by MohammadPCh** [comment]
@laurenluz Thanks for your feedback.
You know, I saw that, and because we didn't do anything for it in our older versions, I left it.
I just use the images that @rodricastillo9013 posted here.
we can use more detailed images.
also, for the background case, we can use SVG version, and use CSS color for the background gradient. wdyt @rodricastillo9013 ?

**Comment by rodricastillo9013** [comment]
Hello team, I have made the changes, and adjusted to tablet and mobile, do you need some exact size? @laurenluz @MohammadPCh 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/61791380/363cb888-7886-49ec-87bc-1e1a5014a623)

![image](https://github.com/Giveth/giveth-dapps-v2/assets/61791380/bc9c6cbc-52bf-43c1-a1fc-79a2a4324f85)

https://www.figma.com/file/LKBHpnxI9sLjde7DzOQIYQ/Giveth-Marketing?type=design&node-id=4775%3A36241&mode=design&t=prSxZdR27pSVL7PH-1

**Comment by rodricastillo9013** [comment]
> @laurenluz Thanks for your feedback. You know, I saw that, and because we didn't do anything for it in our older versions, I left it. do we want to remove some items in specific sizes? I just use the images that @rodricastillo9013 posted here. we can use more detailed images. also, for the background case, we can use SVG version, and use CSS color for the background gradient. wdyt @rodricastillo9013 ?

hello! @MohammadPCh @laurenluz 
 Yes, exactly.

For the background it would be ideal to work as SVG, it will always maintain the best quality.

Regarding the images, they are the highest quality that I have found from polygon, we do not have better quality versions, the ideal is to reduce them and adjust them in size as in the examples that I recently attached.

**Comment by MohammadPCh** [comment]
@rodricastillo9013 Hello :)
can you send me the background without the gradient?

**Comment by rodricastillo9013** [comment]
![Background](https://github.com/Giveth/giveth-dapps-v2/assets/61791380/e22576d9-506e-4371-9521-a7371734024f)

@MohammadPCh like this?  or without the polygon logos too?

**Comment by rodricastillo9013** [comment]
aha! ok perfect! check now and let me know @MohammadPCh 
![Background Transparent](https://github.com/Giveth/giveth-dapps-v2/assets/61791380/7ee63d3c-6dc8-4728-8def-0649453628a3)
