### ISSUE TITLE
Get donation data ready to send to Trustalabs 

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3562]
We need to get the data on the "all donations" tab basically.. but for the Giving Season round :) after we add all the missing donations to the database as per #3526

Spreadsheet from Optimism Round, for reference: https://docs.google.com/spreadsheets/d/1svOVH3vJ5OyJ6iMft8GA9HGiFoy0BSuD5xo9BznAne0/edit#gid=1320367901

**Comment by laurenluz** [comment]
cc @jainkrati

**Comment by jainkrati** [comment]
@CarlosQ96 pls confirm by when can we finish this

**Comment by CarlosQ96** [comment]
**Doing this required just a 2-3 hours MAX**, to double check the data. 

@mohammadranjbarz  and me, We automated a big part of it during the stay in turkey @jainkrati So it's a button to generated all the relevant info, and double check it's all right. 

First I have to get https://github.com/Giveth/giveth-dapps-v2/issues/3526 done.

**Comment by laurenluz** [comment]
data was sent and FYI, I'm tracking all our QF round spreadsheets in this notion: https://www.notion.so/giveth/Giveth-QF-Round-Spreadsheets-b10e1d0d639d498bb522fcab1bfc3360
