### ISSUE TITLE
Change copy on mid-page banner for Polygon round - on prod by Jan 7

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3565]
Should say:

Quadratic Funding on Polygon
The Buidl on Polygon Round aims to reward creators, builders and projects that contribute to the growth and well-being of the Polygon ecosystem. Donate to participating projects on Polygon PoS and get your donations matched with the power of quadratic funding.

<img width="1366" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXlXQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--193ba41e571e0a43833abae97277e8f1a8768c49/image.png" alt="image.png" />

cc @jainkrati

**Comment by laurenluz** [comment]
maybe @RamRamez can pick this up too? so that we can have it on production along with #3540 by Jan 7?

it's a 👶 issue

**Comment by jainkrati** [comment]
@RamRamez pls pick this

**Comment by RamRamez** [comment]
@mohammadranjbarz @MohammadPCh Please review PR #3569 ASAP. We need it on production by Jan 7.
