### ISSUE TITLE
P1 - Update estimated matching cap for Polygon QF round - on production by Jan 13

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3568]
@MohammadPCh @mohammadranjbarz @CarlosQ96 @RamRamez we need to update the estimated matching cap on the dapp again for the Polygon round!

They want a max of 10k Matic per project... and they want to have a matching pool of 250k matic...

so it will be 4%

We need this live before the round starts, so by Jan 13!

cc @jainkrati

**Comment by jainkrati** [comment]
@MohammadPCh is this done? Today is the last date.
