### ISSUE TITLE
‌‌Receiving "You don’t have enough funds!" error by tapping on "available" GIV token

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3571]
**Describe the bug**
When I tap on "available" to set all of my GIV token in amount box for donation 
I got an error "You don’t have enough funds!"
this bug doesn't happen for example xdai token in this scenario 

**To Reproduce**
1. Go to 'one project' page
2. Click on 'Donate'
3. tap on 'available'
4. tap on "donate"
5. see error 

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/ba5da7e3-7caf-4b8b-80bf-0802b0079d5f

**Comment by MoeNick** [comment]
@maryjaf can you pls confirm it's still happening?
