### ISSUE TITLE
Investigation: Bug in showing multisig account in dApp in some scenarios 

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3577]
**Describe the bug**
Sometimes instead of multisig account, account of signer(creator) is shown in dApp

![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/39ba777a-7e17-48e0-a53b-3887a78c8a09)

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/fafc142d-44e3-4017-a2c9-2fb1976a4a72

**Comment by MoeNick** [comment]
Same for this one:
Can you pls put priorities to do it? is it something that sounds broken and p0? or it can be p1?
@divine-comedian

**Comment by jainkrati** [comment]
This is a p0. @mateodaza could you take a investigate.
