### ISSUE TITLE
Set a new error modal for multisig account in Donation-->Switch network scenario 

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3578]
Imagine below scenario:

-My user is a multisig user and network is set on Gnosis
-User select a project to donate
-But this project doesn't support Gnosis 

Now in this scenario a modal is shown that user change network for example to polygon but multisig account couldn't be able to switch network

It would be great if we can consider an new error modal and copy for this scenario 

cc: @divine-comedian

**Comment by Tosinolawale** [comment]
![Normal wallets](https://github.com/Giveth/giveth-dapps-v2/assets/35389241/36158b43-7683-419a-842a-325a419aac2b)
This? @maryjaf @divine-comedian

**Comment by divine-comedian** [comment]
Hey @Tosinolawale - I need to fix some copy and the CTA - can you send me the figma link?

**Comment by divine-comedian** [comment]
@mateodaza - I made some assumptions - mostly that from the donate page we are able to know 2 things: 

1. the currently connected network (according to the multisig) 
2. Which chains the project accepts donations on. 

Then we put those conditionally into the text of the modal. Is this okay? 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/4b232a5d-70ce-4961-8436-478df500292e)
https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=5158%3A28961&mode=design&t=t7MpSILMTRXWXBQp-1

**Comment by mateodaza** [comment]
current design goes like this for EOA wallets

![image](https://github.com/Giveth/giveth-dapps-v2/assets/18689480/6ab17128-a6c8-44a6-abd4-a4f1040d8164)

To keep the same style, kept something like this

![image](https://github.com/Giveth/giveth-dapps-v2/assets/18689480/0bdffc48-a44d-44ea-8ffb-609172bcac59)

**Comment by divine-comedian** [comment]
@maryjaf - Keep an eye on this, when this is approved and merged to prod we can make the feature release announcement on Giveth comms. 

Just keep me in the loop, as always :D

**Comment by maryjaf** [comment]
Is this ready to be tested on stg? @mateodaza

**Comment by divine-comedian** [comment]
> Is this ready to be tested on stg? @mateodaza

Looks like the PR was merged into staging - please test MJ!

**Comment by divine-comedian** [comment]
Great! Moved this to done.

**Comment by MoeNick** [comment]
Just a confirmation if it's merged into staging, let's close this one.

**Comment by divine-comedian** [comment]
> Just a confirmation if it's merged into staging, let's close this one.

You can see in the comments above that its already on staging - closing this one
