### ISSUE TITLE
P2 - Change copy on Polygon Category & banner

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3579]
I didn't consider this before, but we should change the copy of the polygon category... because anyone can say they are in this category... but not ANYONE is in the polygon round.
![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/070d7293-aa52-4796-9d3f-cbee8bcb353d)

Category link: https://giveth.io/projects/polygon-qf-round

Should be:

Main category title: Building on Polygon
Text: SUPPORT PROJECTS CONTRIBUTING TO THE POLYGON ECOSYSTEM
slug: polygon

@RamRamez @CarlosQ96 - is this front or backend?

cc @jainkrati

**Comment by jainkrati** [comment]
@RamRamez this seems like a small change but important; pls take it up

**Comment by RamRamez** [comment]
@jainkrati It's already on production.

**Comment by laurenluz** [comment]
![Uploading image.png…]()
