### ISSUE TITLE
Verification application inaccessible to some users

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#3582]
There have been two people who have experienced this issue and reported it so far.

They are unable to complete the verification form when they are connected to https://giveth.io/es.
I don't know what the language has to do with it? Is it because the form cannot be translated or something?
I have only noticed it with Spanish language so far.

You can see the comments in the support channel here
https://discord.com/channels/679428761438912522/773912257368817684/1193978088321720362

And here:
https://discord.com/channels/679428761438912522/835168432520429578/1184177091613298779

@Cotabe was one of the people experiencing the bug... maybe he can help to troubleshoot.

**Comment by laurenluz** [comment]
cc @divine-comedian @jainkrati

**Comment by divine-comedian** [comment]
@maryjaf  - Can you try testing this one to see if it can be reproduced 

### Steps: 
1. Clear cache and cookies for Giveth.io production
2. Switch language to spanish (bottom of the website in the right corner)
3. Make a new project
4. apply for verification
5. See error ???

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/873079ae-3305-46d5-8811-65d82df67080)

**Comment by maryjaf** [comment]
I've followed above steps and by tapping on verify button,  in the page of first step nothing shows

<img width="1359" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/5b40c115-6f58-40ca-9732-4fb900c8d32c">

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/92a64cfc-e9a2-484d-922e-285f5e1e718e

**Comment by divine-comedian** [comment]
Thanks MJ! @jainkrati  - who can take a look at this bug regarding the verification form in Spanish? I know @RamRamez has worked on this feature quite a bit.

**Comment by jainkrati** [comment]
@RamRamez pls take it up

**Comment by RamRamez** [comment]
The reason is that the error response that backend returns for each supporting language is different. I talked with @mohammadranjbarz and we decided to send a common error response for this endpoint "getCurrentProjectVerificationForm" for all languages. That will solve this issue.

**Comment by mohammadranjbarz** [comment]
> The reason is that the error response that backend returns for each supporting language is different. I talked with @mohammadranjbarz and we decided to send a common error response for this endpoint "getCurrentProjectVerificationForm" for all languages. That will solve this issue.

@maryjaf  @RamRamez  The backend side is deployed on **Production**

**Comment by RamRamez** [comment]
Thanks @mohammadranjbarz. I checked and problem is solved on production. can you merge it on staging too?

**Comment by mohammadranjbarz** [comment]
> Thanks @mohammadranjbarz. I checked and problem is solved on production. can you merge it on staging too?

Done

**Comment by divine-comedian** [comment]
Thanks guys! 

@maryjaf - Can you take this up and test it again to confirm its been resolved

**Comment by maryjaf** [comment]
Thanks, 
This problem has been resolved, verification flow works correctly on spanish version.
