### ISSUE TITLE
P1 / Revamping sentry log collecting

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapps-v2#3584]
We must be sure error logs produced by frontend are collected in the corresponding project in the Sentry.

Sentry queries are blocked sometimes by Brave Browser. We must investigate whether it's possible to solve that.
![image](https://github.com/Giveth/giveth-dapps-v2/assets/5684607/32072ef7-5571-489b-a81e-30672bf943e2)

Besides, if the source map is needed to be deployed, we must do that.

**Comment by mhmdksh** [comment]
<img width="1257" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/52987806/107f6241-b2a3-4f16-b637-57dcd6811e6c">
Some of these can also be unhandled frontend errors. As seen in the screenshot. Especially ones with a lot of occurences

**Comment by mhmdksh** [comment]
Mentioning @MohammadPCh @RamRamez here for further Support.

As we were discussing this issue is also meant to be a work to improve logging, to what we actually need as info for the frontend. In a way it doesn't reach our Sentry limits

**Comment by MohammadPCh** [comment]
@mhmdksh, thanks. I suggest stopping the automatic sending of all errors to Sentry and configuring it to send only the logs that we handle manually.

**Comment by MohammadPCh** [comment]
I will try to push a hotfix asap.

**Comment by mhmdksh** [comment]
Thanks @MohammadPCh

**Comment by MohammadPCh** [comment]
Regarding Sentry, as per the [documentation](https://docs.sentry.io/platforms/javascript/configuration/filtering/), we've implemented log filtering using the beforeSend hook. A hotfix has been pushed to filter older client logs, extending to edge and server logs as well. We hope this resolves the issue, ensuring we only receive urgent errors moving forward.

Furthermore, I recommend maintaining a clean Sentry configuration for two reasons:

1. This ensures that our production environment is the only user of the Sentry configuration, eliminating any potential misuse of keys on local machines.
2. We can avoid concerns about the limits imposed on the current Sentry configuration.

@mhmdksh @aminlatifi
