### ISSUE TITLE
P2 PFP | remove console.log from production builds

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-dapps-v2#3585]
While testing, I found that there is **a lot** of info being written to console. We should consider adding some mechanism to remove `console.log`from our production builds - among other things, to make them more performant.

Here is some inspiration, we can also test a github action to remove it, but that would be more dangerous I think.

https://dev.to/drsimplegraffiti/remove-consolelog-from-production-mode-4d8i

**Comment by jainkrati** [comment]
@lovelgeorge99 please work on this with guidance from @RamRamez

**Comment by lovelgeorge99** [comment]
@geleeroyale that solution will remove all console logs from production.is that what you want?

**Comment by geleeroyale** [comment]
if you ask me - yes 😇

**Comment by kkatusic** [comment]
@geleeroyale, @jainkrati my opinio is that you left console.logs that are inside try()catch() methods, maybe rename that console.log to console.error just to catch some errors if something goes wrong ;)

**Comment by RamRamez** [comment]
> @geleeroyale, @jainkrati my opinio is that you left console.logs that are inside try()catch() methods, maybe rename that console.log to console.error just to catch some errors if something goes wrong ;)

@kkatusic good idea, I think we would better keep crucial logs for debugging

**Comment by geleeroyale** [comment]
I want to add that my only role here is that I posted an article, because I had a hunch that using too many will lower performance. However - let me be clear again here. I am talking about the production frontend client side. Ideally these would be stripped out as part of CI as per the recommendation

**Comment by kkatusic** [comment]
> I want to add that my only role here is that I posted an article, because I had a hunch that using too many will lower performance. However - let me be clear again here. I am talking about the production frontend client side. Ideally these would be stripped out as part of CI as per the recommendation

I agree with you remove unnecessary console logs, but when is some fetching or checking transaction or signature keep console errors ;)

**Comment by geleeroyale** [comment]
> I agree with you remove unnecessary console logs, but when is some fetching or checking transaction or signature keep console errors ;)

it is for sure important to be very diligent here. Please follow your own judgement - I did not dive very deep into this topic and our actual use cases.

**Comment by lovelgeorge99** [comment]
Ok , i have changed the console.log() inside try{}catch{} to console.error() and removed console.log() to show up  if it is in production.

**Comment by RamRamez** [comment]
@lovelgeorge99 please add a comment in your PR and mention this issue so I can find it.
Also please connect your PR to this issue in Zenhub.

**Comment by divine-comedian** [comment]
@lovelgeorge99 - what is the latest on this issue? Did you follow up on ramin's comments?

**Comment by divine-comedian** [comment]
@lovelgeorge99 what is the update for this issue?

**Comment by lovelgeorge99** [comment]
It has been solved and the PR is merged to develop

> @lovelgeorge99 what is the update for this issue?
