### ISSUE TITLE
Failure modal in successful donations

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapps-v2#3591]
It's reported by some users (@maryjaf and [here](https://github.com/Giveth/impact-graph/issues/1218#issuecomment-1874940549)) that they see failure modal at the end of donation, while their donations have been successfully saved to backend.

There is a little chance it has happened due to changes applied by this [PR](https://github.com/Giveth/giveth-dapps-v2/pull/3542)

**Comment by aminlatifi** [comment]
@MoeNick

**Comment by RamRamez** [comment]
@aminlatifi @maryjaf Is this issue only happened once?

**Comment by maryjaf** [comment]
Today I have been working on donation flow on stg and prod and I haven't seen this again in my test

**Comment by RamRamez** [comment]
Thanks @maryjaf, I will test different scenarios and will update you here

**Comment by jainkrati** [comment]
@MoeNick could pls weigh in from product approach on what Ramin commented above.

**Comment by MoeNick** [comment]
Sure will get back on this

**Comment by MoeNick** [comment]
We had a meeting with @RamRamez he will test it again for any other questions.

**Comment by RamRamez** [comment]
@MoeNick I tested today and it was working as expected. I think we can close this issue.

**Comment by MoeNick** [comment]
Thanks @RamRamez
