### ISSUE TITLE
GIVpower Ranking is not updating

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#3595]
The round ended about 6 hours ago and the GIV power ranking did not update.

Unfortunately, I don't have screenshots of before and after round ending. 
But I do know of a few projects that I had personally changed boosting percentage to that did not reflect the change at all at the end of the round.

ALSO... the instant GIVpower adjustment is also not working. You can see that [project #4 ](https://giveth.io/project/pcrf-palestine-childrens-relief-fund?tab=givpower) on the list has more GIVpower than [project #3](https://giveth.io/project/giveth-house?tab=givpower) and yet it still sits in 4th place.

The projects don't even show the current rank

![image](https://github.com/Giveth/giveth-dapps-v2/assets/74267818/c97e2fda-062f-47da-97fc-dad395cc4361)

@laurenluz @aminlatifi @jainkrati @mohammadranjbarz

**Comment by laurenluz** [comment]
@mohammadranjbarz can you please investigate?

**Comment by aminlatifi** [comment]
Can be related to https://github.com/Giveth/impact-graph/issues/1229

**Comment by aminlatifi** [comment]
impact-graph had not filled power balances at snapshots, probably due to connectivity issue between impact-graph and balance-aggregator. Devops team are working on it.

**Comment by aminlatifi** [comment]
@laurenluz @WhyldWanderer It must be fixed now
