### ISSUE TITLE
Showing switch network modal when user try to sign in

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3596]
**Describe the bug**
Switch network modal is shown by tapping on connect wallet /sign in on production env

**To Reproduce**
1. network is set on Gnosis in metamask
2. Click on 'connect wallet'
3. see the wrong modal

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/3fd1820a-67dd-4d48-be7e-e32109ee8673

cc: @alireza-sharifpour @MohammadPCh

**Comment by MoeNick** [comment]
@jainkrati FYI to add assignee and review the status.

**Comment by jainkrati** [comment]
@alireza-sharifpour could you debug and confirm if this is still happening. If yes, please confirm if you can complete this in 2 days?

**Comment by alireza-sharifpour** [comment]
I haven't encountered this issue neither on staging nor on production, do you still have this issue @maryjaf?

**Comment by maryjaf** [comment]
I just checked again but the above scenario doesn't happen to me, it can be closed for now and if this happens again we could repon this issue
