### ISSUE TITLE
Some times The user profile isn't shown correctly 

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3597]
**Describe the bug**
My user had been complete profile before, but sometimes by tapping on sign in and completing "sign in" flow this message is shown in my account that my profile isn't complete 
and by refreshing this problem will be resolved 

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/76b16b90-5091-4cb1-8106-98ce47a2507a

<img width="1437" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/a48cc670-1060-430e-add7-5b7e46bbbe5a">

cc: @CarlosQ96  @mohammadranjbarz @MohammadPCh @MoeNick @jainkrati

**Comment by maryjaf** [comment]
<img width="902" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/1bfe58b3-959b-4fe5-b49d-a599a55fd8f3">
Error rate of this request

**Comment by MoeNick** [comment]
This is also not resolved, I put p1 as it's not happening all the time, but would discover the route cause. 
FYI @jainkrati

**Comment by jainkrati** [comment]
@alireza-sharifpour could you spend 1-2 hours fixing this.
