### ISSUE TITLE
Page view scrolls to bottom when liking a project.

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3600]
Sometime but not always, when I like a project on the all projects page the app needs to load for a few seconds and then it will shift my page view down to the bottom of the page instead of preserving my current  view location of the page. 

https://github.com/Giveth/giveth-dapps-v2/assets/67759413/849f6a94-7f6f-4a65-a62a-d641cee491fd

**Comment by MohammadPCh** [comment]
@divine-comedian can we close this, since we don't have like anymore?
