### ISSUE TITLE
Projects page does not load projects past the first ~15 cards

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3601]
Sometimes the projects page does not load all of the projects, only the first 3-4 rows. No errors are emitted in the console. there is no loading screen or indication that the app is loading more projects. Only way to fix is by refreshing the page 

Originally reported by @GriffGreen  and I was only able to reproduce during stress testing party

https://github.com/Giveth/giveth-dapps-v2/assets/67759413/473316c5-d0cc-4cc9-8d4a-347e63b8725f

**Comment by jainkrati** [comment]
@RamRamez pls take a look

**Comment by maryjaf** [comment]
please take a look @RamRamez , I saw it on stg  but not on production
https://github.com/Giveth/giveth-dapps-v2/assets/111529185/fdd3b60f-d6bb-4854-8061-06e5a2a617da

**Comment by jainkrati** [comment]
@RamRamez pls guide @lovelgeorge99 to take this up

**Comment by RamRamez** [comment]
@lovelgeorge99 I tried multiple times but couldn't reproduce this problem. Mitch, Griff and Maryjaf had this problem.
If you need further information, we can prepare a short call with @maryjaf to try reproduce and debug it.

**Comment by divine-comedian** [comment]
@RamRamez @lovelgeorge99 - we could only repro this when the dapp was under heavy stress FYI

**Comment by divine-comedian** [comment]
I'm going to close this one since we haven't been able to reproduce it since we optimized the dapp performance
