### ISSUE TITLE
Investigate integration with apollo client retry

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapps-v2#3606]
The user queries may fail due to unstable network conditions. We have already implemented a manual retry on saving donations, but there would be more robust solutions.

It's an option that is worth looking at
https://www.apollographql.com/docs/react/api/link/apollo-link-retry/

**Comment by aminlatifi** [comment]
@jainkrati What's your idea?

**Comment by aminlatifi** [comment]
@RamRamez

**Comment by aminlatifi** [comment]
I made this https://github.com/Giveth/giveth-dapps-v2/pull/3613

**Comment by jainkrati** [comment]
Good call @aminlatifi for this.
