### ISSUE TITLE
Solana donations are not calling "updateDonation"

### ISSUE THREAD

**Issue by RamRamez** [Giveth/giveth-dapps-v2#3611]
Solana donations are not showed up on donations table right away because front-end are not calling "updateDonation" service after tx is mined.
![image](https://github.com/Giveth/giveth-dapps-v2/assets/73441857/c3611239-88e8-42b6-9469-efec8c9f9c21)

It's related to PR #3536
cc @aminlatifi @jainkrati

**Comment by aminlatifi** [comment]
@alireza-sharifpour Please take a look

**Comment by alireza-sharifpour** [comment]
This issue should be fixed, can you take a look @maryjaf .
The problem was after Solana donation, we did not call updateDonation (The endpoint for saving donation immediately on the backend) so it took time for you donation to be shown in the project donation list.
Now it should be fixed.
