### ISSUE TITLE
Add new GIVbacks Eligible Tokens on prod

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3615]
These are some larget market cap tokens we should consider adding to the dapp, we will need to check getting the prices on the front-end as well as the back-end.
- [x] STETH mainnet
- [x] RETH mainnet
- [x] RETH optimism
- [x] GNO Gnosis
- [x] GIV on Solana (but no GIVbacks since Solana) https://solscan.io/token/3Xi3EhKjnKAk2KTChzybUSWcLW6eAgTHyotHH1U6sJE1
- [x] OUSD mainnet https://www.coingecko.com/en/coins/origin-dollar
- [x] OETH mainnet https://www.coingecko.com/en/coins/origin-ether
- [x] OGN mainnet https://www.coingecko.com/en/coins/origin-protocol

**Comment by alireza-sharifpour** [comment]
These tokens need to be added to the backend and then we need Icons for the Frontend.
@divine-comedian 
CC: @jainkrati @MoeNick

**Comment by divine-comedian** [comment]
> These tokens need to be added to the backend and then we need Icons for the Frontend. @divine-comedian CC: @jainkrati @MoeNick

I added the icons to the front-end already I think - Do we also need to figure out price fetching for them on the FE?

**Comment by alireza-sharifpour** [comment]
Based on our latest changes in fetching prices, if we have their coingeckoId in our DB, there will be no problem in prices.
@divine-comedian

**Comment by laurenluz** [comment]
Also, we had a request from a user to add the following tokens, and Griff checked them to make sure they could be GIVbacks eligible - can we include them in this effort?

✅  OUSD: https://www.coingecko.com/en/coins/origin-dollar

✅  OETH: https://www.coingecko.com/en/coins/origin-ether

✅   OGN:https://www.coingecko.com/en/coins/origin-protocol

**Comment by GriffGreen** [comment]
Also Please add USDGLO!!

https://github.com/Giveth/impact-graph/issues/1367#issuecomment-2058917751

**Comment by WhyldWanderer** [comment]
This issue was created nearly 6 months ago.
The users are still asking for these tokens to be added: https://discord.com/channels/679428761438912522/1242128875975082024/1242129391862153226

What is the status here? @jainkrati 
Am I now able to add these tokens in AdminBro? or are there still bugs?
If I cannot add them, is there a developer that can take this on??

**Comment by divine-comedian** [comment]
@WhyldWanderer - I just did it myself from the adminBro and it worked like a charm! OGN and OETH should now show up, I'll follow up in the support ticket with the user. 

Make sure you add the coingecko id when you add a token, or else we won't be able to get its price. The id can be found directly in the URL on the coin page for the specific token 
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/94235ffd-cdfb-438f-b4f9-4c9a749e62d5)


adding the token image needs to be done separately by a FE dev for every new token you add, but not if its for an existing token that you are adding to a new network.

**Comment by MoeNick** [comment]
@divine-comedian There's a bad bug here, without any error the coingecko ID won't save 
Look here in adminJs for OGN
![image](https://github.com/Giveth/giveth-dapps-v2/assets/80677512/d0f619b7-a390-4806-97a9-8b163f2f8e8b)

**Comment by MoeNick** [comment]
@divine-comedian after any add token you have to edit the token and add the coingeckiID again.
I hope it will be loved by this issue as I brought it up in Base https://github.com/Giveth/impact-graph/issues/1564

**Comment by divine-comedian** [comment]
> @divine-comedian after any add token you have to edit the token and add the coingeckoID again. I hope it will be solved by this issue as I brought it up in Base [Giveth/impact-graph#1564](https://github.com/Giveth/impact-graph/issues/1564)

Nice catch! I went back and added the coingecko-ids


The user has confirmed the tokens have been added, I think we can close this one.
