### ISSUE TITLE
Decimal Handling in Recurring Donation Slider

### ISSUE THREAD

**Issue by MohammadPCh** [Giveth/giveth-dapps-v2#3617]
Problem:
The recurring donation slider is encountering issues with decimal handling. Editing a recurring donation occasionally results in an inaccurate percentage display.

Details:
Decimal number handling needs improvement to ensure the correct representation of percentages when users edit recurring donations using the slider.

Steps to Reproduce:

1. Navigate to the recurring donation section.
2. Attempt to edit a recurring donation with a decimal number.
3. Observe the displayed percentage for any inaccuracies.

Expected Behavior:
The recurring donation slider should accurately handle decimal values, providing a precise percentage representation during edits.

**Comment by divine-comedian** [comment]
@MohammadPCh  is this issue still relevant?

**Comment by MohammadPCh** [comment]
We can close it.
