### ISSUE TITLE
P1 | Use Sentry in a more selective way

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-dapps-v2#3626]
Currently we log everything to Sentry. We should be more selective as we exceed our quotas pretty quickly.

<img width="913" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/317685/d9292ee9-84aa-4dad-92d6-8f0e5dc16e17">

@jainkrati

**Comment by jainkrati** [comment]
@CarlosQ96 please pick this once all p0s assigned to you are done. This task is needed to reduce the monthly spend on sentry as it is charged based on logging volume.

**Comment by geleeroyale** [comment]
please be advised that sentry captures errors and performance metrics across the board - frontend and backend

**Comment by jainkrati** [comment]
@CarlosQ96 list the logs you are removing. Pls share a PR and review from @aminlatifi @MohammadPCh

**Comment by aminlatifi** [comment]
@jainkrati the diagram Kay has pasted here belongs to dapp (FE).

**Comment by divine-comedian** [comment]
@geleeroyale @CarlosQ96  is this issue still relevant?

**Comment by geleeroyale** [comment]
we should still be better at using Sentry when troubleshooting bugs, performance - not sure we need an issue for it
