### ISSUE TITLE
Low Priority - Why do we take money from the donation to donate to Giveth?

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#3629]
I wanted to donate 2 USDT to this project, but by donating to Giveth, I am taking from the project and giving to giveth.

<img width="487" alt="Screenshot 2024-01-15 at 9 15 29 AM" src="https://github.com/Giveth/giveth-dapps-v2/assets/14945613/9a9dc1bb-1568-4e30-b231-ab64c4bc221d">

I think it should be the other way around, where the project gets exactly what i wanted to give them and then i am giving EXTRA to Giveth.

I can understand that if the user doesnt have enough tokens, then we need to do this... like If i only have 2USDT, then sure, this way makes sense... but if i have enough tokens, this is the worng flow... it feels like Giveth is stealing donations from projects!

**Comment by divine-comedian** [comment]
This is actually something I worked on in #3488 to make it work explicitly that we take the % donated to Giveth from the total amount, please refer to the context in that issue.

**Comment by divine-comedian** [comment]
> I strongly agree with Griff above. We should not be stealing from donations - but we are, according to this text which mentions that this fee will be added **on-top**
> 
> <img alt="image" width="456" src="https://private-user-images.githubusercontent.com/317685/296822217-c1980049-a3d2-4fb7-a8ce-6bcc5961d1de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNDA5NTEsIm5iZiI6MTcwNTM0MDY1MSwicGF0aCI6Ii8zMTc2ODUvMjk2ODIyMjE3LWMxOTgwMDQ5LWEzZDItNGZiNy1hOGNlLTZiY2M1OTYxZDFkZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNVQxNzQ0MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMWM3YzdiMjM2YzI1NDNmNWUzMWM5NjYyZTNkZmNkNmQ5ZmM3OGI4YzZhYjMzYTc5NDIyZmU2Y2EwNjU2MWVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gcR3dIRge5I8kPEDF6SHv7iwMOEtH3Hr3UM3oblR3yU">
> Edit: Most simple fix is to change the text to: ". percentage part of my donation will be given to Giveth's own donation project ..."

We're not stealing donations - that is a huge exaggeration, that kind of hyperbole isn't useful to this conversation. 

The text does need to be fixed however.

**Comment by geleeroyale** [comment]
Sorry for my *language* - I totally get your explanation! We should change the wording of the tooltip to reflect the real situation!

**Comment by GriffGreen** [comment]
> This is actually something I worked on in https://github.com/Giveth/giveth-dapps-v2/issues/3488 to make it work explicitly that we take the % donated to Giveth from the total amount, please refer to the context in that issue.

> It creates some weird issues that a user could try to donate more tokens that they hold, we definitely don't want to make friction if people want to donate to Giveth!

Great find! And great context! I agree with the fix in that context, I don't agree with it for every situation. 

If the user is saying that they want to donate 100 dai to a project, and then they will give 5% to us, we have a choice... either we choose to have the user donate:

A. 105 DAI, 100 to the project and 5 to us.

or 

B. 100 DAI, 95 to the project and 5 to us. 


I think it is obvious that we want A, donating 105 DAI is better than 100 DAI 

If A isn't possible, B is fine.... BUT ONLY if A isn't possible! It shouldn't be the default behavior.
