### ISSUE TITLE
P0 If a project is added to the QF round partway through the round, we should include any donations during the QF round period as part of "in round" donations

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3636]
somehow, this project was marked as "in the round" but wasn't! https://giveth.io/project/marketland-web3-infrastructure-for-creators?tab=donations

I donated to it today before it was "added to the round" and then added it after.

this is happening in some cases where we "miss" adding the project in admin bro to the QF round, but they should have been in the round all along.

It's not fair that projects should be punished for our mistakes, so somehow, we should, in the backend, mark any donations to these projects during the QF round period as donations "in the round"... if they are added to the round a few days late.

@CarlosQ96 @mohammadranjbarz what can we do here?

cc @jainkrati @MoeNick

**Comment by mohammadranjbarz** [comment]
> somehow, this project was marked as "in the round" but wasn't! https://giveth.io/project/marketland-web3-infrastructure-for-creators?tab=donations
> 
> I donated to it today before it was "added to the round" and then added it after.
> 
> this is happening in some cases where we "miss" adding the project in admin bro to the QF round, but they should have been in the round all along.
> 
> It's not fair that projects should be punished for our mistakes, so somehow, we should, in the backend, mark any donations to these projects during the QF round period as donations "in the round"... if they are added to the round a few days late.
> 
> @CarlosQ96 @mohammadranjbarz what can we do here?
> 
> cc @jainkrati @MoeNick

I think we can add a button in the admin panel when the admin clicks on that we execute a query that adds the current active qfRound id to all donations to qfRound's projects that are between beginDate and endDate of qfRound, WDYT about this?

**Comment by MoeNick** [comment]
How frequent it will be? @laurenluz

**Comment by laurenluz** [comment]
> I think we can add a button in the admin panel when the admin clicks on that we execute a query that adds the current active qfRound id to all donations to qfRound's projects that are between beginDate and endDate of qfRound, WDYT about this?

Sound perfect @mohammadranjbarz! What's your estimation for how long this would take to implement? If we don't have time before the round ends, is there a way we can do it manually via query?

> How frequent it will be? @laurenluz

I hope it doesn't happen to often, but already for this round there are a handful of projects (like maybe as many as 5 or 10) who were added after the round started and might have had donations before.

This, though, as you know is a very big round and usually they are much smaller.

**Comment by mohammadranjbarz** [comment]
@laurenluz 
I tested this query on staging (I deleted the relation of all donations of active qf round  by deleting their qfroundId and after that executed this query and it got filled again

```
UPDATE donation
SET "qfRoundId" = qr.id
FROM project_qf_rounds_qf_round pqr
JOIN qf_round qr ON pqr."qfRoundId" = qr.id
WHERE donation."qfRoundId" IS NULL
  AND donation."createdAt" BETWEEN qr."beginDate" AND qr."endDate"
  AND donation."status" = 'verified'
  AND donation."transactionNetworkId" = ANY(qr."eligibleNetworks")
  AND qr."isActive" = true
  AND donation."projectId" = pqr."projectId";

```
So we can execute this query manually in production DB to do the job and we can add a button in adminjs panel to trigger this query.

I would appreciate if some of you review my query before executing on production db, because this query changes records of table and we should not make a mistake
@aminlatifi  @jainkrati  @CarlosQ96

**Comment by CarlosQ96** [comment]
Thanks Mohammad the query looks good to me.

**Comment by laurenluz** [comment]
When can we merge this fix?

There are projects complaining about it because they had donations but it shows that their amount raised in qf is zero.

This will fix it :)

**Comment by mohammadranjbarz** [comment]
> When can we merge this fix?
> 
> There are projects complaining about it because they had donations but it shows that their amount raised in qf is zero.
> 
> This will fix it :)

@laurenluz I executed the queries on the production DB, can you check it to see if the data is ok now or not?

**Comment by MoeNick** [comment]
@mohammadranjbarz if you also made a change on AdminJS, pls let us know to test that as well. 
Thanks

**Comment by laurenluz** [comment]
hey @mohammadranjbarz - it seems like there is still an issue... see this project: https://giveth.io/project/coeto-empower-community-economy?tab=donations

it has donations on Polygon during the round dates that don't show up in the "Buidl on Polygon" donation tab filter

**Comment by mohammadranjbarz** [comment]
> hey @mohammadranjbarz - it seems like there is still an issue... see this project: https://giveth.io/project/coeto-empower-community-economy?tab=donations
> 
> it has donations on Polygon during the round dates that don't show up in the "Buidl on Polygon" donation tab filter

@laurenluz  Are you sure?
I couldn't find any donations with condition that you said. ( There 
<img width="810" alt="Screenshot 1402-11-03 at 9 45 44 in the morning" src="https://github.com/Giveth/giveth-dapps-v2/assets/9850545/bca0c529-105a-4022-8f17-d5b7e12c27be">
are just 3 donations on Polygon and we show them in **Buidl on Polygon** donation tab filter)

<img width="814" alt="Screenshot 1402-11-03 at 9 45 37 in the morning" src="https://github.com/Giveth/giveth-dapps-v2/assets/9850545/c2545e17-05fb-4ea7-8cfb-4106b42de8df">

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz if you also made a change on AdminJS, pls let us know to test that as well. Thanks

Not yet, if it has priority tell us to do it, it would take 2-3 hours to implement in adminJs

**Comment by laurenluz** [comment]
oh! it was my mistake! I was looking at donations on Ethereum assuming they should be included, but they should not.

I will check some other projects and report if I see any issues... but I think it's so far so good!

one more quetsion... can these things be done in reverse? like if I added a project by accident... and their donations were important to the round... can I later remove the project from the round and have those donations get removed from the round?

**Comment by mohammadranjbarz** [comment]
> oh! it was my mistake! I was looking at donations on Ethereum assuming they should be included, but they should not.
> 
> I will check some other projects and report if I see any issues... but I think it's so far so good!
> 
> one more quetsion... can these things be done in reverse? like if I added a project by accident... and their donations were important to the round... can I later remove the project from the round and have those donations get removed from the round?

Yes it's possible, if this case happened please tell us we will create and execute query that time

**Comment by laurenluz** [comment]
@mohammadranjbarz ok sounds good...

so we can consider this issue finished then?
