### ISSUE TITLE
Huge lag in recording donations on the "donations" tab for projects

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3637]
I made donations this morning that appeared in "My donations" tab: https://giveth.io/user/0xc46c67bb7e84490d7ebdd0b8ecdaca68cf3823f4?tab=donations

but didn't show in the project's Donations tab until hours later: https://giveth.io/project/nifty-limos?tab=donations

it's there now, but it was at least an hour until it appeared which is a crazy lag imo 👀 

@jainkrati @divine-comedian

**Comment by divine-comedian** [comment]
What could be the reason of the potential lag? @jainkrati @aminlatifi ?

**Comment by aminlatifi** [comment]
First, we cannot say for sure and must look at the logs. 
Probably, it took a long time to verify the donation! if that's it, there is a chance polygonscan ,the service we use to verify ERC20 transfers, was lagging.

**Comment by divine-comedian** [comment]
@aminlatifi okay - who is checking the logs then to find out why this is happening

**Comment by aminlatifi** [comment]
> @aminlatifi okay - who is checking the logs then to find out why this is happening.
> 
> Is this a devOps task?

I am looking to it.

**Comment by aminlatifi** [comment]
When any issue happens in the donation verification process (e.g. a third-party service like rpc node, etherscan, ... fails), the donation is reinserted for verification multiple times! I see many donations have undergone verification multiple times! 
I update the donation insert queue to not add a donation if it's still in the queue.

**Comment by laurenluz** [comment]
that's great! I still had this lag experience yesterday - when was this merged/when will it be merged?

**Comment by aminlatifi** [comment]
> that's great! I still had this lag experience yesterday - when was this merged/when will it be merged?

The change exactly applied to production with this action step https://github.com/Giveth/impact-graph/actions/runs/7628349365/job/20779874938

**Comment by aminlatifi** [comment]
To be precise Tue, 23 Jan 2024 16:09:55 GMT

**Comment by divine-comedian** [comment]
Great! @aminlatifi - Any ideas on how we can test this?

**Comment by maryjaf** [comment]
I did donation on stg and prod and I could see these transaction in donation table without delay 
It seem this problem has been resolved

**Comment by laurenluz** [comment]
I think the only way to test for real is when the dapp is under load 👀 
but I agree we can call it done, and see if it comes up again during another QF round
