### ISSUE TITLE
RegenFarms Launch - Guide ShapeShift on txs to execute

### ISSUE THREAD

**Issue by willyogo** [Giveth/giveth-dapps-v2#364]
What txs will ShapeShift need to execute in order to launch the RegenFarm and RegenStream?

This is the multisig that will be executing the txs: https://xdai.gnosis-safe.io/app/#/safes/0x25A6343E69CE6cd7a2c34536595341Cb6b038c5F/balances

**Comment by aminlatifi** [comment]
@willyogo  I have prepared a hackmd guide for issue giveth/giveconomy#516. It will be reviewed and finally merged to docs. 
I guess that would be a sufficient guide for RegenFarms launch too.

**Comment by aminlatifi** [comment]
https://github.com/Giveth/GIVeconomy/issues/516#issuecomment-1079907017
