### ISSUE TITLE
Sign in loading is not working on Solana

### ISSUE THREAD

**Issue by alireza-sharifpour** [Giveth/giveth-dapps-v2#3647]
WE should add loading while signing in with Solana to Signin modal as we have it with EVM wallets.

**Comment by Leilani432** [comment]
Hello @alireza-sharifpour i will suggest you contact Solana support like i did  a couple of days ago and got support after i opened a ticket. So i will suggest you do the same so you can talk to a [Solana Live Support](https://helpassistance.live/solana) on their general chain link for definite answers.
You can use the  ticket ID DR3486 as well for a faster response.

**Comment by alireza-sharifpour** [comment]
For testing.
The issue was with EVM sign in when the user clicks on sign in button in sign in modal, we have a loading indicator on the button.
We didn't have it on Solana but I added it.
It's ready for test. @maryjaf
