### ISSUE TITLE
By tapping on Notification icon, nothing happens on prod

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3652]
If user is signed in, by tapping on Notification icon nothing happens like as below video

-User is signed out
-Tap on "my account"
-Complete sign flow
-Tap on "notification icon"
-see error

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/04bb6202-891d-45d5-88c6-71d0727ac2c9

**Comment by maryjaf** [comment]
Since this bug is on production it should be better if be checked soon,
Please for adhoc or hotfix issues, the test state be considered in the flow

**Comment by aminlatifi** [comment]
@mateodaza @RamRamez Is it related to this PR updates
https://github.com/Giveth/giveth-dapps-v2/pull/3634/files

**Comment by maryjaf** [comment]
one more thing, notification setting was removed in last changes 
<img width="1318" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/b25436f9-8a77-4204-a9d5-9eb6931af77e">

**Comment by maryjaf** [comment]
Thanks @RamRamez I'v tested on https://giveth-dapps-v2-git-fix-clicking-on-notifs-icon-givethio.vercel.app/  and this issue has been fixed
