### ISSUE TITLE
Donations missed by back-up

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#3659]
I am finding donations that aren't included in the back-up system or in the db... I will add the hashes here in this issue as I find them

- [ ] 0x2fb50d861f27b4a8899dec42adfca448eceff8b941bd8aaf11481eda9f98bfc9

**Comment by laurenluz** [comment]
related to https://github.com/Giveth/impact-graph/issues/1264

@divine-comedian @jainkrati @mohammadranjbarz - we should make sure that any txs that ashley includes here are accounted for.

**Comment by WhyldWanderer** [comment]
- [ ] 0xd078d093bfd6c911b2ef4dbbc714003411793fa057a366d027d351385f06be3d

**Comment by divine-comedian** [comment]
- [ ] https://polygonscan.com/tx/0xb7a0d1b4cef5f9fd984912cfd57b376d6c1891c503ffaa4730afd4ec3ca8638a
- [ ] https://polygonscan.com/tx/0xf59e7885a6b86b1df50d8ff0b9160d7c4742acffde0f7fc20b2d5a8ed0f6d994
- [ ] https://polygonscan.com/tx/0x28d584ff2ab9070a8ba534266c97b5cdc5eb22962dc062cedbbd72ce31d61598
- [ ] https://polygonscan.com/tx/0xbcd06adc69ca4ded2a0a4d8d9c1f49fd6ed70faa844b7102adbac70063c36c9a
- [ ] https://polygonscan.com/tx/0xeb8ef74127a5ba4c20884715bb7fc7eb033196c92dd3f897b6e428f0125d7cd0

**Comment by aminlatifi** [comment]
> For solving failed donations, lets add arbitrary data to our transactions and then read it in subsquid as well as backup service @CarlosQ96 @aminlatifi @mohammadranjbarz @mateodaza . Ref: https://info.etherscan.com/understanding-transaction-input-data/. Exxample: web3.eth.sendTransaction({ 'nonce': nonce, 'to': address_of_contract, 'value': web3.toWei(1, 'ether'), 'gas': 2000000, 'data' : '', 'gasPrice': web3.toWei('10', 'wei'), })

It's a good idea for native token donations (native token transfers), but for ERC20 token transfers we would not be able to use it. We can include arbitrary data within the same data field. However, the smart contract must be designed to recognize and appropriately handle this arbitrary data. If the contract's function is not expecting extra data, it might ignore it or the transaction could fail, depending on how the contract is coded.

**Comment by CarlosQ96** [comment]
All the donations on this issue were added and I ran the process to add all of the missing ones from subsquid. Further more, Mohammad Curated them and deleted some we added by mistake. 
I consider this issue done in terms of the task at hand.

**Comment by MoeNick** [comment]
Ok great Im moving it to done, any ideas on how can we QA?

**Comment by maryjaf** [comment]
We can close this because this mentioned tx hash([ZNS Connect](https://mainnet.serve.giveth.io/admin/resources/Project/records/3034/show)) and some more missing  tx hash are shown in donation table of project  correctly
