### ISSUE TITLE
Safari/Mobile - Donation token list not updating when switching network

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3660]
**Describe the bug**
While a user in on Safari browser (mobile) and connected with Metamask, on the donation view for a project, trying to switch networks (from OPtimism -> Polygon) the toast notif saying to switch network does not update nor does the token list - it shows the previous networks tokens (optimism in this case)

https://github.com/Giveth/giveth-dapps-v2/assets/67759413/320279d0-7343-454f-a7b2-204774b91d84

**To Reproduce**
1. Sign-in with Metamask on Safari Mobile
2. Go to Donation modal of a project in a chain specific QF round that is NOT the chain you are currently connected with
3. click switch network
4. switch network on metamask
5. check token list
6. check toast notif for switching network to eligible QF matching chain

**Expected behavior**
When a user switches network the token list should also update in the drop down menu on the donation page

Also, if the user is already connected or has switched network to the chain that matches the chain specified by the qf round to be eligible to be matched then the toast notification should not show up anymore.

**Screenshots**

**Desktop (please complete the following information):**
 

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: Apple
 - Browser: Safari 

---

@maryjaf - Can you try testing this to reproduce it first?

**Comment by MoeNick** [comment]
Can we call it done?

**Comment by MoeNick** [comment]
I put p1 as it passed on MJ device

**Comment by jainkrati** [comment]
I am assuming this is done. Moving to QA for maryjaf to test.

**Comment by maryjaf** [comment]
I had tested this on my iPhone(12) and it was ok for me
