### ISSUE TITLE
Make it possible for admin to edit matching pool % in admin bro - by Feb 10

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3664]
Every round, frontned & backend need to do work to edit matching pool %. It would be ideal if we could just edit this in admin bro directly.

cc @jainkrati

FYI - this will save us time/dev resources in the future, but it's not a critical issue. I guess it is P2, but not sure exactly how to label it... depends on the prioritization of our epics.

**Comment by maryjaf** [comment]
By changing "Maximum Reward" in admin bro, the cap of estimated matching isn't changed
must some front changes be applied for this?
@CarlosQ96

**Comment by CarlosQ96** [comment]
@maryjaf yess, the backend changes are minimal but the frontend should fetch the cap from the qfround. 
@MoeNick @jainkrati someone in the frontend can take it.

**Comment by maryjaf** [comment]
Is there any separate front issue for this? or a front developer should be assigned to this issue?

**Comment by jainkrati** [comment]
@CarlosQ96 @mateodaza for working together on this. I hope this is not more than 1 hour of FE and 1 hour of BE Work.

**Comment by mateodaza** [comment]
> @CarlosQ96 @mateodaza for working together on this. I hope this is not more than 1 hour of FE and 1 hour of BE Work.

sure yes, I'll sync w @CarlosQ96

**Comment by laurenluz** [comment]
is this finished? we need to update the matching cap for the meta pool round.

**Comment by maryjaf** [comment]
I've tested on stg and now both backend and front side are ok on stg
