### ISSUE TITLE
Create a typeform for people to report when they did not receive GIVbacks

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3666]
we should set some limits on this.. . like you can only report missed GIVbacks within 2 months of when you were supposed to get them...

this idea came out of the giveconomy call in response to how to handle all the missed donatinos from the dapp these past months.

@WhyldWanderer - do you still want to make this happen? where would it go?
maybe @missgene could support you in making it

**Comment by WhyldWanderer** [comment]
I think that it is sufficient for users to report it in our Discord support channel or by filling out the support form that we already have on our support page. I don't see the value in creating a new form.
https://giveth.io/support

I definitely agree that we should add something to documentation and I will also add a clause to each forum post from now moving forward.
