### ISSUE TITLE
Improve the UX of QF so that users KNOW that the round hasn't started yet

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3673]
Some users have donated to QF rounds before the rounds started because they thought the round will have started...

This issue is coming up because it's not sure clear to users that the round still is not yet set up.

I think one fix would be to make the qf page... giveth.io/qf something that you could view/scroll but if you click a project from there before the round starts... you get a popup saying "The < round name> round hasn't started yet. It starts on < this date >. Do you want to make a donation now anyway? Your donation will not be eligible for matching."

But I'm open to other suggestions.

@mosaeedi - can you help?

**Comment by Tosinolawale** [comment]
![QF](https://github.com/Giveth/giveth-dapps-v2/assets/35389241/0c8f95dc-1a47-4be3-9e3b-0f9529f862bc)
@laurenluz this is the default page showing information that there is currently no active rounds. Not even listing any projects when there is no active round on my end. Or am I missing something?

**Comment by Tosinolawale** [comment]
So when the user visits the QF Page they are automatically informed the round status. All projects are displayed irrespective of round status only if the user actively clears the default filter. I don't think we need to introduce another interaction modal to this

**Comment by laurenluz** [comment]
when there is a round programmed in, but before the "Start date" we shoudl the projects & a countdown timer saying "round starts in x"

right now it is not showing because there is not upcoming round programmed in.

you can see RN on staging that there is an active round... https://staging.giveth.io/qf/all

effectively the "pre-start time active round" looks the same.. except you don't see matching estimations on the project cards...

**Comment by Tosinolawale** [comment]
![Warning](https://github.com/Giveth/giveth-dapps-v2/assets/35389241/3827c142-f127-4122-a879-f71f17737888)
@laurenluz 
https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=5311%3A46152&mode=design&t=zsaRhwJ47mOpEk2p-1

**Comment by Tosinolawale** [comment]
https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=5311%3A46152&mode=design&t=NM8Grnhc9H78txv1-1
Warning Modal for when the round is yet to start and User clicks on project card or donate button from QF Page 
![Warning QF](https://github.com/Giveth/giveth-dapps-v2/assets/35389241/33681dd8-ce58-4e05-8112-d8a82aa4df94)

**Comment by laurenluz** [comment]
perfect! thanks @Tosinolawale!!

@jainkrati can you assign someone?

**Comment by jainkrati** [comment]
@MohammadPCh for FE changes. Also Cherik, I am assuming every round has a start date coming from BE. Please let me know if otherwise

**Comment by MohammadPCh** [comment]
@jainkrati Yes, the round's info is coming from BE.

**Comment by MohammadPCh** [comment]
@laurenluz So, are we planning to display a modal when a user clicks on the donate button on the QF page before the round has started?
I'm hesitant about this approach because it could negatively impact the user experience. If we show the modal and wait for the user to click "got it," it disrupts the donation flow and adds an extra step.
Alternatively, if we redirect to the donation page and then show the modal, it seems redundant because the user would have to click the back button to return and perform another action.
I strongly recommend displaying a message above the donate button on the donation card instead.

**Comment by laurenluz** [comment]
so you are suggesting to add some copy to every single project card? I think that will look really messy... and anyway, people really shouldn't be going to the qf page to donate outside the bounds of QF rounds anyway.... and if they do, they are probably making a mistake, donating early by accident.

I think the extra friction of the modal is exactly what we need on the qf round page when the round is not open... as much as I don't want to get in the way of any donation, we had many users complaining that they donated to early & then were upset that's it's not going to be matched.

this modal, however, should definitely not appear on the projects general page at any point... if people are just on regular giveth side, we shouldn't get in their way.

wdyt? @MohammadPCh

**Comment by MohammadPCh** [comment]
@laurenluz  It wasn't about the project card; it was about the donation card. My suggestion was to add something to this card or to show a modal to get confirmation from the user to donate before proceeding.🥲
<img width="631" alt="Screenshot 2024-02-17 at 6 54 28 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/17097576/99915558-b3d2-4a7e-9319-a9fe5f98c1a3">
However, we can also add a modal to prevent users from going to the donate page. These are two different approaches, and I believe each has its benefits. Let's implement your suggestion. 😄

**Comment by MohammadPCh** [comment]
@maryjaf could you please test it? Thanks.

**Comment by maryjaf** [comment]
When this new modal should be shown ?
now by tapping on project card (not donate button) in QF page this modal is shown also?
I thought only bay tapping on "donate" button it should be shown
<img width="1497" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekZxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c60572c61eee1f196360681dc7f80afd21d4b6be/image.png" alt="image.png" />

**Comment by maryjaf** [comment]
Name of round in modal  isn't correct
<img width="1196" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/9f2ad105-be98-4626-91cf-62fde8640dc2">

**Comment by MohammadPCh** [comment]
Thanks @maryjaf, Fixed.
