### ISSUE TITLE
Make it possible to edit QF mid-page banner in admin bro

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3675]
Every qf round, I make an issue for a dev to change this text. would be great to do it in admin bro directly.

from[this page](https://giveth.io/qf/all)

<img width="1388" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2IzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--be63b1b8edf53f5eac65b28be1e919d1eed258f8/image.png" alt="image.png" />

idk if this is a frontend or backend task @RamRamez @CarlosQ96 @jainkrati

**Comment by RamRamez** [comment]
From front-end side it's a very easy task, I just need to read the title and description from an endpoint. But from the backend side, maybe backend guys can send title and description with the "allProjects" endpoint. @mohammadranjbarz @CarlosQ96 Is it possible?

**Comment by mohammadranjbarz** [comment]
@CarlosQ96  Can you do it?

**Comment by divine-comedian** [comment]
@mohammadranjbarz as per discussion take this one up

**Comment by mohammadranjbarz** [comment]
@RamRamez Can you take this?
(If you had any question feel free to ask me)

**Comment by CarlosQ96** [comment]
Leaving Pr in a few mins

**Comment by CarlosQ96** [comment]
> From front-end side it's a very easy task, I just need to read the title and description from an endpoint. But from the backend side, maybe backend guys can send title and description with the "allProjects" endpoint. @mohammadranjbarz @CarlosQ96 Is it possible?

ok So no formatting, just the title and description, thats easy enough

**Comment by laurenluz** [comment]
Yeah!

**Comment by jainkrati** [comment]
@maryjaf pls verify and close

**Comment by maryjaf** [comment]
I haven't understood which field in qf page be used for setting mid page banner ?
by changing "Description" in qf page from admin, nothing happens on QF banner
Are frontend changes needed?
@CarlosQ96 
<img width="1525" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMU9GQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4d3e971d6e2ce9938407829c6edc527ae326ae1f/image.png" alt="image.png" />

**Comment by CarlosQ96** [comment]
@maryjaf yess the description and title are no available on the api, we need frontend changes now @MohammadPCh @RamRamez

**Comment by jainkrati** [comment]
@Meriem-BM pls take guidance from @RamRamez for this.

**Comment by maryjaf** [comment]
I've set title and description for QF round id: 10, and I haven't seen  any changes in mid page banner, please take a look @Meriem-BM  
https://staging.giveth.io/qf-archive/10

<img width="1603" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM25FQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--084a1222fb4e9e9fca986baa546f90d2fc2215f8/image.png" alt="image.png" />

**Comment by maryjaf** [comment]
Thanks @Meriem-BM 
This issue has been resolved
