### ISSUE TITLE
Add "email address field" to "retrun all donation data" button from admin bro

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3676]
it would be great to export the names of projects + email addresses before the round starts in order to send the project owners emails!!

it would be great to have a one-button click for that.

an easy solution idea would be to include email addresses to this "return all donation data" field:

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/1bb8d99c-de95-4e52-9065-fc57bd9085b4)

@CarlosQ96 @jainkrati

**Comment by CarlosQ96** [comment]
Ill push this tomorrow its not complicated

**Comment by laurenluz** [comment]
SO DREAMY

**Comment by CarlosQ96** [comment]
https://github.com/Giveth/impact-graph/pull/1452 Related PR for review

**Comment by maryjaf** [comment]
The email address has been add to QF report

![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/ca067cd2-91a1-4c0c-8b16-66d5a555231b)

but I have a question that it isn't exactly relate to this issue, If needed I'll create new issue
only 9 projects are in QF round:90 , Is there specific reson for showning all projects in this report 
https://docs.google.com/spreadsheets/d/1Wk8_bG75uQGZnVywos2Ii2t-4QosHoC0pRkMlZ85Ga8/edit#gid=1461273901
@CarlosQ96

**Comment by laurenluz** [comment]
seems like a bug to me

**Comment by maryjaf** [comment]
> but I have a question that it isn't exactly relate to this issue, If needed I'll create new issue
> only 9 projects are in QF round:90 , Is there specific reson for showning all projects in this report
> https://docs.google.com/spreadsheets/d/1Wk8_bG75uQGZnVywos2Ii2t-4QosHoC0pRkMlZ85Ga8/edit#gid=1461273901
> @CarlosQ96

@mohammadranjbarz please take alook

**Comment by mohammadranjbarz** [comment]
> > but I have a question that it isn't exactly relate to this issue, If needed I'll create new issue
> > only 9 projects are in QF round:90 , Is there specific reson for showning all projects in this report
> > https://docs.google.com/spreadsheets/d/1Wk8_bG75uQGZnVywos2Ii2t-4QosHoC0pRkMlZ85Ga8/edit#gid=1461273901
> > @CarlosQ96
> 
> @mohammadranjbarz please take alook

 @maryjaf  I couldn't investigate it for today's release, would appreciate if you can take a look on this on Monday morning @CarlosQ96 
 
 JFYI @CarlosQ96

**Comment by Meriem-BM** [comment]
@CarlosQ96 after clicking on "Return all donations data" button where it's being saved?

**Comment by maryjaf** [comment]
> @CarlosQ96 after clicking on "Return all donations data" button where it's being saved?

https://docs.google.com/spreadsheets/d/1Wk8_bG75uQGZnVywos2Ii2t-4QosHoC0pRkMlZ85Ga8/edit#gid=333193225

**Comment by maryjaf** [comment]
> but I have a question that it isn't exactly relate to this issue, If needed I'll create new issue
> only 9 projects are in QF round:90 , Is there specific reson for showning all projects in this report
> https://docs.google.com/spreadsheets/d/1Wk8_bG75uQGZnVywos2Ii2t-4QosHoC0pRkMlZ85Ga8/edit#gid=1461273901
> @CarlosQ96

This problem has been resolved on STG

**Comment by Meriem-B** [comment]
@maryjaf can I get access to that sheet, is it the same for every user.

**Comment by maryjaf** [comment]
> @maryjaf can I get access to that sheet, is it the same for every user.

I have "comment only" access, @laurenluz can give access to this sheet
