### ISSUE TITLE
Tentative: Add new "sort" to QF round page "by Estimated Matching amount"

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3677]
This came by request from @GriffGreen & others, so include a new "sort by" "estimated matching amount"

I think it might be a bit complex to implement, especially considering out "matching cap" is kind of some hard coded thing.... it may lead to bugs.

wdyt @CarlosQ96 @aminlatifi @RamRamez - is it possible? what would this take? is it worth it?

cc @jainkrati

**Comment by laurenluz** [comment]
related to #2944

**Comment by RamRamez** [comment]
If we are going to sort projects by estimated matching, we need to calculate it in backend. For this calculation we need projectDonationsSqrtRootSum, allProjectsSum and matchingPool. We fetch all these from backend.
Besides that, we need CAP_PERCENTAGE that is hardcoded in both front-end and backend. So, technically it's possible to calculate and sort it in backend, but I don't know it worth it or not.
@mohammadranjbarz @CarlosQ96 what do you think?

**Comment by mohammadranjbarz** [comment]
> If we are going to sort projects by estimated matching, we need to calculate it in backend. For this calculation we need projectDonationsSqrtRootSum, allProjectsSum and matchingPool. We fetch all these from backend. Besides that, we need CAP_PERCENTAGE that is hardcoded in both front-end and backend. So, technically it's possible to calculate and sort it in backend, but I don't know it worth it or not. @mohammadranjbarz @CarlosQ96 what do you think?

Yes you are right, I think we can do it in backend side.

**Comment by jainkrati** [comment]
Sorting should happen in frontend but backend should also populate estimated matching for each project in the project list API. @RamRamez @mohammadranjbarz

**Comment by RamRamez** [comment]
@jainkrati we can't sort projects in front-end because we don't have access to all projects. We have sortBy, skip and limit in allProjects endpoint that we use to fetch sorted projects from backend. We fetch 15 projects and when user scrolls down, we fetch another 15 projects and so on. We don't fetch all projects at once.

**Comment by RamRamez** [comment]
@laurenluz I checked and we already have a filter called "amount raised in QF" for active QF rounds.
Is this what you need? if not, what changes do you need?
![image](https://github.com/Giveth/giveth-dapps-v2/assets/73441857/b7e65fcc-56a3-42ca-a238-1616366d4ee8)

**Comment by laurenluz** [comment]
Griff was requesting a sort by "estimated matching". This is a number we calculate in our backend based on the amounts raised in the round so far.

**Comment by RamRamez** [comment]
@laurenluz I've sent the PRs and BE and FE are ready. What is the desired icon, copy, color and order for this new sort item?

![image](https://github.com/Giveth/giveth-dapps-v2/assets/73441857/b200757f-1a05-4a00-8301-94cda7d21246)

**Comment by RamRamez** [comment]
> @laurenluz I've sent the PRs and BE and FE are ready. What is the desired icon, copy, color and order for this new sort item?
> 
> ![image](https://private-user-images.githubusercontent.com/73441857/318062076-b200757f-1a05-4a00-8301-94cda7d21246.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5ODUyNzcsIm5iZiI6MTcxMTk4NDk3NywicGF0aCI6Ii83MzQ0MTg1Ny8zMTgwNjIwNzYtYjIwMDc1N2YtMWEwNS00YTAwLTgzMDEtOTRjZGE3ZDIxMjQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDE1MjI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiZDZkMTEzMTFmZjE1YmRlMzg0NTgxNjcxMjliMWUyYTBlZWI5ZDJlOGZlODQ3Nzc1NjY4OWNjMmVhMTQ0NzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WgbIjsydwZXT27MgLkBtJJuk2C9IqHGq3u2CW--R5G0)

@mosaeedi can you take a look please?

**Comment by laurenluz** [comment]
copy is great as "estimated matching" - let me DM to Mo to get an icon design quick....

**Comment by mosaeedi** [comment]
Here is the updated sort dropdown with new icons.

[Link to Figma](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=5821-32677&mode=design&t=eN7tTgfhNmBRHEsb-4)

Please also change the **Recently updated** icon to the one I've shared.

The "Amount raised all time" should not be in camel case, in all of the sorting option text, just the first letter should be capitalized.
The same about the **Recently updated** text.

<img width="410" alt="Screenshot 2024-04-03 at 3 23 00 AM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/116173ec-eb45-4198-a980-b162902b4686">

**Comment by RamRamez** [comment]
@maryjaf to test and verify
