### ISSUE TITLE
Solana mainnet public rpc node

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapps-v2#3679]
Solana's main cluster API is aggressive in rate limiting, as our team (behind the same IP address) gets 403 errors. 

We should investigate whether there is any alternative public RPC node for Solana and use it in our FE applicaiton.

**Comment by mhmdksh** [comment]
@aminlatifi The new RPC URL has been shared through DM. Let me know if you need any further assistance.

**Comment by MoeNick** [comment]
Shall I close this? @aminlatifi
