### ISSUE TITLE
"received" is spelled wrong on the dapp in claim modal of GIVeconomy

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3682]
![telegram-cloud-photo-size-4-5877238436623138372-y](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/a029efd4-ab74-4237-b760-937a7e2f53c7)

maybe you can fix this @divine-comedian ?

**Comment by divine-comedian** [comment]
Fixed in https://github.com/Giveth/giveth-dapps-v2/commit/955628f0464201f3e4e6e0cdcebf186b53fd58a5 

nice catch!
