### ISSUE TITLE
Improve search feature on Giveth - PLEASE

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3688]
it really drives me crazy that when I search "soil dao"... I don't find "soildao" on Giveth... and other related search feature frustrations.

We should really improve our search feature, I feel like people have done a lot of work on this in many open source search feautre things and we can just pull something from them.

like even I bet github's search feature could be forked!

@jainkrati do you have any ideas on the best way to do this?

cc @divine-comedian

**Comment by jainkrati** [comment]
This sounds like something @marthendalnunes can help us. Lets sync up this thursday to discuss more. Sending a calendar invite for same.

**Comment by laurenluz** [comment]
Some examples of things that I think should/could be better:
- when I search "praise", I see first "Commons Stack" THEN "Give Praise" - I think we should show first the projects that have the keyword in the title
- when I search "Soil DAO"... nothing is returned... but there is a project called "SoilDAO" - I think when the user puts a space, we should look for with space or without space & show the projects in both conditions
- it's great that we allow the user to search keywords and we are checking if the project has that in their description.... but projects with the words in the title (in any reasonable combo/variation) should be shown first above projects where it existing the description
-

**Comment by MoeNick** [comment]
if it's already started, would you pls assign teh PRs to it? 
and shall I put it in-progress?

**Comment by MoeNick** [comment]
@aminlatifi @marthendalnunes 
can you please connect the PR so I can keep track of it?

**Comment by divine-comedian** [comment]
@marthendalnunes 

Any update on this feature?

**Comment by marthendalnunes** [comment]
@divine-comedian the feature was merged in staging, it will be available in the next release

**Comment by aminlatifi** [comment]
@divine-comedian Before deploying this feature, we conducted a test to measure the performance of query execution. Now, we have to do the same after the merge and compare numbers to become certain we won't face a serious degradation in response time.

**Comment by aminlatifi** [comment]
> @divine-comedian Before deploying this feature, we conducted a test to measure the performance of query execution. Now, we have to do the same after the merge and compare numbers to become certain we won't face a serious degradation in response time.

@maryjaf and @geleeroyale Did this test last time.

**Comment by maryjaf** [comment]
I shared the report of performance test on the discord channel 
https://discord.com/channels/@me/1202648134048686201/1214880883413352529
