### ISSUE TITLE
Problem in sign in/switch network on donation page when both of solana and superfluid are enable 

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3694]
There is a problem on donation page when user signed in with solana 

**To Reproduce**
1. Complete sign in flow on solana
2. Click on 'donate'
3. On donation page "Sign in" button is shown and **it seems the user isn't signed in**
4. tap on "recurring donation" tab
5. Tap on "switch network" **it doesn't work** 

cc: @MohammadPCh @alireza-sharifpour 

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/cefceed6-0e03-477f-a5cf-4a0a193f6db9

**Comment by MoeNick** [comment]
@jainkrati can you pls assign it to DEV?

**Comment by MoeNick** [comment]
@maryjaf This is happening on staging, so is it a problem with the feature label? So this is not urgent. Am I right?

**Comment by MohammadPCh** [comment]
@jainkrati @maryjaf, This issue occurred because we implemented it when Solana was inactive. However, it's something we can fix easily, so there's no need to worry about it.

**Comment by alireza-sharifpour** [comment]
It's ready for testing

**Comment by maryjaf** [comment]
Thanks @alireza-sharifpour this issue has been fixed.
