### ISSUE TITLE
Arb | changes on Donation page

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#3706]
Token List Staging (Sepolia): 
- [ ] ETH
- [ ] WETH - 0xfFf9976782d46CC05630D1f6eBAb18b2324d6B14
For the test-net logo pls take a look [here](https://www.figma.com/file/d3ciTS36toS9mra0RAPMe2/Giveth-Design-System-v0.1?type=design&node-id=5189-6636&mode=design&t=BsWml60bNztQ7qcI-4)

Token List Prd
NAME | Symbol | Address

- [ ] Arbitrum ETH - ETH
- [ ] Tether USDt -USDT - 0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9
- [ ] USDC - USDC - 0xaf88d065e77c8cC2239327C5EDb3A432268e5831
- [ ] Chainlink - LINK - 0xf97f4df75117a78c1A5a0DBb814Af92458539FB4
- [ ] Dai - DAI - 0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1
- [ ] Uniswap - UNI - 0xFa7F8980b0f1E64A2062791cc3b0871572f1F7f0
- [ ] Lido - DAO LDO - 0x13Ad51ed4F1B7e9Dc168d8a00cB3f4dDD85EfA60
- [ ] Arbitrum - ARB - 0x912CE59144191C1204E64559FE8253a0e49E6548
- [ ] Brigded ISDC - USDC.e - 0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8
- [ ] TrueUSD - TUSD - 0x4D15a3A2286D883AF0AA1B3f21367843FAc63E07
- [ ] The Graph - GRT - 0x9623063377AD1B27544C965cCd7342f7EA7e88C7
- [ ] Frax Share - FXS - 0x9d2f299715d94d8a7e6f5eaa8e654e8c74a988a7
- [ ] USDD - USDD - 0x680447595e8b7b3Aa1B43beB9f6098C79ac2Ab3f
- [ ] WOO - WOO - 0xcafcd85d8ca7ad1e1c6f82f651fa15e33aefd07b
- [ ] Gnosis - GNO - 0xa0b862f60edef4452f25b4160f177db44deb6cf1
- [ ] Curve DAO Token- CRV - 0x11cDb42B0EB46D95f990BeDD4695A6e3fA034978
- [ ] Compound - COMP - 0x354A6dA3fcde098F8389cad84b0182725c6C91dE
- [ ] GMX - GMX - 0xfc5a1a6eb076a2c7ad06ed22c90d7e710e35ad0a
- [ ] Loopring - LRC - 0x46d0cE7de6247b0A95f67b43B589b4041BaE7fbE
- [ ] Treasure - MAGIC - 0x539bdE0d7Dbd336b79148AA742883198BBF60342
- [ ] SushiSwap - SUSHI - 0xd4d42f0b6def4ce0383636770ef773390d85c61a
- [ ] yearn.finance - YFI - 0x82e3A8F066a6989666b031d916c43672085b1582
- [ ] Xai - XAI - 0x4Cb9a7AE498CEDcBb5EAe9f25736aE7d428C9D66
- [ ] XLivepeer - LPT - 0x289ba1701C2F088cf0faf8B3705246331cB8A839
- [ ] XWrapped Bitcoin - WBTC - 0x2f2a2543B76A4166549F7aaB2e75Bef0aefC5B0f
- [ ] Cartesi - CTSI - 0x319f865b287fCC10b30d8cE6144e8b6D1b476999

**You can find the logos here** 
https://www.figma.com/file/d3ciTS36toS9mra0RAPMe2/Giveth-Design-System-v0.1?type=design&node-id=4767-71303&mode=design&t=j9avztupJ3uZVwEX-4

## Acceptance Criteria
> Generated by [Zenhub AI](https://www.zenhub.com/ai)

- [ ] **Scenario 1: Viewing the list of eligible tokens**
  - Given that I am on the Donation page
  - When I view the list of tokens
  - Then I should see the list of eligible tokens correctly

- [ ] **Scenario 2: Handling projects that do not raise funds in Arb**
  - Given that I am on the Donation page
  - When I view a project that does not raise funds in Arb
  - Then I should see the wrong network modal

- [ ] **Scenario 3: Viewing the balance**
  - Given that I am on the Donation page
  - When I view the balance
  - Then I should see the balance correctly

- [ ] **Scenario 4: Viewing the logo of tokens and GIVback icon**
  - Given that I am on the Donation page
  - When I view the tokens
  - Then I should see the logo of tokens correctly
  - And I should see the GIVback icon if the tokens are eligible for GIVbaks

- [ ] **Scenario 5: Viewing the price in donation in progress**
  - Given that I am on the Donation page
  - When I view a donation in progress
  - Then I should see the price correctly

- [ ] **Scenario 6: Viewing the success page**
  - Given that I have made a successful donation
  - When I view the success page
  - Then I should see the success page correctly

- [ ] **Scenario 7: Viewing the donation in "My Donations"**
  - Given that I have made a donation
  - When I view "My Donations"
  - Then I should see the donation

- [ ] **Scenario 8: Viewing the donation on the project donation tab**
  - Given that I have made a donation to a project
  - When I view the project donation tab
  - Then I should see the donation

- [ ] **Scenario 9: Verifying my transaction**
  - Given that I have made a transaction
  - When I submit the transaction
  - Then my transaction should get verified

- [ ] **Scenario 10: Handling failed transactions on the frontend**
  - Given that I have made a transaction on the frontend
  - When the transaction fails
  - Then the backup service should save the transaction
  - And the transaction should be updated in "My Donations" in 5 minutes

**Comment by MoeNick** [comment]
@alireza-sharifpour 
@mosaeedi is currently updating the Figma for missing logos, he will finalizing at the end of today.

**Comment by alireza-sharifpour** [comment]
@MoeNick @mosaeedi, The provided Figma link is the logo of all the tokens we use in the project!
I only need a zip file of all the tokens related to this PR.
Can you send it to me?

**Comment by alireza-sharifpour** [comment]
@MoeNick @mosaeedi, The provided Figma link is the logo of all the tokens we use in the project!
I only need a zip file of all the tokens related to this PR.
Can you send it to me?

**Comment by maryjaf** [comment]
these tokens have been added on test env
<img width="1052" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0IvQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4c72b200f600ae364955d264d460cb2820b00c6b/image.png" alt="image.png" />

all of  scenarios have been passed
