### ISSUE TITLE
Remove donations from giving season round 👀 

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3710]
https://optimistic.etherscan.io/tx/0xa19a957f145ab98e62da15db79fdcbdc80931c106e5dce5fae4fc4ffa983cda4
https://optimistic.etherscan.io/tx/0x572f2b47c415da67ba59b064d3d81462659acb666df929d578b58a592613d5bd

these donations from Griff were actually not donations at all 👀 

@CarlosQ96 do we have the list of donations that we added to the backend? maybe we should do a quick check to make sure that there are no other big ones that look fishy.

**Comment by laurenluz** [comment]
cc @jainkrati

**Comment by mohammadranjbarz** [comment]
> https://optimistic.etherscan.io/tx/0xa19a957f145ab98e62da15db79fdcbdc80931c106e5dce5fae4fc4ffa983cda4 https://optimistic.etherscan.io/tx/0x572f2b47c415da67ba59b064d3d81462659acb666df929d578b58a592613d5bd
> 
> these donations from Griff were actually not donations at all 👀
> 
> @CarlosQ96 do we have the list of donations that we added to the backend? maybe we should do a quick check to make sure that there are no other big ones that look fishy.



> https://optimistic.etherscan.io/tx/0xa19a957f145ab98e62da15db79fdcbdc80931c106e5dce5fae4fc4ffa983cda4 https://optimistic.etherscan.io/tx/0x572f2b47c415da67ba59b064d3d81462659acb666df929d578b58a592613d5bd
> 
> these donations from Griff were actually not donations at all 👀
> 
> @CarlosQ96 do we have the list of donations that we added to the backend? maybe we should do a quick check to make sure that there are no other big ones that look fishy.

Do you want to totally delete these donations from DB or just remove them from qfRound?

**Comment by mohammadranjbarz** [comment]
@laurenluz  Done.

**Comment by laurenluz** [comment]
we should also remove this one: https://optimistic.etherscan.io/tx/0xadfb65f34628772ec10fe0335f6b8c2c4478381e377c6d6987216f6ac89e39f0
