### ISSUE TITLE
Change hard-coded passport score in admin bro export to check the round requirements

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3711]
we have it hard coded to 5, but each round may have a different passport score. it should check what was set in admin bro for the round.

**Comment by jainkrati** [comment]
Assigned to @aminlatifi as he is working on similar other issues.

**Comment by laurenluz** [comment]
this will need to be changed to 4 in order to get the right data for the polygon QF round.

@aminlatifi can you do it in the next couple of days?

**Comment by aminlatifi** [comment]
> this will need to be changed to 4 in order to get the right data for the polygon QF round.
> 
> @aminlatifi can you do it in the next couple of days?

I thought you had already exported polygon round data and had started processing it. Will it work for you if we change the formula now?
We can change the formula manually by running an SQL script against the production I guess, @CarlosQ96 wdyt?

**Comment by aminlatifi** [comment]
It's the logic checks the minimum score in SQL
```sql
            DROP MATERIALIZED VIEW IF EXISTS project_actual_matching_view;
            CREATE MATERIALIZED VIEW project_actual_matching_view AS
            WITH DonationsBeforeAnalysis AS (
            SELECT 
                p.id, 
                p.slug, 
                p.title,
                qr.id as "qfId",
                STRING_AGG(distinct pa."networkId" || '-' || pa."address", ', ') AS "networkAddresses",
                COALESCE(SUM(d."valueUsd"), 0) AS "allUsdReceived", 
                COUNT(DISTINCT d."fromWalletAddress") AS "totalDonors"
            FROM 
                public.donation AS d
                INNER JOIN project p ON p.id = d."projectId"
                INNER JOIN qf_round qr on qr.id = d."qfRoundId"
                inner join project_address pa on pa."projectId" = p.id AND pa."networkId" = ANY(qr."eligibleNetworks")
                inner join "user" u on u.id = d."userId" 
            GROUP BY 
                p.id,
                p.title, 
                p.slug,
                qr.id
            ), DonationsAfterAnalysis AS (
            SELECT 
                p2.id, 
                p2.slug, 
                p2.title,
                qr.id as "qfId",
                COALESCE(SUM(d2."valueUsd"), 0) AS "allUsdReceivedAfterSybilsAnalysis", 
                COUNT(DISTINCT d2."fromWalletAddress") AS "uniqueDonors",
                SUM(SQRT(d2."valueUsd")) AS "donationsSqrtRootSum",
                POWER(SUM(SQRT(d2."valueUsd")), 2) as "donationsSqrtRootSumSquared"
            FROM 
                public.donation AS d2
                INNER JOIN project p2 ON p2.id = d2."projectId"
                INNER JOIN qf_round qr on qr.id = d2."qfRoundId"
                inner join project_address pa on pa."projectId" = p2.id AND pa."networkId" = ANY(qr."eligibleNetworks")
                inner join "user" u on u.id = d2."userId" and u."knownAsSybilAddress" = false
            WHERE 
                p2."statusId" = 5 
                AND LOWER(d2."fromWalletAddress") NOT IN (
                SELECT DISTINCT LOWER(pa.address) AS "projectAddress"
                FROM public.project_address pa 
                JOIN project p3 ON p3.id = pa."projectId" 
                AND p3."verified" = true 
                AND p3."statusId" = 5 
                AND p3."isImported" = false
                ) 
                AND d2."qfRoundUserScore" > 5
            GROUP BY 
                p2.id,
                p2.title,
                p2.slug,
                qr.id
            )
            SELECT 
                d1.id AS "projectId",
                d1.title,
                d1.slug, 
                d1."networkAddresses",
                d1."qfId" AS "qfRoundId",
                d1."allUsdReceived",
                d1."totalDonors",
                d2."allUsdReceivedAfterSybilsAnalysis",
                d2."uniqueDonors",
                d2."donationsSqrtRootSum",
                d2."donationsSqrtRootSumSquared"
            FROM 
                DonationsBeforeAnalysis d1
            INNER JOIN DonationsAfterAnalysis d2 ON d1.id = d2.id AND d1.slug = d2.slug and d1."qfId" = d2."qfId";
            
            CREATE INDEX idx_project_actual_matching_project_id ON project_actual_matching_view USING hash ("projectId");
            CREATE INDEX idx_project_actual_matching_qf_round_id ON project_actual_matching_view USING hash ("qfRoundId");
```
            
We can re-execute it against production db by changing that 5 to 4 at line

```sql
                            AND d2."qfRoundUserScore" > 5
```

**Comment by mohammadranjbarz** [comment]
> > this will need to be changed to 4 in order to get the right data for the polygon QF round.
> > @aminlatifi can you do it in the next couple of days?
> 
> I thought you had already exported polygon round data and had started processing it. Will it work for you if we change the formula now? BTW, We can change the formula manually by running an SQL script against the production I guess, @CarlosQ96 @mohammadranjbarz wdyt?

Yes and for now it's ok, but we should change it to can have different minimum passport score for different running qfRounds.
@laurenluz When you say we can change it from `5` to `4`

**Comment by CarlosQ96** [comment]
I think the entity has the minimum passport score we should make it dynamic. Changing it at least is simple in this case.

**Comment by laurenluz** [comment]
yeah I agree we should make a more robust solution so that the "export QF round data" button considers what was the set threshold for that particular QF round...

but you guys mentioned it was complex to do, so at least to finalize polygon qf date (hopefully by end of the week), we should change the hardcoded value from 5 to 4.

**Comment by laurenluz** [comment]
this will unblock *polygon* round data export (which we need now)

For the meta pool round, we will need to again change it to be 5, as the threshold for the round is 5.

**Comment by mohammadranjbarz** [comment]
@maryjaf  Now we  use `qfRound.minimumPAssportScore` instead of hard coded value, you can test it on Staging

**Comment by maryjaf** [comment]
Thanks @mohammadranjbarz I've tested and now the minimum score that is set in admin bro be considered in system behavior

**Comment by jainkrati** [comment]
@maryjaf pls close this once you verify on prod

**Comment by maryjaf** [comment]
Sure 
I should check it on prod after round starts 
but on STG everything are OK

**Comment by laurenluz** [comment]
I think it is fine, I set the cap to 0.2 and it seems to be working.
