### ISSUE TITLE
Let's make a simple, in dapp, seemless experience for allowing our users to bridge GIV

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#3716]
**As a user of the GIV farm, I want to move my GIV to Optimism or Gnosis (or other chains in the future), so that I can get better rewards, or use some functionality that is only on one chain (like GURVES) but I don't want to get GOUGED by Jumper and mainnet fees.**

<img width="664" alt="Screenshot 2024-02-01 at 10 18 46 AM" src="https://github.com/Giveth/giveth-dapps-v2/assets/14945613/4a1377ce-882a-492b-acc2-745b533d87ae">

<img width="856" alt="Screenshot 2024-02-01 at 10 27 23 AM" src="https://github.com/Giveth/giveth-dapps-v2/assets/14945613/1238fc04-34d4-484c-8d98-ba0f279058c2">

Main goals of a solution
- No need to leave the GIVfarm page
- Low slippage (<2%) for bridging
- No need to even consider paying mainnet gas fees unless you are moving 1M GIV or more

Optional side benefits of a solution
- DAO could earn fees acting as a bridge
- More volume and arbitrage totally unrelated to the GIVeconomy can happen through the GIV token if there is a simple route for bridging between Gnosis and Optimism 
- Other staking options for the GIV token become possible outside of GIVpower, moar GIV utility!

There is a Connext <> Giveth chat on Telegram, in it I confirmed the feasibility of working with them to put up liquidity. They are in our circles from the 1hive days and are one of the few bridges that has a lot of gnosis volume and liquidity, they are integrated into  all the main bridge aggregators (Lifi, Socket, Metamask, etc) and have a UI that we would be featured on.

Also, they have expressed interest in integrating with us before! They even deployed a donation bridge for us that would have been useful for our Giving Block integration... obviously, we didnt pursue that as we chose to phase out that integration, but this excitement to work with us in the past and quick response time to our DMs really makes them a great team to partner with!

Here is at a high level what it would take to make this integration happen:
1. The DAO puts up a bunch of GIV on OP and Gnosis as liquidity
2. We run a node to route bridge trades through our liquidity
3. We integrate with their APIs to build a front end portal so people can bridge straight within the GIVfarm page.

WDYT?

**Comment by divine-comedian** [comment]
This could be a lot of work - Do we know how many people realistically have this problem of bridging their GIV and paying fees? 

Do any of our actual users complain about this or just the contributors who have a ton of GIV from vesting.

**Comment by GriffGreen** [comment]
I don't think it is a high priority issue, but I do think that if we want to beef up the economy, this is an easy and straighforward way... even if we don't make the front end experience, we as a DAO could do the infrastructure part. 

It creates a revenue stream and adds liquidity to the GIV token on GNO and OP potentially making volume via arbitrage, as it would make the GIV token a route for bridges and ARB bots will go mad when our Liquidity vs GNO on gnosis chain is competing against our liquidity vs OP on Optimism... and if we are running the bridge via connext, we get a cut on the action.

**Comment by laurenluz** [comment]
I love this idea, and think we should take it up when there's a bit more bandwidth. moving to product backlog for now...

**Comment by laurenluz** [comment]
@SteffanThorn

**Comment by SteffanThorn** [comment]
I definitely love this idea as a way to beef up the GIVeconomy and have liquidity happening in and around GIV in this way. 

A lot of og Regens have liquidity on Gnosis, and Optimism seems to be the new hub so the direct bridge makes sense as gnosis is difficult to move out of. 

High-Level Steps:
•Integrate Bridge
•Add Liquidity 
•Market the update with incentives (snapshot for RetroPGF future rewards maybe 🤷‍♂️ -- could be elusive enough users don't know exactly what dates or amount for rewards, but hidden enough to keep them using the bridge for that potential.) 

With the marketing we'd be helping to make it more sustainable. 

Could also encourage any of our QF sponsors to use the bridge too. 

I also asked on twitter about this kind of bridge and someone mentioned connext anyways -- seems like the perfect market fit. 
https://x.com/SteeTweets/status/1757248530056642939

**Comment by geleeroyale** [comment]
I can make this a priority once I am done with my current Epic - if nothing else comes in between. Should not take too long to get the basic node set up.

**Comment by SteffanThorn** [comment]
Thanks for the update @geleeroyale. When does your current Epic end?

**Comment by SteffanThorn** [comment]
@divine-comedian @laurenluz @GriffGreen @MoeNick 

Would love your feedback on this idea mentioned -- Maybe we need a scope of how much in rewards would be acceptable on our end and enough on users end to be worthwhile and enjoyable: 

•Market the update with incentives (snapshot for RetroPGF future rewards maybe 🤷‍♂️ -- could be elusive enough users don't know exactly what dates or amount for rewards, but hidden enough to keep them using the bridge for that potential.)

**Comment by geleeroyale** [comment]
> Thanks for the update @geleeroyale. When does your current Epic end?

Let's do it in the coming week.

**Comment by geleeroyale** [comment]
I started work on this, following the recommended approach: https://docs.connext.network/routers/spinning-up

I will update this checklist as I move along

## Checklist for Running a Router

- [ ] Spin up the router and configure for testnets.
- [ ] Provide liquidity and gas fees on testnets.
- [ ] Test the router on testnets.
- [ ] Change configuration to mainnets (use a different private key!), or spin up a new mainnet router.
- [ ] Provide liquidity on mainnets.
- [ ] Monitor router logs.

**Comment by geleeroyale** [comment]
![telegram-cloud-photo-size-4-5970017379553492445-y](https://github.com/Giveth/giveth-dapps-v2/assets/317685/cf6460ea-c2cf-468f-9ee2-52845c7a8758)

I am at a point where I can say with confidence, that we should spin up the mainnet router ASAP - at least. I ran all testing required successfully on *testnet* - time to:
- change to mainnet
- appoint a treasurer?
- provide liquidity to our router

**Comment by divine-comedian** [comment]
@laurenluz is this one done?

**Comment by laurenluz** [comment]
YES! 🎉
