### ISSUE TITLE
Blog images on the homepage are broken...

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#3717]
In the 'Recent Posts' section of the homepage, the images are not populating correctly.
https://giveth.io

![image](https://github.com/Giveth/giveth-dapps-v2/assets/74267818/ce32afdf-3dbb-4fe2-b1cb-8a704cfb430b)

**Comment by divine-comedian** [comment]
@jainkrati - Who can look into this - looks like the images are missing or broken, maybe Ramin?
