### ISSUE TITLE
Prevent Users from removing Optimism Address if they have enabled recurring donations

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3718]
We should not allow users to remove their optimism address when they have enabled recurring donations (if they have an anchor address) - this prevents users from missing out on unclaimed donations and solves some potential edge cases

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/415ea7b0-ec2f-498c-bdd9-3ddab1429081)

I don't have the design with me but we should disable this trash can button (grey it out) and add a hover tooltip that shows to the RIGHT of it with the following text: 

> You cannot remove your Optimism recipient address because you have enabled Recurring Donations for this project. You can still replace your recipient address with a new one.

**Comment by alireza-sharifpour** [comment]
This is ready for testing @maryjaf

**Comment by maryjaf** [comment]
the tests have been passed.

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzl5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--363ad93bec27a0b2881ce65deff69388e6822d7b/image.png" alt="image.png" />

**Comment by divine-comedian** [comment]
@alireza-sharifpour - one small thing, when the button is disabled can we prevent this circle animation from showing up? 
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/639c8021-7523-4cf2-9cf7-690d44990628)

**Comment by maryjaf** [comment]
Thanks @alireza-sharifpour 
If the project has a allo profile this below view is shown 

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0d2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1f73b352d32755aed725301a7d64101f9e15a1c7/image.png" alt="image.png" />
