### ISSUE TITLE
Save gitcoin passport score for each user at the time the round ends (and save it in the db)

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3719]
Right now, I think we are dynamically updating the user's passport score... but for QF rounds... we should really check what their passport score is/was during the round to see if at some point during the round they have a passport score at or above our set threshold for the round (usually 5).

I'm thinking of this now because for the Giving Season round, we are a little behind on data processing, so when I do the export, I'm concerned that some users who might have had a passport score, might have since lost it or had it get wiped or something...

and what I really need to know is what was their score during the round/at the end of the round.

@mohammadranjbarz @CarlosQ96

**Comment by laurenluz** [comment]
tbh I think we need to do multiple checks & stores - maybe even one every day or an active round, and check if their score was ever 5 or more during the round period 👀

I'm just discovering that griff's donatinos were excluded form the last qf round because he didn't meet the score threshold... or at least, what I have is that he has no score in my data. :(

**Comment by GriffGreen** [comment]
Yeah, how long do gitcoin scores persisist?

**Comment by aminlatifi** [comment]
> Yeah, how long do gitcoin scores persisist?

Based on my knowledge once you submit your profile against a program (Giveth Scorer program in our case), it will be preserved forever until you submit again.

**Comment by aminlatifi** [comment]
> ave had a passport score, might have since lost it or had it get wiped or something...

Had @GriffGreen updated/refreshed his score on our FE before round end?
Currently, as a round finishes, we update all past donations' corresponding passport score to the latest score their creator have had till that point.

**Comment by CarlosQ96** [comment]
Ok so we have a cronjob that fills empty passport scores.
However, I think we must change it, to specify which round to fill (a qfround JUST ended), and also check at the end of the round if the user scores saved in the donation changed, and update them if so.

**Comment by aminlatifi** [comment]
@laurenluz Would you please provide the Griff donation case details? then we will be able to investigate the issue better.
Based on my understanding (@CarlosQ96 please correct me if it's wrong), the user's passport score is associated with the user entity and is updated on each refresh request triggered by the user. Then, at the end of the round, we propagate the user's last submitted score to all her/his donations (donation corresponding qf score has been empty till that point, and it's not been filled on donation time). 
So, @laurenluz please consider the above routine and let me know your expectations. Also, regarding your proposal to snapshot users' scores at the end of each day, I don't think it's necessary. I think it makes sense to stick to the user's last submitted score till the end of the qfRound as it's right now.

**Comment by CarlosQ96** [comment]
I deleted my comment, my mistake, actually the only time the score is added is at the end of rounds. Or a few seconds after it deactivated. 
So we update the score at the end of the round.

**Comment by CarlosQ96** [comment]
![image](https://github.com/Giveth/giveth-dapps-v2/assets/92376054/540e6c30-d3b5-4412-9ac0-c32adf0cf0e0)
But looking at the code if two rounds are running in parallel we will have issues, we must pass the roundId

**Comment by laurenluz** [comment]
> @laurenluz Would you please provide the Griff donation case details? then we will be able to investigate the issue better.
> Based on my understanding (@CarlosQ96 please correct me if it's wrong), the user's passport score is associated with the user entity and is updated on each refresh request triggered by the user. Then, at the end of the round, we propagate the user's last submitted score to all her/his donations (donation corresponding qf score has been empty till that point, and it's not been filled on donation time).

@aminlatifi - well I'm not exactly sure what happened in Griff's case. All I know is that in the dataset I originally got from Carlos post-round (and actually 3 weeks post-round because it took us so long to add "missed" donations)... Griff's donations had a score of < blank >.

It's possible that Griff didn't click the "refresh score" button during the round or something... but that is confusing because I'm sure that in SOME recent QF round he had refreshed his score, and according to what you're saying... then it should not have been blank.

Later, when I was in admin bro clicking "export QF round data"... it seems like his donations *were* included in the calculations & had an associated score...

So all I know for sure is:
- his donations had no recorded score (score of blank) in our backend when Carlos initially grabbed the donations list for me mid-January
- by the end of January... when I was exporting the data after removing sybils etc. etc... his donations had some score (above 5) recorded with them.

> So, @laurenluz please consider the above routine and let me know your expectations. Also, regarding your proposal to snapshot users' scores at the end of each day, I don't think it's necessary. I think it makes sense to stick to the user's last submitted score till the end of the qfRound as it's right now.

If we can confirm that the user's score associated with the user entity *only* changes when the user himself clicks "refresh"... and that it doesn't like auto-delete when passport does something funky on their end....

AND that we record the score only *once* for the donations.... i.e. at the very moment the round ends... and propogate that score alongside all the user's donations throughout the round....

And that that final "score" for those in-round donations will not then later change in our backend if... for example, the user refreshes their score a week after the round ends...

then I guess what we have built is ok...

My concern is basically that I don't want there to be some case where the user's score is deleted without them knowing form the passport side.... or that 1 week post-round they refresh the score and then the score on their in-round donations changes... because those things would create problems & inconsistencies.

**Comment by aminlatifi** [comment]
@laurenluz It's good that we all agreed on the solution. Let's first be sure what @CarlosQ96 has sent you. where that data comes from. @CarlosQ96 can you put details here?

Plus, @CarlosQ96 I agree with you to fill only the donations' score associated with the QfRound. Because it may cause issues either when we have multiple rounds overlapping with each other, or a donation that is not associated with the last QFRound (and maybe associated with an older round) gets a score. Can you create an issue with details for it?

**Comment by laurenluz** [comment]
@CarlosQ96 can you put the details here?

**Comment by CarlosQ96** [comment]
@aminlatifi @laurenluz What details just to be sure. The exported data came from the database directly, all donations inside the qfround with the passport condition. 

What course of action are we taking here? At this point is hard also to tell whats wrong as we later included donations and even checking Griff's score its set correctly.

**Comment by laurenluz** [comment]
ok, I think if we can achieve this it's fine:
- at the end of a particular qf round (i.e. at the qf round end time as it is set in admin bro), we take a snapshot of the user's passport scores at that moment & add them to each donation they made in the round, so that when we export the donations, we see those scores.

is that what we are supposedly doing right now?

**Comment by CarlosQ96** [comment]
Yes when a round expires the cronjob will catch it and update the scores taking a snapshot. Like I show in the code picture above.

**Comment by laurenluz** [comment]
hmm, ok, then I guess we can just leave this issue w/o further development... and I guess - check? - how it goes in the future?

I really don't understand what happened though... are you sure there were no bugs/issues w/ the cronjob at the end of the giving season round?

because when you gave me the export of donation data to send to trustalabs, it didn't record griff's passport score. but then later when you checked, you said it was in there... maybe there was a day or delay or something on the execution time?

**Comment by jainkrati** [comment]
@mohammadranjbarz to assist @maryjaf to test this post fixing of https://github.com/Giveth/giveth-dapps-v2/issues/3752

**Comment by maryjaf** [comment]
for test of this issue I did these steps but I didn't see the expected result pleas take a look if I'm right 
@mohammadranjbarz 
-minimum score is set 7 for this round 
-I Donated to a project by user with score 7.14 
-I checked list of round's donation and my donation has been shown corrctly
-I changed my score from gitcoin passport into 1 
-I ended the round and after that I checked the list of donatio
-I expected this donation shouldn't be shown in list but this donation was shown in list

**Comment by mohammadranjbarz** [comment]
> for test of this issue I did these steps but I didn't see the expected result pleas take a look if I'm right @mohammadranjbarz -minimum score is set 7 for this round -I Donated to a project by user with score 7.14 -I checked list of round's donation and my donation has been shown corrctly -I changed my score from gitcoin passport into 1 -I ended the round and after that I checked the list of donatio -I expected this donation shouldn't be shown in list but this donation was shown in list

We run this job hourly, so it would not do the job immediately after qfRound has ended, I will change it to 5 min, to can test it easier

**Comment by maryjaf** [comment]
> for test of this issue I did these steps but I didn't see the expected result pleas take a look if I'm right

Thanks @mohammadranjbarz I've tested on stg and this problem has been resolved

**Comment by laurenluz** [comment]
@mohammadranjbarz can you explain to me the change we made? because there was a discussion in this issue and I thought we decided to leave it without further changes, but then it seems like we made changes?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz can you explain to me the change we made? because there was a discussion in this issue and I thought we decided to leave it without further changes, but then it seems like we made changes?

<img width="898" alt="Screenshot 1402-12-01 at 10 04 15 in the morning" src="https://github.com/Giveth/giveth-dapps-v2/assets/9850545/d2ac10b6-8855-4365-946e-1a69764945ad">


We just addressed to this notion file and tried to deliver important issues, but as we were in rush we missed some comments there, @jainkrati  https://github.com/Giveth/giveth-dapps-v2/issues/3719#issuecomment-1946960651

So now we have some overlaps because we do these two things:
1. At the end of the round we add the user's passportScore to donation in field `userPassportScore` and we use it ( it has a problem that we don't check the user's passport score with Gitcoin server and we just fill it with the data that we already have it in our DB the is not the updated/correct value for that user

2. The new thing: at the end of the round we save passport score for all donors on that round in a new table ( not in donation entity) and when trying to calculate actual matching we join it with that new table ...

Now we can do two things:
1. Remove the first solution codes ( just write a migration to to fill the user_passport_score with data that already stored in donation.userPassportScore)
2. Move updating passport score logic from solution2 to solution1 and the delete the rest of the codes from solution 2

@jainkrati  @CarlosQ96  WDYT?

**Comment by aminlatifi** [comment]
> > @mohammadranjbarz can you explain to me the change we made? because there was a discussion in this issue and I thought we decided to leave it without further changes, but then it seems like we made changes?
> 
> <img alt="Screenshot 1402-12-01 at 10 04 15 in the morning" width="898" src="https://private-user-images.githubusercontent.com/9850545/306157444-d2ac10b6-8855-4365-946e-1a69764945ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MjE1NTgsIm5iZiI6MTcwODQyMTI1OCwicGF0aCI6Ii85ODUwNTQ1LzMwNjE1NzQ0NC1kMmFjMTBiNi04ODU1LTQzNjUtOTQ2ZS0xYTY5NzY0OTQ1YWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjBUMDkyNzM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDk3ZTdjM2IwY2Y1MDgxN2JkYmE0MWZkY2I3MTBmZDgxYjYzZDI0ZmEzNWU3MzIwYzg2YTg3YjIwZWQ4YWNiOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NziB4lbraNmyJ4CQwGSup6fsCbph2CsTOADIBqpUTEA">
> We just addressed to this notion file and tried to deliver important issues, but as we were in rush we missed some comments there, @jainkrati [#3719 (comment)](https://github.com/Giveth/giveth-dapps-v2/issues/3719#issuecomment-1946960651)
> 
> So now we have some overlaps because we do these two things:
> 
> 1. At the end of the round we add the user's passportScore to donation in field `userPassportScore` and we use it ( it has a problem that we don't check the user's passport score with Gitcoin server and we just fill it with the data that we already have it in our DB the is not the updated/correct value for that user
> 2. The new thing: at the end of the round we save passport score for all donors on that round in a new table ( not in donation entity) and when trying to calculate actual matching we join it with that new table ...
> 
> Now we can do two things:
> 
> 1. Remove the first solution codes ( just write a migration to to fill the user_passport_score with data that already stored in donation.userPassportScore)
> 2. Move updating passport score logic from solution2 to solution1 and the delete the rest of the codes from solution 2
> 
> @jainkrati @CarlosQ96 WDYT?

@mohammadranjbarz Regarding the first item, the user passport score in our db would be the most updated one because the user has to submit every new passport profile against our scoring program through our backend, so the backend always will be in the loop.

**Comment by jainkrati** [comment]
> st updated one because the user has to submit every new passport profile against our scoring program through our backend, so the backend always will be in the loop.

I agree with @mohammadranjbarz . We had to make the release in time for metapool round despite sporadic availability of our team members and this as a p0 was one of the important fixes. We did keep everyone in loop by discusssing in the channel during the release. 

Because people did not jump in to clarify at that time, we have fixed it in the best possible appraoch and information available at that time. Now to fix the overlap issue. if our DB record is not the most updated one fetched verified from Gitcoin then we should update the logic. 

i do see some differences in your approaches @mohammadranjbarz and @aminlatifi . could you get on a call to sort it out? Let me know if I am needed.

**Comment by mohammadranjbarz** [comment]
> > st updated one because the user has to submit every new passport profile against our scoring program through our backend, so the backend always will be in the loop.
> 
> I agree with @mohammadranjbarz . We had to make the release in time for metapool round despite sporadic availability of our team members and this as a p0 was one of the important fixes. We did keep everyone in loop by discusssing in the channel during the release.
> 
> Because people did not jump in to clarify at that time, we have fixed it in the best possible appraoch and information available at that time. Now to fix the overlap issue. if our DB record is not the most updated one fetched verified from Gitcoin then we should update the logic.
> 
> i do see some differences in your approaches @mohammadranjbarz and @aminlatifi . could you get on a call to sort it out? Let me know if I am needed.

Yeah thanks @jainkrati , I would talk with @aminlatifi  about it

**Comment by mohammadranjbarz** [comment]
I talked with Amin, we knew the old solution is good enough , we can delete the new solution because it's redundant.
JFYI @jainkrati
