### ISSUE TITLE
Add link to forum to allow users to request to add tokens to GIVbacks token list

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#372]
If the user copy/pastes in a token address that is NOT eligible for GIVbacks (i.e. is not in our drop down), this part should say 

"This token is not eligible for GIVbacks. To create a request to add this token to our GIVbacks token list, please make a comment in our **forum.**"

"forum" should link to here: https://forum.giveth.io/t/givbacks-token-list/253
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/a04f5e84-6b7e-415f-83c2-4d67754245b2)

**Comment by divine-comedian** [comment]
@RamRamez  looks mostly good except one small fix
![image](https://user-images.githubusercontent.com/67759413/163848279-e55242a8-c005-42a7-bc3e-064520202f73.png)

on this toast notification the `learn more` looks a bit squished - I added `flex-wrap` to the container and looks a bit better 

![image](https://user-images.githubusercontent.com/67759413/163851886-7c96821e-7108-4a12-a822-22eb07f58758.png)

**Comment by divine-comedian** [comment]
no objections I'll move to done

**Comment by MoeNick** [comment]
Actually, I asked @RamRamez  for editing that toast msg and he had it on staging not merged waiting for review I guess.
