### ISSUE TITLE
Hide MM from wallet adaptor modal

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#3720]
HAPPENING TO SOME USERS: 
Connecting to Solana via the snap in Metamask is not working on DApp, so we must remove the Metamask option from the wallet adaptor modal to avoid confusion.

**Comment by jainkrati** [comment]
@alireza-sharifpour can you pls take this up today itself ? @MohammadPCh and @aminlatifi to review

**Comment by aminlatifi** [comment]
@MoeNick What's the problem with this extension? It's working for me, I guess as expected.

**Comment by MoeNick** [comment]
@maryjaf can you pls make sure whether we have bug on this or not?

**Comment by maryjaf** [comment]
I had tested connecting to solana  with mm and it worked for me

**Comment by alireza-sharifpour** [comment]
Shall we close this issue?
@jainkrati @MoeNick @aminlatifi

**Comment by MoeNick** [comment]
I'll keep it in the backlog for investigation on some users, I will unassign you and we will test with Mitch
Thanks
