### ISSUE TITLE
Removing "Building on Polygon" Category section on project create/edit

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3722]
I think this is a leftover from the polygon round, we should remove this category since it is confusing for users. Currently on production it looks like this:

<img width="870" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeklvQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e5594bba7b516de049114f7aedc2ba2bc95e9155/image.png" alt="image.png" />

Hide this category entirely from the UI since the round is over. 

cc @laurenluz

**Comment by laurenluz** [comment]
yeah we can hide it (just comment out on the frontend)... but I think we should keep the backend info on the category selection.

tbh, I was thinking we could also just keep this... projects can say if they are building on Polygon... it's not exactly related to the QF round because anyone could have chosen said they were building on Polygon...

but I guess since we don't have "building on Optimism" or "Solana" or whatever, it's a bit funny w/ the rest of the options.

**Comment by jainkrati** [comment]
@MohammadPCh can you spend 30-40 minutes for removing this

**Comment by MohammadPCh** [comment]
@laurenluz @jainkrati  All categories are fetched from the backend. I can implement code to hide them on the frontend. Should we proceed with hiding them only on the create/edit project page?

**Comment by laurenluz** [comment]
just you can just hide them on the create/edit project page, I honestly don't htink it''s so bad to show projects who claim to be "Building on Polygon" anyway.

**Comment by divine-comedian** [comment]
The category is confusing and doesn't line up with the other categories on our page

**Comment by MohammadPCh** [comment]
@maryjaf could you please test it? Thanks

**Comment by maryjaf** [comment]
For project that they had this category also this  category and subcategories  won't be shown in edit page
 and this category be  shown now in list of dApp categories, are  these accepted? @divine-comedian

**Comment by divine-comedian** [comment]
> For project that they had this category also this category and subcategories won't be shown in edit page and this category be shown now in list of dApp categories, are these accepted? @divine-comedian

What do you mean specifically by 'shown in list of dApp categories'?

**Comment by maryjaf** [comment]
> > For project that they had this category also this category and subcategories won't be shown in edit page and this category be shown now in list of dApp categories, are these accepted? @divine-comedian
> 
> What do you mean specifically by 'shown in list of dApp categories'?

<img width="960" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/dfb02ab0-53be-46c5-9775-823fcf17524a">

**Comment by divine-comedian** [comment]
Wow seems like an uphill battle against the back-end...

how hard will it be to comment those out @MohammadPCh ?

**Comment by MohammadPCh** [comment]
Done ✅

**Comment by maryjaf** [comment]
> Done ✅
When this changes be deployed on stg, let me know

**Comment by maryjaf** [comment]
> For project that they had this category also this category and subcategories won't be shown in edit page and this category be shown now in list of dApp categories, are these accepted? @divine-comedian

This "Building on polygon " has been removed from list of categories on stg, thanks @MohammadPCh 

and one question @divine-comedian 
"For project that they had this category also this category and subcategories won't be shown in edit page" is this approved ?

**Comment by divine-comedian** [comment]
> > For project that they had this category also this category and subcategories won't be shown in edit page and this category be shown now in list of dApp categories, are these accepted? @divine-comedian
> 
> This "Building on polygon " has been removed from list of categories on stg, thanks @MohammadPCh
> 
> and one question @divine-comedian "For project that they had this category also this category and subcategories won't be shown in edit page" is this approved ?

Yes 

The only edge case I can think of is if a project comes back and wants to add more categories to their project (or remove the polygon ones) they might be limited, but we can deal with it as it comes
