### ISSUE TITLE
Gitcoin passport shouldn't be shown in user view page

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3728]
**To Reproduce**
1. Go to 'https://staging.giveth.io/user/0xcd192b61a8dd586a97592555c1f5709e032f2505''
3. see Gitgoin Passport 

**Expected behavior**
Gitgoin passport shouldn't be shown in this page and it should be shown only in owner view

<img width="1400" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/273b95c4-76b1-4566-a798-9e871e78a760">

**Comment by jainkrati** [comment]
@MohammadPCh coudl you pls take this up

**Comment by MohammadPCh** [comment]
@maryjaf Could you please test this? Thanks.

**Comment by maryjaf** [comment]
This problem has been resolved
