### ISSUE TITLE
Interactive project score on create/edit page

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3729]
In addition to #3465 we will also have a sticky modal underneath that is an interactive score for the user to see the quality of their project and tips on how to improve their "project score"

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/280fd945-e17c-4368-88ef-b5a12c1c8bc4)
 
the score is based on the presence or lack of certain information in the input fields, it is purely a front-end check, nothing is saved to the back-end or taken from the back-end to calculate project score.

In this lower section of the modal the user can toggle to see a bullet list of ways to improve their project - this is the missing pieces of information that would improve their score if they added, this is also taken from the front-end and changes depending on information added/missing. 

Here is the criteria, for each section, the amount of score "points" it is worth and the associated bullet point text shown underneath the toggle if the given criteria is not met: 

## Description
criteria: project description is GREATER THAN 1200 characters
score points: 51 
modal text: 
 > The project description is way too short, use at least 1200 characters to describe your project.

## Description Images
criteria: project description contains 1 media image/video
score points: 8
modal text:
> Adding media such as photos or videos relevant to your project helps donors visualize the work you're doing.

## Social Media Links 
requires #3466 
criteria: provides at least 1 social media platform link
score points: 12
> Add social media links to help donors connect with you and follow your activity.

## Categories
criteria: check off at least 1 category 
score points: 7
> Ensure donors understand your project's purpose by picking at least one category.

## Location 
criteria: add a location to the project  OR select it has a global impact
score points: 7
> Define the location where this project is creating impact.  

## Custom banner image
criteria: upload a custom banner image
score points: 15
> Add a custom banner image to make your project stand out on Giveth.

## Colors: 
0-49 RED
51 - 79 YELLOW
80 - 100 green

## modals/warning

- If the score is below 50 we do not let the user publish their project (we don't let them anyway because the project description minimum limit) we show a hover tool tip

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/daa3c931-f096-4ce8-856d-b5d6f8076180)

- If the score is between 51-79 we show a modal warning them and suggesting to improve their score - however they can proceed in publishing and previewing their project. 
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/667d5dce-514f-4b33-9176-fc205fcb7bdb)

# Social Media Links Feature
While we can't handle this case until the feature has been built (which might require BE work so progress could be slow..)
we can remove it for now and adjust the scores as follow:

- Description: 51
- Desc images: 12
- Categories : 9
- Location: 9
- Custom banner image: 19

**Comment by divine-comedian** [comment]
@jainkrati  - Do we want to pass this one to another developer?

**Comment by MohammadPCh** [comment]
@divine-comedian Could you please confirm these copies:
```js

// Bar desc and dropdown label
export const infoMap = {
	[EScoreState.LOW]: {
		mainTip:
			'Your project score is too low to publish, you need at least a score of 50 to proceed.',
		title: 'Why is it low?',
		scoreColor: semanticColors.punch[500],
	},
	[EScoreState.MEDIUM]: {
		mainTip:
			'You can still publish your project but it might prevent you to receive the donation your are looking for.',
		title: 'Why is it low?',
		scoreColor: semanticColors.golden[500],
	},
	[EScoreState.HIGH]: {
		mainTip:
			'Just keep in mind to regularly update your project to keep donation coming your way.',
		title: 'What else you can do?',
		scoreColor: semanticColors.jade[400],
	},
	[EScoreState.PERFECT]: {
		mainTip:
			'A perfect score! Just keep in mind to regularly update your project to keep donation coming your way.',
		title: '',
		scoreColor: semanticColors.jade[500],
	},
};

/// Dropdown items:
const tipMap = {
	[EScoreType.DESCRIPTION]:
		'The project description is way too short, add at least 1200 characters to your description.',
	[EScoreType.DESC_IMAGE]:
		'Add an image to your description to make it more appealing.',
	[EScoreType.CATEGORIES]:
		'You need to select at least one category to proceed.',
	[EScoreType.LOCATION]:
		'Add location to your project to make it more appealing.',
	[EScoreType.IMAGE]:
		'Add a custom banner to your project to make it more appealing.',
};
```

**Comment by divine-comedian** [comment]
use this one @MohammadPCh 

```
// Bar desc and dropdown label
export const infoMap = {
	[EScoreState.LOW]: {
		mainTip:
			'Your project score is too low to publish, you need at least a score of 50 to proceed.',
		title: 'Why is it low?',
		scoreColor: semanticColors.punch[500],
	},
	[EScoreState.MEDIUM]: {
		mainTip:
			'You can still publish your project but try increasing your score to make your project more attractive to donors.',
		title: 'Why is it low?',
		scoreColor: semanticColors.golden[500],
	},
	[EScoreState.HIGH]: {
		mainTip:
			'Great score! Just keep in mind to regularly update your project to keep donations coming your way.',
		title: 'What else you can do?',
		scoreColor: semanticColors.jade[400],
	},
	[EScoreState.PERFECT]: {
		mainTip:
			'A perfect score! Just keep in mind to regularly update your project to keep donations coming your way.',
		title: '',
		scoreColor: semanticColors.jade[500],
	},
};

/// Dropdown items:
const tipMap = {
	[EScoreType.DESCRIPTION]:
		'The project description is way too short, use at least 1200 characters to describe your project.',
	[EScoreType.DESC_IMAGE]:
		'Adding media such as photos or videos relevant to your project helps donors visualize the work you're doing.',
	[EScoreType.CATEGORIES]:
		'Ensure donors understand your project's purpose by picking at least one category.',
	[EScoreType.LOCATION]:
		'Define the location where this project is creating impact.',
	[EScoreType.IMAGE]:
		'Add a custom banner image to make your project stand out on Giveth.',
};
```

**Comment by MohammadPCh** [comment]
@divine-comedian Thanks

**Comment by MohammadPCh** [comment]
@maryjaf could you please test it? Thanks

**Comment by maryjaf** [comment]
This change does not exist on STG, please take a look  @MohammadPCh

**Comment by maryjaf** [comment]
> This change does not exist on STG, please take a look @MohammadPCh

The problem has been resolved, flag has been enabled by alireza

**Comment by maryjaf** [comment]
There is a problem in showing "Your Project Score" box, please take a look @MohammadPCh 

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/cc6446e3-081d-44e6-9e0d-63b8ac9941dd

**Comment by maryjaf** [comment]
2- 
I think the "Low Project Score" modal shouldn't be shown by tapping on preview button, am I right? @divine-comedian 

<img width="1229" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/d54255c5-df89-4edf-8ab9-b26dd316d23a">

**Comment by maryjaf** [comment]
3- Score point of Description Images is 12, but in description it is set 8

**Comment by divine-comedian** [comment]
To clarify MJs point the current scoring should be as mentioned here: 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/3731448e-61d9-4bd6-9fed-d55c82de6e16)


@maryjaf - yes assuming the project cannot directly publish from preview, that they must go back to the edit page,  they should not receive that warning when clicking preview - only publish

**Comment by maryjaf** [comment]
> they should not receive that warning when clicking preview - only publish

Thanks @divine-comedian 
So only item 1 should be resolved @MohammadPCh 
and Item 4 should be tested when this field be added in create project page

**Comment by MohammadPCh** [comment]
@maryjaf I think it's our design problem and we need to improve the design :(

**Comment by maryjaf** [comment]
> @maryjaf I think it's our design problem and we need to improve the design :(

@divine-comedian

**Comment by divine-comedian** [comment]
Yes, the modals are too big so our regular and responsive design needs to be changed on this one - @mosaeedi can you please take a look at this. 

> 1- There is a problem in showing "Your Project Score" box, please take a look @MohammadPCh
> 
>  Screen.Recording.2024-02-27.at.3.37.38.PM.mov

**Comment by mosaeedi** [comment]
There are some design adjustments and responsive fixes I need to make.
Please hold this issue a bit, I'll share them by tomorrow.
CC: @divine-comedian

**Comment by maryjaf** [comment]
> > they should not receive that warning when clicking preview - only publish
> 
> Thanks @divine-comedian So only item 1 & 2 should be resolved @MohammadPCh and Item 4 should be tested when this field be added in create project page

**Comment by divine-comedian** [comment]
> There are some design adjustments and responsive fixes I need to make. Please hold this issue a bit, I'll share them by tomorrow. CC: @divine-comedian

@mosaeedi - Do you have these updates?

**Comment by mosaeedi** [comment]
Hey @divine-comedian I've asked @MohammadPCh to make some change to the way we detect each input group to show the related hints
When the user mouse enters each section, the related hint is presented. it shows the related info until the user mouse goes to the other sections. it won't change the hint based on user's scroll

<img width="460" alt="Screenshot 2024-03-03 at 5 24 18 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/8d8202f2-f37f-4271-a1ff-6e9d4c77d8b1">
_Just for clarification: red areas are presenting each section_

**Comment by divine-comedian** [comment]
@mosaeedi - also there is an issue with the tips + the score modals not fitting on the view screen, cutting off the bottom part of the score components as MJ demonstrated in the video. 

Is this resolved as well?

**Comment by mosaeedi** [comment]
@divine-comedian Please let me know what you think!

**Comment by divine-comedian** [comment]
I like this! 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/3b3c8ef9-891f-4658-9626-029f7915bb49)


but instead of a new modal can we make it a hover dropdown that includes the associated text & tips 

as you suggested when the bar score is GREEN - we can say "Further Improvements" and have the drop down with the remaining tips 

on score 100/100 - the text changes to Perfect Score!  we keep the dropdown menu and the only tip is the reminder for them to update their project regularly - I think the copy is also provided somewhere on the figma for that

---
Regarding the Publish & Preview - lets not make any changes to this since it has lots of dependent validations - this could make quite a bit of extra work for devs.

**Comment by maryjaf** [comment]
> ## Regarding the score module below the hint module**
> <img alt="Screenshot 2024-03-03 at 5 32 29 PM" width="1358" src="https://private-user-images.githubusercontent.com/13708322/309555337-9a94fdf0-de74-4366-98e1-9e74a6bf6c89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNTI2NTYsIm5iZiI6MTcxMTM1MjM1NiwicGF0aCI6Ii8xMzcwODMyMi8zMDk1NTUzMzctOWE5NGZkZjAtZGU3NC00MzY2LTk4ZTEtOWU3NGE2YmY2Yzg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDA3MzkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlNjliODQ3ZmQzY2M1MWU2ZDY3NDJhMDE1YjkzMTgzNzk1MmRmM2VmZjliZDlmZDFkMzVlMjdhYTA1ZTMyYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mje4GhNVf_DMDluFzHfTwNtv0pEE1gfomgmonDnFCBg">
> On small or medium screens (Tried on 14 and 13 inch Macbooks ) it's almost impossible to see the score module! I've discussed different solution with Cherik regarding the feasibility and being UX-friendly I propose to put the score module in the header.
> 
> ### Before getting to the solution, please look at this heat map generated by PostHog.
> 1. There aren't any interactions with the wallet and notification menu,
> 2. the Create a Project button in the Create Project form is the most unnecessary thing we need.
> 
> <img alt="Screenshot 2024-03-03 at 5 35 02 PM" width="1512" src="https://private-user-images.githubusercontent.com/13708322/309555552-3e5869db-c89c-4d68-a65b-d16afc28286b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNTI2NTYsIm5iZiI6MTcxMTM1MjM1NiwicGF0aCI6Ii8xMzcwODMyMi8zMDk1NTU1NTItM2U1ODY5ZGItYzg5Yy00ZDY4LWE2NWItZDE2YWZjMjgyODZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDA3MzkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4NjViMDAxOTVkZWQ3NTAyMTdhYWY3MzAzODBmYzVjMzUyYmNlYWExNGRmODJkZmUyNTM2MjIzNDJiNmJlNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._hrKylmC0k_ANJXE0DERkmGieAf8g8KsvL3uhT7MMGI">
> ## The solution
> So here is how it could look like to put the score module in the header,
> 
> <img alt="Screenshot 2024-03-03 at 5 38 38 PM" width="1213" src="https://private-user-images.githubusercontent.com/13708322/309555785-7681ee97-f19a-4995-b5f2-4282bcfa5f6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNTI2NTYsIm5iZiI6MTcxMTM1MjM1NiwicGF0aCI6Ii8xMzcwODMyMi8zMDk1NTU3ODUtNzY4MWVlOTctZjE5YS00OTk1LWI1ZjItNDI4MmJjZmE1ZjZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDA3MzkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlNzA2YWMzNTk5MDk5MWUyMjNiZTA5NWNmODA0YzNlYzFiYTVhNzdmNWNjNGNlMjg4NThhZWFiNDE5NzBlZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x8NfzjHSvTRUNR1uNsR6KOh85RI3_0khx3NXIAgp4nY"> <img alt="Screenshot 2024-03-03 at 5 38 52 PM" width="674" src="https://private-user-images.githubusercontent.com/13708322/309555798-e5bf11ce-d8da-4c15-a8c2-e4f6092523f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNTI2NTYsIm5iZiI6MTcxMTM1MjM1NiwicGF0aCI6Ii8xMzcwODMyMi8zMDk1NTU3OTgtZTViZjExY2UtZDhkYS00YzE1LWE4YzItZTRmNjA5MjUyM2YwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDA3MzkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliYWRiNWFjZmRjM2QyYjQwMmEyNmM0OGUwNzUyZmM4NWNhY2EyMTUzMjVhNmY2MzBhZDM0NjEwODE4NzAxNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZV8HSNUWycXRj62F3IzIZ5R8eYtPt8dZxAaNKddPx7U">
> In this version the score module is always in sight and the user can instantly see the score after each change! and the **Why Is It Low** button can show the modal below to let the user know what's the issue or in case the project score is higher than 60, it can show some extra hints to increase it even more. When it's 100, we can just disable the button and change its copy to something like **Great Job**
> 
> <img alt="Screenshot 2024-03-03 at 5 44 55 PM" width="540" src="https://private-user-images.githubusercontent.com/13708322/309556147-0b77afc6-9c7e-4972-981b-01c950d0f169.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNTI2NTYsIm5iZiI6MTcxMTM1MjM1NiwicGF0aCI6Ii8xMzcwODMyMi8zMDk1NTYxNDctMGI3N2FmYzYtOWM3ZS00OTcyLTk4MWItMDFjOTUwZDBmMTY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDA3MzkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyNmQwODFmOTQ1NzFhMjkzZTNlN2M4NTY2NjQzNWM5NjRkZGJiYWJiYzc4MGY4ZDAzNDU2ZDcxNGY0ODYwYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z0N26EVSw9LVtfk2u02zddGF-PLtXwWNeYQfLKQIQv4"> <img alt="Screenshot 2024-03-03 at 5 45 53 PM" width="754" src="https://private-user-images.githubusercontent.com/13708322/309556223-0713be09-27a8-487c-8792-ab7af716a171.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNTI2NTYsIm5iZiI6MTcxMTM1MjM1NiwicGF0aCI6Ii8xMzcwODMyMi8zMDk1NTYyMjMtMDcxM2JlMDktMjdhOC00ODdjLTg3OTItYWI3YWY3MTZhMTcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDA3MzkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzNmFjMmJjZDJhNGUyNTU0ZjM2OGE0NzAzNDZmNTZmY2JkZmRkZGY4ODI2ZDgxMGZlYTNlMzA5MThlMzE2NTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yQTLhg8lyrQlgBUx2jSwKmGVWUif6E7gL55rsqoTACw">
> ## Here is a bit more improvement
> Right now, the preview and publish buttons are at the end of the page, we can also move them to the header to better user the space in the header and make life easier for project owners.
> 
> <img alt="Screenshot 2024-03-03 at 5 48 44 PM" width="1018" src="https://private-user-images.githubusercontent.com/13708322/309556384-339e7b36-e1c6-4b8d-9f6e-d693036c0106.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNTI2NTYsIm5iZiI6MTcxMTM1MjM1NiwicGF0aCI6Ii8xMzcwODMyMi8zMDk1NTYzODQtMzM5ZTdiMzYtZTFjNi00YjhkLTlmNmUtZDY5MzAzNmMwMTA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDA3MzkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkZjliZWViMzcyYzE3YjZjMWNmNzA3ZGZlZDIwZWQ2YTQ3ODg4OGQ4ZWM5Mzg0MzU1ZWMyZTRjMzM5ODEwNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ry8iiEiIiQNiOEMO6BGPtFwa0aYoo4TW2_JOCbHcXag">
> In this version, user can click on the **Preview and Publish** drop-down to get to the button, and right from here, we can handle all the different copies related to the score module.
> 
> <img alt="Screenshot 2024-03-03 at 5 49 23 PM" width="833" src="https://private-user-images.githubusercontent.com/13708322/309556521-8ccbc1a6-c3a3-4654-bc24-5b2194f3b712.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNTI2NTYsIm5iZiI6MTcxMTM1MjM1NiwicGF0aCI6Ii8xMzcwODMyMi8zMDk1NTY1MjEtOGNjYmMxYTYtYzNhMy00NjU0LWJjMjQtNWIyMTk0ZjNiNzEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDA3MzkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxM2U5ZDU3MjAxM2RkYzdiNTllOWM3ZDc3ZjkyNzIzYTNmMTRiOTM2MGVlZGUzMDFjOWNmN2UzNjQwNTE0NmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BdY_b52v1eSzq22orYiFvmm4Rf9helXJImeQ7umH8bk"> <img alt="Screenshot 2024-03-03 at 5 52 28 PM" width="807" src="https://private-user-images.githubusercontent.com/13708322/309556617-4ac68461-5727-4313-8911-55163803f4fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNTI2NTYsIm5iZiI6MTcxMTM1MjM1NiwicGF0aCI6Ii8xMzcwODMyMi8zMDk1NTY2MTctNGFjNjg0NjEtNTcyNy00MzEzLTg5MTEtNTUxNjM4MDNmNGZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDA3MzkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlNjQxOTNmNDM5NGFmOTVhMzE1MjVkZThmYmE0NzhiMTVmYmIwNTk5ZWJlOTUyNTdjZjYzNDVkMjA5YTBjNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Hk4-qOkKCCcD--7Kbak2N6YMD6TXNYFXnyO0xvfclLM">

Since the new design should be implemented, I've moved it to inprogress

**Comment by jainkrati** [comment]
@alireza-sharifpour

**Comment by alireza-sharifpour** [comment]
Can someone send me the figma link of the new design? @divine-comedian @mosaeedi

**Comment by jainkrati** [comment]
@MoeNick pls share figma link

**Comment by MoeNick** [comment]
https://www.figma.com/file/vMiyVd1Ly5LjgSyZrChVV8/Giveth-users?type=design&node-id=1675-12234&mode=design&t=QXekrKKb4SlLJOj7-4
@alireza-sharifpour pls scroll left on this file, if you can't find it, please let me know.

**Comment by mosaeedi** [comment]
We started to work on the project structure and user flow here -> [Figma link](https://www.figma.com/file/QBvhJZY3C93a8NKqcMnEHX/DeVouch?type=design&node-id=6117-459&mode=design&t=v8LXI2yNDyRuuc9a-4)


### Please Note
These are just wireframes and are not ready to hand over to DEV!
**Everything in this file might change at any time.**
When the design is ready we will flag them for Devs to start working on them.

**Comment by alireza-sharifpour** [comment]
CC: @jainkrati

**Comment by laurenluz** [comment]
can you link in the figma or share a screenshot of what the rest of the social media section looks like?

**Comment by MohammadPCh** [comment]
I don't have the old Figma link, maybe @mosaeedi @Tosinolawale  can send it here.

**Comment by MoeNick** [comment]
> https://www.figma.com/file/vMiyVd1Ly5LjgSyZrChVV8/Giveth-users?type=design&node-id=1675-12234&mode=design&t=QXekrKKb4SlLJOj7-4 @alireza-sharifpour pls scroll left on this file, if you can't find it, please let me know.

I put the link before, here you are: 
https://www.figma.com/file/vMiyVd1Ly5LjgSyZrChVV8/Giveth-users?type=design&node-id=1675-12234&mode=design&t=tB4ju8codiVyvaVf-4

@MohammadPCh Do you till need help? there are all the tips there.

**Comment by MohammadPCh** [comment]
@MoeNick, thank you for adding the link. @laurenluz, you can view all the other tips there.
Yes, @MoeNick, as you can see, there are currently no tips for social media.

**Comment by MohammadPCh** [comment]
I created a new Issue for tips because it's not related to score directly and @maryjaf can start testing this.

**Comment by MohammadPCh** [comment]
@maryjaf ready to test.

**Comment by maryjaf** [comment]
Thanks @MohammadPCh the tests of this issue has been passed

**Comment by MohammadPCh** [comment]
@maryjaf It's the time that the rich text is initializing and not easy to fix, but it's about ~1 second. I can show calculation instead.

**Comment by MohammadPCh** [comment]
@maryjaf we check the description validation every one second. so it's ok to see wrong score about 1 sec.

**Comment by maryjaf** [comment]
So I move this issue to Done @divine-comedian @MohammadPCh

**Comment by divine-comedian** [comment]
LGTM - on my browser it showed 0 on load and refresh
