### ISSUE TITLE
Add link for users to flag a project via a Typeform

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3741]
From the stewards call today:

We should add in a simple feature allowing users to flag a project if they believe it violates Giveth's terms of service or covenant. 

While we had talked about a complex feature that would require a lot of back-end effort we can for now create a typeform which links up to a webhook in our discord via zapier. 

We add the link to this typeform somewhere on the project details page 

@Tosinolawale - could you draft a link/icon that we could place for this flag feature on the project details page? 

cc: @laurenluz @MoeNick

**Comment by laurenluz** [comment]
I made an issue for this earlier, some info in there. Should have tagged you @divine-comedian sorry - https://github.com/Giveth/giveth-planning/issues/1731

**Comment by mosaeedi** [comment]
We had this **Report an issue** link down here in some design revisions. I think it's okay to use it.

<img width="804" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3hZQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f6894eba3a76bc39ab3c0b614fce8d14663dfeda/Screenshot%202024-02-14%20at%203.05.54%E2%80%AFPM.png" alt="Screenshot 2024-02-14 at 3.05.54 PM.png" />

**Comment by MoeNick** [comment]
Shall I close it @divine-comedian ?
