### ISSUE TITLE
Archived QF round summary page & link on the main QF page

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3748]
This is coming from #3674 

After a QF round has ended, we want to preserve info about the banner, round dates, stats, projects in the round, etc and give it a unique slug. I think this is already somehow built, @MohammadPCh was working on it.

What we need new is some "homepage" where you can see a list of all archived rounds & their corresponding links.

And, somewhere on the main giveth.io/qf page that links to "See Archived round"... This link should not be super prominant.

Does that cover everything @MohammadPCh ?

@Tosinolawale are you able to help w/ this?

**Comment by Tosinolawale** [comment]
> This is coming from #3674
> 
> After a QF round has ended, we want to preserve info about the banner, round dates, stats, projects in the round, etc and give it a unique slug. I think this is already somehow built, @MohammadPCh was working on it.
> 
> What we need new is some "homepage" where you can see a list of all archived rounds & their corresponding links.
> 
> And, somewhere on the main giveth.io/qf page that links to "See Archived round"... This link should not be super prominant.
> 
> Does that cover everything @MohammadPCh ?
> 
> @Tosinolawale are you able to help w/ this?

On it

**Comment by Tosinolawale** [comment]
https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=5314%3A41254&mode=design&t=ytJobwoYBPPwiZWP-1
![Projects list -](https://github.com/Giveth/giveth-dapps-v2/assets/35389241/c9d61d51-87ea-4dd9-8c69-78a1e351b870)

https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=5506%3A50281&mode=design&t=ytJobwoYBPPwiZWP-1

![Projects list - Archived](https://github.com/Giveth/giveth-dapps-v2/assets/35389241/2f39af2d-46ce-49a8-8162-c399bab388f3)
@laurenluz

**Comment by laurenluz** [comment]
ok Thanks @Tosinolawale - all set.

The most up-to-date version is in [figma](https://www.figma.com/file/C3HykACu0eNImhAqu0our8/Giveth-projects?type=design&node-id=5506-50281&mode=design&t=XKbirHUC0Nkem5PG-4):
![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/6fb81043-690e-4101-80c7-ecd60f3559dd)

@MohammadPCh would love your feedback - think this will work ok?

cc @jainkrati

**Comment by MohammadPCh** [comment]
@laurenluz @Tosinolawale Great design! I have a small suggestion:
Since we have a dedicated page for this at https://giveth.io/qf-archive, we can remove the tabs on top.
Additionally, we'll need the backend API for fetching this information.

**Comment by laurenluz** [comment]
this is the issue for adding banners to the backend cooresponding to QF rounds: https://github.com/Giveth/giveth-dapps-v2/issues/3665 cc @jainkrati @mohammadranjbarz @MohammadPCh

**Comment by laurenluz** [comment]
@MohammadPCh I think the tabs are kind of nice... then we could just have giveth.io/qf go to this page, default view showing the active round... and then if you click the archive tab, you get to /qf-archive where it shows you all the past/ended rounds.

**Comment by laurenluz** [comment]
this will work well if we end up expaning qf to run multiple rounds at once.. because then the active round tab can look similar to the archive tab... but be a homepage for different active rounds.

**Comment by maryjaf** [comment]
It seems this issue isn't ready for testing and is in a wrong state in the board , am I right? @MohammadPCh

**Comment by MohammadPCh** [comment]
@maryjaf It's on progress.

**Comment by MohammadPCh** [comment]
@laurenluz  Could you please confirm whether the design meets your requirements? I'm eager to begin working on it.

**Comment by laurenluz** [comment]
Hey @MohammadPCh! The design looks good, I changed some copy and made a small comment about removing "Default" as sort option.... but aside from that, it's good to go!

**Comment by MohammadPCh** [comment]
Hey @mohammadranjbarz,

We require this information to be fetched from the backend. Could you please provide it?

We need to retrieve all ended (archived) QF rounds with the following details:

1. Slug
2. Name
3. Matching pool
4. Total donations amount
5. Unique donors
6. Start date
7. End date

Additionally, we need to sort them by the following criteria:

- Matching pool
- Number of unique donors
- Newest
- Oldest

Thank you.
<img width="1214" alt="Screenshot 2024-04-09 at 1 58 29 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/17097576/e10c50cd-7688-4192-96b6-640341d37d9d">
cc: @laurenluz @jainkrati

**Comment by jainkrati** [comment]
@mohammadranjbarz if your PR has all data, lets merge it else pls assign to @CarlosQ96 to proceed on this

**Comment by jainkrati** [comment]
@CarlosQ96 pls build on the PR by @mohammadranjbarz linked above.

**Comment by RamRamez** [comment]
The new query for fetching archived QF rounds is ready:

```
  
export const fetchQFArchivedRounds = `
  query (
   $limit: Int
   $skip: Int
   $orderBy: QfArchivedRoundsOrderBy
  ) {
    qfArchivedRounds(
      limit: $limit
      skip: $skip
      orderBy: $orderBy
    ) {
      id
      name
      slug
      isActive
      allocatedFund
      eligibleNetworks
      beginDate
      endDate
      totalDonations
      uniqueDonors
    }
  }
`;


export enum QfArchivedRoundsSortType {
  allocatedFund = 'allocatedFund',
  totalDonations = 'totalDonations',
  uniqueDonors = 'uniqueDonors',
  beginDate = 'beginDate',
}

export enum OrderDirection {
  ASC = 'ASC',
  DESC = 'DESC',
}

```

**Comment by jainkrati** [comment]
@MohammadPCh since you have a draft PR, pls take this up . BE is ready

**Comment by MohammadPCh** [comment]
This is the final result:
<img width="1376" alt="Screenshot 2024-05-12 at 10 30 12 AM" src="https://github.com/Giveth/giveth-dapps-v2/assets/17097576/630caa8d-820d-4d9c-afd9-bc7aa34d048a">
@laurenluz, should we display the dollar sign next to the "Matching Pool"? I remember that the matching pool may have a different unit.
I attempted to retrieve the `allocatedTokenSymbol` from the backend, but this query doesn't support it.
cc: @jainkrati @RamRamez

**Comment by RamRamez** [comment]
@MohammadPCh I added `allocatedFundUSD` and `allocatedTokenSymbol` to the query:

```
  query (
   $limit: Int
   $skip: Int
   $orderBy: QfArchivedRoundsOrderBy
  ) {
    qfArchivedRounds(
      limit: $limit
      skip: $skip
      orderBy: $orderBy
    ) {
      id
      name
      slug
      isActive
      allocatedFund
      allocatedFundUSD
      allocatedTokenSymbol
      eligibleNetworks
      beginDate
      endDate
      totalDonations
      uniqueDonors
    }
  }

```

**Comment by RamRamez** [comment]
@laurenluz you can fill the `allocatedFundUSD` and `allocatedTokenSymbol` fields for all archived QF rounds from AdminJS. If you like to show USD value of allocated fund for archived QF rounds, you can fill only allocatedFundUSD and if you want to show the token amount allocated, you can only fill allocatedTokenSymbol field.

**Comment by MohammadPCh** [comment]
@RamRamez Thanks

**Comment by MohammadPCh** [comment]
@RamRamez Thanks

**Comment by laurenluz** [comment]
@maryjaf - when you test this, can you also check to make sure that things look right and make sense when there is NO active QF round? 

We should basically have some simple "there is no active round" and the regular, quadratic funnding generic banner in this case.

related: https://github.com/Giveth/giveth-dapps-v2/issues/3748

**Comment by maryjaf** [comment]
- [ ] 1-The mid page QF banner should be shown in the page of archived QF? @laurenluz 
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/958979d9-b7e5-41fc-90ce-7b4867b88cf4)



- [ ] 2-"Load more" button isn't shown and all of archived qf round in stg aren't shown in this page 

- [ ] 3- What is the order of displaying the archived rounds in this list? 

- [ ] 4- I see some kind of irregularity in the columns of this table, do you think the same? 
@MohammadPCh 
**STG:**
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/adfb9441-19d7-4d27-92b3-1bbbbc822434)
**PRODUCTION**
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/c29b28d9-4fb7-4e3b-bad2-181c543b950a)

**Comment by maryjaf** [comment]
> @maryjaf - when you test this, can you also check to make sure that things look right and make sense when there is NO active QF round?
> 
> We should basically have some simple "there is no active round" and the regular, quadratic funnding generic banner in this case.
There are lots of archive rounds on stg and I think removing all of them from db maybe isn't a good idea because we need this data in our test 
@MohammadPCh Do you have implemented a design for this case ? and do you think it could be able to tested

**Comment by laurenluz** [comment]
I sent @MohammadPCh updated copy for the mid-page banner text:

Archived QF Rounds
Explore past quadratic funding rounds on Giveth! Check out the projects who participated, matching funds, donations and more info on this page.

Re:
> There are lots of archive rounds on stg and I think removing all of them from db is the only way and isn't a good idea because we need this data in our test
@MohammadPCh Have you implemented a design for this case ? and do you think it could be able to tested ?

Maybe there is some confusion? I wasn't suggesting that we remove any archived rounds. Just, when there is not a round that is currently open & live, the "active round" tab... which should be the default for giveth.io/qf...

I think it is not clear & there is not clear design, I will work with @Tosinolawale on it asap.

**Comment by laurenluz** [comment]
@MohammadPCh can you confirm also where you are getting the value "unique donors"? because this shouldn't be just unique addresses, but should be, effectively:
- donors who had a passport score above the threshold
- donors whose donations were within an active QF round, to a QF project, on an eligible for QF chain
- donors who are not "flagged as sybil for the round" (in our backend, set in admin bro)

- [ ] Also we should have some setting in admin bro where we can mark if a round is completed or not... if the round is not complete, the unique donors should say "pending" cc @CarlosQ96

- [ ] Finally, can we change the copy "Total Donations" to say just "Donations (USD value)"

**Comment by laurenluz** [comment]
working on fixing the /qf homepage design & edge cases in here: https://github.com/Giveth/giveth-dapps-v2/issues/4171

**Comment by MohammadPCh** [comment]
@laurenluz @maryjaf Thanks, guys!
I have updated it. 
@laurenluz, regarding the `unique donors`, I fetched the data from the back-end, so @mohammadranjbarz or @CarlosQ96 can help us with that.
I also made a modification to the table on my own and merge start and end date columns (sorry 😢, but I thought it was necessary):
<img width="1276" alt="Screenshot 2024-05-26 at 3 25 27 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/17097576/e1c20488-b11b-4348-8afe-6225eed4bc3b">

**Comment by maryjaf** [comment]
> * 2-"Load more" button isn't shown and all of archived qf round in stg aren't shown in this page
> * 3- I see some kind of irregularity in the columns of this table, do you think the same?

Thanks @MohammadPCh These 2 items have been resolved.

This item remains @laurenluz @MohammadPCh 
> * [ ]  1-Should the mid page QF banner be shown in the page of archived QF? @laurenluz

**Comment by maryjaf** [comment]
> * Also we should have some setting in admin bro where we can mark if a round is completed or not... if the round is not complete, the unique donors should say "pending" cc @CarlosQ96


> @MohammadPCh can you confirm also where you are getting the value "unique donors"? because this shouldn't be just unique addresses, but should be, effectively:
> 
> * donors who had a passport score above the threshold
> * donors whose donations were within an active QF round, to a QF project, on an eligible for QF chain
> * donors who are not "flagged as sybil for the round" (in our backend, set in admin bro)
> * [ ]  Also we should have some setting in admin bro where we can mark if a round is completed or not... if the round is not complete, the unique donors should say "pending" cc @CarlosQ96

I move it back to inprogress to be checked @CarlosQ96 @mohammadranjbarz

**Comment by laurenluz** [comment]
re: mid-page banner

in this issue https://github.com/Giveth/giveth-dapps-v2/issues/4171 I put the copy for the banner assuming it exists! but if we want to remove it, it's also ok with me. whatever is the least work 😅 

re: "unique donors" number

@CarlosQ96 told me that this number is *just* the number of unique addresses that donated in the round. it is not considering passport score or flagged sybils or other information. I think, to not further block this issue... we can leave it as-is.

I'll create a new issue for making a new type of "unique donor" variable for each round in our backend, and once we get to building that, we can update this here... but for now, I think this doesn't need to be a blocker and we can just move forward with the simple "unique donors aka unique addresses who donated in the round" thing.

**Comment by laurenluz** [comment]
@maryjaf if we exclude those edge cases/improvements, is this issue all ok then?

**Comment by maryjaf** [comment]
> * 1-Should the mid page QF banner be shown in the page of archived QF? @laurenluz
> * @maryjaf if we exclude those edge cases/improvements, is this issue all ok then?

Yeah, all open problems have been fixed, but we have one question about "mid page QF banner "
Should the mid page QF banner be shown in the page of archived QF? @laurenluz

**Comment by laurenluz** [comment]
we can remove the mid-page banner

**Comment by jainkrati** [comment]
@Meriem-BM pls continue on this with guidance from @MohammadPCh

**Comment by Meriem-BM** [comment]
Hey @maryjaf, the mid banner is removed now

**Comment by maryjaf** [comment]
> Hey @maryjaf, the mid banner is removed now

Thanks, this problem has been fixed
