### ISSUE TITLE
Update QF round banner for meta pool QF round

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3749]
We need to update the banner on giveth.io/qf to be the one for metapool,

[Link to figma](https://www.figma.com/file/W9Ace1RyCdykWM72fsSa3t/Giveth-Marketing-2024?type=design&node-id=6032-582&mode=design&t=kA8xTQmlbwDGNvM6-4)

End result should be:
<img width="840" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEJXQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5dc2f1d9f216e6e98847128e5625f8e8990d8518/image.png" alt="image.png" />

Here are the svg filles:

background:
<img width="355" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGhXQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c73864e98712e415c332c1cbd949183e830db166/asia.svg" alt="asia.svg" />
<img width="840" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGxXQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--774b4e2a1e0efce185d4637c42a5706f2e22436d/background.svg" alt="background.svg" />
[bottom left.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHBXQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c03c2cc9a8e59bbe2ad508433060ae91dcabef4f/bottom%20left.zip)
<img width="84" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHRXQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a492039f8e55cf00f66d80e44cca83a0d47fd6b9/bottom%20right.svg" alt="bottom right.svg" />
<img width="56" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDVXQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--19e0aad795f046bdd20cd5a1abe9d1a1a9359bd9/metapool%20logo.svg" alt="metapool logo.svg" />
<img width="232" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDlXQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--07cdb51304f0de443ac2340679c463d17ba142a1/metapool%20words.svg" alt="metapool words.svg" />
<img width="124" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUJXQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c4e33459761f4c9ebb562592e2276913d0ddacff/top%20left.svg" alt="top left.svg" />
[top right.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUZXQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d9a877cc413b0532bf7383d719b8a3e8cffcf80a/top%20right.zip)
<img width="88" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNU5XQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0cb30495ce1eac5a90c1c70465b3cdba53a29997/top%20middle.svg" alt="top middle.svg" />

idk if those svgs work for us, but I remember having quality issues before w/ the pngs

@jainkrati can you get someone on this ASAP. I need it on prod by latest Friday for the meta pool round.

**Comment by jainkrati** [comment]
@maryjaf pls test by tomororw

**Comment by maryjaf** [comment]
The previous banner is shown on stg 

<img width="1355" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/4022e224-6fa4-43c9-bbc5-cd6528087d27">

**Comment by MohammadPCh** [comment]
@maryjaf, the PR has not been merged yet. you can check it on its preview link.

**Comment by jainkrati** [comment]
Just now merged the PR. @maryjaf can you pls test

**Comment by maryjaf** [comment]
<img width="1303" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/703581c3-c7a9-4673-8d0b-9321b7d1ae7a">
