### ISSUE TITLE
Edit mid page QF round copy for meta pool round

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3750]
<img width="1388" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVpXQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f624624d388d3c59546c2750f786d8d993c6cc9a/image.png" alt="image.png" />

This should say:

Title: Quadratic Funding
Subtext: With QF, the number of donors matters more than the amout donated. Donate to participating projects in the round and get your donations matched with the power of quadratic funding!

@jainkrati need this on prod by Friday

**Comment by MohammadPCh** [comment]
@laurenluz, I'll update it shortly. However, I believe it might be better to address this on the dashboard as well.
cc: @jainkrati

**Comment by jainkrati** [comment]
@maryjaf pls test by tomororw

**Comment by laurenluz** [comment]
> @laurenluz, I'll update it shortly. However, I believe it might be better to address this on the dashboard as well.

I agree, I made an issue for it, but it's not complete yet, I believe. https://github.com/Giveth/giveth-dapps-v2/issues/3675

**Comment by maryjaf** [comment]
<img width="1398" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/43927ae2-b170-4d2f-9284-7ce8c3b52c55">
