### ISSUE TITLE
Update matching cap for meta pool round

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3751]
related to #3664 

We need the matching cap for the meta pool round to be 20%.

@jainkrati need this on prod by Friday, and it usually requires both a front & a backend dev.

**Comment by MohammadPCh** [comment]
@laurenluz you can change it from the dashboard(Admin JS) now.

**Comment by maryjaf** [comment]
Thanks @MohammadPCh by changing "Maximum Reward" filed in admin panel for a QF round , correct amount of max estimated matching would be shown in UI

**Comment by jainkrati** [comment]
@MohammadPCh pls take another look. @maryjaf pls test by tomororw

**Comment by maryjaf** [comment]
I completed test of this issue today and everything was ok, Are there any new changes in the code?

**Comment by laurenluz** [comment]
> @laurenluz you can change it from the dashboard(Admin JS) now.
 OH that's great!
 
 @maryjaf - so did you test changing the matching cap % & seeing the different matching caps on staging then?

**Comment by MohammadPCh** [comment]
I'm sure that we get the cap from the backend.

**Comment by maryjaf** [comment]
> > @laurenluz you can change it from the dashboard(Admin JS) now.
> > OH that's great!
> 
> @maryjaf - so did you test changing the matching cap % & seeing the different matching caps on staging then?

 by changing "Maximum Reward" filed in admin panel for a QF round, the below numbers will be changed
 
<img width="584" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/f078a3fe-193e-4e07-8b86-63afde8c0a98">

<img width="1373" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/f0dc2938-3c0c-4d9a-b145-d48255b495d6">
<img width="1362" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/04d93ca1-2430-49ff-8f69-c268095067d4">

**Comment by jainkrati** [comment]
@MohammadPCh coudl you please resolve this on priority. We need to deploy it by Sunday

**Comment by jainkrati** [comment]
@MohammadPCh pls merge the PR if you have ensured that it wont show for solana users. We need to deploy this by sunday

**Comment by MohammadPCh** [comment]
@jainkrati The FE part has been Merged to develop and is ready for release.

**Comment by jainkrati** [comment]
@maryjaf pls test on Metapool round with @laurenluz

**Comment by maryjaf** [comment]
The test of this issue on STG has been successful
After the round starts, we can double check on Metapool round on production

**Comment by maryjaf** [comment]
The cap amount is shown correctly on prod based on new configurable field in admin.
