### ISSUE TITLE
Import csv of "known sybil addresses" & other fraud flags for the polygon QF round

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3752]
This is related to https://github.com/Giveth/impact-graph/issues/1303

In the next days (I hope), I will have a pretty heftly list of sybil attacks that happened in the polygon QF round.

1. We should basically important those "sybil donors" into our db so their donations are excluded when we calculate the matching funds for the round.
2. I will also have a list of project address who have been found to commit fraud in the round and therefore should not get any matching (no donations to them should count).

The 1st part should be easy if that issue 1303 is finished.
The 2nd part is something new we hadn't done before so will need an engineering solution.

I think this might make the most sense for @aminlatifi to take on since he is supposed to help w/ the final data processing for this round, but up to @jainkrati

**Comment by laurenluz** [comment]
I hope also we can have a solution for this this week.

**Comment by laurenluz** [comment]
related to #3713

**Comment by mohammadranjbarz** [comment]
@laurenluz 
For the second option, do we need to permanently mark a project when fraud happens to prevent sending matching fund for them or like sybil thing it would be per round?

**Comment by mohammadranjbarz** [comment]
@maryjaf The first option(import data from csv) is on Staging and you can test it now

**Comment by maryjaf** [comment]
On edit page of sybil, the entered csv data is n't shown @mohammadranjbarz 
https://impact-graph.serve.giveth.io/admin/resources/Sybil/records/4/edit

**Comment by CarlosQ96** [comment]
Should make a table entity similar to sybils, to mark the projects then?

**Comment by laurenluz** [comment]
> @laurenluz
For the second option, do we need to permanently mark a project when fraud happens to prevent sending matching fund for them or like sybil thing it would be per round?

we should have a sybil per round thing.

**Comment by CarlosQ96** [comment]
Yeah @laurenluz I added the sybil per round table. But what about the other fraug flags?

**Comment by laurenluz** [comment]
No that's what I'm saying, they should be per round too.

So if a project is flagged for the round and should have matching funds nullified, we should have it on a separate list as well corresponding to the round.

**Comment by CarlosQ96** [comment]
Ok! Ill add it

**Comment by mohammadranjbarz** [comment]
> On "edit" and " show "page of sybil, the entered csv data is n't shown @mohammadranjbarz https://impact-graph.serve.giveth.io/admin/resources/Sybil/records/4/edit https://impact-graph.serve.giveth.io/admin/resources/Sybil/records/6/show

@maryjaf 
The uploaded CSV should not be shown in the entity show and other things, because we don't have a field for that in DB and it's just a temp input

**Comment by maryjaf** [comment]
For "ProjectFraud" testing I did these steps but I didn't see the expected result, please take a look @CarlosQ96 

- I set this record in "ProjectFraud" menu in admin bro
   round:80 
   projectId:[How many photos is too many photos?](https://impact- graph.serve.giveth.io/admin/resources/Project/records/82/show)
https://impact-graph.serve.giveth.io/admin/resources/ProjectFraud/records/2/show

- I donated to  "How many photos is too many photos"  project in round 80
-by tapping on "Return All Donation data" for round 80, I expected that this donation should not be shown in google sheet but it is shown 

<img width="1391" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/c122f70a-fd82-48d4-a7be-cf3f8fd3c9ef">

**Comment by maryjaf** [comment]
By below config I expect that donation to "how many... " project in round 80 be shown in google sheet
but it hasn't be shown 
it seems there is a problem in updating fraud record, please take a look
<img width="1301" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/83ec3f27-ee9f-4ba9-bafd-753790f5b214">

**Comment by maryjaf** [comment]
Thanks @mohammadranjbarz The problem related to fraud project has been resolved

**Comment by jainkrati** [comment]
@maryjaf pls close it if tested and verfiied
