### ISSUE TITLE
Donations not showing on project page

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#376]
There have been 2 donations made.. however the donations tab on the project page says "It seems this project has not received any donations yet!" https://giveth.io/project/The-Wellness-Bus-0

![image](https://user-images.githubusercontent.com/74267818/160516508-866ab415-08e4-4435-9094-e7ae5ccb7cb0.png)

**Comment by MoeNick** [comment]
@WhyldWanderer are you still havinh this issue? 
Did you make it with an uncompleted profile?

**Comment by WhyldWanderer** [comment]
This isnt my project. This was reported to me by a user. Can you see the donations? I can not see them when I go to the project page and neither can the project owner.

**Comment by MoeNick** [comment]
@mateodaza @CarlosQ96  would you pls take a look to find a route cause?
There were 2 donations and it says no donations yet, the list was empty, I made another, and it shows all.
this is happening in production.
