### ISSUE TITLE
QF round page

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3760]
this is an epic to organize issues related to changing parts of the https://giveth.io/qf

**Comment by jainkrati** [comment]
Unable to see the issues under this in Zenhub

**Comment by laurenluz** [comment]
you don't see any of the issues in this epic?

**Comment by MoeNick** [comment]
@jainkrati if you have Zebhub extension installed you should have the view like this
![image](https://github.com/Giveth/giveth-dapps-v2/assets/80677512/cd2afd9c-ff19-47ff-a576-dee764ca4e7c)
