### ISSUE TITLE
Users reporting bugs in uploading pictures in create projects

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#3779]
<img width="1534" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGQwQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1ab0f059e84f421940f421720635352ed9ccd458/image.png" alt="image.png" />

https://discord.com/channels/679428761438912522/808032358933856306/1209539769223352351

https://discord.com/channels/679428761438912522/808032358933856306/1209539769223352351

https://discord.com/channels/679428761438912522/1209208983957667930/1209209132511662121

**Comment by jainkrati** [comment]
@MohammadPCh @mohammadranjbarz could you pls debug this issue

**Comment by aminlatifi** [comment]
@maryjaf @MoeNick You can test the functionality on staging after this action ends
https://github.com/Giveth/impact-graph/actions/runs/7987911747

If everything okay, we can push it as a standalone hotfix to production

**Comment by maryjaf** [comment]
> https://github.com/Giveth/impact-graph/actions/runs/7987911747

The status is "Failure"

**Comment by MoeNick** [comment]
As its a little bit urgent, can you test it asap @maryjaf ?

**Comment by maryjaf** [comment]
The problem has been resolved on stg and I could  upload an image for my project

**Comment by aminlatifi** [comment]
@MoeNick Made this pr as hotfix  https://github.com/Giveth/impact-graph/pull/1351
