### ISSUE TITLE
New users cant create referral links

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#3780]
**Describe the bug**
New users cant create referral links

**To Reproduce**
1. Go to list of project or specific projects
2. Click on share and get rewarded
3. Nothing happen and we even dont show any error

**Expected behavior**
If third party has problem, we should show an error and a link to report issues. If thirdparty works well, we should create a ref link for user and show it here

**Screenshots**
All available here:

https://discord.com/channels/679428761438912522/1209250336666025994/1209739875813695498

**Comment by maryjaf** [comment]
https://github.com/Giveth/giveth-dapps-v2/assets/111529185/bcdadeb7-c108-48e7-aa67-1da25047eb41

**Comment by alireza-sharifpour** [comment]
I tested this issue,
It seems like it's an issue with lack of loading!
I tested it with 2 accounts, it took about 7 seconds to create referral link!
Can you wait more and test it again?
In this 7 seconds the Modal was empty.
@maryjaf @MoeNick

**Comment by MoeNick** [comment]
Please check the details of the issue, we should add loading and error handling if the api did not respnd or responded late. @CarlosQ96 checked it yesterday and the chaonvine through 500 error after a while

**Comment by alireza-sharifpour** [comment]
In the code we have the error state. So if we get an error we should show it.
It seems like the problem is with lack of having loading.

**Comment by jainkrati** [comment]
as per @alireza-sharifpour it is taking upto 7 seconds to create link and in absence of loader it seems like it is not working at all. 

@MoeNick could you share the laoder design for this or if we should use default loader
@CarlosQ96 could you debug why it took 7 seconds

**Comment by jainkrati** [comment]
Thanks @alireza-sharifpour for your investigation. Assigning @mateodaza for FE change once loader design is confirmed by Moenick

**Comment by MoeNick** [comment]
We have general loader design in our assets in figma, the one we are using for loading projects list.

It worth to mention in some cases back-end did not translate the response error correctly to front-end, in the case of user, chain in e service got 500 and back-end passes 200 so it won't show up the error to user.

**Comment by maryjaf** [comment]
I've checked again and wait for about 1 min but the result is the same as before
https://github.com/Giveth/giveth-dapps-v2/assets/111529185/04ebd38b-240d-445a-b37a-dde803152eb6

**Comment by alireza-sharifpour** [comment]
I tested it again for new user.
And this is the response for creating chainVine referralId I get after about 10 seconds from the backend:
<img width="998" alt="Screenshot 2024-02-25 at 10 17 23 AM" src="https://github.com/Giveth/giveth-dapps-v2/assets/48887817/3c0bf717-d54f-4fd1-b6a6-b36746f992cc">
@maryjaf If you still cannot create chainvine id, please DM and we should check it in your local machine and see the backend's response.

**Comment by alireza-sharifpour** [comment]
I and @Maryjaf also tested it, the problem is on production and it seems like on staging we have that delay issue I mentioned.
For production as I said we get 200 when the backend cannot create chainVine id and that's why we don't show error.
I'm going to handle it on the FE so we show error to the user on that scenario.

![Screenshot 2024-02-25 at 10 46 29 AM](https://github.com/Giveth/giveth-dapps-v2/assets/48887817/dcf3a8ce-cb46-425b-9bfe-d8bf725f8707)

**Comment by MoeNick** [comment]
This is an issue due to the chainVine problem and seems they don't support the service for now, so I guess the removing of share and get rewarded to normal share should get prioritized
