### ISSUE TITLE
RegenFarms & RegenStreams - show cards when on wrong network

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#379]
PR Giveth/liquidity-mining-dapp#183 

Similar to when a user is on the GIVfarm with the wrong network the cards are greyed out and we prompt them to switch to the right network. We should implement a similar feature for the RegenFarms instead of hiding the regenfarms when on the wrong network.

![image](https://user-images.githubusercontent.com/67759413/158180126-66e832aa-3f98-43de-8f93-8b9fa0d553c1.png)

Also add a small modal letting the user know they need to switch to Gnosis Chain (xDai) with a switch wallet button for xDai only if the user is on the wrong chain. 

text should read - `RegenFarms are only avaible on xDai. Please switch the network.`

![image](https://user-images.githubusercontent.com/67759413/158183219-e5ea04ef-1443-452b-bc6c-66358f5cc116.png)

**Comment by laurenluz** [comment]
This is greeeeaaat. works great.
