### ISSUE TITLE
tx error modal in GIVstream page missing bottom spacing

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3790]
giveth production
brave browser
linux 22.04

The error modal on the GIVstream page is missing spacing at the bottom - it should have this spacing underneath the text like other modals 

<img width="1041" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOENKQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2b53cbd8d9b3c7524ddd621238133f0e0b84e5da/image.png" alt="image.png" />

**Comment by jainkrati** [comment]
@alireza-sharifpour pls take this post your p0,p1 issues are done
