### ISSUE TITLE
Add price support for ARB token

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3793]
We should ensure we have FE support for the ARB token and that we can properly fetch the price for it. 

https://www.coingecko.com/en/coins/arbitrum
https://arbiscan.io/token/0x912ce59144191c1204e64559fe8253a0e49e6548

![Screenshot from 2024-02-26 13-14-12](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/5617f974-388b-4bab-9c33-e48892a8763b)

**Comment by MoeNick** [comment]
We tested it for Dai and other tokens, does it related to the rate limit of coingeko?

**Comment by maryjaf** [comment]
I had Dai for testing and the price was shown correctly 

<img width="1294" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/9e992ce4-c00c-4257-84e9-b6438d05b2cb">

**Comment by MoeNick** [comment]
This should get solved first
https://github.com/Giveth/giveth-dapps-v2/issues/3798

**Comment by MoeNick** [comment]
I put it in QA is #3798 is merged.

**Comment by maryjaf** [comment]
> I put it in QA is #3798 is merged.

It should be tested on prod  after deploying
