### ISSUE TITLE
Use coingeckoId for fetching token price

### ISSUE THREAD

**Issue by alireza-sharifpour** [Giveth/giveth-dapps-v2#3798]
In our recent conversation, @aminlatifi highlighted that the primary method for retrieving token prices involves leveraging the coingeckoId in backend. It's recommended that we adopt this approach in our frontend development as well.

In instances where the coingeckoId is unavailable, we should default to utilizing our custom `fetchPrice` function. This alternative method requires both the `chainId` and `contractAddress` as inputs for price retrieval.

To streamline the process of adding new tokens to Giveth, it is crucial for project managers to provide backend developers with the coingeckoId. This ensures efficient and consistent price data integration within our system.

CC: @jainkrati, @MoeNick, @divine-comedian

**Comment by alireza-sharifpour** [comment]
This is the same list on production:

[production.txt](https://github.com/Giveth/giveth-dapps-v2/files/14430885/production.txt)

**Comment by maryjaf** [comment]
The price of tokens are shown correctly on STG
