### ISSUE TITLE
Remove the GIVgarden page from the website

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3799]
- [x] We should remove this page from the Giveth website - https://giveth.io/givgarden

- [x]  the button should also be removed from the giveconomy pages tab list 

![image](https://github.com/Giveth/GIVeconomy/assets/67759413/2a6ef8ae-1c42-4fc9-89ce-17aa2f4d5af9)

- [x] remove from giveconomy dropdown in navbar 

![image](https://github.com/Giveth/GIVeconomy/assets/67759413/bfd305cc-8597-4b89-a3f5-d8ac4d391a6d)

- [x] from the FAQ 

![image](https://github.com/Giveth/GIVeconomy/assets/67759413/8ea37e22-2641-4d1a-9221-549eb713f42d)

Anywhere else on the main Giveth website we should consider @laurenluz @MoeNick 

documentation will be covered in a separate issue.

**Comment by laurenluz** [comment]
- [ ] Remove this whole "vote" box from https://giveth.io/giveconomy
![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/e29f2ff3-3fd9-4de9-a07d-d6652883f9a2)

- [ ] Change copy on the middle box at the bottom of the GIVstream page https://giveth.io/givstream
Title: GIVpower
Text: Lock GIV to earn rewards & get GIVpower. Boost projects with GIVpower to help them get seen first by donors.
Button: See Boosts --> https://giveth.io/account?tab=givpower
![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/2958e381-82cd-4860-a84a-8f25724fbb38)

**Comment by alireza-sharifpour** [comment]
[Uploading... Screenshot 2024-03-03 at 5.03.19 PM.png]

**Comment by alireza-sharifpour** [comment]
We also need some other copy changes:

<img width="1091" alt="Screenshot 2024-03-04 at 1 25 36 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/48887817/8bdac077-eb69-4298-a5fb-edf19788f375">
<img width="1102" alt="Screenshot 2024-03-04 at 1 26 23 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/48887817/bd68be31-2e80-4dd2-9fff-c4d81e123986">

@laurenluz @divine-comedian

**Comment by divine-comedian** [comment]
## from FAQ

> [Join Discord](https://discord.giveth.io/) to engage with the community. If you have GIV, wrap it in the [GIVgarden](https://giveth.io/givgarden) to unlock your governance voting power. Keep abreast of governance proposals and participate in the discussion in our [Forum](https://forum.giveth.io/).

should be -> 

[Join Discord](https://discord.giveth.io/) to engage with the community. If you have GIV, you can use it in [GIVernance Voting](https://snapshot.org/#/giv.eth). Keep abreast of governance proposals and participate in the discussion in our [Forum](https://forum.giveth.io/).

----

> You can get (or increase) your GIVstream flow-rate on Gnosis Chain by donating (on Gnosis or Mainnet) and getting [GIVbacks](https://giveth.io/givbacks), by wrapping GIV to use in the [GIVgarden](https://giveth.io/givgarden), or by staking in the [GIVfarm](https://giveth.io/givfarm) on Gnosis. You can get (or increase) your GIVstream flowrate on Ethereum Mainnet by providing Mainnet liquidity and staking GIV or LP tokens in the [GIVfarm](https://giveth.io/givfarm) on Mainnet.

should be now -> 

You can get (or increase) your GIVstream flow-rate on Optimism, Gnosis Chain and Mainnet by donating and getting [GIVbacks](https://giveth.io/givbacks), and by staking & locking it in [GIVpower](https://giveth.io/givpower) on either Optimism or Gnosis Chain.

## from landing page

> These tokens aren’t just rewards; they're your voice in the [GIVgarden](https://giveth.io/giveconomy), allowing you to influence which proposals get funded, thereby shaping the GIVeconomy's future. Through GIVbacks, GIV empowers donors with governance rights via the GIVgarden.

should be now -> 

These tokens aren’t just rewards; they're your voice in the [GIVernance Voting](https://snapshot.org/#/giv.eth), allowing you to influence which proposals get funded, thereby shaping the GIVeconomy's future. Through GIVbacks, GIV empowers donors with governance rights.

---

> Our mission at Giveth is to recognize and incentivize those who selflessly give. Through GIVbacks, every donation made to our verified projects doesn’t just create societal value, but also earns you GIV tokens. When you donate to verified projects you qualify to receive GIV tokens. Through GIVbacks, GIV empowers donors with governance rights via the GIVgarden.

should be now -> 

Our mission at Giveth is to recognize and incentivize those who selflessly give. Through GIVbacks, every donation made to our verified projects doesn’t just create societal value, but also earns you GIV tokens. When you donate to verified projects you qualify to receive GIV tokens. Through GIVbacks, GIV empowers donors with governance rights.

----

> Shape the future of GIVeconomy in the GIVgarden: The GIV tokens you earn can be used in the [GIVgarden](https://giveth.io/givgarden). Here you can participate in shaping the future of the GIVeconomy by voting on various proposals that resonate with your vision of philanthropy and take part in the governance of Giveth.

should be now -> 

Shape the future of GIVeconomy in with Voting Power: The GIV tokens you earn can be used in the [GIVernance Voting](https://snapshot.org/#/giv.eth). Here you can participate in shaping the future of the GIVeconomy by voting on various proposals that resonate with your vision of philanthropy and take part in the governance of Giveth.

**Comment by divine-comedian** [comment]
## more from the FAQ 

> When you harvest GIV rewards on Gnosis Chain (xDAI) from the [GIVgarden](https://giveth.io/givgarden), [GIVfarm](https://giveth.io/givfarm), or [GIVstream](https://giveth.io/givstream) pages, you get all liquid GIV allocated to you in our token distro in a single transaction. If you earned GIV but don't see it on the [GIVbacks](https://giveth.io/givbacks) page you may have already claimed this allocation from another page.

should be now -> 

When you harvest GIV rewards on from the [GIVfarm](https://giveth.io/givfarm), or [GIVstream](https://giveth.io/givstream) pages, you get all liquid GIV allocated to you in from our smart contract in a single transaction. If you earned GIV but don't see it on the [GIVbacks](https://giveth.io/givbacks) page you may have already claimed this allocation from another page.

**Comment by divine-comedian** [comment]
@alireza-sharifpour - Can you please update this issue? Looks like the PR is merged, is it ready for testing?

**Comment by alireza-sharifpour** [comment]
Yes it's ready for testing.
@maryjaf

**Comment by maryjaf** [comment]
I had tested this issue and moved to "Done"
