### ISSUE TITLE
Project updates are having issues?

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#380]
From Will of Grassroots Econ:
<img width="535" alt="Screen Shot 2022-03-29 at 11 24 13 AM" src="https://user-images.githubusercontent.com/14945613/160660081-c7ccec44-569a-405c-bdec-7c65ea113e87.png">

**Comment by pkretzschmar** [comment]
@GriffGreen could you provide more info? Tried to replicate this, but didn't get any errors.

**Comment by MoeNick** [comment]
@aminlatifi @mateodaza 
Do we have a sentry set for posting an update, editing or deleting updates?

**Comment by GriffGreen** [comment]
@laurenluz knew about this issue... i know nothing else

**Comment by laurenluz** [comment]
I think it's when the users shields are up on brave. They get that error, and the update posts anyway
