### ISSUE TITLE
Issue w/ donation amounts reported in emails to project owners

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3800]
I just got an email saying Giveth got a donation of 2 ETH - which was exciting!! so I went to check it out!

But then I was disappointed because I realized it was most likely a bug... because the most recent donation is 2 MATIC on Polygon... this was the tx I pulled up from around the time of the email (since the donatinon was "anonymous"): https://polygonscan.com/tx/0x20431e086514e6690d6f76e6723bad9783874443b98db081421dbd6bb05c234a

I think we are doing something funky w/ the email email service where we are assuming that the chain's native currency is ETH, when it might be MATIC or xDAI or something else... depending....

@RamRamez - I know you were working on emails

cc @divine-comedian @jainkrati

**Comment by RamRamez** [comment]
Actually I used "findTokenByTokenAddress" function which accepts token address and returns token fields, but the address for all native tokens in impact-graph are ZERO (0x0000....), so, that function returns ETH for all native tokens.
I sent a hotfix and fixed the problem.
I donated 2.5 Matic to a project and received a true email.

https://giveth.io/project/my-brave-project?tab=donations

![image](https://github.com/Giveth/giveth-dapps-v2/assets/73441857/76c8b0ae-96a4-4117-8080-6a0b7a7f74db)

**Comment by RamRamez** [comment]
@maryjaf to test and verify

**Comment by divine-comedian** [comment]
@RamRamez - In your fix did you also consider using Gnosis Chain if a donation of xDAI is sent?

**Comment by RamRamez** [comment]
@divine-comedian Yes, I did.
I just sent a donation with 2.2 xDai now and I got the email.

https://giveth.io/project/my-brave-project?tab=donations

![image](https://github.com/Giveth/giveth-dapps-v2/assets/73441857/7baedde3-eda0-445e-af88-25cc814df7fc)

**Comment by divine-comedian** [comment]
sweet! We'll wait for MJs approval and then can close this one out, thanks for reporting Lauren!

**Comment by maryjaf** [comment]
Is this change on STG?
I've donated 1.355 MATIC on polygon and this is my email :
<img width="1802" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXluQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--187eb921a30a13c640bd217e770913d6b5dd89de/image.png" alt="image.png" />
