### ISSUE TITLE
donate page showing wrong project information 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3804]
# giveth STAGING

related to the changes made in superfluid we updated the project card shown on the donate page

the copy samples are all related to QF but we should not show this on the donate page since the examples provided it is very specific to QF only projects during a QF round. 

we should show information relevant to the project, similar to how it looks on production currently. 

## In figma
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/269ffe13-f127-41b4-b9a0-3e05d64b66bb)

## on staging 
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/d5dd81c3-32f3-4eb8-a9b5-00e86f824d67)

## on production

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/9d287527-053b-4f87-a838-d786b8945dc2)

**Comment by divine-comedian** [comment]
@Tosinolawale - left you a comment - can we try to make it similar to the card that's already on production?

**Comment by Tosinolawale** [comment]
![One-time](https://github.com/Giveth/giveth-dapps-v2/assets/35389241/cdbbe68a-292f-4297-b467-4e3156dd1fd4)
@divine-comedian

**Comment by Tosinolawale** [comment]
![One-time](https://github.com/Giveth/giveth-dapps-v2/assets/35389241/b5e5d463-a93f-424c-8ebe-4e13e0a17264)
@divine-comedian

**Comment by divine-comedian** [comment]
@alireza-sharifpour - giving this one to you. 

I understood we show different project cards conditionally depending if the project being donated to is in a QF round - since we won't have QF eligiblity for recurring donations at launch we should only show this one view of the card with project details ... for now. 

When we enable QF matching eligibility (TBD) we should change it to match one-time donation functionality.

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/e0743151-e9b2-4253-bfd2-4ce0421e4ebf)
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/GIVeconomy?type=design&node-id=25232%3A23315&mode=design&t=Ux4LLUt5sjYXBPKW-1

**Comment by jainkrati** [comment]
@divine-comedian pls dont assign issues directly to engineers. I might be involving them in other priorities based on the need of the hour. Instead pls assign me and I will loop the right person.

**Comment by alireza-sharifpour** [comment]
I implemented this design, but I have some questions.
1-This right section is fixed no matter the user is on One-Time donation or Recurring Donation.
As we have the QF on One-Time donation, what should I do? Should it be changed depending on different tabs.
2- Is the project title a Link?
3- For the project owner name we have a component in which we show the user's PFP on the left-side and use this almost everywhere we show the user's name, should I use that or it will be only the owner's name? Is it a Link?

@divine-comedian

**Comment by divine-comedian** [comment]
@alireza-sharifpour 

1. We will have support for QF matching on recurring donations, but probably not at launch of this feature, so I don't want to confuse users. If its a lot of work we can leave it as is since we would have to revert changes once QF matching support is added. 
2. Project title is a link - same as on production currently.
3. Yes we should use the PFP feature on the user names. Yes it is a link, same as production

**Comment by alireza-sharifpour** [comment]
It's ready for testing @maryjaf

**Comment by maryjaf** [comment]
> * Project title is a link - same as on production currently.
> * Yes we should use the PFP feature on the user names. Yes it is a link, same as production

Name of project and user aren't shown , please take a look @alireza-sharifpour
<img width="1365" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/41d3902a-4f2a-45dc-9d9d-158127657508">

**Comment by divine-comedian** [comment]
@maryjaf - I think this is how the design is supposed to be 

on the QF version of the project card the user name and project title is not displayed @Tosinolawale ? I this intentional?

**Comment by Tosinolawale** [comment]
> @maryjaf - I think this is how the design is supposed to be
> 
> on the QF version of the project card the user name and project title is not displayed @Tosinolawale ? Is this intentional?

That is actually the existing donation page for QF projects. (The original design has project title, so that is missing here). But there is no reason not to have project owner name, I will rectify that now

**Comment by Tosinolawale** [comment]
For QF projects 
![Recurring QF Projects](https://github.com/Giveth/giveth-dapps-v2/assets/35389241/bd31235f-7194-48aa-a71f-eeadcff8efc5)
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/GIVeconomy?type=design&node-id=25583%3A40211&mode=design&t=6LGIqhW1Drvy2dB0-1
@alireza-sharifpour @divine-comedian @maryjaf

**Comment by Tosinolawale** [comment]
Normal donations outside of QF
![Recurring  First time](https://github.com/Giveth/giveth-dapps-v2/assets/35389241/1eb64914-f111-4396-9b0d-e1df49fff2e5)
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/GIVeconomy?type=design&node-id=25232%3A23315&mode=design&t=6LGIqhW1Drvy2dB0-1
@alireza-sharifpour @maryjaf

**Comment by alireza-sharifpour** [comment]
@maryjaf It's ready for testing.

**Comment by maryjaf** [comment]
> For QF projects
> ![Recurring QF Projects](https://private-user-images.githubusercontent.com/35389241/318912157-bd31235f-7194-48aa-a71f-eeadcff8efc5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMjM0MTMsIm5iZiI6MTcxMjIyMzExMywicGF0aCI6Ii8zNTM4OTI0MS8zMTg5MTIxNTctYmQzMTIzNWYtNzE5NC00OGFhLWE3MWYtZWVhZGNmZjhlZmM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDA5MzE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhOTUwZTBhNTVkZTI3NGM1ZDQ2M2RmZTM5OTM5ZWZjMGY0MzRjMjUzY2M3M2YwN2YzZGE5NzY5OGFkNzc1ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yPPxQbs7ETIb5NOMNgPj8BPB_37WKX825ua0nwoUV94)

There is a difference between figma and current design
contribution table isn't shown
<img width="1311" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/2c3e6e66-954b-4aa5-ba52-185553f3cdb0">
contribution table isn't shown

**Comment by alireza-sharifpour** [comment]
In Figma It's like this, I don't know which design is correct. @divine-comedian 
![Screenshot 2024-04-04 at 1 22 28 PM](https://github.com/Giveth/giveth-dapps-v2/assets/48887817/203d6bb9-5d36-4b40-9997-2a8ca9518dc0)

**Comment by MoeNick** [comment]
@alireza-sharifpour @maryjaf the latest link that the @Tosinolawale shared is correct. he shared 2 links. Is there still a confusion? How can I help? (Mitch is on vacay lets not mention him)

**Comment by alireza-sharifpour** [comment]
> @alireza-sharifpour @maryjaf the latest link that the @Tosinolawale shared is correct. he shared 2 links. Is there still a confusion? How can I help? (Mitch is on vacay lets not mention him)

Should I show the table or not?

**Comment by MoeNick** [comment]
@alireza-sharifpour No please, let's go based on the latest design, which does not have the table.
