### ISSUE TITLE
Projects show "Donate first" on mobile even if it received donations

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-dapps-v2#3805]
**Describe the bug**
When you open a project link on mobile, even if it received donations in the past, it still shows me "Donate first and lead the way!"

**To Reproduce**
1. Open any project link on mobile (I'm on an Android)

**Expected behavior**
It shouldn't show the "Donate first and lead the way!" text if a project already has donations 

**Screenshots**
![image](https://github.com/Giveth/giveth-dapps-v2/assets/4855928/189d4fa5-f87d-4c7c-8d96-b148de720882)

**Comment by ahmadabugosh** [comment]
@MoeNick FYI

**Comment by divine-comedian** [comment]
Fixed this one in a previous issue! Thanks for reporting
