### ISSUE TITLE
Collect sentry logs at donation failure time 

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3807]
related to:
https://github.com/Giveth/impact-graph/issues/1264
https://github.com/Giveth/impact-graph/issues/1247#issuecomment-1907589327
https://github.com/Giveth/giveth-dapps-v2/issues/3659
https://www.notion.so/giveth/Missing-Failed-Donations-24e265f19ac7465b8917ac42e5b42fc4

@aminlatifi I'm assigning you because you said we needed this issue, feel free to remove yourself & reassign the correct person

cc @jainkrati

**Comment by laurenluz** [comment]
this should have been in dapps v2 - sorry @oyealmond . I Think it might even be done/not relevant anymore. @aminlatifi please close if this is finished.

**Comment by aminlatifi** [comment]
I couldn't see anything special at those spots.
