### ISSUE TITLE
Copy fix on Incomplete profile

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3808]
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/48ee962b-3ad8-43f2-a122-d155ba6e94db)

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/90c9c206-4406-4058-a71d-776bf7ca6e82)

Copy is weird on both these parts when the user has an incomplete profile. Grammar/flow should be improved.

My suggestions:
"Your profile is incomplete"
"Completing your profile will allow you to receive email notifications, create a project, donate proudly & more!"

And:
"Ready to level-up your Giveth profile?
With a complete profile you can:
Create projects and receive funds.
Communicate with the community.
Let others get to know you a little better."

**Comment by RamRamez** [comment]
@maryjaf to test and verify

**Comment by maryjaf** [comment]
Thanks @RamRamez 
<img width="758" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2UzQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f53f0051e7c9209d74b23fba4002dc1f80b1570a/image.png" alt="image.png" />
