### ISSUE TITLE
Verify Project - Upload File is not throwing proper Error Message and Next button is disabled

### ISSUE THREAD

**Issue by jeevanplus007** [Giveth/giveth-dapps-v2#3809]
**Issue :** In Verify Project Workflow, While Uploading Non Image File like a Video File, the NEXT button is Disabled and cannot proceed further. 

**Steps to Repro :**

- Open an Existing Project
- Go to Verify Project
- Go to Upload File Stage and Upload any Video File or any non image file. 

**Results :** It is not uploaded as expected but it is not displaying any Error Message. Also the NEXT button is greyed and hence the User cannot proceed further. 

**NOTE : There is a workaround - just go to previous button and then Next Button will be Enabled again.** 

**Snapshot 1 for Reference :** 
![image.png](https://images.zenhubusercontent.com/62a3cf4962612d632dd3b42a/1317f45b-9bbe-40af-a1f7-fb9e62049c57)

**Comment by divine-comedian** [comment]
@maryjaf - could you test out this bug and see if it is still relevant?

**Comment by maryjaf** [comment]
It works for me, when I try to upload for example csv file that not supported, the below error is shown for me

![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/435f0265-539e-4d27-abac-17fa590b5d33)
