### ISSUE TITLE
Fixes on Recurring Donation Donate page

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3810]
I've been testing the flow of creating a recurring donation - apart from the changes we have pending in https://github.com/Giveth/giveth-dapps-v2/pull/3806
https://github.com/Giveth/giveth-dapps-v2/issues/3804

There's a few other fixes we should make 

## Available button
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/d02228b8-996f-4266-bb74-fdc5cc25f0ed)

- [x] This should behave the same as one-time donation - when I click the button my available balance should be entered into the input box - only for depositing tokens into my stream balance

## zero super token balances 
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/5f51273e-ff50-4059-8082-cf63c8b1df55)

- [x] if my super token balance is 0 we should hide it from this modal, If I don't have any super tokens we should hide that whole section of the list "Streamable Token Balances" from the UI - it adds confusion for new users. 

However we should always show "Depositable Tokens" even if they are zero since it is good to know all of the underlying tokens available to deposit.

## Success page 

- [x] #3881  The design for the success page needed to be improved to match closer to what we have on production. Here is the design we should implement 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/d4b60e21-1901-4caf-b026-0efd6055ae7e)
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/GIVeconomy?type=design&node-id=24207%3A73763&mode=design&t=0s4bT1zbtKzCAPmW-1

## hide header for balance of depositable tokens

- [x] When a user has a balance for all super tokens we should not show this header at all on the token list 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/c07821c1-169e-4354-b9d8-67e7162a0b3c)

## Donate page sub-header text 

- [x] From feedback from Tosin slight changes on the header text 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/bcc94fd6-8787-40fc-ab4a-98bb09272fdd)

> This looks better @divine-comedian. Reworded the texts a bit too

**Comment by divine-comedian** [comment]
## Success page 

The design for the success page needed to be improved to match closer to what we have on production. Here is the design we should implement 
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/d4b60e21-1901-4caf-b026-0efd6055ae7e)
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/GIVeconomy?type=design&node-id=24207%3A73763&mode=design&t=0s4bT1zbtKzCAPmW-1

**Comment by divine-comedian** [comment]
- [ ] When a user has a balance for all super tokens we should not show this header at all on the token list 


![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/c07821c1-169e-4354-b9d8-67e7162a0b3c)

**Comment by divine-comedian** [comment]
@MohammadPCh - for you here this one based on our call today.

**Comment by MohammadPCh** [comment]
@jainkrati could you please assign the success page to the @alireza-sharifpour  ? I think it's better to create a new issue and assign it to him.

**Comment by divine-comedian** [comment]
Thanks @MohammadPCh - In the future you can tag me if you need any new issues made.

**Comment by alireza-sharifpour** [comment]
The new success view is added and ready for testing. @maryjaf 
CC: @divine-comedian

**Comment by divine-comedian** [comment]
@alireza-sharifpour who should take on the rest of these issues? Would you prefer each bullet is a new issue?

**Comment by alireza-sharifpour** [comment]
I talked with @maryjaf about it, she said she created an issue for each of them.

**Comment by alireza-sharifpour** [comment]
> I talked with @maryjaf about it, she said she created an issue for each of them.

@divine-comedian

**Comment by maryjaf** [comment]
> I talked with @maryjaf about it, she said she created an issue for each of them.

Not for this issue

**Comment by maryjaf** [comment]
> ## Success page
> * [x]  [updated donation success view #3881](https://github.com/Giveth/giveth-dapps-v2/pull/3881)  The design for the success page needed to be improved to match closer to what we have on production. Here is the design we should implement

The design has been changed correctly 
but about "Raised" amount in success page the total amount of recurring donation should be shown 
and now the total amount of one time donation is shown 
I talked to @divine-comedian and he said this problem should be fixed  for this phase of superfluid
and it needs to backend changes because now only one time donations are counted for any total donation fields 
Is there separate issue for these backend changes ?

**Comment by jainkrati** [comment]
@alireza-sharifpour can you pls take at this. @mohammadranjbarz can you pls take up the BE chagnes if any

**Comment by divine-comedian** [comment]
> > ## Success page
> > 
> > * [x]   [updated donation success view #3881](https://github.com/Giveth/giveth-dapps-v2/pull/3881)  The design for the success page needed to be improved to match closer to what we have on production. Here is the design we should implement
> 
> The design has been changed correctly but about "Raised" amount in success page the total amount of recurring donation should be shown and now the total amount of one time donation is shown I talked to @divine-comedian and he said this problem should be fixed for this phase of superfluid and it needs to backend changes because now only one time donations are counted for any total donation fields Is there separate issue for these backend changes ?

The way the BE works is that it saves a "mini-donation" every day for each recurring donation, this means the amount of tokens and total USD value donated to the project should be updating daily. I'm not sure if there's any explicit changes we need on the BE but I think @CarlosQ96  can correct me if this is not the way it is working currently.

**Comment by alireza-sharifpour** [comment]
It's ready for testing @maryjaf

**Comment by maryjaf** [comment]
> It's ready for testing @maryjaf

I haven't seen changes in above items in description, have these changes been deployed correctly on stg?
<img width="651" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/468c1cdd-9c8d-4af6-bba7-ac6f9b2d3209">
<img width="670" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/6e490c52-a740-42f0-ace9-93aa30510035">

**Comment by maryjaf** [comment]
> > > ## Success page
> > > 
> > > * [x]    [updated donation success view #3881](https://github.com/Giveth/giveth-dapps-v2/pull/3881)  The design for the success page needed to be improved to match closer to what we have on production. Here is the design we should implement
> > 
> > 
> > The design has been changed correctly but about "Raised" amount in success page the total amount of recurring donation should be shown and now the total amount of one time donation is shown I talked to @divine-comedian and he said this problem should be fixed for this phase of superfluid and it needs to backend changes because now only one time donations are counted for any total donation fields Is there separate issue for these backend changes ?
> 
> The way the BE works is that it saves a "mini-donation" every day for each recurring donation, this means the amount of tokens and total USD value donated to the project should be updating daily. I'm not sure if there's any explicit changes we need on the BE but I think @CarlosQ96 can correct me if this is not the way it is working currently.

should be created separate issue for this item ?
@divine-comedian @CarlosQ96

**Comment by MoeNick** [comment]
I brought it up in Discord and @jainkrati said let's assign it to you @CarlosQ96

**Comment by MoeNick** [comment]
@mohammadranjbarz a gentle reminder on this! :)

**Comment by MoeNick** [comment]
Another reminder @mohammadranjbarz

**Comment by maryjaf** [comment]
> The design has been changed correctly
> but about "Raised" amount in success page the total amount of recurring donation should be shown
> and now the total amount of one time donation is shown
> I talked to @divine-comedian and he said this problem should be fixed for this phase of superfluid
> and it needs to backend changes because now only one time donations are counted for any total donation fields
> Is there separate issue for these backend changes ?

Now for "raised" amount  in success donation page like as "total donated amount"  total of both one time and recurring donation (the new donation one time or recurring isn't counted like before) is shown
