### ISSUE TITLE
Adding projects to "Fraud" list for QF rounds projectID search improvements

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3811]
I'm supposed to import a "projectID"... but instead of the actual project ID number, I need to find the NAME of the project and it's case sensitive.

This makes it really hard to actually find the project, and adding them in bulk will be nearly impossible imo.

we should make the csv require either... projectID number.. or project recipient address on a specific chain.

And for the one-by-one add... we should make it so that at least the search is not case sensitive.

This isn't super time sensitive (even with the massive polygon round, there were only 6 projects we needed to add to the list), but I think these improvements would be nice to have for sure... As it is, this is kind of hard to use for an admin.

@mohammadranjbarz @jainkrati

**Comment by jainkrati** [comment]
@mohammadranjbarz could you pls take this up for admin bro

**Comment by jainkrati** [comment]
@RamRamez can you take this today and if needed take guidance from @CarlosQ96

**Comment by jainkrati** [comment]
@CarlosQ96 pls guide Lovel George to take this up

**Comment by laurenluz** [comment]
I think this was fixed through an old issue. now we input projectID & qfroundID which is totally fine. @CarlosQ96 @lovelgeorge99
