### ISSUE TITLE
Technical SEO - /user page

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-dapps-v2#3813]
Hey @geleeroyale @MoeNick @mhmdksh , 

I noticed this page: giveth.io/user  is getting a lot of traffic and it's a 404 page (I think it's linked in a few different places and externally somewhere). Can we change it to redirect to giveth.io/account please? (since I think that makes more sense)

Just be sure not to use a wildcard redirect, because we still want the normal user pages to show, like giveth.io/user/0x00... etc

**Comment by divine-comedian** [comment]
@jainkrati - I'm not sure who handles this - FE or devops, could you guide me here?

**Comment by geleeroyale** [comment]
Well my plan was to set our forwarder to forward this url so it does not throw a 404 anymore. Like we do with other routes

**Comment by geleeroyale** [comment]
hmmmm - sorry - I did not see that you were requesting changes in the root domain.  We can't do it with the forwarder (the forwarder is used to handle this problem for subdomains, not for the apex domain)

For this it would indeed be better to default incoming requests in a way that you described @ahmadabugosh - and that would happen on a frontend level as @divine-comedian suggested.

**Comment by divine-comedian** [comment]
OK great 

@jainkrati 
Ahmad noticed in our SEO that users are somehow getting to a /user page - perhaps by their own mistake - but it is a 404 page - we should assign a FE dev that reroutes users who try to go to giveth.io/user to be routed to giveth.io/account

**Comment by jainkrati** [comment]
@RamRamez could you debug this from FE and BE both?

**Comment by RamRamez** [comment]
@maryjaf to test and verify

**Comment by maryjaf** [comment]
Thanks  @RamRamez 
https://staging.giveth.io/user is redirected to https://staging.giveth.io/account
