### ISSUE TITLE
Technical Debt - Create clean sentry projects and fill them with selected errors

### ISSUE THREAD

**Issue by alireza-sharifpour** [Giveth/giveth-dapps-v2#3817]

**Comment by MohammadPCh** [comment]
Three months ago, I adjusted the Sentry settings to only send selected errors. However, for tasks such as creating a new project on Sentry or setting up a new account, I suggest letting the DevOps team handle it as they are accustomed to these tasks.

**Comment by divine-comedian** [comment]
Just need a developer to set new project but first step is devops @Giveth/devops

**Comment by geleeroyale** [comment]
I am not really sure what this is about. Please note that our team has been reduced, so we can't take on any more responsibilities at the moment.
