### ISSUE TITLE
Bug in calculating project weight and/or matching cap

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3822]
When I export the QF round data for the polygon round (see [master spreadsheet](https://docs.google.com/spreadsheets/d/1Wk8_bG75uQGZnVywos2Ii2t-4QosHoC0pRkMlZ85Ga8/edit#gid=1918507526))  and sort by project weight, I can see there is some bug in calculating the matching... because some projects are apparently getting less matching than the matching cap even though they have a higher "weight" than other projects who ARE getting the matching cap.

See image for more clear explanation.

<img width="956" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/75490971/1eb7b96d-7f7e-4a63-964e-23046d32b53c">

@CarlosQ96 @aminlatifi @jainkrati

**Comment by jainkrati** [comment]
This is a BE issue so assigning to @mohammadranjbarz . I know he is already deploying a fix soon.

**Comment by maryjaf** [comment]
it seems this issue is related to https://github.com/Giveth/giveth-dapps-v2/issues/3838#issuecomment-2043083394
I move it to done and track the status on https://github.com/Giveth/giveth-dapps-v2/issues/3838
