### ISSUE TITLE
Fix bugs on project weight & matching calc from QF round data export

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3826]
1. We should consider total donation usd value of a user to one project as a single donation during calculation
2. total value usd of each user should be more than qfRound.minimumValidUsdValue (For polygon round 0.65 $) otherwise we ignore them (If a user has two donations one 0.4$ and the other one 0.3$ we include this donation because sum of those two donations are more than threshold)
3. Should exclude donations of users that their passport score is less than minimumPassportScore
4. Should exclude recipient addresses of verified projects

@mohammadranjbarz @CarlosQ96 can you connect the PR for this?

cc @jainkrati

**Comment by mohammadranjbarz** [comment]
> 1. We should consider total donation usd value of a user to one project as a single donation during calculation
> 2. total value usd of each user should be more than qfRound.minimumValidUsdValue (For polygon round 0.65 )otherwiseweignorethem(Ifauserhastwodonationsone0.4 and the other one 0.3$ we include this donation because sum of those two donations are more than threshold)
> 3. Should exclude donations of users that their passport score is less than minimumPassportScore
> 4. Should exclude recipient addresses of verified projects
> 
> @mohammadranjbarz @CarlosQ96 can you connect the PR for this?
> 
> cc @jainkrati

This is the related PR
https://github.com/Giveth/impact-graph/pull/1392

**Comment by maryjaf** [comment]
It seem this issue is related to https://github.com/Giveth/giveth-dapps-v2/issues/3838#issuecomment-2043083394, 
I move it to done

**Comment by maryjaf** [comment]
- [ ] 2-

 In this report on stg  the "donationIdsAfterAnalysis" is empty, but for example I think this  donation id : 59832 for "How many photos is too many photos?" project should be shown in this"donationIdsAfterAnalysis" field 
 
-The usd amount is more than minimum usd value in qf round setting (Minimum Valid Usd Value:0.01)
-Passport score is 2.251756 (Minimum Passport Score: 2)
-The address isn't in purple list (0xa1179f64638adb613ddaac32d918eb6beb824104)
https://impact-graph.serve.giveth.io/admin/resources/QfRound/records/90/edit

https://docs.google.com/spreadsheets/d/1Wk8_bG75uQGZnVywos2Ii2t-4QosHoC0pRkMlZ85Ga8/edit#gid=1485049122

**Comment by laurenluz** [comment]
@CarlosQ96 maybe you can check the bugs today?

**Comment by mohammadranjbarz** [comment]
@maryjaf  I couldn't fix it today, but I think we can release today and fix this bug later till end of the round

JFYI @jainkrati

**Comment by jainkrati** [comment]
@CarlosQ96 pls take this up

**Comment by CarlosQ96** [comment]
It wasn't saved because the qfroundUserScore is empty in the donation.

**Comment by CarlosQ96** [comment]
Latest changes at the beginning of the week exclude purple list.

**Comment by maryjaf** [comment]
> For item #2, we generated the data for the the ENS round and valid donations appeared in the afterAnalysis just fine.

So on production all condition works correctly and there is no problem ? @CarlosQ96 @laurenluz

**Comment by CarlosQ96** [comment]
Yeah!

**Comment by maryjaf** [comment]
> * [x]  2-
> 
> In this report on stg the "donationIdsAfterAnalysis" is empty, but for example I think this donation id : 59832 for "How many photos is too many photos?" project should be shown in this"donationIdsAfterAnalysis" field
> 
> -The usd amount is more than minimum usd value in qf round setting (Minimum Valid Usd Value:0.001) -Passport score is 2.251756 (Minimum Passport Score: 2) -The address isn't in purple list (0xa1179f64638adb613ddaac32d918eb6beb824104) https://impact-graph.serve.giveth.io/admin/resources/QfRound/records/90/edit
> 
> https://docs.google.com/spreadsheets/d/1Wk8_bG75uQGZnVywos2Ii2t-4QosHoC0pRkMlZ85Ga8/edit#gid=1485049122
> 
> please take a look @mohammadranjbarz

"donationIdsAfterAnalysis" is always empty on stg, maybe there is a problem on stg 
If @laurenluz approves that it works fine on prod we could close this issue, but we should investigate the problem of stg 
cc: @jainkrati 

I retested on stg but I didn't see the expected result  and "donationIdsAfterAnalysis" is empty 
@mohammadranjbarz @CarlosQ96  please take a look


donation id : 104864 , project: "How many photos is too many photos?

-The usd amount is more than minimum usd value in qf round setting (Minimum Valid Usd Value:0.0001)
-Minimum Passport Score is set 0 in qf round setting
-The address isn't in purple list (0xD5db3F8B0a236176587460dC85F0fC5705D78477)
- and there is no project with this recipient address 0xD5db3F8B0a236176587460dC85F0fC5705D78477 in the QF round

**Comment by laurenluz** [comment]
the donation ids after analysis seems to be working ok on prod @maryjaf
