### ISSUE TITLE
Query database for Polygon QF round final numbers

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3828]
to make the report, I'll need:
- total number of unique donors (no sybils, no purple list (w/ our coniditions), no passport less than 4... include donors who made donations than $0.65)
- total number of "eligible" donations... so ones from "unique donors" aka, no sybils, no passport less than 4, no purple list w/ conditions, but also ones that are above $0.65
- total number of projects (including "fraudulent projects"
- total number of verified projects
- total number of donations (including ones from sybils, passport less than 4, etc.)
- total USD value of donations (including all sybils, small donations etc)

I mentioned these to @CarlosQ96 already, but any backend dev can help me w/ it once we finish #3826 and #3827 

cc @jainkrati @mohammadranjbarz

**Comment by jainkrati** [comment]
@CarlosQ96 while you create the report,  lets create a page for documenting each scenario with the queries so that next time we can either implement them as part of adminBro or anyone nontech can run those queries themselves?

**Comment by laurenluz** [comment]
@CarlosQ96 hold off on this until I get the final ok from polygon... so we can know if we should include whether on not we should include the projects I think are totally fraudulent.

**Comment by laurenluz** [comment]
@mohammadranjbarz can you help grab these numbers before the end of the day today?

**Comment by mohammadranjbarz** [comment]
### total number of unique donors (no sybils, no purple list (w/ our coniditions), no passport less than 4... include donors who made donations than $0.65)
#### Query
```
SELECT COUNT(DISTINCT u.user_id) AS unique_user_count
FROM project_actual_matching_view p,
LATERAL UNNEST(p."uniqueUserIdsAfterAnalysis") AS u(user_id)
WHERE p."qfRoundId" = 6;
```
#### Result
`2322`

### total number of "eligible" donations... so ones from "unique donors" aka, no sybils, no passport less than 4, no purple list w/ conditions, but also ones that are above $0.65
#### Query
```
SELECT COUNT(DISTINCT d.donation_id) AS unique_donation_count
FROM "project_actual_matching_view" p,
LATERAL UNNEST(p."donationIdsAfterAnalysis") AS d(donation_id)
WHERE p."qfRoundId" = 6;
```

#### Result
`3240`

### total number of projects (including "fraudulent projects"
* projects related to qfRound
#### Query 
```
select count(*) from project_qf_rounds_qf_round
where "qfRoundId"=6
```
#### Result
`206`

* projects that received donations in that round
#### Query
```
SELECT COUNT(DISTINCT "projectId")
FROM donation
WHERE "qfRoundId" = 6
AND "projectId" IS NOT NULL;
```
# Result
`161`

### total number of verified projects
#### Query
```
SELECT COUNT(DISTINCT p."id") 
FROM project_qf_rounds_qf_round pqfr
JOIN project p ON pqfr."projectId" = p.id 
WHERE pqfr."qfRoundId" = 6 AND p."verified" = true;
```

#### Result
`25`

### total number of donations (including ones from sybils, passport less than 4, etc.)
#### Query
```
select count(*) from donation
where "qfRoundId"=6 and status='verified'
```

#### Result
`7329`

### total USD value of donations (including all sybils, small donations etc)
#### Query
```
select sum("valueUsd") from donation
where "qfRoundId"=6 and status='verified'
```

#### Result
`203083.1`

@laurenluz  @jainkrati 
It would be good if someone else look at the queries to make sure that are correct

**Comment by laurenluz** [comment]
this is great @mohammadranjbarz - thank you so much. I used the data & added the results in the forum.

maybe @CarlosQ96 if he has time can look at the queries, and if they are ok, we can save them for later, and close the issue.
