### ISSUE TITLE
in the UI, we should explain to people that donations less than $1 in QF don't count

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3829]
@mosaeedi - can you help me out w/ this one?

**Comment by mosaeedi** [comment]
<img width="564" alt="Screenshot 2024-04-22 at 5 17 25 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/fea3c7b0-09b4-4ced-9401-2f0e213973dd">


When the user enters an amount under $1 a hint can appear to let the user know.

**Comment by mosaeedi** [comment]
@laurenluz wdyt?

**Comment by laurenluz** [comment]
@mosaeedi I think this is good - we need to consider a couple of cases though...

- the project must be in the QF round
- we might want to hide the "estimated matching" amount if the amount is less than $1.

for ease of development, can you make a couple of versions here so the dev can understand the scenarios?

like:
1. Donation to QF project if the USD amount is >= threshold (FYI we set a min donation amount in our backend so this value should be pulled from there)
2. Donation to QF project if the USD amount is < threshold

**Comment by mosaeedi** [comment]
Hey @laurenluz

I don't think how I can show the scenarios on Figma other than how it is right now!

The _yellow notif row_ "**Make it count**" will only appear if both scenarios are valid!

The project should be in **QF** and the **Donation should be less than the threshold**, 

and by default, **when the amount is less than the threshold**, we only show "**Make it count**" yellow notif row instead of the "estimated matching" green notif row.

Is it clear?

**Comment by maryjaf** [comment]
- [ ] When the round hasn't started yet, should this explanation about minimum amount of donation be shown ?
 
 @mosaeedi @laurenluz 
 
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/c0d6854c-7531-47d1-80a1-865a6cb2a46c)

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/ebc8311b-f805-41e8-9dbf-b8619d81623f

**Comment by mosaeedi** [comment]
The "**Make it count**" explanation is only for the donation of less than a dollar **during the QF round**.

**Comment by Meriem-BM** [comment]
> * [ ]  When the round hasn't started yet, should this explanation about minimum amount of donation be shown ?
> 
> @mosaeedi @laurenluz
> 
> ![image](https://private-user-images.githubusercontent.com/111529185/341324677-c0d6854c-7531-47d1-80a1-865a6cb2a46c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NTYxMjEsIm5iZiI6MTcxODk1NTgyMSwicGF0aCI6Ii8xMTE1MjkxODUvMzQxMzI0Njc3LWMwZDY4NTRjLTc1MzEtNDdkMS04MGExLTg2NWE2Y2IyYTQ2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMVQwNzQzNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNjkxOTZmMDBmNjM2OWQwZDk1Yjk2ZDBiYjlkMzk5NDcyNzIxZTQzYmM4MDZmNmZlZDkzODliNjdjMGU5MTU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RkoYZtOW7_oiGENBoxB9HDcBbNPsyGbsa85Kgd27jgI)
> 
>  Screen.Recording.2024-06-20.at.11.29.16.AM.mov

I don't know why that was showing, I can't see this problem while testing

**Comment by maryjaf** [comment]
> > * [ ]   When the round hasn't started yet, should this explanation about minimum amount of donation be shown ?
> > 
> > @mosaeedi @laurenluz
> > ![image](https://private-user-images.githubusercontent.com/111529185/341324677-c0d6854c-7531-47d1-80a1-865a6cb2a46c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NTYxMjEsIm5iZiI6MTcxODk1NTgyMSwicGF0aCI6Ii8xMTE1MjkxODUvMzQxMzI0Njc3LWMwZDY4NTRjLTc1MzEtNDdkMS04MGExLTg2NWE2Y2IyYTQ2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMVQwNzQzNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNjkxOTZmMDBmNjM2OWQwZDk1Yjk2ZDBiYjlkMzk5NDcyNzIxZTQzYmM4MDZmNmZlZDkzODliNjdjMGU5MTU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RkoYZtOW7_oiGENBoxB9HDcBbNPsyGbsa85Kgd27jgI)
> > Screen.Recording.2024-06-20.at.11.29.16.AM.mov
> 
> I don't know why that was showing, I can't see this problem while testing

It's about this scenario:
- there is an active round 
- but this round will start in coming days

**Comment by Meriem-BM** [comment]
Yeah, I tested the same scenario

**Comment by maryjaf** [comment]
Yeah, it seems it has been resolved I've checked again and havn't seen this problem again

**Comment by Meriem-BM** [comment]
> * we might want to hide the "estimated matching" amount if the amount is less than $1.

@maryjaf, yes, it should not be shown when the estimated matching is low
