### ISSUE TITLE
Bug on PROD | receiving internal server error by setting wrong user address in url 

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3836]
**Describe the bug**
This user address is not correct 0xc46c67bb7e84490d7ebdd0b8ecdaca68cf3823f5
by entering this url: https://giveth.io/user/0xc46c67bb7e84490d7ebdd0b8ecdaca68cf3823f5 i got 500 error 

**Expected behavior**
appropriate error message should be shown like 404 or others,
backend developers know better than me

**Comment by jainkrati** [comment]
@RamRamez can you take a look from FE and BE side to debug this.

**Comment by RamRamez** [comment]
@maryjaf to test and verify

**Comment by maryjaf** [comment]
ُThanks @RamRamez it has been resolved on stg 
<img width="1233" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/b49ed967-7afb-44cf-a30e-f8ec1b080ce9">
