### ISSUE TITLE
Estimating Matching in QF round data export is wrong somehow

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3838]
The "real matching" calc has some issue because these two projects, should not BOTH be getting the matching "cap" of 10000 for the polygon round.

<img width="955" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/75490971/746e0a5a-7fe4-42cd-b709-24b87ad82d86">

I have no idea how we are calculating this or where the issue is, but the matchingshould basically be a function of the project weight & the matching for the round....

So... matching = matching fund * (projectA's project weight)/sum of all project weights

And then if any of those numbers are over the matching cap... we set the matching for that project to the matching cap... and recalculate the rest.. basically subtracting (matching cap) * (number of projects who have the matching cap) from the total matching fund... and then considering this the "new matching amount" that is distributed among the remaining projects.

Anyway.. this is how I do it in a spreadsheet.

Here is the master spreadsheet, for reference, so you can see what the data export is giving us and the weird issue.
https://docs.google.com/spreadsheets/d/1Wk8_bG75uQGZnVywos2Ii2t-4QosHoC0pRkMlZ85Ga8/edit#gid=1163918213

**Comment by laurenluz** [comment]
this is P0... but even if we don't solve it soon... .assuming that our project weight is calculated correctly, I can deduce the matching amounts manually in a spreadsheet.

**Comment by laurenluz** [comment]
@maryjaf have you tested this?

**Comment by maryjaf** [comment]
> @maryjaf have you tested this?

Today i'll start work on QF issues besides superfluid and let you know the result

**Comment by maryjaf** [comment]
I've been trying to test this issue but I got an error on stg by tapping on "return all donation data"  in admin 
please take look on this @mohammadranjbarz 

<img width="1354" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/a2c5ce39-7ca6-463b-8c52-b9bc53922985">

**Comment by mohammadranjbarz** [comment]
I guess this is duplicated and is like https://github.com/Giveth/impact-graph/issues/1421 that Ramin has fixed it.
@maryjaf  If it's the same please move this issue to QA column

**Comment by maryjaf** [comment]
> I've been trying to test this issue but I got an error on stg by tapping on "return all donation data" in admin please take look on this @mohammadranjbarz
> 
> <img alt="image" width="1354" src="https://private-user-images.githubusercontent.com/111529185/319089912-a2c5ce39-7ca6-463b-8c52-b9bc53922985.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNDk0NjIsIm5iZiI6MTcxMjE0OTE2MiwicGF0aCI6Ii8xMTE1MjkxODUvMzE5MDg5OTEyLWEyYzVjZTM5LTdjYTYtNDYzYi04YzUyLWI5YmM1MzkyMjk4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwM1QxMjU5MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNDNhNDhkY2Q1ZGYwNjY3MjgxYzA3MDgxYWUzNWY2YWVmMDI3NGUyMTcyMmNhZjlkNWE3Y2M2NzA2ZDU4Nzk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aAyvBjO7Vw_KVbq3fyfnksMXF5tbRF9lY4kbJBl9eIU">

@mohammadranjbarz this problem is related to  QF round

**Comment by mohammadranjbarz** [comment]
@maryjaf  I fixed

> I've been trying to test this issue but I got an error on stg by tapping on "return all donation data" in admin please take look on this @mohammadranjbarz
> 
> <img alt="image" width="1354" src="https://private-user-images.githubusercontent.com/111529185/319089912-a2c5ce39-7ca6-463b-8c52-b9bc53922985.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1Njk0NTMsIm5iZiI6MTcxMjU2OTE1MywicGF0aCI6Ii8xMTE1MjkxODUvMzE5MDg5OTEyLWEyYzVjZTM5LTdjYTYtNDYzYi04YzUyLWI5YmM1MzkyMjk4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOFQwOTM5MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZWEwNzQ5NTNmNGM0NWQ5MmFiYzcyNjQ1MmYwM2QwZjA5YTI1NzdjYmFkOTcwNDlhMDlhMTI5NDZmMGNmMDg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XxrJyFIWgzP5Pehq3FDVdZ_0WAYETalkN3GE4miRL_Q">

@maryjaf  I fixed this problem and you can test it on Staging now

**Comment by maryjaf** [comment]
Real matching fund and project weight is shown empty 

How project weight should be set for the projects? it should be valued and after that the real matching fund be calculated based on weight and fund and cap amount and, am I right?
<img width="1253" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/d45045f8-e327-4b85-a1b7-b2521369c221">
@mohammadranjbarz

**Comment by maryjaf** [comment]
> Real matching fund and project weight is shown empty

there is some test data problem on stg like this item that i've mentioned and I couldn't do a exact test on stg 
So I've checked the report of QF round id 6 on production that lauren mentioned there were some bug on that 
and I see that  for some project the real matching is more than 10000 , although  the maximum reward was set 0.04 and the fund wa 250,000 
I think the real matching mustn't be more that 10000, am I right ? @mohammadranjbarz 

<img width="1360" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/e22935b7-73ac-4461-a824-13fcc7e80103">

**Comment by laurenluz** [comment]
yep @maryjaf you're right - the matching shouldn't be over 10k for any single project with that matching cap.

**Comment by maryjaf** [comment]
> Real matching fund and project weight is shown empty
> 
> How project weight should be set for the projects? it should be valued and after that the real matching fund be calculated based on weight and fund and cap amount and, am I right? <img alt="image" width="1253" src="https://private-user-images.githubusercontent.com/111529185/320485644-d45045f8-e327-4b85-a1b7-b2521369c221.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2OTI4MzgsIm5iZiI6MTcxMzY5MjUzOCwicGF0aCI6Ii8xMTE1MjkxODUvMzIwNDg1NjQ0LWQ0NTA0NWY4LWUzMjctNGI4NS1hMWI3LWIyNTIxMzY5YzIyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMVQwOTQyMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MzRkZGJlNDBkNTY4NmMyMzRjYzhhYmY0ZWFmYjZiYmQ0MjFhMDY5OTQ5ZWZjNDdlNmU1ZDgwMWYxYzY5MzUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oeWyji6RbkMTk9_silMJiF3RuE9bGBoCxt8hB10Csm0"> @mohammadranjbarz

I couldn't test this issue on stg because Real matching fund and project weight are empty  @mohammadranjbarz @jainkrati 
I had tested last changes on prod and there was a bug, I'm not sure it has been resolved or not

**Comment by maryjaf** [comment]
> > Real matching fund and project weight is shown empty
> 
> there is some test data problem on stg like this item that I've mentioned and I couldn't do a exact test on stg So I've checked the report of QF round id 6 on production that lauren mentioned there were some bug on that and I see that for some project the real matching is more than 10000 , although the maximum reward was set 0.04 and the fund wa 250,000 I think the real matching mustn't be more that 10000, am I right ? @mohammadranjbarz
> 
> <img alt="image" width="1360" src="https://private-user-images.githubusercontent.com/111529185/320550332-e22935b7-73ac-4461-a824-13fcc7e80103.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2OTI4MzgsIm5iZiI6MTcxMzY5MjUzOCwicGF0aCI6Ii8xMTE1MjkxODUvMzIwNTUwMzMyLWUyMjkzNWI3LTczYWMtNDQ2MS1hODI0LTEzZmNjN2U4MDEwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMVQwOTQyMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNjJhNzg5MzIzNjk1ZjM2YzJlYzY5NDE5YWI5NzRiZWRlOTJmZTg5YzViNDkxOThiMDFkMDY2ZTljNDNjODJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-l3rl1JEMsjShDYC9qCUHu0iH3iBUGNCCVvIOjIGs-w">

**Comment by mohammadranjbarz** [comment]
@maryjaf  I think we can test it on production after release and if still exists we should fix it and maybe prepare something to ca be tested on Staging


JFYI @maryjaf

**Comment by jainkrati** [comment]
do you agree to test this on production @maryjaf

**Comment by maryjaf** [comment]
> I couldn't test this issue on stg because Real matching fund and project weight are empty @mohammadranjbarz @jainkrati
> I had tested last changes on prod and there was a bug, I'm not sure it has been resolved or not

Yeah, I'll test again on prod after release 
I couldn't test it on stg because Real matching fund and project weight are empty.

and it would be good if this problem be resolved that we be able to test on stg before production for next similar issues

**Comment by maryjaf** [comment]
> yep @maryjaf you're right - the matching shouldn't be over 10k for any single project with that matching cap.

I've checked again the report of round id=6 on prod after release, but still there are records with real matching fund more than cap (10 K) @CarlosQ96 @jainkrati 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/0f7f3bf2-e5ed-4477-9ea9-599d7a4933e9)

https://docs.google.com/spreadsheets/d/1Wk8_bG75uQGZnVywos2Ii2t-4QosHoC0pRkMlZ85Ga8/edit#gid=957953001

**Comment by maryjaf** [comment]
> I've checked again the report of round id=6 on prod after release, but still there are records with real matching fund more than cap (10 K) @CarlosQ96 @jainkrati
Thanks @CarlosQ96 
I've checked again and this problem has been resolved on prod
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/86c82c02-53a9-4323-806d-66739fc945ba)
Could you please approve this also ? @laurenluz

**Comment by laurenluz** [comment]
no there is still some issue guys. The project weight should not be the same for all the projects who hit the cap. 

@CarlosQ96 I think we talked about this.

The project weight should be a pure calculation... considering all value donations...
the real matching fund should impose the cap.

cc @koday1

**Comment by maryjaf** [comment]
> The project weight should be a pure calculation... considering all value donations...

This problem has been resolved on production, I move it to "Close"
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/1f2affdd-edca-4263-8a1b-5ee5424eacd2)
