### ISSUE TITLE
Update Banner on QF round page for ENS builders round - on production by March 20 latest

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3849]
We should have the banner looking like this :) on https://giveth.io/qf

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/9816ca8e-9d0a-42b5-a54d-0e109971fc96)

Here is the link to figma: https://www.figma.com/file/W9Ace1RyCdykWM72fsSa3t/Giveth-Marketing-2024?type=design&node-id=6072-1579&mode=design&t=MYXXu1uiSqF5NUr4-4

**Comment by laurenluz** [comment]
@jainkrati - can we make sure this is on prod by wed? I don't see anyone assigned yet

**Comment by jainkrati** [comment]
@alireza-sharifpour can pls work on this today

**Comment by laurenluz** [comment]
@alireza-sharifpour is on vacation March 20-21 - who can help get this on prod tomorrow? 😄 

@mateodaza @MohammadPCh @RamRamez @divine-comedian ?

**Comment by divine-comedian** [comment]
Should be good to go in this PR - https://github.com/Giveth/giveth-dapps-v2/pull/3868

You'll need to update the Round Name and the start time in the admin, no?
![Screenshot from 2024-03-19 17-27-18](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/b77ec1aa-ac96-43db-82b4-be217ff1ebba)

**Comment by jainkrati** [comment]
@mateodaza can you pls take this up

**Comment by mateodaza** [comment]
> Should be good to go in this PR - #3868
> 
> You'll need to update the Round Name and the start time in the admin, no? ![Screenshot from 2024-03-19 17-27-18](https://private-user-images.githubusercontent.com/67759413/314263189-b77ec1aa-ac96-43db-82b4-be217ff1ebba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4OTQ4OTEsIm5iZiI6MTcxMDg5NDU5MSwicGF0aCI6Ii82Nzc1OTQxMy8zMTQyNjMxODktYjc3ZWMxYWEtYWM5Ni00M2RiLTgyYjQtYmUyMTdmZjFlYmJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDAwMjk1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmZmZhYzRkNzFjMWViZTUyZmZiY2ZiNzBkNzJhZTRmMDc1NTU0Mzk1MzkzZjZkZDU3Yjk4ZTY1NWU4OTI2NjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._FV1nZyDIzqXMoiIt1OvfxPCM27pVYHHMBR08VHT1D0)

yes those come from the admin
