### ISSUE TITLE
Review homepage content allignment

### ISSUE THREAD

**Issue by jahanzaib-jay** [Giveth/giveth-dapps-v2#385]
On the home page, under the GIVeconomy section, the alignment of subheadings "For projects" and "For Givers" seems a bit off. 

"For Givers" part should be slightly moved further right- similar to the "Calling all changemakers section.

![Screenshot_4.png](https://images.zenhubusercontent.com/620d7be8f7acb77200f9d2d9/a69ff744-8084-4f6c-b15d-6040485987ec)

![Screenshot_5.png](https://images.zenhubusercontent.com/620d7be8f7acb77200f9d2d9/4f76bc06-96f8-402c-a97c-080174e88a7f)

**Comment by jahanzaib-jay** [comment]
@mosaeedi Can you please have a look?

**Comment by divine-comedian** [comment]
the alignment will vary depending on your screen resolution but everything seems to look good! 
![image](https://user-images.githubusercontent.com/67759413/163680214-39f70223-e2e0-4063-b001-e7bb73ce8dc5.png)

moving to DONE
