### ISSUE TITLE
There is at least one project in the Polygon round not included in the qf data export who should be

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3855]
this project: https://giveth.io/project/celuvplay

is not on the data export, but you can see they have several in-round donations are were part of the round. this is really concerning... are there others we missed???

We need to be SURE

@jainkrati @mohammadranjbarz @CarlosQ96

**Comment by mohammadranjbarz** [comment]
> this project: https://giveth.io/project/celuvplay
> 
> is not on the data export, but you can see they have several in-round donations are were part of the round. this is really concerning... are there others we missed???
> 
> We need to be SURE
> 
> @jainkrati @mohammadranjbarz @CarlosQ96

@laurenluz All of user are non eligible as they didn't have passport score at donation time.( and lots of them don't have passport score now)
So I think everything is cool

<img width="1088" alt="Screenshot 1402-12-24 at 5 32 12 in the afternoon" src="https://github.com/Giveth/giveth-dapps-v2/assets/9850545/bad235e1-4352-4662-a77d-14d7469b7389">
