### ISSUE TITLE
Audit QF round data export code to check all edge cases!

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3856]
Since we had so many bugs & edge cases, we should do an audit of our export code & check it all again to make sure it meets all requirements w/ no funny stuff.

In our call, we discussed re-comparing the code w/ Gitcoin and also reassessing Gitcoin's code to see if they were/are doing anything we may have missed (for example, we just recently added in the minimum donation threshold setting).

I made this requirements notion here: https://www.notion.so/giveth/Quadratic-Funding-Data-Export-Acceptance-Criteria-e0a8a0b30f81405fbc1d2c97aa5ecbac

From @CarlosQ96 in the GIVeconomy call:

> 1. The formula is copied 1 on 1 with Gitcoin. But there might be side effect from external files that weren't visible. (like grouping 1 donor donations).  I know because we did tons of testing manually and the values made sense at the time, even with their calculator in their website.
> 2. We had to add the multiple addresses to the spreadsheet. Since we did many changes recently and we cross join many data. Any added data we decide we need to make sure no side effects occur.
> 3. We generate the qf data multiple times through the week, and edit sybils/frauds. This time frame opens for the user to make changes to the project which might affect a calculation. I'd suggest we take a project addresses and some data snapshot of sorts.
> As mohammad is said a good start is adding tests for specific edge cases. 

Then from @jainkrati:

> For fixing #3, what do you suggest @laurenluz, should we limit the times we generate QF data or freeze projects from editing their project data?

I don't think it's possible for us to put a limit on the times we generate data... because sometimes it takes longer to do analysis, then we find issues. Basically, I don't have the confidence that our systems are working well enough to impose this kind of restriction on my own ability to do analysis... but I think an edit freeze could be an option... some ideas (for validation):
- We could make a "history of project recipient addresses" for each chain and attribute this to each project. Maybe we can label on as "current" and others as "past". And then keep all these addresses in consideration when calculating the results.
- We could make it impossible for a project to edit their recipient addresses during a QF round (but still allow them to add "new" chain addresses if they had none before)... and then keep some record of what the project's recipient address for the round.. Then on the data export the "recipient address field" should show only those recipient addresses that were "locked in" during QF rounds.

wdyt?

**Comment by laurenluz** [comment]
I'll post other small issues here as comments to be resolved...

the project link in the export is missing "/project/" 
![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/8e7abd0e-220a-435c-8a11-af835a7eb817)

**Comment by laurenluz** [comment]
Polygon round - somehow this project https://giveth.io/project/public-optimism was missed completely on our old export but in the new data, has a valid donation and more than 50 matic of matching...

You can check March 11 export vs. March 15 export on the master spreadsheet https://docs.google.com/spreadsheets/d/1Wk8_bG75uQGZnVywos2Ii2t-4QosHoC0pRkMlZ85Ga8/edit#gid=297407251

**Comment by jainkrati** [comment]
I am setting up 30 min each day to pair program and review existing code along with @mohammadranjbarz and @CarlosQ96

**Comment by laurenluz** [comment]
I see this rolling into @maryjaf's court. Can I get an update of the conclusions? Did we re-compare our code with gitcoin's?

I would love to see some clear documentation explaining how we are calculating parts, and the names of the variables, etc.

**Comment by mohammadranjbarz** [comment]
> I see this rolling into @maryjaf's court, but before she does any testing... @mohammadranjbarz Can I get an update of the conclusions? Did we re-compare our code with gitcoin's?
> 
> I would love to see some clear documentation explaining how we are calculating parts, and the names of the variables, etc.

No decision has been made, I just assigned it to @maryjaf  like other issues that I move it to QA column :))
about documentation no we don't have it right now, we just added some test cases that make it easier to understand for developers but for non technical persons we don't have anything about it right now.
@laurenluz  @jainkrati 
I think it's necessary, so should I move this issue to In-Progress?

**Comment by laurenluz** [comment]
yes please!! @mohammadranjbarz
