### ISSUE TITLE
Add to QF round data export exceptions - projects can't donate in the round & qualify for matching

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3857]
Any donation made from a project recipient address of a project that is part of the active QF round (verified or not) to any other project in the round should be considered “ineligible for matching”.

@CarlosQ96 do you have time to add this today to the export? 😮‍💨 this condition missing is messing up the final data for the polygon round, and I promised to update it today.

cc @jainkrati

**Comment by laurenluz** [comment]
I imported the entire list of "recipient address" for the polygon round as the "sybil list", so this issue can also wait if superfluid is being blocked
I reposted the final results for polygon to the forum today

**Comment by maryjaf** [comment]
Is there a way to found for what reason  the donation isn't recognized eligible for matching fund ? @mohammadranjbarz 
I've tested this scenario: 
-I donated with wallet address to a project in a round 
 -This wallet address is recipient address for another project in this round 
-and this donation isn't shown in "donationIdsAfterAnalysis" column correctly 
but I'm not sure the reason of not showing is this or not, is there a way to be sure?

**Comment by mohammadranjbarz** [comment]
> Is there a way to found for what reason the donation isn't recognized eligible for matching fund ? @mohammadranjbarz I've tested this scenario: -I donated with wallet address to a project in a round -This wallet address is recipient address for another project in this round -and this donation isn't shown in "donationIdsAfterAnalysis" column correctly but I'm not sure the reason of not showing is this or not, is there a way to be sure?

Can we have a call after the SuperFluid release for this?
Now I'm not focus enough to know what happening there

**Comment by laurenluz** [comment]
I can help set it up, when is the release happening? @mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
> I can help set it up, when is the release happening? @mohammadranjbarz

Thanks @laurenluz 
We have some bugs that should be fixed, but next week I'm Off, I guess we can have a call for a week after that

**Comment by laurenluz** [comment]
@jainkrati The ENS team is waiting for us to give them the distribution of funds ASAP. We have already done the data analysis & identified which addresses are sybil...

So I need these bugs fixed ASAP.

It really can't wait a full week until we can work on it!!

**Comment by laurenluz** [comment]
realized that I got Kieran to make a redundant issue: https://github.com/Giveth/giveth-dapps-v2/issues/4011 (closing that one).

@CarlosQ96

**Comment by maryjaf** [comment]
> Is there a way to found for what reason the donation isn't recognized eligible for matching fund ? @mohammadranjbarz I've tested this scenario: -I donated with wallet address to a project in a round -This wallet address is recipient address for another project in this round -and this donation isn't shown in "donationIdsAfterAnalysis" column correctly but I'm not sure the reason of not showing is this or not, is there a way to be sure?

I had tested this issue,  could you please take a look on this comment @CarlosQ96 @mohammadranjbarz 
and one more thing now I got 404 from "/staging/purpleList " request
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/8a6bea97-f26a-47cd-81dd-139427f62fcf)

**Comment by jainkrati** [comment]
@CarlosQ96 pls take a look at the edge case mentioned by Maryjaf.

**Comment by CarlosQ96** [comment]
ENS data export was done.  This was fixed with the purple list fix earlier this week. @mohammadranjbarz could you take a look at the givback app why is down? We tested in prod and it worked fine.

**Comment by laurenluz** [comment]
@maryjaf I see you moved it to done - was the GIvbacks issue resolved? or is that a separate issue and we can close this?

**Comment by maryjaf** [comment]
> I got 404 from "/staging/purpleList " request

Yeah, for testing I needed to check the purple list and I got an error form swager, I checked with @mohammadranjbarz and he sent me a query to check the purple list 
but the problem related to swager hasn't been fixed yet, but It is not related to this issue exactly
I'll check with @mohammadranjbarz again and if needed a I'll create separate issue

**Comment by laurenluz** [comment]
ok thank you! @maryjaf 

if you create a new issue  please tag me & @koday1 so I can keep an eye on it

**Comment by maryjaf** [comment]
> ok thank you! @maryjaf
> 
> if you create a new issue please tag me & @koday1 so I can keep an eye on it

> and one more thing now I got 404 from "/staging/purpleList " request

I've checked with @mohammadranjbarz and it seems this is a devops problem and it should be checked by @mhmdksh
