### ISSUE TITLE
P1 - Missing donation

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#3861]
While doing GIVbacks review, i noticed that this donation to pairwise for 0.045 ETH  at 2024-02-10-03:16:24 is not displayed on the Pairwise donation list here: https://giveth.io/project/pairwise-simplifying-choices-amplifying-voices	

Here is a link to the donation. https://optimistic.etherscan.io/tx/0x67d0ae4562ba68bfc305dbedd016f3a09e3775e163f54a491f58673f96155250		

Really curious if other donations are missing too....

**Comment by jainkrati** [comment]
@aminlatifi could you take a look at this and confirm if donation draft service has some bugs/edge cases to be handled due to which this went missing

**Comment by aminlatifi** [comment]
@GriffGreen 
The donation already exists in database, verified with correct values in the fields I checked.
Attached the record data here
[data-1710862748011.csv](https://github.com/Giveth/giveth-dapps-v2/files/14652885/data-1710862748011.csv)

**Comment by jainkrati** [comment]
@GriffGreen let us know how you verify the presence / absence of a record.
