### ISSUE TITLE
RegenFarms: Missing Tooltip

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#387]
When you mouse over the "?" on the FOXstream flowrate... should say "Your FOXstream flowrate"

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/1e2a951d-ac44-477f-accf-be5600a1d4fb)

**Comment by divine-comedian** [comment]
testing on `staging.giveth.io` 

looks like the `?` has been removed 
I can see the code has been commented out - looks like some formatting error waiting to be fixed
is this the intended functionality @pkretzschmar ? Is this a quick fix so we can launch?

![image](https://user-images.githubusercontent.com/67759413/161098206-f951d622-cd87-49a9-8f61-a489a837bef8.png)

**Comment by pkretzschmar** [comment]
Due to a bug with the tooltip, @laurenluz requested to remove it

**Comment by divine-comedian** [comment]
testing on `staging.giveth.io`
aaaand it's gone! 

calling this done for now

![image](https://user-images.githubusercontent.com/67759413/161350099-668e5686-feeb-4298-9653-0712a3f4f5b8.png)
