### ISSUE TITLE
problem of loading Icon in project creation flow 

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3873]
> @maryjaf to test and verify No functionality has been changed in this PR and no new functions has been added. Just general testing is needed like donating, creating a project, testing AdminJS functionality, etc

by tapping on "preview"or "publish" in project creation flow, the loading icon is shown for both button  

https://github.com/Giveth/impact-graph/assets/111529185/d9281836-11de-40ac-a7d6-793f0c67f552

_Originally posted by @maryjaf in https://github.com/Giveth/impact-graph/issues/1405#issuecomment-2013751553_

**Comment by Reshzera** [comment]
@maryjaf @LatifatAbdullahi This Issue is ready to be tested on the staging, could you please take a look?

**Comment by LatifatAbdullahi** [comment]
@Reshzera @maryjaf 

This issue is fixed on my end.
@maryjaf You can also check from your end.



Uploading Create a Project on Giveth with Zero Fees - Google Chrome 2024-07-31 19-42-59.mp4…

**Comment by maryjaf** [comment]
Thanks guys 
yeah, It has been fixed on staging.
