### ISSUE TITLE
Bug in showing balance of super token to donate to another project

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3877]
-My user has an active recurring donation and the "Current stream Balance" is shown 0.001984
ETHx 
-I select another project in list of projects to donate, in donation page I could select all of 0.001984
ETHx to donate to this new project 
It seems this behavior is buggy and it should be checked again
cc: @MohammadPCh @divine-comedian 

<img width="1382" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/3eb2dbb1-15f8-4768-a50f-bbd3b2ab17c0">
<img width="1131" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/b19ab81c-fa7f-490d-a91c-5a5136ece083">
__________

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/30b990c9-2f8c-487a-97d7-c3cf346ee55c

**Comment by divine-comedian** [comment]
@maryjaf @MohammadPCh 

I tested this some more - looks like this affects ONLY projects that do not have any recurring donation. 

Normally when you have other active recurring donations and use the slider at some point it will prevent you from proceeding if you choose to donate monthly an amount that would cause your stream balance to last less than one month. 

This functionality should be applied evenly for projects that have not received any recurring donations. 


https://github.com/Giveth/giveth-dapps-v2/assets/67759413/89a460c6-ace2-454d-9f45-f6ac1400cf53


https://github.com/Giveth/giveth-dapps-v2/assets/67759413/63c13926-49ad-462f-942a-afb2c74e9a5c

**Comment by maryjaf** [comment]
> Normally when you have other active recurring donations and use the slider at some point it will prevent you from proceeding if you choose to donate monthly an amount that would cause your stream balance to last less than one month.

Yeah exactly

**Comment by MohammadPCh** [comment]
@maryjaf @divine-comedian please check it again on staging 😄  Thanks.

**Comment by maryjaf** [comment]
I couldn''t reproduce above problem on stg again, If you have a time please take a look if it happens for you or not @divine-comedian 

but I see different behavior for 2 project  like as below video

- my user is maya maya 0xf577Ae8b97d839B9c0522A620299DC08792c738c
-when I select "testtt" project that I have not  donated to this yet, the scroll bar is red and I couldn't set any amount for. donation
-when I select one project that I've donated to that, I could set a small amount for donation
-I don't understand what is the difference between these project and if this behavior is expected or not 



https://github.com/Giveth/giveth-dapps-v2/assets/111529185/683bca4e-4490-4513-a40c-4dace167886e

**Comment by divine-comedian** [comment]
It took me some time to figure this one out but I think I know why! 

When you're creating a new recurring donation it is adding a new amount to your total stream rate (for all your ETHx balance) 

When you are modifying your recurring donation you can actually reduce the amount you donate monthly to this project - so you can see the part of the slider that is not red is actually modifying your donation to donate less than you are currently for that project, which is why it lets you proceed. 

Does this make sense?
