### ISSUE TITLE
Bug in "filter" of recurring donation tab and "switch to archive donation"

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3885]
**Describe the bug**
I was not sure if  is there a separate issue for this section of recurring donation tab or not and I've created this new bug 

- [x] -By setting "active" or "ended" option in filter, all of donations are shown regardless of their status

-like as below screen record, some times one donation isn't shown in the list and by refreshing this problem be  will resolved 

please take a look on below screen record 

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/4da3c1e8-fffc-4ab8-9481-8050aea0beba

cc: @MohammadPCh @divine-comedian

**Comment by maryjaf** [comment]
2- besides above problem the " switch to archive donation" option doesn't work

**Comment by divine-comedian** [comment]
Thanks @maryjaf - good catch 

When the toggle is on archived donations should not be shown on the list, this should be on by default, the user should toggle it off to show their archived recurring donations.

**Comment by MohammadPCh** [comment]
@maryjaf Thanks, It seems there is a bug in BE, @mohammadranjbarz Could you please take a look?
this is my variables:
```
{
  "userId": 168,
  "take": 10,
  "skip": 0,
  "orderBy": {
    "field": "createdAt",
    "direction": "DESC"
  },
  "finishStatus": {
    "active": true,
    "ended": false
  },
  "filteredTokens": [],
  "includeArchived": false
}
```
but the result has some ended donations.

**Comment by mohammadranjbarz** [comment]
> @maryjaf Thanks, It seems there is a bug in BE, @mohammadranjbarz Could you please take a look? this is my variables:
> 
> ```
> {
>   "userId": 168,
>   "take": 10,
>   "skip": 0,
>   "orderBy": {
>     "field": "createdAt",
>     "direction": "DESC"
>   },
>   "finishStatus": {
>     "active": true,
>     "ended": false
>   },
>   "filteredTokens": [],
>   "includeArchived": false
> }
> ```
> 
> but the result has some ended donations.

It's because all ended donations are not archived, so when you send ` "includeArchived": false` still might be some ended recurring donations that are not archived

**Comment by mohammadranjbarz** [comment]
@MohammadPCh  We had some recurring donation records in DB that were `status: ended` with `finished:false` I updated those records manually in DB and it seems fine, but if you faced this again please let me know

**Comment by maryjaf** [comment]
Thanks guys
Item 1 related to filter has been resolved
and about "switch to archive donation" toggle, by enabling this option all of donations included archive , active and ended be shown , is that ok? or only archive donations should be shown ?
@divine-comedian @MohammadPCh 
<img width="1283" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/156e4631-0cb0-4381-a402-f2359676d317">

**Comment by divine-comedian** [comment]
@maryjaf  

As I've explained in multiple places - This toggle should either hide or include archived donations in the table - if its toggled then we show archived donations alongside all other statuses, if it is toggled off we hide archived donations from the table.

**Comment by maryjaf** [comment]
Sorry, I didn't get this

Thanks guys, all problems have been resolved
