### ISSUE TITLE
Bug in recurring donation in user page

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3886]
**Describe the bug**

- [x] 1- by tapping on for example this user link : https://staging.giveth.io/user/0xf577ae8b97d839b9c0522a620299dc08792c738c?tab=donations

recurring donation table isn't shown 

<img width="1203" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/eccb7a8d-2212-4598-9ef8-8e81ec070bf4">

________

- [x] 2- Number of donations and total donation amount are same for both one time and recurring donation 

<img width="1307" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/a95cebe5-a4aa-4113-8d9b-ec6ef63d0ada">

cc: @divine-comedian @MohammadPCh

**Comment by alireza-sharifpour** [comment]
This is the filtering issue and @MohammadPCh is working on it.
 The way backend handles the filters is changed so we need to change accordingly.
CC: @divine-comedian

**Comment by MohammadPCh** [comment]
@divine-comedian @maryjaf The query is updated and working fine now, Maybe we can add a loading in the future,
but for donations count and total donations, we need to update them in the backend. @mohammadranjbarz could you please take a look? we use this variables: `donationsCount` and `totalDonated`

**Comment by maryjaf** [comment]
> [ ] 2- Number of donations and total donation amount are same for both one time and recurring donation

> but for donations count and total donations, we need to update them in the backend. @mohammadranjbarz could you please take a look? we use this variables: `donationsCount` and `totalDonated`

Should this item be resolved for this phase of superfluid ?

**Comment by mohammadranjbarz** [comment]
> @divine-comedian @maryjaf The query is updated and working fine now, Maybe we can add a loading in the future, but for donations count and total donations, we need to update them in the backend. @mohammadranjbarz could you please take a look? we use this variables: `donationsCount` and `totalDonated`

Do you mean we don't count recurring donations in `donationsCount` and `totalDonated`

**Comment by divine-comedian** [comment]
need to know which webservice and which fields to debug problem for @mohammadranjbarz

**Comment by maryjaf** [comment]
> need to know which webservice and which fields to debug problem for @mohammadranjbarz

Should this issue be assigned to Mohammad?

**Comment by mohammadranjbarz** [comment]
@

> need to know which webservice and which fields to debug problem for @mohammadranjbarz

@MohammadPCh  Would appreciate it if you can pass me more information as Mitch said here

**Comment by MohammadPCh** [comment]
@maryjaf @divine-comedian 
Regarding the design, the contribute card that shows the donations count and the total donated amount is upper than the donation type tab selector, so as I know it shouldn't change by selecting each tab.
I mentioned that if you want to show recurring donations and one-time donations info separately, we need the BE to send them separately. also, we need to change the design and move the card into the tabs.
let me know what's your decision. and if you need changes please ask @mohammadranjbarz to provide these info in this query:
```
query UserByAddress($address: String!) {
    userByAddress(address: $address) {
        id
        firstName
        lastName
        name
        email
        avatar
        walletAddress
        url
        location
        totalDonated
        totalReceived
        likedProjectsCount
        projectsCount
        donationsCount
        isSignedIn
        passportScore
	    passportStamps
	    boostedProjectsCount
        chainvineId
		isReferrer
		wasReferred
    }
}
```

**Comment by divine-comedian** [comment]
I think I understood what you're trying to say...

For the upper component we shouldn't need to show them separately, but for each new recurring donation made it should increase the donation count for the user. Similarly the USD value of total donations should increase with recurring donations

**Comment by MohammadPCh** [comment]
@mohammadranjbarz @maryjaf @divine-comedian I suggest cutting the scope for this phase, and just make sure that our `totalDonated` and `donationsCount ` is correct. wdyt?

**Comment by maryjaf** [comment]
I agree , but now these numbers aren’t correct and should be checked

**Comment by MohammadPCh** [comment]
@maryjaf can you check with @mohammadranjbarz , Thanks.

**Comment by MoeNick** [comment]
Total Donated (value and amount) should be the sum of normal and recurring donations.
This is buggy on the Profile Page @mohammadranjbarz pls check.

**Comment by maryjaf** [comment]
https://staging.giveth.io/user/0xa1179f64638adb613ddaac32d918eb6beb824104?tab=recurring-donations
@mohammadranjbarz

**Comment by MoeNick** [comment]
Yes, @mohammadranjbarz we need the total (amount and value) will include the recurring ones, NOT ONLY for this view but also everywhere.

**Comment by maryjaf** [comment]
So after that this changes be applied on "DONATIONS RECEIVED" count and amount, I'll move this issue  to Done @MohammadPCh @MoeNick

**Comment by maryjaf** [comment]
> and I need to check this fields also in project page if there are problems in these fields I'll create separate issue
i've created this new issue for problems related to showing count and amount of donations  in project page

https://github.com/Giveth/giveth-dapps-v2/issues/3968

**Comment by maryjaf** [comment]
> So after that this changes be applied on "DONATIONS RECEIVED" count and amount, I'll move this issue to Done 

I move this issue to don and I track the status of this problem on https://github.com/Giveth/giveth-dapps-v2/issues/3968
@mohammadranjbarz @MoeNick
