### ISSUE TITLE
Bug on project card image? 

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3899]
Eth Limo reported that their banner image is behaving weirdly. Is this a bug? What is the issue?

@divine-comedian @jainkrati 

Project card:
![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/496963e0-ee95-412a-bbd4-9c109fb22cfe)

Banner on project page:
![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/fbfb655a-8cc3-424f-8546-ee99e845cde4)

Project link: https://giveth.io/project/ethlimo

If it's a bug, would be nice to fix asap because they are in the QF round now.

**Comment by divine-comedian** [comment]
I checked it out... looks like they were unlisted - maybe they made a change to their project, however when I relisted them it appears the banner image issue has been fixed! 
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/89e00900-0117-4ecc-b1ec-e4f3eb4850e3)

**Comment by alireza-sharifpour** [comment]
> I checked it out... looks like they were unlisted - maybe they made a change to their project, however when I relisted them it appears the banner image issue has been fixed!
> 
> Hard to tell if it was our fault or maybe they were confused with the image upload listing/unlisting process when they make project changes. ![image](https://private-user-images.githubusercontent.com/67759413/317098748-89e00900-0117-4ecc-b1ec-e4f3eb4850e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NDY5MzEsIm5iZiI6MTcxMTU0NjYzMSwicGF0aCI6Ii82Nzc1OTQxMy8zMTcwOTg3NDgtODllMDA5MDAtMDExNy00ZWNjLWIxZWMtZTRmM2ViNDg1MGUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDEzMzcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhZTZiMTg5NTkxMGJiNDMxMzViMTRjOWY1ZjI4YjA0ODZmNDI3NWQ4MTdjYTRkYjZlY2UzOWRlYjg3ZDI2NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bSHxD12TMgWDzb9bT0vbx4JcAcxUaUbd9_oGXpBgZuw)

I cannot see any issues with their image RN, Is there anything I can check on this issue? @divine-comedian

**Comment by divine-comedian** [comment]
Let's move it to done - it looks like upon relisting their project I can't see any issues with their banner image.

**Comment by laurenluz** [comment]
I see the chat here... but it was unlisted yesterday... then I listed it myself, found it in the search and I still saw the problem persisting...

I don't have an issue w/ like... seeing if it happens again, but either it was a one-off or loading-type bug... or soemthing else... but it was not happening just because the project was unlisted.

**Comment by divine-comedian** [comment]
> I see the chat here... but it was unlisted yesterday... then I listed it myself, found it in the search and I still saw the problem persisting...
> 
> I don't have an issue w/ like... seeing if it happens again, but either it was a one-off or loading-type bug... or soemthing else... but it was not happening just because the project was unlisted.

Very weird - if it happens again lets try to catch it - It looks like it resolved itself before I could investigate further what was going on.
