### ISSUE TITLE
ENS Swag shop bug - wrong image being shown when I size select

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3900]
**Describe the bug**
When I select a color other than the default... it shows me the correct image. but then when I pick the size... it toggles to the wrong color (even though pink, for example is selected).

see below:

https://github.com/GeneralMagicio/ens-merch-shop/assets/75490971/58f82c83-99e7-4560-9c86-9ef42a817386

**To Reproduce**

1. Go to https://www.ensmerchshop.xyz/product/customizable-women-s-t-shirt-1
3. Click on any color that's not the default
4. Click on any size
5. See error

**Expected behavior**
The color (or the arrow buttons) should be the only thing that toggles the image... if I select a size or change the size select, it should just show me the same image as the one that was auto-toggled to when I picked the color

@jainkrati would love get this in the pipe as a P0 - it's a weird bug and we are pushing a lot on ENS swag shop this week.... also... I think I don't have permissions for being able to post issues in the correct repo for ENS anymore... so I made it here... feel free to transfer: https://github.com/GeneralMagicio/ens-merch-shop

cc @ahmadabugosh

**Comment by alireza-sharifpour** [comment]
This is the first time I want to run this project and I need basic configs (ENV Variables) for this site to run the project.
Who has access to it? @jainkrati @laurenluz

**Comment by laurenluz** [comment]
Maybe @RamRamez or @ahmadabugosh can help!

**Comment by RamRamez** [comment]
@alireza-sharifpour I sent you the config in DM

**Comment by ahmadabugosh** [comment]
@alireza-sharifpour Added the issue on the ENS merch github too: https://github.com/GeneralMagicio/ens-merch-shop/issues/119

**Comment by jainkrati** [comment]
@RamRamez

**Comment by RamRamez** [comment]
@maryjaf to test and verify
