### ISSUE TITLE
Deduct transaction fee if user tries to donate/deposit max token balance

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3903]
To prevent users from accidentally donating or depositing all of their native tokens we should automatically subtract the estimated transaction fee from their available balances
 
If a user presses the button to input the max amount into an input field such as depositing into their stream balance or donating to a project we should input their native balance - estimated tx fee

If a user manually inputs an amount that exceeds this projected available balance we should throw a warning underneath the input field and prevent the user from continuing - they must lower the amount to continue 

The warning text should say: 

"You need to keep at least {amount} {native token} in your wallet to pay the network fees for this transaction. Please enter a lower amount."

---
to be clear this is a very niche error message, take for example: 

- user balance is 10 tokens
- they choose to donate 9.9
- network fee is 0.2
- the total cost of the tx would be 10.1

 which exceeds their balance, even though they are "donating" less than their balance the tx fee added would cause it to fail. so we show the error message.

----
 
 > @divine-comedian @maryjaf All issues have been resolved except case 11. @maryjaf can you reproduce it again? 
 > let's have a call and reproduce it together. but you can check all other issues on the staging environment.
> And case 11 happens when for example  the user has no super token and in donation flow after getting super token the > user's ETH balance change to lower than minimum for a donation transaction 
> in this scenario the above message is shown that it would be better a handle message be shown

_Originally posted by @maryjaf in https://github.com/Giveth/giveth-dapps-v2/issues/3091#issuecomment-2019840839_

**Comment by divine-comedian** [comment]
Are we still waiting to pick this one up?

**Comment by RamRamez** [comment]
@Reshzera could you please take it?

**Comment by Reshzera** [comment]
@RamRamez Yes, I'll take a look

**Comment by Reshzera** [comment]
@maryjaf @LatifatAbdullahi This Issue is ready to be tested on the staging, could you please take a look?

**Comment by maryjaf** [comment]
Could you please take a look on below screen record ? @Reshzera 

- by entering the number in box, the available amount is changed 

https://github.com/user-attachments/assets/470f64d7-eba0-4999-ae91-bf66e58f77e4

**Comment by Reshzera** [comment]
@maryjaf Sure

**Comment by Reshzera** [comment]
@maryjaf I just push a new PR to staging to correct this bug, could you please take a look?

**Comment by maryjaf** [comment]
> Could you please take a look on below screen record ? @Reshzera
> 
> * by entering the number in box, the available amount is changed

Thanks @Reshzera 
This problem has been fixed

one question
showing this long number in UI for gas fee is accepted? 
 0.000629999999895 

![image](https://github.com/user-attachments/assets/4e4f82cf-2b5e-43bc-903a-b9c3fd02a3a0)

**Comment by Reshzera** [comment]
@maryjaf I don't know I'll check with Mitch

**Comment by divine-comedian** [comment]
This doesn't look right @maryjaf @Reshzera 

If you are trying to donate MORE than your balance of tokens we should show an error related to "insufficient balance" which we already handle on the app


https://github.com/user-attachments/assets/849c1ff6-cb27-48e6-8a13-33fe96b90487


https://github.com/user-attachments/assets/c6718a05-2777-4abd-b980-79202db2b78e


please both of you have a look at these videos to properly understand the scenario where this error should be shown..

if I try to donate the max balance of a native token, it will fail in the MM because we are not accounting for the required gas fee. If as a user I try to manually input a donation amount that is NOT GREATER THAN MY TOTAL NATIVE TOKEN BALANCE but does not leave enough native token balance to cover the cost of the transaction THEN we should show the error message. 

IF I try to donate more than my total native token balance then we stick with showing the current insufficient wallet balance modal that is already in place.

**Comment by Reshzera** [comment]
@divine-comedian, I just realized, I didn't know about the modal telling the user they don't have enough funds. I'll fix it.

**Comment by Reshzera** [comment]
@maryjaf I just fix the problem that @divine-comedian mention and push it to the staging environment, I think now it's every thing correct

**Comment by maryjaf** [comment]
> This doesn't look right @maryjaf @Reshzera
> 
> If you are trying to donate MORE than your balance of tokens we should show an error related to "insufficient balance" which we already handle on the app
> 
>  Screencast.2024-08-01.10.24.02.mp4 
>  Screencast.2024-08-01.10.25.31.mp4 
> please both of you have a look at these videos to properly understand the scenario where this error should be shown..
> 
> if I try to donate the max balance of a native token, it will fail in the MM because we are not accounting for the required gas fee. If as a user I try to manually input a donation amount that is NOT GREATER THAN MY TOTAL NATIVE TOKEN BALANCE but does not leave enough native token balance to cover the cost of the transaction THEN we should show the error message.
> 
> IF I try to donate more than my total native token balance then we stick with showing the current insufficient wallet balance modal that is already in place.

These videos didn't play for me and I couldn't download them 
How ever this is the current behaviour that I've seen on staging


https://github.com/user-attachments/assets/71e3dfdc-527b-4a8f-b53a-10e39768a515

and I have some questions :

- My user has  0.897709 xdai token
-in donation page I see Available: 0.897709 and by tapping on the available this amount is changed and 0.897674(my balance - transaction gas fee ) is set for donation amount , Is this expected behavior ?

- If I set for example 0.8977 I see this error
You need to keep at least **0.0000346500** XDAI in your wallet to pay the network fees for this transaction. Please enter a lower amount.

- If I set 0.9 the "donate" button is enabled and by tapping on that I see the insufficient modal 

Is these scenarios are as expected ?

@divine-comedian @Reshzera

**Comment by maryjaf** [comment]
- [ ] It seems sth is changed in donation page and maybe it isn't related to exactly this issue 

@RamRamez had determined some limitation for donation to giveth in system , that it couldn't be lower than 0.000001 
and for example if user enters  0.000001 XDAI for donation by setting 5, 10, 15 , 20 % , the donation to giveth is set 0.000001

but now it is changed on stg and when I set 5, 10, 15 , 20 % for donation to giveth, it is shown 0 

in below screen record I try to show the behavior of system on stg and prod

@divine-comedian @Reshzera 

https://github.com/user-attachments/assets/fac2c1bb-05cd-4132-ac38-6a655e2aa3f5

**Comment by maryjaf** [comment]
> * [ ]  It seems sth is changed in donation page and maybe it isn't related to exactly this issue

Maybe it is related to this issue https://github.com/Giveth/impact-graph/issues/1710

**Comment by divine-comedian** [comment]
> > This doesn't look right @maryjaf @Reshzera
> > If you are trying to donate MORE than your balance of tokens we should show an error related to "insufficient balance" which we already handle on the app
> > Screencast.2024-08-01.10.24.02.mp4
> > Screencast.2024-08-01.10.25.31.mp4
> > please both of you have a look at these videos to properly understand the scenario where this error should be shown..
> > if I try to donate the max balance of a native token, it will fail in the MM because we are not accounting for the required gas fee. If as a user I try to manually input a donation amount that is NOT GREATER THAN MY TOTAL NATIVE TOKEN BALANCE but does not leave enough native token balance to cover the cost of the transaction THEN we should show the error message.
> > IF I try to donate more than my total native token balance then we stick with showing the current insufficient wallet balance modal that is already in place.
> 
> These videos didn't play for me and I couldn't download them How ever this is the current behaviour that I've seen on staging
> 
>  Screen.Recording.2024-08-04.at.10.45.00.AM.mov 
> and I have some questions :
> 
> * My user has  0.897709 xdai token
>   -in donation page I see Available: 0.897709 and by tapping on the available this amount is changed and 0.897674(my balance - transaction gas fee ) is set for donation amount , Is this expected behavior ?
> * If I set for example 0.8977 I see this error
>   You need to keep at least **0.0000346500** XDAI in your wallet to pay the network fees for this transaction. Please enter a lower amount.
> * If I set 0.9 the "donate" button is enabled and by tapping on that I see the insufficient modal
> 
> Is these scenarios are as expected ?
> 
> @divine-comedian @Reshzera

This is the correct behaviour! :tada:

**Comment by divine-comedian** [comment]
please take up investigation @Reshzera on the related bug MJ is reporting as I will be on vacation this week.

**Comment by maryjaf** [comment]
> please take up investigation [@Reshzera](https://github.com/Reshzera) on the related bug MJ is reporting as I will be on vacation this week.

kindly reminder

**Comment by maryjaf** [comment]
Thanks @Reshzera 
Is this change deployed on prod ?
after deploying on prod the issue could be changed into closed
