### ISSUE TITLE
Modal of "End  recurring donation" and "archive doantion"

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3905]
The format or copy of these modal should be changed 

- [x] **End  recurring donation:**

<img width="1196" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/ad41d8e7-96c6-4c81-b737-cc74e61f8210">

- [x] **Archive donation:**

before tapping on "Done" the modal will be  closed 

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/983c7b1e-4b38-4419-9962-3bbfdbec6cfd

cc: @MohammadPCh @divine-comedian

**Comment by divine-comedian** [comment]
Thanks @maryjaf 

@MohammadPCh 
We should fix the size of the title to be either H6 or B 

Also as MJ is mentioned when we archive or end a donation the step showing the confirmation and DONE button is only showing very briefly 1-2 seconds and closing automatically without the user clicking the DONE button - the modal should show until the user clicks DONE

**Comment by MohammadPCh** [comment]
@divine-comedian @maryjaf About the design, I can change the size to B or H6 (the component is not mentioned in the design).
but about closing automatically I checked the code, we don't have any code to close it automatically, besides that I checked it and it's working fine.

**Comment by divine-comedian** [comment]
Thanks Cherik - I was experiencing the same issue as MJ with the modal closing automatically... Very strange, let us know when we can retest this one.

**Comment by MohammadPCh** [comment]
@alireza-sharifpour could you check the closing automatically issue on your machine? because it's working fine for me

**Comment by alireza-sharifpour** [comment]
I tested this issue for automatically closing Done modal both on localHost and staging.

I tested and archived two on my localHost and non of them closed automatically.
I tested and archived two on staging and non of them closed automatically.

I wait for some minutes and also switched between tabs but it was ok.
@divine-comedian @maryjaf

**Comment by maryjaf** [comment]
Yeah I've also checked and now the modal isn't closed automatically but we have new problem that the status isn't changed from ended to archive 
and may be it is the reason that the previous problem doesn't happen
It seems there a new backend problem that should be checked I've reported in channel

**Comment by alireza-sharifpour** [comment]
After fixing archive issue I could see Automatically closing modal issue.
I fixed it in #3928 PR which is waiting for review.

**Comment by maryjaf** [comment]
Thanks @alireza-sharifpour this problem has been resolved
