### ISSUE TITLE
After modifying flow rate the page should be refreshed to see the change of  "Streaming at a Rate of" filed 

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3907]
After modifying flow rate the page should be refreshed to see the change of  "Streaming at a Rate of" filed 

**To Reproduce**
1. Go to 'my donation'
2. Select one active recurring donation
3. Tap on "modify flow rate"
4. complete modifying flow 

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/c84289a3-7a71-4ab8-be91-b1689770ce41

cc: @MohammadPCh @divine-comedian

**Comment by maryjaf** [comment]
Yeah the status in  table was updated when I ended a recurring donation

**Comment by maryjaf** [comment]
ُThis problem hasn't been assigned to developers @divine-comedian

**Comment by divine-comedian** [comment]
@MohammadPCh - Can you pick this one up or assign it to @alireza-sharifpour if it is more appropriate?

**Comment by divine-comedian** [comment]
@alireza-sharifpour  send the webservice you call and fields you use for showing in the streaming at a rate of column to @mohammadranjbarz

**Comment by maryjaf** [comment]
> After modifying flow rate the page should be refreshed to see the change of "Streaming at a Rate of" filed
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to 'my donation'
> 2. Select one active recurring donation
> 3. Tap on "modify flow rate"
> 4. complete modifying flow

This problem hasn't been resolved 
I modified the active donation and "Amount" filed in recurring donation was updated correctly like as before, but the "Streaming at a Rate of" filed in  Streamable Token Balances table wasn't changed and by refreshing the update wasn't applied 


https://github.com/Giveth/giveth-dapps-v2/assets/111529185/c221edd8-c0c2-4dc4-83ba-760fc8289c26

and based on below video I see the amount of "testhamid" is 60 GIV in recurring donation table but by tapping on modify in the modal I see 160 GIV


https://github.com/Giveth/giveth-dapps-v2/assets/111529185/b2acbed1-7476-4f67-a573-783d8df87b96

**Comment by divine-comedian** [comment]
Could this be related to the subgraph syncing issues from today?

**Comment by maryjaf** [comment]
It hasn't been resolved yet @MohammadPCh

**Comment by maryjaf** [comment]
> Could this be related to the subgraph syncing issues from today?

it seems yes,
Today I haven't seen the above problem but still after modifying flow rate the page should be refreshed to see the changes of "Streaming at a Rate of" field in "Streamable Token Balances" table
@MohammadPCh

**Comment by MohammadPCh** [comment]
@maryjaf, you'll need to wait for the request result. Sometimes, it takes a while to resolve. By the way, let's check it together.

**Comment by MohammadPCh** [comment]
@divine-comedian, after checking with @maryjaf, it appears that we are fetching data from the subgraph, but occasionally, it's not updated yet, resulting in the retrieval of old data. I propose adding a one-second delay before fetching it. This adjustment may fix the issue or at least reduce the likelihood of it occurring.

**Comment by maryjaf** [comment]
I've tested again and the problem of 
-closing automatically 
-and updating "Streaming at a Rate of" field after modifying flow rate
have been resolved but I saw a new problem it seems the  last changes have made it happens 

after confirming modal in metemak I got an error and the "amount" field in "Recurring Donations" table hasn't been updated and the page should be refreshed to see the update of "Recurring Donations" table 


https://github.com/Giveth/giveth-dapps-v2/assets/111529185/d810b2c0-6012-4868-9366-d3a74a866951

@MohammadPCh

**Comment by MoeNick** [comment]
Total Donated (value and amount) should be the sum of normal and recurring donations. 
This is buggy on the Profile Page @mohammadranjbarz pls check.

**Comment by MoeNick** [comment]
@MohammadPCh will check and I put it on in progress.

**Comment by maryjaf** [comment]
> I've tested again and the problem of -closing automatically -and updating "Streaming at a Rate of" field after modifying flow rate have been resolved but I saw a new problem it seems the last changes have made it happens
> 
> after confirming modal in metemak I got an error and the "amount" field in "Recurring Donations" table hasn't been updated and the page should be refreshed to see the update of "Recurring Donations" table

Thanks @MohammadPCh These problems have been resolved
