### ISSUE TITLE
Usd amount in recurring donation modal is shown 0

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3911]
Usd amount in recurring donation modal is shown 0

![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/baac5045-6aa3-4bfd-b93f-9cf094545ad1)

cc: @alireza-sharifpour

**Comment by alireza-sharifpour** [comment]
It's ready for testing @maryjaf

**Comment by maryjaf** [comment]
Thanks @alireza-sharifpour this problem has been resolved
