### ISSUE TITLE
Change name of Asia Pacific QF round to "Meta Pool APAC" 

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3914]
Now that the round is over, it will look better in our records on the dapp to say "Meta Pool APAC" but I can't change it in admin bro because the round is over.

@CarlosQ96 - please help! 😄 

cc @jainkrati

**Comment by laurenluz** [comment]
@CarlosQ96 - lmk if you can finish this soon!

**Comment by jainkrati** [comment]
@RamRamez pls take this up

**Comment by RamRamez** [comment]
I updated the name of this QF round.
@laurenluz you can go to qfRound tab in AdminJS and then search for the qf round by name or slug, then you can use the three dots (...) on the right to edit

**Comment by maryjaf** [comment]
what is changed  abot this issue? have you changed the logic that the all QF fields be editable after the rounds over? @RamRamez

**Comment by laurenluz** [comment]
yep it wasn't possible for admin to edit them when the round was edited (before, when I created the issue).  I think the fields were made editable post-round in another issue that was completed before this one

**Comment by maryjaf** [comment]
I've checked on stg and now after the rounds over, admin user can change the name and title.
