### ISSUE TITLE
Bug| user could set 0 amount in modifying recurring donation flow 

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3918]
**Describe the bug**

-user has a active recurring donation to a project
-by tapping on modify recurring donation, user could set 0 amount and "Donate" button is enable 
-by tapping on "Donate" an error message is shown 

cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason=\"execution reverted\", method=\"estimateGas\", transaction={\"from\":\"0xf577Ae8b97d839B9c0522A620299DC08792c738c\",\"to\":\"0xcfA132E353cB4E398080B9700609bb008eceB125\",\"data\":\"0x0c033991000000000000000000000000dfd824f6928b9776c031f7ead948090e2824ce8b000000000000000000000000f577ae8b97d839b9c0522a620299dc08792c738c0000000000000000000000000015ce4fea643b64000400b0e61f4c03e020b75f000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000000\",\"accessList\":null}, error={\"code\":-32603,\"message\":\"Internal JSON-RPC error.\",\"data\":{\"code\":3,\"message\":\"execution reverted\",\"data\":\"0x91acad16\",\"cause\":null}}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)

**Expected behavior**
It would be good if the user couldn't be able to set 0 amount in the first step and "Donate" button be disabled like as when user want to donate to a new project
<img width="1061" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/446e4866-f3ef-4b41-a434-0e15a7445f82">

**Screenshots**

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/d4fed03b-e449-48a5-8cb3-1c95efca9f97

cc: @divine-comedian @MohammadPCh

**Comment by divine-comedian** [comment]
We should definitely include this! good catch MJ

We should have the same behaviour on modify - the Donate button should be disabled if they modify their recurring donation amount to 0

**Comment by maryjaf** [comment]
It hasn't been assign to developers

**Comment by divine-comedian** [comment]
@MohammadPCh - Can you pick this one up or assign it to @alireza-sharifpour if it is more appropriate?

**Comment by maryjaf** [comment]
This problem has been resolved
