### ISSUE TITLE
Cant see any token list for GivingBlock Projects while Im on Ropsten as main network 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#392]
on UAT trying to test default token list on GivingBlock Projects.
when I switch network, I switch to Ropsten as mainnet, but Im still cant see any token list there. 
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/ee0b8030-67de-4f68-af6f-e68f6ed59280)

**Comment by divine-comedian** [comment]
testing on `staging.giveth.io` 
tokens now show up on ropsten while on the donate page for a giving block project 
![image](https://user-images.githubusercontent.com/67759413/163680490-b8533f7a-6f24-4172-aef6-ff6b1acba577.png)

AND I can whitelist more tokens to show up on this list using the updates to the adminbro panel for tokens. WOW! moving to DONE
