### ISSUE TITLE
Bug in end recurring donation flow 

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3920]
**Describe the bug**
 I had tested the "end recurring donation"and it was ok and the status was changed to ended correctly
but in one of my tests, I've faced this problem 

1- I selected one of active recurring donation 
2- and taped on "end recurring donation" 
3- after confirming transaction in metemask, the status wasn't changed to "ended" and remained "active"
4-by tapping again on "end recurring donation" I got the below error 

<img width="1259" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/77adcd78-4bf4-416f-9642-fc5d606b33e2">

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/f0720013-762d-4d85-8949-e2c4cc62181a

cc: @divine-comedian

**Comment by divine-comedian** [comment]
woah that is weird, @alireza-sharifpour - does this error make any sense to you?

**Comment by MohammadPCh** [comment]
@maryjaf Are we still encountering this issue?

**Comment by MohammadPCh** [comment]
The issue has been resolved. @maryjaf approved it. so I will close it.
