### ISSUE TITLE
Add link to Stake Together from GIVfarm

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3921]
@divine-comedian - can you put the link in here?

@Tosinolawale I would love to have a space in the GIVfarm where people can get directed to stake ETH in Stake Together. Can you help me figure out where to put that?

**Comment by Tosinolawale** [comment]
I think it can work. Let me draft something. This is just an external link that has no interaction with Giveth dApp right?

**Comment by divine-comedian** [comment]
Here it is! 
https://app.staketogether.org/brl/ethereum/project/deposit/0xf102fe6d6cf7f98c7c4ca45eb082caaaaa951d52

**Comment by laurenluz** [comment]
yep, just an external link and some copy... we could put copy like...

Copy:
Want to stake ETH & support public goods?
Join the Giveth Ethereum Staking pool. Stake ETH for stpETH, earn a passive interest & support top-boosted projects on with part of the rewards. 

Button: Go to Stake Together (links to https://app.staketogether.org/brl/ethereum/project/deposit/0xf102fe6d6cf7f98c7c4ca45eb082caaaaa951d52)

**Comment by Tosinolawale** [comment]
![GIVfarm V3](https://github.com/Giveth/giveth-dapps-v2/assets/35389241/d9256c30-06a7-4bf2-af5b-d898809be868)
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/GIVeconomy?type=design&node-id=22477%3A208069&mode=design&t=YPDaoJv3bHrkgcVz-1
@laurenluz

**Comment by laurenluz** [comment]
works for me! @jainkrati can we get this to development?

**Comment by maryjaf** [comment]
> @maryjaf ready to test
I don't know much about functionality of stake together 
Is this issue only related to adding link to stake together ? if yes it works correctly 
another question: should this be enabled on every networks?
@MohammadPCh

**Comment by laurenluz** [comment]
yeah it's just a link to stake together
and it should be enabled on every network... but stake together actually only works on mainnet (but that should be on their side)

**Comment by maryjaf** [comment]
By tapping on "GO STAKE TOGHETER" I got 404 error  
https://app.staketogether.org/brl/ethereum/project/deposit/0xf102fe6d6cf7f98c7c4ca45eb082caaaaa951d52

**Comment by divine-comedian** [comment]
Got the links, there are now one for Mainnet and one for Optimism now, COOL! 

https://app.staketogether.org/en/usd/ethereum/product/staking/eth-staking?projectAddress=0xf102fe6d6cf7f98c7c4ca45eb082caaaaa951d52

https://app.staketogether.org/en/usd/optimism/product/staking/eth-restaking?projectAddress=0xf102fe6d6cf7f98c7c4ca45eb082caaaaa951d52

**Comment by maryjaf** [comment]
> Got the links, there are now one for Mainnet and one for Optimism now, COOL!
> 
> ### Mainnet
> https://app.staketogether.org/en/usd/ethereum/product/staking/eth-staking?projectAddress=0xf102fe6d6cf7f98c7c4ca45eb082caaaaa951d52
> 
> ### Optimism
> need to follow up on this as our deposit address needed to be changed on Optimism but I expect it to be:
> 
> https://app.staketogether.org/en/usd/optimism/product/staking/eth-restaking?projectAddress=0x93E79499b00a2fdAAC38e6005B0ad8E88b177346

@MohammadPCh

**Comment by maryjaf** [comment]
ُThanks @MohammadPCh 
Now on prod for all networks except  Mainnet this address is set 
https://app.staketogether.org/en/usd/optimism/product/staking/eth-restaking?projectAddress=0x93E79499b00a2fdAAC38e6005B0ad8E88b177346

 Mainnet:
https://app.staketogether.org/en/usd/ethereum/product/staking/eth-staking?projectAddress=0xf102fe6d6cf7f98c7c4ca45eb082caaaaa951d52
@laurenluz
