### ISSUE TITLE
problem of anonymous donation

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3926]
User selects "make it anonymous"  in donation page but after completing donation flow , the user name is shown in donation table
@alireza-sharifpour has checked and it seems this is related to backend 
please take a look @mohammadranjbarz

**Comment by alireza-sharifpour** [comment]
Thanks @maryjaf.
I tested it and we send this query to backend: 
![Screenshot 2024-04-01 at 2 48 52 PM](https://github.com/Giveth/giveth-dapps-v2/assets/48887817/3f910fd9-1817-43c6-9219-376d74d68596)

But when I fetch it I get the anonymous value of false:

![Screenshot 2024-04-01 at 2 49 03 PM](https://github.com/Giveth/giveth-dapps-v2/assets/48887817/4723eab0-8325-4f53-bc1a-214dceec06ed)

Can you take a look? @mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
@alireza-sharifpour  you dont send $anonymous in your request payload, so it will not change

**Comment by maryjaf** [comment]
Thanks @alireza-sharifpour the problem of anonymous donation has been resolved
