### ISSUE TITLE
2-If there are 2 donations with different status for one project, it counts as 2 project in Supporting field

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3929]
In the streamable token balances table there is a column for "Supporting". 

This currently appears to count the total amount of recurring donations made to projects using the given stream balance. However this is not correct. 

When a recurring donation is ended or archived it should not count in the total number of project in supporting - since the donor is no longer sending funds to that project we shouldn't count it as being "supported", right? 

So the criteria here is 
1. user ends recurring donation that is active
2. the number of projects being "supported" for the given stream balance should decrease by 1. 

Is there something else missing here @maryjaf ?

**Comment by maryjaf** [comment]
Yeah ended and archive recurring donation should not be counted in "supporting" field

**Comment by jainkrati** [comment]
Testing is blocked on Pending Donations. @mohammadranjbarz can you pls unblock

**Comment by jainkrati** [comment]
@MohammadPCh to verify if this is a FE issue

**Comment by maryjaf** [comment]
based on the current view the number of supporting isn't ok 
for example "5 projects" is shown in supporting field of ETH but I have only 1 active donation 

<img width="1396" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGNvQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--baa090f64df5fea0da086452514da75f1db8654b/image.png" alt="image.png" />

**Comment by MohammadPCh** [comment]
@maryjaf We fetch the data from superfluid. you may have other donations that are not saved in our DB.

**Comment by maryjaf** [comment]
And "2 projects" is shown for GIV,  but as you can see in above pic that  I have 3  GIV active donation 
sth is wrong about this

**Comment by maryjaf** [comment]
Yeah,  I meant it's maybe not related to not saving in our db only, because for GIV recurring donation the showing number in supporting is lower than number of my active donation

**Comment by maryjaf** [comment]
this is my superfluid app view:
<img width="983" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/63323179-279f-4c30-befe-b2a5f6a1dbdc">

I  understand the difference in the number of ETH donations, which may be due to old donations that have been ended by mistake 
But I don't understand the difference in the number of GIV donations, how there are three actives in Giveth, but actually I  have two actives.
<img width="1252" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/2c5618d9-81d0-49e5-a4ff-bbb22c558830">
<img width="679" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/19d0d3c1-9174-43da-9390-10a3bab45e0b">

actually based on superfluid data the number of supporting is correct  but based on dapp information not

**Comment by divine-comedian** [comment]
Could this be related to the subgraph issues faced today? 

Good to know that it is being fetched from the subgraph but consider this case @MohammadPCh. What happens if I make a stream to a an address that is not a Giveth project through the superfluid UI? Would this count towards my "supporting" number? 

@MohammadPCh Is there a reason we chose to get this from the subgraph and not from our BE?

**Comment by maryjaf** [comment]
It hasn't been resolved, I've moved it to "inprogress" to be checked again

**Comment by maryjaf** [comment]
> So the criteria here is
> 
> 1. user ends recurring donation that is active

This problem has been resolved and now by ending a recurring donation the number of supporting projects will be updated correctly , I've tested with new user and the expected result is shown 

 about the type of implementation and conversation between @MohammadPCh @mohammadranjbarz you know better what should be decided

**Comment by maryjaf** [comment]
It seems last changes have made a problem in updating status in recurring donation table(https://github.com/Giveth/giveth-dapps-v2/issues/3907#issuecomment-2041348319)
after resolving this i'll test again end recurring donation flow and move it to done 
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVk5QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e592963fca24a60b8cdab21644570dcad9bce8a1/image.png" alt="image.png" />

but the new explanation has been added correctly

**Comment by divine-comedian** [comment]
I understand this scenario @MohammadPCh - but we get the top-up information from the superfluid subgraph and the "supporting" column from our DB that should ensure the relevant information is accurate for users.
