### ISSUE TITLE
[3rd April] 3-when I have an ended donation to Giveth in my recurring donation, by adding a new donation to a project and giveth

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3930]
This issue is related to when a user has previously made a donation to Giveth. Usually by the add donation to Giveth feature on the donate page it creates a second recurring donation that is shown in the table of recurring donations for the user. 

When that donation is archived or ended and a user makes another recurring donation and chooses to donate to Giveth a % it is currently updating the archived donation, however it should create a new recurring donation entry into the table, since the previous one was ended. 

-----
One thing to note for testing @maryjaf is that to consider previous BE bugs of project status that are now resolved there still could be older recurring donations that don't have the proper state - as in technically they may still be streaming funds but might have a status of ended/archived in our DB. good to check on the superfluid dashboard https://app.superfluid.finance/ to make sure 

Otherwise we may encounter unexpected errors on the blockchain level.

**Comment by maryjaf** [comment]
This is the result of my previous test
https://github.com/Giveth/giveth-dapps-v2/issues/3915#issuecomment-2024526956

I will test this scenario again with new user and let you know the result of  the new test

**Comment by maryjaf** [comment]
> I will test this scenario again with new user and let you know the result of the new test

Because of pending donation problem, I couldn't retest this scenario yet

**Comment by jainkrati** [comment]
This might be related to subgraph as well @mohammadranjbarz to take a look. @MohammadPCh to verify and move to QA after that

**Comment by MohammadPCh** [comment]
@mohammadranjbarz, what do you think? In the frontend, we verify if the user has an active stream to Giveth. If so, we update it; otherwise, we create new donations.

**Comment by MoeNick** [comment]
According to @maryjaf for the new user, it's working. I put here for doing more QA to confirm.

**Comment by maryjaf** [comment]
I've tested again with new user and this problem has been resolved
