### ISSUE TITLE
In public view of user page the "Streamable Token Balances" table of owner also is shown

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3943]
In public view of user page the "Streamable Token Balances" table of owner also is shown

https://staging.giveth.io/user/0xa1179f64638adb613ddaac32d918eb6beb824104?tab=recurring-donations

![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/20bddff1-4fc4-47be-930e-70ea3b052101)

based on call that I had with @MohammadPCh this issue has been assigned to him

**Comment by MohammadPCh** [comment]
@maryjaf we have to hide it regarding the Figma:
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/GIVeconomy?type=design&node-id=23644-29401/
I will Left a PR for it.

**Comment by MohammadPCh** [comment]
@maryjaf ready to test

**Comment by maryjaf** [comment]
ُThanks @MohammadPCh "Streamable Token Balances" table has been removed in public view of user page

**Comment by maryjaf** [comment]
> and it would be good if switch to archive donation is also be removed from this page

This item also has been resolved
