### ISSUE TITLE
Call updateRecurringDonationStatus after updating txHash and flowRate

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/giveth-dapps-v2#3953]
related https://github.com/Giveth/giveth-dapps-v2/issues/3930

We just be aware that we should either change both txHash, flowRate or none of them (if we change one of them the change would not be applied on these two fields)

And you should call updateRecurringDonationStatus to verify it again, because after modifying the txHash we make it pending and need to verify with network again

**Comment by MohammadPCh** [comment]
@mohammadranjbarz Thanks for explaining it.
I checked the code and it's fine now (we always update donations with both of them).
for the second part, I will leave a PR.
