### ISSUE TITLE
Get historical GIV staking data from Oct '23 to present date

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3960]
In order to set up the next round of incentives for GIVpower, I need some data from querying the graph.

We need to make a rough estimate/projection of how much GIV will be staked into the future... and the best way to do that is if we get some data around **how much GIV was staked on OP Mainnet & how much GIV was staked on Gnosis on each of the following dates**

10/31/2023
11/14/2023
11/28/2023
12/12/2023
12/26/2023
1/9/2024
1/23/2024
2/6/2024
2/20/2024
3/5/2024
3/19/2024
4/2/2024

We also need **how much GIV is locked & getting the max APR today (or whatever day you're checking) and how much GIV is just staked and not locked at all (i.e. min APR) today**

@aminlatifi hoping to get your help with this since it relates to the work you are doing for the dune dashboard.

**Comment by aminlatifi** [comment]
https://github.com/Giveth/giveth-dapps-v2/issues/2420

**Comment by aminlatifi** [comment]
I added some diagrams to show how much users have locked for different round spans

**Comment by laurenluz** [comment]
I need to know how much is staked in GIVpower on optimism & gnosis... combined. and I need the amounts at those specific dates I listed above.
