### ISSUE TITLE
Update QF Round Banner on Giveth for the Galactic Giving Round

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#3961]
@rodricastillo9013 please share here the link to figma, as well as svgs for the backgroud, top middle, top bottom, and each corner.

For this colouring:

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/e4c0990b-28f4-4aa5-85f6-d51805b7ba67)

**Comment by laurenluz** [comment]
cc @koday1

**Comment by rodricastillo9013** [comment]
https://www.figma.com/file/W9Ace1RyCdykWM72fsSa3t/Giveth-Marketing-2024?type=design&node-id=6302%3A5787&mode=design&t=0G2L5D6zVBKkcKrU-1 hi team! you have the assets here @laurenluz @koday1

**Comment by laurenluz** [comment]
ooh this needs a fix @rodricastillo9013 ! check figma comment

**Comment by laurenluz** [comment]
ok I think this is good to get up. @jainkrati can you assign someone?

just FYI - the sponsors will also change later (we will be adding more)... so this will need a tweak in the future (after April 25)...

but if we can get the banner up on prod sometime this week, it would be great for the curation team to be able to start adding the projects.

**Comment by koday1** [comment]
@rodricastillo9013 here's the updated Glo Dollar logo to add to the galactic giving round banner 
![glo-logo-dualcolor](https://github.com/Giveth/giveth-dapps-v2/assets/34075192/8dc27d75-27b1-4ac5-a24b-3f61125a40cf)

**Comment by laurenluz** [comment]
@rodricastillo9013 - they are a "small sponsor"... also we will have once more "small sponsor" coming soon "lotto PGF"...

you can hold off on making any more changes to the banner until we have all the logos in (April 25).

**Comment by laurenluz** [comment]
@RamRamez please help to update the banner w/ no sponsors ASAP, looking like this - [link to figma](https://www.figma.com/file/W9Ace1RyCdykWM72fsSa3t/Giveth-Marketing-2024?type=design&node-id=6302-5787&mode=design&t=6Rpurs7QDmQQt20R-4):

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/04cee968-ba3c-48aa-a24e-95f935c7942f)

We'll need to update it again (adding the sponsors once they are all confirmed & we have their logos)... in about a week, but it would be great to have this up asap so we can start adding projects and directing people to the page.

**Comment by RamRamez** [comment]
@maryjaf to test and verify
https://staging.giveth.io/qf/all

**Comment by RamRamez** [comment]
@laurenluz I added the three sponsors in Figma. Do you want me to remove them?
Check here
https://staging.giveth.io/qf/all

**Comment by laurenluz** [comment]
oh it's no problem. lets' go with that for now :-D those sponsors are all confirmed anyway

**Comment by RamRamez** [comment]
@laurenluz if you need it on production RN, I can prepare a cherry-pick fast

**Comment by laurenluz** [comment]
the sooner the better :) then we can start adding projects and telling them to look there

**Comment by RamRamez** [comment]
@laurenluz it's live

**Comment by RamRamez** [comment]
We have no active rounds on production RN, so this banner doesn't have a title
https://giveth.io/qf/all

**Comment by laurenluz** [comment]
perfect! thank you @RamRamez !

**Comment by laurenluz** [comment]
@koday1 please add the new sponsor logos for Rodri.

**Comment by koday1** [comment]
@rodricastillo9013 Adding Premia ($1500 sponsor). You can find their logo here: https://docs.premia.blue/resources/media-kit

**Comment by koday1** [comment]
@rodricastillo9013 Adding MUX (small sponsor, $1500) logos here:

<img width="512" alt="MUX Icon" src="https://github.com/Giveth/giveth-dapps-v2/assets/34075192/c660c2e4-1272-4004-a00b-71bf6d43f031">
![MUX_Logo_Black](https://github.com/Giveth/giveth-dapps-v2/assets/34075192/e656f125-8ce7-48ca-afdf-2e1178079828)
![MUX_Logo_Colored_Dark](https://github.com/Giveth/giveth-dapps-v2/assets/34075192/f3530c2e-3741-48a4-b808-c91833764025)
![MUX_Logo_Colored_Light](https://github.com/Giveth/giveth-dapps-v2/assets/34075192/e9586c35-05f6-47e7-ace6-09f89bbe1da6)
![MUX_Logo_White](https://github.com/Giveth/giveth-dapps-v2/assets/34075192/6e5900e9-4f86-422b-ac37-48a814368c5e)

**Comment by jainkrati** [comment]
this issue has been fixed with the given assets 5 days back. If more logos / banners / assets come in and need updates pls create a new issue @koday1 instead of reopening this issue because as part of Zenhub and github analytics, the total time taken to close this issue increases as requirements changed after closing the issue even though it was closed correctly based on last assets. These analytics will be used to representation of team efficiency and speed and it will be best if we correctly represent new requirements as new issues.

**Comment by laurenluz** [comment]
hmm ok  @koday1 - please create a new issue for updating the banner the 2nd time 🙏
