### ISSUE TITLE
Apply Recurring donations in Total Donations and total Amount in all views

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3968]
**As a user, I want to see the correct amount of donations (number and value) in all these views.** 
- [x] Project Page | Public View | Amount
- [x] Project Page | Public View | Donation tab right column
- [x] Project Page | Private View | Right upper column
- [x] Project Page | Private View | Donation Tab | Allmount received in right column
- [x] Project Page | Private View | all  2 above in QF Views
- [x] Project Page | Private View | Right upper column
--------------------
- [x] Project Card | HompePage, Projects page,
- [x] Project Card | Donation Page (before and after donation)
- [x] Project Card | In Similar projects inside the single project page view
- [x] Project Card | 3 above views in QF rounds view 
- [x] Project Card | Liked Projects Tab in Public Profile Page
- [x]  Project Card | Projects Tab in Public Profile Page
---------------------------------
- [x] My Accuont | Overview 
- [x] My Account | My Project Title
- [x] My Account | My Donation Table
-------------------------------
- [x] Public Profile Page | Overview
- [x] Public Profile Page | Projects tab
- [x] Project Card | Donation Tab

**Comment by MoeNick** [comment]
- [ ] 1-showing counter on donations tab is only related to records in "all donations " tab not "recurring donation tab"
for the [testtt project](https://staging.giveth.io/project/testtt?tab=donations) there are 2 records in all donation tab and 2 for recurring donation but, the counter is shown 2 
I'm not sure if this is a front or backend issue cc: @MohammadPCh @mohammadranjbarz 

<img width="1250" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/4ec8a1a4-6504-4055-8e7d-5fb2f4ad5647">
<img width="1265" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/69b34a34-824a-4e24-bfb2-c7b90218e6db">

__________________

- [ ] 2- "Total amount raised " and "All time donations received" are different 
https://staging.giveth.io/project/testtt?tab=donations
 
 and it seems the amount of  "All time donations received " is correct 
 and "Total amount raised "  that is also shown in project card should be changed based on this field 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/ac5aa3f8-f499-4803-8ae1-71441301e4f2)

cc: @MoeNick

**Comment by maryjaf** [comment]
- Consider that **number of  contributors** also should be updated correctly
<img width="622" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/6081e80f-312a-4700-8f20-bacb2c8094f2">

**Comment by MohammadPCh** [comment]
@mohammadranjbarz  Public view: `donationsCount`, `totalDonated` in this query
```ts
export const GET_USER_BY_ADDRESS = gql`
	${USER_CORE_FIELDS}
	query UserByAddress($address: String!) {
		userByAddress(address: $address) {
			...UserCoreFields
			totalDonated
			totalReceived
			likedProjectsCount
			projectsCount
			donationsCount
			boostedProjectsCount
			passportScore
			passportStamps
		}
	}
`;
```

**Comment by maryjaf** [comment]
has "totalReceived " count and amount been fixed? @mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
> has "totalReceived " count and amount been fixed? @mohammadranjbarz

Not yet, I think that time `totalReceived` wasn't in message :))
I will let you know once I do it

**Comment by MohammadPCh** [comment]
@mohammadranjbarz Project info in donation Page: `sumDonationValueUsd` in
```ts
gql`
			query ProjectBySlug($slug: String!, $connectedWalletUserId: Int) {
				projectBySlug(
					slug: $slug
					connectedWalletUserId: $connectedWalletUserId
				) {
					__typename
					id
					title
					image
					slug
					verified
					totalDonations
					description
					descriptionSummary
					addresses {
						address
						isRecipient
						networkId
						chainType
					}
					socialMedia {
						type
						link
					}
					totalProjectUpdates
					creationDate
					reaction {
						id
						userId
					}
					totalReactions
					categories {
						name
						value
						mainCategory {
							title
						}
					}
					adminUser {
						id
						name
						walletAddress
						avatar
					}
					listed
					status {
						id
						name
					}
					organization {
						name
						label
						supportCustomTokens
					}
					projectVerificationForm {
						status
					}
					verificationFormStatus
					projectPower {
						powerRank
						totalPower
						round
					}
					projectFuturePower {
						totalPower
						powerRank
						round
					}
					givbackFactor
					sumDonationValueUsdForActiveQfRound
					sumDonationValueUsd
					countUniqueDonorsForActiveQfRound
					countUniqueDonors
					estimatedMatching {
						projectDonationsSqrtRootSum
						allProjectsSum
						matchingPool
					}
					qfRounds {
						id
						name
						isActive
						beginDate
						endDate
						eligibleNetworks
						maximumReward
					}
					campaigns {
						id
						title
						# description
						# type
						# photo
						# video
						# videoPreview
						# slug
						# isActive
						# order
						# landingLink
						# filterFields
						# sortingField
						# createdAt
						# updatedAt
					}
					anchorContracts {
						address
						isActive
					}
				}
			}
		`
		```

**Comment by MohammadPCh** [comment]
@mohammadranjbarz, Project card in. Similare box:  `sumDonationValueUsd`
```ts
export const SIMILAR_PROJECTS = gql`
	${PROJECT_CARD_FIELDS}
	query SimilarProjectsBySlug($slug: String!, $take: Int, $skip: Int) {
		similarProjectsBySlug(slug: $slug, take: $take, skip: $skip) {
			projects {
				...ProjectCardFields
			}
		}
	}
`;
```

**Comment by MohammadPCh** [comment]
@mohammadranjbarz, Project card in Projects Tab (public profile):  `sumDonationValueUsd`
```ts
export const FETCH_USER_PROJECTS = gql`
	${PROJECT_CARD_FIELDS}
	query FetchUserProjects(
		$take: Float
		$skip: Float
		$userId: Int!
		$orderBy: OrderField!
		$direction: OrderDirection!
	) {
		projectsByUserId(
			take: $take
			skip: $skip
			userId: $userId
			orderBy: { field: $orderBy, direction: $direction }
		) {
			projects {
				...ProjectCardFields
				creationDate
				listed
				status {
					id
					name
				}
				addresses {
					address
					isRecipient
					networkId
					chainType
				}
				projectVerificationForm {
					status
				}
			}
			totalCount
		}
	}
`;

```

**Comment by maryjaf** [comment]
> * [ ]  1-showing counter on donations tab is only related to records in "all donations " tab not "recurring donation tab"
>   for the [testtt project](https://staging.giveth.io/project/testtt?tab=donations) there are 2 records in all donation tab and 2 for recurring donation but, the counter is shown 2
>   I'm not sure if this is a front or backend issue cc: @MohammadPCh @mohammadranjbarz
> 
> <img alt="image" width="1250" src="https://private-user-images.githubusercontent.com/111529185/320447552-4ec8a1a4-6504-4055-8e7d-5fb2f4ad5647.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NDUzNzYsIm5iZiI6MTcxMjY0NTA3NiwicGF0aCI6Ii8xMTE1MjkxODUvMzIwNDQ3NTUyLTRlYzhhMWE0LTY1MDQtNDA1NS04ZTdkLTVmYjJmNGFkNTY0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQwNjQ0MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZDdjM2E2NTQ5YjMyODU5YTViODYyNDQ5YjM2YWE4N2RkMTMzOTBiZmRmOWQ0ZTFiZmI1OTU2MzU0NWVlMGJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZGAPzzOy2Iikq44u-dnx-1XN06PQUIN2FhR2971iYeY"> <img alt="image" width="1265" src="https://private-user-images.githubusercontent.com/111529185/320447719-69b34a34-824a-4e24-bfb2-c7b90218e6db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NDUzNzYsIm5iZiI6MTcxMjY0NTA3NiwicGF0aCI6Ii8xMTE1MjkxODUvMzIwNDQ3NzE5LTY5YjM0YTM0LTgyNGEtNGUyNC1iZmIyLWM3YjkwMjE4ZTZkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQwNjQ0MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMDYzMTgwNDNkNTZlM2JhM2MxZjcyMGZjMTZmZmZhYTQyMDA0ODBlNjJkMjUwODk2MjBlMjRkM2FlZTQ1OTk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._XClVq-99gSjfB4fFGxZPr7ZHWsezrDgoDGRVgyvV4k">
> * [ ]  2- "Total amount raised " and "All time donations received" are different
>   https://staging.giveth.io/project/testtt?tab=donations
> 
> and it seems the amount of "All time donations received " is correct and "Total amount raised " that is also shown in project card should be changed based on this field
> 
> ![image](https://private-user-images.githubusercontent.com/111529185/320450958-ac5aa3f8-f499-4803-8ae1-71441301e4f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NDUzNzYsIm5iZiI6MTcxMjY0NTA3NiwicGF0aCI6Ii8xMTE1MjkxODUvMzIwNDUwOTU4LWFjNWFhM2Y4LWY0OTktNDgwMy04YWUxLTcxNDQxMzAxZTRmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQwNjQ0MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMzViMGRmNTU5NjE3NGY5MmNjZjk4YzM4MDVlMGI1NmYzZDYxNTZmMmE5NDc3N2Q2YjA4NDM3OWFjNzJkZDVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zrLj5LwAf3a9fBYOc5u7eewCWm5yZL7QQres34gTB7Q)
> 
> cc: @MoeNick

These 2 problems haven't been resolved 
@mohammadranjbarz

**Comment by maryjaf** [comment]
> * [ ]  **countUniqueDonors**
> *

Please take a look on this @mohammadranjbarz 
cc: @MohammadPCh 
https://staging.giveth.io/project/testpic101?tab=donations

This project has only one recurring donation, and there isn't any one time donation for it but like as below pic the number of contributor is shown  "2 "

<img width="1349" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/56b7b0ca-3e7c-4025-abf4-6d094dc14e59">
<img width="1161" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/a5530290-cec3-4c99-aff6-01d175a51c3c">

**Comment by maryjaf** [comment]
> > * [ ]   **countUniqueDonors**
> 
> Please take a look on this @mohammadranjbarz cc: @MohammadPCh https://staging.giveth.io/project/testpic101?tab=donations
> 
> This project has only one recurring donation, and there isn't any one time donation for it but like as below pic the number of contributor is shown "2 "
> 
> <img alt="image" width="1349" src="https://private-user-images.githubusercontent.com/111529185/320829700-56b7b0ca-3e7c-4025-abf4-6d094dc14e59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NzM0NjQsIm5iZiI6MTcxMjY3MzE2NCwicGF0aCI6Ii8xMTE1MjkxODUvMzIwODI5NzAwLTU2YjdiMGNhLTNlN2MtNDAyNS1hYmY0LTZkMDk0ZGMxNGU1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQxNDMyNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YWMyNTQ4NGJkNmNlODc3OWI0ZTZkMTNlYzE2NTg4ZTJlYWYxMWVlZjFhNzE4MzUzNTgzODEzNzMzZTIxZjFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4_fcWRfoxFQaivP-eMQQjy8fkDPqy8gNz5Xk-Sqon4g"> <img alt="image" width="1161" src="https://private-user-images.githubusercontent.com/111529185/320830332-a5530290-cec3-4c99-aff6-01d175a51c3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NzM0NjQsIm5iZiI6MTcxMjY3MzE2NCwicGF0aCI6Ii8xMTE1MjkxODUvMzIwODMwMzMyLWE1NTMwMjkwLWNlYzMtNGM5OS1hZmY2LTAxZDE3NWE1MWMzYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQxNDMyNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOWUxOTNmMjcwMDM2YTM0N2MxMmUwMjg1YjE3NzJiZGU0ODNmMTVjNDZjNjA0MjM1NzVkNTVmMzNhMDcwYzFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.g4Fu6QxR4MTb0Zt8VvuYhfQmZFrN-vrdoMm6RYrM6m0">

This problem hasn't been resolved, I'm not sure this problem is related to superfluid changes or not @MohammadPCh @MohammadPCh

**Comment by mohammadranjbarz** [comment]
> > * [ ]   **countUniqueDonors**
> 
> Please take a look on this @mohammadranjbarz cc: @MohammadPCh https://staging.giveth.io/project/testpic101?tab=donations
> 
> This project has only one recurring donation, and there isn't any one time donation for it but like as below pic the number of contributor is shown "2 "
> 
> <img alt="image" width="1349" src="https://private-user-images.githubusercontent.com/111529185/320829700-56b7b0ca-3e7c-4025-abf4-6d094dc14e59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MzQ5MjcsIm5iZiI6MTcxMjczNDYyNywicGF0aCI6Ii8xMTE1MjkxODUvMzIwODI5NzAwLTU2YjdiMGNhLTNlN2MtNDAyNS1hYmY0LTZkMDk0ZGMxNGU1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQwNzM3MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Y2NmZjFhYTgyYWYyNDI4MmQxMDc0NGUxODQzMzU0NDE3ZGU5YjMzMTFmMDJjYzU1M2FkYWI4NzBiOWY3MTQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3Wmjk1sPM417RsTX0cQ41lBTvba7_rcFvCY0tNBcdCo"> <img alt="image" width="1161" src="https://private-user-images.githubusercontent.com/111529185/320830332-a5530290-cec3-4c99-aff6-01d175a51c3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MzQ5MjcsIm5iZiI6MTcxMjczNDYyNywicGF0aCI6Ii8xMTE1MjkxODUvMzIwODMwMzMyLWE1NTMwMjkwLWNlYzMtNGM5OS1hZmY2LTAxZDE3NWE1MWMzYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMFQwNzM3MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00M2Y3MjI4ZTQyMWU4MTM1ZTA1NzEyNjQ4ZWY5ZTdmMThlOTMxOGY0MmYyNDM4NTFmOWYyNWM4ZjY4NDRmMDY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.o8f7tnToONMrtDHEnktnZrXAMCqozHY-6pD7lyPYTw8">

@maryjaf  Can you test this again

**Comment by maryjaf** [comment]
Thanks @mohammadranjbarz The problem related to "number of contributors" has been resolved 
but this problem that had been resolved yesterday, has happened again

 2- "Total amount raised " and "All time donations received" are different
https://staging.giveth.io/project/testtt?tab=donations

<img width="1357" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/641a69e0-2302-47a5-9f39-abaec8895420">

**Comment by mohammadranjbarz** [comment]
@maryjaf  please test it, now it works

**Comment by maryjaf** [comment]
ُThanks @mohammadranjbarz This problem has been resolved
