### ISSUE TITLE
Application error on stg environment 

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3970]
**Describe the bug**

Sometimes by changing user from metamask, I got this error on my account page
Application error: a client-side exception has occurred (see the browser console for more information).

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/fbfac6f5-b076-47ac-a66a-2552bbd40689

cc: @MohammadPCh @MoeNick

**Comment by maryjaf** [comment]
> @maryjaf, I've attempted several times, but I couldn't reproduce it. It may be due to a poor internet connection.

Thanks @MohammadPCh I'll move it to done and check again on prod feature branch

**Comment by maryjaf** [comment]
@RamRamez said he also got this error for a user who all of his donations are ended 
 please take a look @MohammadPCh 
 
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/f12f37b6-9aea-4f3c-b76f-bf1b91330ba1)

**Comment by MohammadPCh** [comment]
@maryjaf please check it again. thanks.

**Comment by maryjaf** [comment]
I've checked with @RamRamez and it has been resolved 
Thanks @MohammadPCh @RamRamez
