### ISSUE TITLE
Add social media tips on create page

### ISSUE THREAD

**Issue by MohammadPCh** [Giveth/giveth-dapps-v2#3971]
Since we've added the social media section to the create page, we need to incorporate its corresponding tips.

**Comment by MohammadPCh** [comment]
@laurenluz @divine-comedian Could please provide tips? I need something like this (this is for banner section):
<img width="425" alt="Screenshot 2024-04-08 at 7 41 39 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/17097576/130ba96e-a6b7-410f-aa6f-13d00fb83172">

**Comment by MohammadPCh** [comment]
This is the Figma Link: @laurenluz 
https://www.figma.com/file/vMiyVd1Ly5LjgSyZrChVV8/Giveth-users?type=design&node-id=1675-12234&mode=design&t=tB4ju8codiVyvaVf-4

**Comment by MoeNick** [comment]
I added the Epic @MohammadPCh so as not to lose track of it.

**Comment by laurenluz** [comment]
Get Connected!
- Adding your social media accounts allows your donors and community to connect with you and learn what you are up to!
- Your accounts will be linked to from your project's page on Giveth.
- Giveth might use your social media handles to contact you or tag you on posts to support your fundraising.

**Comment by laurenluz** [comment]
^^ some copy for you @MohammadPCh

**Comment by MohammadPCh** [comment]
@laurenluz Thanksss

**Comment by MohammadPCh** [comment]
@maryjaf ready to test. Thanks
