### ISSUE TITLE
List of ALL projects on Giveth

### ISSUE THREAD

**Issue by oyealmond** [Giveth/giveth-dapps-v2#3973]
For sending emails to different subscription groups - there needs to be an audience/tag created for ALL projects. This was discussed on the last comms call and @divine-comedian suggested a list to be exported from the database and uploaded to Ortto.

Please have a look @RamRamez 
cc @krmet

**Comment by oyealmond** [comment]
Hey @krmet , @RamRamez sent me this. Would this be enough? Let us know 
[all-projects.csv](https://github.com/Giveth/giveth-dapps-v2/files/14911526/all-projects.csv)

**Comment by RamRamez** [comment]
@oyealmond I sent you the list in DM. Please tell me if you need anything else.

**Comment by RamRamez** [comment]
@divine-comedian I think we can close this issue.

**Comment by divine-comedian** [comment]
@oyealmond - You should be able to filter all project owners using the Project Owner tag that is given to the contact when they create a project on the dapp.
