### ISSUE TITLE
Can't publish my project without first previewing it.

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#398]
I filled in all the info, how come "publish" is greyed out? 

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/c84845db-170a-4822-9ff1-9247557cd553)

**Comment by laurenluz** [comment]
FYI, it allows me to publish after previewing... the user should be allowed to publish without preview...

![image](https://user-images.githubusercontent.com/75490971/161126676-cc68ff1f-e4bf-4769-861e-dec000427f9f.png)

**Comment by divine-comedian** [comment]
testing on `staging.giveth.io`  
looks like I can make a project, preview it, go back to edit and publish it directly from there. 

I think this is related to another issue we were resolving @pkretzschmar  but I can't seem to find it :thinking: 

I can also publish my project directly without previewing it. calling this DONE!

![image](https://user-images.githubusercontent.com/67759413/163843624-097a30ad-9133-4df8-bef4-fc47e833cac4.png)
