### ISSUE TITLE
Save draft recurring donation before executing transaction

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/giveth-dapps-v2#3981]
related to 
https://github.com/Giveth/impact-graph/issues/1463

We need to store these fields

```
  networkId: number;
  flowRate: string;
  currency: string;
  isBatch: boolean;
  anonymous: boolean;
  projectId: number;
  donorId: number;
  errorMessage?: string;
‍‍‍‍‍‍```

**Comment by MohammadPCh** [comment]
@mohammadranjbarz Do we need the `donorId` and `errorMessage`?
besides that, I think we need to add draftDonationId to save the donation query. am I right?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz Do we need the `donorId` and `errorMessage`? besides that, I think we need to add draftDonationId to save the donation query. am I right?

I think it's better to have them if it's possible for you, because it's good to know why it has failed but if you don't have it, I think it's ok,
about draftDonationId you are right, I think it's good to have it, will ping you once I implement the draft recurring donation  stuff

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz I believe we need to establish a draft donation service for the donation update process as well. What do you think?

Hmmm, you are right, It might be a little complicated and takes some time as well in the backend side.
@jainkrati do we need the draft service for update recurring donation in first release?

**Comment by mohammadranjbarz** [comment]
> Yes @mohammadranjbarz . We have to handle all scenarios of possibly missing donations / update to donations

Cool, we support it now

**Comment by MohammadPCh** [comment]
duplicate with #4038
