### ISSUE TITLE
Add Polygon QF round matching fund data to backend

### ISSUE THREAD

**Issue by koday1** [Giveth/giveth-dapps-v2#3985]
Need to take the Polygon QF round matching data and add it to the backend.

Here's the data for all projects in the Polygon round:

Google sheet - https://docs.google.com/spreadsheets/d/1-Y7fcm72xCxv4n73ldKdALJGhWM8BXQQpnOS1YnjAnw/edit?usp=sharing

CSV - [Polygon Round Data for Backend - Sheet1 (1).csv](https://github.com/Giveth/giveth-dapps-v2/files/14980443/Polygon.Round.Data.for.Backend.-.Sheet1.1.csv)

cc @laurenluz

**Comment by laurenluz** [comment]
Hey @koday1 - confirmed w/ the polygon team that we can send funds to Gravity DAO. I made a multisig tx for it. Need to wait for signers: https://app.onchainden.com/safes/matic:0x6e8873085530406995170Da467010565968C7C62/transactions/0xad191324000b917a1ef0f88554f465b968bab8cd5d6ff6a2fe11e05900e914e7?nid=304998

can you keep an eye on that, and once it is sent, input the amount, tx hash, details into the spreadsheet?

Also would love edit access :)

**Comment by laurenluz** [comment]
@CarlosQ96 some of the project recipients didn't fill out their KYC, so will not be getting any matching funds.

In this case... where they have 0 matching funds on the sheet... will the frontend just be updated to show that 0 was allocated and there is no link to the tx sending funds? Or how will it be handled where the tx hash is N/A?

(also wait until we assign you before starting on this :-D want to get that last tx in there)

**Comment by jainkrati** [comment]
@CarlosQ96 pls take this up on priority today.

**Comment by koday1** [comment]
@laurenluz added the Gravity DAO txn and details to the sheet and updated the csv uploaded above. Should be all set to get this added to the backend today. Thanks @jainkrati for assigning
