### ISSUE TITLE
Update stream balance after modifying (deposit/withdraw) the stream

### ISSUE THREAD

**Issue by MohammadPCh** [Giveth/giveth-dapps-v2#3988]
<img width="1277" alt="Screenshot 2024-04-11 at 1 06 19 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/17097576/ce0172ad-e4e6-40a4-b2b1-76322058ec28">

**Comment by MohammadPCh** [comment]
@maryjaf ready to test.

**Comment by maryjaf** [comment]
Thanks @MohammadPCh this problem has been fixed
