### ISSUE TITLE
I got unauthorized error when I try to archive an ended recurring donation

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#3990]
**Describe the bug**
I got unauthorized error when I trying to archive an ended recurring donation

**To Reproduce**
1. Go to 'my account'
2. select "one ended recurring donation"
3. Click on 'actions' icon
4. tap on "archive"
5. See error

it seems the condition on signed user isn't check in this flow at the first step

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/578d426f-0414-4bf7-9e32-54e6dfa18652

**Comment by maryjaf** [comment]
in my new try I haven't seen unauthorized error again, i try to reproduce
but now by tapping on archive and complete flow , the status isn't changed from ended to archive and it is still shown ended

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/455d0989-8e38-4162-a141-5b7d8abe5caf

**Comment by mohammadranjbarz** [comment]
> in my new try I haven't seen unauthorized error again, i try to reproduce
> 
> but now by tapping on archive and complete flow , the status isn't changed from ended to archive and it is still shown ended I've checked this with @MohammadPCh and this scenario happens for Giveth project that I already have a archive donation for this and it should be checked on backend side @mohammadranjbarz
> 
>  Screen.Recording.2024-04-11.at.1.31.49.PM.mov

@MohammadPCh  @maryjaf  I checked this donation and this is archived, I think there is a frontend issue that shows `Ended` recurring donations as `Ended` doesn't matter it's archived or not

**Comment by MohammadPCh** [comment]
update: regarding our call, we need to change the BE service to get a donation ID for archiving recurring donations.

**Comment by jainkrati** [comment]
@maryjaf pls verify close

**Comment by maryjaf** [comment]
> @maryjaf pls verify close

I've moved already it to Done, and after deploy on prod it could be closed
