### ISSUE TITLE
When supporting 0 projects. Top-up before estimation is wrong

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#3998]
In my recurring donations view I have a stream balance of GIV but I am not donating to any projects. The estimated top-up before amount shows as < 1 month, but this is incorrect. Since my flowrate is 0 it should show as an empty value. 

This is the current view: 
<img width="1549" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekJoQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c6fb5fbd59ec8305f537f10151311e1b62f1a9ab/image.png" alt="image.png" />

It should be replaced with a simple dash `-`
<img width="1512" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelJoQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--287d6e553ce397aea330d077663fb2e25ae85c0d/image.png" alt="image.png" />

**Comment by MohammadPCh** [comment]
@divine-comedian Thanks for reporting, I've fixed it in another issue, so please check it again.

**Comment by maryjaf** [comment]
I move it to dona and track the status of these problem on  # 4001
