### ISSUE TITLE
Problem in "Top-up before" field after ending stream

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#4001]
**Describe the bug**
My stream has been ended but Top-up before is still shown < 1 month 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/5953dd98-3792-4e65-b117-a4fa62c62e94)

**Comment by MohammadPCh** [comment]
@maryjaf ready to test, Thanks.

**Comment by maryjaf** [comment]
It couldn't be tested until subgraph problem from superfluid side be resolved

**Comment by maryjaf** [comment]
It has been resolved
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/56362d0a-6a8a-4a72-91a6-a4c12173a4f6)

**Comment by maryjaf** [comment]
ُThere is a problem that now for a not ended stream of my user it is also shown "--"
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/9f02b112-851c-401f-b31b-3687d23cacfb)

**Comment by MohammadPCh** [comment]
@maryjaf Please check it again in 10 mins.

**Comment by maryjaf** [comment]
It should be fixed in this modal also @MohammadPCh 
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/be795568-5346-4314-bf70-58a9bb8a8362)

**Comment by MohammadPCh** [comment]
@maryjaf Fixed and ready to test.

**Comment by maryjaf** [comment]
it has been resolved
<img width="1049" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUZ5QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fed40b45eb2bdb6ff17148a32e54473b82290eda/image.png" alt="image.png" />
