### ISSUE TITLE
Remove donating to giveth row on giveth doante page

### ISSUE THREAD

**Issue by MohammadPCh** [Giveth/giveth-dapps-v2#4002]
<img width="1115" alt="Screenshot 2024-04-16 at 12 20 03 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/17097576/73038ff8-49b7-4791-a7c1-870b4d898616">
we haven't show giveth row here.

**Comment by maryjaf** [comment]
It has been fixed
