### ISSUE TITLE
Number of "Funding project" and "Available" amount in deposit/withdraw modal should be fixed

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#4007]
In "Modify Stream Balance" modal, "Funding project" should shows number of "Active" donation 
Now it shows number of all recurring donation(active,ended, archived)

<img width="679" alt="Screenshot 2024-04-16 at 4 30 04 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/772525c5-4df0-4f09-be2c-6140f8aeb5a1">

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/03d6c946-2be0-4199-92b3-0913c3a48035

**Comment by MohammadPCh** [comment]
@maryjaf ready to test. Thanks.

**Comment by maryjaf** [comment]
It has been resolved

**Comment by maryjaf** [comment]
There is another issue in this modal 
Showing negative number in available amount in withdraw tab , please take a look @MohammadPCh 
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/ce5ded12-8381-419d-a592-98e7a6118820)

**Comment by maryjaf** [comment]
It has been fixed
