### ISSUE TITLE
Exclude donations from project recipient addresses for QF matching calculations

### ISSUE THREAD

**Issue by koday1** [Giveth/giveth-dapps-v2#4011]
Right now, we only exclude addresses from verified projects for QF matching calculations. We need to update this to include the recipient addresses for ALL listed & active projects.

To summarize:

NO matching: addresses of all listed & active projects
YES matching: addresses of draft state & unlisted projects & cancelled projects & deactivated projects

The primary goal is to exclude the projects that are active on Giveth, raising funds right now, and then using their funds to support other projects in QF rounds.

**Comment by koday1** [comment]
@laurenluz FYI

**Comment by laurenluz** [comment]
make sure that active & listed projects are the ones whose recipient address is excluded from donating & getting matching in QF
