### ISSUE TITLE
Show ended recurring donations on user public profile

### ISSUE THREAD

**Issue by MohammadPCh** [Giveth/giveth-dapps-v2#4020]
we need to show ended recurring donations on user public profile

**Comment by maryjaf** [comment]
Based on @divine-comedian comment, both ended and archived should be shown 
in user and project page

**Comment by MohammadPCh** [comment]
@maryjaf we show archived donations now. ready to test.

**Comment by maryjaf** [comment]
Thanks @MohammadPCh The ended and archived donation are shown in user page
