### ISSUE TITLE
Bug: response not successful: received status code 400 error in  response of "updateRecurringDonationQuery"

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#4023]
**Describe the bug**
I've faced this bug in modifying flow and after modifying my active donation is changed to "ended" 

**To Reproduce**
1. Go to 'recurring donation' list
2. Click on 'one active donation'
3. tap on "modify flow rate"
4. confirm metmask message
5. See error

![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/39feb4d0-069e-429e-b5c2-54e2dd35727b)
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/116c1d97-76bd-4177-9041-615773bba2b7)
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/471ce130-ebcb-4838-a2b5-0ca9bb250c64)

**Comment by maryjaf** [comment]
It should be checked, I'm not sure it's backend or frontend problem
@jainkrati 
cc: @mohammadranjbarz @MohammadPCh

**Comment by maryjaf** [comment]
This error does not happen anymore, but now after modifying the "total donated" field is changed to 0
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/3e5f3d5d-a7e1-430b-b6e5-5e12798871bd)
@mohammadranjbarz @MohammadPCh

**Comment by maryjaf** [comment]
- [ ] 

It seems something was changed that makes this bug in donating,modifying... flow 
"response not successful: received status code 400"

please take a look on below record that shows this 400 error in donating flow 
- I made a donation to both "testmatic2020" and"Giveth" projects 
- After confirming metamask message, this error is shown
response not successful: received status code 400
-in my recurring donation list the new record for "testmatic2020" is recorded but with "active" status and total donated "0" in a normal flow it should be shown for a min "pending"
-and there is no new record for "Giveth" project

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/1c0e0018-dc7c-41f1-8577-17ec2d8528f0
cc: @mohammadranjbarz @CarlosQ96

**Comment by maryjaf** [comment]
Curl:
curl 'https://impact-graph.serve.giveth.io/graphql' \
  -H 'accept: */*' \
  -H 'accept-language: en' \
  -H 'authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdWJsaWNBZGRyZXNzIjoiMHhBMTE3OWY2NDYzOGFkYjYxM0REQUFjMzJEOTE4RUI2QkVCODI0MTA0IiwiZXhwaXJhdGlvbkRhdGUiOiIyMDI0LTA1LTE2VDExOjQwOjU1LjExNVoiLCJqdGkiOiIxNzEzMjY3NjU1MTE1LTY0NWI1OWNjN2IiLCJpYXQiOjE3MTMyNjc2NTUsImV4cCI6MTcxNTg1OTY1NX0.ieu5ZJVAohvf6-Kl-MyqT7MXDru_XnHk9iZz4nCAjXA' \
  -H 'authversion: 2' \
  -H 'content-type: application/json' \
  -H 'origin: https://staging.giveth.io' \
  -H 'referer: https://staging.giveth.io/' \
  -H 'sec-ch-ua: "Google Chrome";v="123", "Not:A-Brand";v="8", "Chromium";v="123"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-site' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36' \
  -H 'wallet-address: 0xa1179f64638adb613ddaac32d918eb6beb824104' \
  --data-raw $'{"operationName":"updateRecurringDonationQuery","variables":{"projectId":1,"networkId":11155420,"txHash":"0x4818232fabefdb6bc6e2f8bf673503137c6052d5b255e1c56c7092c1b357eb24","flowRate":"61309563370962","currency":"GIV","anonymous":false},"query":"mutation updateRecurringDonationQuery($projectId: Int\u0021, $networkId: Int\u0021, $currency: String\u0021, $txHash: String, $flowRate: String, $anonymous: Boolean, $isArchived: Boolean, $status: String) {\\n  updateRecurringDonationParams(\\n    projectId: $projectId\\n    networkId: $networkId\\n    txHash: $txHash\\n    anonymous: $anonymous\\n    flowRate: $flowRate\\n    currency: $currency\\n    isArchived: $isArchived\\n    status: $status\\n  ) {\\n    id\\n    txHash\\n    networkId\\n    currency\\n    flowRate\\n    anonymous\\n    status\\n    isArchived\\n  }\\n}"}'

**Comment by jainkrati** [comment]
@mohammadranjbarz couldnt repro. @maryjaf to try repro

**Comment by maryjaf** [comment]
> @mohammadranjbarz couldnt repro. @maryjaf to try repro

After last changes that  is made by @mohammadranjbarz it doesn't happen again , I don't move it to "done" to check more if I won't see this bug again I'll move it to done

**Comment by divine-comedian** [comment]
@maryjaf 

Any updates or are you still waiting to re-check if this issues occurs again?

**Comment by maryjaf** [comment]
> @maryjaf
> 
> Any updates or are you still waiting to re-check if this issue occurs again?

I haven't seen this error again
but I need a confirmation from @CarlosQ96 or @mohammadranjbarz for the below flow 
when I modify an active donation, after completing modify flow the status isn't changed to pending  and it remains active , is this ok? because in my previous tests after modify active donation, I saw the status changed to pending and after afew minutes change to active

**Comment by divine-comedian** [comment]
> > @maryjaf
> > Any updates or are you still waiting to re-check if this issue occurs again?
> 
> I haven't seen this error again but I need a confirmation from @CarlosQ96 or @mohammadranjbarz for the below flow when I modify an active donation, after completing modify flow the status isn't changed to pending and it remains active , is this ok? because in my previous tests after modify active donation, I saw the status changed to pending and after afew minutes change to active

As long of the rest of the related data is fine (numbers update correctly, etc..) then this flow is fine.
