### ISSUE TITLE
Twitter threads for Galactic Giving Round sponsors 

### ISSUE THREAD

**Issue by koday1** [Giveth/giveth-dapps-v2#4026]
Need to prepare a Twitter/X thread for the sponsors of the Galctic Giving Round.

Sponsors who will need to be included:

* Octant
* Public Nouns

* GMX (Not paid yet - will update here when they are confirmed)
* Premia (Could be small or big, not confirmed yet)

**Comment by oyealmond** [comment]
Hey @koday1! 

This issue should be in the comms / Marketing board. Please open it here: https://www.notion.so/giveth/d43ba90865ae430e982ac2eda39e103e?v=8ece43d3a2db4b6191d1bde4056e1f1a 

Also can you provide info on GMX / Premia? Link, information about who they are etc.

**Comment by koday1** [comment]
@oyealmond Thank you for the heads up! My mistake, still getting used to the flow of things. I will go ahead and create the issue over in the comms/marketing board. 

As for GMX/Premia, I don't have all the info but I will update the new issue as soon as I have it.

**Comment by laurenluz** [comment]
once you move all the info to notion for comms @koday1 please close this issue.

**Comment by koday1** [comment]
Moved to Notion - see Mkt/comms request hereL https://www.notion.so/giveth/d43ba90865ae430e982ac2eda39e103e?v=8ece43d3a2db4b6191d1bde4056e1f1a&p=4b6d4ad1d9784951a9f6a87ed9b5895b&pm=s
