### ISSUE TITLE
Hide GIVbacks icon on supertokens.. for now

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4032]
Until we implement https://github.com/Giveth/impact-graph/issues/1483 we should not show GIVbacks eligibility badge  on the super tokens icons, since we are not offering GIVbacks on super tokens for now.. but we will eventually. 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/f8ee7a21-2650-4be1-9d16-326121020afe)

**Comment by maryjaf** [comment]
Thanks @MohammadPCh it has been fixed
