### ISSUE TITLE
Remove GIVbacks donations from R59 Calculation

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#4035]
There have been recirculated donations brought to our attention by Trustalabs during the ENS qf round.
They should be removed before the votes can go up.

This is for Round 59 GIVbacks.

@MohammadPCh can you help with this? Thanks <3
cc @jainkrati 

https://optimistic.etherscan.io/tx/0xd7a4e579c8209ad19241f429b37b54402419a2f899a9d5f3fdf9c736b8ba342d
https://optimistic.etherscan.io/tx/0xe75ab55d4654ac5bb48b8bcfab380524ada45de6412b82b7fbee17a56eda5f73
https://optimistic.etherscan.io/tx/0x0fe304c6b300f69094fb13d4aba0afa8a0a309b7a6fa0c42be49c8f5e3712cc4
https://optimistic.etherscan.io/tx/0xb026fcef14f6f1d3d50fc92a6826e5dbea3deb99801165513ed6fa0b8d4199fb
https://optimistic.etherscan.io/tx/0xc8476d3e91f6fcaee85be305c5abf228660835e4d263cf3bbb0898c15749d9bb
https://optimistic.etherscan.io/tx/0x46203391e154c33971880780cebd72bd2b40fd9cff83949e1a25bdf76302d7df
https://optimistic.etherscan.io/tx/0xbd832e1a187f785a7ec5709c51daa1efa8e003a1bfc2399766c785a5239220b0
https://optimistic.etherscan.io/tx/0x5be490d27c2eff20df0921e1d6095c2f9a5083ef1344c3cdd0b707474a4bda02
https://optimistic.etherscan.io/tx/0x9d8956793c9ea2722267fd36c5f1142aceca7eb97047a9687ac2019d19530800
https://optimistic.etherscan.io/tx/0x95ed77df32b9bd95ac26741399a957b302ae749ea2e0b64a4cb03e6df511c572
https://polygonscan.com/tx/0x27007f70ae23d3387228b830e3d0153f2d3e4b4b55d45601055d6323c088cbd5
https://polygonscan.com/tx/0x1741f020f856240217b2e795a78099b0267823933969413d5649d0168014f694
https://gnosisscan.io/tx/0xb1ba5f9f7b6d6acfd327e6886ae69c65f313856192f61b34f0ccc0d8ea7ea727
https://gnosisscan.io/tx/0x869195abe6b45c12139c22413b6f64d3ba75672cbfda13148a555e9fae3e98e5
https://gnosisscan.io/tx/0xfeefc73c871986ca14379ade980ddaf4cb1f3469b4dc17cac9ee0444e522a69b
https://gnosisscan.io/tx/0x078ea40ee5cc91a45c35b95274f139dd0c8cf440bbdac8245e4a05ec1e24c87e
https://gnosisscan.io/tx/0x6269008df99e24c7794803e901211b0b236899d969d32fe8f3587406100c2406
https://optimistic.etherscan.io/tx/0x4118c9dcbd2ab6f5bf7aacc85970e72901561fac008ce574ca1c0c4fcc57d9ce

**Comment by jainkrati** [comment]
@mohammadranjbarz pls take this up as a p0 on 21st April

**Comment by mohammadranjbarz** [comment]
@WhyldWanderer It's done, can you test it?

**Comment by WhyldWanderer** [comment]
Hey @mohammadranjbarz - Im really sorry. There was some oversight and we excluded too many donations.

Can we please add these ones back in?

https://optimistic.etherscan.io/tx/0xd7a4e579c8209ad19241f429b37b54402419a2f899a9d5f3fdf9c736b8ba342d
https://optimistic.etherscan.io/tx/0xe75ab55d4654ac5bb48b8bcfab380524ada45de6412b82b7fbee17a56eda5f73
https://optimistic.etherscan.io/tx/0xc8476d3e91f6fcaee85be305c5abf228660835e4d263cf3bbb0898c15749d9bb
https://optimistic.etherscan.io/tx/0x95ed77df32b9bd95ac26741399a957b302ae749ea2e0b64a4cb03e6df511c572
https://polygonscan.com/tx/0x27007f70ae23d3387228b830e3d0153f2d3e4b4b55d45601055d6323c088cbd5
https://polygonscan.com/tx/0x1741f020f856240217b2e795a78099b0267823933969413d5649d0168014f694
https://gnosisscan.io/tx/0xb1ba5f9f7b6d6acfd327e6886ae69c65f313856192f61b34f0ccc0d8ea7ea727
https://gnosisscan.io/tx/0x869195abe6b45c12139c22413b6f64d3ba75672cbfda13148a555e9fae3e98e5
https://gnosisscan.io/tx/0xfeefc73c871986ca14379ade980ddaf4cb1f3469b4dc17cac9ee0444e522a69b
https://gnosisscan.io/tx/0x078ea40ee5cc91a45c35b95274f139dd0c8cf440bbdac8245e4a05ec1e24c87e
https://gnosisscan.io/tx/0x6269008df99e24c7794803e901211b0b236899d969d32fe8f3587406100c2406
https://optimistic.etherscan.io/tx/0x4118c9dcbd2ab6f5bf7aacc85970e72901561fac008ce574ca1c0c4fcc57d9ce

**Comment by WhyldWanderer** [comment]
Hey there @maryjaf - I see that you closed the issue. Do you know if these donations got added back in?

**Comment by mohammadranjbarz** [comment]
> https://optimistic.etherscan.io/tx/0xd7a4e579c8209ad19241f429b37b54402419a2f899a9d5f3fdf9c736b8ba342d
> https://optimistic.etherscan.io/tx/0xe75ab55d4654ac5bb48b8bcfab380524ada45de6412b82b7fbee17a56eda5f73
> https://optimistic.etherscan.io/tx/0xc8476d3e91f6fcaee85be305c5abf228660835e4d263cf3bbb0898c15749d9bb
> https://optimistic.etherscan.io/tx/0x95ed77df32b9bd95ac26741399a957b302ae749ea2e0b64a4cb03e6df511c572
> https://polygonscan.com/tx/0x27007f70ae23d3387228b830e3d0153f2d3e4b4b55d45601055d6323c088cbd5
> https://polygonscan.com/tx/0x1741f020f856240217b2e795a78099b0267823933969413d5649d0168014f694
> https://gnosisscan.io/tx/0xb1ba5f9f7b6d6acfd327e6886ae69c65f313856192f61b34f0ccc0d8ea7ea727
> https://gnosisscan.io/tx/0x869195abe6b45c12139c22413b6f64d3ba75672cbfda13148a555e9fae3e98e5
> https://gnosisscan.io/tx/0xfeefc73c871986ca14379ade980ddaf4cb1f3469b4dc17cac9ee0444e522a69b
> https://gnosisscan.io/tx/0x078ea40ee5cc91a45c35b95274f139dd0c8cf440bbdac8245e4a05ec1e24c87e
> https://gnosisscan.io/tx/0x6269008df99e24c7794803e901211b0b236899d969d32fe8f3587406100c2406
> https://optimistic.etherscan.io/tx/0x4118c9dcbd2ab6f5bf7aacc85970e72901561fac008ce574ca1c0c4fcc57d9ce

It's ok, I did it, now there are eligible
