### ISSUE TITLE
What is the story with the Giveth hand?

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#4036]
Who owns this? is it Mitch?

0x06263e1a856b36e073ba7a50d240123411501611

https://giveth.io/user/0x06263e1a856b36e073ba7a50d240123411501611?tab=givpower

It boosted a bunch of projects... i have a faint memory that we need to remove the boosting eventually?

ALSO

https://x.com/dexkit/status/1781396129436865007

They are sending swap fees there... is that ok?

ALSO!

We might need to use this address to verify for RetroPGF4

**Comment by divine-comedian** [comment]
That key was compromised a while back. I announced it on multiple channels.. 

The GIV was successfully taken out and sent back to the liquidity multisig. We also informed DexKIT to not use that address for anything.
