### ISSUE TITLE
Display Standard Card on Recurring Donation Tab

### ISSUE THREAD

**Issue by MohammadPCh** [Giveth/giveth-dapps-v2#4044]
<img width="1281" alt="Screenshot 2024-04-22 at 11 15 58 AM" src="https://github.com/Giveth/giveth-dapps-v2/assets/17097576/7eb4d989-fd1f-4136-9eda-c95f590cde90">

**Comment by MohammadPCh** [comment]
@maryjaf ready to test.

**Comment by maryjaf** [comment]
Thanks @MohammadPCh it has been fixed
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/5b1b8c92-a17b-4ddd-a3d4-b45b01467413)
