### ISSUE TITLE
Fix Button hover

### ISSUE THREAD

**Issue by MohammadPCh** [Giveth/giveth-dapps-v2#4051]
<img width="357" alt="Screenshot 2024-04-22 at 3 37 36 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/17097576/7e3b4fdb-73e4-48fc-bc90-1b4633ca3514">

**Comment by maryjaf** [comment]
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/148e3e85-7971-49c8-b334-02cacafc1377)
