### ISSUE TITLE
Create notify reward bot for GIVpower rewards extension April 30 - Oct 29 2024

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4057]
here is my spreadsheet: https://docs.google.com/spreadsheets/d/1neUUsppi4HZ5b0BlOUR60Vt2Hn-_e-hvoJeO20cTqyk/edit#gid=840759408

Basically on both Optimism & Gnosis Chain we should have the same amounts for the notify reward both:

|||GIV per round||
|---|---|---|---|
|Round 1|May 14|282500|6.65%|
|Round 2|May 28|286000|6.73%|
|Round 3|June 11|289000|6.80%|
|Round 4|June 25|292500|6.88%|
|Round 5|July 9|295500|6.95%|
|Round 6|July 23|298500|7.02%|
|Round 7|August 6|302000|7.11%|
|Round 8|August 20|305000|7.18%|
|Round 9|September 3|308500|7.26%|
|Round 10|September 17|311500|7.33%|
|Round 11|October 1|315000|7.41%|
|Round 12|October 15|318000|7.48%|
|Round 13|October 29|321500|7.56%|
|Round 14|November 12|324500|7.64%|
|Total GIV||4,250,000|100.00%|

And we need to assign a new balance for the unipools on gnosis & optimism... for 4,250,000 GIV on each chain.

@aminlatifi & I will sync on wednesday to set this up.

cc @jainkrati

**Comment by jainkrati** [comment]
I assume this is for creating connext liquidity ?

**Comment by laurenluz** [comment]
Hey @aminlatifi - I think I fixed it in the PRs, can you check?

**Comment by laurenluz** [comment]
I also updated the issue to have the right dates

**Comment by laurenluz** [comment]
@aminlatifi I think we can close this now right? everything is all good?
- Mitch topped up the Optimism token distro
- Mitch assigned a new balance of 4,250,000 GIV to the unipools on gnosis & optimism
- We set up the notify reward bots for both chains to start May 14

Done?

**Comment by aminlatifi** [comment]
@laurenluz I can set up the notify reward when we enter the last round of the current farming program. So let's keep it open when we do that also.

**Comment by mohammadranjbarz** [comment]
@aminlatifi Percentages, amounts and other numbers seems good.
Just one thing  as I see you haven't added :
`distributor:xDAI:givPower:extended:apr2024` to `./distributor-xDAI-givPower.sh` script, can you check it yourself?

**Comment by aminlatifi** [comment]
> @aminlatifi Percentages, amounts and other numbers seems good. Just one thing as I see you haven't added : `distributor:xDAI:givPower:extended:apr2024` to `./distributor-xDAI-givPower.sh` script, can you check it yourself?

It's renamed to May. Please double check with PRs.

**Comment by aminlatifi** [comment]
> > @aminlatifi Percentages, amounts and other numbers seems good. Just one thing as I see you haven't added : `distributor:xDAI:givPower:extended:apr2024` to `./distributor-xDAI-givPower.sh` script, can you check it yourself?
> 
> It's renamed to May. Please double check with PRs.

@mohammadranjbarz Could you double check the server configurations? are everything OK?

**Comment by mohammadranjbarz** [comment]
Thanks @aminlatifi everythings seems good, and I checked the server, crontab jobs and everything seems fine, I think we are good to go for tomorrow
