### ISSUE TITLE
Export final list of donations (with true/false if they were included or not) from ENS round

### ISSUE THREAD

**Issue by koday1** [Giveth/giveth-dapps-v2#4059]
Creating this issue to export the final results from the ENS QF round, accounting for Sybil/recirculation analysis. 

This issue is dependent upon the completion of https://github.com/Giveth/giveth-dapps-v2/issues/3857 (removing QF matching exceptions from counting)

After export, @laurenluz and I will double check the data before confirming it looks good and sending to the ENS team.

Once matching funds are paid out, we will need to add the data to the backend (issue https://github.com/Giveth/giveth-dapps-v2/issues/4018)

**Comment by koday1** [comment]
@laurenluz @jainkrati Created this issue to export the final results for the ENS round. This is dependent upon the completion of issue 3857 and I have marked it as such

**Comment by jainkrati** [comment]
@CarlosQ96 is this done as well/?

**Comment by laurenluz** [comment]
will close @jainkrati - I asked @CarlosQ96 in the end not to do this because he had other priorities blocking... this would have helped with the final analysis, but I made do without it
