### ISSUE TITLE
Update QF Round Banner for the Galactic Giving Round

### ISSUE THREAD

**Issue by koday1** [Giveth/giveth-dapps-v2#4063]
Need to finalize and update the QF round banner for the Galactic Giving round.

This is a follow up to https://github.com/Giveth/giveth-dapps-v2/issues/3961 and has been created to avoid re-opening that issue.

The sponsor list is being finalized and will be confirmed by April 25. @rodricastillo9013 is working on finishing the banner as the last sponsors are confirmed, at which point we will need to add the banner to the site.

Current list below

BIG:
    - Public nouns
    - Octant
    - GMX (pending txn)
    - Gains 
    - Arbitrum
    - Kyle/Gitcoin
   
SMALL:
    - Glo Dollar
    - LottoPGF
    - Open Dollar
    - Premia
    - MUX
    - WOOFi 
    - DODO
    - Rage Trade

**Comment by laurenluz** [comment]
![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/f05556aa-7980-4d6f-bfb6-e5c977166027)

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/8eb11942-16b7-4ba3-9528-148e13b5e8b6)

**Comment by koday1** [comment]
@rodricastillo9013 Adding DoDo logo: https://docs.dodoex.io/en/home/media-kit

**Comment by koday1** [comment]
Dodo logo 
![vertical yellow2-LOGO DODO](https://github.com/Giveth/giveth-dapps-v2/assets/34075192/2706352d-235b-4ac3-a66e-e5335fc4e580)


Rage trade logo 
![Rage Trade Logo](https://github.com/Giveth/giveth-dapps-v2/assets/34075192/d6b79ab5-3abd-4587-aae9-2f0128f0b889)

**Comment by koday1** [comment]
@jainkrati @RamRamez Rodri finished up the final banner, here's the Figma link: https://www.figma.com/file/W9Ace1RyCdykWM72fsSa3t/Giveth-Marketing-2024?type=design&node-id=6558-1086&mode=design&t=7PyOwWLwSf3nLgnB-4

Also attached here: 
![GalacticGivingBannerFINAL](https://github.com/Giveth/giveth-dapps-v2/assets/34075192/80812f6e-0585-438f-a64c-100bf2853ab6)

cc @laurenluz

**Comment by laurenluz** [comment]
@Meriem-BM - the final banner is here: https://www.figma.com/file/W9Ace1RyCdykWM72fsSa3t/Giveth-Marketing-2024?type=design&node-id=6554-1083&mode=design&t=Mk6FT1RVAaIiaUaF-0

looks like this:
![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/4b06d130-888f-4e50-ba96-93f9e04dad85)

@rodricastillo9013 can you share the .svg files for the background, the sponsors & any top corner art, so that she has easy access to build the responsive version?

**Comment by Meriem-BM** [comment]
@rodricastillo9013 could you wrap breederDodo elements in one group do I can copy it as svg

**Comment by laurenluz** [comment]
hey hey @Meriem-BM @jainkrati this round goes live at 11am ET - where's the hot fix? pleaaase

**Comment by Meriem-BM** [comment]
Its on staging

**Comment by jainkrati** [comment]
@maryjaf pls test and close

**Comment by maryjaf** [comment]
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/dc27c9a0-9379-4e37-9032-a1946b43da6e)
