### ISSUE TITLE
Project owner must be able to claim ETH from recurring donations

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4064]
We need to verify that users can claim their recurring donations in ETH successfully.

Krati is working on a workaround for a missing function from superfluid contracts that allows downgrading of ETH directly to another recipient address from the anchor contract, executed by the project owner.

_Originally posted by @divine-comedian in https://github.com/Giveth/giveth-dapps-v2/issues/3094#issuecomment-2075003636_

**Comment by maryjaf** [comment]
There is a problem in ETh claim flow
@MohammadPCh  
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/a07a03aa-5025-4667-b536-c4add03a1b39)

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/d5bf41ac-a6f8-4493-bc89-fa2f7465a199
