### ISSUE TITLE
Verification Social Media Post Link

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#4067]
The verification application used to ask project owners to post a link to their Giveth project from a social media account, website, github repo, etc. owned by the organization. There was a field for this in the application process.

Now this field just looks like an optional field with no explanation. Users are submitting the application without the link and this is a very important step of the verification process. This is how we verify that the project is actually owned by the org that it is claimed to be.

I don't have a screenshot of how it was before but this is what it looks like now.
![image](https://github.com/Giveth/giveth-dapps-v2/assets/74267818/4d9ca97d-1770-4ead-bafb-0c4fca418972)

Maybe this happened because we are now showing these links on the project page?
The link to their social media post should not be displayed on the project page. This is only for the verification team.
Maybe we need to add it to a different page of the form? 

Let me know if it's not clear or you have questions.

**Comment by MohammadPCh** [comment]
@maryjaf ready to test

**Comment by maryjaf** [comment]
This change isn't on stg environment @MohammadPCh 
<img width="1288" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzdDQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b6aba3f9a00b1624cfe114ee453b75042b2bbf0b/image.png" alt="image.png" />

**Comment by maryjaf** [comment]
Verification form:
<img width="1496" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFREQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--91a3177d115e15fccd617c3e232056d05d9dfadb/image.png" alt="image.png" />

Admin bro:
<img width="1787" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFhEQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--675374039b3e2faff57695b79b85722f02b8fb69/image.png" alt="image.png" />

Thanks guys
If you approve these changes, this issue could be closed @WhyldWanderer

**Comment by WhyldWanderer** [comment]
I ran through it on staging and it all looks good to me...
Thanks so much for prioritizing this and working out all of the kinks!
