### ISSUE TITLE
Review About Us page on Mobile phone

### ISSUE THREAD

**Issue by jahanzaib-jay** [Giveth/giveth-dapps-v2#407]
Hi there, 
I was surfing the website from my phone and notices a couple of issues on the "About us" page. 

![issue 1.jpeg](https://images.zenhubusercontent.com/620d7be8f7acb77200f9d2d9/bcad3398-7e00-4a7f-9007-a20a365cc1ea)

Here the Yellow line is blocking the text.

![isssue 2.jpeg](https://images.zenhubusercontent.com/620d7be8f7acb77200f9d2d9/8d785ce3-9a4f-4792-9a50-6c4704a510ac)

Here the text should be in center.

**Comment by jahanzaib-jay** [comment]
@MoeNick  can you please look into this?

**Comment by MoeNick** [comment]
Thanks for reporting @jahanzaib-jay
