### ISSUE TITLE
If you change networks in the middle of the superfluid stream creation, we don't make them switch back to OP Mainnet

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#4073]
![Screenshot 2024-04-29 at 12 10 40 PM](https://github.com/Giveth/giveth-dapps-v2/assets/14945613/f5eacd76-ba5f-4ec5-a5dc-21e88cc88e25)

GM! I started the stream creation, then changed the network to do other things.... and then came back to this screen, clicked approve and nothing happen.

I would expect that if I click approve, that a request to change networks should pop up and then the approve tx will automatically pop up too, without needing to click approve AGAIN! :-D

Please check other buttons for a required network switch and tx pop up tooooo

https://github.com/Giveth/giveth-dapps-v2/assets/67759413/81a32db4-5616-45d6-b3d5-1c988057ce0c

**Comment by divine-comedian** [comment]
@MohammadPCh - I think we just need to handle adding a check for the network and sending a switch network request when a user is doing any sort of action, including:

- [ ] Approving tokens 
- [ ] Creating recurring donation
- [ ] Depositing to stream balance
- [ ] Withdrawing from stream balance
- [ ] updating recurring donation amount
- [ ] claiming tokens from anchor contract

**Comment by maryjaf** [comment]
In the current flow by tapping on 
Deposit/withdraw button and Actions in recurring donation table, switch network to op is shown

**Comment by maryjaf** [comment]
But based on Griff screen record we should check this in the second step of these flows also

**Comment by divine-comedian** [comment]
@maryjaf - this issue is speaking of explicitly in this step where the confirmation modal is shown, not before.

**Comment by maryjaf** [comment]
> In these current flows the switch network is shown -Deposit/withdraw -Actions in recurring donation table (modify,end,archive) -Claim recurring donation -Create recurring donation tab @divine-comedian

Yeah I got it, based on this comment I thought you mean netwoek isn't checked on these flow now

But in fact, in these flows, the network is checked in the first step, but not in the next steps
And if the user changes the network during this interval, the network switch medal will not be displayed

**Comment by maryjaf** [comment]
> @MohammadPCh - I think we just need to handle adding a check for the network and sending a switch network request to the wallet provider when a user is doing any sort of action, including:
> 
> * [ ]  Approving tokens
> * [ ]  Creating recurring donation
> * [ ]  Depositing to stream balance
> * [ ]  Withdrawing from stream balance
> * [ ]  updating recurring donation amount
> * [ ]  claiming tokens from anchor contract

Yeah I got it, based on this comment I thought you mean network isn't checked on these flow now

But in fact, in these flows, the network is checked in the first step, but not in the next steps
And if the user changes the network during this interval, the network switch medal will not be displayed

**Comment by maryjaf** [comment]
I've tested on this branch
https://giveth-dapps-v2-git-fix-handle-wrong-network-givethio.vercel.app/
 the problem has been resolved 
 __
 Uploading Screen Recording 2024-04-30 at 3.04.53 PM.mov…




One question : @divine-comedian 
If user tap on "cancel" and doesn't switch network to OP for example in modifying flow 
the same error is shown, is it the expected result or some changes should be made in this scenario ? 
Network Mismatch Error: Your provider network chainId is: 100 whereas your desired chainId is: 11155420

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/975b7a4c-d954-486f-acd1-e1c4fb2f4ec5

**Comment by divine-comedian** [comment]
This flow looks good to me as is!

**Comment by MohammadPCh** [comment]
@maryjaf ready to test

**Comment by maryjaf** [comment]
This problem has been resolved
