### ISSUE TITLE
price fetching of ETH in recurring donation isn't working

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4075]
Currently the price of ETH is showing as 0 USD on recurring donation - however when I choose to make a one-time donation with the same amount the price appears to show correctly. 

This error only occurs when I am depositing into my stream balance and creating a recurring donation in a single tx

https://github.com/Giveth/giveth-dapps-v2/assets/67759413/7f35ebf8-915e-4259-8a48-647c40c72d8f

### when depositing & donating - no price
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/0ffc917d-9301-4e7f-a625-3a6d906d6345)

### when only donating - price shows
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/4af88693-3cc0-425c-b138-9d715124af5d)

**Comment by maryjaf** [comment]
Thanks @MohammadPCh It has been resolved on feature branch

**Comment by maryjaf** [comment]
It has been fixed on stg
