### ISSUE TITLE
Add a "max" button for the stream

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#4081]
<img width="677" alt="Screenshot 2024-04-30 at 12 31 02 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/14945613/0f8735bb-364e-4a09-8555-c5a78614e107">

I want to use the Max of the tokens i have in my wallet... but i don't have the option!

**Comment by divine-comedian** [comment]
Nice catch! We had this feature defined but must have overlooked it during QA.

@MohammadPCh - On the donation page when a user is entering the amount they want to deposit to their stream balance they should be able to click the "available" button and it puts into the input field their current balance for the selected token. 

However we need to set one condition, if the selected token is a native token, clicking the "available" text will enter their current balance - 0.0005 of native token. 

For example - user has 0.01 ETH, clicks 'available' to deposit all, field is input with 0.0995

**Comment by jainkrati** [comment]
Instead of "Available" we should add "MAX" because most web3 users are trained for it. Its intuitive. @divine-comedian

**Comment by divine-comedian** [comment]
> Instead of "Available" we should add "MAX" because most web3 users are trained for it. Its intuitive. @divine-comedian

Thanks for your suggestion, however we have the same functionality as described on one-time donation, so we just need to copy it over for recurring donations

**Comment by MohammadPCh** [comment]
@maryjaf ready to test

**Comment by maryjaf** [comment]
It has been fixed
