### ISSUE TITLE
Make the stream amount round numbers, ideally only 3 sig figs

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#4082]
<img width="616" alt="Screenshot 2024-04-30 at 12 38 41 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/14945613/3fc04a80-62a4-4b37-96d4-7fdda925b9b1">

I dont want to stream 1278.328889 tokens per month... I want to stream 1270 GIV a month 

All the extra digits are unnecessary and confusing

**Comment by divine-comedian** [comment]
Gets kinda weird when say you have 0.1 ETH in your balance and you want to use part of that in a recurring donation, decimals get small and they matter!

hopefully #4034 will remedy your pains Griff
