### ISSUE TITLE
Success page needs to be customized for Streaming donations!

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#4083]
As a streamer, I would love to get a custom success page that is specifically for streaming.

#1 This just looks a little bare... lots of blank space, so mention about how to end the stream, top up the stream or manage the stream in general

<img width="1440" alt="Screenshot 2024-04-30 at 12 42 30 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/14945613/6c3fdb0b-8cc3-4413-833f-b5963dd4a022">

#2 The social links should have stream specific content, tagging superfluid and Optimism so that we can get this feature well known!

<img width="538" alt="Screenshot 2024-04-30 at 12 44 20 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/14945613/d5631b25-b247-4ba1-a093-c0a109394e2d">

**Comment by GriffGreen** [comment]
ok! I found where i can manage the stream: https://giveth.io/account?tab=recurring-donations

It was REALLY hard to find tho!

**Comment by divine-comedian** [comment]
No problem, we can add some extra content to the success page for recurring donations. 

Let's add the following sections headers & text

### Managing your recurring donations
You can modify or delete your recurring donation as well as top-up funds to your stream balance from the [My Recurring Donations ](https://giveth.io/account?tab=recurring-donations) page.

To learn more about how recurring donations work, visit our [documentation article](https://docs.giveth.io/dapps/recurringDonation/).

**Comment by Tosinolawale** [comment]
![Sstreaming 2](https://github.com/Giveth/giveth-dapps-v2/assets/35389241/b26606ca-3b33-45ee-a25a-89c84a1e9c1d)
When GIVbacks is not Eligible 
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/GIVeconomy?type=design&node-id=25672%3A23572&mode=design&t=H9ZoIMHf7AcsZAdD-1

**Comment by Tosinolawale** [comment]
@divine-comedian @GriffGreen

**Comment by MohammadPCh** [comment]
@maryjaf ready to test

**Comment by maryjaf** [comment]
It has been changed on STG correctly
