### ISSUE TITLE
Copy fix on QF round summary stats!!

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4086]
the copy doens't work when the round is yet to start, we should fix asap since we are sending people here now, and it looks unprofessional.

Should say

- [x] "Round start"
- [x] "Round end"
- [x] and the $ on  the matching pool amout should be at the beginning, not the end of the number. i.e. $30,000

instead of ... "round started"... "ends on"...

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/58a1b77a-5539-45de-a582-ebff146fb496)

cc @jainkrati - maybe @Meriem-BM can grab this when she updates the banner #4063 in a hot fix?

**Comment by laurenluz** [comment]
cc @koday1

**Comment by MohammadPCh** [comment]
@maryjaf ready to test
