### ISSUE TITLE
SEO related updates to homepage copy 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4104]
From @krmet report on SEO improvements we should update parts of the homepage text and metadata to improve our SEO rating. 

Here is the table of changes we should make, including where the copy is located, the previous text and what the updated text should be:

|  | Current description  | SEO optimized description  |  |  |
| --- | --- | --- | --- | --- |
|  |  |  |  |  |
| Meta title | Giveth: Welcome to the Future of Giving | Giveth: Future of Giving with Zero-Fee Crypto Donation |  |  |
|  |  |  |  |  |
| Meta Description  | Get rewarded for giving to for-good projects with zero added fees. Donate crypto directly to thousands of for-good projects, nonprofits & charities! | Get rewarded for crypto donations to for-good projects with zero added fees and accepting crypto donations. Donate crypto directly to thousands of nonprofits & charities! |  |  |
|  |  |  |  |  |
| Homepage | Discover what makes Giveth different from other donation platforms | Discover what makes Giveth different from other crypto donation platforms |  |  |
|  |  |  |  |  |
|  | Giveth empowers changemakers with evolutionary funding. | Giveth empowers changemakers to accept crypto donations. |  |  |
|  |  |  |  |  |
|  | Join our community-driven movement to transform the way we fund nonprofits and social causes. | Join our community-driven movement to transform the way we fund nonprofits and social causes using innovative crypto fundraising strategies. |  |  |
|  |  |  |  |  |
|  | Trust that your donations will make an impact with our verification system. | Trust that your crypto donations will make an impact with our verification system. |  |  |
|  |  |  |  |  |
|  | Get rewarded for giving to verified public goods projects. | Get rewarded for giving to verified public goods projects with crypto donations. |  |  |
|  |  |  |  |  |
|  | New to crypto? It’s easy to get started on Giveth. | New to crypto fundraising? It’s easy to get started on Giveth. |  |  |
|  |  |  |  |  |
|  | Giveth is building a new way forward with our zero-fee, community-driven donation platform - leveraging the power of blockchain technology to connect on-the-ground projects with regenerative funding opportunities. | Giveth is building a new way forward with our zero-fee crypto donation, community-driven donation platform - leveraging the power of blockchain technology to connect on-the-ground projects with regenerative funding opportunities. |  |  |
|  |  |  |  |  |
|  | An evolution in community fundraising. | An evolution in supporting donations to charity with community fundraising. |  |  |
|  |  |  |  |  |
|  | Your donations, and participation in the GIVeconomy, enables us to build a new future where real world impact projects benefit from their own community-driven regenerative economies. | Your crypto donations, and participation in the GIVeconomy, enables us to build a new future where real world impact projects benefit from their own community-driven regenerative crypto economies. |  |  |

## Checklist

- [ ] - **Meta title**: Update from "Giveth: Welcome to the Future of Giving" to "Giveth: Future of Giving with Zero-Fee Crypto Donation"
- [ ] - **Meta Description**: Update from "Get rewarded for giving to for-good projects with zero added fees. Donate crypto directly to thousands of for-good projects, nonprofits & charities!" to "Get rewarded for crypto donations to for-good projects with zero added fees and accepting crypto donations. Donate crypto directly to thousands of nonprofits & charities!"
- [ ] - **Homepage**: Update from "Discover what makes Giveth different from other donation platforms" to "Discover what makes Giveth different from other crypto donation platforms"
- [ ] -  **Homepage**: Update from "Giveth empowers changemakers with evolutionary funding." to "Giveth empowers changemakers to accept crypto donations."
- [ ] - **Homepage**: Update from "Join our community-driven movement to transform the way we fund nonprofits and social causes." to "Join our community-driven movement to transform the way we fund nonprofits and social causes using innovative crypto fundraising strategies."
- [ ] - **Homepage**: Update from "Trust that your donations will make an impact with our verification system." to "Trust that your crypto donations will make an impact with our verification system."
- [ ] - **Homepage**: Update from "Get rewarded for giving to verified public goods projects." to "Get rewarded for giving to verified public goods projects with crypto donations."
- [ ] - **Homepage**: Update from "New to crypto? It’s easy to get started on Giveth." to "New to crypto fundraising? It’s easy to get started on Giveth."
- [ ] - **Homepage**: Update from "Giveth is building a new way forward with our zero-fee, community-driven donation platform - leveraging the power of blockchain technology to connect on-the-ground projects with regenerative funding opportunities." to "Giveth is building a new way forward with our zero-fee crypto donation, community-driven donation platform - leveraging the power of blockchain technology to connect on-the-ground projects with regenerative funding opportunities."
- [ ] - **Homepage**: Update from "An evolution in community fundraising." to "An evolution in supporting donations to charity with community fundraising."
- [ ] - **Homepage**: Update from "Your donations, and participation in the GIVeconomy, enables us to build a new future where real world impact projects benefit from their own community-driven regenerative economies." to "Your crypto donations, and participation in the GIVeconomy, enables us to build a new future where real world impact projects benefit from their own community-driven regenerative crypto economies."

**Comment by jainkrati** [comment]
@MohammadPCh will this be a good issue for kkechy to pick up?

**Comment by MohammadPCh** [comment]
@jainkrati Sure. @kkatusic can you take it?

**Comment by kkatusic** [comment]
> @jainkrati Sure. @kkatusic can you take it?

I can, thx

**Comment by kkatusic** [comment]
@jainkrati, @MohammadPCh you can check pull request: #4137

**Comment by kkatusic** [comment]
@MohammadPCh just noticed, that meta tags, first two meta tags in this issue doesn't have translation management

**Comment by divine-comedian** [comment]
@kkatusic @MohammadPCh - Looks like this was merged to staging, we should move this to DONE and only close when it is merged to production.
