### ISSUE TITLE
GIVeconomy transactions don't work on Mobile/Android

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4106]
Testing 
Google Pixel 7
Android OS
Chrome Browser/MetaMask

visting the givfarm page I try to do any GIVpower transaction, while connected to the giveth website with metamask they all fail. I can click the button, arrive at the metamask tx confirmation - when I click accept to the transaction MetaMask throws an error as Internal RPC error! "

I tried all these functions with no success: 

- [ ] Stake
- [ ] Unstake
- [ ] Harvest
- [ ] Increase Rewards

https://github.com/Giveth/giveth-dapps-v2/assets/67759413/e667d372-a302-4183-8c6d-dab0177bbc37

When I switched to desktop I was able to execute the transaction with no issue.

**Comment by jainkrati** [comment]
@RamRamez can you pls take a quick look.

**Comment by mohammadranjbarz** [comment]
@divine-comedian 
Are you sure it's not from your end?
Is it possible to change the RPC URL of your network and test it again?
And also please test with gnosis chain as well to see the result

@maryjaf  I would appreciate if you can test it with android and ios devices and share the result with us (for both gnosis, OP and mainnet networks)

**Comment by divine-comedian** [comment]
> @divine-comedian Are you sure it's not from your end? Is it possible to change the RPC URL of your network and test it again? And also please test with gnosis chain as well to see the result
> 
> @maryjaf I would appreciate if you can test it with android and ios devices and share the result with us (for both gnosis, OP and mainnet networks)

I was notified by a user report on twitter of the GIVeconomy not working on mobile, which led me to testing it myself, please let me know the results from testing on iPhone!

**Comment by maryjaf** [comment]
I've tested Stake,Unstake,Harvest, Lock flows on iPhone 12 and there is no problem on my device

**Comment by laurenluz** [comment]
@WhyldWanderer maybe you can try testing this on android?

**Comment by WhyldWanderer** [comment]
I tested this morning and was able to complete all four actions that mitch outlined successfully 🚀

**Comment by divine-comedian** [comment]
I get a very cryptic error, not sure what it could be about!

![Screenshot from 2024-05-13 13-25-12](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/dcb5e631-8abc-4c79-b586-dfbcad35979e)

**Comment by divine-comedian** [comment]
UPDATE:  I did a fresh reinstall of metamask on my device and everything appears to be working fine now! closing this one.

**Comment by kkatusic** [comment]
> UPDATE: I did a fresh reinstall of metamask on my device and everything appears to be working fine now! closing this one.

@divine-comedian you have always option inside MetaMask to clear all cache, maybe you did this already, but here it is:

![clear](https://github.com/Giveth/giveth-dapps-v2/assets/1242145/d78192c9-2c18-4ee7-87f6-b3161cbb1927)
