### ISSUE TITLE
Add Telegram as option for adding social media links in project creation/edit page

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4107]
We should add another field to allow projects to add a link to their Telegram groups in the project creation flow. 
## Project Creation/Edit
![Create Project UI](https://github.com/Giveth/giveth-dapps-v2/assets/35389241/d86f7fa1-f77c-448a-b69f-c53a95c2d59e)
https://www.figma.com/file/vMiyVd1Ly5LjgSyZrChVV8/Giveth-users?type=design&node-id=2676%3A85227&mode=design&t=GirFVLd4FldPdLKF-1

## Project public view
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/cb811233-7ce9-4fef-b9dc-2f865c720365)
https://www.figma.com/file/vMiyVd1Ly5LjgSyZrChVV8/Giveth-users?type=design&node-id=1907%3A23890&mode=design&t=GirFVLd4FldPdLKF-1

---
Do we need to handle any back-end changes for this field or can we handle this new field for Telegram related to project socials without changes @RamRamez ? 
old BE issue for reference - https://github.com/Giveth/impact-graph/issues/1364

**Comment by Tosinolawale** [comment]
![Create Project UI](https://github.com/Giveth/giveth-dapps-v2/assets/35389241/d86f7fa1-f77c-448a-b69f-c53a95c2d59e)
https://www.figma.com/file/vMiyVd1Ly5LjgSyZrChVV8/Giveth-users?type=design&node-id=2676%3A85227&mode=design&t=GirFVLd4FldPdLKF-1

**Comment by Tosinolawale** [comment]
@divine-comedian

**Comment by Tosinolawale** [comment]
![Project Single - About](https://github.com/Giveth/giveth-dapps-v2/assets/35389241/f3a2daa9-8fe5-4796-92a8-8f2cfadcdcb6)
https://www.figma.com/file/vMiyVd1Ly5LjgSyZrChVV8/Giveth-users?type=design&node-id=1907%3A23890&mode=design&t=GirFVLd4FldPdLKF-1
Project Profile View

**Comment by Meriem-BM** [comment]
@maryjaf this issue is ready for test

**Comment by maryjaf** [comment]
> ## Project public view
> ![image](https://private-user-images.githubusercontent.com/67759413/327519252-cb811233-7ce9-4fef-b9dc-2f865c720365.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2ODc0MjgsIm5iZiI6MTcxNTY4NzEyOCwicGF0aCI6Ii82Nzc1OTQxMy8zMjc1MTkyNTItY2I4MTEyMzMtN2NlOS00ZmVmLWI5ZGMtMmY4NjVjNzIwMzY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDExNDUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4NWI3ZWMyZDYxMTJiZDc4MDg5MGQyZTE3NTg0M2MwZDcxZjlkZTEzMTFhNDBmMTBhYWEzM2E3ZjY1NDRmZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eitKmWTytr7sxsk6HYHkjFD4VRvM1O7Ll65xtK4iK80) https://www.figma.com/file/vMiyVd1Ly5LjgSyZrChVV8/Giveth-users?type=design&node-id=1907%3A23890&mode=design&t=GirFVLd4FldPdLKF-1

Thanks @Meriem-BM 
There is no problem in setting telegram link in create project flow 
but please take a look on this :
The colors of telegram and linkedin are same
