### ISSUE TITLE
Not all maintence is scheduled, please fix splash page

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#4112]
![Screenshot 2024-05-02 at 2 37 19 PM](https://github.com/Giveth/giveth-dapps-v2/assets/14945613/d6dddff9-8e23-4514-927e-31c650cec2fd)

just delete "scheduled"

**Comment by divine-comedian** [comment]
fixed in https://github.com/Giveth/giveth-dapps-v2/commit/38e638df3a23a6f3cac3cad6038f6989a4f080ad
