### ISSUE TITLE
Add back functionality to bypass maintenance mode splash page

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4113]
When the maintenance mode splash page is up we should have a way to bypass it to continue debugging on production. 

Previously we allowed it by clicking in the corner of the page to bypass the splash page and use the website normally. 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/c6e2431e-4b4d-4eb5-bea7-4fffec95dfc9)

**Comment by jainkrati** [comment]
@divine-comedian are you suggesting it should be for everyone in produciton?
