### ISSUE TITLE
Metrics at the top of the QF round can improve in a few ways

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#4114]
<img width="1424" alt="Screenshot 2024-05-02 at 8 53 36 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/14945613/731f2f22-9a15-4271-92ff-eb263724af6c">

- [x] Matching pool should have a comma: $50,000
- [x] Donations should round to 2 decimals:$387.31
- [x] # of unique donors isn't right. It seems like its number of donations, every time i donate it goes up by 1

**Comment by GriffGreen** [comment]
RE: # of unique donors isn't right. It seems like its number of donations, every time i donate it goes up by 1

<img width="670" alt="Screenshot 2024-05-03 at 4 49 12 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/14945613/b1cf32c4-2204-4616-8e78-d2f144dc0704">

**Comment by divine-comedian** [comment]
finished this one last week and live on production

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/7e45afc1-1786-4084-9780-8b539ed3f28b)
