### ISSUE TITLE
Users Unable to verify email address

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#4119]
**Describe the bug**
Users who are trying to fill out the application for project verification are unable to verify their email address.
One user reported in Discord here: https://discord.com/channels/679428761438912522/1236954000859861023/1236954132246433822
And the other user reported the issue in Giveth TG group: https://t.me/Givethio

It happened with 2 different users from 2 different projects.

**Screenshots**
![image](https://github.com/Giveth/giveth-dapps-v2/assets/74267818/fbaa6155-e721-42db-afee-60e1bc434c00)

**Desktop (please complete the following information):**
Chrome

**Comment by WhyldWanderer** [comment]
Another user reported here: https://discord.com/channels/679428761438912522/1236998431189499946/1236998676606615554
Also for a different project than both listed above

**Comment by maryjaf** [comment]
Was a new item deployed after the SuperFluid changes? because I submitted verification form in sanity test on production after superfluid  deploying and there is no problem on this flow
actually I want to know which changes is made this problem

**Comment by divine-comedian** [comment]
Testing on Staging I get the same error. Here is my console:

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/5c94a9f4-977a-4786-89c3-87249a025135)

**Comment by divine-comedian** [comment]
@maryjaf - We should be able to test this with success on prod and staging now.

**Comment by maryjaf** [comment]
This issue has been resolved on stg and prod
