### ISSUE TITLE
QF eligible chains message is incorrect

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#4123]
A user reported that they were donating to an active round qf project and got a message that has incorrect information.

![image](https://github.com/Giveth/giveth-dapps-v2/assets/74267818/54015f35-304e-4c4c-947f-46680c7be060)

The eligible networks listed should be Ethereum Mainnet, Gnosis, Polygon PoS, OP Mainnet, Aribitrum One for the Galactic Giving round.

How the user reached this message:

1. Navigate to a project that is in the active qf round and accepts funds on a network that is not eligible for this round (Celo in this case)
2. Press the "Donate" button
3. select token and amount then press "donate" button
4. After pressing the button the above message appears

It seems that the message on the donate page is correct
![image](https://github.com/Giveth/giveth-dapps-v2/assets/74267818/61029efd-646d-4686-b3d9-744a8833d3a9)

But once the button is pushed, you get the above message.

**Comment by jainkrati** [comment]
@MohammadPCh once you add kkechy, will this be a good issue for him to pick up?

**Comment by MohammadPCh** [comment]
@kkatusic, could you handle it? I'm available to assist if you need any help.

**Comment by kkatusic** [comment]
> @kkatusic, could you handle it? I'm available to assist if you need any help.

I will take it thx and ask for help if needed, thx @MohammadPCh
