### ISSUE TITLE
Use NextJS Image instead of img tag

### ISSUE THREAD

**Issue by MohammadPCh** [Giveth/giveth-dapps-v2#4124]
We need to ensure that we use the Next.js `<Image />` component instead of the standard `<img>` tag on our important pages.

**Comment by divine-comedian** [comment]
The following images have been converted to Image files and can be tested for consistency and expected responsive behaviour: 

- [ ] blog posts image cards on homepage 
- [ ] uploading & showing profile picture on my account and public user pages
- [ ] uploading & previewing banner image on project creation/edit
- [ ] hands image on givbacks page 
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/d989820d-07cd-4da3-8098-195b35ee8e28)

- [ ] profile picture image on navbar when logged in
- [ ] background yellow 'arc' designs on project creation success page
- [ ] org badge on project cards - i.e. 'giving block', 'change'
- [ ] cog gears on maintenance page 
- [ ] warning symbols on error page (i.e. 500, 404 error pages)
- [ ] toggle 'carets' when choosing project category 
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/23792879-62be-45f7-bdb4-cddaafb272e4)

There is a known issue related to GIVbacks image here - https://github.com/Giveth/giveth-dapps-v2/issues/4131

**Comment by maryjaf** [comment]
could you please take a look on this ? the giveback icon isn't shown correctly @MohammadPCh 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/4eb96d39-8abc-425d-9e23-0eb7817906ab)


> * [ ]  hands image on givbacks page
>   ![image](https://private-user-images.githubusercontent.com/67759413/329862053-d989820d-07cd-4da3-8098-195b35ee8e28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3OTYxNTQsIm5iZiI6MTcxNjc5NTg1NCwicGF0aCI6Ii82Nzc1OTQxMy8zMjk4NjIwNTMtZDk4OTgyMGQtMDdjZC00ZGEzLTgwOTgtMTk1YjM1ZWU4ZTI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDA3NDQxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlNTY1NDNjNjgwYjVhYTA1ZTk5NTRhYmExMjE5ZmFmMjc2MTYwOTBhNzVkMTkxOWJlYzQ3ZDU5NTQ2Yzg5ZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6SjVszNVvjdhUlGc4VsD9Ip3y1EY7KZH4C1gWujY4z0)
> * [ ]  org badge on project cards - i.e. 'giving block', 'change'
> * [ ]  cog gears on maintenance page

And I didn't understand  these 3 items @MohammadPCh

**Comment by divine-comedian** [comment]
@maryjaf  - the GIVbacks icon is not related to these changes and we're following it in #4131 

The other 3 points I can clarify 

- hands image on GIVbacks page (scroll to bottom - see component)
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/d9f41d65-65ce-482d-993e-2e326fa53f01)

- org badge  
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/34daea3b-8904-48bb-8ebb-78b3305391e4)

- cogs on maintenance page - I tested these so you can actually ignore it, it's very hard to test without dev access

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/fe06e3ab-6204-442f-823c-114035dcbaef)

**Comment by jainkrati** [comment]
@maryjaf @divine-comedian what is needed to we complete this?
