### ISSUE TITLE
Repurpose "Likes" feature into "Bookmark" feature

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4128]
Following up on removing uneccesary information on project cards, improving our page loading performance we should get rid of most of the UI elements regarding the "like"  feature, the few that remain we will rename to be a "Bookmark". 

This will allow users to bookmark projects that they want to keep track of or check out at another time. Their list of bookmarked projects will be found under the current tab named "liked projects' under my account. 

# We should get rid of these UI elements and their associated BE calls:

## Project Card
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/815a3200-c5a6-4196-b21b-9ef5f6193a89)

## My Projects page 
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/9f0fb211-06e4-4255-8e01-62f39db4c37a)

## Projects Sorting 
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/e28d136d-3fb4-4659-aa08-bb588422f0be)

# We should change the icon/text for these references to likes: 

## Project Details
change heart icon to bookmark icon. remove number count & associated BE call
we should still check if the connected user has bookmarked this project, this behaviour remains the same. clicking this icon either adds or removes it from the users "liked" or "bookmarked" projects
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/4645cc42-c4ab-4397-a8de-60c91710821c)

## My Liked Projects 
change text from Liked Projects to Bookmarked Projects
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/419c017f-5e61-4de1-b0e3-6a8a052aeca7)

---- 

## Bookmark Icon
Here is the new icon we can use instead of the likes button icon 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/673f6890-f1cd-41ef-88b4-5625efb8dfad)
https://www.figma.com/design/C3HykACu0eNImhAqu0our8/Giveth-projects?node-id=6062-25124&t=mnkiPuI5OngA4Ksj-4

**Comment by divine-comedian** [comment]
@Tosinolawale - Could you please add a bookmark icon to the DS? Something simple that will replace the heart icon on some pages as described above. 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/6a585d2a-be34-4266-9f0b-c4db975bb5df)

**Comment by mosaeedi** [comment]
<img width="1189" alt="Screenshot 2024-05-14 at 7 15 05 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/fe881728-c840-47e1-90d0-f936b688aaab">

Link to the project card -> [Figma link](https://www.figma.com/design/C3HykACu0eNImhAqu0our8/Giveth-projects?node-id=6062-25124&t=mnkiPuI5OngA4Ksj-4)

**Comment by MohammadPCh** [comment]
@divine-comedian, is the bookmark's back-end ready? Can you share the BE issue link here?

**Comment by divine-comedian** [comment]
> @divine-comedian, is the bookmark's back-end ready? Can you share the BE issue link here?

It works exactly the same as likes we just modify some UI elements so it feels like bookmarking instead. For now you can use the same endpoints and remove calling them from the relevant places in our UI page loads

**Comment by MohammadPCh** [comment]
@divine-comedian Should we remove likes from `My Projects` too?
<img width="1274" alt="Screenshot 2024-06-26 at 11 48 28 AM" src="https://github.com/Giveth/giveth-dapps-v2/assets/17097576/2b3a8eab-3878-49f7-bcfb-81a51e1fa512">

**Comment by maryjaf** [comment]
> <img alt="Screenshot 2024-05-14 at 7 15 05 PM" width="1189" src="https://private-user-images.githubusercontent.com/13708322/330505225-fe881728-c840-47e1-90d0-f936b688aaab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NzI3NTgsIm5iZiI6MTcxOTQ3MjQ1OCwicGF0aCI6Ii8xMzcwODMyMi8zMzA1MDUyMjUtZmU4ODE3MjgtYzg0MC00N2UxLTkwZDAtZjkzNmI2ODhhYWFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDA3MTQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkNGJkMTcxNGYzODI3ZDllOGI1Y2JmNTM3NGFkMmQyNGJjMDE4Y2QzZmI5ODc4ZTZkZjZiMGYzM2E1NGJjODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XdiUMx-zAS-4nIKISDCtknmIBroZpKsEYDUNDHMn0GI">
> Link to the project card -> [Figma link](https://www.figma.com/design/C3HykACu0eNImhAqu0our8/Giveth-projects?node-id=6062-25124&t=mnkiPuI5OngA4Ksj-4)

- [ ] project card isn't based on the figma @MohammadPCh 

<img width="1555" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeW1YQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1e54ca40ca2e25519fd28ba10d0ba79e5de8ed0c/image.png" alt="image.png" />

**Comment by divine-comedian** [comment]
@maryjaf  - I think @Tosinolawale misunderstood the design requirements, we shouldn't show the bookmark icon on the all projects page since the purpose of this feature was to remove the need to load likes on the all projects page, making it easier to load.

This view looks correct to me, even though the design file is wrong.
