### ISSUE TITLE
Update Quadratic Force PDF to new version 

### ISSUE THREAD

**Issue by koday1** [Giveth/giveth-dapps-v2#4129]
We added a bunch of new sponsors for the Galactic Giving round, and Rodri updated the Quadratic Force PDF to reflect the new sponsors. We also updated the sponsor tiers to $2k-$8k-$16k.

Here's the new PDF: 
[Giveth_QF_Force.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEcvQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0a93d9ac06b22ff6015f2eb105590061aade2335/Giveth_QF_Force.pdf)

Figma Link: https://www.figma.com/file/W9Ace1RyCdykWM72fsSa3t/Giveth-Marketing-2024?type=design&node-id=6458-2418&mode=design&t=fVFKQUfjQHPk5IEb-4

@jainkrati Can we add this to the site once the P0 dapp issues are addressed?

Cc @laurenluz @SnakeGH

**Comment by laurenluz** [comment]
this should replace the current pdf living at https://giveth.io/quadraticforce

**Comment by Meriem-BM** [comment]
Hey @MohammadPCh, @RamRamez when I replaced the current PDF with this new one it's showing all PDF pages blank, even tho I can see the file from my machine correctly, have you encountered this issue before?

**Comment by Meriem-BM** [comment]
@maryjaf you can check this, it's on staging.
