### ISSUE TITLE
GIVbacks Logo is not showing properly

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4131]
Noticed this on production but it looks like the GIVbacks logo somehow is not being show properly, you can only see a sliver of the hand and the image itself is overflowing outside of the element container... 

https://github.com/Giveth/giveth-dapps-v2/assets/67759413/091a3eef-35d4-4a1e-b628-d0ca588dd041

cc: @laurenluz

**Comment by jainkrati** [comment]
@MohammadPCh once you add kkechy, will this be a good issue for him to pick up?

**Comment by MohammadPCh** [comment]
@kkatusic can you pick it up? Thanks.

**Comment by kkatusic** [comment]
> @kkatusic can you pick it up? Thanks.

I will, thx
