### ISSUE TITLE
"uncomment" GIVbacks eligible-related frontend pieces that were hidden for superfluid integration

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4132]
We discussed in the GIVeconomy call that we will be making all recurring donations to verified projects in givbaks eligible tokens count towards GIVbacks... right away :-D

So the parts that we hid before to exclude GIVbacks should be brought back in.

@MohammadPCh - I'm assuming you know exactly what these are? or do you need more specific context?

cc @divine-comedian @jainkrati 

related to https://github.com/Giveth/impact-graph/issues/1483

**Comment by jainkrati** [comment]
@MohammadPCh lets finish this by 13th May atleast

**Comment by maryjaf** [comment]
Is this issue related to only showing givback icon on tokens like below pic? @MohammadPCh 
or for example in donate page and success donation page a related box for givback should be shown?
<img width="1082" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFVBQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--252123fc9bd5d4eeb97f0e61fb2533c21f7c62b6/image.png" alt="image.png" />

**Comment by divine-comedian** [comment]
@maryjaf  @MohammadPCh 

We should have on the donate page the toast notif like this :
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/ca466e04-5f83-455b-8432-ea9c0608d8c8)

here on the recurring donation donate view:

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/d93d831c-47fe-43f8-aa0e-33bb8b275af4)


We should also make sure we include the 'eligible for givbacks' component on the success page
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/30d858f2-0f7a-40a3-966b-0e38b2af6ca5)

**Comment by MohammadPCh** [comment]
@divine-comedian @maryjaf we have these:
![image](https://github.com/Giveth/giveth-dapps-v2/assets/17097576/df14d94c-590a-45ca-bd1f-8589c472d3c6)
![image](https://github.com/Giveth/giveth-dapps-v2/assets/17097576/4737fd72-a031-4e77-9128-967f549804a8)
but we have to add this:
![image](https://github.com/Giveth/giveth-dapps-v2/assets/17097576/05d2a55e-febc-4640-93a5-e905af939b76)
I'll work on it.
