### ISSUE TITLE
Add network column to donations table on user page

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4138]
Currently while looking at the private and public view of the user's donation table there is no column that identifies on which network a donation was made:

![Screenshot from 2024-05-09 18-39-36](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/cf1ec71f-673b-4079-a0c3-0a0fb8f368f7)

We should add a column to this table and show the network logo for each donation to allow the user to know which network they have made their donations on. Similar to the recurring donations table: 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/d8a55822-b23d-4d4b-a26f-eb3f828b76ce)

**Comment by jainkrati** [comment]
@kkatusic pls take guidance from @RamRamez on solving this

**Comment by kkatusic** [comment]
> @kkatusic pls take guidance from @RamRamez on solving this

Thx @jainkrati I will ask @RamRamez

**Comment by divine-comedian** [comment]
@MohammadPCh - Did this to go production or staging? We should close it only when it hits production
