### ISSUE TITLE
Base | changes on Donation page

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#4148]
As a user i want to donate with Base tokens to a project. 

- [ ] List of supported Base tokens on staging abnd production with their logos and their GIVback eligibility should be correct
<img width="936" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2Y5QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d9bf90ca6ed78fe1287c6f02c464c0d21d725dc8/image.png" alt="image.png" />

- [x] Balances of tokens should be correct after selection. 
<img width="324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzc5QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4647df4eb65ea70f917bf406e7cdc18dc53f8bae/image.png" alt="image.png" />

- [x] If the project does not have any Bas address defined and if user is on Base, we should show an error with supported chainlist.
<img width="1882" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3I5QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9a3fd4aabb54f6c747c388c0f87916d95bdac4af/image.png" alt="image.png" />

- [x] If the project has a Base address defined and if user is on a chain which is not supported by project, we should show an error with supported chainlist and we should see the Base logo here which can leads to switch network. 

- [x] The price of all tokens on Base should be correct on donation modal
<img width="681" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFQ5QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c871a8eb0235994c15afb9d3f0e0285c56a93d54/image.png" alt="image.png" />

- [x] Transaction should work properly and process with the network and user should see the success page in a happy scenario. 

- [x] The link to explorer should be correct in success page
<img width="876" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOG45QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--46c32264e63a1bbdb284b8bbefe30d851e580752/image.png" alt="image.png" />

**Comment by maryjaf** [comment]
> [ ] List of supported Base tokens on staging abnd production with their logos and their GIVback eligibility should be correct

Only base token on stg is "ETH" and "givbeck eligible" isn't enable for this  @MoeNick @Meriem-BM 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/b1248590-8edb-48b4-8a85-67f7f5cab252)

**Comment by maryjaf** [comment]
> Only base token on stg is "ETH" and "givbeck eligible" isn't enable for this @MoeNick @Meriem-BM

I've set "is givback eligible " for this token from admin bro, and now it is ok
but only one question, should there be only this token on stg? @MoeNick

**Comment by MoeNick** [comment]
> > Only base token on stg is "ETH" and "givbeck eligible" isn't enable for this @MoeNick @Meriem-BM
> 
> I've set "is givback eligible " for this token from admin bro, and now it is ok but only one question, should there be only this token on stg? @MoeNick

Not it should be also LINK token so we make sure we can support tokens as well. I described it here https://github.com/Giveth/impact-graph/issues/1559 
(I can see you make this done from test, so Im assuming we have it back-end and not here? ) 

@maryjaf

**Comment by maryjaf** [comment]
The icon of Link token isn't shown  @Meriem-BM 
<img width="1476" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmtyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e20ac4a1169ac72e4be1017e48a865608b7b610b/image.png" alt="image.png" />

**Comment by MoeNick** [comment]
@maryjaf I think not having an icon on staging is OK.
