### ISSUE TITLE
GIVback overview in my account

### ISSUE THREAD

**Issue by mosaeedi** [Giveth/giveth-dapps-v2#415]
## Why?
Users need to have an Overview of GIVbacks in one place, "My account" so they can see the GIVbacks they harvested from different sources

## How to measure?
This is a new thing that we are adding and we need to observe user behavior to understand how they are using it!

## Design resources
This feature is still under development, we are missing the Responsive and mobile guide

- [My account overview](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=3889%3A104687)
- [List of donations](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=3898%3A119510)

**Comment by Tosinolawale** [comment]
GIVBacks Overview 

https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=7446%3A192290

@MoeNick  @mosaeedi

**Comment by markoprljic** [comment]
Looks ok.

**Comment by mosaeedi** [comment]
@MoeNick Design is done.
