### ISSUE TITLE
Remove Safe option from web3modal

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4152]
Connecting my wallet to the Dapp I can see a few options on web3modal that are confusing/misleading to the user. 

There is an option to choose Safe, which shouldn't be there, Giveth only allows Safe connections directly through the Safe Apps UI, so it should not be shown there as an option since if a users tries to connect their Safe this way, it won't work.

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/72b6d49e-2fec-4467-a3af-107cd0c3e0e5)

**Comment by HrithikSampson** [comment]
@LatifatAbdullahi @maryjaf , this issue is ready to be tested.

**Comment by LatifatAbdullahi** [comment]
@divine-comedian  @HrithikSampson 
**Test Update**

Status: Test Passed

The "Safe" option has been removed as required.



![image](https://github.com/user-attachments/assets/ac0004bf-1765-4bb4-ba48-7bfc8267c2c5)



Uploading Giveth_ Future of Giving with Zero-Fee Crypto Donation - Google Chrome 2024-08-28 18-27-14.mp4…
