### ISSUE TITLE
copyfix on superfluid popup (1st donor)

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4162]
![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/8e3e20a4-7308-4ce0-adf8-8b8cd1759235)

it's weird to me that this popup is called "set up allo protocol registry" - are we using Allo? is this even true? why do we need to tell the user that?

can we call this instead something like:

"Heads up!" ?

@divine-comedian

**Comment by laurenluz** [comment]
maybe we can also remove the "guess what? you're awesome!"?

**Comment by divine-comedian** [comment]
Thanks! I fixed this and other copy improvements in https://github.com/Giveth/giveth-dapps-v2/commit/d238ce7c380d2f7c86e6936910f733e2e4ccc5d7
