### ISSUE TITLE
Used changeAddress to transfer GIVstream, subgraph is showing wrong amount now

### ISSUE THREAD

**Issue by RamRamez** [Giveth/giveth-dapps-v2#4165]
I had 65 GIV/week on my first account and 8370 GIV/week stream on the second account, I decided to move my stream from first account to second one, I used this function:
https://gnosisscan.io/address/0xc0dbDcA66a0636236fAbe1B3C16B1bD4C84bB1E1#writeProxyContract#F4

But after that, my stream of my first account became zero and second one became 65.
![image](https://github.com/Giveth/impact-graph/assets/73441857/50aee6e1-e0d0-4995-b479-b44351c906e7)

Actually I should have something like 8435 GIV/week stream for the second account.
There's a possibility that there's something wrong with Subgraph because after one day the dapp is showing I only have 0.3 claimable GIV

![image](https://github.com/Giveth/giveth-dapps-v2/assets/73441857/f94d584c-840c-4937-9b94-b47fa3f9d289)

but when I harvest, I got 1500 GIV. So, it seems my stream is ok but dapp is not showing the correct number.

cc @divine-comedian

**Comment by divine-comedian** [comment]
For more context. 

I told ramin to run the `changeAddress` function that I modified a couple months ago. It appears from what I can tell that his claimable and allocated amounts were successfully added from his old address to his new address. 

I ran the calculations directly from the information on the smart contract and everything appears to be working as intended on a smart contract level. 

but for some reason the subgraph is not noticing the change in his GIVstream.

**Comment by aminlatifi** [comment]
@divine-comedian @RamRamez We had forgotten to update the production subgraph
Done by this
https://github.com/Giveth/giveconomy-subgraph/pull/71

**Comment by aminlatifi** [comment]
It's deployed, waiting to be synced.
May take long time 
https://thegraph.com/hosted-service/subgraph/giveth/giveth-economy-second-xdai?version=pending

**Comment by divine-comedian** [comment]
@RamRamez - can you test this when it is synced?

**Comment by RamRamez** [comment]
It's ok now, thanks
![image](https://github.com/Giveth/giveth-dapps-v2/assets/73441857/921b770f-144c-4273-ba17-a84324f1fd51)
