### ISSUE TITLE
Allow Sharing links directly to Farcaster

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4167]
We currently allow users to share messages to their communities via direct social media post links for twitter, facebook and linkeding
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/77ba0da7-38a6-42fb-b4cc-74b62e6fdba9)

We should allow users who have a farcaster account to share messages for these scenarios:
 
- successful donation
- successful project creation
- project page

We can use the same message text that is from the pre-drafted twitter message.

**Comment by MohammadPCh** [comment]
@kkatusic can you take it?

**Comment by divine-comedian** [comment]
@kkatusic what is the update on this issue?

**Comment by kkatusic** [comment]
@divine-comedian, cc @MohammadPCh, we use `react-share` package for all other social networks, unfortunately it doesn't support, better to say don't have Forecast share option. I manage by adding custom link that open in another window tab and you can make share, cast that link. Composing that is described in their documents on this [link](https://docs.farcaster.xyz/reference/warpcast/cast-composer-intents) , they don't have option to open their embeded modal window, user have to do cast on their webpage app.

![Screenshot 2024-06-22 at 15 50 09](https://github.com/Giveth/giveth-dapps-v2/assets/1242145/ad612fac-b0f7-4ec7-97bc-04bd39f87da8)
![Screenshot 2024-06-22 at 16 13 44](https://github.com/Giveth/giveth-dapps-v2/assets/1242145/0754700b-9b17-403a-b437-ae14ff7521df)
![Screenshot 2024-06-22 at 16 28 24](https://github.com/Giveth/giveth-dapps-v2/assets/1242145/364b26d2-6e0c-4d4a-9df3-dd87392b1e5e)
![Screenshot 2024-06-22 at 15 50 04](https://github.com/Giveth/giveth-dapps-v2/assets/1242145/ef30a8d5-7a65-4bf1-a4b8-d7447e34eb84)

**Comment by kkatusic** [comment]
> Guys!!! it's wired! I didn't close it!!!

Something is closing your issues :)

**Comment by divine-comedian** [comment]
I think it is related to attaching the issues directly to the PR, when you merge the PR, zenhub closes all the attached issues - for now better to reference them in the issues or PR but not to "attach" them. 
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/5995b39f-9e5d-44d3-8a26-b5f3f60ef3d3)


I'll check if we can change this behaviour in the settings.

**Comment by maryjaf** [comment]
> * successful donation
> * successful project creation
> * project page

I've checked and it has been added in above pages

**Comment by divine-comedian** [comment]
@kkatusic - @MohammadPCh - if we can approve this feature on staging is it possible to make a small release for this? It would be nice to have this feature for the QF round that just opened today.

**Comment by kkatusic** [comment]
> Just tested it out, this feature looks great!
> 
> @kkatusic - @MohammadPCh - if we can approve this feature on staging is it possible to make a small release for this? It would be nice to have this feature for the QF round that just opened today.

@divine-comedian I don't have access for deploying branch and merging, @MohammadPCh isn't hre, maybe @RamRamez or @Meriem-BM can approve it ;)

**Comment by Meriem-BM** [comment]
> > Just tested it out, this feature looks great!
> > @kkatusic - @MohammadPCh - if we can approve this feature on staging is it possible to make a small release for this? It would be nice to have this feature for the QF round that just opened today.
> 
> @divine-comedian I don't have access for deploying branch and merging, @MohammadPCh isn't hre, maybe @RamRamez or @Meriem-BM can approve it ;)

I'll prepare a PR for this

**Comment by Meriem-BM** [comment]
> > Just tested it out, this feature looks great!
> 
> > 
> 
> > @kkatusic - @MohammadPCh - if we can approve this feature on staging is it possible to make a small release for this? It would be nice to have this feature for the QF round that just opened today.
> 
> 
> 
> @divine-comedian I don't have access for deploying branch and merging, @MohammadPCh isn't hre, maybe @RamRamez or @Meriem-BM can approve it ;)

It's deployed, can check it pls.

**Comment by divine-comedian** [comment]
Looks good! Closing this one.
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/d038c11e-0727-4ec5-a9e7-bdd6fe938d3f)
