### ISSUE TITLE
Remove uniswap-v2 subgraph dependency 

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapps-v2#4168]
We use uniswap-v2 subgraphs to fetch token prices on chains. This dependency must be removed and replace its usage with fetching price from coingecko.

NOTE: The subgraph hosted service will be deprecated and we have removed subgraph usage for price fetching in other places.

**Comment by jainkrati** [comment]
@mohammadranjbarz @mhmdksh  pls share updates on this as you make progress

**Comment by mohammadranjbarz** [comment]
@maryjaf  can you test it, please?
You should donate **GIV** token and the price should fill correctly
