### ISSUE TITLE
Export donation list from Galactic Giving Round 

### ISSUE THREAD

**Issue by koday1** [Giveth/giveth-dapps-v2#4169]
Need to grab a list of all the Galactic Giving donations now that the round has ended.

This is dependent on 2 open issues:
https://github.com/Giveth/impact-graph/issues/1556
https://github.com/Giveth/giveth-dapps-v2/issues/3284

Lauren and I will conduct a preliminary analysis to see if we think it's worth it to send this data to Trusta Labs for Sybil analysis again.

After Sybil analysis (internal or external) we'll update the Sybil list and create another issue to export the final donation list with TRUE/FALSE for all donations.

**Comment by laurenluz** [comment]
This is the query @CarlosQ96 made to get this data... one note... we need to include the purple list condition when determinig the True/False for "isMatchingIncluded"

cc @mohammadranjbarz 

`SELECT d.id, p.title , p.slug, d."transactionId", d."toWalletAddress", d."fromWalletAddress", d.currency, d.anonymous, d.amount, d."valueUsd", d."createdAt", d."projectId", d."userId", d."transactionNetworkId", d."valueEth", d."priceEth", d."priceUsd", d.nonce, d.status, d."tokenAddress", d."isProjectVerified", d."qfRoundId", d."qfRoundUserScore", u.email, CASE WHEN d."qfRoundUserScore" > qr."minimumPassportScore" and d."valueUsd" > qr."minimumValidUsdValue" THEN true ELSE false END AS "isMatchingIncluded"
FROM public.donation as d
inner join "user" u on u.id = d."userId"
inner join project p on p.id = d."projectId" 
inner join qf_round qr on qr.id = d."qfRoundId" 
where "qfRoundId" = 9;`

**Comment by jainkrati** [comment]
@CarlosQ96 is this already done?

**Comment by koday1** [comment]
@jainkrati Yeah this is done, Lauren and I worked with Carlos to get the right data export for the round and the results are up on the forum now. Will close this issue. cc @laurenluz @CarlosQ96
