### ISSUE TITLE
Can't donate with Wallet Connect

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#417]

**Comment by aminlatifi** [comment]
I have 1 GIV in my multisig wallet, but donate view doesn't recognize it
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/5684607/163791207-9cda3b64-64c8-4418-837e-f607756b5563.png">

<img width="916" alt="image" src="https://user-images.githubusercontent.com/5684607/163791267-b04d434c-c139-4901-a7d0-0f7cbe019186.png">

**Comment by aminlatifi** [comment]
If the grpc node url is the issue, we can use a public one like this
https://rpc.ankr.com/eth

**Comment by divine-comedian** [comment]
testing on `staging.giveth.io` 

appears to be having the same issue as before. I can successfully connect my gnosis-safe with walletConnect

we can see on staging it shows my DRGIV3 balance in the top corner, however in the donate modal it is not detecting any of my tokens, making it impossible to donate.

![image](https://user-images.githubusercontent.com/67759413/169868088-6f81c892-430d-4342-a265-dc76bc74f2a2.png)

moving back to backlog

**Comment by divine-comedian** [comment]
@MoeNick 

Do we have any current Wallet Connect integration? This is used often by mobile apps as well, not only multisigs

**Comment by MoeNick** [comment]
It was working but we removed it due to the bug that I remember it was for the grpc node url and should use public one.
https://rpc.ankr.com/eth

However, we decided to do it again here as you brought it up: https://github.com/Giveth/giveth-dapps-v2/issues/3053

**Comment by MoeNick** [comment]
we can close this one
