### ISSUE TITLE
Problem showing menu in Verification view in mobile

### ISSUE THREAD

**Issue by RamRamez** [Giveth/giveth-dapps-v2#4177]
![Untitled 2](https://github.com/Giveth/giveth-dapps-v2/assets/73441857/eeaf7560-edef-4e1b-9489-06bdbe4c7c07)

**Comment by RamRamez** [comment]
@maryjaf please test and verify

**Comment by maryjaf** [comment]
This problem has been resolved but take a look on below video , after verifying email address in well done page there is no button for completing  the flow 
@RamRamez 
https://github.com/Giveth/giveth-dapps-v2/assets/111529185/30f99411-21fa-4bd2-8a18-85a46d05d9a5

**Comment by RamRamez** [comment]
> This problem has been resolved but take a look on below video , after verifying email address in well done page there is no button for completing the flow @RamRamez
> 
>  RPReplay_Final1716200788.mp4

Seems the Continue button is hidden under the Giveth logo and the purple pattern. It's not related to my PR and it's an old issue.

**Comment by maryjaf** [comment]
> > This problem has been resolved but take a look on below video , after verifying email address in well done page there is no button for completing the flow @RamRamez
> > RPReplay_Final1716200788.mp4
> 
> Seems the Continue button is hidden under the Giveth logo and the purple pattern. It's not related to my PR and it's an old issue.

https://github.com/Giveth/giveth-dapps-v2/issues/4179
