### ISSUE TITLE
After verifying email in verification flow "Continue" button is hidden under the Giveth logo and the purple pattern 

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#4179]
After verifying email in verification flow "Continue" button is hidden under the Giveth logo and the purple pattern.
this problem happens on mobile view 

1. Go to 'my project'
2. Click on 'an unverified project'
3.tap on"verify project" button
4. enter your email
5. tap on confirm button in email
6. see problem 

 - Device: iPhone 12
 - Browser chrome

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/30f99411-21fa-4bd2-8a18-85a46d05d9a5

cc: @RamRamez

**Comment by divine-comedian** [comment]
@mosaeedi - can you please investigate this issue?

**Comment by divine-comedian** [comment]
@mosaeedi - could you link to the view that shows us how this page should look on mobile

**Comment by mosaeedi** [comment]
Here is the Mobile version.

[Link to Figma](https://www.figma.com/design/WCfheR8ID8yqNglhW1ZeM0/Project-Verification?node-id=6278-9538&t=6yyyAS5vBIBX7t4i-4)

<img width="213" alt="Screenshot 2024-09-24 at 5 00 35 PM" src="https://github.com/user-attachments/assets/957259b6-aa55-47e6-9c96-f9dc19a6b411">

CC: @divine-comedian

**Comment by maryjaf** [comment]
> * Device: iPhone 12
> * Browser chrome



> After verifying email in verification flow "Continue" button is hidden under the Giveth logo and the purple pattern. this problem happens on mobile view
> 
> Steps to reproduce the behavior:
> 
> 1. Go to 'my project'
> 2. Click on 'an unverified project'
>    3.tap on"verify project" button
> 3. enter your email
> 4. tap on confirm button in email
> 5. see problem
> 
> * Device: iPhone 12
> * Browser chrome
> 
>  RPReplay_Final1716200788.mp4 


I've checked again  but I see the above video like as before

**Comment by kkatusic** [comment]
@maryjaf when you find time you can check it again, thx

**Comment by maryjaf** [comment]
- [ ] the button is shown correctly but bt tapping on this nothing happens

- [ ] in this case that the link is expired the ui has a problem

**Comment by maryjaf** [comment]
Thanks @kkatusic item 2 has been fixed 
The problem related to click on button also  has been resolved but there is another problem , by clicking on button the page isn't loaded and loading icon is shown in mobile view 
I'm not sure this problem is exactly related to this issue or it needed new issue 
@divine-comedian

**Comment by maryjaf** [comment]
https://github.com/user-attachments/assets/15bef23f-a0d1-44ce-ab93-e24d864494c2

**Comment by kkatusic** [comment]
@maryjaf you can test again when you get time ;)

**Comment by maryjaf** [comment]
Thanks @kkatusic the problem has been fixed
