### ISSUE TITLE
The project status is not displayed correctly within its border

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#4180]
The project status is not displayed correctly within its border in "my project" list on **mobile** 

**To Reproduce**
1. Go to 'my project' list
2. see the status of project 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/478e3730-2cd9-4948-a04d-be1c1cb27e0d)

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - Browser:Chrome
 
cc: @RamRamez

**Comment by maryjaf** [comment]
The problem of mobile view has been resolved but now on desktop "action" is shown like below pic @MohammadPCh 
<img width="1460" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTRSQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fe23d73f7949db3ff8ab1b1d353c9ac073c536b7/image.png" alt="image.png" />

**Comment by maryjaf** [comment]
The problem of mobile view has been resolved but now on desktop "action" is shown like below pic @MohammadPCh 
<img width="1460" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTRSQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fe23d73f7949db3ff8ab1b1d353c9ac073c536b7/image.png" alt="image.png" />

**Comment by maryjaf** [comment]
The problem of mobile view has been resolved but now on desktop "action" is shown like below pic @MohammadPCh 
<img width="1460" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTRSQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fe23d73f7949db3ff8ab1b1d353c9ac073c536b7/image.png" alt="image.png" />

**Comment by MohammadPCh** [comment]
Thanks @maryjaf  Nice catch, please test it again

**Comment by maryjaf** [comment]
> Thanks @maryjaf Nice catch, please test it again
no change

![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/a88add6b-4e59-40a4-b18c-1a2dee1840c6)
