### ISSUE TITLE
"Flip" GIVbacks - most GIVbacks should go out on Optimism, only gnosis donations get GIV on gnosis

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4181]
As discussed in the last GIVeconomy call, we want to move GIVbacks more onto Optimism network.

So that only donations from gnosis get GIVbacks on Gnosis.
And donations on all other eligible chains, get GIVbacks on Optimism.

cc @WhyldWanderer @divine-comedian @GriffGreen @jainkrati

**Comment by laurenluz** [comment]
@mohammadranjbarz do you think we'll be able to deliver this by the start of the next round Tuesday May 28?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz do you think we'll be able to deliver this by the start of the next round Tuesday May 28?

@laurenluz Yeah I  try to do it, but we should hold on and don't merge till @WhyldWanderer give us approval to merge it

**Comment by mohammadranjbarz** [comment]
It's implemented on https://github.com/Giveth/giveth-dapps-v2/issues/4181#issuecomment-2124192706, but we just can merge it after @WhyldWanderer tell us

FYI @divine-comedian  @laurenluz

**Comment by jainkrati** [comment]
lets merge and close this @mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
> lets merge and close this @mohammadranjbarz

ّI think we should wait till @WhyldWanderer tell us merge it, because Ashley wants to have this feature after distributing previous givback rewards

**Comment by WhyldWanderer** [comment]
Yes please!
I will let you know when we have the green light to merge it.

We still have a couple rounds to distribute first.
Thanks Krati & Mohammad!

**Comment by jainkrati** [comment]
let us know when we should proceed @WhyldWanderer

**Comment by WhyldWanderer** [comment]
This is now ready for implementation @mohammadranjbarz @jainkrati

**Comment by mohammadranjbarz** [comment]
> This is now ready for implementation @mohammadranjbarz @jainkrati

Thanks @WhyldWanderer  I merged/deployed it, please let me know if you found something incorrect

**Comment by WhyldWanderer** [comment]
I finished the calculation today and everything looks accurate!

Great job guys <3

I think we can close this one now
