### ISSUE TITLE
Update Quadratic Force PDF on Giveth to the newest version

### ISSUE THREAD

**Issue by koday1** [Giveth/giveth-dapps-v2#4185]
Rodri has updated the Quadratic Force PDF to display the new sponsor tiers ($2k - $8k - $16k), add sponsor logos, and other changes.

Can we please update the PDF hosted at https://giveth.io/QuadraticForce to the new version?

Quadratic Force PDF Figma: https://www.figma.com/design/W9Ace1RyCdykWM72fsSa3t/Giveth-Marketing-2024?node-id=6458-2418&t=5SiO8OSPQHPTJqZr-4

cc @laurenluz

**Comment by koday1** [comment]
Hey @RamRamez @divine-comedian I created this issue to update the quadratic force PDF hosted at https://giveth.io/QuadraticForce. This is essentially a duplicate of https://github.com/Giveth/giveth-dapps-v2/issues/3897 and should be a quick fix. Could you assign it or let me know who it should be assigned to? Thanks

**Comment by divine-comedian** [comment]
@jainkrati can help you find a developer to take this on.

**Comment by koday1** [comment]
@kkatusic You're correct, the updated version is there now. Awesome. Closing this issue
