### ISSUE TITLE
RegenFarms Transaction Status modal displays 'Add GIV to MetaMask' but should display 'Add [Reward Token] to MetaMask'

### ISSUE THREAD

**Issue by willyogo** [Giveth/giveth-dapps-v2#419]
<img width="845" alt="image" src="https://user-images.githubusercontent.com/26232238/161396387-478d055c-d561-49a0-825e-2ff42eddcb3e.png">

AC:
1. The transaction status modal for any regen projects should have a button to 'Add [Reward Token] to MetaMask' with Reward Token matching the corresponding RegenFarm

**Comment by laurenluz** [comment]
@MoeNick would be good to get this one fixed asap

**Comment by divine-comedian** [comment]
testing on `staging.giveth.io` 

the modal appears to be update on tx pending and tx successful screen
![image](https://user-images.githubusercontent.com/67759413/163844207-3ad1d286-1b49-41b2-a551-9917e848f487.png)

moving to DONE
