### ISSUE TITLE
Recurring Donations table not parsing token decimals properly

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4196]
In this donation on production you can see the USDC amount matched seems wildly out of proportion compared to the USD value 

I think we are not considering that USDC has a decimal precision of 6 while most other tokens it is 18. We should fix this so the decimal precision is taken into consideration when showing values on this table and in other views as well. 

This should be treated as a hotfix since this is a visual bug on production. 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/ec8abb43-4350-44dc-a6eb-e86b3ee2cd23)

**Comment by mohammadranjbarz** [comment]
@maryjaf Can you test it?

https://giveth.io/project/pcrf-palestine-childrens-relief-fund?tab=donations

## Before

<img width="1263" alt="Screenshot 1403-04-25 at 2 50 05 in the afternoon" src="https://github.com/user-attachments/assets/1803fd30-77d1-458f-b862-bd7e4b2a1188">


## After
<img width="1273" alt="Screenshot 1403-04-25 at 4 42 41 in the afternoon" src="https://github.com/user-attachments/assets/88396bef-c787-4cc6-9d7e-5f334030fda6">

@divine-comedian  @maryjaf If you can create another USDC recurring donation to monitor it for few days would be great

**Comment by maryjaf** [comment]
This problem has been fixed.

![image](https://github.com/user-attachments/assets/e3c62920-75a1-43a5-8bb6-2d48cb50f70a)
