### ISSUE TITLE
Shows total USD value of recurring donation on private and public view

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4197]
We should add in on the recurring donations table a column to show the total USD value of a user's donations from a given recurring donation on both the public view and private view. 

## current public view 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/bb6a25c0-9e6d-412b-8d3e-f300b579fed0)

## current private view

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/0f3fdad0-6783-4986-afdc-867596139c5e)

## current project donation table view (for ref.)

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/6ac09a25-d63a-435a-bd34-eeac7d818968)

**Comment by Tosinolawale** [comment]
![Update Private View](https://github.com/Giveth/giveth-dapps-v2/assets/35389241/f9e3337e-8e63-4b6d-a72c-29be003fbbc5)
https://www.figma.com/design/nVoinu0tgJ565enN5R4WDE/GIVeconomy?node-id=23642%3A13324&t=RucaS0w5ViE0hcza-1

**Comment by Tosinolawale** [comment]
PUBLIC VIEW
![Public View](https://github.com/Giveth/giveth-dapps-v2/assets/35389241/0ba95a42-f097-41f3-81b9-686a82091b09)
https://www.figma.com/design/nVoinu0tgJ565enN5R4WDE/GIVeconomy?node-id=23644%3A29401&t=RucaS0w5ViE0hcza-1

**Comment by Tosinolawale** [comment]
@divine-comedian

**Comment by maryjaf** [comment]
The Usd value is shown for user page in public and private view .
