### ISSUE TITLE
Better handling of public user profile with no name set

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4198]
When a user has a profile on Giveth but has not set a first name or last name there is a few weird things that happen as a result.

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/c5afc1eb-20d4-410f-9c95-d8b76065018d)

### page metadata
 the meta data shows `null null` which I assume is because it cannot find the first and last name. If no names can be found for this profile we should instead use the user address shortened to the first 8 characters and followed by an ellipsis (...)
 so from the example above the metadata should show like:
 
 > Giveth | 0xf8a025b... User Profile

## user information tabs 

On certain tabs such as Projects and Donations it says 'Unknown's Projects' or 'Unknown's Donations'  because we don't have any names to show- When their is no name found for the user profile instead we should use their address instead of unknown

for example:

> 0xf8a025b42b07db05638fe596cce339707ec3cc71's Projects

**Comment by maryjaf** [comment]
Thank @MohammadPCh 

@divine-comedian Is this view approved? 

<img width="1215" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelVTQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e8a6164a07a636acda81cad59180f69c46e1550c/image.png" alt="image.png" />

**Comment by maryjaf** [comment]
Thanks @MohammadPCh 
@divine-comedian Is this view approved? 
<img width="1163" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVlTQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f87c33c0e39e5b383cacd6dc9a17e73a53f8f509/image.png" alt="image.png" />

**Comment by maryjaf** [comment]
Now for saved user the wallet address is shown as its name @MohammadPCh 

<img width="1347" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzBTQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ffd7b1d748b8986faf08d0067ba98a3ea7b618a5/image.png" alt="image.png" />

**Comment by divine-comedian** [comment]
Looks mostly good - I think the only change we can make @MohammadPCh is to shorten the address on the Donations and Projects tab, it looks nicer.

So for example it would show:
> 0xf8a025b...'s Donations 
> 0xf8a025b...'s Projects

**Comment by maryjaf** [comment]
> So for example it would show:
> 
> > 0xf8a025b...'s Donations
> > 0xf8a025b...'s Projects

@MohammadPCh it's not based on Mitch's comment

![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/a5930113-9936-490c-83d2-84e0149f8f67)

**Comment by divine-comedian** [comment]
> > So for example it would show:
> > > 0xf8a025b...'s Donations
> > > 0xf8a025b...'s Projects
> 
> @MohammadPCh it's not based on Mitch's comment
> 
> ![image](https://private-user-images.githubusercontent.com/111529185/342645250-a5930113-9936-490c-83d2-84e0149f8f67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMzIwOTYsIm5iZiI6MTcxOTMzMTc5NiwicGF0aCI6Ii8xMTE1MjkxODUvMzQyNjQ1MjUwLWE1OTMwMTEzLTk5MzYtNDkwYy04M2QyLTg0ZTAxNDlmOGY2Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNVQxNjA5NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05Y2M4N2E5MTM4Y2FkYjRjYjFjMjAxNjFmZjM5MGJlNWUxM2UyZGRkNzUzNWNmZjhlZTI0OWFiNjVkNmViYTgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qpAvt-oVs1VeErmvG8ZD9AHnbsSNPNT1c1aasmB8qCE)

@maryjaf 

I think it looks fine, just to be clear 

on the page metadata - shorten address with elipsisis ....
on page tab - show full address

**Comment by MohammadPCh** [comment]
@maryjaf  OMG 😢 
Please re-check it after about 10 mins.

**Comment by maryjaf** [comment]
Thanks @MohammadPCh it has been fixed
