### ISSUE TITLE
Add More Actions to Actions menu on my projects page

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4199]
When a user is visiting the 'my projects' page they should be able to easily find the verify project button. They should also be able to deactivate and activate their project as well from this same actions menu
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/23e0f5a7-9424-49d0-a35b-05cd74270ade)

## Acceptance Criteria | AC
On the Action bar for the project card we should handle the following:

- [ ] When a project's verified status is  'Not Verified' we should show an option called `Verify Project` - this leads to verification page.
- [ ] When a project's verified status is  'Incomplete' (their application is started but not submitted) we should show an option called `Resume Verification` - this leads to verification page.
- [ ] When project's status is Active there should be an option to deactivate their project
- [ ] when project's status is deactive there should be an option to activate their project

cc: @WhyldWanderer

**Comment by kkatusic** [comment]
@divine-comedian just to notice you, I'm half done, for other half will ask @MohammadPCh what is best practice to do inside code enable activation/deactivation.

![verify_project](https://github.com/Giveth/giveth-dapps-v2/assets/1242145/c0f21c1f-9d5f-49f2-a755-ac9b7ed20d5e)

**Comment by MohammadPCh** [comment]
@kkatusic I'll dm you.

**Comment by divine-comedian** [comment]
@MohammadPCh @kkatusic What is the update on this issue?

**Comment by kkatusic** [comment]
> @MohammadPCh @kkatusic What is the update on this issue?

@MohammadPCh and I will check that on Monday, I push working branch, all function are there but having issue changing state for _activating_ and _deactivating_ project.

**Comment by maryjaf** [comment]
This issue could be assigned to Latifat as a first task

**Comment by divine-comedian** [comment]
@LatifatAbdullahi 

To test this issue you'll need to create a project on Giveth staging

- Create project
- go to my projects page from navbar
- see project card 
- check if new action buttons on action menu on project card work as expected 

For determining the expected behaviour you can confirm with @maryjaf on what happens when a project becomes deactivated/activated and how it should handle being forwarded to the project verification form depending which new button you are testing

**Comment by LatifatAbdullahi** [comment]
Sure! On it

**Comment by kkatusic** [comment]
@LatifatAbdullahi if you need help for first time be free to contact me

**Comment by LatifatAbdullahi** [comment]
Noted, thank you

**Comment by LatifatAbdullahi** [comment]
@divine-comedian 

**Test completed** Test Status: **Passed**

When a project's  verified status is "Not Verified", an option called "Verify project" is seen which leads to the verification page.
![Verify Project](https://github.com/Giveth/giveth-dapps-v2/assets/112261242/f3695b09-9786-4ce7-a59e-e5d6a24e42db)

When a project is Verified, Users are able to deactivate their projects successfully. Also they are able to activate back after deactivation.



With regards to the Acceptance Criteria relating to the Project card Action bar;


-When a project's  verified status is "Not Verified", an option called "Verify project" is seen which leads to the verification page.

-When a project's verified status is 'Incomplete' there is an option called "Resume Verification " which  this leads to verification page.
![ResumeVerification](https://github.com/Giveth/giveth-dapps-v2/assets/112261242/6d282868-0606-4b5c-8083-f974836b6bd3)

 When project's status is Active there is an option to deactivate their project
 
![nm](https://github.com/Giveth/giveth-dapps-v2/assets/112261242/cdfe0cb5-cf71-4ae8-83d2-9644c09bf007)


 When Project's status is Deactivated there is an option to activate their project
 
![last](https://github.com/Giveth/giveth-dapps-v2/assets/112261242/b8471d52-80e0-475a-b101-33900ce2c3e5)


-Users are able to perform all necessary actions as  expected in the  Project card action car. 

![av](https://github.com/Giveth/giveth-dapps-v2/assets/112261242/17b0f74f-b256-418f-b840-aec741e051ea)
![jk](https://github.com/Giveth/giveth-dapps-v2/assets/112261242/f392ecb9-3ddb-4d4c-bb37-c46d150eede8)

**Comment by divine-comedian** [comment]
@LatifatAbdullahi - could you also confirm, when a project is not verified that you also see a Verify Project button on the drop down menu on the project card? 
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/89bd4f44-cca3-45ab-b821-210f3edfaf5d)

**Comment by LatifatAbdullahi** [comment]
Sure!
A non-verified project

![nn](https://github.com/Giveth/giveth-dapps-v2/assets/112261242/c60671fd-d182-417c-9924-91cfbd086118)

**Comment by kkatusic** [comment]
Nice, look @MohammadPCh we passed :)
