### ISSUE TITLE
Donation Improvement 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#42]
- [ ] GIVbackWL warning
- [ ] GIVback  after success donation
- [ ] Custom Token donating

**Comment by mateodaza** [comment]
What do you mean on point 10- watermark text of the search token should be based on design.
I'm a bit confused 
@MoeNick

**Comment by mateodaza** [comment]
Also, 11- I couldn't test eligible token drop-down, pls give me a project that I can test.

Every listed token is eligible. The case it's needed is for copy/pasted addresses

**Comment by MoeNick** [comment]
Testing again today on the final merged version:

- [ ] I can't proceed to donate after I sign my wallet. I stuck in this step:


![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/91273588-2425-4c31-a8ec-1a43fb925577)

- [ ] Hover on Text Box & DropDown Menu is neglected. Hover should be with a shadow and pressed with purple border. you can find the instructions here:
https://www.figma.com/file/d3ciTS36toS9mra0RAPMe2/Giveth-Design-System-v0.1?node-id=209%3A1095

- [ ] Raised Amount is empty.

- [ ] This Token is eligible for GIVbacks. should not be Bold, only Learm More should be Bold. 

- [ ] Can't donate has some design problems, "Can" is lighter the the rest of sentence, pls check it again with figma design. 

- [ ]  How we can differ a giving block with not giving block projects? 

- [ ] Watermark text is this text below, I can see it in search token. BUT I think I only can see this on Giving Block projects: 
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/a6297b7f-fda9-4f08-ab7e-376097c995b7)

for the usual projects I can see this, which is like the provided design :
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/330ea244-0fd7-4f53-a41c-0977b29bf1ea)

- [ ] No result for token should be like this: 
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/aac094aa-7fb2-4174-8409-8e00ff1bc0e4)

**Comment by mateodaza** [comment]
[] Watermark text is this text below, I can see it in search token. BUT I think I only can see this on Giving Block projects:

For this, Giving Block Projects can't receive donations other than the tokens listed

**Comment by MoeNick** [comment]
QAing today, on https://giveth-dapps-v2.vercel.app/donate/giveth-2021:-retreat-to-the-future

- [ ] Im still stuck in this step and cant proceed. 
https://giveth-dapps-v2.vercel.app/donate/giveth-2021:-retreat-to-the-future


- [ ]  I think I found the problem: I think there is a picture background overlay the links and text: 
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/a4c9780f-a1cc-4ab1-a996-c133307e4e10)

Home / Projects / About Us are not clickable and "can't donate " is in different color.

**Comment by MoeNick** [comment]
@mateodaza Im still can't approve it due to problems I can see above, shall we move it back?

**Comment by mateodaza** [comment]
@MoeNick will get this done asap

**Comment by MoeNick** [comment]
First I have to thank you, good job man +1

Some tint design notes: 
- [ ] Why this is not valid? 
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/39100a11-ae6b-4c1a-8fd0-8d24cbcc0d39)

- [ ] Prevent user to enter more than 1 zero before the dot. 
 ![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/9bbb19c7-66aa-4824-861e-3d9eefb2984e)


- [ ] Regarding to the design, please use this color background: #FFF7E0; for background and #C6920C; for text,  for the toast of non-eligible tokens. It's not well readable right now. 
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/d20bf5be-e8e7-41cd-8286-4ddb1483e691)

- [ ] According to the design, it should be a border next to the drop down menu, this is what I see: ![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/e5163b33-5cb1-4335-886d-737245c82470)
This is I supposed to see: 
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/8a10a48b-3bab-4583-abf4-7375ee65e1e8)

- [ ] For hovering text box, this shadow should be considered: 
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/dcbac956-0ed2-4617-8695-6ddff7231ac1)
But purple border, should apply on the form when user clicks in the ford (Pressed state) 
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/4dbf7ca6-f606-4679-98e5-021cb5ff89e3)

you can easily copy and paste the CSS properties. 

- [ ] It should be a toast msg (blue one) in the modal: "Your donation is being processed, you can close this modal"
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/4e2fc7dc-1b81-4eef-892a-787030db98e3)

- [ ] Is there any reason we forget about having approval on spending tokens?
