### ISSUE TITLE
Our GIvbacks checks are not considering if an address is a multisig on the wrong chain to receive GIVbacks

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4200]
Some thoughts:
- we could consider a check in the UI where if a user is a mulsitig, we ask them to input a "GIVbacks address" that is part of the giveth user profile
- we should/could set up some kind of "claim window" for GIVbacks... if they don't claim after 2years, we pull them back to the DAO

But we need to discuss the best solution for how to deal w/ this

@WhyldWanderer @divine-comedian

**Comment by divine-comedian** [comment]
I think the claim window is a separate issue, and we shouldn't consider it part of this issue, unless there is something I'm not aware of. 

I think the user profile idea is good, when they log in successfully we show a modal where they need to input an address to receive their GIVbacks on Gnosis Chain/Optimism and whatever other chains we add in the future.

**Comment by laurenluz** [comment]
I think we need some design here @mosaeedi or @Tosinolawale - do either of you have time to take it up? We basically want:

1. Add chain/network to donation successpage givbacks message. We can have it say
You're eligible for GIVbacks!
Your GIV rewards will be claimable on < network > through our GIVbacks page (link) after the round ends.
Learn more
![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/e72aa092-867a-4e55-b946-ddf08895be6c)

2. Something on the donation flow, like a modal or popup, that doesn't impede their donation... maybe it comes after they donate... that is shown to the user who is donating with a multisig that is NOT on Gnosis or Optimism, that says something like:
Attention
In order to receive GIVbacks for your donation, you'll need to set a GIVbacks recipient address on OP Mainnet.
Button: Manage GIVbacks Address
![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/ae00d26e-5232-4893-a436-479683ba6be9)

3. Something in the user profile where the user can set a GIVbacks recipient address on OP Mainnet (that, if the user donated with a EOA wallet, or a mutlisig on Optimism, is auto-filled by default with their Optimism address.

@divine-comedian - does this sound good to you?
I think we don't need to ask for gnosis GIVbacks addresses because they'll only get GIVbacks on gnosis for donations on gnosis... we should only make them fill this in if they use a multisig that is on a chain that is not used for GIVbacks distribution.

**Comment by mosaeedi** [comment]
**1. Updated the copy on the success page**

<img width="676" alt="Screenshot 2024-06-03 at 4 51 08 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/94296df1-6a90-45ee-ad7f-308459153653">


**2. Added a modal for multi-sig users**

<img width="698" alt="Screenshot 2024-06-03 at 4 51 57 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/b6e5181d-9bfc-4ade-b888-599a6d72dd60">


**3. On user profile**
Is it something we will show to all users regarding their wallets? or just to the multi-sig users! also is it possible to change that in the future? or will it just happen once!?

**Comment by laurenluz** [comment]
Hey @mosaeedi - this is looking good! A couple of notes:

2. For the modal can we adjust the copy... title being "Don't miss out on GIVbacks"

3. On user profile, I think we should just allow multi-sig users add a GIVbacks address... if they are not donating from a gnosis or optimism multisig... (to not make things more complicated). I think we should make it possible for users to change this in the future, so perhaps it can have an "edit" thing.
