### ISSUE TITLE
Retroactive Sponsor Donations & GIVbacks

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#4203]
@mohammadranjbarz @divine-comedian 

Here is the list of donation data that needs to be added to the UI.
We also need to distribute GIV to these addresses through the GIVstream - this should come from the OP GIVbacks Token Distro.

**GloDollar**
Tx link: https://arbiscan.io/tx/0xd9bf19eb3c09baf79159e772ba0fd824b812d5953a7e2d026a2d65966501c7b3
OP Wallet to receive GIVbacks: 0x1bbfc95b826693bf17665f36a66ac9c389b7e581
Amount to be streamed on OP: 71,713.1474 GIV
User already has a profile on Giveth

**Aragon Project**
Tx link: https://etherscan.io/tx/0x4b0b0e7b8137ac68e42ebfa170607e6b59015d3583e7290af081ea974cfd6b10
OP Wallet to receive GIVbacks: 0xD6B270DFEE268B452c86251Fd7e12Db8dE9200FB
Tx link: https://etherscan.io/tx/0x12135b286cbcb71c1c4155ee650613e1840d54619d4d06ae7be77f17bdc4683b
OP Wallet to receive GIVbacks: 0xD6B270DFEE268B452c86251Fd7e12Db8dE9200FB
Total amount to be streamed on OP: 286,852.5896 GIV
User does not already have a Giveth profile. We should name it "Aragon Project"

**Public Nouns**
Tx link: https://etherscan.io/tx/0x30954cb441cb7b2184e6cd1afc6acbd1318f86a68b669f6bfb2786dd459e2d6c
OP Wallet to receive GIVbacks: 0xda04c025F4d8Ac555Fdb3497B197D28FCEcf4d41
Tx link: https://etherscan.io/tx/0x10975407db91205cda1e9f9bb288488d215d6d94dfa12b192ffa0cb78893df11
OP Wallet to receive GIVbacks: 0xda04c025F4d8Ac555Fdb3497B197D28FCEcf4d41
Amount to be streamed on OP: 995,091.6335 GIV
User does not already have a Giveth profile. We should name it "Public Nouns"

**Jordi Baylina**
Tx link: https://etherscan.io/tx/0xa6e68136fdb972597cb795d73059aa5a7eedfe5a84b0af3b0091121231e1529d
OP Wallet to receive GIVbacks: 0x1DBA1131000664b884A1Ba238464159892252D3a
Amount to be streamed on OP: 47,808.7649 GIV
User already has a profile on Giveth

Forum Post for reference: https://forum.giveth.io/t/rewarding-the-quadratic-force-with-givbacks/1442

Let me know if you need anything else from me.

**Comment by divine-comedian** [comment]
@WhyldWanderer - why do we care about what their giveth profile name is?

**Comment by laurenluz** [comment]
@mohammadranjbarz would love if you could take a look at this as well when you are back tomorrow :)

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz would love if you could take a look at this as well when you are back tomorrow :)

sure, I would add these donations to https://github.com/Giveth/impact-graph/pull/1588

**Comment by mohammadranjbarz** [comment]
@WhyldWanderer Lots of these donations are too old so we would not have them in the givback calculation, is it ok?
Do you want to distribute givbacks for them manually?

**Comment by WhyldWanderer** [comment]
Exactly @mohammadranjbarz... we will distribute the GIVbacks for these donations manually since the rounds have already passed and been finalized. We just need the donations to show up in the database and on the UI. 

@divine-comedian What will be the process for manually distributing these GIVbacks. Will Mohammad need to have any considerations when adding the donations that may affect the distribution of GIVbacks for these projects?

**Comment by divine-comedian** [comment]
> Exactly @mohammadranjbarz... we will distribute the GIVbacks for these donations manually since the rounds have already passed and been finalized. We just need the donations to show up in the database and on the UI.
> 
> @divine-comedian What will be the process for manually distributing these GIVbacks. Will Mohammad need to have any considerations when adding the donations that may affect the distribution of GIVbacks for these projects?

We just call it manually from the nrGIV Agent to distribute the GIVbacks - we'll need the addresses and exact amount of GIV that should be allocated.

**Comment by mohammadranjbarz** [comment]
@WhyldWanderer @maryjaf You can test this issue by checking https://giveth.io/project/giveth-matching-pool-0 or checking admin panel and filter donations to find these donations

**Comment by WhyldWanderer** [comment]
@mohammadranjbarz

I have checked the project page as you suggested and I dont see these donations showing there :/

**Comment by WhyldWanderer** [comment]
@divine-comedian - I think we can move forward with the distribution even if the donations arent yet showing in the UI.

> We just call it manually from the nrGIV Agent to distribute the GIVbacks - we'll need the addresses and exact amount of GIV that should be allocated.

The wallet addresses and exact amount of GIV are listed above with each transaction.. What are the next steps to "call it manually"? Can you help with this?

**Comment by divine-comedian** [comment]
Okay, I see. 

I need to get permissions from the giv.eth multisig to send out the GIVbacks rewards from the rGIV agent on Optimism. 

This multisig transaction will need to pass then I can make the vote on the rGIV to send them out. 
https://app.onchainden.com/safes/oeth:0x4D9339dd97db55e3B9bCBE65dE39fF9c04d1C2cd/transactions/0x2991f41f5dc97980a0a8175c0ff3a0c051b670a6c98280309b68cd1f2c1bb23b?nid=351456

**Comment by WhyldWanderer** [comment]
These GIVbacks have now been distributed. Thanks to everyone who helped on this!

@mohammadranjbarz - We can go ahead with making sure the donations are showing accurately in the UI now that the tokens have been sent.

**Comment by laurenluz** [comment]
@koday1 @SnakeGH - we should reach out to these spnosors and let them know their GIV was sent and tell them to stake & lock on Optimism... locking the tokens earns them a yield and means they can boost & influence projects (so let's tell the sponsors that!)

**Comment by mohammadranjbarz** [comment]
> These GIVbacks have now been distributed. https://optimistic.etherscan.io/tx/0xd5326ef36932d37f83ba6c47be59f8fa396e5f7b1fcd30a4bf21b162f569e5fd Thanks to everyone who helped on this!
> 
> @mohammadranjbarz - We can go ahead with making sure the donations are showing accurately in the UI now that the tokens have been sent.

Thanks @WhyldWanderer  for letting me know, I updated the `networkId` of those donations to the correct one

**Comment by WhyldWanderer** [comment]
Youre the best @mohammadranjbarz! 

I think this issue can now be closed
