### ISSUE TITLE
"Last Update" on project card is not correct

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#4204]
This project made an update today but it still says "Last update 22 days ago" on the project card.
https://giveth.io/project/digital-street-musician-doing-free-live-concerts

![image](https://github.com/Giveth/giveth-dapps-v2/assets/74267818/1254a83e-f9c5-4a47-8636-3af752e7a326)

![image](https://github.com/Giveth/giveth-dapps-v2/assets/74267818/60baf5f5-7eaf-41cf-960f-afac50a141d2)

**Comment by divine-comedian** [comment]
@CarlosQ96 

I checked several projects after Ashley's report and it appears this number is not updating at all for any project.. who knows since when.

**Comment by divine-comedian** [comment]
@CarlosQ96  Can you please check and provide an update on this issue.

**Comment by RamRamez** [comment]
@divine-comedian You need last update field on project card to be updated after only on adding a project update? So what about editing description and title?

**Comment by WhyldWanderer** [comment]
@RamRamez - jumping in to answer the question. ..

It should only show the time that the last update was added to the project.

You can ignore changes to project description/title

**Comment by RamRamez** [comment]
Thanks @WhyldWanderer 
I can take this issue.

**Comment by RamRamez** [comment]
@maryjaf @LatifatAbdullahi Please test and verify

**Comment by maryjaf** [comment]
I've tested and now the "Last Updated" on project card and "Latest Updates" in Homepage are shown correctly.
