### ISSUE TITLE
PassPort banner is hidden under header

### ISSUE THREAD

**Issue by RamRamez** [Giveth/giveth-dapps-v2#4212]
When there's an active QF round, we should show passport banner on top

<img width="1159" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/73441857/6b1feca7-f765-4a79-bb08-616ec2995114">

**Comment by RamRamez** [comment]
@maryjaf please test and verify

**Comment by maryjaf** [comment]
It has been resolved.

<img width="1482" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1lXQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--34e41d79aed8e55449f8695898bfdc34d2174832/image.png" alt="image.png" />
