### ISSUE TITLE
Add Github as social media badge option for projects

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4216]
We should add an additional option for users to provide social media info - for the Github platform. 

We should: 

- [ ] Have a field in the project creation/edit flow to add a github link to the project's github organization or repository
- [ ] show a badge on the public/private view of the project details page. 
- [ ] the badge should be the color black and use the github icon

**Comment by Tosinolawale** [comment]
![Create Project UI](https://github.com/Giveth/giveth-dapps-v2/assets/35389241/03db89e7-c8ac-4c6b-98ec-253c300f0f9f)
https://www.figma.com/design/vMiyVd1Ly5LjgSyZrChVV8/Giveth-users?node-id=2676-85227&t=X9VcE8okT11XMAcy-1

![Project Single - About](https://github.com/Giveth/giveth-dapps-v2/assets/35389241/c3aef84b-f4cd-446b-bc91-109b1b3176b7)
https://www.figma.com/design/vMiyVd1Ly5LjgSyZrChVV8/Giveth-users?node-id=1907-23890&t=X9VcE8okT11XMAcy-1
@divine-comedian

**Comment by Reshzera** [comment]
@LatifatAbdullahi @maryjaf

**Comment by LatifatAbdullahi** [comment]
@Reshzera  @divine-comedian 

Test update:


Have a field in the project creation flow to add a github link to the project's github organization or repository - Pass 
Have a field edit flow to add a github link to the project's github organization or repository - Pass
Show a badge on the public view of the project details page -  Pass 
Show a badge on the Private view of the project details page - Pass
The badge should be the color black and use the github icon - Pass


![11](https://github.com/user-attachments/assets/42ee7a27-ab12-4984-bbce-86fa3620db07)


![122](https://github.com/user-attachments/assets/76e6eb3b-f9a2-4667-a787-158e5c6c0074)
