### ISSUE TITLE
optimize qfRounds query - FE and BE

### ISSUE THREAD

**Issue by RamRamez** [Giveth/giveth-dapps-v2#4217]
for optimizing qfRounds query, FE needs work because we have used qfRounds query a lot, and we fetch all qf Rounds but we only need the current active qfRound, not all them, so BE need to fetch only current active qf Round from DB, and FE also need to read from Redux state, because lots of pages are querying qfRounds, but that should be fetched only once in Redux, then all the components can read from Redux

For BE side we need to add a cache for that query.

**Comment by RamRamez** [comment]
@maryjaf please test and verify

- [ ] projects and projects categories page (/projects and /projects/[slug])
- [ ] /qf-archive/[slug] page
- [ ] /qf/[slug] page
- [ ] current QF round info (such as QF round stats in /qf and /qf-archive page and also QF top and middle banners info in those pages)
- [ ] passport banner and passport page

**Comment by maryjaf** [comment]
> [ ] /qf-archive/[slug] page

-I got 500 error in these pages
 https://staging.giveth.io/qf-archive/qf-stats
 https://staging.giveth.io/qf-archive/banner-e-baba

**Comment by RamRamez** [comment]
> > [ ] /qf-archive/[slug] page
> 
> -I got 500 error in these pages https://staging.giveth.io/qf-archive/qf-stats https://staging.giveth.io/qf-archive/banner-e-baba

Thanks
I fixed it

**Comment by maryjaf** [comment]
> -I got 500 error in these pages
> https://staging.giveth.io/qf-archive/qf-stats
> https://staging.giveth.io/qf-archive/banner-e-baba

It has been resolved.
