### ISSUE TITLE
Webpack Bundle Analyzer Report April 7th 2021: Improve imports on api/airdrop.js

### ISSUE THREAD

**Issue by mateodaza** [Giveth/giveth-dapps-v2#422]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/18689480/161657456-9894d607-86fd-4670-b6d6-a6aa02990fed.png">

api/airdrop.js is loading >4Mb on load, let's solve this!

**Comment by MoeNick** [comment]
Can you elaborate on what's needed from the design team? any reason you put Design label? @mateodaza

**Comment by mateodaza** [comment]
> Can you elaborate on what's needed from the design team? any reason you put Design label? @mateodaza

That was a misclick, my bad
