### ISSUE TITLE
FE changes to show recurring donations for QF

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4222]
Some FE changes should be made that show this recurring donation be in a QF round 
like in donate page and donation success page 

<img width="1402" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1A3QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6bf773edf251763f4b9c57fc36e915e32a253de0/image.png" alt="image.png" />

<img width="1326" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd243QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f4c3d1dbf975a42651398a100c1bc0f24cf0413b/image.png" alt="image.png" />

_Originally posted by @maryjaf in https://github.com/Giveth/giveth-dapps-v2/issues/3284#issuecomment-2122543938_
----

On the donate page for recurring donations - if the project is in a QF round and optimism is an eligible network for the current QF round   we should show the QF related project card on the side instead of the regular card.

On the success page we should show the section related to QF matching on this view as well.

**Comment by divine-comedian** [comment]
Just checked on production as well, the values appear to be the same for both variables and update very quickly after making a donation.. 

last question now @CarlosQ96 

In the FE should we use only `sumDonationValueUsd` or `totalDonation` or keep everything as is?

**Comment by maryjaf** [comment]
- [ ] It would be good if we consider this scenario 

- The project hasn't any one time donation in a round 
- The project has a recurring donation and it be counted in estimated matching 
-The project card is shown like below pic, amount raised in this round is 0 , estimated matching is more than zero (because of recurring donation in the round)

![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/563cb129-10b3-406c-8e70-3d167a6dbf54)

cc: @divine-comedian @MohammadPCh

**Comment by divine-comedian** [comment]
nice catch MJ! So the value of the recurring donation is not being considered in the "amount raised this round" field on the project card when the project is inside of an active QF round. 

We should count the value of eligible recurring donations made inside the QF round to the given project and include it in this number. 

@MohammadPCh I can make a new issue if you prefer or track it here

**Comment by MohammadPCh** [comment]
@divine-comedian Yes, please create a new issue :D

**Comment by divine-comedian** [comment]
@maryjaf  I created a new issue for the scenario you reported - can you confirm if the original parts of this issue are completed?

**Comment by maryjaf** [comment]
> like in donate page and donation success page

**Donate page:**

- [ ] There is difference between one time and recurring tab for  project in a round, please take a look @MohammadPCh 

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/63711a1c-2a86-4ab0-8c54-4b9f9f042d0f

- [ ] Estimated matching isn't shown in recurring donation tab

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/011ba277-f7ef-4019-81a5-676a67e8924b




Donation success page:

There is no problem in donation success page
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/db97b63d-fb09-444b-a82b-b41e24fb1217)

**Comment by divine-comedian** [comment]
I don't think we defined how to get the estimated matching for a recurring donation... 

My guess to do the estimated matching we would need to know 

1. How many seconds are left in the QF round
2. How much the user is proposing to donate per second 

Then we would need to take the seconds left in QF round, multiplied by amount to donate per second, this would become the value we use for the estimated matching.

**Comment by maryjaf** [comment]
> I don't think we defined how to get the estimated matching for a recurring donation...
> 
> My guess to do the estimated matching we would need to know
> 
> 1. How many seconds are left in the QF round
> 2. How much the user is proposing to donate per second
> 
> Then we would need to take the seconds left in QF round, multiplied by amount to donate per second, this would become the value we use for the estimated matching

I don't get it correctly , so this behavior is expected or it should be changed 

> * [ ]  1- There is difference between one time and recurring tab for  project in a round, please take a look @MohammadPCh
 > * [ ] 2- Estimated matching isn't shown in recurring donation tab

**Comment by divine-comedian** [comment]
Oh, the 1st issue looks to be a bigger issue, not related to this issue - I would consider it out of scope here and we can follow it up elsewhere and see how Lauren wants to handle it. 

The second issue however - looks like the QF project card hasn't been implemented for recurring donations yet.

**Comment by MohammadPCh** [comment]
@divine-comedian can we close this issue? or wrap up the remaining tasks?

**Comment by divine-comedian** [comment]
> @divine-comedian can we close this issue? or wrap up the remaining tasks?

Did you resolve the second issue MJ reported? The QF version of the project card should show up when user selects to make a recurring donation from donate page

**Comment by MohammadPCh** [comment]
@lovelgeorge99, could you take care of this and resolve this old issue? Thanks!

**Comment by lovelgeorge99** [comment]
For this one i am waiting for a PR in imapct graph to get reviewd which gets the recurring dontaions from a data range.

> @lovelgeorge99, could you take care of this and resolve this old issue? Thanks!

**Comment by divine-comedian** [comment]
@lovelgeorge99 what is the update on this issue?

**Comment by lovelgeorge99** [comment]
@divine-comedian this issuse was resolved here
https://github.com/Giveth/giveth-dapps-v2/issues/3284

**Comment by divine-comedian** [comment]
Looks like MJs reported issue is done - moving this issue over to done.

![image](https://github.com/user-attachments/assets/f7bd011b-e766-46e7-8da2-5f6ccd970faa)
