### ISSUE TITLE
Support Giveth Subgraphs as ENV Variables

### ISSUE THREAD

**Issue by mhmdksh** [Giveth/giveth-dapps-v2#4223]
We need to have the subgraphs used in the Frontend as ENV Variables.

This is a requirement to move to subgraph studios, since we'll be accessing the subgraphs with API Keys in the URL

The subgraphs are currently hardcoded here: https://github.com/Giveth/giveth-dapps-v2/tree/develop/src/config

Also we need to be able to change them quickly to be able to test new subgraphs

**Comment by kkatusic** [comment]
@mhmdksh there aren't one subgraph address inside configuration file, we need to remove one or two specific or all? thx

**Comment by mhmdksh** [comment]
Hey @kkatusic we mainly need the below subgraphs to be identified in the ENV Variables:
```
line: 140,141
		subgraphAddress:
			'https://api.studio.thegraph.com/query/40764/giveconomy-staging-goerli/1.5.0?source=giveth',
```
```
Line: 196,197
		subgraphAddress:
			'https://api.studio.thegraph.com/query/40764/giveconomy-staging-gnosischain/1.5.1?source=giveth',
```
```
Line: 358, 359
		subgraphAddress:
			'https://api.thegraph.com/subgraphs/name/giveth/giveth-economy-optim-sepolia?source=giveth',
```

**Comment by RamRamez** [comment]
@mhmdksh four new env var are added:

NEXT_PUBLIC_SUBGRAPH_MAINNET
NEXT_PUBLIC_SUBGRAPH_GNOSIS
NEXT_PUBLIC_SUBGRAPH_OPTIMISM
NEXT_PUBLIC_SUBGRAPH_CLASSIC

**Comment by kkatusic** [comment]
> Hey @kkatusic we mainly need the below subgraphs to be identified in the ENV Variables:
> 
> ```
> line: 140,141
> 		subgraphAddress:
> 			'https://api.studio.thegraph.com/query/40764/giveconomy-staging-goerli/1.5.0?source=giveth',
> ```
> 
> ```
> Line: 196,197
> 		subgraphAddress:
> 			'https://api.studio.thegraph.com/query/40764/giveconomy-staging-gnosischain/1.5.1?source=giveth',
> ```
> 
> ```
> Line: 358, 359
> 		subgraphAddress:
> 			'https://api.thegraph.com/subgraphs/name/giveth/giveth-economy-optim-sepolia?source=giveth',
> ```

Thx @mhmdksh , @RamRamez made pull request

**Comment by RamRamez** [comment]
@mhmdksh I added these 

> @mhmdksh four new env var are added:
> 
> NEXT_PUBLIC_SUBGRAPH_MAINNET NEXT_PUBLIC_SUBGRAPH_GNOSIS NEXT_PUBLIC_SUBGRAPH_OPTIMISM NEXT_PUBLIC_SUBGRAPH_CLASSIC

I added these env var to Vercel for both prod and staging

**Comment by maryjaf** [comment]
How can I test this issue? @RamRamez

**Comment by RamRamez** [comment]
> How can I test this issue? @RamRamez

On staging you can check GIV token balance and staked amount and locked amount balance

**Comment by maryjaf** [comment]
- [ ] I see some errors in stake flow in console /network tab but it isn't a blocker for completing flow and I could stake but it takes more time than before, could you please take a look? @RamRamez 

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/b249523b-afb8-407a-ac6b-88fcde5661f3

![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/7f1cdb03-f59a-43f1-b64f-3afd9711e689)
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/15dec5d9-3d28-44cf-8f38-498aed56ff14)

**Comment by maryjaf** [comment]
- [ ] Harvest  and lock flow

![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/320560a5-9ed4-4fc8-9099-db6e68e41682)

**Comment by mohammadranjbarz** [comment]
@maryjaf  I think these errors are related to the rpc , and not related to subgraph.
@RamRamez Am I right?

**Comment by mohammadranjbarz** [comment]
@mhmdksh  Has balance-aggregator subgraphs has been changed as well?

**Comment by mohammadranjbarz** [comment]
> * [ ]  I got some errors in stake/unstake flow in console /network tab
>   but I completed stake flow for one time, could you please take a look? @RamRamez
> 
>  Screen.Recording.2024-06-09.at.4.27.15.PM.mov 
> ![image](https://private-user-images.githubusercontent.com/111529185/337975466-7f1cdb03-f59a-43f1-b64f-3afd9711e689.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMTI0MTksIm5iZiI6MTcxODAxMjExOSwicGF0aCI6Ii8xMTE1MjkxODUvMzM3OTc1NDY2LTdmMWNkYjAzLWY1OWEtNDNmMS1iNjRmLTNhZmQ5NzExZTY4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMFQwOTM1MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMTY3YmJkOTg3ZmVhNjAxOThlOTZmZjNlNDc4NmQzNjEzOTM0MDk2OTBkMWMxYzJkZjAzMmU5NmQ4N2FhM2FmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aIv2YXwjSF1_XzmG-nN68buJ7RahxWQtbSlDEMBCcQw) ![image](https://private-user-images.githubusercontent.com/111529185/337975522-15dec5d9-3d28-44cf-8f38-498aed56ff14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMTI0MTksIm5iZiI6MTcxODAxMjExOSwicGF0aCI6Ii8xMTE1MjkxODUvMzM3OTc1NTIyLTE1ZGVjNWQ5LTNkMjgtNDRjZi04ZjM4LTQ5OGFlZDU2ZmYxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMFQwOTM1MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZWMwMmIwOTc5NDJjMDUzMjYyZTU1YzMyYmYwMzM0MjQ0NzI5Y2UxYzNmNTg2ZTg5Nzg5NGY4OTdlZjFjNTI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HJ6ik-RdlmNRr_cLDXuWRy4ZMum5MTI7yqcUgXY2fQA)

@RamRamez 
Could you take a look to see what's the reason of `takingPool.ts:268 error on fetching balancer apr: TypeError: Cannot read properties of undefined (reading 'map')` error?

**Comment by divine-comedian** [comment]
@mohammadranjbarz @RamRamez - before I close this one can we confirm Mohammad's last comments are resolved?

**Comment by RamRamez** [comment]
@divine-comedian This is related to Gnosis APR that's is not shown on staging but it's ok on production. This is not a new bug, we had this problem before, @aminlatifi Could you please take a look?

**Comment by aminlatifi** [comment]
One of the chains our staging giveconomy is deployed on is Goerli which is deprecated and is not supported anymore.  I think we can remove supporting.

**Comment by divine-comedian** [comment]
> One of the chains our staging giveconomy is deployed on is Goerli which is deprecated and is not supported anymore. I think we can remove supporting.

Yep! We'll have to remove it, future task will be adding in Sepolia to replace Goerli
