### ISSUE TITLE
Request to add #ID

### ISSUE THREAD

**Issue by mosaeedi** [Giveth/giveth-dapps-v2#4235]
Just came across this issue #1731 created by @ahmadabugosh 

I also need some more IDs for the same purpose! I want to gather better info on Posthog, but in some cases I can't get it right on Posthog.

So here I'll list the IDs I need and the elements they should add to.

<img width="538" alt="Screenshot 2024-06-04 at 12 54 52 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/d59c943a-034f-47c3-b587-3c5b349be896">

### 1 | On Homepage

**Explore projects** button -> ID: Explore_Hero

---

<img width="348" alt="Screenshot 2024-06-04 at 12 56 11 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/0178d929-c7b9-4156-ae97-63e2b8cdecf4">

### 2 | On Homepage

**Explore** button -> ID: Explore_Row

---

<img width="432" alt="Screenshot 2024-06-04 at 12 57 53 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/98f59bd8-3f53-4f01-8a97-a73846ee5144">

### 3 | On Projects card on list of projects page

**Donate** button -> ID: Donate_Card

---

<img width="381" alt="Screenshot 2024-06-04 at 12 59 19 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/dd7e8eee-21d6-427d-b801-1e074a82a459">

### 4 | On View project detail page

**Donate** button -> ID: Donate_Project

---

<img width="660" alt="Screenshot 2024-06-04 at 1 00 20 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/13708322/521fbd91-f3a2-4850-b9d3-bf452c498c77">

### 5 | On Donate screen

**Donate** button -> ID: Donate_Final

**Comment by divine-comedian** [comment]
@kkatusic  - I think you're familiar with this one, just adding some more IDs!

**Comment by kkatusic** [comment]
@mosaeedi, cc @divine-comedian, I added all requested ids to elements that you marked, but we need to wait to someone approve changes on giv design system ([link to pull request](https://github.com/Giveth/ui-design-system/pull/103)) because button was missing id property.

I'll let you know when the changes are made ;)
