### ISSUE TITLE
Provide "Receiving Funds" context in the project creation flow

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#4236]
As a donor, I want to know that adding a wallet address for all chains possible will lead to more donations.

Breaking this down:

I have been noticing that most of the new projects created on Giveth lately usually only have added an ETH address. I think that the text in the project creation flow was changed and is now lacking some context.

![image](https://github.com/Giveth/giveth-dapps-v2/assets/74267818/351e9a78-7bf3-40c0-ae8c-fbafbb0e4d14)

We should add some text here that provides an understanding that being able to accept funds on all chains possible will yield more donations.

Maybe like "Donors tend to choose the network that is most convenient for them. By providing a wallet address for all chains that Giveth supports, your project is more likely to receive funding from donors."

Or "The more chains your project can accept funds on, the more likely it is to receive donations."

Something like that...

**Comment by WhyldWanderer** [comment]
Which Tech Lead should this one be assigned to @jainkrati?

Maybe @divine-comedian could take a look? I think its an easy text implementation...

**Comment by divine-comedian** [comment]
I can work on this today, thanks for bringing it up!

**Comment by divine-comedian** [comment]
Should be live on the site in about 10 mins! If it looks good @WhyldWanderer you can close this issue.
