### ISSUE TITLE
Update Quadratic Force PDF to new version

### ISSUE THREAD

**Issue by koday1** [Giveth/giveth-dapps-v2#4241]
We just made a minor update to the quadratic force PDF - changing the 2nd tier from $8k to $10k. We need to update the version of the PDF that lives at https://giveth.io/quadraticforce

Here's the new version: [Giveth_QF_2024.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTAyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d98768c1d3cdeadf5817ac131aa39e93abe63850/Giveth_QF_2024.pdf)

Figma: https://www.figma.com/design/W9Ace1RyCdykWM72fsSa3t/Giveth-Marketing-2024?node-id=6891-4523&t=l1pu8FKiPf9skX8t-4

**Comment by koday1** [comment]
@Meriem-BM Are you able to make this edit today? Just updating the quadratic force PDF that lives at https://giveth.io/quadraticforce

**Comment by Meriem-BM** [comment]
Sure, I'll update it

**Comment by Meriem-BM** [comment]
Hey @koday1 the updated pdf is live, sorry for the delay as we had staging issue that prevented us from deploying.

**Comment by koday1** [comment]
Thanks @Meriem-BM! I see the updated one one the site :)
