### ISSUE TITLE
Add Glo Dollar to partnerships page

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4246]
Glo dollar requested to be added to here:

https://giveth.io/partnerships

With this logo:
![telegram-cloud-photo-size-4-5978538826596991394-y](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/8e21a94c-4c25-450f-aa0e-696acf107fd5)

Name: Glo Dollar
Subtext: The stablecoin that funds public goods

@MohammadPCh can you pass to the appropriate person?

cc @divine-comedian

**Comment by divine-comedian** [comment]
@kkatusic I think you can handle this one.
