### ISSUE TITLE
zkEVM | Projects View | Add filter: AcceptFunds on zkEVM 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#4254]

**Comment by maryjaf** [comment]
- [ ] The filter related to zkevm hasn't been added 
<img width="535" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVY4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d719e41f98262d973193fff1b80164fea366cb1c/image.png" alt="image.png" />

**Comment by mohammadranjbarz** [comment]
> * [x]  The filter related to zkevm hasn't been added
> 
> <img alt="image.png" width="535" src="https://camo.githubusercontent.com/9e2af811778bb4061881840a2a35f295a2ae25795d08234ba07e6cf76d539ff4/68747470733a2f2f6170692e7a656e6875622e636f6d2f617474616368656446696c65732f65794a66636d467062484d694f6e73696257567a6332466e5a534936496b4a426148424265565934516c453950534973496d563463434936626e56736243776963485679496a6f69596d7876596c39705a434a3966513d3d2d2d643731396534316639383236326439373331393366666631623830313634666561333636636231632f696d6167652e706e67">

<img width="505" alt="Screenshot 1403-04-03 at 10 05 51 in the morning" src="https://github.com/Giveth/giveth-dapps-v2/assets/9850545/d4a72dfc-a577-47c3-9dae-7116bde040b6">

Now we have it.

**Comment by maryjaf** [comment]
> * [ ]  The filter related to zkevm hasn't been added

This problem has been fixed.
