### ISSUE TITLE
zkEVM | Sign-in and Switch network

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#4255]

**Comment by maryjaf** [comment]
- [ ] in this box the zkEvm shouldn't be active 

<img width="1105" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelY4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--68f9f28a7751b5b75769606459072d502f3085ca/image.png" alt="image.png" />

**Comment by mohammadranjbarz** [comment]
> * [x]  in this box the zkEvm shouldn't be active
> 
> <img alt="image.png" width="1105" src="https://camo.githubusercontent.com/0cfad8fc0daba79c668004ff20dd8ddacc753d78e77a71fb79c52b04e27281ca/68747470733a2f2f6170692e7a656e6875622e636f6d2f617474616368656446696c65732f65794a66636d467062484d694f6e73696257567a6332466e5a534936496b4a4261484242656c5934516c453950534973496d563463434936626e56736243776963485679496a6f69596d7876596c39705a434a3966513d3d2d2d363866396632386137373531623562373537363936303634353930373264353032663330383563612f696d6167652e706e67">

<img width="740" alt="Screenshot 1403-04-03 at 10 07 09 in the morning" src="https://github.com/Giveth/giveth-dapps-v2/assets/9850545/8044ac75-3c43-407b-bf96-6afb63cf648b">

Done.
