### ISSUE TITLE
zkEVM | Verification Flow | Managing funds | Adding relative addresses

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#4258]

**Comment by divine-comedian** [comment]
@MoeNick - does this need an assignee? should it be included in the epic?

**Comment by MoeNick** [comment]
Thanks @divine-comedian 
I think it has not been attached to their main epic and was missed.
Assigned to @mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
@maryjaf  You can test it
