### ISSUE TITLE
zkEVM | My Account | My project | manage recipient address

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#4261]
![image](https://github.com/Giveth/giveth-dapps-v2/assets/80677512/6d9eb7c8-177f-463a-b672-be09d12182ea)

![image](https://github.com/Giveth/giveth-dapps-v2/assets/80677512/0719b29e-a6a9-44af-9e17-b8f92c5e5e5e)

![image](https://github.com/Giveth/giveth-dapps-v2/assets/80677512/cd162b78-c3ce-4d48-9e17-179785fbe2a0)

**Comment by MoeNick** [comment]
Thanks @divine-comedian 
I think it has not been attached to their main epic and was missed.
Assigned to @mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
@maryjaf You can test it
