### ISSUE TITLE
Copy fix on create a project helpful tips for social media section

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4263]
We are missing the Y from "Your"

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/5111917c-1dc4-4c59-8f55-46e696c76787)

@MohammadPCh - assigning to you as the lead for frontend things! feel free to delegate

**Comment by kkatusic** [comment]
Hi @laurenluz , is there only one "Y", if it is than we fixed.
![Screenshot 2024-06-11 at 11 48 36](https://github.com/Giveth/giveth-dapps-v2/assets/1242145/a8246796-50d8-430f-b19f-dc8ee017f310)

**Comment by laurenluz** [comment]
yep :-D thanks guys
