### ISSUE TITLE
Hide Social media section of project page if no social handles are added

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4264]
We have recently added this whole thing where users when creating or editing their project, can add social media handles...

but we have TONS of grandfathered projects that have no social handles that might not even realize that they should add them... so right now there are loads of projects that just have this:

e.g. [pairwise](https://giveth.io/project/pairwise-simplifying-choices-amplifying-voices)
<img width="1336" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/75490971/7f5640d2-fcae-41d2-869e-1704e112eb61">

We should add a modal popup ping for project owners who connect to Giveth, who have no social media handles... that tells them that they should add them - it looks kind of bad/strange otherwise.

@divine-comedian if you're ok with this I can coordinate w/ @mosaeedi ?

**Comment by divine-comedian** [comment]
> We have recently added this whole thing where users when creating or editing their project, can add social media handles...
> 
> but we have TONS of grandfathered projects that have no social handles that might not even realize that they should add them... so right now there are loads of projects that just have this:
> 
> e.g. [pairwise](https://giveth.io/project/pairwise-simplifying-choices-amplifying-voices) <img alt="image" width="1336" src="https://private-user-images.githubusercontent.com/75490971/338341576-7f5640d2-fcae-41d2-869e-1704e112eb61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNTY0ODQsIm5iZiI6MTcxODA1NjE4NCwicGF0aCI6Ii83NTQ5MDk3MS8zMzgzNDE1NzYtN2Y1NjQwZDItZmNhZS00MWQyLTg2OWUtMTcwNGUxMTJlYjYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDIxNDk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlN2QyN2NhYzQ4M2QwZmNiMjI5NWU2Mjk5ZDJhYzE5MmJiMmYzNzY3MTEyNWE3N2NmZmQ4MTQ3YzBmN2JjZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BGMsFnrPp0BK5WOQeQXtguiAr_tS_lgc3cjyjuMomT4">
> 
> We should add a modal popup ping for project owners who connect to Giveth, who have no social media handles... that tells them that they should add them - it looks kind of bad/strange otherwise.
> 
> @divine-comedian if you're ok with this I can coordinate w/ @mosaeedi ?

Thanks Lauren! This is a good idea but I will take on coordinating this issue for the dapp. 

For now I think a quick fix so it doesn't look funny is we can hide this section if there are no social media handles added for the project.

**Comment by kkatusic** [comment]
@divine-comedian is this ok for you, one is project with no social links, pairwise, second has social share:

![Screenshot 2024-06-11 at 13 13 23](https://github.com/Giveth/giveth-dapps-v2/assets/1242145/a0ed6fca-32c7-4748-9a5d-fe9d71c2aafb)

second:

![Screenshot 2024-06-11 at 13 13 42](https://github.com/Giveth/giveth-dapps-v2/assets/1242145/3005a216-a141-4495-a2c3-6092067190fd)

**Comment by divine-comedian** [comment]
@kkatusic looks good!
