### ISSUE TITLE
Why does it say $0 raised in the matching pool card?

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#4272]
![Screenshot 2024-06-12 at 9 24 45 AM](https://github.com/Giveth/giveth-dapps-v2/assets/14945613/bb7336d0-81dc-4850-b3e3-9ac2f1c6cae9)

**Comment by divine-comedian** [comment]
A quick fix from Ramin! looks to be working properly now, thanks for reporting. 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/da91f55b-ecf7-45f7-b863-6c49fd0247ac)
