### ISSUE TITLE
Endaoment project badge

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4279]
We will need to show a badge on the project cards that identifies a given project as being imported from Endaoment 

![image](https://github.com/Giveth/Roadmap/assets/67759413/13417258-d196-45e1-9db3-1e139697f0fa)
![image](https://github.com/Giveth/Roadmap/assets/67759413/63464202-3a8c-443a-b7b3-cd2d84e422cb)

## Design 

Here is the design we can use to create this badge: 
https://www.figma.com/design/d3ciTS36toS9mra0RAPMe2/Giveth-Design-System-v0.1?node-id=5986-53451&t=smU4gXzUQqUtrI4H-1
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/75146257-ba43-48ec-8e3f-3db7ff615173)

**Comment by divine-comedian** [comment]
@mosaeedi - Do you have any updates for this isue?

**Comment by Tosinolawale** [comment]
![Project Card v2(Variants)](https://github.com/Giveth/giveth-dapps-v2/assets/35389241/97bd2cfa-5f19-4f91-a739-5a5e4a477a39)
![Project Card Base](https://github.com/Giveth/giveth-dapps-v2/assets/35389241/7e91a044-8016-406a-9aba-794c9b54c726)

https://www.figma.com/design/d3ciTS36toS9mra0RAPMe2/Giveth-Design-System-v0.1?node-id=5986-53451&t=smU4gXzUQqUtrI4H-1
@divine-comedian

**Comment by mohammadranjbarz** [comment]
@divine-comedian 
Hey I think we need a logo for Endaoment as well like the below one that we have for Giving blocks


![Image](https://github.com/user-attachments/assets/c8bb6f08-816d-487e-8c6c-fb9845e241f7)

**Comment by divine-comedian** [comment]
![endaoment-logo-color@0 5x](https://github.com/user-attachments/assets/0f3aad61-dfba-4bfe-9406-c41b4bd50b56)

**Comment by mohammadranjbarz** [comment]
@maryjaf  @divine-comedian 
You can test it in the preview link

<img width="1402" alt="Screenshot 1403-04-26 at 11 33 35 in the morning" src="https://github.com/user-attachments/assets/1c4cf273-6a7e-4586-8e39-276c2e5da07a">

https://giveth-dapps-v2-git-4280showendaomentprojectsdetail-givethio.vercel.app/



<img width="1171" alt="Screenshot 1403-04-26 at 11 34 32 in the morning" src="https://github.com/user-attachments/assets/059e9746-c88e-4b46-80b3-ff0dde2b6ca8">

https://giveth-dapps-v2-git-4280showendaomentprojectsdetail-givethio.vercel.app/partnerships

**Comment by divine-comedian** [comment]
@mohammadranjbarz - can you change the partnership text to 

> The Philanthropic Institution of the Future. Managing and encouraging charitable giving using emerging technologies.

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz - can you change the partnership text to
> 
> > The Philanthropic Institution of the Future. Managing and encouraging charitable giving using emerging technologies.

Done

**Comment by divine-comedian** [comment]
@LatifatAbdullahi - you can go ahead and test this one.

**Comment by LatifatAbdullahi** [comment]
@divine-comedian @mohammadranjbarz 

Test status: Pass

All Endaoments project have the designated badge on them

![image](https://github.com/user-attachments/assets/e09cb448-6132-430a-9b2d-a49a7e5d86c8)
