### ISSUE TITLE
GIVfarm total rewards are not being calculated properly

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#428]
It seems like it's excluding GIV / HNY on gnosis chain

A user reported it:
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/a35d5e1c-0f05-4bf7-acf4-9fd205832988)

And it's happening for me as well:
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/015970cf-1fc2-4bb2-9b0d-7b938224780f)

@aminlatifi can you have a look?

**Comment by MoeNick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-Devs-61644589b92edf0016f6999c/issues/Giveth/giveth-dapps-v2/428?planning-poker) with ZenHub @aminlatifi @MohammadPCh

**Comment by aminlatifi** [comment]
@MoeNick Made a PR which solves it.

**Comment by laurenluz** [comment]
looking good on staging

![image](https://user-images.githubusercontent.com/75490971/165184271-fd93a092-9944-4052-a589-6bf29996aee4.png)
