### ISSUE TITLE
Show project cards & project details from Endaoment projects

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4280]
As we import Endaoment projects we should be able to show them on the Giveth UI - we should be able to show the following info: 

- [ ] - project title
- [ ] - project description
- [ ] - recipient addresses
- [ ] - donations received
- [ ] - total donation value
- [ ] - total donors
- [ ] - qf estimated matching (when eligible)
- [ ] - qf donations received (when eligible)
- [ ] - have verified badge

## BE related issues
 https://github.com/Giveth/impact-graph/issues/1598
https://github.com/Giveth/impact-graph/issues/1600

**Comment by mohammadranjbarz** [comment]
@divine-comedian  @maryjaf 
You can find Endaoment projects in the NGO category
https://giveth-dapps-v2-git-4280showendaomentprojectsdetail-givethio.vercel.app/projects/ngo

**Comment by maryjaf** [comment]
When I try to edit my project I got this error, could you please take a look @mohammadranjbarz 
https://giveth-dapps-v2-git-4280showendaomentprojectsdetail-givethio.vercel.app/project/care-peru

![image](https://github.com/user-attachments/assets/24891cba-e951-4138-ad01-2ae088ef76dc)

**Comment by maryjaf** [comment]
- [ ] By tapping on [donation tab](https://giveth-dapps-v2-git-4280showendaomentprojectsdetail-givethio.vercel.app/project/care-peru?tab=donations) I got this error:
Application error: a client-side exception has occurred (see the browser console for more information).


![image](https://github.com/user-attachments/assets/6b95f007-25c6-4f54-a68e-56262a43d06d)

**Comment by mohammadranjbarz** [comment]
> * [ ]  When I try to edit my project I got this error, could you please take a look @mohammadranjbarz
> 
> https://giveth-dapps-v2-git-4280showendaomentprojectsdetail-givethio.vercel.app/project/care-peru
> 
> ![image](https://private-user-images.githubusercontent.com/111529185/349050866-24891cba-e951-4138-ad01-2ae088ef76dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMzMwNzksIm5iZiI6MTcyMTEzMjc3OSwicGF0aCI6Ii8xMTE1MjkxODUvMzQ5MDUwODY2LTI0ODkxY2JhLWU5NTEtNDEzOC1hZDAxLTJhZTA4OGVmNzZkYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQxMjI2MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kY2U3N2ViZTQ4MmU0MDNlZDFhNzczYWMyOGNlMGZiNWE1ZTU5ZmRmNTBjZjQ3Nzk3OWRiNzY2ZDBhM2M5ZjBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0DztyBEJK_u9f4sqqjGBqiPVf2zFRpe0CDlOpdck2ZA)

I guess it's related to https://github.com/Giveth/giveth-dapps-v2/issues/4282#issuecomment-2230605592 and should be fixed now, can you check it?

**Comment by maryjaf** [comment]
Thanks  @mohammadranjbarz It has been fixed and now I can edit my project

**Comment by divine-comedian** [comment]
@maryjaf - has this issue passed QA or does it require more testing?

**Comment by maryjaf** [comment]
> * [ ]  - qf estimated matching (when eligible)
> * [ ]  - qf donations received (when eligible)

These items remain and haven't been tested

**Comment by divine-comedian** [comment]
@mohammadranjbarz - might be missing a field for the description summary 

this project has a slash in its name https://staging.giveth.io/project/apc/cza

This is causing a 404 error

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz - might be missing a field for the description summary
> 
> this project has a slash in its name https://staging.giveth.io/project/apc/cza
> 
> This is causing a 404 error - maybe replace a slash or any other special characters that will break the URL with a hyphen

*  Now description summaries have been filled for endaoment projects
<img width="1473" alt="Screenshot 1403-04-28 at 12 34 35 in the afternoon" src="https://github.com/user-attachments/assets/b5ac6832-2893-43ce-bd7a-481989d2a9ff">


* I wrote a migration to replace it with `-` now this link is working https://staging.giveth.io/project/apc-cza

**Comment by divine-comedian** [comment]
@LatifatAbdullahi this one is ready for testing again I believe

**Comment by LatifatAbdullahi** [comment]
@divine-comedian @mohammadranjbarz 

Test Update 

- qf estimated matching (when eligible) - Pass
 - qf donations received (when eligible) - Pass
 - have verified badge - Pass
 
 
 
![pt](https://github.com/user-attachments/assets/755ccc25-662b-4641-8b45-d0b32a88bb96)
