### ISSUE TITLE
Ensure Endaoment projects are NOT eligible for recurring donations 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4281]
Due to the nature of Endaoment projects, we cannot handle sending them recurring donations since they don't have a clear way to be claimed... 

We should prevent users from making recurring donations, using the already established flow.

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/6ff7b0d5-5564-4710-8531-9edbddeabe5b)

**Comment by mohammadranjbarz** [comment]
@maryjaf  @divine-comedian 

You can test it here 
https://giveth-dapps-v2-git-4280showendaomentprojectsdetail-givethio.vercel.app/donate/reach-out-ngo

**Comment by LatifatAbdullahi** [comment]
@mohammadranjbarz 

I want to  believe this is what is expected for the Endaoments projects not being eligible for Recurring donations, the tab being deactivated. 

![image](https://github.com/user-attachments/assets/cfcb6c98-341d-4f5f-baaa-40e26f1a5253)


When I check on this link you attached earlier
https://giveth-dapps-v2-git-4280showendaomentprojectsdetail-givethio.vercel.app/donate/reach-out-ngo

The recurring donations Tab is completely taken out here

![emp](https://github.com/user-attachments/assets/d17e5b23-16dd-4e21-bcd7-3fa223081332)


When I checked the normal stage link,  it shows the expected result when I attempted to donate to an Endaoment projects

![image](https://github.com/user-attachments/assets/87a7668e-bf7c-40c4-8d87-1e02f4249dc8)

**Comment by divine-comedian** [comment]
@LatifatAbdullahi - we should assume that staging is the source of truth so let's use only staging for testing this feature from now on unless @mohammadranjbarz notifies us otherwise
