### ISSUE TITLE
Users can successfully donate to Endaoment Projects

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4282]
Once Endaoment projects have been imported we should be able to donate to them successfully with various conditions: 

- [ ] Endaoment projects can receive donations on ETH mainnet / Base and Optimism (need to verify)
- [ ] Endaoment projects are GIVbacks eligible, corresponding UI elements are shown
- [ ] Users cannot donate to Endaoment projects on ineligible networks
- [ ] correct donation history appears after making successful donations

**Comment by mohammadranjbarz** [comment]
https://giveth-dapps-v2-git-4280showendaomentprojectsdetail-givethio.vercel.app/donate/reach-out-ngo

Endaoment projects just supports `Base mainnet`, `Ethereum mainnet`, `OP mainnet` but as we don't support these networks on the staging I added `OP Sepolia` to these projects as well , so you can test donation on `OP Sepolia` network

**Comment by maryjaf** [comment]
> * correct donation history appears after making successful donations

By tapping on [donation tab](https://giveth-dapps-v2-git-4280showendaomentprojectsdetail-givethio.vercel.app/project/care-peru?tab=donations) I got this error:
Application error: a client-side exception has occurred (see the browser console for more information).
image


![image](https://github.com/user-attachments/assets/e493b8e9-817e-4fba-8541-320fa1c9537a)

**Comment by mohammadranjbarz** [comment]
> > * correct donation history appears after making successful donations
> 
> I could complete donation flow for endowment project but
> 
> * [ ]  By tapping on [donation tab](https://giveth-dapps-v2-git-4280showendaomentprojectsdetail-givethio.vercel.app/project/care-peru?tab=donations) I got this error:
> 
> Application error: a client-side exception has occurred (see the browser console for more information). image
> 
> ![image](https://private-user-images.githubusercontent.com/111529185/349056107-e493b8e9-817e-4fba-8541-320fa1c9537a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMjg3NzYsIm5iZiI6MTcyMTEyODQ3NiwicGF0aCI6Ii8xMTE1MjkxODUvMzQ5MDU2MTA3LWU0OTNiOGU5LTgxN2UtNGZiYS04NTQxLTMyMGZhMWM5NTM3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQxMTE0MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YzJhNTUxZGJiM2M2ZmFmNWQzMmVlNzY1YzcxNzk0NWQwZDZhY2FmOWRjYmM0OTY4MzQzYmRhZTFjOWM5YTI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PN-vvwEoQS_-fGIPsFtdSSEvN8av_O0LDuK2-7o0wrA)

@maryjaf Thanks for reporting it, I had made a mistake and had a type error on mainnet address of this project I fixed that and it's working now

<img width="758" alt="Screenshot 1403-04-26 at 3 22 21 in the afternoon" src="https://github.com/user-attachments/assets/d2e79c01-2f14-46f7-a1be-a9e25d18b3f1">

**Comment by divine-comedian** [comment]
@LatifatAbdullahi - can you jump in here and take over testing this feature? 

Check the requirements above - you can filter for endaoment projects by using the corresponding sub-category page filter

**Comment by LatifatAbdullahi** [comment]
Sure!

**Comment by divine-comedian** [comment]
@mohammadranjbarz - Can you add support for Base-Sepolia

Then let's make sure we test donations on: 

- [ ] Base-Sepolia 
- [ ] Optimism-Sepolia

**Comment by LatifatAbdullahi** [comment]
@divine-comedian @mohammadranjbarz 

 (Donated to Reach Out NGO)
 Endaoment projects can receive donations  Optimism Sepolia- Pass
 Endaoment projects are GIVbacks eligible, corresponding UI elements are shown - Pass
 Users cannot donate to Endaoment projects on ineligible networks - Pass
 correct donation history appears after making successful donations - Pass
 
 @mohammadranjbarz please let me know when I can verify with Base- sepolia

**Comment by mohammadranjbarz** [comment]
> @divine-comedian @mohammadranjbarz
> 
> (Donated to Reach Out NGO) Endaoment projects can receive donations Optimism Sepolia- Pass Endaoment projects are GIVbacks eligible, corresponding UI elements are shown - Pass Users cannot donate to Endaoment projects on ineligible networks - Pass correct donation history appears after making successful donations - Pass
> 
> @mohammadranjbarz please let me know when I can verify with Base- sepolia

I added the Base Sepholia address for endaoment projects, can you test it ?

**Comment by LatifatAbdullahi** [comment]
@divine-comedian @mohammadranjbarz

(Donated to Reach Out NGO)
Endaoment projects can receive donations Base Sepolia- Pass
Endaoment projects are GIVbacks eligible, corresponding UI elements are shown - Pass
Users cannot donate to Endaoment projects on ineligible networks - Pass
correct donation history appears after making successful donations - Pass



![ooo](https://github.com/user-attachments/assets/24cd41fb-ac2b-4a74-aa74-7254fbd37fdf)
