### ISSUE TITLE
Include Recurring donation number on QF project card

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4287]
## It would be good if we consider this scenario 

- The project hasn't any one time donation in a round 
- The project has a recurring donation and it be counted in estimated matching 
- The project card is shown like below pic, amount raised in this round is 0 , estimated matching is more than zero (because of recurring donation in the round)

So the value of the recurring donation is not being considered in the "amount raised this round" field on the project card when the project is inside of an active QF round.

We should count the value of eligible recurring donations made inside the QF round to the given project and include it in this number.

![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/563cb129-10b3-406c-8e70-3d167a6dbf54)

_Originally posted by @maryjaf in https://github.com/Giveth/giveth-dapps-v2/issues/4222#issuecomment-2160198009_

FYI @koday1

**Comment by MohammadPCh** [comment]
@lovelgeorge99 can you take it, please? Thanks

**Comment by maryjaf** [comment]
When I change the start time of round , the sum of recurring donation in the round should be changed, am I right?

- the start date of round was 19/06
- the raised amount in the round was 129.63
- I changed the start time into 10/08
-but raised amount hasn't been changed and it is shown 129.63

https://staging.giveth.io/project/testtttttttt?tab=donations


and also the Number of contributor should be set based on both one time and recurring donation
for example for above project it should be set 2 contributors

**Comment by maryjaf** [comment]
and one more thing this issue hasn't been tested but I think since this change was on stagimg it was deployed on prod by the previous release, am I right?

**Comment by lovelgeorge99** [comment]
@maryjaf the current changes that I made , should reflect the change of amount in the project card . I have not made the changes to reflect it on the project donation card..will work on that next. Thanks for the feedback

**Comment by maryjaf** [comment]
> When I change the start time of round , the sum of recurring donation in the round should be changed, am I right?
> 
> * the start date of round was 19/06
> * the raised amount in the round was 129.63
> * I changed the start time into 10/08
> * but raised amount hasn't been changed and it is shown 129.63
> 
> https://staging.giveth.io/project/testtttttttt?tab=donations
> 
> and also the Number of contributor should be set based on both one time and recurring donation for example for above project it should be set 2 contributors

In this scenario, the project card is shown like below pic 

![image](https://github.com/user-attachments/assets/d7fb81d9-d223-416d-9cae-65355ea503a7)

it seems the number of amount raised in the round and estimated matching isn't correct

**Comment by maryjaf** [comment]
> and one more thing this issue hasn't been tested but I think since this change was on stagimg it was deployed on prod by the previous release, am I right?
> 
> unfortunately I hadn't seen this in QA board yesterday

Since this issue hadn't been tested, Can we revert this change on prod ?

**Comment by lovelgeorge99** [comment]
> > and one more thing this issue hasn't been tested but I think since this change was on stagimg it was deployed on prod by the previous release, am I right?
> > unfortunately I hadn't seen this in QA board yesterday
> 
> Since this issue hadn't been tested, Can we revert this change on prod ?

Yes,this should be reverted

**Comment by maryjaf** [comment]
> > > and one more thing this issue hasn't been tested but I think since this change was on stagimg it was deployed on prod by the previous release, am I right?
> > > unfortunately I hadn't seen this in QA board yesterday
> > 
> > 
> > Since this issue hadn't been tested, Can we revert this change on prod ?
> 
> Yes,this should be reverted

who should do that ?
@lovelgeorge99 
cc: @MohammadPCh @divine-comedian

**Comment by MohammadPCh** [comment]
@maryjaf @lovelgeorge99 Could we explore fixing it rather than reverting?

**Comment by MohammadPCh** [comment]
@maryjaf @lovelgeorge99 I'll remove the recurring donation amount from the card and release a hotfix. Please follow up on this issue to ensure it's fully resolved. Thanks!

**Comment by lovelgeorge99** [comment]
@maryjaf i have added the sum of recurring donations and the number of donars made in QF round 
![image](https://github.com/user-attachments/assets/f2e0bd11-eebc-4b31-98a1-92a3ada5faba)


also should that amount also be included here
![image](https://github.com/user-attachments/assets/47236d7f-8b67-45a1-a9de-ad2a70371dd8)

**Comment by maryjaf** [comment]
> When I change the start time of round , the sum of recurring donation in the round should be changed, am I right?
> 
> * the start date of round was 19/06
> * the raised amount in the round was 129.63
> * I changed the start time into 10/08
> * but raised amount hasn't been changed and it is shown 129.63
> 
> https://staging.giveth.io/project/testtttttttt?tab=donations
> 
> and also the Number of contributor should be set based on both one time and recurring donation for example for above project it should be set 2 contributors

Have you seen this scenario ? @lovelgeorge99

**Comment by mohammadranjbarz** [comment]
> When I change the start time of round , the sum of recurring donation in the round should be changed, am I right?
> 
> * the start date of round was 19/06
> * the raised amount in the round was 129.63
> * I changed the start time into 10/08
> * but raised amount hasn't been changed and it is shown 129.63
> 
> https://staging.giveth.io/project/testtttttttt?tab=donations
> 
> and also the Number of contributor should be set based on both one time and recurring donation for example for above project it should be set 2 contributors

We connect the qfRound and recurring donation streams when donations are made, so changing the start time of the qfRound later would not affect it and can't change the relation between donations and qfRounds

**Comment by lovelgeorge99** [comment]
![image](https://github.com/user-attachments/assets/47236d7f-8b67-45a1-a9de-ad2a70371dd8)
@mohammadranjbarz this is the recurring donations in that qf round and this should be shown in the QF project card...right?

**Comment by mohammadranjbarz** [comment]
> ![image](https://private-user-images.githubusercontent.com/36924734/360074346-47236d7f-8b67-45a1-a9de-ad2a70371dd8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0ODk1MzYsIm5iZiI6MTcyNjQ4OTIzNiwicGF0aCI6Ii8zNjkyNDczNC8zNjAwNzQzNDYtNDcyMzZkN2YtOGI2Ny00NWExLWE5ZGUtYWQyYTcwMzcxZGQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDEyMjAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyMTI5NTQ3YzNhMmE1MTg2ZTM4M2M0Mzg1NzVlMDA2ZjdhYzYzZTdlOTI1YzI3ODNmMzA1NGNlMzIwZWRiYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.82-MP8wE_phARM_-XAE32j1szbwHa48JvPBmKrtB9qY) @mohammadranjbarz this is the recurring donations in that qf round and this should be shown in the QF project card...right?

@lovelgeorge99  Yeah I think so

**Comment by lovelgeorge99** [comment]
![image](https://github.com/user-attachments/assets/ffae5ed4-f1e2-43d3-a79b-be8e6a101440)
https://staging.giveth.io/project/testing-project-lovel-george

@maryjaf This project does not have any one time donation only recurring donations and it is shown in the QF project card>
Can you check and verify

**Comment by maryjaf** [comment]
> https://staging.giveth.io/project/testing-project-lovel-george

Yeah we can call it Done
