### ISSUE TITLE
GIVeconomy network switch drop down showing the wrong networks

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4288]
This is what I see when I try to choose another network for the GIVfarm:
![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/e9a559d3-cb8b-45e8-98c3-b8ca3f66815c)

The only options should be:
- Gnosis
- Optimism

And coming soon should be:
- Polygon zkEVM

Celo and Ethereum Classic should not show at well.

@MohammadPCh

**Comment by maryjaf** [comment]
I've tested on this branch and it works as expected @MohammadPCh 
https://giveth-dapps-v2-git-update-switch-network-dropdown-givethio.vercel.app/?vercelToolbarCode=KKO8rb1AoM730KW
