### ISSUE TITLE
QF rounds should be sorted by date, where the one closest to the right is the most recent

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4289]
I was looking at [glo dollar](https://giveth.io/project/glo-dollar?tab=donations) and realized that our QF rounds are sorted in a really weird way... maybe alphabetically?

The qf round "tabs" on the donations tab for a project on the project single page should be sorted *from left to right according to most recent*.

so you should see here Galactic Giving, Giving Season, Optimism, for example

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/934670e9-509c-4d29-aab9-4b846e53317f)

@CarlosQ96 or @MohammadPCh can you assign the right frontend dev for this?

cc @koday1

**Comment by koday1** [comment]
Hey @Meriem-BM just reviving this issue - could you take a look at how we're sorting QF rounds under the 'Donations' tab on project pages?

**Comment by divine-comedian** [comment]
@HrithikSampson do you mind taking a look at this one w/ guidance from @CarlosQ96

**Comment by HrithikSampson** [comment]
Sure @divine-comedian . I will thake this issue

**Comment by HrithikSampson** [comment]
@maryjaf @LatifatAbdullahi , this issue is ready to be tested

**Comment by maryjaf** [comment]
The tests have been passed, thanks @HrithikSampson
