### ISSUE TITLE
Update QF round banner for the GIV-Earth round

### ISSUE THREAD

**Issue by koday1** [Giveth/giveth-dapps-v2#4294]
We are approaching the start of the GIV-Earth QF round and need to update the banner for the QF round page at https://giveth.io/qf.

Rodri has created the banner, a few more sponsors might be added before the round but here is the Figma link:
https://www.figma.com/design/W9Ace1RyCdykWM72fsSa3t/Giveth-Marketing-2024?node-id=7011-2700&t=TuIUxOpdv2h9ZqVb-4

@jainkrati @CarlosQ96 tagging you both as I'm not sure who this issue should go to, can you please assign it and I will provide an update here as soon as the banner is ready to add to the site?

**Comment by koday1** [comment]
Figma link to GIV-Earth round banner: https://www.figma.com/design/W9Ace1RyCdykWM72fsSa3t/Giveth-Marketing-2024?node-id=7011-2700&t=TuIUxOpdv2h9ZqVb-4

**Comment by laurenluz** [comment]
banner should look like this

@RamRamez are you working on this?
![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/0990bc9e-c21c-45a5-a39b-4896a9ce7526)

**Comment by RamRamez** [comment]
https://giveth-dapps-v2-git-add-new-qf-round-givethio.vercel.app/qf/all

@laurenluz This is the preview link, if you approve we can go live.

**Comment by koday1** [comment]
@RamRamez It looks good! Thanks for getting this up. We can push it live to production, but there may be 1-2 more sponsor logos that need to be added before the round starts on Tuesday. 

cc @laurenluz

**Comment by koday1** [comment]
@RamRamez We've added one more sponsor to the banner - here's the new one:
![GIVEarth banner](https://github.com/Giveth/giveth-dapps-v2/assets/34075192/0efb51cf-6043-40d7-b53f-1fa29b80f252)

The Figma link in the description is up to date. Could you update the banner once again when you have a chance? Thanks

**Comment by RamRamez** [comment]
> @RamRamez We've added one more sponsor to the banner - here's the new one: ![GIVEarth banner](https://private-user-images.githubusercontent.com/34075192/341528906-0efb51cf-6043-40d7-b53f-1fa29b80f252.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NzEzNDAsIm5iZiI6MTcxODk3MTA0MCwicGF0aCI6Ii8zNDA3NTE5Mi8zNDE1Mjg5MDYtMGVmYjUxY2YtNjA0My00MGQ3LWI1M2YtMWZhMjliODBmMjUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDExNTcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiMjNjZDY3MGI3ZTI1MTBlOTcxYjNhOTFlODA2OWY3NGYzOWMzMWIyN2UxOTQ0MDhkYmMwNjJlOTFjN2RkNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ztExeHGRGUMmeCA88UhK-OSMQZyLiFr1sIm7ltJGxFw)
> 
> The Figma link in the description is up to date. Could you update the banner once again when you have a chance? Thanks

Done!
