### ISSUE TITLE
stop the auto-redirect on the giveth.io/qf page

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4300]
we have qf round starting and need the giveth.io/qf page to just be the giveth.io/qf page so need to remove the redirect to giveth.io/projects

@MohammadPCh - can you help with this?

cc @koday1

**Comment by koday1** [comment]
Assigned to @RamRamez, he's also working on https://github.com/Giveth/giveth-dapps-v2/issues/4294
