### ISSUE TITLE
replace react-google-maps with @react-google-maps/api

### ISSUE THREAD

**Issue by MohammadPCh** [Giveth/giveth-dapps-v2#4317]
We need to replace `react-google-maps` with `@react-google-maps/api` since `react-google-maps` hasn't been updated for six years.

**Comment by maryjaf** [comment]
Which flows might be changed by this change and should be tested? @kkatusic @MohammadPCh

**Comment by maryjaf** [comment]
Which flows might be changed by this change and should be tested? @kkatusic @MohammadPCh

**Comment by kkatusic** [comment]
> Which flows might be changed by this change and should be tested? @kkatusic @MohammadPCh

@maryjaf, cc @MohammadPCh , this is change for google map location that you choose when you are creating new project. We have there old map package, now is new one. Please check [preview](https://giveth-dapps-v2-git-addgooglereactmap-givethio.vercel.app/) for this pull request, test it and let us know if there any bug, thx

**Comment by kkatusic** [comment]
> Merged

You are right, it is on staging server, thx

**Comment by maryjaf** [comment]
- [ ] by unchecking the box the "Global" word should be removed in text box

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/9daefba0-8a06-4a5d-a04a-f0107329a1fc

**Comment by maryjaf** [comment]
> * [x]  by unchecking the box the "Global" word should be removed in text box
> 
>  Screen.Recording.2024-07-03.at.3.28.47.PM.mov

Has this problem been fixed on staging? I see the merge request is open

**Comment by kkatusic** [comment]
> > * [x]   by unchecking the box the "Global" word should be removed in text box
> > 
> > Screen.Recording.2024-07-03.at.3.28.47.PM.mov
> 
> Has this problem been fixed on staging? I see the pull request is open @kkatusic when it is merged on staging, let me know to retest

@maryjaf it has been merged now, thx

**Comment by MohammadPCh** [comment]
Thanks @kkatusic
