### ISSUE TITLE
Fix 'Donations (USD value)' column on the Archived QF Rounds page

### ISSUE THREAD

**Issue by koday1** [Giveth/giveth-dapps-v2#4321]
The reported values for donations (usd value) in the archived QF rounds are way off for most (all?) of the rounds. See the screenshot below: 

<img width="1367" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODJKQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--99053c486bf53a248097758e3851378472004eb0/Screen%20Shot%202024-06-24%20at%2012.45.12%20PM.png" alt="Screen Shot 2024-06-24 at 12.45.12 PM.png" />

It seems all of the rounds are reporting much higher values than they should be. I think we should investigate how recurring donations are being calculated first and see if there's an issue there before troubleshooting in other ways.

@CarlosQ96 Could you investigate or assign this? It would be awesome to discover the fix before the GIV-Earth round begins in 20 hours, as we will be driving lots of traffic to the /QF page.

**Comment by laurenluz** [comment]
interestingly, on the round stats when you click open the round, the donation numbers look correct. example for ENS round: https://giveth.io/qf-archive/ens-builders

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/7f44940d-73da-41a4-b785-a4374aaff824)

Also, there should be no "Optimism test" listed on the archived rounds section. maybe we can delete that round?

**Comment by CarlosQ96** [comment]
Rewriting the query for count and total donations there is an error there, adding a test too.

**Comment by koday1** [comment]
Thanks @CarlosQ96! I double-checked the values and they look accurate now. Closing this issue
