### ISSUE TITLE
Change link on "Bridge your GIV" from Jumper to connext

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4322]
We have set up a new bridge for GIV. on the GIVeconomy, we should change the link of "Bridge your GIV" to...

When user is connected to gnosis: here: https://bridge.connext.network/GIVETH-from-gnosis-to-optimism
When user is connected to optimism here: https://bridge.connext.network/GIVETH-from-optimism-to-gnosis
When user is connected to mainnet here: https://bridge.connext.network/GIVETH-from-ethereum-to-optimism

This is on the page: https://giveth.io/givfarm

<img width="1348" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/75490971/8b9b2e9c-12bd-489b-bb58-e97ce7c3ae47">

This issue should only be done after @geleeroyale finishes setting up the liquidity and we finish building the arb bot.

**Comment by laurenluz** [comment]
@divine-comedian - no we are waiting on the completion of the arb bot before we move it. I will move it along when that's done.

**Comment by laurenluz** [comment]
@MohammadPCh this is issue is ready to go, can you give it to the appropriate dev?

**Comment by laurenluz** [comment]
or maybe @RamRamez can you have a look?

**Comment by LatifatAbdullahi** [comment]
@laurenluz @divine-comedian 


**Test Update**

This works as expected on https://giveth.io/, @laurenluz  you can check the attached video to confirm please.


When User is connected to Gnosis 


https://github.com/user-attachments/assets/789fa7b6-6b9e-4f98-aea5-49d51469fdb9




When User is connected to Optimism



https://github.com/user-attachments/assets/a11ef7db-fd47-4a17-9277-4003c0087b6b




When User is connected to Mainnet



https://github.com/user-attachments/assets/3b32d71d-68f1-4e4d-85da-0b09249360a4

**Comment by laurenluz** [comment]
@LatifatAbdullahi - did you check the scenarios when the user is connected to other chains (polygon, arbitrum, etc.)?

**Comment by LatifatAbdullahi** [comment]
> @LatifatAbdullahi - did you check the scenarios when the user is connected to other chains (polygon, arbitrum, etc.)?

@laurenluz 

I checked specifically for the networks listed above, I can run another check for other networks and get back to on it

**Comment by LatifatAbdullahi** [comment]
@laurenluz 

When connected to **Alfajores**  and the link is clicked it redirects to - https://bridge.connext.network/GIVETH-from-ethereum-to-optimism

When connected to **Polygon**  and the link is clicked it redirects to - https://bridge.connext.network/GIVETH-from-ethereum-to-optimism

When connected to **Arbitrum Sepolia**  and the link is clicked it redirects to -https://bridge.connext.network/GIVETH-from-ethereum-to-optimism but **requests for the user to switch network**

![image](https://github.com/user-attachments/assets/dbc2a6e1-065a-41e4-bb23-1665ce5defb8)


When connected to **Polygon zkvem**  and the link is clicked it redirects to -https://bridge.connext.network/GIVETH-from-ethereum-to-optimism but **requests for the user to switch network**

When connected to **Base Sepolia**  and the link is clicked it redirects to - https://bridge.connext.network/GIVETH-from-ethereum-to-optimism but **requests for the user to switch network**

**Comment by laurenluz** [comment]
ok nice! that's great, let's call this done

**Comment by LatifatAbdullahi** [comment]
@laurenluz 

This is the current behaviour for other chain networks

When connected to **Celo**  and the link "[Bridge your GIV]" is clicked it redirects to - https://bridge.connext.network/GIVETH-from-ethereum-to-optimism

When connected to **Polygon**  and the link  "[Bridge your GIV]" is clicked it redirects to - https://bridge.connext.network/GIVETH-from-ethereum-to-optimism

When connected to **Arbitrum One**  and the link  "[Bridge your GIV]" is clicked it redirects to -(https://bridge.connext.network/GIVETH-from-ethereum-to-optimism)

![image](https://github.com/user-attachments/assets/dbc2a6e1-065a-41e4-bb23-1665ce5defb8)


When connected to **Polygon zkvem**  and the link  "[Bridge your GIV]" is clicked it redirects to -(https://bridge.connext.network/GIVETH-from-ethereum-to-optimism)

When connected to **Base **  and the link  "[Bridge your GIV]" is clicked it redirects to - https://bridge.connext.network/GIVETH-from-ethereum-to-optimism
