### ISSUE TITLE
GIVpower is acting strange

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4326]
We've had several user reports of GIVpower acting strange. 

Some projects not changing rank at the beginning of a new round, when the estimate has show for several rounds that the project's rank would increase. Several projects have their estimated rank the same as many other projects. 

<img width="600" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3lLQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f174700c7ff6dda69dace60c0bb4ada6eae679ce/image.png" alt="image.png" />

<img width="600" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzJLQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--519a4c0cbfdf369d43620c0d488db918cd99a9c0/image.png" alt="image.png" />

Some projects or specific boosting have their amount shows as `NaN`

<img width="750" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3VLQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d38101d7e875bb762b26c3ccdf84baf3112d9434/image.png" alt="image.png" />

@RamRamez Did some investigation and here are his findings: 

> This is the first time I'm working on Givpower, the logic is complicated and I'm reading the codes trying to understand.
> 
> Different tables are involved in calculating givpower rank:
> ```
> power_snapshot
> power_round
> power_balance_snapshot
> power_boosting_snapshot
> project_power_view
> last_snapshot_project_power_view
> user_project_power_view
> project_user_instant_power_view
> ```
> etc...
> 
> The problem in staging is the `totalPower` field is zero for all projects in `project_power_view` table.
> 
> `project_power_view` table is a materialized view calculating totalPower by having power_balance_snapshot, power_boosting_snapshot and power_snapshot tables.
> 
> The current power round is `44197` but we don't have this roundNumber in `power_snapshot` table. The newest round in `power_snapshot` table is `35864` and we don't have any data for rounds after that.
> 
> Also other tables like power_balance_snapshot and power_boosting_snapshot have data until `35864` round, and there's no data for rounds after that.

We should investigate further, find out what's wrong with GIVpower and execute the required fixes to bring it back to normal.

cc: @laurenluz

**Comment by aminlatifi** [comment]
The problem was a wrong power boosting record from a user who never have had a positive givpower balance 0xa198b3e3028882122d6365a2290906074aad3431

I removed his boosting record and the state would be fine after the cronjob is executed again.

**Comment by aminlatifi** [comment]
https://github.com/Giveth/giveth-dapps-v2/issues/4333

**Comment by aminlatifi** [comment]
@RamRamez staging issue must be fixed now. The issue was database name was changed from staging -> staging2 and the db cron job was not updated to point to that db.

**Comment by RamRamez** [comment]
@aminlatifi the totalPower in projectPowerView is still zero for all projects on staging and givPower is not shown on UI.

Maybe we should refresh the all views manually?

https://staging.giveth.io/project/a-delicious-help?tab=givpower

**Comment by RamRamez** [comment]
@aminlatifi totalPower is still zero for all projects. Also UI not showing the GIVPower.

**Comment by mohammadranjbarz** [comment]
> @aminlatifi totalPower is still zero for all projects. Also UI not showing the GIVPower.

<img width="1178" alt="Screenshot 1403-04-06 at 10 45 20 in the morning" src="https://github.com/Giveth/giveth-dapps-v2/assets/9850545/3fbd7330-f18a-47a0-934c-7ba9cdaf6194">
@RamRamez Are you sure?
It's ok for my project

**Comment by aminlatifi** [comment]
Staging balance aggregator has issue in requesting subgraph
```

Fetch id 0xdaea66adc97833781139373df5b3bced3fdda5b1-100 - subgraph url https://api.studio.thegraph.com/query/76292/giveconomy-staging-gnosischain/version/latest - last update time 1719241855 - skip 0 - take 500 |  
-- | --
  |   | [Nest] 1  - 06/26/2024, 8:50:34 AM   DEBUG [FetchAgent] |  
  |   | [Nest] 1  - 06/26/2024, 8:50:34 AM   DEBUG [FetchAgent] Fetching id 0xdaea66adc97833781139373df5b3bced3fdda5b1-100 |  
  |   | [Nest] 1  - 06/26/2024, 8:50:25 AM   ERROR [FetchAgent] AxiosError: Request failed with status code 410 |  
  |   | [Nest] 1  - 06/26/2024, 8:50:25 AM   ERROR [FetchAgent] Error on fetch id 0x632ac305ed88817480d12155a7f1244cc182c298-420 -
```
@mhmdksh can you look at this?

**Comment by RamRamez** [comment]
> > @aminlatifi totalPower is still zero for all projects. Also UI not showing the GIVPower.
> 
> <img alt="Screenshot 1403-04-06 at 10 45 20 in the morning" width="1178" src="https://private-user-images.githubusercontent.com/9850545/343047295-3fbd7330-f18a-47a0-934c-7ba9cdaf6194.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzOTUxOTAsIm5iZiI6MTcxOTM5NDg5MCwicGF0aCI6Ii85ODUwNTQ1LzM0MzA0NzI5NS0zZmJkNzMzMC1mMThhLTQ3YTAtOTM0Yy03YmE5Y2RhZjYxOTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjZUMDk0MTMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzljMzcwMDc3ZTM0ZjJjZmVlY2UyNmU5NWNkY2NkZDU0YTExOTZhM2IyZmFlZDY1ZDBjODg0ZDYzMWI4YTk3YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Zo2A9LWmbXiDpHYy4H6rsz1DtI6lHL_f1QsOvDQ9CgQ"> @RamRamez Are you sure? It's ok for my project

@mohammadranjbarz GIVPower not showing is on staging only

**Comment by aminlatifi** [comment]
> > > @aminlatifi totalPower is still zero for all projects. Also UI not showing the GIVPower.
> > 
> > 
> > <img alt="Screenshot 1403-04-06 at 10 45 20 in the morning" width="1178" src="https://private-user-images.githubusercontent.com/9850545/343047295-3fbd7330-f18a-47a0-934c-7ba9cdaf6194.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzOTUxOTAsIm5iZiI6MTcxOTM5NDg5MCwicGF0aCI6Ii85ODUwNTQ1LzM0MzA0NzI5NS0zZmJkNzMzMC1mMThhLTQ3YTAtOTM0Yy03YmE5Y2RhZjYxOTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjZUMDk0MTMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzljMzcwMDc3ZTM0ZjJjZmVlY2UyNmU5NWNkY2NkZDU0YTExOTZhM2IyZmFlZDY1ZDBjODg0ZDYzMWI4YTk3YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Zo2A9LWmbXiDpHYy4H6rsz1DtI6lHL_f1QsOvDQ9CgQ"> @RamRamez Are you sure? It's ok for my project
> 
> @mohammadranjbarz GIVPower not showing is on staging only

It's fixed now.

**Comment by RamRamez** [comment]
@aminlatifi Thanks, it's ok now
