### ISSUE TITLE
Solana showing up as 'Unknown (101)' in eligible donation list during QF round

### ISSUE THREAD

**Issue by koday1** [Giveth/giveth-dapps-v2#4341]
We added Solana as an eligible chain for the GIV-Earth round but in the project view for eligible donation chains it's showing up as 'Unknown (101)'

<img width="1494" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK21PQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fc1c2d64d6b87b8be1c95232fcf584165fe98e44/Screen%20Shot%202024-06-25%20at%2010.46.57%20AM.png" alt="Screen Shot 2024-06-25 at 10.46.57 AM.png" />

Can we get a quick fix for this to let people know Solana is eligible for this round?

**Comment by maryjaf** [comment]
It hasn't been fixed @RamRamez 
<img width="1694" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFNTQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--57f33574a7757a11969b412ea28a162734bca228/image.png" alt="image.png" />

**Comment by RamRamez** [comment]
@maryjaf on staging we use different ids for Solana on FE and BE for test network so we have thiss problem, but in production it's ok, please test on production
