### ISSUE TITLE
Missing units on Matching pool amount in the archived qf round view

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4344]
for example ENS builders round, shows 20,000 for the matching pool : https://giveth.io/qf-archive/ens-builders

it should show the units... either $ or < token name > depending on what is set in the backend.

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/a42024ff-afb2-4141-aa31-168357cd61c1)

@koday1

**Comment by maryjaf** [comment]
This happened because the fields related to "Allocated Fund USD Preferred" or "Allocated Token Symbol/chainId" haven't been filled for this round

https://mainnet.serve.giveth.io/admin/resources/QfRound/records/8/show

**Comment by koday1** [comment]
Thanks for catching this @laurenluz and thanks for the explanation @maryjaf 

I updated the token info to DAI on OP Mainnet in Adminbro and now the matching pool shows properly as 20,000 DAI.
<img width="1345" alt="Screen Shot 2024-07-30 at 1 49 14 PM" src="https://github.com/user-attachments/assets/1e4f2c19-6b11-480c-a912-e9763e5d66ce">

Closing this issue

**Comment by laurenluz** [comment]
Nice @koday1 ! Thanks! Did you check all the other rounds too?

**Comment by koday1** [comment]
@laurenluz I found the same issue for the Giving Season, Polygon, and Optimism rounds. They're all updated now as well. Should be good for historical round data

cc @maryjaf

**Comment by laurenluz** [comment]
Thanks @koday1 !!
