### ISSUE TITLE
Add Farcaster link to Giveth in footer

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4353]
We should add another icon which will link to the Giveth Farcaster channel on Warpcast

Here's the link: 
https://warpcast.com/~/channel/giveth

![Image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/2e100637-b92b-4cc8-b058-143b5ed75fdc)

**Comment by Tosinolawale** [comment]
![Footer (_1280   _1439)](https://github.com/Giveth/giveth-dapps-v2/assets/35389241/c7062a87-b6ac-4005-8565-133b20b1ab55)
https://www.figma.com/design/hNqwpebu4JCy1XIed2c862/Giveth-Public?node-id=2564-12775&t=oDLQAiD3IAaF7F7j-1
@divine-comedian

**Comment by divine-comedian** [comment]
@kkatusic - I think you know how to handle this one :smile:

**Comment by divine-comedian** [comment]
@LatifatAbdullahi to test this - go to https://staging.giveth.io/

scroll to the footer
find farcaster icon in footer
verify when clicking icon it goes to giveth's farcaster channel

**Comment by LatifatAbdullahi** [comment]
Got it!

**Comment by LatifatAbdullahi** [comment]
@divine-comedian 

The Farcaster icon works as expected, when clicked it  directs Users to the  Giveth Farcaster channel.

https://github.com/user-attachments/assets/74c9348f-0fd1-4efb-8ec0-2bddd7fab498



Also,

This section is not properly placed on the design compared to the screen attached in previous comments. Is this okay?

![ste](https://github.com/user-attachments/assets/6753da81-3d15-4cfc-be87-3c2bd604e709)

**Comment by divine-comedian** [comment]
nice catch latifat! it looks like it is related to the responsive design, since when I increase the resolution / zoom out the elements goes into the expected position - @kkatusic is it possible to divide the social icons into two even rows instead?

**Comment by kkatusic** [comment]
@divine-comedian , cc @LatifatAbdullahi, it depends on screen size, can you provide me screen size and I will check on my side, better to said, on my screen it is ok
<img width="1374" alt="Screenshot 2024-07-17 at 01 05 48" src="https://github.com/user-attachments/assets/f9004a52-0f48-424b-88f1-92076b9d3245">

**Comment by LatifatAbdullahi** [comment]
@kkatusic 
 Its a 14.00 inch, resolution 1366×768 pixels Laptop.

**Comment by kkatusic** [comment]
> Added farcaster icon and related link #4392

My laptop is also 14" but has bigger resolution, I saw problem and fix for this added.

**Comment by kkatusic** [comment]
@LatifatAbdullahi when you get time can you check this fix? thx

**Comment by LatifatAbdullahi** [comment]
@kkatusic 

This  issue is fixed, thanks!

And the Farcaster icon directs users to the giveth channel.



![image](https://github.com/user-attachments/assets/62b021ab-bde8-463c-9b55-717a28a6885b)
