### ISSUE TITLE
Users Unable to  Filter  New Projects by Title in the Giveth Admin Portal

### ISSUE THREAD

**Issue by LatifatAbdullahi** [Giveth/giveth-dapps-v2#4363]
After successfully creating a new Project on Stage, When the Admin Users attempts to search for the Projects by its Title, it returns no results found(This happens even when the Project is Verified and Listed)

1.**Given** User has created a New Project
2. **And** User Logs into the  Giveth Admin Portal "((https://impact-graph.serve.giveth.io/admin/login))"
3. **And** User scroll navigates to Menu icon from the Top-left corner and clicks on it
4. **And** User clicks on "Projects" from the Drop down list
5. **And** User clicks on the "Filter" button at the Top-right corner 
6. **When** Users Pastes the Title of the New Project 
7.**And** User clicks on "Apply changes"
8. **Then** it returns "No records"

**Expected behavior**
When a Newly created valid Project is searched by Title, the Projects should be returned 
**Screenshots**
![dh](https://github.com/Giveth/giveth-dapps-v2/assets/112261242/0abd3815-2887-4c90-a685-76805a2649ee)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser : Chrome
 - Version 126.0.6478.127 (Official Build) (64-bit)

**Additional context**
When Users attempt to filter for Projects on the day the new project was created, it returns the expected response.

**Comment by divine-comedian** [comment]
@LatifatAbdullahi  - is that the partial project title or is it the full project title you are searching by?

**Comment by divine-comedian** [comment]
@RamRamez  - I think you are the tech lead for this one so passing it to you to investigate

**Comment by LatifatAbdullahi** [comment]
> @LatifatAbdullahi - is that the partial project title or is it the full project title you are searching by?

That is the Full project Title

**Comment by maryjaf** [comment]
The name of project is "OneProjectByLati" and the slug is "oneprojectbylati" by searching these in admin the expected result is shown 
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/d7623752-cec8-4ccd-83c5-cb36f46e2927)

@LatifatAbdullahi

**Comment by maryjaf** [comment]
I've created new project and then I searched it's name  in admin immediately, this project is shown correctly in admin
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/1de96088-2e16-41b2-8a29-f4f543833558)

also for "OneProjectByLati" the expected result is shown 
Could you please recheck this ? @LatifatAbdullahi

**Comment by LatifatAbdullahi** [comment]
Also, I searched with the same project you search for and it still showed no records

![image](https://github.com/Giveth/giveth-dapps-v2/assets/112261242/d9c07ea0-2d65-406a-8e86-f8d7d0f77941)

**Comment by RamRamez** [comment]
@LatifatAbdullahi You have entered an extra space before the title, that's why no record is found. The `+` in the URL means there's an extra space.

![image](https://github.com/Giveth/giveth-dapps-v2/assets/73441857/8fe68068-8655-41e2-8a1c-e700de9b7ce8)

**Comment by RamRamez** [comment]
@LatifatAbdullahi The title field doesn't have any dropdown, but it has auto-complete that browser manages it, so it means in the past you have typed the title with an extra space, and now your browser suggests it. It's not related to AdminJS, it's your browser history/cache.

**Comment by LatifatAbdullahi** [comment]
@RamRamez  Yes true the list from the auto complete. thanks for the info
