### ISSUE TITLE
Projects status not changing for several hours after being listed from admin panel

### ISSUE THREAD

**Issue by LatifatAbdullahi** [Giveth/giveth-dapps-v2#4364]
After successfully creating a new Project on Stage and the Projects has been Listed and Verified, When  Users attempts to search for the new Projects by its Title, it returns no results found

1.**Given** User has created a New Project on Stage (https://staging.giveth.io/)
2. **And** The Projects has been Listed and Verified
3. **And** User navigates to the "All Projects" page
4. **And** User clicks on the search icon
5. **When** Users Pastes the Title of the New Project in the search bar
7. **And** User clicks on "Enter"
8. **Then** it returns "No records", sometimes "500:Internal Server error"

Expected behavior
When a Newly created valid Project  which has been listed and verified is searched by Title, the Projects should be returned

**Desktop**
OS: Windows 11
Browser : Chrome
Version 126.0.6478.127 (Official Build) (64-bit)

**Additional context**
I have observed, it takes hours before Users can find the newly created Projects when searched

**Comment by divine-comedian** [comment]
@LatifatAbdullahi - I tested this out and wasn't able to reproduce it, is there a specific project that is not being returned on search or is it when searching for ANY keyword in the search bar?

**Comment by LatifatAbdullahi** [comment]
@divine-comedian 

I have created a new Project, updated the status at the Admin
![op](https://github.com/Giveth/giveth-dapps-v2/assets/112261242/6415dec5-9c1a-4df6-b2c8-e2f4a50275a2)

Project Title:  YProjectsByLatifat



Search for the Project here (All Products page)
https://staging.giveth.io/projects/all?searchTerm

**Comment by divine-comedian** [comment]
@LatifatAbdullahi - could be related to this specific project - looks like the search feature is working, but not for this proeject - this one also doesn't show up under the projects related to your profile 
https://staging.giveth.io/user/0xd30e526d3b5a65c68c0224fdad1096c9023b4f1b?tab=projects

We can however search and find successfully some other projects that you have made
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/ebf098ef-ed3c-4b0b-af5e-cb4b03c72917)

**Comment by RamRamez** [comment]
The project `YProjectsByLatifat` was not Listed, we only show listed projects on projects page.

I just changed the reviewStatus to `Listed` and it's being shown now.

https://staging.giveth.io/projects/all?searchTerm=YProjectsByLatifat

**Comment by divine-comedian** [comment]
very strange - let's try to reproduce this - @LatifatAbdullahi try to make a new project, set it as listed in the admin and test again if the UI shows it as listed on the project details page and if it can be searched for

**Comment by LatifatAbdullahi** [comment]
Sure

**Comment by divine-comedian** [comment]
I chatted with @LatifatAbdullahi and we were able to reproduce this issue 

She creates a project then lists it in the admin panel 

the UI shows the project as listed, however it cannot be found on the all projects page, by search or on the public view of the user profile page. 

Only after a few hours does the project finally show on the UI, even though it's already been listed for several hours from the admin panel 

@RamRamez - looks like there is a bug here, could be related to the instability of staging.

**Comment by RamRamez** [comment]
@divine-comedian We have a cache time of one minute on staging and production for projects page so it should be listed after one minute.

I just created this project "yprojects2bylatifat" and it was shown in search right after creating and listing.

https://staging.giveth.io/projects/all?searchTerm=yprojects2bylatifat

let's schedule a call and reproduce this, because everything seems fine.

**Comment by LatifatAbdullahi** [comment]
@RamRamez Lets connect tomorrow about this please

**Comment by LatifatAbdullahi** [comment]
@divine-comedian 

Test completed 
Test Status: Pass

@RamRamez and I connected and tried different scenarios and the projects when searched is found immediately after being listed
