### ISSUE TITLE
Fully Verified New Projects when viewed still shows the "Verify Tag"

### ISSUE THREAD

**Issue by LatifatAbdullahi** [Giveth/giveth-dapps-v2#4365]
When a new Project has been successfully Verified, when viewed, it still shows the "Verify Tag"

**To Reproduce**
1. **Given** a new Project has been verified 
2.  **And** Users has signed in with wallet
3. **And** Users navigates to "My Projects" on stage (https://staging.giveth.io/)
4. **And** User check for the newly verified Project
5. **And** User clicks on the Project Menu Action
6. **When** User clicks on "View Project"
7. **Then** there is "Verify Tag" on the Project

**Expected behavior**
**Successfully verified Projects should not show the "Verify Tag"**

**Screenshots**
![image](https://github.com/Giveth/giveth-dapps-v2/assets/112261242/a62d6d5e-c7ca-47d1-a902-ed7516750968)

**Desktop**
OS: Windows 11
Browser : Chrome
Version 126.0.6478.127 (Official Build) (64-bit)

**Additional context**
When Users click on the "Verify Tag" it directs Users to a page showing they have been Verified and the Tag remains.

**Comment by Meriem-BM** [comment]
@divine-comedian for this issue it's frontend issue, we should just make sure the conditions reflect each other everywhere, here is where we should check 


![Screenshot 2024-07-02 at 11 06 38 1(2)](https://github.com/Giveth/giveth-dapps-v2/assets/59566186/ebdda0ad-2c2a-4ba4-96f7-d1011762cbde)


Here I made I change that's why it's showing boost, which it's the correct thing to show when project verification status is verified + project status is activated + is verified
![Screenshot 2024-07-02 at 11 00 19 (2)](https://github.com/Giveth/giveth-dapps-v2/assets/59566186/1740a22f-f9b8-47fd-bbda-f4db76b58588)

Here are the fields
![Screenshot 2024-07-02 at 11 18 24 (2)](https://github.com/Giveth/giveth-dapps-v2/assets/59566186/78a661b7-30c9-40fa-a3ba-c8fa546b9e76)

![Screenshot 2024-07-02 at 11 17 50 (2)](https://github.com/Giveth/giveth-dapps-v2/assets/59566186/9f549bdc-9592-4d90-8870-ab37ba887fbf)

**Comment by MohammadPCh** [comment]
@kkatusic Can you take it?

**Comment by kkatusic** [comment]
@Meriem-BM thx for pointing that one combination of the submitting, verifying project is missing

**Comment by maryjaf** [comment]
I've checked the "MB" project and this problem happens because 
-The verification status of this project in "project verification form" is "verified"
-but in "project" menu it's status is "not verify"
and the tag in project page is changed from "verify project" into"boost" if the verify status of project in "project " menu in admin is "verify"

It seems there is also a problem in admin, i'll check with Ramin

**Comment by kkatusic** [comment]
> I've checked the "MB" project and this problem happens because -The verification status of this project in "project verification form" is "verified" -but in "project" menu it's status is "not verify" and the tag in project page is changed from "verify project" into"boost" if the verify status of project in "project " menu in admin is "verify"

Let's go throw steps, you create new project and verified it, after that project menu still showing "not verify"? Am I right?

**Comment by maryjaf** [comment]
> > I've checked the "MB" project and this problem happens because -The verification status of this project in "project verification form" is "verified" -but in "project" menu it's status is "not verify" and the tag in project page is changed from "verify project" into"boost" if the verify status of project in "project " menu in admin is "verify"
> 
> Let's go throw steps, you create new project and verified it, after that project menu still showing "not verify"? Am I right?



> We should add a case to what to show when verified + project status is activated + is verified and the user on that page is the owner of the project
> ![Screenshot 2024-07-02 at 14 42 06 (2)](https://private-user-images.githubusercontent.com/59566186/345055089-991d02cd-f7f4-418a-8f28-d1c3705de28f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MTY3NTMsIm5iZiI6MTcyMDYxNjQ1MywicGF0aCI6Ii81OTU2NjE4Ni8zNDUwNTUwODktOTkxZDAyY2QtZjdmNC00MThhLThmMjgtZDFjMzcwNWRlMjhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDEzMDA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiYzgzYTI2N2M0Njk3ZGE3NTY4ODVmNzVlYjlmYWU5M2U5NzM1ZjQ5YjA3ZWQ0M2UxZmUzOTFjMzYwMDljMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VpErZwuOSKbZq9rEkpGRoDC4Yy3tAfC0CTclBz9Sow0)

No, for my new verified project this problem doesn't happen 
I checked the @Meriem-BM project to check why this problem happened for "MB" project but for my  projects it was ok

**Comment by kkatusic** [comment]
> > > I've checked the "MB" project and this problem happens because -The verification status of this project in "project verification form" is "verified" -but in "project" menu it's status is "not verify" and the tag in project page is changed from "verify project" into"boost" if the verify status of project in "project " menu in admin is "verify"
> > 
> > 
> > Let's go throw steps, you create new project and verified it, after that project menu still showing "not verify"? Am I right?
> 
> > We should add a case to what to show when verified + project status is activated + is verified and the user on that page is the owner of the project
> > ![Screenshot 2024-07-02 at 14 42 06 (2)](https://private-user-images.githubusercontent.com/59566186/345055089-991d02cd-f7f4-418a-8f28-d1c3705de28f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MTY3NTMsIm5iZiI6MTcyMDYxNjQ1MywicGF0aCI6Ii81OTU2NjE4Ni8zNDUwNTUwODktOTkxZDAyY2QtZjdmNC00MThhLThmMjgtZDFjMzcwNWRlMjhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDEzMDA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiYzgzYTI2N2M0Njk3ZGE3NTY4ODVmNzVlYjlmYWU5M2U5NzM1ZjQ5YjA3ZWQ0M2UxZmUzOTFjMzYwMDljMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VpErZwuOSKbZq9rEkpGRoDC4Yy3tAfC0CTclBz9Sow0)
> 
> No, for my new verified project this problem doesn't happen I checked the @Meriem-BM project to check why this problem happened for "MB" project but for my projects it was ok

How you can check her projects if you don't has her wallet? Can you advice me how can I check that? thx

**Comment by maryjaf** [comment]
> **Screenshots**
> ![image](https://private-user-images.githubusercontent.com/112261242/344936874-a62d6d5e-c7ca-47d1-a902-ed7516750968.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MTcyMDEsIm5iZiI6MTcyMDYxNjkwMSwicGF0aCI6Ii8xMTIyNjEyNDIvMzQ0OTM2ODc0LWE2MmQ2ZDVlLWM3Y2EtNDdkMS1hOTAyLWVkNzUxNjc1MDk2OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMFQxMzA4MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MTA4MGZiYzljYTRlMDA1ZDhkZmE2OWYyNjFkMDE1ZjE4ZmVkNTk1ZWVmNDBmNGEwNWU4MmQzZjJkNzhhOTAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NOQ8pvlic_WYjn_l5bYdsoHY2-7UY6_xP7UGaXx73Jc)

for @LatifatAbdullahi  project as below pics the verification status in project menu isn't verify and it is the reason why "verify project" button is shown in project page

but we should check why this problem and this discrepancy happened in "project " and "project verification form" in "verify" status 
Is this a bad data related to test data and some manual changing or there is a bug 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/28c42548-7c6a-41cd-98a7-59f236fbf904)
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/6137d50d-f979-41d0-ade3-6b4ae0d712c8)

**Comment by kkatusic** [comment]
@maryjaf I think this happen when you verify project isnide verification form tab inside administration, than you unverify it from edit option of the project. @LatifatAbdullahi correct me if I wrong.

**Comment by LatifatAbdullahi** [comment]
@kkatusic 

I remember making the Project update only at the "Project" section, the only time I made an update in "Project verification" Tab was to Reject a project, all verifications have been in "Project" tab

**Comment by maryjaf** [comment]
> for @LatifatAbdullahi project as below pics the verification status in project menu isn't verify (verified:No - pic 2) and it is the reason why "verify project" button is shown in project page
> 
> 
>  ![image](https://private-user-images.githubusercontent.com/111529185/347418055-6137d50d-f979-41d0-ade3-6b4ae0d712c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2NzgyMjgsIm5iZiI6MTcyMDY3NzkyOCwicGF0aCI6Ii8xMTE1MjkxODUvMzQ3NDE4MDU1LTYxMzdkNTBkLWY5NzktNDFkMC1hZGUzLTZiNGFlMGQ3MTJjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMVQwNjA1MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZmU1ZGM4N2IzNmYxZjcyMTI4ZGZkMjg2Zjc5OTMwNWViMjdlMmY3NjkxMDkzMGQ5MWExYjcyNzY3ZGM2ZjIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dcMBM7i7SWQC09Y1v2o8mjqMcWJ2cdMC79QmWpG4A6I)

hmm, it's weird , in project menu in admin the status of verification for this project is : "verified:No"
https://impact-graph.serve.giveth.io/admin/resources/Project/records/224038/show

**Comment by maryjaf** [comment]
Please let us now when the changes be merged. @kkatusic 
I couldn't recheck the verification flow and there were some weird behavior and when I check with @RamRamez he said this is related to last changes that hasn't been merged

**Comment by RamRamez** [comment]
@LatifatAbdullahi When you are trying to verify or reject verification status, please do not use the below checkbox. It's not our standard flow because they will directly change the DB without applying required logics.
![image](https://github.com/Giveth/giveth-dapps-v2/assets/73441857/c5224962-7bec-45cb-b7df-1c4d9a693bba)


Please use the verify and reject button below for verification and rejection.
![image](https://github.com/Giveth/giveth-dapps-v2/assets/73441857/743b9182-e970-4192-b4d0-f0d7c2193d09)

I believe we can close this issue.

**Comment by divine-comedian** [comment]
@RamRamez  is it possible to hide this checkbox to prevent confusion in the future?

**Comment by RamRamez** [comment]
Yes, I've hidden it for both project and verification form (in staging).

**Comment by maryjaf** [comment]
Thanks @RamRamez I've checked, it works as expected

**Comment by kkatusic** [comment]
@divine-comedian can we close this? thx
