### ISSUE TITLE
connecting with solana dev net causes switch network model to show up constantly

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4371]
When I connect to solana devnet from the app the switch network modal constantly appears on every page including the homepage 

I am already connected to a known network so this modal should not show up on the homepage or any other pages that don't require me to be connected to a specific network

https://github.com/Giveth/giveth-dapps-v2/assets/67759413/5e4a66ca-66dc-473d-b0db-e9921d82ca9c

**Comment by ae2079** [comment]
@divine-comedian 
Does this bug exist now?
because I can not reproduce it and everything works correctly for me

**Comment by divine-comedian** [comment]
You're right, looks to be resolved, closing for now.
