### ISSUE TITLE
The GIVfarm is not working!

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4374]
I am logged in, signed in, on OP Mainnet, yet I don't see my balances, APRs, and I can't do anything like harvest, stake, unstake, etc.

help!! @aminlatifi @MohammadPCh 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/d5e52ec3-1577-487c-b947-05585aea7d9e)

**Comment by aminlatifi** [comment]
It works fine for me, maybe it was a subgraph outage

**Comment by MohammadPCh** [comment]
@laurenluz It seems that it was its problem, I think reducing the requests may also help this.
