### ISSUE TITLE
QF round donation success page - bug on round end date

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4378]
Here it is saying "invaid date" where it should show the QF round end date. I'm not sure if this bug is also happening in the qf round passport banners, or just on the donation success page, but we should check both.

![image](https://github.com/Giveth/giveth-dapps-v2/assets/75490971/5afabede-0557-4e92-b258-31fe9de34048)

cc @koday1

**Comment by koday1** [comment]
Hey @Meriem-BM @CarlosQ96 are one of you able to take a look into this bug?

**Comment by Meriem-BM** [comment]
Yeah, I'll do

**Comment by maryjaf** [comment]
> Here it is saying "invaid date" where it should show the QF round end date. I'm not sure if this bug is also happening in the qf round passport banners, or just on the donation success page, but we should check both.

Did this bug happen on production? 
I've checked on prod to reproduce this bug but the end date is shown correctly
![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/5ab2e0ea-dd4b-40e3-8ed9-6e5bd4353a44)

**Comment by laurenluz** [comment]
Yes it was during the giv-earth round on prod! @maryjaf

**Comment by Meriem-BM** [comment]
I have not been able to run into this issue, but I have made some adjustments that will prevent this from happening.
