### ISSUE TITLE
user getting signed out when loading QF page

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4379]
PRODUCTION 
METAMASK

when loading the QF page while navigating from another page in Giveth or even refreshing the page, if my user was signed in then it gets signed out and I have to reconnect my wallet. 

I can successfully navigate from the all projects page, project details and donate pages without getting signed out, only on loading the QF page does this appear to happen

https://github.com/Giveth/giveth-dapps-v2/assets/67759413/1b733baa-df87-4028-a473-44d6205d9f36

![Image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/7f110fa6-ae06-44f9-9555-14c1c0f028bf)

**Comment by mateodaza** [comment]
@divine-comedian can you give this a try on staging? I think It's solved with an upgrade on the connector I did

**Comment by divine-comedian** [comment]
@LatifatAbdullahi - here's another one for you to test out

**Comment by divine-comedian** [comment]
https://staging.giveth.io/qf/all

**Comment by LatifatAbdullahi** [comment]
@divine-comedian 

This works as expected, Users are no longer signed out when loading or refreshing the QF page

Uploading Give directly to for-good projects with crypto & zero fees - Google Chrome 2024-07-17 20-45-03.mp4…

**Comment by divine-comedian** [comment]
thanks MJ - @mateodaza - looks like there has been some regression on staging since this bug has appeared again.

**Comment by divine-comedian** [comment]
let's try to fix this and push a hotfix

**Comment by mateodaza** [comment]
@divine-comedian @maryjaf it's been impossible for me to replicate, but I'm pushing a [PR](https://github.com/Giveth/giveth-dapps-v2/pull/4574) removing an unused hook for referrals which is not needed in that page - I suspect it could be something very particular on staging, so I'm trying to isolate as much as possible - please try again

**Comment by maryjaf** [comment]
> This problem hasn't been fixed on prod Hasn't this issue been deployed on production in last release? @mateodaza cc: @divine-comedian

I've checked again, today this error  doesn't happen again for me on production

**Comment by maryjaf** [comment]
Some times by refreshing the page I got this error, It doesn't happen every time 
https://rpc.walletconnect.org/v1/profile/reverse/0xD5db3F8B0a236176587460dC85F0fC5705D78477?projectId=5ac0191ea92f7d0456628b30629e1b52 404 (Not Found)

![image](https://github.com/user-attachments/assets/66ad3815-2ddd-4340-9c79-ce5b0b30a428)
____________________

https://github.com/user-attachments/assets/09bfc666-9423-4fcb-96e2-f2112754c8ef

**Comment by divine-comedian** [comment]
@maryjaf - so you are connected to the app, and SOMETIMES on page refresh you are signed out and see this error you captured above?

**Comment by jainkrati** [comment]
@maryjaf were you able to repro the  issue ?

**Comment by divine-comedian** [comment]
@mateodaza 
I was able to reproduce the conditions under which to see this error. I tested on brave  using both MM and rabby wallet

 If I connect my wallet to the website, but DO NOT sign-in (getting JWT token) and refresh the page the dapp will disconnect my wallet from the app. 
 
 When I connect to the app, but haven't signed in I can navigate to other pages of the app and remain connected, but as soon as I refresh the page the app disconnects my wallet. 
 
 Ideally the user remains connected to the website with their wallet, even if the page is refreshed


https://github.com/user-attachments/assets/9a701014-654d-41c3-bce5-dd7451bc02cb

**Comment by maryjaf** [comment]
This getting sign out problem makes another problem in verification flow 

-When my user taps on the link to confirm the email address and complete the verification flow,  in this new page user isn't signed in , and the page is shown loading until the user complete the sign flow again

- or if user taps on "Resume verification",  in this page the same scenario happens , take a look on below screen record 


https://github.com/user-attachments/assets/b1f48ef7-57f9-4581-803e-763bb655a80e

@divine-comedian @mateodaza

**Comment by divine-comedian** [comment]
I think it's related to this issue @maryjaf let's wait for mateo to comment

**Comment by mateodaza** [comment]
@divine-comedian @maryjaf this is an issue exclusive to Brave and it's Shields configuration

If I have them up like this, then I encounter this bug 
![image](https://github.com/user-attachments/assets/e6c1c629-9900-46dd-968f-2a6ea0466250)

It's something very particular on their cookie/storage policy, so not sure how we can fix this on our side...

If you take it down like this it should work as expected, it did for me

![image](https://github.com/user-attachments/assets/0414db58-b862-459c-bf97-84de0603791d)

**Comment by divine-comedian** [comment]
Oh wow! You're totally right, I tested this on firefox and the issue doesn't exist 

@maryjaf if you can confirm this issue is related to brave shields then I think we have to close this issue as won't fix

**Comment by maryjaf** [comment]
> This getting sign out problem makes another problem in verification flow
> 
> * When my user taps on the link to confirm the email address and complete the verification flow,  in this new page user isn't signed in , and the page is shown loading until the user complete the sign flow again
> * or if user taps on "Resume verification",  in this page the same scenario happens , take a look on below screen record
> 
> if needed I'll create separate issue for this
> 
>  Screen.Recording.2024-09-10.at.11.09.35.AM.mov 
> @divine-comedian @mateodaza

This problem happened for me on chrome
