### ISSUE TITLE
When adding Solana address the wrong template is provided

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-dapps-v2#4380]
**Describe the bug**
Solana addresses don't start with 0x ... but the placeholder in the add address field says "0x ..."

**To Reproduce**
1. Go to 'manage addresses' on account/project view
4. See error in the preview

**Expected behavior**
See an example of a Solana address

**Screenshots**
<img width="828" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/317685/9c890364-0f6c-4e6f-b56c-017282889464">

**Comment by kkatusic** [comment]
@geleeroyale it is done, cc @maryjaf , @LatifatAbdullahi ;)

**Comment by LatifatAbdullahi** [comment]
Thanks @kkatusic , the placeholder is no longer "0x.. " and updated to the right format.

![yi](https://github.com/user-attachments/assets/e865a5a5-2572-4861-a5ea-388aee276bfc)
