### ISSUE TITLE
GIVpower page text adjustments

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#4382]
I have recently been looking into ways that we can add GIVpower into our messaging so that project owners know they can boost their own projects. I think that we could adjust the text on the GIVpower page to make this more clear.

I think we can remove "Top-ranked projects will eventually get funding from the Giveth Matching Pool." as that isn't so relevant now with QF rounds. 

Instead we could add "Stake your GIV donations to boost your project while earning rewards."

WDYT?

![image](https://github.com/Giveth/giveth-dapps-v2/assets/74267818/f945e759-d2a2-466a-b66e-b3e14bc22492)

**Comment by laurenluz** [comment]
- [ ] GIVpower subtext: GIVpower is your Giveth governance power! Use it to boost projects or vote on Giveth DAO proposals.
![image](https://github.com/user-attachments/assets/8e8a4a78-dd30-4a1d-bc90-d22c70e96d33)

- [ ] Change "imagine..." text to: "Discover decentralized project curation with GIVpower boosting"
![image](https://github.com/user-attachments/assets/93f8a66d-6b61-46bd-85ed-5ac71766ca30)

- [ ] remove this whole thing:
![image](https://github.com/user-attachments/assets/5016d00b-bb01-4007-98c4-76e8a78a9d30)

- [ ] Change title copy to: How does boosting work?
![image](https://github.com/user-attachments/assets/f1ee3934-4250-4b46-b777-90d12db6afb4)

- [ ] Win-win for Givers & Projects 
![image](https://github.com/user-attachments/assets/203e345d-ce24-412d-9cc9-6407144be903)

- [ ] For Givers section, last bullet point: "Donate to top-ranked projects to maximize your GIVbacks"
![image](https://github.com/user-attachments/assets/eb3aa41b-2fad-42dc-965d-d2ec0a8a25cc)

- [ ] For projects section, all bullets:
- Ask your community to boost your project
- The higher your rank, the better the GIVbacks rewards for donors.
- Don't forget to boost your own project too!
![image](https://github.com/user-attachments/assets/de2ca030-9507-4428-8270-6aee662ccf13)

- [ ] Also, there should be some space under the title "for projects" and the bullets
![image](https://github.com/user-attachments/assets/4d05ee81-35ed-4806-a9a6-2d8d41b3eecb)

**Comment by laurenluz** [comment]
@mohammadranjbarz can you assign someone for these frontend changes?

**Comment by mohammadranjbarz** [comment]
@maryjaf can you test it on this link https://giveth-dapps-v2-b4iwwt02n-givethio.vercel.app ?

**Comment by maryjaf** [comment]
> * قemove this whole thing:



> * remove this whole thing:
>   ![image](https://private-user-images.githubusercontent.com/75490971/364186875-5016d00b-bb01-4007-98c4-76e8a78a9d30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NjA3MTgsIm5iZiI6MTcyNjU2MDQxOCwicGF0aCI6Ii83NTQ5MDk3MS8zNjQxODY4NzUtNTAxNmQwMGItYmIwMS00MDA3LTk4YzQtNzZlOGE3OGE5ZDMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDA4MDY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2NTc4NDI2ZGM0NTZlZDYzMGQzYTkwMDk5NmRkZDU4ODgzZjg3MGE0ZGYwMTk3ZGNmODk0MGFjMjM1MDg0N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QR_SfxvseWbEFjR30AjcoykhfqO_rbJ26UqTJ94t3WQ)

The subject also should be removed or not ? @laurenluz @mohammadranjbarz 

![image](https://github.com/user-attachments/assets/d841db0f-f1c6-4018-8427-caa066b70f3f)

**Comment by maryjaf** [comment]
> * [x]  Also, there should be some space under the title "for projects" and the bullets

The lines in these two section aren't aligned @mohammadranjbarz 

![image](https://github.com/user-attachments/assets/99123272-09d4-46e5-903a-ed20fed79308)

**Comment by mohammadranjbarz** [comment]
> > * قemove this whole thing:
> 
> > * remove this whole thing:
> >   ![image](https://private-user-images.githubusercontent.com/75490971/364186875-5016d00b-bb01-4007-98c4-76e8a78a9d30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NjA3MTgsIm5iZiI6MTcyNjU2MDQxOCwicGF0aCI6Ii83NTQ5MDk3MS8zNjQxODY4NzUtNTAxNmQwMGItYmIwMS00MDA3LTk4YzQtNzZlOGE3OGE5ZDMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDA4MDY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2NTc4NDI2ZGM0NTZlZDYzMGQzYTkwMDk5NmRkZDU4ODgzZjg3MGE0ZGYwMTk3ZGNmODk0MGFjMjM1MDg0N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QR_SfxvseWbEFjR30AjcoykhfqO_rbJ26UqTJ94t3WQ)
> 
> The subject also should be removed or not ? @laurenluz @mohammadranjbarz
> 
> ![image](https://private-user-images.githubusercontent.com/111529185/368073754-d841db0f-f1c6-4018-8427-caa066b70f3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NjE2ODYsIm5iZiI6MTcyNjU2MTM4NiwicGF0aCI6Ii8xMTE1MjkxODUvMzY4MDczNzU0LWQ4NDFkYjBmLWYxYzYtNDAxOC04NDI3LWNhYTA2NmI3MGYzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxN1QwODIzMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wM2VhMGQxYTE3NTQzMDg0NTA1ODdiNzJmNDliNzQxNzQyNWY0YTEyMWNmMjkzZWQzNmJiOTA1ZGIzMzQxOGQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gvjUpoYakmb3m-jof1PMz0vWKL7O3wrhlFgGz6u3JrI)

I removed it and pushed
