### ISSUE TITLE
[BUG][STG] 404 error :  "No name for address is found"

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#4391]
**Describe the bug**
Sometimes I see strange behavior on stg 
as you can see in below screen records, my user is signed in, but for doing some actions like verify project , I got 404 error in console log 
it seems it's related to safe, but my user that I tested with it , isn't a multisig user 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/0bea96ef-5ad1-49fb-b922-289bb8b9f708)

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/8e19a193-7c1d-4f81-b3a7-beb6f49c503a

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/6e365b2d-018f-48e2-8070-bf8c077b14cf

cc: @mateodaza @divine-comedian

**Comment by maryjaf** [comment]
- [ ] As you can see in below screen record my metmask is lock but in giveth my user profile is shown 

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/079337ce-d60e-4e7a-80de-932764b99c90

**Comment by mateodaza** [comment]
I don't think this is related to multisig - there's some problem with the project you're testing. We'd have to check on the backend, 

- "No name for address is found" comes from wallet connect
- The useSafeConnect error is gracefully failing when you are indeed not inside a safe

For the little times I got them, in both cases it's just noise on the console - or are you getting an actual error ? we should scale it if you specify what exactly breaks

**Comment by maryjaf** [comment]
> * [ ]  As you can see in below screen record my metmask is lock but in giveth my user profile is shown
> 
>  Screen.Recording.2024-07-08.at.4.28.25.PM.mov

It isn't related to a specific project 
the actual  error in this case as you can see in this video  is that my metamask is lock but this user is shown as signed user in dapp
and I couldn't sign out and I should clear my cache every time 
 
I should remind that this problem isn't permanent but both cases taht I reported in description and comment happend to me multiple time

**Comment by maryjaf** [comment]
Thanks @mateodaza 
My concern is if the root of this problem is not found after deployment on production
Happen more often on production

**Comment by maryjaf** [comment]
Since this error happened to a user with whom I have a multisig account 0xA1179f64638adb613DDAAc32D918EB6BEB824104
And I signed in the site before with this multisig account, I thought it might be related to multisig

**Comment by mateodaza** [comment]
Thanks will take this into account

> Since this error happened to a user with whom I have a multisig account 0xA1179f64638adb613DDAAc32D918EB6BEB824104 And I signed in the site before with this multisig account, I thought it might be related to multisig

**Comment by mateodaza** [comment]
@maryjaf can you do some testing using this [link](https://giveth-dapps-v2-git-upgrades-web3modal-givethio.vercel.app/es), I updated the wallet connector library... personally I haven't been able to replicate so would appreciate your check

**Comment by maryjaf** [comment]
Yeah it’s hard to replicate and I don’t see this bug  in my all testsI, I haven’t fount the exact scenario 
yet, I’ll check  on this link and let you know

**Comment by maryjaf** [comment]
Thanks @mateodaza It seems now there is no problem and both above bugs don't happen again for me 
in console log the error is shown but I didn't see any problem in flows like verification, sign in, sign out.

![image](https://github.com/Giveth/giveth-dapps-v2/assets/111529185/3d437d14-623b-4453-9c0e-4132cae475d2)

**Comment by divine-comedian** [comment]
hopefully #4401 will fix this one

**Comment by maryjaf** [comment]
> in console log the error is shown but I didn't see any problem in flows like verification, sign in, sign out.
> 
> ![image](https://private-user-images.githubusercontent.com/111529185/347279720-3d437d14-623b-4453-9c0e-4132cae475d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MDAzMjAsIm5iZiI6MTcyMDYwMDAyMCwicGF0aCI6Ii8xMTE1MjkxODUvMzQ3Mjc5NzIwLTNkNDM3ZDE0LTYyM2ItNDQ1My05YzBlLTQxMzJjYWU0NzVkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMFQwODI3MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ODg1MTc3YTQ0OTRkNWYzYjkwZWNkYTNhYTZhNDUxNTQ1MzhiMGNlMmQwZjFhN2E4ODY1MzRiNTBkM2QwYjVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oTDKXZYuzaeMsXiQ4LOVsXjptAVb-R8wx2ZLIeauptE)

Is it accepted ?or the showing this error log should be resolved? @divine-comedian

**Comment by divine-comedian** [comment]
> > in console log the error is shown but I didn't see any problem in flows like verification, sign in, sign out.
> > ![image](https://private-user-images.githubusercontent.com/111529185/347279720-3d437d14-623b-4453-9c0e-4132cae475d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MDAzMjAsIm5iZiI6MTcyMDYwMDAyMCwicGF0aCI6Ii8xMTE1MjkxODUvMzQ3Mjc5NzIwLTNkNDM3ZDE0LTYyM2ItNDQ1My05YzBlLTQxMzJjYWU0NzVkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMFQwODI3MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ODg1MTc3YTQ0OTRkNWYzYjkwZWNkYTNhYTZhNDUxNTQ1MzhiMGNlMmQwZjFhN2E4ODY1MzRiNTBkM2QwYjVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oTDKXZYuzaeMsXiQ4LOVsXjptAVb-R8wx2ZLIeauptE)
> 
> Is it accepted ?or the showing this error log should be resolved? @divine-comedian

I think it is accepted if there is no abnormal behaviour on the user flow - regardless of if there are errors in the logs
