### ISSUE TITLE
My Account | Donations

### ISSUE THREAD

**Issue by mateodaza** [Giveth/giveth-dapps-v2#44]
@MoeNick commented on [Mon Jan 17 2022](https://github.com/Giveth/giveth-io-typescript/issues/70)

As us user I want to see list my donations and the USD value of them. 

# Design resources

- [My donations tab](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=4393%3A112100)

Note: for the current state we only have the sorting on the table, we'll add filtering in the next sprints.

**Comment by MoeNick** [comment]
fyi, recent changes on donation table:
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=4393%3A111393


we added hove state, with hover bg, hover text and an icon
we added also USD value and trx icon link
And also this ![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/16516d88-e00e-4a79-9a73-3919b7dfda5a)
to let the user know which column is sortable
we may apply it to my account -> my donation, not yet updated in Figma

**Comment by MoeNick** [comment]
QAing Overview:

- [ ] total amount donated is null 

QAing project page:
- [ ] The design of my donation is totally different than what I can see in this PR: 
This is what was expected: 
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/494b8f74-6a91-4077-92fc-d8b6450ff3da)

- Listing should be listing status null for not listed, true for listed and banned from false.

- ALso the verified badge if the project is verified. 

the active volume only checked if the project is active if other statuses like draft, deactivate or cancelled.

- [ ] I can swear these are not my projects :)) 
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/1f2e7a9e-19df-4b65-b497-863c080a9d37)

**Comment by CarlosQ96** [comment]
On it, found some issues, uploading hotfixes.

**Comment by CarlosQ96** [comment]
@MoeNick fixed the null value and migration. 
Improved projectsByUserId query. However those two projects according to staging are yours hahahahahaha

**Comment by CarlosQ96** [comment]
Found another issue with the likedprojects query gotta modify it to work with Amin reaction changes
it's missing one part

**Comment by CarlosQ96** [comment]
Fixed likedProjectQuery with new reaction changes! Tested with Mateo's user.

**Comment by MoeNick** [comment]
Please add no result in donation tab, if no donation is found:
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/352f863a-e360-4df5-8478-a9f7473d8e7e)
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=5413%3A132861
