### ISSUE TITLE
When I donate to a project, I want to go back to the project page but can't!

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#440]
I would expect that if I clicked the project card, it would bring me back to the "Learn More" page with all the project details
<img width="1495" alt="Screen Shot 2022-04-08 at 11 34 38 AM" src="https://user-images.githubusercontent.com/14945613/162484579-c25b923d-6241-422e-823f-3ecbacf2e24e.png">

**Comment by MoeNick** [comment]
@pkretzschmar  I think we fixed the name of project in staging, but would you pls make the project name in success page as a hyperlink to the project?

**Comment by MoeNick** [comment]
@pkretzschmar I mean, pls make it hyper link: 
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/861453cd-a809-4458-b0e2-3087a6ea6c3b)

**Comment by RamRamez** [comment]
@MoeNick 
In PR #515:
1. project image and project title on project card is linked to project view
2. the project name under 'You're a giver' is bolded linked to project view
