### ISSUE TITLE
giv.giveth links in emails don't work! Specifically Givbacks email gave a 404

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#441]
<img width="560" alt="Screen Shot 2022-04-09 at 7 11 19 AM" src="https://user-images.githubusercontent.com/14945613/162573662-2b277c81-89b6-447a-8f54-a68f907a43f3.png">

**Comment by MoeNick** [comment]
It assigned to devops, according to Amin. @geleeroyale  can you confirmed pls?

**Comment by geleeroyale** [comment]
Isn't it better to put this at comms to change the link in emails? Or should we put a redirect for `giv.giveth.io/givbacks` to `giveth.io/givbacks` even though the resource never existed?

**Comment by MoeNick** [comment]
> Isn't it better to put this at comms to change the link in emails? Or should we put a redirect for `giv.giveth.io/givbacks` to `giveth.io/givbacks` even though the resource never existed?



Im assuming [this issue](https://github.com/Giveth/giveth-dapps-v2/issues/290) should solve the problem. My question is the redirection is not working or Im missing something? @geleeroyale

**Comment by geleeroyale** [comment]
I added it (givbacks was missing from the original list of redirects). All of them work as intended

**Comment by MoeNick** [comment]
Thanks @geleeroyale
