### ISSUE TITLE
p0 - Givpower tab doesnt show anything for projects in production

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/giveth-dapps-v2#4410]
<img width="1920" alt="Screenshot 1403-04-23 at 11 44 28 in the morning (2)" src="https://github.com/user-attachments/assets/6b7f8ae3-4cd6-41f1-b6e2-7c4095763ea2">

As this problem just exists on production, I think it's because of some subgraph issues.
Probably related to this subgraph: `process.env.NEXT_PUBLIC_SUBGRAPH_GNOSIS`

**Comment by mohammadranjbarz** [comment]
@geleeroyale  : Our balance was running low till it ran out early morning. I filled up our account 


@maryjaf I think we can close this issue now

**Comment by maryjaf** [comment]
I've checked again on production and GIVpower tab is shown correctly
