### ISSUE TITLE
Giveth search function is not working at all?

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4411]
When I try to search "soilDAO", I see the spinning wheel, but then nothing... no filter, no indication of the search being executed. In the console it says "blocked by client".

<img width="1932" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemZjQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a0b560300bbd5405a0a3276846a3852667ad0986/image.png" alt="image.png" />

<img width="1387" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBempjQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--22bc00c454741654838d970cdcc3a5cb06d77291/image.png" alt="image.png" />

@MohammadPCh @divine-comedian

**Comment by kkatusic** [comment]
@laurenluz I'm checking

**Comment by kkatusic** [comment]
@laurenluz, cc @divine-comedian I wrote you search term _soildao_ clicked than on search and got this result:

![Screenshot 2024-07-15 at 14 14 32](https://github.com/user-attachments/assets/5128ffa2-6fe3-4dad-9985-9a21fe9eedbd)
also checked as log in user in chrome and brave browser.

Can you try reopen browser and check? thx in advance

**Comment by laurenluz** [comment]
hm... it worked now this time. I wonder what happened before. Thanks for check @kkatusic! I think we can close this and make a new one if it comes up again.

**Comment by kkatusic** [comment]
> hm... it worked now this time. I wonder what happened before. Thanks for check @kkatusic! I think we can close this and make a new one if it comes up again.

Np, we didn't push any changes this days, like you said if it happen we will investigate ;)
