### ISSUE TITLE
Stellar | My Account | My project | manage recipient address

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#4420]
As a user I want to be able to add Stellar address to an specific project in my projects list.

- [ ] Memo is not required, but if the user left it blank and click in Add Address, we should show a warning modal.  `Be Careful!  Some exchanges and wallets requires Memo to fund your account. Make sure to put it in the form if your wallet supports a memo. [Memo is not required in my exchange or wallet.]  

<img width="416" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGdiQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a3e3a8aeb828a29f53d128bc2bf34493327cbbee/image.png" alt="image.png" />
<img width="755" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGtiQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0431c0a171752d7e0a850bb110b8efde40e4fb13/image.png" alt="image.png" />
<img width="548" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMG9iQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0aa4aff07ffb9136ea8353e2085edaace55db33f/image.png" alt="image.png" />

**Comment by maryjaf** [comment]
> * Memo is not required, but if the user left it blank and click in Add Address, we should show a warning modal.  `Be Careful!  Some exchanges and wallets requires Memo to fund your account. Make sure to put it in the form if your wallet supports a memo. [Memo is not required in my exchange or wallet.]

- [ ] 1-

The warning modal isn't shown in manage address


https://github.com/user-attachments/assets/3a643636-c2ed-4457-8ee9-254044258966

**Comment by maryjaf** [comment]
> > * Memo is not required, but if the user left it blank and click in Add Address, we should show a warning modal.  `Be Careful!  Some exchanges and wallets requires Memo to fund your account. Make sure to put it in the form if your wallet supports a memo. [Memo is not required in my exchange or wallet.]
> 
> * [x]  1-
> 
> The warning modal isn't shown in manage address
> 
>  Screen.Recording.2024-08-13.at.11.12.00.AM.mov

![image](https://github.com/user-attachments/assets/db5e1775-e2eb-4b10-ba4e-2f20bb649b66)

it has been fixed
