### ISSUE TITLE
Stellar | Public Profile Page | Donations List of user

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#4421]
in /user/address

In the table of the donation, the logo and name of network, the amount and the link to base explorer should be correct.

**Comment by maryjaf** [comment]
> In the table of the donation, the logo and name of network, the amount and the link to base explorer should be correct.

The tests have been passed

![image](https://github.com/user-attachments/assets/9aea3792-3885-4615-8313-eaaf00e41755)
