### ISSUE TITLE
Stellar | Verification Flow | Managing funds | Adding relative addresses

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#4423]

**Comment by maryjaf** [comment]
> [ ] when I set an ETH address for stellar, an error message should be shown like as create/ edit project page, am I right?
> but as you can see in below screen record, I can set ETH address

@Meriem-BM Thanks, this problem has been fixed
only one question the "memo" field should be shown in this modal ? @MoeNick 
![image](https://github.com/user-attachments/assets/7487f788-2ba3-4db3-ab27-662050c77f75)

**Comment by MoeNick** [comment]
Thank you for reporting @maryjaf 
No the memo should not be shown here. @Meriem-BM

**Comment by maryjaf** [comment]
> Thank you for reporting @maryjaf No the memo should not be shown here. @Meriem-BM

Kindly reminder @Meriem-BM 
after removing memo in this modal we can move it to Done
