### ISSUE TITLE
Stellar | Changes in single project view | Owner View AND Public View

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#4424]
As an owner of the project when I open up my project I want to see m recipient addresses and also the Stellar Address if I'm raising fund on this chain. 

- showing Stellar address in the recipient addresses on right pane
- showing Stellar donation in the all donation table with the right amount. The logo and name of network, the amount and the link to base explorer should be correct.

**Comment by maryjaf** [comment]
![image](https://github.com/user-attachments/assets/84659f11-1b6f-4887-87a0-34c2d1996a04)
