### ISSUE TITLE
Stellar | Donation receipt/follow up page for lot logged in users.  

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#4426]
As a Stellar User I don't want to connect, but I want to follow up my donations. 

**Design:** 
https://www.figma.com/design/5qh6OaJRJSCNj2h22MMSwa/Stellar-Grant?node-id=8032-54901&t=9OPb4ZVdDbPcyjdV-4

- [x] Every donation has a public url path. 
- [x] Every donation has different status and a separate view based on that status. [pending, failed, success]
- [x] When user click on see my donation link in QR page, they can see this screen, save / copy the url and check later, or pass the URL to somebody else to donate if they want. So this screen acts as payment request / invoice and a receipt.

**Comment by maryjaf** [comment]
- [ ] When my user is signed in, by tapping on "Check Donation" I see my account, is this accepted? 
or for both scenario signed and not-signed users the page like figma should be shown

@Meriem-BM @MoeNick 

![image](https://github.com/user-attachments/assets/283605e6-46c1-4949-b315-4e31da641def)

**Comment by maryjaf** [comment]
- [ ] 2- 
The formatting of these 2 fields is not exactly base on the design 
- Recipient address
- Valid for


![image](https://github.com/user-attachments/assets/a5f1a09c-bbfe-4dca-b6b6-d39c88a5805a)

figma:

![image](https://github.com/user-attachments/assets/5e3bd58a-e743-4f1c-96b4-a475be88cdaf)
![image](https://github.com/user-attachments/assets/3ddd6407-4488-4c48-8891-142ecaff4767)

_______

- [ ] 3- "From" is shown NA

![image](https://github.com/user-attachments/assets/f55cebac-cf62-4503-902e-a9322ebbad7a)

**Comment by maryjaf** [comment]
This token is added in admin @MoeNick 
https://impact-graph.serve.giveth.io/admin/resources/Token/records/306/show

**Comment by maryjaf** [comment]
- [ ] 3-
 After success donation and showing below pic , how can user check the status of donation ? I mean the view of success in figma since there is no "Check Donation " button 
@MoeNick @Meriem-BM 

![image](https://github.com/user-attachments/assets/7570bc1c-8f85-447e-955a-5e6f21d7dc5b)

**Comment by maryjaf** [comment]
- [ ] 5-

as you can see in below screen record, I'm donating to "test base01" project but when I tap on check eligibility,  in this page the "MB" project is shown in "Donating to" field

https://github.com/user-attachments/assets/f8e9a88c-89ed-49ad-a002-1ee8f256287c

**Comment by maryjaf** [comment]
Items 1 , 3 and 5 haven't been fixed.
@Meriem-BM

**Comment by Meriem-BM** [comment]
> - [ ] 5- I see the success donation page but in check donation status page, the status is shown pending until I refresh the page
> 
> 
> 
> https://github.com/user-attachments/assets/a87b1217-aaa7-434f-8db9-26d87bf92402
> 
> 
> 
> 

Yeah, I didn't implement it to be updated in real time as donation page, user should refresh this page, but once it timeouts it will be updated, @MoeNick WDYT?

**Comment by Meriem-BM** [comment]
> - [ ] 1-  When my user is signed in, by tapping on "Check Donation" I see my account, is this accepted? 
> 
> or for both scenario signed and not-signed users the page like figma should be shown
> 
> 
> 
> @Meriem-BM @MoeNick 
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/283605e6-46c1-4949-b315-4e31da641def)
> 
> 

Yeah, that's what @MoeNick told me, @MoeNick can you confirm?

**Comment by MoeNick** [comment]
For 1, I meant the donations tab of the projects page, but as we don't show the pending donations there, I think we should load the receipt page instead. @Meriem-BM @maryjaf

**Comment by MoeNick** [comment]
For 5, is it possible it get updated as well like donation page?

**Comment by maryjaf** [comment]
> but once it timeouts it will be updated, @MoeNick WDYT?

- [ ] 7- 
There is a tiny problem in failed scenario also

when the time is over is see below pic, after refreshing I see second pic that "Expired at" field is shown on it 

before refresh:
<img width="1124" alt="Screenshot 2024-08-19 at 2 49 45 PM" src="https://github.com/user-attachments/assets/8247d41c-4ed9-4ae5-abd1-5614555832fb">

after refresh:
<img width="1270" alt="Screenshot 2024-08-19 at 2 51 41 PM" src="https://github.com/user-attachments/assets/4dfb6359-2ead-4fba-b355-15b30fbbb9ac">

**Comment by maryjaf** [comment]
Items 5 and 7 should be checked

**Comment by maryjaf** [comment]
> Items 5 and 7 should be checked

These problems have been fixed

**Comment by maryjaf** [comment]
- [ ] I see a new bug , i'm not sure if it is related to event problem or not  as you can see my donation is shown success in donation page(the donation success view isn't shown) but in receipt page it's status is failed !
@Meriem-BM 


https://github.com/user-attachments/assets/a7f1a126-a401-40cb-850d-140ff8cd67b2

**Comment by Meriem-BM** [comment]
> - [ ] I see a new bug , i'm not sure if it is related to event problem or not  as you can see my donation is shown success in donation page(the donation success view isn't shown) but in receipt page it's status is failed !
> 
> @Meriem-BM 
> 
> 
> 
> 
> 
> https://github.com/user-attachments/assets/a7f1a126-a401-40cb-850d-140ff8cd67b2
> 
> 
> 
> 
> 
> 

Yes, it is related.
