### ISSUE TITLE
Bridge the GIV token to Polygon zkEVM

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4429]

**Comment by divine-comedian** [comment]
GIV token on polygon zkEVM can be found here -> 
https://zkevm.polygonscan.com/token/0xddAFB91475bBf6210a151FA911AC8fdA7dE46Ec2

**Comment by laurenluz** [comment]
boooom!!

**Comment by laurenluz** [comment]
should we move out MATIC LP over here now that the GIV token is there too?
