### ISSUE TITLE
Deactivation email should be different with cancelled email

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#443]
In deactivation:

- we show the project with a blue notification that this project is deactivated. 
- nobody can donate
- It can be done by the owner
- it can be reactivated again by the owner. 

In canceled : 
- we won't show it at all
- it can only be done by Admin

So it should be totally different email and content over autopilot.

**Comment by MoeNick** [comment]
Sorry, @divine-comedian I assigned it to you cause I don;t know who can handle it. it's a little bit urgent and appreciates it if you could give it to others, manage it, or let me know how we can fix it.

**Comment by CarlosQ96** [comment]
Checkin this issue now

**Comment by CarlosQ96** [comment]
Hmm ok found the bug, there is a wrong mapping with the states after we refactored. Will upload a hotfix.

**Comment by CarlosQ96** [comment]
@divine-comedian @MoeNick fixed on staging for testing. Let me know when you can check the flow on autopilot.
<img width="794" alt="image" src="https://user-images.githubusercontent.com/92376054/163746125-d9004d68-3a47-4697-8821-78300c619d41.png">

**Comment by divine-comedian** [comment]
okay testing this out again I cancelled a few of my projects via the adminBro and I can see it comes through segment 

![image](https://user-images.githubusercontent.com/67759413/163809630-9b3a87f7-6c0d-4cdd-98a6-6d0237d6a30a.png)

and I receive an email telling me that it's been cancelled
![image](https://user-images.githubusercontent.com/67759413/163809880-aaaefaab-4c86-48ab-8796-f89a1fde26b4.png)

I checked for project deactivated - we still receive the event in segment but an email is no longer sent to the user. calling this DONE
