### ISSUE TITLE
Change GIVpower aggregator to consider GIVpower on Polygon zkEVM as well as other chains

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4431]

**Comment by mohammadranjbarz** [comment]
@maryjaf @laurenluz  @LatifatAbdullahi 
As I integrated ZKEVM mainnet with balance-aggregator if you stake/lock GIVs on below preview link your givPower balance would change in giveth.io

https://giveth-dapps-v2-git-addpolygonzkevmgivpower-givethio.vercel.app/givfarm

**Comment by maryjaf** [comment]
My GIVpower is shown 0 on this branch 
0xcd192b61a8Dd586A97592555c1f5709e032F2505
![image](https://github.com/user-attachments/assets/b2677aa6-6281-43cd-a275-f4ecbf405f49)

**Comment by laurenluz** [comment]
@mohammadranjbarz it's strange that on this branch, I ONLY see my GIVpower from zkEVM mainnet, but not from gnosis or Optimism... and my GIVpower balance on the branch is only what I have from zkEVM... is this expected?

![image](https://github.com/user-attachments/assets/31ec5b58-1997-4638-9987-c3eaf4cd510d)

![image](https://github.com/user-attachments/assets/f9e9d8a2-a496-46ad-a9b2-39782ad3b853)

**Comment by laurenluz** [comment]
also are these branch APRs real from the real unipool? where are these zkEVM mainnet rewards coming from?

**Comment by mohammadranjbarz** [comment]
> also are these branch APRs real from the real unipool? where are these zkEVM mainnet rewards coming from? it's too much!! is the unipool actually allocating rewards from the real zkEVM token distro?

I just notifyReward for unipool an amount to test it, I transferred some GIV tokens (about 100) to the tokenDistro and assigned it to unipool, because the stakes amount is not much the APR is high, and yes the rewards come from zkevm token distro

**Comment by maryjaf** [comment]
I've checked the GIVpower scenarios on zkEVM and other chains and the showing GIVpower is correct and it is the aggregation of givpower on gnosis, op and zk as expected 
I've tested it on staging
