### ISSUE TITLE
Update GIVbacks so donations on polygon zkEVM yield GIVbacks on polygon zkEVM

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4432]

**Comment by WhyldWanderer** [comment]
Do you mean the documentation @laurenluz ?

**Comment by laurenluz** [comment]
noooo, we need to make sure that we are actually giving the GIVbacks on Polygon zkEVM for those donations. When we did this for Optimism, I remember we had to change something in the process or calcualtions to earmark which donations get rewarded on which chain.

This issue is the expansion of that corresponding to our polygon zkevm integration.

**Comment by WhyldWanderer** [comment]
Ah okay... I don't think there is much I can do for this issue except testing it after its finished. 

This will probably have to be done by @mohammadranjbarz when he returns from vacation.

**Comment by mohammadranjbarz** [comment]
@laurenluz  @WhyldWanderer 

Now we distribute **Gnosis** donations on **Gnosis**  chain and all other donations on `OP**, but we want to distribute **ZKEVM** donations on the **ZKEVM** chain like **Gnosis** am I right?

**Comment by laurenluz** [comment]
exactly

**Comment by mohammadranjbarz** [comment]
@HrithikSampson Please work on this task
1. Clone this repository https://github.com/Giveth/givback-calculation
2. I will send a `.env` file in DM for you, you should use it for running locally
3. You can browse the staging swagger and play a little with APIs https://givback.develop.giveth.io/api-docs
4. You should modify below endpoints , to add another option like `gnosis` for the `chain` or `download` param
* https://givback.develop.giveth.io/api-docs/#/default/get_calculate
* https://givback.develop.giveth.io/api-docs/#/default/get_eligible_donations
* https://givback.develop.giveth.io/api-docs/#/default/get_not_eligible_donations
* https://givback.develop.giveth.io/api-docs/#/default/get_calculate_updated

<img width="1512" alt="Screenshot 1403-05-30 at 11 23 34 in the morning" src="https://github.com/user-attachments/assets/89131a1e-8ee3-47af-8611-edba4dc2d45e">

**Comment by HrithikSampson** [comment]
Hi,
I need access to create a branch for creating a pull request.

**Comment by mohammadranjbarz** [comment]
> Hi, I need access to create a branch for creating a pull request.

@mhmdksh  @geleeroyale  @Rolazo  Can you take care of it?

**Comment by geleeroyale** [comment]
@mohammadranjbarz 

Your permissions were elevated to maintainer @HrithikSampson

**Comment by mhmdksh** [comment]
Thanks @geleeroyale

**Comment by divine-comedian** [comment]
@HrithikSampson what is the update on this issue?

**Comment by HrithikSampson** [comment]
@divine-comedian , this issue is merged. Mohammad merged the pull request, I will ask him once whether the testing is done or it still requires to be done.

**Comment by mohammadranjbarz** [comment]
@WhyldWanderer Can you confirm if it's ok or not?

**Comment by WhyldWanderer** [comment]
Sure! I can take a look @mohammadranjbarz. Its on production now?
Which round should this start taking effect?

I had already calculated round 70 and made the forum post but then found that the sponsor donations hadnt been included yet. So now I need to re-calculate and put the new results in the forum post. Do you think it will be weird to change up the distribution method when doing the re-calculation of the round?

**Comment by HrithikSampson** [comment]
@WhyldWanderer , I only know that It is not on production but on staging.

**Comment by laurenluz** [comment]
@HrithikSampson are you sure??

This should have been merged to production along with the GIVeconomy release on zkEVM @mohammadranjbarz

**Comment by HrithikSampson** [comment]
@laurenluz @mohammadranjbarz  , I cant find my commit on the master branch. I couldn't find the zkevm option in https://givbacks.giveth.io/api-docs.

**Comment by mohammadranjbarz** [comment]
> @laurenluz @mohammadranjbarz , I cant find my commit on the master branch. I couldn't find the zkevm option in https://givbacks.giveth.io/api-docs. Should I merge it to production after it is tested

@laurenluz Yes exactly

**Comment by WhyldWanderer** [comment]
Maybe we should wait to merge it until the round 70 GIVbacks have been distributed. There was a delay due to qf sponsor donations getting added. I am putting up the new data in the forum post now. Then it should stay for at least 24 hours for any objections before moving to a vote.

I will tag you here once they have been distributed. It should be by Wednesday. Sound good?

**Comment by HrithikSampson** [comment]
@maryjaf @LatifatAbdullahi , this issue is ready to be tested

**Comment by maryjaf** [comment]
https://givback.develop.giveth.io/api-docs/#/default/get_eligible_donations

This address isn't working now  @HrithikSampson @mohammadranjbarz

**Comment by HrithikSampson** [comment]
@maryjaf , Can you check again . I think it will work now

**Comment by maryjaf** [comment]
Thanks. @HrithikSampson 
could you please check this donation
https://cardona-zkevm.polygonscan.com/tx/0x3d06b5be32cda3f90020cdc29eaf6a2a2ff3e0e6b0672770a8048740b0d0ca7e

I made this donation and my user isn't in purple list and project is givback eligible, but i havn't seen this donation in response of givback api , the response is empty
0xA1179f64638adb613DDAAc32D918EB6BEB824104
https://staging.giveth.io/project/mejan
__
curl:
curl -X 'GET' \
  'https://givback.develop.giveth.io/eligible-donations?chain=zkEVM&startDate=2024%2F10%2F01-00%3A00%3A00&endDate=2024%2F10%2F02-23%3A59%3A59&minEligibleValueUsd=0.00001&givethCommunityProjectSlug=the-giveth-community-of-makers&download=no' \
  -H 'accept: application/json'
  
 
![image](https://github.com/user-attachments/assets/bd5bacaa-ca36-455a-bfd6-173323b29f93)

**Comment by HrithikSampson** [comment]
Hi @maryjaf ,
I have filtered it based on the zkevm-mainnet address should I do it for zkevm-cardona

**Comment by CarlosQ96** [comment]
Talked with Hrithik, @maryjaf will add the filter. For testing's sake.

**Comment by HrithikSampson** [comment]
For Staging the network is configured to be zkevm cardona and for production it is zkevm mainnet

**Comment by maryjaf** [comment]
> Thanks. @HrithikSampson could you please check this donation https://cardona-zkevm.polygonscan.com/tx/0x3d06b5be32cda3f90020cdc29eaf6a2a2ff3e0e6b0672770a8048740b0d0ca7e
> 
> I made this donation and my user isn't in purple list and project is givback eligible, but i havn't seen this donation in response of givback api , the response is empty

Thanks @HrithikSampson now it works correctly and I see my zkEVM donation in response of GIVback api 

![image](https://github.com/user-attachments/assets/863bbc10-e22b-4bfc-8948-29e2d2df751b)

**Comment by WhyldWanderer** [comment]
Yes! The votes went up yesterday for Round 70 so the coast is clear now to merge to production @HrithikSampson 

Thank you!

**Comment by mohammadranjbarz** [comment]
@HrithikSampson  @WhyldWanderer 
I deployed all the changes to production
