### ISSUE TITLE
Add Polygon zkEVM GIVstream to GIVstream page UI

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4433]

**Comment by mohammadranjbarz** [comment]
@laurenluz  In this preview link I added zkevm mainnet smart contracts, so you can check the zkevm mainnet smart contracts 

https://giveth-dapps-v2-git-addpolygonzkevmgivpower-givethio.vercel.app/givfarm

**Comment by mohammadranjbarz** [comment]
FYI @maryjaf @LatifatAbdullahi @divine-comedian

**Comment by LatifatAbdullahi** [comment]
@mohammadranjbarz 

I keep getting this error when attempting to stake using Polygon zkEVM,  with no  errors in the main logs,  I have experienced this issue like 3 out of 5 times I tried staking tokens, before I successful flow.

![image](https://github.com/user-attachments/assets/0efad660-1673-46d0-806c-6a06bd533e68)



https://github.com/user-attachments/assets/a8ce34f8-405f-4bf2-bb0b-0ae93d90b597



Although after multiple trial, the transaction was finally approved and I was able to complete the stake flow, Increase rewards, Harvest claims, Lock tokens and Unstake tokens.

**Comment by laurenluz** [comment]
@mohammadranjbarz I found some issues on this branch, including with GIVstream page here: https://github.com/Giveth/giveth-dapps-v2/issues/4599

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz I found some issues on this branch, including with GIVstream page here: #4599

Thanks

**Comment by maryjaf** [comment]
I've tested it again and it works as expected, could you please check it again @LatifatAbdullahi 

https://github.com/user-attachments/assets/0ecc3a40-ab56-4af9-947e-2a04510b877a

**Comment by LatifatAbdullahi** [comment]
@maryjaf @MohammadPCh 

I just tried it and it worked fine without glitches, probably the network when I tested earlier.
