### ISSUE TITLE
Adjust notify reward bots on OP, Gnosis & Polygon zkEVM so Polygon zkEVM has 10% of total rewards

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4434]

**Comment by laurenluz** [comment]
Since we have a set amount of GIV available to distribute for this GIvpower incentives period, we need to borrow from other chains.

As per [this forum post](https://forum.giveth.io/t/givpower-summary-requesting-giv-for-incentives-update-q2-2024/719/31) we decided that we would take 5% from gnosis and 5% from optimism for the remaining time and move it zkEVM - so we need to re-program the notify reward bots for each chain.

this was the last notify reward issue we implemented FYI: https://github.com/Giveth/giveth-dapps-v2/issues/4057

I worked in this spreadsheet to calculate the amounts per chain if we launch this September 3 or September 17: https://docs.google.com/spreadsheets/d/14kj7eIJg_hTf8BwVoGvPEWAo2Z6O18lA2bd1jOGZaNc/edit?gid=220436869#gid=220436869

**We need to launch this on one of those two dates in order for everything to be properly synced with the other farms**

@mohammadranjbarz how do we do this? I'm assuming we stop the old notify reward bot and then a new one, with a new total amount and new percentages per round? If so, here are the distributions:

## If we launch & start rewards September 3

<google-sheets-html-origin><style type="text/css"></style>
Gnosis & OP |   |   |  
-- | -- | -- | --
Round Number | Start Date | GIV per round | % of total
Round 1 | September 3 | 295,977 | 19.59%
Round 2 | September 17 | 299,207 | 19.80%
Round 3 | October 1 | 302,033 | 19.99%
Round 4 | October 15 | 305,264 | 20.20%
Round 5 | October 29 | 308,494 | 20.42%
  | Totals: | 1,510,975 | 100.00%

<google-sheets-html-origin><style type="text/css"></style>
Polygon zkEVM |   |   |  
-- | -- | -- | --
Round Number | Start Date | GIV per round | % of total
Round 1 | September 3 | 31,155 | 19.59%
Round 2 | September 17 | 31,495 | 19.80%
Round 3 | October 1 | 31,793 | 19.99%
Round 4 | October 15 | 32,133 | 20.20%
Round 5 | October 29 | 32,473 | 20.42%
  | Totals: | 159,050 | 100.00%



## If we launch & start rewards September 17

Gnosis & Optimism notify reward bots will be the same with:

Gnosis & OP |   |   |  
-- | -- | -- | --
Round Number | Start Date | GIV per round | % of total
Round 1 | September 17 | 299,220 | 24.63%
Round 2 | October 1 | 302,046 | 24.86%
Round 3 | October 15 | 305,277 | 25.12%
Round 4 | October 29 | 308,507 | 25.39%
  | Totals | 1,215,050 | 100.00%


Polygon zkEVM |   |   |  
-- | -- | -- | --
Round 11 | September 17 | 31,497 | 24.63%
Round 12 | October 1 | 31,794 | 24.86%
Round 13 | October 15 | 32,134 | 25.12%
Round 14 | October 29 | 32,474 | 25.39%
  | Totals | 127,900 | 100.00%


One question/concern I have is regarding the balance we assign to the unipool distributor on each chain... we'll be removing some allocation from Gnosis and OP... so I guess we should just discount that the next time we assign a new balance for reward extensions? or can we reduce the amount of GIV the gnosis & OP unipools can spend from the token distros?

In the case of zkEVM, we'll need to make sure we assign a balance to the polygon zkevm unipool to distirbute the right amount of tokens.

Also, would appreciate it if someone checked my math/my work here on the calculations. I think it's correct, but a second opinion is always nice.

cc @aminlatifi

**Comment by mohammadranjbarz** [comment]
> Since we have a set amount of GIV available to distribute for this GIvpower incentives period, we need to borrow from other chains.
> 
> As per [this forum post](https://forum.giveth.io/t/givpower-summary-requesting-giv-for-incentives-update-q2-2024/719/31) we decided that we would take 5% from gnosis and 5% from optimism for the remaining time and move it zkEVM - so we need to re-program the notify reward bots for each chain.
> 
> this was the last notify reward issue we implemented FYI: #4057
> 
> I worked in this spreadsheet to calculate the amounts per chain if we launch this September 3 or September 17: https://docs.google.com/spreadsheets/d/14kj7eIJg_hTf8BwVoGvPEWAo2Z6O18lA2bd1jOGZaNc/edit?gid=220436869#gid=220436869
> 
> **We need to launch this on one of those two dates in order for everything to be properly synced with the other farms**
> 
> @mohammadranjbarz how do we do this? I'm assuming we stop the old notify reward bot and then a new one, with a new total amount and new percentages per round? If so, here are the distributions:
> 
> ## If we launch & start rewards September 3
> <style type="text/css"></style>
> 
> Gnosis & OP	 	 	 
> Round Number	Start Date	GIV per round	% of total
> Round 1	September 3	295,977	19.59%
> Round 2	September 17	299,207	19.80%
> Round 3	October 1	302,033	19.99%
> Round 4	October 15	305,264	20.20%
> Round 5	October 29	308,494	20.42%
>  	Totals:	1,510,975	100.00%
> <style type="text/css"></style>
> 
> Polygon zkEVM	 	 	 
> Round Number	Start Date	GIV per round	% of total
> Round 1	September 3	31,155	19.59%
> Round 2	September 17	31,495	19.80%
> Round 3	October 1	31,793	19.99%
> Round 4	October 15	32,133	20.20%
> Round 5	October 29	32,473	20.42%
>  	Totals:	159,050	100.00%
> ## If we launch & start rewards September 17
> Gnosis & Optimism notify reward bots will be the same with:
> 
> Gnosis & OP	 	 	 
> Round Number	Start Date	GIV per round	% of total
> Round 1	September 17	299,220	24.63%
> Round 2	October 1	302,046	24.86%
> Round 3	October 15	305,277	25.12%
> Round 4	October 29	308,507	25.39%
>  	Totals	1,215,050	100.00%
> Polygon zkEVM	 	 	 
> Round 11	September 17	31,497	24.63%
> Round 12	October 1	31,794	24.86%
> Round 13	October 15	32,134	25.12%
> Round 14	October 29	32,474	25.39%
>  	Totals	127,900	100.00%
> One question/concern I have is regarding the balance we assign to the unipool distributor on each chain... we'll be removing some allocation from Gnosis and OP... so I guess we should just discount that the next time we assign a new balance for reward extensions? or can we reduce the amount of GIV the gnosis & OP unipools can spend from the token distros?
> 
> In the case of zkEVM, we'll need to make sure we assign a balance to the polygon zkevm unipool to distirbute the right amount of tokens.
> 
> Also, would appreciate it if someone checked my math/my work here on the calculations. I think it's correct, but a second opinion is always nice.
> 
> cc @aminlatifi

Yes we can stop the old notify reward script and execute new ones, so once we decide about the launch time I will implement it with these given data

**Comment by mohammadranjbarz** [comment]
> other

@laurenluz  I checked the numbers and seems ok

**Comment by mohammadranjbarz** [comment]
@aminlatifi I deployed this script, added the run scripts to crontab jobs, changed the distribution reward of unipool smart contract, can you review them?

**Comment by aminlatifi** [comment]
> @aminlatifi I deployed this script, added the run scripts to crontab jobs, changed the distribution reward of unipool smart contract, can you review them?

@mohammadranjbarz The script doesn't run on the server, can you take a look?

**Comment by aminlatifi** [comment]
> > @aminlatifi I deployed this script, added the run scripts to crontab jobs, changed the distribution reward of unipool smart contract, can you review them?
> 
> @mohammadranjbarz The script doesn't run on the server, can you take a look?

It's fine now. Thanks @mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
Remaining things are:
* Assign balance
* Send GIV token to tokenDistro

**Comment by laurenluz** [comment]
@divine-comedian is on it for both accounts!
