### ISSUE TITLE
Add GIVpower staking card to GIVfarm page for polygon zkEVM

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4435]

**Comment by maryjaf** [comment]
zkEVM isn't shown in list of networks in below box in GIVfarm, GIVback,  GIVstream page 

![image](https://github.com/user-attachments/assets/3afb5a9c-8172-4fb5-a5c0-7b718446d737)

**Comment by maryjaf** [comment]
> * zkEVM isn't shown in list of networks in below box in GIVfarm, GIVback,  GIVstream page

Thanks @mohammadranjbarz,  This problem has been fixed on GIVfarm and GIVstream page. 

for GIVback, available networks are Gnosis and OP Sepolia
![image](https://github.com/user-attachments/assets/b802d66c-0494-4dcd-8357-965915e1580e)

**Comment by maryjaf** [comment]
- [ ] Is there a way to check the unlock scenario sooner than 3 Sep ? @mohammadranjbarz 

![image](https://github.com/user-attachments/assets/d68b9a0e-03de-48ea-b3ae-af5550f6ce72)

**Comment by maryjaf** [comment]
- [ ] By tapping on "Bridge your GIV" this link is shown (https://bridge.connext.network/GIVETH-from-ethereum-to-optimism), the correct link should be replaced 
@divine-comedian @mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
> * [ ]  By tapping on "Bridge your GIV" this link is shown (https://bridge.connext.network/GIVETH-from-ethereum-to-optimism), the correct link should be replaced
>   @divine-comedian @mohammadranjbarz

@laurenluz Can you help us?

**Comment by laurenluz** [comment]
I think we should add something to our docs that is a new section about bridging GIV and explains how to do it on all chains. I asked @WhyldWanderer to create some docs for this, maybe she can make something quick and put it up... and then we can use the link in here for all chains.

**Comment by WhyldWanderer** [comment]
I have added some info to the docs but Lauren and I were talking about it and we think the best place to link to from the dApp is the GIV token Linktree here: https://linktr.ee/givtoken

cc. @mohammadranjbarz

**Comment by laurenluz** [comment]
yes! let's make "bridge your GIV" link to the linktree https://linktr.ee/givtoken for every chain the user is connect too (and when wallet is not connected)

@mohammadranjbarz can you do it?
