### ISSUE TITLE
Add Polygon zkEVM to "GIVbacks" chains on frontend (GIVbacks page)

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4437]

**Comment by laurenluz** [comment]
![Image](https://github.com/user-attachments/assets/6d92b554-63d7-4687-8c61-27a7a23d07ea)

**Comment by maryjaf** [comment]
![image](https://github.com/user-attachments/assets/f6828fea-1754-42da-8d36-49dc907c87aa)
