### ISSUE TITLE
Update GIVbacks documentation to include Polygon zkEVM

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4439]

**Comment by wmb81321** [comment]
We should include in that[ GIVbacks docs](https://docs.giveth.io/giveconomy/givbacks) will be available in Polygon ZKEVM too, right?

I think we can show with some logos (Optimism, Gnosis and PolygonZKEVM) for better understand for users.

The following section:
![Screenshot 2024-07-17 at 08 46 58](https://github.com/user-attachments/assets/92062c43-3cac-4cc6-8bf9-cef4e10c3804)

**Comment by laurenluz** [comment]
yeah - this issue is for updating the givbacks docs. I assigned you and ashley because I think either of you can do it, but this should be done after we build it, so it's blocked.
