### ISSUE TITLE
enabling autopilot for a test project on staging. 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#444]
Is there any chance that we can proceed with a test project to make sure what emails users receive on UAT?

**Comment by MoeNick** [comment]
Do you have any updates in this @Cotabe ?

**Comment by Cotabe** [comment]
Yes @MoeNick 

We can enable it any time. Just need to ask Mitch, Ahmad o someone with access to segment to enable it (super quick).

It usually is disable to prevent anything that could go wrong on staging from triggering a lot of emails
