### ISSUE TITLE
Add Endaoment Integration description component on project details page

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4447]
for projects that have been imported from Endaoment we should have a small component added on the page that allows us to insert a short description of what the Endaoment Integration is and how it works, we should also include the Endaoment org logo and a link to their website

There should be a header that says 

## This project is delivered by [Endaoment](https://endaoment.org/)

with a subtext 

> This project is delivered by Endaoment, which handles the conversion and delivery of fiat funding to this project. Endaoment charges a 1.5% fee on donations which is processed outside of the Giveth Dapp. 

## design 

![Project Details Endaoment](https://github.com/user-attachments/assets/ca4a656e-57e1-470d-bc8f-1c1021ed19cd)
https://www.figma.com/design/vMiyVd1Ly5LjgSyZrChVV8/Giveth-users?node-id=3027-16954&t=e9OIAhqaQKgvtYtO-1
@divine-comedian 

## test AC 

- [ ] when visting the project details page for an endaoment imported project the integration description appears in the correct locatoin
- [ ] projects not imported from endaoment do not show this component

**Comment by Tosinolawale** [comment]
![Project Details Endaoment](https://github.com/user-attachments/assets/72b09600-886a-45a1-ad57-e8a4e838b660)
https://www.figma.com/design/vMiyVd1Ly5LjgSyZrChVV8/Giveth-users?node-id=3027-16954&t=f782Uh7I0Ma3rcUl-1
@divine-comedian

**Comment by divine-comedian** [comment]
This looks good @Tosinolawale - my only suggestion is to move the Endaoment logo closer to the header text - since it is kind of lost out there on the right edge of the page.

**Comment by Tosinolawale** [comment]
![Project Details Endaoment](https://github.com/user-attachments/assets/ca4a656e-57e1-470d-bc8f-1c1021ed19cd)
https://www.figma.com/design/vMiyVd1Ly5LjgSyZrChVV8/Giveth-users?node-id=3027-16954&t=e9OIAhqaQKgvtYtO-1
@divine-comedian

**Comment by divine-comedian** [comment]
@mohammadranjbarz this should be ready for you to build

**Comment by divine-comedian** [comment]
@mohammadranjbarz what is the update on this issue?

**Comment by mohammadranjbarz** [comment]
@divine-comedian @LatifatAbdullahi  It's ready to test on staging

**Comment by LatifatAbdullahi** [comment]
@mohammadranjbarz 

 - when visting the project details page for an endaoment imported project the integration description appears in the correct locatoin - Pass
- projects not imported from endaoment do not show this component - Pass

This shows correctly on the project details page
![tr](https://github.com/user-attachments/assets/5ebc301a-9899-4bec-bb44-21eaaf449d0a)



However, it is missing on the donate page, here is the design, please take a look

![image](https://github.com/user-attachments/assets/fa325df0-5fab-4216-af1b-fa08c3716900)


An Endaoment project on stage

![ms](https://github.com/user-attachments/assets/fe7d4dc2-9cbd-4927-b2a7-6aed3317a448)

**Comment by mohammadranjbarz** [comment]
Thanks @LatifatAbdullahi nice catch, I pushed a commit, now it's on donate page and you can test it on staging
for instance : https://staging.giveth.io/donate/Safernet-Brasil

**Comment by LatifatAbdullahi** [comment]
@mohammadranjbarz @divine-comedian 

Test Update: **Pass**

![image](https://github.com/user-attachments/assets/6120d2a3-05e2-4b4e-a23a-56cc79f119db)


![image](https://github.com/user-attachments/assets/a25dbf80-ed87-42ed-8b40-c84891d7ef6c)


![image](https://github.com/user-attachments/assets/0362283e-9036-4bb0-9041-71ab2f49e822)
