### ISSUE TITLE
add hover tooltip to endaoment project card badge

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4448]
We should add a small hover tooltip to the endaoment project badge that can give users a bit more context about what this integration is about 

The tooltip text should contain 

> This project is delivered by [Endaoment](https://endaoment.org/), who handles the conversion and delivery of funds to this project.

![Image](https://github.com/user-attachments/assets/97230475-9a50-491e-a46d-4bd09e7d5fb8)

**Comment by divine-comedian** [comment]
@mohammadranjbarz what is the update on this issue?

**Comment by mohammadranjbarz** [comment]
@divine-comedian @LatifatAbdullahi  It's ready to test on staging

**Comment by LatifatAbdullahi** [comment]
@mohammadranjbarz @divine-comedian 

Test Update: Pass


<img width="890" alt="image" src="https://github.com/user-attachments/assets/0212cf46-e531-4e7f-93d3-59bbaa5139bf">
