### ISSUE TITLE
prevent users on OFAC list from donating to Endaoment projects

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4449]
Users who are on the OFAC list should not be allowed to donate to Endaoment projects from the Giveth FE. 

Endaoment will provide code snippets on how to use the TRM Endpoint which we can use to check on the front-end, here it is: 
https://github.com/pedroyan/trm-sanctions-demo

If a project is detected on this list we should give them a modal warning that prevents them from proceeding in making a donation and can redirect them to the all-projects page

## Flow

1. User navigates to donate page for Endaoment project
2. Perform check if the connected address is on sanctions list 
3. If true, show pop-up modal with the following attributes: 
  a. Has header and description text (will provide below)
  b. Cannot be closed while the sanctioned wallet is connected to dapp, user must disconnect from app, switch wallet or leave the page
  c. modal contains button to take user back to all-projects page 
4. If false, user continues as normal making their donation

### Header:
> Sanctioned Address Detected

### text: 

> This address has been found on the USA [OFAC](https://ofac.treasury.gov/) sanctions list. Unfortunately, Endaoment does not permit addresses on the OFAC sanction list to donate to projects delivered by Endaoment. Check out another project to donate to.

### button text: 

> View All Projects

---

@mohammadranjbarz - please check out the code snippet above and get familiar with it.

@Tosinolawale - can we draft up this modal that we need to implement?

**Comment by Tosinolawale** [comment]
![Info](https://github.com/user-attachments/assets/691a7f41-9a6c-405a-af6b-718bc9ec5c56)
https://www.figma.com/design/vMiyVd1Ly5LjgSyZrChVV8/Giveth-users?node-id=3045-18067&t=zPs9vK4X84dt5xPk-1
@divine-comedian

**Comment by Tosinolawale** [comment]
> We'll have to see but I think it is very quick - I hope we can implement this feature with just 1 modal and a loading spinner if necessary. 90% of donors I think will never need to see this modal - the words OFAC, sanctions etc... are just bad vibes.

![Info](https://github.com/user-attachments/assets/9107aebc-bdb3-4323-82f9-968da4b77443)
https://www.figma.com/design/vMiyVd1Ly5LjgSyZrChVV8/Giveth-users?node-id=3045-18067&t=8AgZPV0S7EDbd1da-1
we can just have this then and have the loading state in the background

**Comment by divine-comedian** [comment]
@mohammadranjbarz - the design is ready for you to pickup once you got a good grasp on integrating the above mentioned TRM endpoint for checking addresses

**Comment by divine-comedian** [comment]
Can wrap an endpoint in our back-end so the FE only needs to communicate with our back-end and not another service.

**Comment by mohammadranjbarz** [comment]
> Can wrap an endpoint in our back-end so the FE only needs to communicate with our back-end and not another service.

I didn't do that because their webservice has rate limit, so if we call all requests from our server will get `429` error but if we call it from client side would not get that error, but once we get the apiKey from them in future we can do it (and also not implementing BE side was faster)

**Comment by LatifatAbdullahi** [comment]
@mohammadranjbarz @divine-comedian 


Test Update

- The modal has header and description text (will provide below) - Pass
- The modal cannot be closed while the sanctioned wallet is connected to dapp, user must disconnect from app, switch wallet or leave the page - Pass
- modal contains button to take user back to all-projects page - Pass



![image](https://github.com/user-attachments/assets/9726d553-fbf4-4181-a1d8-753c7905043c)



https://github.com/user-attachments/assets/3c8801df-625c-4e0f-b81f-98cab5ee2c9e

**Comment by divine-comedian** [comment]
@mohammadranjbarz - are you trigger this on the FE when the user tries to click the donate button or is there a delay? 

Ideally we don't let the user get so far as to select tokens and click the donate button, as soon as we have an address connected to the dapp on this page we run the OFAC check and show the modal.

**Comment by divine-comedian** [comment]
@HrithikSampson - please tag @LatifatAbdullahi  to test one this is ready for QA on develop

**Comment by mohammadranjbarz** [comment]
> still waiting for PR review from @mohammadranjbarz @MohammadPCh or @jainkrati to move this issue to QA #4589

Thanks for reminding, I just reviewed right now

**Comment by LatifatAbdullahi** [comment]
@HrithikSampson @mohammadranjbarz 

Where should I test this fix? I can't test it staging, as I can make donations there.

**Comment by HrithikSampson** [comment]
Hi @LatifatAbdullahi ,

I forgot to mention that I had created this pull request for testing it

https://github.com/Giveth/giveth-dapps-v2/pull/4590

The preview link is here:

https://giveth-dapps-v2-git-test-issue-4449-dont-merge-givethio.vercel.app/

**Comment by LatifatAbdullahi** [comment]
@divine-comedian 

Here is the current behaviour

https://github.com/user-attachments/assets/4a751ed1-c333-409c-b682-9911b6fb1037

**Comment by HrithikSampson** [comment]
Hi @divine-comedian @LatifatAbdullahi ,
https://giveth-dapps-v2-git-dontmergebuttestissue4449-givethio.vercel.app/

I am not sure whether to do the above process in OneTime Donation or the Superfluid Donation which is appearing now  since the WrongNetworkModel is in OneTimeDonation Card but I think I was able to solve this issue but in the OneTime Donation Card. I can transfer the OneTime Donation Modal to the Superfluid Donation or should I keep it in OneTimeDonation Card. 

Previously Endaoment Projects only had OneTimeDonation Card.
<img width="1469" alt="Screenshot 2024-09-10 at 11 55 27 AM" src="https://github.com/user-attachments/assets/9d4ecd89-920f-42f7-af0c-436ce8974633">



> @divine-comedian
> 
> Here is the current behaviour
> 
>  Give.directly.to.for-good.projects.with.crypto.zero.fees.-.Google.Chrome.2024-09-04.09-29-39.mp4

**Comment by divine-comedian** [comment]
I pushed a hotfix for this on production - you can copy the same 
https://github.com/Giveth/giveth-dapps-v2/pull/4710

**Comment by divine-comedian** [comment]
@HrithikSampson if the testing PR you made is ready and with the latest changes we made can we mark this as ready for test? Please assign @LatifatAbdullahi if it is ready to go.

**Comment by HrithikSampson** [comment]
@LatifatAbdullahi @divine-comedian ,Testing PR has been made. The preview link is this : https://giveth-dapps-v2-git-dontmergebuttestissue4449-givethio.vercel.app/

I was just waiting for https://github.com/Giveth/giveth-dapps-v2/pull/4711 to be approved

**Comment by LatifatAbdullahi** [comment]
@divine-comedian 

This is the current behavior

https://github.com/user-attachments/assets/538a1841-6a39-42b1-97b7-c98041051be0

**Comment by HrithikSampson** [comment]
Thanks @LatifatAbdullahi , I will try to fix this glitching.

**Comment by HrithikSampson** [comment]
@LatifatAbdullahi ,I still have to get review for my PR.
I think I have fixed it in this preview link
https://giveth-dapps-v2-git-dontmergebuttestissue4449-givethio.vercel.app/

**Comment by LatifatAbdullahi** [comment]
@HrithikSampson @HrithikSampson 


This issue seems fixed

https://github.com/user-attachments/assets/d2617566-c14c-4bb7-9882-5d156b75af01
