### ISSUE TITLE
When an error  occurs in QF eligibility check flow, this error is shown repeatedly 

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#4453]
When an error  occurs in QF eligibility check flow, this error is shown repeatedly, please take a look on below screen record 
I expect by closing this modal and opening it again I could be able to recheck the QF eligibility 

https://github.com/user-attachments/assets/f45aab03-b356-414c-8ddb-b5bfb4e77821

cc: @Meriem-B

**Comment by maryjaf** [comment]
I appreciate it when the reported bug is ready for testing, tag me on issue or add me into assignees

One question , Since  the error in this flow doesn't happen always , do you have an idea for testing this ?
Can we create conditions for this error to occur? @Meriem-BM

**Comment by Meriem-BM** [comment]
> I appreciate it when the reported bug is ready for testing, tag me on issue or add me into assignees
> 

Sure, will do.

> One question , Since the error in this flow doesn't happen all the time, , do you have an idea for testing this ? Can we create conditions for this error to occur? @Meriem-BM

I'll DM you once I merge a temporary change to staging so you can test this case.

**Comment by maryjaf** [comment]
Thanks @Meriem-BM 
This problem has been fixed 

https://github.com/user-attachments/assets/ea23d028-1b82-47c9-b4ff-c606182c5295
