### ISSUE TITLE
Giveth's project banner not showing on project card

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4461]
PRODUCTION
brave browser
ubuntu 
metamask

when on the all projects page on production I noticed that the project card does not show the banner of certain Giveth-related projects including: 

- Giveth community
- Giveth matching pool
- Giveth House 
- Commons Stack

however when you load the project details page then it does load the image correctly. What could be the correlation between these projects? other project banners appear to load correctly.. 

https://github.com/user-attachments/assets/89a6c983-3ce1-4181-8be8-926b559d5992

@geleeroyale @mateodaza - could you guys investigate? I can't tell if this originate from  FE issue or IPFS or.. who knows..

**Comment by mateodaza** [comment]
@divine-comedian brave ubuntu GIVing you a bad time - sadly can't replicate. Is there a chance to update browser / delete cache ? Just an idea to reduce the scope

**Comment by divine-comedian** [comment]
looks like its back already! very weird, maybe it was a temporary outage or my browser got an update. Closing this one! 

![image](https://github.com/user-attachments/assets/793ad950-4ea7-4dc0-aa57-74285b2b9810)
