### ISSUE TITLE
Update QF round banner for the GIV-ARB round

### ISSUE THREAD

**Issue by koday1** [Giveth/giveth-dapps-v2#4462]
The GIV-ARB QF round will start on July 30 and we will need to get the site banner updated for this round.

Figma link: https://www.figma.com/design/W9Ace1RyCdykWM72fsSa3t/Giveth-Marketing-2024?node-id=7209-2684&t=ARZr3QLPJfUBIxHa-4

**Comment by koday1** [comment]
Updated Figma link: https://www.figma.com/design/W9Ace1RyCdykWM72fsSa3t/Giveth-Marketing-2024?node-id=7209-2684&t=ARZr3QLPJfUBIxHa-4

The banner should look like this: 
![image](https://github.com/user-attachments/assets/81a7e97a-c4e8-418c-a2ad-0279360c449b)

@Meriem-BM are you able to take this one?

**Comment by Meriem-BM** [comment]
This is on staging and prod, you can check it @maryjaf, @koday1

**Comment by koday1** [comment]
@Meriem-BM I just checked and I don't see it live yet on giveth.io/qf, I still see no active round. Do I just need to wait a little longer? cc @maryjaf

**Comment by koday1** [comment]
However it does look good on staging @Meriem-BM :)

**Comment by koday1** [comment]
We're live at Giveth.io/qf - GIV-ARB round is a go! Thanks @Meriem-BM
