### ISSUE TITLE
New "Permit" toggle - Tx fails when Permit selected

### ISSUE THREAD

**Issue by Danibelle** [Giveth/giveth-dapps-v2#4463]
There's a new toggle in town, and the Permit feature causes failed transactions.

https://www.loom.com/share/452fe7887a784d858ed6a8964b4eb6c8?sid=43e9f89a-d59d-4eef-adec-799173ea5d06

Chrome browser on laptop with Metamask extension

**Comment by divine-comedian** [comment]
@MohammadPCh can you confirm I think we fixed this in an older issue..

**Comment by MohammadPCh** [comment]
@divine-comedian Yeah, It has been fixed.
