### ISSUE TITLE
Multisig | Not detecting connection from Safe

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4483]
Firefox
Ubuntu 22.04
MM

While trying to connect to the Giveth app from my multisig, using the Giveth native app it is not detecting that I am connecting from the Safe App and is stuck connecting to the app with my MM wallet. It should be detecting the Multisig and connecting to the app from that other address. 

![Image](https://github.com/user-attachments/assets/91a7bb11-7600-4aaf-9ada-72d23c7e1226)

---

While testing this on Brave using a different multisig I can see there is a massive pile of errors in the console, while I was able to successfully complete the multisig sign-in could these errors be related to some of the user errors occurring still? 

![Image](https://github.com/user-attachments/assets/2cf937bd-1acf-40a6-8349-fbb5ebea433f)
![Image](https://github.com/user-attachments/assets/f1e491a1-90d1-4a86-8632-abad76555ef3)

---

I noticed I can sometimes get to the multisig if while the app is connected to my MM signer I click Sign Out - then it will connect to the Multisig instead of my MM EOA

**Comment by mateodaza** [comment]
If you are inside the Safe ENV you shouldn't be able to sign out manually 

I did some improvements on the session here on this [PR](https://github.com/Giveth/giveth-dapps-v2/pull/4496/files), so maybe let's test again there once it's merged

**Comment by jainkrati** [comment]
@maryjaf please confirm if this is happening still

**Comment by maryjaf** [comment]
> If you are inside the Safe enb you shouldn't be able to sign out manually
> 
> I did some improvements on the session here on this [PR](https://github.com/Giveth/giveth-dapps-v2/pull/4496/files), so maybe let's test again there once it's merged
> 
> PS: all other red errors come from the safe env, it's annoying I know

Since we should test on stg, is the changes merged on staging? @mateodaza

**Comment by mateodaza** [comment]
@maryjaf @divine-comedian for some reason the safe connector was removed on staging
adding it back in this [PR](https://github.com/Giveth/giveth-dapps-v2/pull/4720)

You should be able to test again

**Comment by divine-comedian** [comment]
> @maryjaf @divine-comedian for some reason the safe connector was removed on staging adding it back in this [PR](https://github.com/Giveth/giveth-dapps-v2/pull/4720)
> 
> You should be able to test again

OOOOH yes in this issue #4152 that was my bad 

I think it was causing confusion because people were coming to Giveth not through the safe app and trying to connect their multisigs through that option

**Comment by maryjaf** [comment]
> > If you are inside the Safe enb you shouldn't be able to sign out manually
> > I did some improvements on the session here on this [PR](https://github.com/Giveth/giveth-dapps-v2/pull/4496/files), so maybe let's test again there once it's merged
> > PS: all other red errors come from the safe env, it's annoying I know
> 
> Since we should test on stg, is the changes merged on staging? @mateodaza
> 
> I tested on stg and haven't seen any change, my safe account isn't detected
> 
>  Screen.Recording.2024-09-09.at.10.47.20.AM.mov

Thanks @mateodaza It has been fixed on staging

**Comment by divine-comedian** [comment]
I think we should try to apply as a hotfix if we are able to without pushing any unwanted changes

**Comment by mateodaza** [comment]
@maryjaf @divine-comedian merge here in this [PR](https://github.com/Giveth/giveth-dapps-v2/pull/4725)

**Comment by maryjaf** [comment]
Thanks @mateodaza It has been fixed on prod.
