### ISSUE TITLE
User reported - cannot add github repo to project

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#4484]
A user sent an email showing me that they are unable to add a github repo to their project description.

![image](https://github.com/user-attachments/assets/d23d0ef9-5d8b-43e5-a07b-d7bdcd7795ff)

According to the Tech Leads document in Notion, I think @MohammadPCh is the right person to tag here?
Thanks!

**Comment by MohammadPCh** [comment]
@WhyldWanderer Thanks for reporting it. @kkatusic can you take it?

**Comment by maryjaf** [comment]
Thanks @kkatusic it has been fixed

![image](https://github.com/user-attachments/assets/124a98cd-2488-417e-8c93-a70bc3a49d08)

**Comment by kkatusic** [comment]
@WhyldWanderer can you close this? thx
