### ISSUE TITLE
Add logo for BitCone token

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#4486]
I have added this token to the list on Polygon but I am unable to add the logo.

Here is the link to the logo: https://assets.coingecko.com/coins/images/32278/standard/BitCone_Logo_V7.5_halo_NO_circle_-200x200_copy_BIGGER.png?1697180757

Token address: 0xbA777aE3a3C91fCD83EF85bfe65410592Bdd0f7c

According to the Tech Leads doc in notion, I assume that @MohammadPCh is the lead to tag on this issue but I may be wrong

**Comment by MohammadPCh** [comment]
@WhyldWanderer Thanks for letting us know, @lovelgeorge99 can you take it?

**Comment by maryjaf** [comment]
I haven't seen this token in polygon token list on stg and prod to check the logo

**Comment by WhyldWanderer** [comment]
@maryjaf is this helpful?
![image](https://github.com/user-attachments/assets/6f94cef9-909e-471d-9256-8fe2947f6de3)

**Comment by maryjaf** [comment]
Thanks @WhyldWanderer I meant in list of tokens in donation page 

https://github.com/user-attachments/assets/bc6ce543-1c73-4493-9a5b-b980770413f0

**Comment by lovelgeorge99** [comment]
> @maryjaf is this helpful? ![image](https://private-user-images.githubusercontent.com/74267818/354218376-6f94cef9-909e-471d-9256-8fe2947f6de3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MzE3NTYsIm5iZiI6MTcyMjUzMTQ1NiwicGF0aCI6Ii83NDI2NzgxOC8zNTQyMTgzNzYtNmY5NGNlZjktOTA5ZS00NzFkLTkyNTYtOGZlMjk0N2Y2ZGUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDE2NTczNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0NzA2MDljZDA2NTQ2ZDI4NTNhMGI5MGRlMTZiMTMzZGIxYWY3OWZkOGYzNDllYmYwMDkwYTdlZDRkNDgyNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dEevffpc76oOXTs9KYmMqJIyfJgcaHglwuLmwxwp1Ag)

Hu, did you add this token in staging impact graph  or production impact graph?

**Comment by WhyldWanderer** [comment]
I added the token on production.

I can see it in the drop-down list on Polygon here:
![image](https://github.com/user-attachments/assets/d6c28954-a302-4771-a100-5c97d3309938)

@maryjaf @lovelgeorge99

**Comment by lovelgeorge99** [comment]
@maryjaf  can you add this token in the staging impact graph and then check the token list?..it should work then in staging too

**Comment by maryjaf** [comment]
Thanks @lovelgeorge99 
![image](https://github.com/user-attachments/assets/5ed245f5-21fe-4e4b-9766-0da308064692)
