### ISSUE TITLE
Problem on donation page on solana 

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#4498]
**Describe the bug**

- [ ] when my network is set on solana, I can't enter the amount lower than 0.001 in donation page ,  like as below screen record 

https://github.com/user-attachments/assets/80d94572-ab4e-48b2-8f50-02449e34d2d5

This problem doesn't exist for example on Gnosis
![image](https://github.com/user-attachments/assets/7a40859a-0fb8-498d-98fd-3189606b7070)

cc: @divine-comedian @MohammadPCh

**Comment by laurenluz** [comment]
@maryjaf can you test again?

**Comment by maryjaf** [comment]
Thanks @MohammadPCh it has been fixed.
