### ISSUE TITLE
bug in showing list of tokens in donation page

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#4499]
**Describe the bug**

- [x] when I switch my network for example from Gnosis to polygon the token symbol on donation page isn't updated

- [x] when my network is set on solana, by changing the network into ethereum, the token symbol on donation page isn't updated
Or vice versa when I switch from ethereum to Solana

https://github.com/user-attachments/assets/66e2ddfe-cc3e-4d1d-8946-88c9061574a9

cc: @divine-comedian @MohammadPCh

**Comment by laurenluz** [comment]
@maryjaf can you test again?

**Comment by maryjaf** [comment]
Thanks @MohammadPCh this problem has been fixed
