### ISSUE TITLE
My Account | Projects

### ISSUE THREAD

**Issue by mateodaza** [Giveth/giveth-dapps-v2#45]
@MoeNick commented on [Mon Jan 17 2022](https://github.com/Giveth/giveth-io-typescript/issues/71)

As a Project Owner, I would love to see all of my donations and their status on a list. 

# Design resources

- [My projects tab](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=3898%3A104982)

_Note: for the current state, we only have the sorting on the table, we will add the Filters in the next sprint_

**Comment by MoeNick** [comment]
QA of my project is here: https://github.com/Giveth/giveth-dapps-v2/issues/44#issuecomment-1048708605

**Comment by MoeNick** [comment]
@CarlosQ96 @mateodaza 

I make one of my project deactivae, but it totally get disappeared from my projects in my account, 
https://github.com/Giveth/giveth-dapps-v2/issues/44#issuecomment-1048708605
I have to see it but as not active like below:
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/952eb87d-efe8-4ed5-a428-5ee34cff9642)

**Comment by CarlosQ96** [comment]
Fixed on backend, Mateo will be using new query.
