### ISSUE TITLE
There are some bugs in showing token list and balance in donation page 

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#4503]
**Describe the bug**

- [x] The available balance shouldn't be shown, when no token is selected

- [x] The "Donate " button is disabled when user first taps on available balance and then select token

https://github.com/user-attachments/assets/d0d57f7b-fed1-4536-8209-be5547aae178

**Comment by MohammadPCh** [comment]
@maryjaf can you check it on [production](https://giveth.io/)?

**Comment by maryjaf** [comment]
The problem related to resetting amount in the box by switch network that we discussed about it, hasn't been fixed and makes a problem about donate button 

Uploading Screen Recording 2024-07-30 at 3.02.12 PM.mov…

**Comment by maryjaf** [comment]
https://github.com/user-attachments/assets/1ce9df66-3e9a-4ce5-8d17-8ba8077be2b0

**Comment by divine-comedian** [comment]
@maryjaf could you take another look at this issue - is it fixed?

**Comment by maryjaf** [comment]
In the new design of donation page these problems have been fixed
