### ISSUE TITLE
Some times "recheck eligibility" button is shown immedietly after tapping on "check eligibility""

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#4508]
- [ ] I see this the below behavior for a user after sign on staging

-by tapping on "check eligibility" nothing happens and then the "recheck eligibility "  button is shown

https://github.com/user-attachments/assets/7c9bd9ef-2198-4d0f-b852-29f3a3551b57

@Meriem-BM

_Originally posted by @maryjaf in https://github.com/Giveth/giveth-dapps-v2/issues/4247#issuecomment-2256453729_

**Comment by maryjaf** [comment]
-It also happens for some old users on production

https://github.com/user-attachments/assets/c5c67b60-a98f-431a-9a03-32f77b56fdac

cc: @laurenluz

**Comment by Meriem-BM** [comment]
Hey @maryjaf I was thinking about this, I believe this is normal for some users that already have their Gitcoin account connected, so it skips the `add more info` step because his Gitcoin is already connected, and his score it.

cc: @laurenluz

**Comment by laurenluz** [comment]
That sounds ok to me!!
