### ISSUE TITLE
QF project card is not being shown on projects in an active QF round from the "bookmarked projects" view

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4512]
Even in My account --> Bookmarked projects , we should show the QF project card a project active in QF

![image](https://github.com/user-attachments/assets/f535d2eb-7434-4cdb-b889-6f49bf94538f)

@jainkrati not sure who to assign w/ Carlos on vacation. this is a small and not critical bug.

cc @MoeNick @koday1

**Comment by koday1** [comment]
@jainkrati I just DM'd you on Discord, but let me know if you're able to assign this issue while Carlos is out. Thanks in advance

**Comment by jainkrati** [comment]
@MohammadPCh could you or @kkatusic deliver this soon ?

**Comment by kkatusic** [comment]
@laurenluz, cc @jainkrati, you wan't to QF flag be added like on this example:

![flag](https://github.com/user-attachments/assets/ac4c8f79-fb0d-46f5-bbbc-b5a56ad5aebd)

**Comment by koday1** [comment]
Hey @kkatusic yeah that's the one. In this case the active round is the GIV-ARB round, so there should be a tag on all the projects (69 as of today) that says 'GIV-ARB', like the format you highlighted above

**Comment by kkatusic** [comment]
Thx @koday1, this is from test view, I will push changes to backend, when someone applied that I will let you know.

**Comment by koday1** [comment]
@kkatusic Sounds good! Thank you for working on this

**Comment by MohammadPCh** [comment]
Thanks @kkatusic

**Comment by maryjaf** [comment]
It hasn't been fixed @kkatusic [this project](https://staging.giveth.io/project/how-many-photos-is-too-many-photos) is in the current round but in bookmark list the QF tag isn't shown

![image](https://github.com/user-attachments/assets/b5c086de-31e8-45dd-972b-065c69c05879)

**Comment by kkatusic** [comment]
@maryjaf this fix is on backend, we need to wait to PR be merged and than we can test: https://github.com/Giveth/impact-graph/pull/1745

**Comment by maryjaf** [comment]
> @maryjaf this fix is on backend, we need to wait to PR be merged and than we can test: [Giveth/impact-graph#1745](https://github.com/Giveth/impact-graph/pull/1745)

Thanks @kkatusic 
Since  the assumption is that the issues in the QA state are ready for testing, after merging and when the issue could be tested, move it to QA

**Comment by kkatusic** [comment]
@maryjaf when you get time please can you test it again? thx

**Comment by maryjaf** [comment]
> [this project](https://staging.giveth.io/project/how-many-photos-is-too-many-photos) is in the current round but in bookmark list the QF tag isn't shown
> 
> ![image](https://private-user-images.githubusercontent.com/111529185/355002031-b5c086de-31e8-45dd-972b-065c69c05879.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNzk3MjgsIm5iZiI6MTcyMzM3OTQyOCwicGF0aCI6Ii8xMTE1MjkxODUvMzU1MDAyMDMxLWI1YzA4NmRlLTMxZTgtNDVkZC05NzJiLTA2NWM2OWMwNTg3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMVQxMjMwMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NDZkOGFlZmVhNDAyM2YzOTllYzRkNmM4N2NmYzk0NjlkM2FkYjU1MjdiNjllNTE0NDAwMTFjNmRiZmUxNTA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RkQizEmsCm_FHEDIzOoHwFK7hRGLlgsSXjgTXER8lpU)

It seems it hasn't been fixed, I still see above pic on staging and there is no QF badge in "bookmarked projects"  tab

**Comment by koday1** [comment]
Thanks @maryjaf @kkatusic :) 

Closing this issue
