### ISSUE TITLE
Minified React Errors on Production

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4514]
We are getting some minified react errors on prod 
![image](https://github.com/user-attachments/assets/1cec1933-c3ea-4e58-915d-a1d015262985)

@MohammadPCh mentioned that @geleeroyale & devOps team might need to upgrade connections to https to remove these erros.

_Originally posted by @divine-comedian in https://github.com/Giveth/giveth-dapps-v2/issues/4375#issuecomment-2258504595_

**Comment by geleeroyale** [comment]
Hey @divine-comedian - react is part of the frontend stack. While I really miss hacking away on react stuff it's not really within the realm of DevOps.

Also @MohammadPCh mentioned the problem was temporary for him and he could not reproduce it again.

**Comment by divine-comedian** [comment]
just found it again, right on homepage load - so let's get to the bottom of it! @MohammadPCh 
![image](https://github.com/user-attachments/assets/2bb769d8-96b2-4b49-98cd-46aea05cff82)

**Comment by MohammadPCh** [comment]
Thanks @divine-comedian 
@lovelgeorge99 can you take this? Thanks

**Comment by lovelgeorge99** [comment]
@divine-comedian i tried to reproduce this in error but could'nt get it.
Are there any steps that i should do to reproduce these?

**Comment by divine-comedian** [comment]
Weird, it isn't reproducing anymore for me either - let's close this issue for now..
