### ISSUE TITLE
WC Testing: Chrome Desktop | Trust Wallet DESKTOP

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4515]
The following test cases should be completed and successful:

- [x] - Sign in
- [x] - Switch Network (from navbar dropdown menu)
- [x] - Switch Network (from givfarm)
- [x] - Connect Wallet(from GIVfarm/GIVback)
- [x] - Connect Wallet and sign in (from passport banner)
- [x] - Switch network (from donate page)
- [x] - Donate ERC20
- [x] - Donate native token
- [x] - Stake GIV
- [x] - Lock GIV
- [x] - Unstake GIV
- [x] - Harvest rewards (GIVfarm)
- [x] - claim GIVbacks 
- [x] - claim GIVstream
- [x] Connect with Multisig
- [x] Create recurring donation
- [x] modify recurring donation
- [x] deposit/withdraw from stream balance 
- [x] end recurring donation

**Comment by maryjaf** [comment]
- [ ] I got on error when I try to sign with solana on "desktop browse | Trust wallet desktop"  (staging and prod)
@divine-comedian 

https://github.com/user-attachments/assets/a18618f3-2084-44b5-bdbd-a2e5615f0819

**Comment by divine-comedian** [comment]
Thanks MJ - After some consideration let's remove Solana connections as a requirement for this feature, if everything else is approved let's move it to done.

**Comment by kkatusic** [comment]
@maryjaf I can't see Solana request inside test cases?

**Comment by maryjaf** [comment]
> * I got on error when I try to sign with solana on "desktop browse | Trust wallet desktop"  (staging and prod)

In this scenario I installed trust extension on my chrome

**Comment by kkatusic** [comment]
Thx @maryjaf, cc @divine-comedian, this has been now reported to creator of this sign in function: https://github.com/Web3Auth/sign-in-with-solana/issues/34

**Comment by divine-comedian** [comment]
@maryjaf - FYI we removed requirements regarding Solana donations - if you can confirm all EVM related test cases are passed we can move to done
