### ISSUE TITLE
New Categories Specifications

### ISSUE THREAD

**Issue by mosaeedi** [Giveth/giveth-dapps-v2#452]
We need to show categories as a submenu, under Projects. but we need to pick up to 7 main categories to make it easier for users to find the thing they are looking for and not make a really long list of categories.
_Note: over than 9, is not UX-friendly at all!_

So here are my suggestions,

**Main categories:**

- Environment & Energy
- Finance &  Economy
- Health & Medical
- Technology & Education
- Non-profit
- Art & Culture

### Each of these categories has these subcategories:
**Environment & Energy**: _Agriculture, Air, Climate, Energy, Land, Oceans, Pollution, Waste, Water_
**Finance &  Economy**: _Housing, Employment, Finance, Infrastructure, Reall state_
**Health & Medical**: _Food, Nutrition, Health_
**Technology & Education**: _Technology, Research, Education_
**Art & Culture**: Art & Culture, _Community, Inclusion, Biodiversity_

## ❓ Why is it important?
It's not UX-friendly at all to have a long list of categories as a sub-menu!

## 🤼‍ Reviewer

@laurenluz @MoeNick @markoprljic

**Comment by MoeNick** [comment]
> Sorry to join late in the conversation. Non-profit is not a cause, it is just a form of organization and any of the nonprofit can be from the categories above. Anyone had referenced a common cause category? Here are some that are missing that people may be searching (several wanted to search for women at Ethbarcelona): Conflict resolution, Disaster Relief, Human or Social Services, Animal Charities, Racial and Gender Equality and standard categories normally used are the following terms (so it can be compared when it comes to giving volumn with other traditional financing model) Arts & Culture Education Environment Health International Public Benefit Religion Social Services

@melodysongq thanks for the clarification, I have some points:
1- we have some imported projects from Givingblock and CHANGE network, which due to technical problems we can't have their specific categories so we just named them non-profits, in this case what we should do? do we need to remove the whole categories?

2- We have some specific non-profits working in different areas that came across the business side due to cooperation or partnership with giveth. 

3- there all current non-profit tags for lots of projects and @mohammadranjbarz can say the numbers more accurate, what to do with them?

**Comment by melodysongq** [comment]
@MoeNick  I think just from a project point of view, "nonprofit" is a confusing category.  If they are verified social goods project, they are all technically "nonprofit".  I suggest you replace it with a less used or less common term for those in a specific category (like imported from the Giving block etc.).     In general, we use NGO, NPO a lot just in regular speech to indicated organizations in the social sector in general definitely a confusing one for users (both project and donor).

**Comment by mosaeedi** [comment]
Thanks, @melodysongq for your suggestion, I just need to say that the whole idea for this task was rearranging current categories under some main categories to make it easier for users to create or find projects.
We can actually create new main categories and sub-categories if there is something missing and I'm sure we are missing some!

Since this issue was open for a very long and basically it achieve its goal I suggest we open a new one for optimizing and improving the categories and subcategories under the new structure.

But, I totally agree with the **nonprofit** term and I think we should change it with something better.

What do you guys think? we can start fresh on a new issue and discuss the categories and subcategories!
Also optimizing SEO should be another issue too.

**Comment by SnakeGH** [comment]
Hey guys, I know I am late to this but after reviewing and sorting through our projects lately, and since there are a lot of The Giving Block projects listed on our platform that require donations to be from mainnet, maybe its valuable to have a "sort by" mainnet vs gnosis chain category.
