### ISSUE TITLE
Make the qf banners float down the page as the user scrolls.

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4520]
You know how our menu bar floats down the page or reappears when you up scroll? I want the QF banner to do that!!

It would be great if this info & eligibility check stuff wasn't lost because the user scrolled down, you know?

@mosaeedi are you ok with this? if you give me an ok, I'll push it to dev.

This is our scrolly menu bar thing

https://github.com/user-attachments/assets/adbefec9-ab0c-48a5-b2e9-9e20b1665e00

**Comment by mosaeedi** [comment]
The QF banner is huge and if this banner reappears when user scrolls up, it will make it harder for user to focus on the project which is more important!
I can suggest creating a tiny mini banner to show that instead of the main banner with important info but in a condensed way to show users what we need to show and also not make it harder for them to focus on the project cards.

**Comment by laurenluz** [comment]
I'm talking just about the mini banner that says "you are eligible for QF" or "connect your passport". the banner we implemented for MBD & passport system @mosaeedi

**Comment by mosaeedi** [comment]
Oh!
That's okay, we can do that! 😀

**Comment by laurenluz** [comment]
yay!! ok! @MohammadPCh since you are leading frontend, can you assign the appropriate person?

**Comment by mosaeedi** [comment]
I don't think we need a design for it, we should just make it appear with the main navigation when the user scrolls up!

**Comment by MohammadPCh** [comment]
@maryjaf Is it suitable for you to start FE?

**Comment by maryjaf** [comment]
in all pages this banner should be float like below screen record? @laurenluz 

https://github.com/user-attachments/assets/6d65e35d-78d9-4cb3-b116-bfcd2b561c1b

**Comment by laurenluz** [comment]
just on QF-related pages!! so the regular QF page, donating to a QF project, success page after donating to a QF project. @maryjaf
