### ISSUE TITLE
Problem in harvest flow 

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#4527]
- [ ] When user completes harvest flow, the UI isn't updated and it takes some time , in this time user can taps again on harvest and see the previous  amount for harvest
please take a look on below screen record @MohammadPCh 

https://github.com/user-attachments/assets/73cec7e7-8ecd-459f-ad58-8f90d8194ecf

_Originally posted by @maryjaf in https://github.com/Giveth/giveth-dapps-v2/issues/4375#issuecomment-2260638420_
            
  cc: @divine-comedian @MohammadPCh

**Comment by divine-comedian** [comment]
Thanks @maryjaf - however this appears to be just a temporary slowness probably from subgraphs, RPC nodes or who knows, since this doesn't cause any major errors I don't think we will need to make any fixes...

**Comment by MohammadPCh** [comment]
@divine-comedian We need to charge the token distro to test this (I cannot harvest on staging now). Would it be possible for you to add some test tokens to it?

**Comment by divine-comedian** [comment]
optimism-sepolia token distro

**Comment by divine-comedian** [comment]
@MohammadPCh it appears that the tokenDistro is very full! 

https://sepolia-optimism.etherscan.io/address/0x301c739cf6bfb6b47a74878bdeb13f92f13ae5e7

you can see is has almost 1 billion test GIV tokens in it

it could be that the optimism sepolia farm has ended and another distribution needs to be setup for it @aminlatifi might be able to set that up

**Comment by aminlatifi** [comment]
I setup farm for another round of rewarding

**Comment by divine-comedian** [comment]
@MohammadPCh should be good to go now for testing and dev 
![image](https://github.com/user-attachments/assets/da1e5dcf-762e-4a19-8c5d-9b7e490fc9fb)

**Comment by maryjaf** [comment]
This problem has been fixed on staging
