### ISSUE TITLE
GIVpower unlock is not behaving as expected

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4529]
@RamRamez has tokens that should have been unlocked July 23, but are not yet. You can see the issue in this screenshot:

![image](https://github.com/user-attachments/assets/079b2f31-556d-4bc4-b8c1-6a9dd67e9532)

I remember we had a similar problem before with the unlock bot running out of gas... @aminlatifi or @mohammadranjbarz can you look into this and see what the problem is?

**Comment by geleeroyale** [comment]
The bot is stopped currently. Was it stopped manually by you @aminlatifi or did it crash? I saw a message from you about stopping it - so I want to ask before I investigate

**Comment by aminlatifi** [comment]
We started it again yesterday.
