### ISSUE TITLE
Update GIVbacks % icon in the "sort by" drop down

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4534]
We are using the lightning bolt, but should use the hand!

Right now it's:
![image](https://github.com/user-attachments/assets/a4f0db08-fbf4-4344-84a7-935c8974d679)

Should be:
![image](https://github.com/user-attachments/assets/38f0a22f-c0c1-4075-8ab5-5180730b05c0)

@mosaeedi can you link to figma?

**Comment by mosaeedi** [comment]
Here is the link to Figma -> [Figma Link](https://www.figma.com/design/Zjrx4AB4l5k9GzjjfLDIwR/Project-List?node-id=6116-13186&t=83xxFtzJ3GPJk67Y-4)

**Comment by RamRamez** [comment]
@HrithikSampson could you please take this issue?
cc @jainkrati

**Comment by HrithikSampson** [comment]
https://github.com/Giveth/giveth-dapps-v2/pull/4543

**Comment by maryjaf** [comment]
![image](https://github.com/user-attachments/assets/ae34df94-35b3-4521-abb6-64e7d31a85e9)
