### ISSUE TITLE
P0 - tried to donate ARB and the 5% to Giveth failed... out of Gas?

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#4537]
https://arbiscan.io/tx/0xa8a420ca94fa961333d652f8b0d77c0370f37fabf12a68162edf253d1e00330e

We can't let our donations to ourselves fail!

**Comment by RamRamez** [comment]
We don't suggest gas fees to wallets, and wallets use their defaults, so I believe either gas price went high suddenly or the wallet predicted a wrong amount for gas that caused tx to fail.

**Comment by maryjaf** [comment]
based on this new issue https://github.com/Giveth/giveth-dapps-v2/issues/3903#issuecomment-2271095735, transaction fee is deducted if user tries to donate/deposit max token balance
