### ISSUE TITLE
User donates lower than minimum usd value but in donation success page this message is shown "donation is eligible to be matched"

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#4539]
**Describe the bug**

User donates lower than minimum usd value but in donation success page this message is shown "donation is eligible to be matched"
- Imagine  my user is eligible for estimated matching
- The minimum value for donation is set 1 $ in admin bro for the round 
- When I donate lower than 1 $, in donation success page I see this box 

![image](https://github.com/user-attachments/assets/c4c876ed-8d97-4408-be72-c26f6812fc07)

https://github.com/user-attachments/assets/4f1a4c5f-aa6a-4608-8c94-789e2b5a1cee

cc: @laurenluz @koday1

**Comment by RamRamez** [comment]
@HrithikSampson could you please take this issue?
cc @jainkrati

**Comment by maryjaf** [comment]
Maybe some new design or copy is needed for this scenario .

**Comment by laurenluz** [comment]
Oh that's a good point @maryjaf. I think we can resolve this by changing the copy for both cases (qf eligible donor & not qf eligible donor) to be saying if the *donor* is eligible or not... and not mention the particular donation.

Scenario 1: The user is qf-eligible
Title: Quadratic Funding
Text: You are QF-eligible! As long as your donations are at least < minUSDvalue >, they are eligible to be matched in the round.

Scenario 2: The user is not qf-eligible (i.e. MBD not verified/checked, passport not verified/checked, passport score too low)
Title: Quadratic Funding
Text: Make sure you donations get matched! Verify your < qf eligibility > before < round end date >.

^^for this case, < qf eligibility > should link to https://giveth.io/account

@HrithikSampson - is that good enough for you? or do you need design?

**Comment by HrithikSampson** [comment]
That's a great explanation @laurenluz , I dont need a design for it.

**Comment by maryjaf** [comment]
> Scenario 2: The user is not qf-eligible (i.e. MBD not verified/checked, passport not verified/checked, passport score too low) Title: Quadratic Funding Text: Make sure your donations get matched! Verify your QF eligibility before < round end date >.
> 
> ^^for this case, Scenario 2, < QF eligibility > should have a hyperlink to https://giveth.io/account

You mean this current flow should be changed also ? @laurenluz 
![image](https://github.com/user-attachments/assets/83d10d5a-4bfe-452b-bbcd-5c6c38927853)
![image](https://github.com/user-attachments/assets/329c0b65-b5c7-4cb3-8fa8-cde89b61da1d)

**Comment by HrithikSampson** [comment]
Sorry, I misunderstood it.

I have initially implemented it wrongly.
I had considered Scenario 1 as the donation is more than the minimumValidUsdValue for the project and the Donor is QF eligible

For the case of Scenario 2 I had considered it when the Donor is QF eligible but has made a donation lesser than the minimumValidUsdValue for the project. The flow with QF Donor eligibility Modal I had kept the same as shown in the screenshot as shown above from @maryjaf.

Since I assumed the wrong scenarios, right now I was also wondering whether the current Flow will be changed. 

I was also thinking that a scenario could occur when the user is QF eligible but has donated lesser than the minimumValidUsdValue for the project.

@laurenluz I still have these doubts regarding the two scenarios?

**Comment by divine-comedian** [comment]
@laurenluz can you provide hrithik which scenario he should implement?

**Comment by laurenluz** [comment]
Hey @HrithikSampson - sorry for the delay here.

Scenario 1: The user is qf-eligible (doesn't matter the size of the donation)
Title: Quadratic Funding
Text: You are QF-eligible! As long as your donations are at least < minUSDvalue >, they are eligible to be matched in the < QF round name > round.
Button: Back to projects (which links to giveth.io/qf)
![image](https://github.com/user-attachments/assets/c65c3004-d2c0-4aea-a033-b2d4ad174be1)


Scenario 2: The user is not qf-eligible (i.e. MBD not verified/checked, passport not verified/checked, passport score too low) (doesn't matter the size of the donation)
Keep the flow that @maryjaf explained in her comment, but make a small copy chang:
Title: Don't miss out!
Copy: Donations above < minUSDvalue > are eligible to be matched with quadratic funding. Verify your QF Eligibility before < round end date > 
Button: "Check eligibility" leading to the modals & flow we currently have.
![image](https://github.com/user-attachments/assets/0b190f2c-9718-469d-96ba-df9dc5870eeb)

**Comment by HrithikSampson** [comment]
@maryjaf @LatifatAbdullahi , this issue is ready to be tested.

**Comment by maryjaf** [comment]
> Scenario 2: The user is not qf-eligible (i.e. MBD not verified/checked, passport not verified/checked, passport score too low) (doesn't matter the size of the donation)
> Keep the flow that @maryjaf explained in her comment, but make a small copy chang:
> Title: Don't miss out!
> Copy: Donations above < minUSDvalue > are eligible to be matched with quadratic funding. Verify your QF Eligibility before < round end date >
> Button: "Check eligibility" leading to the modals & flow we currently have.


User: not eligible 
Donation more than 0.001(the minimum amount for matching on stg)
success page:
![image](https://github.com/user-attachments/assets/2066f86e-b406-49db-a7ae-477ffb57baf0)
**Pass**
___
User: not eligible 
Donation lower than 0.001(the minimum amount for matching on stg)
success page:
![image](https://github.com/user-attachments/assets/d2c8a41e-fa3e-49d7-9729-08b6fa5e0f50)

**failed**, based on @laurenluz 's comment in this scenario thi success page should be like as first pic

__________

User: eligible 
Donation lower than 0.001(the minimum amount for matching on stg)
success page:
![image](https://github.com/user-attachments/assets/099e7970-3d08-4061-b9bf-f2d20dfcac71)

**failed** 

> Scenario 1: The user is qf-eligible (doesn't matter the size of the donation)
> Title: Quadratic Funding
> Text: You are QF-eligible! As long as your donations are at least < minUSDvalue >, they are eligible to be matched in the < QF round name > round.
> Button: Back to projects (which links to giveth.io/qf)


@HrithikSampson

**Comment by MohammadPCh** [comment]
@HrithikSampson Thanks for your great efforts
As we prepare to release the new version, if this issue fails during testing, we need to either fix it or revert the changes.
thanks.

**Comment by HrithikSampson** [comment]
@maryjaf ,this issue is ready to be tested

**Comment by maryjaf** [comment]
Thanks @HrithikSampson the problem has been fixed

Scenario 1: The user is qf-eligible (doesn't matter the size of the donation)
<img width="1404" alt="Screenshot 2024-10-08 at 11 38 52 AM" src="https://github.com/user-attachments/assets/56d0719b-c870-45eb-9f1e-10a6d61d4956">

Scenario 2: The user is not qf-eligible (i.e. MBD not verified/checked, passport not verified/checked, passport score too low) (doesn't matter the size of the donation)

<img width="1381" alt="Screenshot 2024-10-08 at 11 29 40 AM" src="https://github.com/user-attachments/assets/da192f5d-517c-4c3b-9f24-ee1dbb0d4c05">
