### ISSUE TITLE
Number of donations stat on QF page is not updating!

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4544]
I checked the stats at the top of https://giveth.io/qf/all for the GIV-ARB round, and it showed $7880 and 378 donations. then I made 3 or 4 donations, and saw this:
![image](https://github.com/user-attachments/assets/513d7bab-f847-4740-9a2f-b05324369d11)

Look, I'll do it again, I'm going to go donate $13

![image](https://github.com/user-attachments/assets/c3388732-3ecf-4b80-b0ee-6ccc0de20ce2)

See? that's not good.

We should be showing the number of donations, not the donors.. Is it showing the unique donor addresses by accident perhaps?

@MohammadPCh @RamRamez - can one of you try to fix this on prod? or assign the right person?

cc @maryjaf

**Comment by maryjaf** [comment]
Yeah # Of donations is shown the number of unique donors

**Comment by RamRamez** [comment]
@maryjaf @LatifatAbdullahi please test and verify on production

**Comment by maryjaf** [comment]
All donation should be counted? I mean for example donation with lower than minimum amount is also counted? @RamRamez

**Comment by laurenluz** [comment]
yes! all donations should be counted, including the ones with lower than min amount

**Comment by maryjaf** [comment]
The # of donation is updated as expected by adding new donation
