### ISSUE TITLE
Add GIV-Earth QF Round matching data to backend

### ISSUE THREAD

**Issue by koday1** [Giveth/giveth-dapps-v2#4547]
The GIV-Earth round has wrapped up, the snapshot vote for ratification passed and we have sent out all the matching funds. We need to add the matching data to the backend so that it accurately shows on project pages.

Txn link: https://celoscan.io/tx/0xe83f413038fc3d495b2bf584b7835a6c2c9063d9e59f448246260f883dc7d9e4

Spreadsheet with the data for the backend: https://docs.google.com/spreadsheets/d/1riqma8CS5TW1uUVPI_d9L4Zynbn0GfqrFpN8MBqPtD4/edit?usp=sharing

**Comment by divine-comedian** [comment]
@koday1 is this issue still relevant?

**Comment by koday1** [comment]
@divine-comedian nope this was completed, closing out
