### ISSUE TITLE
change copy in bookmarked projects tab when there is no bookmarked project 

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#4550]
The name of the "liked projects" tab was changed into "bookmarked project", but when there is no bookmarket project for a user the previous message is shown 
should it be changed? 
@divine-comedian 

![image](https://github.com/user-attachments/assets/7be21588-5739-459d-8146-ec8538f6d5bb)

**Comment by kkatusic** [comment]
@maryjaf this is merged and when you get time you can check ;)

**Comment by LatifatAbdullahi** [comment]
@maryjaf @kkatusic @divine-comedian 

Test Status: **Pass**



The Text when there are no "Bookmarked Projects" no shows **"You haven't bookmarked any project yet!"**


![image](https://github.com/user-attachments/assets/39588ae1-7308-444a-bd58-305ea1beef1e)
