### ISSUE TITLE
Add Endaomement Integration to project card on donation success page

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4552]
When a user makes a successful donation to a endaoment project we should change one of the components on the project card to display information about the endaoment integration. 

This component in the donation success page related to 100% of the donation goes the project isn't true for endaoment imported projects (endaoment charges a 1.5% fee). So we should replace this:
![Image](https://github.com/user-attachments/assets/fa868157-327a-4ded-a217-80bb86df7403)

and instead insert this endaoment integration text component as we have done on previous views, such as on the donate page.

![Image](https://github.com/user-attachments/assets/b9c25ca0-8a14-4379-9689-bb7e94e759cb)

Additionally on the donate page we should remove the same component as highlighted on the donation success page above 

## AC

- [ ] remove text component "100% goes the project always" on project card on donation page
- [ ] removed text component  "100% goes the project always" on project card on donation SUCCESS page
- [ ]  Endaoment Integration text component to top of project card on donation SUCCESS page
- [ ] non Endaoment projects still maintain text components "100% goes the project always" on donation & donation success page

**Comment by mohammadranjbarz** [comment]
@HrithikSampson  This is an Endaoment sample project https://staging.giveth.io/project/Safernet-Brasil
You can test your code with it (you can donate on **Optimism Sepholia** or **Base Sepholia** testnet chains, if you dont have toke on test chain you get it from faucets or ask me in DM I will give you some)

**PS** If you have any questions ask me here or in DM

**Comment by HrithikSampson** [comment]
@mohammadranjbarz @divine-comedian ,

I want to confirm once, are these the intended changes for this issue.

For an Endaoment Project, I have attached the screenshot for donation success Page below

screencapture-localhost-3000-donate-Safernet-Brasil-2024-08-13-09_59_20

For a non Endaoment Project, I have attached the screenshot for donation success page below

screencapture-localhost-3000-donate-teach-music-to-children-2024-08-13-10_03_01

Similarly I have attached the Donation Page for an Endoament and Non-Endaoment Project Respectively.

1-screencapture-localhost-3000-donate-Safernet-Brasil-2024-08-13-10_05_48
1-screencapture-localhost-3000-donate-teach-music-to-children-2024-08-13-10_06_18

**Comment by HrithikSampson** [comment]
Preview Link: https://vercel.com/givethio/giveth-dapps-v2/5HSy6SuL8TZaDrXB5waZX2CtxsCJ

**Comment by divine-comedian** [comment]
@HrithikSampson - please let us know when it is merged to staging for it to move to QA, we do not do testing on feature branches

**Comment by HrithikSampson** [comment]
Hi @LatifatAbdullahi , I have merged this branch to staging.

**Comment by LatifatAbdullahi** [comment]
@HrithikSampson  @divine-comedian 

Test Update


**To Endaoment Projects**

 remove text component "100% goes the project always" on project card on donation page - **Pass**
 removed text component "100% goes the project always" on project card on donation SUCCESS page - **Pass**
 Endaoment Integration text component to top of project card on donation SUCCESS page - **Pass**
 
 
 
![image](https://github.com/user-attachments/assets/9c8bcc43-5898-4142-be4a-cd7d39511985)

 
![goo](https://github.com/user-attachments/assets/42d1c510-436b-4c22-b8ed-209bff53ae33)


https://github.com/user-attachments/assets/4c83a08e-b6c4-47d9-b117-aace03bd2215





**To Non- Endaoment Projects**
 non Endaoment projects still maintain text components "100% goes the project always" on donation & donation success page - **Pass**
 
 
 
![myy](https://github.com/user-attachments/assets/a3830b82-4097-4b6a-abb5-bbb610f3c1f1)
![image](https://github.com/user-attachments/assets/88e8a954-7258-46bd-a540-715833932104)
