### ISSUE TITLE
Bug in showing passport banner

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#4553]
**Describe the bug**

when user isn't signed , this banner is shown: "there is no active round" although there is an active round 

![image](https://github.com/user-attachments/assets/c8d00df1-b401-4844-8789-831434988752)

**Expected result**

This banner should be shown

![image](https://github.com/user-attachments/assets/4afe5cea-9628-466b-a131-73b959b6be53)

cc: @Meriem-B @mohammadranjbarz

**Comment by maryjaf** [comment]
When I complete sign flow and then tap on sign out , the correct banner is shown

![image](https://github.com/user-attachments/assets/e4cc30aa-4d89-456a-befa-e452183b0e61)

**Comment by kkatusic** [comment]
@maryjaf I can't reproduce this error, deleted all cache/storage/cookies variables, tried on staging, production and on main branch. Also tried all option in several browsers and their incognito mode.

**Comment by maryjaf** [comment]
> When I complete sign flow and then tap on sign out , the correct banner is shown
> 
> ![image](https://private-user-images.githubusercontent.com/111529185/356987192-e4cc30aa-4d89-456a-befa-e452183b0e61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0OTA2NjIsIm5iZiI6MTcyMzQ5MDM2MiwicGF0aCI6Ii8xMTE1MjkxODUvMzU2OTg3MTkyLWU0Y2MzMGFhLTRkODktNDU2YS1iZWZhLWU0NTIxODNiMGU2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMlQxOTE5MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZjQyNDU0NzBlZTQ3OGYzZGZiMTlhYzU1YjI4MDMxYzc1ZDYyZTViYTllN2ZlYjBjZjhjMTU1MzkyYmJkOTUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.S9eU6WQou4oh-C6T97g4LZHiXvIPgGq3_08Ye1yazHM)

Yeah, after this I also couldn’t reproduce the bug again
