### ISSUE TITLE
WC Testing: Chrome Desktop | Coinbase Extension DESKTOP

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4555]
The following test cases should be completed and successful:

- [x] - Sign in
- [x] - Switch Network (from navbar dropdown menu)
- [x] - Switch Network (from givfarm)
- [x] - Connect Wallet(from GIVfarm/GIVback)
- [x] - Connect Wallet and sign in (from passport banner)
- [x] - Switch network (from donate page)
- [x] - Donate ERC20
- [x] - Donate native token
- [x] - Stake GIV
- [x] - Lock GIV
- [x] - Unstake GIV
- [x] - Harvest rewards (GIVfarm)
- [x] - claim GIVbacks 
- [x] - claim GIVstream
- [x] Connect with Multisig
- [x] Create recurring donation
- [x] modify recurring donation
- [x] deposit/withdraw from stream balance 
- [x] end recurring donation

**Comment by divine-comedian** [comment]
@LatifatAbdullahi this is ready for QA on staging 

You can get the coinbase wallet here 
https://www.coinbase.com/wallet

download the desktop extension for chrome  and set it up with some test funds
https://www.coinbase.com/wallet/downloads


Then using chrome desktop browser test the connection via the desktop extension and go through the test cases outlined above

**Comment by LatifatAbdullahi** [comment]
@divine-comedian @kkatusic 

**Test Update** 

**COINBASE EXTENSION CHROME DESKTOP VERSION**
 - Sign in - **Pass**
 - Switch Network (from navbar dropdown menu) - **Pass**
 - Switch Network (from givfarm) - **Pass**
 - Connect Wallet(from GIVfarm/GIVback/GIVstream)- **Pass**
 - Connect Wallet and sign in (from passport banner) - **Pass**
 - Switch network (from donate page) - **Pass**
 - Donate ERC20 - **Pass**
 - Donate native token - **Pass**
 - Stake GIV- **Pass**
 - Lock GIV - **Pass**
 - Unstake GIV - **Pass**
 - Harvest rewards (GIVfarm)- Pending
 - claim GIVbacks - Pending
 - claim GIVstream- Pending
 Connect with Multisig - **Pass**
 Create recurring donation - **Pass**
 Modify recurring donation - **Pass**
 Deposit to stream balance - **Pass**
 Withdraw from stream balance - **Pass**
End recurring donation - **Pass**
