### ISSUE TITLE
I tried to donate to a project but it freezes, when i refresh it works

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#4556]
I opened a bunch of tabs and then tried to donate to a project but it freezes, when i refresh it works...

Here's a screen shot of the errors when the donation fails... i click donate but it won't open up metamask.

<img width="1530" alt="Screenshot 2024-08-12 at 9 19 49 PM" src="https://github.com/user-attachments/assets/3de9a965-b561-44f4-9fd1-89696c740426">

**Comment by GriffGreen** [comment]
using brave on a macbook

**Comment by GriffGreen** [comment]
Another screenshot
<img width="1545" alt="Screenshot 2024-08-12 at 9 54 54 PM" src="https://github.com/user-attachments/assets/14eacc9f-b691-4a74-9a0d-8f603daa6bbf">

**Comment by GriffGreen** [comment]
Another hint... if i start with an hour old tab that was sitting on the project page, and then click donate to go to the donate page, then try to donate, it also freezes... it feels like something timed out

**Comment by jainkrati** [comment]
@RamRamez could you please guide @HrithikSampson to debug this ?

**Comment by maryjaf** [comment]
> Another hint... if i start with an hour old tab that was sitting on the project page, and then click donate to go to the donate page, then try to donate, it also freezes... it feels like something timed out

I've checked different scenarios but I couldn't reproduce it , How about you ? @RamRamez

**Comment by RamRamez** [comment]
I couldn't reproduce it but @HrithikSampson did.
@HrithikSampson could you please share your findings here?

**Comment by HrithikSampson** [comment]
Hi @maryjaf @RamRamez ,

I was able to reproduce #4557,

I am not able to reproduce this issue.
