### ISSUE TITLE
refreshed the donation page and got an application error

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#4557]
<img width="1553" alt="Screenshot 2024-08-12 at 10 01 17 PM" src="https://github.com/user-attachments/assets/90059156-b0aa-4dfa-9a90-f31dd39f76ce">

**Comment by jainkrati** [comment]
@maryjaf @RamRamez could you please take a look at this issue : how frequently it happens ? what is the cause ? deploy the fix sooner

**Comment by HrithikSampson** [comment]
I was able to reproduce this issue using URL Throttler extension and setting a delay to https://rpc.walletconnect.org/* for a long time while refreshing the page and I clicked on select Token very quickly I got this error in giveth.io

<img width="1447" alt="Screenshot 2024-08-15 at 3 20 42 PM" src="https://github.com/user-attachments/assets/8a193ac9-e62c-4882-b5ca-2b88f6b89181">

Similarly In localhost I got the following error

<img width="1075" alt="Screenshot 2024-08-15 at 6 31 57 PM" src="https://github.com/user-attachments/assets/7b780bc6-f0cf-4234-9876-3a2aa4b6e187">

**Comment by divine-comedian** [comment]
@HrithikSampson - What is the update on this issue?

**Comment by HrithikSampson** [comment]
Hi @divine-comedian ,

I was facing errors while trying to solve it. There was one solution where I was able to get resolve the error but it was causing many rerenders to  to the page.

I will try another solution to it. I am not sure whether it will work.

**Comment by HrithikSampson** [comment]
Hi @RamRamez @divine-comedian ,

I was getting a react queueing issue previously(it wasnt coming all the time) but after a small change the queueing issue disappeared. I cant see it now but I am not sure why it isnt coming. I tried it multiple times and it isnt coming.

I was getting this error:
Should have a queue. This is likely a bug in React. Please file an issue

**Comment by kkatusic** [comment]
@HrithikSampson, cc @divine-comedian, maybe this is caused ny same issue that Ashley reported, searching inside input field for token. 
If that is true @lovelgeorge99 is handling this.

**Comment by HrithikSampson** [comment]
@kkatusic ,

I think root cause might be the same.

I just wanted to inform that I am not seeing any error coming while clicking select Token Modal while refreshing now. But I am getting the error which Ashley reported while searching for the tokens.

@divine-comedian, I think that if the error is resolved while searching for the tokens, this error will also be resolved along with it.

**Comment by divine-comedian** [comment]
seems that @lovelgeorge99 and @HrithikSampson are working on two similar bugs in the same file, we should coordinate the changes and make sure both bug reports cannot be reproduced once we implement all fixes 

please coordinate with @jainkrati if either of you have code questions.

**Comment by HrithikSampson** [comment]
@maryjaf @LatifatAbdullahi ,
This issue is ready to be tested. I have also resolved this comment https://github.com/Giveth/impact-graph/issues/743#issuecomment-2324300583

**Comment by LatifatAbdullahi** [comment]
Currently unable to reproduce the error after refreshing the donation page multiple times.

https://github.com/user-attachments/assets/524a161c-c2c8-4d00-ae0b-d0b2a7bc7b13

**Comment by divine-comedian** [comment]
@LatifatAbdullahi I think to reproduce this error you not only need to refresh/load the page but also open the token select drop down menu. it appears it happens when you try to load the page and open the token modal very quickly.

**Comment by LatifatAbdullahi** [comment]
@divine-comedian Yes you are right, I tried that as well and still not reproducible
https://github.com/user-attachments/assets/40beeef4-8dfa-4af4-b888-3a72d9e1ed00

**Comment by kkatusic** [comment]
@LatifatAbdullahi I think this issue was related to input token search **_hook_** , @HrithikSampson solved that problem yesterday and push hotfix to production. Why I think that is the same, same error was occurring.

**Comment by LatifatAbdullahi** [comment]
@HrithikSampson @kkatusic 

Thanks! I just retested on production but couldnt reproduce it. The only anomaly I have noticed is the slight glitch when refreshing both on stage and production. @divine-comedian  what do you think?

https://github.com/user-attachments/assets/e74f259c-5b5a-4188-a973-775ebbdb47e3

**Comment by divine-comedian** [comment]
Follow up in #4686 

@LatifatAbdullahi could you confirm if the token list is NOT loading or rather if it is loading very slow? Try leaving the token list drop down menu open for longer and see if it eventually loads. 

At any rate let's mark this issue as DONE and follow up in the linked issue

**Comment by LatifatAbdullahi** [comment]
@divine-comedian  It loads after a couple of seconds

https://github.com/user-attachments/assets/f797bee9-5196-4b06-840a-876a97fd9f6d
