### ISSUE TITLE
Create a Project: Remove Cancel and Allow publish directly. 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#456]
While creating a project, there should only be 2 buttons: Preview / Publish

We should allow user to publish the project directly, and we have to remove the cancel button there. 

(In edit view, we have to let the user see the cancel button beside the Publish button. )

**Comment by divine-comedian** [comment]
testing on `staging.giveth.io` 

on create project i no longer see the cancel button
![image](https://user-images.githubusercontent.com/67759413/163635883-e15f86b2-1ff3-45b7-b626-597251c626a9.png)

However I can enter a weird state if, while still "creating" a project I click `preview` then `edit` -  this takes me back to the "create project" page and now I can see I can click `PREVIEW` but the `PUBLISH` button is blurred out and the cancel button has returned.  If I click `cancel` it takes me back to the preview page.. now I have a draft project on the DB. 

Is this intended functionality? Does this flow make sense? @MoeNick

**Comment by MoeNick** [comment]
Yeah while you're editing a draft project it is what we except you see, however  @mosaeedi is now working on the edit form view to have a better flow.

**Comment by divine-comedian** [comment]
okay! moving this to DONE
