### ISSUE TITLE
add link to devouch project page on giveth project page

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4563]
we should add a link & some text somewhere on the project page available to see for all users that will lead them to the project page on DeVouch for the given Giveth project.. 

example:
- this project -> https://giveth.io/project/giveth-house
- leads to this link -> https://devouch.xyz/project/giveth/1711

## text sample 
> ### View this project on DeVouch
> If you are an eligible Giveth Verifier you can vouch for this project's legitimacy, potentially increasing the benefits it receives on Giveth. Learn more about DeVouch & Decentralized Verification

https://www.figma.com/design/fHpNMd8Q9iBrAr6kBj9oo5/DeVouch-Giveth-Integration?node-id=8138-7066&t=wNsPy0Q4Zq5xCmTZ-1

![Image](https://github.com/user-attachments/assets/c85769d6-7540-4b93-8599-722946942b24)

**Comment by Tosinolawale** [comment]
![Project Single - About](https://github.com/user-attachments/assets/98bf52fb-f5d2-4f97-92af-a786828fccf2)
https://www.figma.com/design/fHpNMd8Q9iBrAr6kBj9oo5/DeVouch-Giveth-Integration?node-id=8138-7066&t=wNsPy0Q4Zq5xCmTZ-1
@divine-comedian

**Comment by divine-comedian** [comment]
@mateodaza this should be ready for you to code up

**Comment by divine-comedian** [comment]
waiting for https://github.com/Giveth/giveth-dapps-v2/pull/4598 to merge
