### ISSUE TITLE
copy fix on recurring donations modification

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4564]
it says I'm modifying a donation to giveth community of makers, but it means commons stack...

I think this needs to be updated to fetch the project name, not have default "giveth" copy.

![image](https://github.com/user-attachments/assets/454f435b-cd2f-4be6-92ef-92a955b78137)

cc @divine-comedian

**Comment by divine-comedian** [comment]
@kkatusic can you take this one up? It is related to when **making a recurring donation to a project**

If you look at the toast message the wrong project name is shown - we should make sure the correct project name is shown when making a donation to a project and also when donating to a project AND additional donation to Giveth

**Comment by laurenluz** [comment]
thanks for making this issue more clear @divine-comedian - you are great!!

**Comment by maryjaf** [comment]
Thanks @kkatusic this problem has been fixed 

![image](https://github.com/user-attachments/assets/d8604885-7653-4617-a752-d99a35d8578a)
