### ISSUE TITLE
Stellar | ask for a sign when wallet is connected. 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#4566]
Explaining the user experience: 
- I connected my wallet and I saw this screen: 
![image](https://github.com/user-attachments/assets/8ea937c1-04ff-409a-ad3a-b3b0215789c2)

- I donated to this project, and it was successful. It showed me a `You're a giver now!` status.
- I went to my donation page and I could not find the transaction in my donation list. Then I found out it has been listed as Anonymous on the projects' donation page. 
![image](https://github.com/user-attachments/assets/3f6440a0-71ee-4d3e-ae42-ef6a4b825ae4)

The reason for that is we did not ask for a sign-in message before processing the transaction. We do let people donate without connecting, but in the case they are connected, we should ask for a signed message before letting them put the amount for stellar donations.

**Comment by MoeNick** [comment]
cc: @maryjaf

**Comment by Meriem-BM** [comment]
@maryjaf you can test this.

**Comment by maryjaf** [comment]
The sign modal is also shown when the user isn't connected

- [ ] User isn't connected:

 
https://github.com/user-attachments/assets/76f5b9b5-cb9d-474f-a0ed-7e0a3da0732d

- [x] User is connected but isn't signed in 


https://github.com/user-attachments/assets/a5c8317f-b931-4374-a9fa-c0a47d577b27

@Meriem-BM

**Comment by maryjaf** [comment]
- [ ] 2- there is a problem about showing user 
as you can see in pic 1&2 my user isn't signed when I donate to " test stellar"  project 
but in donation table this donation is shown for "test account" user . pic 3

________

<img width="1435" alt="Screenshot 2024-08-20 at 12 48 05 PM" src="https://github.com/user-attachments/assets/66585a37-f9b3-425b-8aba-5a4e1ad5eea0">

![image](https://github.com/user-attachments/assets/ddba20f3-90b1-4a1f-8a07-45422bbb1ecb)


________

<img width="1469" alt="Screenshot 2024-08-20 at 12 49 53 PM" src="https://github.com/user-attachments/assets/54da619c-32d9-4c07-82c6-abd4d001deac">

@Meriem-BM

**Comment by maryjaf** [comment]
- [ ] 3-

It seems the asking for sign when wallet in connected should be add in this page https://staging.giveth.io/donate/test-stellar?chain=stellar and by tapping on "Next"

- imagine the  process of wallet connect is done by user in this page https://staging.giveth.io/donate/test-stellar?chain=stellar
- or the connected user is redirected to this page directly ba tapping on "donate with stellar" in project page 
in these cases the sign modal should be shown also
@MoeNick @Meriem-BM 


https://github.com/user-attachments/assets/8a858166-9173-42ec-a3b2-0075ad2e3087

**Comment by maryjaf** [comment]
> * [ ]  3-
> 
> It seems the asking for sign when wallet in connected should be add in this page https://staging.giveth.io/donate/test-stellar?chain=stellar and by tapping on "Next"
> 
> * imagine the  process of wallet connect is done by user in this page https://staging.giveth.io/donate/test-stellar?chain=stellar
> * or the connected user is redirected to this page directly ba tapping on "donate with stellar" in project page
>   in these cases the sign modal should be shown also
>   @MoeNick @Meriem-BM
> 
>  Screen.Recording.2024-08-22.at.10.15.32.AM.mov

Kindly reminder
@MoeNick @Meriem-BM

**Comment by maryjaf** [comment]
These problems have been fixed, but the issue is in "in progress"
I'm not sure if some other thing should be developed relate to this issue or it remained in this status by mistake 

@Meriem-BM
