### ISSUE TITLE
Stellar | Letting user know if the Memo is required or not for donation 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#4567]
for projects which is raising funds on wallets without Memo, can we add a toast message below the project address like this:

`No Memo is needed for this address` 

![image](https://github.com/user-attachments/assets/8b9ce5ce-1637-42b6-95ab-11c091e2c971)

**Comment by MoeNick** [comment]
CC: @maryjaf

**Comment by maryjaf** [comment]
It has been fixed
![image](https://github.com/user-attachments/assets/3df64943-d8da-4ea1-906f-aadf5e3c010f)
