### ISSUE TITLE
Stellar| bug in donation flow 

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#4568]
In order to be able to follow up better, I registered a separate issue for this bug 

1. I tap on Donate with stellar to this project https://staging.giveth.io/donate/test-base01

2. the below pic is shown correctly 
![image](https://github.com/user-attachments/assets/f58f8285-5258-4a5d-ba73-4bd775f47d42)

3. after afew minutes  I select another project to donate with stellar https://staging.giveth.io/donate/test-stellar
4. after about 1 min I see the showing timer for both of them are the same !
_____

https://github.com/user-attachments/assets/61cb5f33-dd73-4719-80bb-dc0c600a5ab4

_________

5. I complete the donation flow only for one project (test-stellar),  the success donation page is shown for both project ! although I see this record on donation only in dontion table of test-stellar project 

![image](https://github.com/user-attachments/assets/f5d58b14-2bf1-43a9-a598-0580b9e61069)
![image](https://github.com/user-attachments/assets/2e33ba00-507d-4a3b-9904-9122b533712a)
________
![image](https://github.com/user-attachments/assets/d2c216fc-50cd-4d16-aaec-15f33c5f882d)
![image](https://github.com/user-attachments/assets/f3cfb8ba-0477-4a6d-b384-f6f29d065b91)

cc: @MoeNick

**Comment by Meriem-BM** [comment]
@maryjaf can you check this too pls.

**Comment by maryjaf** [comment]
> @maryjaf can you check this too pls.

Could you please take a look on below screen record 
I see a strange behavior by tapping on donate for [Test stellar](https://staging.giveth.io/project/test-stellar) project

https://github.com/user-attachments/assets/c17774a9-054b-4702-8bcd-461db5d72c40

**Comment by Meriem-BM** [comment]
> > @maryjaf can you check this too pls.
> 
> 
> 
> Could you please take a look on below screen record @Meriem-BM 
> 
> I see a strange behavior by tapping on donate for [Test stellar](https://staging.giveth.io/project/test-stellar) project
> 
> 
> 
> https://github.com/user-attachments/assets/c17774a9-054b-4702-8bcd-461db5d72c40
> 
> 
> 
> 

Hey, @MoeNick requested that if user attempt to make a donation and he refreshed the page or left it while it's still pending, to redirect him to receipt page.

**Comment by maryjaf** [comment]
> > @maryjaf can you check this too pls.
> 
> Could you please take a look on below screen record @Meriem-BM I see a strange behavior by tapping on donate for [Test stellar](https://staging.giveth.io/project/test-stellar) project
> 
>  Screen.Recording.2024-08-19.at.3.39.34.PM.mov

Is this behavior is fine in point of your view @MoeNick

**Comment by MoeNick** [comment]
Hey @Meriem-BM 
I think there was a misunderstanding about the flow as I did not create the promised issue yet :D 
Actually, I want to keep the flow as is, but if possible we make the URL  fixed like what we have for transaction (receipt) so it won't affect the refreshing. 

So
1- User see the amount entering screen. 
2- User goes to the Scan QR screen like what we have but in a specific URL https://staging.giveth.io/transaction/883 in 
![image](https://github.com/user-attachments/assets/3c35c090-66b0-4e2e-8f09-00c9d4eeb00f)

3- The failed view donation page and success view donation page would be like what we have right now. 
4- The link of change donation, change to transaction receipt page, for both logged in and logged out users. 

I did not check  with you the technical possibility of this yes. but let me know if you need any meeting or something,

This will solve the problem of refreshing the donation page, let me know if is it possible or you like it or not? the value is only for users who refresh don't lose the track of donation. 

FYI: @maryjaf

**Comment by maryjaf** [comment]
> In order to be able to follow up better, I registered a separate issue for this bug
> 
> 1. I tap on Donate with stellar to this project https://staging.giveth.io/donate/test-base01
> 2. the below pic is shown correctly
> 3. after afew minutes  I select another project to donate with stellar https://staging.giveth.io/donate/test-stellar
> 4. after about 1 min I see the showing timer for both of them are the same !
> 5. I complete the donation flow only for one project (test-stellar),  the success donation page is shown for both project ! although I see this record on donation only in dontion table of test-stellar project
Thanks @Meriem-BM this problem has been fixed.
Since this problem has been fixed, Do you agree above comment be referenced in a new issue? @MoeNick

**Comment by MoeNick** [comment]
> > In order to be able to follow up better, I registered a separate issue for this bug
> > 
> > 1. I tap on Donate with stellar to this project https://staging.giveth.io/donate/test-base01
> > 2. the below pic is shown correctly
> > 3. after afew minutes  I select another project to donate with stellar https://staging.giveth.io/donate/test-stellar
> > 4. after about 1 min I see the showing timer for both of them are the same !
> > 5. I complete the donation flow only for one project (test-stellar),  the success donation page is shown for both project ! although I see this record on donation only in dontion table of test-stellar project
> 
> Thanks @Meriem-BM this problem has been fixed. Since this problem has been fixed, Do you agree above comment be referenced in a new issue? @MoeNick

Yes will do.
