### ISSUE TITLE
Error on claiming from GIVstream on mainnet ""TransactionReceiptNotFoundError"

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4570]
Brave browser
Ubuntu 22.04
MetaMask

I tried to claim my GIVstream on mainnet and I received an error with "TransactionReceiptNotFoundError"

![Image](https://github.com/user-attachments/assets/fd6991e6-648d-4047-9962-576f0b0a55fb)

However I can see the transaction still went through on the blockchain and my GIV tokens were successfully claimed to my wallet

**Comment by laurenluz** [comment]
@mohammadranjbarz can you investigate? or assign the right person?

**Comment by divine-comedian** [comment]
@laurenluz - looks like it worked well when I switched from using MM to rabby wallet, just claimed with no errors!  unless

**Comment by laurenluz** [comment]
think I can close this then @divine-comedian ?
