### ISSUE TITLE
Users unable to stake GIV using the Polygon zkVEVM cardona network

### ISSUE THREAD

**Issue by LatifatAbdullahi** [Giveth/giveth-dapps-v2#4571]
*After successfully connecting to the Polygon zkEVM cardona network, and users attempt to stake GIV token, Users get stuck on clicking the "stake" button after granting permission.

To Reproduce
1. Given User is on the GivFarm page [](https://staging.giveth.io/givfarm) on stage  - https://staging.giveth.io/givfarm
2. And Users click on "Stake" option from the card
3. And Users inputs desired amount of GIV to stake
4. And Users clicks on the "Permit" button
5. And User confirms sig -in from the pop up modal
6. When Users click on "Stake"
7. Then no action is taken

**Expected behavior**
Users GIV token should be successfully staked

https://github.com/user-attachments/assets/bf5aea8e-dffa-42a2-8b0a-83d5862674b7

Environment: Staging

**Comment by mohammadranjbarz** [comment]
> *After successfully connecting to the Polygon zkEVM cardona network, and users attempt to stake GIV token, Users get stuck on clicking the "stake" button after granting permission.
> 
> To Reproduce Steps to reproduce the behavior:
> 
> 1. Given User is on the GivFarm page  on stage  - https://staging.giveth.io/givfarm
> 2. And Users click on "Stake" option from the card
> 3. And Users inputs desired amount of GIV to stake
> 4. And Users clicks on the "Permit" button
> 5. And User confirms sig -in from the pop up modal
> 6. When Users click on "Stake"
> 7. Then no action is taken
> 
> **Expected behavior** Users GIV token should be successfully staked
> 
>  GIVfarm_.Stake-to-earn.while.supporting.for-good.DAOs.-.Google.Chrome.2024-08-14.19-21-53.mp4 
> Environment: Staging

I faced the same problem, if you uncheck the `permit mode` the stake would be success, @aminlatifi  @MohammadPCh can you tell me what could be the reason?

**Comment by aminlatifi** [comment]
The kind of token deployed on zkevm cardona doesn't support this feature. We must disable it in the frontend.

**Comment by mohammadranjbarz** [comment]
> The kind of token deployed on zkevm cardona doesn't support this feature. We must disable it in the frontend.

Thanks @aminlatifi

**Comment by mohammadranjbarz** [comment]
> *After successfully connecting to the Polygon zkEVM cardona network, and users attempt to stake GIV token, Users get stuck on clicking the "stake" button after granting permission.
> 
> To Reproduce Steps to reproduce the behavior:
> 
> 1. Given User is on the GivFarm page  on stage  - https://staging.giveth.io/givfarm
> 2. And Users click on "Stake" option from the card
> 3. And Users inputs desired amount of GIV to stake
> 4. And Users clicks on the "Permit" button
> 5. And User confirms sig -in from the pop up modal
> 6. When Users click on "Stake"
> 7. Then no action is taken
> 
> **Expected behavior** Users GIV token should be successfully staked
> 
>  GIVfarm_.Stake-to-earn.while.supporting.for-good.DAOs.-.Google.Chrome.2024-08-14.19-21-53.mp4 
> Environment: Staging

@LatifatAbdullahi It's fixed now, can you test it again?

**Comment by LatifatAbdullahi** [comment]
@mohammadranjbarz 
Sure, thanks

**Comment by LatifatAbdullahi** [comment]
Thanks @mohammadranjbarz  the issues has been fixed.



Uploading GIVfarm_ Stake-to-earn while supporting for-good DAOs - Google Chrome 2024-08-14 19-21-53.mp4…
