### ISSUE TITLE
Stellar| Mobile view - donation page 

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#4572]
There are some problems on mobile view

- [x] 1- showing the “donate with stellar” button 

![image](https://github.com/user-attachments/assets/983a3137-8207-46f4-a796-2c6d59b70bbb)

- [x] 2- entering number in amount box is buggy 

https://github.com/user-attachments/assets/85427670-dd2b-49b6-ad69-0ce5e2123bf3

![image](https://github.com/user-attachments/assets/4eb443e9-fd23-4ab6-ac5c-e34046a965f8)

cc: @MoeNick

**Comment by maryjaf** [comment]
- [ ] 3-

![image](https://github.com/user-attachments/assets/0a018d0a-68e7-4af7-9773-f79d937809b8)

**Comment by Meriem-BM** [comment]
@maryjaf you can check this.

**Comment by maryjaf** [comment]
Thanks @Meriem-BM These 3 items have been fixed 
But because of this blocker that I've reported on [discord channel ](https://discord.com/channels/679428761438912522/861692942645067777/1275073339030765638, I couldn't complete donation scenario on mobile.
after fixing this problem and completing donation on mobile  I'll move it to done

**Comment by MoeNick** [comment]
The blocker is removed, right?

**Comment by maryjaf** [comment]
I did a donation on mobile but I haven’t seen in donation table 

https://github.com/user-attachments/assets/522f568c-79d3-47f2-826f-fdb8f80ad72f

Success transaction: 
![IMG_3780](https://github.com/user-attachments/assets/b51dbd4d-65bb-47b3-a055-cab20d44a3f5)

But there is no record with this amount 0.011 in donation table


https://github.com/user-attachments/assets/22e544ed-b633-4562-8966-412a0a8fbfd5

**Comment by maryjaf** [comment]
> Hey @maryjaf it's the 1st one, ti has the same transaction link, maybe there is an amount format that keeps 2 digits, I'll check.

so I think it's the same problem with this https://github.com/Giveth/giveth-dapps-v2/issues/4566#issuecomment-2298396473 , since my user isn't signed in on mobile i expect the record is set anonymous

**Comment by maryjaf** [comment]
Is there any UI change  on mobile view that should be applied in point of your view? @MoeNick 
if not, I'll move this issue to done and we can track the last problem on related issue (# 4566)

**Comment by MoeNick** [comment]
Please check the responsiveness with Stellar Figma.

**Comment by maryjaf** [comment]
Is there a figma for mobile view ? Please share it here

**Comment by maryjaf** [comment]
> Is there any UI change on mobile view that should be applied in point of your view? @MoeNick if not, I'll move this issue to done and we can track the last problem on related issue (# 4566)

The reported UI problems have been fixed, I meant If other changes needed let us know since I haven't seen separate design for mobile, Is there a figma for mobile view ? Please share it here

**Comment by MoeNick** [comment]
https://www.figma.com/file/5qh6OaJRJSCNj2h22MMSwa?node-id=1:103&locale=en&type=design#917906640

If you scroll down you can find transaction responsiveness design as well.

**Comment by maryjaf** [comment]
- [ ]  these pics are not exactly based on the design

![image](https://github.com/user-attachments/assets/b2b78d61-e4fa-49cd-b458-c79f7f50530b)

Figma:
https://github.com/Giveth/giveth-dapps-v2/issues/4440#issuecomment-2295271289
