### ISSUE TITLE
Stellar | Check pending donation onchain on specific events

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#4573]
Was talking to @Meriem-BM to seek for a live solution to detect in seconds, or  we run one manual fetch data before 
- we let the user click back, 
- before changing the status to failed OR when the time is up
- before raising a ticket. 
So we make sure it's not a pending state on our side and no need to mention the 5 min @maryjaf (FYI)

_Originally posted by @MoeNick in https://github.com/Giveth/giveth-dapps-v2/issues/4422#issuecomment-2288782804_

**Comment by MoeNick** [comment]
FYI: @maryjaf

**Comment by Meriem-BM** [comment]
@maryjaf this one ready for test.

**Comment by maryjaf** [comment]
> @maryjaf this one ready for test.

Could you please tell me more about this new change? actually what changes be made in this page?
![image](https://github.com/user-attachments/assets/ed1f4d66-3af1-4ae5-9591-dc0f27feef62)

**Comment by Meriem-BM** [comment]
@maryjaf user might make a donation in last minutes, or scan QR code and tries to go back which will mark it as failed, and since we refresh UI every 5 mins when user is waiting for status update it might be missed, so we added fetching updated status on certain events (when time is up, when user try raising a ticket, or hen going back) to avoid any mismatch and get last status before those events.

**Comment by maryjaf** [comment]
> when time is up

- [ ]  1- it seems there is a problem in this case (when time is up), as you can see in below video after the time is over this request, operationName:"GetDonationById" hasnot been called

https://github.com/user-attachments/assets/791f5b78-0739-4c10-952c-b299da46acb5


and after about 2 mins I see the below pic

![image](https://github.com/user-attachments/assets/0f412944-085f-490c-92e7-549436ba9937)

**Comment by maryjaf** [comment]
- [ ] 2- one question 
 When users refresh the page this request shouldn't be called?  @Meriem-BM @MoeNick

**Comment by MoeNick** [comment]
For 2 I think we can do it while loading the page if @Meriem-BM agrees.

**Comment by maryjaf** [comment]
> when user try raising a ticket,

- [ ] 3- in this case the time is over and user hasn't donated to the project, the behavior is like below record 
- after the time is over, the related request is called and the status is pending 
- when I tap on the "raise a ticket" the request is called and the status is pending 

my question is that if  the showing pending status in this scenario is correct when the the time is over and there is no donation?

**Comment by maryjaf** [comment]
> > when user try raising a ticket,
> 
> * [ ]  3- in this case the time is over and user hasn't donated to the project, the behavior is like below record
> * after the time is over, the related request is called and the status is pending
> * when I tap on the "raise a ticket" the request is called and the status is pending
> 
> my question is that if the showing pending status in this scenario is correct when the the time is over and there is no donation?
> 
>  Screen.Recording.2024-08-20.at.11.58.21.AM.mov



> [ ] 1- it seems there is a problem in this case (when time is up), as you can see in below video after the time is over this request, operationName:"GetDonationById" hasnot been called


kindly reminder

**Comment by MoeNick** [comment]
For 3 - the status should change to failed when the time is up, A manual check on this event could only change the status to success if there's a donation is detected on-chain within the 5 min intervals. @maryjaf 
For better testing please youse different amounts.

**Comment by maryjaf** [comment]
> [ ] 1- it seems there is a problem in this case (when time is up), as you can see in below video after the time is over this request, operationName:"GetDonationById" hasnot been called



> * 3- in this case the time is over and user hasn't donated to the project, the behavior is like below record
> * after the time is over, the related request is called and the status is pending
> * when I tap on the "raise a ticket" the request is called and the status is pending

Is there an update related to these 2 items?

**Comment by Meriem-BM** [comment]
> > when user try raising a ticket,
> 
> * [ ]  3- in this case the time is over and user hasn't donated to the project, the behavior is like below record
> * after the time is over, the related request is called and the status is pending
> * when I tap on the "raise a ticket" the request is called and the status is pending
> 
> my question is that if the showing pending status in this scenario is correct when the the time is over and there is no donation?
> 
>  Screen.Recording.2024-08-20.at.11.58.21.AM.mov

@maryjaf the cron job runs every minute to get transactions on stellar, so I make sure to not mark any donation as failed when time is up until one minute passes, to make sure if any donation detected in next minute, because the user might donation in last minute on seconds. if you wait 1 min it will be changed to failed.
