### ISSUE TITLE
Make Recurring Donations default option

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4577]
We would like to further promote the experimentation by users of the recurring donation feature. With that we should show the recurring donations view by default when the user loads the donate page IF the project has added an optimism address.

![Image](https://github.com/user-attachments/assets/d01284dc-a0d2-4cbc-9e10-2b57efa4b87e)

## Requirements
- when entering donate page for a specific project WITH an Optimism recipient address the recurring donation view is shown by default on page load
- entering the donate page for a project WITHOUT an Optimism recipient address shows the one-time donation view.

**Comment by divine-comedian** [comment]
@kkatusic think you can take this one on?

**Comment by maryjaf** [comment]
> * when entering donate page for a specific project WITH an Optimism recipient address the recurring donation view is shown by default on page load
> * entering the donate page for a project WITHOUT an Optimism recipient address shows the one-time donation view.

Thanks @kkatusic These ACs are passed
