### ISSUE TITLE
Remove email verification from verification form

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4579]
As part of #4476 anyone who adds an email to their profile will need to verify their ownership. This means that asking users to verify email ownership when applying for project verification will be redundant, since we already have a verified email associated with the project owner. 

We should ensure that the email verification component is removed from the verification form. The email that is associated with the project owner's profile should be used when submitting the application data and also for sending any subsequent project verification related emails.

![image](https://github.com/user-attachments/assets/e81c2575-586e-41da-9703-a02b10cbbbaa)

**Comment by divine-comedian** [comment]
@HrithikSampson this issue is also related to #4476

**Comment by divine-comedian** [comment]
@kkatusic this one will also need to be done before we can release email verification feature. 

Since we are verifying project owner's email it is no longer necessary to make them verify their email again on the givbacks eligiblity form.

**Comment by kkatusic** [comment]
@divine-comedian this wont be easy, let's think with BE guy @CarlosQ96 , if I remove this should I remove all fields related to email verification process inside project_verification_form table and all related logics on BE? What you @CarlosQ96 suggest? thx

**Comment by divine-comedian** [comment]
Is it possible instead to remove the field from the UI and send some data to the back-end that says the email is already verified. We could even send the email that is already listed on the project owner's user profile.

**Comment by kkatusic** [comment]
> Is it possible instead to remove the field from the UI and send some data to the back-end that says the email is already verified. We could even send the email that is already listed on the project owner's user profile.

Some kind of camouflage, BE is handling all data submission and if you click "Verify" than it runs verification procedure, timing, dating, generating token... it should be also removed from BE side, or on first submission make it validated

**Comment by kkatusic** [comment]
Let me check now

**Comment by divine-comedian** [comment]
@kkatusic following up from convo today - see if we can insert the user.profile on creating the form. Or we can insert the user email on the step/function where it is expecting the email in the form. 

The givbacks eligibility forms (verification form) are kept as separate objects from user data, I think it is only loosely associated with the project data itself. 

We should try to keep the table entry there since remove any table data from our DB could create lots of unexpected consequences. 

Please ask questions to @CarlosQ96 for any advice on how to handle requirements the BE needs to make hiding the front-end elements possible.

**Comment by kkatusic** [comment]
@divine-comedian I removed and tested, after approve QF staff will test it better in all cases ;)

**Comment by maryjaf** [comment]
Imagine this scenario:
I had started verification form before, with this email : maryam.jafarymehr@gmail.com
my email isn't verified and I can't complete the verification form 
I set this new email for my user: jafarimehrmaryam725@gmail.com
now I can complete the verfication form 
I see below pic in admin js 
email:maryam.jafarymehr@gmail.com
userId:afarimehrmaryam725@gmail.com
![image](https://github.com/user-attachments/assets/29af502d-43c2-45fb-8fcc-a3e70ec5f670)

Is this accepted ? @divine-comedian @kkatusic

**Comment by divine-comedian** [comment]
> Imagine this scenario: I had started verification form before, with this email : [maryam.jafarymehr@gmail.com](mailto:maryam.jafarymehr@gmail.com) my email isn't verified and I can't complete the verification form I set this new email for my user: [jafarimehrmaryam725@gmail.com](mailto:jafarimehrmaryam725@gmail.com) now I can complete the verfication form I see below pic in admin js email:[maryam.jafarymehr@gmail.com](mailto:maryam.jafarymehr@gmail.com) userId:[afarimehrmaryam725@gmail.com](mailto:afarimehrmaryam725@gmail.com) ![image](https://private-user-images.githubusercontent.com/111529185/392006791-29af502d-43c2-45fb-8fcc-a3e70ec5f670.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMzc4MTMsIm5iZiI6MTczMzIzNzUxMywicGF0aCI6Ii8xMTE1MjkxODUvMzkyMDA2NzkxLTI5YWY1MDJkLTQzYzItNDVmYi04ZmNjLWEzZTcwZWM1ZjY3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwM1QxNDUxNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZjk4ZGI4NDljMTFhMTI3Y2EwNWU5YWEyODEwN2M1YzhiYjA2MGJiYWE1MjljYjdiNDA5ZjJmYWNmNmY5NTQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gsseQ2_7ZtHMtOszE4QvCnfvtK7cm-l8_BDpVaczVbI)
> 
> Is this accepted ? @divine-comedian @kkatusic

As long as the email associated with the user's profile is the one that you verified I think this is accepted. 

We don't really need this field at all anymore but it is quite complicated to remove entirely. We will use the user profile email to communicate with the project owner, this will also only affect project's with incomplete forms so this issue is negligible now and will be irrelevant at some point when all incomplete forms at launch have been submitted.

**Comment by maryjaf** [comment]
I haven't seen any other problem in verification flow, we can call it done .
