### ISSUE TITLE
Stellar | GIVback eligiblity 

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#4582]
"Is givback eligible" is set for this token https://impact-graph.serve.giveth.io/admin/resources/Token/records/306/show
but I haven't seen the donation with stellar in response of this API

curl -X 'GET' \
  'https://givback.develop.giveth.io/eligible-donations?chain=all-other-chains&startDate=2024%2F08%2F18-00%3A00%3A00&endDate=2024%2F08%2F19-23%3A59%3A59&download=no' \
  -H 'accept: application/json'
  
  
  cc: @MoeNick @Meriem-B

**Comment by MoeNick** [comment]
Also, the icon for Stellar should demonstrate with a tiny GIVback hand icon.

**Comment by maryjaf** [comment]
This issue hasn't been assigned yet

**Comment by mohammadranjbarz** [comment]
@maryjaf  @MoeNick  Now we have some restrictions that send givbacks for EVM donations, should we change it?
Because if we change it to support non-EVM donations we need to find a solution to send givbacks for them as the script and the format that we use for sending givbacks is only available on `Gnosis` and `OP` chain.
Correct me if I'm wrong @laurenluz  @WhyldWanderer

**Comment by GriffGreen** [comment]
We would send GIVbacks on OP, not on Stellar, like we do for donations on Arbitrum.

**Comment by mohammadranjbarz** [comment]
> We would send GIVbacks on OP, not on Stellar, like we do for donations on Arbitrum, the main thing is that it will only work if they are logged in with a Ethereum profile (not a solana profile)

Thanks @GriffGreen , will work on that

**Comment by mohammadranjbarz** [comment]
FYI @maryjaf  @MoeNick  it's deployed on Staging

**Comment by maryjaf** [comment]
> but I haven't seen the donation with stellar in response of this API
> 
> curl -X 'GET' 'https://givback.develop.giveth.io/eligible-donations?chain=all-other-chains&startDate=2024%2F08%2F18-00%3A00%3A00&endDate=2024%2F08%2F19-23%3A59%3A59&download=no' -H 'accept: application/json'

So I should see the stellar donation in response of this api now? @mohammadranjbarz

**Comment by divine-comedian** [comment]
Hey guys! I was testing the flow today and wanted to add a comment related to this issue: 

For me it wasn't obvious that if I'm not signed in with my EVM profile I won't get GIVbacks! It would be nice to remind me if I'm  not signed in that I should do it, otherwise I'll miss out on GIVbacks! 


![Image](https://github.com/user-attachments/assets/f3b4b84c-badf-4692-aa36-d298c1742af2)

**Comment by divine-comedian** [comment]
Also! If I'm not signed in and make a successful donation I shouldn't see the GIVbacks component on the donation success page, since I won't actually get GIVbacks 


![Image](https://github.com/user-attachments/assets/ce944e96-248b-478a-9943-d8b35b176fc6)

**Comment by maryjaf** [comment]
> > but I haven't seen the donation with stellar in response of this API
> > curl -X 'GET' 'https://givback.develop.giveth.io/eligible-donations?chain=all-other-chains&startDate=2024%2F08%2F18-00%3A00%3A00&endDate=2024%2F08%2F19-23%3A59%3A59&download=no' -H 'accept: application/json'
> 
> So I should see the stellar donation in response of this api now? [@mohammadranjbarz](https://github.com/mohammadranjbarz)

  {
    "amount": 0.1,
    "currency": "XLM",
    "createdAt": "2024-09-01-07:49:00",
    "valueUsd": 0.0092289,
    "bottomRankInRound": null,
    "givbacksRound": null,
    "projectRank": null,
    "givbackFactor": 0.75,
    "valueUsdAfterGivbackFactor": 0,
    "giverAddress": "0xa047b554b435674eb28fd4553201cb1a800be53b",
    "txHash": "0383be71d2d726233e09477973d44ac8338ea7ce9df10f4faca405d202d3306c",
    "network": "stellar",
    "source": "giveth.io",
    "giverName": "testaccoun2 mozila",
    "giverEmail": null,
    "projectLink": "https://giveth.io/project/test-stellar",
    "isReferrerGivbackEligible": false,
    "referrerWallet": null
  },

I donated to test [stellar project](https://staging.giveth.io/donate/test-stellar), and above record is shown in response of givback api.
Is the value of these below fields correct? @mohammadranjbarz 

 "bottomRankInRound": null,
 "givbacksRound": null,    
"valueUsdAfterGivbackFactor": 0,

**Comment by MoeNick** [comment]
Thanks, @divine-comedian for raising those issues, those will be addressed on the issues above so as not to distract the GIVback API QA.

**Comment by mohammadranjbarz** [comment]
> 0383be71d2d726233e09477973d44ac8338ea7ce9df10f4faca405d202d3306c

I checked the stellar donations on staging, the rank info is null for all of them as you see in this screenshot

<img width="612" alt="Screenshot 1403-06-13 at 11 37 17 in the morning" src="https://github.com/user-attachments/assets/c3e3448a-2cb0-483f-99be-39b794a78528">


@Meriem-B Can you investigate it? I spent about 1 hour but couldn't find the reason, if you could not find it as well, please write some test cases for this scenario, reproduce it in test cases and then fix it ( Ask me if you need help)

**Comment by mohammadranjbarz** [comment]
@maryjaf can you test it again?
It should work for new donations that you will create from now on

**Comment by maryjaf** [comment]
Now this record is shown in response of givback eligibility
It seems the problem has been fixed @mohammadranjbarz 

  "givbacksRound": 49443 is this filed filled correctly?

 {
    "amount": 0.1,
    "currency": "XLM",
    "createdAt": "2024-09-03-09:53:00",
    "valueUsd": 0.0093546,
    "bottomRankInRound": 33,
    "givbacksRound": 49443,
    "projectRank": 33,
    "givbackFactor": 0.5,
    "valueUsdAfterGivbackFactor": 0.0046773,
    "giverAddress": "0x7f37e3008207c27360b20abcfb5fdcc8e37596b8",
    "txHash": "d02a1bf00da3ffcc344d4700ff2dfadfe3d28bd981a8765565a8fcf27babd305",
    "network": "stellar",
    "source": "giveth.io",
    "giverName": "maryamaa mehr",
    "giverEmail": null,
    "projectLink": "https://giveth.io/project/test-stellar",
    "isReferrerGivbackEligible": false,
    "referrerWallet": null
  },

**Comment by mohammadranjbarz** [comment]
w

> Now this record is shown in response of givback eligibility It seems the problem has been fixed @mohammadranjbarz
> 
> "givbacksRound": 49443 is this filed filled correctly?
> 
> { "amount": 0.1, "currency": "XLM", "createdAt": "2024-09-03-09:53:00", "valueUsd": 0.0093546, "bottomRankInRound": 33, "givbacksRound": 49443, "projectRank": 33, "givbackFactor": 0.5, "valueUsdAfterGivbackFactor": 0.0046773, "giverAddress": "0x7f37e3008207c27360b20abcfb5fdcc8e37596b8", "txHash": "d02a1bf00da3ffcc344d4700ff2dfadfe3d28bd981a8765565a8fcf27babd305", "network": "stellar", "source": "giveth.io", "giverName": "maryamaa mehr", "giverEmail": null, "projectLink": "https://giveth.io/project/test-stellar", "isReferrerGivbackEligible": false, "referrerWallet": null },

Thanks @maryjaf yes it's o
