### ISSUE TITLE
Stellar| Bug in showing QR code 

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#4585]
**Describe the bug**
I've edited the recipient address of stellar in my project and remove memo, After that I see below error in donate with stellar page 
https://staging.giveth.io/donate/testmap02

![image](https://github.com/user-attachments/assets/d7ab00c5-244d-4668-ae8c-0dc3b2d4e4dd)

________

https://github.com/user-attachments/assets/cff9265d-5a48-49c6-bd62-699822c2819d

 For this project the memo field wasn't set when It was created and there is no problem in showing QR code, it seems the bug is related to edit flow
https://staging.giveth.io/donate/test-base01

cc: @MoeNick

**Comment by maryjaf** [comment]
For this project the memo field wasn't set when It was created and there is no problem in showing QR code, it seems the bug is related to edit flow 


https://staging.giveth.io/donate/test-base01

**Comment by maryjaf** [comment]
> I've edited the recipient address of stellar in my project and remove memo, After that I see below error in donate with stellar page
> https://staging.giveth.io/donate/testmap02

Now when I try to donate to this project, this bug doesn't occur, 
Does it take time to the changes be applied? may the bug is related to the time that the change hasn't been applied?

**Comment by Meriem-BM** [comment]
> > I've edited the recipient address of stellar in my project and remove memo, After that I see below error in donate with stellar page
> > https://staging.giveth.io/donate/testmap02
> 
> Now when I try to donate to this project, this bug doesn't occur, Does it take time to the changes be applied? may the bug is related to the time that the change hasn't been applied?

I'm not sure why that happened, will test more.

**Comment by maryjaf** [comment]
Today I've been retesting this issue, it seems it was a temproty bug, I move it to done
