### ISSUE TITLE
Stellar | New route for stellar donations - to not get affected by refresh. 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#4587]
Hey @Meriem-BM 
I think there was a misunderstanding about the flow as I did not create the promised issue yet :D 
Actually, I want to keep the flow as is, but if possible we make the URL  fixed like what we have for transaction (receipt) so it won't affect the refreshing. 

So
1- User see the amount entering screen. 
2- User goes to the Scan QR screen like what we have but in a specific URL https://staging.giveth.io/transaction/883 in 
![image](https://github.com/user-attachments/assets/3c35c090-66b0-4e2e-8f09-00c9d4eeb00f)

3- The failed view donation page and success view donation page would be like what we have right now. 
4- The link of check donation, should change to transaction receipt page, for both logged in and logged out users. 

I did not check  with you the technical possibility of this yes. but let me know if you need any meeting or something,

This will solve the problem of refreshing the donation page, let me know if is it possible or you like it or not? the value is only for users who refresh don't lose the track of donation. 

FYI: @maryjaf

_Originally posted by @MoeNick in https://github.com/Giveth/giveth-dapps-v2/issues/4568#issuecomment-2296593629_

**Comment by maryjaf** [comment]
- [ ] I'm not sure maybe this new problem is related to this change 
https://github.com/Giveth/giveth-dapps-v2/issues/4608 

@Meriem-BM

**Comment by maryjaf** [comment]
- [ ] 2- maybe also this new problem is related to this change , if not tell me to create separate issue

- I have a donation that its time is up and the status is failed 
- I tap on donate with stellar to create a new donation
- in new page the timer is reloaded but the showing status is failed 

https://github.com/user-attachments/assets/eea1bbc9-aa4f-442b-b399-b4e89c2178f3


@Meriem-BM @MoeNick

**Comment by maryjaf** [comment]
> * [x]  2- maybe also this new problem is related to this change , if not tell me to create separate issue
> * I have a donation that its time is up and the status is failed
> * I tap on donate with stellar to create a new donation
> * in new page the timer is reloaded but the showing status is failed
> 
>  Screen.Recording.2024-08-22.at.3.11.27.PM.mov 
> @Meriem-BM @MoeNick

This problem has been fixed 

https://github.com/user-attachments/assets/1c925bae-c902-4370-879c-6005a2feda73

**Comment by maryjaf** [comment]
> * [ ]  1- I'm not sure maybe this new problem is related to this change
>   [Stellar| Update QR code problem #4608](https://github.com/Giveth/giveth-dapps-v2/issues/4608)
> 
> @Meriem-BM

I move this issue to Done 
and this problem,  can be tracked on relevant issue
