### ISSUE TITLE
project page and donation flow updates for verified projects (not givbacks eligible)

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4597]
## Project details page
We should ensure there is a corresponding component for when a project has reached the `verified` status but is no yet `givbackEligible`. 

![Image](https://github.com/user-attachments/assets/0b5b32a2-951b-4efb-acc3-1bab47bb4387)

This project is eligible to be boosted with GIVpower but will not yield GIVbacks to it's donors. @Tosinolawale @mosaeedi we will need a DESIGN for this new component version.

here's some text:

> ### Boost this project with GIVpower!
> [Stake & lock](https://giveth.io/givfarm) your GIV tokens to get GIVpower. Boost this project make it more visible on the projects page!

We'll also need to fix the copy on the current "verified" version of this component to be accurate for givbacks eligible projects: 

> ### Get rewarded with up to {givbacksFactor}% of your donation value!
> Ethereum donations to this project are rewarded with GIV. Boost this project to increase its rewards percentage and make it more visible on the projects page!

### Successful donation page 

We'll need to make sure that when donating to a verified but not givbacks eligible project we show the donate success page as it currently is when donating to a non-verified project

![Image](https://github.com/user-attachments/assets/651cf181-7b64-45d0-a748-1e71a11104ae)

### verified & givbacks eligible badge

when a project is givbacks eligible we should ensure both the verified and givbacks eligible badge is shown on the project card and project details page, next to the verified badge. I think we had an badge design for this once upon a time @Tosinolawale if you can help find this or design a quick one. 

**To note**, this likely will change when we move into the full specification and we will be showing different badges when we get the time to move into the full specification of this project.

----

Summary Task list: 

- [ ] new component for verified projects on project details page
- [ ] update current verified projects component for givbacks eligible status
- [ ] ensure correct version of donation success page shows for non givbacks eligible projects
- [ ] givbacks eligible badge on project card and project details page for givbacks eligible projects

# for testing 

- copy change on component on project details page for projects that are vouched but NOT GIVbacks eligible is correct
- copy change on component on project details page for projects that are GIVbacks eligible is correct
- donations to vouched projects on donation success page shows correct copy (no references to receiving GIVbacks or GIV token rewards)

**Comment by Tosinolawale** [comment]
![Project Single - About2](https://github.com/user-attachments/assets/bf7d4bdc-708b-4b23-a6a9-aec7bc6ebec5)
GIVBacks Eligible verified projects

![Project Single - About](https://github.com/user-attachments/assets/d56c82c3-9514-4c94-bfe7-c20357b871e9)
GIVbacks not eligible verified projects

https://www.figma.com/design/fHpNMd8Q9iBrAr6kBj9oo5/DeVouch-Giveth-Integration?node-id=8214-4238&t=8P26W4jR0mgkG3SQ-1

**Comment by divine-comedian** [comment]
@mateodaza this should be ready for you now

**Comment by LatifatAbdullahi** [comment]
@mateodaza  @divine-comedian 

**Test Update**


-Copy change on component on project details page for projects that are vouched but NOT GIVbacks eligible is correct - **Pending**

@mateodaza  **Seems the "Stake and lock" should be a hyperlink that redirects to the Giveconomy section, but its not here**


![hh](https://github.com/user-attachments/assets/d7adaf63-c672-468b-a1f0-37781fe68ca4)


- Copy change on component on project details page for projects that are GIVbacks eligible is correct - **Pass**


When a project is Verified and Givback eligible - Pass

Project card - **Pass**
![gk](https://github.com/user-attachments/assets/b5ec5b62-cbe2-42b1-86bb-3719590d72e1)


Project details page - **Pass**
![fj](https://github.com/user-attachments/assets/32684162-028b-469f-85a9-15c497f136ea)


Project cards - **Pass**
![cg](https://github.com/user-attachments/assets/742b5793-f360-44ca-a2f2-0a622fb9c498)


- Donations to vouched projects on donation success page shows correct copy - **Pass**

![lk](https://github.com/user-attachments/assets/e0340f36-5b40-4ccb-af6a-61c822118030)


- Success page to Projects verified but not Givback eligible - **Pass**


![image](https://github.com/user-attachments/assets/e42607c1-d173-4e2f-afe1-3246e277e07a)


- Success page for Projects not verified and not eligible for Givbacks - **Pass**


![mm](https://github.com/user-attachments/assets/b91e6308-f915-496e-94f5-000cb9f74c91)




**However, from the Designs, we have a section showing the amounts raised by the Projects on the Success page, but it is missing on staging.**


Staging

![dfff](https://github.com/user-attachments/assets/61c90ba0-5a31-4404-af15-fec361f1aae2)




Design

![tu](https://github.com/user-attachments/assets/29a2af30-6310-4709-94c8-ac6442b78f48)

**Comment by mateodaza** [comment]
@LatifatAbdullahi @divine-comedian for this last point

`However, from the Designs, we have a section showing the amounts raised by the Projects on the Success page, but it is missing on staging.`

It was on purpose set to false and not display this part, was this maybe an old requirement? I can easily change it but just wanna be double sure

```
<DonatePageProjectDescription
     projectData={project}
     showRaised={false}
/>

```

**Comment by LatifatAbdullahi** [comment]
> @mateodaza **Seems the "Stake and lock" should be a hyperlink that redirects to the Giveconomy section, but its not here**
> 
> ![hh](https://private-user-images.githubusercontent.com/112261242/368333387-d7adaf63-c672-468b-a1f0-37781fe68ca4.png?

@mateodaza Also this "Stake and lock" section as Hyperlink

**Comment by mateodaza** [comment]
yes :) that'll be fixed  @LatifatAbdullahi

**Comment by mateodaza** [comment]
Here's the [PR](https://github.com/Giveth/giveth-dapps-v2/pull/4756)

**Comment by divine-comedian** [comment]
looks like it's been merged - can we  retest @LatifatAbdullahi ?

**Comment by LatifatAbdullahi** [comment]
Sure

**Comment by LatifatAbdullahi** [comment]
@mateodaza This section has not been updated to Hyperlink

![srr](https://github.com/user-attachments/assets/f22f0475-0cb2-4091-b4f3-75ea709982ea)








**All good with the missing Raised amounts** and all other sections

![rs](https://github.com/user-attachments/assets/b9379a49-5fd3-46c7-9055-acc8df74bc2e)


![ret](https://github.com/user-attachments/assets/6b9c097c-b8ee-4267-997e-a41df9dcac25)

**Comment by LatifatAbdullahi** [comment]
@mateodaza The hyperlink section has not been updated please take a look

**Comment by LatifatAbdullahi** [comment]
@mateodaza  @divine-comedian 

Test update - **Passed**


![kh](https://github.com/user-attachments/assets/1c50f6fc-13b7-4a0b-9366-520eb00e1a8e)
