### ISSUE TITLE
zkEVM branch testing bugs

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4599]
Testing on this branch: https://giveth-dapps-v2-git-addpolygonzkevmgivpower-givethio.vercel.app/givfarm

- [ ] The greyish/muted text should be white for all the staking modals:
![image](https://github.com/user-attachments/assets/7d53df3d-5077-44dc-979d-a94f43faa466)
![image](https://github.com/user-attachments/assets/452df50e-c7d8-49b2-bf84-4fe84dc68c83)

- [ ] View on PolygonScan... this should always just say "View on Block Explorer" so we avoid mistakes on different chains
- [ ] This branch thinks it's 1969 (check the lock until date...) is this a bug? or is this something to do with the branch?
![image](https://github.com/user-attachments/assets/9b219af4-6e19-490c-8fd1-59a9db5df902)

...gotta be a bug because my unlock date in locked GIV details is different: 
![image](https://github.com/user-attachments/assets/9b148bfe-3d6b-4e95-a988-f9909704383d)

- [ ] Somehow on this branch, the GIVstream expansion shows at 0% on other chains besides zkEVM. it should look the same regardless of the chain
![image](https://github.com/user-attachments/assets/210e0700-db09-43e9-9961-5d8c4cecb42a)

cc @LatifatAbdullahi @maryjaf

**Comment by maryjaf** [comment]
> : https://giveth-dapps-v2-git-addpolygonzkevmgivpower-givethio.vercel.app/givfarm

Should we test on this branch or on staging 

> * [ ]  This branch thinks it's 1969 (check the lock until date...) is this a bug? or is this something to do with the branch?

I did test of stake, lock ... on staging
Is this branch final for testing? @mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
@laurenluz  As @maryjaf said please test on staging.giveth.io.
 https://giveth-dapps-v2-git-addpolygonzkevmgivpower-givethio.vercel.app/givfarm is just for testing stake/unstake/harvest/lock on the zkevm mainnet , and other things might be broken because I haven't filled all needed data for the config of that preview link

**Comment by laurenluz** [comment]
ok sorry! this issue probably isn't relevant then, if you think it's all ok, we can close. I will test on staging.

**Comment by mohammadranjbarz** [comment]
> ok sorry! this issue probably isn't relevant then, if you think it's all ok, we can close. I will test on staging.

Thanks @laurenluz , yeah it would be better
