### ISSUE TITLE
At the start of a new QF round, we should enable some way by which we "check" the users MBD score

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4602]
In the data output from the giv-arb round, we had some donations with a recorded passport score but no recorded MBD score.

we need to make sure that the scores we have for users were recently checked... because they might change. So we should check a users qf-eligibility for the start of each QF round.

@CarlosQ96 had an idea whereby we could check the user's qf eligibility if it's a new QF round, something like:

impact graph receives JWT token => checks its valid => checks if scores are recently updated and updates if so  => pass

Carlos - feel free to add more context to this issue so that we can avoid the extra steps involved post-round!

cc @koday1

**Comment by CarlosQ96** [comment]
To test this issue lets coordinate a meeting. So basically:
1. Create a new round. Leave it active.
2. Check user MDB score before. (or a new user for it to have it null)
2. Donated on that round.
3. Cronjob should run and update the user score since he participated in the round (must be a valid donation, min usd, verified)

**Comment by maryjaf** [comment]
> To test this issue lets coordinate a meeting. So basically:
> 
> 1. Create a new round. Leave it active.
> 2. Check user MDB score before. (or a new user for it to have it null)
> 3. Donated on that round.
> 4. Cronjob should run and update the user score since he participated in the round (must be a valid donation, min usd, verified)

whether  I understand correctly? 
I donate with a user that have no MDB score,  and after donation we do some manual change that  score be updated and then we check that the new MDB score recorded correctly ? @CarlosQ96

**Comment by CarlosQ96** [comment]
Correct @maryjaf let me know when you are gonna test. I have the cronjob disabled at the moment.

**Comment by maryjaf** [comment]
I've donated with this user 0xf577Ae8b97d839B9c0522A620299DC08792c738c and the user has no MBD score for now  
https://optimism-sepolia.blockscout.com/tx/0x3bd49bbabe05dd6470cee8b671fcb54b6b30b602469763bd0c45f7fdac890eba

So now we should add manually score with this and then we check the cron job ? @CarlosQ96

**Comment by maryjaf** [comment]
I've donated with this new user: 0x6F1203f7e37D1F269885ee4ADCeFC0Ec2D3Fb261 , it's score is zero 
Round Id:90 @CarlosQ96

**Comment by CarlosQ96** [comment]
@maryjaf the 21 users got synced. Yours also with score of 0. I fixed the cronjob! runs every 15 mins

**Comment by maryjaf** [comment]
Thanks @CarlosQ96 It seems everything works as expected, we could call it Done
