### ISSUE TITLE
Streamline "adding qf matching results to the backend" so it's not a massive manual effort each time

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4603]
Right now, when a QF round ends, we do data analysis and matching calculations and then end up with a matching fund distribution that we send out via a multisig tx.

Then, a backend dev needs to manually input this data so that it shows up on the dapp.

We should build some way where this can be done fast & more efficiently, and perhaps without a dev (i.e. through AdminJS).

@CarlosQ96 would love your thoughts!

cc @koday1

**Comment by CarlosQ96** [comment]
Draft in progress. https://github.com/Giveth/impact-graph/pull/1799 
Just missing some small tweaks will leave for review.

**Comment by laurenluz** [comment]
on staging @CarlosQ96 ?

@maryjaf leave a comment if you need more context!

**Comment by CarlosQ96** [comment]
Yes staging!

**Comment by maryjaf** [comment]
> on staging @CarlosQ96 ?
> 
> @maryjaf leave a comment if you need more context!

Thanks @laurenluz I've checked the new button and records  in admin js but  I haven't understood the issue and how to be checked

**Comment by maryjaf** [comment]
When I try to search a round id or project id in f orund history page I got 500 error 
I enter Ids like as the mentioned format in the fields 

@CarlosQ96 
https://github.com/user-attachments/assets/349f8ec3-8d45-4166-b09a-206811caaece

**Comment by CarlosQ96** [comment]
@maryjaf thats an error on the copy of the text but just input the ID, Ill fix the text.

**Comment by maryjaf** [comment]
When I complete the  fields like as below screen record, the data is shown as expected in project donation table 

https://github.com/user-attachments/assets/425aaa8e-aac0-4d9f-b061-a4523af83fa6
<img width="1441" alt="Screenshot 2024-09-30 at 11 41 50 AM" src="https://github.com/user-attachments/assets/3cb57faa-ba74-4f6f-8df6-1560e80bf094">

Is there other scenarios to be checked  or this is whole thing that we want ? @CarlosQ96 @laurenluz

**Comment by CarlosQ96** [comment]
Yes just this for now @maryjaf, so someone can help me input the data jajajajaja

Ill add better options later but adminjs is a lot of work always. This is a start.
