### ISSUE TITLE
Stellar| Update QR code problem

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#4608]
**Describe the bug**
I see a new problem in "update QR code" scenario 
after the time is over by tapping on Update QR code for both below scenarios, I see the below pic 

- [ ] my user has a current pending donation
- [ ] my user has no pending donation

![image](https://github.com/user-attachments/assets/1485b1a8-bf48-44d5-ba9a-7cca82b13ac6)

_______

https://github.com/user-attachments/assets/c635a39a-46e4-42c9-bf13-528c8c3325fc

cc: @MoeNick

**Comment by MoeNick** [comment]
When the time is up we should change the status to failed, which means we have a hovered toast message above QR code and a failed red status.

**Comment by maryjaf** [comment]
> When the time is up we should change the status to failed, which means we have a hovered toast message above QR code and a failed red status.

When The time is up the below pic is shown, but by tapping on update QR code the expected result doesn't happen 

![image](https://github.com/user-attachments/assets/e88be929-50ef-453d-b6ed-e647f1413884)

tapping on Update QR code:

![image](https://github.com/user-attachments/assets/e88be929-50ef-453d-b6ed-e647f1413884)

**Comment by maryjaf** [comment]
This problem hasn't been fixed yet

- [ ] By tapping on Update QR code , and then tap on check donation the ID of previous donation is shown 
for example in below screen record 
- transaction id is 1002 
- this transaction is failed 
- by tapping on update qr code the same id is shown (1002)

@Meriem-BM 

https://github.com/user-attachments/assets/7c439c06-50d0-4bce-83a0-e9180ff29a2a

 
 

- [ ] and another problem is that some times when time is up the timer is showing 00:00 but the update QR code isn't shown , after refreshing the correct view for this scenario is shown 

https://github.com/user-attachments/assets/97f7a2e5-1ce5-4940-9013-360b8751ec42

**Comment by Meriem-BM** [comment]
> This problem hasn't been fixed yet
> 
> * [ ]  By tapping on Update QR code , and then tap on check donation the ID of previous donation is shown
>   for example in below screen record
> * transaction id is 1002
> * this transaction is failed
> * by tapping on update qr code the same id is shown (1002)
> 
> @Meriem-BM
> 
>  Screen.Recording.2024-08-26.at.1.01.00.PM.mov 
> * [ ]  and another problem is that some times when time is up the timer is showing 00:00 but the update QR code isn't shown , after refreshing the correct view for this scenario is shown
> 
>  Screen.Recording.2024-08-26.at.1.19.08.PM.mov

@maryjaf 
For the first point I keep the same draft donation and by clicking on update QR code I just update expiration date and status to pending, so it's normal.

**Comment by maryjaf** [comment]
> > This problem hasn't been fixed yet
> > 
> > * [ ]   By tapping on Update QR code , and then tap on check donation the ID of previous donation is shown
> >   for example in below screen record
> > * transaction id is 1002
> > * this transaction is failed
> > * by tapping on update qr code the same id is shown (1002)
> > 
> > @Meriem-BM
> > Screen.Recording.2024-08-26.at.1.01.00.PM.mov
> > 
> > * [ ]   and another problem is that some times when time is up the timer is showing 00:00 but the update QR code isn't shown , after refreshing the correct view for this scenario is shown
> > 
> > Screen.Recording.2024-08-26.at.1.19.08.PM.mov
> 
> @maryjaf For the first point I keep the same draft donation and by clicking on update QR code I just update expiration date and status to pending, so it's normal.

So the changing status from failed into pending is normal ?
in this case as you can see in below screen record if the receipt page of previous donation is open, the status is shown faild until user refresh it 
https://github.com/user-attachments/assets/2d53cfed-d117-4b0b-8278-105e46088c0f

cc: @MoeNick

**Comment by Meriem-BM** [comment]
> > > This problem hasn't been fixed yet
> > > 
> > > * [ ]    By tapping on Update QR code , and then tap on check donation the ID of previous donation is shown
> > >   for example in below screen record
> > > * transaction id is 1002
> > > * this transaction is failed
> > > * by tapping on update qr code the same id is shown (1002)
> > > 
> > > @Meriem-BM
> > > Screen.Recording.2024-08-26.at.1.01.00.PM.mov
> > > 
> > > * [ ]    and another problem is that some times when time is up the timer is showing 00:00 but the update QR code isn't shown , after refreshing the correct view for this scenario is shown
> > > 
> > > Screen.Recording.2024-08-26.at.1.19.08.PM.mov
> > 
> > 
> > @maryjaf For the first point I keep the same draft donation and by clicking on update QR code I just update expiration date and status to pending, so it's normal.
> 
> So the changing status from failed into pending is normal ? in this case as you can see in below screen record if the receipt page of previous donation is open, the status is shown failed until user refresh it
> 
>  Screen.Recording.2024-08-27.at.4.20.57.PM.mov 
> cc: @MoeNick

Yeah, that's also related to the event problem on staging that we trying to fix with DevOps team.

**Comment by maryjaf** [comment]
the problem related to update QR code hasn't been fixed @Meriem-BM 
-By tapping on update QR code the timer is resumed but the status in donation and receipt page remains failed 

https://github.com/user-attachments/assets/32c8cf5a-8745-46d8-959b-1bfc827457b2

**Comment by maryjaf** [comment]
Thanks @Meriem-BM This issue has been fixed
