### ISSUE TITLE
Backend: new category labels should be included with their subcategories

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#461]

**Comment by Cotabe** [comment]
I consider donors should be able to sort by location. Many donors want to donate to local initiatives.

**Comment by Cotabe** [comment]
Many projects are aligning their impact to the Sustainable Development Goals (SDGs). I think we should have them as categories or subcategories.

**Comment by mohammadranjbarz** [comment]
@MoeNick  It's done through https://github.com/Giveth/GIVeconomy/issues/655
