### ISSUE TITLE
Projects with $0 in QF round matching show "matching funds coming soon..." message instead of $0 

### ISSUE THREAD

**Issue by koday1** [Giveth/giveth-dapps-v2#4613]
After Carlos entered the matching fund data for projects in the GIV-Earth round, we discovered a bug where projects that received $0 in matching continued to show the message "Matching funds coming soon..." and "fund have not yet been sent. Please check back later." See below:
<img width="427" alt="Screen Shot 2024-08-20 at 9 56 54 AM" src="https://github.com/user-attachments/assets/7c661b7c-fade-4670-b796-d818aef76cf4">

This screenshot is from ecoToken https://giveth.io/project/ecotoken - they received a few donations but $0 in matching, yet this is the message under the donations tab -> GIV-Earth.

The other two projects with the same situation are https://giveth.io/project/menthol-protocol-blockchain-co2e-emissions-calculator & https://giveth.io/project/metameadow-boomtown-game. These projects should show $0, as they were qualified for the round but didn't receive any matching based on the COCM algorithm and/or eligibility of their donations. 

cc @CarlosQ96 @laurenluz

**Comment by RamRamez** [comment]
I tested on staging and couldn't reproduce this bug, I believe it's resolved. @koday1 Could you please test on staging and confirm it?

**Comment by koday1** [comment]
Hey @RamRamez I still see this bug on prod - EcoToken from my example above still shows "Matching funds coming soon..." for the GIV-Earth QF round, when it should show $0 in matching funds. 
![Screen Shot 2024-10-07 at 2 35 32 PM](https://github.com/user-attachments/assets/1050d38c-2129-467e-ac8e-157964c56ebf)

**Comment by RamRamez** [comment]
@maryjaf @LatifatAbdullahi please test and verify on production

**Comment by maryjaf** [comment]
I've checked on staging with this condition that the round is over and matching fund is not distributed yet,  the result is as expected 
@koday1 @RamRamez 

**if project has donation in round:**
<img width="1432" alt="Screenshot 2024-10-08 at 12 14 17 PM" src="https://github.com/user-attachments/assets/6f478277-4126-463e-a4a8-2975f7dab8df">

**if project has no donation in round:**
<img width="1395" alt="Screenshot 2024-10-08 at 12 13 53 PM" src="https://github.com/user-attachments/assets/6a1d93b1-fce8-45af-af7c-2da848a77d53">


but I haven't found why there is a tx link for 0 matching fund on production https://giveth.io/project/ecotoken?tab=donations


> ![kt](https://private-user-images.githubusercontent.com/112261242/374460384-f8e4ecca-6e24-4a41-a588-bb70cffb8110.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNzc5NjYsIm5iZiI6MTcyODM3NzY2NiwicGF0aCI6Ii8xMTIyNjEyNDIvMzc0NDYwMzg0LWY4ZTRlY2NhLTZlMjQtNGE0MS1hNTg4LWJiNzBjZmZiODExMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQwODU0MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjBjZDBkMmNkYTk1NDcyNTVhZjJhYmJjMjVhMTVhYTIxNzc1YTQxOTJhMjY3MTk0ZWYwOWVlNGQ5MjllZjdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.j8q_ms6ribVywbi5Uq84bQf8fAgovcqdnpl9miSf-tg)
>

**Comment by RamRamez** [comment]
> I've checked on staging with this condition that the round is over and matching fund is not distributed yet, the result is as expected @koday1 @RamRamez
> 
> **if project has donation in round:** <img alt="Screenshot 2024-10-08 at 12 14 17 PM" width="1432" src="https://private-user-images.githubusercontent.com/111529185/374484863-6f478277-4126-463e-a4a8-2975f7dab8df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MjAzNTMsIm5iZiI6MTcyODQyMDA1MywicGF0aCI6Ii8xMTE1MjkxODUvMzc0NDg0ODYzLTZmNDc4Mjc3LTQxMjYtNDYzZS1hNGE4LTI5NzVmN2RhYjhkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQyMDQwNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYzdhODRhNjU3ZGQ2YzMxN2I5OGQyMTU1ZGJiM2YyNmIwYzNjMDk4ZWIyMDNiNjMzZDBjOTA2YmU5NzMzNzE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9k941xAwLBy-_RXAQLVSWGhrBTzUQHlfArZf3z30L_I">
> 
> **if project has no donation in round:** <img alt="Screenshot 2024-10-08 at 12 13 53 PM" width="1395" src="https://private-user-images.githubusercontent.com/111529185/374484952-6a1d93b1-fce8-45af-af7c-2da848a77d53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MjAzNTMsIm5iZiI6MTcyODQyMDA1MywicGF0aCI6Ii8xMTE1MjkxODUvMzc0NDg0OTUyLTZhMWQ5M2IxLWZjZTgtNDVhZi1hZjdjLTJkYTg0OGE3N2Q1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQyMDQwNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNzc3MzcxNWIwMDJjMmFmNDJhODg1YjY2ZGE1YmNmY2RjMzU3MWNmZjZjZmU0YjBhMDZmZmEyOGQ3NmY1YmE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-unLTfFD6cxNw3iB-MiYgzG1aI8XhNZvR17XoMUgkn0">
> 
> but I haven't found why there is a tx link for 0 matching fund on production https://giveth.io/project/ecotoken?tab=donations @RamRamez @koday1
> 
> > ![kt](https://private-user-images.githubusercontent.com/112261242/374460384-f8e4ecca-6e24-4a41-a588-bb70cffb8110.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNzc5NjYsIm5iZiI6MTcyODM3NzY2NiwicGF0aCI6Ii8xMTIyNjEyNDIvMzc0NDYwMzg0LWY4ZTRlY2NhLTZlMjQtNGE0MS1hNTg4LWJiNzBjZmZiODExMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwOFQwODU0MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjBjZDBkMmNkYTk1NDcyNTVhZjJhYmJjMjVhMTVhYTIxNzc1YTQxOTJhMjY3MTk0ZWYwOWVlNGQ5MjllZjdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.j8q_ms6ribVywbi5Uq84bQf8fAgovcqdnpl9miSf-tg)

@koday1 do you confirm this?

**Comment by koday1** [comment]
Hey @maryjaf thanks for looking into this. The issue here is that not all donations in a round are eligible for matching. In EcoToken's case, they received $7.36 in donations from 3 accounts - but these accounts did not meet the Passport or MBD threshold and were not eligible for matching. So they were allocated $0 in matching funds, and the page should say "$0.00 Matching Funds" instead of "matching funds coming soon". This is an edge case to your above scenarios, but it's an important edge case as we are seeing this same thing with multiple projects in our recent QF rounds.

I believe this is fixed now per @RamRamez's update a few days ago. I think we can close the issue unless there is something else I am missing.

cc @laurenluz
