### ISSUE TITLE
monthly donated amount is showing incorrect number in recurring donation table

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4615]
On the recurring donations table in the my donations page the amount I am donating to each project is slightly incorrect compared to what was entered when I setup the recurring donation

![Image](https://github.com/user-attachments/assets/0c7cb432-e4b9-4d80-b747-d1adf24de3e4)

for example in the table above you can see some amounts show as `39.999999` or `99.99999` when the entered amount I chose to donate was 40 and 100 respectively. 

you can see on the project page on the recurring donations table it is showing the correct number - 100 - in place of 99.99999 for the same donation but on the my donations page. 

![Image](https://github.com/user-attachments/assets/9563052e-0149-4fb1-9ec2-811458c3ca1b)

the recurring donations table in the my donations page should show the correct whole number.

**Comment by divine-comedian** [comment]
@kkatusic what is the update on this? I see an open PR from a few weeks ago.

**Comment by maryjaf** [comment]
Thanks @kkatusic I've tested and the problem has been fixed on staging 

![image](https://github.com/user-attachments/assets/fa445295-d42f-4c43-946a-acf704ba9d19)
![image](https://github.com/user-attachments/assets/7fca9a1b-061d-4867-bba6-7add347a09c7)

**Comment by kkatusic** [comment]
@divine-comedian we done this? thx
