### ISSUE TITLE
UI issue in project page 

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#4621]
This problem that was reported in [dev channel ](https://discord.com/channels/679428761438912522/861692942645067777/1273602436514451498)  hasn't been fixed completely, as you can see in below pics

- [x]  the counter of tabs in project page isn't shown correctly 
- [ ] name of project and project owner

![image](https://github.com/user-attachments/assets/0707c89f-ca72-4458-b1bd-1c76683dfff7)
![image](https://github.com/user-attachments/assets/f7e407a5-df35-4eaf-8123-7937c464e68d)

cc: @divine-comedian

**Comment by divine-comedian** [comment]
@kkatusic do you mind picking his one up? it appears to only happen on STAGING

**Comment by maryjaf** [comment]
actually it isn't only related to project page, there are style, font and color changing in some modal like sign modal

**Comment by maryjaf** [comment]
> [ ] name of project and project owner

It seems this problem  hasn't been fixed @kkatusic

**Comment by maryjaf** [comment]
> actually it isn't only related to project page, there are style, font and color changing in some modal like sign modal

![image](https://github.com/user-attachments/assets/746a561c-4102-4c45-b38d-06390c24b12c)

**Comment by kkatusic** [comment]
@maryjaf , maybe you look at it before right build process finished, can you check it again on staging, thx:

https://staging.giveth.io/project/herbs-and-drugs-and-tools-to-combat-sleepiness

**Comment by maryjaf** [comment]
The project that has no banner :

staging:
![image](https://github.com/user-attachments/assets/08880159-3482-4f8e-af3f-ab86ad6e796a)


production:
![image](https://github.com/user-attachments/assets/aa7abeb2-5dcc-427e-8ffe-c119ff230915)

**Comment by kkatusic** [comment]
for me it is fine, can you test inside incognito mode?

![Screenshot 2024-08-28 at 16 16 17](https://github.com/user-attachments/assets/0242dc50-e736-498b-a659-0aac755bd04b)

**Comment by maryjaf** [comment]
and I still see this modal:
![image](https://github.com/user-attachments/assets/cc2b5086-6564-47c6-8fdf-ff5a9c42758d)

**Comment by maryjaf** [comment]
> for me it is fine, can you test inside incognito mode?

It's weird, have you checked it on staging?
I've checked on incognito and I see the same view like as before

**Comment by divine-comedian** [comment]
@maryjaf - tested too on brave and firefox, same for me on staging, also checked incognito

@kkatusic what OS are you running on your machine?

**Comment by kkatusic** [comment]
@maryjaf can you check it again when you get time: https://staging.giveth.io/project/herbs-and-drugs-and-tools-to-combat-sleepiness

@divine-comedian it wasn't problem by browser, something strange is here, nobody changed code for months I explicit defined color

**Comment by maryjaf** [comment]
> and I still see this modal: ![image](https://private-user-images.githubusercontent.com/111529185/362321481-cc2b5086-6564-47c6-8fdf-ff5a9c42758d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MTgzMDQsIm5iZiI6MTcyNDkxODAwNCwicGF0aCI6Ii8xMTE1MjkxODUvMzYyMzIxNDgxLWNjMmI1MDg2LTY1NjQtNDdjNi04ZmRmLWZmNWE5YzQyNzU4ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOVQwNzUzMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNTZkMDFhZTM1YjZkYmFhZjAzYjU4MWYwZWE3ZDk0M2M2YjQzNjEzNDU5MTljY2VhOTJiYmQzZWVkMGJkODE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UhX_FH3DztQN2ZdKIMqH7LJHbA2MCVk-gWsHgM39BUA)

.

**Comment by kkatusic** [comment]
@maryjaf maybe something was wrong with package that is listing this notification, red color was added by @divine-comedian 8 months ago:

https://github.com/Giveth/giveth-dapps-v2/blame/2bdb3c7a977c734735ff2a03b4b668ba103912de/src/components/modals/SignWithWalletModal.tsx#L248

it is gray color inside css property, but when you explicit add `color="red"` it should show red text. When @divine-comedian added this maybe everything was ok, after some time with new package update it disappear and it is fixed again. 

I'm still investigating this, if it is red for you and @divine-comedian than it is like it should be by code definition.

**Comment by maryjaf** [comment]
> > actually it isn't only related to project page, there are style, font and color changing in some modal like sign modal
> 
> ![image](https://private-user-images.githubusercontent.com/111529185/362292750-746a561c-4102-4c45-b38d-06390c24b12c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MjQ3ODIsIm5iZiI6MTcyNDkyNDQ4MiwicGF0aCI6Ii8xMTE1MjkxODUvMzYyMjkyNzUwLTc0NmE1NjFjLTQxMDItNGM0NS1iMzhkLTA2MzkwYzI0YjEyYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOVQwOTQxMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NzcxODRkNTZiY2VhYmVhMjhlYzViMGYzZTE2MDk3NmRhYmJlZjA0YmQwZmRlNmZiOWRmMWU3ZmE4NzJhNDQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YLAU6LRWQx-fvg1hYj7OXgkN5Tq_tdQQE5v24DJzeno)
> 
> ![image](https://private-user-images.githubusercontent.com/111529185/362294098-abc434ff-9298-4f61-b702-5fe9414c7e26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MjQ3ODIsIm5iZiI6MTcyNDkyNDQ4MiwicGF0aCI6Ii8xMTE1MjkxODUvMzYyMjk0MDk4LWFiYzQzNGZmLTkyOTgtNGY2MS1iNzAyLTVmZTk0MTRjN2UyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOVQwOTQxMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OGU5OTFhODg5NjYzMGVmNDY0YzE2NWJjOWMxYzc2OGE4N2IxN2JiNGZmOWM2ODc4Y2JjNjdmNjdhYjNkZjc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.v0Fl4rC8lf81JOU72v9yEFmXBonGsSrCXNAs6Upkcbc)

Production view of these 2 modals:

https://github.com/user-attachments/assets/32cc0f22-fde3-4d01-83f6-ec675a0de726

https://github.com/user-attachments/assets/38bf9ffb-fe1e-49dd-abd4-d2626edfc1d0

**Comment by kkatusic** [comment]
@maryjaf new PR is merged, you can test it again :)

**Comment by divine-comedian** [comment]
OK took me a sec to dig through the commits - I think I put this in to show when user is attempting to connect from Multisig but @mateodaza  changed the conditions outside of the element sometime in the last month. 

That would explain why even if the code was added 8 months we ago we only see it showing up now for regular users - the red notification text should show only when user is connecting through multisig app

**Comment by kkatusic** [comment]
@maryjaf, cc @divine-comedian, red notification fixed only for multisig app, you can test it.

**Comment by maryjaf** [comment]
> @maryjaf, cc @divine-comedian, red notification fixed only for multisig app, you can test it.

The Note is removed 

![image](https://github.com/user-attachments/assets/3f60b9b4-9796-423c-a8eb-d03feb1d7e43)


Multisig:

![image](https://github.com/user-attachments/assets/c7817965-ec8a-4fc0-9974-547156f2305f)

**Comment by kkatusic** [comment]
@divine-comedian, @maryjaf tested this if you are ok we can close this one?

**Comment by divine-comedian** [comment]
@kkatusic @maryjaf I think we still had the issue of the project banner text still showing in the wrong format, but imho as long as it's not on production we can move on from this issue.

**Comment by kkatusic** [comment]
@divine-comedian, cc @maryjaf, for me is fine now, can you share your screenshot?

![Screenshot 2024-09-03 at 13 20 48](https://github.com/user-attachments/assets/bf7e7d54-1e87-43c8-90e0-62bbe65071ac)

**Comment by divine-comedian** [comment]
looks good now for me too :) 
![image](https://github.com/user-attachments/assets/cb788b0f-87c4-49a8-ae0d-2b2c8e1b0a33)


I'll move it to DONE
