### ISSUE TITLE
When the time is over, by tapping on back and then create a new donation an error happens 

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#4627]
**Describe the bug**
- When the time is over
- by tapping on back icon and then create a new donation 
- I expect a new pending trn be created but the wrong view is shown like as below screen record

The time is over and donation is failed:
https://github.com/user-attachments/assets/fea2a762-5f22-47c8-9f80-0014cd15da47

the time is over and donation is success:

https://github.com/user-attachments/assets/853be578-8fdd-4da0-b08e-bcd812182257

please take a look on this @Meriem-B 

cc: @MoeNick

**Comment by Meriem-BM** [comment]
@maryjaf can retest this please

**Comment by maryjaf** [comment]
> @maryjaf can retest this please

It hasn't been fixed @Meriem-BM 


https://github.com/user-attachments/assets/d04b4dce-8e7f-4ded-8c43-5ba2358dfe7c

**Comment by maryjaf** [comment]
This problem has been fixed, Thanks @Meriem-BM
