### ISSUE TITLE
Assign balance to GIVpower unipool distributor to spend GIV from the zkEVM token distro

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4630]
The notify reward balance info is all in #4434 

We should basically assign a balance to the unipool distributor of:
- 159,050 GIV if rewards start Sept 3
- 127,900 GIV if rewards start Sept 17

**Comment by mohammadranjbarz** [comment]
@aminlatifi I have a question, which one is better, WDYT?
* Assign balance myself then transfer the ownership
* Transfer the ownerships and then assign balance by creating multisig tx, ...

**Comment by aminlatifi** [comment]
> @aminlatifi I have a question, which one is better, WDYT?
> 
> * Assign balance myself then transfer the ownership
> * Transfer the ownerships and then assign balance by creating multisig tx, ...

I prefer the second one, people can audit

**Comment by mohammadranjbarz** [comment]
> > @aminlatifi I have a question, which one is better, WDYT?
> > 
> > * Assign balance myself then transfer the ownership
> > * Transfer the ownerships and then assign balance by creating multisig tx, ...
> 
> I prefer the second one, people can audit

Makes sense, thank you

**Comment by mohammadranjbarz** [comment]
@laurenluz  @divine-comedian All the ownership has been transferred to Giveth multi sig address, who will create the TX for calling assign balance ?
https://github.com/Giveth/giveth-dapps-v2/issues/4631

**Comment by divine-comedian** [comment]
tx is here! 
https://app.safe.global/transactions/tx?id=multisig_0xaF4D68B8084b01D2c8120120497511035A2ea3a1_0x6f1b2f782d6b25f999c023d90653e521b41857f6675173f77fef20d27ec485dc&safe=zkevm:0xaF4D68B8084b01D2c8120120497511035A2ea3a1

**Comment by laurenluz** [comment]
excellent!

**Comment by laurenluz** [comment]
That issue he linked should be calling the assign function from the token distro to give a balance to the unipool.

this was the issue to add more tokens to the token distro: https://app.onchainden.com/safes/gno:0xd10bac02a02747cb293972f99981f4faf78e1626/transactions/0xa601afa7afac4b3cf4f6cf23145d681725f49c853aa1b1e32393c99f3352f9aa

I'm assuming @divine-comedian moved them already, or is moving them today, maybe he can confirm?

**Comment by laurenluz** [comment]
oh sorry, that tx mitch shared is actually to set up the givbacks distributor.

I asked mitch to set up the other tx to assign the balance to the unipool distributor: 0xc790f82bf6f8709aa4a56dc11afad7af7c2a9867

from https://www.notion.so/giveth/Deployment-52935e6579034f1b940bbef161e82229

with a balance of 159,050 GIV 

from https://github.com/Giveth/giveth-dapps-v2/issues/4434

I think it's right. @aminlatifi or @mohammadranjbarz please confirm

**Comment by mohammadranjbarz** [comment]
> oh sorry, that tx mitch shared is actually to set up the givbacks distributor.
> 
> I asked mitch to set up the other tx to assign the balance to the unipool distributor: 0xc790f82bf6f8709aa4a56dc11afad7af7c2a9867
> 
> from https://www.notion.so/giveth/Deployment-52935e6579034f1b940bbef161e82229
> 
> with a balance of 159,050 GIV
> 
> from #4434
> 
> I think it's right. @aminlatifi or @mohammadranjbarz please confirm

Yeah thanks, it's right

**Comment by laurenluz** [comment]
it's done https://zkevm.polygonscan.com/tx/0x4d8716810c4f9aed8ecfdea719508ee70225c3c721b70dacdea872ab347d6fd3
