### ISSUE TITLE
Transfer ownership of GIV token contracts on zkEVM to the main giveth multisig on zkEVM

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4631]
After we are done deploying & setting everything up, we should do the final housekeeping, transfer the ownership to the giveth main multisig...

zkevm:0xaF4D68B8084b01D2c8120120497511035A2ea3a1

this should be the main giveth multisig on polygon zkEVM - @mohammadranjbarz & @aminlatifi  you should be a signers too.

**Comment by aminlatifi** [comment]
@mohammadranjbarz We must have a call to do it

**Comment by mohammadranjbarz** [comment]
@laurenluz  I did them with help of @aminlatifi 
The checklist and TXs are in the notion

https://www.notion.so/giveth/Deployment-52935e6579034f1b940bbef161e82229?pvs=4#b1fcedbc68be4d238668566dc15ffe60

**Comment by laurenluz** [comment]
all done, right @mohammadranjbarz can we close?

**Comment by mohammadranjbarz** [comment]
> all done, right @mohammadranjbarz can we close?

Sure
