### ISSUE TITLE
Stellar | Allow redundant addresses for Stallar if their MEMO is diffrent

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#4645]
If some project owners going to use a similar exchange like LBank, all their addresses will be the same but with different MEMOs, so we should consider this case. 
It should be unique for each project, if 2 projects are using the same addresses at least they have to have different MEMOs. We should check this on the backend side on save and edit. 

![image](https://github.com/user-attachments/assets/77b5f9cc-2d8f-4a7c-872e-e65eb91c889f)

CC: @maryjaf

**Comment by Meriem-BM** [comment]
Hey @MoeNick will we should change the error message too?

**Comment by MoeNick** [comment]
Good catch @Meriem-BM 
if the user puts the same address and MEMO we should say:
`This address is already used for another project with the same MEMO. Please enter a different address or a different MEMO. `

Thanks

**Comment by maryjaf** [comment]
There is a UI problem in this modal when user enters a repetitive address and memo
@Meriem-BM 

https://github.com/user-attachments/assets/1fb2c0d6-d3ba-40c7-86cc-e8d33de2d667

**Comment by Meriem-BM** [comment]
> There is a UI problem in this modal when user enters a repetitive address and memo [@Meriem-BM](https://github.com/Meriem-BM)
> 
>  Screen.Recording.2024-09-02.at.1.04.06.PM.mov

@maryjaf I can't see this UI misplacement, I tested on Brave, Chrome, Arc

**Comment by Meriem-BM** [comment]
Oh, got it, it happens when I opened console down.
