### ISSUE TITLE
Stellar | Copy change on failed donation QR page

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#4646]
instead of this copy on this page, please say `The time is up.` 
![image](https://github.com/user-attachments/assets/3e01ff51-dbec-4707-a9c0-4229f8e89b70)

FYI: @maryjaf

**Comment by maryjaf** [comment]
![image](https://github.com/user-attachments/assets/abaa5e4b-61bf-4b92-83ee-92460186f6dd)
