### ISSUE TITLE
Stellar | Having a link to receipt page on success page. 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#4647]
As a user I want to see the link with `Check Donation` text with that same formatting we have in QR page here in the yellow area that opens another page linking to the transaction page. 
![image](https://github.com/user-attachments/assets/b3b9ca6f-2a67-4adf-bd77-96d1a9d003c1)

**Comment by MoeNick** [comment]
![image](https://github.com/user-attachments/assets/ab7d1d67-3cb6-4344-9c36-7e8469a13a15)
I mean this formatting

**Comment by Meriem-BM** [comment]
Is this okay? 

![Image](https://github.com/user-attachments/assets/c107210d-5bd8-4270-9146-678fdd4cb122)


> ![image](https://github.com/user-attachments/assets/ab7d1d67-3cb6-4344-9c36-7e8469a13a15) I mean this formatting

**Comment by MoeNick** [comment]
Thanks, Please remove the `s` - "Check Donation"  is perfect.

**Comment by maryjaf** [comment]
![image](https://github.com/user-attachments/assets/10f6566d-c310-4180-af3c-89a5ee709e17)
