### ISSUE TITLE
Stellar | The success donation page isn't shown in a certain scenario

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#4651]
**Describe the bug**
when I complete the donation flow in last seconds, after time is up the status of donation is changed to success correctly but the success donation page isn't shown like as below screen record

https://github.com/user-attachments/assets/dcdf708e-2d73-4ef9-94bd-f9da0e1da804

@Meriem-B @MoeNick

**Comment by maryjaf** [comment]
> **Describe the bug** when I complete the donation flow in last seconds, after time is up the status of donation is changed to success correctly but the success donation page isn't shown like as below screen record
> 
>  Screen.Recording.2024-08-29.at.4.26.55.PM.mov 
> [@Meriem-B](https://github.com/Meriem-B) [@MoeNick](https://github.com/MoeNick)

This issue hasn't been fixed
The below pic is the view that I've seen in this scenario 

![Image](https://github.com/user-attachments/assets/dd250565-a914-4564-81cb-7b3cee72b2c5)

Is this accepted ? or the success donation page should be shown ? @MoeNick @Meriem-BM

**Comment by Meriem-BM** [comment]
> > **Describe the bug** when I complete the donation flow in last seconds, after time is up the status of donation is changed to success correctly but the success donation page isn't shown like as below screen record
> > Screen.Recording.2024-08-29.at.4.26.55.PM.mov
> > [@Meriem-B](https://github.com/Meriem-B) [@MoeNick](https://github.com/MoeNick)
> 
> This issue hasn't been fixed The below pic is the view that I've seen in this scenario
> 
> ![Image](https://private-user-images.githubusercontent.com/111529185/363649743-dd250565-a914-4564-81cb-7b3cee72b2c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNzc0NjYsIm5iZiI6MTcyNTI3NzE2NiwicGF0aCI6Ii8xMTE1MjkxODUvMzYzNjQ5NzQzLWRkMjUwNTY1LWE5MTQtNDU2NC04MWNiLTdiM2NlZTcyYjJjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMlQxMTM5MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzgwZTA3M2YxMzRlMTM4NjY1YzVmODVjNTdhMjQyYWNlODhjMjI4NWQ3NTljNTA4YjJhOTkwY2YwY2JhNTUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SRTTpP5k14YJE5_suhT4JvqR_kBH6yycz2hIeB_l628)
> 
> Is this accepted ? or the success donation page should be shown ? @MoeNick @Meriem-BM

No, it should show the success page

**Comment by maryjaf** [comment]
Thanks @Meriem-BM This issue has been fixed
