### ISSUE TITLE
Add GIvpower from zkEVM to our Giveth snapshot strategy

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4652]
This is the POW token on zkEVM 0xc790f82bF6F8709aa4A56dc11afaD7aF7C2a9867

We should make sure we include it in our snapshot strategy! @divine-comedian can you edit it and add that in time for our next vote?

cc @mohammadranjbarz

**Comment by divine-comedian** [comment]
DONE 
![image](https://github.com/user-attachments/assets/0e019354-e28f-44e5-8cef-0e066f0fb375)

**Comment by laurenluz** [comment]
HERO
