### ISSUE TITLE
Stellar | Remind users to sign-in to be eligible for GIVbacks

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#4658]
Hey guys! I was testing the flow today and wanted to add a comment related to this issue: 

For me it wasn't obvious that if I'm not signed in with my EVM profile I won't get GIVbacks! It would be nice to remind me if I'm  not signed in that I should do it, otherwise I'll miss out on GIVbacks! 

![Image](https://github.com/user-attachments/assets/f3b4b84c-badf-4692-aa36-d298c1742af2)

_Originally posted by @divine-comedian in https://github.com/Giveth/giveth-dapps-v2/issues/4582#issuecomment-2318702426_

**Comment by MoeNick** [comment]
Hey @Meriem-B , based on the above report: 

Please add a toast message under the `Next`

"Sign in with your ETH address to be eligible for GIVbacks. Learn More." 
Link learn more to https://docs.giveth.io/giveconomy/givbacks
"learn more" will be right aligned with the formatting of our design system, you can find the formatting in the code base by searching lear more, we have in other pages. if you can't in i icon (information icon) would be sufficient. 

FYI: @maryjaf

**Comment by Meriem-BM** [comment]
> Hey [@Meriem-B](https://github.com/Meriem-B) , based on the above report:
> 
> Please add a toast message under the `Next`
> 
> "Sign in with your ETH address to be eligible for GIVbacks. Learn More." Link learn more to https://docs.giveth.io/giveconomy/givbacks "learn more" will be right aligned with the formatting of our design system, you can find the formatting in the code base by searching lear more, we have in other pages. if you can't in i icon (information icon) would be sufficient.
> 
> FYI: [@maryjaf](https://github.com/maryjaf)

Hey @MoeNick if you can share a capture, that will be helpful

**Comment by MoeNick** [comment]
![image](https://github.com/user-attachments/assets/2b9b21dd-1c00-42c6-991c-699c9e5ffbc2)

Please add a toast message under the `Next` button, similar with this formatting. 

"Sign in with your ETH address to be eligible for GIVbacks. Learn More."
Link learn more to https://docs.giveth.io/giveconomy/givbacks

**Comment by maryjaf** [comment]
![Image](https://github.com/user-attachments/assets/43ad2db8-e857-4918-9ca0-66078e09d373)

**Comment by Meriem-BM** [comment]
> And is it possible to change the formating @Meriem-BM like teh standard toast message I shared above?
> 
> 
> 
> CC: @maryjaf

Yes I did, can you check @maryjaf

**Comment by maryjaf** [comment]
![image](https://github.com/user-attachments/assets/4447a012-abf4-4fb6-b563-cf1833a3a787)

**Comment by Meriem-BM** [comment]
> ![image](https://private-user-images.githubusercontent.com/111529185/363943471-4447a012-abf4-4fb6-b563-cf1833a3a787.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNjEzNzQsIm5iZiI6MTcyNTM2MTA3NCwicGF0aCI6Ii8xMTE1MjkxODUvMzYzOTQzNDcxLTQ0NDdhMDEyLWFiZjQtNGZiNi1iNTYzLWNmMTgzM2EzYTc4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwM1QxMDU3NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMzg4ODIxZjNlMTQ4OWUzODg4MGZkOTdjZGNmMjI3MzllOWM3ZmVkMzA2YmY1YTI3YWU0NjliMTVmZjE1ODZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0ZtIsh_ndSMGK2xhUIJD4n80ASkffqPzx841RaVjzDo)

I'll make a change to look exactly like one above (use the same component)

**Comment by MoeNick** [comment]
The copy as I mentioned above should be like this: 
"Sign in with your ETH address to be eligible for GIVbacks. Learn More." @Meriem-BM

**Comment by Meriem-BM** [comment]
![Screenshot 2024-09-03 at 13 21 10 (2)](https://github.com/user-attachments/assets/e423f895-30d6-4c54-b25c-2868b51c4c98)

@MoeNick

**Comment by MoeNick** [comment]
Thanks

**Comment by maryjaf** [comment]
> ![Screenshot 2024-09-03 at 13 21 10 (2)](https://github.com/user-attachments/assets/e423f895-30d6-4c54-b25c-2868b51c4c98)
> 
> [@MoeNick](https://github.com/MoeNick)

I see this on staging 

Desktop:

![Image](https://github.com/user-attachments/assets/60806a43-7914-4523-a647-8ab302153f50)

Mobile:

**Comment by Meriem-BM** [comment]
> > ![Screenshot 2024-09-03 at 13 21 10 (2)](https://github.com/user-attachments/assets/e423f895-30d6-4c54-b25c-2868b51c4c98)
> 
> > 
> 
> > [@MoeNick](https://github.com/MoeNick)
> 
> 
> 
> I see this on staging 
> 
> 
> 
> **Desktop:**
> 
> 
> 
> ![Image](https://github.com/user-attachments/assets/60806a43-7914-4523-a647-8ab302153f50)
> 
> 
> 
> _________
> 
> 
> 
> **Mobile:**
> 
> 
> 
> ![IMG_3921](https://github.com/user-attachments/assets/a2f469f0-93ba-4245-a2e3-8156265e6dec)
> 
> 

For the capture I shared it still on code review.
