### ISSUE TITLE
Stellar | check to show GIVback components, if users is not eligible. 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#4659]
Also! If I'm not signed in and make a successful donation I shouldn't see the GIVbacks component on the donation success page, since I won't actually get GIVbacks 

![Image](https://github.com/user-attachments/assets/71c056fd-53ca-4d4e-9a52-0bf6f9cfe44c)

_Originally posted by @divine-comedian in https://github.com/Giveth/giveth-dapps-v2/issues/4582#issuecomment-2319142373_

**Comment by MoeNick** [comment]
Based on the above report @Meriem-B 

We should check the users eligibility with these conditions:

1. Project is verified
2. Token is GIVback eligible
3. User is signed in

Those conditions would be effective on 

1. GIVback icon on token logo
2. The toast message on reminding to sign in 
3. the GIVback components on success page.

FYI: @maryjaf

**Comment by maryjaf** [comment]
> * GIVback icon on token logo

So when my user isn't signed in, the GIVback eligible icon shouldn't be shown? @MoeNick
Now in this case the givback icon is shown @Meriem-BM 


![Image](https://github.com/user-attachments/assets/099ab57a-fbe6-4788-83ac-fc409beef55e)

**Comment by maryjaf** [comment]
The showing of  GIVback components on success page works as expected 

Not signed user :

![Image](https://github.com/user-attachments/assets/b6bb8d0f-dc38-4a92-b999-1a632c7f2638)



Sign user:

![Image](https://github.com/user-attachments/assets/bf8bf6ef-84ef-45b3-9da3-663026b4b632)

**Comment by MoeNick** [comment]
> > * GIVback icon on token logo
> 
> So when my user isn't signed in, the GIVback eligible icon shouldn't be shown? @MoeNick Now in this case the givback icon is shown @Meriem-BM
> 
> ![Image](https://private-user-images.githubusercontent.com/111529185/363661232-099ab57a-fbe6-4788-83ac-fc409beef55e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNTc5OTIsIm5iZiI6MTcyNTM1NzY5MiwicGF0aCI6Ii8xMTE1MjkxODUvMzYzNjYxMjMyLTA5OWFiNTdhLWZiZTYtNDc4OC04M2FjLWZjNDA5YmVlZjU1ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwM1QxMDAxMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZTVmYjU5NGUwOTJlMWU5MTQwMTVlMDkwN2E4ODhjZjlhOGEzNWVlZjUwNDdhZThiZjFkMzdjYThmODdmNzg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G_MOmq5PryFj8bqfxfanBoWq-fAT7FMuJEahu8qWOh4)

I think it's fine @maryjaf , user can see the icon and givback eligibility toast message. so lets put it in done

**Comment by MoeNick** [comment]
And is it possible to change the formating @Meriem-BM like teh standard toast message I shared above?
