### ISSUE TITLE
change copy on project verification form to "GIVbacks Eligiblity form"

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4663]
we should change the text on this form and all places visible from project owner view regarding project verification form to GIVbacks Eligiblity form - until we are ready to move to Impact Audits

**Comment by maryjaf** [comment]
The button isn't shown correctly on my device
Chrome / Mac
![image](https://github.com/user-attachments/assets/e8908878-4fb2-4c23-8569-8adf893191b6)

**Comment by divine-comedian** [comment]
should be fixed on production in #4708
