### ISSUE TITLE
Address showing twice on user profile page

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#4664]
When I navigate to a users profile page, I can see that the profile picture has a strange alignment and the wallet address shows double.

For example:
![image](https://github.com/user-attachments/assets/d662f479-7b36-4853-807c-8f8afda2b388)
https://giveth.io/user/0x173D87dfa68aEB0E821C6021f5652B9C3a7556b4

@MohammadPCh I can see that youre listed as tech lead for FE so I will assign you. <3

**Comment by maryjaf** [comment]
This problem had been fixed .
