### ISSUE TITLE
changed verified badge to vouched and show givbacks eligible badge on projects

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4670]
We'll need to make minor changes to how project badges are handled on Giveth. 

- If a project has been vouched for by 3 projects (i.e `verified=true`) we should show the current Verified badge but change the text to "Vouched"

![Image](https://github.com/user-attachments/assets/e7b53e16-d798-4e67-b29c-ab522d7d1032)

- If a project is GIVbacks Eligible we should show the Vouched badge AND a GIVbacks eligible badge

### making a project "vouched" status 
- go to admin panel
- select under "Project" tab and choose a project to make vouched
- click verify button
![Image](https://github.com/user-attachments/assets/b381e22d-13a5-4ba4-b711-b75f03eae143)
- should see vouched badge appear on project card and project details page 
- should NOT see GIVbacks eligible badge appear on project card and project details page

### making a project GIVbacks Eligible
- check if project has submitted "GIVbacks Eligiblity" form (formerly verification form) 
- go to admin panel, "Project Verification Form" tab
- find application form from given project 
- press approve project button
![Image](https://github.com/user-attachments/assets/48bc1f96-6d64-47ff-b1be-ecba216b744e)
- project should have both Vouched and GIVbacks Eligible badge on project card and project details page

**Comment by divine-comedian** [comment]
@Tosinolawale please provide updates here once the designs are ready

**Comment by Tosinolawale** [comment]
![Project Single - About](https://github.com/user-attachments/assets/6b0f566f-c4a1-4ec4-8268-80b287f193d1)
![Project Card Base](https://github.com/user-attachments/assets/ba707925-97f4-43ec-bcce-b955d0aaaea7)

https://www.figma.com/design/fHpNMd8Q9iBrAr6kBj9oo5/DeVouch-Giveth-Integration?node-id=8326-7009&t=apu4QylZN67xGsSA-1
@divine-comedian

**Comment by divine-comedian** [comment]
@mateodaza this issue should be ready for you now - we'll need this for the first version of decentralized verification

**Comment by divine-comedian** [comment]
> @divine-comedian for extra clarification "Vouched" in the card means having verified=true "You've already vouched" means connected user vouched for this particular project

yep you got it exactly

**Comment by LatifatAbdullahi** [comment]
@divine-comedian @mateodaza 


**Test Update**




Project Vouched or verified from the Admin but not GIVback Eligible - **Pass**

Project card

![vc](https://github.com/user-attachments/assets/6470b93c-df7c-4fb8-9082-7c3f24654165)


Project details page

![ri](https://github.com/user-attachments/assets/417a2e92-76d4-45a6-b729-ab6fc565c0fc)




Project Vouched or verified from the Admin and GIVback Eligible - **Pass**

Project card
![lov2](https://github.com/user-attachments/assets/e4a93871-dc2b-4cc7-b19d-e4f559bd3477)



Project details page

![lov](https://github.com/user-attachments/assets/fc461c12-6463-4c85-b075-266b1b1e4e99)
