### ISSUE TITLE
We should use our GIV linktree for all "bridge your GIV" and "get more GIV" prompts for every chain & wallet not connected

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4673]
This is the link we should send people to. we have get more GIV on the GIV staking page & GIVfarm: 
https://linktr.ee/GIVtoken

- [x] on the GIVfarm page, both these things should be replaced w/ a single link that says "Get or bridge GIV" and goes to the linktree
![image](https://github.com/user-attachments/assets/b3e2f7a7-9629-4455-a36b-dead18571ac9)
- [x] when the user is staking on any chain for GIVpower, the "get more GIV" link should go to the linktree
![image](https://github.com/user-attachments/assets/7e619b7f-90bb-46e2-8382-ffcb820150e5)

@mohammadranjbarz can you assign the right person?

**Comment by LatifatAbdullahi** [comment]
@laurenluz  Both links have been updated as requested

**Buy Giv Token**


https://github.com/user-attachments/assets/e9d167b1-4b94-4543-b1d1-04e865d8982a




**Get more GiV**

https://github.com/user-attachments/assets/34c0e816-4734-4a04-958b-7f6014b5112a

**Comment by laurenluz** [comment]
@mohammadranjbarz make sure that the font color of the copy for the giv token contract address & the get/bridge link out are the same... either both greyish or both white... this way looks a bit weird.

![image](https://github.com/user-attachments/assets/67b0f4dc-6d3a-464d-92f6-ba57776b1112)

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz make sure that the font color of the copy for the giv token contract address & the get/bridge link out are the same... either both greyish or both white... this way looks a bit weird.
> 
> I think the best is to make them both greyish
> 
> ![image](https://private-user-images.githubusercontent.com/75490971/364144698-67b0f4dc-6d3a-464d-92f6-ba57776b1112.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3MTIxNzcsIm5iZiI6MTcyNTcxMTg3NywicGF0aCI6Ii83NTQ5MDk3MS8zNjQxNDQ2OTgtNjdiMGY0ZGMtNmQzYS00NjRkLTkyZjYtYmE1Nzc3NmIxMTEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDEyMjQzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3MTg1M2NkNDhlNWNkYjc3ZmVjYzg4MWE0ODNjZDQ4NDJjZGVmNjliODJlMDAwNmY2MzAyYTc0MWYwMzVhMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4v59ijRgt82ynNO15im7ZNgsXL0uVL0K8pesJU5peFg)

Do you mean we should make it grey or the cyan is good like below image?

<img width="1489" alt="Screenshot 1403-06-18 at 11 17 12 in the morning" src="https://github.com/user-attachments/assets/afab1818-1ded-40e1-b47f-0bfbcd835a3e">

**Comment by laurenluz** [comment]
cyan :-D I mean like "gray vibes" rather then specifically gray... that looks good in the image you put!

**Comment by mohammadranjbarz** [comment]
> cyan :-D I mean like "gray vibes" rather then specifically gray... that looks good in the image you put!

Awesome :))
@LatifatAbdullahi  @maryjaf It's ready to test https://staging.giveth.io/givfarm

**Comment by LatifatAbdullahi** [comment]
@laurenluz 

The update has been made on staging.

![FN](https://github.com/user-attachments/assets/87da87f9-646b-4df1-ae9c-1c802815c533)
