### ISSUE TITLE
Update banner for GIV-a-Palooza QF round

### ISSUE THREAD

**Issue by koday1** [Giveth/giveth-dapps-v2#4674]
We need to update the banner for the GIV-a-Palooza QF round, which starts September 10. 

Here is the Figma link: https://www.figma.com/design/W9Ace1RyCdykWM72fsSa3t/Giveth-Marketing-2024?node-id=7752-2879&t=f17tgIac7jHPXhYk-4

This will be live at https://giveth.io/qf

**Comment by divine-comedian** [comment]
@koday1 @laurenluz is this issue complete?

**Comment by koday1** [comment]
@divine-comedian Yep closing it out!
