### ISSUE TITLE
GIVbacks page changes corresponding to new GIVbacks changes - on prod by Sept 16

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4679]
Starting on September 17, we will have a minimum $5 donation requirement for GIVbacks eligibility, plus we are experimenting with the raffle & with decentralized verification, here are some changes I think we can/should make:

## [GIVbacks Page ](https://giveth.io/givbacks)

- [x] givbacks page, title subtext: "When you make a donation of $5 or more to a GIVbacks eligible project you qualify to get GIV!"
![image](https://github.com/user-attachments/assets/77e852d6-25b3-4962-a862-f4d5d3086f99)

- [x] givbacks page, remove all this:
![image](https://github.com/user-attachments/assets/314e4b0e-41bf-405d-9bcc-0191dd5f7f3a)

- [x] Change "GIV Allocated to Round" to "GIVbacks Rewards"
![image](https://github.com/user-attachments/assets/bfe6a1aa-5eb4-4665-8415-b343693b2b0a)

- [x] Change hard coded 1 Million GIV to a dynamic number from https://github.com/Giveth/giveth-dapps-v2/issues/4678 (if possible)

- [x] Change GIVbacks box copy title "When you give you get GIV back!" to "Give and get GIV back!"
![image](https://github.com/user-attachments/assets/12675a71-450f-4c82-89e9-6ffcb333ef10)

- [x] Change GIVbacks box copy subtext to: "Each GIVbacks round lasts two weeks. The GIVbacks Rewards available depends on the amount donated at in the round, to a maximum amount of 1 million GIV. After the End Date, the GIVbacks Rewards for the round go to the eligible donors."
![image](https://github.com/user-attachments/assets/e13553ce-dad6-4ef7-9915-da0d77a67607)

- [x] Comment out "why don't I have GIVbacks" part and corresponding modal
![image](https://github.com/user-attachments/assets/40c6027f-f117-49f6-a9e3-a254db70dfd5)

@mohammadranjbarz can you assign the right person?

**Comment by laurenluz** [comment]
cc @WhyldWanderer

**Comment by mohammadranjbarz** [comment]
@maryjaf  @laurenluz  Can you check the preview link https://giveth-dapps-v2-git-4679modifygivbackchangetobe-210dfd-givethio.vercel.app/givbacks

When for any reason FE request fails and can't get the result, or it is zero I show **?** is it ok?


@maryjaf As we have 1 hour cache you can't check it in FE to see if it works properly or not, so it's better to test webservice

```
curl --location 'https://impact-graph.serve.giveth.io/graphql' \
--header 'Content-Type: application/json' \
--data '{"query":"query {\n    allocatedGivbacks(\n        refreshCache:true\n    ){\n            usdValueSentAmountInPowerRound\n            allocatedGivTokens\n            givPrice\n            date\n    }\n}","variables":{}}'
```

And send `refreshCache:true` to get updated result

**Comment by laurenluz** [comment]
hmmm it's showing me "?" right now - is it likely the FE request is failing right now?

ideally, we should the last updated GIVbacks pool amount until the FE can get the new value... so if last time it was working the GIVbacks pools size is 50,000 GIV, we should that, rather than "?"

If it's the start of a new round though, and we are having issues, not getting the data, maybe "TBD" is better than "?" :)

**Comment by maryjaf** [comment]
Thanks @mohammadranjbarz The copy fixes has been applied correctly on feature branch
but for testing the web service I have a question 

By donating on staging, the "allocatedGivTokens"  in response of api should be increased? 
{
    "data": {
        "allocatedGivbacks": {
            "usdValueSentAmountInPowerRound": 0,
            "allocatedGivTokens": 0,
            "givPrice": 0.00584277,
            "date": "2024-09-15T07:45:17.709Z"
        }
    }
}

**Comment by mohammadranjbarz** [comment]
> Thanks @mohammadranjbarz The copy fixes has been applied correctly on feature branch but for testing the web service I have a question
> 
> By donating on staging, the "allocatedGivTokens" in response of api should be increased? { "data": { "allocatedGivbacks": { "usdValueSentAmountInPowerRound": 0, "allocatedGivTokens": 0, "givPrice": 0.00584277, "date": "2024-09-15T07:45:17.709Z" } } }

@maryjaf If project is givback eligible, token is givback eligible and donor address is not in the purple list, yes it would be increased

**Comment by maryjaf** [comment]
Thanks @mohammadranjbarz could you please tell me more about the formula of increasing GIV for givback 

This is the result of my test but i'm not if sure it's correct or not 

I Donated 0.001 xdai 
https://gnosisscan.io/tx/0x3bdbe85fc92eb5fc4ac573a5d6e97c3e39baf09d9daea8d47a691fe0e93e4ab2
Response :
{
    "data": {
        "allocatedGivbacks": {
            "usdValueSentAmountInPowerRound": 0.00078181823,
            "allocatedGivTokens": 1,
            "givPrice": 0.00584277,
            "date": "2024-09-15T14:05:05.995Z"
        }
    }
}


____
I Donated 0.01 xdai 
https://gnosisscan.io/tx/0x286c4b93384b7ec0473d7ee89e31bbefb83faf28e9b2184c5a9cd6ca0c5e4329
 Response :
 
 {
    "data": {
        "allocatedGivbacks": {
            "usdValueSentAmountInPowerRound": 0.0086,
            "allocatedGivTokens": 2,
            "givPrice": 0.00584277,
            "date": "2024-09-15T14:08:15.953Z"
        }
    }
}

__
I donate 100GIV on OP sepolia(1 GIV=1$)
https://optimism-sepolia.blockscout.com/tx/0xdd583ecc27038822018d2cb5091343517008241d475fbff2deecb795845cd1ac
Response:


{
    "data": {
        "allocatedGivbacks": {
            "usdValueSentAmountInPowerRound": 60.909092,
            "allocatedGivTokens": 10425,
            "givPrice": 0.00584277,
            "date": "2024-09-15T14:35:35.531Z"
        }
    }
}

**Comment by mohammadranjbarz** [comment]
> Thanks @mohammadranjbarz could you please tell me more about the formula of increasing GIV for givback
> 
> This is the result of my test but i'm not sure if it's correct or not
> 
> **I Donated 0.001 xdai** https://gnosisscan.io/tx/0x3bdbe85fc92eb5fc4ac573a5d6e97c3e39baf09d9daea8d47a691fe0e93e4ab2 Response : { "data": { "allocatedGivbacks": { "usdValueSentAmountInPowerRound": 0.00078181823, "allocatedGivTokens": 1, "givPrice": 0.00584277, "date": "2024-09-15T14:05:05.995Z" } } }
> 
> **I Donated 0.01 xdai** https://gnosisscan.io/tx/0x286c4b93384b7ec0473d7ee89e31bbefb83faf28e9b2184c5a9cd6ca0c5e4329 Response :
> 
> { "data": { "allocatedGivbacks": { "usdValueSentAmountInPowerRound": 0.0086, "allocatedGivTokens": 2, "givPrice": 0.00584277, "date": "2024-09-15T14:08:15.953Z" } } }
> 
> **I donate 100GIV on OP sepolia(1 GIV=1$)** https://optimism-sepolia.blockscout.com/tx/0xdd583ecc27038822018d2cb5091343517008241d475fbff2deecb795845cd1ac Response:
> 
> { "data": { "allocatedGivbacks": { "usdValueSentAmountInPowerRound": 60.909092, "allocatedGivTokens": 10425, "givPrice": 0.00584277, "date": "2024-09-15T14:35:35.531Z" } } }

@maryjaf We just calculate the value USD amount in the round, get GIV price from coingecko, then divide the USD amount value to GIV price and it is the allocatedGivTokens in the round so far.

**Comment by maryjaf** [comment]
> hmmm it's showing me "?" right now - is it likely the FE request is failing right now? or it's more likely that it's because the value is 0?
> 
> ideally, we should the last updated GIVbacks pool amount until the FE can get the new value... so if last time it was working the GIVbacks pools size is 50,000 GIV, we should that, rather than "?"
> 
> If it's the start of a new round though perhaps, and the amount is actually 0.. let's show "TBD"

Thanks @mohammadranjbarz it seems the calculation is correct based on above formula.

 Only this item remains, showing ? for "GIVbacks Rewards" on this branch https://giveth-dapps-v2-git-4679modifygivbackchangetobe-210dfd-givethio.vercel.app/givbacks

**Comment by mohammadranjbarz** [comment]
@maryjaf can you test it on this link https://giveth-dapps-v2-b4iwwt02n-givethio.vercel.app ?

**Comment by maryjaf** [comment]
> If it's the start of a new round though perhaps, and the amount is actually 0.. let's show "TBD"

Since it isn't the start of new round and there are some donations on staging, is TBD right? @mohammadranjbarz 
![image](https://github.com/user-attachments/assets/682047e3-9893-4aa8-b9eb-e76476342166)

**Comment by mohammadranjbarz** [comment]
> > If it's the start of a new round though perhaps, and the amount is actually 0.. let's show "TBD"
> 
> Since it isn't the start of new round and there are some donations on staging, is TBD right? @mohammadranjbarz ![image](https://private-user-images.githubusercontent.com/111529185/368077494-682047e3-9893-4aa8-b9eb-e76476342166.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NjI2MDUsIm5iZiI6MTcyNjU2MjMwNSwicGF0aCI6Ii8xMTE1MjkxODUvMzY4MDc3NDk0LTY4MjA0N2UzLTk4OTMtNGFhOC1iOWViLWU3NjQ3NjM0MjE2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxN1QwODM4MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYjIwMTcyYWEzYzg2NGMzNjQ3OTY0OTUyMzRjMWZiZGUxMTI4MTRjYjU2ZThiZTQ5NTAxMWExZGUyZDcyZjQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PURB6F1mgLIsPIka2YmPtEBfc0kBpZYPHhgb3uiLaa0)

It shows correctly for me

<img width="1455" alt="Screenshot 1403-06-27 at 12 09 13 in the afternoon" src="https://github.com/user-attachments/assets/92e3b054-32f3-4055-a926-d180af01a631">

**Comment by maryjaf** [comment]
Thanks @mohammadranjbarz now it is shown for me correctly
