### ISSUE TITLE
Add some prompt for the user to tell them to donate 5 USD or more to be eligibile for GIVbacks

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4681]
We have something like this for QF. Because now donations need to be at least $5 in order to qualify for GIVbacks... we should encourage the user on the donation page to increase their donation to $5USD

I think we can change the copy perhaps in the "this token is eligible for GIVbacks" thing... something like "This token is eligible for GIVbacks, but you need to increase your donation to $5 or more in order to qualify!"

@mosaeedi can you help me with a design?

![image](https://github.com/user-attachments/assets/e2f3bb3c-4bd1-4097-8ff3-f19ef0d8c423)

**Comment by laurenluz** [comment]
consider also what happens when a project is in a QF round!

min 1 USD for QF eligibility
min 5 USD to get rewarded through GIVbacks

**Comment by mosaeedi** [comment]
Please check issue #4731 .

**Comment by laurenluz** [comment]
closing this in favour of https://github.com/Giveth/giveth-dapps-v2/issues/4731 !
