### ISSUE TITLE
New condition: Only show "your eligible for GIVbacks" on donation success page if the donation value was above our GIVbacks donation minimum

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4682]
We are telling users that their donation needs to be at least $5 to qualify for GIVbacks... in actuality (internally), we will use $4 USD as the threshold... so let's use $4 USD as the threshold for this....

but basically, we should not show this "givbacks eligible" thing if the user's donation:

- in a GIVbacks eligible token
- on a GIVbacks eligible chain (e.g. not on Solana)
- at least $4 USD equivalent or more

![image](https://github.com/user-attachments/assets/c46daf98-1f7b-4cb9-b40a-d7e21200eff3)

@mohammadranjbarz can you help w/ this

**Comment by mohammadranjbarz** [comment]
@maryjaf can you test it on this link https://giveth-dapps-v2-b4iwwt02n-givethio.vercel.app ?

**Comment by maryjaf** [comment]
> * in a GIVbacks eligible token
> * on a GIVbacks eligible chain (e.g. not on Solana)
> * at least $4 USD equivalent or more

![image](https://github.com/user-attachments/assets/5e6dda30-4d3b-4960-abea-e54138e650a1)


For donations < 4

![image](https://github.com/user-attachments/assets/d61555eb-9a57-47fa-9785-36232057b1dd)
