### ISSUE TITLE
Change GIVbacks % bubble text for min donation amount & lottery

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4683]
- [x] GIVbacks eligible, public user view
Get rewarded with up to x% of your donation value!
A donation of $5 or more makes you eligible to recieve GIVbacks. Boost this project to increase its rewards percentage and make it more visible on the projects page!
![image](https://github.com/user-attachments/assets/59f4553a-0bf9-4636-96cb-47abcabba0d1)

- [x] GIVbacks eligible, project owner view
Donations of $5 or more qualify for GIVbacks with up to x% of the donation value!
Boost your project to increase its GIVbacks % and increase its visibility among other projects!
![image](https://github.com/user-attachments/assets/b0fa0a87-d835-41b2-95bf-6d0c0355f1ad)

- [ ] Non- GIVbacks eligible, public view
Can we just remove this bubble entirely? @mosaeedi @WhyldWanderer ?
<img width="936" alt="image" src="https://github.com/user-attachments/assets/0f7f7a8d-c386-4363-82e5-ce3d3438c462">

- [ ] Non- GIVbacks eligible, project owner view
@WhyldWanderer @mosaeedi can you help me find what it says in this case?

**Comment by mosaeedi** [comment]
@laurenluz I made some changes to the copy to reduce the description to two lines, Please let me know if it's okay.
I've removed the no GIVbacks 

![Image](https://github.com/user-attachments/assets/d95557da-b903-46e5-badf-672e7c3b3c10)

I also noticed we have another one, should I still keep it?

![Image](https://github.com/user-attachments/assets/bae7cc4b-5b29-4290-bca5-d58601da643c)


If we have to keep it, I suggest to change the copy,

![Image](https://github.com/user-attachments/assets/a0df0e7b-84eb-42b3-8073-b6804af93f66)

**Comment by laurenluz** [comment]
For the GIVbacks V2 changes, I think we only need to consider 2 alterations @RamRamez 

- [ ] GIVbacks eligible project, public view
![Image](https://github.com/user-attachments/assets/a692a66b-6566-4654-85ae-004f6358b5ac)

- [ ] GIVbacks eligible project, project owner view
![Image](https://github.com/user-attachments/assets/ff9f062a-2ddb-405b-b3b4-f23eaae68fe0)

link to [figma](https://www.figma.com/design/jrgULA0ZGWcfjRn0aXyPwj/DS---UI-Elements?node-id=11-19471&t=cnxwdnabGvQqpxrC-4)

The above changes are required for the Sept 16/Sept 17 release.

... Later...

For the following release when we separate GIVbacks & verification, we should also adjustments for cases cases for:
- Verified (vouched) but not GIVbacks eligible project, public view
- Verified (vouched) but not GIVbacks eligible project, project owner view (who has not applied for verification)
- Verified (vouched) but not GIVbacks eligible project, project owner view (who has applied for verification)
- Non-verified project, public view
- Non-verified project, project owner view

cc @divine-comedian

**Comment by RamRamez** [comment]
> For the GIVbacks V2 changes, I think we only need to consider 2 alterations @RamRamez
> 
> * [x]  GIVbacks eligible project, public view
>   ![Image](https://private-user-images.githubusercontent.com/75490971/367867855-a692a66b-6566-4654-85ae-004f6358b5ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1Njg4MTcsIm5iZiI6MTcyNjU2ODUxNywicGF0aCI6Ii83NTQ5MDk3MS8zNjc4Njc4NTUtYTY5MmE2NmItNjU2Ni00NjU0LTg1YWUtMDA0ZjYzNThiNWFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDEwMjE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyNWQyNDhhN2ZhOGE1NTFkYjI5NTZjZWYyMDZhOTRkM2M4YTFiOTk5NjNkNjdlMjNjMjg2MWNmMTVjZGFmOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T7FimqaNFSzzuWoQ4rLsFpq-fLEYIj8T9OQTom0vQ24)
> * [x]  GIVbacks eligible project, project owner view
>   ![Image](https://private-user-images.githubusercontent.com/75490971/367867998-ff9f062a-2ddb-405b-b3b4-f23eaae68fe0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1Njg4MTcsIm5iZiI6MTcyNjU2ODUxNywicGF0aCI6Ii83NTQ5MDk3MS8zNjc4Njc5OTgtZmY5ZjA2MmEtMmRkYi00MDViLWIzYjQtZjIzZWFhZTY4ZmUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDEwMjE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyODhmODMyZmQxZTQ1OTM4ZGRhZDc4YjMyMWQ0NDk1YzJmYzJiM2Q0ODk4YTZmOTIwZTFhZDJjYmI4NjBhZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YqbF2CNVJWla1gI-pICikk27jhMQF_UC9vODCGX9aeE)
> 
> link to [figma](https://www.figma.com/design/jrgULA0ZGWcfjRn0aXyPwj/DS---UI-Elements?node-id=11-19471&t=cnxwdnabGvQqpxrC-4)
> 
> The above changes are required for the Sept 16/Sept 17 release.
> 
> ... Later...
> 
> For the following release when we separate GIVbacks & verification, we should also adjustments for cases cases for:
> 
> * Verified (vouched) but not GIVbacks eligible project, public view
> * Verified (vouched) but not GIVbacks eligible project, project owner view (who has not applied for verification)
> * Verified (vouched) but not GIVbacks eligible project, project owner view (who has applied for verification)
> * Non-verified project, public view
> * Non-verified project, project owner view
> 
> cc @divine-comedian

These two are done!
@maryjaf please test and verify
https://giveth-dapps-v2-git-release17sep-givethio.vercel.app/

**Comment by maryjaf** [comment]
Thanks @RamRamez GIVback eligible copy for public and owner view have been changed based on the design 

Non- GIVbacks eligible views haven't been changed and I think it isn't necessary for this release
