### ISSUE TITLE
0% APR on OP - notify reward issue

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4685]
I didn't get an email about notify reward and the apr on prod is 0% on optimism: https://giveth.io/givfarm

@aminlatifi @mohammadranjbarz please help... I think there was a mistake w/ the new notify reward bot... maybe you removed the OP one and didn't set up the rewards for the new version?

![image](https://github.com/user-attachments/assets/314d7564-6245-47f2-91c4-9f5b851f0398)

**Comment by laurenluz** [comment]
related https://github.com/Giveth/giveth-dapps-v2/issues/4434

**Comment by mohammadranjbarz** [comment]
@laurenluz There was an error in name of script, it's working now

<img width="1470" alt="Screenshot 1403-06-14 at 11 21 34 in the morning" src="https://github.com/user-attachments/assets/23f583dd-a976-412f-9631-0407459b55d1">

**Comment by maryjaf** [comment]
![image](https://github.com/user-attachments/assets/508f667b-2ce8-4fb4-bbc5-a8d23cec2e8e)
