### ISSUE TITLE
On page refresh sometimes the token list does not appear

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4686]
Latifat reported this issue that sometimes the token list doesn't load and she needs to refresh in order to make it appear
 
> I have noticed is the slight glitch when refreshing both on stage and production.  what do you think?
> 
> https://github.com/user-attachments/assets/e74f259c-5b5a-4188-a973-775ebbdb47e3
> 
> _Originally posted by @LatifatAbdullahi in https://github.com/Giveth/giveth-dapps-v2/issues/4557#issuecomment-2329183097_
> 

Howver I think simply it is taking a while to load. In order to prevent confusion we should show the spinning loading wheel instead of showing "no token balances" while the app is loading up the tokens. 

## Additionally

When loading the token list  sometimes the balance appears as `--` it should continue loading the rest of the token balances and if the balance is `0` then it should show 0 instead of `--`

![image](https://github.com/user-attachments/assets/6054e948-7120-4516-9dde-4343b0d8ce7d)

**Comment by LatifatAbdullahi** [comment]
@divine-comedian 

It loads after a couple of seconds


https://github.com/user-attachments/assets/5498b24b-b06d-4d13-8716-a146914e61ee

**Comment by divine-comedian** [comment]
@lovelgeorge99 assigning this to you when you have bandwidth to take it.

**Comment by divine-comedian** [comment]
> @divine-comedian
> 
> It loads after a couple of seconds
> 
>  DeSci.Round.Operation.Group._.Giveth.-.Google.Chrome.2024-09-04.16-15-44.mp4

Thanks! We still need to check out the 2nd point of the token balances showins as `--`

**Comment by lovelgeorge99** [comment]
> > @divine-comedian
> > It loads after a couple of seconds
> > DeSci.Round.Operation.Group._.Giveth.-.Google.Chrome.2024-09-04.16-15-44.mp4
> 
> Thanks! We still need to check out the 2nd point of the token balances showins as `--`

Ok got it  ... will work on this

**Comment by LatifatAbdullahi** [comment]
@divine-comedian 
Test Update

This now works as expected with the loader added.


https://github.com/user-attachments/assets/8b78ff4c-9c95-4eab-9cb2-580fbcb41832

**Comment by divine-comedian** [comment]
@LatifatAbdullahi could you also test out if any token balances appear as `--` 

If you already did and can confirm this is resolved we can keep in Done

**Comment by LatifatAbdullahi** [comment]
@divine-comedian 

No token balance appears as --



![image](https://github.com/user-attachments/assets/00bb4dfc-335a-4365-ad09-a0108ca6498f)
