### ISSUE TITLE
Sync notify reward calls for all GIVpower staking programs to be timed with GIVbacks round rollovers (11am ET every other Tuesday)

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4687]
The notify reward calls for our GIVpower pools are out of sync and also too late!

We should have new rewards calls happen at the same time that new GIVbacks rounds start (for me, it's 11am Toronto time every other Tuesday).

Not sure if we can change this sooner... or if we should wait until the next time we extend the rewards.

This includes the rewards for Polygon zkEVM, Gnosis Chain, and OP Mainnet for GIV stakers.

@mohammadranjbarz @aminlatifi

**Comment by aminlatifi** [comment]
In order to sync, we can modify the script less than one hour before the boundary to notify reward regardless of previous round is finished or not. Then after the notify time, we revert the changes.

**Comment by laurenluz** [comment]
oh that's nice! then it would be great to do that perhaps in time for Sept 17, so we have everything lined up for the future. wdyt @mohammadranjbarz @aminlatifi ?

**Comment by aminlatifi** [comment]
> oh that's nice! then it would be great to do that perhaps in time for Sept 17, so we have everything lined up for the future. wdyt @mohammadranjbarz @aminlatifi ?

Yes, I and @mohammadranjbarz must make an event to be available then. I will create

**Comment by aminlatifi** [comment]
@laurenluz When must be the exact time in GMT?

**Comment by laurenluz** [comment]
3pm GMT

**Comment by mohammadranjbarz** [comment]
@aminlatifi I created a [PR](https://github.com/Giveth/giv-token-contracts/pull/104) for that, and this is my idea, look and say what is your idea:

1. Comment current cronjobs for these three farms in crontab , so we make sure the current scripts would not execute automatically
2. Channge the init times for these 3 farms to 3 hours earlier
3. Create a copy from each script(I called them **temp** scripts) and change 
```
    // 10 minutes of precision
    if (periodFinish < currentTime + 60 * 10) {
```

to 

```
    // 24 hours of precision
    if (periodFinish < currentTime + 60 * 60 * 24) {
```
For instance because of some problem OP period finish is for Wednesday now, so I used `24 hours` to make sure it will be executed when I run the script
4. On Tuesday `3pm GMT` we will run all **temp** scripts manually
5. Then uncomment the crontab jobs for calling notifyReward

@aminlatifi WDYT about my approach?

**Comment by aminlatifi** [comment]
> 3pm GMT

Good, we can go for it. Just are you 100% sure? Asking since I double-checked and saw that givpower rounds are aligned on Tuesdays at 4 PM GMT. Also, previous notify reward scripts were mostly aligned to Tuesdays at 6 PM GMT.
It's good to set a GMT based time as the reference point and align everything with that.

**Comment by aminlatifi** [comment]
> @aminlatifi I created a [PR](https://github.com/Giveth/giv-token-contracts/pull/104) for that, and this is my idea, look and say what is your idea:
> 
> 1. Comment current cronjobs for these three farms in crontab , so we make sure the current scripts would not execute automatically
> 2. Channge the init times for these 3 farms to 3 hours earlier
> 3. Create a copy from each script(I called them **temp** scripts) and change
> 
> ```
>     // 10 minutes of precision
>     if (periodFinish < currentTime + 60 * 10) {
> ```
> 
> to
> 
> ```
>     // 24 hours of precision
>     if (periodFinish < currentTime + 60 * 60 * 24) {
> ```
> 
> For instance because of some problem OP period finish is for Wednesday now, so I used `24 hours` to make sure it will be executed when I run the script 4. On Tuesday `3pm GMT` we will run all **temp** scripts manually 5. Then uncomment the crontab jobs for calling notifyReward
> 
> @aminlatifi WDYT about my approach?

I like the idea, we must change the init time to align with the time @laurenluz will declare.
Just, I don't think we need to clutter source code with that _tmp scripts. If we want to run the manually, we can just be around during the edge time and manually manipulate that rule and let the cronjob run them at the top of hour

**Comment by laurenluz** [comment]
> Good, we can go for it. Just are you 100% sure? Asking since I double-checked and saw that givpower rounds are aligned on Tuesdays at 4 PM GMT. Also, previous notify reward scripts were mostly aligned to Tuesdays at 6 PM GMT.
It's good to set a GMT based time as the reference point and align everything with that.

oh man, I think it's 3pm GMT. Sorry. I want them to be synced with the same time GIVbacks rounds roll over. for me, i see 11am on my machine when I look at the GIVbacks page... but I think I'm in daylight savings time... so EDT... I checked 11am EST....

But yeah, I think 3pm GMT or, to be more clear... **the same time GIVbacks rounds rolls over**. can you confirm?

**Comment by mohammadranjbarz** [comment]
> > @aminlatifi I created a [PR](https://github.com/Giveth/giv-token-contracts/pull/104) for that, and this is my idea, look and say what is your idea:
> > 
> > 1. Comment current cronjobs for these three farms in crontab , so we make sure the current scripts would not execute automatically
> > 2. Channge the init times for these 3 farms to 3 hours earlier
> > 3. Create a copy from each script(I called them **temp** scripts) and change
> > 
> > ```
> >     // 10 minutes of precision
> >     if (periodFinish < currentTime + 60 * 10) {
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to
> > ```
> >     // 24 hours of precision
> >     if (periodFinish < currentTime + 60 * 60 * 24) {
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > For instance because of some problem OP period finish is for Wednesday now, so I used `24 hours` to make sure it will be executed when I run the script 4. On Tuesday `3pm GMT` we will run all **temp** scripts manually 5. Then uncomment the crontab jobs for calling notifyReward
> > @aminlatifi WDYT about my approach?
> 
> I like the idea, we must change the init time to align with the time @laurenluz will declare. Just, I don't think we need to clutter source code with that _tmp scripts. If we want to run the manually, we can just be around during the edge time and manually manipulate that rule and let the cronjob run them at the top of hour

Yeah you are right, it could be more simple

**Comment by mohammadranjbarz** [comment]
Ok done

* https://gnosisscan.io/tx/0xd2a7ac4e396c22c90b37f0503dee294f0e7c93c10ce00b426704ae3c0a15ff29

* https://zkevm.polygonscan.com/tx/0xddc53f3bc5fc04a594423e6bd20b4fb2eb2f0a98b4fe7fdcc342fa407b1e03b6

* https://optimistic.etherscan.io/tx/0xebbb9bcd0b875a68d31f60bc9d88e35f051913ae87ab09f910085c576691afc6

Now it's time to remove extra codes and reenable the cronjob
