### ISSUE TITLE
Text for "load more" at the bottom has a white text collor which is not visable

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#4694]
![Screenshot 2024-09-06 at 10 41 53 AM](https://github.com/user-attachments/assets/6b22e4f2-cd3e-4d45-9b65-6d02509cbbfe)

![Screenshot 2024-09-06 at 10 42 39 AM](https://github.com/user-attachments/assets/b0f7959f-c698-438b-9980-f982acf4ce50)

![Screenshot 2024-09-06 at 10 43 35 AM](https://github.com/user-attachments/assets/9e0fed9c-4754-468d-9869-8398c1f5be11)

**Comment by maryjaf** [comment]
Thanks @kkatusic This issue has been fixed.

![image](https://github.com/user-attachments/assets/bee58ab6-ba56-4530-9eba-ea7b3a3ad106)
