### ISSUE TITLE
Some projects not showing on the QF page

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#4705]
it seems that the projects are not populating correctly on the QF page. The round should have 77 projects but I'm only showing about 45 in the list when I go to this page. https://giveth.io/qf

I can see that the projects are in the round in the AdminBro so I'm unsure as to why they are not all showing. Can someone take a look?

**Comment by kkatusic** [comment]
@WhyldWanderer it is showing 77 projects, I checked, what project you see that is missing? Maybe not all project loaded immediately after changing data inside administration, you can always check inside another browser or incognito browser window.
