### ISSUE TITLE
Default view when the user clicks donate should be "one time donation"

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4714]
For some reason, I am being navigated 1st to make a recurrding donation. this is not most people's default and the UX is so much more confusing....

Please, let's make the default flow donate --> one time donation

https://github.com/user-attachments/assets/6c6238eb-7df3-4e9f-a732-8c393d79cb30

**Comment by divine-comedian** [comment]
the change should be reverted in https://github.com/Giveth/giveth-dapps-v2/pull/4717
