### ISSUE TITLE
change metadata on verify project page for GIVbacks Eligibility

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4715]
when a project is filling out the GIVbacks eligiblity form the metadata shown on the browser tab preview and any linked text should be changed from "Project Verification" to GIVbacks Eligibility

**Comment by LatifatAbdullahi** [comment]
@divine-comedian 

This has been updated and shows "GIVbacks Eligibility Application" when previewed.


https://github.com/user-attachments/assets/1381468f-bf31-4ac2-a6ec-b40a00fa86fc
