### ISSUE TITLE
add new endaoment projects into DB

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4718]
A few Endaoment projects not on our original list of imported projects have requested to be added into the app, we'll need to fetch these projects by their Endaoment ID, parse the project information, assign the correct categories and banners. This is related to the current QF round.

then we need to write a migration to add them into the DB

## AC

testing these 8 projects on PRODUCTION

- [ ] https://giveth.io/project/ukraine-america-initiative
- [ ] https://giveth.io/project/reef-guardians-hawaii
- [ ] https://giveth.io/project/mindfulness-through-play
- [ ] https://giveth.io/project/solutions-project-inc
- [ ] https://giveth.io/project/peace-winds-america
- [ ] https://giveth.io/project/love-justice-international
- [ ] https://giveth.io/project/metagovernance-project-inc

this criteria is met: 

- project banner shows correctly  (referenced below each banner for each project)
- project categories show correctly on UI
- description shows correctly 
- can access donate page and make successful donation
- project title shows correctly 
- delivered by endaoment related banners and badges show on project card and project details pages

**Comment by WhyldWanderer** [comment]
Here are the projects that should be added:

Ukraine America Initiative
https://app.endaoment.org/orgs/88-2280006
Project ID: 0ede481a-c59c-4201-8b0c-69e375cdd7ea

Reef Guardians Hawaii
https://app.endaoment.org/orgs/47-3975420
Project ID: 2627e4ee-f713-4298-84d2-9fbad53d9ed9

Mindfulness Through Play
https://app.endaoment.org/orgs/82-4211804
Project ID: 2d257c44-c39e-4f41-b4b4-24dd732f545d

SOLUTIONS PROJECT INC
https://app.endaoment.org/orgs/46-3811348
Project ID: a60836a2-f06e-4b5b-9354-584a4ca5b4b0

Peace Winds America
https://app.endaoment.org/orgs/26-3744952
Project ID: 25b2e4a9-20de-4564-be24-fc523a22d65c

Love Justice International
https://app.endaoment.org/orgs/71-0982808
Project ID: c8101dbe-f308-425c-a0a5-39a98316c02f

Metagovernance Project Inc
https://app.endaoment.org/orgs/85-3442527
Project ID: d94cdffb-50cc-4127-806d-051b26f5ce00

**Comment by WhyldWanderer** [comment]
I will start to work on creating these projects and then transfer ownership to the endaoment profile.

I will update this issue when Im done and then the only thing we will need a dev for is to add the categories once the projects are created as I cannot add the endaoment category through the UI.

**Comment by divine-comedian** [comment]
## Ukraine America Initiative
https://giveth.io/images/defaultProjectImages/community.png

## Reef Guardians Hawaii
https://giveth.io/images/defaultProjectImages/nature.png

## Mindfulness Through Play
https://giveth.io/images/defaultProjectImages/education.png

## SOLUTIONS PROJECT INC
https://giveth.io/images/defaultProjectImages/nature.png

## Peace Winds America
https://giveth.io/images/defaultProjectImages/community.png

## Love Justice International
https://giveth.io/images/defaultProjectImages/community.png

## Metagovernance Project Inc
https://giveth.io/images/defaultProjectImages/finance.png

**Comment by WhyldWanderer** [comment]
The projects have been created! @CarlosQ96 do you think you can help us to make these projects verified and add the "Endaoment" category to each one?



### Ukraine America Initiative
https://giveth.io/project/ukraine-america-initiative

### Reef Guardians Hawaii
https://giveth.io/project/reef-guardians-hawaii

### Mindfulness Through Play
https://giveth.io/project/mindfulness-through-play

### SOLUTIONS PROJECT INC
https://giveth.io/project/solutions-project-inc

### Peace Winds America
https://giveth.io/project/peace-winds-america

### Love Justice International
https://giveth.io/project/love-justice-international

### Metagovernance Project Inc
https://giveth.io/project/metagovernance-project-inc

**Comment by WhyldWanderer** [comment]
Also.. should there be a restricted token list for these projects @divine-comedian?

**Comment by CarlosQ96** [comment]
@WhyldWanderer added isImported to adminJs and the ability to add categories.

**Comment by CarlosQ96** [comment]
Will investigate the socials issue now. Didn't find anything wrong, might be a frontend issues. But not sure yet.

**Comment by divine-comedian** [comment]
I've made https://github.com/Giveth/giveth-dapps-v2/issues/4759 to follow up this bug report 

testing these projects now it seems all of their categories are missing from the UI 
![image](https://github.com/user-attachments/assets/e0411ea2-a22d-43ef-aa88-43df56895abc)

Here's another Endaoment project for comparison - you can see the categories show up including the Endaoment category 
https://giveth.io/project/East-Bay-Food-Justice-Project

**Comment by CarlosQ96** [comment]
@divine-comedian we have to add their categories. They weren't added. I gotta release this to prod tomorrow.

**Comment by divine-comedian** [comment]
ready for QA need to AC

**Comment by divine-comedian** [comment]
@LatifatAbdullahi this should be ready for QA

**Comment by LatifatAbdullahi** [comment]
@HrithikSampson @divine-comedian 

**Test update**



**Ukraine America Initiative**

Project banner shows correctly - **Pass**
Project categories show correctly on UI - **Failed** (Category missing)
Description shows correctly - **Pass**
Can access donate page - **Pass**
Make successful donation - **Pass**
Project title shows correctly - **Pass**
Delivered by Endaoment related banners and badges show on project card and project details pages - **Pass**



**Reef Guardians Hawaii**

Project banner shows correctly - **Pass**
Project categories show correctly on UI - **Failed** (Category missing)
Description shows correctly - **Failed**

![x](https://github.com/user-attachments/assets/acae32e1-9cfd-4076-9209-ee677f9e3cbe)

Can access donate page - **Pass**
Make successful donation - **Pass**
Project title shows correctly - **Pass**
Delivered by Endaoment related banners and badges show on project card and project details pages - **Pass**


**Mindfulness Through Play**


Project banner shows correctly - **Pass**
Project categories show correctly on UI - **Failed** (Category missing)
Description shows correctly - **Pass**
Can access donate page - **Pass**
Make successful donation - **Pass**
Project title shows correctly - **Pass**
Delivered by Endaoment related banners and badges show on project card and project details pages - **Pass**



**SOLUTIONS PROJECT INC**


Project banner shows correctly - **Pass**
Project categories show correctly on UI - **Failed** (Category missing)
Description shows correctly - **Pass**
Can access donate page - **Pass**
Make successful donation - **Pass**
Project title shows correctly - **Pass**
Delivered by Endaoment related banners and badges show on project card and project details pages - **Pass**

**Peace Winds America**


Project banner shows correctly - **Pass**
Project categories show correctly on UI - **Failed** (Category missing)
Description shows correctly - **Failed** (Wrong description)

![l](https://github.com/user-attachments/assets/49e7e56e-88f6-4a49-8d5b-8905f57d27f8)

![ii](https://github.com/user-attachments/assets/253130dc-fe1f-441d-b5ba-223e5446c2ec)

Can access donate page - **Pass**
Make successful donation - **Pass**
Project title shows correctly - **Pass**
Delivered by Endaoment related banners and badges show on project card and project details pages - **Pass**


**Love Justice International**

Project banner shows correctly - **Pass**
Project categories show correctly on UI - **Failed** (Category missing)
Description shows correctly - **Pass**
Can access donate page - **Pass**
Make successful donation - **Pass**
Project title shows correctly - **Pass**
Delivered by Endaoment related banners and badges show on project card and project details pages - **Pass**


**Metagovernance Project Inc**

Project banner shows correctly - **Pass**
Project categories show correctly on UI - **Failed** (Category missing)
Description shows correctly - **Pass**
Can access donate page - **Pass**
Make successful donation - **Pass**
Project title shows correctly - **Pass**
Delivered by Endaoment related banners and badges show on project card and project details pages - **Pass**

**Comment by divine-comedian** [comment]
Thanks @LatifatAbdullahi so the categories still seem to be missing on these extra projects. 

Also there needs to be some parsing of the information to handle line breaks in the raw text - @CarlosQ96 can you handle the categories? Who is the best person to check-out handling the line breaks? @mohammadranjbarz  I think you worked on this originally.

**Comment by CarlosQ96** [comment]
@divine-comedian Ill set up the categories today.

**Comment by CarlosQ96** [comment]
All should be updateble from adminjs @divine-comedian thats the update I did even categories.

**Comment by CarlosQ96** [comment]
@LatifatAbdullahi @divine-comedian I added the category endaoment to all of them

**Comment by CarlosQ96** [comment]
Hmm not sure of the line breaks and stuff @RamRamez @mohammadranjbarz  do you know?

**Comment by mohammadranjbarz** [comment]
> Hmm not sure of the line breaks and stuff @RamRamez @mohammadranjbarz do you know?

I will DM you

**Comment by mohammadranjbarz** [comment]
> @CarlosQ96 @divine-comedian
> 
> **Test update**
> 
> **Ukraine America Initiative**
> 
> Project banner shows correctly - **Pass** Project categories show correctly on UI - **Failed** (Category missing) Description shows correctly - **Pass** Can access donate page - **Pass** Make successful donation - **Pass** Project title shows correctly - **Pass** Delivered by Endaoment related banners and badges show on project card and project details pages - **Pass**
> 
> **Reef Guardians Hawaii**
> 
> Project banner shows correctly - **Pass** Project categories show correctly on UI - **Failed** (Category missing) Description shows correctly - **Failed**
> 
> ![x](https://private-user-images.githubusercontent.com/112261242/373757538-acae32e1-9cfd-4076-9209-ee677f9e3cbe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMDUwMzMsIm5iZiI6MTcyODMwNDczMywicGF0aCI6Ii8xMTIyNjEyNDIvMzczNzU3NTM4LWFjYWUzMmUxLTljZmQtNDA3Ni05MjA5LWVlNjc3ZjllM2NiZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QxMjM4NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMzAzY2IwMzY1NWU4MmYyY2Q4YTgzNWU5MTE4ZDFlMjBkNjExODRhYzdlYTk5NGJhZTVhMDhhZTE1YzNlOWUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZZTHXLro4HXoQAoavL84sWYJY__eb-x4b3prk-VEzw8)
> 
> Can access donate page - **Pass** Make successful donation - **Pass** Project title shows correctly - **Pass** Delivered by Endaoment related banners and badges show on project card and project details pages - **Pass**
> 
> **Mindfulness Through Play**
> 
> Project banner shows correctly - **Pass** Project categories show correctly on UI - **Failed** (Category missing) Description shows correctly - **Pass** Can access donate page - **Pass** Make successful donation - **Pass** Project title shows correctly - **Pass** Delivered by Endaoment related banners and badges show on project card and project details pages - **Pass**
> 
> **SOLUTIONS PROJECT INC**
> 
> Project banner shows correctly - **Pass** Project categories show correctly on UI - **Failed** (Category missing) Description shows correctly - **Pass** Can access donate page - **Pass** Make successful donation - **Pass** Project title shows correctly - **Pass** Delivered by Endaoment related banners and badges show on project card and project details pages - **Pass**
> 
> **Peace Winds America**
> 
> Project banner shows correctly - **Pass** Project categories show correctly on UI - **Failed** (Category missing) Description shows correctly - **Failed** (Wrong description)
> 
> ![l](https://private-user-images.githubusercontent.com/112261242/373763161-49e7e56e-88f6-4a49-8d5b-8905f57d27f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMDUwMzMsIm5iZiI6MTcyODMwNDczMywicGF0aCI6Ii8xMTIyNjEyNDIvMzczNzYzMTYxLTQ5ZTdlNTZlLTg4ZjYtNGE0OS04ZDViLTg5MDVmNTdkMjdmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QxMjM4NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hY2JjOTkyMzNjNGRjZTI2ZjE1ODQxZTYzYjc4ZTU1NDg1NzE5NWYwYzM0YmRmZjQyMGVkYjA0MWM2NDRlYzhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.84JxpqK0BKsqu90PIFY9rbHtpxMYHEij4HokZdoGQo4)
> 
> ![ii](https://private-user-images.githubusercontent.com/112261242/373763367-253130dc-fe1f-441d-b5ba-223e5446c2ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMDUwMzMsIm5iZiI6MTcyODMwNDczMywicGF0aCI6Ii8xMTIyNjEyNDIvMzczNzYzMzY3LTI1MzEzMGRjLWZlMWYtNDQxZC1iNWJhLTIyM2U1NDQ2YzJlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QxMjM4NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOTcyYzkzMDk1MjRiOGYxYWFkMTBhY2QyYzEzMTlmOWU3MmE2MmZhMDk2MWJmYmUxZGY3MjAyODNkODY4Y2I0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Cm2RJlNz3GhmYYiCG5ZTN135niVMJaPakD0Wi83Iqzc)
> 
> Can access donate page - **Pass** Make successful donation - **Pass** Project title shows correctly - **Pass** Delivered by Endaoment related banners and badges show on project card and project details pages - **Pass**
> 
> **Love Justice International**
> 
> Project banner shows correctly - **Pass** Project categories show correctly on UI - **Failed** (Category missing) Description shows correctly - **Pass** Can access donate page - **Pass** Make successful donation - **Pass** Project title shows correctly - **Pass** Delivered by Endaoment related banners and badges show on project card and project details pages - **Pass**
> 
> **Metagovernance Project Inc**
> 
> Project banner shows correctly - **Pass** Project categories show correctly on UI - **Failed** (Category missing) Description shows correctly - **Pass** Can access donate page - **Pass** Make successful donation - **Pass** Project title shows correctly - **Pass** Delivered by Endaoment related banners and badges show on project card and project details pages - **Pass**

I would appreciate it if besides sending screenshots put the links in the issue as well, it would help us to troubleshoot better when have the link, if I'm not wrong we have this project

https://giveth.io/project/peace-winds-america

and the real project info in endqaoment is 
https://app.endaoment.org/orgs/26-3744952

And the decription is wrong in our DB, am I right?

Now I have a question: who and how this project has been added because I couldn't find this project in the CSV that @divine-comedian had passed it to me before

**Comment by divine-comedian** [comment]
> > @CarlosQ96 @divine-comedian
> > **Test update**
> > **Ukraine America Initiative**
> > Project banner shows correctly - **Pass** Project categories show correctly on UI - **Failed** (Category missing) Description shows correctly - **Pass** Can access donate page - **Pass** Make successful donation - **Pass** Project title shows correctly - **Pass** Delivered by Endaoment related banners and badges show on project card and project details pages - **Pass**
> > **Reef Guardians Hawaii**
> > Project banner shows correctly - **Pass** Project categories show correctly on UI - **Failed** (Category missing) Description shows correctly - **Failed**
> > ![x](https://private-user-images.githubusercontent.com/112261242/373757538-acae32e1-9cfd-4076-9209-ee677f9e3cbe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMDUwMzMsIm5iZiI6MTcyODMwNDczMywicGF0aCI6Ii8xMTIyNjEyNDIvMzczNzU3NTM4LWFjYWUzMmUxLTljZmQtNDA3Ni05MjA5LWVlNjc3ZjllM2NiZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QxMjM4NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMzAzY2IwMzY1NWU4MmYyY2Q4YTgzNWU5MTE4ZDFlMjBkNjExODRhYzdlYTk5NGJhZTVhMDhhZTE1YzNlOWUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZZTHXLro4HXoQAoavL84sWYJY__eb-x4b3prk-VEzw8)
> > Can access donate page - **Pass** Make successful donation - **Pass** Project title shows correctly - **Pass** Delivered by Endaoment related banners and badges show on project card and project details pages - **Pass**
> > **Mindfulness Through Play**
> > Project banner shows correctly - **Pass** Project categories show correctly on UI - **Failed** (Category missing) Description shows correctly - **Pass** Can access donate page - **Pass** Make successful donation - **Pass** Project title shows correctly - **Pass** Delivered by Endaoment related banners and badges show on project card and project details pages - **Pass**
> > **SOLUTIONS PROJECT INC**
> > Project banner shows correctly - **Pass** Project categories show correctly on UI - **Failed** (Category missing) Description shows correctly - **Pass** Can access donate page - **Pass** Make successful donation - **Pass** Project title shows correctly - **Pass** Delivered by Endaoment related banners and badges show on project card and project details pages - **Pass**
> > **Peace Winds America**
> > Project banner shows correctly - **Pass** Project categories show correctly on UI - **Failed** (Category missing) Description shows correctly - **Failed** (Wrong description)
> > ![l](https://private-user-images.githubusercontent.com/112261242/373763161-49e7e56e-88f6-4a49-8d5b-8905f57d27f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMDUwMzMsIm5iZiI6MTcyODMwNDczMywicGF0aCI6Ii8xMTIyNjEyNDIvMzczNzYzMTYxLTQ5ZTdlNTZlLTg4ZjYtNGE0OS04ZDViLTg5MDVmNTdkMjdmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QxMjM4NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hY2JjOTkyMzNjNGRjZTI2ZjE1ODQxZTYzYjc4ZTU1NDg1NzE5NWYwYzM0YmRmZjQyMGVkYjA0MWM2NDRlYzhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.84JxpqK0BKsqu90PIFY9rbHtpxMYHEij4HokZdoGQo4)
> > ![ii](https://private-user-images.githubusercontent.com/112261242/373763367-253130dc-fe1f-441d-b5ba-223e5446c2ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMDUwMzMsIm5iZiI6MTcyODMwNDczMywicGF0aCI6Ii8xMTIyNjEyNDIvMzczNzYzMzY3LTI1MzEzMGRjLWZlMWYtNDQxZC1iNWJhLTIyM2U1NDQ2YzJlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwN1QxMjM4NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOTcyYzkzMDk1MjRiOGYxYWFkMTBhY2QyYzEzMTlmOWU3MmE2MmZhMDk2MWJmYmUxZGY3MjAyODNkODY4Y2I0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Cm2RJlNz3GhmYYiCG5ZTN135niVMJaPakD0Wi83Iqzc)
> > Can access donate page - **Pass** Make successful donation - **Pass** Project title shows correctly - **Pass** Delivered by Endaoment related banners and badges show on project card and project details pages - **Pass**
> > **Love Justice International**
> > Project banner shows correctly - **Pass** Project categories show correctly on UI - **Failed** (Category missing) Description shows correctly - **Pass** Can access donate page - **Pass** Make successful donation - **Pass** Project title shows correctly - **Pass** Delivered by Endaoment related banners and badges show on project card and project details pages - **Pass**
> > **Metagovernance Project Inc**
> > Project banner shows correctly - **Pass** Project categories show correctly on UI - **Failed** (Category missing) Description shows correctly - **Pass** Can access donate page - **Pass** Make successful donation - **Pass** Project title shows correctly - **Pass** Delivered by Endaoment related banners and badges show on project card and project details pages - **Pass**
> 
> I would appreciate it if besides sending screenshots put the links in the issue as well, it would help us to troubleshoot better when have the link, if I'm not wrong we have this project
> 
> https://giveth.io/project/peace-winds-america
> 
> and the real project info in endqaoment is https://app.endaoment.org/orgs/26-3744952
> 
> And the decription is wrong in our DB, am I right?
> 
> Now I have a question: who and how this project has been added because I couldn't find this project in the CSV that @divine-comedian had passed it to me before

These were projects that heard about the QF round and we added them manually on request from Endaoment

**Comment by mohammadranjbarz** [comment]
@divine-comedian Ok got it, I thouth we had problem on importing projects, so these are just some cases that we should change them manually in DB

Just the **Peace winds america** has problem, or the are other projects as well?

**Comment by LatifatAbdullahi** [comment]
> Here are the projects that should be added:
> 
> Ukraine America Initiative https://app.endaoment.org/orgs/88-2280006 Project ID: 0ede481a-c59c-4201-8b0c-69e375cdd7ea Category: Disaster Preparedness and Relief Services
> 
> Reef Guardians Hawaii https://app.endaoment.org/orgs/47-3975420 Project ID: 2627e4ee-f713-4298-84d2-9fbad53d9ed9 category: Water Resource, Wetlands Conservation and Management
> 
> Mindfulness Through Play https://app.endaoment.org/orgs/82-4211804 Project ID: 2d257c44-c39e-4f41-b4b4-24dd732f545d Category: Student Services and Organizations
> 
> SOLUTIONS PROJECT INC https://app.endaoment.org/orgs/46-3811348 Project ID: a60836a2-f06e-4b5b-9354-584a4ca5b4b0 Category: Energy Resources Conservation and Development
> 
> Peace Winds America https://app.endaoment.org/orgs/26-3744952 Project ID: 25b2e4a9-20de-4564-be24-fc523a22d65c Category: Disaster Preparedness and Relief Services
> 
> Love Justice International https://app.endaoment.org/orgs/71-0982808 Project ID: c8101dbe-f308-425c-a0a5-39a98316c02f Category: Victims' Services
> 
> Metagovernance Project Inc https://app.endaoment.org/orgs/85-3442527 Project ID: d94cdffb-50cc-4127-806d-051b26f5ce00 Category: Computer Science





@CarlosQ96 thanks, regarding this, seems we still have some missing categories/sub-categories as shown here



![uo](https://github.com/user-attachments/assets/6aaaa030-5bbb-4f46-b0b1-5422320a4940)



Staging
![ft](https://github.com/user-attachments/assets/dc61134c-d1ee-4d69-abeb-a45530c81963)

**Comment by CarlosQ96** [comment]
@divine-comedian can we close this one too? or anything missing here? I think its basically the same issue we had the categories missing.

cc: @LatifatAbdullahi

**Comment by LatifatAbdullahi** [comment]
Thanks @CarlosQ96 

The Project description for **Peace Wind America** has been updated as well


![ri](https://github.com/user-attachments/assets/a263638a-14d7-46c0-ab01-0bd6db8514e1)
