### ISSUE TITLE
GIVbacks V2 - make the rGIV DAO multisigs on OP & Gnosis chain GIVbacks distributors and assign them a balance of GIV to send to the winners

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4719]
We'll need 1,500,000 GIV assigned in total to cover ourselves for the upcoming 3 GIVbacks V2 trial experiments rounds (but not sure what chain that will need to be on, really)...

So I think we could safely assign a balance of 5M GIV to each multisig for starters 🤔, it's likely imo that we will continue this kind of thing into the future.

I will also put a note to discuss on tomorrow's GIVeconomy call

**Comment by divine-comedian** [comment]
multisig txs are here 

https://app.onchainden.com/safes/gno:0x4D9339dd97db55e3B9bCBE65dE39fF9c04d1C2cd/transactions/0xf5b76dbe4b8635ed23cde3b230c9bbbdbbfcf5f74c4110df919c94573da1bcc0?nid=439798

https://app.onchainden.com/safes/oeth:0x4D9339dd97db55e3B9bCBE65dE39fF9c04d1C2cd/transactions/0x036ecd19194cb4567b97596a16ca76e80f2e41f8ec8b525938a23510355426b7?nid=439780

**Comment by laurenluz** [comment]
god bless you ser

**Comment by divine-comedian** [comment]
@laurenluz can this be closed?
