### ISSUE TITLE
OP shows wrong available to unstake value

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-dapps-v2#4722]
I noticed this problem just when I staked some GIV on OP (not on Gnosis or other chains). 

1) When I stake a GIV amount on OP, and click on "Locked GIV details", is shows the wrong value 
2) When I try to "Increase your reward" by locking for GIVpower, it doesn't let me do it if I choose the max amount. 
3) I have to guess what the "real" amount of GIV I have locked is, otherwise it doesn't work. 

See image:

<img width="348" alt="Screenshot 2024-09-11 at 1 28 09 PM" src="https://github.com/user-attachments/assets/e1929c93-97dc-4049-a154-bb645f5a9672">

Ex.  here it says I have over 4,000 GIV locked, but it doesn't let me lock that amount. I can only lock 3,500 GIV for some reason. If I try to lock the max nothing happens, I have to do trial and error until I figure out what the real amount of GIV I have locked is.

**Comment by kkatusic** [comment]
@maryjaf or @LatifatAbdullahi I checked this one on staging and production few times with Giveth token, I didn't get same issues like @ahmadabugosh . Can you one of you two test it when you find time? thx

**Comment by LatifatAbdullahi** [comment]
@kkatusic  I just checked as well and I am not able to reproduce the issues, @maryjaf please kindly confirm..thanks

**Comment by maryjaf** [comment]
I've tested and I could lock all of my available GIV on OP on staging and it is shown correctly in UI
