### ISSUE TITLE
Document the "things we forgot about" during zkEVM integration, for use in future GIVeconomy integrations

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4723]
This issue will be part of the zkeVM integration product and we can then use it/fork it for future giveconomy integrations. Want to make sure we don't repeat the same mistake, so we should document

Things like:
- fund givpower unlock bot with gas
- assign a distributor role to a new multisig to send out GIVbacks
etc.

@mohammadranjbarz 
cc @aminlatifi @geleeroyale

**Comment by mohammadranjbarz** [comment]
@laurenluz I think this document is completed now
https://gist.github.com/mohammadranjbarz/a44f3cede21d5aa7e82ef127b90c8235

**Comment by laurenluz** [comment]
yay mohammad I think that's great

@aminlatifi do you have to have a quick look and if it's all good, we can close this issue?

**Comment by aminlatifi** [comment]
I see the doc is a gist under Mohammad's account. @mohammadranjbarz can you put it somewhere under Giveth ownership? Also, I will be able to put comments for later possible amendments

**Comment by mohammadranjbarz** [comment]
> I see the doc is a gist under Mohammad's account. @mohammadranjbarz can you put it somewhere under Giveth ownership? Also, I will be able to put comments for later possible amendments

Yes of course, but I can't create gist under Giveth organization, can you do it and give me the link to add my content there?

**Comment by aminlatifi** [comment]
Not necessary gist, we can find another place. Like a README file in giveconomy foundry repo

**Comment by mohammadranjbarz** [comment]
> Not necessary gist, we can find another place. Like a README file in giveconomy foundry repo

I added it in giv-token-contract readme
https://github.com/Giveth/giv-token-contracts/pull/106

**Comment by laurenluz** [comment]
ok nice! @aminlatifi is that good? should we close this?

**Comment by aminlatifi** [comment]
> ok nice! @aminlatifi is that good? should we close this?

Let me review please

**Comment by aminlatifi** [comment]
Done

**Comment by laurenluz** [comment]
lovely - thanks guys @mohammadranjbarz @aminlatifi - let's keep this doc in mind for next time!!
