### ISSUE TITLE
GIVpower is being SO slow and buggy? 

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4724]
Issues I've noticed:
1. From "My GIvpower" when I remove projects from my givpower list... I see the right modals (showing tha it I removed them) but I need to refresh before the chances are reflected on the page
2. From projects page - when I am boosting, adding more and more projects... it just says I have only 4 projects boosted.
3. Once I hit 20 projects (acutally boosted 20). the UI says I boosted 4, my GIVpower shows all 20... and when I try to boost another, it just loads forever and nothing..

what is causing this? do we have some kind of caching implemented?
@mohammadranjbarz ?

<img width="572" alt="image" src="https://github.com/user-attachments/assets/4a1e7098-3293-4e55-a597-a176d9a55c99">

**Comment by maryjaf** [comment]
> * From "My GIvpower" when I remove projects from my givpower list... I see the right modals (showing tha it I removed them) but I need to refresh before the chances are reflected on the page
> * From projects page - when I am boosting, adding more and more projects... it just says I have only 4 projects boosted.
> * Once I hit 20 projects (acutally boosted 20). the UI says I boosted 4, my GIVpower shows all 20... and when I try to boost another, it just loads forever and nothing..

These problems have been fixed, thanks @HrithikSampson
