### ISSUE TITLE
UI issues on project details page.

### ISSUE THREAD

**Issue by mosaeedi** [Giveth/giveth-dapps-v2#4726]
# UI Adjustments

1. There is a **24px** gap between each row.
Right now, we have different gap between each row, all of them should be just **24px**.
<img width="838" alt="Screenshot 2024-09-11 at 8 28 20 PM" src="https://github.com/user-attachments/assets/8e03dc73-cffb-4854-a50d-7f223af41481">

2. Please reduce this gap to **8px**.

<img width="527" alt="Screenshot 2024-09-11 at 8 29 19 PM" src="https://github.com/user-attachments/assets/5d43dae2-c166-41bf-8389-b2cb487747d9">

3. Please remove the "Learn more about donating on Giveth > " from this card.
<img width="630" alt="Screenshot 2024-09-11 at 8 31 54 PM" src="https://github.com/user-attachments/assets/1d30a276-b680-4d7e-91db-95d1e3ab3276">

4.1. The "SHARE" button should be in camel-case "**Share**". 
4.2. The bookmark icon should use **Gray/700** as color.
<img width="562" alt="Screenshot 2024-09-11 at 8 32 58 PM" src="https://github.com/user-attachments/assets/b7cba621-615c-42e7-8ade-a61e2b82b381">

5. Instead of listing the eligible network in text, please change it to icons,
**Please note:** By default, all network icons appear in grayscale, and just when the user hovers over them, they should turn into the colorful version.
**Please note:** the icons by default should have a **40% opacity**, and just on hover the opacity should increase to 100%.
_Please let me know if we can use CSS to turn them into grayscale, or if I have to provide two versions!_ 

<img width="489" alt="Screenshot 2024-09-11 at 8 35 29 PM" src="https://github.com/user-attachments/assets/133ec3d5-444b-4df6-bb13-0f7f604b0ce3">

6. The project banner should have a 430px height, right now it's about 510px!

<img width="697" alt="Screenshot 2024-09-11 at 8 46 22 PM" src="https://github.com/user-attachments/assets/ba9b6e38-8cd6-4723-8c71-d2259bf81493">

## Design asset is here

[Link to Figma](https://www.figma.com/design/Qp56yzWMCb88SofnuhXhu3/Project-Detail-%5B-Public-%5D-(-%E2%9C%85-)?node-id=7329-1501&t=DWsyxTM2DyDxitgg-4)

**Comment by laurenluz** [comment]
Hey @divine-comedian - since Cherik is on vacation, who can we pass this too?

**Comment by divine-comedian** [comment]
@mosaeedi 

for the boost button we should consider variations of this button that we show under certain conditions, consider this for example: 

![image](https://github.com/user-attachments/assets/4fd31903-2a9f-48a6-9115-fc96d2f9b1b0)

We recently had to change the fixed width of this because the text is obviously much longer than the "Boost" one

**Comment by mosaeedi** [comment]
Where does this one come from? can you share the link to Figma with me?

**Comment by divine-comedian** [comment]
@mosaeedi no Figma - we needed to change the copy from this issue 
https://github.com/Giveth/giveth-dapps-v2/issues/4597

**Comment by mosaeedi** [comment]
@divine-comedian These UI issues are important to fix! Can we do it sooner?

**Comment by divine-comedian** [comment]
> @divine-comedian These UI issues are important to fix! Can we do it sooner?

Can you please update your issue to remove the fixed width for the boost button. This will prevent Developers from mistakenly reverting the change we made.

**Comment by divine-comedian** [comment]
@lovelgeorge99 do you have bandwidth to check into this?

**Comment by lovelgeorge99** [comment]
@divine-comedian Yes, I  will try to finish it by tomorrow

**Comment by mosaeedi** [comment]
> [@divine-comedian](https://github.com/divine-comedian) Yes, I will try to finish it by tomorrow

Please let me know when you made any changes I can quickly do the design QA.
Thanks.

**Comment by lovelgeorge99** [comment]
> > [@divine-comedian](https://github.com/divine-comedian) Yes, I will try to finish it by tomorrow
> 
> Please let me know when you made any changes I can quickly do the design QA. Thanks.

I have made changes for 1,2,3,4 and 6...and pushed the PR for review ...will fix 5 by today

**Comment by lovelgeorge99** [comment]
@mosaeedi for the logo's of supported networks can u provide the size of each logo..as i cannot see in figma

**Comment by mosaeedi** [comment]
Hey @lovelgeorge99 , The size of each icon is 24px X 24px

@RamRamez already developed this piece for the Donation page, maybe we can reuse the same component over here! the design is shared between the project details and the donation page.

**Comment by lovelgeorge99** [comment]
> Hey @lovelgeorge99 , The size of each icon is 24px X 24px
> 
> @RamRamez already developed this piece for the Donation page, maybe we can reuse the same component over here! the design is shared between the project details and the donation page.

ok thank you

**Comment by RamRamez** [comment]
Yes, we have that component, @lovelgeorge99 you can check `QFEligibleNetworks` component on donate page.
It will be shown on donate page only when project is in the current QF round.
