### ISSUE TITLE
QF bug - telling me I already donated but I did not.

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4728]
UI is teling me I already donated to public nouns operatios in the round, but I didn't!!

See?
![image](https://github.com/user-attachments/assets/8ed92519-3022-41a0-8ad8-aad69e102c77)

My donations:
![image](https://github.com/user-attachments/assets/7e8a0599-efe2-492b-aa22-e54be8c8bc8c)

I donated well before this round started.

Are we using the round "start time" to consider if the user donated? or the round "Active time? @CarlosQ96

**Comment by divine-comedian** [comment]
@CarlosQ96 coulnd't reproduce this issue @laurenluz

**Comment by divine-comedian** [comment]
@HrithikSampson do you mind investigating this one with guidance from @CarlosQ96

**Comment by HrithikSampson** [comment]
Sure @divine-comedian . I will investigate this.

**Comment by HrithikSampson** [comment]
@laurenluz , it seems that the round for the project needs to be active and it needs to be within the beginDate and endDate.

I am investigating but some donations arent also showing in the active QF Round

**Comment by HrithikSampson** [comment]
@laurenluz , I think that there were no rounds on September 3, when the donation was made


![Image](https://github.com/user-attachments/assets/c91e237c-8786-4130-944b-f810e028dbaa)

**Comment by laurenluz** [comment]
yes @HrithikSampson - there was no QF round on Sept 3 (when I did donate)... yet (when the QF round was active & live) the dapp was telling me that _I already donated to that project during this QF round, so my estimated matching will be wrong_

I should not have seen this prompt at all, so there is a bug, which is why I created this issue.

**Comment by CarlosQ96** [comment]
@HrithikSampson did you manage to replicate the issue? Can DM the details and ill continue.

**Comment by CarlosQ96** [comment]
@laurenluz @divine-comedian It's really weird this issue occured as looking at the query there is no way that message should happen by mistake.
The message is triggered if you have already donated to a project during the round, so you have 1 marked donation already on that project. 

This function takes into account userId, projectId, qfroundId and that the donation is verified.

However it does not take into account startTime. I can add that.

Reasons it could have happened it's too hard to debug atm and no way to tell from the backend. I checked the 3rd of september donation and its not marked in the round, so the function shouldn't have triggered that.  Not sure if it could have been some cache of sorts in the frontend. 

But to be sure it doesnt happen ill add the starttime condition

**Comment by CarlosQ96** [comment]
@divine-comedian Fix is ready to be merged on staging, approved by Ramin. But I am not sure how to replicate/test the issue. Not sure even QA can replicate it.

For now it's a band aid fix that forces checking the DATES too on top of the other conditions, to prevent the alert to show when it shouldn't.

Should we merge and release a hotfix? Then call it done but monitor it on the next round? What do you think?

**Comment by laurenluz** [comment]
this sounds good to me! I can keep an eye on it next round, since I experienced the original bug.
