### ISSUE TITLE
Stellar | Remove QF from production

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#4732]
**Describe the bug**

Stellar donation doesn't work for QF, buy users are not warn completely to understand it's not eligible. 

- [x]  Remove the QF banner shown in the stellar donation page, BOTH in connected and not connected scenarios

![image](https://github.com/user-attachments/assets/78d42430-6cef-4324-b9d2-d0ff7effcccb)

- [x] Remove the matching amount in project card in AMOUNT screen like above. 
![image](https://github.com/user-attachments/assets/f0789e50-3308-45a5-9e20-cc290b4be104)

- [x] Add a toast message like this (with the same styling) and change the copy:
![image](https://github.com/user-attachments/assets/f58e0103-2dec-43bb-a4fd-71e2f1d2bb75)

**Make your donation eligible for matching**
Donations made on {eligible QF round chains} are eligible to be matched. Stellar is not eligible for this round. 
Go back and make sure you're on the right network. {linked to https://giveth.io/donate/hand-protocol }

**Comment by maryjaf** [comment]
also estimated matching fund should be removed in this page

![image](https://github.com/user-attachments/assets/6b648eb5-bfe2-4be4-84a3-39cdb95be514)

**Comment by MoeNick** [comment]
@Meriem-BM @maryjaf 
I updated the success criteria and title.

**Comment by mohammadranjbarz** [comment]
https://giveth-dapps-v2-git-4732fixstellardoantecardui-givethio.vercel.app/?vercelToolbarCode=rLnDdl4rMPzg2vn


@MoeNick @maryjaf You can test it on preview link

**Comment by MoeNick** [comment]
@mohammadranjbarz Thank for the PR
the highlighted text should be linked in the read styling and we should remove those buttons in this case. For more context please check the details of the last item in the issue. 

![image](https://github.com/user-attachments/assets/d0515d04-44e6-4357-b5bf-4e0a920c6e83)

**Comment by maryjaf** [comment]
> https://giveth-dapps-v2-git-4732fixstellardoantecardui-givethio.vercel.app/?vercelToolbarCode=rLnDdl4rMPzg2vn
> 
> @MoeNick @maryjaf You can test it on preview link

1- 
- I tap on Donate button 
- in donation page , I tap on "donate with stellar"
- in this page the QF banner is shown and the box related to supported network isn't shown 

https://github.com/user-attachments/assets/4b0b4022-53ea-4ea4-bc16-c40bb70f9f78

@mohammadranjbarz

**Comment by maryjaf** [comment]
2-
The QF banners should be removed in this page
- I tap on "donate with stellar"
- I set an amount
- and the I tap on next 

https://giveth-dapps-v2-git-4732fixstellardoantecardui-givethio.vercel.app/donate/test-stellar?chain=stellar&draft_donation=1233

![image](https://github.com/user-attachments/assets/8322a287-af4a-4c66-8499-fab9c2e686d7)

**Comment by maryjaf** [comment]
4- 

The estimated matching, amount raised in round 
and also this message "Donate first and lead the way" if project has no donation in a round , shouldn't be shown in stellar donation page 
actully the normal view of donation should be shown 

![image](https://github.com/user-attachments/assets/b8f54de3-dec1-44a8-a92e-1ff4ad150bf8)

![image](https://github.com/user-attachments/assets/4136e0ff-e688-4333-b7a2-b013f3d3d599)

expected result :
 the normal view of donation should be shown in stellar donation page

![image](https://github.com/user-attachments/assets/9f93fb72-ca53-423c-9953-d6bdf57f3780)

**Comment by Meriem-BM** [comment]
Hey @maryjaf, @MoeNick can you check the remaining issues now
https://giveth-dapps-v2-ghngjaj4f-givethio.vercel.app/

**Comment by maryjaf** [comment]
> 3- This below message also should be removed in [stellar donation page ](https://giveth-dapps-v2-git-4732fixstellardoantecardui-givethio.vercel.app/donate/test-stellar?chain=stellar)
> 
> this message for project in a round is shown when user has donated to the project before

This banner is still shown in stellar donation page @Meriem-BM 

![image](https://github.com/user-attachments/assets/a025e81a-4945-4f2d-bf6b-9b60af4c253d)

**Comment by Meriem-BM** [comment]
> > 3- This below message also should be removed in [stellar donation page ](https://giveth-dapps-v2-git-4732fixstellardoantecardui-givethio.vercel.app/donate/test-stellar?chain=stellar)
> > this message for project in a round is shown when user has donated to the project before
> 
> This banner related to QF is still shown in stellar donation page @Meriem-BM

I added a fix @maryjaf  https://giveth-dapps-v2-6y5vg6yvh-givethio.vercel.app/

**Comment by Meriem-BM** [comment]
https://github.com/Giveth/giveth-dapps-v2/issues/4733#issuecomment-2352932213

**Comment by maryjaf** [comment]
Thanks @Meriem-BM all reported problems have been fixed
