### ISSUE TITLE
Stellar |  back button in Amount screen  should get back to original donation page. 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#4733]
**Describe the bug**

I clicked on back from the amount screen and I can still see this URL: https://giveth.io/donate/hand-protocol?chain=stellar 
it cause problems on QF errors and users may got confused. It has to go back to teh original donation path which is https://giveth.io/donate/hand-protocol
![image](https://github.com/user-attachments/assets/a0de6a35-79de-4e49-9023-d3a084e01e27)

CC: @maryjaf

**Comment by Meriem-BM** [comment]
Made a fix for this too @maryjaf if you can check
