### ISSUE TITLE
Empty form when Users attempt to apply for Givback Eligibilty for newly created Projects

### ISSUE THREAD

**Issue by LatifatAbdullahi** [Giveth/giveth-dapps-v2#4749]
**To Reproduce**
1. Given Users just created a new project
2. And User navigates and clicks on "My Project" section
3. And User clicks on the Action button of newly created project
4. And users click on "apply for Givback eligibility
5. Then Users are redirected to the Project verification form section
6. And the Form is empty with no way to proceed.

**Expected behavior**
Users should be able to fill and submit the Project verification form

**Screenshots**
![image](https://github.com/user-attachments/assets/c8258a5b-68b1-4841-b2c8-253e2d929abd)

Also: "**form**" is not correctly spelt here

![mmm](https://github.com/user-attachments/assets/960fe526-f5d3-44fb-9811-12bb8bcf81ac)

**Comment by divine-comedian** [comment]
I found this also happened for an existing project that had not started a verification form 

![image](https://github.com/user-attachments/assets/659a0605-e9cf-4bbf-82db-9219090c0035)

However if the project had already started a verification form but not yet completed it then it shows up correctly

**Comment by divine-comedian** [comment]
@MohammadPCh are you right person to investigate this? Could there have been some BE changes from renaming things that could have caused this?

**Comment by MohammadPCh** [comment]
@LatifatAbdullahi Can you re-check it? Thanks

**Comment by LatifatAbdullahi** [comment]
@divine-comedian 

**Test Update**

This issue has been fixed

New Projects
![image](https://github.com/user-attachments/assets/1c1c8477-a733-46cc-bb05-ebc6a7dedb8a)


Existing projects

![image](https://github.com/user-attachments/assets/a17040ec-df8c-4767-8f7e-feeb001cca99)
