### ISSUE TITLE
Revise GIVbacks picker to select the top 10 winners... not just 5 :-D

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4750]
In the UI of the GIVbacks picker right now we are just showing 5 txs as winning... I want to see 10!

The reason is because some of them end up as recircs and then we need to run it again, and this makes things weird... we sometimes end up with the same txs in the 2nd run, or donations from the same donors, etc.

So I want to see 10 :-D

**Comment by maryjaf** [comment]
I'm not sure where can I check this , could you please add more data? thanks 
@CarlosQ96

**Comment by CarlosQ96** [comment]
@maryjaf no need. WE tested in a testing party with Griff, @laurenluz, Auubree and more people. Its a vercel mini app we made.
