### ISSUE TITLE
Add hover tooltip descriptions on project status badges

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4751]
When a user hovers on the badges on the project details page we should show a hover tooltip with a short description of what those badges mean. We should only show the tooltips after the user has been hovering on the badge for 0.5 seconds.

![Image](https://github.com/user-attachments/assets/85b66352-2337-4212-b184-642c36468d14)

The copy shown on each tooltip should be as follows: 

## Vouched badge
> This project has been Vouched for as legitimate by Giveth Verifiers

## GIVbacks Eligible 
> This project has been verified as a Public Good by Giveth

FYI @mosaeedi 

# Requirements 
- tooltip shows correct copy for vouched badge
- tooltip shows correct copy for givbacks eligible badge
- tooltip only shown after .5 second delay WHILE hovering on the respective badge
- tooltip is not shown if the user isn't currently hovering over the given badge

**Comment by mateodaza** [comment]
@divine-comedian do we have copies for these already ?

**Comment by divine-comedian** [comment]
Copies are included in the issue above! Please review carefully the issue

![image](https://github.com/user-attachments/assets/05fe21da-cd0b-441e-b895-c20280f5f917)

**Comment by mateodaza** [comment]
woops, glasses not working 
thanks @divine-comedian 🤣

**Comment by divine-comedian** [comment]
@mateodaza can you share the PR associated with this, please update us when it is ready for QA

**Comment by mateodaza** [comment]
Not sure why it didn't connect it, but here it is

[PR](https://github.com/Giveth/giveth-dapps-v2/pull/4765)

**Comment by divine-comedian** [comment]
Reviewed! Looks good
