### ISSUE TITLE
QF of Stellar | Total matching amount on the project card on the amount page

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#4752]
As a user, I want to see how much matching funds the project gets with the given XLM amount I put there.

![image](https://github.com/user-attachments/assets/99a38585-0923-4e04-b6b6-b83644eb953a)

Design: https://www.figma.com/design/qXxAEsN3jePyRqBcHR9Ihq/Donation?node-id=6438-10552&m=dev

**Comment by MoeNick** [comment]
I dited the title sorry @HrithikSampson it was a typo I mean this amount on the project card 
![image](https://github.com/user-attachments/assets/4543238e-c96a-438f-9723-29a9a4029069)


Also when the design is ready for estimated matching @RamRamez will put it there based on this flow https://www.youtube.com/watch?v=oEHhmh6B7BE

**Comment by maryjaf** [comment]
- [ ] 1- The amount of estimated matching shouldn't be shown in stella donation page like as one time donation ? 

@MoeNick @HrithikSampson 

![image](https://github.com/user-attachments/assets/d4414165-fd0b-4db9-8e43-ca053591def6)

![image](https://github.com/user-attachments/assets/8b9327f4-6fd8-4f63-8d40-6900f26f21e6)


- [ ] 2- and also when the project has no donation in the round,  different designs are shown for one time and stellar donation, take a look on above pic ?

**Comment by maryjaf** [comment]
- [ ] 3- in success donation page also different designs related to project detail are shown for one time and stellar donation.
@MoeNick @HrithikSampson 

success donation stellar:

![image](https://github.com/user-attachments/assets/dc049f3d-83de-4f87-a310-39b916f1e1f2)

success donation one time:
![image](https://github.com/user-attachments/assets/aa0e4874-b924-45dd-8cff-d32e4cee560b)

**Comment by maryjaf** [comment]
- [ ] 4- this banner is shown for one time donation when I have donated to the project in this round before, but it isn't shown in stellar donation 


**You have already donated to this project so the estimated matching will be incorrect.**

![image](https://github.com/user-attachments/assets/3dd78e55-0ab6-452d-b10c-883349d9f651)
![image](https://github.com/user-attachments/assets/c32843a3-df6e-435d-9495-7c50c9f9969d)

**Comment by maryjaf** [comment]
> [ ] 2- and also when the project has no donation in the round, different designs related to project detail are shown for one time and stellar donation, take a look on above pic

- [ ] 5- when project has donation in the round

stellar donation
![image](https://github.com/user-attachments/assets/6c8a293c-7618-43f2-8114-3f78533abea2)
one time donation:
![image](https://github.com/user-attachments/assets/91278f7d-defc-4952-b2ed-c277b43d2764)

**Comment by HrithikSampson** [comment]
> As a user, I want to see how much matching funds the project gets with the given XLM amount I put there.
> 
> ![image](https://private-user-images.githubusercontent.com/80677512/368701663-99a38585-0923-4e04-b6b6-b83644eb953a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MzkwNTQsIm5iZiI6MTcyNjgzODc1NCwicGF0aCI6Ii84MDY3NzUxMi8zNjg3MDE2NjMtOTlhMzg1ODUtMDkyMy00ZTA0LWI2YjYtYjgzNjQ0ZWI5NTNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDEzMjU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlOWIzZDYwYWJhYjIwYTA1OWE2ZDNmNjc1MmJhYzEyNGJmYTk5Mjg4YTU0NjA4NzllYmQzYjJkZDhjNWQ5MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gxR69bd7PPDJBRZSccY-Q8YPYz-YPTvPukZU0oaw8Ok)
> 
> Design: https://www.figma.com/design/qXxAEsN3jePyRqBcHR9Ihq/Donation?node-id=6438-10552&m=dev

For Point Number 5 , 

I actually copied the same thing as shown here @maryjaf , can I keep the original ProjectCard

**Comment by maryjaf** [comment]
- [ ] 6- one question @MoeNick when my user isn't signed , should his stellar donation be shown in QF round donations?
now it is shown

![image](https://github.com/user-attachments/assets/1b664d85-cd65-406f-a42e-f8b68f939169)

**Comment by laurenluz** [comment]
yeah I think we can include it in QF round donations... although it won't actually influence the matching if they did not connect their wallet and verify gitcoin passport...

is there a way that users can go back to their stellar donation after the fact and connect their EVM wallet? or they need to connect wallet before doing the donation?

**Comment by HrithikSampson** [comment]
they can connect the wallet in the donation page.

> yeah I think we can include it in QF round donations... although it won't actually influence the matching if they did not connect their wallet and verify gitcoin passport...
> 
> is there a way that users can go back to their stellar donation after the fact and connect their EVM wallet? or they need to connect wallet before doing the donation?

**Comment by HrithikSampson** [comment]
@maryjaf, I think I have tried to fix points 1 through 5, I think it is ready to be tested

**Comment by maryjaf** [comment]
> * [ ]  1- The amount of estimated matching shouldn't be shown in stella donation page like as one time donation ?

now the estimated matching amount is also shown in stellar donation page , but it seems there is a problem in calculating this amount 
as you can see in below pics, in one time donation page , 1$ --> $835 estimated matching fund 
but in stellar donation page by entering every amount I see  the maximum of estimated matching fund , 1600$ 

Stellar donation:
![image](https://github.com/user-attachments/assets/06bb4a5d-6a2a-4534-b078-f8ac58a47e4d)


_______
One time donation:
![image](https://github.com/user-attachments/assets/75c1d0c4-488f-481a-bb69-9c70959d452a)

@HrithikSampson

**Comment by maryjaf** [comment]
> [ ] 2- and also when the project has no donation in the round, different designs related to project detail are shown for one time and stellar donation, take a look on above pic

This item hasn't been changed @HrithikSampson

**Comment by maryjaf** [comment]
> * [x]  5- when project has donation in the round

Thanks @HrithikSampson this item has been fixed 
One question related to design  @mosaeedi The "verified" badge should be shown in this page or not ?
now in stellar donation is shown and for one time it isn't shown
stellar:
![image](https://github.com/user-attachments/assets/e18c776d-754a-4667-90a9-600134552cee)

one time:
![image](https://github.com/user-attachments/assets/a595b952-39f4-472d-bb4e-11c497bc8ef5)

**Comment by mosaeedi** [comment]
This is how it should look like:

<img width="526" alt="Screenshot 2024-09-22 at 11 22 19 AM" src="https://github.com/user-attachments/assets/791ec1a1-25ef-4d33-8bd6-2c40f2a2a07a">

This is how it is right now: 
<img width="203" alt="Screenshot 2024-09-22 at 11 22 59 AM" src="https://github.com/user-attachments/assets/bcdf2485-5821-4ccd-ab7d-f6a94bbe53bc">

---

<img width="785" alt="Screenshot 2024-09-22 at 11 21 13 AM" src="https://github.com/user-attachments/assets/9d8cbcd1-48a9-4c4e-9f7d-73688fa7a515">

**Comment by mosaeedi** [comment]
> > * [x]   5- when project has donation in the round
> 
> Thanks @HrithikSampson this item has been fixed One question related to design @mosaeedi The "verified" badge should be shown in this page or not ? now in stellar donation is shown and for one time it isn't shown stellar: ![image](https://private-user-images.githubusercontent.com/111529185/369670818-e18c776d-754a-4667-90a9-600134552cee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5OTE3MjYsIm5iZiI6MTcyNjk5MTQyNiwicGF0aCI6Ii8xMTE1MjkxODUvMzY5NjcwODE4LWUxOGM3NzZkLTc1NGEtNDY2Ny05MGE5LTYwMDEzNDU1MmNlZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMlQwNzUwMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMGNjNzI0NTYzNDYyNDg3MzczYzg5ZTg1Y2E5MjM1MmE4ZDhlNzNmZDFkZjIzOTQyN2I1MmE3NDY0ZWNkMDIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WbAsoLgxLbbhrqePQssjkP_2qoxUAEmYAABDBTjd4M4)
> 
> one time: ![image](https://private-user-images.githubusercontent.com/111529185/369670835-a595b952-39f4-472d-bb4e-11c497bc8ef5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5OTE3MjYsIm5iZiI6MTcyNjk5MTQyNiwicGF0aCI6Ii8xMTE1MjkxODUvMzY5NjcwODM1LWE1OTViOTUyLTM5ZjQtNDcyZC1iYjRlLTExYzQ5N2JjOGVmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMlQwNzUwMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZjhiNWI4MDkwMDJhNjBiNGRjMzRkN2Y2ZmE3MDBjNTA4MTBmMTY0ZWU4MDJkMzEwOGI1Mzc1ZmNlYjI3OTYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DbJQ8eKSWzPQkrj1vZwbd2ae0K5EnuTeu9wJXy36QWg)

If it's not too much work, let's show the Verified badge on all types of donations.
It's not a blocker at all, but if we can make it look more consistent, let's do it.

**Comment by mosaeedi** [comment]
<img width="593" alt="Screenshot 2024-09-22 at 11 29 48 AM" src="https://github.com/user-attachments/assets/47284d45-9303-449e-8228-178d6a6f0dfe">

The estimated matching should stick to the amount input,
Also, please show/hide the estimated matching with a transition.

**Comment by MoeNick** [comment]
> yeah I think we can include it in QF round donations... although it won't actually influence the matching if they did not connect their wallet and verify gitcoin passport...
> 
> is there a way that users can go back to their stellar donation after the fact and connect their EVM wallet? or they need to connect wallet before doing the donation?

It's like having an anonymous donation. Do we accept anonymous donations for be counted on Matching Funds ? @laurenluz 

Although users will be notified they donation won't count if they don't sign. If it's not accepted let's change it.

**Comment by maryjaf** [comment]
- [ ] 7- when my user isn't signed in, the estimated matching shouldn't be shown @HrithikSampson 

![image](https://github.com/user-attachments/assets/19f297ab-bb81-4b98-99a1-d13afd35f59a)

**Comment by HrithikSampson** [comment]
Hi @maryjaf ,
I have tried to fix point 7 above and

> > * [ ]   1- The amount of estimated matching shouldn't be shown in stella donation page like as one time donation ?
> 
> now the estimated matching amount is also shown in stellar donation page , but it seems there is a problem in calculating this amount
> 
> * [ ]  as you can see in below pics, in one time donation page , 1$ --> $835 estimated matching fund
> 
> but in stellar donation page by entering every amount I see the maximum of estimated matching fund , 1600$
> 
> Stellar donation: ![image](https://private-user-images.githubusercontent.com/111529185/369668661-06bb4a5d-6a2a-4534-b078-f8ac58a47e4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwMTEwMDIsIm5iZiI6MTcyNzAxMDcwMiwicGF0aCI6Ii8xMTE1MjkxODUvMzY5NjY4NjYxLTA2YmI0YTVkLTZhMmEtNDUzNC1iMDc4LWY4YWM1OGE0N2U0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMlQxMzExNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYWEzMTdmYmVmNWQ2ODgyMDc3NDBkMWJkY2YzYmY3MDY3MjRiN2FhNmU3MTlmYTFkZWI5OGYyYTg4N2NhZWMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZiYlFQ6otasjFmMc_wS1CRjXJY-toQgyow_vRr-T7e8)
> 
> One time donation: ![image](https://private-user-images.githubusercontent.com/111529185/369668614-75c1d0c4-488f-481a-bb69-9c70959d452a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwMTEwMDIsIm5iZiI6MTcyNzAxMDcwMiwicGF0aCI6Ii8xMTE1MjkxODUvMzY5NjY4NjE0LTc1YzFkMGM0LTQ4OGYtNDgxYS1iYjY5LTljNzA5NTlkNDUyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMlQxMzExNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OGJhMTkyMWUxZGU0MmMzOGYxZjdlOGNmY2I2MmZkOTNkOTVjOGI2Njk4OGFjNjkzN2NiZTBkMzRlMDgxYjNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4cB98VaertkXDMZUfvvvS7v9soFAI6FhXG0TgqzedqY)
> 
> @HrithikSampson
> 
> * [ ]  and also when I set a amount that is lower than the minimum of donation for matching,  the estimated matching shouldn't be shown
> 
> ![image](https://private-user-images.githubusercontent.com/111529185/369668859-41313467-5c13-4e5a-b868-7d414dc02df8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwMTEwMDIsIm5iZiI6MTcyNzAxMDcwMiwicGF0aCI6Ii8xMTE1MjkxODUvMzY5NjY4ODU5LTQxMzEzNDY3LTVjMTMtNGU1YS1iODY4LTdkNDE0ZGMwMmRmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMlQxMzExNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYmYxNTVjMGMwN2Y5MjBkNjNjYmFjY2NjOGZmY2ExMjI1MWU2MTRiMWU5YzJlYzZjYjU0YzM1MTBjN2RkNWY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QUmV2nPEn78H4FH-ZXAJIk3Wan6EReXYtsN9A6M3k88)

**Comment by maryjaf** [comment]
> Hi @maryjaf , I have tried to fix point 7 above and

Thanks @HrithikSampson 1, 2 and 7 have been fixed

**Comment by HrithikSampson** [comment]
> > * [ ]  1- The amount of estimated matching shouldn't be shown in stella donation page like as one time donation ?
> 
> now the estimated matching amount is also shown in stellar donation page , but it seems there is a problem in calculating this amount 
> 
> - [ ] as you can see in below pics, in one time donation page , 1$ --> $835 estimated matching fund 
> 
> but in stellar donation page by entering every amount I see  the maximum of estimated matching fund , 1600$ 
> 
> Stellar donation:
> ![image](https://github.com/user-attachments/assets/06bb4a5d-6a2a-4534-b078-f8ac58a47e4d)
> 
> 
> _______
> One time donation:
> ![image](https://github.com/user-attachments/assets/75c1d0c4-488f-481a-bb69-9c70959d452a)
> 
> @HrithikSampson 
> 
> 
> 
> ______
> 
> - [ ] and also when I set a amount that is lower than the minimum of donation for matching,  the estimated matching shouldn't be shown 
> 
> ![image](https://github.com/user-attachments/assets/41313467-5c13-4e5a-b868-7d414dc02df8)
> 

@maryjaf , I have also tried to fix this.

**Comment by maryjaf** [comment]
> @maryjaf , I have also tried to fix this.

Yeah Thanks It has been fixed and 
all problems related to this issue have been passed, I'll move it to Done 
only some problems related to issue 4573 remains about stellar and QF

**Comment by MoeNick** [comment]
Hey @maryjaf I think only this use-case is left: 
As a user, I need to be notified that my donation won't match if Im not signed in. 
(I should be able to donate without connecting my wallet though after seeing this message) 

CC: @mosaeedi

**Comment by maryjaf** [comment]
Thanks @MoeNick The current  design is like as below pic, I'm aware of this change but  that you mentioned but I Thought this change is about this issue that ramin is working on it , if I'm wrong correct me 
https://github.com/Giveth/giveth-dapps-v2/issues/4731
![image](https://github.com/user-attachments/assets/e456dd77-2f89-415a-861d-56d2bb2f8628)

**Comment by mosaeedi** [comment]
We updated the copy to tell the user about QF matching too.

Please take a look here -> [Figma link](https://www.figma.com/design/qXxAEsN3jePyRqBcHR9Ihq/Donation?node-id=6660-2337&t=xqDkhkGxOG7ZCWC5-4)

CC: @MoeNick @maryjaf @RamRamez

**Comment by maryjaf** [comment]
- [ ] 8- There is an UI problem in donation page when there is no active round  @HrithikSampson 
https://giveth-dapps-v2-git-add-givbacks-and-qf-badges-ed2d3d-givethio.vercel.app/donate/test-stellar?tab=one-time&chain=stellar&draft_donation=1411
![image](https://github.com/user-attachments/assets/70bedf08-d73e-4094-9986-643c6a549057)

**Comment by mosaeedi** [comment]
> * [ ]  8- There is a new UI problem in donation page, the estimated matching shouldn't be shown in below pic  @HrithikSampson
>   https://giveth-dapps-v2-git-add-givbacks-and-qf-badges-ed2d3d-givethio.vercel.app/donate/test-stellar?tab=one-time&chain=stellar&draft_donation=1411
>   ![image](https://private-user-images.githubusercontent.com/111529185/369712262-70bedf08-d73e-4094-9986-643c6a549057.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNzM3NzgsIm5iZiI6MTcyNzA3MzQ3OCwicGF0aCI6Ii8xMTE1MjkxODUvMzY5NzEyMjYyLTcwYmVkZjA4LWQ3M2UtNDA5NC05OTg2LTY0M2M2YTU0OTA1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QwNjM3NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNWU2M2MxNWYwNmFhNzMxY2ZkYTBmMTdlNzlhY2EzYmFmZjY0ZDE3MzRkODJlZjlkNzgzNWVmNDk3YzgxNGY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.O9spcVKWJ0QAoKXWqiVlY14FPvjTOESym26G88vutJE)

## Yes, it's correct, 
we don't need to show the estimated matching here.

**Comment by maryjaf** [comment]
- [ ] 9- when the stellar network isn't in the list of supported network for QF this banner shouldn't be shown @HrithikSampson 

![image](https://github.com/user-attachments/assets/efcaddff-16ae-4a6a-9e86-e43009334480)

**Comment by RamRamez** [comment]
> * [x]  8- There is a new UI problem in donation page, the estimated matching shouldn't be shown in below pic  @HrithikSampson
>   https://giveth-dapps-v2-git-add-givbacks-and-qf-badges-ed2d3d-givethio.vercel.app/donate/test-stellar?tab=one-time&chain=stellar&draft_donation=1411
>   ![image](https://private-user-images.githubusercontent.com/111529185/369712262-70bedf08-d73e-4094-9986-643c6a549057.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwOTM5OTcsIm5iZiI6MTcyNzA5MzY5NywicGF0aCI6Ii8xMTE1MjkxODUvMzY5NzEyMjYyLTcwYmVkZjA4LWQ3M2UtNDA5NC05OTg2LTY0M2M2YTU0OTA1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QxMjE0NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNzBlNmVmY2JiM2RiNjM0MTIyNmIxODlhM2RjNWZlMDNhZTI3MzUwZGM4MjU2MzRjYzJiZWRiMWIwOTZjZDAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xKTauOpVQZXV0yPpKSm1XeBARo6VB6qn_HpMDAFNIQw)

@maryjaf This one is already fixed

**Comment by HrithikSampson** [comment]
@maryjaf , I have tried to fix 

> * [ ]  9- when the stellar network isn't in the list of supported networks for the QF round, this banner should this banner be shown in stellar donation page @MoeNick @laurenluz @HrithikSampson
> 
> ![image](https://private-user-images.githubusercontent.com/111529185/369797383-efcaddff-16ae-4a6a-9e86-e43009334480.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwOTUxMzksIm5iZiI6MTcyNzA5NDgzOSwicGF0aCI6Ii8xMTE1MjkxODUvMzY5Nzk3MzgzLWVmY2FkZGZmLTE2YWUtNGE2YS05ZTg2LWU0MzAwOTMzNDQ4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QxMjMzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OWY4YjBlN2IzOTFmMWRhMjYxYWZmMjE5MDJiMWU3NWI3MzQ4YWZlNGYyNTAwOTBlYWM5NGUzZWRlMGQzOWMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wfAwmKr0um0yJpXNqYuoZoUiYLG2TXKR6jOMAYQHmBU)

**Comment by RamRamez** [comment]
> We updated the copy to tell the user about QF matching too.
> 
> Please take a look here -> [Figma link](https://www.figma.com/design/qXxAEsN3jePyRqBcHR9Ihq/Donation?node-id=6660-2337&t=xqDkhkGxOG7ZCWC5-4)
> 
> CC: @MoeNick @maryjaf @RamRamez

@maryjaf It's done. You can test after 10 min.

**Comment by maryjaf** [comment]
> > We updated the copy to tell the user about QF matching too.
> > Please take a look here -> [Figma link](https://www.figma.com/design/qXxAEsN3jePyRqBcHR9Ihq/Donation?node-id=6660-2337&t=xqDkhkGxOG7ZCWC5-4)
> > CC: @MoeNick @maryjaf @RamRamez
> 
> @maryjaf It's done. You can test after 10 min.

when stellar isn't in list of supported networks in the round and the project is in a round this badge is shown and it isn't correct @RamRamez 

![image](https://github.com/user-attachments/assets/577df3a5-254c-49cf-a17a-56b83c704f08)

**Comment by HrithikSampson** [comment]
> > > We updated the copy to tell the user about QF matching too.
> > > Please take a look here -> [Figma link](https://www.figma.com/design/qXxAEsN3jePyRqBcHR9Ihq/Donation?node-id=6660-2337&t=xqDkhkGxOG7ZCWC5-4)
> > > CC: @MoeNick @maryjaf @RamRamez
> > 
> > 
> > @maryjaf It's done. You can test after 10 min.
> 
> when stellar isn't in list of supported networks in the round and the project is in a round this badge is shown and it isn't correct @RamRamez
> 
> ![image](https://private-user-images.githubusercontent.com/111529185/369890426-577df3a5-254c-49cf-a17a-56b83c704f08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxMDQ1MjYsIm5iZiI6MTcyNzEwNDIyNiwicGF0aCI6Ii8xMTE1MjkxODUvMzY5ODkwNDI2LTU3N2RmM2E1LTI1NGMtNDljZi1hMTdhLTU2YjgzYzcwNGYwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QxNTEwMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YTllM2UwYWY2ZDNiMTYyODVmNzY1YTNmNWY4MDhiNGQ2MTgzZTg2NjI1OTUxZmJkZTRjZmQ4YjQ4ZjZlMDgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.P0e-EzinOohCnx2QU5Q4I0AZKZlN4GbFqgyOKdIn8BE)

I have tried to fix it @maryjaf @RamRamez @mosaeedi

**Comment by mosaeedi** [comment]
<img width="112" alt="Screenshot 2024-09-23 at 7 15 28 PM" src="https://github.com/user-attachments/assets/e430b1e1-8df5-4a93-af70-37753e395229">

I've added the QF Round column.

[Link to Figma](https://www.figma.com/design/qXxAEsN3jePyRqBcHR9Ihq/Donation?node-id=6660-2337&t=En589WwbXJhHThax-4)

**Comment by HrithikSampson** [comment]
> <img alt="Screenshot 2024-09-23 at 7 15 28 PM" width="112" src="https://private-user-images.githubusercontent.com/13708322/369950567-e430b1e1-8df5-4a93-af70-37753e395229.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxMTMxODYsIm5iZiI6MTcyNzExMjg4NiwicGF0aCI6Ii8xMzcwODMyMi8zNjk5NTA1NjctZTQzMGIxZTEtOGRmNS00YTkzLWFmNzAtMzc3NTNlMzk1MjI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDE3MzQ0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5ODdmOTQzM2FhYjgwMDI2Y2E1Y2M2NzQxYzYyZTM1ZmY5MTRhNzEzZGFkN2I1OWI1ZDAxN2NkOTFiNTQ0OGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nbuwHIf5w7XSBseCbQVfnfalfQK2IrXmXUgWBmLLsIE">
> I've added the QF Round column.
> 
> [Link to Figma](https://www.figma.com/design/qXxAEsN3jePyRqBcHR9Ihq/Donation?node-id=6660-2337&t=En589WwbXJhHThax-4)

@maryjaf @mosaeedi @ramin, I have tried to fix this.
