### ISSUE TITLE
Add "is the donation anonymous" to GIVbacks API export

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4757]
I want an extra column in the data that Ashley grabs from the givbacks API each round that shows whether the donor selected the "donate anonymously" button, or not.

![image](https://github.com/user-attachments/assets/9c17e4ca-9502-47be-bfdc-aa25da56f0b9)

cc @WhyldWanderer

**Comment by mohammadranjbarz** [comment]
@WhyldWanderer @maryjaf It's on staging and is ready for the test

**Comment by maryjaf** [comment]
I made an anonymous donation but I see this response in givback api , could you please take a look @mohammadranjbarz 
[
  {
    "amount": 5,
    "currency": "GIV",
    "createdAt": "2024-09-26-06:25:10",
    "valueUsd": 5,
    "anonymous": true,
    "bottomRankInRound": 35,
    "givbacksRound": 51089,
    "projectRank": 22,
    "givbackFactor": 0.61470586,
    "valueUsdAfterGivbackFactor": 3.0735293,
    "giverAddress": "0xa1179f64638adb613ddaac32d918eb6beb824104",
    "txHash": "0x8a10dc5e0846d1380f5bb43a2ea6a54ac51f6b98931095687d7178907096578b",
    "network": "optimism-sepolia",
    "source": "giveth.io",
    "giverName": "mary jafarimehr",
    "giverEmail": null,
    "projectLink": "https://giveth.io/project/mejan",
    "isReferrerGivbackEligible": false,
    "referrerWallet": null
  },
  
  ![image](https://github.com/user-attachments/assets/bdb6c84e-3602-4303-b8e9-51a66113fe06)
  https://staging.giveth.io/project/mejan?tab=donations

**Comment by maryjaf** [comment]
I made an anonymous donation and I see the below response in givback api, 
this field is added in response :
"anonymous": true,
[
{
"amount": 5,
"currency": "GIV",
"createdAt": "2024-09-26-06:25:10",
"valueUsd": 5,
"anonymous": true,
"bottomRankInRound": 35,
"givbacksRound": 51089,
"projectRank": 22,
"givbackFactor": 0.61470586,
"valueUsdAfterGivbackFactor": 3.0735293,
"giverAddress": "0xa1179f64638adb613ddaac32d918eb6beb824104",
"txHash": "0x8a10dc5e0846d1380f5bb43a2ea6a54ac51f6b98931095687d7178907096578b",
"network": "optimism-sepolia",
"source": "giveth.io",
"giverName": "mary jafarimehr",
"giverEmail": null,
"projectLink": "https://giveth.io/project/mejan",
"isReferrerGivbackEligible": false,
"referrerWallet": null
},
