### ISSUE TITLE
Define Events to trigger notifications

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#476]
**Events to trigger notification:**

- Profile Needs to be completed
- Profile is completed.
- Donation is made. 
- Errors on Donation from backend 
- Project is saved as a draft
- Project is published
- Project is listed
- Project is delisted
- Project is canceled
- Projects deactivated
- Project is reactivated
- Project is get verified. 
- Project is getting donations. 
- Project is liked.

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz @mateodaza @aminlatifi I love to have your opinions on this.

I love this, and I think all of them are good ( except the part of sending email after project has been liked, because there is a risk that make us spam)

Besides I think maybe verifying email should be required, otherwise someone else can use your email for his account and you would get lots of emails you don't want to recieve

**Comment by divine-comedian** [comment]
> **Events to trigger notification:**
> 
> * Profile Needs to be completed
> * Profile is completed.
> * Donation is made.
> * Errors on Donation from backend
> * Project is saved as a draft
> * Project is published
> * Project is listed
> * Project is delisted
> * Project is canceled
> * Projects deactivated
> * Project is reactivated
> * Project is get verified.
> * Project is getting donations.
> * Project is liked.
I think if we have a notification center that makes lots of sense. Here's my thought on what should trigger an email or not based on the list above. 

Profile Needs to be completed - no email
Profile is completed. - no email
Donation is made. - email
Errors on Donation from backend - email
Project is saved as a draft - no email
Project is published - email
Project is listed - email
Project is delisted - email
Project is canceled - email
Projects deactivated - no email
Project is reactivated - no email
Project is get verified. - email
Project is getting donations. - no email
Project is liked. - no email

**Comment by MoeNick** [comment]
Guys, @mohammadranjbarz @mateodaza @divine-comedian 
Its not about just sending emails. Its about letting the user select which on event event he/she receive notification, on which channel. 

Currently we only have email, we are going to add web notifications (or messages) in the DApp right next to the header below a **bell icon**

So we may first, list all events and let the user turn off/ on them in the settings. 

So for example we can set default value of _event 1_ false for _channel 1_ and set it true for _channel 2_

**Comment by mateodaza** [comment]
@MoeNick should we add "Liked projects updates" to this list?
Following up this [issue](https://github.com/Giveth/giveth-dapps-v2/issues/451)

**Comment by divine-comedian** [comment]
I think default the notification center won't annoy the user so much if we show too many updates - if we can have an MVP of the notification center that doesn't have all the custom notification toggles AND we can stop sending so many emails that would be an awesome update in itself.

**Comment by MoeNick** [comment]
> @MoeNick should we add "Liked projects updates" to this list?
> 
> Following up this [issue](https://github.com/Giveth/giveth-dapps-v2/issues/451)
> 
> 
> 
> So when a project is updated, the user that liked it will get a notification 

Yeah it's subscribing thing that we had a talk about it with design team and @Tosinolawale

**Comment by maryjaf** [comment]
I listed & then unlisted my project in admin and my expection is i see these notification in response of get notification (https://staging.notification.giveth.io/v1/notifications?limit=20&offset=0&isRead=false) but i didn't.
@mohammadranjbarz please check this and advise

**Comment by mohammadranjbarz** [comment]
> I listed & then unlisted deactivate & reactive my project in admin and my expection is i see these notification in response of get notification (https://staging.notification.giveth.io/v1/notifications?limit=20&offset=0&isRead=false) but i didn't. @mohammadranjbarz please check this and advise

@maryjaf  Thanks for your report, there was an access error between microservices (impact-graph and notification-center), I fixed the nginx , now it works for me, please test it again

**Comment by maryjaf** [comment]
The result of checking 

Review by @mohammadranjbarz :
1-When the project is active and inactive from the user panel, the notification is not sent .
2-Verify and unverified notification  are not sent from the admin panel

Check with @MoeNick :
1-Check the final list of actions that need to be notified 
2-Currently, the actions that are performed from the edit section of the project from the admin are not sent a notification
and for this reason, if an action is taken from the list that does not necessarily lead to a change in the status of the project, the notification will still be sent.

**Comment by maryjaf** [comment]
Tested & pass(notification is sent):
Project is saved as a draft
"name": "Project created",
"description": "Project has been created.",
---
Project is published
name": "Draft published",
"description": "Project draft has been published",
---
Project is listed
"description": "Project has been listed!",
 "schemaValidator": "projectListed",
--
Project is delisted
"description": "Project has unlisted!",
 "schemaValidator": "projectUnlisted",
----
Project is canceled
"description": "Project has been cancelled",
 "schemaValidator": "projectCancelled",
----
Projects deactivated(admin/user)
"name": "Project deactivated",
 "description": "Project has been deactivated",
---
Project is activated(admin/user)
"name": "Project activated",
"description": "Project has been activated!",
---
Project is get verified.
"name": "Project verified",
"description": "Project has been verified! Rejoice!",
---
Project revoke badge(unverified)?
"name": "Project unverified",
 "description": "Project has been unverified",
---
Project rejected(unverified)?
"name": "Project unverified",
 "description": "Project has been unverified",
---------------------------------------------------
Tested & failed:(notification is not sent):
Profile Needs to be completed
Profile is completed
Project is liked
-------------------------------------------------------
Not tested:
Donation is made.
Errors on Donation from backend
Project is getting donations.

**Comment by maryjaf** [comment]
According to a chat with @mohammd we have to change some logics ther, moving to sprint planning.

**Comment by maryjaf** [comment]
currently, notifications are only triggered when admin actions are performed from the list of projects
but for example, if the project verification is done from the project detail page, the notification will not be sent.
For this, it is necessary to create new issue ? @MoeNick @mohammadranjbarz
