### ISSUE TITLE
ensure GIVbacks Eligiblity status on project details is correct

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4763]
When I "verify'/vouch a project from the admin panel I noticed it changes the GIVbacks Eligibility of the project to "Eligible" even though the project is not eligible to receive GIVbacks.

https://github.com/user-attachments/assets/80326ff5-f058-4e1f-bcbd-aefa3fdafa39

The field for GIVbacks Eligiblity on both the project details page and the project cards on "my projects" should consider two things 

1. the status of the project's GIVbacks eligiblity form
2. if the field for `isGIVbacksEligible` is true or false

It should not be related to the projects `verified` or "Vouched" status

## AC
From project details page and project cards on my projects page:
- [ ] changing project's status to vouched/verified from admin panel DOES NOT change GIVbacks eligiblty status to eligible
- [ ] changing project's status to vouched/verified from admin panel DOES NOT change GIVbacks eligiblty BADGE
- [ ] status of givbacks eligiblity updates correctly based on status of application form "not started = not eligible, in progress = Incomplete, submitted = submitted"
- [ ] givbacks eligiblity shows as eligible when application form is approved in admin panel
- [ ] can revoke givbacks eligiblity status from admin panel and reflects on project status for givbacks eligiblity badge

view guide here for how to manage project status from admin panel -> https://www.notion.so/giveth/Giveth-Verification-Team-Guide-1043ab28d48c80d4bd5bff85259a890c?pvs=4#7742cef0a680423cadcc8d2efbd9caea

**Comment by mateodaza** [comment]
This is ready to test @divine-comedian

**Comment by divine-comedian** [comment]
@LatifatAbdullahi passing to you for QA

**Comment by LatifatAbdullahi** [comment]
@mateodaza 

This issue doesnt seem fixed, please take a look


After  updating the status of a new project to "Verified" from the Admin panel, the Givback Eligibility status was still updated to "Eligible" on the Project details page as shown below. Also the "Is Givback Eligible" remains "No" at the Admin panel.


![elli](https://github.com/user-attachments/assets/4ed01b43-bf44-4e03-98ca-56579dabf79b)


![snn](https://github.com/user-attachments/assets/4e9224d8-0222-4840-9f2b-04e627e24a9c)

**Comment by mateodaza** [comment]
@divine-comedian I noticed we don't have an updated copy for this scenario, wrongly left the previous one

this is the case where
- You are an owner, your project is verified but it's NOT givback eligible

This is the current copy, can you help me change it? - just revised the logic and it's fine, what's wrong is the copy

`	
	"project.givback_toast.title.verified_owner_not_eligible": "Your project has been Vouched for",

"project.givback_toast.description.verified_owner_not_eligible": "Your project has been vouched for by Giveth Verifiers and can now benefit from GIVpower! Stake and lock your GIV tokens to boost this project and make it more visible on the projects page. However, donating to this project won't yield GIVbacks to donors.",

`

**Comment by LatifatAbdullahi** [comment]
@mateodaza the initial issue with verifying  automatically changing status to Givbacl eligible has been fixed.

**However, after approving projects, the GIVback status is updated on Project card , the top of the Project details page but not in the project details page, it still shows "Ineligible"**





![yy](https://github.com/user-attachments/assets/2f5db98d-515f-464f-9195-c579f9f34b11)


![iiii](https://github.com/user-attachments/assets/8877694c-5512-4cf6-90fd-bb3b8505aa2b)

**Comment by divine-comedian** [comment]
@LatifatAbdullahi this seems like a bug 

If a project has the GIVbacks eligible badge, isGIVbacksEligibile from the project data then it should show "Eligible" next to the GIVbacks eligibility project status on the card. 

Can you confirm what you did? 

You went to the project in the admin panel and hit verify - this was NOT from approving the verificaition application form, correct?

**Comment by LatifatAbdullahi** [comment]
@divine-comedian Yes this is a bug,
What I said was fixed was the issue I reported last night.

From the Admin panel, went to the "Project" section to verify the new project.

The project became verified/vouched.

On the project details page, you can see the "Vouched" badge and the Givback Eligibility changed from "submitted" to "Ineligible".

From the Admin panel "Project verification form" section, I approved the project.

The Givback eligible badge is shown on the Project card, Top of the project details page but the 
Givback Eligibility status remained "Ineligible".

**Comment by divine-comedian** [comment]
Thanks! I tested it out and it seems something is being handled wrong in the admin, just as you suggested latifat

I made a table here that hopefully can carefully explain the impact of each action in the admin and what the expected outcome should be on the projects status for a variety of conditions

there are 4 columns: 
1. the current status of the 3 relevant values: givbacks form, verified, isGIVbacksEligible
2. the action being applied
3. the expected status of the 3 values 
4. notes (error conditions etc..) 

you can also view the sheet in google where it might look a bit easier to follow
https://docs.google.com/spreadsheets/d/1RTvg0YaMjEyZOgUpW1i0YQPnnlEPgHZM7ZDXq5e39ro/edit?usp=sharing

| current status |  |  | action | expected status |  |  | notes |
| --- | --- | --- | --- | --- | --- | --- | --- |
| givbacks form  | verified | isGIVbacksEligible |  | givbacks form  | verified | isGIVbacksEligible |  |
| not started | FALSE | FALSE | verify project (vouch) | not started | TRUE | FALSE |  |
| incomplete | FALSE | FALSE | verify project (vouch) | incomplete | TRUE | FALSE |  |
| submitted | FALSE | FALSE | verify project (vouch) | submitted | TRUE | FALSE |  |
| approved | TRUE | TRUE | verify project (vouch) | approved | TRUE | TRUE | (no status change) |
| declined | FALSE | FALSE | verify project (vouch) | declined | TRUE | FALSE |  |
| not started | TRUE | FALSE | revoke badge (vouch) | not started | FALSE | FALSE |  |
| incomplete | TRUE | FALSE | revoke badge (vouch) | incomplete | FALSE | FALSE |  |
| submitted | TRUE | FALSE | revoke badge (vouch) | submitted | FALSE | FALSE |  |
| approved | TRUE | TRUE | revoke badge (vouch) | throws error | -- | -- | (cannot revoke Vouched badge of GIVbacks eligible project) |
| declined | TRUE | FALSE | revoke badge (vouch) | declined | FALSE | FALSE |  |
| not started | TRUE | FALSE | approve application form (givbacks eligible) | throws error | TRUE | -- | (cannot approve unsubmitted or incomplete application) |
| not started | FALSE | FALSE | approve application form (givbacks eligible) | throws error | FALSE | -- | (cannot approve unsubmitted or incomplete application) |
| incomplete | TRUE | FALSE | approve application form (givbacks eligible) | throws error | TRUE | -- | (cannot approve unsubmitted or incomplete application) |
| incomplete | FALSE | FALSE | approve application form (givbacks eligible) | throws error | FALSE | -- | (cannot approve unsubmitted or incomplete application) |
| submitted | TRUE | FALSE | approve application form (givbacks eligible) | approved | TRUE | TRUE |  |
| submitted | FALSE | FALSE | approve application form (givbacks eligible) | approved | TRUE | TRUE |  |
| approved | TRUE | TRUE | approve application form (givbacks eligible) | approved | TRUE | TRUE | (no status change) |
| approved | FALSE | TRUE | approve application form (givbacks eligible) | approved | TRUE | TRUE | (should be impossible for verified = false while GIVbacks eligible = true |
| declined | TRUE | FALSE | approve application form (givbacks eligible) | approved | TRUE | TRUE |  |
| declined | FALSE | FALSE | approve application form (givbacks eligible) | approved | TRUE | TRUE |  |
| not started | TRUE | FALSE | reject application form (givbacks eligible) | throws error | TRUE | -- | (cannot reject unsubmitted or incomplete application) |
| not started | FALSE | FALSE | reject application form (givbacks eligible) | throws error | FALSE | -- | (cannot reject unsubmitted or incomplete application) |
| incomplete | TRUE | FALSE | reject application form (givbacks eligible) | throws error | TRUE | -- | (cannot reject unsubmitted or incomplete application) |
| incomplete | FALSE | FALSE | reject application form (givbacks eligible) | throws error | FALSE | -- | (cannot reject unsubmitted or incomplete application) |
| submitted | TRUE | FALSE | reject application form (givbacks eligible) | declined | TRUE | FALSE |  |
| submitted | FALSE | FALSE | reject application form (givbacks eligible) | declined | FALSE | FALSE |  |
| approved | TRUE | TRUE | reject application form (givbacks eligible) | declined | TRUE | FALSE |  |
| approved | FALSE | TRUE | reject application form (givbacks eligible) | declined | FALSE | FALSE |  |
| declined | TRUE | FALSE | reject application form (givbacks eligible) | declined | TRUE | FALSE | (no status change) |
| declined | FALSE | FALSE | reject application form (givbacks eligible) | declined | FALSE | FALSE | (no status change) |

**Comment by mateodaza** [comment]
> @divine-comedian Yes this is a bug, What I said was fixed was the issue I reported last night.
> 
> From the Admin panel, went to the "Project" section to verify the new project.
> 
> The project became verified/vouched.
> 
> On the project details page, you can see the "Vouched" badge and the Givback Eligibility changed from "submitted" to "Ineligible".
> 
> From the Admin panel "Project verification form" section, I approved the project.
> 
> The Givback eligible badge is shown on the Project card, Top of the project details page but the Givback Eligibility status remained "Ineligible".

This is an admin mess, basically the badge is checking the verification form first and then the real isGivbackEligible, that's why the false positive

Just pushed a change where we ONLY check on isGivbackEligible as the main truth - all other statuses should remain the same

**Comment by divine-comedian** [comment]
@LatifatAbdullahi ready for test again based on the original AC

**Comment by LatifatAbdullahi** [comment]
Currently unable to test updating Givback eligibility status due to this issue : https://github.com/Giveth/giveth-dapps-v2/issues/4796

**Comment by divine-comedian** [comment]
this project appears to still not be getting the correct badges @mateodazab 

https://staging.giveth.io/project/testing-the-success-view

form status = draft (even though I've already submitted it and approved it before) 
verified = false 
givbacks = true

**project card shows givbacks badge but NOT vouched badge | it should show both badges**

**project details page shows NO badges | it should show both givbacks and vouched badge**

if I change the form status = approved still no change on the badges that appear

![image](https://github.com/user-attachments/assets/e4e60a61-3965-4648-911e-dcb6cf2ac28b)
![image](https://github.com/user-attachments/assets/b9b97776-8ecb-4459-bd7b-b1a881d7c649)

### status in admin

![image](https://github.com/user-attachments/assets/132fe3d5-3825-482b-8571-ded07d4346c8)
![image](https://github.com/user-attachments/assets/090d98bf-8cd4-44a4-a820-39fe2d3a1d11)

**Comment by LatifatAbdullahi** [comment]
Verify/Vouch a Project(True) - Pass
Verify/Vouch a Project(Pass) - Pass
Givback Eligible (True) - Pass
Givback Eligible (False) - Pass
Verify/Vouched(True) + Givback Eligible(True) -  Pass





However when a new project is verified, then the Givback Eligibilty status(Submitted) is changed to "Ineligible".
A new bug has been created for this issue


![image](https://github.com/user-attachments/assets/1badf2db-cfa5-4e67-a2b3-fe14bdeb9efb)

**Comment by LatifatAbdullahi** [comment]
@mateodaza @divine-comedian 

Status: **Test passed**

This now works as expected and the status are correctly displayed.

**Comment by LatifatAbdullahi** [comment]
@mateodaza 

Putting the Table above into consideration

approved |GIVback - TRUE | Verified - TRUE | reject (vouch) | throws error | -- | -- | (cannot revoke Vouched badge of GIVbacks eligible project) |   


**No error is thrown when Admin Users attempt to Remove/Revoke Vouched for Givback Eligible projects**

**Comment by divine-comedian** [comment]
> @mateodaza @RamRamez
> 
> Putting the Table above into consideration
> 
> Givback form - Approved |GIVback - TRUE | Verified - TRUE | Action : reject (vouch) | Expected : throws error | -- | -- | (cannot revoke Vouched badge of GIVbacks eligible project) |  
> 
> **No error is thrown when Admin Users attempt to Remove/Revoke Vouched for Givback Eligible projects and the revoke action was successful**
> 
> In addition
> 
> Table Info Givback - Approved | Verified - FALSE | Givback - TRUE | Action: approve application form (givbacks eligible) | Expected : approved | Verified - TRUE | Givback : TRUE | (**should be impossible for verified = false while GIVbacks eligible = true**)
> 
> Considering the above from the table
> 
> **When the project is not vouched, and the Givback form is approved, the Vouched status didnt automatically update to verified when the Givback status is now Eligible.**
> 
> Aside these the other statuses works as expected.

@LatifatAbdullahi let's follow up the table conditions in https://github.com/Giveth/impact-graph/issues/1848
