### ISSUE TITLE
Setting Page - to enable/disable notifs on different channels

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#477]
## Design resource
**Important: General setting is not a tab and users can't close it!**

Notification settings / Default -> [Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=12508%3A232879)
_In the default state, all tabs are closed._

Notification settings / Project activities - > [Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=12069%3A208344)

Notification settings / GIVeconomy settings -> [Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=12076%3A209291)

---

![Screen Shot 2022-08-16 at 4.13.55 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/67168569-1c4a-4f60-9df1-eb9b13b2f4ed)

**Comment by Tosinolawale** [comment]
> 

Yeah we can. I will just resolve it on Notification settings

**Comment by MoeNick** [comment]
Let's finalize it @Tosinolawale , shall we start next week ?

**Comment by Tosinolawale** [comment]
> 

Started work on this currently. Will have something for you tomorrow

**Comment by MoeNick** [comment]
@MoeNick to sync frontend and backedn together. 
@CarlosQ96 would you pls snd the related endpoints here.

**Comment by CarlosQ96** [comment]
Hey @MohammadPCh @alireza-sharifpour @RamRamez 
This are the docs for the staging backend: https://staging.notification.giveth.io/docs

Here are the endpoints:
1. GET https://staging.notification.giveth.io/v1/notification_settings
    -  Retrieves User notifications
    -  Query Params: limit, offset, category
    -  Category is optional for extra filtering, but posible values are: general, projectRelated, givEconomy
    - Only General and projectRelated are available, there is no givEconomy yet.
    - This returns:
```
{
  "count": 0,
  "notificationSettings": [
    {
      "id": 0,
      "isGlobalSetting": true,
      "allowNotifications": true,
      "allowEmailNotification": true,
      "allowDappPushNotification": true,
      "notificationType": {
        "id": 0,
        "microService": "string",
        "name": "string",
        "description": "string",
        "schemaValidator": "string",
        "category": "string",
        "emailNotifierService": "string",
        "emailNotificationId": "string",
        "pushNotifierService": "string",
        "requiresTemplate": true,
        "htmlTemplate": "string",
        "title": "string",
        "content": "string",
        "notificationSettings": [
          "string"
        ],
        "createdAt": "2022-09-13T14:48:14.664Z",
        "updatedAt": "2022-09-13T14:48:14.664Z"
      },
      ........ etc
   ]
}
```
2. PUT https://staging.notification.giveth.io/v1/notification_settings/:id
    -  Updates a given notification by id
    -  Body Params: Id, allowNotifications, allowEmailNotification, allowDappPushNotification
    -  The allow notifications body params are strings (true or false)
    -  This returns: 
```
{
  "id": 0,
  "isGlobalSetting": true,
  "allowNotifications": true,
  "allowEmailNotification": true,
  "allowDappPushNotification": true,
  "notificationType": {
    "id": 0,
    "microService": "string",
    "name": "string",
    "description": "string",
    "schemaValidator": "string",
    "category": "string",
    "emailNotifierService": "string",
    "emailNotificationId": "string",
    "pushNotifierService": "string",
    "requiresTemplate": true,
    "htmlTemplate": "string",
    "title": "string",
    "content": "string",
    "notificationSettings": [
      "string"
    ],
    "createdAt": "2022-09-13T14:48:14.655Z",
    "updatedAt": "2022-09-13T14:48:14.655Z"
  },
  "notificationTypeId": 0,
  "userAddress": {
    "id": 0,
    "walletAddress": "string",
  }
}
```

**Comment by MohammadPCh** [comment]
Thanks @CarlosQ96

**Comment by MoeNick** [comment]
Hey @CarlosQ96 
As per discussed, can you also relate them here, so I have clue about how can I work on the product side with @mosaeedi ?

**Comment by maryjaf** [comment]
In figma for Notification settings / Project activities, verification form status is not explained, the notification is not sent after verify or un-verify? @MoeNick

**Comment by maryjaf** [comment]
I staked and got rewarded but i didn't receive any notification about these, even though they are active in the setting @RamRamez @mohammadranjbarz 
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/a1a10df8-c7c8-4947-842e-695733ee42c2)

**Comment by RamRamez** [comment]
> I staked and got rewarded but i didn't receive any notification about these, even though they are active in the setting @RamRamez @mohammadranjbarz ![image.png](https://camo.githubusercontent.com/6385ee023916a7179c5f005c7816659e52497f39848b4b2f25d340b52bcbcbf0/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f61316131306466382d633763382d343934372d383432652d363935373333656534326332)

@CarlosQ96 I use typeId 59 and 60 for these settings. Are they correct?

**Comment by CarlosQ96** [comment]
They are correct, but please hold off on the testing of giveconomy notifications this logic does not exist yet. We have to write a service that listens to a new subgraph for changes. That’s a lot of work and is not yet done.

**Comment by CarlosQ96** [comment]
@maryjaf @RamRamez

**Comment by CarlosQ96** [comment]
Right now giveconomy notifications settings mostly change the Boolean value of the database.

**Comment by CarlosQ96** [comment]
So you can mostly check if the checkmark persist when disabling or enabling.

**Comment by maryjaf** [comment]
> Right now we are migrating sending emails from impact graph backend to the Notification Center backend. So some notifications might send emails right now even when you disable it.
> 
> After Mohammad migrates that part. We will move on to GIVeconomy notifications implementation but it’s on planning stages.

Thanks 
So now this issue is blocked and the test cannot be completed? @CarlosQ96 @MoeNick 
Can you please send the link of this issue?

**Comment by maryjaf** [comment]
> In "Notification settings / Project activities" figma, verification status is not shown in Notification settings, the notification is not sent after verify or un-verify project from admin panel? @MoeNick

I tested, the notification is sent after verify or un-verify project, but this verification item is not mentioned in the project activities. @MoeNick 
<img width="1167" alt="image" src="https://user-images.githubusercontent.com/111529185/201485756-285a15c2-4a29-4494-83b7-a5c7ea9df160.png">

**Comment by maryjaf** [comment]
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/111529185/201486332-2d46eefd-9f82-463b-89f7-096fa8e3682b.png">
<img width="828" alt="image" src="https://user-images.githubusercontent.com/111529185/201486484-ee0b2a4d-189f-48b0-86a6-21ee0fa4ecf1.png">
Figma and test environment are different

**Comment by RamRamez** [comment]
> ![image.png](https://camo.githubusercontent.com/119c9772949fb344d4f98136aab8e27a020d7294c2afc63855adc3acd1e3d79f/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f66623865613435652d393462362d346133392d386535342d373563663637313065383264) <img alt="image" width="828" src="https://user-images.githubusercontent.com/111529185/201486484-ee0b2a4d-189f-48b0-86a6-21ee0fa4ecf1.png"> Figma and test environment are different @RamRamez Is it okay that both items have the same title? @mosaeedi

Yeah, @MoeNick added two new rows.

**Comment by maryjaf** [comment]
> > ![image.png](https://camo.githubusercontent.com/119c9772949fb344d4f98136aab8e27a020d7294c2afc63855adc3acd1e3d79f/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f66623865613435652d393462362d346133392d386535342d373563663637313065383264) <img alt="image" width="828" src="https://user-images.githubusercontent.com/111529185/201486484-ee0b2a4d-189f-48b0-86a6-21ee0fa4ecf1.png"> Figma and test environment are different @RamRamez Is it okay that both items have the same title? @mosaeedi
> 
> Yeah, @MoeNick added two new rows.

Yeah, but Is it okay that both items have the same title? @MoeNick

**Comment by RamRamez** [comment]
> ing notification and email by deactivating the project,I couldn't deactive my proje

selecting a reason is required in that form

**Comment by maryjaf** [comment]
> > To test sending notification and email by deactivating the project,I couldn't deactive my project and "deactive project"button doesn't work, plz check @RamRamez
> 
> @maryjaf selecting a reason is required in that form
ohhhhh :((

**Comment by maryjaf** [comment]
Boost scenarios cannot be tested on this branch https://notification-center-13.vercel.app/

**Comment by MohammadPCh** [comment]
@maryjaf no, we don't have them here, also as I know we don't send notifications for boosts now. it's not implemented yet.

**Comment by maryjaf** [comment]
> The result of sending notification and email test so far: @mohammadranjbarz @RamRamez -Publish Email:ok Notif: not ok
> 
> -Update Project(You Posted an update on your project & When your liked project has an update) Email: not ok Notif: not ok
> 
> -Project likes Email: not ok Notif: ok
> 
> -List & Unlist Email: not ok Notif: ok
> 
> -Deactive & Reactive(by custmer & admin) Email: not ok Notif: ok
> 
> -Cancel Project Email: not ok Notif: ok
> 
> Edit my project: (it isn't shown in notification center setting @MoeNick ) Email: not ok Notif: ok
> 
> Donate (When someone donates to your project & when you donate to a project) Email: ok Notif: ok

Please check this test result and plan to fix the cases where the email or notification is not sent @mohammadranjbarz @MoeNick @RamRamez

**Comment by MoeNick** [comment]
> > > ![image.png](https://camo.githubusercontent.com/119c9772949fb344d4f98136aab8e27a020d7294c2afc63855adc3acd1e3d79f/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f66623865613435652d393462362d346133392d386535342d373563663637313065383264) <img alt="image" width="828" src="https://user-images.githubusercontent.com/111529185/201486484-ee0b2a4d-189f-48b0-86a6-21ee0fa4ecf1.png"> Figma and test environment are different @RamRamez Is it okay that both items have the same title? @mosaeedi
> > 
> > 
> > Yeah, @MoeNick added two new rows.
> 
> Yeah, but Is it okay that both items have the same title? @MoeNick

Let's change it to:
1- Your project update
2- Your liked project update

1- Your project status
2- Your liked project status

@RamRamez @maryjaf

**Comment by RamRamez** [comment]
> 



> > > > ![image.png](https://camo.githubusercontent.com/119c9772949fb344d4f98136aab8e27a020d7294c2afc63855adc3acd1e3d79f/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f66623865613435652d393462362d346133392d386535342d373563663637313065383264) <img alt="image" width="828" src="https://user-images.githubusercontent.com/111529185/201486484-ee0b2a4d-189f-48b0-86a6-21ee0fa4ecf1.png"> Figma and test environment are different @RamRamez Is it okay that both items have the same title? @mosaeedi
> > > 
> > > 
> > > Yeah, @MoeNick added two new rows.
> > 
> > 
> > Yeah, but Is it okay that both items have the same title? @MoeNick
> 
> Let's change it to: 1- Your project update 2- Your liked project update
> 
> 1- Your project status 2- Your liked project status
> 
> @RamRamez @maryjaf

We moved all copies to backend. @mohammadranjbarz could you please update these copies?

**Comment by mohammadranjbarz** [comment]
@RamRamez  @MoeNick 

These copies had been changed

>Moenick: Let's change it to:
1- Your project update
2- Your liked project update
1- Your project status
2- Your liked project status

**Comment by mohammadranjbarz** [comment]
@maryjaf 
* Update Project(You Posted an update on your project & When your liked project has an update)
  * Owner:
    * Email:We don't have it yet
     * Notif: It's ok now
  * Who liked:
     * Email:We don't have it yet
     * Notif: It's ok now
* Project likes
   * Email: We don't have it yet
   
* List & Unlist
   * Email:ok, I received emails
<img width="1380" alt="Screen Shot 1401-09-03 at 14 45 28" src="https://user-images.githubusercontent.com/9850545/203776827-7292309e-3439-496e-950a-af8d297d6665.png">
<img width="1377" alt="Screen Shot 1401-09-03 at 14 46 00" src="https://user-images.githubusercontent.com/9850545/203776859-d3e4a649-426f-449d-bb32-4dec2b49fef3.png">



* Deactive (by project owner & admin)
     * Email:  The event (**Project deactivated**) goes to Segment but email doesn't send, and I checked it seems the autopilot is stopped for this event, @divine-comedian  can you help us ?
        
<img width="1344" alt="Screen Shot 1401-09-03 at 14 58 35" src="https://user-images.githubusercontent.com/9850545/203779257-be5fd27e-ea9b-435c-a540-8ee471ebbbdd.png">
<img width="602" alt="Screen Shot 1401-09-03 at 14 58 44" src="https://user-images.githubusercontent.com/9850545/203779261-751b7423-12f3-4921-b0e5-7a18af75c691.png">

* Activate(by project owner & admin)
     * Email:  The event (,**Project activated**) goes to Segment but email doesn't send, @divine-comedian  can you help us ?
     
<img width="1213" alt="Screen Shot 1401-09-03 at 15 08 52" src="https://user-images.githubusercontent.com/9850545/203781166-eed3a84c-db3a-4c2f-b27c-e3a3a641a4d4.png">

* Cancel Project
   * Email: ok, I received the email
   
<img width="1288" alt="Screen Shot 1401-09-03 at 15 03 08" src="https://user-images.githubusercontent.com/9850545/203780009-234cfbf2-8fd5-460e-93be-43989397af74.png">

* Edit my project
   * Email: Event(**Project edited**) goes to Segment, but email doesn't send, maybe @divine-comedian  can help us
   
<img width="1198" alt="Screen Shot 1401-09-03 at 15 07 20" src="https://user-images.githubusercontent.com/9850545/203780933-ba73722d-9c17-4229-8a44-4753fb88e761.png">

**Comment by divine-comedian** [comment]
Did you turn on the autopilot integration in segment?

**Comment by mohammadranjbarz** [comment]
> Did you turn on the autopilot integration in segment?

I don't know how should I do that

**Comment by divine-comedian** [comment]
> > Did you turn on the autopilot integration in segment?
> 
> I don't know how should I do that, can you teach me?

I can see it's already or else you wouldn't receive any emails at all in staging but it can be done from this page in segment - 

![image](https://user-images.githubusercontent.com/67759413/203841448-678c9f8f-b12f-4d40-b19d-c6a8e48e3022.png)

![image](https://user-images.githubusercontent.com/67759413/203841516-b2e8eea1-3ecd-49c1-b31b-b89eb131e157.png)

**Comment by divine-comedian** [comment]
@mohammadranjbarz @maryjaf 

Checking in on autopilot I can see three things:

The project deactivated journey was stopped for some reason - I just re-enabled it 
- There is no email for project activated - we'll need to draft one - can we specify the cases for calling this? how does this differ from project listed?
- There is also no email and thus no email journey for project edited - we'll need to draft one. 

looping in @WhyldWanderer and @ahmadabugosh - do either of you have space to draft emails or can you chime in on this subject?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz @maryjaf
> 
> Checking in on autopilot I can see three things:
> 
> * The project deactivated journey was stopped for some reason - I just re-enabled it
> * There is no email for project activated - we'll need to draft one - can we specify the cases for calling this? how does this differ from project listed?
> * There is also no email and thus no email journey for project edited - we'll need to draft one.
> 
> looping in @WhyldWanderer and @ahmadabugosh - do either of you have space to draft emails or can you chime in on this subject?

Thanks for reenabling  **project deactivated**
@MoeNick  Can you help on ?
>  There is no email for project activated - we'll need to draft one - can we specify the cases for calling this? how does this differ from project listed?

**Comment by maryjaf** [comment]
**Email is sent in the following scenarios on Giveconomy** 
-Donate project ( send  email to the project owner and the person who donated it)
-Project listed
-Project Published
-Project deactivate(email send when deactivated by admin user from list no on the project detail page)
-Project deactivated by project owner
-Email for verify email address in verification form process
-Project cancelled
-Project unlisted
-project

---
**Email not send (on production & stg)**
-Project  verification form verified
-Project reactivate(activate after deactivated by admin and project owner)
-Project liked
-Project edited
We need to submitted some issue for above scenarios that email has not been sent on production

**Comment by maryjaf** [comment]
> The result of sending notification and email test so far: @mohammadranjbarz @RamRamez -Publish Email:ok Notif:ok
> 
> -Update Project(You Posted an update on your project & When your liked project has an update) Email: not ok Notif: ok
> 
> **-Project likes** Email: not ok Notif: ok
> 
> -List & Unlist Email: ok Notif: ok
> 
> -Deactive (by customer & admin) Email: ok Notif: ok
> 
> **Activate(by customer & admin)** Email: not ok Notif: ok
> 
> -Cancel Project Email: ok Notif: ok
> 
> **-Edit my project: (it isn't shown in notification center setting @MoeNick )** Email: not ok Notif: ok
> 
> -Donate (When someone donates to your project & when you donate to a project) Email: ok Notif: ok
> 
> **-Verification form: (it isn't shown in notification center setting @MoeNick )** --Rejected : Email: ok Notif: ok --make eligible by user: Email: not ok Notif: ok --Verified: Email: not ok Notif: ok

I updated test result after final test @mohammadranjbarz @MoeNick

**Comment by maryjaf** [comment]
> > 
> 
> > > > > ![image.png](https://camo.githubusercontent.com/119c9772949fb344d4f98136aab8e27a020d7294c2afc63855adc3acd1e3d79f/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f66623865613435652d393462362d346133392d386535342d373563663637313065383264) <img alt="image" width="828" src="https://user-images.githubusercontent.com/111529185/201486484-ee0b2a4d-189f-48b0-86a6-21ee0fa4ecf1.png"> Figma and test environment are different @RamRamez Is it okay that both items have the same title? @mosaeedi
> > > > 
> > > > 
> > > > Yeah, @MoeNick added two new rows.
> > > 
> > > 
> > > Yeah, but Is it okay that both items have the same title? @MoeNick
> > 
> > 
> > Let's change it to: 1- Your project update 2- Your liked project update
> > 1- Your project status 2- Your liked project status
> > @RamRamez @maryjaf
> 
> We moved all copies to backend. @mohammadranjbarz could you please update these copies?

Reminder @mohammadranjbarz

**Comment by maryjaf** [comment]
> @RamRamez @MoeNick
> 
> These copies had been changed
> 
> > Moenick: Let's change it to:
> > 1- Your project update
> > 2- Your liked project update
> > 1- Your project status
> > 2- Your liked project status

Based on Monique's explanation, the title should have been changed and the description remained unchanged
But now the description has changed @mohammadranjbarz

**Comment by maryjaf** [comment]
> > In "Notification settings / Project activities" figma, verification status is not shown in Notification settings, the notification is not sent after verify or un-verify project from admin panel? @MoeNick
> 
> I tested, the notification is sent after verify or un-verify project, but this verification item is not mentioned in the project activities. @MoeNick <img alt="image" width="1167" src="https://user-images.githubusercontent.com/111529185/201485756-285a15c2-4a29-4494-83b7-a5c7ea9df160.png">

Reminder @MoeNick

**Comment by maryjaf** [comment]
> > @RamRamez @MoeNick
> > These copies had been changed
> > > Moenick: Let's change it to:
> > > 1- Your project update
> > > 2- Your liked project update
> > > 1- Your project status
> > > 2- Your liked project status
> 
> Based on Monique's explanation, the title should have been changed and the description remained unchanged But now the description has changed @mohammadranjbarz

Kindly Reminder @mohammadranjbarz

**Comment by maryjaf** [comment]
I want to lock and tap on "increase your reward" in Giveconomy 
select **1000** Giv and **1** round and the calculated Giv power in modal(pic 1) is **1,414.21**
 after the transaction has been completed, I notify by this message and I didn't understand how is the givpower calculated **"Staking 414.213562 of GIVPower was successful."**
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/d8db3dd1-2798-438a-9e7a-b827322bb1f4)
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/7741adfb-3af7-4d68-98f6-adf996bf3713)

In the same scenario when I selected **1000** Giv and **3** round the calculated Givpower in modal  is **2000** and i receive this message **"Staking 1000.0 of GIVPower was successful."**

plz check this @aminlatifi

**Comment by aminlatifi** [comment]
> I want to lock and tap on "increase your reward" in Giveconomy select **1000** Giv and **1** round and the calculated Giv power in modal(pic 1) is **1,414.21** after the transaction has been completed, I notify by this message and I didn't understand how is the givpower calculated **"Staking 414.213562 of GIVPower was successful."** ![image.png](https://camo.githubusercontent.com/4e18484f8a328cd3ab5f7fdcab6ba09778489465be17068952eaecc42e3bc74b/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f64386462336464312d323739382d343338612d396537612d623832373332326262316634) ![image.png](https://camo.githubusercontent.com/3b2210c7ad33a55239391ebf05f664ca9b9864f14310e35dcf18205091538a43/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f37373431616466622d336166372d346436382d393866362d616466393936626633373133)
> 
> In the same scenario when I selected **1000** Giv and **3** round the calculated Givpower in modal is **2000** and i receive this message **"Staking 1000.0 of GIVPower was successful."**
> 
> plz check this @aminlatifi

Oh yes! It happens because of GIVpower contract mechanism! Technically, when a user locks tokens, the rewarded power is staked to GIVpower unipool. Consequently, a stake event with reward value is emitted and causes a stake notification.
@laurenluz @MoeNick Are you okay with this?

**Comment by laurenluz** [comment]
I think it's confusing and doesn't add value to the user to tell them that they staked their GIVpower - this isn't understood or clear in the UI anywhere else.

Tbh, I talked to @WhyldWanderer & @GriffGreen, and have the opinion that perhaps we shouldn't notify the user at all when they stake/unstake or lock. They know they are doing it because they get confirmation right away. The notification is redundant... we should notify the user when things happen that they are not aware of.

I know we have been working on building this, but I honestly think we should cut these from scope.

**Comment by laurenluz** [comment]
If we make too many redundant notifications the notifications won't have value because people won't check them. @aminlatifi @MoeNick

**Comment by aminlatifi** [comment]
@laurenluz I agree, let's focus on actions happening in the background. Like givpower unlock and givback payments.

**Comment by laurenluz** [comment]
Yes!! @aminlatifi

**Comment by maryjaf** [comment]
So, notifying the user after the stake/unstake should also be removed? 
In this case, the page related to the notification setting of Giveconomy should also be changed @MoeNick 
Please let me know if the  frond and backend changes have been done and I will test again

**Comment by mohammadranjbarz** [comment]
@maryjaf  I changed the titles of Notification setting items based on what moenick had said

@aminlatifi  @maryjaf  I removed Stakes item from notification setting items

**Comment by maryjaf** [comment]
> @maryjaf I changed the titles of Notification setting items based on what moenick had said
> 
> @aminlatifi @maryjaf I removed Stakes item from notification setting items

Based on the discussions, I think that this item  also should be removed
<img width="1290" alt="image" src="https://user-images.githubusercontent.com/111529185/208427906-2eed0412-70e3-47c3-addc-f6cb4ec76f0e.png">
 because in the lock scenario that was mentioned above, the correct notification was not received.
 And I don't receive notifications for Harvest and Givback, have these not been implemented? @mohammadranjbarz @aminlatifi

**Comment by maryjaf** [comment]
> @maryjaf I changed the titles of Notification setting items based on what moenick had said
> 
Thanks @mohammadranjbarz I checked and it passed

**Comment by laurenluz** [comment]
I think it is good to tell people when their GIV gets unlocked (and their GIVpower balancr goes down).

Do we have this notification @mohammadranjbarz @maryjaf

**Comment by maryjaf** [comment]
> I think it is good to tell people when their GIV gets unlocked (and their GIVpower balancr goes down).
> 
> Do we have this notification @mohammadranjbarz @maryjaf

I didn't receive notification about that

**Comment by maryjaf** [comment]
based on this change( https://github.com/Giveth/giveth-dapps-v2/issues/1947#issuecomment-1362706734)
I checked  my notification and I received unlock notification in "all " tab but i didn't see these on Giveconomy tab in notification setting
<img width="1318" alt="image" src="https://user-images.githubusercontent.com/111529185/209444259-052aad47-a646-455d-977b-5d6b8261f5a6.png">
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/111529185/209444282-7254a535-e523-4e08-8df7-efb704e4b807.png">
@aminlatifi @mohammadranjbarz

**Comment by aminlatifi** [comment]
> based on this change( [#1947 (comment)](https://github.com/Giveth/giveth-dapps-v2/issues/1947#issuecomment-1362706734)) I checked my notification and I received unlock notification in "all " tab but i didn't see these on Giveconomy tab in notification setting <img alt="image" width="1318" src="https://user-images.githubusercontent.com/111529185/209444259-052aad47-a646-455d-977b-5d6b8261f5a6.png"> <img alt="image" width="1202" src="https://user-images.githubusercontent.com/111529185/209444282-7254a535-e523-4e08-8df7-efb704e4b807.png"> @aminlatifi @mohammadranjbarz

@maryjaf It must be fixed now

**Comment by maryjaf** [comment]
> > based on this change( [#1947 (comment)](https://github.com/Giveth/giveth-dapps-v2/issues/1947#issuecomment-1362706734)) I checked my notification and I received unlock notification in "all " tab but i didn't see these on Giveconomy tab in notification setting <img alt="image" width="1318" src="https://user-images.githubusercontent.com/111529185/209444259-052aad47-a646-455d-977b-5d6b8261f5a6.png"> <img alt="image" width="1202" src="https://user-images.githubusercontent.com/111529185/209444282-7254a535-e523-4e08-8df7-efb704e4b807.png"> @aminlatifi @mohammadranjbarz
> 
> @maryjaf It must be fixed now

Thanks @aminlatifi I Checked again now the unlock notification are shown in Giveconomy tab

**Comment by maryjaf** [comment]
I think these three items are open from the notification center @aminlatifi @mohammadranjbarz 
1- I don't receive a notification when I boost a project or someone boosts my project
<img width="1189" alt="image" src="https://user-images.githubusercontent.com/111529185/209673664-be53df16-7b9a-4500-960e-f8d136360fb0.png">

2- The same for give back and harvest
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/111529185/209673585-811be299-b6e5-4db2-94fe-895b53053d2d.png">

3- Based on the discussions, it was decided not to send a notification to Lock, and in this case, it is necessary to change the text below. @MoeNick 
<img width="833" alt="image" src="https://user-images.githubusercontent.com/111529185/209673767-9964d526-6678-434f-95d3-a6ba00345c3e.png">

And one question: Will we not send notifications for stake and unstake from now?

**Comment by mohammadranjbarz** [comment]
@MoeNick  @maryjaf  @laurenluz 

We dont trigger notification for this item
<img width="1226" alt="Screen Shot 1401-10-12 at 15 50 10" src="https://user-images.githubusercontent.com/9850545/210230444-97d21fb1-6513-49bf-a03d-d5f1aa85d175.png">

If we want it please make an issue for that to start implementing that, otherwise we can remove it from setting page

**Comment by MoeNick** [comment]
> @MoeNick @maryjaf @laurenluz
> 
> We dont trigger notification for this item <img alt="Screen Shot 1401-10-12 at 15 50 10" width="1226" src="https://user-images.githubusercontent.com/9850545/210230444-97d21fb1-6513-49bf-a03d-d5f1aa85d175.png">
> 
> If we want it please make an issue for that to start implementing that, otherwise we can remove it from setting page

No, we don't want to have it. 

We only have to add these:
1- Boost event for the project manager. (in projects section, not give economy section) 
2- Token unlocked for the user.
3- GIVbacks for the users.

**Comment by mohammadranjbarz** [comment]
> > @MoeNick @maryjaf @laurenluz
> > We dont trigger notification for this item <img alt="Screen Shot 1401-10-12 at 15 50 10" width="1226" src="https://user-images.githubusercontent.com/9850545/210230444-97d21fb1-6513-49bf-a03d-d5f1aa85d175.png">
> > If we want it please make an issue for that to start implementing that, otherwise we can remove it from setting page
> 
> No, we don't want to have it.
> 
> We only have to add these: 1- Boost event for the project manager. (in projects section, not give economy section) 2- Token unlocked for the user. 3- GIVbacks for the users.

Nice, please give me the titles and descriptions for these three items that you already mentioned

**Comment by maryjaf** [comment]
> I think these three items are open from the notification center @aminlatifi @mohammadranjbarz 1- I don't receive a notification when I boost a project or someone boosts my project <img alt="image" width="1189" src="https://user-images.githubusercontent.com/111529185/209673664-be53df16-7b9a-4500-960e-f8d136360fb0.png">
> 
> 2- The same for give back and harvest <img alt="image" width="1262" src="https://user-images.githubusercontent.com/111529185/209673585-811be299-b6e5-4db2-94fe-895b53053d2d.png">
> 
> 3- Based on the discussions, it was decided not to send a notification to Lock, and in this case, it is necessary to change the text below. @MoeNick <img alt="image" width="833" src="https://user-images.githubusercontent.com/111529185/209673767-9964d526-6678-434f-95d3-a6ba00345c3e.png">
> 
> And one question: Will we not send notifications for stake and unstake from now?

The last update of testing notification

I receive notification for **Givback** correctly
<img width="897" alt="image" src="https://user-images.githubusercontent.com/111529185/210381040-2c3dc2e7-e1b4-4304-b7ba-c6c372f1eda7.png">


when some one **boost my projec**t for first time I receive notification 

<img width="906" alt="image" src="https://user-images.githubusercontent.com/111529185/210381149-cd5d1044-ccd3-4a8f-a7c2-6fc7af47c833.png">
@MoeNick @aminlatifi @mohammadranjbarz

**Comment by maryjaf** [comment]
The display order of project activities items for some accounts is changed by changing the setting (send email and notification)
The exact scenario is not clear yet 
Plz check this @RamRamez @mohammadranjbarz 
account:0xD5db3F8B0a236176587460dC85F0fC5705D78477
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/7b3e3343-52ff-459b-b487-ac7fbad7ebd8)
account:0xA1179f64638adb613DDAAc32D918EB6BEB824104
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/e8cc3b8d-d761-4381-b96f-27384a8bf40d)

**Comment by maryjaf** [comment]
The display order of project activities items for some accounts is changed by changing the setting (send email and notification)
The exact scenario is not clear yet 
Plz check this @RamRamez @mohammadranjbarz 
account:0xD5db3F8B0a236176587460dC85F0fC5705D78477
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/7b3e3343-52ff-459b-b487-ac7fbad7ebd8)
account:0xA1179f64638adb613DDAAc32D918EB6BEB824104
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/e8cc3b8d-d761-4381-b96f-27384a8bf40d)

**Comment by mohammadranjbarz** [comment]
> The display order of project activities items for some accounts is changed by changing the setting (send email and notification) The exact scenario is not clear yet Plz check this @RamRamez @mohammadranjbarz account:0xD5db3F8B0a236176587460dC85F0fC5705D78477 ![image.png](https://camo.githubusercontent.com/f97b150e1a01be0cd7465be3642888c728b0199c5338fee7b4428287ece185c1/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f37623365333334332d353266662d343539622d623438372d616337666261643765626438) account:0xA1179f64638adb613DDAAc32D918EB6BEB824104 ![image.png](https://camo.githubusercontent.com/55842bb4833babf6229b5c5e4837cd9923651ad9d4a8e819819d5c229eff7ba0/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f65386363336238642d643736312d343338312d623936662d323733383461386266343064)

@maryjaf  Can you please test it again?

**Comment by maryjaf** [comment]
Thanks @mohammadranjbarz it has been fixed

**Comment by maryjaf** [comment]
We can move this issue to Done  after final changes of this page are deployed and tested
