### ISSUE TITLE
GIVpower bugs on Optimism!

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4779]
A user reported these issues and I can verify that something weird is going on.

- [ ]  the number under "stake" is not accurate representing the GIV in the user's wallet on Optimism
For example, I have 12k GIV on OP: 
![image](https://github.com/user-attachments/assets/30ce96ca-2f40-432b-a9df-78345008a872)

but the farm says I can stake 2M:
![image](https://github.com/user-attachments/assets/2f634708-427a-4bac-a64c-3b0aeaf0ae09)

- [ ] Total staked GIV in "locked details" is not added up correctly
![image](https://github.com/user-attachments/assets/90bbfefd-4fa3-4a87-9212-1071a86890a9)
![image](https://github.com/user-attachments/assets/0a53b409-2af8-42fb-baad-38bdc9d736bf)

- [ ] Some locked GIV is not being considered as locked
https://discord.com/channels/679428761438912522/1288271849591013386/1288406405539168286

- [ ] GIVpower amount is not accurately reflecting all the user's staked & locked GIV
https://discord.com/channels/679428761438912522/1288271849591013386/1288406405539168286

**Comment by mohammadranjbarz** [comment]
@aminlatifi  @RamRamez Was this problem related to the  subgraph bug as well?

**Comment by aminlatifi** [comment]
> @aminlatifi @RamRamez Was this problem related to the subgraph bug as well?

It could be. Values returned by subgraph were nonsense during that issue.

**Comment by laurenluz** [comment]
I update the user that it should have been fixed. for me it looks ok now. we can close this
