### ISSUE TITLE
Design Open Notification Menu: Read/ Undread

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#478]
## Design resource

Notification modal -> [Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=12186%3A223386)

---

![Screen Shot 2022-08-16 at 4.06.08 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/38bef015-1888-4dd1-b0f4-b4c731240cd9)
---

**Comment by mosaeedi** [comment]
@Tosinolawale we may need to update this modal too.

**Comment by maryjaf** [comment]
How many notifications should be displayed in this menu? @alireza-sharifpour 
I see the last three notifications now.
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/a3ea8659-02ec-4040-96b5-e2c3e5b35701)
all of them:
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/d014e28d-cc4b-47d5-9c6c-d9e3f2d8b068)

**Comment by alireza-sharifpour** [comment]
> How many notifications should be displayed in this menu? @alireza-sharifpour I see the last three notifications now but in figma 4 notification are shown ![image.png](https://camo.githubusercontent.com/ac1d26e7faf928ecdbe7ca69b5a1b27b0da127e95a39ef11aa0fedd65a7ed26f/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f61336561383635392d303265632d343034302d393662352d653263336535623335373031) all of them: ![image.png](https://camo.githubusercontent.com/e1910f3515772ccd33e509841d1dd102fe75f48d786aa18075f9362ef393d3a3/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f64303134653238642d636334622d343764352d396336632d643965336632643862303638)

I think @MoeNick or @mosaeedi can tell us.

**Comment by maryjaf** [comment]
> > How many notifications should be displayed in this menu? @alireza-sharifpour I see the last three notifications now but in figma 4 notification are shown ![image.png](https://camo.githubusercontent.com/ac1d26e7faf928ecdbe7ca69b5a1b27b0da127e95a39ef11aa0fedd65a7ed26f/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f61336561383635392d303265632d343034302d393662352d653263336535623335373031) all of them: ![image.png](https://camo.githubusercontent.com/e1910f3515772ccd33e509841d1dd102fe75f48d786aa18075f9362ef393d3a3/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f64303134653238642d636334622d343764352d396336632d643965336632643862303638)
> 
> I think @MoeNick or @mosaeedi can tell us.

reminder @mosaeedi @MoeNick

**Comment by alireza-sharifpour** [comment]
@mosaeedi mentioned in the weekly call that we need to show 4 items in the menu based on the design and also 6 items in the notifications page.
and also we should add infinite scroll functionality, like the one in projects page.
I've implemented all of them so you can test.
@maryjaf
