### ISSUE TITLE
vouched projects should still be able to fill out givbacks form

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4781]
when a project has status of verified/vouched as true it appears that the project can no longer apply for GIVbacks eligibility. 

however vouched/verified projects should still be able to apply for givbacks eligibility and the UI elements should show up on relevant pages such as the project owner view on the drop down menu and the button on the givbacks component. also should be available from the project card drop down menu from the my projects menu.

![Image](https://github.com/user-attachments/assets/85c4dd68-7c57-4746-9f73-6adf50f3fad5)

**Comment by mateodaza** [comment]
@divine-comedian double checking the logic here... so this button will appear if: 

- isGivbackEligible is false, no matter what verified is saying (like your example, we're checking the verified value which is already true)

**Comment by mateodaza** [comment]
@divine-comedian this is ready to test on staging

**Comment by divine-comedian** [comment]
looks to be working correctly! Thanks
