### ISSUE TITLE
We should allow the users to switch to mainnet on the GIVstream page network drop down!

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4783]
Right now it isn't showing up here. Is this network dropdown the same for all pages GIVbacks, GIVfarm, GIVstream?.. because it either should be different for each page (corresponding to live & supported chains)... or should include all the options of all, if it needs to be the same - gnosis, polygon zkevm, mainnet, optimism

![image](https://github.com/user-attachments/assets/d666d1c7-c39d-40a1-b052-99f3539c1399)

**Comment by mohammadranjbarz** [comment]
<img width="913" alt="Screenshot 1403-07-05 at 11 35 29 in the morning" src="https://github.com/user-attachments/assets/d9c1d560-596d-43fc-93cd-f388873405ab">

https://staging.giveth.io/givfarm

I added Mainnet (Sepolia for staging). yes the network selector is the same in givFarm and givStream page

@laurenluz  @maryjaf  I made a hotfix PR , so when you approve the changes I can deploy just these changes to production

**Comment by maryjaf** [comment]
Thanks @mohammadranjbarz it has been fixed on staging
![Image](https://github.com/user-attachments/assets/00f35909-6d34-43ce-989d-51c5b601e0a2)
