### ISSUE TITLE
Updating projects list on "My projects" page

### ISSUE THREAD

**Issue by mosaeedi** [Giveth/giveth-dapps-v2#479]
We need to update the Project table on "my project" page to include the new status type
Status: Active, Deactive, "Draft" <- (The new status)

## Design resources

[Projects table on Figma](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=4116%3A109871)

### Status
- Active  ![Labels.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/3f463073-3c03-4e99-af1e-9a4d2ec9bcaf)
---

- Draft ![Labels-3.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/4440c7c6-0d15-40da-858e-d488f80afbae)
---

- Cancelled ![Labels-2.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/b19555fd-6bf0-441a-9754-ca98771e6e5b)
---

- Deactive ![Labels-1.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/652c7b5b-3f14-4d1c-a05e-86731769087a)

**Comment by mosaeedi** [comment]
![Screen Shot 2022-04-12 at 3.07.54 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/4a7678ac-a345-4ecd-b441-ead7377b3125)

**Comment by RamRamez** [comment]
For UAT testing:

1. add status column to the project table
2. center all tables pagination in all tabs
3. remove banned and draft from listing column in projects table
4. remove unnecessary styles and codes and decompose big components into smaller ones
5. replace user website with user email address in my account head
6. remove copy user wallet address icon
7. disable edit and view buttons in projects table for cancelled projects
8. improve my account responsiveness, specifically tables
9. remove `networksObj` and replace with `networksParams`
