### ISSUE TITLE
Users are unable to complete their Profile

### ISSUE THREAD

**Issue by LatifatAbdullahi** [Giveth/giveth-dapps-v2#4796]
An error "Failed to to fetch" is being thrown when Users attempt to complete their profile before creating a new project.

![image](https://github.com/user-attachments/assets/4e640789-30a4-4c85-9a9d-a12f9f020bf7)

![image](https://github.com/user-attachments/assets/19b05c1f-ea21-45ba-96c1-b1c585793aac)

**Comment by divine-comedian** [comment]
@LatifatAbdullahi seems to be working now - can you confirm?

**Comment by LatifatAbdullahi** [comment]
After retesting the issue is still reproducible @CarlosQ96 

![image](https://github.com/user-attachments/assets/1b84b09b-427c-4019-ba8f-5b626c6f3f0d)

**Comment by divine-comedian** [comment]
after rolling back the issues on staging server this appears to be working for me now on both profile creation and profile edit.

@LatifatAbdullahi if you experience this issue again please re-open this issue
