### ISSUE TITLE
GIVbacks user flow

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#480]
As a user, I need to have a clear flow (gamification/engagement) for donations with GivBacks.

-  I have to know from 1st step, which projects I have givebacks on them to donate (the verified badge won't show it clearly for me) 

- I need to see how much GivBacks I may have in the donation page (like: you donate some, you have this amount back)
 
- I also need to know which round I will be expecting that money, I need to see the calculation and overview in my account, in my donations, and in my account overview.

**Comment by Tosinolawale** [comment]
https://www.figma.com/file/d3ciTS36toS9mra0RAPMe2/Giveth-Design-System-v0.1?node-id=2059%3A59953

@MoeNick  we can get started with implementing the new Project Cards

**Comment by Tosinolawale** [comment]
https://www.figma.com/file/d3ciTS36toS9mra0RAPMe2/Giveth-Design-System-v0.1?node-id=2059%3A59953

@MoeNick  We can start with implementing the new Project cards

**Comment by markoprljic** [comment]
@Tosinolawale @MoeNick New project cards look ok.
