### ISSUE TITLE
Problem in switch network modal  on staging 

### ISSUE THREAD

**Issue by maryjaf** [Giveth/giveth-dapps-v2#4801]
**Describe the bug**

when the switch network modal is shown in donation page, by tapping on supported network , the switch nework is done but the modal won't be closed and it is shown constantly .

https://github.com/user-attachments/assets/ab9180a8-0aac-4c5f-8bb2-c56fffebf99f

cc: @divine-comedian

**Comment by maryjaf** [comment]
It seems this problem is related to this change https://github.com/Giveth/giveth-dapps-v2/issues/4612#issuecomment-2340901810
@MohammadPCh

**Comment by maryjaf** [comment]
It seems last changes made some problem in previous passed scenario, by changing the user the project owner modal is still shown @HrithikSampson 
https://github.com/user-attachments/assets/037a7325-dfe6-457f-84ff-3426307a6b60

**Comment by maryjaf** [comment]
> **Describe the bug**
> 
> when the switch network modal is shown in donation page, by tapping on supported network , the switch nework is done but the modal won't be closed and it is shown constantly .
> 
>  Screen.Recording.2024-10-01.at.11.00.18.PM.mov 
> cc: @divine-comedian

This problem has been fixed, but is the below screen record is ok? by tapping on op sepolia , switch network is disappeared for a sec and it is shown again
but after switching network it isn't shown again 

https://github.com/user-attachments/assets/6b43c2e8-51bd-4@HrithikSampson -9763-1d0100af3be8

@HrithikSampson @MohammadPCh

**Comment by MohammadPCh** [comment]
@maryjaf Thanks for testing :)
We need to refactor this part, but it's not a blocker for release. So let's release it and then fix this UI problem.

**Comment by HrithikSampson** [comment]
Sure @MohammadPCh

**Comment by HrithikSampson** [comment]
Not Sure

> > It seems last changes made some problem in previous passed scenario, by changing the user the project owner modal is still shown @HrithikSampson
> > Screen.Recording.2024-10-02.at.2.11.28.PM.mov
> 
> can you fix it before release? @HrithikSampson

**Comment by maryjaf** [comment]
So should we deploy  this change with these 2 problems  in this release  or revert it ? @divine-comedian 
cc: @HrithikSampson @MohammadPCh

**Comment by HrithikSampson** [comment]
I have tried to resolve this

> It seems last changes made some problem in previous passed scenario, by changing the user the project owner modal is still shown @HrithikSampson
> 
>  Screen.Recording.2024-10-02.at.2.11.28.PM.mov

**Comment by maryjaf** [comment]
> It seems last changes made some problem in previous passed scenario, by changing the user the project owner modal is still shown @HrithikSampson
> 
>  Screen.Recording.2024-10-02.at.2.11.28.PM.mov

this problem hasn't been fixed and after changing account the page should be refreshed @divine-comedian

**Comment by maryjaf** [comment]
> > **Describe the bug**
> > when the switch network modal is shown in donation page, by tapping on supported network , the switch nework is done but the modal won't be closed and it is shown constantly .
> > Screen.Recording.2024-10-01.at.11.00.18.PM.mov
> > cc: @divine-comedian
> 
> This problem has been fixed, but is the below screen record is ok? by tapping on op sepolia , switch network is disappeared for a sec and it is shown again but after switching network it isn't shown again
> 
>  Screen.Recording.2024-10-02.at.2.13.37.PM.mov 
> @HrithikSampson @MohammadPCh

this problem has been fixed @kkatusic @divine-comedian
