### ISSUE TITLE
Ensure correct emails are sent for project status changes related to decentralized verification

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4805]
we should ensure correct emails are sent on the corresponding admin actions related to decentralized verification 

### project tab -> verify project 
![image](https://github.com/user-attachments/assets/5fac85cf-ad3a-46cc-be62-cbec45fb648e)

**this action should not trigger any email** ... for now.
currently it triggers the GIVbacks acceptance email which is incorrect

### project -> reject 
![image](https://github.com/user-attachments/assets/f9e36949-1d1d-472d-a2c0-78ad0ac4096a)
**this action should not trigger any email** ... for now.
currently it triggers the GIVbacks rejection email which is incorrect.

### project verification form tab -> approve projects 
currently it triggers the GIVbacks acceptance email which is CORRECT

### project verification form tab -> reject projects 
currently it triggers the GIVbacks rejection email which is CORRECT.

### revoke badge 
![image](https://github.com/user-attachments/assets/8f492a60-440f-40f7-a810-1ef06e58760f)

this should send the badge revoked email
currently NO email is triggered
@RamRamez we send the same call but verified-status = "revoked"

# AC

- [x] triggering verify from admin panel does not send any email
- [x] triggering reject from admin panel does not send any email 
- [x] trigger approve projects from admin panel sends GIVbacks acceptance email
- [x] triggering reject projects from admin panel sens GIVbacks rejection email
- [x] triggering revoke badge from admin panel sends GIVbacks badge revoked email

**Comment by CarlosQ96** [comment]
Currently the project verify/revoke and verification-form approved/reject, trigger the same action. I can disable it for the first two.
