### ISSUE TITLE
Design givback game in donation page

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#481]

**Comment by Tosinolawale** [comment]
GIVbacks in Donation Page

https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=8401%3A165834

@MoeNick

**Comment by Tosinolawale** [comment]
This Design includes the solution for three different scenarios ; 
1. If a Project is eligible for GIVbacks and the user uses a non eligible token
2. If a Project is eligibile for GIVbacks but the user selects a non eligible token and 
3. if a project is not eligible for GIVbacks at all.

**Comment by divine-comedian** [comment]
I'm a bit lost, where did this UX request come from?

A few things that might make this confusing or less useful for the user. 

the actual amount of GIVbacks they get will be different because we calculate the price of GIV at the time of distribution, done bi-weekly, not the price at time of donation.

If the amount of GIV to distribute based on the 75% value is over 1 million GIV then we match donations with an amount less than 75%, again this amount is calculated at time of distribution.

so when we estimate their amount of GIV they will receive or the USD value (not in favour of showing USD value) this amount will very likely be different. If the user doesn't read into the estimation or complains that the estimation is off then this creates more work for people doing user support. 

The assumption that most users will read and fully understand the estimation concept or that they will understand or care how all of this works to me, seems very unlikely.

**Comment by MoeNick** [comment]
You are right, but this is too complicated for the user, it's too hard to sell. We were thinking we just give a hint to the user to know what GIVback is, we just say an estimated amount. If we want to grow we have the pin of supporting and engaging more users, but as I know, we have GIVbacks and no one knows what it is exactly. So do you have an idea how we can make a kind of gamification on this page (interactivaly) so that users may have a clue how much he/she can donate in net to have something back? We want the user to have a strong sense of donation regen and more impact than the current donation amount.

**Comment by divine-comedian** [comment]
We should also consider the entire default GIVback amount might change once we introduce boosting and project ranking

**Comment by divine-comedian** [comment]
currently we have an API `givback-calculation` that is used to calculate how much givbacks we distribute for each donation and also to find out the givbacks factor. We could call this API, in addition to the giv-price API everyday or twice daily and use it to know what the current matching amount is, if it is 75% or lower. this would also give us a more accurate estimate of how much GIVbacks a user can expect using the latest giv price.

perhaps also a user could see their pending GIVbacks, with the most recent API info on their `My donations` page. When a round is passed we mark the GIVbacks as sent on the UI.

**Comment by laurenluz** [comment]
Just catching up here... @tropicalmangos had an interesting idea for improving the donor flow that included adding a "GIVbacks" calculator where... the user could input a donation amount and get an estimate "liquid" & "streaming" GIV amount that they might get back if they donate. We could make it clear that this is a simulator and actualy value may change... but I think it will help to educate the user better about what they will actually get.

I like @divine-comedian's idea about also providing information to the user about when their GIVbacks has been sent via My donations.

**Comment by MoeNick** [comment]
jfyi @mosaeedi and @Tosinolawale 
we have to review Katia's suggestion and comparing with provided design. 

@divine-comedian it's included in Notification Epic, pls take a look at list of notifications, we're working on the copies here: 
https://docs.google.com/spreadsheets/d/1VMsmF9oJEwf1JyNEAfWi2n2eYvG6ZtnkXKB_3Hv29x8/edit?usp=sharing

**Comment by MoeNick** [comment]
This is @tropicalmangos 's suggestion: 
https://github.com/Giveth/giveth-planning/issues/824#issue-1335929514

**Comment by divine-comedian** [comment]
> Just catching up here... @tropicalmangos had an interesting idea for improving the donor flow that included adding a "GIVbacks" calculator where... the user could input a donation amount and get an estimate "liquid" & "streaming" GIV amount that they might get back if they donate. We could make it clear that this is a simulator and actualy value may change... but I think it will help to educate the user better about what they will actually get.
> 
> I like @divine-comedian's idea about also providing information to the user about when their GIVbacks has been sent via My donations.

Are you suggesting the calculator would be a separate from the regular donation flow? 

 I'm getting ptsd from the last calculator feature... 🙃
 
 
![image](https://user-images.githubusercontent.com/67759413/184214791-22343350-e3b0-4c36-922f-a1721959cc2e.png)

**Comment by laurenluz** [comment]
haha omg nooo not the GIVdrop calculators 🤣 

Check out the video @tropicalmangos posted in https://github.com/Giveth/giveth-planning/issues/824#issuecomment-1211961096 it's a pretty cool idea.

Bascially the user, on the "donate" page" could have a caculator where they "test" how much GIV they might get back (streamign & liquid) if they donated x amount. It would need:
- An input field for the the donation amount & perhaps donation currency + its USD amount
- Stated assumptions including (1) the GIV price, (2) the max USD value amount of donations for which the user would get 75% GIVbacks factor
- Two outputs: Liquid GIV + streaming GIV/week
- Estimate distribution date = round end date + 3? weeks

Something like that. This would need some collaboration work between someone who understands GIVbacks  + perhaps Mo for design. Plus we need to get approval from @MoeNick that this would work well with the flow... I think @MoeNick & @tropicalmangos can discuss that.

**Comment by divine-comedian** [comment]
I'm not really a big fan of the added complexity of adding a "testing" calculator to the donation page. I think the UX is much simpler as @Tosinolawale  proposed. The user would input how much they want to donate in the same box as always and we show a preview underneath calculated from the current API price of the token, price of GIV, and GIVstream rates.

 It's basically the same thing but you just use one input box for donating and the GIVbacks simulator is automatic without having a separate "test calculator" feature.

The project card on the left is reserved for project information and the part on the right is for donating so it kind of messes up the page's structure. You'll also be wanting that extra space on the project card as we move into project ranking with GIVpower.
