### ISSUE TITLE
when a project is vouched, allow project owner to boost their own project

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4814]
Currently from the project owner view, when a project is vouched and also has an incomplete GIVbacks eligiblity form they are unable to boost their project from any view on Giveth! 

We should reconsider the CTA buttons we use or make the necessary design change to accomodate this scenarion

![Image](https://github.com/user-attachments/assets/58e95cfd-cf35-4fae-9533-f7f05832ce9e)

**Comment by Tosinolawale** [comment]
![Project Single - About](https://github.com/user-attachments/assets/5ec4fd7f-c063-471f-b587-21c3b8aa58d4)
https://www.figma.com/design/fHpNMd8Q9iBrAr6kBj9oo5/DeVouch-Giveth-Integration?node-id=8603-16467&t=ptXDi0plJ53GiteA-1
@divine-comedian @MohammadPCh @mateodaza

**Comment by divine-comedian** [comment]
@Tosinolawale to understand the `New` label shows up if the project has a incomplete form? Maybe we 

Can we just make this a small notification dot instead of using the text "New"? Or could we perhaps use a warning color or notification symbol to let them know that they should check out their application is incomplete?

**Comment by Tosinolawale** [comment]
> @Tosinolawale to understand the `New` label shows up if the project has a incomplete form? Maybe we
> 
> Can we just make this a small notification dot instead of using the text "New"? Or could we perhaps use a warning color or notification symbol to let them know that they should check out their application is incomplete?
![Project Single - About](https://github.com/user-attachments/assets/f0e19c6c-0846-472e-a32a-3961ce6c1156)
I introduced a warning/info label under the project actions
https://www.figma.com/design/fHpNMd8Q9iBrAr6kBj9oo5/DeVouch-Giveth-Integration?node-id=8603-16467&t=gtqWMULOww7z7Ga2-1 @divine-comedian

**Comment by divine-comedian** [comment]
Thanks Tosin! I think we can go ahead on this. Adding the warning text when user is VOUCHED and has incomplete givbacks form

I don't think its necessary to add the notification dot when the user opens the drop down menu.

@kkatusic - Can you take this one on?

**Comment by kkatusic** [comment]
@divine-comedian this is what you want?

![Screenshot 2024-11-08 at 11 43 15](https://github.com/user-attachments/assets/fb073966-83b7-4757-9379-8af3b57b34e3)

**Comment by divine-comedian** [comment]
sort of - bear in mind this should ONLY appear when form status is incomplete AND project is vouched AND when project is NOT givbacks eligible. 

I can see the project you have shown here already has givbacks status of eligible.

**Comment by kkatusic** [comment]
@divine-comedian I changed only inside administration value for eligible status for testing purpose, but form confirmation has been done for this project, that's why it is green.

**Comment by divine-comedian** [comment]
ready for QA @LatifatAbdullahi

**Comment by kkatusic** [comment]
@LatifatAbdullahi, ccc @divine-comedian , I skipped _project status rejection_ issue but fixed this condition that Mitch requested. Here we have lots of the conditions maybe in future we can refactor this code, every new condition we just add it here :)

**Comment by LatifatAbdullahi** [comment]
@divine-comedian All seems good now

- Show givbacks component header and text for condition of vouched, not givbacks eligible project (including boost button) - **Pass**

- Show text under project actions drop down menu to warn user they have incomplete givbacks form - **Pass**

- When givbacks form is not started we do not show warning text under project actions drop down menu - **Pass**

- When givbacks form is submitted we do not show warning text under project actions drop down menu - **Pass**

- When givbacks form is approved we do not show warning text under project actions drop down menu - **Pass**

- When the Givback form is incomplete, the text here should be "Resume Givbacks Form" not "Givbacks Eligibilty Form" - **Pass**

- When givbacks form is rejected we do not show warning text under project actions drop down menu - **Skipped**(would be covered later on with other conditions)




![sf](https://github.com/user-attachments/assets/4b0bad1e-0908-4c61-b82e-1d43f5e8c79d)

![image](https://github.com/user-attachments/assets/a82a49a5-5c03-4cfe-b005-b1f9c52a671c)

![image](https://github.com/user-attachments/assets/9b86f36e-b72f-416c-8cb5-6328728f822e)
