### ISSUE TITLE
Missing Category/Sub-category for newly added Endaoment Projects

### ISSUE THREAD

**Issue by LatifatAbdullahi** [Giveth/giveth-dapps-v2#4825]
@CarlosQ96 @mohammadranjbarz 

Ukraine America Initiative
https://app.endaoment.org/orgs/88-2280006
Project ID: 0ede481a-c59c-4201-8b0c-69e375cdd7ea
Category: Disaster Preparedness and Relief Services

Reef Guardians Hawaii
https://app.endaoment.org/orgs/47-3975420
Project ID: 2627e4ee-f713-4298-84d2-9fbad53d9ed9
category: Water Resource, Wetlands Conservation and Management

Mindfulness Through Play
https://app.endaoment.org/orgs/82-4211804
Project ID: 2d257c44-c39e-4f41-b4b4-24dd732f545d
Category: Student Services and Organizations

SOLUTIONS PROJECT INC
https://app.endaoment.org/orgs/46-3811348
Project ID: a60836a2-f06e-4b5b-9354-584a4ca5b4b0
Category: Energy Resources Conservation and Development

Peace Winds America
https://app.endaoment.org/orgs/26-3744952
Project ID: 25b2e4a9-20de-4564-be24-fc523a22d65c
Category: Disaster Preparedness and Relief Services

Love Justice International
https://app.endaoment.org/orgs/71-0982808
Project ID: c8101dbe-f308-425c-a0a5-39a98316c02f
Category: Victims' Services

Metagovernance Project Inc
https://app.endaoment.org/orgs/85-3442527
Project ID: d94cdffb-50cc-4127-806d-051b26f5ce00
Category: Computer Science

https://github.com/Giveth/impact-graph/blob/staging/migration/data/endaomentProjectCategoryMapping.ts

![image](https://github.com/user-attachments/assets/cd6eec30-0649-46ca-aa67-5c8f8c251464)

![image](https://github.com/user-attachments/assets/2076b853-db83-4172-ac32-56b42743e04f)

**Comment by kkatusic** [comment]
@LatifatAbdullahi , cc @CarlosQ96 and @mohammadranjbarz , all these categories that you mentioned in the issue have its related categories inside Giveth dApp, for example _Disaster Preparedness and Relief Services_ should have defined these categories: **_NGO => Endaoment_** and _**Nature => Disaster Relief**_ like it is defined inside google sheet document that you share with me. Thx

**Comment by LatifatAbdullahi** [comment]
The default category and subcategory (**NGO:Endaoment**) is present in the projects but other project specific categories and sub-categories are still missing 


@CarlosQ96 @mohammadranjbarz 

For example

Reef Guardians Hawaii
https://app.endaoment.org/orgs/47-3975420

**Category: Water Resource, Wetlands Conservation and Management**

![io](https://github.com/user-attachments/assets/7b840ec5-684c-4197-be4a-8a6bbc3a1bc0)

**Comment by CarlosQ96** [comment]
Thanks @LatifatAbdullahi Im jumping on this issue agian today, will let you know when its ready!

**Comment by kkatusic** [comment]
> Computer Science

When I check for example _**Category: Computer Science**_ it is equivalent _Endaoment_, _Tech_ and _Education_ like it has been defined inside sheet document that you @LatifatAbdullahi provide to me. We don't need to introduce new categories.

**Comment by LatifatAbdullahi** [comment]
@kkatusic I am referring to the FE...the categories should reflect on in the project details page.

**Comment by kkatusic** [comment]
> @kkatusic I am referring to the FE...the categories should reflect in the project details page.

can this be modified inside AminJS?

**Comment by CarlosQ96** [comment]
But I don't see all categories being exposed. I'll push a hotfix.

**Comment by CarlosQ96** [comment]
> @kkatusic @LatifatAbdullahi I added a way to add categories on production. If you edit a project you can add the categories, just be sure to add them all at the same time.
> 
> It displays the handle: <img alt="image" width="1074" src="https://private-user-images.githubusercontent.com/92376054/382766926-a449f3a3-184c-495b-9f9e-47ad4379c828.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5MjAwNDIsIm5iZiI6MTczMDkxOTc0MiwicGF0aCI6Ii85MjM3NjA1NC8zODI3NjY5MjYtYTQ0OWYzYTMtMTg0Yy00OTViLTlmOWUtNDdhZDQzNzljODI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDE5MDIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyNGEyZjMwNzBmYWI1NjJiNzM5NTFiMDlmYzFmMmM5NzgzZDlkOGVjZThlZDc2M2VlY2IxNmFkZWNiOTgxODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YwghWVPxx4OgeU9k7B53kDxJObrrxgsfzvcxUP0bxz4">

@LatifatAbdullahi I apologize upon further investigation, no more coding needs to be done. While it only displays 50 visually. There is a search funcitonality in the same bar of the dropdown from the picture, so you can search for the category and add it to the project.  Can you help me adding them? We can coordinate tomorrow. 

Just a disclaimer. You gotta add them all together at the same time. in the edit view of a project.

**Comment by CarlosQ96** [comment]
@divine-comedian @LatifatAbdullahi  granted you admin access!

**Comment by LatifatAbdullahi** [comment]
@divine-comedian 

From the Admin JS, some of the  Categories available are similar to the catgories of the latest Endaoment projects.
Below I listed out the closest categories in the Admin to the categories of the new Projects, kindly confirm if I should add them, and for some there are no close catgories to be added.

- **Ukraine America Initiative**

Category: Disaster Preparedness and Relief Services

Closest category in Admin: **Disaster Relief (Added)**

- **Reef Guardians Hawaii**

category: Water Resource, Wetlands Conservation and Management

Closest category in Admin: **Water and Sanitation**  and **Conservation and Biodiversity** (Not added yet)

- **Mindfulness Through Play**

Category: Student Services and Organizations

Closest category in Admin: **Education** and **Schooling** (Not added yet)

- **SOLUTIONS PROJECT INC**

Category: Energy Resources Conservation and Development

Closest category in Admin: **Energy**

- **Peace Winds America**

Category: Disaster Preparedness and Relief Services

Closest category in Admin: **Disaster Relief** **(Added)**

- **Love Justice International**

Category: Victims' Services

Closest category in Admin: Null (Maybe **Social Services**) **Not Added  yet**

- **Metagovernance Project Inc**

Category: Computer Science

Closest category in Admin: **Tech**  **(Added)**

**Comment by LatifatAbdullahi** [comment]
@CarlosQ96 

For the field for adding categories in the Admin, after adding and saving categories, it is not saved for Users to be aware of the added categories, even though its visible on the FE, It would be better to be shown, so Admin Users can see what category is added and probably be able to delete if required. Or what do you think?


https://github.com/user-attachments/assets/6c304d4e-21eb-41ef-b0c7-2bad21220f1b



In addition, some Sub-categories when added from the Admin is not in the right category

For example; "Disaster Relief" is Categorized under "Nature" not "NGO"

Then, I attempted to add "Education" to a project but it didnt reflect on the FE



![ru](https://github.com/user-attachments/assets/8b23254e-28d4-422a-bbee-0bcb8467c0dd)





The Categories are shown in this sheet

https://docs.google.com/spreadsheets/d/1DVhymxzLTPLCJ82X35IhZzwF7sse8a1l7CeHJuy9Z7Q/edit?gid=1668425089#gid=1668425089

**Comment by CarlosQ96** [comment]
@LatifatAbdullahi I see, instead of going to the edit view, go to the SHOW view and the categories are displayed there. I had to create that custom component because of some limitation. Let me know if this is enough, might require a lot of work to fix that admin framework is not that flexible.

On your second concern. There is a Category Tab you can go in the admin (as an admin) and add new categories, or modify existing ones. The categories should be marked as "Can use in the frontend" for it to be visible. If it still doesn't show I would contact Ramin or Cherik to double check.

**Comment by LatifatAbdullahi** [comment]
Thank you @CarlosQ96 

I have added the new subcategories to existing main categories and they have been added to all the new Endaoment projects.



**Ukraine America Initiative**

Category: Disaster Preparedness and Relief Services

![Ukraine](https://github.com/user-attachments/assets/197bb9ef-5362-4fa3-afc1-c5e4b21433b2)


**Reef Guardians Hawaii**

category: Water Resource, Wetlands Conservation and Management

![reef](https://github.com/user-attachments/assets/73f6eda0-a5a4-4858-8fb3-af3bde9c8cab)


**Mindfulness Through Play**

Category: Student Services and Organizations

![mind](https://github.com/user-attachments/assets/971c720e-13e6-4e99-b3fa-6857820de23d)


**SOLUTIONS PROJECT INC**

Category: Energy Resources Conservation and Development

![solu](https://github.com/user-attachments/assets/11ee9f39-5b37-44e3-90ff-c2cf66d6b31b)


**Peace Winds America**

Category: Disaster Preparedness and Relief Services

![Peace Winds America _ Giveth - Google Chrome 2024-](https://github.com/user-attachments/assets/120639db-2fd7-41df-ac6f-efff30f6554b)


**Love Justice International**

Category: Victims' Services

![love](https://github.com/user-attachments/assets/fe502977-edec-425c-a4c9-f75974eb8cb1)


**Metagovernance Project Inc**

Category: Computer Science

![Metagovernance Project Inc _ Giveth - Google Chrom](https://github.com/user-attachments/assets/3e546851-3a25-4eac-b1b1-09ad7d79d89a)

**Comment by divine-comedian** [comment]
whew! Thank goodness we got to the bottom of this one. Since this looks to already be on production I will close this issue as done.
