### ISSUE TITLE
Design GIVbacks data in my donation table | My Account

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#483]
## Design resource

My account / Donations table with GIVbacks
-->  [Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=8746%3A186690)

---

**Comment by markoprljic** [comment]
@Tosinolawale @mosaeedi Do we have any mockups for this?

**Comment by mosaeedi** [comment]
@MoeNick Design is done
