### ISSUE TITLE
Cart of projects

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#484]
**What problem is this design solving? Why is it necessary?**
*A clear and concise description of what the problem is. Link to any relevant issues, PRs, and other resources.*
Users usually want to donate over a topic or category instead of specific projects, they don;t have time to make sure what project is. Sometimes they want to select multiple projects and add them to their cart, so they can donate a specific amount to all of these projects. 

There are some draft design in Figma, they need to be clarified by the user flow. 

**Is there any user data or feedback backing up this feature request?**
*Share any user research conducted by yourself or others.*
There were some feedback. Not specific research. 

**Which metrics will define this feature's success?**
*Provide current and/or expected metrics.*
Nothing unfortunately 

**Additional context**
*Add any other context or screenshots related to your design here.*

**Comment by mosaeedi** [comment]
@MoeNick (just a reminder)
