### ISSUE TITLE
small bug, easy fix: the date is way off on a Donation from the Matching pool when distributing funds to projects

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#4840]
<img width="145" alt="Screenshot 2024-10-12 at 1 38 03 PM" src="https://github.com/user-attachments/assets/5f00d632-5d20-4901-a8ff-d8fe8e256805">
<img width="835" alt="Screenshot 2024-10-12 at 1 39 19 PM" src="https://github.com/user-attachments/assets/2b1b637d-86a7-44af-a678-bee737ec1538">

https://giveth.io/project/daostar?tab=donations

probably wrong on other project pages too

**Comment by kkatusic** [comment]
@GriffGreen thx for reporting this, I fixed and found bunch of others on same date, fixed also that donations.
