### ISSUE TITLE
P0 issue! Sorting vouched projects  via GIVpower doesn't work!

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#4844]
https://giveth.io/project/help-each-other-chiangmai

https://giveth.io/project/chiang-mai-ping-river-flood-relief

They both have more GIVpower than Pairwise.. and yet, they are not sorted:
<img width="1263" alt="Screenshot 2024-10-18 at 11 27 57 AM" src="https://github.com/user-attachments/assets/1adc5342-e585-4921-9999-4eb755fa00b9">

**Comment by mohammadranjbarz** [comment]
@GriffGreen 

It got fixed
<img width="1444" alt="Screenshot 1403-07-27 at 2 32 12 in the afternoon" src="https://github.com/user-attachments/assets/78208b62-54b6-452c-a087-372a1f335516">
