### ISSUE TITLE
Remove "stake together" from GIVfarm

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4851]
The Stake Togehter thing is deprecated, so we should now hide this whole card from the frontend of https://giveth.io/givfarm

![image](https://github.com/user-attachments/assets/3c65e803-771e-44a0-ab8f-c4129c90adaf)

**Comment by mohammadranjbarz** [comment]
@laurenluz It's merged now, can you test it?

**Comment by laurenluz** [comment]
thanks guys! @kkatusic @mohammadranjbarz looks good :)
