### ISSUE TITLE
cannot enter search term on mobile from giveth homepage

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4860]
while using mobile I could not submit a search term using the search feature on the giveth landing page / home page

It does however work successfully from the all projects page

https://github.com/user-attachments/assets/7cd2eb86-82a5-482a-8330-6bee5b583dda

## AC
- [x] entering search term on homepage on mobile, user clicks enter on mobile keyboard and search query is submitted. 
- [x] Returns results on all projects page

**Comment by LatifatAbdullahi** [comment]
https://github.com/user-attachments/assets/36d4bfc9-6665-43de-8de8-81695cba0632


@kkatusic 
Please kindly take a look, I am still unable to search for terms on the homepage mobile on staging/production

-  entering search term on homepage on mobile, user clicks enter on mobile keyboard and search query is submitted - Failed
-  Returns results on all projects page - Failed

**Comment by kkatusic** [comment]
@LatifatAbdullahi you can test it now, PR hasn't merged

**Comment by LatifatAbdullahi** [comment]
Thanks @kkatusic 

@divine-comedian here is the current behaviour


https://github.com/user-attachments/assets/b8318b62-f0ed-4644-8613-cebdcf017997




- Entering search term on homepage on mobile, user clicks enter on mobile keyboard and search query is submitted - **Pass**
- Returns results on all projects page - **Pass**
