### ISSUE TITLE
usdc recurring donation decimals are incorrect and transactions reverts 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4861]
when adding a recurring donation in usdc it does not seem to parse the decimals correctly. 

It does not estimate the amount of months left from the proposed amount to deposit and amount to stream monthly - when going to the confirmaiton modal it shows an amount MUCH lower than the expected, based on the amounts input 

in addition it appears the optional donation to giveth toggle is not working correctly - it always applies a donation to giveth even when you toggle it off!! 

https://github.com/user-attachments/assets/6729b5af-bf83-44be-898a-3850f13d6bc8

**Comment by kkatusic** [comment]
@divine-comedian done hotfix for this USDC token, problem was with it's decimal, but also found problem related with months number, it wasn't ok. Other problem that you mentioned like applying donation to Giveth if you unchecked it didn't saw and also in video that you sent doesn't showing.

**Comment by divine-comedian** [comment]
@kkatusic from our discussion yesterday it appears that there is still an error in the flow somewhere

![image](https://github.com/user-attachments/assets/09385e2c-5878-4ed9-bca1-a14c5ff91047)


## Things we've tested 
- make recurring donation with other ERC20 tokens (OP & GIV) - WORKS ✅ 
- wrap USDC on superfluid app, make recurring donation with already wrapped USDC - WORKS ✅ 
- make recurring donation with ETH - WORKS ✅ 
- double checked configs for correct token addresses - WORKS ✅ 
-deposit tokens through my recurring donation page - FAILS ❌ -  it seems to revoke the approve instead of approve the allowance to deposit the token

![image](https://github.com/user-attachments/assets/0166116a-57fa-48d9-be7f-b7b67e7331f4)

It seems this could be related to how we handle depositing tokens or how we batch the deposit function together with creating a stream... bearing in mind USDC is the only token that has 6 decimal precision while all other tokens have 18.. the super USDC token has 18 decimals

**Comment by divine-comedian** [comment]
Gave it a look, tested it out and make some fixes, tested again locally and it looks to be working good! please tag @mateodaza to review the PR and we should push this hotfix on monday.

**Comment by kkatusic** [comment]
> Gave it a look, tested it out and make some fixes, tested again locally and it looks to be working good! please tag @mateodaza to review the PR and we should push this hotfix on monday.

Let's go, thx @divine-comedian

**Comment by divine-comedian** [comment]
Merged and tested on prod! closing this one.
