### ISSUE TITLE
Add new rewards for GIVpower extension November 2024

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4869]
According to [this forum post](https://forum.giveth.io/t/givpower-summary-requesting-giv-for-incentives-update-q4-2024/719/37) we have 8.5M new GIV to use for GIVpower rewards extension!

These should be split 45/30/25 optimism/gnosis/poygon. But also, since I made a mistake on the last set of rewards, we need to do a manual "round 0" that should only last 1 week, before our new rewards set starts Nov 26, 2024.

The notify reward on Nov 26 will also need to be done manually

The balances to assign were in this issue https://github.com/Giveth/giveth-dapps-v2/issues/4870 and all my math was done in [this spreadsheet](https://docs.google.com/spreadsheets/d/1neUUsppi4HZ5b0BlOUR60Vt2Hn-_e-hvoJeO20cTqyk/edit?gid=456674340#gid=456674340)

## Gnosis

Round | Date | GIV amount | To be done
-- | -- | -- | --
Round 0 | November 19 | 200,000 | Manual
Round 1 | November 26 | 60,500 | Manual

This will be set up via script:
Round | Date | GIV amount | % of total
-- | -- | -- | --
Round 2 | December 10 | 163,800 | 6.85%
Round 3 | December 24 | 167,100 | 7.00%
Round 4 | January 7 | 170,400 | 7.13%
Round 5 | January 21 | 173,700 | 7.27%
Round 6 | February 4 | 177,300 | 7.42%
Round 7 | February 18 | 180,600 | 7.56%
Round 8 | March 4 | 183,900 | 7.70%
Round 9 | March 18 | 187,200 | 7.83%
Round 10 | April 1 | 190,500 | 7.97%
Round 11 | April 15 | 193,800 | 8.11%
Round 12 | April 29 | 197,100 | 8.25%
Round 13 | May 13 | 200,400 | 8.39%
Round 14 | May 27 | 203,700 | 8.52%
  | Total | 2,389,500 | 100.00%

Total allocation for this 6 month period (FYI): 2,550,000

## Optimism

Round | Date | GIV amount | To be done
-- | -- | -- | --
Round 0 | November 18 | 200,000 | Manual
Round 1 | November 26 | 140,750 | Manual

This will be set up via script:
Round | Date | GIV amount | % of total
-- | -- | -- | --
Round 2 | December 10 | 245,700 | 6.85%
Round 3 | December 24 | 250,650 | 7.00%
Round 4 | January 7 | 255,600 | 7.13%
Round 5 | January 21 | 260,550 | 7.27%
Round 6 | February 4 | 265,950 | 7.42%
Round 7 | February 18 | 270,900 | 7.56%
Round 8 | March 4 | 275,850 | 7.70%
Round 9 | March 18 | 280,800 | 7.83%
Round 10 | April 1 | 285,750 | 7.97%
Round 11 | April 15 | 290,700 | 8.11%
Round 12 | April 29 | 295,650 | 8.25%
Round 13 | May 13 | 300,600 | 8.39%
Round 14 | May 27 | 305,550 | 8.52%
  | Total | 3,584,250 | 100.00%

Total allocation for this 6 month period (FYI): 3,825,000

## Polygon zkEVM

Round | Date | GIV amount | To be done
-- | -- | -- | --
Round 0 | November 18 | 32,000 | Manual
Round 1 | November 26 | 117,750 | Manual

This will be setup via script:
Round | Date | GIV amount | % of total
-- | -- | -- | --
Round 2 | December 10 | 136,500 | 6.85%
Round 3 | December 24 | 139,250 | 7.00%
Round 4 | January 7 | 142,000 | 7.13%
Round 5 | January 21 | 144,750 | 7.27%
Round 6 | February 4 | 147,750 | 7.42%
Round 7 | February 18 | 150,500 | 7.56%
Round 8 | March 4 | 153,250 | 7.70%
Round 9 | March 18 | 156,000 | 7.83%
Round 10 | April 1 | 158,750 | 7.97%
Round 11 | April 15 | 161,500 | 8.11%
Round 12 | April 29 | 164,250 | 8.25%
Round 13 | May 13 | 167,000 | 8.39%
Round 14 | May 27 | 169,750 | 8.52%
  | Total | 1,991,250 | 100.00%

Total allocation from this 6 month period (FYI): 2,125,000

@aminlatifi I updated it!

**Comment by aminlatifi** [comment]
@laurenluz 
1. I noticed on Gnosis and Polygon you have planned to pay 100k in the one-week Round 0. Did you do it on purpose? I doubt since the remaining balance on those chains was around 390k
2. The percentages don't add up to 100, it's 99.99

**Comment by laurenluz** [comment]
@mohammadranjbarz so if you can set up the notify reward bot scripts starting for December 10, will be great!

**Comment by laurenluz** [comment]
@aminlatifi when you're back from vacation please have a look at Mohammad's script! We should have the notify reward calls start on Dec 10.

**Comment by laurenluz** [comment]
Hey @mohammadranjbarz @aminlatifi - is this done?

**Comment by mohammadranjbarz** [comment]
> Hey @mohammadranjbarz @aminlatifi - is this done?

@laurenluz 
Yes it is done
https://discord.com/channels/679428761438912522/759816279623467023/1316057556833009747

**Comment by laurenluz** [comment]
oh yeah great :D
