### ISSUE TITLE
Move GIV from GIVgarden multisig to corresponding token distros for Nov 2024 GIVpower rewards extension

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4871]
2,550,000 GIV to Gnosis Chain token distro
3,825,000 GIV to Optimism token distro
2,125,000 GIV to Polygon zkEVM token distro

Total from GIVgarden: 8.5 million GIV

@divine-comedian - you know what to do 😎

**Comment by divine-comedian** [comment]
multisig txs are here: 

https://app.onchainden.com/safes/eth:0xd10BAC02a02747cB293972f99981F4Faf78E1626/transactions/0x5dd18b5b41f2d9b7f9dcaff328add92172ec2569b068416b21d1497980a7842b

https://app.onchainden.com/safes/gno:0xd10BAC02a02747cB293972f99981F4Faf78E1626/transactions/0x6908723c6d043ee10c22148366fd266916834671334509520ffdc22a89ab567d

https://app.onchainden.com/safes/oeth:0xd10bac02a02747cb293972f99981f4faf78e1626/transactions/0x2d1761d24676c4d9da9609b1578581d8590aea20c5343d9193565df2a6a52e09

**Comment by divine-comedian** [comment]
@laurenluz 

FYI since the polygon bridge is now working I was able to deposit the reamining 2.125M GIV into the tokendistro on zkevm
https://zkevm.polygonscan.com/tx/0xce90dab0fe98602836eabeab040aa25303783244da7cbeb21bb3d8ad497fe330

**Comment by laurenluz** [comment]
YAY! thanks @divine-comedian
