### ISSUE TITLE
Giveth Slide Deck URL

### ISSUE THREAD

**Issue by cordurboi** [Giveth/giveth-dapps-v2#4887]
We need to take the following slide deck, upload it to the giveth hosting and create a custom URL that points to it.

[Giveth Co-Marketing Slides.pdf](https://github.com/user-attachments/files/17996288/Giveth.Co-Marketing.Slides.pdf)

Should just be something similar to this link: [https://giveth.io/quadraticforce](https://giveth.io/quadraticforce)

The URL for this should ideally be https://giveth.io/comarketing

Let me know if you have any questions, thanks!

**Comment by kkatusic** [comment]
> @jainkrati @divine-comedian - who can we give this to?

I will

**Comment by kkatusic** [comment]
@laurenluz link is: https://giveth.io/comarketing

**Comment by laurenluz** [comment]
perfect! thanks @kkatusic!!

**Comment by cordurboi** [comment]
Thanks @kkatusic 🙏
