### ISSUE TITLE
Add monitoring subgraphs availability 

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapps-v2#489]
One straightforward way is to compare the earliest block number with the last block that was indexed

https://thegraph.com/docs/en/developer/quick-start/#5-check-your-logs

**Comment by divine-comedian** [comment]
@aminlatifi @geleeroyale is this issue still relevant?

**Comment by divine-comedian** [comment]
pinging again, @aminlatifi @geleeroyale please respond.

**Comment by geleeroyale** [comment]
Thanks Mitch - I am not sure how to go about this. We can throw an alert when the subgraph is out of sync (from something likle givpower-bot)
