### ISSUE TITLE
Giveth Safe App is broken, ancestor violates Content Security Policy directive

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#4898]
**Describe the bug**

Cannot use Giveth Multisig App on Safe 

produces error related to `Refused to frame 'https://giveth.io/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'"`

Issue was reported by user and I was able to reproduce it.

**To Reproduce**
1. Go to a Safe you are a sign of on either Optimism, Mainnet, Arbitrum, Base, Polygon...
2. Go to Safe Apps
3. Open Give safe app
4. See broken page error `giveth.io refused to connect.`

**Expected behavior**
When you try to connect to the Giveth Safe App it should load properly the giveth homepage inside the Safe App frame. 

**Screenshots**
![Screenshot from 2024-12-11 11-30-21](https://github.com/user-attachments/assets/bbbc2bf3-451f-4943-85ef-36f010ffbbc1)

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04
 - Browser Brave

**Comment by geleeroyale** [comment]
Nice - our new headers work. We were hoping to catch any bugs in testing. @kkatusic was able to put together a quick PR to allow framing specifically for safe.

https://github.com/Giveth/giveth-dapps-v2/pull/4899

**Comment by divine-comedian** [comment]
Hero! Tested on production and it appears to work, closing this one out
