### ISSUE TITLE
APRs in the GIVfarm are 0 - issue w/ notify reward

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#4908]
@mohammadranjbarz @aminlatifi @geleeroyale 
can you help to troubleshoot the issue here? We should try to resolve ASAP

![image](https://github.com/user-attachments/assets/7b6df518-782a-4603-90ca-74e1b8dc2043)

**Comment by kkatusic** [comment]
@laurenluz I think this is fixed?
