### ISSUE TITLE
Verification Application User Flow 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#492]
https://docs.google.com/presentation/d/1P_vUtporlEqtu_hY5aIVrySskdM-__rSfGObUwIlhJI/edit#slide=id.p 

 https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=7489%3A189503

**Comment by MoeNick** [comment]
These are feedbacks from @NikolaCreatrix 
https://docs.google.com/document/d/1pMaqfzLRJpYALYRdZDUQnatk6fsCux6OhQ7Z7bTUVSo/edit?usp=sharing

**Comment by MoeNick** [comment]
This is the Miro Board from @melodysongq and Giveth-Connect WG:
https://miro.com/app/board/uXjVOHUtG4M=/?moveToWidget=3458764524045494808&cot=14

**Comment by MoeNick** [comment]
We can go ahead in this issue @WhyldWanderer

**Comment by WhyldWanderer** [comment]
Wow!! Im very excited for this...
What an upgrade!

I have left lots of comments in the figma that take into consideration nikolas comments as well as the connect wg's comments.

Let me know if you have any questions..
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=7489%3A189503

**Comment by MoeNick** [comment]
@mosaeedi I'm waiting for you to apply required changes to Figma. It's simple and don;t take too much time. 
Ramin already started implementing. Thanks

**Comment by NikolaCreatrix** [comment]
And 4 more issues here is a doc w/ prntscrns

https://docs.google.com/document/d/1761qUNT8Lgjgun2vRnr4voKBroMlJ_7HZz6RI-slygw/edit?usp=sharing
