### ISSUE TITLE
Canceled project view

### ISSUE THREAD

**Issue by mosaeedi** [Giveth/giveth-dapps-v2#497]
## Why do we need it?
When users open a canceled project using a direct link, they can see an empty screen with just an alert message that this project is canceled!
Right now it's a dead-end for users and we can make it a starting point for users to discover similar projects.

## solution
We will have a small Graphic on top to show users that this project is no longer available
and then, we can list similar projects at the bottom.

## Design resources
[**Figma design**](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=6814%3A138702)

[Download graphical asset](https://app.zenhub.com/files/448919340/82cf149c-274c-4e22-99a9-5214a4554694/download)

---

**Comment by MoeNick** [comment]
for Similar projects, are we gonna show only 3 of them?

**Comment by rodricastillo9013** [comment]
I don't know, I would standardize 3 or 6 projects, what do you think?

here you have the figma https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=6814%3A138702

**Comment by mosaeedi** [comment]
![Canceled Project.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/b719bdc3-735f-4e45-9c89-c7b384999d7e)

The similar project row can contain up to 12 projects.

**Comment by rodricastillo9013** [comment]
OK! so we show 12?

**Comment by mateodaza** [comment]
> ![Canceled Project.png](https://camo.githubusercontent.com/59feafbfbc0b8a12c51fe721f3270f3e11e5acccb52e9979717e92ffee725d9c/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3631646438356239613134313961306663383366313564312f62373139626463332d373335662d346534352d396338392d633762333834393939643765)
> 
> The similar project row can contain up to 12 projects.

Can we say just "Is no longer available"? 
Project owner will know it's cancelled on his list, not sure if it's important to the external user to know a project has been cancelled, I believe it's enough saying not available, what do you think? @MoeNick @mosaeedi @rodricastillo9013

**Comment by MoeNick** [comment]
> > ![Canceled Project.png](https://camo.githubusercontent.com/59feafbfbc0b8a12c51fe721f3270f3e11e5acccb52e9979717e92ffee725d9c/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3631646438356239613134313961306663383366313564312f62373139626463332d373335662d346534352d396338392d633762333834393939643765)
> > The similar project row can contain up to 12 projects.
> 
> Can we say just "Is no longer available"? Project owner will know it's cancelled on his list, not sure if it's important to the external user to know a project has been cancelled, I believe it's enough saying not available, what do you think? @MoeNick @mosaeedi @rodricastillo9013
> 
> Also, are the 12 projects randomized?

You are absolutely right, no longer available is fine. 
The similar projects should follow the query of @CarlosQ96  for similar projects, is it usable right now? 
If not, we suggest upon our credit score.
