### ISSUE TITLE
Even tho this address claimed it's givdrop already, it keeps coming up on the modal

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#508]
<img width="578" alt="Screen Shot 2022-04-12 at 11 16 28 PM" src="https://user-images.githubusercontent.com/14945613/163099057-966e3ea8-dd55-4d26-a51e-ec08a27de9de.png">

**Comment by aminlatifi** [comment]
@GriffGreen Sometimes backend index events with delay, how long was it from the claim? 
Can you share account and claim transaction with me?

**Comment by aminlatifi** [comment]
I tested now with our test env, and it's working well!
