### ISSUE TITLE
Even to smart members of our team... the givstream progress bar is confusing

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#513]
<img width="660" alt="Screen Shot 2022-03-31 at 6 56 37 AM" src="https://user-images.githubusercontent.com/14945613/161049569-5407db0d-60b2-4656-b106-496600b776a9.png">

Chadfi wrote this in a token swap forum post... this progress bar shout be rethought.

**Comment by divine-comedian** [comment]
testing on `staging.giveth.io` 

looks like the progress bar has been updated to show the total liquid GIV from rewards - I noticed that the amount is showing exactly 15.00% - are calculations actually being done to this precision? maybe its a coincidence but worth checking - if not then perhaps we round the number to the nearest whole unless there is some value to the user of showing such precision. 

![image](https://user-images.githubusercontent.com/67759413/163631908-a3a5af27-22e2-4bb3-8e99-83733ece5931.png)

please confirm @mateodaza @aminlatifi

**Comment by aminlatifi** [comment]
You are right @divine-comedian 
There was an issue should be fixed by #526

**Comment by aminlatifi** [comment]
@divine-comedian now you can test

**Comment by divine-comedian** [comment]
yes looks much more plausible now - 
![image](https://user-images.githubusercontent.com/67759413/163807013-283ea016-37b5-477a-aa46-5f8e18c99cef.png)

call this DONE!
