### ISSUE TITLE
My Account| overview: Shorten decimals of USD Amount to 2 numbers only.

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#529]
As a user, I need to see the only 2 decimals of these number. 

![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/f66e3260-e634-4c71-a20f-0b07dfde334d)

Apparently the real value should get rounded to 2 decimal numbers, so it mean for example : 
3.78644 ~= 3.79 $ 

7.0001 ~= 7.00 $

**Comment by ascode94** [comment]
@MoeNick Fixed it, could you please check it out again?
