### ISSUE TITLE
Links are not working in Partner's page

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#53]
in this page: https://giveth-dapps-v2.vercel.app/partnerships
links to partners websites are not working properly.

**Comment by NikolaCreatrix** [comment]
I just tested all the links on my chrome browser and this is the results:

1HIVE - working
Alibre - working
Aragon - NOT working
BrightID - working
clr.funds - working
DappNode - working
Datafund - working
District0x - working
DoinGud - working
Ethereum Colombia - working
Gitcoin - working
Governauts - working
Gravity DAO - working
Iden3 - working
Maker DAO - working
Meta Cartel - working
Meta Gama Delta - working
My Crypto - working
MyEtherWallet (MEW) - working
Panvala - working
Polygon Hermez - working
PrimeDAO - working
Rainbow Rolls - working 
SDG Impact Fund - working
ShapeShift DAO - working
SourceCred - working
Swarm - NOT working
Status.im - working
The Commons Stack - working
The DAOIst - working
The Giving Block - working
The Engineering Commons - working
Vocdoni - working
White Hat Group - working
xDAI - working
