### ISSUE TITLE
Set up GIV/DAI Univ2 Rewards Mainnet Contracts 

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#540]
Since the [snapshot](https://snapshot.org/#/giv.eth/proposal/0xf68897df1e7d25344091616dccc94b3ab74b518cd0b8d2f997a0c2ae0afebfeb) passed, we should set up this GIV/DAI Univ2 Pool on Mainnet.

As per the [forum discussion](https://forum.giveth.io/t/mainnet-liquidity-solution-ideas-now-that-univ3-is-being-turned-off/440/10) we should set this up as follows:

- Allocate GIV to mirror the rewards for the GIV/ETH pool on Balancer (approx. 750k GIV)
- Set up the rewards to distributing the exact same way as the Balancer pool from now on
- The rewards should end June 2022 along with all the other pools

@aminlatifi is there anything you need clarified on this before you can get started?

I will make a separate issue for the frontend updates

**Comment by aminlatifi** [comment]
Working on its backend

**Comment by aminlatifi** [comment]
@laurenluz Current unipool reward distribution round ends GMT: Saturday, April 30, 2022 19:00:33, is it ok to launch this farming at the same time?

**Comment by laurenluz** [comment]
yeah! @aminlatifi I think that would be perfect. gives us a little over a week to develop & test.

**Comment by divine-comedian** [comment]
I think this has been up and running without issue on production, moving to DONE!
