### ISSUE TITLE
GIVfarm Frontend updates for GIV/DAI Univ2 Rewards program

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#541]
We should add a new card to the GIVfarm for the new GIV/DAI Univ2 pool. There are more details in #540

- [x] The new Univ2 card should take the place of the Univ3 pool
- [x] The Univ3 card (with the popup message of "no longer available") should be move to a new row (for normal browsers)... below the first row of 3 cards & above RegenFarms

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/447ac844-3f6b-46d9-87e5-64af10c526f8)

- [x] The Univ2 card should be very similar to the SushiSwap card:
     - [x] Top should say "Uniswap V2" Instead of "Sushiswap" and should have the uniswap logo
     - [x] GIV / DAI
     - [x] 50% GIV, 50% DAI
     - [x] Everything else the same as the other cards
     - [x] Provide liquidity... @aminlatifi or @divine-comedian can you send the appropriate link here?

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/a62e9273-c4de-48fd-9155-c5809ea98a6c)

FYI, this should not be pushed to production until #540 is completed & tested

**Comment by laurenluz** [comment]
@MoeNick maybe you can help assign someone to this. @aminlatifi can also help suggest, or leave any comments here

**Comment by divine-comedian** [comment]
Here is the link for adding liquidity - 
https://app.uniswap.org/#/add/v2/0x6B175474E89094C44Da98b954EedeAC495271d0F/0x900dB999074d9277c5DA2A43F252D74366230DA0?chain=mainnet

**Comment by laurenluz** [comment]
Ahh yeah, thanks @divine-comedian i edited my original comment

**Comment by aminlatifi** [comment]
> Here is the link for adding liquidity - https://app.uniswap.org/#/add/v2/0x6B175474E89094C44Da98b954EedeAC495271d0F/0x900dB999074d9277c5DA2A43F252D74366230DA0?chain=mainnet

Thanks Mitch, I updated this doc
https://www.notion.so/giveth/Deployment-52935e6579034f1b940bbef161e82229

**Comment by aminlatifi** [comment]
As I will be on vacation next week, I prepared everything I could. I coordinated with @mohammadranjbarz to run the reward distributor on time.
Also, I made a couple of transactions on gnosis-safe (nonces 8 and 9) for 
1. Granting `Distributor` role to GIV/DAI unipool on Token Distro
2. Assigning 587,500 GIV to GIV/DAI unipool on Token Distro 
It would be better if @divine-comedian or @paxthemax verify them before executing.

**Comment by aminlatifi** [comment]
@mohammadranjbarz will make the reward distributor call on the exact time the farm will start

**Comment by aminlatifi** [comment]
- [ ] Run frontend develop branch with production config and see whether it works well @MohammadPCh or @mateodaza or any other frontend guygs
- [ ] Verify and execute multisig transactions (nonces 8 and 9) @paxthemax or @divine-comedian 
- [ ] Merge https://github.com/Giveth/giv-token-contracts/pull/58 and make sure notify reward cron job works as expected @mohammadranjbarz

**Comment by laurenluz** [comment]
@aminlatifi @mateodaza @MoeNick 

Can we push this live on April 27 or 28 so that we have a few days of the "countdown"? The timer should be working, right?

Would love to announce a few days ahead of time to get people to ape in early.

**Comment by laurenluz** [comment]
I did some testing and there was just one small frontend fix that I saw #613... everything else appears to be working well on staging.

**Comment by paxthemax** [comment]
Just to confirm @GriffGreen - everything seems to be in order.
