### ISSUE TITLE
Cannot sign in with metamask

### ISSUE THREAD

**Issue by missgene** [Giveth/giveth-dapps-v2#544]
Hi @MoeNick! I encountered the same problem again when accessing My Account, My Project and Donation pages. 

You can see it here: https://www.loom.com/share/5f9dd17ae01149b990b1cbd8317b6346 

I haven't tried disconnecting my metamask wallet and try to connect it again..

**Comment by MoeNick** [comment]
I think maybe the popup won't show up but it's pending on your Meta Mask if you open it.

**Comment by MoeNick** [comment]
So pls click on SIgn-In on the pop-up and if nothing happens go to your wallet and send me the movie again.

**Comment by missgene** [comment]
I tried clicking on the Metamask plugin on Chrome to see if there was a Sign In request (as it did not pop up), but there was none. However, for some reason, I tried to access the site again, my account is already connected. I just tried to refresh 2 times.

**Comment by MoeNick** [comment]
Are you still having this issue?
