### ISSUE TITLE
Nothing happens after clicking "Donate to a project" 

### ISSUE THREAD

**Issue by missgene** [Giveth/giveth-dapps-v2#545]
As mentioned in the video, this is still related to the Sign In process but this time the prompt is different as it brings me to the Donate to a Project page and when I clicked it, nothing happened. 

Please see video below.. 
https://www.loom.com/share/193e281d4f9e40c7beda8757b7d42885 

Earlier today, I also encountered this problem after clicking "Donate to a Project" 
![image](https://user-images.githubusercontent.com/93360299/163983897-9c6c7660-6d01-4172-b88a-1d085547c955.png)

This is the error:
![image](https://user-images.githubusercontent.com/93360299/163983979-b00547b1-a999-47d6-9e97-4943c435cb08.png)

**Comment by missgene** [comment]
@MoeNick

**Comment by MoeNick** [comment]
@missgene I think that was temporary issue, would you pls try again?

**Comment by missgene** [comment]
Yeah, this worked again :)
