### ISSUE TITLE
Error Pages

### ISSUE THREAD

**Issue by markoprljic** [Giveth/giveth-dapps-v2#552]
404, 401, 500, 502, 503 etc. https://www.presslabs.com/how-to/error-pages/

**Comment by mosaeedi** [comment]
@MoeNick is there still something missing on Design? Can we remove the UI tag?

**Comment by divine-comedian** [comment]
@alireza-sharifpour any tricks for testing out all these pages?

**Comment by alireza-sharifpour** [comment]
> @alireza-sharifpour any tricks for testing out all these pages?

The UI template of these pages is the same.
You can check 404 page => enter a wrong URL.
also you can check default maintenance page => [https://giveth.io/maintenance](url)

**Comment by divine-comedian** [comment]
> > @alireza-sharifpour any tricks for testing out all these pages?
> 
> The UI template of these pages is the same. You can check 404 page => enter a wrong URL. also you can check default maintenance page => [https://giveth.io/maintenance](url)
I can see in the figma the images and text are a bit different from each other.
Need to check still:

- [ ] Error 401
- [ ] Error 403
- [ ] 502
- [ ] 500
- [ ] 503
- [ ] 504


Any tricks for how to test these?
