### ISSUE TITLE
Can't sign in with Google, FB, Discord or Twitter on my Brave browser

### ISSUE THREAD

**Issue by Cotabe** [Giveth/giveth-dapps-v2#553]
I managed to sign in with my google account on Chrome.

Maybe a warning could be beneficial.

Tor.us get's stucked on this URL: https://app.tor.us/v1.21.0/end
![sign in bug](https://user-images.githubusercontent.com/101358184/159603559-d145c7d9-2aff-43ab-a8af-e11b7a7ca94a.PNG)
.

**Comment by RamRamez** [comment]
We have added a modal for Brave users to inform them to lower their shields before using Torus.

**Comment by divine-comedian** [comment]
modal looks mostly good but I would suggest a few updates to the modal 





Can we add this image below the first text block

![image](https://user-images.githubusercontent.com/67759413/165544581-6a7898c2-fc22-4850-81fd-e9b8704c7cbb.png)

We can remove this second part of the text 
![image](https://user-images.githubusercontent.com/67759413/165544716-fc7a978c-77bf-4a97-85fd-e4ea04147cbf.png)

and replace it with "Brave Shields will prevent Torus Wallet from opening the window for you to complete your sign-in

**Comment by divine-comedian** [comment]
changes look good! 

![image](https://user-images.githubusercontent.com/67759413/168646982-f4bbf55c-1451-41f4-9160-9d1af9d736c4.png)

moving to done!
