### ISSUE TITLE
Emojis don't work when sharing a donation page via Facebook

### ISSUE THREAD

**Issue by missgene** [Giveth/giveth-dapps-v2#555]
I clicked the Facebook share button on [this page](https://giveth-dapps-v2.vercel.app/donate/my-next-project-is) and found out that the emojis are not carried out in the caption. They are shown as symbols.

![image](https://user-images.githubusercontent.com/93360299/164127121-313c8214-7ee5-4451-ba24-1352bd6a58a4.png)

Check this photo for reference and comparison (works well with Twitter share button):
![image](https://user-images.githubusercontent.com/93360299/164127215-5bd2f84b-fc90-490b-9c80-5190ba02f22e.png)

@MoeNick

**Comment by ascode94** [comment]
I checked this issue, we followed the guidelines that Facebook mentioned, but it seems like Facebook doesn’t support emojis as quotes.
![Screen Shot 2022-05-02 at 9 32 33 PM](https://user-images.githubusercontent.com/48887817/166291923-30ad78c1-7ef4-4b72-ab49-45adb4cb6975.png)
As you can see, we send the emojis as URL parameters to Facebook (same as tweeter), but Facebook cannot interpret them.
So What are the alternatives?
Is it possible to show the link and hashtag and let users write whatever they want?
Or do you suggest something else?
@MoeNick @missgene

**Comment by ahmadabugosh** [comment]
@MoeNick yes I looked at the documentation, tested it out, asked a few dev friends that work with facebook, and no one has an answer. 😕

 Unfortunately, I think it's just something their API doesn't allow. so I recommend keeping the share status blank when they share on Facebook since even encoding emojis don't work with sharer

**Comment by divine-comedian** [comment]
testing on `staging.giveth.io`

sharing a link via facebook on the donation page 

the status is now empty but includes the giveth hashtag and a link to the project 

![image](https://user-images.githubusercontent.com/67759413/170076588-c0627293-320f-412a-8f25-ba733b53cb2c.png)

seems to be resolved! moving to DONE
