### ISSUE TITLE
Standardize z-indexes

### ISSUE THREAD

**Issue by MohammadPCh** [Giveth/giveth-dapps-v2#560]
We should fix this:
![Screenshot from 2022-04-20 11-09-46](https://user-images.githubusercontent.com/17097576/164166518-beb5b9c6-e776-4dbe-b6e1-ba9808f1649c.png)

**Comment by MohammadPCh** [comment]
I think It's better to have a standard for z-indexes. for example this is for bootstrap:
$zindex-dropdown:                   1000;
$zindex-sticky:                     1020;
$zindex-fixed:                      1030;
$zindex-modal-backdrop:             1040;
$zindex-offcanvas:                  1050;
$zindex-modal:                      1060;
$zindex-popover:                    1070;
$zindex-tooltip:                    1080;
@ascode94

**Comment by ascode94** [comment]
Thanks for sharing, i'll check it. @MohammadPCh
