### ISSUE TITLE
Sort by "Oldest" - not chronologically arranges

### ISSUE THREAD

**Issue by missgene** [Giveth/giveth-dapps-v2#572]
https://www.loom.com/share/8bbe48bf65394b288d441a31686045c4 

@MoeNick

**Comment by MoeNick** [comment]
Thanks, @missgene for reporting
Would you pls check it out @mohammadranjbarz or @CarlosQ96 who have bandwidth?

**Comment by CarlosQ96** [comment]
I'll have to validate with @mateodaza . But my theory is that it's sorting by creation date not last_updated in this case.

**Comment by mateodaza** [comment]
> I'll have to validate with @mateodaza . But my theory is that it's sorting by creation date not last_updated in this case.

Let's check that out

**Comment by mateodaza** [comment]
> are there any updates guys? @mateodaza @CarlosQ96

nope, this went over my head 😅 

I'll get back to this

**Comment by mateodaza** [comment]
@MoeNick @missgene This is an UX issue. The projects are being ordered chronologically in the right way. But some "old" projects have recent updates. They are two different things
