### ISSUE TITLE
Get informed when donating without completing your profile

### ISSUE THREAD

**Issue by Cotabe** [Giveth/giveth-dapps-v2#576]
I did my first donation before completing my profile on purpose.

I wasn't informed that I haven't completed my profile. Many donors would like to have their name and email given before making their first donation.

**Comment by MoeNick** [comment]
@Cotabe Actually, It was another requirement that we make it easier for donors to donate and don't obliged them to have a completed profile. 
Maybe we can revise it in the flow with @Tosinolawale

**Comment by Tosinolawale** [comment]
Checking this out. @MoeNick  @Cotabe

**Comment by Cotabe** [comment]
Hey @Tosinolawale, you made any changes on staging. I just tried again with a new wallet, but I didn't see any changes :thinking:

**Comment by MoeNick** [comment]
@Cotabe, @Tosinolawale is our user researcher and he's trying to review the UX and make it better, so there is no technical changes applied to the staging yet.

**Comment by Tosinolawale** [comment]
@Cotabe @Tosinolawale I will review the flow and see how we can improve it.

**Comment by Cotabe** [comment]
@Tosinolawale great!

Just let me know when you have any updates :)

**Comment by Tosinolawale** [comment]
@Cotabe @MoeNick  what are the Implications of not donating with a complete profile? And what are the incentives? 
Some users deliberately donate without a complete profile and like you said, it is good to notify all users who are donating without a complete profile, either intentionally or not. 
So, what are the implications and benefits of donating with a complete profile? This will inform my design decisions

**Comment by Cotabe** [comment]
@Tosinolawale 

I believe some people might want to have their name and email linked to the donation. Some people DO like that.

But I also think others would prefer to stay anonymous. 

I think a quick pop-up could be nice to have, but it's just my perspective. I definitely wouldn't want to create any friction.

**Comment by Cotabe** [comment]
Ok.

Thanks @Tosinolawale for taking a look at this issue.

Thanks @MoeNick for the comments.

I will close this issue.
