### ISSUE TITLE
Status: Waiting for review (deactivated project) 

### ISSUE THREAD

**Issue by missgene** [Giveth/giveth-dapps-v2#591]
I deactivated this project two days ago and reactivated it right after 30 minutes. Until now, I can see that it is still "Waiting for review".

![image](https://user-images.githubusercontent.com/93360299/164519298-c7cae2ab-4b7f-4eb9-a57d-51bc48dfc685.png)

How long does it take to review deactivated projects that are activated before they get listed again? 

@MoeNick

**Comment by MoeNick** [comment]
It's fine @missgene, it still needs to get reviewed again. 
@WhyldWanderer is it what should be expected or I'm missing something?
