### ISSUE TITLE
Amount of donation

### ISSUE THREAD

**Issue by missgene** [Giveth/giveth-dapps-v2#595]
The amount of donation shows these:

1. Home page
![image](https://user-images.githubusercontent.com/93360299/164912635-d256913c-5508-4b0b-9cde-d585c4db2789.png)

2. [Project page](https://giveth-dapps-v2.vercel.app/project/how-many-photos-is-too-many-photos)
![image](https://user-images.githubusercontent.com/93360299/164912663-6037fe8d-41b7-4893-9ac9-18c1d4725f23.png)

I think it should be rounded off? And at least two decimals? 

@MoeNick

**Comment by MoeNick** [comment]
@ascode94 can you jump into this please?

**Comment by ascode94** [comment]
Sure @MoeNick

**Comment by MoeNick** [comment]
@missgene it's a [Scientific Notation](https://en.wikipedia.org/wiki/Scientific_notation) to shorten the very long numbers. Usually, we round the numbers up and don't show decimals, so it's ok. closing this.
