### ISSUE TITLE
Donation amount - negative 

### ISSUE THREAD

**Issue by missgene** [Giveth/giveth-dapps-v2#596]
I wonder why this shows a negative donation amount? 

[This is the page.](https://giveth-dapps-v2.vercel.app/project/hugenduben-0) 
![image](https://user-images.githubusercontent.com/93360299/164912749-0c348538-eef3-4de4-8e71-992d8085d438.png)

I checked the donations tab and I saw these:
![image](https://user-images.githubusercontent.com/93360299/164912781-faeb8700-553c-4efd-8356-4dab7a7151d9.png)

@MoeNick

**Comment by MoeNick** [comment]
Good job @missgene we gonna resolve it in: https://github.com/Giveth/impact-graph/issues/496

**Comment by mohammadranjbarz** [comment]
@missgene Thanks for your report
@MoeNick 
 Now the negative donations have been deleted, and the total amount of donations for this project is correct
 https://giveth-dapps-v2.vercel.app/project/hugenduben-0
