### ISSUE TITLE
Tweet This on homepage

### ISSUE THREAD

**Issue by missgene** [Giveth/giveth-dapps-v2#597]
I clicked Tweet this and I was expecting that this line "Giving is effortless and people all around the world are rewarded for creating positive change." and a link will be tweeted..

![image](https://user-images.githubusercontent.com/93360299/164913410-4ce167a4-fa7d-4f34-bfd6-024f030047d1.png)

However, this is what I got
![image](https://user-images.githubusercontent.com/93360299/164913470-07808713-af5e-4a08-bad2-89ddf248cbb4.png)

Also, there's no image on the tweet or at least a thumbnail for the link.

@MoeNick

**Comment by MoeNick** [comment]
@laurenluz would you pls provide good Twitter post content for this? or if you are busy who can I ask for?

**Comment by laurenluz** [comment]
Great issue @missgene - thank you!

@MoeNick 

Here you go:
"Imagine a future where...
Giving is effortless and people all around the world are rewarded for creating positive change.

Explore @givethio to support this vision for the Future of Giving. 💜"

**Comment by divine-comedian** [comment]
testing on `staging.giveth.io`

I click the tweet this link on the homepage and it correctly shows the updated text 

![image](https://user-images.githubusercontent.com/67759413/168868850-9903e2f8-bc6f-449a-b5f9-fe7a469dfd70.png)

looks to be resolved! moving to done
