### ISSUE TITLE
Social media buttons on "Successfully created a Project page" 

### ISSUE THREAD

**Issue by missgene** [Giveth/giveth-dapps-v2#598]
I tried clicking the social media buttons after creating a project. I was expecting to see that the auto-caption would be about the fact that I submitted or created a new project on the platform. 

![image](https://user-images.githubusercontent.com/93360299/164915621-a63567b3-1b31-4db7-8003-ed1a503f69e9.png)

However, this is what I got: "I am a Giver and you can be one too! 💙 @givethio. Let's Build the Future of Giving together! 🙌 🌈 #maketheworldabetterplace 🌏 💜 https://giveth-dapps-v2.vercel.app/ #Giveth" 

@MoeNick

**Comment by MoeNick** [comment]
@laurenluz would you pls provide good Twitter post content for this? or if you are busy who can I ask for?

**Comment by laurenluz** [comment]
@MoeNick 

"Our project is raising funds in crypto on @givethio! 🙌 

Donate directly on Ethereum Mainnet or @gnosischain w/ no fees or intermediaries.👇

<link>"

**Comment by divine-comedian** [comment]
testing on `staging.giveth.io`

after successfully creating a project I'm clicking on the social links to share them across my networks.

the twitter posts seems to format fine but we should consider that on facebook and linkedin the same format doesn't work well.

facebook, looks like it doesn't update the actual status text but embeds something in it below, meaning the project creator can't change the text if they want to.
![image](https://user-images.githubusercontent.com/67759413/168863814-6ed5139b-9c08-42b9-8724-464f42a82284.png)

the default text should change to: 
 Our project is raising funds in crypto on @givethio!
Donate directly on Ethereum Mainnet or Gnosis Chain with no fees or intermediaries.

Here's the link to our project:
{project link}

for linkedin it doesn't seem to be formatting any message, only provides a link to the project and asks to send it as a post or private message, shouldn't it automatically make it into a post?

I'm not super familiar with how linkedin works but I would suggest using the same text as facebook for the message.
![image](https://user-images.githubusercontent.com/67759413/168863568-52f1826c-c8c1-4799-86f0-ce3f4b7c3ab3.png)

**Comment by alireza-sharifpour** [comment]
Thanks @divine-comedian for testing.
It seems like Linkedin only supports Links now (with no description).
And it exactly looks like the image you sent.
So I'll change the Facebook text as you said and I'll send a PR.

**Comment by laurenluz** [comment]
Twitter looks great, as mitch said.

Facebook updated with no emojis is great
![image](https://user-images.githubusercontent.com/75490971/171267497-e43db724-c849-42d2-813b-e35c58ed1318.png)

All good on linkedIn... if we can only share the link, so be it.
