### ISSUE TITLE
Code doesn't work

### ISSUE THREAD

**Issue by missgene** [Giveth/giveth-dapps-v2#610]
Html code didn't work on [this page](https://giveth-dapps-v2.vercel.app/project/ram-second-torus)

This is also how it looks on the Project main page: 
![image](https://user-images.githubusercontent.com/93360299/165128100-4e1b6bc1-6b14-4d3d-9062-5018b081c241.png)

@MoeNick

**Comment by MoeNick** [comment]
It's ok and it's for testing.
