### ISSUE TITLE
Donors' names on Donation tab of a project

### ISSUE THREAD

**Issue by missgene** [Giveth/giveth-dapps-v2#612]
Shouldn't the names of the donor be clickable if they have an existing account/project in the site? I'm not sure if this is important but I'm just mentioning it. 

![image](https://user-images.githubusercontent.com/93360299/165138083-443dcb47-6144-4b90-8528-b383a393034b.png)

This is the page where I got the screenshot above:
https://giveth-dapps-v2.vercel.app/project/ram-second-torus 

@MoeNick

**Comment by MoeNick** [comment]
Nice one @missgene 
What do you think @mosaeedi?
