### ISSUE TITLE
GIVstream history table entry for GIV/DAI univ2 pool is not showing up right

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#613]
Should have the GIVfarm label, like the others.

Who's best for this @MoeNick ? @MohammadPCh perhaps?

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/0b352569-c7a2-49f7-acc2-bf84f7dad31e)

**Comment by MohammadPCh** [comment]
Thank you @laurenluz 
I will fix it soon.
