### ISSUE TITLE
Add checkbox to GIVfarm for archived pools

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#614]
Where it's circled here, we should add a checkbox & text that says "See archived pools"
This checkbox should enable to see archived pools on the connected chain:
- When it is checked, you should see inactive pools on that chain (such as the univ3 pool on mainnet)
- When it is unchecked, inactive pools should be hidden (right now, the only hidden one should the univ3 pool on mainnet)

You need to also code it so the pool gets hidden normally.
Default state should be unchecked.

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/2b07fe9c-65c5-46ae-82f5-65aa2d01447c)

@mateodaza I think you'd be good for this one because it required a little bit of design eye. it's so small, I don't think we need to trouble Mo.

@MoeNick FYI

**Comment by divine-comedian** [comment]
testing on `giveth.io`
brave browser

when I first arrive on the givfarm page the button is left unchecked, hiding inactive pools (univ3)

clicking the circular check box it displays the deactivated givfarm

![image](https://user-images.githubusercontent.com/67759413/168646498-2b4dd529-1550-4327-bdfa-ffc3109059a1.png)

this looks to be DONE!
