### ISSUE TITLE
RegenFarm FOX/HNY everything is 0!! BUG ALERT

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#626]
people with LPs are seeing 0 LPs... the APR is 0... the rewards are 0... what is going on??

@mateodaza @MoeNick - help this is important. may users complaining in support channel.

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/028f5a1f-5391-4784-b70c-e4185bab9e92)

**Comment by giantkin** [comment]
not sure same bug, Giv/hny shows ok, but LP that i have (and others) doesnt show as stakable.

**Comment by MohammadPCh** [comment]
@laurenluz 
We didn't change anything, I think the main problem is the Graph service on the gnosis chain. @aminlatifi and @mohammadranjbarz can approve it.

**Comment by mohammadranjbarz** [comment]
> @laurenluz We didn't change anything, I think the main problem is the Graph service on the gnosis chain. @aminlatifi and @mohammadranjbarz can approve it.

@MohammadPCh 
Yeah it was a problem in subgraph config, Amin deployed a new version of subgraph and now it's ok

<img width="1322" alt="Screen Shot 1401-02-08 at 09 13 55" src="https://user-images.githubusercontent.com/9850545/165678208-7e9f413a-a35a-4dc3-9196-bed9638477f2.png">

**Comment by giantkin** [comment]
> not sure same bug, Giv/hny shows ok, but LP that i have (and others) doesnt show as stakable.

This is now working today as well.

**Comment by giantkin** [comment]
oops. totally didnt mean to close the issue. (still learning)  if needs reopened, sorry!
