### ISSUE TITLE
GIV/HNY LP balance showing as zero, can't stake

### ISSUE THREAD

**Issue by deeayeen** [Giveth/giveth-dapps-v2#627]
I have LP tokens, but the interface is showing that I have zero GIV/HNY LP tokens

![image](https://user-images.githubusercontent.com/35680780/165635861-b6505959-5eda-4136-a1e1-c9fbfaf85dfe.png)

I can't stake due to this issue

**Comment by giantkin** [comment]
![screenshot 84](https://user-images.githubusercontent.com/8282544/165655370-6fa86194-cf58-4c4e-a051-74dfe9e412ba.jpg)
This shows Both the hny/giv in the LP  and the stake not showing available at same time.

**Comment by mohammadranjbarz** [comment]
@giantkin Thanks for reporting this

@MoeNick 

Now we fixed the problem, and the UI shows my liquidity 

<img width="1792" alt="Screen Shot 1401-02-08 at 14 31 06" src="https://user-images.githubusercontent.com/9850545/165728932-29a35943-72ca-44fa-bdc8-f84fa5adc95f.png">
