### ISSUE TITLE
Change Save Donation Service (Send nonce  and other required fields)

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#630]

**Comment by divine-comedian** [comment]
how can this issue be tested?

**Comment by mohammadranjbarz** [comment]
> how can this issue be tested?

@RamRamez  Did we merge the frontend PR for donation flow?
It can not be tested alone, you should donate on the frontend and see if donations has been created successfully, you got email as donor, as project owner, ...

**Comment by RamRamez** [comment]
> > how can this issue be tested?
> 
> @RamRamez Did we merge the frontend PR for donation flow? It can not be tested alone, you should donate on the frontend and see if donations has been created successfully, you got email as donor, as project owner, ...

Yeah, this issue is same as #693 and @divine-comedian did some testing

**Comment by divine-comedian** [comment]
@RamRamez can we close this issue if it is a duplicate?

**Comment by MoeNick** [comment]
> @RamRamez can we close this issue if it is a duplicate?

It was for the backed side, we can relate, and move them together if the QA approves it.
