### ISSUE TITLE
Show success page only after trx confirmed by web3

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#633]

**Comment by divine-comedian** [comment]
is this related to 
https://github.com/Giveth/giveth-dapps-v2/issues/693
and 
https://github.com/Giveth/giveth-dapps-v2/issues/630
AND 

?

**Comment by RamRamez** [comment]
Actually three different tasks that is resolved in one PR

**Comment by divine-comedian** [comment]
testing on `staging.giveth.io` 

I created two donations with low gas on gnosis chain and ropsten 

the donation modal remains and the button says `donating` the success page only shows once metamask notifys me the tx is successful. 

![image](https://user-images.githubusercontent.com/67759413/169913108-638069ac-2cbe-457a-b59f-da1931ea8564.png)


one question @RamRamez did we remove the modal for pending transactions? I know we used to have a spinning circle or something

**Comment by RamRamez** [comment]
@divine-comedian Yeah you're right, there are some changes on the design and we should update the codes. [Link to issue](https://github.com/Giveth/giveth-dapps-v2/issues/791)

**Comment by divine-comedian** [comment]
> @divine-comedian Yeah you're right, there are some changes on the design and we should update the codes. [Link to issue](https://github.com/Giveth/giveth-dapps-v2/issues/791)

okay we'll call this issue DONE and follow up in the other issue you created.
