### ISSUE TITLE
Donation Not Appearing in Profile

### ISSUE THREAD

**Issue by bh2smith** [Giveth/giveth-dapps-v2#638]
https://blockscout.com/xdai/mainnet/tx/0x8faf7219683837aa34f242c276c2aa0a19fca0348f54e59c358896c758cdd248

This Donation Appears in the [Project Page](https://giveth.io/project/Feed-the-Hungry-in-Chilliwack-BC-Canada-0)
<img width="852" alt="Screen Shot 2022-04-28 at 10 07 45 PM" src="https://user-images.githubusercontent.com/11778116/165836884-7c3d630e-a0fb-49de-ab14-e12e0674ca13.png">

but not in the sender's profile. Is there some sort of time lag for this?

**Comment by MoeNick** [comment]
Related to #648
@mohammadranjbarz @CarlosQ96 somebody take it pls.

**Comment by CarlosQ96** [comment]
@mohammadranjbarz @MoeNick  after debugging it seems the userId is null in our db, many anonymous donations don't have it, but some do. (after checking the donations of this project).
So the frontend is not correctly sending the userId in every case and the sender profile searches by userId, leading to no donation showing up.

However, we can fix this by getting the userId searching with the user address which we always receive, and running a script to fix the other donations without userId.
Should I proceed with this solution?

But someone from the frontend should check the donation flow too.

**Comment by CarlosQ96** [comment]
This IMO however should include the fix we have pending, about public profile showing anonymous donations, add the logged in helper.

**Comment by mohammadranjbarz** [comment]
> This IMO however should include the fix we have pending, about public profile showing anonymous donations, add the logged in helper.

Thanks @CarlosQ96 
I wanted to merge this https://github.com/Giveth/impact-graph/pull/498
What changes do you mean we should do on that to support this problem?
( Maybe we should change `donationsByUserId` query, to instead of finding donations with that userId, we find the walletAddress of user and query based on that, and this may cause some side effects, for instance someone create lots of donations with my walletAddress as fromWalletAddress nad it would make My-donations page messy for my account
what do you think?

**Comment by CarlosQ96** [comment]
The PR https://github.com/Giveth/impact-graph/pull/498 should fix the issue about showing anonymous in public profile. So 1 less problem. So let's merge it.

In the saveDonation, we have findUserById(), we should add as second option findByFromWallet() in case the userId is not present (this shouldn't happen, let's check with frontend guys first if there is a bug).
So we will always fill the userId.

We could add the search by walletAddress but if the root issue isn't the backend, let's wait on that. I don't think there will be many side effects, but frontends will have to change the logic.

**Comment by mohammadranjbarz** [comment]
> The PR [Giveth/impact-graph#498](https://github.com/Giveth/impact-graph/pull/498) should fix the issue about showing anonymous in public profile. So 1 less problem. So let's merge it.
> 
> In the saveDonation, we have findUserById(), we should add as second option findByFromWallet() in case the userId is not present (this shouldn't happen, let's check with frontend guys first if there is a bug). So we will always fill the userId.
> 
> We could add the search by walletAddress but if the root issue isn't the backend, let's wait on that. I don't think there will be many side effects, but frontends will have to change the logic.

Thanks, Carlos, I really agree with you, We ( backend +frontend) should decide what to do to together, it's not just backend problem

**Comment by divine-comedian** [comment]
I was able to make a few anonymous donations to a project, once on ropsten and another on gnosis chain, both appeared on the project page and again in my donations

![image](https://user-images.githubusercontent.com/67759413/168854182-b20fff8e-7100-44cc-9706-962525b2439f.png)


![image](https://user-images.githubusercontent.com/67759413/168854361-cc1f45af-2e32-4960-b7e5-52b0bc5ee7a6.png)


is there anything further that can be tested to resolve this issue @CarlosQ96 ?

**Comment by CarlosQ96** [comment]
I think not, we fixed the ids in the donations so they should all be good now, both old and on creation. 
We can move to done. The tests you did is all.
