### ISSUE TITLE
I am authenticated but giveth.io asks me for authentication

### ISSUE THREAD

**Issue by vporton** [Giveth/giveth-dapps-v2#639]
I `porton.victor@gmail.com` am authenticated with Google at giveth.io.

But when I try to create or edit a project, I see `Authentication required.`

**Comment by MoeNick** [comment]
Are you experiencing it on Brave? on mobile or on desktop? and are you using Torus? 
@RamRamez it may be related to #553

**Comment by MoeNick** [comment]
@RamRamez

**Comment by MoeNick** [comment]
@RamRamez

**Comment by MoeNick** [comment]
@RamRamez

**Comment by MoeNick** [comment]
@RamRamez

**Comment by MoeNick** [comment]
@RamRamez

**Comment by MoeNick** [comment]
@RamRamez

**Comment by RamRamez** [comment]
@vporton I need more clue to debug. Can you take a screen shot from your console log?

**Comment by vporton** [comment]
It works now, the bug disappeared.
