### ISSUE TITLE
refactoring donate components and tnx flow

### ISSUE THREAD

**Issue by RamRamez** [Giveth/giveth-dapps-v2#641]
1. require sign for anonymous users also
2. remove unused saveDonationTransaction query
3. show error to user if donation is not saved
4. remove setInProgress and setUnconfirmed and wait till tx is mined then show success/error to user
5. complete refactor send transaction related functions
6. capture if tx is cancelled, failed, mined or speed up
7. remove requesting to network every one second for tx state and add listen instead
8. remove unused codes

**Comment by RamRamez** [comment]
For testing:

Three tx states should be tested: normal success, speed up and success, cancel tx
Also two different scenarios should be tested: regular Eth transfer and ERC20 token transfer

**Comment by MoeNick** [comment]
Nice job @RamRamez Thanks
