### ISSUE TITLE
Gnosis chain seems to be not accruing.

### ISSUE THREAD

**Issue by giantkin** [Giveth/giveth-dapps-v2#642]
Gnosis chain seems to be not accruing.
![screenshot 96](https://user-images.githubusercontent.com/8282544/166111802-abbc9e31-3793-4d59-a4c1-cde4fe880c8e.jpg)

ill check in a few minutes to confirm.

**Comment by giantkin** [comment]
Mainnet Giv/eth is accruing rewards.  (i cant test giv alone i dont have a deposit there yet)

**Comment by MoeNick** [comment]
I could not reproduce it find the route cause, would you pls make sure you are on the right address, right URL? or would you pls record your screen?

**Comment by MoeNick** [comment]
@giantkin can you confirm it's ok now?

**Comment by divine-comedian** [comment]
checking farms on `https://giveth.io/givfarm` 

the farm seems to be accruing rewards, I can see the amount go up periodically

perhaps it was a temporary RPC or sub-graph issue

moving this to DONE

**Comment by giantkin** [comment]
Finished weeks ago
