### ISSUE TITLE
I don’t see my last donation on my giveth.io/account

### ISSUE THREAD

**Issue by rpdb-ops** [Giveth/giveth-dapps-v2#648]
I don’t see my last donation on my [giveth.io/account]. I’ve already interacted with the same contract so I’ve checked the transaction hash and everything is correct. The donation appears in the project donation page so I don’t worry. I've already posted on forum.giveth.io/c/support/

**Comment by MoeNick** [comment]
Would u pls provide trx link?

**Comment by divine-comedian** [comment]
related to #638 and was resolved, moving to DONE
