### ISSUE TITLE
My Account and Projects error

### ISSUE THREAD

**Issue by freshelle** [Giveth/giveth-dapps-v2#654]
When I clicked - "My Account" and "My donations" from the dropdown list of the account icon (upper right).
<img width="614" alt="image" src="https://user-images.githubusercontent.com/86718721/166168669-dc63ff36-9304-4e48-8676-16d9833c5801.png">

When I open https://giveth.io/projects
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/86718721/166168693-fd0b44b8-427e-4df4-9694-9e8459da35e0.png">

**Comment by MoeNick** [comment]
Its solved for now but the route cause will solve in this issue: Giveth/impact-graph#505
