### ISSUE TITLE
Design: Failed donations needs to be shown in modal and also in success page. 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#655]
**What problem is this design solving? Why is it necessary?**
*A clear and concise description of what the problem is. Link to any relevant issues, PRs, and other resources.*
Sometimes tx is failed and the web3 provider lets us know it, so we need to let the user know it as well. 

**Is there any user data or feedback backing up this feature request?**
*Share any user research conducted by yourself or others.*
Several issues were reported that the transaction is failed in their wallet but they think they saw the success page. 

**Which metrics will define this feature's success?**
*Provide current and/or expected metrics.*
Make Sentry errors on donation page less than 1 in a month. 

**Additional context**
*Add any other context or screenshots related to your design here.*
We got the problem and we planned to solve it with better frontend vs. backend interactions, meanwhile we encountered the ux and felt we have to have a design for failed or cancelled by user transactions.

**Comment by Tosinolawale** [comment]
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=7748%3A167545
![Donation Modal #2](https://user-images.githubusercontent.com/35389241/166236678-ec043c2a-e536-4435-a57c-236760a47e76.png)
![Donation Modal #2(1)](https://user-images.githubusercontent.com/35389241/166236686-e1df05ea-8d6b-491d-a0b3-c246ab85a00d.png)

**Comment by MoeNick** [comment]
@Tosinolawale 
On success mode, we just close the modal and show you are a giver now. So IMO We do not need to change the success page.

**Comment by Tosinolawale** [comment]
@MoeNick Noted.

**Comment by MoeNick** [comment]
Are there any updates @Tosinolawale @mosaeedi

**Comment by Tosinolawale** [comment]
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=7748%3A167545
@MoeNick  I believe this works for the failed donation modal

**Comment by Tosinolawale** [comment]
![Donating](https://user-images.githubusercontent.com/35389241/167589839-476a1acd-306e-472d-82fd-f15759b98428.png)
Yes. Changed the design a bit, also with Etherscan  link to view transaction harsh. 
@RamRamez

**Comment by Tosinolawale** [comment]
Apologies for the extra work @RamRamez . But that is the final design.

**Comment by Tosinolawale** [comment]
@MoeNick You can close this

**Comment by RamRamez** [comment]
@Tosinolawale thanks for the great design

**Comment by divine-comedian** [comment]
testing on `staging.givethi.io`

making a test donation I put the gas limit low to intetionally make the tx fail. 

I receive this message:
![image](https://user-images.githubusercontent.com/67759413/168651298-830087df-f4ae-4f86-ba4b-228205c20b88.png)

I don't see the link for me to see the tx of my failed transaction but I can find it through metamask:
https://blockscout.com/xdai/mainnet/tx/0xdcb199f68438d4a8a4f8416b8d2cefa1635d2dd5d606a84797c32ca6c1fe378a

it seems like the block explorer link isn't showing up or is there another way I'm supposed to test this? @RamRamez

**Comment by RamRamez** [comment]
@divine-comedian 
You should see the tx hash link. I set a low gas fee then cancelled the tx and it was ok for me.
![image](https://user-images.githubusercontent.com/73441857/168668576-21db3535-9b0d-48dc-a7bf-1bccfd92d53d.png)

**Comment by divine-comedian** [comment]
> You should see the tx hash link. I set a low gas fee then cancelled the tx and it was ok for me. ![image](https://user-images.githubusercontent.com/73441857/168668576-21db3535-9b0d-48dc-a7bf-1bccfd92d53d.png)
> 
> @divine-comedian I set a very low gas fee but tx keeps pending. How did you check failed status?

I set a very low gas limit so the tx would run out of gas before completing the tx

**Comment by RamRamez** [comment]
> > You should see the tx hash link. I set a low gas fee then cancelled the tx and it was ok for me. ![image](https://user-images.githubusercontent.com/73441857/168668576-21db3535-9b0d-48dc-a7bf-1bccfd92d53d.png)
> > @divine-comedian I set a very low gas fee but tx keeps pending. How did you check failed status?
> 
> I set a very low gas limit so the tx would run out of gas before completing the tx

Still not successful in failing a tx
![image](https://user-images.githubusercontent.com/73441857/168740128-311ca577-5b6d-4dc1-92df-859078ce0640.png)

**Comment by divine-comedian** [comment]
@RamRamez yours looks a bit different than mine, I think you have to turn on a setting in MM to get some extra tx options

![image](https://user-images.githubusercontent.com/67759413/168813024-be32c73e-cf2e-41d3-af33-116fb0a27188.png)
and make sure this is off:
![image](https://user-images.githubusercontent.com/67759413/168813657-127418f6-9269-407e-85d5-f9cb25d2c6cb.png)


then the tx pop up you should be able to `edit` and see this modal 

![image](https://user-images.githubusercontent.com/67759413/168813683-da1d0d11-b0d8-42cf-aa7a-05148912b6df.png)

**Comment by divine-comedian** [comment]
@RamRamez can you confirm if we should be seeing a tx hash on the modal for this case? i.e tx runs out of gas

**Comment by RamRamez** [comment]
@divine-comedian 
When setting gas limit very low, there is no tx hash, so App is working correctly.
<img width="689" alt="image" src="https://user-images.githubusercontent.com/73441857/169878477-7a42e7bf-7905-47b5-8619-bfe06ed1dc53.png">

**Comment by divine-comedian** [comment]
@RamRamez 

I can set the tx so it runs out of gas

![image](https://user-images.githubusercontent.com/67759413/169913878-534cd2be-7aba-4561-9002-c8e7453c8348.png)

the tx runs out of gas, produces the error modal - I have a tx hash I can look up 

![image](https://user-images.githubusercontent.com/67759413/169913927-db60bc42-5108-482d-9896-1b8e672ecbbe.png)

this is the link to the tx hash
https://ropsten.etherscan.io/tx/0xb7ee3deebb4be29bec35b4055374d9aedb17fcc960503d1d43bc89a1f309935d

**Comment by RamRamez** [comment]
moving to in-progress for investigation

**Comment by divine-comedian** [comment]
I did the same trick for making the tx fail and now it does successfully show me a link in the modal - the last pending issue I think is resolved, moving to DONE!
