### ISSUE TITLE
Frontend for CULT/ETH Regen Farm

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#664]
The Cult DAO proposals have passed so we have 26ETH worth of CULT coming our way to setup this RegenFarm as per [this post](https://forum.giveth.io/t/cult-dao-regen-farm/518)

We need to dev up the frontend cards to be just like the FOX/HNY pool put for CULT.

Looks like this:
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/777b7a43-d18f-4b1c-a5d2-7398b2346616)

We need to:
- [x] set up this farm so that it appears only when the user is connected to Mainnet
- [x] remove the greyed out appearance of the FOX/ HNY farm when the user is connected to Mainnet (so that FOX/HNY only shows up on Gnosis chain)
- [x] exchange should be Uniswap v2 (not honeyswap)
- [x] Logos should show CULT & ETH - [coingecko link for CULT](https://www.coingecko.com/en/coins/cult-dao)
- [x] Token should be "CULT" everywhere instead of "FOX"... so it should say CULTstream, CULT/week, CULT, etc.. I think this is just one setting fix, but make sure it is the case in all the popups on the RegenFarm as well (i.e. in the APR popup)
- [x] On the back of the card, the description should say "The purpose of Cult is to empower and fund those building and contributing towards out decentralized future." (this might change, waiting on Kris)
- [x] "Learn more" should go to: https://cultdao.io/
- [x] "Provide liquidity" should link to CULT / ETH pool on uniswap v2

I'm waiting to hear back from Kris about how long the CULTstream should flow, but it would be great to get this started.

@mateodaza lmk what you think or if you have any questions!

FYI @MoeNick @aminlatifi @Cotabe

**Comment by aminlatifi** [comment]
@laurenluz Do we have any issue for preparing its backend?

**Comment by aminlatifi** [comment]
We cannot go for it until we have a prepared backend. This issue can be part of that also as current implementation of regen farm is modular and can be implemented as part of testing backend.

**Comment by laurenluz** [comment]
We don't yet! I was sort of waiting for you to come back so we could discuss. Can you create it?

**Comment by aminlatifi** [comment]
Yes, I can. How urgent is it? I am thinking about engaging other devs in deploying subgraph/backend. That may make deploying it a little bit longer.

**Comment by aminlatifi** [comment]
https://docs.google.com/document/d/1Dq-c2p4kTASGHpp8hG5o9KPB8g7TwPFdDgQJ8B6bXG8/edit

**Comment by aminlatifi** [comment]
@laurenluz @mosaeedi We need CULT token icon also

**Comment by aminlatifi** [comment]
These are svg images of icon on Coingecko and CoinMarketCap
![CultLogo](https://user-images.githubusercontent.com/5684607/167706942-1dfedb60-6f79-481c-bbd8-3fee2b2891a8.svg)
![Cult-DAO-Token](https://user-images.githubusercontent.com/5684607/167706964-e87295a0-ef18-4ddb-9328-a5a72e95390d.svg)

**Comment by mateodaza** [comment]
> > Here they are in SVG version! Coingecko and CoinMarketCap both use the face closeup version (Cult-DAO-Token.svg) if you want to be consistent
> 
> ![CultLogo](https://user-images.githubusercontent.com/5684607/167706942-1dfedb60-6f79-481c-bbd8-3fee2b2891a8.svg) ![Cult-DAO-Token](https://user-images.githubusercontent.com/5684607/167706964-e87295a0-ef18-4ddb-9328-a5a72e95390d.svg)

@mosaeedi can I get a better version? I get this one squared

![cult_dao](https://user-images.githubusercontent.com/18689480/167724274-680a4bfd-ba04-4cb1-8d45-8efb66bcb59c.svg)

**Comment by mateodaza** [comment]
@laurenluz I did all of. your checkpoints on the frontend, just waiting for the better quality icon. I'll be working with @mohammadranjbarz with the help of @aminlatifi to integrate backend

**Comment by mohammadranjbarz** [comment]
@mateodaza  @aminlatifi  
I added CULT/ETH regen farm , but be aware I just changed the staging subgraph addresses ( to use giveth subgraph instead of using my personal subgraph) so you need to change the subgraph addresses for staging ENV

https://github.com/Giveth/giv-token-subgraph#staging

Test scenario:
* If you don't have any test CULT token, please DM me or @aminlatifi  to send some CULTs to your wallet ( in Kovan network)
* Go to https://app.uniswap.org/#/add/v2/0x3e4d3FadEE2338D420bb5E5cB26aAd96c165476c/ETH?chain=kovan and stake some ETH/CULT
* Check your balance in our subgraph to see if your balance is correct or not
* subgraph API address https://api.thegraph.com/subgraphs/name/giveth/giveth-economy-kovan-staging
* The body that you should send to get your balances 
```
{
  balances( where: {
    id: "{your wallet address in lowercase}"
  } ) {
    balance
    allocatedTokens
    claimed
    rewardPerTokenPaidGivLm
    rewardsGivLm
    givback
    balancerLp
    balancerLpStaked
    sushiswapLp
    sushiSwapLpStaked
    honeyswapLp 
    honeyswapLpStaked 
    givStaked
    cultEthLpStaked
    cultEthLp
    cultClaimed
    cultAllocatedTokens
  }
}
```
For instance this is for my account and the numbers are good
<img width="1162" alt="Screen Shot 1401-02-21 at 16 00 43" src="https://user-images.githubusercontent.com/9850545/167839471-15739e48-96f4-4ad6-ba4f-ae28c328ea0e.png">

<img width="940" alt="Screen Shot 1401-02-21 at 16 01 25" src="https://user-images.githubusercontent.com/9850545/167839785-9ec59233-64db-4bd4-ad79-3f73aeabd91b.png">


@mateodaza These are fields you may need in frontend side from subgraph balances:
* `cultClaimed`
* `cultAllocatedTokens`
* `cultEthLpStaked`
* `cultEthLp`
* `rewardPerTokenPaidCultEthLm`
* `rewardsCultEthLm`

**Comment by mosaeedi** [comment]
[CULT.zip](https://github.com/Giveth/giveth-dapps-v2/files/8670068/CULT.zip)

@mateodaza

**Comment by aminlatifi** [comment]
@mateodaza every detail for this regen farm test deployment is written down here
https://www.notion.so/giveth/Test-Deployment-097ddfb4a58b4a1dbd50d889cfe7bb3f#a3dceed60bcd41d2a8a29d1d98f8a827

**Comment by mosaeedi** [comment]
[CULT-svg.zip](https://github.com/Giveth/giveth-dapps-v2/files/8671841/CULT-svg.zip)

The cult logo.

Cult logo on the Design system. [Here](https://www.figma.com/file/d3ciTS36toS9mra0RAPMe2/Giveth-Design-System-v0.1?node-id=333%3A41275)

**Comment by Cotabe** [comment]
Quick comments:

1. I think we should remove this "Our society is built to make it as difficut as possible to break away from societal, economic and other norms." it feels like an incomplete idea and it's not what we agreed with Kris.

2. APR looks too big, I understand this changes as people jump in. But I prefer to note it, better safe than sorry.

3. Maybe not a big thing... but once the transaction is confirmed the card gives the option to add GIV to Metamask. Not needed if GIV is not in the pair... not big trouble to have it either.

**Comment by aminlatifi** [comment]
@mateodaza Can you look at PAR? I imagine maybe the APR is correct and only CULT to ETH price in test (kovan) network is more than equivalent price on mainnet. So APR value is correct since the CULT value is considered higher. But it needs to be verified.

**Comment by laurenluz** [comment]
Also "Add GIV to metamask" should be "Add CULT to metamask" @mateodaza 

Working on getting new description copy form Kris.

**Comment by laurenluz** [comment]
Also agree with @Cotabe pon #4! 

> Pop up to harvest says: "When you harvest CULTrewards anywhere in the GIVeconomy, all liquid CULT allocated to you on that chain is sent to your wallet. Your CULTstream flowrate may also increase. Below is the breakdown of rewards you will get when you harvest." I suggest to delete "anywhere in the GIVeconomy"... you can only harvest here.

@mateodaza

**Comment by mateodaza** [comment]
> Also agree with @Cotabe pon #4!
> 
> > Pop up to harvest says: "When you harvest CULTrewards anywhere in the GIVeconomy, all liquid CULT allocated to you on that chain is sent to your wallet. Your CULTstream flowrate may also increase. Below is the breakdown of rewards you will get when you harvest." I suggest to delete "anywhere in the GIVeconomy"... you can only harvest here.
> 
> @mateodaza

Understood!

**Comment by mateodaza** [comment]
> 

Can you guide me where did you see this?  Because I'm getting this when harvesting
<img width="749" alt="image" src="https://user-images.githubusercontent.com/18689480/168915708-f1f66da7-d1d3-4498-90de-a07f8e7151ea.png">

**Comment by Cotabe** [comment]
@mateodaza 

That message appears when you successfully stake the LP tokens

**Comment by laurenluz** [comment]
Since the frontend is devv'd up already, I moving this to done. We should create separate issues for each of the problems found during testing.

The "add GIV" thing is covered in #786
