### ISSUE TITLE
Anon donations not very anon!

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#668]
<img width="1458" alt="Screen Shot 2022-05-05 at 5 06 29 AM" src="https://user-images.githubusercontent.com/14945613/166911088-1c578e9f-0285-4fb4-a784-968c3cbfc68e.png">

It shouldn't have a link to the transaction in the front end if it's an anon donation

**Comment by MoeNick** [comment]
We have to fix it on public views:

- [ ] Public Profile Donations

- [ ] Donations in Single Project View

**Comment by divine-comedian** [comment]
testing on `staging.giveth.io`

I made an anonymous donation on ropsten and the transaction on the project page no longer has a link to the tx hash

![image](https://user-images.githubusercontent.com/67759413/168849654-674ebbec-dfe4-44e1-9d78-a0c10997f62f.png)

however on the `my donations` page I can still find my donation, made anonymously and the link to the tx hash is available from there.

issue seems to be resolved, moving to DONE
