### ISSUE TITLE
Distribute GIV for Q4 Vesting to team

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#671]
https://forum.giveth.io/t/q4-2021-vesting-distribution/524/ says it's good to go

See the For Distro tab for the GIVstream allocation
https://docs.google.com/spreadsheets/d/12WmNihIHLaYz2TPfE3BHvH6Vs_JFcJ-6Vy07d9BGK5E/edit#gid=2114695455

**Comment by divine-comedian** [comment]
DONE!
