### ISSUE TITLE
GivBack design for Single Project Page

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#684]

**Comment by Tosinolawale** [comment]
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=8154%3A171412

GIVback design for Single Project Page. @MoeNick

**Comment by markoprljic** [comment]
@Tosinolawale What is the difference here on this page related to GIVbacks? The GIVbacks info on the donation panel? 
We should be consistent and use purple color for GIVback information, just like we did on Project cards.

**Comment by mosaeedi** [comment]
@MoeNick Design is done.
