### ISSUE TITLE
Cannot read properties of undefined (reading 'categories')

### ISSUE THREAD

**Issue by RamRamez** [Giveth/giveth-dapps-v2#688]
For projects without `categories`, backend sends this error for similar projects route:
`Cannot read properties of undefined (reading 'categories')`

@mohammadranjbarz @CarlosQ96 Can you take a look?

![image](https://user-images.githubusercontent.com/73441857/168030141-1eaeaaa4-d7cd-4f2f-b680-7c5e54066153.png)

**Comment by mohammadranjbarz** [comment]
@RamRamez 
Thanks, I will fix it

**Comment by divine-comedian** [comment]
testing on `staging.giveth.io` 

I checked out the project ramin mentioned, there is no longer an error message that appears, I also edited one of my projects and removed all categories and tested it, no errors appeared.

I created a new project with no categories and no error appeared.

![image](https://user-images.githubusercontent.com/67759413/175565818-701fb087-6426-46b9-ae22-5fb07fab39a1.png)

looks to be resolved, moving to DONE
