### ISSUE TITLE
From our blog not showing

### ISSUE THREAD

**Issue by RamRamez** [Giveth/giveth-dapps-v2#689]
<img width="1247" alt="image" src="https://user-images.githubusercontent.com/73441857/168035129-f6b09cc4-ad34-4325-8a2e-f79c96be0e02.png">

**Comment by divine-comedian** [comment]
testing on `giveth.io` 

I am on the homepage and I can see the content from our blog successfully
![image](https://user-images.githubusercontent.com/67759413/168647225-04784e9e-66b1-48da-90af-d6c192605e45.png)

this seems to be working well, moving to DONE!
