### ISSUE TITLE
Project owner sign-up problems

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#691]
1) **Not able to consistently log-in on Mac** sometimes not able to log-in using Mac laptop: system sends her round in a loop, asking her to verify email over and over. Verification link in email doesn't link to anything. Her solution has been to leave the log-in process for a day or day and then go back to it and it work. She has cleared her history. This is not an issue all of the time. When logging in with i-Phone, she does not experience these problems.

2) **Project not linked with account** Because she has tried to register a few times and has used different devices, she believes it has created a 'glitch' in the process. When she logs in with her account, using the exact details, she cannot see a project on her account. However, she has received a confirmation email to say project is listed. But, if she goes to the platform and searches for her project, she can find the listing but cannot see it in her account!

3) **Wallet** Also the wallet address on her account is different to the one the project is listed with.

(I have some more detail in a recording)

@ahmadabugosh I think these are issues for the platform / dev team - seem like IT issues.
@MoeNick

_Originally posted by @clara-zi in https://github.com/Giveth/giveth-planning/issues/665#issuecomment-1123763851_

**Comment by MoeNick** [comment]
I need the project owner's address, project link, and his/her email address. Is it possible to have this information? @clara-zi

**Comment by MoeNick** [comment]
I thinks it's happening out by Torus. Let's take the records to make sure.

**Comment by MoeNick** [comment]
sasa@nisria.co
https://giveth.io/project/nisria

**Comment by clara-zi** [comment]
did you get everything you needed from the recordings? 
Wallet appears to be connected with project user's personal profile and the project itself does not have a wallet. Seems like a Torus issue. 
Interestingly, project user doesn't think she has a wallet yet when asked which wallet.

**Comment by ahmadabugosh** [comment]
Also, from my initial conversations, she's very new so I think she'd be open to setting up a new wallet if that makes things easier

**Comment by clara-zi** [comment]
This issue has been resolved and project is now verified. I think we can close this issue. Thank-you.
