### ISSUE TITLE
Cancelled/Unlisted projects showing up on projects page.

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#692]
When I filter the projects using these settings

![image](https://user-images.githubusercontent.com/74267818/168337409-5bfbe5ea-763a-4db5-8e54-6d95c7b9b292.png)

It shows all projects ever made... even those which are unlisted and cancelled or just test projects... 
its even showing some projects that violate our terms and conditions (like the opp shutdown russia project shown below).. This is no good!! lets prioritize this issue!

![image](https://user-images.githubusercontent.com/74267818/168337533-a3624a47-9125-441e-8f1f-b7fb6b1c382f.png)

**Comment by MoeNick** [comment]
@WhyldWanderer can you confirm it's done?

**Comment by MoeNick** [comment]
According to [this](https://discord.com/channels/679428761438912522/981803266918727720/981854988106080276) we have a slight confirmation from @WhyldWanderer .
