### ISSUE TITLE
Not zero APR on finished farm

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapps-v2#695]
The rewarding period of TestFOX/TestHNY farm on staging regen farm has finished, so now it doesn't pay any more reward. But the APR is not zero!

<img width="405" alt="image" src="https://user-images.githubusercontent.com/5684607/168459851-a87330dd-67f0-4e94-b363-dd8757ee1d35.png">

**Comment by laurenluz** [comment]
did you reset it @aminlatifi ?

still the APR is not zero on staging

![image](https://user-images.githubusercontent.com/75490971/171271467-d5b83dd9-638d-4def-950c-57d2f6b0e836.png)

**Comment by aminlatifi** [comment]
> did you reset it @aminlatifi ?
> 
> still the APR is not zero on staging
> 
> ![image](https://user-images.githubusercontent.com/75490971/171271467-d5b83dd9-638d-4def-950c-57d2f6b0e836.png)

Yes, I notified a new round of reward paying. It will be over in 11 days!!

https://blockscout.com/xdai/mainnet/address/0x06851400866e065972ff21e1ECdE035b4772736d/read-proxy
<img width="554" alt="image" src="https://user-images.githubusercontent.com/5684607/171365121-25b02b84-74de-450c-b4be-d3b6da3062df.png">

CULT/ETH farm will be over in 5 days, you can test it there sooner
<img width="205" alt="image" src="https://user-images.githubusercontent.com/5684607/171365304-8b30bae8-35a0-4602-b5ec-73191d08b744.png">

**Comment by divine-comedian** [comment]
testing on `[staging](https://staging.giveth.io/givfarm)`

I can see on Kovan the CULT/ETH farm has ended, the APR is now 0%
issue seems to be resolved, moving to DONE! 
![image](https://user-images.githubusercontent.com/67759413/172269866-cbaba25a-fde3-4a94-b561-222a5571a59c.png)
