### ISSUE TITLE
Multi recipient addresses for different networks

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#703]

**Comment by MoeNick** [comment]
Testing:
1- Created the project: https://staging.giveth.io/project/test-multi-recipient-addresses
2- Donate to it in Ropsten with the same address for both networks. https://ropsten.etherscan.io/tx/0x661330bf7bf5c663d412e12403b1f63c9d86223e1f7226addc35a2429628160a

3- Edit the second recipient's address, for xDai

4- Donate to it again while I was on Gnosis, the trx seems to be fine on Gnosis:

https://blockscout.com/xdai/mainnet/tx/0x9143c839bb4a4ce43a25a83d95d85430d051eb7cec3bc218ae59357310add3d7

the basic functionality is good.

**Comment by MoeNick** [comment]
Only 2 tiny edits should be made, @mateodaza 

1- Please totally remove browser's warning for unsaved data, it's too buggy  on updating and saving, also on saving as draft. Let's remove it . 

2- Please change xDai to Gnosis in Create / Edit form.

**Comment by mateodaza** [comment]
> Only 2 tiny edits should be made, @mateodaza
> 
> 1- Please totally remove browser's warning for unsaved data, it's too buggy on updating and saving, also on saving as draft. Let's remove it .
> 
> 2- Please change xDai to Gnosis in Create / Edit form.

ready [here](https://github.com/Giveth/giveth-dapps-v2/pull/960) on this pr
