### ISSUE TITLE
Add table and endpoint for GET/PUT notification setting for users

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/giveth-dapps-v2#710]

**Comment by maryjaf** [comment]
How to test this issue? @mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
> How to test this issue? @mohammadranjbarz

@maryjaf  It's all technical about how we want to implement in backend side, there isn't anything for test on this issue

**Comment by mohammadranjbarz** [comment]
@MoeNick
Should I move this kind of issues to `Done` myself?
