### ISSUE TITLE
Design database table for project verification schema

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/giveth-dapps-v2#711]

**Comment by mohammadranjbarz** [comment]
The schema design based on https://docs.google.com/presentation/d/1P_vUtporlEqtu_hY5aIVrySskdM-__rSfGObUwIlhJI/edit#slide=id.g125fd5dd422_0_108

### Basic fields
* projectId
* userId ( project owner's id) (required)
* status ( verified | rejected | draft and default is **draft** ) (required)
* createdAt (required, auto generated)
* updatedAt  (required, auto generated)


### Personal info
It can use the project and project owner data, no need for additional fields
( just may need adding verify email that it would call another resolver to verify email, so it's not related to **ProjectVerification** entity

### Social Profiles 
It can be another table with these schema
* socialNetwork ( facebook | twitter | Instagram | youtube | discord )
* projectVerificationId  (required)
* projected (required)
* userId (required)
* isVerified (required)

### Project Registry
* isNonProfitOrganization (required, default is **false**)
* country (optional)
* website ( optional)
* description (optional)

### Project Contact
* twitter (optional)
* facebook (optional)
* linkedin (optional)
* instagram (optional)
* youtube (optional)

### Milestones
* foundationDate (optional)
* mission (optional)
* achievedMilestones (required)
* achivedMilestonesProof ( optional, image)

### Managing Funds
* managingFundDescription (required)
* primaryAddress (required), Should support ENS

* We should use another table maybe **PurpleAddress** and , project should have one to many relation with that, for new address, that table should have these fields
    * title
    * address
    * chain
### Term & Conditions
* isTermAndConditionAccepted

**Comment by aminlatifi** [comment]
Thanks @mohammadranjbarz, it's great. Just a few things:
- The Primary Address is defined in the project entity and we don't need it here
- I suppose `SocialProfiles` entity is the same OAuth connections. It should have a `Access Token` probably which implies is verified or not. Also, I think fields of `projectVerificationId` or `ProjectId` are not needed there, having a relation table would be enough.

**Comment by mohammadranjbarz** [comment]
> Thanks @mohammadranjbarz, it's great. Just a few things:
> 
> * The Primary Address is defined in the project entity and we don't need it here
> * I suppose `SocialProfiles` entity is the same OAuth connections. It should have a `Access Token` probably which implies is verified or not. Also, I think fields of `projectVerificationId` or `ProjectId` are not needed there, having a relation table would be enough.

1. @aminlatifi  @MoeNick  So we assume `primaryAddress` is a relatedAddress that have a `isPrimary:true` ?
2. We don't need to have accessToken because we don't want to call social networks ,  we need something in verify with OAUTH2 but at the end knowing that is verified is enough
3. Do you mean when a user verified a social profile he/she can use it for other project verification requests without verifying again? I assume everytime they want to add a social profile to a project verification request they have to verify it by OAU2 again

**Comment by aminlatifi** [comment]
> > Thanks @mohammadranjbarz, it's great. Just a few things:
> > 
> > * The Primary Address is defined in the project entity and we don't need it here
> > * I suppose `SocialProfiles` entity is the same OAuth connections. It should have a `Access Token` probably which implies is verified or not. Also, I think fields of `projectVerificationId` or `ProjectId` are not needed there, having a relation table would be enough.
> 
> 1. @aminlatifi  @MoeNick  So we assume `primaryAddress` is a relatedAddress that have a `isPrimary:true` ?
> 2. We don't need to have accessToken because we don't want to call social networks ,  we need something in verify with OAUTH2 but at the end knowing that is verified is enough
> 3. Do you mean when a user verified a social profile he/she can use it for other project verification requests without verifying again (In this case we would have Many to Many relations between socialProfile and projectVerification) ? I assume everytime they want to add a social profile to a project verification request they have to verify it by OAU2 again

1. Yeah, but we don't need it in `ProjectVerification` entity. The relation should be saved in `Project` entity and be filled in `Create Project` scenario, not verify.
2. You are right, we need it once. Just a point, backend should verify the access token itself and not just rely on value obtained by api
3. It's a misunderstanding. I don't mean to reuse them. But you are right, you don't need to change your design. Relation between `ProjectVerification` and connected account can be established by `projectId` and `projectVerificationId`. It plays ManyToOne relation role.

**Comment by mohammadranjbarz** [comment]
> > > Thanks @mohammadranjbarz, it's great. Just a few things:
> > > 
> > > * The Primary Address is defined in the project entity and we don't need it here
> > > * I suppose `SocialProfiles` entity is the same OAuth connections. It should have a `Access Token` probably which implies is verified or not. Also, I think fields of `projectVerificationId` or `ProjectId` are not needed there, having a relation table would be enough.
> > 
> > 
> > 
> > 1. @aminlatifi  @MoeNick  So we assume `primaryAddress` is a relatedAddress that have a `isPrimary:true` ?
> > 2. We don't need to have accessToken because we don't want to call social networks ,  we need something in verify with OAUTH2 but at the end knowing that is verified is enough
> > 3. Do you mean when a user verified a social profile he/she can use it for other project verification requests without verifying again (In this case we would have Many to Many relations between socialProfile and projectVerification) ? I assume everytime they want to add a social profile to a project verification request they have to verify it by OAU2 again
> 
> 1. Yeah, but we don't need it in `ProjectVerification` entity. The relation should be saved in `Project` entity and be filled in `Create Project` scenario, not verify.
> 2. You are right, we need it once. Just a point, backend should verify the access token itself and not just rely on value obtained by api
> 3. It's a misunderstanding. I don't mean to reuse them. But you are right, you don't need to change your design. Relation between `ProjectVerification` and connected account can be established by `projectId` and `projectVerificationId`. It plays ManyToOne relation role.

Nice, I changed the diagrams and edited my comment https://github.com/Giveth/giveth-dapps-v2/issues/711#issuecomment-1128435255

**Comment by CarlosQ96** [comment]
I was thinking we to handle project verification rejections and the current step queries. 
We could have a projectVerificationForm Entity like I mentioned in issue: https://github.com/Giveth/giveth-dapps-v2/issues/713

Basically relate it all the info the form needs
### ProjectVerificationForm
- Id
- state or currentStep (step1,step2,step3, completed, rejected)
- rejectedReasons (JSONB with schema, just an example { projectRegistry: { organizationCountry: "We don't support this country at the moment" } }
- ProjectRegistryId
- ProjectContacts (one to many here)
- ManagingFundsIds (one to many) 
- Social Profiles (one to many

**Comment by CarlosQ96** [comment]
When the project verification form is completed, the jsonb column data is deleted or maybe moved to a historic. What do you think @mohammadranjbarz @aminlatifi?

**Comment by CarlosQ96** [comment]
Aside from that I think it's good! Great Job Mohammad, if we go with the projectVerificationForm entity we could put the Term & Conditions field **isTermAndConditionAccepted** field there.

**Comment by CarlosQ96** [comment]
Wait maybe I was confused (text vs diagram), the entities will be separated? or we have them all in 1 entity called projectVerification?? (with validators handle all). 

Either approach works for me I think. I have done all in one entity with validators or separate it into models.
I think it's easier to implement in one entity. 

So I would add in that case:
To the ProjectVerification entity the currentStep.

**Comment by mohammadranjbarz** [comment]
@CarlosQ96  Thank you , I had not worked with JSONB so I it didn't come to my mind, your suggestion was great, using JSONB instead of using flat fields is more readable ( I feel like it's Mongo DB haahaa)
and the entities, diagram is what I meant, 3 tables for this purpose

**Comment by mohammadranjbarz** [comment]
@CarlosQ96 
I changed the diagrams and reflect your suggestions there, thank you



The schema design based on https://docs.google.com/presentation/d/1P_vUtporlEqtu_hY5aIVrySskdM-__rSfGObUwIlhJI/edit#slide=id.g125fd5dd422_0_108
## Entity Schemas
### Basic fields
* projectId
* userId ( project owner's id) (required)
* status ( verified | rejected | submitted | draft and default is **draft** ) (required)
* createdAt (required, auto generated)
* updatedAt  (required, auto generated)


### Personal info
It can use the project and project owner data, no need for additional fields
( just may need adding verify email that it would call another resolver to verify email, so it's not related to **ProjectVerification** entity

### Social Profiles 
It can be another table with these schema
* socialNetwork ( facebook | twitter | Instagram | youtube | discord )
* projectVerificationId  (required)
* projected (required)
* userId (required)
* isVerified (required)

### Project Registry
We fill all fields in a field named `projectRegistry`  as `JSONB` and after request got confirmed we clone those data in below fields in project registry
* isNonProfitOrganization (required, default is **false**)
* organizationCountry (optional)
* organizationWebsite ( optional)
* organizaitonDescription (optional)

### Project Contacts
We fill all fields in a field named `projectContact`  as `JSONB` and after request got confirmed we clone those data in below fields in `projectContacts`
* twitter (optional)
* facebook (optional)
* linkedin (optional)
* instagram (optional)
* youtube (optional)

### Milestones
We fill all fields in a field named `milestones`  as `JSONB` and after request got confirmed we clone those data in below fields in `milestones`
* foundationDate (optional)
* mission (optional)
* achievedMilestones (required)
* achivedMilestonesProof ( optional, image)

### Managing Funds
We fill all fields in a field named `managingFunds`  as `JSONB` and after request got confirmed we clone those data in below fields in `managingFunds`
We store related addresses as an array in `JSONB` but after verifying we will create related addresses based on that and relate them to project
* managingFundDescription (required)

* We should use another table maybe **PurpleAddress** and , project should have one to many relation with that, for new address, that table should have these fields
    * title
    * address
    * chain
### Term & Conditions
* isTermAndConditionAccepted

## Diagram
[![](https://mermaid.ink/img/pako:eNqdVktv2zAM_iuEzy7QYrfcgnbDelhXpEN3yUWR6IStLaWS3CBr8t9HyY84dlx488W2xMdH8hOpj0QahcksQXtHYm1FsdRLDe3zaM0LSv-MljKSwpPRC3wr0Xn46MqFh7THNVrYVjr3akygdGiHu84LXzp-WdJrWCbv0ScqOIDFYDB-Kisyz29XrgryvLZMhoaiBedxy2ZqNAtcE2_sWbVeuTXaC-kdrxSUc0RGoxtaU8IjSIv8UnN_cbfcqma3v__ijF5BH8MyIS3zUqGbkXswmrOckU9BmlLzfgo7XDnymAKLSEvbkHcYYjuz3sazTPwupMamkAmJK2NeU8hJv6IinXIVONOh0insTenLFY4ZPqWFbWaMTUUC3ImArCDn-CcFITf0ju-ofrTi1eLZGodosqEjBpej0EDuF9pirhVHoSh4mUuJ21DfjsbxIjkHTDwZbXP7066Fpj8Rf0-6povpSNxWdeCoTUy9yAfIL2j9ror2j1p3ZxXual7WrWs7wUtT_AmiDTsmiLb0mSBb82tSXOf8mmC8JuAEyQsMnag1pHBHkY_SNnMxd-NhFUKLNX984-g6pe6x-vRz-u6uPhlJIo9UZjDD1tu0vCj2gH5nbCh7y4BDS5tDp4CHtkDcV8lJYz_ppl3T94qNF2LPmqGXa1Fc6CG9cdAdIeOj4T9nx-nEP9dTY0KCARaYx8atlEU3nlZPPseRPVHpjsHVnYTdhBGnlWOqW-YFad5M4Uv8XWvjiPvmzfV1_Ldm67z-rF8-WipE7FHf0SKIPAe3MWWugKuSidxxj16VHnYb1NX8CnDr_DJ1fUfc2xJbVG1IZ86PMPlicDhcXZmPHmdnDHTugcGzBB8maMd7xayALAhyZDzu30qy_dHedPtR8_ccbBORrSoLfFngKkijM7JFJwG1-wp4dMjI-6e45_GcLTGgEevdrPAsr68P4DfoArRw0BwwFWqYYaMAbxr1ZZKkScHzUJDiq1mkJQ91FuJjFvwqzESZR7xHFq3uH195bhqbzKraJ6L05mmvZTIL1W2E6kteLXX8CywALZ8)](https://mermaid-js.github.io/mermaid-live-editor/edit#pako:eNqdVktv2zAM_iuEzy7QYrfcgnbDelhXpEN3yUWR6IStLaWS3CBr8t9HyY84dlx488W2xMdH8hOpj0QahcksQXtHYm1FsdRLDe3zaM0LSv-MljKSwpPRC3wr0Xn46MqFh7THNVrYVjr3akygdGiHu84LXzp-WdJrWCbv0ScqOIDFYDB-Kisyz29XrgryvLZMhoaiBedxy2ZqNAtcE2_sWbVeuTXaC-kdrxSUc0RGoxtaU8IjSIv8UnN_cbfcqma3v__ijF5BH8MyIS3zUqGbkXswmrOckU9BmlLzfgo7XDnymAKLSEvbkHcYYjuz3sazTPwupMamkAmJK2NeU8hJv6IinXIVONOh0insTenLFY4ZPqWFbWaMTUUC3ImArCDn-CcFITf0ju-ofrTi1eLZGodosqEjBpej0EDuF9pirhVHoSh4mUuJ21DfjsbxIjkHTDwZbXP7066Fpj8Rf0-6povpSNxWdeCoTUy9yAfIL2j9ror2j1p3ZxXual7WrWs7wUtT_AmiDTsmiLb0mSBb82tSXOf8mmC8JuAEyQsMnag1pHBHkY_SNnMxd-NhFUKLNX984-g6pe6x-vRz-u6uPhlJIo9UZjDD1tu0vCj2gH5nbCh7y4BDS5tDp4CHtkDcV8lJYz_ppl3T94qNF2LPmqGXa1Fc6CG9cdAdIeOj4T9nx-nEP9dTY0KCARaYx8atlEU3nlZPPseRPVHpjsHVnYTdhBGnlWOqW-YFad5M4Uv8XWvjiPvmzfV1_Ldm67z-rF8-WipE7FHf0SKIPAe3MWWugKuSidxxj16VHnYb1NX8CnDr_DJ1fUfc2xJbVG1IZ86PMPlicDhcXZmPHmdnDHTugcGzBB8maMd7xayALAhyZDzu30qy_dHedPtR8_ccbBORrSoLfFngKkijM7JFJwG1-wp4dMjI-6e45_GcLTGgEevdrPAsr68P4DfoArRw0BwwFWqYYaMAbxr1ZZKkScHzUJDiq1mkJQ91FuJjFvwqzESZR7xHFq3uH195bhqbzKraJ6L05mmvZTIL1W2E6kteLXX8CywALZ8)

**Comment by MoeNick** [comment]
@WhyldWanderer jfyi.
