### ISSUE TITLE
Implement endpoint for creating project verification

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/giveth-dapps-v2#712]

**Comment by mohammadranjbarz** [comment]
* We should clone project verificatoin data into project ( for instance website, email, ..)
* Maybe send email to project owner when got verified
* Send email to project owner when got rejected

**Comment by CarlosQ96** [comment]
Added send email confirmation flow. 
First Pr is all frontend and backend.

Will create a second Pr related to https://github.com/Giveth/giveth-dapps-v2/issues/803 adminbro

**Comment by CarlosQ96** [comment]
https://github.com/Giveth/impact-graph/pull/519 PR with regarding queries so it's not lost.
