### ISSUE TITLE
Implement endpoint for editting project verification

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/giveth-dapps-v2#713]

**Comment by mohammadranjbarz** [comment]
@MoeNick  @aminlatifi  @CarlosQ96 
Please say your opinions on choosing how should we implement

**Comment by CarlosQ96** [comment]
I have done before project "registration" forms with tons of info like company info, owner contact, payment method, etc. 
And the approach I took usually is ONE ENDPOINT but it receives the STEP, with a custom validator we validate the fields of that step and insert into the right model in the db.

I am more attracted to option one. 
So we have a general updateProjectVerificationRequest, that receives the step and the fields of that step. 
Return error if the step fields don't match or any is missing or invalid, and return success with the next step if all fields are ok.

But we also need to implement an additional query, which is current step, if the person closes the form and left incomplete, what happens? Usually there is a "cache" in the front for handling this temporarily but we can have a query that receives the projectId and returns the project verification info and the CURRENT step it's in.

If getting the current step is complicated, we could even have a verificationForm entity with the related db records and the current step (step1, step2, completed, rejected).
If rejected, I was thinking maybe we could add a jsonb to the verificationForm entity with the field and the reason. What do you think?

**Comment by mohammadranjbarz** [comment]
> I have done before project "registration" forms with tons of info like company info, owner contact, payment method, etc. And the approach I took usually is ONE ENDPOINT but it receives the STEP, with a **custom validator** we validate the fields of that step and insert into the right model in the db.
> 
> I am more attracted to option one. So we have a general **updateProjectVerificationRequest**, that receives the step and the fields of that step. Return error if the step fields don't match or any is missing or invalid, and return success with the next step if all fields are ok.
> 
> But we also need to implement an additional query, which is **form current step**, If the person closes the form and left incomplete, what happens? Usually there is a "cache" in the front for handling this temporarily but we can have a query that receives the projectId and returns the project verification info and the CURRENT step it's in.
> 
> If getting the current step is complicated, we could even have a verificationForm entity with the related db records and the current step (step1, step2, completed, rejected). If rejected, I was thinking maybe we could add a jsonb to the verificationForm entity with the field and the reason. What do you think?

Thanks for your suggestion, it was great, I'm ok all of you said except one thing, I think it's better to no use `step1` ,`step2` ,.. as status, I think the status  for all of these steps should be `draft` and we should have another field like `step` that value of that field can be `ProjectRegistry` , `Milestones` ,...
