### ISSUE TITLE
Implement verify business in admin panel

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/giveth-dapps-v2#714]

**Comment by mohammadranjbarz** [comment]
- [ ] Add list of verification forms in admin bro
- [ ] Add view for single verification form
- [ ] Add verify button and logic for verification forms
- [ ] Send email to project owner after it got verified/rejected
- [ ] Update project info after it got verified ( should be updated with verification form data)

@MoeNick  @aminlatifi  @CarlosQ96 
Please add items if I missed something

**Comment by CarlosQ96** [comment]
Thanks Mohammad. I'll be checking the list today. Related to https://github.com/Giveth/giveth-dapps-v2/issues/803

**Comment by divine-comedian** [comment]
same comment as in #803 :

can this be tested with the `operator` role? I'm testing on staging and I don't see many of the features, including assigning a reviewer, leaving notes..

![image](https://user-images.githubusercontent.com/67759413/174683930-bed209a4-2b31-4d93-a506-53e98a4b4587.png)


> Adminbro should have a “Verification Team” role that allows for the following actions. These are the only actions that this role should be able to take.
> 
> * Assign applications to themselves
> * View forms/applications and any uploaded files
> * Add team notes for status

Shouldn't the verificattion team also be able to approve or reject applications?
