### ISSUE TITLE
Remove Apollo from our application

### ISSUE THREAD

**Issue by MohammadPCh** [Giveth/giveth-dapps-v2#723]
We use Apollo client only to communicate to the Graphql server and we don't use any feature of it. so I think It's better to remove it from our app and use fetch (The browser's built-in API) to communicate with the server.

**Comment by MohammadPCh** [comment]
@mateodaza @RamRamez @alireza-sharifpour 
Dear Friends,
I am eager to know your comments.

**Comment by RamRamez** [comment]
Yeah, we are not using its features. I checked all our graphQL end-points and I think we can't use Apollo cache feature in most of them because we need to update like count on user reaction. In some cases we need to send token authorization in header and cache is not useful either.
And lots of end-points are mutations that can be handled easily.

**Comment by MohammadPCh** [comment]
Today we had a meeting with @alireza-sharifpour and have an agreement about the structure of our replacement. @alireza-sharifpour could you please add snippet code here?

**Comment by alireza-sharifpour** [comment]
Yes, I agree. I think we can go with the browser’s native fetch and write a function or middleware for doing the repetitive stuff.
I will work on the function and send you the code to hear your opinions.

**Comment by alireza-sharifpour** [comment]
Ok, Here is our helper function:
```ts
export function gqlFetch(
	query: string,
	variables: {} = {},
	additionalHeaders: HeadersInit = {},
) {
	const token = !isSSRMode ? localStorage.getItem(StorageLabel.TOKEN) : null;
	const Authorization = token ? `Bearer ${token}` : undefined;
	const defaultHeaders = {
		'Content-Type': 'application/json',
		...additionalHeaders,
	};
	const headers = Authorization
		? {
				...defaultHeaders,
				Authorization,
		  }
		: { ...defaultHeaders };
	try {
		const res = fetch(links.BACKEND, {
			method: 'POST',
			headers,
			body: JSON.stringify({
				query,
				variables,
			}),
		});
		return res;
	} catch (error) {
		return Promise.reject(error);
	}
}
```
What is your opinions?
@MohammadPCh @RamRamez @mateodaza @aminlatifi

**Comment by alireza-sharifpour** [comment]
Also a simple asyncThunk with and without the function:

Without:
```ts
export const fetchUserByAddress = createAsyncThunk(
	'user/fetchUser',
	async (address: string) => {
		try {
			const userData = await fetch(links.BACKEND, {
				method: 'POST',
				headers: {
					'Content-Type': 'application/json',
				},
				body: JSON.stringify({
					query: getUserByAddress,
					variables: {
						address,
					},
				}),
			});
			return userData.json();
		} catch (error) {
			console.log('Error');
		}
	},
);
```

With:

```ts
export const fetchUserByAddress = createAsyncThunk(
	'user/fetchUser',
	async (address: string) => {
		try {
			const userData = await gqlFetch(getUserByAddress, { address });
			return userData.json();
		} catch (error) {
			console.log('Error');
		}
	},
);

```

**Comment by MohammadPCh** [comment]
@alireza-sharifpour 
Great Job.
I think we can change the function name because It's not just used for fetching it can use for the mutation.
my suggestion is gqlRequest.

**Comment by alireza-sharifpour** [comment]
Thanks @MohammadPCh for the feedback.
Yes, totally agree.
I Also changed the function a little bit for handle backend fetch errors so here is the updated version:
```ts
import { isSSRMode } from '@/lib/helpers';
import links from '@/lib/constants/links';
import StorageLabel from '@/lib/localStorage';

export default async function gqlRequest(
	query: string,
	variables: {} = {},
	additionalHeaders: HeadersInit = {},
	additionalOptions: RequestInit = {},
) {
	const token = !isSSRMode ? localStorage.getItem(StorageLabel.TOKEN) : null;
	const Authorization = token ? `Bearer ${token}` : undefined;
	const defaultHeaders = {
		'Content-Type': 'application/json',
		...additionalHeaders,
	};
	const headers = Authorization
		? {
				...defaultHeaders,
				Authorization,
		  }
		: { ...defaultHeaders };
	try {
		return fetch(links.BACKEND, {
			method: 'POST',
			headers,
			body: JSON.stringify({
				query,
				variables,
			}),
			...additionalOptions,
		}).then(async response => {
			if (response.ok) {
				return await response.json();
			} else {
				const errorObject = await response.json();
				const errorMessage =
					errorObject?.errors[0]?.message ?? 'An error occurred';
				return Promise.reject(new Error(errorMessage));
			}
		});
	} catch (error) {
		return Promise.reject(error);
	}
}
```

So I think the only change we need in our current queries is to remove gql from apollo in our queries and use this function.

**Comment by divine-comedian** [comment]
@MohammadPCh @alireza-sharifpour can we close this one? I see an old draft PR attached to this

**Comment by MohammadPCh** [comment]
Yes, Let's close this.
