### ISSUE TITLE
SEO changes to Main Page Titles & Meta Descriptions

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-dapps-v2#735]
Hi @MoeNick can you help me direct this request. We want to change the page titles and meta descriptions on some of our top pages (for SEO). 

See the document here: [https://docs.google.com/spreadsheets/d/1181x53ughd8xaUa5EI4okgLNdpzmaKllMh9JuqcyeLc/edit#gid=0](https://docs.google.com/spreadsheets/d/1181x53ughd8xaUa5EI4okgLNdpzmaKllMh9JuqcyeLc/edit#gid=0)

**Comment by ahmadabugosh** [comment]
Hey @mateodaza, is this something you can help out with?

**Comment by MoeNick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-Devs-61644589b92edf0016f6999c/issues/Giveth/giveth-dapps-v2/735?planning-poker) with ZenHub @mateodaza @MohammadPCh @RamRamez @alireza-sharifpour

**Comment by RamRamez** [comment]
> Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-Devs-61644589b92edf0016f6999c/issues/Giveth/giveth-dapps-v2/735?planning-poker) with ZenHub @mateodaza @MohammadPCh @RamRamez @alireza-sharifpour
> 
> Assign it to yourself in you have bandwidth in these days.

I've implemented the component for adding Meta to all pages. It's related to issue #305. That time I asked communication team for SEO content but no response so I set some content myself.

@MohammadPCh Please check PR #315

**Comment by MohammadPCh** [comment]
Thank you @RamRamez for your explanation.
I saw the code, It's just changing the content.
Do you like to take it?

**Comment by RamRamez** [comment]
@MohammadPCh I'm busy with issue #745. Do you have free time to take it?

**Comment by MohammadPCh** [comment]
@ahmadabugosh @MoeNick 
I updated the content and structure.
From now on you can change any of these contents in this file. (src/content/metatags.ts)
I would also like to inform you that the title and meta description of these URLs also need to be reviewed and rewritten:
1. /support
2. /partnership
3. /onboard
4. /join
5. /faq
6. /create
7. /claim
8. /account (I think we should de-index this)
9. /user/[address]

I don't have access to the forum to update its information.
also, I think DevOps guys can help us with de-indexing staging sites. (I can do it with the front-end but I guess It's easier for them).

Thank you

**Comment by divine-comedian** [comment]
@MohammadPCh I can see the updates you made in the metatag document but none of them  seem to be showing the updates. For example:

## giveth.io
![image](https://user-images.githubusercontent.com/67759413/172268509-1af0688b-a11b-4f39-8a67-4201aefd8fb3.png)

## giveth.io/about
![image](https://user-images.githubusercontent.com/67759413/172268591-b0c964c3-af16-4d2b-9b97-256f68ac48f1.png)

## giveth.io/givstream
![image](https://user-images.githubusercontent.com/67759413/172268776-b7310a1a-a452-4eea-a8f5-c29b35a77435.png)

## giveth.io/givgarden
![image](https://user-images.githubusercontent.com/67759413/172268958-4537cc97-8f7b-47f3-93b5-e6dc90929f84.png)

You get the idea... I tested the rest and none of them seem to be showing the updated metadata

**Comment by ahmadabugosh** [comment]
@divine-comedian that's strange, when you right click and inspect each page, I do see the changes implemented. For example, this is the one from the /about page
<img width="1174" alt="Screen Shot 2022-06-07 at 2 43 28 PM" src="https://user-images.githubusercontent.com/4855928/172361121-b2d83e7f-30e0-42f2-b302-30d3b99c482f.png">

**Comment by divine-comedian** [comment]
> @divine-comedian that's strange, when you right click and inspect each page, I do see the changes implemented. For example, this is the one from the /about page <img alt="Screen Shot 2022-06-07 at 2 43 28 PM" width="1174" src="https://user-images.githubusercontent.com/4855928/172361121-b2d83e7f-30e0-42f2-b302-30d3b99c482f.png">

I opened a PR to work on this one 
https://github.com/Giveth/giveth-dapps-v2/pull/888

do you want to update any other meta descriptions like @MohammadPCh  mentioned?
i.e
/support
/partnership
/onboard
/join
/faq
/create
/claim
/account (I think we should de-index this)
/user/[address]

**Comment by ahmadabugosh** [comment]
Hey
1)  @laurenluz I added the other pages @MohammadPCh mentioned here, let us know if you have any comments on the wording before they post them: https://docs.google.com/spreadsheets/d/1181x53ughd8xaUa5EI4okgLNdpzmaKllMh9JuqcyeLc/edit#gid=0

2) @divine-comedian can you change the title and meta description for the forum homepage too? 

3) @geleeroyale I think we still need to deindex https://staging.giveth.io/, https://next.giveth.io/ and the other pages listed on the doc https://giveth.io/onboard and https://giveth.io/account

**Comment by divine-comedian** [comment]
> Hey
> 
> 1. @laurenluz I added the other pages @MohammadPCh mentioned here, let us know if you have any comments on the wording before they post them: https://docs.google.com/spreadsheets/d/1181x53ughd8xaUa5EI4okgLNdpzmaKllMh9JuqcyeLc/edit#gid=0
> 2. @divine-comedian can you change the title and meta description for the forum homepage too?
> 3. @geleeroyale I think we still need to deindex https://staging.giveth.io/, https://next.giveth.io/ and the other pages listed on the doc https://giveth.io/onboard and https://giveth.io/account

forum is updated!

**Comment by laurenluz** [comment]
looks good @ahmadabugosh, I made some small suggestions.

**Comment by ahmadabugosh** [comment]
Thanks @laurenluz @divine-comedian !

@MohammadPCh we can update the other pages now (please check the sheet to see the content): https://docs.google.com/spreadsheets/d/1181x53ughd8xaUa5EI4okgLNdpzmaKllMh9JuqcyeLc/edit#gid=0

**Comment by MohammadPCh** [comment]
Thanks, @laurenluz @divine-comedian @ahmadabugosh 
Today I will update all titles and descriptions.

**Comment by divine-comedian** [comment]
I checked all of the titles and metadata for the updates! looks good! MOVING TO DONE
