### ISSUE TITLE
newly whitelisted token not showing when donated

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#737]
I listed the DRGIV3 token in staging as an eligible token to be donated. address is `0x83a8eea6427985c523a0c4d9d3e62c051b6580d3` on gnosis chain

it shows up in the token list, I can donate it to a project, however the donation does not show up in my donations or the project page.

![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/e2ef28e7-123e-47e6-8972-ec4c0405ef4e)

![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/05ef0fb8-763b-40d9-8a2c-5c19b1ee5e85)

**Comment by mohammadranjbarz** [comment]
@divine-comedian 
As I checked the code it would create the donations and also I was a DRGIV3 donation in database that I put the screenshot below, but I don't have any DRGIV2 tokens so I couldn't test this case myself I willDM you to send me some DRGIV3 then I test it and update this issue

https://staging.giveth.io/project/giveth-2021:-retreat-to-the-future
<img width="1579" alt="Screen Shot 1401-05-04 at 12 07 57" src="https://user-images.githubusercontent.com/9850545/180950829-349138e2-2172-4fb3-a971-41178254ec3e.png">

**Comment by divine-comedian** [comment]
testing this out. It appears my donation with drgiv3 no longer fails to record and it shows up normally on the dapp.

I would like to test the full process, adding a new token via adminbro and trying to donate it on the dapp. waiting for adminbro access privileges from @WhyldWanderer to test again.

**Comment by divine-comedian** [comment]
testing on `staging.giveth.io`

got access and testing with DRGIV2 - I was able to add the token into the token list on adminbro on staging

I was then able to proceed and donate it on the dapp, donation was successful and appeared instantly on the project donations page

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67759413/182470792-4d2a2626-c676-43e6-bd92-08d9f513e3d4.png">

great work! caling this DONE
