### ISSUE TITLE
GIVpower - Explanatory Page

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#738]
This page is ready to be built! It's just an explainer page.

We still don't have all the links set up, or the rewards for the harvest section, but perhaps we can start implementing the design?

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/2e414a31-d9a0-44a8-ab68-df38455441f3)

[Link to figma](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=8207%3A169976)

@MoeNick @mateodaza

**Comment by MoeNick** [comment]
Is it final Lauren, I can see it with Review tab in Figma

**Comment by laurenluz** [comment]
@alireza-sharifpour on the GIVpower page, the rewards box needs to be updated...

If the user has their wallet connected & on the wrong chain, it should say:
"GIVpower is only available on Gnosis Chain. Please switch the network."
"Switch to Gnosis Chain"

If the user does not have their wallet connect, it should say:
"GIVpower is available on Gnosis Chain. Please connect your wallet."
"Connect Wallet"

**Comment by laurenluz** [comment]
Also, this should say "BROWSE PROJECTS"

![image](https://user-images.githubusercontent.com/75490971/171269315-2bd44104-42d0-4b02-adf1-1202e1cb68f3.png)

**Comment by alireza-sharifpour** [comment]
Thanks, @laurenluz, for checking this page.
I will fix the issues you mentioned.
Also, I have a question about the texts at the bottom. Are there links somewhere? if they are, where should they link to? [GET GIVPOWER, BOOST PROJECTS, SEE REWARDS, BROWSE PROJECTS]
<img width="1121" alt="Screen Shot 2022-06-01 at 10 42 08 AM" src="https://user-images.githubusercontent.com/48887817/171339257-1395122d-7737-4d09-aa75-69da867fcdf6.png">
<img width="1280" alt="Screen Shot 2022-06-01 at 10 44 57 AM" src="https://user-images.githubusercontent.com/48887817/171339648-eeeb0309-4dc0-41be-b040-045159c50573.png">

**Comment by divine-comedian** [comment]
where can this issue be tested? is there a separate deployment?

**Comment by alireza-sharifpour** [comment]
> where can this issue be tested? is there a separate deployment?

This issue is just UI related stuff, the upper card and modal is in issue #763 and after that we can connect the upper card to staking modal.
You can check the UI in this Vercel link:

https://giveth-dapps-v2-git-givpower-develop-branch-givethio.vercel.app/givpower

**Comment by divine-comedian** [comment]
I think the responsiveness is a bit off...

on 1024x780 the three top cards are stacked vertically and leave lots of blank space on the sides, maybe scale them down to fit horizontally, anything underneath this size looks fine stack vertically.

Also in the `for projects` heading the CTA still needs to be changed to `browse projects` at the bottom of the card

this is probably a late comment but also shouldn't some or all of these be buttons? this would be more cosistent with other pages on the giveconomy sections.
![image](https://user-images.githubusercontent.com/67759413/175612657-21d4b1e8-b232-4d03-9812-bfaae487f856.png)


@laurenluz @marko

**Comment by laurenluz** [comment]
@mosaeedi @rodricastillo9013 can you guys have a look?

I'm down for mitch's suggestions

**Comment by alireza-sharifpour** [comment]
> 

If we want to fit it horizontally in this size, it would be something like this:

<img width="821" alt="Screen Shot 2022-06-26 at 11 49 23 AM" src="https://user-images.githubusercontent.com/48887817/175803835-ab4f7e29-7cd4-4423-a63b-9dce3009f2b2.png">

and with 0 pixel padding:

<img width="803" alt="Screen Shot 2022-06-26 at 11 51 09 AM" src="https://user-images.githubusercontent.com/48887817/175803880-32e0babf-67d7-43a3-bb6a-d604562db359.png">

@divine-comedian

**Comment by divine-comedian** [comment]
I think the above one with padding looks fine, given it's the exceptional case of 1024px - 1440px screens.

**Comment by rodricastillo9013** [comment]
hi how are you! sorry for the delay, @mosaeedi  will take care of adapting this with a responsive grid! @divine-comedian @laurenluz

**Comment by divine-comedian** [comment]
okay, moving to backlog pending responsive grid and button design for links, assigning @mosaeedi for follow-up

**Comment by mosaeedi** [comment]
Mobile design -> [Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=11238%3A206951)

Responsive -> [Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=11238%3A205879)

![Screen Shot 2022-07-15 at 5 09 25 PM](https://user-images.githubusercontent.com/13708322/179240423-ca629aec-7100-4f37-a29f-a40721a858e2.png)

**Comment by Cotabe** [comment]
Tested on iphone, android and tablet. 

Looks good!

Link to learn more doesn't do anything. But it's fine because we still don't have the blog/documentation.

**Comment by Cotabe** [comment]
WAIT... 
I think if I'm not conected or in the wrong network it doesn't ask me to connect my wallet or change the network. It only says that my GIVpower is 0
