### ISSUE TITLE
Remove Welcome Modal for GIVeconomy and editing  the copy. 

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#743]
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/e44f4f82-3c45-417c-bf8d-6861bd27421c)

@danelsuga to fix the typos here.

Also I think it's strange that this popuped up on the GIVfarm page and then sent me to the project page... strange UX

**Comment by laurenluz** [comment]
@MoeNick @mateodaza can you guys have a look at this user flow too...? why are we pushing people off of their current Giveth page and onto the projects page? 

We shouldn't be sending people away from the GIVfarm.

**Comment by MoeNick** [comment]
It's a general UX flow suggested by the Design team, it appears after the user sign-in for the first time, on all pages of the DApp. We can exclude GIVeconomy part but I think we can have @markoprljic 's confirmation before.

**Comment by markoprljic** [comment]
Also, the links on this popup are not readable. Should change color @mosaeedi

**Comment by laurenluz** [comment]
Why don't we just get rid of the link to the projects page and make it an "Ok" that just closes the modal?
It's a bit weird to send the donor all over in that modal & also then send them to the projects page on the biggest button. In this case we could also keep in on the GIVeconomy side.

Also, I think we should remove "Let's Donate" at the top... maybe just start with "Welcome to the Future of Giving"... it's a bit weird because the options are not all donating options.

Also, I think we should update the copy to:

"
Welcome to the Future of Giving

You can use Giveth to:
- Donate awesome for-good **projects**.
- **Create a project** & start raising funds for your cause.
- Earn GIV from **GIVbacks** when you donate to verified **projects**.
- Earn a yield by staking tokens in the **GIVfarm**.
"

Links should be:
- "projects" --> https://giveth.io/projects
- "Create a project" --> https://giveth.io/create
- "GIVbacks" --> https://giveth.io/givbacks
- "GIVfarm" --> https://giveth.io/givfarm

Thoughts @markoprljic @MoeNick ?

**Comment by danelsuga** [comment]
Hi friends.

May I just leave the edits here for the pop-up above?
[Changes in boldface.]

Welcome to the **Future** of **Giving** [Note caps for our slogan.]

Here **are some** things that you can do **right** now!
[I'm not sure this is the sentence we want? But I'm leaving it, with corrections. @laurenluz ?]

- Take a look at **the** awesome projects on Giveth.
- **Create** a new project and receive donations.
- **Earn** GIV **tokens** by donating to projects.

**Comment by danelsuga** [comment]
Simultaneous posting! Oops. Disregard mine, folks!

@laurenluz there is a typo in your corrections: 
Donate **to** awesome for-good projects.

**Comment by laurenluz** [comment]
Oops, sorry Suga - thank you!

**Comment by MoeNick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-Devs-61644589b92edf0016f6999c/issues/Giveth/giveth-dapps-v2/743?planning-poker) with ZenHub @alireza-sharifpour @mateodaza @MohammadPCh @RamRamez
