### ISSUE TITLE
Design email template for Verify your email.

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#746]
### Design resource

1. **Email template**

- Email template
[Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=8873%3A175725)
--
-  Assets
[Download here](https://app.zenhub.com/files/448919340/2c653bed-2604-4527-967f-053e2eedfe9a/download)
---
2. **Successful email verification**

- by clicking on **Verify your email address** on the email we will open this page
[Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=8885%3A176993)

- Assets
[Download here](https://app.zenhub.com/files/448919340/2aaa13a2-fd16-4245-b212-056cf1953b15/download)

**Comment by mosaeedi** [comment]
@MoeNick Please take a look.

**Comment by mosaeedi** [comment]
![Screen Shot 2022-05-25 at 6.09.55 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/92abbb6e-5615-41f7-8753-0be8390ec05e)

@WhyldWanderer the copy!

**Comment by WhyldWanderer** [comment]
Should say 
"Well done
Your email has been verified! ⏎
You can now close this page and continue verifying your project."

Button should say:
"CONTINUE VERIFICATION"

**Comment by CarlosQ96** [comment]
Added segment event to track this action. @divine-comedian @WhyldWanderer let me know when you configure autopilot for staging/prod so we can test sending the email.

**Comment by divine-comedian** [comment]
how can we trigger this email to test it?
