### ISSUE TITLE
Implement before you start page

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#748]

**Comment by divine-comedian** [comment]
looking at this page, has the text been reviewed? Also, there is a lot of empty space under the text, can the card be made to fit the text or how can we remove this empty space? @RamRamez 
![image](https://user-images.githubusercontent.com/67759413/175965526-75bf4aae-8d85-4c1d-a4dd-8aef4f6124aa.png)

**Comment by RamRamez** [comment]
@divine-comedian as far as I know, the text had been reviewed in figma. The empty space and the text is according to [Figma](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=8474%3A182721).
If you think they can be better, please talk with @MoeNick .

![image](https://user-images.githubusercontent.com/73441857/176138201-04f49744-192a-411d-9559-a5bf6dab3763.png)

**Comment by divine-comedian** [comment]
Okay, well according to Figma it looks to be the right spec. moving to DONE.
