### ISSUE TITLE
Implement Personal Info page

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#750]

**Comment by alireza-sharifpour** [comment]
Remaining Tasks:
- [x] Implement personalInfo Mutation
- [ ] Implement Email Verification Mutation
- [ ] Implement Token Mutation
- [ ] Create Email Template
- [ ] Create Success Template
- [ ] Create Failed Template
- [ ] Add Email-Verification Phases different steps in personal info
