### ISSUE TITLE
GIVpower | My Account - Boosted Projects Tab

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#759]
- User didn't boost anything yet -> [Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=12771%3A233675)

- Has boosted -> [Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=12568%3A236207)

**Comment by mosaeedi** [comment]
@MoeNick I think we don't need this one!

**Comment by MoeNick** [comment]
1- Does date have meaning on this view? we change the date regularly on each boosting. 
2- Shall we have the trash icon on this view?

**Comment by MoeNick** [comment]
@divine-comedian @maryjaf pls confirm and merge.

**Comment by divine-comedian** [comment]
testing on https://givpower.vercel.app/

I will add in issues continually as i find them to this issue.

Looking at this page I notice a few issues:

![image](https://user-images.githubusercontent.com/67759413/190472507-a5015a0d-5ae5-4152-85ae-bad97affed95.png)


- where it says `~Total amount of GIVpower` the `~` should be in front of the number below, not the text
- some capitalization should be made more consisted, where we have 'My Donations' we should also capitalize 'My Projects', 'Boosted Projects', and 'Liked Projects'

`GIVPower Table Summary` should be `GIVpower Summary`

In the table it says 'boosted with' - this should be '% of Total'

**Comment by divine-comedian** [comment]
text fixes pending in 
https://github.com/Giveth/giveth-dapps-v2/pull/1511

**Comment by MohammadPCh** [comment]
@divine-comedian thanks for the fixes.

**Comment by maryjaf** [comment]
Can we move this issue to the unit test pass column? @divine-comedian

**Comment by MoeNick** [comment]
@maryjaf text fixes have been done in https://github.com/Giveth/giveth-dapps-v2/pull/1511 but please still these the functionality of this page, try to lock/unlock, change numbers, trash, save and all related h-cases.

**Comment by maryjaf** [comment]
> @maryjaf text fixes have been done in #1511 but please still these the functionality of this page, try to lock/unlock, change numbers, trash, save and all related h-cases.

these scenarios are tested and some issue that reported about save module on #758 has been resolved.
