### ISSUE TITLE
GIVpower - Adding Boost to Single Project View (Public and PM view)

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#762]
**[Public view]**
- Project don't have any boost yet -> [Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=12931%3A251020)

- Project has boost -> [Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=12568%3A234000)

**[Private view]**

- No boost view -> [Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=13046%3A255612)

- project boosted p-> [Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=13046%3A254867)

## Guides 
- Responsive guide -> [Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=12922%3A242058)

- Mobile guide -> [Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=12922%3A242964)

-----------------------------
Issues after unit test 29 Sep

- [ ] public/private link 
- [ ] ranking
-

**Comment by MoeNick** [comment]
Project Owner View?

**Comment by MohammadPCh** [comment]
@alireza-sharifpour can you take the integration of this part with the back-end? we need it for 14 Sep (Test party).

**Comment by alireza-sharifpour** [comment]
> @alireza-sharifpour can you take the integration of this part with the back-end? we need it for 14 Sep (Test party).

Sure, I'll take it.

**Comment by maryjaf** [comment]
Project don't have any boost yet  figma pic 
<img width="654" alt="image" src="https://user-images.githubusercontent.com/111529185/192976307-633f03e1-8e01-4fc3-9a77-eb5bde699345.png">

Project don't have any boost yet  giv power env pic
<img width="865" alt="image" src="https://user-images.githubusercontent.com/111529185/192976585-7faed91c-fa61-4a11-919a-1926f7bda14c.png">
which one is correct ? #1 or -- ?
@MohammadPCh @aminlatifi

**Comment by aminlatifi** [comment]
@maryjaf I found the bug, it will be fixed soon https://github.com/Giveth/impact-graph/pull/670

**Comment by maryjaf** [comment]
Thanks @aminlatifi 
Now the last rank, 11, is displayed for projects that have not been boosted yet.
But according to Figma, they should not have a rank(--). We discussed this before, but I did not understand what the final decision was

**Comment by aminlatifi** [comment]
@maryjaf I think it's better to handle it on the frontend, show (--) when the project total power is zero

**Comment by maryjaf** [comment]
There are discrepancies in this picture plz check it
The rank of the project is 3
But the name is not displayed
The number of people who have boosted is not correct, my user is not displayed for example

<img width="1408" alt="image" src="https://user-images.githubusercontent.com/111529185/192983646-5140e45a-7f37-49cc-9f66-67adebc7b62d.png">

**Comment by maryjaf** [comment]
I think this issue does not have the necessary conditions to continue the test and I will move  it to code review for further investigation

**Comment by aminlatifi** [comment]
> There are discrepancies in this picture plz check it The rank of the project is 3 But the name is not displayed The number of people who have boosted is not correct, my user is not displayed for example
> 
> <img alt="image" width="1408" src="https://user-images.githubusercontent.com/111529185/192983646-5140e45a-7f37-49cc-9f66-67adebc7b62d.png">
> 
> And another contradiction is that I don't see my user in the Give Power section of the projects that I have boosted and it shown in my boosted list (for example:New Organization 2), but ,for a project that is not in my user's boosted list and has been deleted, my user is shown in the givpower list of project(for example:New). @aminlatifi

@maryjaf Note, when you boost a project it doesn't show here immediately. You must wait till the end of round to see it. Actually, we regularly take snapshot of your boosting and power balance and at the end of round average it to allocate balance to the project.
In above case, the use who had boosted project wasn't you! it was user id 122 who had not filled his profile name

**Comment by aminlatifi** [comment]
@maryjaf I put it back to uint test. We may need to split problems in different issues if you agree. The public/private link and ranking are different topics

**Comment by MoeNick** [comment]
@aminlatifi both public and PM view should handle in this issue as a single User Story Value. we may define some tasks under it for now.

**Comment by alireza-sharifpour** [comment]
> 

Yes, I'll do it

**Comment by alireza-sharifpour** [comment]
> GIVpower - Single Project View - Boosting Modal #761

Yes, I'll do it @aminlatifi

**Comment by maryjaf** [comment]
I still see this message "This project hasn't received any boosts yet!
Share this project on social media and ask your friends for a boost!" for my unboosted project .

but in figma shown this: "Your project didn't receive any boosts yet!
Share this project on social media and ask your friends for a boost!"
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/a40ce49c-ae07-4cd3-a487-6b785060a67e)

@alireza-sharifpour

**Comment by alireza-sharifpour** [comment]
Now it should be fixed! @maryjaf

**Comment by RamRamez** [comment]
`Your project didn't receive any boosts yet!`
I think this sentence is grammatically wrong (when using `yet`, verb must be in past participle form). @divine-comedian Can you check it?

**Comment by divine-comedian** [comment]
> `Your project didn't receive any boosts yet!`
> I think this sentence is grammatically wrong (when using `yet`, verb must be in past participle form). @divine-comedian Can you check it?

nice catch!! 

`Your project hasn't received any boosts yet!`
