### ISSUE TITLE
GIVpower - Implement Stake for GIVpower Modal

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#763]
This User Story includes the following use-cases: 

- [x] Approve 
- [x] Stake and lock
- [x] Unstake
- [ ] Claim rewards

### Design resource

**Overview**
[Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=7788%3A167012)

1. Givpower farming card
[Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=8026%3A175918)
**Important**: on the farming card, users has the option to **open** the **Lockup details** modal.
- **Standalone** Lockup details modal
[Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=8885%3A177799)

- GIVpower modal
[Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=8408%3A168171)

---

2. Unstake card
[Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=8678%3A185910)

**Important**: On the Unstake modal, we have the option to **navigate** to **Lockup details** and the user can go back to the Unstake modal using the **back**  button at the top
- Lockup Details modal
[Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=8474%3A189731)

**Comment by mosaeedi** [comment]
@MohammadPCh @MoeNick Design resource added, please take a look.
Also I've added some hints on Figma to make it more clear.

**Comment by laurenluz** [comment]
@mosaeedi I think we need to update the links to the figma here. Can you please do it?

Also first, please resolve the outstanding comments that are in there from Griff, Marko & me.

**Comment by divine-comedian** [comment]
ah okay, lauren advised me that you are using DRGIV2, I tried getting DRGIV2 from the GIVdrop but I hit an error - the claim button does nothing and I can see a few errors in the console. How else can I get DRGIV2 for testing?

<img width="1440" alt="Screenshot 2022-07-05 at 14 17 12" src="https://user-images.githubusercontent.com/67759413/177325686-ebcf9747-9123-43be-a1f5-3fb13c49515d.png">

**Comment by divine-comedian** [comment]
on this modal here:

![image](https://user-images.githubusercontent.com/67759413/177330418-0397a74c-0c1b-46bc-9e85-09ebd9546a2a.png)

shouldn't we have a `learn more` link somewhere?

---

there's a lot of information here and the modal is looking very skinny, would it be better to increase the width of the modal so the information displays better?

![image](https://user-images.githubusercontent.com/67759413/177331547-4f0a0dd2-401f-44e0-a1c4-8206cb826cf7.png)

**Comment by divine-comedian** [comment]
Locking up my GIVpower for more rounds the date of unlock never changes - it always shows as July 6 no matter if I lock for 2 rounds, 4 rounds, 6 rounds....
<img width="1440" alt="Screenshot 2022-07-06 at 09 31 08" src="https://user-images.githubusercontent.com/67759413/177495476-a83cfd61-7d9e-47d5-9976-75bca23c6a01.png">

<img width="1440" alt="Screenshot 2022-07-06 at 09 39 56" src="https://user-images.githubusercontent.com/67759413/177496638-5942ea9a-6424-416e-9d7e-4343e8c931cd.png">

**Comment by Cotabe** [comment]
All these seems to be implemented & working
