### ISSUE TITLE
GIVpower - Implement Manage your GIVTokens Modal

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#764]
https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=8154%3A170197

**Comment by laurenluz** [comment]
Just waiting on @mosaeedi to clean things up a little. we went over it yesterday and fixed things up. let's review in tomorrow's GIVeconomy dev call
