### ISSUE TITLE
GIVbacks UI bug

### ISSUE THREAD

**Issue by csggene3** [Giveth/giveth-dapps-v2#769]
Just harvested my GIVstream like usual, but there was seemingly a GIVeconomy user interface error showing double of what was intended to be given as GIVbacks, though even the quantity given back seems way too high. I'd like to GIVback this GIVback =D Including screenshots
![Screenshot (193)](https://user-images.githubusercontent.com/10295641/169481369-f5ae78b3-f668-4ad0-9fa5-f931ca31ef5a.png)
![Screenshot (194)](https://user-images.githubusercontent.com/10295641/169481398-6b14c04e-455e-472f-9b22-ba1e2459a48a.png)
![Screenshot (195)](https://user-images.githubusercontent.com/10295641/169481425-1b5df5a7-02a3-4195-92e3-18591e9183eb.png)
![Screenshot (196)](https://user-images.githubusercontent.com/10295641/169481443-3b2fd007-95d6-41ae-bf5d-0e036dfa00c3.png)
![Screenshot (197)](https://user-images.githubusercontent.com/10295641/169481470-5762d76f-4f57-492e-a3c4-5d9d8493f1a8.png)
![Screenshot (198)](https://user-images.githubusercontent.com/10295641/169481499-4f0ef4f3-9d89-4521-a846-ea08cde5dd00.png)
![Screenshot (199)](https://user-images.githubusercontent.com/10295641/169481514-491634bf-d451-4fdc-831f-751bf9d7fd0d.png)
![Screenshot (200)](https://user-images.githubusercontent.com/10295641/169481524-7f8561e3-bc96-4ac5-83be-8a5d3d5cc1a8.png)

**Comment by laurenluz** [comment]
looks to be fixed now!
