### ISSUE TITLE
Issues with newsletter “subscribe” landing page location and copy

### ISSUE THREAD

**Issue by danelsuga** [Giveth/giveth-dapps-v2#770]
Hi friends!

I was on https://docs.giveth.io/newsletter/

I clicked on “To subscribe to our monthly emails, follow this link.” 

It took me to the giveth.io home page. Address is https://giveth.io/#subscribe but it was just the top of the regular page. I had to scroll way down to search, discover, find, if there would be a place to subscribe. Indeed, there is! But why so far away?

Also, text might need to be corrected: 

Thank you for subscribing to **the** Giveth newsletter.

And I would replace the second sentence with the following: 

You’ll be hearing from us soon!

@laurenluz 
@ahmadabugosh 

I don’t know what devs to tag if tagging is needed here? Help. Thanks. Merci. :)

**Comment by laurenluz** [comment]
yeah let's do it

**Comment by ahmadabugosh** [comment]
[I created another issue for this ](https://github.com/Giveth/giveth-dapps-v2/issues/850)
