### ISSUE TITLE
Did this donation show up?

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#772]
Here’s the link the user dm'd me:

https://blockscout.com/xdai/mainnet/tx/0x02bee74fa8c893f10ed6bc00d27f4d21b1e8cfe6c9d3698d9a550c88ce3996f3

update: https://forum.giveth.io/t/i-dont-see-my-last-donation-on-my-giveth-io-account/564

**Comment by CarlosQ96** [comment]
@MoeNick Fixed the user, his donation should show up correctly. However I found a really bad bug, anonymous donations specifically are arriving without userId to the backend. 

@mateodaza Will take a look, I had a migration that fixed april donations but its ocurring again with May donations. We have to prioritize this as its affecting users. I could rerun my migration to temporalily fix it but we need to fix the flow of donations.

**Comment by CarlosQ96** [comment]
Will add a fix to the createdonation mutation

**Comment by RamRamez** [comment]
@MoeNick 
I added a toast message when donation saving is failed, but I need the text message for the tx failed modal content when tx is submitted on network but not save on DB for some reason.

**Comment by divine-comedian** [comment]
is there a way to test this? @RamRamez did you get the text to show in the toast message?

**Comment by RamRamez** [comment]
@divine-comedian I added an error text on my own.
Please test this issue with [this one](https://github.com/Giveth/giveth-dapps-v2/issues/880). ([PR ](https://github.com/Giveth/giveth-dapps-v2/pull/881)is not merged yet).

To test donation save failing, you can comment line 44 of `donation.ts`. This way:

`const { data } = await client.mutate({
			mutation: CREATE_DONATION,
			variables: {
				// transactionId: txHash,
				transactionNetworkId: chainId,
				nonce,
				amount,
				token: symbol,
				projectId,
				tokenAddress: address,
				anonymous,
			},
		});`

**Comment by divine-comedian** [comment]
> @divine-comedian I added an error text on my own. Please test this issue with [this one](https://github.com/Giveth/giveth-dapps-v2/issues/880). ([PR ](https://github.com/Giveth/giveth-dapps-v2/pull/881)is not merged yet).
> 
> To test donation save failing, you can comment line 44 of `donation.ts`. This way:
> 
> `const { data } = await client.mutate({ mutation: CREATE_DONATION, variables: { // transactionId: txHash, transactionNetworkId: chainId, nonce, amount, token: symbol, projectId, tokenAddress: address, anonymous, }, });`

I found a way to test this token via this issue:

https://github.com/Giveth/giveth-dapps-v2/issues/737

I donate with DRGIV3 and I get the donation failed toast, tested successfully in #880 

anything else I should test for this issue @RamRamez ?

**Comment by RamRamez** [comment]
@divine-comedian If your donation is confirmed on blockchain but not saved on our DB for some reason, you should see `Please contact our support team` modal message. Did you see this or `Your transaction has failed!`?
