### ISSUE TITLE
set a valid amount error in donation page

### ISSUE THREAD

**Issue by RamRamez** [Giveth/giveth-dapps-v2#774]
It says "set a valid amount" but still I can donate

<img width="344" alt="image" src="https://user-images.githubusercontent.com/73441857/169698216-1ff53c73-f9e1-47fc-90e4-9dd3869e4976.png">

**Comment by divine-comedian** [comment]
testing on `staging.giveth.io` 

now on the donate page when I have an invalid amount, as in too many decimal places the donate button is no longer clickable and I cannot donate.

![image](https://user-images.githubusercontent.com/67759413/169842103-4b49d7d3-c214-4b4a-889b-d385cd76239e.png)

seems to be resolved! moving to DONE
