### ISSUE TITLE
sign-in to giveth splash page not closing

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#782]
testing on `staging.giveth.io` 
clean cache and cookies
brave browser

when I do my first sign in on giveth.io with no cookies I see this page. 

![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/4de4dbf0-f21f-40f1-b7c6-c60fd680da6f)

I choose a wallet option, complete the sign-in from the pop-up, however this splash page doesn't not close automatically, clicking the sign-in with ethereum button does nothing now and I have no confirmation that I have signed in successfully. 

the only way to move forward from this screen is to click the `x`

when a user completes their sign-in either by torus or web wallet this splash page should close automatically, no?

![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/cda573c7-37a4-4f7e-a760-e9cbcf68b613)

**Comment by MoeNick** [comment]
Would u pls test it again?

**Comment by divine-comedian** [comment]
tested and resolved in #838 moving to DONE!
