### ISSUE TITLE
Donating from a purple list address fails to trigger warning about GIVbacks.

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#789]
According to https://github.com/Giveth/giveth-next/issues/642, there should be a warning that comes up when someone is donating from a purple list address. This lets the user know that their donation is not eligible for GIVbacks.

However, Griff helped me test this today and it seems that its no longer the case. Actually, it says quite the opposite.

![image](https://user-images.githubusercontent.com/74267818/169924438-be9f3c83-cc10-445b-a66a-887da957c55f.png)

![image](https://user-images.githubusercontent.com/74267818/169923299-2eddbaa6-5c5d-431b-ace2-dacdf5e7b37e.png)

![image](https://user-images.githubusercontent.com/74267818/169923267-5a9e3b08-ea0a-4df2-8362-7616bafbd7ed.png)

Here is the transaction: https://blockscout.com/poa/xdai/tx/0x82ab1441c45e77876e1b6698b56fb59ccbddf2c9af5818c42795f76bf503d36e

And the confirmation that this address is on the purple list:
![image](https://user-images.githubusercontent.com/74267818/169923357-c870a329-022f-47a6-a24f-0c4528d7c783.png)

Can we fix this so that it is no longer misleading to the user?
We should first detect whether the user is donating with a purple list address 
- If yes, we should warn them that they will not receive GIVbacks for that donation and ask them if they would like to proceed.

Something like this:
"This wallet address is associated with a Giveth project, therefore, donations made from this address are not eligible for GIVbacks. Would you like to proceed?"

**Comment by MoeNick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-Devs-61644589b92edf0016f6999c/issues/Giveth/giveth-dapps-v2/789?planning-poker) with ZenHub @alireza-sharifpour @mateodaza @MohammadPCh @RamRamez

**Comment by MoeNick** [comment]
@mosaeedi would u pls review this for warning design? do we have to have it on toast msg?

**Comment by MoeNick** [comment]
@CarlosQ96 can we have a service on purple list addresses for front endguys? is it available somewhere?

**Comment by CarlosQ96** [comment]
@MoeNick yes we have a purple list addresss query called getPurpleList.
Doesn't require any params, just fetch and it returns an array of addresses.

**Comment by CarlosQ96** [comment]
```
query {
    getPurpleList
}
```

**Comment by mohammadranjbarz** [comment]
@WhyldWanderer 
If we want  this to work well , we need to add all purplelists ( the addresses that are in givback-calculation config) in the impact-graph admin panel, otherwise Dapps cant know the address is in purpleList address
please check
https://github.com/Giveth/giveth-next/issues/671 and ask me if you had any questions

**Comment by WhyldWanderer** [comment]
@mohammadranjbarz - I understand... however now that the application will be in the DApp, we wont need to manually add address anymore correct?

It should add any addresses entered by the user in the application automatically when they receive the verified badge and their application is approved.

Am I missing a different requirement?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz - I understand... however now that the application form will be in the DApp, we wont need to manually add address anymore correct?
> 
> It should add any addresses entered by the user in the application automatically when they receive the verified badge and their application is approved.
> 
> Am I missing a different requirement?

Yeah you  are exactly right, but it's for the projects that get verified after merging that PR, but for existing projects we need to add the purple addresses manually

**Comment by divine-comedian** [comment]
is this issue ready to be tested?

**Comment by RamRamez** [comment]
@divine-comedian yeah, it's merged.

**Comment by divine-comedian** [comment]
testing on `staging.giveth.io`

I added in a test purple list adddress via admin bro, and now I try to donate to a verified project while connected to this wallet I receive this message on the donate page:
![image](https://user-images.githubusercontent.com/67759413/172471126-76a06687-6b9b-41f1-b8a4-5b6c004ce684.png)

I have some quick grammar fixes I will make but I think we can call this DONE!
