### ISSUE TITLE
update donate modal according to figma

### ISSUE THREAD

**Issue by RamRamez** [Giveth/giveth-dapps-v2#791]
Add loading to donate modal button

https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=2412%3A83312

![image](https://user-images.githubusercontent.com/73441857/177785412-d44effad-d49f-41b5-92cc-74ba8b8aeecc.png)

**Comment by divine-comedian** [comment]
on the confirm donation modal I can now see the spinning wheel to show my donation is being loaded/processed. 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67759413/178481727-8902c509-d10b-4ca6-9e14-910778b8272c.png">
 
moving to done!
