### ISSUE TITLE
Integrate Adminbro with Project Verification Form

### ISSUE THREAD

**Issue by CarlosQ96** [Giveth/giveth-dapps-v2#803]
The verification team must be able to track the applications coming in by date, view the form responses, access any files uploaded by the applicant, and assign applications to themselves so that the team knows someone is working on it.
Maybe we can have a section in admin bro where the team can

- see unreviewed/unassigned applications in chronological order,
- assign an application to themselves,
- easily view the application responses and access files via a link,
- approve/reject projects,
- a section for team notes where we can share information about the verification process of a project (status, reason for rejection, etc.)??

Adminbro should have a “Verification Team” role that allows for the following actions. These are the only actions that this role should be able to take.

- Assign applications to themselves
- View forms/applications and any uploaded files
- Add team notes for status

**Comment by divine-comedian** [comment]
can this be tested with the `operator` role? I'm testing on staging and I don't see many of the features, including assigning a reviewer, leaving notes..

![image](https://user-images.githubusercontent.com/67759413/174683930-bed209a4-2b31-4d93-a506-53e98a4b4587.png)


> Adminbro should have a “Verification Team” role that allows for the following actions. These are the only actions that this role should be able to take.
> 
> * Assign applications to themselves
> * View forms/applications and any uploaded files
> * Add team notes for status

Shouldn't the verificattion team also be able to approve or reject applications?

**Comment by WhyldWanderer** [comment]
No.. this is done on the first day of the round by someone with a higher role that also lists and unlists etc. 

The Verification team role would leave their decision in the notes section and the badges would be awarded on the first day of the round by someone like nikola who has permissions to list/unlist etc.
