### ISSUE TITLE
Backend Verification: Implement Verify Email service

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#804]
As a project owner, I want to click on verify my email button and I got an email to verify my email. whenever i click on the link on verification email, it should get my email verified. 

Success Criteria:

- The verification code needs to generate with an expiration date for a certain user request.
- Acknowledge needs to be implemented for the front end, (so when UI opens the tab it shows the verification is sent and the user won't be able to send it again. )
- The email should get sent the with the call-back URL with this verification code[  EMAIL SAMPLE is here](https://github.com/Giveth/giveth-dapps-v2/issues/746)
- 
- We have another service to make the email verified=true, when the user open this email. [Verified Email Page is here. ](https://github.com/Giveth/giveth-dapps-v2/issues/746)

**Comment by CarlosQ96** [comment]
Implemented this. But need to coordinate that callback url flow. but I think the mutations I did are enough, added tests to them.

**Comment by CarlosQ96** [comment]
@divine-comedian @WhyldWanderer when you can help me set up autopilot with frontend guys let me know. We have to set the link in the email.

**Comment by divine-comedian** [comment]
testing on `staging.giveth.io` 
I entered my email and I receive an email into my inbox, I click the link, either the button or raw URL and it takes me to a 404 page on Giveth.io

![image](https://user-images.githubusercontent.com/67759413/175964866-3c62b220-1ee9-4197-9cf7-63d9e97d48af.png)
![image](https://user-images.githubusercontent.com/67759413/175964954-c7cbefd5-3570-432a-9c9d-52e28eb7649b.png)

this does not seem to be working - moving to backlog
