### ISSUE TITLE
update xDAI icon for GIV/xDAI GIVfarm

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#806]
we need to update the new xDAI/GIV GIVfarm for the GIVfarm extension, we'll need to update the token icon from DAI to xDAI

![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/aa5e7d38-3762-41ae-8dd4-c223b58f8543)

here is the media asset we'll need to modify and create the appropriate svg files for (64px,40px,32px,24px,16px .  ![Identity-Stacked-LightBG.svg](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/4ff890fa-0ae8-46cb-8db7-760689f48270)

then we'll need to insert it into the dapps repo and make the UI changes

**Comment by mosaeedi** [comment]
It's part of the icon library
[Figma link](https://www.figma.com/file/d3ciTS36toS9mra0RAPMe2/Giveth-Design-System-v0.1?node-id=333%3A41275)

It's up to devs to implement it.

**Comment by divine-comedian** [comment]
@mateodaza @MohammadPCh ?

**Comment by divine-comedian** [comment]
nvm I got this guys

**Comment by divine-comedian** [comment]
in here 
https://github.com/Giveth/giveth-dapps-v2/pull/835
