### ISSUE TITLE
Anonymous donations arriving without UserId 

### ISSUE THREAD

**Issue by CarlosQ96** [Giveth/giveth-dapps-v2#810]
Related to https://github.com/Giveth/giveth-dapps-v2/issues/772

Anonymous donations specifically being saved without userId. The frontend is not sending it. We have a new mutation that throw error if this is the case (is it implemented in the frontend?)

I had a migration to fix donations of april, but it's ocurring again in May. Let's have a meeting to check the flow and fix this.

This affects users being able to see their anonymous donations in their profile.

**Comment by MoeNick** [comment]
According to our talks we don't send them in F.E. we send the jwt in the header and the problem occurs when the user is not signed in, so the recent changes on Production may fix the problem, the only concern is on staging. 
On staging according to the recent flow, we have to through error if saveDonation don't have jwt in the header.

**Comment by MoeNick** [comment]
Moving to UAT. 
Test Scenario:
Change wallet and donate and should appear in my donations.
