### ISSUE TITLE
User request for DAOhaus compatibility

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#811]
Related to #417

<img width="656" alt="Screen Shot 2022-05-25 at 8 34 56 AM" src="https://user-images.githubusercontent.com/14945613/170288038-dcdcf416-2f6c-4979-b2da-0fc092795ce2.png">

<img width="688" alt="Screen Shot 2022-05-26 at 8 28 46 AM" src="https://user-images.githubusercontent.com/14945613/170508834-07469fd3-0843-482b-9663-c134a5ae079a.png">

If we can get Wallet Connect to work, then DAOs and gnosis safes  can Donate!

**Comment by MoeNick** [comment]
@CarlosQ96 it might be fixed now, right?

**Comment by deeayeen** [comment]
We are using DAOHaus's Gnosis Safe Minion, and using WalletConnect from the Safe Minion UI. When attempting to donate, a login prompt asks you to make a signature to sign in, but this signature request is not recognized by DAOHaus's WalletConnect interface

**Comment by CarlosQ96** [comment]
Hello @deeayeen @GriffGreen I uploaded a hotfix to production fixing donations that don't show in user profile. Could you please verify your account again. Thanks!

**Comment by deeayeen** [comment]
Hey @CarlosQ96 I think that may be a separate issue!

**Comment by CarlosQ96** [comment]
Oh hey @deeayeen you might be right. I commented as I saw it wasn't showing in the UI. But thanks, will check if it's anything else.

**Comment by GriffGreen** [comment]
yeah and there should be some thought put in to make it work on Mainnet...

It should always work for Gnosis Chain... but if a DAO is on mainnet... they might have issues claiming GIVbacks...

for more context check out this post here: 
https://forum.aragon.org/t/aragon-ukraine-response-wg-proposal/3312/30?u=griffgreen

**Comment by aminlatifi** [comment]
> We are using DAOHaus's Gnosis Safe Minion, and using WalletConnect from the Safe Minion UI. When attempting to donate, a login prompt asks you to make a signature to sign in, but this signature request is not recognized by DAOHaus's WalletConnect interface

@CarlosQ96 That's the main issue! the donating process includes a write to the backend which needs the user to be signed in! Therefore, it's not possible to make a new donation entity in the backend. The first solution that comes to my mind is allowing multisig users to proceed without signing in and saving the donation entity to the backend (We can have a checkbox in the UI or automatically check connected wallet is a smart contract or not!).
And after they make the transaction, they can reach out to us to add the donation via the admin panel.

**Comment by aminlatifi** [comment]
We can detect multisig wallets by `getCode` methods of ethers library in the front-end

https://docs.ethers.io/v5/api/providers/provider/#Provider-getCode

**Comment by mohammadranjbarz** [comment]
> > We are using DAOHaus's Gnosis Safe Minion, and using WalletConnect from the Safe Minion UI. When attempting to donate, a login prompt asks you to make a signature to sign in, but this signature request is not recognized by DAOHaus's WalletConnect interface
> 
> @CarlosQ96 That's the main issue! the donating process includes a write to the backend which needs the user to be signed in! Therefore, it's not possible to make a new donation entity in the backend. The first solution that comes to my mind is allowing multisig users to proceed without signing in and saving the donation entity to the backend (We can have a checkbox in the UI or automatically check connected wallet is a smart contract or not!). And after they make the transaction, they can reach out to us to add the donation via the admin panel.

I agree with @aminlatifi , just we don't need to add something in admin panel, we can just add a minimal form for those users in giveth.io then after enter their txHash there, we can create donations from that tx ourselves

**Comment by MoeNick** [comment]
Discussions about it here:
https://discord.com/channels/679428761438912522/988784701231738910

**Comment by MoeNick** [comment]
@mosaeedi now we can add manually in Admin, suggested UX how to communicate this kind of users they need to reach out to admins? 
@MohammadPCh can we understand the wallet is multisig?

**Comment by MohammadPCh** [comment]
@MoeNick 
as @aminlatifi told us, we can check it. also, I created a PR that tested it there. and the response is YES it works.
