### ISSUE TITLE
add drop down menu to GIVeconomy header tab

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#812]
Instead of or in addition to having the sub tabs in the GIVeconomy page we should add a drop down menu while hovering on the GIVeconomy button in the main header that will show all the related pages, this would allows users to quickly navigate to the page they want to visit rather than having to pass through the GIVeconomy page

![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/a907e218-f504-46b9-8734-6bfca697da37)

So user would hover over GIVeconomy and shows 

**GIVeconomy**
- GIVfarm
- GIVbacks
- GIVstream
- GIVgarden

does this make sense?

**Comment by markoprljic** [comment]
Yes. @mosaeedi

**Comment by divine-comedian** [comment]
Hey! I would love to see this issue happen, I keep going on the app and dreaming of a drop down menu

**Comment by MoeNick** [comment]
I follow it up with @mosaeedi

**Comment by MoeNick** [comment]
It's related to our new header so I close this one.
