### ISSUE TITLE
CULT/ETH Farm is innacessible when not connected to Giveth

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#820]
testing on `staging.giveth.io`
brave browser
clean cache and cookies

on the givfarm page and not signed into giveth at all I cannot interact with the RegenFarm. It is blurred out and the modal tells me connect to mainnet (Kovan). 
![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/d972d7e8-f14f-4013-bdc0-759ef99ec4b0)
If I am already on Kovan this button does nothing. 

However on the regular givfarms further up top there is a card asking me to switch to either GC or mainnet, if I am not connected to giveth clicking either of those buttons will prompt me to sign in with my wallet. 

![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/8c266719-4841-4f8f-a36b-ae65144e22e9)

we should apply a similar funcitonality to this regen farm `switch network` modal

**Comment by MoeNick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-Devs-61644589b92edf0016f6999c/issues/Giveth/giveth-dapps-v2/820?planning-poker) with ZenHub @alireza-sharifpour @mateodaza @MohammadPCh @RamRamez

**Comment by laurenluz** [comment]
@mateodaza testing on staging this seems still not fixed.

I think what he is saying, is that::
- if the user is already on Kovan (or in production, mainnet)
- but their wallet is not connected to the dapp
- and they click the "Swtich to Mainnet" button

They should get the "connect your wallet" prompt in metamask

**Comment by laurenluz** [comment]
OH actually, this is weird on more layers.

Right now, if I am on kovan, not connected, and I click "switch to gnosis chain" at the top... it prompts me to connect by wallet, but does *not* switch to gnosis chain.

![image](https://user-images.githubusercontent.com/75490971/171063787-250c67fb-2322-4365-ab53-35c53dd60c22.png)

**Comment by laurenluz** [comment]
Is there someway that, if the user is not connected & not on that network... when the user clicks... it prompts a "connect wallet" followed by a "switch newwork" in metamask? @mateodaza

**Comment by laurenluz** [comment]
- [x] "switch to mainnet" triggering connect wallet if the user is not connected but on mainnet

But if I click the "switch to gnosis chain" at the top, and I wasn't connected, it doesn't switch to gnosis. 

I will make a separate issue for that though, and call this one done.
