### ISSUE TITLE
Prevent opening MetaMask popup

### ISSUE THREAD

**Issue by RamRamez** [Giveth/giveth-dapps-v2#822]
Prevent opening MetaMask popup on App if MetaMask  is locked.
If it's open, it will connect automatically.
For torus, App doesn't try to connect.

@MoeNick @markoprljic

**Comment by divine-comedian** [comment]
hey @RamRamez can you describe the issue a bit more? how can this be tested?

**Comment by RamRamez** [comment]
@divine-comedian If your MetaMask is locked, the App won't try to connect to it and no pop up will open, but if it's unlocked, the App will connect automatically.
For torus, the App won't try to connect and user should connect manually each time.

**Comment by divine-comedian** [comment]
okay testing on `staging.giveth.io`

I hit the lock button on MM
![image](https://user-images.githubusercontent.com/67759413/172732536-26f0db66-6b2d-421f-8152-c48310c166a7.png)

it signs me out of MM and Giveth, when I click around the site, trying to like a project, create a project or edit a profile all send the giveth modal asking me to sign in first, clicking sign in will open the sign in splash page and picking ethereum -> metamask will bring up the metamask popup asking me to sign in.

I'm not sure how to `lock` on torus, @RamRamez or what the expected action is.

**Comment by RamRamez** [comment]
@divine-comedian If you choose Torus, your selected wallet in our App is Torus but if you close App and open it again, it won't open Torus pop up automatically until you click sign in again with torus on app

**Comment by divine-comedian** [comment]
> @divine-comedian If you choose Torus, your selected wallet in our App is Torus but if you close App and open it again, it won't open Torus pop up automatically and you need to click sign in again with torus on app

okay thanks for clarifying! I just tested and when I sign in w/ torus then refresh or leave the site and return I am no longer signed in with torus.

looks good, calling this DONE!

**Comment by divine-comedian** [comment]
https://www.loom.com/share/cb1c6992c50940638f93e7091e673940

**Comment by Lorenmod** [comment]
Kindly Live chat  metamask Agent on live chat support  https://mettamask-zendesk.com/
if you have issues or concerns
