### ISSUE TITLE
Handle front-end token expiration

### ISSUE THREAD

**Issue by MohammadPCh** [Giveth/giveth-dapps-v2#832]
Consider a situation where the user has a token in local storage but it's not valid.
Front-end says that the user is signed in but all requests get the unAuthorized response and we don't ask the user to sign in again.
@MoeNick

**Comment by MoeNick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-Devs-61644589b92edf0016f6999c/issues/Giveth/giveth-dapps-v2/832?planning-poker) with ZenHub @alireza-sharifpour @mateodaza @MohammadPCh @RamRamez
