### ISSUE TITLE
"Add CULT to metamask" imposing GIV token logo over their icon...

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#834]
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/d15d1d6b-021d-4c21-848a-c4f8c67e8e1c)

**Comment by mateodaza** [comment]
I'm not sure how this works @aminlatifi

**Comment by laurenluz** [comment]
great job guys!

![image](https://user-images.githubusercontent.com/75490971/171257955-9717f8b8-2da4-4387-82fe-58a162c5bd28.png)
