### ISSUE TITLE
close welcome modal on user sign in

### ISSUE THREAD

**Issue by RamRamez** [Giveth/giveth-dapps-v2#838]
when user chooses a wallet to sign in, the full width `Sign in to Giveth` modal should be closed

![image](https://user-images.githubusercontent.com/73441857/171163476-e5d29024-63e0-4bcb-9eec-77af3f390a87.png)

**Comment by divine-comedian** [comment]
is this related to #782?

**Comment by divine-comedian** [comment]
testing on `staging.giveth.io` 
clean cache and cookies 

now when I sign in with ethereum I sign in with metamask and the sign in splash pages closes automatically. also works when I use torus! 
@RamRamez if you can confirm if this is related in my comment above then we can call this done!

**Comment by RamRamez** [comment]
> is this related to #782?

@divine-comedian Yeah this is related
