### ISSUE TITLE
GIVfarm - If wallet not connected, "Switch to Mainnet" prompts a connect wallet, not a switch chain

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#840]
I think if the user's wallet is not connect to the dApp, on the GIVfarm page, the copy should be different...

This should say "GIVfarm is available on Mainnet and Gnosis Chain. Please connect your wallet." And the button says "Connect Wallet"
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/62711add-f75d-4290-9d25-aab275d4a43b)

And on the RegenFarms section, the popup thing should say "Connect Wallet" "This RegenFarm is available on Mainnet" "Connect Wallet"
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/ed04eba5-02c1-4a38-a085-502434c15a00)

If the user's wallet is connected, but they are on the wrong chain, it should be exactly as it is now with no changes.

**Comment by laurenluz** [comment]
This is what it looks like on production right now, when the user's wallet is not connected. It's ok, but there should be a minor text fix:

"GIVfarm is availale on Mainnet and Gnosis Chain. Please connect your wallet."

(I think we need to delete the word "only" at the very least)

![image](https://user-images.githubusercontent.com/75490971/192641269-969d2dd7-e769-4a15-b2a6-2486b23d902d.png)

**Comment by MoeNick** [comment]
@MohammadPCh jan this is old one, but I think worth takin ga look at, thanks

**Comment by MohammadPCh** [comment]
I remember that we wanted to completely redesign this section. anyway, I can take it.

**Comment by laurenluz** [comment]
it's just removing the word "only" from the copy @MohammadPCh

**Comment by MohammadPCh** [comment]
I will fix it with #1806

**Comment by MoeNick** [comment]
Closing this and following it up at #1806
