### ISSUE TITLE
"$" should be in front of the number, not behind

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#842]
<img width="164" alt="Screen Shot 2022-05-31 at 3 40 50 PM" src="https://user-images.githubusercontent.com/14945613/171289066-e52fb9e7-19e8-4c2f-8f8f-128be304387c.png">

https://giveth.io/project/giveth-magical-terrace

**Comment by divine-comedian** [comment]
hey @RamRamez I think we just needed to move the $ from behind the numbers to in front like this 

![image](https://user-images.githubusercontent.com/67759413/174892477-92b19410-9ebf-4f41-a5e8-c5c3e5948959.png)

I just made quick commit on `develop` to resolve this 

https://github.com/Giveth/giveth-dapps-v2/commit/ed575696c4e9118f0a406f3b5b479e33dda8bac5

**Comment by RamRamez** [comment]
@divine-comedian Donation tables should be consistent along the App. In my donations table there is no dollar sign so I decided to replace this one with `USD`.

![image](https://user-images.githubusercontent.com/73441857/174905907-afee38ae-ffe7-477f-a01b-30b37cf56102.png)

**Comment by RamRamez** [comment]
> > @divine-comedian Donation tables should be consistent along the App. In my donations table there is no dollar sign so I decided to replace this one with `USD`.
> > ![image](https://user-images.githubusercontent.com/73441857/174905907-afee38ae-ffe7-477f-a01b-30b37cf56102.png)
> 
> Okay, I see your point, however if the header is USD value at the top of the column then do we need to add `USD` to every item?
> 
> would it make more sense then to add the `$` to the values in my accounts tab and remove the USD text?

Fixed in PR #980

**Comment by divine-comedian** [comment]
Let me know when it is merged and I will test again!

**Comment by RamRamez** [comment]
> Let me know when it is merged and I will test again!

@divine-comedian It's merged.

**Comment by divine-comedian** [comment]
@RamRamez 

Looks like the `$` and USD was removed from both views, so now only the numerical value is shown under the USD value column, is this the intended functionality?

![image](https://user-images.githubusercontent.com/67759413/175931156-54b62b25-25cc-4152-aeb1-533cc2a5aa76.png)

**Comment by RamRamez** [comment]
What I implemented was according [figma](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=4393%3A112100):
![image](https://user-images.githubusercontent.com/73441857/175966717-23cc8fa4-b6ee-45b8-81dd-fb3bfd2423dc.png)

@MoeNick told me to bring back the dollar sign though. (PR #1010)

**Comment by divine-comedian** [comment]
testing `staging.giveth.io`

Okay! Well I checked again on both the project view and my donations view and they both have the $ appearing in the correct place! Let's call this DONE
