### ISSUE TITLE
Donation token list dropdown should say "connect your wallet" if my wallet is not connected

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#843]
This is pretty confusing right now:
![image](https://user-images.githubusercontent.com/75490971/171294085-c2b85b94-67aa-4f2b-82db-2bd0c8d91559.png)

If my wallet is not connected it should say:  "Please connect your wallet to see the donation token list." not "no results found" etc.
It should not have the "GIVbacks eligible" thing... because there is no context for it without my wallet being connected.

**Comment by MoeNick** [comment]
Let's not let the user open the token list while not connected. @RamRamez @alireza-sharifpour

**Comment by MoeNick** [comment]
Let's only disable the token drop-down in this issue.

**Comment by jeevanplus007** [comment]
@RamRamez Can you share the snapshot of how does the Expected Result look like ?

**Comment by RamRamez** [comment]
@jeevanplus007 When wallet is not connected, token select should be disabled.

![image](https://user-images.githubusercontent.com/73441857/178065406-871974bb-735c-4e73-9fdb-30e71c8cdc60.png)

**Comment by jeevanplus007** [comment]
**Test Snapshot :** 
![image](https://user-images.githubusercontent.com/107279959/178104601-c66a3d69-64aa-4909-8474-9c88a5ae725a.png)

**Comment by divine-comedian** [comment]
@jeevanplus007 Is this issue tested successfully? can it be moved to done?

**Comment by divine-comedian** [comment]
testing on `staging.giveth.io` 

while not signed in with my wallet I can't see the drop down list of tokens. when I sign in the token list then becomes openable.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67759413/184935526-d3854de0-5867-4f38-94a8-f798ac566d40.png">

looks good! moving to done!
