### ISSUE TITLE
Reorganize donation token list - they should be not alphabetical... but should be in order of most used (at least at the top)

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#844]
It's crazy that people should have to scroll to the bottom of the token list to get to xDai. Let's make this *at least*
1. GIV
2. xDAI
3. the rest in alphabetically order

Also, it shouldn't be XDAI, XCOMB, XNODE... it should be xDAI, xCOMB, xNODE

![image](https://user-images.githubusercontent.com/75490971/171294953-2329e950-be07-4f7d-b861-4be7c6ca140b.png)

**Comment by CarlosQ96** [comment]
I think it has some default order of the db, insert order. But we would have to sort by creation date or id.
