### ISSUE TITLE
Frontend read destination address from projects related address

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#847]

**Comment by MoeNick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-Devs-61644589b92edf0016f6999c/issues/Giveth/giveth-dapps-v2/847?planning-poker) with ZenHub @alireza-sharifpour @mateodaza @MohammadPCh @RamRamez

**Comment by divine-comedian** [comment]
how can this issue be tested?
