### ISSUE TITLE
Add Community Call to Join page

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#849]
![image](https://user-images.githubusercontent.com/74267818/171446046-7e472a26-46d5-4f2b-ac6c-ddc224609b31.png)

Should say "Giveth is first and foremost a community of givers and changemakers. We are passionate people working together to build a crypto-economic system that can reward giving to good causes. Our project is open-source, decentralized, altruistic, and community-led.

You can join our Community Call every Thursday in Discord, follow our social media, or come say hello in a channel below. We look forward to welcoming you!"

Below this, there should be a button that says "Add to Calendar"

This button should link to here: https://calendar.google.com/event?action=TEMPLATE&tmeid=dWZydnNoNjVmb2NvNDNrZ2htMmtzaDNydGZfMjAyMjA2MDlUMTUwMDAwWiBnaXZldGhkb3Rpb0Bt&tmsrc=givethdotio%40gmail.com&scp=ALL

**Comment by divine-comedian** [comment]
testing on `staging.giveth.io`

on the join page 

I can see one of the first things is the text that ashley specified.

text looks good, link works good

moving this to DONE
