### ISSUE TITLE
Change Newsletter Form on Homepage

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-dapps-v2#850]
Hey @MohammadPCh we want to change the newsletter form on the homepage (since we changed email services). 

Can you please: 

1) Change the form to the one below (feel free to edit for our style etc)
2) Can you add a link to that element id, so we can send users there? Before we had this as giveth.io/subscribe (and that would redirect to the bottom of the homepage via the a CSS class ID). 

```
<div id="revue-embed">
  <form action="http://news.giveth.io/add_subscriber" method="post" id="revue-form" name="revue-form"  target="_blank">
  <div class="revue-form-group">
    <label for="member_email">Email address</label>
    <input class="revue-form-field" placeholder="Your email address..." type="email" name="member[email]" id="member_email">
  </div>
  <div class="revue-form-actions">
    <input type="submit" value="Subscribe" name="member[subscribe]" id="member_submit">
  </div>
  </form>
</div>
```

**Comment by MoeNick** [comment]
We also have it in the community page, should we fix it there also? 
https://giveth.io/join

**Comment by ahmadabugosh** [comment]
@MoeNick yes please!

**Comment by MoeNick** [comment]
Would u pls approve the copy after posting the information:
![image](https://user-images.githubusercontent.com/80677512/172838000-7cc6caab-dbf0-4026-b13f-481aa980e5a5.png)

Is it good? 
I think we have  to change Subscribed to smth else. 
@ahmadabugosh

**Comment by ahmadabugosh** [comment]
hey @MoeNick, what is the workflow like? Does it open anything in a new tab? I think also they need to opt-in from their inbox. 

I would change it to: 
**You're In!** 
We just sent you an email to confirm your subscription! Once you do, you'll receive the next issue of our newsletter in your inbox. If you'd like to view previous issues, visit our [GIVnews page](http://news.giveth.io/).

**Comment by MoeNick** [comment]
> hey @MoeNick, what is the workflow like? Does it open anything in a new tab? I think also they need to opt-in from their inbox.
> 
> I would change it to: **You're In!** We just sent you an email to confirm your subscription! Once you do, you'll receive the next issue of our newsletter in your inbox. If you'd like to view previous issues, visit our [GIVnews page](http://news.giveth.io/).

Wow, what an excellent copy. @ahmadabugosh 
We will send you the link to see it and approve the flow.

**Comment by ahmadabugosh** [comment]
hey @MoeNick I agree, I don't think we should do it that way for sure! 

The thing is, the newsletter page doesn't have https enabled (since we would need to implement it on Cloudflare or something similar, which @geleeroyale told me we may do in the future, but we don't have now), so I agree we shouldn't embed it if it gives that error.  

However, I do think the platform is great for us (since we started using it our email subscribers grew by 400+, and people can subscribe directly from our Twitter page).

What I suggest is instead we just have a link for them that takes them to the [Newsletter url](http://news.giveth.io/)? So remove the embed form and just have the subscribe link go to that page.

**Comment by MoeNick** [comment]
@ahmadabugosh I can flow up the https, I think it avoid us redo it again after we have this.

**Comment by ahmadabugosh** [comment]
thanks @MoeNick ! As a temporary fix though, I recommend to just link to the newsletter page

**Comment by ahmadabugosh** [comment]
Thanks @divine-comedian , I believe this is because we removed the custom domain (since we couldn't get the SSL to work). 

I believe it should work if we just change "http://news.giveth.io/add_subscriber " to "https://www.getrevue.co/profile/giveth/add_subscriber"
