### ISSUE TITLE
FORM: Bug/Issue

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-dapps-v2#860]
**Please describe the issue or bug you are experiencing:**
this is a test
![image](https://api.typeform.com/forms/O9gpKmnt/responses/bdofonx38mmjmie265bdofob294y49gb/fields/eB8INCgwFHrW/files/bac0f75f4681-step_11.PNG)

**Comment by WhyldWanderer** [comment]
The support feature request and bug/issue zaps were never changed from the giveth-next repo to this one... 
This was to test that the switch was successful
