### ISSUE TITLE
Bad card project formatting on hi 5 page. (success project creation) 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#865]
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/81a2b18e-37d3-44f7-84ae-af8815880f32)

**Comment by RamRamez** [comment]
For testers of PR #875:
1. make success view responsive
2. fix project card formatting in success view
3. add copy url to success view
4. fix copy url functionality (return to normal after 5s)
5. fix success view style issues (headings, etc)

**Comment by divine-comedian** [comment]
testing on `staging.giveth.io` 

tested responsiveness on mobile, tablet and laptop sizes - looks good
project card formatting looks good
copy url functionality works
copy url functionality returns to normal state
headers look good
no footer - looks good

this issue looks to be resolved! moving to DONE!
