### ISSUE TITLE
Users are getting unsaved browser warning when trying to save projects as draft. 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#866]
on the project creation page, when I try to preview, I got this: 
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/3596f7d1-33eb-43b8-85ae-177ab375fcb1)

**Comment by divine-comedian** [comment]
testing on `staging.giveth.io`

when i go to preview my project from the project creation page there is no longer any message warning me of unsaved changes. 
![image](https://user-images.githubusercontent.com/67759413/172673298-37ab29d1-111a-4017-b394-590751787b4b.png)
