### ISSUE TITLE
I'm registered but it says 'Complete your profile'

### ISSUE THREAD

**Issue by RamRamez** [Giveth/giveth-dapps-v2#868]
![image](https://user-images.githubusercontent.com/73441857/172066077-3bfdde04-43e5-4335-89fb-cac85bd2b990.png)

**Comment by divine-comedian** [comment]
hey @RamRamez testing this issue on `staging.giveth.io`
clean cache and cookies

I have a profile already with a first and last name and an email associated with my account. I go to create project, it asks me to fill in my profile, I go to my profile and it shows my first name, last name and email as empty fields. What's happening?

made a loom video to explain more:
https://www.loom.com/share/2342280d0f024a989bf607cc9db09991

moving this to prod backlog

**Comment by RamRamez** [comment]
@divine-comedian thanks for reporting. Backend has removed sending user mail address for not signed-in users so you have mail address and app thinks that you are not registered. After sign in, we should should user data again from backend.

fixed in PR #911
