### ISSUE TITLE
Converted USD value of GIV-denominated donation is artificially high by a factor of 4x+ This same high value is currently displayed on CoinGecko

### ISSUE THREAD

**Issue by csggene3** [Giveth/giveth-dapps-v2#870]
I tried to make a couple small donations this evening, and my GIV converted to USD value shown in the Donation Preview is really high, like 44 cents versus the gardens oracle value of 09 cents. I checked CoinGecko and it's displaying volume at this higher price. How is the value and volume calculated on CoinGecko? Which markets are being reflected? The My Donations page displays the gardens price, so if you check My Donations later, you will see the lower value historically. Are there markets that are actually trading at this higher multiple today? I'll look around and find out.

![Screenshot (207)](https://user-images.githubusercontent.com/10295641/172077349-fdceac12-c82e-4094-b42a-4df5230792d0.png)
![Screenshot (203)](https://user-images.githubusercontent.com/10295641/172077386-1d77139a-3167-4064-9507-b04629604e9a.png)
![Screenshot (209)](https://user-images.githubusercontent.com/10295641/172077394-f8f0be8e-99b3-4bb6-83b1-ffe92b0c7830.png)
![Screenshot (210)](https://user-images.githubusercontent.com/10295641/172077398-dea5e972-03b8-4082-b54f-181fb0530437.png)

**Comment by csggene3** [comment]
Also noticed this area of Unconverted Data on CoinGecko. Very nifty. Indicates this comes from the WXDAI/GIV pair on Honeyswap..
![Screenshot (211)](https://user-images.githubusercontent.com/10295641/172077886-71cb8d87-82ee-45e1-be94-348754a7ac1a.png)

**Comment by mohammadranjbarz** [comment]
@csggene3   @MoeNick 
I dont know how coingecko works, but we get the ethPrice of our token from ETH/GIV pool and then with ETH USD price we can calculate the GIV usd price, and you can always check  GIV price in both gnosis and mainnet networks in any block/txHash with below API
https://givback.develop.giveth.io/api-docs/#/default/get_givPrice
