### ISSUE TITLE
Mobile / Responsiveness view

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#876]

**Comment by divine-comedian** [comment]
testing this out 

on tablet/mobile view shouldn't these  top two elements be swapped so it matches the order on laptop view? Or perhaps a better question is why is it a separate element? Wouldn't it make more sense to add the menu next to the bottom element and remove the top one altogether?

<img width="1440" alt="Screen Shot 2022-06-27 at 9 49 52 AM" src="https://user-images.githubusercontent.com/67759413/175971105-3115b1bf-d51d-4b76-afb4-09e627f11a22.png">

**Comment by divine-comedian** [comment]
on tablet view the top two elements are different widths than the bottom one, shouldn't they match widths?

![image](https://user-images.githubusercontent.com/67759413/175971654-ae5937ce-5442-4ded-be8f-a8af3daf3a0c.png)

**Comment by RamRamez** [comment]
> xt to the bottom element and r

@MoeNick @mosaeedi

**Comment by RamRamez** [comment]
> testing this out
> 
> on tablet/mobile view shouldn't these top two elements be swapped so it matches the order on laptop view? Or perhaps a better question is why is it a separate element? Wouldn't it make more sense to add the menu next to the bottom element and remove the top one altogether?
> 
> <img alt="Screen Shot 2022-06-27 at 9 49 52 AM" width="1440" src="https://user-images.githubusercontent.com/67759413/175971105-3115b1bf-d51d-4b76-afb4-09e627f11a22.png">

@MoeNick @mosaeedi

**Comment by RamRamez** [comment]
> on tablet view the top two elements are different widths than the bottom one, shouldn't they match widths?
> 
> ![image](https://user-images.githubusercontent.com/67759413/175971654-ae5937ce-5442-4ded-be8f-a8af3daf3a0c.png)

thanks @divine-comedian fixed in PR #1016
