### ISSUE TITLE
Switch network not working on RegenFarms

### ISSUE THREAD

**Issue by MohammadPCh** [Giveth/giveth-dapps-v2#882]
![Screenshot from 2022-06-07 10-15-36](https://user-images.githubusercontent.com/17097576/172304862-f942f406-f814-47d7-8703-1d904dbbcd49.png)

**Comment by divine-comedian** [comment]
testing on `staging.giveth.io`

while on another network besides kovan or gnosis chain I see the cult/eth farm blurred out with the switch network modal in front, I click switch network and it prompts me to switch to kovan in metamask, switch works successfully. 

my only regret is that if I am on the wrong network I will never see any regen farms on gnosis chain, nor will I ever be prompted to switch to gnosis chain with this modal. - related to issue #821 

calling this DONE
