### ISSUE TITLE
Projects will lose donations if they put an exchange address

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#890]
<img width="1166" alt="Screen Shot 2022-06-07 at 12 39 57 PM" src="https://user-images.githubusercontent.com/14945613/172447780-42521999-515d-4db7-a620-bc07cc847fd8.png">

https://giveth.io/project/expedition-grundeinkommen

https://blockscout.com/xdai/mainnet/tx/0x3432b18a7543aaf5bc47beb1083fee75da48b62eaee87ba7d68bd832f5898f38

**Comment by MoeNick** [comment]
1- Gnosis was removed from this project's recipient address. 
2- Just added a warning msg on creating / edit project form, not to use exchange addresses for Gnosis.

**Comment by MoeNick** [comment]
Test Scenario: Warning added no to used exchange addresses. 
Should test on new UX. both same address flow or different address flow.
