### ISSUE TITLE
Bug donating after second guessing the donation - tx went through, but it says it didn't!

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#891]
I tried to donate on production to a project and my donation went through but was not recorded on our UI. I did something weird though, here:
1. Went to donate 600 GIV to a project, hit "donate", got the tx popup, then decide I didn't want to donate, so clicked "reject"...I got this:

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/dce18476-0bea-4fd9-ae31-25f4f6870560)

- [x] this should tell the user that they rejected the tx, not that the tx has failed.

2. I clicked the "x", then got this screen again (but ofc it said 600 GIV)

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/0bda66c3-0f0b-4f45-b72f-bd6d4e107a81)

3. I decided I actually DID want to donate, then clicked "donate" again... got the tx in my metamask, confirmed...

but then I got again that the tx failed... although it didn't... the tx went through [here](https://blockscout.com/xdai/mainnet/tx/0x759f65cae43f41f67d0f79982f76c9ea5e34a248916690f6d74ced3512526dd6)

Also, the donation is not recorded on the project's page: https://giveth.io/project/support-carabela-guild

- [x] the donation should be recorded
- [x] it should not tell me the tx failed when it did not

This is what the console said:
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/32fd6e9b-3222-48ee-bc55-65b8f3ca5274)3

**Comment by MoeNick** [comment]
@laurenluz the required changes you need are implemented in staging and need to be tested. here is the issue:  #880

**Comment by divine-comedian** [comment]
I tested some of these features already in #880 
but testing again.. on `staging.giveth.io` on gnosis chain and ropsten

I click to donate to a project, confirm the amount then reject the metamask pop-up, the modal says the transaction was rejected, I go back to the confirm donation modal, click donate, another metamask tx pops up, I confirm. The donation goes through successfully and I'm taken to the successful donation page. no errors encountered.

moving this issue to DONE!
