### ISSUE TITLE
CULT / ETH regenFarm CULTstream seems wrong

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-dapps-v2#892]
@aminlatifi we decided to have the CULTstream run until the same end date as the GIVstream... not the full 5 years. It's showing over 5 years... it should be like 4 years 6 months... did we deploy the contracts with the longer stream? can we fix it?

Also, the % should start at 10%... remember we made that change on the GIVstream side so that it shows the % of liquid tokens.. will this say 10% when the rewards go live?

![image](https://user-images.githubusercontent.com/75490971/172495630-6c344cab-3015-454d-b027-4966bd7ebd0d.png)

**Comment by aminlatifi** [comment]
@laurenluz I changed the CULTstream duration. So it will end with GIVstream.
<img width="317" alt="image" src="https://user-images.githubusercontent.com/5684607/172835415-2cc11b18-8941-4957-a4bc-586c37293c4d.png">
Yes, 10% of the stream will be liquidated immediately when the stream starts.

**Comment by laurenluz** [comment]
you are a hero
