### ISSUE TITLE
Support saving last step that user filled

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/giveth-dapps-v2#893]

**Comment by mohammadranjbarz** [comment]
@MohammadPCh 
I would save `lastStep` that user has filled in project verification form, So if user fill `step1` then fill `step2` the last step of user should be `step2`, but if user has filled `step3` already and his `lastStep` is `step3` and want to fill `step2` again his last step would remain `step3 `
steps order is :
* personalInfo
* projectRegistry
* projectContacts
* managingFunds
* milestones
* termAndCondition
* submit

**Comment by MohammadPCh** [comment]
Thank you @mohammadranjbarz It looks great.

**Comment by mohammadranjbarz** [comment]
> Thank you @mohammadranjbarz It looks great.

@MohammadPCh  It's deployed now

**Comment by divine-comedian** [comment]
where can this issue be tested?

**Comment by MohammadPCh** [comment]
@divine-comedian You can test it here:
https://giv-verification.vercel.app/verification/[project-slug]
or just go to the:
https://giv-verification.vercel.app/
go you one of your projects page and click on the verification button.

**Comment by divine-comedian** [comment]
I couldn't test this issue because I can't get past the first step, email verification. Will come back to this one.

**Comment by divine-comedian** [comment]
testing again on `https://giv-verification.vercel.app/`

I am able to toggle back and forth from previous pages and my response is saved in the verification flow! 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67759413/178682743-a44feda4-6282-4f5e-a5bc-fbecaf7084e7.png">

moving to done!
