### ISSUE TITLE
Updates not showing pictures on Firefox

### ISSUE THREAD

**Issue by Mettodo** [Giveth/giveth-dapps-v2#897]
The pictures in our updates work fine on Brave but cannot be seen on Firefox: https://giveth.io/project/njombebeyond
Brave:
![image](https://user-images.githubusercontent.com/24914615/172604677-000574fd-8acd-4c65-9c39-e4b099d3d0c3.png)
Firefox: 
![image](https://user-images.githubusercontent.com/24914615/172604778-334aba77-fee4-476d-bcd6-f7680f1b9fc1.png)

**Comment by RamRamez** [comment]
@Mettodo It's ok for me. Sometimes it takes a few seconds for the picture to be loaded. Could you please test it again?

**Comment by Mettodo** [comment]
OK, good to hear. Thanks. Then I guess it is a problem of my Firefox settings.
