### ISSUE TITLE
Upgrading to Web3-react new version

### ISSUE THREAD

**Issue by MohammadPCh** [Giveth/giveth-dapps-v2#900]
We are using web3-react version 6 released about 2 years ago.
I think we need to investigate the new beta version of web3-react. because react and nextjs had many changes in these 2 years. and sometimes this old boy not working correctly.
https://www.npmjs.com/package/@web3-react/core?activeTab=versions
What do you think @MoeNick, Do we have any budget for it?

**Comment by MoeNick** [comment]
Ok cool. we have to dedicate some budget every sprint for technical debts.

**Comment by MohammadPCh** [comment]
I investigated on this and it seems we need to wait for its stable version.

**Comment by MohammadPCh** [comment]
I investigated on this and it seems we need to wait for its stable version.

**Comment by MoeNick** [comment]
@divine-comedian 
We can also have this  into the pipeline again.

**Comment by divine-comedian** [comment]
Yup, does this issue require thorough testing since we are changing a big part of the architecture, right?

**Comment by divine-comedian** [comment]
this issue can be closed now since we are going to switch to wagmi and viem, right?

**Comment by MoeNick** [comment]
Im not sure. @MohammadPCh
