### ISSUE TITLE
Front-end Test

### ISSUE THREAD

**Issue by MohammadPCh** [Giveth/giveth-dapps-v2#901]
We always read about writing tests for applications. and all of us agree that it a necessary for the back-end. but shall we have it for the front-end? what are its advantages? we need to think about it. maybe it help us to have an application with fewer bugs.
God knows!
What's your idea @MoeNick?

**Comment by MoeNick** [comment]
Yeah functional tests works but needs lots of bandwidth to get benefited from. Let's have QA specialist first, then we can complete it after

**Comment by mateodaza** [comment]
Let's share in this thread some ideas on which framework should we use!

@alireza-sharifpour did I hear in some call that you had some implementations before?

+ @MohammadPCh @RamRamez

**Comment by mateodaza** [comment]
In this [article from the nextjs docs](https://nextjs.org/docs/testing) they have some examples for cypress, playwright, jest and vitest

**Comment by alireza-sharifpour** [comment]
> 

Yes I had some implementations and read lots of documents before.
The PR for our project's configuration is here:
https://github.com/Giveth/giveth-dapps-v2/pull/1074
I'm going to share some resources in the next comment

**Comment by alireza-sharifpour** [comment]
I investigated on Big projects code bases and read some docs and watched some courses.
We can use Jest + React Testing Library for Unit testing and Mocking and ...
React Testing Library is a great tool and it provides lot's of React and DOM related utilities.
https://testing-library.com/docs/react-testing-library/intro/
https://chrome.google.com/webstore/detail/testing-playground/hejbmebodbijjdhflfknehhcgaklhano?hl=en
Best course i found for testing:
https://testingjavascript.com/

Kent C dodds has great articles about testing on his website.

Also for E2E tests we can use Cypress which I'm not used it before but i see that some repos like Uniswap are using it and it seems perfect.
https://www.cypress.io/
[Uniswap Repo](https://github.com/Uniswap/interface)
[Pancakeswap Repo
](https://github.com/pancakeswap/pancake-frontend)

**Comment by MohammadPCh** [comment]
Wow, thanks @alireza-sharifpour and @mateodaza 
It's great. I suggest that each of you undertakes a part of this research and demo it for the team( dev team + POs + testers)
what do you think?

**Comment by alireza-sharifpour** [comment]
> Wow, thanks @alireza-sharifpour and @mateodaza It's great. I suggest that each of you undertakes a part of this research and demo it for the team( dev team + POs + testers) what do you think?

I think it's a good idea 👍

**Comment by MoeNick** [comment]
@alireza-sharifpour @MohammadPCh would you please update the issue the latest plan? can we create another issue then after this one?

**Comment by alireza-sharifpour** [comment]
I think it doesn’t need an issue anymore, because it would be a part of our workflow, but before that, we all need to get on the same page.
I think this issue was mainly for Research and configuration of the tools, and it's done.
@MoeNick

**Comment by MohammadPCh** [comment]
@MoeNick writing test is not an easy task. we need all team members to be ready for writing and also, need to have the additional time budget for each job.
for example consider all team members know how to write tests because we don't have experience in the team, a task with 5 story points maybe takes 8 or 13 story points.

**Comment by MoeNick** [comment]
> @MoeNick writing test is not an easy task. we need all team members to be ready for writing and also, need to have the additional time budget for each job. for example consider all team members know how to write tests because we don't have experience in the team, a task with 5 story points maybe takes 8 or 13 story points.

Im with it! Let's make it happen.
I think we have to close this and create another for the test plan, guidelines, milestones, and monitoring of the test coverage. what do you think? @MohammadPCh @alireza-sharifpour

**Comment by MohammadPCh** [comment]
I'm totally agree with you
