### ISSUE TITLE
Verify social networks by oauth2

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/giveth-dapps-v2#902]

**Comment by mohammadranjbarz** [comment]
We have to verify these social network accounts
- [ ] Gmail
- [ ] Twitter
- [ ] Facebook
- [ ] Discord
- [ ] Youtube ( Not sure if it's possible)
- [ ] Instagram (Not sure if it's possible)

**Comment by mohammadranjbarz** [comment]
@alireza-sharifpour 
And please give me two routes from frontend to redirect to them
1. For when users verify their social profiles succcessfully
2. For when the oauth2 verification fails

**Comment by alireza-sharifpour** [comment]
> @alireza-sharifpour And please give me two routes from frontend to redirect to them
> 
> 1. For when users verify their social profiles succcessfully
> 2. For when the oauth2 verification fails

@mohammadranjbarz I think something like  [baseUrl]/verification/slug?[...(keys = values)]

**Comment by divine-comedian** [comment]
What should I do as a user to test this issue?

**Comment by MoeNick** [comment]
@jeevanplus007 I think you can relate the test scenario number in your sheet to this issue.

**Comment by mohammadranjbarz** [comment]
@MoeNick  
It's done now, you can test
@alireza-sharifpour

**Comment by alireza-sharifpour** [comment]
Thanks @mohammadranjbarz 
I tested it and implemented the frontend side, and it works perfectly 🤩.
Thank you.

**Comment by divine-comedian** [comment]
Is this issue done or does it require further testing?

**Comment by divine-comedian** [comment]
> It needs testing @divine-comedian pls take a look. especially when user abort the process.

Okay I'm still waiting to be told how I can test this issue...

**Comment by MoeNick** [comment]
@jeevanplus007 can you link it to the written test scenario? (The sheet you prepared I mean) we need it asap.
