### ISSUE TITLE
better behaviour for browsing multiple projects

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-dapps-v2#910]
While searching through projects I apply a filter or sort projects to look at ones I'm interested in, when I click on a project, view its details and go back to the projects page, it is reset without any of the filters I set, I have to then set my filters again and try to find where I was last in looking through all of the projects.

it would be cool if when I am on a project page and I hit the back button to go back to the projects page that:

- the same filters/sorting, if any, is applied as before
- I am taken back to the part of the page where the project I last clicked on was located.

**Comment by divine-comedian** [comment]
Coming back around on this issue - I think we need only one small design change to the project page and that would be a back button.
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/c8e11215-5375-4d0b-a0a4-080f6d6b4e0f)


this back button will take the user to the all projects page

 OR 

if the user came from a certain category - take them back to that category projects page (i.e. education / wellness / tech)

AND ALSO

apply any filters, sorts and search queries they might have applied when they return using the back button. The intention is that if a user wants to check out projects with a certain criteria they don't need to reset all of their search parameters every time they leave the single project page and return to the all projects page they began searching from.

**Comment by divine-comedian** [comment]
pending in #3289

**Comment by maryjaf** [comment]
It seem it should be better if this filter name is changed 
because I think it makes the user be confused 
I set rank sort but in url GIVpower is shown although  GIVpowr sort exists also and it's related to instant boosting

<img width="1439" alt="image" src="https://github.com/Giveth/giveth-dapps-v2/assets/111529185/6fd6282a-0800-44af-b117-99a7fe5e6b00">
@MohammadPCh

**Comment by MohammadPCh** [comment]
@maryjaf Thanks, The filter's name comes from the backend. and I totally agree with you. it's confusing for developers too, the rank option is GIVpower, and the GIVpower option is InstantBoosting.

**Comment by maryjaf** [comment]
> @maryjaf Thanks, The filter's name comes from the backend. and I totally agree with you. it's confusing for developers too, the rank option is GIVpower, and the GIVpower option is InstantBoosting.

@MoeNick @mohammadranjbarz

**Comment by divine-comedian** [comment]
@maryjaf - can we create a new issue since I think this needs to be solved in the back-end and probably needs input from @laurenluz

**Comment by mohammadranjbarz** [comment]
> @maryjaf Thanks, The filter's name comes from the backend. and I totally agree with you. it's confusing for developers too, the rank option is GIVpower, and the GIVpower option is InstantBoosting.

@MohammadPCh  Are you sure?
I guess they are not come from backend, for instance we don't have any filter named **Rank** in backend

These are our filter and sorting variables in backend

<img width="654" alt="Screen Shot 1402-08-08 at 10 55 03" src="https://github.com/Giveth/giveth-dapps-v2/assets/9850545/579dea68-3866-44a3-8ca0-39961bea16ba">

**Comment by divine-comedian** [comment]
@mohammadranjbarz 

You can see that Rank on the FE became 'GIVpower' in the BE and GIVpower in the FE is InstantBoosting in the BE

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/f62687e3-a39e-4124-b9c1-f47132cf98f9)

**Comment by MohammadPCh** [comment]
I believe it's crucial to finalize our decisions regarding queries before the release. Once we release this version, Google will begin crawling the pages, and each page with a different query will be identified as a new page. If we decide to alter some queries afterward, the previously indexed pages will become outdated. This could lead to a situation where Google may penalize us for having multiple outdated pages. Hence, it's prudent to settle on our query structure beforehand. @divine-comedian

**Comment by divine-comedian** [comment]
Can you explain this in a bit more detail? 

So you're saying since each search query will produce a new URL that saves the user's search parameters we will have many "pages" that are indexed by Google? 

Is this by the Google SE or by our Google Analytics integration?

What do the consequences of being penalized mean?

**Comment by MohammadPCh** [comment]
let me explain with example:
after the release, google will index a page like this:
https://staging.giveth.io/projects/all?sort=GIVPower
and after a while, we will decide to change the GIVpower to another thing, like test, so the new address will be:
https://staging.giveth.io/projects/all?sort=test
what's happened to our previous address?
Google says you should redirect users to the new address, but now we show an error page. So Google says oops, you provide a bad experience to your users, so maybe it's better to don't show you in the top search results (decrease our website score).
and it's not easy to handle this redirect. So it's better to decide about it now. and then release.

**Comment by divine-comedian** [comment]
I think it's fine because users won't be visiting our site directly from those "filter" urls

We apply the custom url while they are navigating - they don't visit it directly 

So in 99% of cases users won't visit a broken page since we are handling the application of correct urls from the FE based on the filters/sorting they apply on the UI

**Comment by divine-comedian** [comment]
I did some research and found there is a file we can defined called `robots.txt` which tells google to not index certain URLs connected to a website - I think this can help us with the filtering and prevent being penalized for bad urls

## Ref
https://support.google.com/webmasters/answer/7645831?hl=en

## How to 
https://developers.google.com/search/docs/crawling-indexing/robots/intro?sjid=17580995289940380458-NC


----

I don't think this will be a huge issue since we shouldn't change our filters very often but we will have an option now to mitigate it's negative effects in the event we do change them

**Comment by MohammadPCh** [comment]
@divine-comedian Thanks, But it's better to not use it too many times because we have to care bout many URLs on every change.

**Comment by divine-comedian** [comment]
> @divine-comedian Thanks, But it's better to not use it too many times because we have to care bout many URLs on every change.

At any rate I think it;s safe to proceed. I don't think we will change the filtering too often on production for it to be a huge issue, good to keep in mind though

**Comment by maryjaf** [comment]
I'v created this issue https://github.com/Giveth/giveth-dapps-v2/issues/3406 for that  
Could we move this issue to Done now?

**Comment by divine-comedian** [comment]
I think this enhancement is only partially finished...

We can call the first part done and I've created this issue #3417 to follow up the second half of this improvement feature

-----------
> 
> it would be cool if when I am on a project page and I hit the back button to go back to the projects page that:
> 
> * the same filters/sorting, if any, is applied as before
> * I am taken back to the part of the page where the project I last clicked on was located.
The second part is allowing the user to return to the section of the list of projects they were scrolling through...

for example if I scroll through 1/2 to the bottom of the page - select a project to view and then go back I should be returned to that same position I left off at - 1/2 to the bottom of the page, or wherver it was that the project I clicked on was located at in the list. 

This means that if a user is browsing amongst a large list of a projects everytime time they want to view a project in detail and go back to the main list they don't have to start at the top of a long list of projects they have already seen.

https://github.com/Giveth/giveth-dapps-v2/assets/67759413/776f916b-5f50-4552-b217-e8b83790604e
