### ISSUE TITLE
Already singed in but it says sign in

### ISSUE THREAD

**Issue by RamRamez** [Giveth/giveth-dapps-v2#912]
In onboarding page I'm already singed in but it says sign in:

![image](https://user-images.githubusercontent.com/73441857/173207234-e5de10a7-ba93-46dd-8864-1fb066f4b5b4.png)

**Comment by divine-comedian** [comment]
testing on `staging.giveth.io`
clean cache and cookies. 

testing with a fresh eth address that has no profile on giveth. I sign in with my wallet on the homepage and navigate to complete my profile, no modal shows up asking me to sign in again. tested on both ropsten and xdai.

seems to be resolved, moving to DONE.
