### ISSUE TITLE
Add project verification db join in list of prooject

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#923]

**Comment by mohammadranjbarz** [comment]
@MoeNick 
Can you attach the design page that was the reason of creating this issue?

**Comment by mohammadranjbarz** [comment]
As I talked with @MoeNick  and @RamRamez 
I should join the project verification forms and return it in below queries
- [ ] projectBySlug
- [ ] projectsByUserId

**PS** We should return it if the owner of project is requesting, otherwise the `verified` field is enough

**Comment by mohammadranjbarz** [comment]
@RamRamez  @MoeNick 
The PR merged

Now you can get project verification form in `projectBySlug` and `projectsByUserId` queries like below  https://github.com/Giveth/impact-graph/blob/staging/test/graphqlQueries.ts#L419-L515
