### ISSUE TITLE
Sent a donation to project cahuita-roots-regenerative-development-project but does not show on Donations list

### ISSUE THREAD

**Issue by rpiesveloces** [Giveth/giveth-dapps-v2#925]
I sent 96 GIV to [CAHUITA ROOTS Regenerative Development Project](https://giveth.io/project/cahuita-roots-regenerative-development-project), but it doesn't show on listed donations.

When I made the donation, the page gave me an error and a transaction ID. But the transaction record shows the transfer was successful.

Transaction:
https://blockscout.com/xdai/mainnet/tx/0x1254293d9ddbb40c4b09c6f9fc2b6bd95d321e8dbc6fc2899479c7f922ebe839

**Comment by jeevanplus007** [comment]
@mohammadranjbarz Kindly share your latest updates on this.

**Comment by mohammadranjbarz** [comment]
@rpiesveloces 
Sorry we had some problem in saving donations that time, I added your donation manually, I really appreciate your report

<img width="1538" alt="Screen Shot 1401-04-21 at 09 56 34" src="https://user-images.githubusercontent.com/9850545/178415271-e2b64635-ed73-4d73-b247-676f7913202b.png">
