### ISSUE TITLE
Text fixes on 'Let's Donate' modal

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/giveth-dapps-v2#939]
There are a few text things that should be fixed on this modal.

**Future of Giving** is always capitalized in all of our documentation and the application should reflect this also.
I have highlighted a few more things as well and rewrote the text below. 

![image](https://user-images.githubusercontent.com/74267818/174079488-c7b870e2-5eab-4492-ac84-c9caf03d7454.png)

**Should say:**

"Welcome to the Future of Giving!

Here are the things you can do now.

 - Take a look at awesome projects on Giveth.
 - Create a new project and receive donations.
 - Earn GIV by donating to projects."

The links are fine and can stay how they are.
Thank you!

**Comment by divine-comedian** [comment]
I can't remember how to make this modal pop-up I deleted my cache and cookies, and signed in with an empty profile..
