### ISSUE TITLE
Show User friendly Message when Server is Down

### ISSUE THREAD

**Issue by MohammadPCh** [Giveth/giveth-dapps-v2#948]
When the server is down, the SSR routes show a message like this:
![Screenshot from 2022-06-19 10-42-29](https://user-images.githubusercontent.com/17097576/174468300-db34823f-f49f-4074-9242-18b3273ed548.png)
it's better to handle it and show the appropriate error page.

**Comment by divine-comedian** [comment]
without crashing the server, how could we test this issue?

**Comment by mohammadranjbarz** [comment]
> without crashing the server, how could we test this issue?

If you want to , I can make backend down and you do your tests then I will bring that up again, please DM me when you want to test this

**Comment by MoeNick** [comment]
This happened last week. 
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/d65b3178-360b-47b3-9570-e399f7bee3d2)while we merged this to production without testing this issue.
