### ISSUE TITLE
Small punctuation corrections

### ISSUE THREAD

**Issue by danelsuga** [Giveth/giveth-dapps-v2#954]
Hi team! I've found a few little mistakes that need fixing. Thank you!
![blockchain technology](https://user-images.githubusercontent.com/81351744/174584269-a9e75f74-d869-447a-b6c1-234fdb6be431.png)
In the third bullet point, the period is accidentally in the wrong place. It should be after "technology".
![consume2](https://user-images.githubusercontent.com/81351744/174584393-1dc983d9-5ccc-4884-ae53-0eb656b8f900.png)
This has been pointed out before but not yet changed. We should change the word "consume" to something more Giveth-aligned such as "Learn". 
![period](https://user-images.githubusercontent.com/81351744/174584769-8b196ddc-59fc-4a04-bacc-b42e3d67bf51.png)
This one also has a little problem where there is a space before the period in the first bullet point.

Thank you!

**Comment by divine-comedian** [comment]
resolved in pending PR #1193

**Comment by oyealmond** [comment]
1) The period is already in place after *technology*.

<img width="1140" alt="Captura de Pantalla 2022-08-12 a la(s) 10 26 49" src="https://user-images.githubusercontent.com/110692280/184388123-e9b60181-cea5-4c62-8334-d48aa7823bc5.png">

2) The word was changed to Learn.
<img width="1293" alt="Captura de Pantalla 2022-08-12 a la(s) 10 30 10" src="https://user-images.githubusercontent.com/110692280/184388684-9a910d13-4dae-4d1e-b5ca-d330b65694e3.png">

3) The Space was removed, and now is correct. 

<img width="703" alt="Captura de Pantalla 2022-08-12 a la(s) 10 33 06" src="https://user-images.githubusercontent.com/110692280/184389231-213517e8-b886-4240-89f8-dffa49d3463c.png">
