### ISSUE TITLE
Replace reporting issue to typeform in support page

### ISSUE THREAD

**Issue by MoeNick** [Giveth/giveth-dapps-v2#963]
As a user, I need to be able to report issues in this page, https://giveth.io/support to the type form bug form: https://giveth.typeform.com/issue-bug so I can report issues even if I don't have a Github account.

**Comment by MoeNick** [comment]
@RamRamez mentioned we are using this link in also drop-down menu and single project view, I asked him to change them as well , FYI @WhyldWanderer

**Comment by oyealmond** [comment]
I tested on https://staging.giveth.io/support 
And the specified Typeform for issues shows correctly in the **Report an Issue** button. 

1) 
<img width="1199" alt="Captura de Pantalla 2022-08-12 a la(s) 12 06 10" src="https://user-images.githubusercontent.com/110692280/184409013-156db240-479a-4cda-ba74-a7206d9fe63a.png">

2) 
<img width="1203" alt="Captura de Pantalla 2022-08-12 a la(s) 12 06 18" src="https://user-images.githubusercontent.com/110692280/184409056-a33075a3-0d2d-4db1-acd2-bad7b8cbdc3e.png">

3) Made a test to check Typeform regarding issues is working: 
<img width="1213" alt="Captura de Pantalla 2022-08-12 a la(s) 12 06 37" src="https://user-images.githubusercontent.com/110692280/184409133-c07f9390-0a6b-4218-90e6-5063818ff02e.png">
