### ISSUE TITLE
xDai is at the bottom of the token list for donations.

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-dapps-v2#966]
<img width="613" alt="Screen Shot 2022-06-21 at 6 48 44 AM" src="https://user-images.githubusercontent.com/14945613/174815499-cd69692f-c220-439b-bdb4-7223126fb10a.png">

Can we move this to the top, below Giveth? It is the second most popular donation token behind Giveth

Also why is it Xdai... it looks bad.. 

Can it be xDai or xDAI? it should be consistent in the token list.

**Comment by mateodaza** [comment]
@CarlosQ96 @mohammadranjbarz can you guys change the name on the database for xDai?

All rest is fixed on this [PR](https://github.com/Giveth/giveth-dapps-v2/pull/1013)

**Comment by MoeNick** [comment]
Env: staging
Test Scenario: change the sorting value of each token on different networks, and it should show sorting on the donation page as preferred.

**Comment by MoeNick** [comment]
Tested, it's on production now.
