### ISSUE TITLE
Create a Project - Entering Only Title Field and Clicking on Publish throws an Error

### ISSUE THREAD

**Issue by jeevanplus007** [Giveth/giveth-dapps-v2#969]
**Issue :** When Create a Project - Entering Only Title Field and Clicking on Publish throws an Error

**Steps to Repro :** 
1.	Click on Create a Project 
2.	Enter the Title and do not fill any other details
3.	Click on Publish

**Results :**  Throws Error when clicked on Publish

**Snapshot for Reference :**
![image](https://user-images.githubusercontent.com/107279959/174901012-1cc36103-0ebf-43c5-b859-eabbe45f0ed8.png)

**Comment by RamRamez** [comment]
I've fixed this with issue No. #1006

**Comment by jeevanplus007** [comment]
**Test Status : PASS in STAGING

Test URL :** https://staging.giveth.io/create

**Test Results :** Valid Error Message are shown when Only Title is added and hit Publish button

**Snapshot :**
![image.png](https://images.zenhubusercontent.com/62a3cf4962612d632dd3b42a/27953023-ca6d-4ec2-b27c-7e180b7b62e2)

**Comment by jeevanplus007** [comment]
We can move this to DONE as QA is Successful in STAGING.
