### ISSUE TITLE
Create a Project - No Relevant Information in the Hyperlink - "How to write fundraising Project..."

### ISSUE THREAD

**Issue by jeevanplus007** [Giveth/giveth-dapps-v2#971]
**Issue :** When Creating a Project - No Relevant Information in the Hyperlink - "How to write fundraising Project..."

**Steps to Repro :**

1.	Create a Project
2.	Click on the Hyperlink – “how to write a great project description”
3.	Click on the Hyperlink in the bottom – “How to write fundraising project……………………….”

**Results :** Link is opening but not showing any relevant information. 

**Snapshot for Reference :**

![image](https://user-images.githubusercontent.com/107279959/174902664-39f25742-e790-40f8-b81a-fd863a057a5c.png)

**Comment by melodysongq** [comment]
We have a check-list resource as well as simple pointers to create a basic description with a good case for support.  Please assign to me (I can't assign myself) and I will come back with a draft.

**Comment by jeevanplus007** [comment]
@RamRamez Please share your updates.

**Comment by RamRamez** [comment]
@WhyldWanderer @divine-comedian could you send me the valid link for this?

**Comment by melodysongq** [comment]
Here is a draft of the Fundraising tips we can share.  Please make suggestions and edits as well before finalizing and use: https://docs.google.com/document/d/1nqrhxv_-WpRM2lQBaAOiTBIUFWEszPJmVdOLZ08PBb8/edit#heading=h.cvdrjfjmr1cy

**Comment by divine-comedian** [comment]
> Here is a draft of the Fundraising tips we can share. Please make suggestions and edits as well before finalizing and use: https://docs.google.com/document/d/1nqrhxv_-WpRM2lQBaAOiTBIUFWEszPJmVdOLZ08PBb8/edit#heading=h.cvdrjfjmr1cy

where will this be hosted? as in where will this link point to? We can upload your doc to the documentation and link it from there, has anyone in connect already reviewed it?

**Comment by divine-comedian** [comment]
> > where will this be hosted? as in where will this link point to? We can upload your doc to the documentation and link it from there, has anyone in connect already reviewed it?
> 
> The document has been reviewed and edited by Claire and myself. I am unsure where we would host it. Ideally on the website for a location for projects to find resources. Guidance and suggestions on where and how would be good as we were focusing on completing the content itself. Thanks.

I don't think anything like that exists on the dapp, probably the docs will be the best place.

**Comment by MoeNick** [comment]
If it's going to be like just user guide, I also suggest Docs, if you gonna change it by specific events or campaign, we have to use kind of landing management tool. 
For now lest do it on Docs, @divine-comedian can you take this one and send us the links to be addressed in the dapp?

**Comment by divine-comedian** [comment]
> If it's going to be like just user guide, I also suggest Docs, if you gonna change it by specific events or campaign, we have to use kind of landing management tool. For now lest do it on Docs, @divine-comedian can you take this one and send us the links to be addressed in the dapp?

we'll wait for QA to be finished, if we go this route can you ping me @melodysongq when this is ready for upload?

Also gave it a quick review, this is a great resource! Nice work!

**Comment by melodysongq** [comment]
> we'll wait for QA to be finished, if we go this route can you ping me @melodysongq when this is ready for upload?

For sure.  Also thanks to @clara-zi who started the original draft.  We will take a final look and it will be ready as a first step.

**Comment by melodysongq** [comment]
@divine-comedian this document is ready to be uploaded.  We can close the issue after that.

**Comment by melodysongq** [comment]
> > @divine-comedian this document is ready to be uploaded. We can close the issue after that.
> 
> I just had a look, there's a lot of unmerged content and unresolved comments, are you sure this is ready?

I can't close those as I think @clara-zi owns the document, is that the reason?   @clara-zi I wonder if you can take another look and close some editing.  Thanks!!

**Comment by clara-zi** [comment]
Thanks to all for taking the time to read and edit. All edits now resolved.

**Comment by melodysongq** [comment]
> UK English spelling. Do we have any comments on that? Should it be in US English to conform to other docs in Docs?
> (Breaks my heart to ask the question!!) @melodysongq @divine-comedian @WhyldWanderer

Once I am in Europe my correction is automatically UK instead of Canadian.  I think as long as it's consistent, we don't need to be American centric or anything.

**Comment by RamRamez** [comment]
> voilà! https://docs.giveth.io/whatisgiveth/fundraisingGuide @RamRamez

Done in PR #1164

**Comment by divine-comedian** [comment]
> > voilà! https://docs.giveth.io/whatisgiveth/fundraisingGuide @RamRamez
> 
> Done in PR #1164

okay let us know when it is merged and I will test again

**Comment by MoeNick** [comment]
@jeevanplus007 this one after the journey to the comms team and getting back, it's ready to test again.

**Comment by divine-comedian** [comment]
> UK English spelling. Do we have any comments on that? Should it be in US English to conform to other docs in Docs? (Breaks my heart to ask the question!!) @melodysongq @divine-comedian @WhyldWanderer

Canadian spelling, forever and always.. :)

**Comment by MoeNick** [comment]
From a product point of view, let's have the copywriting of Giveth the same in all pages, from docs to Dapp and social medias, newsletter etc.

**Comment by divine-comedian** [comment]
testing on `staging.giveth.io`

the link is now in and links succesfully to the fundraising guide!
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67759413/180003169-5940b318-f1fc-408c-987e-298fed20d9f5.png">

I think we can call this DONE!
