### ISSUE TITLE
Create a Project - Multiple Warning Messages for same issue while selecting more than 5 Categories

### ISSUE THREAD

**Issue by jeevanplus007** [Giveth/giveth-dapps-v2#972]
**Issue :** When Creating a Project - Multiple Warning Messages are displayed for same issue while selecting more than 5 Categories. 

**Steps to Repro :**

1.	Create a Project
2.	Go to Please Select a Category
3.	Click More than 5 Categories and continue to select more Categories

**Results :** It should not keep displaying more error messages instead should repeat showing/popping up only the existing Error. 

**Snapshot for Reference :**

![image](https://user-images.githubusercontent.com/107279959/174903030-ecaaf8e1-7b52-47a4-8f23-14f00d4d037f.png)

**Comment by RamRamez** [comment]
I've fixed this on verification develop branch. When verification is merged, it should be ok.

For testers: it can be tested via [this link](https://giveth-dapps-v2-git-verification-develop-branch-givethio.vercel.app/create)
