### ISSUE TITLE
Create a Project - There is a flickering issue while selecting a New location and it always selects Barcelona for first time

### ISSUE THREAD

**Issue by jeevanplus007** [Giveth/giveth-dapps-v2#973]
**Issue :** When Creating a Project - There is a flickering issue while selecting a New location and it always selects Barcelona for first time

**Steps to Repro :**

1.	Create a Project
2.	Go to Where will your Project……… section
3.	Type any Location like Dubai or Africa or India and click on the First Link in the Drop down list

**Results :** By Default, for the First time, it will always go to Barcelona Location. Only the Second time, it goes to the Specified Location which user has chosen. There is some flickering happening there while selecting. 

**Snapshot for Reference :**

![image](https://user-images.githubusercontent.com/107279959/174903489-344da234-42d7-4974-b4ea-393ab0c4d891.png)

**Comment by jeevanplus007** [comment]
@RamRamez There are two fixes done as part of this Ticket : 
1. Location Field Flickering issue
2. Global Impact Checkbox Flickering issue

**Comment by RamRamez** [comment]
> @RamRamez There are two fixes done as part of this Ticket :
> 
> 1. Location Field Flickering issue
> 2. Global Impact Checkbox Flickering issue

Thanks @jeevanplus007 
Also the problem with selecting everything twice is resolved in this PR.
