### ISSUE TITLE
Posting an Update in Project - Update text area should have an expand limit

### ISSUE THREAD

**Issue by jeevanplus007** [Giveth/giveth-dapps-v2#977]
**Issue :** When Updating a Project - Update text area should have a expand limit

**Steps to Repro :**

1. Create a Project or Go to My Project - Choose the any Created Project
2. Click on View Project and Select Update tab 
3. Type any large content as shown in snapshot and check the behaviour 

**Results :** Expand limit should be set for both Update Text area and Edit already Posted Comment area. 

**Snapshot for Reference :**

![image](https://user-images.githubusercontent.com/107279959/174913909-dabe5c0b-c663-473b-a989-26702b0e0a96.png)

**Comment by jeevanplus007** [comment]
Attaching one more Snapshot for Reference. 
![image](https://user-images.githubusercontent.com/107279959/176399080-1495dbc6-0a23-48eb-82eb-95b4937b757e.png)

**Comment by MohammadPCh** [comment]
Moved to Backlog as it is NOT VERIFIED by QA in STAGING

**Comment by jeevanplus007** [comment]
**Test Status :** PASS in STAGING

**Test URL :** https://staging.giveth.io/create

**Test Results :** Update text area is set with a expand limit as expected. 

**Snapshot :**
![image.png](https://images.zenhubusercontent.com/62a3cf4962612d632dd3b42a/1f033032-54c0-43f0-b18e-77f644d7b5d6)
