### ISSUE TITLE
Show popup when subgraph is out of sync

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/giveth-dapps-v2#999]
Subgraph sometimes offers poor service and its state is out of sync! 
We must compare the subgraph's latest block number (it's available) with the network's value. If the gas is much (equal or more than 2) show a popup to the user.
The text can be
"the Subgraph on Gnosis Chain is experiencing issues, and things will be slow to update"

**Comment by MohammadPCh** [comment]
I suggest having a status item on our menu. if everything is ok we can show a green dot with the "sync" word beside that and if the network has issue show a red dot and "unsync".

**Comment by jeevanplus007** [comment]
@mosaeedi Please have a look
